### ISSUE TITLE
iHeartRadio

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#100]
I can play song from my device  , i.e when I say "Alexa get soft rock from iHeartRadio" it works fine.

But when I try to play music from alexa.amazon.com , it says your device is offline.

What am I missing , please suggest.

**Comment by shikha-bansal** [comment]
I can see my device online now , I did not change anything on the device side. Not sure what made it go online this time

**Comment by shikha-bansal** [comment]
I  have the same  issue again , my device is working fine. But from the app ( alexa.amazon.com) it says device is offline.

Any suggestions please ?

**Comment by kencecka** [comment]
Hi @shikha-bansal,

I ran a couple of quick tests here, and when I start the SampleApp and it connects, the status of the device in the Settings panel change immediately to online, and when I terminate the SampleApp, it changes to offline.

Can you try enabling logging in the sample application (run with the DEBUG9) parameter and watch to see if you are experiencing disconnects in the log?

Ken

**Comment by shikha-bansal** [comment]
works for me too.
Thanks for your help.
