### ISSUE TITLE
No sound with a bluetooth speaker

### ISSUE THREAD

**Issue by ciprian288** [alexa/avs-device-sdk#1000]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
<no sound with bluetooth speaker>

## Provide the steps to reproduce the issue, if applicable:
<- modified ~/.asoundrc
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
} 
pcm.mic {
  type plug slave { pcm "hw:1,0" }
}
pcm.speaker {
  type plug 
  slave.pcm { 
    type bluealsa device "XXXXXXXXXXXXX"  
    profile "a2dp" 
  } 
}
- Edited the MediaPlayer.cpp with line:
m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");>

### What version of the AVS Device SDK are you using?
      <Version 1.9.0>

### Tell us what hardware you're using:
- [ x] Raspberry Pi

### Tell us about your OS (Type & version):
- [x ] Raspbian Stretch

**Comment by mavamazon** [comment]
Hi!
Could you please use this [troubleshooting guide](https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide)? it covers problems like that as well. In general AVS SDK just passes audio stream to the sink (ALSA in your case) and the rest is the matter of configuration.

Please let me know if guide helps.
