### ISSUE TITLE
Communication between AVS APP and companion APP

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#1001]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
the "AVS Security Requirements-v1_1.pdf" file provided by amazon required: Your device SHALL use TLS 1.2 or greater for all communications outside of initial setup.
Does the AVS APP and companion APP communication must use TLS?
If yes, the below file is my server sample app, but i  am not sure if it is use the TLS communication, can you help check it? 
Thanks!
[server.txt](https://github.com/alexa/avs-device-sdk/files/2449665/server.txt)

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!
Sorry, we are not able to provide support for user code, but it looks to me that you are going into the right direction. You may take a look [here](https://wiki.openssl.org/index.php/Simple_TLS_Server) as well if you didn't do that yet.
