### ISSUE TITLE
Do not see startsample.sh after build

### ISSUE THREAD

**Issue by ruradium** [alexa/avs-device-sdk#1003]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After finishing bash ./setup.sh config.txt
I did not see startsample.sh in the directory neither running bash startsample.sh returns 
"bash: startsample.sh: No such file or directory"

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ x ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ X ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: Android

**Comment by visayamv** [comment]
@ruradium , which guide are you following for the steps? What steps have your performed?

**Comment by onceupon** [comment]
i am following the wiki guide for raspberry pi and cannot fine the startsample.sh after running setup.sh
