### ISSUE TITLE
rpath settng how to when build AVS SDK SampleAPP for cross platform

### ISSUE THREAD

**Issue by DiazSo** [alexa/avs-device-sdk#1004]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

when I run SampleApp with "strace", I see it load share libraries from the path that is defined on compile host PC, the path is not exist on my target platform. Even it will try to search the path /lib that I install all libraries on my target platform finally. Is there any method to set library path while I compile SampleAPP with cross compile tool?  
## What is the expected behavior?

When I run SampleAPP, it will load share library from the path /lib, not from the path that is on my compile host PC. It will reduce the time duration when SampleAPP is started
## What behavior are you observing?

When I run SampleAPP with "strace SampleApp /var/alexa/AlexaClientSDKConfig.json DEBUG9", then I can see a lot of try to load library from my compile host PC, and then it will get "no such file or directory", then it will try other path, ad finally, it will try to use "/lib". It will take long time to load all share library.
## Provide the steps to reproduce the issue, if applicable:

build strace, and run SampleAPP with the command "strace SampleApp /var/alexa/AlexaClientSDKConfig.json DEBUG9"
### What version of the AVS Device SDK are you using?
      <x.y.z>
<1.9.0>
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ X] Other - tell us more: my embedded platform

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
You can explore the following CMAKE options:
CMAKE_SHARED_LIBRARY_PREFIX
CMAKE_LIBRARY_OUTPUT_DIRECTORY
