### ISSUE TITLE
AVS secure communication

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#1006]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

the 1.3 section in [Security Best Practices](https://developer.amazon.com/docs/alexa-voice-service/security-best-practices.html) document required the all communications have to use the TLS1.2 or greater, so i searched the AVS SDK code and found the below code in AVSCommon/Utils/src/LibcurlUtils/LibcurlUtils.cpp file:

```
bool prepareForTLS(CURL* handle) {
    if (!handle) {
        ACSDK_ERROR(LX("prepareForTLSFailed").d("reason", "nullHandle"));
        return false;
    }
    if (!(SETOPT(handle, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2) &&
          SETOPT(handle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2_0) &&
          SETOPT(handle, CURLOPT_USE_SSL, CURLUSESSL_ALL) && SETOPT(handle, CURLOPT_SSL_VERIFYPEER, 1L) &&
          SETOPT(handle, CURLOPT_SSL_VERIFYHOST, 2L))) {
        return false;
    }

    auto config = configuration::ConfigurationNode::getRoot()[LIBCURLUTILS_CONFIG_KEY];

    std::string caPath;
    if (config.getString(CAPATH_CONFIG_KEY, &caPath) &&
        !setopt(handle, CURLOPT_CAPATH, caPath.c_str(), "CURLOPT_CAPATH", caPath.c_str())) {
        return false;
    }

// Only allow disabling the verification of hosts and peers in debug configurations.
#ifdef DEBUG
    bool verifyHostsAndPeers = true;
    if (config.getBool(VERIFY_HOSTS_AND_PEERS_CONFIG_KEY, &verifyHostsAndPeers) && !verifyHostsAndPeers) {
        if (!(SETOPT(handle, CURLOPT_SSL_VERIFYPEER, 0L) && SETOPT(handle, CURLOPT_SSL_VERIFYHOST, 0L))) {
            return false;
        }
        ACSDK_WARN(LX("verificationOfHostsAndPeersDisabled"));
    }
#endif

    return true;
}
```
Does the all communications in the AVS SDK used TLS1.2 or greater?
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by celinval** [comment]
Hi @BobXLiu, the SDK always use TLS1.2 or greater to communicate with AVS.

**Comment by BobXLiu** [comment]
Hi @celinval ,
Thanks for you reply!
