### ISSUE TITLE
Unrecoverable authorization error

### ISSUE THREAD

**Issue by ANUSUYA-1996** [alexa/avs-device-sdk#1007]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 I am developing an alexa sample application for ubuntu linux.at the time building i received an error called unrecoverable authorization error and unrecoverable capabilities API error

## What is the expected behavior?
to receive an authorization  #code

## Provide the steps to reproduce the issue, if applicable:
``
## Tell us about your environment:
ubuntu linux
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- lenovo 320p
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
``

**Comment by celinval** [comment]
Hi @ANUSUYA-1996, can you please run the sample application with DEBUG9 and paste the logs for us? Thanks
