### ISSUE TITLE
Issue starting sample application

### ISSUE THREAD

**Issue by deeneshchowdhary** [alexa/avs-device-sdk#101]
Can someone please help me with starting the sample app?
when i run the following command, I get error. My config.json file is inside integration folder.
TZ=UTC ./SampleApp /Integration/ $LOCAL_BUILD/models

Failed to read config file!
Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by sanjayrd** [comment]
@deeneshchowdhary,

Please pass the path to the config file as the first argument, not the folder enclosing the config file. For example, your command would be `TZ=UTC ./SampleApp /Integration/AlexaClientSDKConfig.json $LOCAL_BUILD/models`

**Comment by deeneshchowdhary** [comment]
Thank you Sanjay! I was able to run the application but got another issue (https://github.com/alexa/avs-device-sdk/issues/105)
