### ISSUE TITLE
SSL CONNECT ERROR

### ISSUE THREAD

**Issue by ANDROIDTODO** [alexa/avs-device-sdk#1010]
Hi AVS Team,

I encountered a SSL problems causing me to be unable to connect to AVS .
The curl version is 7.53.1 and tht nghttp2 version is 1.24.0.

log is below:
[ssl.log](https://github.com/alexa/avs-device-sdk/files/2475182/ssl.log)

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @ANDROIDTODO , from your log:

`2018-10-13 03:59:07.131 [ 12] 9 HttpPut:httpPutData:Information(24 bytes)=ALPN\, offering http/1.1`

It seems that it is using HTTP/1.1 instead of 2.0. Can you check again that your build is linking to the correct curl library with nghttp2 with it?
