### ISSUE TITLE
[PlaybackController] playbackThumbsDown is the same behaviour to playbackNext

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#1011]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I play Amazon music in Alexa,  then I inputed '-'  through console, Alexa played next song.
## What is the expected behavior?

Alexa should continue to play , not play next song.
## What behavior are you observing?

When I inputed '-' through console , Alexa play next song.
## Provide the steps to reproduce the issue, if applicable:

Play music, if ThumbsDown is supported , input '-' through console
### What version of the AVS Device SDK are you using?
      <x.y.z> 1.9.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:  Embeded system

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @DonghuaZheng , this is an expected behavior. The music will be rated and the next music will be played.

**Comment by DonghuaZheng** [comment]
@visayamv  thanks, i got it.
