### ISSUE TITLE
Functional self-test for Italy language

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1012]
Hi AVS team,

Hi AVS team,

There are issues for functional self-tests under Italy language. (SDK 1.9.0)
Could you help to advice if these are known server site issue ?

[Section 2: User Interface]
1. Audible is not supported. Blocked all related tests.
2. case#215 Kindle book - Play :  Play command "Riproduci" doesn't work
3. case#220 Kindle book - Skip : [IT] Skip command "Salta" doesn't work
4. case#232 Named Timers : [IT] unable to set a named timer
5. case#243 Sports Update : [IT] unable to get sports update 
6. Notifications : No Quate Maker support under Italy.
7. case#255 Shopping : [IT] unable to create an order.
8. case#260 Music - Verify unsupported MSP on device : incorrect error TTS for unsupported MSP SoundClound

**Comment by visayamv** [comment]
Hi @zeusshuang , Italian is currently not supported by SDK.

**Comment by visayamv** [comment]
Hi @zeusshuang , Ill be closing this issue. Please reopen if you have more questions regarding this.

**Comment by zeusshuang** [comment]
Hi @visayamv ,

In functional test Italy language, the "case#220 Kindle book - Skip : [IT] Skip command "Salta" doesn't work" is still not working.
