### ISSUE TITLE
Question about the WWE thread

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1013]
Hi AVS team,

SDK 1.8.3 / 1.9.0 , ARM based embedded linux.

I have a question about a thread for WWE , keyword detection.
There is a command "c" to switch locale and language, but we still need to have different WWE for the locale settings, is there any way to re-load different WWE in run-time without restart full SampleAPP ?

Thanks,

**Comment by zeusshuang** [comment]
Hi @visayamv ,

Same WWE.
Just use the different model file for different language, eg. change en-US to jp-JP, same WWE but different model files.

**Comment by visayamv** [comment]
Hi @zeusshuang , unfortunately this is not possible at the current SDK as this involves shutting down and recreating the KeywordDetectorProvider interface which has a hardcoded filename for the model path.

**Comment by dhpp** [comment]
Thanks @zeusshuang for this question, and the suggestion.  We have created an internal ticket to investigate adding this functionality to a future release of the SDK.  I'll close this ticket out.
