### ISSUE TITLE
List of required gstreamer plugins

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1016]
Hi,
I found a full install of gstreamer plugins take too much flash space. So we want to trim the plugins that alexa client does not use, and also remove the dependencies of the useless plugins.  I have tried doing this optimization. But the problem is after the optimization, it can play this but failed to play that, which takes too much time for me to do a clean trim. 

I'm not sure if AVS SDK team have a list of gstreamer plugins that MUST keep. That will help a lot if you can provide that. 

Thanks

**Comment by visayamv** [comment]
Hi @subjectxbj , you can find the required gstreamer plugins here: https://github.com/alexa/avs-device-sdk/wiki/Dependencies under "MediaPlayer reference implementation dependencies"

**Comment by subjectxbj** [comment]
Hi @visayamv ,
I know that document. The problem is after a full installation of gstreamer plugins. There are about 190 plugin files. But actually I did some clean up and removed part of the plugin files, and only keep about 13 plugin files:
```
[alexa] / # ls /usr/lib/gstreamer-1.0/
libgstalsa.so               libgstlibav.so
libgstapp.so                libgstmpegtsdemux.so
libgstaudioconvert.so       libgstplayback.so
libgstaudioparsers.so       libgsttypefindfunctions.so
libgstaudioresample.so      libgstvolume.so
libgstcoreelements.so       libgstwavparse.so
libgstid3demux.so
[alexa] / #

```
With these 13 plugins I tested Amazon Music, iHeart Radio, Audible, Kindle Book. And it can play music or read book without problem. I did not test other MSPs. So my question is if I only keep these 13 plugins, is it enough to support all alexa services?

If I only keep these 13 plugins and their dependencies, I can save about 40M flash space. You know flash space is quite cost sensitive on an embeded system. 

Thanks

**Comment by visayamv** [comment]
Hi @subjectxbj , I'm sorry but I think this is more of a question for Gstreamer. Although I can probably suggest to check the dependencies of the gstreamer libraries used by SampleApp to see exactly what shared library files it's using.

you can do this by doing ldd to the SampleApp executable, e.g.

ldd ./SampleApp

Find the gstreamer related shared libraries and recursively do ldd on it.


OR you can just do:

sudo apt-get install pax-utils
lddtree ./SampleApp

**Comment by subjectxbj** [comment]
Thanks.

**Comment by scotthea-amazon** [comment]
Hi @subjectxbj,

It looks like this issue is resolved, so I am closing it.  If I have closed it in error, please feel free to re-open it!

Thank you,
-SWH
