### ISSUE TITLE
UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       # #       Entering limited interaction mode.         

### ISSUE THREAD

**Issue by sansari1959** [alexa/avs-device-sdk#1017]
##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
#       Entering limited interaction mode.                       #
##################################################################

+----------------------------------------------------------------------------+
|                          In Limited Mode:                                  |
+----------------------------------------------------------------------------+
| Status : Unrecoverable authorization failure.                              |
+----------------------------------------------------------------------------+
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

2018-10-19 13:15:04.624 [  2] 5 CBLAuthDelegate:handleStopping
2018-10-19 13:15:04.624 [  f] E CapabilitiesDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
2018-10-19 13:15:04.624 [  f] E CapabilitiesDelegate:publishCapabilitiesFailed:reason=getAuthTokenFailed
2018-10-19 13:15:04.624 [  f] 5 CapabilitiesDelegate:setCapabilitiesState:newCapabilitiesState=FATAL_ERROR
2018-10-19 13:15:04.624 [  f] 9 CapabilitiesDelegate:callingOnCapabilitiesStateChange:state=FATAL_ERROR,error=FORBIDDEN
2018-10-19 13:15:04.624 [  f] E CapabilitiesDelegate:capabilitiesPublishFailed:reason=unableToPublishCapabilities
###############################################################
#       UNRECOVERABLE CAPABILITIES API ERROR: FORBIDDEN       #
#       Entering limited interaction mode.                    #
###############################################################

+----------------------------------------------------------------------------+
|                          In Limited Mode:                                  |
+----------------------------------------------------------------------------+
| Status : Unrecoverable Capabilities API call failure.                      |
+----------------------------------------------------------------------------+
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

## Briefly summarize your issue:

Not responding. Not sure how to authenticate CBL

## What is the expected behavior?

ALEXA IDLE

## What behavior are you observing?

Limited Mode

## Provide the steps to reproduce the issue, if applicable:

sudo bash startsample.sh

### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK 1.9.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Poncherelly** [comment]
I'm having the exact same error/response ... its showing that I've successfully registered "Success!
Your registration is now complete." however it's not seeming to work.  Now it's just scrolling "2018-10-19 14:11:12.470 [  3] 5 InternetConnectionMonitor:testConnection
2018-10-19 14:11:12.725 [  3] 0 InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-10-19 14:11:12.725 [  3] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true
2018-10-19 14:11:12.725 [  3] 9 LibCurlHttpContentFetcher:~LibCurlHttpContentFetcher
2018-10-19 14:11:39.775 [ 10] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut"

**Comment by visayamv** [comment]
Hi @sansari1959 ,

 Make sure the value of clientId in your AlexaClientSDKConfig.json file is the clientId found under the Other devices and platforms tab on developer.amazon.com, not the one found under the Web tab

After that remove the CBL database file you are using and rerun the SampleApp. Let me know if it works for you

**Comment by henriz** [comment]
Not that the above mentioned clientID is NOT the clientID you get on top of the device page on amazon. You HAVE to go to the other devices tab, and generate an ID there.

**Comment by sansari1959** [comment]
Thanks to all. Indeed, I recognized my mistake. It works perfectly now.

**Comment by hotsauce1861** [comment]
> Thanks to all. Indeed, I recognized my mistake. It works perfectly now.
Hi
I met the same problem, could you please tell me how to solve it.
tks
