### ISSUE TITLE
cut responses from Alexa

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#102]
Sometimes are response from Alexa is not complete.
For example " Alexa whats up" sometimes gives me a complete answer , sometimes it is cut short in between.

**Comment by deeneshchowdhary** [comment]
hey,
since your app is already started. can you please help me how with command to start the sample application?
this command is not working for some reason.

TZ=UTC ./SampleApp /Integration/ $LOCAL_BUILD/models

**Comment by shikha-bansal** [comment]
i just say ./SampleApp AlexaClientSDKConfig.json 123 DEBUG , and it works fine

**Comment by deeneshchowdhary** [comment]
it does not work. what is 123 DEBUG for ? Do I need to include something else too?

**Comment by sanjayrd** [comment]
@shikha-bansal,

Do you have any logs you can provide us if this is still happening? We haven't experienced the issue you are describing.

Thanks,
Sanjay

**Comment by kencecka** [comment]
Hi @shikha-bansal,

I'm going to close this issue for now.  Please feel free to re-open if you are still having problems and would like more assistance.  If you do, please try running with DEBUG9 logging enabled, and post the logs here for review.

Ken
