### ISSUE TITLE
Alexa keeps listening while talking, triggering itself

### ISSUE THREAD

**Issue by henriz** [alexa/avs-device-sdk#1020]
## summary

I'm using a Raspberry Pi Zero W, with a Respeaker 2 mic HAT.

In order to get Alexa working, I use the KITT.ai wakewordengine.

This works, however while finetuning pulseaudio and portaudio I still get a lot of false positives on the wakeword-detection. This is not the issue this ticket is about.

Due to this false issues, I have noticed that Alexa keeps listening while talking, and, if it recognizes the wakeword again, it stops talking. This means I get a lot of unfinished texts, which are truncated.

## What is the expected behavior?
Alexa should not listen while speaking. This also prevent it hearing itself say 'Alexa', as is described in another ticket.

## What behavior are you observing?
It's listening while it's speaking.

**Comment by visayamv** [comment]
Hi @henriz , listening while speaking is allowed so that user can barge-in anytime and override the current dialog. A good use case is when you ask Alexa and it responds with a long response, and you can stop it anytime by barging-in. For example ask alexa what's the fastest animal, it will read out a long statement, you can stop it by saying 'Alexa stop' anytime or initiating another voice request.

As noted by [Issue 372](https://github.com/alexa/avs-device-sdk/issues/372) and [Issue 130](https://github.com/alexa/avs-device-sdk/issues/130), you will need an Acoustic Echo Cancellation component to filter the speaker output from the microphone input. Most production devices would include an Audio Front End (AFE) which would perform AEC.

**Comment by henriz** [comment]
I am already using AEC.  As I mention in the start post, I use pulseaudio. It has an echo cancellation module.

Is it possible to switch the 'listening while talking' off? like a toggle? or in the code?

**Comment by henriz** [comment]
There's also another open ticket about basically the same issue. If you ask Alexa 'what's your name', it'll keep itself busy for like 2-3 answers. This cannot be fixed by AEC, as it's no echo and won't be cancelled or filtered out by any filter. Even in your usecase, if the answer contains the word 'Álexa', it should not listen, as it will break itself off then.

I'll see If I can implement a toggleable setting for this myself. Thanks for confirming that Alexa does indeed listen while talking.

**Comment by subjectxbj** [comment]
We also encounter this problem when we test "alexa, learn my voice".

I think AVS can make an enhancement, when the AVS cloud find the response contains the keyword "alexa", it can send a directive to the device to disable barge in before sending the speak directive.

**Comment by scotthea-amazon** [comment]
Hello henriz,

There is no such switch available in the code, so you will have to implement that yourself.  However, if you do, it will break the interaction model that allows Alexa to be interrupted by the user - so from a usability standpoint it is very likely that it will do more harm than good.

Thank you for the suggestion for how we might avoid this problem.  We will look in to it!

Best regards,
-SWH

**Comment by henriz** [comment]
we dont use alexa for long questions, but for controlling lights, thermostats and outlets. Ocasionally a timer the weather. So for our use case the barge in functionality is unneeded. Also you could make it so that barge in only wotks after x seconds of answer. That would sokve 95% of the false bargeins.

**Comment by scotthea-amazon** [comment]
Hello henriz,

Thank you again for your suggestions.  I am going to close this issue because it has been inactive for so long.  If it has been close din error, please feel free to re-open it.

Best regards,
-SWH
