### ISSUE TITLE
How to map the DSN during authentication and the serialnumber on the Alexa APP

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1022]
Hi,

As you know, we provided the DSN(device serial number) during LWA authentication, But when we check the device on the alexa app, there is another serial number displayed.  These 2 serial numbers are totally different.

But the problem is when our customers report issue, they always report the serial number that displayed on the alexa app. We need to find a way to translate this serialnumber into the DSN we provided, so that we can locate the real device.

So is it possible for provide the mapping method to us?

Thanks

**Comment by scotthea-amazon** [comment]
Hello subjectxbj,

That is a very good question.  I do not know off-hand of a way to do that but will see if there is a way for us to do it.  Do you need this for just one instance - or are you looking for a tool you can use on an as needed basis?

Thank you,
-SWH

**Comment by subjectxbj** [comment]
I need a tool or a script, that take the serialnumber as input and output the DSN. Or you can give me a link on how this should do, then I can write a script to implement that. 

Thanks,
Arthman

**Comment by sey2kim** [comment]
Could I also get an update on this?

**Comment by scotthea-amazon** [comment]
Hello subjectxbj and sey2kim,

I have asked around, and I am sorry to say that there is no public interface or tool with which to perform this mapping.

This sounds like a great feature request.  You can post such feature requests here: https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268

Thank you,
-SWH
