### ISSUE TITLE
[AVS SDK v1.9][Bluetooth] AVS Bluetooth latency > 2 seconds.

### ISSUE THREAD

**Issue by MTKYZ** [alexa/avs-device-sdk#1025]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

HI Amazon,

Current we have integrated AVS SDK 1.9 on our platform. the AVS works well. We also have integrated our Bluetooth stack (Bluedroid), but we found the Bluetooth play latency >1 second. The Bluetooth playback data flow is Phone-->bt stack-->ipc-->avs-->gstreamer-->alsa. 
**Phone-->bt stack-->ipc-->avs** takes 200ms, 
**avs-->gstreamer**  takes about 1~2 seconds.

### **Here** is the log,
(181024_10:41:20.425)2018-10-24 02:41:31.663 [  8] 9 MediaPlayer:handleBusMessage:message=GST_MESSAGE_BUFFERING,percent=0
(181024_10:41:20.425)2018-10-24 02:41:31.663 [  8] 9 MediaPlayer:messageReceived:type=stream-start,source=audio-pipeline
(181024_10:41:20.425)2018-10-24 02:41:31.667 [  8] 9 MediaPlayer:messageReceived:type=buffering,source=decodedQueue
(181024_10:41:20.425)2018-10-24 02:41:31.667 [  8] 9 MediaPlayer:handleBusMessage:message=GST_MESSAGE_BUFFERING,percent=### **1**
(181024_10:41:20.425)**### _2018-10-24 02:41:31.668_** [  8] 9 MediaPlayer:messageReceived:type=buffering,source=decodedQueue
.......
(181024_10:41:22.296)2018-10-24 02:41:33.604 [  8] 9 MediaPlayer:messageReceived:type=buffering,source=decodedQueue
(181024_10:41:22.296)**### _2018-10-24 02:41:33.604_** [  8] 9 MediaPlayer:handleBusMessage:message=GST_MESSAGE_BUFFERING,percent=### **100**

## We found the buffer set in MediaPlayer.cpp, the bufferPercent should be 100 to start bluetooth play, can we set the bufferpercent to 50?
> `

        case GST_MESSAGE_BUFFERING: {
            gint bufferPercent = 0;
            gst_message_parse_buffering(message, &bufferPercent);
            ACSDK_DEBUG9(LX("handleBusMessage").d("message", "GST_MESSAGE_BUFFERING").d("percent", bufferPercent));

            if (bufferPercent < 100) {
                if (GST_STATE_CHANGE_FAILURE == gst_element_set_state(m_pipeline.pipeline, GST_STATE_PAUSED)) {
                    std::string error = "pausingOnBufferUnderrunFailed";
                    ACSDK_ERROR(LX(error));
                    sendPlaybackError(ErrorType::MEDIA_ERROR_INTERNAL_DEVICE_ERROR, error);
                    break;
                }
                // Only enter bufferUnderrun after playback has started.
                if (m_playbackStartedSent) {
                    m_isBufferUnderrun = true;
                }
            }`

### What version of the AVS Device SDK are you using?
      avs 1.9

### Tell us what hardware you're using:
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by kjkh** [comment]
Hi,

Thanks for bringing this to our attention. We will log a ticket and investigate internally. In the meantime, if you wish to reduce the size of the queue, you can refer to the queue2 element API: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-queue2.html. You can reduce the decodedQueue element used in the MediaPlayer pipeline based on either samples, size, or time. This can be done generically across all the MediaPlayers, or targeted at the Bluetooth MediaPlayer if you wish.

**Comment by MTKYZ** [comment]
Hi Amazon,

I have set the "max-size-buffers" to 20 (the default is 100). But the bluetooth playback sound crackles and distorted, so how to reduce the size of the queue in case of normal play? Can we add Mediaplay control in Bluetooth.cpp? i think the buffer will cause latency, it has great influence when playing video.

thanks

**Comment by kjkh** [comment]
Hi,

You can consider modifying only the MediaPlayer that you have passed into the Bluetooth capability agent. This is the one that is responsible for Bluetooth related playback. There are a number of ways to do this, the most straight forward being an extra optional parameter in the MediaPlayer constructor. 

Can you elaborate on what you are considering by adding Mediaplay control in Bluetooth.cpp?

**Comment by visayamv** [comment]
Hi, I will be closing this thread due to inactivity, but feel free to reopen if you can provide more information.

**Comment by fv2018** [comment]
Hi @MTKYZ I'm wondering if there are details on how you implemented the _ipc_ part for your Bluedroid implementation and what platform your are using?  I'm considering doing something similar.
Thanks.

**Comment by MTKYZ** [comment]
> Hi @MTKYZ I'm wondering if there are details on how you implemented the _ipc_ part for your Bluedroid implementation and what platform your are using? I'm considering doing something similar.
> Thanks.

MTK mt8516

**Comment by fv2018** [comment]
Hi @MTKYZ are you able to share any of source code?  I have 2 main issues 1) the correct sequence for power up and connecting/pair a device ... once this works then 2) mapping the AVS Bluetooth interface into MTK calls.  
Thank you.
