### ISSUE TITLE
Problem during AVS installation on Pi 2

### ISSUE THREAD

**Issue by KataPi** [alexa/avs-device-sdk#1026]
Hi everyone,
I have already installed AVS several times, now I want to try Alexa in Italian and I tried to reinstall AVS: I deleted the folders and I followed the instructions from wiki. At 65% my Pi2 slows down almost until it stops. The mouse does not respond, the lights are on and do not flash, from 2 hours it is stopped, the screen goes into standby and turns on normally. It is not freeze but the installation does not go on.
I have formatted everything. With clean installation it makes the same problem.
Raspberry Pi 2 has no bluetooth ....
What to do?

![img_20181026_112934](https://user-images.githubusercontent.com/17763702/47559505-facbc900-d915-11e8-914e-ad4abb0d4cbe.jpg)

## Briefly summarize your issue:
Problem during AVS installation

## Tell us about your environment:
Only openhab already installed

### What version of the AVS Device SDK are you using?
Last version

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Raspbian Stretch

**Comment by scotthea-amazon** [comment]
Hello KataPi,

It sounds like you Pi may be running out of resources during the build.  I see you listed Pi 2.  Is it model B?  Also, do you know the size of your SD card?  Were you still able to open another console window when the build was in a stuck state?

One thing that may help narrow down the problem is to check the available 'disk' and memory (df and free commands) before the build, then early on in the build (say 5%), and finally near the problem point (say 50%).   You can use Ctrl-S to pause the build (by blocking console output) while you run these commands in a separate console and Ctrl-Q to continue.

Best regards,
-SWH

**Comment by KataPi** [comment]
Hello @scotthea-amazon ,
I thank you for your reply. I did not know the df and free commands, thanks to you I learned something new.

I did a bit of testing to verify both ram and disk (SD = 16GB) and I had no problems. The installation is clean. I have formatted the sd and installed the latest version of noobs. I think it's hard to have problems with a newly installed operating system.
![img_20181026_192504](https://user-images.githubusercontent.com/17763702/47584572-2a50f480-d95b-11e8-8e03-119da6a7758e.jpg)

I have no idea why I first installed openhab and Alexa's app later, but I did it!

I was afraid of having little ram and I stopped the openhab service ... !!!

The installation was successful and is fully functional!
![img_20181026_192432](https://user-images.githubusercontent.com/17763702/47584596-3f2d8800-d95b-11e8-8e64-387f53222c91.jpg)

Surely the problem is between openhab and the bluetooth configuration.
After the reboot the openhab service left and Alexa works perfectly!

Thank you all
It can be closed.

P.S.= why Alexa in Italian has a voice worse than that in English?

**Comment by remym777** [comment]
Hi,
I have exactly the same problem with a brand new install of stretch. I've not install any thing else before tryingto install the avs.
the install stops like you at :
**[ 57%] Building CXX object CapabilityAgents/AudioPlayer/src/CMakeFiles/AudioPlayer.dir/AudioPlayer.cpp.o
[ 57%] Building CXX object CapabilityAgents/Bluetooth/src/CMakeFiles/Bluetooth.dir/Bluetooth.cpp.o**

I don't really understand your answer when you explain how you solved the problem. I didn't install ophenhab before. I just strictly followed the tutorial.
My sd is 8gb

thanks by advance
