### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by chesterkuo** [alexa/avs-device-sdk#103]
Hi there,

I just create a docker file used to build docker image for AVS SDK development, if anyone interested in, we can see if this can upstream to it.

Chester

**Comment by chesterkuo** [comment]
There are two image public for docker, if anyone interesting for Dockerfile , I can create pull request of git.

docker pull chesterkuo/avs-device-sdk_core
docker pull chesterkuo/avs-device-sdk_ktti_engine_ubuntu14.04.5

**Comment by kencecka** [comment]
This looks handy.  Thanks for putting it together!  I'm going to close this out as an issue but it should remain searchable on the github page if anyone goes looking for docker.  Fell free to reopen if you have further comments or issues related to this.

Ken

**Comment by AdityaGovardhan** [comment]
Is the dockerfile open sourced?
