### ISSUE TITLE
Installation freezing

### ISSUE THREAD

**Issue by MrXuiryus** [alexa/avs-device-sdk#1030]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When installing the AVS on my Raspberry PI it freezes at a certain part

## What is the expected behavior?
It should continue to install

## What behavior are you observing?
The installer freezes and the OS becomes unresponsive. It always stops at the process at 63%. I've attempted this with a completely fresh install of raspian on a high quality 32GB sdcard with the pi plugged directly into mains power.

## Provide the steps to reproduce the issue, if applicable:
Attempt a fresh install

## Tell us about your environment:
Raspberry Pi Zero WH hooked up to a ReSpeaker 2 pHAT with a speaker plugged in

### What version of the AVS Device SDK are you using?
The latest

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

![image](https://user-images.githubusercontent.com/5465357/47606717-efa89400-da0e-11e8-88bb-00ab2d425889.png)

**Comment by khassel** [comment]
maybe #1014 helps ...

**Comment by kjkh** [comment]
Hi, 

As @khassel mentioned, can you take a look and see if #1014 resolves your issue?

**Comment by kclchan** [comment]
Hi @jtmurphy18, have you tried the solution in #1014?

**Comment by visayamv** [comment]
Hi, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance on this matter.

**Comment by timbeh** [comment]
Well, I'm having this issue and I'm not really finding a working solution for it.
I tried out #1014 but it doesn't work.

**Comment by Haddybaba123** [comment]
I also have the same problem first I was stucked at 93% then after writing various commands and decresing the graphics memory it started but then got stucked on 95% please help waiting from a month and I have also written the same thing on the stackoverflow but no response please please and please help me out
