### ISSUE TITLE
Alexa cannot return the name of the playing song

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1032]
Hi AVS team,

SDK 1.9.0.

While playing a song from Spotify, and ask Alexa about the name of the song, it will fail.

Steps:
Alexa, play music from Spotify
Alexa, what is the name of this song.  (or, Alexa, what is playing)
Alexa will say there is no music is playing right now.

But if I play music from Amazon Music or TuneIn, it will return the current playing name.
It is an SDK bug ?

**Comment by kjkh** [comment]
Hi @zeusshuang,

This is a known bug that is fixed in v1.10.
