### ISSUE TITLE
libDefaultClient.so: internal error

### ISSUE THREAD

**Issue by tushargajjar** [alexa/avs-device-sdk#1033]
i am doing cross compilation of AVS SDK for  apq8053(ARM)
when i run Sampleapp i got error -> libDefaultClient.so: internal error
i have copy   libDefaultClient.so in /usr/lib , /usr/lib64 on the my ARM board

What is the expected behavior?
it should run

## What behavior are you observing?
error of  libDefaultClient.so file

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- for build laptop ubuntu
and target is ARM(apq8053)

### Tell us about your OS (Type & version):
- [x] Linux

**Comment by kjkh** [comment]
Hi @tushargajjar,

Are there any additional error logs or stack traces that you can provide?

**Comment by tushargajjar** [comment]
Solved
I used cross toolchail 32 bit 'arm-linux-gnueabihf-g++'  but now i use 'aarch64-linux-gnu-g++-5' fpr 64 bit ,and re compiled all and solved that error

**Comment by kclchan** [comment]
Hi @tushargajjar, I'm happy to hear that you were able to resolve the issue.  I am going to close this issue now.  Thanks!
