### ISSUE TITLE
COMMS issue

### ISSUE THREAD

**Issue by ANDROIDTODO** [alexa/avs-device-sdk#1035]
Hi AVS Team,

I encountered a problem when I use the comms in the avs, contextManager can not build success.

The AVS SDK version is 1.9.0

The log is below,
[v3.log](https://github.com/alexa/avs-device-sdk/files/2526520/v3.log)

Please help analyze the reasons.

Thanks.

**Comment by dhpp** [comment]
Closing this out.  Please re-open or create a new ticket if you require further assistance.
