### ISSUE TITLE
[AVS SDK 1.10] The Equalizer feature

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1036]
Hi AVS team,

SDK 1.10 on ARM based embedded linux system.

Just a question if it's must to add Equalizer function in SDK 1.10 ? Is it possible to remove it manually ?

Regards,
Eric

**Comment by kjkh** [comment]
Hi @zeusshuang ,

The Equalizer can be disabled. When you say you want to remove the feature, are you talking about compiling it out, or simply disabling it so it does not interfere with other equalizers that may be present on your device?

**Comment by zeusshuang** [comment]
Hi @kjkh ,

I would like to disable it only.
I tried to add it false in json file or set the false in init function in SampleAppliction.cpp, it will still try to init it. Finally I need to set the member data to false by default and now it's disabled.
We can close it now.

**Comment by kjkh** [comment]
Hi @zeusshuang,

Glad you were able to figure it out. However, as per AlexaClientSDKConfig.json, adding the following to your JSON config will disable the Equalizer Capability Agent and the Equalizer Controller from being enabled:

```
"equalizer" : {
   "enabled" : false
}
```

It shouldn't be necessary to make any more code modifications other than that. If you did that and it still is enabled and you want to pursue it further, please re-open the ticket and attach DEBUG9 logs.
