### ISSUE TITLE
Shopping response is changed?

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1037]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi,
I just want check the AVS response of shopping command.

Ask "Alexa, buy paper towels"

In 8/7, AVS response would give me some option
![2018-10-30 13-54-44](https://user-images.githubusercontent.com/43197587/47698811-c294f500-dc4b-11e8-9f81-56b8e70a88a2.png)
In today (10/30), AVS response was changed
![2018-10-30 13-56-16](https://user-images.githubusercontent.com/43197587/47698817-c9bc0300-dc4b-11e8-8547-0851d3a697b8.png)

So, the new response is right?
Or, what should I open the setting in Amazon?
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ * ] Other - tell us more: arm embedded system

### Tell us about your OS (Type & version):
- [ * ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @elfdie00475,

It looks like the response is different because you already have the item in your cart. Can you try removing it from your cart and seeing if you get the 8/7 prompt? On another note, Alexa is constantly getting new features and responses added. This may be a new feature that was introduced, but does not indicate an error.

**Comment by elfdie00475** [comment]
Hi @kjkh, thanks for your reply

I go to remove the things about paper towels from your recommendation.
And, I try shopping command again.
The response is also the same like 10/30.

I totally agree with you. I also think that is a new features.
I just want to confirm that someone has the same experience about shopping.

Thanks for your help again.
