### ISSUE TITLE
A2DP source not fully supported in1.10

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1038]
I just found the the release note in AVS SDK 1.10 mentioned that A2DP Source is supported. 

But as I check the code. Seems the SDK now support A2DP Source profile, it support receving AVRCP command from the sink, but it seems does not support streaming audio from AVS client to A2DP SINK devices.

Can you explain?

Thanks,
Arthman

**Comment by subjectxbj** [comment]
Ok, I noticed that pulseaudio is required to support this.

**Comment by kjkh** [comment]
Hi @subjectxbj,

Yes, the audio routing responsibility is left to the audio layer. For the reference implementation, we use PulseAudio. Do you have a use case in which you require that the SDK handle this instead?

**Comment by subjectxbj** [comment]
Yes, our PLL requires that the device can choose the audio target automatically in following sequence:
1. Bluetooth speaker;
2. Onboard speaker.

So the requirement is when our deivice connected to an external bluetooth speaker, it shall automatically switch audio to the bluetooth speaker.

But the SDK seems does not have such capability.

**Comment by kclchan** [comment]
Hi @subjectxbj, what you describe is outside the scope of the SDK and will need to be implemented by your application.

**Comment by kclchan** [comment]
I am closing this issue now since there is no further question on the topic.  Thanks for reaching out to us.
