### ISSUE TITLE
Set Timer and Play Music cause AVS unstable

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1039]
Hi AVS team,

SDK 1.8.1 / SDK 1.9.0  ARM based embedded linux.

We got many reports from users that while it setup a timer and music is playing, the AVS will become abnormal.
The simple steps are ,
- Alexa, play music
- Alexa, set a timer for 1 minute
--- while time is up
- Alexa, stop.
At this moment, there are vary behavior .
1. It will stop Timer (sound is off) and Music will continue to play. (seldom happen)
2. It will stop Timer (sound is off) and stop Music. (often)
3. It will stop Timer (sound is off) and stop Music, and Alexa no longer response. (seldom happen)
4. It will stop Music, but timer continue. (seldom happen)
5. It will not play timer and Music is playing. (seldom happen)
User complained it burnt the bread with this failed timer ...
6. It will stop Timer (sound is off) and stop Music. After restart, the timer is still play, but from APP, it's closes. At this moment, sometimes, it will cause music play abnormal. (sometimes)

Here I got a first log for case (2).
[timer_music.log](https://github.com/alexa/avs-device-sdk/files/2528752/timer_music.log)

I also tried it with SDK 1.10. The first trial are failed on case (2). Due to my SDK1.10 is unstable, I will attached log while I can confirm it's reproducible.

**Comment by zeusshuang** [comment]
Hi AVS team,
I saw there are same issue reports for this case.
It's really a strange case since Alert / Timer / Alarm are basic function, and we have tried it for months, and as my remember, it's working before.
Is it possible the Alexa directive or any process changes recently ?

**Comment by zeusshuang** [comment]
Hi AVS team,

Attached two log on SDK 1.9.

It's set timer for 20 seconds. After time is up. say Alexa, stop.  
It seems the timer not really stop, after restart avs, it will bring timer tone again.

[set_timer_for_20_seconds.log](https://github.com/alexa/avs-device-sdk/files/2529652/set_timer_for_20_seconds.log)
[stop_and_restart_avs.log](https://github.com/alexa/avs-device-sdk/files/2529653/stop_and_restart_avs.log)

**Comment by zeusshuang** [comment]
Hi AVS team,

It's SDK 1.10.

Just simple test -
Alexa, set timer for 20 seconds.
Time is up.
Alexa. stop

I attached an OK case and a Fail case.  Why I know it's failed, due to while I restart AVS, the timer tone will up again.

And while it's failed, the following timer will no longer up if I set 2nd or 3rd timer.
And while it's failed, if I following ask, Alexa, play Music.  The TTS will play but no music will be played ..

[4-ok.log](https://github.com/alexa/avs-device-sdk/files/2533035/4-ok.log)
[3-fail.log](https://github.com/alexa/avs-device-sdk/files/2533036/3-fail.log)

**Comment by kjkh** [comment]
Hi @zeusshuang,

Thanks for bringing this to our attention. For timer_music.log, what's happening is that the Alert is deleted but then the Alert CA regains focus. There is nothing to play, so the music does not resume. We are investigating this issue and will update when we have more information.

**Comment by zeusshuang** [comment]
Hi @kjkh ,

A question, if I would like to back port the fix from 1.10 to 1.9.0 -
Fixed a bug where there was a delay between receiving a DeleteAlert directive, and deleting the alert.

Which part should I do ? Just the /CapabilityAgents/Alerts ?

**Comment by kclchan** [comment]
Hi @zeusshuang, yes the fix for that issue are localized in CapabilityAgents/Alerts.  Thanks!

**Comment by zeusshuang** [comment]
Hi @kjkh ,
thanks, we can close this case now.
