### ISSUE TITLE
SampleApp can be exit by this exception,please help me check it.

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#104]
2017-08-17 07:44:31.179 [  6] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-08-17 07:49:32.130 [  6] 0 HTTP2Transport:sendPing:pingStream=0
2017-08-17 07:50:02.136 [  6] 0 HTTP2Transport:handlePingResponse
2017-08-17 07:50:02.139 [  6] E HTTP2Transport:pingFailed:responseCode=0
terminate called without an active exception

**Comment by sanjayrd** [comment]
@NyxRockchip2017,

Thanks for the info! Based on a quick google search, it seems like a thread is being destructed without being joined or detached properly. 

Could you provide us some more details about abort? What were you doing just before you encountered this issue? Are there any specific steps we can take to reproduce this? Also, what version of the SDK are you using? Answers to any of these questions would be very helpful in debugging the issue.

Thanks,
Sanjay

**Comment by kencecka** [comment]
Hi @NyxRockchip2017,

I'm going to close this out for now.  Please reopen if you are still encountering this issue, and add any details and logs per Sanjay's suggestions above so that we can further diagnose and reproduce.

Ken
