### ISSUE TITLE
Alarm can not stop issue

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1040]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, 
This issue is found accidentally. So, this may not a problem.

The normal step is:
1. Set an alarm e.g. set alarm for 2:30 p.m.
2. Power off the device until the time past.
3. Power on the device and then the alarm will be started.
4. Stop the alarm.

Follow the normal step, the alarm will be stopped.

But,
When I ask the weather or time question before stop alarm, the alarm will lost control.

Here is the log.
[log.txt](https://github.com/alexa/avs-device-sdk/files/2528983/log.txt)

The log has two part,
one is set alarm, the other is ask question and stop alarm when power on.

## What is the expected behavior?

The alarm could be stopped when power cycle.

## What behavior are you observing?

The alarm could not be stopped when power cycle.

## Provide the steps to reproduce the issue, if applicable:

1. Set an alarm e.g. set alarm for 2:30 p.m.
2. Power off the device until the time past.
3. Power on the device and then the alarm will be started.
4. Ask the time question e.g. what time is it?
5. Stop the alarm.

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [****] Other - tell us more: arm embedded system

### Tell us about your OS (Type & version):
- [****] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @elfdie00475, 

Thanks for bringing this to our attention. There appears to be a failure when the Alerts agent tries to stop and resume the playback upon a barge-in. This is causing it to go into an invalid state. We will investigate further.

**Comment by zeusshuang** [comment]
Hi @kjkh ,

I also got this problem while running simple Alarm test

Alexa, set alarm fro 12:55 A.M
---power cycle DUT, and wait 12:56 and boot up DUT.
---after DUT and AVS is ready, the Alarm started correctly.
Alexa. stop
it seems it got failed and go into ERROR state.

[alarm_cannot_stop.log](https://github.com/alexa/avs-device-sdk/files/2575515/alarm_cannot_stop.log)

**Comment by scotthea-amazon** [comment]
This is fixed in v1.11.  Closing this issue.  If you think this issue has been closed in error, please re-open it and include a comment describing why it should not have been closed.
