### ISSUE TITLE
AudioPlayer can't resume play in the position last time stopped

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#1043]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

For example, "alexa, play hey  jude", alexa started to play hey  jude , and I received PlayerInfoCard to render in screen,  two minutes later, "alexa stop", alexa stopped hey  jude,  I received a new PlayerInfoCard which's offset milliseconds is zero, not the position alexa stopped. Then “alexa resume”，
alexa continue to play hey jude at the position that is not the position I stopped last time, at the same time , I received a new PlayerInfoCard which's offset milliseconds is not  the position I stopped last time.

## What is the expected behavior?

Alexa should continue to play song at the position I stopped last time, and the offset milliseconds too.
## What behavior are you observing?

alexa continue to play to play song at the position that is not the position I stopped last time, 
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more: Embded system

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @DonghuaZheng,

Can you compile with DEBUG9 and attach logs for the issue?

**Comment by DonghuaZheng** [comment]
@kjkh Hi, is there any problem in the log , by the way, I was implemented MediaPlayer with my own mediaplayer instead of GStreamer.

**Comment by kclchan** [comment]
Hi @DonghuaZheng, the TemplateRuntime Capability Agent gets the PlayerInfoCard's offset by calling the getAudioItemOffset() api from the AudioPlayer Capability Agent.  The AudioPlayer Capability Agent would then retrieve the information from its MediaPlayer.  So the fact that PlayerInfoCards is displaying offset of zero points to a MediaPlayer issue.

And please check the offset field in the PlaybackStopped event sent by the AudioPlayer.  This offset is again retrieved from the MediaPlayer, and if this is also zero, this should be why you are having resume issue where it's not resuming where it should be.

**Comment by DonghuaZheng** [comment]
@kclchan Hi, thanks, I solved this issue
