### ISSUE TITLE
SampleApplication Failed to create media player for speech for sdk 1.10.0

### ISSUE THREAD

**Issue by hinar24** [alexa/avs-device-sdk#1045]
## Briefly summarize your issue:
I am cross compiling AVS SDK for ARM platform. As per AVS SDK dependencies Gstreamer & its plugins of 1.8.3 or later version is required. So I have cross compiled Gstreamer & its plugins of version 1.14.4 through source code in Ubuntu 16.04.
but there's some fail when run SampleApp

## What is the expected behavior?
    SampleApp should start

## What behavior are you observing?
  AlexaClientSDKConfig.json  SampleApp  application-necessities
  /data/AVS # ./SampleApp AlexaClientSDKConfig.json
  1970-01-08 17:25:14.636 [  1] I sdkVersion: 1.10.0
  configFile AlexaClientSDKConfig.json

(SampleApp:2773): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:2773): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-08 17:25:14.743 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-08 17:25:14.743 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

### What version of the AVS Device SDK are you using?
      AVS SDK - 1.10.0
      aarch64-linux-gnu-gcc-5
      gstreamer-1.14.4

### Tell us what hardware you're using:
      - [ ] Other : APQ8053 arm 

### Tell us about your OS (Type & version):
      - [ ] Linux

**Comment by kclchan** [comment]
Hi @hinar24, would you be able to attach the full DEBUG9 logs?  Also, could you check if you have all the necessary gstreamer plugin as well as described in: https://github.com/alexa/avs-device-sdk/wiki/Dependencies 
Thanks!

**Comment by hinar24** [comment]
Hi @kclchan, here is logs with DEBUG9

/data/AVS # ./SampleApp Integration/AlexaClientSDKConfig.json DEBUG9
1970-01-12 13:28:00.862 [  1] I sdkVersion: 1.10.0
configFile Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
1970-01-12 13:28:00.866 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

1970-01-12 13:28:00.866 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

1970-01-12 13:28:00.873 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

1970-01-12 13:28:00.873 [  1] E MediaPlayer:setupPipelineFailed:reason=createQueueElementFailed
1970-01-12 13:28:00.873 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed

(SampleApp:2752): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:2752): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-12 13:28:00.873 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

1970-01-12 13:28:00.873 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=SpeakMediaPlayer
1970-01-12 13:28:00.874 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-12 13:28:00.874 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by kclchan** [comment]
Hi @hinar24, from the logs, the MediaPlayer failed to create due to this error:
```
1970-01-12 13:28:00.873 [ 1] E MediaPlayer:setupPipelineFailed:reason=createQueueElementFailed
```
Could you take a look at #935?  The problem was resolved by adding an environment variable.  Thanks!

**Comment by kclchan** [comment]
Hi @hinar24.

Could you try to run this command:
```
CMD="./SampleApp Integration/AlexaClientSDKConfig.json DEBUG9"
strace $CMD  2>&1 | grep open | grep libgst
```
And then see if the path to the libgst* can be found in your system.

Also, maybe you can take a look at the url below and see some environment variables that you might need to set on your platform:
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html

**Comment by hinar24** [comment]
Hi @kclchan ,
Thank you for support. Problem is solved after adding environment variable for gst-plugins .

**Comment by digoot** [comment]
Hi @hinar24,

Could you explain me about what environment variable do you used to solve this problem? Where I should set it? And last, which path should I use to load all gstreamer plugins? I've read all threads posted previously, but no one writes about a concrete solution or maybe I don't understand it so much what they are talking about.

Thank you so much.

**Comment by hinar24** [comment]
Hi @digoot ,
All variables are given on https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html .I have used export GST_PLUGIN_PATH=gstreamer-1.0-lib-path on terminal.

**Comment by tekprepper** [comment]
sudo apt-get install gstreamer1.0-alsa fixed it for me :)
