### ISSUE TITLE
Alexa AVS SDK V1.10 doesn't Play Music

### ISSUE THREAD

**Issue by ShivaKrishnaCharka** [alexa/avs-device-sdk#1046]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We have upgraded our solution from AVS SDK1.5 to AVS SDK1.10. After the upgrading, when uttered, "Alexa Play My Music", it is playing only NPR News Only, where as AVSSDKV1.5 is playing music.
## What is the expected behavior?

It should play Music file associate to the account.
## What behavior are you observing?

It is playing only NPR News
### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK1.10
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
ARM CORTEX A9 Based Platform
### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Linux

**Comment by ShivaKrishnaCharka** [comment]
Hi ,
We have recently migrated to AVS SDK V1.10. After Integrating AVS SDK V1.10, We are unable to Play Music, Even though the account registered is prime and contains music files, it plays only NPR News and Say's music is not supported on this device? 

Please find the DEBUG LOG for the same.(First time we asked, PLay My Music, it Played NPR News, then We asked Play Happy Song, it said, Music is not supported on this device)
 
[Music_Not_Playing.log](https://github.com/alexa/avs-device-sdk/files/2538394/Music_Not_Playing.log)

**Comment by kclchan** [comment]
Hi @ShivaKrishnaCharka, please note that Access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

If you have gotten the approval before, could you check if you are using the same clientId and productId?

**Comment by ShivaKrishnaCharka** [comment]
Hi @kclchan ,
Thanks for your response. We will contact our representative and try after approval.

Thanks,
Shiva
