### ISSUE TITLE
SampleApp provided by SDK on Android  can't get any response from keyboard input

### ISSUE THREAD

**Issue by HanYunChenLuo** [alexa/avs-device-sdk#1047]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I wangto run the sampleApp provided by sdk on Android , now i could run the sampleApp, but i can't get any response from input by my keyboard.

## What is the expected behavior?
run android sampleapp

## What behavior are you observing?
any keyboard input haven.t been responsed

## Provide the steps to reproduce the issue, if applicable:
using android sampleapp

## Tell us about your environment:
 Ubuntu16.04     SDK<1.10>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

*Android
### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @HanYunChenLuo, Does your SampleApp response to voice command?  Would you be able to attach the logs when you run the SampleApp?  Thanks!

**Comment by HanYunChenLuo** [comment]
> Hi @HanYunChenLuo, Does your SampleApp response to voice command? Would you be able to attach the logs when you run the SampleApp? Thanks!

Thank you! 
Now I run this sampleApp without adb , and problen has been solved.
And I wish a guidance how to build a android app through using NDK could be pushlished soon!

**Comment by kclchan** [comment]
HI @HanYunChenLuo, I am glad that the SampleApp is working for you now.
