### ISSUE TITLE
ESP is not supported in this device.

### ISSUE THREAD

**Issue by ginamdar** [alexa/avs-device-sdk#1048]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I setup alexa avs sdk, everything seems to be working fine, even sameple app and sdk compiled properly. I can even launch the SampleApp and hear the ding with menu. When I hit t <Enter> command I get above error/message followed by "Invalid Option"

## What is the expected behavior?
Should get the response back?

## What behavior are you observing?
It comes back saying ESP it not supported

## Provide the steps to reproduce the issue, if applicable:
1) Launch the SampleApp
2) Wait for Authorization
3) Authorization is successful
4)type t Enter
5)Get Listening... message back on console
6)Type some question
7)Immediately  gets above message

### What version of the AVS Device SDK are you using?
1.10.0

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x ] MacOS  iMac 2012 10.13.6 (17G65) High Sierra
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ginamdar** [comment]
Now to read it again i feel really stupid, i need to speak and not type!,

**Comment by kclchan** [comment]
Hi @ginamdar, no problem at all, I am glad that you got it working!  I'm going to close this issue now, thanks!
