### ISSUE TITLE
Distinguish between disconnect error and refresh authorization token

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1051]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi,

I want add disconnect error state by visual cue. I use the onConnectionStatusChanged callback function to check disconnect error state.
But, I see that when the authorization process refresh token, it will change connection status a while.
The onConnectionStatusChanged callback also be worked.
So, have any way can distinguish between disconnect error and refresh token?

Here is log.
[log.TXT](https://github.com/alexa/avs-device-sdk/files/2552594/log.TXT)

Thanks~~
## Provide the steps to reproduce the issue, if applicable:

In log time 
"2018-11-06 08:27:44", I plug out the ethernet cable.
"2018-11-06 08:28:44", I can get onConnectionStatusChanged status=PENDING, reason=SERVER_SIDE_DISCONNECT.
"2018-11-06 08:29:52", I plug in the ethernet cable.
"2018-11-06 08:29:57", I get onConnectionStatusChanged status=CONNECTED, reason=ACL_CLIENT_REQUEST.
"2018-11-06 09:16:56", the authorization process start refresh token.
"2018-11-06 09:24:50:", I get onConnectionStatusChanged status=PENDING, reason=SERVER_SIDE_DISCONNECT.
"2018-11-06 09:24:51", I get onConnectionStatusChanged status=CONNECTED, reason=ACL_CLIENT_REQUEST.
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [****] Other - tell us more: arm-linux embedded

### Tell us about your OS (Type & version):
- [*****] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello elfdie00475,

What your logs show at 2018-11-06 09:24:50 is a normal periodic disconnect from Alexa service (happens about once an hour) and recovery from that disconnect.  The SDK could try to hide the temporary disconnect, but instead it provides the current state and leaves it up the the application to smooth over this transition for the user.  You should be able to do this by delaying any user notification for a short time (e.g. 10 seconds), to allow for a successful reconnect. 

I hope that helps,
-SWH
