### ISSUE TITLE
Not able to build MRM Modules in AVS SDK V1.10

### ISSUE THREAD

**Issue by ShivaKrishnaCharka** [alexa/avs-device-sdk#1052]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am trying to build the AVS SDK V1.10 by enabling the MRM modules.
I have used the below flags to build the MRM. 
 -DENABLE_MRM=ON -DMRM_LIB_PATH=$BASE_DIR/sdk-source/avs-device-sdk-master/CapabilityAgents/MRM/src/libMRM.a -DMRM_INCLUDE_DIR=$BASE_DIR/sdk-source/avs-device-sdk-master/CapabilityAgents/MRM/include 

## What is the expected behavior?

MRM Modules should be enabled and compiled.
## What behavior are you observing?

MRM Modules are not built.
### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK V1.10
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ X] Other - tell us more: ARM CORTEX based linux Platform. 

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ShivaKrishnaCharka** [comment]
Hi,
We are trying to demonstrate MRM on our product which is a cortex based linux platform. 
To do this we firstly tried with Amzon Echo and Dot devices by registering both the devices using same AMAZON Account. We are able to add Amazon Echo Devices under MRM group in Amazon Alexa Appp and name the devices.(Ex: One device with Bedroom , one device name as Kitchen)

We build AVS SDK V1.10 and loaded on our platform. We have registered the app running on our platform(Which has Ethernet Port, doesn't have Wifi) also to the same account as the above two echo devices.

We tried adding our device to MRM group in Add "Multi-Room Music Speakers" group. But our device is not displayed in the list of devices available.

We realized that we have not enabled MRM modules in AVS SDKV1.10 and tried building MRM Modules by giving the below flags.
-DENABLE_MRM=ON -DMRM_LIB_PATH=$BASE_DIR/sdk-source/avs-device-sdk-master/CapabilityAgents/MRM/src/libMRM.a -DMRM_INCLUDE_DIR=$BASE_DIR/sdk-source/avs-device-sdk-master/CapabilityAgents/MRM/include

When we build the app, CMAKE is ignoring above Flags and not building the MRM Modules.
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_MRM
    MRM_INCLUDE_DIR
    MRM_LIB_PATH

My Question is :
1) Is MRM needs to be enabled in app for alexa app to detect our device under MRM Group?
2) In case , MRM is needed, Please suggest the steps needed to build?
3)  Is there any other steps needed to do for listing our devices under MRM?

Please provide your suggestions.

Thanks.

**Comment by kclchan** [comment]
Hi @ShivaKrishnaCharka, please note that in order to enable MRM, you will need an additional package.  Please contact your Amazon Business Development Representative to get more information on how to enable MRM on your product.  Thanks!

**Comment by zuowanbushiwo** [comment]
@kclchan  How to contact Amazon Business Development Representative？ Is there an email?

**Comment by anu-mathur** [comment]
@zuowanbushiwo can you please fill out the contact form [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and we'll reach out to you?

**Comment by zuowanbushiwo** [comment]
@anu-mathur  thanks！

**Comment by kclchan** [comment]
Closing the issue now.  Thanks for reaching out to us!
