### ISSUE TITLE
Alexa is not going to speaking state at all on ubuntu 16.04 platform

### ISSUE THREAD

**Issue by vijay464** [alexa/avs-device-sdk#1053]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by kclchan** [comment]
Hi @vijay464, could you please run the sample application with DEBUG9 and attach the logs for us?  Thanks!

**Comment by kclchan** [comment]
Hi @vijay464, from the logs, it seems AVS couldn't understand your utterance so there's why it doesn't go into speaking state at all.  Could you log into the web app at https://alexa.amazon.com/ and check if  you see your utterance there?  Thanks!

**Comment by vijay464** [comment]
Hi kclchan,
I didnt found my utterance in that link. Problem is with machine as it is not taking the question. Now it is working fine.
Thank you for your support.

**Comment by kclchan** [comment]
Hi @vijay464, I am glad that you got it working now.  Thanks!
