### ISSUE TITLE
macOS Quick Start Guide steps lead to "Permission denied" error

### ISSUE THREAD

**Issue by Kyle-Falconer** [alexa/avs-device-sdk#1054]
## Briefly summarize your issue:
The "macOS Quick Start Guide" steps cannot be followed as written. 

for macOS do not include the instruction needed to make `genConfig.sh` executable.

## What is the expected behavior?
`genConfig.sh` should execute properly and report "Completed generation of config file" if the given parameters are correct.

## What behavior are you observing?

When running `genConfig.sh` with the suggested arguments, it results in the following error:

```
bash: ./genConfig.sh: Permission denied
```

This can be solved by making `genConfig.sh` executable with `chmod +x genConfig.sh`, but the instructions do not indicate this needs to happen.

## Provide the steps to reproduce the issue, if applicable:

Follow the steps in the setup guide up to "Setup your configuration", step 2 under the "genConfig.sh" heading, which gives the following instruction:

> Navigate to {{path to source folder}}/avs-device-sdk/tools/Install and run genConfig.sh, including the following arguments:

```
cd {{path to source folder}}/avs-device-sdk/tools/Install

genConfig.sh config.json {device serial number} \
/{{path to database}} \
/{{path to source folder}}/avs-device-sdk \
{{path to build}}/Integration/AlexaClientSDKConfig.json
```

## Tell us about your environment:
n/a

### What version of the AVS Device SDK are you using?
This issue is found in Rev 26 of the "macOS Quick Start Guide":

https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide/4f84931a3e798dd161168d05b57938bb466e2416

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @Kyle-Falconer, thanks for bringing this to our attention.  You are correct, this is an error in the start guide.  Could you try this instead?
```
bash genConfig.sh config.json {device serial number} \
/{{path to database}} \
/{{path to source folder}}/avs-device-sdk \
{{path to build}}/Integration/AlexaClientSDKConfig.json
```
Thanks!

**Comment by kclchan** [comment]
Thanks for the feedback and PR.  We have corrected the instruction now.  Thanks!
