### ISSUE TITLE
Will the companionAuth source code be provided later?

### ISSUE THREAD

**Issue by gavinlwz** [alexa/avs-device-sdk#1055]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Will the companionAuth source code be provided later?
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:
WIFI speaker

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @gavinlwz, is this what you are looking for?  Thanks!
https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-app.html#sample-code

**Comment by kclchan** [comment]
Hi @gavinlwz, and here is some more instruction you may look into:
https://github.com/alexa/avs-device-sdk/wiki/Authorizing-AVS-Device-SDK-Software-with-AVS#companion-app
