### ISSUE TITLE
play audio book fail

### ISSUE THREAD

**Issue by yanggewei** [alexa/avs-device-sdk#1058]
[audio book fail.txt](https://github.com/alexa/avs-device-sdk/files/2560797/audio.book.fail.txt)
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue: I play audio book fail
I use my own player rather than gstreamer, and I modified MediaPlayer.cpp to adapt to my player, when play music , audio book and radio, I transfer url to AttachmentReader, and AttachmentReader will download data(the same way as sample code), when I play music, radio, kindle book, it works well, but when I play audio book, i failed. AttachmentReader returns AttachmentReader::ReadStatus::OK_WOULDBLOCK, I will provide log file , and I want to know why, thaks

The reason may be a missing ssl certificate on the device , how can I get certificate?

### What version of the AVS Device SDK are you using? 
SDK 1.9

### Tell us what hardware you're using:
STB

### Tell us about your OS (Type & version):
 Linux

**Comment by kclchan** [comment]
Hi @yanggewei, from the log file you attached, I am not seeing OK_WOULDBLOCK.  And also please note that OK_WOULDBLOCK is not a failure, below is the document for this status:
```
On a request for n bytes, less than n bytes were available on a non-blocking read.
```

**Comment by yanggewei** [comment]
it is bacause loss of DigiCert_Global_Root_CA.pem, it work well now, thank you ,the issue can be closed
