### ISSUE TITLE
It takes about 5-7 seconds delay while playing music from Amazon Music 

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1060]
Hi AVS team,

AVS SDK 1.9.0  ARM based embedded linux.

To compare the Echo and AVS SDK at the same environment, while playing amazon music (or TuneIn / iHeartRadio), it will be late about 5-7 seconds on AVS SDK.
But while it plays the Spotify, it will almost the same as Echo.
We tried it at different sites (US, UK, Italy, and Germany), all have the same results.

For example in our test -
Alexa, play Madonna from Amazon Music.
--> it will have a TTS then start playing. Between TTS and start playing, it will have 5-7 seconds latency.
Alexa, play Madonna from Spotify.
--> it will have a TTS then start playing, the latency is within 2 seconds.

With Amazon Music, we tried many different combinations, to just play music, or play a specific song name or play from a music library, all the same behavior.  

I have a sample log and look into the logs for this case, please help to check it ?

[avs.log](https://github.com/alexa/avs-device-sdk/files/2561490/avs.log)
[spotify_and_Amazon_music.txt](https://github.com/alexa/avs-device-sdk/files/2561492/spotify_and_Amazon_music.txt)

**Comment by kclchan** [comment]
Hi @zeusshuang, from the logs, it seems it's taking considerable amount of time to get the playlist from Amazon Music:
```
2018-11-06 07:57:02.238 [  4] 0 MediaPlayer:handleSetSourceForUrlCalled
...
2018-11-06 07:57:07.313 [ 25] 3 UrlContentToAttachmentConverter:onPlaylistEntryParsed:status=STILL_ONGOING
...
2018-11-06 07:57:07.328 [ 25] 3 UrlContentToAttachmentConverter:onPlaylistEntryParsed:status=FINISHED
```

If possible, please set the cmake option "ACSDK_EMIT_SENSITIVE_LOGS=ON", then you should be able to see the url the SDK is trying to read from.  With this information, you can try to do a ping to that url and see if you see considerable delay as well.  Hope this helps!

**Comment by zeusshuang** [comment]
Hi @kclchan ,

Thanks for the information, I will try and check it.
Could you have a simple example and mention which information I should check while I enabled this option ?

**Comment by kclchan** [comment]
Hi @zeusshuang, for example:

```
2018-11-10 00:05:10.808 [ 18] 9 MediaPlayer:setSourceForUrlCalled:url=https\://d29r7i......
...
2018-11-10 00:05:11.125 [ 21] 9 PlaylistParser:PlaylistParser:contentType=application/vnd.apple.mpegurl,url=https\://.....,length=-1

```

**Comment by zeusshuang** [comment]
Hi @kclchan ,

Thanks that and I tried it here ..

looks like there is no networking latency from my site.  (168.95.1.1 is my ISP's DNS server).
I saw case #805 also mentioned this case before, is there any other possibility for this case ?

ping d29r7idq0wxsiz.cloudfront.net
PING d29r7idq0wxsiz.cloudfront.net (13.35.0.136): 56 data bytes
64 bytes from 13.35.0.136: seq=0 ttl=244 time=4.608 ms
64 bytes from 13.35.0.136: seq=1 ttl=244 time=3.898 ms
64 bytes from 13.35.0.136: seq=2 ttl=244 time=4.266 ms

ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=119 time=4.411 ms
64 bytes from 8.8.8.8: seq=1 ttl=119 time=6.102 ms
64 bytes from 8.8.8.8: seq=2 ttl=119 time=4.884 ms
64 bytes from 8.8.8.8: seq=3 ttl=119 time=4.419 ms

ping 168.95.1.1
PING 168.95.1.1 (168.95.1.1): 56 data bytes
64 bytes from 168.95.1.1: seq=0 ttl=247 time=3.283 ms
64 bytes from 168.95.1.1: seq=1 ttl=247 time=3.661 ms
64 bytes from 168.95.1.1: seq=2 ttl=247 time=3.425 ms
64 bytes from 168.95.1.1: seq=3 ttl=247 time=3.647 ms


[ping.txt](https://github.com/alexa/avs-device-sdk/files/2567924/ping.txt)
[4.log](https://github.com/alexa/avs-device-sdk/files/2567925/4.log)

**Comment by ShivaKrishnaCharka** [comment]
Hi AVS Team,

I am seeing the similar issue with Audible book play. When i asked to play audible books, TTS response comes immediately, however the book reading will be started after **~15sec** of delay. Is there anyway i could verify, who is the culprit. Is there any way i could verify ping audible URL? If so where can i find the URL?

Thanks,
Shiva

**Comment by celinval** [comment]
Hi @ShivaKrishnaCharka, please follow @kclchan's suggestion and print the URLs being fetched. Then use the command `ping` to see what is the latency to reach those urls.

Hi @zeusshuang,  do you see any performance difference when you build the SDK using RELEASE mode?

Thanks

**Comment by zeusshuang** [comment]
Hi @celinval ,

I tried SDK1.11, seems approved about 1 second.
And I found a very interesting thing, if I play music from MRM, it will be very faster !!
It almost the same as Echo ---> TTS (here is XXX by YYY on Amazon Music playing in the OOO group) and playing Music at the same time in the background!
So, it seems ffmepg mode is faster than gst mode ?

**Comment by scotthea-amazon** [comment]
Hi Zeusshuang,

This appears to be the same issue as reported here: [Issue #1088](https://github.com/alexa/avs-device-sdk/issues/1082).

As such I am closing this so that we can track the issue in one place.  If you think this issue has been closed in error, please feel free to re-open it and provide information about why it is different than [Issue #1088](https://github.com/alexa/avs-device-sdk/issues/1082).

Thank you,
-SWH
