### ISSUE TITLE
can not add music to playlist for Device playback test

### ISSUE THREAD

**Issue by daizhenmail** [alexa/avs-device-sdk#1063]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
we are doing the Alexa Far Field Reference Solutions Test, In the test it requires to upload some music to the library for playback test, but I found it is unable to upload local music to Amazon music library any more
## What is the expected behavior?
How can I upload the test music to Amazon library

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
HI @daizhenmail, you didn't mention how you tried to upload the music to Amazon Music, did you follow the steps similar to below:
https://www.amazon.com/gp/help/customer/display.html?nodeId=201379280

**Comment by daizhenmail** [comment]
> HI @daizhenmail, you didn't mention how you tried to upload the music to Amazon Music, did you follow the steps similar to below:
> https://www.amazon.com/gp/help/customer/display.html?nodeId=201379280

Hi, I tried to upload the music with the Amazon Music for PC, but I can not find the Upload section, it seems that this app doesn't support uploading music any more?

**Comment by aumatsui** [comment]
Hi daizhenmail,

Thank you for confirming and we are sorry you are not able to upload contents using the PC app. We have already filed an internal ticket to track the issue that you are having. We will update this ticket as soon as we have any additional information.

**Comment by aumatsui** [comment]
Hi @daizhenmail,

I was just informed that unfortunately the music storage feature is getting discontinued: https://www.amazon.com/gp/help/customer/display.html?nodeId=201379330

So I am closing this ticket. Please let us know if you need additional help.
