### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by edmondkreuk** [alexa/avs-device-sdk#1066]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by aumatsui** [comment]
Hi edmondkreuk, can you give us details about the problem that you are having?

**Comment by edmondkreuk** [comment]
Well.... I can't seem to get my Raspberry to execute the bash script
(startsample.sh) on reboot or crash...

I've tried crontab, init.d.

I'm a (relatieve) newbie, so maybe I haven't looked around enough.

So, any kind of help is usefull :-)

Regards,

Edmond

>

**Comment by aumatsui** [comment]
Please check this issue: https://github.com/alexa/avs-device-sdk/issues/539

**Comment by aumatsui** [comment]
I am closing this issue since it looks like what you are trying to accomplish is already being discussed on the other issue.

**Comment by edmondkreuk** [comment]
Okay, thanks for your help :-)
