### ISSUE TITLE
Echo Spatial Perception Feature - Question

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#107]
Hi,

Can you comment on ESP feature that AMAZON has for ECHO devices.
Is it a cloud-based solution or it is something that needed to be coded on device side?
Will a product implementing AVS C++ SDK support that feature across multiple devices using same AVS account?

Thank you in advanced,
Juliano Ribeiro

**Comment by jairajiv** [comment]
Hi Juliano, ESP is not currently supported for AVS devices. We are not yet publically discussing the ESP feature or the functional requirements. Regards,
Rajiv
