### ISSUE TITLE
No template directive send when play kindle book

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1072]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi,

We are starting to implement display card into our device.
In recent, we play the Kindle book very well, but we cannot get template directive.

Does anyone also have the same problem?

Here is my log
[log.TXT](https://github.com/alexa/avs-device-sdk/files/2579940/log.TXT)

## What is the expected behavior?

AVS get template directive and we can get player info data from callback.

## What behavior are you observing?

AVS not get template directive

## Provide the steps to reproduce the issue, if applicable:

Play kindle book

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: arm-linux embedded system

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by aumatsui** [comment]
Hi elfdie00475,

After some investigation, it looks like there is a cloud issue related to AVS not sending such cards for Kindle books. We are opening an internal issue to get this checked by the service team.

**Comment by liunanxuan** [comment]
Is the problem that the client cannot receive the template directive solved? We have also encountered this problem at the moment. And recently it is necessary to go to the certification body certification test.

**Comment by techistoner** [comment]
same issue

**Comment by kclchan** [comment]
This issue is fixed on cloud side already.  Please re-open this issue if it's not the case.  Thanks!
