### ISSUE TITLE
How to make the sampleapp use Pulseaudio Source & Sink?

### ISSUE THREAD

**Issue by henriz** [alexa/avs-device-sdk#1075]
I have a raspberry pi zero W with a Respeaker MIC hat 2.0.

As the pi zero is ARM6, you cannot use the default wakeword engine. I have built it using the snowboy (kitt.ai) wakeengine, compiled for ARM6 and without using NEON.

This all works fine. However, the Respeaker has dismal audio quality. To this extent, I also installed pulseaudio, with the webrtc AEC, again, compiled for ARM6 and disabling NEON.

Now how do I get the sample app to actually use pulse? I created a source (AEC_src) and a (AEC_sink) in pulseaudio, tested both with paplay and parecord, and both work. The audio improvement from the mic, is amazing.

However, I can't get the sampleapp to use pulse, nor can I find any information on how to set this up.

In the clientconfig file, there's this:

 "gstreamerMediaPlayer":{
         "outputConversion":{
             "rate":16000,
             "format":"S16LE",
             "channels":1
         },
         "audioSink":"AEC_sink"
    }

I have also tried 'pulseaudiosink', to no effect.

I get this:

2018-11-16 08:51:53.401 [  1] E MediaPlayer:setupPipelineFailed:reason=createAudioSinkElementFailed,audioSinkElement=AEC_sink
2018-11-16 08:51:53.402 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed

SO how do I tell the sample app the source and sink to use with pulseaudio?

Note, I did install the gstreamer1.0-pulseaudio package. Gstreamer works with pulseaudio fine.

**Comment by aumatsui** [comment]
Hi henriz,

You can also try "pulsesink" for GStreamer.

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-pulsesink.html

Please let us know if you are still having trouble after trying this string.

**Comment by henriz** [comment]
This does not work either. Strangely enough, it seems to still be using alsa, as it starts with a lot of remarks about alsa. The microphone however, does work. It does understand the question, but for some reason it cannot answer.

##############################################################################
#     RenderTemplateCard
#-----------------------------------------------------------------------------
# Focus State         : FOREGROUND
# Template Type       : WeatherTemplate
# Main Title          : Vleuten, Netherlands
##############################################################################

2018-11-17 12:09:01.331 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"ExpectSpeech"\,messageId\:"fea77967-36bf-47dd-89e0-726c6fe5b8a0"\,dialogRequestId\:"b1eb222b-b7fb-4578-9dde-7ef0ad4a6988"}
2018-11-17 12:09:01.335 [  4] I DirectiveRouter:preHandleDirective:messageId=fea77967-36bf-47dd-89e0-726c6fe5b8a0,action=calling
2018-11-17 12:09:01.337 [  8] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-11-17 12:09:02.001 [  8] E MediaPlayer:handleBusMessageError:source=src,error=Internal data stream error.,debug=gstbasesrc.c(2950)\: gst_base_src_loop ()\: /GstPipeline\:audio-pipeline/GstAppSrc\:src\:
streaming stopped\, reason not-linked (-1)
2018-11-17 12:09:02.002 [  8] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-11-17 12:09:02.008 [  5] I DirectiveRouter:cancelDirective:messageId=fea77967-36bf-47dd-89e0-726c6fe5b8a0,action=calling
########################################
#       Alexa is currently idle!       #
########################################

**Comment by henriz** [comment]
It simply does not work. Alexa works fine with alsa. Pulseaudio works fine, tested with parecord and paplay. 

Alexa simply won't work with pulse. Whatever I do it starts out with a lot of text about alsa. With pulseaudio it does record audio, but simply won't play. It sais "speaking" but there's no audio.

The old java app did work fine, it had an audio frontend. The avs-device-sdk apparently does not, as without pulse I get A LOT of false positives on the wakeword detection. Which means any answer it wants to give, is interrupted by the untoggleable barge in function. With pulse it listens fine, but answers are not played correctly.

I'm kindoff out of options.

Note that gstreamer works fine. Ie:

gst-launch-1.0 filesrc location=creep.wav ! wavparse ! audioconvert ! pulsesink

plays my 'creep.wav' file just fine (creep by radiohead).

Does a debug build tell you exactly where alexa writes the output audio to?

**Comment by henriz** [comment]
Finally got the time to get around to this. 

So, Pulseaudio is working. Gstreamer is working with pulseaudio. 

The relevant section in the clientconfig:

  "gstreamerMediaPlayer":{
         "outputConversion":{
             "rate":16000,
             "format":"S16LE",
             "channels":2
         },
         "audioSink":"pulsesink"
     }


This is the relevant output:

ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:556:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave

As you can see, it still tries to use alsa instead of pulseaudio.

**Comment by henriz** [comment]
I have found what's wrong here. Gstreamer is just about the OUTPUT of the avs-device-sdk. I want to manipulate the INPUT, and get the INPUT from pulseaudio.

This apparently cannot be done, or I'm doing it wrong. Portaudio uses alsa, not pulseaudio.

However, it still can be accomplished. You can load the snd_aloop loopback device for pulse, then an alsa-sink driver for pulse, and then the loopback in pulse to route the echo-cancelled microphone input back to alsa.

This works, but it's a drag to setup. So for the microphone input, the full audio-route then becomes:

microphone --> alsa --> pulseaudio source --> module echo_cancel --> pulseaudio source --> pulseaudio loopback module --> pulseaudio alsa sink module --> alsa loopback device --> portaudio --> avs_device_sdk.

As you can see, this is pretty convoluted. Is there no way to have the sample application take it's audio directly from pulseaudio, instead of portaudio?

**Comment by kclchan** [comment]
Hi @henriz, the SDK uses the PortAudioMicrophoneWrapper to read data from portaudio.  You may take a look and see if you could write a wrapper that reads from pulseaudio instead.  Hope this helps!

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.
