### ISSUE TITLE
Config json file not found (Installation)

### ISSUE THREAD

**Issue by namsohj** [alexa/avs-device-sdk#1076]
I setup Alexa voice service to Raspberry to do the thesis Smart Home Control by Alexa Voice Service. When I enter this sudo bash setup.sh config.txt to Raspberry, after run the program return Config json file not found!. I don't know how to solve this problem.

I have not found a solution, this is my log (see the latest line): https://paste.ubuntu.com/p/VZYCGT5ggk Where is the json Config file, how to solve this problem to complete the installation?

**Comment by dhpp** [comment]
Hi @namsohj, per our guide [here](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script#setup), it is possible you simply misnamed your config.json as config.txt (which I see in your linked log), and I also note that you did not provide a serial number.

Could you please try again carefully following the instructions, and let us know if that helps?
