### ISSUE TITLE
custom wake word

### ISSUE THREAD

**Issue by shabdhu** [alexa/avs-device-sdk#1078]
Sorry for violating the issue writing guide. For more than a week I have been trying to add a custom wake word to my avs sdk. I have been facing many issues. Can someone please guide me step by step to use kitt ai mypersonalmodel.pmdl as the hotword for alexa.

I am running it on raspberry pi.

Thanks in advance

**Comment by andrewsl1234** [comment]
I have been having the same problem for quite some time and would also greatly appreciate help on this. I have no programming experiencing and have not been able to figure out how to use cmake. ie. When I am in the terminal do I execute the below command while I am in my avs-device-sdk folder? For example: cd ~/Desktop/avs-device-sdk cmake.... 

Can you give an example on what the "absolute-path-to-lib" and "absolute-path-to-include-dir" would be for this if someone were to have their avs-device-sdk folder saved on their desktop?

Also, can I leave my custom wake word file as a .pmdl or do I need to convert it to something else? Lastly do I save this custom wake word file? 

Thank you very much for your help

cmake <absolute-path-to-source> -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=<absolute-path>/snowboy-1.2.0/lib/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=<absolute-path>/snowboy-1.2.0/include
