### ISSUE TITLE
Response shows Client not connect just before connecting successfully

### ISSUE THREAD

**Issue by ankit-agrahyah** [alexa/avs-device-sdk#1084]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Most of the time just before Client is successfully connected to the server, it gives a pretty print in the logs for a short span of time as "Client not connected"

## What is the expected behavior?
Status of AVS should directly go to "Alexa is idle" state from "Connecting" state if internet connection is not having any issues.

## What behavior are you observing?
Many a times, there exists a state in logs "Client not connected" for a short span of time, between "Connecting..." and "Alexa is idle" state.  

## Provide the steps to reproduce the issue, if applicable:
Try to reconnect through sample app on multiple devices and platform and multiple internet connections

### What version of the AVS Device SDK are you using?
     1.10.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android

**Comment by dhpp** [comment]
Hi @ankit-agrahyah.  I would suggest you look at SampleApplication/src/UIManager.cpp, in particular the void UIManager::printState() function.  That function is invoked when either:
* onDialogUXStateChanged
* onConnectionStatusChanged
* microphoneOn
occurs.  The first 2 should result in trace that the user expects.  Are you toggling the microphone before the connection occurs?  In that case, if you'd like to suppress the trace in that case, then I would consider updating that function to test the m_connectionStatus variable, and only call printState if connected.

Let us know if you need any further assistance.

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.

**Comment by walaankit** [comment]
I made the changes as recommended, printing state only if connected in the microphoneOn function
