### ISSUE TITLE
How to get the Alexa Speech Recognition result?

### ISSUE THREAD

**Issue by lhp620** [alexa/avs-device-sdk#1086]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How to get the Alexa Speech Recognition result? For example, 
1. user says "Alexa, what is the weather today?"
2. device microphone records the sound and processes it as binary audio, then send to Alexa cloud service
3. due to the accent, distance or something else, Alexa may get any of the following result as transcription text from the binary audio stream:
- "Alexa, what the weather today?"
- "Alexa, what is the wee today?"
- "Alexa, what is the weather?"

4. I want to know how to get the actual Alexa recognition result in text.

### What version of the AVS Device SDK are you using?
AVS 1.6

### Tell us what hardware you're using:
Amazon Amlogic DDK

### Tell us about your OS (Type & version):
Linux

**Comment by dhpp** [comment]
Thanks @lhp620.  Unfortunately this is not a supported feature of AVS at the current time.  I would suggest you do post this as a feature request [here](https://forums.developer.amazon.com/topics/feature+request.html).
