### ISSUE TITLE
Can I use the Alexa Voice Service (AVS) Device SDK  for Android 4.4?

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1088]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I look at   Android Quick Start Guide ，I'm notice that the parameter, API_LEVEL  , Supported version: API 23+ or greater is supported.  The API 23  is  correspond to Android 6.0，it's that mean i can't use the SDK for Andorid 4.4 ?    Please tell  me, thanks very much !

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!
Sorry for long response. The way SDK currently adapted for the Android requires device to run on API 23+. So yes, you will not be able to run it on older OS.

**Comment by celinval** [comment]
Hi @xuewenxu,

You are more than welcome to try. I don't think we use anything specific introduced on API 23. That said, this can change at any time and we only support / test devices running API 23 and above.

**Comment by xuewenxu** [comment]
Thank you @celinval,

I'm trying it on for Android 4.4.

**Comment by mavamazon** [comment]
It seems that there might be an answer:
https://github.com/alexa/avs-device-sdk/issues/1092#issuecomment-441973926
