### ISSUE TITLE
Memory Leak Observed (10MB/Hr) with Gst Appsink Element in AVS SDK V1.10

### ISSUE THREAD

**Issue by ShivaKrishnaCharka** [alexa/avs-device-sdk#1089]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We are observing lot of memory leak(~10MB/hr), In AVS SDK V1.10, when we use gstAppsink element to pull the data from the pipeline. Where as there is no memory leak observed when used with gstAutoAudiioSink element.
## What is the expected behavior?

There shouldn't be any memory leak
## What behavior are you observing?

There is a memory leak of 10MB/hr
## Provide the steps to reproduce the issue, if applicable:

Integrate the appsink to replace the autoaudiosink and do the continous music play.
### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK V1.10
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Linux

**Comment by ShivaKrishnaCharka** [comment]
Hi,
Please find the integration of appsink element  and how we used appsink methods to fetch the data from pipeline.

int MediaPlayer::app_sink_pull_data(char* inputBuffer, int * data_size)
{
   int data_available = 0;
   GstSample *sample = NULL;
   *data_size = 0;
   GstState curState;
   auto stateChange = gst_element_get_state(m_pipeline.pipeline, &curState, NULL, TIMEOUT_ZERO_NANOSECONDS);
   if (stateChange == GST_STATE_CHANGE_FAILURE) {
       ACSDK_ERROR(LX("handlePlayFailed").d("reason", "gstElementGetStateFailed"));
   }
   if((curState != GST_STATE_READY) && (curState != GST_STATE_PLAYING))
   {
      //printf("data unavailable state:%d \n", curState); 
      return data_available;
   }
   if (m_pipeline.appSink != NULL)
   {
      sample = gst_app_sink_try_pull_sample(GST_APP_SINK(m_pipeline.appSink), GST_SECOND/1000);
      if (sample)
      {
         /* The only thing we do in this example is print a * to indicate a received buffer */
         // Actual compressed image is stored inside GstSample.
         GstBuffer* buffer = gst_sample_get_buffer(sample);
         GstMapInfo map;
         gst_buffer_map(buffer, &map, GST_MAP_READ);

         // Copy data
         memmove(inputBuffer, map.data, map.size);
         *data_size = map.size;

         gst_buffer_unmap(buffer, &map);
         gst_buffer_unref(buffer);
         data_available = 1;
      }
   }

   return data_available;
}

Also, Please find the modified MediaPlayer.cpp file to use the appsink.

Our Algorithm, will make a call to "probe_app_sink" function for every 10ms to fetch the data from the pipeline.

**Comment by mavamazon** [comment]
Thank you, @ShivaKrishnaCharka. We are going to investigate it and loop back to you.

**Comment by kclchan** [comment]
Hi @ShivaKrishnaCharka, I would recommend taking a look at (https://gstreamer.freedesktop.org/documentation/plugin-development/advanced/allocation.html) and see if you need to use gst_memory_unmap() to release the memory.  Since the use of gstAppSink is outside the scope of the SDK, I am closing the issue now.
