### ISSUE TITLE
sign out from device

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#109]
What does it mean by "Sign out of Alexa on device ".
I did a sign out from my account on alexa.amazon.com , but the device keeps working fine.

Please suggest.

**Comment by kencecka** [comment]
You can sign out of the companion "Amazon Alexa" app on your phone/tablet as follows:
- Open the menu
- Select Settings
- Scroll to the bottom of the settings menu
- Select SIGN OUT

Ken
