### ISSUE TITLE
sometimes "recommend podcast" fail

### ISSUE THREAD

**Issue by yanggewei** [alexa/avs-device-sdk#1091]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

when I say "Alexa, recommend podcast" , sometimes it work well , but sometimes it play fail.
In the log file I provide，in line 1734：
2018-11-26 07:34:35.532 [ 10] E AudioPlayer:executeOnPlaybackError:id=8,type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=playFailed
it play fial, and alexa set a new url, but it fail again, in line 2028:
2018-11-26 07:34:47.860 [ 10] E AudioPlayer:executeOnPlaybackError:id=9,type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=playFailed
then , alexa set a new url again, then it play successfully in line 2358:
2018-11-26 07:34:54.056 [ 10] 1 AudioPlayer:sendEventWithTokenAndOffset:eventName=PlaybackStarted,offset=0
I find when it play fail, there is no data downloaded to attachment, AttachmentReader::read returns OK_WOULDBLOCK
can you find the reasion from the log file?

### What version of the AVS Device SDK are you using?
      SDK 1.10

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [y ] Other - tell us more: STB

### Tell us about your OS (Type & version):
- [ y] Linux  
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
[recommend podcast fail.txt](https://github.com/alexa/avs-device-sdk/files/2614528/recommend.podcast.fail.txt)

**Comment by mavamazon** [comment]
Hi!
The MEDIA_ERROR_INTERNAL_DEVICE_ERROR error is a result of MediaPlayer::play() failure. Looking at the logs it seems that play() fails because of this:
```
2018-11-26 07:34:35.532 [ 10] 5 MediaPlayer:HI_SVR_PLAYER_Play Called:s32Ret=-1,m_hPlayer=2864381953
2018-11-26 07:34:35.532 [ 10] E MediaPlayer:HI_SVR_PLAYER_Play fail
```
It looks like a custom call you've added. If this custom message corresponds to some vanilla SDK actions please let me know.

**Comment by yanggewei** [comment]
@mavamazon thank you for your reply
HI_SVR_PLAYER_Play is the interface of my own player to play music, the reason why it play fail is that AttachmentReader read data fail, so the player has no data to process.
I find AttachmentReader::read returns OK_WOULDBLOCK until my player report "play fail"

**Comment by mavamazon** [comment]
`OK_WOULDBLOCK` read status means that there is no data available yet. This happens pretty often for the content downloaded from the internet. This is especially true for the streaming services, when there is nothing to "download" and the audio data arrives in portions as soon as it becomes available. When you receive such state you should process the available data and then read from attachment reader again as soon as new data arrives. You can see the example of handling this value [here](https://github.com/alexa/avs-device-sdk/blob/178bcb10514de7e84c725adc8bbf0a777f3970f9/MediaPlayer/GStreamerMediaPlayer/src/AttachmentReaderSource.cpp#L121).

Please let me know if it helps.

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.
