### ISSUE TITLE
Cant run startsample.sh on Android devices. Error information: CANNOT LINK EXECUTABLE: could not load library "libAndroidSLESMediaPlayer.so" needed by "/data/alexa/bin/SampleApp"; caused by could not load library "libavformat.so" needed by "libAndroidSLESMediaPlayer.so"; caused by cannot locate symbol "BN_free" referenced by "libavformat.so"...

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1092]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I follow Android guide,  this more information:
[100%] Linking CXX executable SampleApp
[100%] Built target SampleApp

==============> SAVING CONFIGURATION FILE ==============

Completed generation of config file: /home/xxw/xuxuewen/work/alexa_for_android/script/build/Integration/tmp_AlexaClientSDKConfig.json

==============> FINAL CONFIGURATION  ==============

 {
    "gstreamerMediaPlayer":{
        "audioSink":"autoaudiosink"
    },
    "cblAuthDelegate":{
        // Path to CBLAuthDelegate's database file. e.g. /home/ubuntu/Build/cblAuthDelegate.db
        // Note: The directory specified must be valid.
        // The database file (cblAuthDelegate.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for CBLAuthDelegate (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/cblAuthDelegate.db"
    },
    "deviceInfo":{
        // Unique device serial number. e.g. 123456
        "deviceSerialNumber":"123456",
        // The Client ID of the Product from developer.amazon.com
        "clientId":"amzn1.application-oa2-client.57982a64ab0545569013f9076adf5148",
        // Product ID from developer.amazon.com
        "productId":"idh"
    },
    "capabilitiesDelegate":{
        // The endpoint to connect in order to send device capabilities.
        // This will only be used in DEBUG builds.
        // e.g. "endpoint": "https://api.amazonalexa.com"
        // Override the message to be sent out to the Capabilities API.
        // This will only be used in DEBUG builds.
        // e.g. "overridenCapabilitiesPublishMessageBody": {
        //          "envelopeVersion":"20160207",
        //          "capabilities":[
        //              {
        //                "type":"AlexaInterface",
        //                "interface":"Alerts",
        //                "version":"1.1"
        //              }
        //          ]
        //      }
    },
    "miscDatabase":{
        // Path to misc database file. e.g. /home/ubuntu/Build/miscDatabase.db
        // Note: The directory specified must be valid.
        // The database file (miscDatabase.db) will be created by SampleApp, do not create it yourself.
        "databaseFilePath":"/data/alexa/databases/miscDatabase.db"
    },
    "alertsCapabilityAgent":{
        // Path to Alerts database file. e.g. /home/ubuntu/Build/alerts.db
        // Note: The directory specified must be valid.
        // The database file (alerts.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for alerts (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/alerts.db"
    },
    "settings":{
        // Path to Settings database file. e.g. /home/ubuntu/Build/settings.db
        // Note: The directory specified must be valid.
        // The database file (settings.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for settings (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/settings.db",
        "defaultAVSClientSettings":{
            // Default language for Alexa.
            // See https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated for valid values.
            "locale":"en-US"
        }
    },
    "bluetooth" : {
        // Path to Bluetooth database file. e.g. /home/ubuntu/Build/bluetooth.db
        // Note: The directory specified must be valid.
        // The database file (bluetooth.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for bluetooth (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/bluetooth.db"
    },
    "certifiedSender":{
        // Path to Certified Sender database file. e.g. /home/ubuntu/Build/certifiedsender.db
        // Note: The directory specified must be valid.
        // The database file (certifiedsender.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for certifiedSender (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/certifiedSender.db"
    },
    "notifications":{ 
        // Path to Notifications database file. e.g. /home/ubuntu/Build/notifications.db
        // Note: The directory specified must be valid.
        // The database file (notifications.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for notifications (don't use it for other components of SDK)
        "databaseFilePath":"/data/alexa/databases/notifications.db"
    },
    "sampleApp":{
        // To specify if the SampleApp supports display cards.
        "displayCardsSupported":true
        // The firmware version of the device to send in SoftwareInfo event.
        // Note: The firmware version should be a positive 32-bit integer in the range [1-2147483647].
        // e.g. "firmwareVersion": 123
        // The default endpoint to connect to.
        // See https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#endpoints for regions and values
        // e.g. "endpoint": "https://avs-alexa-na.amazon.com"

        // Example of specifying suggested latency in seconds when openning PortAudio stream. By default,
        // when this paramater isn't specified, SampleApp calls Pa_OpenDefaultStream to use the default value.
        // See http://portaudio.com/docs/v19-doxydocs/structPaStreamParameters.html for further explanation
        // on this parameter.
        //"portAudio":{
        //    "suggestedLatency": 0.150
        //}
    }

    // Example of specifying output format and the audioSink for the gstreamer-based MediaPlayer bundled with the SDK.
    // Many platforms will automatically set the output format correctly, but in some cases where the hardware requires
    // a specific format and the software stack is not automatically setting it correctly, these parameters can be used
    // to manually specify the output format.  Supported rate/format/channels values are documented in detail here:
    // https://gstreamer.freedesktop.org/documentation/design/mediatype-audio-raw.html
    //
    // By default the "autoaudiosink" element is used in the pipeline.  This element automatically selects the best sink
    // to use based on the configuration in the system.  But sometimes the wrong sink is selected and that prevented sound
    // from being played.  A new configuration is added where the audio sink can be specified for their system.
    // "gstreamerMediaPlayer":{
    //     "outputConversion":{
    //         "rate":16000,
    //         "format":"S16LE",
    //         "channels":1
    //     },
    //     "audioSink":"autoaudiosink"
    // },

    // Example of specifiying curl options that is different from the default values used by libcurl.
    // "libcurlUtils":{
    //
    //     By default libcurl is built with paths to a CA bundle and a directory containing CA certificates. You can
    //     direct the AVS Device SDK to configure libcurl to use an additional path to directories containing CA
    //     certificates via the CURLOPT_CAPATH setting.  Additional details of this curl option can be found in:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_CAPATH.html
    //     "CURLOPT_CAPATH":"INSERT_YOUR_CA_CERTIFICATE_PATH_HERE",
    //
    //     You can specify the AVS Device SDK to use a specific outgoing network interface.  More information of
    //     this curl option can be found here:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html
    //     "CURLOPT_INTERFACE":"INSERT_YOUR_INTERFACE_HERE"
    // },

    // Example of specifying a default log level for all ModuleLoggers.  If not specified, ModuleLoggers get
    // their log level from the sink logger.
    // "logging":{
    //     "logLevel":"INFO"
    // },

    // Example of overriding a specific ModuleLogger's log level whether it was specified by the default value
    // provided by the logging.logLevel value (as in the above example) or the log level of the sink logger.
    // "acl":{
    //     "logLevel":"DEBUG9"
    // },

    // // Example for specifiying the Template Runtime display card timeout values.
    // "templateRuntimeCapabilityAgent": {
    //     // If present, shall overide the default timeout for clearing the RenderTemplate display card when SpeechSynthesizer is in FINISHED state.
    //     "displayCardTTSFinishedTimeout": 2000,
    //     // If present, shall overide the default timeout in ms for clearing the RenderPlayerInfo display card when AudioPlayer is in FINISHED state.
    //     "displayCardAudioPlaybackFinishedTimeout": 2000,
    //     // If present, shall overide the default timeout in ms for clearing the RenderPlayerInfo display card when AudioPlayer is in STOPPED or PAUSED state.
    //     "displayCardAudioPlaybackStoppedPausedTimeout": 60000
    // }

    // // The equalizer function allows you to adjust equalizer settings, such as decibel (dB) levels and modes.
    // // By default, the equalizer is enabled. The default settings are:
    // // * `"enabled":true`. By default, the equalizer is active.
    // // * All `"bands"` are active: `BASS`, `MIDRANGE`, `TREBLE`.
    // // * "modes" are disabled. See below for more information.
    // // * Minimum band level (`"minLevel"`): -6 dB
    // // * Maximum band level (`"maxLevel"`): +6 dB
    // // * Default state (defaultState): All "bands" are set to 0dB, and no "mode" is active.

    // "equalizer": {
    //     // Enables or disables the equalizer. Setting this value to `false` will disable the equalizer locally, and report to AVS that it is disabled.
    //     "enabled": true,
    //     // The equalizer bands supported by the device. Currently, there are only three available options: `BASS`, `MIDRANGE` and `TREBLE`.
    //     // By default, all bands are enabled. However, if you specify a band or bands, then only those will be supported.
    //     // bands will be supported.
    //     "bands": {
    //         "BASS": true,
    //         "MIDRANGE": true,
    //         "TREBLE": true
    //     },
    //     // The equalizer modes supported by the device. AVS doesn't define specific behavior for modes,
    //     // the `EqualizerModeControllerInterface` defines this behavior. AVS provides the following options for modes: "MOVIE", "MUSIC", "NIGHT",
    //     // "SPORT", "TV". By default, all modes are disabled (`false`), unless specifically marked as enabled (`true`).
    //     "modes": {
    //         "NIGHT": false,
    //         "MOVIE": false,
    //         "MUSIC": false,
    //         "SPORT": false,
    //         "TV": false
    //     },
    //     // The equalizer factory settings. These default values are used for a newly registered device, or when a user requests that Alexa reset a band.
    //     "defaultState": {
    //         // The default mode to be applied. When no default mode is desired, set the `"mode"` value to `"NONE"`, which is a custom value.
    //         "mode": "NONE",
    //         // Defines band level defaults (integer dB)
    //         "bands": {
    //             "BASS": 0,
    //             "MIDRANGE": 0,
    //             "TREBLE": 0
    //         }
    //     },
    //     // Minimum value an equalizer band could have (integer dB).
    //     "minLevel": -6,
    //     // Maximum value an equalizer band could have (integer dB).
    //     "maxLevel": 6
    // }

 }

// Notes for logging
// The log levels are supported to debug when SampleApp is not working as expected.
// There are 14 levels of logging with DEBUG9 providing the highest level of logging and CRITICAL providing
// the lowest level of logging i.e. if DEBUG9 is specified while running the SampleApp, all the logs at DEBUG9 and
// below are displayed, whereas if CRITICAL is specified, only logs of CRITICAL are displayed.
// The 14 levels are:
// DEBUG9, DEBUG8, DEBUG7, DEBUG6, DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, DEBUG0, INFO, WARN, ERROR, CRITICAL.

// To selectively see the logging for a particular module, you can specify logging level in this json file.
// Some examples are:
// To only see logs of level INFO and below for ACL and MediaPlayer modules,
// -  grep for ACSDK_LOG_MODULE in source folder. Find the log module for ACL and MediaPlayer.
// -  Put the following in json:

// "acl":{
//  "logLevel":"INFO"
// },
// "mediaPlayer":{
//  "logLevel":"INFO"
// }

// To enable DEBUG, build with cmake option -DCMAKE_BUILD_TYPE=DEBUG. By default it is built with RELEASE build.
// And run the SampleApp similar to the following command.
// e.g. ./SampleApp /home/ubuntu/.../AlexaClientSDKConfig.json /home/ubuntu/KittAiModels/ DEBUG9"
================================================================================
= Installing AVS Device SDK on the target device.
================================================================================
= Wait until device is online. Please make sure the device is 
= connected.
================================================================================
= Make sure device intall target exists and has write permission
================================================================================
= Generate CA bundle
/system/etc/security/cacerts/: No such file or directory
/home/xxw/xuxuewen/work/alexa_for_android/script/debug/android-19/armeabi-v7a/install/lib/: 67 files pushed. 0.7 MB/s (171409473 bytes in 236.046s)
/home/xxw/xuxuewen/work/alexa_for_android/script/build/SampleApp/src/SampleApp: 1 file pushed. 0.7 MB/s (18422744 bytes in 24.750s)
/home/xxw/xuxuewen/work/alexa_for_android/script/build/Integration/AlexaClientSDKConfig.json: 1 file pushed. 0.4 MB/s (12551 bytes in 0.030s)
 **** Completed Configuration/Build ***
xxw@kitty:~/xuxuewen/work/alexa_for_android/script$ 
xxw@kitty:~/xuxuewen/work/alexa_for_android/script$ /bin/bash startsample.sh 
CANNOT LINK EXECUTABLE: could not load library "libAndroidSLESMediaPlayer.so" needed by "/data/alexa/bin/SampleApp"; caused by could not load library "libavformat.so" needed by "libAndroidSLESMediaPlayer.so"; caused by cannot locate symbol "BN_free" referenced by "libavformat.so"...
### What version of the AVS Device SDK are you using?
      1.10

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more: Android devices, Android version is 4.4

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!
It seems that SDK unable to find FFMpeg libraries on your Android. Could you please make sure that setup.sh worked well for you and send us logs for it? You may want to start it fresh by deleting the following folders before running setup.sh:
Libraries
build
debug

In addition to the setup.sh logs could you please provide your config.txt?

**Comment by xuewenxu** [comment]
Hi, @mavamazon

The attach file log.txt  is log that run setup.sh.  
My config.txt is androidConfig.txt  and its details as follow:
    # Fill the lines below to configure android build.
    PLATFORM="android"
    API_LEVEL="19"
    TARGET_SYSTEM="arm"
    DEVICE_INSTALL_PATH="/data/alexa" 
    BUILD_TYPE="debug"

**Comment by xuewenxu** [comment]
Hi, @mavamazon 

It seems that the files upload failed.  And i upload again.

[log.txt](https://github.com/alexa/avs-device-sdk/files/2618145/log.txt)
[androidConfig.txt](https://github.com/alexa/avs-device-sdk/files/2618146/androidConfig.txt)

**Comment by mavamazon** [comment]
It seems that OS is unable to link SDK binaries with the proper version of OpenSSL. It automatically links SDK with the system's version of OpenSSL that either lacks big number support or having problems linking crypto library (BN_free function is missing). This happens because when we build libraries on the host machine we use our version of OpenSSL with all its dependencies provided. However when compiled SDK (and OpenSSL) binaries are loaded into the Android, OS uses its own versions of the dependencies OpenSSL uses. And it seems that for API 19 these dependencies do not meet the expectations of OpenSSL 1.1.0 the way we build it. 

I've checked on my emulator with two versions of API 19 (open sources and Google APIs) - both have problems with OpenSSL dependencies and don't run even though I build SDK having API version set to 19 in config.txt. The same binary works find under API 26 emulator device when installed without rebuild.

So it seems that in order to use API 19 you need to deal with the versions of OpenSSL and its dependencies. Our installation script supports only that much, sorry :(

@celinval could clarify better, since she knows more details that I may miss.

**Comment by xuewenxu** [comment]
Hi, @mavamazon 

Are you sure that  the  problem is the version of Openssl .  
To  test it, I tried to  delete  libssl.so  which is Android comes with   in  '/system/lib'  directory  then  run  startsample.sh  and it shows  the same  error  as above.
The error information shows  libavformat.so cannot locate symbol "BN_free"  rathan than libssl.so.

**Comment by mavamazon** [comment]
Yea, I initially was looking in ffmpeg code, but BN_free is apparently an OpenSSL (libcrypto) function:
https://www.openssl.org/docs/manmaster/man3/BN_free.html
I just checked where BN_free is in our binaries and it resides in libssl.so (libssl.so.1.1 as well). So it seems that in your environment libavformat.so for some reason cannot find libssl.so at all. Can you please check if libssl.so (libssl.so.1.1) exists in /data/alexa/lib folder?

**Comment by xuewenxu** [comment]
Hi, @mavamazon 

The libssl.so(libssl.so.1.1) is exist in /data/alexa/lib folder.  And symbol  "BN_free"  is both  in libssl.so  and  libavformat.so.

**Comment by xuewenxu** [comment]
Hi, @mavamazon 

The puzzle above  about  Openssl  is  solved.  I make  the ffmpeg  to link the  libssl.a  rathan  than  the libssl.so  through  modify  the script android.sh.  Change   LDFLAGS="-L${INSTALL_TARGET_LIB} -lssl"  to  LDFLAGS="-L${INSTALL_TARGET_LIB} -l:libssl.a -fPIC"  and  commented   --enable-openssl(#--enable-openssl) when build  ffmpeg. 

But  there is another error while run startsample.sh, the error information as follow:
xxw@kitty:~/xuxuewen/work/alexa_for_android/script$ /bin/bash startsample.sh 
2015-01-01 01:13:39.919 [  1] I sdkVersion: 1.10.0
configFile /data/alexa/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2015-01-01 01:13:40.111 [  1] 0 ConfigurationNode:initializeSuccess
2015-01-01 01:13:40.143 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
2015-01-01 01:13:40.144 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
2015-01-01 01:13:40.145 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
2015-01-01 01:13:40.145 [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
2015-01-01 01:13:40.311 [  1] E AndroidSLESObject:getInterfaceFailed:result=12
2015-01-01 01:13:40.311 [  1] E AndroidSLESMediaPlayer:createFailed:reason=equalizerInterfaceUnavailable
Segmentation fault (core dumped)

**Comment by mavamazon** [comment]
Hi!
Yes, your system does not seem to support equalizer. You should install a third party equalizer. There is a bug in 1.10 that does not allow you to work on an android system not supporting equalizer.

**Comment by mavamazon** [comment]
BTW, the fix for this bug is going to be released in 1.11 so please stay in touch.

**Comment by xuewenxu** [comment]
That's great, thank you.

**Comment by celinval** [comment]
Hi @xuewenxu, do you have any further questions related to this issue? Let me know if I can close this one.
