### ISSUE TITLE
Can't build Portaudio  for SDK  on Android?  

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1094]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Add build_port_audio funciton in setup.sh  and  the options of run ./configure  as follow:
 ./configure --without-jack  --host="${TOOLCHAIN_HOST}" --build="${TOOLCHAIN_BUILD}" --with-sysroot="${SYSROOT}" 

logs:

==============> BUILDING PORT AUDIO ==============

~/xuxuewen/work/alexa_for_android/script/third-party ~/xuxuewen/work/alexa_for_android/script
--2018-11-27 15:52:09--  http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
Resolving www.portaudio.com (www.portaudio.com)... 107.22.210.58
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

~/xuxuewen/work/alexa_for_android/script/third-party/portaudio ~/xuxuewen/work/alexa_for_android/script/third-party ~/xuxuewen/work/alexa_for_android/script
arm-linux-androideabi
/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/sysroot
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking target system type... arm-unknown-linux-androideabi
checking for arm-linux-androideabi-gcc... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang accepts -g... yes
checking for /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang option to accept ISO C89... none needed
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld
checking if the linker (/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-nm -B
checking the name lister (/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to arm-unknown-linux-androideabi format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld option to reload object files... -r
checking for arm-linux-androideabi-objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for arm-linux-androideabi-dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-androideabi-ar... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ar
checking for archiver @FILE support... @
checking for arm-linux-androideabi-strip... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-strip
checking for arm-linux-androideabi-ranlib... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ranlib
checking for gawk... no
checking for mawk... mawk
checking command to parse /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-nm -B output from /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang object... ok
checking for sysroot... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/sysroot
checking for arm-linux-androideabi-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
checking how to run the C preprocessor... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-cpp
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang supports -fno-rtti -fno-exceptions... yes
checking for /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang option to produce PIC... -fPIC -DPIC
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang PIC flag -fPIC -DPIC works... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang static flag -static works... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang supports -c -o file.o... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang supports -c -o file.o... (cached) yes
checking whether the /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang linker (/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ -E
checking whether the /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ linker (/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld) supports shared libraries... yes
checking for /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ option to produce PIC...  -DPIC
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ PIC flag  -DPIC works... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ static flag  works... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ supports -c -o file.o... yes
checking if /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ supports -c -o file.o... (cached) yes
checking whether the /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-clang++ linker (/home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for ar... /home/xxw/Android/ndk/toolchains/android-ndk-r16/toolchain-armeabi-v7a/android-19/bin/arm-linux-androideabi-ar
checking whether byte ordering is bigendian... no
checking for snd_pcm_open in -lasound... no
checking for HPI_SubSysCreate in -lhpi... no
checking sys/soundcard.h usability... no
checking sys/soundcard.h presence... no
checking for sys/soundcard.h... no
checking linux/soundcard.h usability... yes
checking linux/soundcard.h presence... yes
checking for linux/soundcard.h... yes
checking machine/soundcard.h usability... no
checking machine/soundcard.h presence... no
checking for machine/soundcard.h... no
checking for _oss_ioctl in -lossaudio... no
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking for clock_gettime in -lrt... no
checking for clock_gettime... yes
checking for nanosleep... yes
checking for pthread_create in -lpthread... no
configure: error: libpthread not found!

BUT  I look at the logs of building libcurl  in android.sh  and  the result of checking for pthread_create in -lpthread  is yes.

How do i  set the options  for   build  portaudio for SDK  on Andorid,  please  tell me!

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:  Android device

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hey! You don't need PortAudio for Android. SDK uses OpenSL ES API instead which is a native part of most Android OS builds, so you may skip this step.

**Comment by xuewenxu** [comment]
@mavamazon , thank you
