### ISSUE TITLE
sensory

### ISSUE THREAD

**Issue by Alexander-Guy** [alexa/avs-device-sdk#1095]
I have a rasberry pi 3 and get as far as the  **sudo bash setup.sh config.json -s 1234** command 

however when the install gets to the section

=================>CLONING AND BUILDING SENSORY<=======================

I get this message :

Cloning into 'alexa-rpi'...

fatal: unable to connect to github.com:
github.com[0: 140.82.118.3]: Connection timed out
github.com[0: 140.82.118.3]: Connection timed out

I have tried cloning the sensory rpi git as suggested in issue  #94 but it leads to the smae message
has anyone got a fix for this or is there a way to manually install this sensory software package ?

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.
