### ISSUE TITLE
How to Access wiki pages for AVS SDK 1.9.0

### ISSUE THREAD

**Issue by avp24** [alexa/avs-device-sdk#1096]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I could see that from 1.10.0 onwards modifications have been made in SDK for generating AlexaClientSDKConfig.json using genConfig.sh. But previous to these versions steps to directly modify AlexaClientSDKConfig.json were mentioned.

## What is the expected behavior?

As I have made already made a working setup using AVS SDK 1.9.0 how do I access wiki pages related to 1.9.0.
## What behavior are you observing?

I could see wiki pages related to 1.10.0
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!
On the wiki page of your interest you can click on a "XX revisions" link below the title. It will show you the list of all the versions of this page.
Additionally I will ask our tech writers to update the wiki to provide help to developers who is using previous version of the SDK. Thank you for pointing out!
