### ISSUE TITLE
Does the Alexa use Amazon transcribe API to recognize the audio stream

### ISSUE THREAD

**Issue by lhp620** [alexa/avs-device-sdk#1097]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I want to know how Alexa recognize the audio stream from Amazon Alexa DDK, like Amlogic. For example:
1. I say "Alexa, what is the weather today?" to the Alexa DDK. The device convert the voice to binary audio stream and sent to AVS.
2. AVS recognize it and provide response.

I want to know how Alexa recognize the audio steam. Does Alexa call Amazon transcribe API convert the audio stream to text and then analyze it?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
Amlogic DDK

### Tell us about your OS (Type & version):
Linux

**Comment by mavamazon** [comment]
Hi!
Sorry, but AVS SDK is a client side product and we are not aware of full cycle for speech recognition happening on the server side. 
I believe [Alexa Developer Forums](https://forums.developer.amazon.com/spaces/165/index.html) is the right place for your question.

**Comment by lhp620** [comment]
Thanks, I post to forum:
https://forums.developer.amazon.com/questions/192257/does-the-alexa-use-amazon-transcribe-api-to-recogn.html
