### ISSUE TITLE
AVS always picking locale as en-IN irrespective of locale set in config file

### ISSUE THREAD

**Issue by ankit-agrahyah** [alexa/avs-device-sdk#1098]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Having issues with locale ,
Changing locale using setLocale call in UserInputManager class, gives me a callback of onSettingsChanged that locale is changed , for example to en-GB, still the locale remains unchanged and stays as en-IN for Alexa's voice. Also even when the locale in config file is kept as en-US and the sdk and sample app is run on a new device where it was never previously installed or run, the locale stays as en-IN. 

Have faced less such issues early, when changing locale

## What is the expected behavior?

The locale should get picked up from config file and setlocale should reflect properly

## What behavior are you observing?

Locale does not change even after changing locale to multiple different locales using setLocale from the UserInputManager class, settings.db file also gets updated accordingly.

## Provide the steps to reproduce the issue, if applicable:

Try changing the locale to some different locale that the default one. Try keeping it as en-GB in the config file and then run the sample app after deleting the settings.db file.

### What version of the AVS Device SDK are you using?
   1.10.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android Phones

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android 23 to 29

**Comment by mavamazon** [comment]
Hi!
I've tried several ways to update the locale and they seem to work. Could you please send us the SDK logs covering both the SDK startup and the moment you change the locale (preferably as an attachment) .

**Comment by visayamv** [comment]
Hello, I will be closing this thread due to inactivity, but feel free to reopen if you need further assistance.
