### ISSUE TITLE
timers and alarms

### ISSUE THREAD

**Issue by bill-lzb** [alexa/avs-device-sdk#1099]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Play some music right after setting a timer(for 30 seconds), when the time set for timer is reached, music paused,but alert sound is not played, and "Stop" dismisses the alarm,then the music resumed.
## What is the expected behavior?

The alarm should be delivered to the device once the time it's set for is reached, music should pause, "Stop" dismisses the alarm and the music resumes.
## What behavior are you observing?

when the time set for timer is reached, music pauses and alert sound for timer should be played.
## Provide the steps to reproduce the issue, if applicable:

1, set a timer for 30 seconds.
2, play music.
3,wait for the timer to go off.
4,say "Stop".

And this is the test case 2.46 in AVS_functional_self-test_checklist_v1_7.xlsx.
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bill-lzb** [comment]
[avs-log.txt](https://github.com/alexa/avs-device-sdk/files/2648537/avs-log.txt)

I attached the log file, and there are some errors.
1,After I said "Alexa, set a time for 1 minute", the DialogUXState changed to speaking, but no sound is played.
The following errors maybe related to the problem.
-----
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.163 [  b] 9 AlertsCapabilityAgent:handleSetAlert
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] E JsonUtils:lookupArrayExistsFailed:reason=keyNotFound,key=assets
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] 0 Alert:parseAlertAssetConfigurationFromJson : assets are not present.
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] E JsonUtils:lookupArrayExistsFailed:reason=keyNotFound,key=assetPlayOrder
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] 0 Alert:parseAlertAssetConfigurationFromJson : asset play order is not present.
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=loopCount
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] 0 Alert:parseAlertAssetConfigurationFromJson : loop count is not present.
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=loopPauseInMilliSeconds
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] 0 Alert:parseAlertAssetConfigurationFromJson : loop pause in milliseconds is not present.
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] E JsonUtils:findNodeFailed:reason=missingDirectChild,child=backgroundAlertAsset
Dec 05 10:55:45 m3ulcb avs-service-app[4687]: 2018-12-05 10:55:45.164 [  b] 0 Alert:parseAlertAssetConfigurationFromJson : backgroundAssetId is not present.
-----

2, When it was playing music, the timer went off, the alert sound for the timer did not alert.
the logs related to this is start from about line 3138.

Thanks,
ZongbiaoLiao

**Comment by visayamv** [comment]
Hi @bill-lzb , It seems from the logs:

`
Dec 05 10:56:14 m3ulcb avs-service-app[4687]: 2018-12-05 10:56:14.374 [ 2f] 1 Renderer:executeOnPlaybackStarted:sourceId=8
Dec 05 10:56:14 m3ulcb avs-service-app[4687]: 2018-12-05 10:56:14.374 [ 2f] 1 Alert:onRendererStateChange:state=STARTED,reason=,m_hasTimerExpired=false,m_dynamicData.state=ACTIVATING
`

that the timer you scheduled is sounding...

If you're not playing music, does your scheduled timer sound properly?

Can you also check if your Alerts volume is set to a high value?

**Comment by bill-lzb** [comment]
Hi visayamv

if it is not playing music, the scheduled timer sound properly.
And the alerts volume is set to 100.

And one more problem.
when I said "set a timer for 1 minute", Alexa should response "one minute, starting now.", then the timer was set.
But when I said "set a timer for 1 minute", the DialogUXState changed to Speaking, but no sound was output, and from the Alexa app I can confirm that the timer was set.

Thank you,
ZongbiaoLiao

**Comment by visayamv** [comment]
Hi @bill-lzb , can you check if adding a dmix plugin will help? Please refer to https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide under the Linux section issue "Can't play more than one sound simultaneously". Thanks

**Comment by bill-lzb** [comment]
Hi visayamv

I failed to add dmix plugin.
Is this problem related to the following error messages?

2018-12-11 03:16:07.702 [  1] I sdkVersion: 1.9.0
configFile /data/avs-device-sdk/config/AlexaClientSDKConfig_cbl.jsonKConfig.json
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.front.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround51.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround51.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround40.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround51.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround51.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround51.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.surround71.0:CARD=0'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib ../../alsa-lib-1.1.3/src/confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.rsnd-dai_0-ak46.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib ../../alsa-lib-1.1.3/src/conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib ../../../alsa-lib-1.1.3/src/pcm/pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline

**Comment by bill-lzb** [comment]
Hi kclhan

After configuring ~/.asoundrc as following, the problem was resoved.
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "dmixer"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

pcm.dmixer {
  type dmix
  ipc_key 1024
  slave {
    pcm "hw:0,0"
    period_time 0
    period_size 1024
    buffer_size 8192
  }
  bindings {
    0 0
    1 1
  }
}

ctl.dmixer {
  type hw
  card 0
}

Thank you!
