### ISSUE TITLE
iHeartRadio channels

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#110]
I can play some live radio stations from iHeartRadio , like soft rock , kiss FM.

However , none of the shows work , are they not supported for 1.0.1 release ?

**Comment by kjkh** [comment]
Hi, 

Do you have an example of a show that isn't working?

**Comment by shikha-bansal** [comment]
Alexa play Hip-Hop from IHeartRadio.

Response  : sorry I can't find the station you requested

**Comment by kjkh** [comment]
I tried this command with local debug logs on and saw that aside from the Speech Directive sent ("Sorry, I can't find the station you requested"), AVS is not sending a directive to play any media. This doesn't appear to be an issue related to the SDK itself.

Is "Hip-Hop" a valid channel?

**Comment by shikha-bansal** [comment]
yes it is valid show. I get the name by going to iHeartRadio on alexa.amazon.com. select shows, entertainment. Hip-Hop is the first show listed.
Between this issue is not limited to just this show. I can't get to hear any show.

**Comment by kjkh** [comment]
Ah I see. I was able to get it working with "iHeartRadio program _\<show name\>_". For example, there is a show called _A Piece of Work_, and the latest episode was played with the command:

"iHeartRadio program A Piece ofWork".

Similarly, this worked with _Alien Minute_. 

Manually playing the show _#Hip-Hop_ from alexa.amazon.com worked, and the AVS Sample App I have running received the correct URL and Play Directive. However, I had troubles with verbally getting the program to play by saying "iHeartRadio program hashtag hip hop". 

Hope this helps!

**Comment by kjkh** [comment]
Closing issue. Feel free to re-open if you have further questions.
