### ISSUE TITLE
Error "Failed to create to SampleApplication!"

### ISSUE THREAD

**Issue by Sinsambin** [alexa/avs-device-sdk#1101]
Briefly summarize your issue:
I think it is a bug cause there is a error and it says "Failed to create to SampleApplication!"

What is the expected behavior?
When i run the failed command "Not Yet Authorized" should pop up.

What behavior are you observing?
I was running the command "sudo bash startsample.sh". Many codelines came up (Screenshot below) and then i recieved "Failed to create to SampleApplication!".

Provide the steps to reproduce the issue, if applicable:
I followed the guide. After the run of "sudo bash startsample.sh" the error came up.

I use version 1.10.0 of SDK  

Hardware:
Raspberry Pi (Used via SSH Connection, but it would be possible via mouse, keyboard and monitor)
![errorraspi_2](https://user-images.githubusercontent.com/36137659/49206012-009f4900-f3b1-11e8-9854-ac30722cb880.JPG)
![errorraspi_3](https://user-images.githubusercontent.com/36137659/49206014-009f4900-f3b1-11e8-8319-a4db21dd1698.JPG)
![errorraspi_4](https://user-images.githubusercontent.com/36137659/49206016-009f4900-f3b1-11e8-8cd7-b085bc5aea46.JPG)
![errorraspi_1](https://user-images.githubusercontent.com/36137659/49206017-009f4900-f3b1-11e8-95f1-97fcd1d72c3e.JPG)

OS:
Raspbian Stretch 4.14.79-v7+

**Comment by Sinsambin** [comment]
Resolved

**Comment by Raiv3n** [comment]
How did u solved it? I occour the same problem
