### ISSUE TITLE
Question - will system date/time impact AVS service ?

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1102]
Hi AVS team,

Just a question here, if the system date/time is incorrect (eg. 1970/01/01, or future date), will it cause AVS services abnormal or failed ?
I tried it and it looks fine and it seems only log system will be impacted ?

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang, 

You will have problem with Alerts and some certificates might not work if the date is wrong.
