### ISSUE TITLE
Feature questions

### ISSUE THREAD

**Issue by rdoebler** [alexa/avs-device-sdk#1103]
## Briefly summarize your issue:
Not a bug, just a question:

On the previous alexa-sample-app you said the Wakeword, Alexa, you would get a tone feedback indicating that it heard you and is listening for the question/command. Is there anything like this on the SDK? I liked having that feedback. 

Thanks!

### What version of the AVS Device SDK are you using?
      
![image](https://user-images.githubusercontent.com/8881529/49222694-8d92d400-f3aa-11e8-87ca-48badaec6805.png)

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by celinval** [comment]
Hi @rdoebler,

Thanks for asking. Our SDK currently does not support wake word notification. It's in our radar though.

Best,
Celina
