### ISSUE TITLE
Running `cmake clang-format doxygen` during installation results in error

### ISSUE THREAD

**Issue by Eptin** [alexa/avs-device-sdk#1104]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I've previously installed the Device SDK on my computer, but this time I deleted the sdk-folder and am starting over. I'm following the [macOS Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide).

## What is the expected behavior?
Should be able to follow every step in the macOS Quick Start Guide and result in a functioning Device SDK sample app.

## What behavior are you observing?
Starting from inside the sdk-folder, when I run the command `cmake clang-format doxygen`, I get the following error: `CMake Error: The source directory "/Users/micinnes/sdk-folder/doxygen" does not exist.`

## Provide the steps to reproduce the issue, if applicable:
Create the folders (`mkdir sdk-folder`, etc)
`cd ~/sdk-folder`
`brew update`
`brew upgrade curl --with-nghttp2`
`brew link curl --force`
`brew upgrade gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav sqlite3 repo`
`cmake clang-format doxygen`

## Tell us about your environment:
I'm on a MacBook Pro 2015 with High Sierra (macOS 10.13.6)
`export PATH="/usr/local/opt/curl/bin:$PATH"` has already been added to `~/.bash_profile` many times over.

### What version of the AVS Device SDK are you using?
version 1.10

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X] MacOS 10.13.6
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Widea** [comment]
+1. I am running into the same issue.

**Comment by Widea** [comment]
Just realized, this might be a single sentence, 


brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav sqlite3 repo
cmake clang-format doxygen

so we just need to run a brew install cmake clang-format doxygen

**Comment by Widea** [comment]
@celinval would it possible to update the document, or add a note to ensure this is more clear for the next person. Thank you.

**Comment by celinval** [comment]
Thanks for asking, @Widea.

We are going to update the doc. This was a mistake that we made on our side. The document is incorrect.

**Comment by visayamv** [comment]
Hi @Widea , the doc has been corrected. Thanks for reporting this in.
