### ISSUE TITLE
No sound output

### ISSUE THREAD

**Issue by haliburt** [alexa/avs-device-sdk#111]
After installing everything on rasbian stretch I can no longer output any sound. I've modified the .asoundrc file, forced audio through the 3.5mm jack still nothing.

**Comment by kencecka** [comment]
Hi Sean,

Can you provide a few more details on what you have tried and what you are observing?

- Are you able to play sound through other applications such as aplay?
- Is the speaker icon in the taskbar at the top of the screen active or crossed out?
- If it is active, and you right-click on it, what output options are listed at the top of the pop-up menu, and which one has a check mark?
- What are the contents of your .asoundrc?
- If other applications are working, and you are only having trouble with the SDK, can you run the SDK with DEBUG9 logging and copy the logging here?

Ken
