### ISSUE TITLE
The installation script doesn't support current system. (System: Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

### ISSUE THREAD

**Issue by xuyongqing9527** [alexa/avs-device-sdk#1113]
root@ubuntu:/home/arnold/avs# sudo bash setup.sh config.json -s 123456
The installation script doesn't support current system. (System: Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
MTK(android8.1) paltform 
PLATFORM="android"
API_LEVEL="27"
TARGET_SYSTEM="arm"
DEVICE_INSTALL_PATH="/data/app/avs"
BUILD_TYPE="release"

**Comment by celinval** [comment]
Hi @xuyongqing9527,

That's our bad. The android quick start guide is  wrong and we are going to updated. The correct command is:
```
sudo bash setup.sh config.json -a androidConfig.txt -s 123456
```
Please let me know if that works for you.

**Comment by kameshkancherla** [comment]
bash -x setup.sh config.json -a androidConfig.txt -s deviceName

**Comment by xuyongqing9527** [comment]
Hi celinval：
  Thanks a lot ！

**Comment by xuyongqing9527** [comment]
Hi kameshkancherla:
    Thanks a lot ！

**Comment by kclchan** [comment]
Hi @xuyongqing9527, seems you were able to get the answer you need.  I'm going to close this issue now.  Thanks for reaching out to use.
