### ISSUE TITLE
Where does avs-device-sdk source code fit into Android source code?

### ISSUE THREAD

**Issue by xuyongqing9527** [alexa/avs-device-sdk#1114]
MTK platform (Android source is Android8.1.0)
Where does avs-device-sdk source code fit into Android source code?
Thanks!

**Comment by celinval** [comment]
Hi @xuyongqing9527, I'm not sure what you mean. The avs-device-sdk has a sample application that can be run on Android. You can also create your own application that uses the avs-device-sdk to use Alexa on Android.

**Comment by xuyongqing9527** [comment]
Hi celinval:
 Thank you!

**Comment by kclchan** [comment]
Hi @xuyongqing9527, seems you were able to get the answer you need.  I'm going to close this issue now.  Thanks for reaching out to use.
