### ISSUE TITLE
There is an error  when i cross compile  the AVS Device SDK for ARM Devices in Linux system.

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1115]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

My arm device  doesn't has  microphone，the audio  input to the device through bluetooth headset .
So i set the build option -DBLUETOOTH_BLUEZ=ON.
What  Bluetooth dependencies  do i  need to install for the arm device.

Error information:
In file included from /home/xxw/xuxuewen/work/alexa_for_android/script/avs-device-sdk/BluetoothImplementations/BlueZ/src/BlueZA2DPSource.cpp:20:
In file included from /home/xxw/xuxuewen/work/alexa_for_android/script/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/MediaEndpoint.h:29:
/home/xxw/xuxuewen/work/alexa_for_android/script/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/MediaContext.h:19:10: fatal error: 'sbc/sbc.h' file not found
#include <sbc/sbc.h>
         ^~~~~~~~~~~
1 error generated.
make[3]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/BlueZA2DPSource.cpp.o] Error 1
make[2]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/all] Error 2

### What version of the AVS Device SDK are you using?
      <1.10>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more: arm linux

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @xuewenxu , it maybe missing the SBC library.

For Linux systems, you can install it using the command:
 
sudo apt-get install libsbc-dev

**Comment by xuewenxu** [comment]
Hi @visayamv 
Thanks for your response, but my devices is embedded devices  and it can't use apt-get install SBC library.

**Comment by visayamv** [comment]
Hi @xuewenxu , please refer to [SBC repository](https://git.kernel.org/pub/scm/bluetooth/sbc.git/tree/) on how to build it

**Comment by visayamv** [comment]
Hi @xuewenxu , I will be closing this issue. Feel free to reopen if you have any further inquiries regarding this.
