### ISSUE TITLE
Template card not close when interrupt situation

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1116]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, 
I am checking the template card implement.
I notice that template card was not cancelled in two situation:
1. [Card to NowPlaying](https://developer.amazon.com/docs/alexa-voice-service/display-cards-tvs.html#card-to-nowplaying)
2. [NowPlaying to Card](https://developer.amazon.com/docs/alexa-voice-service/display-cards-tvs.html#nowplaying-to-card)

When I run SampleApp with debug0 level, I can not get the template card cleared callback.
In debug9 level, this issue does not happen.

Here is the log,
[log_region.TXT](https://github.com/alexa/avs-device-sdk/files/2652404/log_region.TXT)

In the log, it has two part:
1. Card to NowPlaying
2. NowPlaying to Card

You can see the TemplateRuntime name to track this issue.

## What is the expected behavior?

In SampleApp, it will show "RenderTemplateCard - Cleared" message when dialog going back idle.  

## What behavior are you observing?

Not shown "RenderTemplateCard - Cleared" message when dialog going back idle.

## Provide the steps to reproduce the issue, if applicable:

A. Card to NowPlaying
     1. Run the SampleApp with debug0
     2. Ask Alexa weather
     3. When Alexa is speaking, ask Alexa play iHeartRadio or another MSP.

B. NowPlaying to Card
    1. Run the SampleApp with debug0
    2. Play iHeartRadio or another MSP.
    3. Ask alexa weather

### What version of the AVS Device SDK are you using?
      <1.10.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: arm-linux embedded system

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

I think that the timer is cancelled by now playing card activity.
I try to modify the code about using clear card function.
Here is the code,
[TemplateRuntime.txt](https://github.com/alexa/avs-device-sdk/files/2652545/TemplateRuntime.txt)
I hope this will help to you

**Comment by visayamv** [comment]
Hi @elfdie00475 , I may not have understood the problem correctly, can you help clarify? Do you mean after step 3 above, it is expected to have a RenderTemplateCard-Cleared message when the music is playing? Or do you mean that after the weather utterance, and device switched to playing music, it should have RenderTemplateCard-Cleared message before it shows the RenderTemplateCard for the playing music?

**Comment by visayamv** [comment]
Hi @elfdie00475 , can you also provide the debug9 case where you can see the RenderTemplateCard-Cleared message? Thanks.

**Comment by elfdie00475** [comment]
Hi @visayamv, 

Here is the log,
[log_region_debug9.TXT](https://github.com/alexa/avs-device-sdk/files/2662033/log_region.TXT)

I try the issue with debug9 log, it can see the message in card to now playing case.
But, now playing to card  case still does not have the message.

So, you can see only one message in the log.

Thanks for help

**Comment by kclchan** [comment]
Hi @elfdie00475, from the log_region_debug9.txt, I am not entirely clear what's the issue.  The reason why it didn't show "RenderTemplateCard - Cleared" is because after showing the weather, the TemplateRuntime start showing the MSP again, and that's why there's no need to "RenderTemplateCard - Cleared"

**Comment by elfdie00475** [comment]
Hi @kclchan,
I think that I can understand what you say.

I watch the document of TemplateRuntime again. The AVS server only tell us what kind of template need to show on, but it does not tell us how to close the template.
So, the way about closing the template implement by coding designer.

In the begin, I think that the behavior of the template function is "Show template, close template. Show now playing, close now playing".
Please close this problem if your behavior is not my think.
I will find some workaround to handle it.

Thanks~~

**Comment by kclchan** [comment]
Hi @elfdie00475, please feel free to reach out to us if you need further clarification.  I am closing this issue now.  Thanks!
