### ISSUE TITLE
Can you please tell If i would like to integrate this SDK into my iOS application.

### ISSUE THREAD

**Issue by KrishCompusoft** [alexa/avs-device-sdk#1117]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @KrishCompusoft , I'm not sure what you mean, but if you mean you want to run compile Alexa SDK for IOS, you can refer to this related issue: https://github.com/alexa/avs-device-sdk/issues/837 . Thanks
