### ISSUE TITLE
Mic error after running AVS SDK on android

### ISSUE THREAD

**Issue by kameshkancherla** [alexa/avs-device-sdk#1120]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Microphone able to identify the voice but when it is speaking, I am not getting the voice out side.
## What is the expected behavior?

Speaking is executing but there in no audio
###########################
#       Speaking...       #
###########################

2018-12-08 10:59:00.538 [  7] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-12-08 10:59:00.538 [  7] E FFmpegDecoder:decode::readFrameFailed:error=tryAgain
2018-12-08 10:59:00.549 [  7] E FFmpegDecoder:readDecodedFrameFailed:error=tryAgain

### What version of the AVS Device SDK are you using?
      New Version of AVS on Android.

### Tell us what hardware you're using:

- Respeaker Core V2.0

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
- Android Ore 8.0

**Comment by kameshkancherla** [comment]
2018-12-08 10:58:15.755 [  1] E AndroidMicrophone:configureRecognizeModeFailed:reason=cannot set configuration,result=2
2018-12-08 10:58:15.755 [  1] W AndroidSLESEngine:Failed to set Recognize mode. This might affect the voice recognition.
2018-12-08 10:58:15.755 [  1] I AndroidMicrophone:startStreamingMicrophoneData

**Comment by kclchan** [comment]
Hi @kameshkancherla, it would be useful to get the Android log to understand more on why this is failing.  Could you do the following?
```
adb logcat 
```
Thanks!

**Comment by kameshkancherla** [comment]
Thank you for reply.

Please find attachment.

Regards
Vithal
________________________________

**Comment by kameshkancherla** [comment]
I recorded some voice and played using with tinyplay a.wav -d 0 p 1 I am able to hear the voice from Jack.


Regards
Vithal

**Comment by kclchan** [comment]
Hi @kameshkancherla, I have looked into this a bit more, the error with AndroidMicrophone:configureRecognizeModeFailed shouldn't be the cause of the issue you are seeing as we try to configure the microphone to use a recognize configuration to improve voice capture, but it is not necessary.  Just to make sure, could you go to https://alexa.amazon.com/spa/index.html#settings/dialogs with your credential and see if your utterance are being detected?  If you see your utterance, then it means your microphone is working properly.
Also, could you attached the DEBUG9 log, this could help with narrowing down the cause of the issue you are seeing.  Thanks!

**Comment by kameshkancherla** [comment]
sorry for this question, where can I find DEBUG9 log file, I didnt find any where.

In..between this is the error which I am seeing.

###########################
#       Thinking...       #
###########################

2018-12-11 20:00:36.771 [  2] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"SetEndOfSpeechOffset"\,messageId\:"e737a6e4-8ae3-4fd3-b317-c2d074a19ff5"\,dialogRequestId\:"0ffc75ed-fc45-4711-84c5-ff0aa14370bc"}
2018-12-11 20:00:36.772 [  3] I DirectiveRouter:preHandleDirective:messageId=e737a6e4-8ae3-4fd3-b317-c2d074a19ff5,action=calling
2018-12-11 20:00:36.772 [  4] I DirectiveRouter:handleDirective:messageId=e737a6e4-8ae3-4fd3-b317-c2d074a19ff5,action=calling
2018-12-11 20:00:36.773 [  4] E JsonUtils:convertToInt64ValueFailed:reason=invalidValue,expectedValue=Int64
2018-12-11 20:00:36.774 [  2] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"0769cef3-aab6-443a-9c70-b2e3eeb36445"\,dialogRequestId\:"0ffc75ed-fc45-4711-84c5-ff0aa14370bc"}
2018-12-11 20:00:36.774 [  3] I DirectiveRouter:preHandleDirective:messageId=0769cef3-aab6-443a-9c70-b2e3eeb36445,action=calling
2018-12-11 20:00:36.775 [  4] I DirectiveRouter:handleDirective:messageId=0769cef3-aab6-443a-9c70-b2e3eeb36445,action=calling
2018-12-11 20:00:36.780 [  2] I DirectiveSequencer:onDirective:directive={"namespace\:"TemplateRuntime"\,name\:"RenderTemplate"\,messageId\:"bc681295-192e-4931-a67b-987eb8016e59"\,dialogRequestId\:"0ffc75ed-fc45-4711-84c5-ff0aa14370bc"}
2018-12-11 20:00:36.781 [  3] I DirectiveRouter:handleDirectiveWithPolicyHandleImmediately:messageId=bc681295-192e-4931-a67b-987eb8016e59,action=calling
##############################################################################
#     RenderTemplateCard
#-----------------------------------------------------------------------------
# Focus State         : FOREGROUND
# Template Type       : WeatherTemplate
# Main Title          : Hadern, Deutschland
##############################################################################

###########################
#       Speaking...       #
###########################

2018-12-11 20:00:51.244 [  7] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-12-11 20:00:51.245 [  7] E FFmpegDecoder:decode::readFrameFailed:error=tryAgain
2018-12-11 20:00:51.251 [  7] E FFmpegDecoder:readDecodedFrameFailed:error=tryAgain


Error after speaking

Regards
Vithal

**Comment by kclchan** [comment]
Hi @kameshkancherla, yes this is the log we are looking for.  But unfortunately, it seems you are running a release build instead.  To change, in your androidConfig.txt  file, could you specify BUILD_TYPE to debug, and then delete your build directory and rerun the setup.sh again?  This should give us a more verbose output.  Thanks!

**Comment by kameshkancherla** [comment]
I changed the config.txt from release to debug. I ran the setup.sh and I am getting this error now.

vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alexa/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libsqlite3.so" not found
Aborted

**Comment by kameshkancherla** [comment]
when I run the program in Debug mode, I missed all these files.

vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libavcodec.so" not                                                                                         found
Aborted
vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libavutil.so" not f                                                                                        ound
Aborted
vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libavformat.so" not                                                                                         found
Aborted
vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libswresample.so" n                                                                                        ot found
Aborted
vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libssl.so.1.1" not                                                                                         found
Aborted
vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alex                                                                                        a/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libcrypto.so.1.1" n                                                                                        ot found
Aborted

Regards
Vithal

**Comment by kclchan** [comment]
Hi @kameshkancherla, looks like the /data/alexa/lib path is not created properly.  Could you refer to #968 and see if it helps?

**Comment by kameshkancherla** [comment]
i did that twice but in..between how to pull the debug log.

Regards
Vithal
________________________________

**Comment by kameshkancherla** [comment]
Hi,

ADB version.

vithal@linux:~$ adb version
Android Debug Bridge version 1.0.36
Revision 1:7.0.0+r33-2

If I change androidConfig.txt to debug, I saw that files itself not generation, huge difference in release and debug.


vithal@linux:~$ bash -x startsample.sh
+ adb shell LD_LIBRARY_PATH=/data/alexa/lib /data/alexa/bin/SampleApp /data/alexa/AlexaClientSDKConfig.json DEBUG9
CANNOT LINK EXECUTABLE "/data/alexa/bin/SampleApp": library "libsqlite3.so" not found

vithal@linux:~$ adb shell ls /data/alexa
AlexaClientSDKConfig.json
bin
cacert.pem
databases
lib
vithal@linux:~$ adb shell ls /data/alexa/lib
libACL.so
libADSL.so
libAFML.so
libAIP.so
libAVSCommon.so
libAVSSystem.so
libAlerts.so
libAndroidSLESMediaPlayer.so
libAndroidUtilities.so
libAudioPlayer.so
libAudioResources.so
libBluetooth.so
libCBLAuthDelegate.so
libCapabilitiesDelegate.so
libCertifiedSender.so
libContextManager.so
libDefaultClient.so
libESP.so
libEqualizer.so
libEqualizerImplementations.so
libExternalMediaPlayer.so
libInteractionModel.so
libKWD.so
libMRM.so
libNotifications.so
libPlaybackController.so
libPlaylistParser.so
libRegistrationManager.so
libSQLiteStorage.so
libSettings.so
libSpeakerManager.so
libSpeechSynthesizer.so
libTemplateRuntime.so
libc++_shared.so
vithal@linux:~$ cd /home/vithal/debug/android-27/armeabi-v7a/install/lib

vithal@linux:~/debug/android-27/armeabi-v7a/install/lib$ ls
libACL.so                     libAndroidUtilities.so  libCapabilitiesDelegate.so  libEqualizerImplementations.so  libMRM.so                  libSpeakerManager.so
libADSL.so                    libAudioPlayer.so       libCBLAuthDelegate.so       libEqualizer.so                 libNotifications.so        libSpeechSynthesizer.so
libAFML.so                    libAudioResources.so    libCertifiedSender.so       libESP.so                       libPlaybackController.so   libSQLiteStorage.so
libAIP.so                     libAVSCommon.so         libContextManager.so        libExternalMediaPlayer.so       libPlaylistParser.so       libTemplateRuntime.so
libAlerts.so                  libAVSSystem.so         libc++_shared.so            libInteractionModel.so          libRegistrationManager.so
libAndroidSLESMediaPlayer.so  libBluetooth.so         libDefaultClient.so         libKWD.so                       libSettings.so



if the code is changed to release , these are files getting created.

vithal@linux:~$ adb shell ls /sdcard/Download/alexafiles
AlexaClientSDKConfig.json
cacert.pem
libACL.so
libADSL.so
libAFML.so
libAIP.so
libAVSCommon.so
libAVSSystem.so
libAlerts.so
libAndroidSLESMediaPlayer.so
libAndroidUtilities.so
libAudioPlayer.so
libAudioResources.so
libBluetooth.so
libCBLAuthDelegate.so
libCapabilitiesDelegate.so
libCertifiedSender.so
libContextManager.so
libDefaultClient.so
libESP.so
libEqualizer.so
libEqualizerImplementations.so
libExternalMediaPlayer.so
libInteractionModel.so
libKWD.so
libMRM.so
libNotifications.so
libPlaybackController.so
libPlaylistParser.so
libRegistrationManager.so
libSQLiteStorage.so
libSettings.so
libSpeakerManager.so
libSpeechSynthesizer.so
libTemplateRuntime.so
libavcodec.so
libavdevice.so
libavfilter.so
libavformat.so
libavutil.so
libc++_shared.so
libcrypto.a
libcrypto.so
libcrypto.so.1.1
libcurl.la
libcurl.so
libnghttp2.a
libnghttp2.la
libsqlite3.la
libsqlite3.so
libssl.a
libssl.so
libssl.so.1.1
libswresample.so
libswscale.so



Regards
Vithal
________________________________

**Comment by kameshkancherla** [comment]
Can any one assist me further to debug this Mic issue

Regards
Vithal

**Comment by celinval** [comment]
Hi @kameshkancherla,

Can you please run the following commands:
```
ls /home/vithal/debug/android-27/armeabi-v7a/
ls /home/vithal/debug/android-27/armeabi-v7a/sqlite3/
cat /home/vithal/debug/android-27/armeabi-v7a/sqlite3/sqlite3.pc
```

Thanks,
Celina

**Comment by kameshkancherla** [comment]
Hi Celina,

I didnt find the file sqlite3.pc.

vithal@linux:~$ cd /home/vithal/debug/android-27/armeabi-v7a/
vithal@linux:~/debug/android-27/armeabi-v7a$ ls -ltr
total 4
drwxrwxr-x 4 vithal vithal 4096 Dec 11 22:04 install
vithal@linux:~/debug/android-27/armeabi-v7a$


Regards
Vithal

________________________________

**Comment by kameshkancherla** [comment]
Hello Celina,

Do you have any update for me.

Regards
Vithal
________________________________

**Comment by kameshkancherla** [comment]
Hi Team,

I found the issue, kindly help me how to fix the problem.

When Alexa sending the voice it is redirecting to PCMC1D0P, when we verified with tinyplay it was picking up PCMC0D1P.

How can i redirect my Alexa voice to PCMC0D1P.
Regards
Vithal

**Comment by kameshkancherla** [comment]
Existing code is written for Android and debain to use PCMC1D0p as a sound card but on android of respeaker it is actually PCMC0D1P, kindly help me how to change this.

**Comment by kameshkancherla** [comment]
This code is designed to work on USB as audio not audio Jack.
