### ISSUE TITLE
Cannot setup reminders and routines on Amazon devices like Echo similar to Amazon Companion App

### ISSUE THREAD

**Issue by rajeev47billion** [alexa/avs-device-sdk#1131]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

 I cannot configure reminders and routines on Amazon Echo devices using this SDK.
## What is the expected behavior?

This SDK should allow me to see all Alexa devices on my account (custom as well as Amazon Echo devices), select one and set reminders and routines similar to what Amazon companion app does.
## What behavior are you observing?

It seems this functionality is not exposed in SDK. If I have my custom device along with Amazon device. There is no way for me to write a custom companion app to control both types of devices without this functionality. I have to use companion app for Echo and custom app for my device.
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [X] Other - tell us more:
Amazon Echo and Raspberri Pi

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello rajeev47billion,

I just verified with that I could use the standard `Amazon Alexa` app on my Android phone to create a routine and an alarm that are both played by an instance of SampleApp that I am running locally.  

I am using the `Amazon Alexa` app version 2.2.248063 and the 1.10 version of the SDK.

To create a `Routine` I did the following:
- Press `Home` icon on the bottom left of the screen
- Press the three horizontal lines at the top left of the screen
- Pressed Routines
- Select `Your Routines` tab
- Select the circled `+` at the top right of the screen
- Select the circled `+` to the right of "When this happens"
- Selected schedule (skipping details of setting the time/schedule)
- Select the back arrow at top left of the `When this happens` screen
- Select the circled `+` to the right of `Add action`
- Select `Alexa says`
- Select `Tell me a joke`
- Select `ADD`
- At the bottom of the `NEW ROUTINE` screen near the bottom under `From` select the device corresponding to my SampleApp
- Select `Save`
- Wait for the scheduled time to hear a joke

To set an alarm on my SampleApp I did the following:
- Press `Home` icon on the bottom left of the screen
- Press the three horizontal lines at the top left of the screen
- Select `Reminders and Alarms`
- At the top middle of the screen (above `ALARMS` select the device corresponding to my SampleApp (note, your SampleApp needs to be on-line)
- Select the circled `+` at the top right of the `Add Alarm`
- Specify the time for the alarm (skipping those details)
- Select `Save`
- Wait for the scheduled time to observe the alarm

Perhaps I do not understand what you are asking for.  It seems like you may be asking to create a custom companion app that will handle both.  If so, I am sorry, but I am not aware of an SDK for creating companion apps that interact with Alexa services to drive behavior on devices.

Best regards,
-SWH

**Comment by rajeev47billion** [comment]
Hi @scotthea-amazon 

Thanks for the reply.

My question is related to custom companion app to setup reminder and routines on Amazon Echo or other custom devices. Are there any functions in SDK that we can use or a documented API that Amazon Alexa Companion App uses to setup routines and reminders on Echo devices? We would like to use them in our custom companion app. If not, is there any plan to open up these APIs to Alexa device developers (particularly for Alexa for business).

regards,
Rajeev

**Comment by scotthea-amazon** [comment]
Hi Rajeev,

I am not aware of any such APIs.

Here is a form you can use to [create a feature request](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).  Please include a description of that you are trying to accomplish.  If you provide contact information there we may contact you to get further details about your request.

Thank you,
-SWH

**Comment by visayamv** [comment]
Hi @rajeev47billion , were you able to get the answers you were seeking?

**Comment by visayamv** [comment]
Hi @rajeev47billion , I'm closing this issue but feel free to reopen if you have further questions on this.
