### ISSUE TITLE
Interrupt the thinking state and then go to the listening state.

### ISSUE THREAD

**Issue by liunanxuan** [alexa/avs-device-sdk#1132]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We want Amazon to tell you how to interrupt the thinking state and then go to the listening state.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by scotthea-amazon** [comment]
Hello liunanxuan,

Interrupting the `Thinking` state is not something we currently support.  When `Thinking` is in progress, the SDK's AudioInputProcessor explicitly prevents barge-in, as per the AVS
[SpeechRecognizer specification](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#states).

Hope that helps,
-SWH

**Comment by liunanxuan** [comment]
Thanks for your support. But we can see that your company's product Echo device can support this behavior.

**Comment by scotthea-amazon** [comment]
Hello liunanxuan,

Perhaps I am not understanding what you are asking for.  Can you give me a step by step example of what you are experiencing with an Echo product that you can not replicate with the SDK?

Thank you,
-SWH

**Comment by liunanxuan** [comment]
We want to achieve this behavior in order to improve the user experience.
Voice: alexa.what is the weather like?
State:IDLE ->RECOGNIZING
AVS: StopCapture directive
State:RECOGNIZING -> BUSY
In the BUSY state, the voice wakes up "alexa" again. We hope to interrupt the last voice conversation and reopen a new round of voice conversations.

**Comment by liunanxuan** [comment]
Thanks for your support.

We see that the ECHO setting can support the behavior I described above.

**Comment by scotthea-amazon** [comment]
Hello liunanxuan,

I have not been able to reproduce the behavior you describe on my Echo.  When I interrupt the Echo's flashing blue `busy` state with `Alexa` it seems be ignored.  However, often when I attempt this, Alexa responds quickly enough that speaking `Alexa` overlaps the start of the response and truncates it, allowing my subsequent utterance to be processed.

I get the sense that I am still missing something.  Maybe if you provide an audio recording of the interaction with an Echo that you want to achieve, I will better understand what you are asking for.

Thank you,
-SWH

**Comment by liunanxuan** [comment]
Thanks for your support.
It seems that standard authentication does not support think interrupts.

Thank you very much for your answer.

**Comment by jan4984** [comment]
Is there any difficult allowing cancel a recolonization in THINKING state?
