### ISSUE TITLE
How to De-Register device from AMAZON Account in AVSSDKV1.10

### ISSUE THREAD

**Issue by ShivaKrishnaCharka** [alexa/avs-device-sdk#1134]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, I would like to de-register the device from amazon account. But when i do de-register in the web, i am not getting any communication to the AVS SDK. We have enabled the debug logs in SampleAPP, but it is not showing any prints, when the device is de-registered.
## What is the expected behavior?

We should get some communication to the AVS SDK, when device is de-registered, so that we can shutdown the app?
## Provide the steps to reproduce the issue, if applicable:

Run the SampleApp, and go to the amazon account and de-register your device.
### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK V 1.10
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ShivaKrishnaCharka** [comment]
Hi, We would like to de-register the device from amazon account. When we de-register, we need to delete the database and re-authorize the device. But we are not seeing any prints or state change when de-registered on Amazon Account. (DEBUG9)

Do we need to enable any flags, to get the communication from Account to AVS SDK ?

Please suggest.

**Comment by scotthea-amazon** [comment]
Hello ShivaKrishnaCharka,

Thank you for your question.  No special flags are needed to enable this notification.

What version of the SDK are you using?  1.10 was enhanced to infer de-authorization by providing notification through [AuthObserverInterface::onAuthStateChange()](https://github.com/alexa/avs-device-sdk/blob/v1.10/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/AuthObserverInterface.h#L91) with a status of [AUTHORIZATION_EXPIRED](https://github.com/alexa/avs-device-sdk/blob/v1.10/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/AuthObserverInterface.h#L62).

Note that this notification may not be immediate.  The client only discovers that it has been de-registered when making a request to AVS fails with a 403 and subsequent attempts to refresh the authorization token indicate that the refresh token is invalid.  So, for example, if the client is not actively interacting with AVS it may take about five minutes for the failure of a keep-alive ping to AVS to trigger this notification.

Best regards,
-SWH

**Comment by visayamv** [comment]
Hi @ShivaKrishnaCharka , I hope that answers your question. I'll be closing down this thread but feel free to reopen if you have other questions regarding this.
