### ISSUE TITLE
ALEXA responding to Wake Up Word ¨ ALEXA¨

### ISSUE THREAD

**Issue by bassem111** [alexa/avs-device-sdk#1135]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bassem111** [comment]
Everything working fine except not responding to Wake Up Word ¨ ALEXA¨
After starting the app, it initialises and comes to the #Alexa is currently idle!# state. Here it should respond to the Wake up word.
It does NOT respond to ALEXA. However, it responds nicely to the t+ENTER key input ...I can make all queries.
any help???﻿

**Comment by frivas** [comment]
Hello @bassem111 I just commented here #1108 I am having the very same issue.

**Comment by bassem111** [comment]
hi @scotthea-amazon i have tested my audio device and it work correctly i am using : 

usb Microphone and Speaker through a jack 3.5mm 
tested them with "arecord --format cd --duration 10 --channels 1 test.wav" then "omxplayer -o alsa test.wav" and everything work fine 
and about the SDK version i think that it's the lastest 
and i have following this step from this site "https://developer.amazon.com/docs/alexa-voice-service/input-avs-credentials.html "
also i dont know how to give you more information about wake-word engine, and some DEBUG9 level logs i am sorry 
and thanks for your help

**Comment by bassem111** [comment]
thank you , the problem is solved now i just reinstall it for the 3rd time and it's work now :D

**Comment by frivas** [comment]
That is not a solution. The behaviour has to be consistent: it has to work all the time. Please, do not close the issue, I will provide logs later on, this needs further investigation.

Thank you very much

**Comment by dhpp** [comment]
Hi @frivas - did you follow the advice given here : 

https://github.com/alexa/avs-device-sdk/issues/1108#issuecomment-452587002 

which appeared to solve the issue in that other ticket?

**Comment by samcoult** [comment]
Closing this issue as the original poster's issue appears to be fixed.

@richmondu if you are still experiencing an issue please open a new ticket.
