### ISSUE TITLE
cant build sdk under windows 

### ISSUE THREAD

**Issue by patadia** [alexa/avs-device-sdk#1137]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Provide the steps to reproduce the issue, if applicable:

Windows Quick Start Guide with Script
 under Setup your configuration
bash setup.sh config.json -s 123456
it gives this only not going forword to clone or build

---------------------------------------------consol output----------------------------------------------

hshah@DESKTOP-GDV1SHK MINGW64 ~
$ bash setup.sh config.json -s 123456
################################################################################
################################################################################

AVS Device SDK Windows mingw64 Script - Terms and Agreements

The AVS Device SDK is dependent on several third-party libraries, environments,
and/or other software packages that are installed using this script from
third-party sources ("External Dependencies"). These are terms and conditions
associated with the External Dependencies
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that
you need to agree to abide by if you choose to install the External Dependencies.

If you do not agree with every term and condition associated with the External
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".

################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
==============> INSTALLING REQUIRED TOOLS AND PACKAGE ============

warning: git-2.20.1-1 is up to date -- skipping
:: There are 17 members in group mingw-w64-x86_64-toolchain:
:: Repository mingw64
   1) mingw-w64-x86_64-binutils  2) mingw-w64-x86_64-crt-git
   3) mingw-w64-x86_64-gcc  4) mingw-w64-x86_64-gcc-ada
   5) mingw-w64-x86_64-gcc-fortran  6) mingw-w64-x86_64-gcc-libgfortran
   7) mingw-w64-x86_64-gcc-libs  8) mingw-w64-x86_64-gcc-objc
   9) mingw-w64-x86_64-gdb  10) mingw-w64-x86_64-headers-git
   11) mingw-w64-x86_64-libmangle-git  12) mingw-w64-x86_64-libwinpthread-git
   13) mingw-w64-x86_64-make  14) mingw-w64-x86_64-pkg-config
   15) mingw-w64-x86_64-tools-git  16) mingw-w64-x86_64-winpthreads-git
   17) mingw-w64-x86_64-winstorecompat-git

Enter a selection (default=all):
warning: mingw-w64-x86_64-binutils-2.30-5 is up to date -- skipping
warning: mingw-w64-x86_64-crt-git-7.0.0.5275.ad74a50c-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-ada-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-fortran-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-libgfortran-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-libs-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-objc-8.2.1+20181214-1 is up to date -- skipping
warning: mingw-w64-x86_64-gdb-8.2-1 is up to date -- skipping
warning: mingw-w64-x86_64-headers-git-7.0.0.5275.ad74a50c-1 is up to date -- skipping
warning: mingw-w64-x86_64-libmangle-git-7.0.0.5230.69c8fad6-1 is up to date -- skipping
warning: mingw-w64-x86_64-libwinpthread-git-7.0.0.5273.3e5acf5d-1 is up to date -- skipping
warning: mingw-w64-x86_64-make-4.2.1-2 is up to date -- skipping
warning: mingw-w64-x86_64-pkg-config-0.29.2-1 is up to date -- skipping
warning: mingw-w64-x86_64-tools-git-7.0.0.5272.d66350ea-1 is up to date -- skipping
warning: mingw-w64-x86_64-winpthreads-git-7.0.0.5273.3e5acf5d-1 is up to date -- skipping
warning: mingw-w64-x86_64-winstorecompat-git-7.0.0.5230.69c8fad6-1 is up to date -- skipping
warning: mingw-w64-x86_64-cmake-3.12.4-1 is up to date -- skipping
warning: tar-1.30-1 is up to date -- skipping
warning: make-4.2.1-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-x86_64-python2-pip-18.1-2 is up to date -- skipping
 there is nothing to do
Requirement already satisfied: flask in c:/msys64/mingw64/lib/python2.7/site-packages (1.0.2)
Requirement already satisfied: requests in c:/msys64/mingw64/lib/python2.7/site-packages (2.20.1)
Requirement already satisfied: commentjson in c:/msys64/mingw64/lib/python2.7/site-packages (0.7.1)
Requirement already satisfied: itsdangerous>=0.24 in c:/msys64/mingw64/lib/python2.7/site-packages (from flask) (1.1.0)
Requirement already satisfied: Jinja2>=2.10 in c:/msys64/mingw64/lib/python2.7/site-packages (from flask) (2.10)
Requirement already satisfied: click>=5.1 in c:/msys64/mingw64/lib/python2.7/site-packages (from flask) (7.0)
Requirement already satisfied: Werkzeug>=0.14 in c:/msys64/mingw64/lib/python2.7/site-packages (from flask) (0.14.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:/msys64/mingw64/lib/python2.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in c:/msys64/mingw64/lib/python2.7/site-packages (from requests) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:/msys64/mingw64/lib/python2.7/site-packages (from requests) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:/msys64/mingw64/lib/python2.7/site-packages (from requests) (2018.11.29)
Requirement already satisfied: MarkupSafe>=0.23 in c:/msys64/mingw64/lib/python2.7/site-packages (from Jinja2>=2.10->flask) (1.1.0)
warning: mingw-w64-x86_64-sqlite3-3.26.0-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-x86_64-gstreamer-1.14.4-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-x86_64-gst-plugins-good-1.14.4-1 is up to date -- skipping
warning: mingw-w64-x86_64-gst-plugins-base-1.14.4-1 is up to date -- skipping
warning: mingw-w64-x86_64-gst-plugins-ugly-1.14.4-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-x86_64-gst-plugins-bad-1.14.4-3 is up to date -- skipping
warning: mingw-w64-x86_64-faad2-2.8.8-1 is up to date -- skipping
 there is nothing to do
warning: mingw-w64-x86_64-portaudio-190600_20161030-3 is up to date -- skipping
 there is nothing to do

==============> CREATING PATHS AND GETTING SOUND FILES ============

==============> BUILDING PORT AUDIO ==============

~/third-party ~
--2018-12-21 17:41:13--  http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
Resolving www.portaudio.com (www.portaudio.com)... 107.22.210.58
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.
----------------------------------------------------------------------------------------------------------------------

### What version of the AVS Device SDK are you using?
      <1.11>

### Tell us what hardware you're using:
- [ -] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [- ] Other - tell us more:WINDOWS

**Comment by scotthea-amazon** [comment]
Hello patadia,

It looks like the error you are encountering is probably a result of the command in mingw.sh:

```
pacman -S ${PACMAN_ARGS} mingw64/mingw-w64-x86_64-portaudio
```

You might try [cleaning the pacman package cache](https://wiki.archlinux.org/index.php/pacman#Cleaning_the_package_cache) or looking in /var/cache/pacman/pkg for a partially downloaded pa_stable_v190600_20161030.tgz and deleting it - and then re-running setup.sh.

Please let us know if that helps or not.

Best regards,
-SWH

**Comment by scotthea-amazon** [comment]
Hello @patadia,

I am closing this issue because it has been inactive for a very long time with no reply.  Please feel free to re-open it if you think it has been closed in error.

Thank you,
-SWH
