### ISSUE TITLE
SampleApp - PortAudio can't get correct deivce info from ALSA

### ISSUE THREAD

**Issue by barrel35618** [alexa/avs-device-sdk#114]
Hi, I'm tried to run SampleApp on TX1, and got error since it tried to do Pa_OpenDefaultStream in PortAudioMicrophoneWrapper.cpp.

**The log as shown below:**

- - -

TZ=UTC ./SampleApp /alexa_1.0/AlexaClientSDKConfig.json /alexa_1.0/inputs/KittAiModels/ DEBUG9

2017-08-25 09:37:36.772 [  1] I ConfigurationNode:initializeSuccess
Running app with log level: DEBUG9

(gst-plugin-scanner:9515): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstvaapi.so': /usr/lib/aarch64-linux-gnu/libva-drm.so.1: undefined symbol: drmGetClient

(gst-plugin-scanner:9515): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstclutter.so': /usr/lib/aarch64-linux-gnu/libgbm.so.1: undefined symbol: drmGetDevice

(gst-plugin-scanner:9515): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstcurl.so': libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

(gst-plugin-scanner:9515): GStreamer-WARNING **: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/libgstclutter-3.0.so': /usr/lib/aarch64-linux-gnu/libgbm.so.1: undefined symbol: drmGetDevice
2017-08-25 09:37:37.422 [  1] I StateSynchronizer:unexpectedConnectionStatusChange:reason=noConnectHappenedUnexpectedly
2017-08-25 09:37:37.424 [  2] I AlertsCapabilityAgent:executeScheduleNextAlertForRendering::no work to do.
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x752d00,policy=BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x73ee00,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x73ee00,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x73ee00,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x779500,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x779500,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x715d00,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x715d00,policy=NON_BLOCKING
2017-08-25 09:37:37.424 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x795a00,policy=NON_BLOCKING
2017-08-25 09:37:37.425 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x82d608,policy=NON_BLOCKING
2017-08-25 09:37:38.441 [  3] I StateSynchronizer:unexpectedConnectionStatusChange:reason=noConnectHappenedUnexpectedly
#############################
#       Connecting...       #
#############################
########################################
#       Alexa is currently idle!       #
########################################
Kenny, PaAlsa_Initialize, index=0
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.front.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib confmisc.c:768:(parse_card) cannot find card 'Tegra'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such device
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such device
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM dmix:Tegra
ALSA lib confmisc.c:768:(parse_card) cannot find card 'Tegra'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such device
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such device
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM dmix:Tegra
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Kenny> before Pa_OpenDefaultStream
 OpenStream, device=14
Kenny, inParams
Kenny, PaAlsaStreamComponent_Initialize
**Kenny. way1, device index=14
Kenny, alsaName=default, minInputChannels=127, minOutputChannels=127
Kenny, PaAlsaStream_Configure
Kenny> numHostChannels = 127, paInvalidChannelCount=-9998**
Expression 'alsa_snd_pcm_hw_params_set_channels( pcm, hwParams, self->numHostChannels )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2078
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2749
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2880
Kenny> after Pa_OpenDefaultStream
Failed to open PortAudio default stream
Failed to initialize PortAudioMicrophoneWrapper
2017-08-25 09:37:39.807 [  1] I DirectiveSequencer:shutdown

- - -

It ask ALSA to provide device "default" information, and got a strange value "127".
After it received this abnormal channel number, it failed to open PortAudio default stream.

I've copy the same libportaudio.a into Snowboy's example code, rebuilt the code, and run it.
( /snowboy/examples/C/demo.c )
It work fine and also could got keyword from the USB microphone.

**Here's the log runs with same "libportaudio.a" in Snowboy's example:**

- - -

ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.front.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.tegra-hda.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib confmisc.c:768:(parse_card) cannot find card 'Tegra'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such device
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such device
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM dmix:Tegra
ALSA lib confmisc.c:768:(parse_card) cannot find card 'Tegra'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such device
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such device
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such device
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such device
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM dmix:Tegra
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
 OpenStream, device=14
Kenny, inParams
Kenny, PaAlsaStreamComponent_Initialize
Kenny. way1, device index=14
**Kenny, alsaName=default, minInputChannels=1, minOutputChannels=1
Kenny, PaAlsaStream_Configure**
Kenny> numHostChannels = 1, paInvalidChannelCount=-9998
Kenny, >>>1
Kenny, minPeriods=3, maxPeriods=1024
Listening... Press Ctrl+C to exit

- - -

I've check my ALSA setting, but still don't know why the SampleApp got failed in PaAlsaStreamComponent_Initialize phase, and it works fine in Snowboy's demo code.

The ALSA card's information is:
**nvidia@tegra-ubuntu:/alexa/snowboy_c/portaudio$ cat /proc/asound/cards 
 0 [tegrahda       ]: tegra-hda - tegra-hda
                      tegra-hda at 0x70038000 irq 348
 1 [tegrasndt210ref]: tegra-snd-t210r - tegra-snd-t210ref-mobile-rt565x
                      tegra-snd-t210ref-mobile-rt565x
 2 [Device         ]: USB-Audio - USB PnP Sound Device
                      C-Media Electronics Inc. USB PnP Sound Device at usb-70090000.xusb-3.1, full sp**

And the .asoundrc is:
**nvidia@tegra-ubuntu:/alexa/snowboy_c/portaudio$ cat /home/nvidia/.asoundrc 
pcm.!default {
    type hw
    playback.pcm {
        type plug
        slave.pcm "hw:2,0"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:2,0"
    }
}
ctl.!default {
    type hw
    card 2
}**

**Comment by kencecka** [comment]
Hi @barrel35618,

I'm not seeing any obvious differences from the logs you've provided, and the fact that it works with the KITT demo code with the same library is very interesting.  I reviewed the KITT code and don't see them doing anything different from what we do in PortAudioMicrophoneWrapper.cpp in the SDK SampleApp.  If the library is the same and the basic initialization calls are the same, it seems unlikely that you have an alsa configuration issue.

Are you using the same model file when you test with the KITT demo code?  The SampleApp is hard-coded to use paInt16, but the KITT demo application gets the sample size from the model file.  That's the only potential difference I can see, if the demo app is choosing a different sample size.  

As a test, could you modify the KITT demo.c at line 200 to always call `StartAudioCapturing(16000, 1, 16)` and verify whether it still works?

Ken

**Comment by barrel35618** [comment]
Hi Ken,
Thank you for the reply, I've tried to fixed the given variable pass to Pa_OpenDefaultStream.
And also copy the code from Kitt demo app, and replace this part in "PortAudioMicrophoneWrapper.cpp"

It's really odd that these parts about PortAudio implementation should be the same, and I thought that the issue may cause by the wrong initialize phase or missing something in init part.

I've even init the PaUtil_InitializeRingBuffer, because Kitt sample use this ring buffer to save the captured audio data, but still not working.

For now, I've enabled the PA_DEBUG and add some log message to observe the different.
It seems that PortAudio can't get correct information from ALSA by calling "alsa_snd_pcm_hw_params_any( pcm, hwParams )"

In Kitt sample code, the hwParams could be got like this:

BuildDeviceList: Filling device info for 37 devices
FillInDevInfo: Filling device info for: tegra-hda: HDMI 0 (hw:0,3)
 OpenPcm, name=hw:0,3, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = **2050**, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = **2050**, maxInputChannels = 0, defaultSr=44100.000000..
Kenny >>> final: minChannels = **2**, maxChannels = **2**, defaultSampleRate = 44100.000000 ..
Default output device: tegra-hda: HDMI 0 (hw:0,3)
FillInDevInfo: Adding device tegra-hda: HDMI 0 (hw:0,3): 0
FillInDevInfo: Filling device info for: tegra-snd-t210ref-mobile-rt565x: - (hw:1,0)
 OpenPcm, name=hw:1,0, mode=1
Query capture...GropeDevice: collecting info ..
Direction : in Kenny >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=44100.000000..
Kenny >>> final: minChannels = 1, maxChannels = 16, defaultSampleRate = 44100.000000 ..
 OpenPcm, name=hw:1,0, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = 8200, maxInputChannels = 0, defaultSr=44100.000000..
Kenny . Get hw_params >>> minInputChannels = 8200, maxInputChannels = 0, defaultSr=44100.000000..
Kenny >>> final: minChannels = 1, maxChannels = 16, defaultSampleRate = 44100.000000 ..
Default input device: tegra-snd-t210ref-mobile-rt565x: - (hw:1,0)
FillInDevInfo: Adding device tegra-snd-t210ref-mobile-rt565x: - (hw:1,0): 1
FillInDevInfo: Filling device info for: tegra-snd-t210ref-mobile-rt565x: - (hw:1,1)
 OpenPcm, name=hw:1,1, mode=1
Query capture...GropeDevice: collecting info ..
Direction : in Kenny >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=44100.000000..
Kenny >>> final: minChannels = 1, maxChannels = 16, defaultSampleRate = 44100.000000 ..
 OpenPcm, name=hw:1,1, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = 14350, maxInputChannels = 0, defaultSr=44100.000000..
Kenny . Get hw_params >>> minInputChannels = 14350, maxInputChannels = 0, defaultSr=44100.000000..
Kenny >>> final: minChannels = 1, maxChannels = 16, defaultSampleRate = 44100.000000 ..


But in Sample App, it got wrong information for all devices:

BuildDeviceList: Filling device info for 37 devices
FillInDevInfo: Filling device info for: tegra-hda: HDMI 0 (hw:0,3)
 OpenPcm, name=hw:0,3, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = **134275**, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = 134275, maxInputChannels = 0, defaultSr=48000.000000..
Kenny >>> final: minChannels = **-742729332**, maxChannels = **8153984**, defaultSampleRate = 48000.000000 ..
Default output device: tegra-hda: HDMI 0 (hw:0,3)
FillInDevInfo: Adding device tegra-hda: HDMI 0 (hw:0,3): 0
FillInDevInfo: Filling device info for: tegra-snd-t210ref-mobile-rt565x: - (hw:1,0)
 OpenPcm, name=hw:1,0, mode=1
Query capture...GropeDevice: collecting info ..
Direction : in Kenny >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=192000.000000..
Kenny >>> final: minChannels = -742729332, maxChannels = 8146448, defaultSampleRate = 192000.000000 ..
 OpenPcm, name=hw:1,0, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = 140425, maxInputChannels = 0, defaultSr=192000.000000..
Kenny . Get hw_params >>> minInputChannels = 140425, maxInputChannels = 0, defaultSr=192000.000000..
Kenny >>> final: minChannels = -742729332, maxChannels = 8254080, defaultSampleRate = 192000.000000 ..
Default input device: tegra-snd-t210ref-mobile-rt565x: - (hw:1,0)
FillInDevInfo: Adding device tegra-snd-t210ref-mobile-rt565x: - (hw:1,0): 1
FillInDevInfo: Filling device info for: tegra-snd-t210ref-mobile-rt565x: - (hw:1,1)
 OpenPcm, name=hw:1,1, mode=1
Query capture...GropeDevice: collecting info ..
Direction : in Kenny >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=-1.000000..
Kenny . Get hw_params >>> minInputChannels = 0, maxInputChannels = 0, defaultSr=192000.000000..
Kenny >>> final: minChannels = -742729332, maxChannels = 8154496, defaultSampleRate = 192000.000000 ..
 OpenPcm, name=hw:1,1, mode=1
Query playback...GropeDevice: collecting info ..
Direction : out Kenny >>> minInputChannels = 146575, maxInputChannels = 0, defaultSr=192000.000000..
Kenny . Get hw_params >>> minInputChannels = 146575, maxInputChannels = 0, defaultSr=192000.000000..
Kenny >>> final: minChannels = -742729332, maxChannels = 8115552, defaultSampleRate = 192000.000000 ..


I still try to figure out how come it seems like memory leaking or overflow in somewhere.

Kenny

**Comment by mradulan** [comment]
hi Kenny, were you able to resolve this issue?

**Comment by BennyAvramson** [comment]
Hi @barrel35618,

As we didn't hear from you, I assume you were able to solve the issue. I'm closing the issue. Please reopen it if you have further questions.

Thanks,
Benny
