### ISSUE TITLE
Alexa Sound Library files for AVS - File sizes are pretty much the same, docs state something different

### ISSUE THREAD

**Issue by frivas** [alexa/avs-device-sdk#1144]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have noticed the following statement in the documentation : 

> you will notice folders filled with audio clips of various size/quality - if your shipping device has limited memory, you might want to choose the "sml" folder to save space. 

The thing is checking the files themselves it does not reflect such statement, so for that, are the files wrong or the docs are?

## What is the expected behavior?

Consistency between what is stated in the documentation and the actual files. Just clarifying if the files should actually differ in quality and size (all of them) or not.

## What behavior are you observing?

I have checked a few files with different tools `avprobe` and `sox` I have not noticed a real difference.

I have noticed a file size change only in one file `*_ui_wakesound.wav`. What about the rest?

```
$ sox --i ful/ful_ui_wakesound.wav           

Input File     : 'ful/ful_ui_wakesound.wav'
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:00.65 = 31065 samples ~ 48.5391 CDDA sectors
File Size      : 124k
Bit Rate       : 1.54M
Sample Encoding: 16-bit Signed Integer PCM

pi@raspberrypi:~/Documents/Alexa Sound Library for AVS $ sox --i med/med_ui_wakesound.wav 

Input File     : 'med/med_ui_wakesound.wav'
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:00.65 = 31065 samples ~ 48.5391 CDDA sectors
File Size      : 124k
Bit Rate       : 1.54M
Sample Encoding: 16-bit Signed Integer PCM

pi@raspberrypi:~/Documents/Alexa Sound Library for AVS $ sox --i sml/sml_ui_wakesound.wav 

Input File     : 'sml/sml_ui_wakesound.wav'
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:00.47 = 22653 samples ~ 35.3953 CDDA sectors
File Size      : 90.7k
Bit Rate       : 1.54M
Sample Encoding: 16-bit Signed Integer PCM
```

The same output for `avprobe` and `file`.

```
$ file ful/ful_ui_wakesound.wav med/med_ui_wakesound.wav sml/sml_ui_wakesound.wav                   
ful/ful_ui_wakesound.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 48000 Hz
med/med_ui_wakesound.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 48000 Hz
sml/sml_ui_wakesound.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 48000 Hz
```
### What version of the AVS Device SDK are you using?
      <1.11>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Thank you very much in advanced

**Comment by frivas** [comment]
Hello @kjkh 

No. I am not having any problems caused by that. In any case I can use ```ffmpeg``` to convert it. I just wanted to bring this to AVS team's attention. Thank you for the support. I can help fixing the documentation and/or the files.

**Comment by dhpp** [comment]
Thanks @frivas, we appreciate that.  I'll close out this ticket in the meantime.
