### ISSUE TITLE
AVS Device SDK error : The refresh request failed with the response code 400

### ISSUE THREAD

**Issue by kameshkancherla** [alexa/avs-device-sdk#1146]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?

Authorize
## What behavior are you observing?

Error : Amazon page is not responding
### What version of the AVS Device SDK are you using?
      <x.y.z>
Lates one
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
- Respeaker Core V2.0

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
- Debian

Problem

Team,

I am getting the same error.

respeaker@v2:~/sdk-folder/sdk-build$ python AuthServer/AuthServer.py
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

Serving Flask app "AuthServer" (lazy loading)
Environment: production
WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
Debug mode: off
Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Dec/2018 21:22:46] "GET / HTTP/1.1" 302 -
Jason File core

{
"authDelegate":{
// The Client Secret of the Product from developer.amazon.com
"clientSecret":"da27xxxxxxxxxxxxxxxxxxxxxxxxxxxxx97a1786e019fxxxxxxxxxcef79d3",
// Unique device serial number. e.g. 123456
"deviceSerialNumber":"MMAxxxxxxNBW",
// Refresh Token populated by running AuthServer.py
"refreshToken":"",
// The Client ID of the Product from developer.amazon.com
"clientId":"amzn1.application-oa2-client.aebaxxxxxxxxxxxxxxb56464db1814",
// Product ID from developer.amazon.com
"productId":"rk322x"
},
"alertsCapabilityAgent":{
// Path to Alerts database file. e.g. /home/ubuntu/Build/alerts.db
// Note: The directory specified must be valid.
// The database file (alerts.db) will be created by SampleApp, do not create it yourself.
// The database file should only be used for alerts (don't use it for other components of SDK)
"databaseFilePath":"/home/respeaker/sdk-folder/application-necessities/alert.db"
},
"settings":{
// Path to Settings database file. e.g. /home/ubuntu/Build/settings.db
// Note: The directory specified must be valid.
// The database file (settings.db) will be created by SampleApp, do not create it yourself.
// The database file should only be used for settings (don't use it for other components of SDK)
"databaseFilePath":"/home/respeaker/sdk-folder/application-necessities/settings.db",
"defaultAVSClientSettings":{
// Default language for Alexa.
// See https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated for valid values.
"locale":"en-US"
}
},
"certifiedSender":{
// Path to Certified Sender database file. e.g. /home/ubuntu/Build/certifiedsender.db
// Note: The directory specified must be valid.
// The database file (certifiedsender.db) will be created by SampleApp, do not create it yourself.
// The database file should only be used for certifiedSender (don't use it for other components of SDK)
"databaseFilePath":"/home/respeaker/sdk-folder/application-necessities/certifiedSender.db"
},
"notifications":{
// Path to Notifications database file. e.g. /home/ubuntu/Build/notifications.db
// Note: The directory specified must be valid.
// The database file (notifications.db) will be created by SampleApp, do not create it yourself.
// The database file should only be used for notifications (don't use it for other components of SDK)
"databaseFilePath":"/home/respeaker/sdk-folder/application-necessities/notifications.db"

I tried with Local Host but the error is same : http://localhost:3000 & http://127.0.0.1:3000/

Error on VNC - Firefox

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Show Details

**Comment by kjkh** [comment]
Hi @kameshkancherla,

Which version of the SDK are you using? The AuthServer was an old mechanism that was deprecated in favor of the Code Based Linking method. Can you try using the latest version of the SDK and see if you are able to authenticate?

**Comment by kameshkancherla** [comment]
I was using this.

http://wiki.seeedstudio.com/ReSpeaker_Core_v2.0/#preparation

Regards
Vithal

**Comment by dhpp** [comment]
Hi @kameshkancherla, you may get the most recent SDK version directly from this GitHub repo - just perform a fresh clone or pull to your repo.

**Comment by kameshkancherla** [comment]
After adding the https://localhost:3000/authResoponse to Developer.amazon.com -> my products->under security profile. Problem solved.
