### ISSUE TITLE
Initialization with Non en-US Language

### ISSUE THREAD

**Issue by comperge** [alexa/avs-device-sdk#1147]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Initialization with Non en-US Language
## What is the expected behavior?

Alexa speak no English Language such as Japanese

## What behavior are you observing?

Only English spoken

## Provide the steps to reproduce the issue, if applicable:

I have sent a locale setting when device start, 
"settings": {    
"databaseFilePath": "/sdcard/alexa_config/settings.db",    
"defaultAVSClientSettings": {        "locale": "ja-JP"    }},

i can see the Login window in chrome with the language I set
but actual Alexa do not speak the language, but only English US.

I know there is

https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated
this thing. (not tried yet)

Do i have to Re-Set locale to get proper spoken Language even in intial sequence??

## Tell us about your environment:

Android 7.0 base device

### What version of the AVS Device SDK are you using?
     1.8.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [0 ] Other - tell us more: Android like Device with Screen built in

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [0 ] Other - tell us more: android

**Comment by comperge** [comment]
hi
I am building Alexa on a certain  Android device. and i am not sure what 'Pressing "c"' means.
what i am doing is sending above setting value while log in process. (working on Java code because it is Android). Then, web browser helps me getting in Alexa Amazon. However, i can only hear English. version code 1.8

**Comment by visayamv** [comment]
Hi @comperge , I hope that answers your question. I will be closing this issue but feel free to reopen if you need further assistance on this matter.
