### ISSUE TITLE
Client not connected

### ISSUE THREAD

**Issue by iotMice** [alexa/avs-device-sdk#1148]
I am trying to install alexa c++ sdk for raspberrypi model 3B+ (Stretch installed in it).
I followed the steps given in the tutorial.
My device is getting authorized as well,
after authorization it shows "client not connected"
and then it shows "alexa is in idle state".

How to solve client not connected issue.
I have downloaded config.json from OTHER DEVICES AND PLATFORM tab in developer account of alexa.
config.json has client id , and product name.

how to solve the problem

**Comment by frivas** [comment]
Hello @iotMice, I have also asked the same question at #1108, just in case you want to keep that issue as reference.

**Comment by kjkh** [comment]
Hi @iotMice,

Can you attach DEBUG9 logs? See steps to [enable debug logs](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#debug-builds).
