### ISSUE TITLE
 Press 's' does not exit the skill, only stops the TTS

### ISSUE THREAD

**Issue by ankit-agrahyah** [alexa/avs-device-sdk#1152]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 Press 's' and Enter to stop an ongoing interaction.        
This does not end the skill, it only stops the TTS

## What is the expected behavior?

There should be some direct method to end any skill other than just by voice input

## What behavior are you observing?

Only TTS stops, but the skill doesnot end.

## Provide the steps to reproduce the issue, if applicable:

Press 's' when any skill is ongoing and does not end.

### What version of the AVS Device SDK are you using?
      <x.y.z>
Android

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android

**Comment by visayamv** [comment]
Hi @ankit-agrahyah , unfortunately, currently only voice utterance can trigger the skill to exit.
