### ISSUE TITLE
No Json file can be downloaded when creating profile 

### ISSUE THREAD

**Issue by Miguelon110602** [alexa/avs-device-sdk#1153]
When I create the new profile it doesn't give me the option to download the .json file and later in the installation it does not save the configuration, someone help me please

**Comment by visayamv** [comment]
Hi @Miguelon110602 ,

On the security profile page, click on "Other devices and platforms", you should find a download button there.


![security_profile_download](https://user-images.githubusercontent.com/38438010/50715111-80fc3e00-1030-11e9-9e4d-5c6b4a6d27ae.png)

**Comment by Miguelon110602** [comment]
Thaaanks!!!
