### ISSUE TITLE
Play Pandora cause SampleAPP crash silently

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1154]
Hi AVS team,

SDK 1.9 and SDK 1.11.  ARM based embedded linux system.

We got complained from customers that it cannot play Pandora music over hours. (mostly, it will stop music in an hour)
We tried to reproduce this case and found it's actually cannot play Pandora long term. (we are still under checking with EchoDot, and will file another case)
During the tests, we found sometimes, the SampleAPP will disappear silently, and it seems crashed at the same point under SDK1.9 or SDK1.11.

I attached three logs for your reference, you can just see the end of the files, the SampleAPP disappear and music stop.

I don't know how to 100% reproduce this case, most of the cases, the Pandora will finish music first.

[pandora_avs_crash-sdk_1.9-2.log](https://github.com/alexa/avs-device-sdk/files/2729254/pandora_avs_crash-sdk_1.9-2.log)
[pandora_avs_crash-sdk-1.9.log](https://github.com/alexa/avs-device-sdk/files/2729255/pandora_avs_crash-sdk-1.9.log)
[pandora_sdk1.11-crash.log](https://github.com/alexa/avs-device-sdk/files/2729256/pandora_sdk1.11-crash.log)

**Comment by visayamv** [comment]
Hi @zeusshuang , is it possible for you to run SampleApp with GDB? when the SampleApp crashes, you can execute backtrace to get the stacktrace and post here. This will tell us where in the code it is crashing.

**Comment by visayamv** [comment]
the debug9 logs can only show the last message printed but not necessarily the point of crash

**Comment by visayamv** [comment]
Hi @zeusshuang , thanks. Let us know if you need help on setting it up.

**Comment by zeusshuang** [comment]
Hi @visayamv ,

Yes, I need your help to provide ways to debug in GDB.

It seems it always crashed after TemplateRuntime related functions, not sure if it's related ad. from Pandora (due to I never got ad. while testing Pandora in these three months which defined in Pandora music self-test cases)

**Comment by visayamv** [comment]
Hi @zeusshuang ,

First install GDB, in Linux, this can be done by:

`sudo apt-get install gdb`

Now run the SampleApp with gdb. You need to put "gdb --args" in front of the SampleApp command.

For example if you're SampleApp command is:

`./SampleApp/src/SampleApp -C ./Integration/AlexaClientSDKConfig.json -L debug9`

run it with gdb like this:

`gdb --args ./SampleApp/src/SampleApp -C ./Integration/AlexaClientSDKConfig.json -L debug9`

This will get you to the GDB prompt:

`(gdb) `

Type "run" in the gdb prompt to run the SampleApp with GDB

`(gdb) run`

Use it as usual.

When the SampleApp crashes, type "info threads" and "backtrace" as follows:

`(gdb) info threads`
`(gdb) backtrace`

If you're running it in Raspberry pi, you can find the SampleApp command inside the startsample.sh file

Post the output of "info threads" and "backtrace" here.

**Comment by zeusshuang** [comment]
Hi @visayamv ,

I have trouble to run GDB in our embedded system. But I still got this fail case randomly.
To compare all failed and working case, I found, while it's going to crashed, it will have these message:

TemplateRuntime:onPlayerActivityChangedInExecutor
TemplateRuntime:executeAudioPlayerInfoUpdates:audioItemId=amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#b5e0f014-e99c-49dc-a64b-ea5e2bea9f89\:3,offset=41,audioPlayerState=PLAYING,isRenderTemplatelastReceived=false
TemplateRuntime:executeAudioPlayerInfoUpdates:audioItemId=amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#b5e0f014-e99c-49dc-a64b-ea5e2bea9f89\:1:Dropping out-dated audioItemId in queue.
TemplateRuntime:executeAudioPlayerInfoUpdates:audioItemId=amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#b5e0f014-e99c-49dc-a64b-ea5e2bea9f89\:1:Dropping out-dated audioItemId in queue.
TemplateRuntime:executeOnFocusChangedEvent:prevFocus=NONE,newFocus=FOREGROUND
TemplateRuntime:executeRenderPlayerInfoCallbacks:isClearCard=False

To have several "Dropping out-dated" message.
With working case, it will never have this message. Then it will it will crashed at 
observer->renderPlayerInfoCard(m_audioItemInExecution.directive->directive->getPayload(), m_audioPlayerInfo, m_focus);

and never go into renderPlayerInfoCard

**Comment by kclchan** [comment]
Hi @zeusshuang, the crash in TemplateRuntime has been fixed in v1.13 of the SDK.  Thank!
