### ISSUE TITLE
How to change  Device name

### ISSUE THREAD

**Issue by comperge** [alexa/avs-device-sdk#1157]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Wish to change device name like echo show dose.

## What is the expected behavior?
I want to see my modified Device name on alexa.amazon.com or alexa app on my Phone.

## Provide the steps to reproduce the issue, if applicable:

i assumed in alexa config json ....
"deviceInfo": {
                "deviceSerialNumber": "xxxxx",
                "clientId": "xxxxxxxxxxxx",
                "productId": "HER_MY_DEVICE"
            },
productId might be the Device name, in alexa.amzon.com.
I replace the productId  and restarted my code, but nothing happened.

Is there any API or something ?
My Client expects  my device works exactly same as echo shows.

Working based on Avs sdk with android app dev.

### What version of the AVS Device SDK are you using?
      <1.8.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [0] Other - tell us more: Android 7.0 based Device 

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [0] Other - tell us more: Android 7.0

**Comment by aumatsui** [comment]
Hi comperge,

Currently, the AVS SDK does not have such functionality. So in order to change the device name your only option at this point is to use the companion site or app on your phone.

If you really need this feature, I would suggest you [file a feature request](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).

Thank you,

aumatsui

**Comment by aumatsui** [comment]
I am closing this issue since the question was answered.

**Comment by jcrist678** [comment]
@comperge , delete the .db files
