### ISSUE TITLE
Which audio content should be streamed to BT speaker

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1159]
I'm now able to stream all the audio to BT speaker. But let's think about the use scenario. If we stream all the audio including speech, audio, alerts to BT speaker. Then it will be strange that user stand by and talk to the alexa device, but the response come from the remote BT speaker a few meters away.

So I think we should only stream the audio like music to BT speaker, while other audios like speech/alert/notification should be streamed to the alexa device. 

What do you think? What is the expected behavior? And how does echo do when it works as A2DP source?

Appreciate for your suggestions.

**Comment by aumatsui** [comment]
Hi subjectxbj,

Thank you for your question. The user experience you described is an interesting one for sure. Currently, the SDK does not implement audio capture from a BT speaker, but it is in theory possible to add such a feature to it.

Echo devices do not implement this particular use case, but are able to receive voice from the Alexa voice remote. These devices do not select the speaker based on the kind of audio. So all audio (alarms, music, etc) will always be played on the BT speaker when one is connected to the Echo device.

Thank you,

**Comment by subjectxbj** [comment]
So if a BT speaker is connected, all the audio will be streamed to BT speaker, and nothing is played on the echo?

**Comment by aumatsui** [comment]
Correct.
