### ISSUE TITLE
[WWE] No response from amazon when ask question

### ISSUE THREAD

**Issue by MTKYZ** [alexa/avs-device-sdk#1164]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

**On AVS SDK 1.11, we have integrated Amazon WWE, When I say “Alexa”, it can be detected, but there isn’t any response when ask question. Here is the detail log, would you please give me some advice?**

(190110_17:49:20.375)[   48.037467] <0>.(0)[30:kworker/0:1]E_WF: mtk_get_gpu_loading doesn't exist
(190110_17:49:20.951) AmazonLiteKeywordDetector Detected keyword 'ALEXA'info: (set_current_cloud_state) state=1, recognition_delay_slots=1
(190110_17:49:20.953)2019-01-10 09:49:20.562 [ 11] E AudioInputProcessor:YZ AudioInputProcessor::recognize:begin=381600
(190110_17:49:20.953) AudioInputProcessor::executeRecognize==={"type":"WAKEWORD","payload":{"wakeWordIndices":{"startIndexInSamples":8000,"endIndexInSamples":17280},"wakeWord":"ALEXA"}}
(190110_17:49:20.953)2019-01-10 09:49:20.564 [ 1d] 5 AudioInputProcessor:executeRecognize
(190110_17:49:20.953)2019-01-10 09:49:20.565 [ 1d] 0 AudioInputProcessor:notEncodingAudio
(190110_17:49:20.953)2019-01-10 09:49:20.566 [ 1d] 5 UserInactivityMonitor:onUserActive
(190110_17:49:20.953)2019-01-10 09:49:20.566 [ 1d] 0 AudioInputProcessor:setState:from=IDLE,to=RECOGNIZING
(190110_17:49:20.953)2019-01-10 09:49:20.567 [  4] 0 DialogUXStateAggregator:setState:from=IDLE,to=LISTENING
(190110_17:49:21.034)############################
(190110_17:49:21.034)#       Listening...       #
(190110_17:49:21.034)############################
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 16] 5 VisualActivityTracker:provideState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 16] 5 AudioActivityTracker:provideState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 16] 5 NotificationsCapabilityAgent:provideState:stateRequestToken=2
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 17] 5 VisualActivityTracker:executeProvideState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 17] 9 ContextManager:updateStateLocked:action=updatedState,namespace=VisualActivityTracker,name=ActivityState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 18] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=2
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 18] 9 ContextManager:updateStateLocked:action=updatedState,namespace=ExternalMediaPlayer,name=ExternalMediaPlayerState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 18] 0 ExternalMediaPlayer:executeProvideState:sendToken=true,stateRequestToken=2
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 18] 9 ContextManager:updateStateLocked:action=updatedState,namespace=Alexa.PlaybackStateReporter,name=playbackState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 1a] 5 AudioActivityTracker:executeProvideState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [ 1a] 9 ContextManager:updateStateLocked:action=updatedState,namespace=AudioActivityTracker,name=ActivityState
(190110_17:49:21.034)2019-01-10 09:49:20.568 [  e] 5 NotificationsCapabilityAgent:executeProvideState:sendToken=true,stateRequestToken=2
(190110_17:49:21.034)2019-01-10 09:49:20.569 [  e] 9 ContextManager:updateStateLocked:action=updatedState,namespace=Notifications,name=IndicatorState
(190110_17:49:21.034)2019-01-10 09:49:20.569 [ 16] 9 ContextManager:buildContextIgnored:namespace=VisualActivityTracker,name=ActivityState
(190110_17:49:21.034)2019-01-10 09:49:20.569 [ 16] 9 ContextManager:buildContextIgnored:namespace=AudioActivityTracker,name=ActivityState
(190110_17:49:21.034)2019-01-10 09:49:20.569 [ 16] 5 ContextManager:buildContextSuccessful
(190110_17:49:21.034)YZ m_recognizePayload **### _{"profile":"FAR_FIELD","format":"AUDIO_L16_RATE_16000_CHANNELS_1","initiator":{"type":"WAKEWORD","payload":{"wakeWordIndices":{"startIndexInSamples":8000,"endIndexInSamples":17280},"wakeWord":"ALEXA"}},"startOfSpeechTimestamp":"48603844540"}_**
2019-01-10 09:49:20.570 [ 1d] 0 AudioInputProcessor:executeOnContextAvailable
(190110_17:49:21.034)2019-01-10 09:49:20.571 [ 1d] 1 FocusManager:acquireChannel:channelName=Dialog,interface=SpeechRecognizer
(190110_17:49:21.034)2019-01-10 09:49:20.573 [ 1d] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=1cb11b66-9758-45e4-bb49-8a7286f99492
(190110_17:49:21.034)2019-01-10 09:49:20.573 [ 1e] 9 AudioInputProcessor:onFocusChanged:newFocus=FOREGROUND
(190110_17:49:21.035)2019-01-10 09:49:20.615 [ 1e] 5 AudioActivityTracker:notifyOfActivityUpdates
(190110_17:49:21.035)2019-01-10 09:49:20.616 [ 1a] 5 AudioActivityTracker:executeNotifyOfActivityUpdates
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 1d] 0 DirectiveProcessor:scrubDialogRequestIdLocked:reason=emptyDialogRequestId
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 1d] 0 EventBuilder:buildJsonEventString:messageId=8a504200-e03e-4537-9bf3-c90b28a2fe26,namespace=SpeechRecognizer,name=Recognize
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 1d] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 1d] 5 HTTP2Transport:send
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 1d] 5 HTTP2Transport:enqueueRequest:beforeConnected=false
(190110_17:49:21.035)2019-01-10 09:49:20.617 [ 13] 5 MessageRequestHandler:create:context=0xb2510a9c,messageRequest=0x5bde4c
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 ExchangeHandler:ExchangeHandler:context=0xb2510a9c
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 MessageRequestHandler:MessageRequestHandler:context=0xb2510a9c,messageRequest=0x5bde4c
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2MimeRequestEncoder:HTTP2MimeRequestEncoder:boundary=WhooHooZeerOoonie!,source=0xaff0f18c
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 MimeResponseSink:MimeResponseSink:handler=0xaff0f190
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2MimeResponseDecoder:HTTP2MimeResponseDecoder
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2Transport:onMessageRequestSent:countOfUnfinishedMessageHandlers=1
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2Transport:createAndSendRequest:type=POST,url=https\://avs-alexa-na.amazon.com/v20160207/events
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2MimeRequestEncoder:getRequestHeaderLines
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 MessageRequestHandler:getRequestHeaderLines
(190110_17:49:21.035)2019-01-10 09:49:20.618 [ 13] 5 HTTP2Transport:onActivity
(190110_17:49:21.107)2019-01-10 09:49:20.709 [ 14] 9 LibcurlHTTP2Connection:insertActiveStream:handle=0xaff146c0,streamId=AVSEvent-7
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=NEW
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=NEW,newState=GETTING_1ST_PART_HEADERS
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:getMimePartHeaderLines
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=GETTING_1ST_PART_HEADERS,newState=SENDING_1ST_BOUNDARY
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_1ST_BOUNDARY,newState=SENDING_PART_HEADERS
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_PART_HEADERS,newState=SENDING_PART_DATA
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16277
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=14660
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_PART_DATA,newState=SENDING_END_BOUNDARY
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_END_BOUNDARY,newState=GETTING_NTH_PART_HEADERS
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:getMimePartHeaderLines
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=GETTING_NTH_PART_HEADERS,newState=SENDING_CRLF_AFTER_BOUNDARY
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_CRLF_AFTER_BOUNDARY,newState=SENDING_PART_HEADERS
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_PART_HEADERS,newState=SENDING_PART_DATA
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=14548
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.710 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=14548
(190110_17:49:21.112)2019-01-10 09:49:20.711 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:21.112)2019-01-10 09:49:20.711 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:21.112)2019-01-10 09:49:20.711 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:21.112)2019-01-10 09:49:20.711 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.112)2019-01-10 09:49:20.711 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:21.372)[   49.037149] <0>.(0)[30:kworker/0:1]E_WF: mtk_get_gpu_loading doesn't exist
(190110_17:49:21.450)[   49.117698] <0>.(0)[75:hps_main]CPU1: shutdown
(190110_17:49:21.456)[   49.118303] <0>.(0)[75:hps_main]CPU1 killed.
(190110_17:49:21.902)[   49.517592] <1>-(1)[0:swapper/1]CPU1: update cpu_capacity 1024
(190110_17:49:21.913)[   49.518338] <1>-(1)[0:swapper/1]CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
(190110_17:49:21.980)2019-01-10 09:49:21.566 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:21.982)2019-01-10 09:49:21.566 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:21.982)2019-01-10 09:49:21.566 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:21.982)2019-01-10 09:49:21.566 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.982)2019-01-10 09:49:21.566 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:21.982)2019-01-10 09:49:21.568 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:21.982)2019-01-10 09:49:21.568 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:21.982)2019-01-10 09:49:21.568 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:21.982)2019-01-10 09:49:21.568 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:21.982)2019-01-10 09:49:21.568 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:22.244)2019-01-10 09:49:21.859 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:22.248)2019-01-10 09:49:21.860 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:22.248)2019-01-10 09:49:21.860 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:22.248)2019-01-10 09:49:21.860 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:22.249)2019-01-10 09:49:21.860 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:22.385)[   50.037494] <0>.(0)[30:kworker/0:1]E_WF: mtk_get_gpu_loading doesn't exist
(190110_17:49:22.587)2019-01-10 09:49:22.195 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:22.589)2019-01-10 09:49:22.195 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:22.589)2019-01-10 09:49:22.195 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:22.589)2019-01-10 09:49:22.196 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:22.589)2019-01-10 09:49:22.196 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:23.039)2019-01-10 09:49:22.617 [ 14] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-7,size=1,nmemb=16384,userData=0xaff0e540
(190110_17:49:23.043)2019-01-10 09:49:22.617 [ 14] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=SENDING_PART_DATA
(190110_17:49:23.043)2019-01-10 09:49:22.617 [ 14] 5 MessageRequestHandler:onSendMimePartData:size=16384
(190110_17:49:23.043)2019-01-10 09:49:22.617 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:23.043)2019-01-10 09:49:22.617 [ 14] 5 MessageRequestHandler:attachmentRead:readStatus=0,bytesRead=16384
(190110_17:49:23.117)2019-01-10 09:49:22.691 [ 14] 9 LibcurlHTTP2Request:writeCallback:id=AVSDownChannel-1,size=1,nmemb=273,userData=0xaff06d80
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 HTTP2MimeResponseDecoder:onReceiveData:size=273
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 MimeResponseSink:onBeginMimePart
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 9 MimeResponseSink:JsonContentDetected
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 MimeResponseSink:onReceiveMimeData:size=199
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 MimeResponseSink:onEndMimePart
(190110_17:49:23.120)2019-01-10 09:49:22.691 [ 14] 5 HTTP2Transport:onActivity
(190110_17:49:23.120)2019-01-10 09:49:22.693 [ 1f] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"ed772c98-1330-4aa2-b6d8-d4fb78927c51"\,dialogRequestId\:"1cb11b66-9758-45e4-bb49-8a7286f99492"}
(190110_17:49:23.120)2019-01-10 09:49:22.695 [ 20] I DirectiveRouter:preHandleDirective:messageId=ed772c98-1330-4aa2-b6d8-d4fb78927c51,action=calling
(190110_17:49:23.120)2019-01-10 09:49:22.695 [ 20] 0 CapabilityAgent:addingMessageIdToMap:messageId=ed772c98-1330-4aa2-b6d8-d4fb78927c51
(190110_17:49:23.120)2019-01-10 09:49:22.696 [  5] 9 DirectiveProcessor:processCancelingQueueLocked:size=0
(190110_17:49:23.120)2019-01-10 09:49:22.696 [  5] 9 DirectiveProcessor:handleQueuedDirectivesLocked:queue size=1
(190110_17:49:23.120)2019-01-10 09:49:22.697 [  5] 9 DirectiveProcessor:handleQueuedDirectivesLocked:proceeding with directive=ed772c98-1330-4aa2-b6d8-d4fb78927c51,policy= Mediums:MEDIUMS_NONE00 .isBlocking:False
(190110_17:49:23.120)2019-01-10 09:49:22.697 [  5] I DirectiveRouter:handleDirective:messageId=ed772c98-1330-4aa2-b6d8-d4fb78927c51,action=calling
**_### (190110_17:49:23.120)2019-01-10 09:49:22.697 [  5] 9 DirectiveProcessor:processCancelingQueueLocked:size=0
(190110_17:49:23.120)2019-01-10 09:49:22.697 [ 1d] 0 AudioInputProcessor:stopCapture:stopImmediately=true
(190110_17:49:23.120)2019-01-10 09:49:22.697 [ 1d] 5 UserInactivityMonitor:onUserActive
(190110_17:49:23.120)2019-01-10 09:49:22.698 [ 1d] 0 AudioInputProcessor:setState:from=RECOGNIZING,to=BUSY_**
(190110_17:49:23.120)2019-01-10 09:49:22.698 [ 1d] 0 DirectiveProcessor:onHandlingCompeted:messageId=ed772c98-1330-4aa2-b6d8-d4fb78927c51,directiveBeingPreHandled=(nullptr)
(190110_17:49:23.121)2019-01-10 09:49:22.698 [ 1d] 0 CapabilityAgent:removingMessageIdFromMap:messageId=ed772c98-1330-4aa2-b6d8-d4fb78927c51
(190110_17:49:23.121)2019-01-10 09:49:22.699 [  4] 0 DialogUXStateAggregator:setState:from=LISTENING,to=THINKING
(190110_17:49:23.121)2019-01-10 09:49:22.699 [  4] 5 TemplateRuntime:onDialogUXStateChanged:state=THINKING
(190110_17:49:23.121)###########################
(190110_17:49:23.121)#       Thinking...       #
(190110_17:49:23.121)###########################

### What version of the AVS Device SDK are you using?
      AVS SDK 1.11

### Tell us what hardware you're using:
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Yocto

**Comment by dhpp** [comment]
Hi @MTKYZ, I noice the following trace in your log:

(190110_17:49:21.372)[ 49.037149] <0>.(0)[30:kworker/0:1]E_WF: mtk_get_gpu_loading doesn't exist
(190110_17:49:21.450)[ 49.117698] <0>.(0)[75:hps_main]CPU1: shutdown
(190110_17:49:21.456)[ 49.118303] <0>.(0)[75:hps_main]CPU1 killed.
(190110_17:49:21.902)[ 49.517592] <1>-(1)[0:swapper/1]CPU1: update cpu_capacity 1024
(190110_17:49:21.913)[ 49.518338] <1>-(1)[0:swapper/1]CPU1: thread -1, cpu 1, socket 0, mpidr 80000001

I'd also like to ask what happens next in the application after the last line of trace you post - does the application hang, or exit?  Thanks.

**Comment by MTKYZ** [comment]
> Hi @MTKYZ, I noticed the following trace in your log:
> 
> (190110_17:49:21.372)[ 49.037149] <0>.(0)[30:kworker/0:1]E_WF: mtk_get_gpu_loading doesn't exist
> (190110_17:49:21.450)[ 49.117698] <0>.(0)[75:hps_main]CPU1: shutdown
> (190110_17:49:21.456)[ 49.118303] <0>.(0)[75:hps_main]CPU1 killed.
> (190110_17:49:21.902)[ 49.517592] <1>-(1)[0:swapper/1]CPU1: update cpu_capacity 1024
> (190110_17:49:21.913)[ 49.518338] <1>-(1)[0:swapper/1]CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
> 
> That looks like something problematic. Do you know the cause and impact of that trace?
> 
> I'd also like to ask what happens next in the application after the last line of trace you post - does the application hang, or exit? Thanks.

The application runs normally, the same problem will be reproduced when i ask question again.i check the AmazonLite API and find it returns PRYON_LITE_ERROR_INVALID_PARAM sometimes when i call PryonLiteDecoder_PushAudioSamples API, can you share demo for this API?

thanks

**Comment by aumatsui** [comment]
Hi @MTKYZ,

Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.

Regards,

**Comment by MTKYZ** [comment]
thanks, I have fixed this issue, the wwe works now.
