### ISSUE TITLE
SDK setup fails at the "Building the SDK" part. 

### ISSUE THREAD

**Issue by Widea** [alexa/avs-device-sdk#1165]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Setup fails at the "make" command in "Building the SDK" step at 41%. 

## What is the expected behavior?
The SDK should build 100% without any issues. 

## What behavior are you observing?
The make step fails at 41%

## Provide the steps to reproduce the issue, if applicable:
Followed the exact steps as mentioned in the sdk guide. Started with a clean slate twice to ensure I wasn't missing anything. Upgraded/reinstalled all the mentioned dependencies. 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [X ] Desktop / Laptop -> Laptop.
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X
![screen shot 2019-01-11 at 10 09 24 am](https://user-images.githubusercontent.com/1750248/51051571-062fa780-1589-11e9-87e9-8024c44ecffc.png)
 ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Thanks @Widea, 

This is a known issue we will be patching on our next release.  In the meantime, please add a virtual destructor to Settings/include/Settings/SettingInterface.h, to the SettingInterface class.  It may be a default virtual destructor.  This will resolve the compile issue.

Let us know if any other issues come up, thanks.

**Comment by frivas** [comment]
Hello, 

This one might help you [#1136](https://github.com/alexa/avs-device-sdk/issues/1136#issuecomment-450365235)
