### ISSUE TITLE
Trying to create the sdk device using beta product

### ISSUE THREAD

**Issue by Widea** [alexa/avs-device-sdk#1166]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
device with beta product id and client id gives "Unrecoverable authorization error"

## What is the expected behavior?
Should run the same way as a prod device

################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_VALUE       #
#       Entering limited interaction mode. 

## Provide the steps to reproduce the issue, if applicable:
Instead of using config.json generated from prod device, use the one created from beta environemnt. 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ X
![screen shot 2019-01-11 at 11 18 24 am](https://user-images.githubusercontent.com/1750248/51054760-a6d69500-1592-11e9-8e4f-83adef574ce9.png)
] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @Widea, this means that you were not able to authorize over LWA / CBL, so the SampleApp went into a limited-functionality mode.  This is to avoid a locked application, or an infinite loop of authorization retry.

Others have asked for guidance on this before, so please see the following:
https://github.com/alexa/avs-device-sdk/issues/1019#issuecomment-431689965
https://github.com/alexa/avs-device-sdk/issues/1017#issuecomment-431443389

Let us know if you need any further input, thanks.

**Comment by Jennydandancai** [comment]
Hi, i am getting the same value, and i have tried all above, i am getting the right client id under other devices and platforms tab, and i also deleted everything under db folder, but i am still getting the same error. one thing i would like to call out is that i registered the device under developer.integ.amazon.com, any help would be appreciated!
