### ISSUE TITLE
Poor documentation about using KITT.AI with AVS SDK 1.11

### ISSUE THREAD

**Issue by jmfrancofraiz** [alexa/avs-device-sdk#1169]
## Briefly summarize your issue:
After switching wake word to kitt.ai in pi.sh make flags, it fails on building. Documentation on using kitt.ai instead of sensory is very poor.

## What is the expected behavior?
Successful build.

################################################################################
Proceeding with installation
################################################################################
[ 34%] Built target AVSCommon
[ 37%] Built target SQLiteStorage
[ 41%] Built target ACL
[ 44%] Built target ADSL
[ 46%] Built target AFML
[ 48%] Built target RegistrationManager
[ 51%] Built target EqualizerImplementations
[ 51%] Built target ContextManager
[ 51%] Built target CapabilitiesDelegate
[ 53%] Built target PlaylistParser
[ 53%] Built target KWD
[ 53%] Built target SpeechEncoder
[ 55%] Built target AudioResources
[ 55%] Built target AudioPlayer
[ 58%] Built target Bluetooth
[ 58%] Built target Equalizer
[ 58%] Built target ExternalMediaPlayer
[ 60%] Built target InteractionModel
[ 62%] Built target Notifications
[ 65%] Built target PlaybackController
[ 65%] Built target SpeakerManager
[ 65%] Built target SpeechSynthesizer
[ 67%] Built target AVSSystem
[ 69%] Built target TemplateRuntime
[ 72%] Built target CBLAuthDelegate
[ 76%] Built target MediaPlayer
[ 79%] Built target CertifiedSender
make[3]: *** No rule to make target '/home/pi/alexa/third-party/snowboy/rpi/libsnowboy-detect.a', needed by 'KWD/KittAi/src/libKITTAI.so'.  Stop.
CMakeFiles/Makefile2:5605: recipe for target 'KWD/KittAi/src/CMakeFiles/KITTAI.dir/all' failed
make[2]: *** [KWD/KittAi/src/CMakeFiles/KITTAI.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 81%] Built target AIP
CMakeFiles/Makefile2:10105: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:2526: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

## Provide the steps to reproduce the issue, if applicable:
I've cloned https://github.com/Kitt-AI/snowboy.git into $THIRD_PARTY_PATH and changed pi.sh to use KITTAI make flags:

CMAKE_PLATFORM_SPECIFIC=(-DKITTAI_KEY_WORD_DETECTOR=ON \
    -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON \
    -DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" \
    -DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include" \
    -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$THIRD_PARTY_PATH/snowboy/rpi/libsnowboy-detect.a \
    -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$THIRD_PARTY_PATH/snowboy/include)

then I try to build as usual with "sudo bash setup.sh config.json"

### What version of the AVS Device SDK are you using?
      1.11.0

### Tell us what hardware you're using:
- [  ] Desktop / Laptop
- [X] Raspberry Pi
- [  ] Other - tell us more:

It's a AIY Voice Kit v1

### Tell us about your OS (Type & version):
- [  ] Linux
- [  ] MacOS 
- [X] Raspbian Stretch
- [  ] Raspbian Jessy
- [  ] Other - tell us more:

**Comment by khassel** [comment]
maybe [this](https://github.com/alexa/avs-device-sdk/issues/1162#issuecomment-453276622) helps.

**Comment by khassel** [comment]
One thing I see is a wrong param in 
`-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$THIRD_PARTY_PATH/snowboy/rpi/libsnowboy-detect.a`
should be 
`-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$THIRD_PARTY_PATH/snowboy/lib/rpi/libsnowboy-detect.a`

You can find a working example in this [Dockerfile](https://gitlab.com/khassel/alexa_sdk_docker/blob/master/build/Dockerfile).

**Comment by dhpp** [comment]
@jmfrancofraiz - can you please advise if @khassel 's suggestion resolved your issue?

**Comment by jmfrancofraiz** [comment]
@dhpp yes, it did!! 

Actually, all the tips are in his Dockerfile. I'll attach the two bash scripts I'd modified to get it to work with kitt.ai in my AIY Voice Kit v1.

[scripts.zip](https://github.com/alexa/avs-device-sdk/files/2761089/scripts.zip)

**Comment by dhpp** [comment]
Thanks @jmfrancofraiz , great to hear that :)
