### ISSUE TITLE
KINDLE and AudioBook support for AVS C++ SDK

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#117]
Hi,

AVS SDK V 1.0.2 release notes is saying that Audioplayer is supported for IHeartRadio only.
Based on that, what are the limitation to fully support KINDLE and AudioBook functionalities using that version of AVS SDK?

V1.0.2 release notes:

> Features
> Native components for the following capability agents are included in this release: Alerts, **AudioPlayer**, SpeechRecognizer, SpeechSynthesizer, and System
> **Supports iHeartRadio**
> Includes a sample application to demonstrate interactions with AVS

Thank you,
Juliano Ribeiro

**Comment by kencecka** [comment]
Hi Juliano,

There are a few limitations related to seeking in an audio stream and playlist handling which caused us to limit initial support to iHeartRadio.  Beyond that, it's largely an issue of testing and QA.  We are planning to support the broader range of content sources, including Kindle and AudioBook in a future release.

Ken
