### ISSUE TITLE
Audio player directive exception

### ISSUE THREAD

**Issue by liunanxuan** [alexa/avs-device-sdk#1170]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The audioplayer directive is abnormal for the corresponding audioItemId of the payload.

### Tell us about your OS (Type & version):
- [* ] Linux
[new_problem.txt](https://github.com/alexa/avs-device-sdk/files/2753927/new_problem.txt)

**Comment by liunanxuan** [comment]
AudioPlayer：
"audioItemId"\:"amzn1.as-ct.v1.Domain\:Application\:DailyBriefing\:TTS#ACRI#url#ACRI#DailyBriefingPrompt.b61381c7-2ba8-49c2-8b92-b82e9cf12a6a\:ChannelError\:1\:ErrorMessageResourceId\:channel_not_available"\

TemplateRuntime:
getPayload={"content"\:{"provider"\:{"name"\:""\,"logo"\:{"sources"\:[{}]}}\

**Comment by dhpp** [comment]
Thanks @liunanxuan - can you please elaborate further on what is the user experience, and is this reproducible?

**Comment by liunanxuan** [comment]
@dhpp Voice input: alexa, what's my flash briefing?
When the news content is played, the cloud will come over the new audioplay directive, and the new directivehas a problem.

**Comment by dhpp** [comment]
Interesting - looking again at the logfile you attached, I see that a daily DailyBriefing successfully started & finished before the problem occurred (when the briefing is invoked a second time).

How are you invoking the daily briefing?  It appears that in the log there is the usual Alexa listening, thinking, speaking output, but the daily briefing does not have this.  Are you invoking this by sending AVS a local audio file of the user saying "Daily Briefing"?  It seems like the first time this works, but the second time it breaks, with AVS believing the channel is not available.  Are you sending the correct Events and updates via the [AudioActivityTracker Interface](https://developer.amazon.com/docs/alexa-voice-service/audioactivitytracker.html)?

**Comment by liunanxuan** [comment]
> Interesting - looking again at the logfile you attached, I see that a daily DailyBriefing successfully started & finished before the problem occurred (when the briefing is invoked a second time).
> 
> How are you invoking the daily briefing? It appears that in the log there is the usual Alexa listening, thinking, speaking output, but the daily briefing does not have this. Are you invoking this by sending AVS a local audio file of the user saying "Daily Briefing"? It seems like the first time this works, but the second time it breaks, with AVS believing the channel is not available. Are you sending the correct Events and updates via the [AudioActivityTracker Interface](https://developer.amazon.com/docs/alexa-voice-service/audioactivitytracker.html)?

 I have told. My voice input: alexa, what's my flash briefing? The first daily briefing is completed, and the finish event will be sent to the AVS cloud. However, the AVS cloud will reply to the new AudioPlay directive, which is not available for the channel. Is this not a problem with the AVS cloud? Previous tests did not have this problem.

**Comment by dhpp** [comment]
Thanks @liunanxuan.  Yes, it wasn't clear to me in your earlier posts that there was a successful Flash Briefing request (ie. it played correctly upon user request), but when requested again, then it failed.

While it looks like this may be a cloud issue, we have found while developing the SDK that often the cloud is in the incorrect state because of how the client is reporting state.  The AudioActivityTracker is something above I mentioned which I'd recommend you double check in your code.  The Events sent in that interface are informing the cloud about the client state, and it may explain the error you're getting next from AVS.

If you don't think that's the cause, we can keep exploring this, thanks.

**Comment by liunanxuan** [comment]
@dhpp Thanks for the support. Please refer to the attachment new_problem.txt I provided. After the successful request to the briefing content in the attached log, the playback is completed. The finished event was sent to the AVS cloud. However, the cloud replied to the audioplay directive that the channel is not available. This is not a question that is requested again.
[new_problem.txt](https://github.com/alexa/avs-device-sdk/files/2766694/new_problem.txt)

**Comment by liunanxuan** [comment]
The latest situation should not be the case. The renderplayinfo command from the AVS cloud is normal.
