### ISSUE TITLE
Try to integrate Sensory Windows library into AVS device SDK on Windows 10 device

### ISSUE THREAD

**Issue by wcchen0519** [alexa/avs-device-sdk#1175]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, I have the Windows wake work engine library and model from Sensory. However, I try to integrate this Windows library(.lib) and model(.snsr) into AVS device SDK as Raspberry Pi platform did, but encounter some compiled errors. I wonder if it could follow the same instructions of Raspberry Pi platform on Windows 10 device.

### What version of the AVS Device SDK are you using?
      <v1.9>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [*] Other - tell us more: Windows 10 64bits

**Comment by dhpp** [comment]
Hi @wcchen0519, thanks for this question.  Unfortunately, we don't currently provide support for Sensory (or other wake word engines) on Windows, per our note [here](https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script).  Please also see the discussion in #998.

We would suggest you reach out to Sensory directly with compile issues at this time.
