### ISSUE TITLE
ExternalMediaPlayer spotify adapter playback wasn't being recognized by AVS.

### ISSUE THREAD

**Issue by maidisula** [alexa/avs-device-sdk#1176]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

ExternalMediaPlayer spotify adapter playback wasn't being recognized by AVS.

## What is the expected behavior?

ExternalMediaPlayer spotify adapter playback was being recognized by AVS.
The playback event and metadata can be show on now playing webpage.

## What behavior are you observing?

The now playing webpage can not show ExternalMediaPlayer spotify adapter playback event and metadata.
![avs](https://user-images.githubusercontent.com/3785111/51368671-6d220300-1b2b-11e9-864b-6f406f947e70.png)

## Provide the steps to reproduce the issue, if applicable:

1.Say, "Alexa play music on spotify"
2.Music starts playing on spotify

### What version of the AVS Device SDK are you using?
      <1.1.0> and <1.1.1> are both not working now, but last week sdk <1.1.0> is working.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [x ] Other - tell us more:Linux

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by zeusshuang** [comment]
Hi AVS team,

I also got the same issue on SDK 1.11. It seems there is no display card information from cloud site.

**Comment by kjkh** [comment]
Hi,

Thanks for bringing this to our attention. We are investigating this internally and will update once we have more information.

**Comment by maidisula** [comment]
It's working fine now, thanks.

**Comment by maidisula** [comment]
It's not working again.

**Comment by kjkh** [comment]
Hi @maidisula,

There was an issue discovered when you initially opened the ticket that was resolved internally. I just tested it and I see the Now Playing page working correctly. Can you retest as well?  If it is not working, can you attach DEBUG9 logs?

**Comment by maidisula** [comment]
Hi @kjkh,
It's working now, thanks.

**Comment by Vaishnavikumara** [comment]
Hi AVS team , I know it seems silly to ask this question , but how play music from spotify on avs enabled devices . Please help . when I say "play spotify " the avs enabled device is  prompting "I cant play from dpotify music on that device " @maidisula  you could be of some help to me
