### ISSUE TITLE
Mediaplayer buffering issue

### ISSUE THREAD

**Issue by bhargavbhoot** [alexa/avs-device-sdk#1177]
## Briefly summarize your issue:
- Media player not buffering the audio data properly during the song playback from saavn/Tunein. 

## What is the expected behavior?
- Media player should buffer the data properly upto 100%. 

## What behavior are you observing?
- Alexa responses to queries are working fine. 
- This issue is seen only during song playback.
- Sometimes it buffers upto 100% and sometimes the buffer percent is stuck between 0% and 1%  resulting in the clipping of the data. For more details attaching the logs.
- This issue was not seen in avs version 1.8

## Provide the steps to reproduce the issue, if applicable:
- run the SampleApp and play the tunein/saavn

## Tell us about your environment:
- avs sdk 1.11
- OS  : linux (openwrt)
- gstreamer version 1.10.5

### Tell us what hardware you're using:
- [ ] Other - ARM cortex A7.

### Tell us about your OS (Type & version):
-  Linux
[AVS_mediaPlayerErrorLogs.txt](https://github.com/alexa/avs-device-sdk/files/2773241/AVS_mediaPlayerErrorLogs.txt)

**Comment by dhpp** [comment]
Hi @bhargavbhoot, have looked at your logs, and reading the issue you are reporting, it would appear that this is a network or server issue, since the SDK and GStreamer implementation log trace looks fine, and furthermore if it cannot always replicate.  This may be related to where you are geographically, as we do see a wide range of this type of issue from our users depending on where they are located.

If you find anything else, such as actual error trace, please update this ticket accordingly.

**Comment by bhargavbhoot** [comment]
Hi @dhpp ,
I understand that there might be some network or server issue. That is why I have tested the AVS SDK 1.8 on the same wifi network. It was working properly.
I want to understand like is there a gstreamer version issue ? As I have gstreamer version 1.10.5 and the latest gstreamer version in 1.14 ,

**Comment by bhargavbhoot** [comment]
[tcp_dump_wireshark.zip](https://github.com/alexa/avs-device-sdk/files/2777562/tcp_dump_wireshark.zip)
This is the tcp dump of the communication with the saavn server while playing the music. 
If we check in the wireshark then when the data is transferred from saavn server to our device then it shows "Ignored Unknown Record". 
What can be the possible issues ?

**Comment by womw** [comment]
Hey @bhargavbhoot 

Can you give us the steps to try to replicate this behaviour? It's unlikely that an updated sdk version is the cause of these network issues. If the problem is related to a network issue then it is outside of our ability to help with this issue.

**Comment by womw** [comment]
To determine whether this is an issue with gstreamer try running the command `gst-launch-1.0 playbin uri=uriToBePlayed` with the song url causing the buffer issue.
