### ISSUE TITLE
Video streaming feature

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1180]
Hi, all

This is not issue on AVS SDK, it just ask the feature for the someone.

In recently, we buy one Echo Show and one IP camera that has Alexa skills. We set those up in our account and we can watch camera’s video on Echo Show through camera’s Alexa skills. Because, our AVS device has HDMI output port, we think that our AVS device can show camera’s video by HDMI screen. Unfortunately, we do the same active in our AVS device and Alexa will respond “cameras don’t not work on this device”. So, we want to ask how we let our AVS device get video streaming from IP cameras and show it up?

If this feature below the AVS SDK team, please close or delete it.
Thanks~~

**Comment by womw** [comment]
If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268.  Thanks!

**Comment by elfdie00475** [comment]
Dear @womw ,

OK,
I will tell him.

Close this issue.

Thanks for your help~~
