### ISSUE TITLE
SQLiteDatabase:open::File specified does not exist.:file path=/data/avs/database/smiscDatabase.db

### ISSUE THREAD

**Issue by phyen808724** [alexa/avs-device-sdk#1185]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Using Android device to run SampleApp
Install path is /data/avs
Run SampleApp command : LD_LIBRARY_PATH=/data/avs/       /data/avs/bin/SampleApp       /data/avs/AlexaClientSDKConfig.json /data/avs DEBUG9
Can't find "smiscDatabase.db" when run SampleApp , log as below :
01-23 15:53:46.853 D/AlexaSampleApp(12325): [  1] 0 ConfigurationNode:initializeSuccess
01-23 15:53:46.874 D/AlexaSampleApp(12325): [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
01-23 15:53:46.874 D/AlexaSampleApp(12325): [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
01-23 15:53:46.874 D/AlexaSampleApp(12325): [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating Equalizer configuration
01-23 15:53:46.874 D/AlexaSampleApp(12325): [  1] 1 InMemoryEqualizerConfiguration:validateConfiguration::Validating default Equalizer state
01-23 15:53:46.875 D/AlexaSampleApp(12325): [  1] 0 SQLiteDatabase:open::File specified does not exist.:file path=/data/avs/database/smiscDatabase.db
01-23 15:53:46.875 D/AlexaSampleApp(12325): [  1] 0 SQLiteMiscStorage:openDatabaseFailed
01-23 15:53:46.875 D/AlexaSampleApp(12325): [  1] 3 MiscDBEqualizerStorage:initialize::Couldn't open misc database. Creating.
01-23 15:53:46.880 E/AlexaSampleApp(12325): [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=/data/avs/database/smiscDatabase.db,error message=unable to open database file
01-23 15:53:46.880 E/AlexaSampleApp(12325): [  1] E SQLiteUtils:createSQLiteDatabaseFailed::Could not create database.
01-23 15:53:46.880 E/AlexaSampleApp(12325): [  1] E SQLiteDatabase:initialize::Database could not be created.:file path=/data/avs/database/smiscDatabase.db
01-23 15:53:46.880 E/AlexaSampleApp(12325): [  1] E SQLiteMiscStorage:createDatabaseFailed
01-23 15:53:46.880 E/AlexaSampleApp(12325): [  1] E MiscDBEqualizerStorage:initializeFailed:reason=Could not create misc database.
01-23 15:53:46.881 E/AlexaSampleApp(12325): [  1] E MiscDBEqualizerStorage:createFailed:reason=Failed to initialize.
01-23 15:53:47.101 V/AlexaSampleApp(12325): [  1] 5 AndroidSLESMediaPlayer:initializeEqualizer
01-23 15:53:47.101 V/AlexaSampleApp(12325): [  1] 7 AndroidSLESMediaPlayer:initializeEqualizer:Bands: =5
01-23 15:53:47.104 V/AlexaSampleApp(12325): [  1] 7 AndroidSLESMediaPlayer:initializeEqualizer:Min=-15,Max=15
01-23 15:53:47.195 V/AlexaSampleApp(12325): [  1] 5 SQLiteDeviceSettingStorage:create
01-23 15:53:47.197 V/AlexaSampleApp(12325): [  1] 5 SQLiteBluetoothStorage:create
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegate:create
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegate:CBLAuthDelegate
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegate:init
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegateConfiguration:create
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegateConfiguration:init
01-23 15:53:47.198 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegateConfiguration:initScopeData
01-23 15:53:47.199 V/AlexaSampleApp(12325): [  1] 9 CBLAuthDelegateConfiguration:initScopeDataSucceeded
01-23 15:53:47.199 V/AlexaSampleApp(12325): [  1] 5 SQLiteCBLAuthDelegateStorage:open
01-23 15:53:47.212 D/AlexaSampleApp(12325): [  1] 0 SQLiteDatabase:open::File specified does not exist.:file path=/data/avs/database/smiscDatabase.db
01-23 15:53:47.213 D/AlexaSampleApp(12325): [  1] 0 SQLiteMiscStorage:openDatabaseFailed
01-23 15:53:47.213 D/AlexaSampleApp(12325): [  1] 0 CapabilitiesDelegate:CapabilitiesDelegateInit::Couldn't open misc database. Creating.
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=/data/avs/database/smiscDatabase.db,error message=unable to open database file
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E SQLiteUtils:createSQLiteDatabaseFailed::Could not create database.
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E SQLiteDatabase:initialize::Database could not be created.:file path=/data/avs/database/smiscDatabase.db
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E SQLiteMiscStorage:createDatabaseFailed
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E CapabilitiesDelegate:initFailed::Could not create misc database.
01-23 15:53:47.213 E/AlexaSampleApp(12325): [  1] E CapabilitiesDelegate:createFailed:reason=CapabilitiesDelegateInitFailed
01-23 15:53:47.214 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:handleAuthorizationFlow
01-23 15:53:47.214 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:handleStarting
01-23 15:53:47.214 V/AlexaSampleApp(12325): [  2] 5 SQLiteCBLAuthDelegateStorage:getRefreshToken
01-23 15:53:47.216 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:handleRefreshingToken
01-23 15:53:47.216 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:requestRefresh
01-23 15:53:47.218 E/AlexaSampleApp(12325): [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=CapabilitiesDelegate
01-23 15:53:47.218 V/AlexaSampleApp(12325): [  1] 5 CBLAuthDelegate:stop
01-23 15:53:49.034 V/AlexaSampleApp(12325): [  2] 5 HttpPost:doPostSucceeded:code=200
01-23 15:53:49.034 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=200
01-23 15:53:49.034 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=200,error=SUCCESS
01-23 15:53:49.035 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:setAuthError:authError=SUCCESS
01-23 15:53:49.035 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:setRefreshToken
01-23 15:53:49.035 V/AlexaSampleApp(12325): [  2] 5 SQLiteCBLAuthDelegateStorage:setRefreshToken
01-23 15:53:49.059 V/AlexaSampleApp(12325): [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=REFRESHED
01-23 15:53:49.077 V/AlexaSampleApp(12325): [  1] 5 SQLiteCBLAuthDelegateStorage:~SQLiteCBLAuthDelegateStorage
01-23 15:53:49.077 V/AlexaSampleApp(12325): [  1] 5 SQLiteCBLAuthDelegateStorage:close
01-23 15:53:49.078 V/AlexaSampleApp(12325): [  1] 5 SQLiteDeviceSettingStorage:close

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Android P device

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Android P device

**Comment by visayamv** [comment]
Hi @phyen808724 , make sure that the "/data/avs/database/" directory exists and that are able to create files in there

**Comment by mavamazon** [comment]
Hi @phyen808724!

Please let us know if you were able to resolve the problem using the @visayamv's recommendation?

**Comment by phyen808724** [comment]
It is workable.
Thanks.
