### ISSUE TITLE
Unable to play my Release Radar and Discover Weekly from spotify

### ISSUE THREAD

**Issue by maidisula** [alexa/avs-device-sdk#1187]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Unable to play my Release Radar and Discover Weekly from spotify.

## What is the expected behavior?

Speaker starts playing release radar or discover weekly from spotify.

## What behavior are you observing?

Alexa response:I don't see the playlist release radar.

## Provide the steps to reproduce the issue, if applicable:

1.Say "Alexa, play my release radar".

### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ x] Other - tell us more:Linux

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @maidisula , did it work for you before or did the issue happen only recently?

**Comment by maidisula** [comment]
Hi @visayamv ,This is my first time playing the release radar from spotify.

**Comment by visayamv** [comment]
Hi @maidisula , I see. I am asking the team responsible if this is currently supported. We have also tried it on our end, and it apparently the stations you listed are not supported.

**Comment by maidisula** [comment]
Hi @visayamv , Thanks, but why Spotify creates these test cases if Alexa doesn't support these stations.


![avs_radar](https://user-images.githubusercontent.com/3785111/51720958-a22dd880-208a-11e9-8f4f-645bc64a9f05.png)

**Comment by visayamv** [comment]
Hi @maidisula , I have forwarded your inquiry to the certification team.

**Comment by maidisula** [comment]
Hi @visayamv , OK, thanks.

**Comment by visayamv** [comment]
Hi @maidisula , Before testing, go to the Spotify app. Using the Spotify account you will test search for the playlists (Release Radar and Discover Weekly) and "Follow" the playlist. (There will be a 'follow' button when you select the playlist.)

**Comment by maidisula** [comment]
Hi @visayamv , Thank you very much, It's working fine.
