### ISSUE TITLE
[AVS-1.11]When AVS reply alexa keyword. It will trigger by itself

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1188]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I say 'Alexa,message'
The AVS will reply 'Messaging with Alexa is not supported on this device. You can use the Alexa app instead.'

It will heard first Alexa as next wakeup word and enter to listening mode again

## What is the expected behavior?

Don't enter to listening mode when it speaking alexa by itself

## What behavior are you observing?

It will heard first Alexa as next wakeup word and enter to listening mode again

 Does it could bypass this case?
How do we get reply TTS? One idea is when I know AVS will speaking alexa keyword by itself. We could disable KWD function during speaking to idle status 

## Provide the steps to reproduce the issue, if applicable:

Alexa,message

### What version of the AVS Device SDK are you using?
      <1.11>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:

ARM CA7

### Tell us about your OS (Type & version):
- [ *] Linux - 4.9
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi, @yuan0258 , as mentioned here: https://github.com/alexa/avs-device-sdk/issues/1020 , disabling the keyword when device is speaking will not allow barge-in which breaks the interaction model. 

I would suggest to look for an acoustic echo cancellation solution front end (which can be done in the audio signal processor hardware) which removes output of the speaker from the microphone input.

**Comment by yuan0258** [comment]
@visayamv , if the AEC solution is too bad. Could we get server reply data which contain keyword information? So we have some possible to skip this case?

**Comment by mavamazon** [comment]
Hi @yuan0258!

The keyword could be changed and this becomes impractical to consider all the cases. Another major problem is that Alexa cannot modify content generated by external providers, for example if she reads an audiobook she will not be able to remove words "Alexa, computer, etc.." from the text. I believe AEC is essential and very common for the voice interaction and I wouldn't expect Alexa to handle this problem in a different way.

**Comment by yuan0258** [comment]
@visayamv , Thanks your reply. I close this issue
