### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by nunokid** [alexa/avs-device-sdk#119]
I integrated customize board (ubuntu arm64 16.04).
I follow below guide.
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide

Our library path is "/home/ubuntu/AVS_Demo/local-build".

but, I met below errors.

ubuntu@localhost:~$ cd AVS_SDK/avs-device-sdk/
ubuntu@localhost:~/AVS_SDK/avs-device-sdk$ cd BUILD/
ubuntu@localhost:~/AVS_SDK/avs-device-sdk/BUILD$ cmake /home/ubuntu/AVS_SDK/avs-device-sdk/ -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DCMAKE_PREFIX_PATH=/home/ubuntu/AVS_Demo/local-build -DCMAKE_INSTALL_PREFIX=/home/ubuntu/AVS_Demo/local-build

[Error]
###############################################################################
#                                                                             #
# ERROR:                                                                      #
# AlexaClientSDK must not be built in the AlexaClientSDK source directory.    #
#                                                                             #
# You must run cmake in a separate build directory completely outside the     #
# the source directory.                                                       #
#                                                                             #
# Source Directory:                                                           #
#     /home/ubuntu/AVS_SDK/avs-device-sdk                                     #
# Build Directory:                                                            #
#     /home/ubuntu/AVS_SDK/avs-device-sdk                                     #
#                                                                             #
# NOTE:                                                                       #
# Since you have tried to create an in-source build already, CMake may have   #
# created some files and directories in the source tree. To find these files, #
# run:                                                                        #
#     $ git status                                                            #
#                                                                             #
# To remove these files, simply use 'rm' on the appropriate files and         #
# directories.                                                                #
#                                                                             #
###############################################################################
CMake Error at build/cmake/DisallowOutOfSourceBuilds.cmake:59 (message):
  In-source-build detected, quitting!
Call Stack (most recent call first):
  build/cmake/DisallowOutOfSourceBuilds.cmake:63 (DisallowOutOfSourceBuilds)
  build/BuildDefaults.cmake:7 (include)
  CMakeLists.txt:7 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/AVS_SDK/avs-device-sdk/CMakeFiles/CMakeOutput.log".
ubuntu@localhost:~/AVS_SDK/avs-device-sdk/BUILD$

Plz let me now cmake build method.

Thx.

**Comment by nunokid** [comment]
I moved to lib path and try again.
I met below error.


ubuntu@localhost:~/AVS_Demo/local-build$ cmake /home/ubuntu/AVS_SDK/avs-device-sdk -DSENSORY_KEY_WORD                                                                                                                 _DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libsnsr.a -DS                                                                                                                 ENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DGSTREAMER_MEDIA_PLAY                                                                                                                 ER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libportaudio.a -DPORT                                                                                                                 AUDIO_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DCMAKE_PREFIX_PATH=/home/ubuntu/AVS_Demo                                                                                                                 /local-build -DCMAKE_INSTALL_PREFIX=/home/ubuntu/AVS_Demo/local-build
###############################################################################
#                                                                             #
# ERROR:                                                                      #
# AlexaClientSDK must not be built in the AlexaClientSDK source directory.    #
#                                                                             #
# You must run cmake in a separate build directory completely outside the     #
# the source directory.                                                       #
#                                                                             #
# Source Directory:                                                           #
#     /home/ubuntu/AVS_SDK/avs-device-sdk                                     #
# Build Directory:                                                            #
#     /home/ubuntu/AVS_SDK/avs-device-sdk                                     #
#                                                                             #
# NOTE:                                                                       #
# Since you have tried to create an in-source build already, CMake may have   #
# created some files and directories in the source tree. To find these files, #
# run:                                                                        #
#     $ git status                                                            #
#                                                                             #
# To remove these files, simply use 'rm' on the appropriate files and         #
# directories.                                                                #
#                                                                             #
###############################################################################
CMake Error at build/cmake/DisallowOutOfSourceBuilds.cmake:59 (message):
  In-source-build detected, quitting!
Call Stack (most recent call first):
  build/cmake/DisallowOutOfSourceBuilds.cmake:63 (DisallowOutOfSourceBuilds)
  build/BuildDefaults.cmake:7 (include)
  CMakeLists.txt:7 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/AVS_SDK/avs-device-sdk/CMakeFiles/CMakeOutput.log".
ubuntu@localhost:~/AVS_Demo/local-build$ cmake /home/ubuntu/a -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSOR                                                                                                                 Y_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libsnsr.a -DSENSORY_KEY_WORD_DETEC                                                                                                                 TOR_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON                                                                                                                  -DPORTAUDIO_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/ho                                                                                                                 me/ubuntu/AVS_Demo/local-build/include -DCMAKE_PREFIX_PATH=/home/ubuntu/AVS_Demo/local-build -DCMAKE_                                                                                                                 INSTALL_PREFIX=/home/ubuntu/AVS_Demo/local-build
alexa-rpi/            assistant-sdk-python/ avs-device-sdk/
ubuntu@localhost:~/AVS_Demo/local-build$ cmake /home/ubuntu/a -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSOR                                                                                                                 Y_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libsnsr.a -DSENSORY_KEY_WORD_DETEC                                                                                                                 TOR_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON                                                                                                                  -DPORTAUDIO_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/ho                                                                                                                 me/ubuntu/AVS_Demo/local-build/include -DCMAKE_PREFIX_PATH=/home/ubuntu/AVS_Demo/local-build -DCMAKE_                                                                                                                 INSTALL_PREFIX=/home/ubuntu/AVS_Demo/local-build
alexa-rpi/            assistant-sdk-python/ avs-device-sdk/
ubuntu@localhost:~/AVS_Demo/local-build$ cmake /home/ubuntu/avs-device-sdk -DSENSORY_KEY_WORD_DETECTO                                                                                                                 R=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libsnsr.a -DSENSORY_K                                                                                                                 EY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DGSTREAMER_MEDIA_PLAYER=ON -D                                                                                                                 PORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/ubuntu/AVS_Demo/local-build/lib/libportaudio.a -DPORTAUDIO_IN                                                                                                                 CLUDE_DIR=/home/ubuntu/AVS_Demo/local-build/include -DCMAKE_PREFIX_PATH=/home/ubuntu/AVS_Demo/local-b                                                                                                                 uild -DCMAKE_INSTALL_PREFIX=/home/ubuntu/AVS_Demo/local-build
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
No build type specified, defaulting to Release.
Creating the build directory for the AlexaClientSDK with build type: RELEASE
Creating AlexaClientSDK with keyword detector type: Sensory
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Found gstreamer-1.0, version 1.12.1
--   Found gstreamer-app-1.0, version 1.10.4
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /home/ubuntu/AVS_Demo/local-build/lib/libcurl.so (found suitable version "7.50.2", min                                                                                                                 imum required is "7.43.0")
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ACL with build type: RELEASE
Creating ACL with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the AuthDelegate with build type: RELEASE
Creating AuthDelegate with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ADSL with build type: RELEASE
Creating ADSL with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the AFML with build type: RELEASE
Creating AFML with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ContextManager with build type: RELEASE
Creating ContextManager with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the MediaPlayer with build type: RELEASE
Creating MediaPlayer with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the PlaylistParser with build type: RELEASE
Creating PlaylistParser with keyword detector type: Sensory
Totem-Pl-Parser based playlist parser will not be built, and the playlist parser is disabled.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the SENSORY with build type: RELEASE
Creating SENSORY with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the CapabilityAgents with build type: RELEASE
Creating CapabilityAgents with keyword detector type: Sensory
Creating the build directory for the AIP with build type: RELEASE
Creating AIP with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Alerts with build type: RELEASE
Creating Alerts with keyword detector type: Sensory
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.11.0
Creating the build directory for the AudioPlayer with build type: RELEASE
Creating AudioPlayer with keyword detector type: Sensory
Creating the build directory for the SpeechSynthesizer with build type: RELEASE
Creating SpeechSynthesizer with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Integration with build type: RELEASE
Creating Integration with keyword detector type: Sensory
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Please fill /home/ubuntu/AVS_Demo/local-build/Integration/AlexaClientSDKConfig.json before you exe                                                                                                                 cute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
Creating the build directory for the ApplicationUtilities with build type: RELEASE
Creating ApplicationUtilities with keyword detector type: Sensory
Creating the build directory for the DefaultClient with build type: RELEASE
Creating DefaultClient with keyword detector type: Sensory
Creating the build directory for the SampleApp with build type: RELEASE
Creating SampleApp with keyword detector type: Sensory
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
FATALDoxygen is required to generate documentation.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/AVS_Demo/local-build
ubuntu@localhost:~/AVS_Demo/local-build$

**Comment by kencecka** [comment]
Hi @nunokid,

The SDK cmake scripts are set up to error out if you try to build from anywhere inside the source directory.  In your first couple of logs, you had your sources in **/home/ubuntu/AVS_SDK/avs-device-sdk**, and you are trying to build in **/home/ubuntu/AVS_SDK/avs-device-sdk**/BUILD.  The cmake scripts detect that BUILD is inside **/home/ubuntu/AVS_SDK/avs-device-sdk** and report an error.

In your final attempt, I see that you have moved your build directory to /home/ubuntu/AVS_Demo/local-build, which is outside of the source directory, and the cmake process completes successfully.

I see a number of messages about GTest, as well as a note about Doxygen, but no real errors.  The GTest messages are a known issue with googletest, and you can disregard them.  Doxygen is optional, and only needed to regenerate the [API documentation](https://alexa.github.io/avs-device-sdk/).

Did you have additional concerns, or are you able to build successfully now?

Ken

**Comment by nunokid** [comment]
Hi @kencecka 

Thanks for update.
After the last attempt I'm ongoing.
After modifying the AlexaClientSDKConfig.json file, I ran make and the following error occurred.
Please give me advice on this error.



ubuntu@localhost:~/AVS_Demo/local-build/Integration$ vi AlexaClientSDKConfig.json
ubuntu@localhost:~/AVS_Demo/local-build/Integration$ cd ..
ubuntu@localhost:~/AVS_Demo/local-build$ make -j3
[  0%] Building CXX object ThirdParty/googletest-release-1.8.0/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  1%] Building CXX object ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachmentWriter.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSDirective.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessage.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessageHeader.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/CapabilityAgent.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/EventBuilder.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/build.make:62: recipe for target 'ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o' failed
make[2]: *** [ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o] Error 4
CMakeFiles/Makefile2:1107: recipe for target 'ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/all' failed
make[1]: *** [ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/ExceptionEncounteredSender.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/HandlerAndPolicy.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/MessageRequest.cpp.o
[  6%] Linking CXX static library libgtest.a
[  6%] Built target gtest
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/NamespaceAndName.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/DialogUXStateAggregator.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Configuration/ConfigurationNode.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Executor.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/JSONUtils.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ConsoleLogger.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Level.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntry.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntryBuffer.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntryStream.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Logger.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LoggerSinkManager.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LoggerUtils.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ModuleLogger.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ThreadMoniker.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/RequiresShutdown.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/StringUtils.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskQueue.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskThread.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Timer.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimeUtils.cpp.o
[ 16%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/UUIDGeneration.cpp.o
[ 16%] Linking CXX shared library libAVSCommon.so
[ 18%] Built target AVSCommon
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tflack** [comment]
@nunokid I think my error was more apparent since it specifically stated permissions issues in the dump but I also ran into some issues running the make on the sdk.  The solution for my issue was running `sudo make -j3` for the sdk.

@kencecka I was going to suggest an edit to the wiki for this issue but didn't know where to make the request.

**Comment by kencecka** [comment]
Hi @nunokid,

The AlexaClientSDKConfig.json is used at runtime, but does not have anything to do with compiling, so it is unrelated to the compile error you are getting.

Looking at your log, I see that you are getting a "c++: internal compiler error".  Can you run your build as follows and post the result here: `make VERBOSE=1`

I'm particularly interested in seeing the full compile line that results in the compiler error.

Also, can you tell me what compiler you are using and where you got it from?
- Looks like it's GCC 5?  What specific version?
- Is it a cross-compiler, or are you doing a native build on your board?
  - If you are doing a native build on your board, does the build work better if you don't run a parallel make (remove the -j3 flag)?  It may be that you are running out of memory.
- Did you build the compiler yourself?  Did it come with a linux distribution?  Is it a Linaro toolchain?
- Can you send me the full output of running `aarch64-linux-gnu-gcc -v` (using your compiler's name)?

Thanks,
Ken

**Comment by nunokid** [comment]
Dear @kencecka 

I delete the folder and try again. I will give you the results again.
Plz check below.

ubuntu@localhost:~$ aarch64-linux-gnu-gcc -v
Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4)

**Comment by kencecka** [comment]
Looks like you are using a modern linaro toolchain, so I would not expect compiler bugs.  If you are buiding on a machine with limited memory, I would suggest trying without a parallel build (no -j flag to make) and see if it works better for you.

Ken
