### ISSUE TITLE
Failed to create Sample Application RSPI3B+

### ISSUE THREAD

**Issue by Awazleon** [alexa/avs-device-sdk#1191]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I tried to build the Sample application without success. The RSPI freezes after a while. It's a new RSPI3B+ just received couple of weeks ago and running the latest "Raspbian Stretch with desktop" version. I carefully followed the instruction found on the "Raspberry Pi Quick Start Guide with Script" web page but didn't reach success.
## What is the expected behavior?

To get Sample Application built
## What behavior are you observing?

The RSPI stays stuck at 57%. See the screen copy underneath. I did the copy after to run the build a second time. Because the freeze, I had to restart the RSPI. I can of course restart from the beginning by deleting all files already installed if you need the whole copy of the installation.
## Provide the steps to reproduce the issue, if applicable:

This happend after to run the "sudo bash setup.sh config.json -s nnnnnn" command
### What version of the AVS Device SDK are you using?
      <1.11>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

################################################################################
Proceeding with installation
################################################################################
[ 35%] Built target AVSCommon
[ 38%] Built target SQLiteStorage
[ 42%] Built target ACL
[ 45%] Built target ADSL
[ 47%] Built target AFML
[ 47%] Built target RegistrationManager
[ 50%] Built target EqualizerImplementations
[ 50%] Built target ContextManager
[ 50%] Built target CapabilitiesDelegate
[ 52%] Built target PlaylistParser
[ 54%] Built target KWD
[ 54%] Built target SpeechEncoder
[ 57%] Built target AudioResources
[ 57%] Building CXX object CapabilityAgents/AudioPlayer/src/CMakeFiles/AudioPlayer.dir/AudioPlayer.cpp.o
[ 57%] Building CXX object CapabilityAgents/Bluetooth/src/CMakeFiles/Bluetooth.dir/Bluetooth.cpp.o

**Comment by visayamv** [comment]
Hi @Awazleon, it seems this issue is related to [1014](https://github.com/alexa/avs-device-sdk/issues/1014) or [1167](https://github.com/alexa/avs-device-sdk/issues/1167). It is suspected that this could be a memory issue or too many parallel jobs that's consuming 100% CPU.

Try:

1. Editing the setup.sh and look for "make SampleApp -j2" instances and replace it with "make SampleApp -j1"
2. Run the setup.sh once again and monitor the memory usage also via "free -h"

**Comment by Awazleon** [comment]
Hello,
Thx for your quick answer. Modifying setup.sh as suggested fix the issue. -j1 is the good setup.
I was able to get the Sample application built but now I'm facing some other issues. It doesn't work and I get some error messages when I start it. I have to investigate a bit and identify the message and could be open a new issue thread. 
Have a nice day
