### ISSUE TITLE
Playing custom Voice announcements on my Alexa AVS SDk enabled Linux platform

### ISSUE THREAD

**Issue by tellapati** [alexa/avs-device-sdk#1192]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi all,

Thank you very much for your time.

On my Alexa AVS SDK enabled device, I would like to play my custom announcements like

Network Reset Case - 'Network Reset Initiated. The device might take few seconds to reboot'
Firmware Upgrade - 'Firmware Upgrade initiated. Pls do not power-off the device'
Factory Reset - 'The Factory Reset will erase all the device settings. Pls tap volume up button once to confirm'
Now please help me to understand

Do I need to create my own TTS files (wave files) with the help of some TTS service. If yes, what is the service I need to use to create these announcement wave files which I could store on my Alexa AVS SDK enabled device? I need these wave files with Indian English.

Does the Amazon Certification process restrict us from creating our own announcement wave files?

Do I have any other options to create and play my custom voice announcements on my device without violating any Amazon certification guidelines.

Any help in this regard will be highly appreciated. 

Thanks in advance.

Regards,
Tellapati.

## Tell us about your environment:
Arm based embedded system

### What version of the AVS Device SDK are you using?
   1.10

### Tell us what hardware you're using:
ARM based Linux embedded system

### Tell us about your OS (Type & version):
Linux

**Comment by visayamv** [comment]
Hi @tellapati , I have forwarded your inquiry to the certification team.

**Comment by visayamv** [comment]
Hi @tellapati , upon conferring, kindly contact your Amazon Business Development Representative to help on your inquiries about certification.

**Comment by tellapati** [comment]
Many thanks @visayamv for your help in this regard.
