### ISSUE TITLE
Question : speech recognizer enhancement

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1195]
Hi AVS team,

Just a question about "Speech Recognizer Enhancement" option defined in development console.
Is it for V2.0 ?  What will be different if I enabled this option? only to support new audio format ?

Thanks,

**Comment by mavamazon** [comment]
Hi @zeusshuang!

Please contact your BD or use [the Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) for more details on this question.

**Comment by zeusshuang** [comment]
Hi @mavamazon ,

Thanks and I will contact our BD.
