### ISSUE TITLE
Is it possible to add alexa skill to the sample app for testing reasons? 

### ISSUE THREAD

**Issue by edi4101** [alexa/avs-device-sdk#1199]

**Comment by mavamazon** [comment]
Hi!

Skills could be added to the device from the Alexa App. Once you add any, there is usually no need in any setup on the SDK side. In most of the cases skills operate on the features already existing in Alexa. An exception could be a visual skill, for which SDK does not provide a proper rendering engine at the moment.

**Comment by visayamv** [comment]
Hi @edi4101 , I hope that answers your question. I'll be closing this issue, but feel free to reopen if you have further questions regarding this.
