### ISSUE TITLE
Resume spotify command is not working on spotify

### ISSUE THREAD

**Issue by maidisula** [alexa/avs-device-sdk#1202]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

![avs_resume](https://user-images.githubusercontent.com/3785111/51882998-079c0500-23bc-11e9-9559-e1c6e858d25c.png)

Alexa responds to me "I cann't resume" when I say "Alexa, resume spotify"
## What is the expected behavior?

Playback resumes at the same place as it was paused 
## What behavior are you observing?

Alexa responds to me "I cann't resume" when I say "Alexa, resume spotify"
## Provide the steps to reproduce the issue, if applicable:

1.Alexa, Play Spotify.
2.Open Spotify app on phone.
3.Pause playback via phone app.
4.Alexa, resume Spotify.
### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ x] Other - tell us more:Linux

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by maidisula** [comment]
Say "Alexa, resume" is working.

**Comment by mavamazon** [comment]
Hi!

If I got you right and "Alexa resume" resumes Spotify in the use case you described above I would say that this is how Alexa-Spotify interaction is designed. But to be clear, were you able to resume Spotify by saying "Alexa, resume Spotify" under any other circumstances / on other devices?

**Comment by maidisula** [comment]
Hi @mavamazon , Echo is OK.

**Comment by kclchan** [comment]
Thanks for reporting this issue, we will fix this in a future release of the SDK.  Thanks!

**Comment by kclchan** [comment]
This has been fixed in v1.14 of the SDK release.  Thanks!
