### ISSUE TITLE
The Amazon Music continues to play for a few seconds when change music source from Amazon to Spotify

### ISSUE THREAD

**Issue by maidisula** [alexa/avs-device-sdk#1204]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The music from Amazon Music continues to play for a few seconds and then Spotify Music starts to play.
Please see the below video link to view details of this issue.
https://www.dropbox.com/s/vockk2k2glybz0e/amazon-to-spotify.mp4?dl=0
## What is the expected behavior?

Music from Spotify should play at once.
## What behavior are you observing?

The music from Amazon Music continues to play for a few seconds and then Spotify Music starts to play.
## Provide the steps to reproduce the issue, if applicable:

1.Alexa, play Amazon music.
2.Alexa, play music by Rihanna on Spotify.
### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [x ] Other - tell us more:Linux

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!

Thank you for reporting this. We are going to investigate that and provide you with more context. Meanwhile it will be very helpful if you provide us with the SDK logs (preferably DEBUG9 logs) attached as a file.

**Comment by maidisula** [comment]
Hi @mavamazon , I have found the cause of this issue, the command that "play music by Rihanna on Spotify" takes more time than "play spotify", so the time to the spotify adapter player acquire focus is later than the audio player get the resume focus, so the audio player continues to play for a few seconds and then Spotify Music starts to play.
[avs-amazon-to-spotify.log](https://github.com/alexa/avs-device-sdk/files/2815462/avs-amazon-to-spotify.log)

**Comment by celinval** [comment]
Thanks for the update, @maidisula! I'll add this issue to our backlog.

**Comment by kclchan** [comment]
This is fixed already.  Please re-open it if the issue still exist.
