### ISSUE TITLE
How to set android system property in SampleApp

### ISSUE THREAD

**Issue by phyen808724** [alexa/avs-device-sdk#1205]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
We want to build in AVS sdk on Android devices.
We want to set Android system property in some status of SampleApp.
How to do about this?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Qualcomm SDM450

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Android P device

**Comment by mavamazon** [comment]
Hi!

You can take a look at this file:
`SampleApp/src/UIManager.cpp`
There you can choose the callback that handles the state of your interest and set property or perform any other reaction. We do not provide support for general platform development though.

**Comment by phyen808724** [comment]
OK , Thanks for your help.
