### ISSUE TITLE
Stop Music timer is not working on Spotify

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1206]
Hi AVS team,

SDK 1.11 .

Alexa, play music on Spotify
Alexa, stop music in one minute
--- after one minute, the music will not stop.

If I test this command for Amazon Music, it's working.
The Echo is working on both Spotify and Amazon Music.

[3.log](https://github.com/alexa/avs-device-sdk/files/2812069/3.log)

**Comment by zeusshuang** [comment]
Hi @mavamazon ,

Will it plan to add this fix in next SDK release ?

**Comment by visayamv** [comment]
Hi @zeusshuang , we are working on the fix. Please direct your question for the timeline to the Amazon Business Development Representative. Thanks.

**Comment by kclchan** [comment]
This issue is fixed in 1.13 of the SDK.  Thanks!
