### ISSUE TITLE
How to change sink at runtime?

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1209]
Hi AVS team,

I get a requirement to support dynamically changing the alsa sink device at run time. That means when user is playing music with avs client, the user can choose different sinks between multiple alsa sinks.

I  implemented a interface for MediaPlayer as below:
```
void MediaPlayer::onProfileChanged(const std::string profile) {                                           
    ACSDK_DEBUG5(LX(__func__));                                                                               
    std::string sinkName;                                                                                     
    sinkName += "dawser:DAP-PRESET="+profile;                                                                 
                                                                                                              
    g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);                                                   
    gst_element_set_state (m_pipeline.pipeline, GST_STATE_NULL);                                              
                                                                                                              
    g_object_set(m_pipeline.audioSink, "device", sinkName.c_str(), NULL);                                     
                                                                                                              
    gst_element_set_state (m_pipeline.pipeline, GST_STATE_PLAYING);                                           
    g_object_set(m_pipeline.audioSink, "sync", FALSE, NULL);                                                  
    ACSDK_DEBUG5(LX("onDolbyConfigChanged").d("sinkName", sinkName));                                         
}
```
I originally wrote a smart audio application based on gstreamer to verified this process , in which, a timer will change the audio sink during the play back. which works good, the new sink device takes effect immediately. And the output sound takes the new profile immediately. 

But when I integrate this feature into the MediaPlayer of AVS SDK. From the log the  new sink device is changed and opened, but the output sound is stopped and can't resume.

Can you give some guidance on how to make it work?

Thanks

**Comment by visayamv** [comment]
Hi @subjectxbj , since SDK only support SDK static pipeline, please refer to gstreamer's guidelines on dynamically manipulating pipelines: https://gstreamer.freedesktop.org/documentation/application-development/advanced/pipeline-manipulation.html .  You might want to check the "changing the elements in the pipeline" section.

**Comment by subjectxbj** [comment]
Thanks
