### ISSUE TITLE
Server side disconnect more frequently since 2019/2/4

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1214]
SDK 1.9

Hi SDK team,

Recently we found the Server-Side disconnection occurs more frequently than before. Originally it disconnect once every 50 minutes, but recently we found it disconnect once every 20~30 minutes since 2019/2/4.

Is this an expected behavior, and why made this change?

Thanks,
Arthman

**Comment by womw** [comment]
Hey @subjectxbj thanks for posting,

Please provide more information following [this template](https://github.com/alexa/avs-device-sdk/blob/master/issue_template.md) You can get more detailed logs by running with the following steps:
Enable DEBUG9 by running cmake with -DCMAKE_BUILD_TYPE=DEBUG and enabling DEBUG9 mode with $TZ=UTC ./SampleApp /root/BUILD/Integration/AlexaClientSDKConfig.json DEBUG9

Please capture the entire log and attach the file.

Server-Side disconnects are not a regular occurrence  when running the sdk and the issue may be a network issue on your end.
