### ISSUE TITLE
I need to Capture Audio buffer  from the microphone  and write  the buffer on to a file

### ISSUE THREAD

**Issue by WilliamVJacob** [alexa/avs-device-sdk#1215]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I need to Capture Audio buffer from the microphone  and write  the buffer on to a file . For eg 
if i say   "Alexa, whats the weather", i need to capture this audio (the captured data   can be raw data or it can be  in audio format)  and store it in  a file .
## What is the expected behavior?
when i say "Alexa, whats the weather" . a file will be created in my /tmp directory  containing my audio input buffer.

### What version of the AVS Device SDK are you using?
      AVS 1.9.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
I am using alexa sdk on a mips architecture device 

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Linux kernel 3.13

**Comment by womw** [comment]
Hey @WilliamVJacob thanks for posting,

As per the [Alexa Service Agreements](https://developer.amazon.com/support/legal/alexa/alexa-voice-service/terms-and-agreements#alexa-service-requirements) point 2.3, you can not store copies of any audio from the user.

I hope this answers your question and I will be closing this issue.
