### ISSUE TITLE
brew install curl --with-nghttp2 errors saying "invalid option: --with-nghttp2"

### ISSUE THREAD

**Issue by seichert** [alexa/avs-device-sdk#1216]
## Briefly summarize your issue:
I was following the macOS Quick Start Guide from the wiki at:
https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

I reached step 3 and tried:
```
brew install curl --with-nghttp2
```

## What is the expected behavior?
Curl is installed with nghttp2 

## What behavior are you observing?
brew fails, shows the usage information and reports:
```
Error: invalid option: --with-nghttp2
```

## Provide the steps to reproduce the issue, if applicable:
Follow the macOS Quick Start Guide

## Tell us about your environment:
macOS Mojave 10.14.3
brew formula up to date as of Feb 6, 2019

## Notes
The options for curl were removed on January 16 with this commit:
https://github.com/Homebrew/homebrew-core/commit/7f9bfa679229a6837d2d8ba8a08bc6154f0ed4d4

**Comment by womw** [comment]
hello @seichert thank you for posting

Recent changes to brew has removed the --with-nghttp2 option from curl. We have updated our quick start wiki with the new steps. Please try following them and let us know if that resolves your issue.

**Comment by seichert** [comment]
@womw - Your update to use `brew install curl-openssl` looks good to me.
