### ISSUE TITLE
Running cmake doxygen results in "/home/pi/doxygen source directory does not exist"

### ISSUE THREAD

**Issue by guruprasad363** [alexa/avs-device-sdk#1217]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I followed the exact same steps mentioned in Raspberry Pi quick start guide. While installing dependencies, I get the  error "home/pi/doxygen does not exist" for
 "sudo apt-get -y
install git gcc

cmake build-essential libsqlite3-dev libcurl4-openssl-dev libfaad-dev \
libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev \
gstreamer1.0-plugins-good libasound2-dev doxygen
"

### Tell us what hardware you're using:
- Raspberry Pi

### Tell us about your OS (Type & version): 
- [x] Raspbian Stretch

**Comment by womw** [comment]
Hey @guruprasad363 thanks for the post,

Looking at your error it looks like an error in our formatting in the wiki. The following command should be run as one line
`sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good libasound2-dev doxygen`

We will update our documentation to fix this mistake.

Alternatively you can also setup the sample app using the setup script in this [link](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script)

**Comment by womw** [comment]
@guruprasad363 did the new command fix this issue?

We've updated our document to fix this error
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#install-dependencies

**Comment by guruprasad363** [comment]
Hey @womw,

Ya, it fixed the issue. Thank you for your time.
