### ISSUE TITLE
 - Windows build fails

### ISSUE THREAD

**Issue by eyalber** [alexa/avs-device-sdk#1219]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
Can't finish SDK installation using setup file, no build files are generated.

## Briefly summarize your issue:

When running the setup.sh, after cloning all objects, an error is thrown with the following details: 

## What is the expected behavior?

Finish the installation successfully

## What behavior are you observing?

An error is thrown: `
cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
`

## Provide the steps to reproduce the issue, if applicable:

Follow the installation guide for windows on the wiki page

### What version of the AVS Device SDK are you using? 
       Latest

### Tell us what hardware you're using:
- Laptop/Desktop

### Tell us about your OS (Type & version):
- Windows

**Comment by eyalber** [comment]
Does somebody know how to fix it?

**Comment by womw** [comment]
Hey @eyalber thanks for posting,

Do you think it's possible to post the full output to get more context about this error? Thanks.

**Comment by eyalber** [comment]
@womw Yes, I will post it later this day.

**Comment by kclchan** [comment]
Hi @eyalber, are you still seeing the issue?

**Comment by eyalber** [comment]
Oh sorry my bad, I forgot about it 😅 
I will check again tomorrow to see what happens and I'll inform you c:

**Comment by eyalber** [comment]
It's fixed now
