### ISSUE TITLE
macOS Quick Start Guide - Step 2 is no longer needed

### ISSUE THREAD

**Issue by seichert** [alexa/avs-device-sdk#1220]
## Briefly summarize your issue:
Not a big deal, but step 2 for installing `openssl` via Homebrew is no longer needed and may create confusion for new developers.  When you execute step 3 to install `curl-openssl`, it will bring in `openssl` as a dependency.  Furthermore, you don't need to link the openssl include directory.  However, you do need to do `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` before running the `cmake` command so that `libcrypto` can be found by `pkg-config`.

## Tell us about your environment:
macOS Mojave with Homebrew

### What version of the AVS Device SDK are you using?
1.11.0

### Tell us what hardware you're using:
Macbook

### Tell us about your OS (Type & version):
macOS  Mojave

**Comment by womw** [comment]
Thanks for the feedback @seichert we'll look into updating our documentation. Will be closing this issue but feel free to reopen if you have more feedback.
