### ISSUE TITLE
CPU Usage 100% with script in Autostart.

### ISSUE THREAD

**Issue by t4rif4ri** [alexa/avs-device-sdk#1221]
## Briefly summarize your issue:
CPU usage to 100% if alexa script starting with autostart routine after booting my pi.

## What is the expected behavior?
Normal cpu usage with start of alexa

## What behavior are you observing?
If i start alexa with "sudo bash startscript.sh" it runs smooth and cpu usage is not rising significant. Without Alexa 12% and with Alexa running maybe 16%.
If i put the script into the autostart routine to /etc/xdg/lxsession/LXDE-pi/autostart with @/home/pi/alexa/startscript.sh 
the cpu usage goes to 100%. 

## Provide the steps to reproduce the issue, if applicable:
Tried a few times with manual start. No significant cpu usage. 
Put the script inso start routine to  /etc/xdg/lxsession/LXDE-pi/autostart --> CPU usage 100%
Put the script into /etc/rc.local. --> 100% cpu usage. 

### What version of the AVS Device SDK are you using?
     Newest SDK. Installed yesterday.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Newest version. Updated with update and upgrade script.

**Comment by khassel** [comment]
see https://github.com/alexa/avs-device-sdk/issues/539#issuecomment-369286728

**Comment by womw** [comment]
Hey @t4rif4ri are you still having trouble or did @khassel comment resolve the issue?

**Comment by t4rif4ri** [comment]
This was the solution :) its working well now.

Cpu usage is low as before

**Comment by womw** [comment]
ok thanks for the response, I will close this issue.
