### ISSUE TITLE
SampleApp how to enable "Alexa [ding] ..." ?

### ISSUE THREAD

**Issue by smititelu** [alexa/avs-device-sdk#123]
Hi. My AlexaClientSDKConfig.json looks like this:
```
 {
    "authDelegate":{
...
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"/root/alexa_db",
     "alarmSoundFilePath":"/root/snowboy/resources/ding.wav",
     "alarmShortSoundFilePath":"/root/snowboy/resources/ding.wav",
     "timerSoundFilePath":"/root/snowboy/resources/ding.wav",
     "timerShortSoundFilePath":"/root/snowboy/resources/ding.wav"
   }
 }
```

However, none of the file paths affect whant I want to do. How can I enable that [ding] after the wakeword ?

**Comment by sanjayrd** [comment]
Hey @smititelu,

You can implement `AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/KeyWordObserverInterface.h` to be notified of wake word detections, as long as your class is hooked up to the wake word detector. The wake word detector will notify your class whenever a wake word is detected, and you can play a sound at that point.

Hope that helps,
Sanjay

**Comment by smititelu** [comment]
@sanjayrd thank you for your input! Can you help me with a basic code skeleton example? ...since I don't fully understand how to do what you've told

**Comment by sanjayrd** [comment]
Hey @smititelu,

Yup, that's almost correct. If you plan on developing around the Sample App, then the function on `SampleApp/src/KeywordObserver.cpp` called `onKeyWordDetected` gets called whenever a wake word (Alexa) is detected. 

So, you could have some code to play a sound at the beginning of that function and that way, whenever Alexa is detected, your code would execute.

**Comment by smititelu** [comment]
@sanjayrd after adding a line like the below in the ```onKeyWordDetected()``` I get the beep, but works only before Alexa speaks for the first time:
```
onKeyWordDetected(...) {
    system("aplay /root/snowboy/resources/ding.wav");
    ...
}
```
The below syslog appears for the next triggers, as well as when I try from console directly:
```
Sep  1 08:59:07 raspberrypi SampleApp[1839]: aplay: main:788: audio open error: Device or resource busy
```

Maybe Alexa does not free the mic/speaker device after she uses it?

**Comment by sanjayrd** [comment]
Hi @smititelu,

Apologies in the delay for getting back to you! Yes it's possible that PortAudio (the third party library that the Sample App is using for microphone input) is using the device indirectly through some sort of daemon. Could you verify whether there are any daemons running that might be using the speaker? This would only be a problem in the Sample App, since PortAudio isn't a direct dependency of our SDK, but rather only a dependency of our Sample App. 

Closing for now, but feel free to re-open!

Thanks,
Sanjay
