### ISSUE TITLE
Failed to Get a Refresh Token

### ISSUE THREAD

**Issue by dakota72** [alexa/avs-device-sdk#1230]
Hi, 
In my Raspberry, I followed this guide: 
https://developer.amazon.com/it/docs/alexa-voice-service/get-a-refresh-token.html
After to Build the AVS Device SDK with Success, 
I installed my usb microphone and 
I tried to Get a refresh token. I launched
sudo bash startsample.sh
but the script not write the token. why?
In attach the log file.
[ale.log](https://github.com/alexa/avs-device-sdk/files/2864038/ale.log)
thanks,
dak.

**Comment by womw** [comment]
Hey @dakota72 thanks for the post.

It looks like your device is already authorized and the current auth credentials are causing an error. Try pressing z according to the options menu to reauthorize your device and see if this error still occurs.

**Comment by dakota72** [comment]
ok, thanks. I resolved! :)
