### ISSUE TITLE
How much time of cycle setting by function "readConsoleInput"

### ISSUE THREAD

**Issue by phyen808724** [alexa/avs-device-sdk#1231]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

In UserInputManager.cpp (sampleapp\src) , the function "readConsoleInput" is using for get user input from console. Could you tell us how long is it? Can we change it?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Android P devices.

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Android P

**Comment by visayamv** [comment]
Hi @phyen808724 , It will read continuously every 100 milliseconds from the user input until it got something. Yes you can change the sample app as you see fit.
