### ISSUE TITLE
Alexa SDK Install Issues

### ISSUE THREAD

**Issue by mwoodage** [alexa/avs-device-sdk#1234]
Hello,
I'm struggling with installing the Alexa SDK to my Raspberry Pi. The installation was going well but i can't get it past 38%. I've tried everything i can think of and also followed the install guide to the letter. 
Is anyone able to help?

Thanks in advance,
Martin

Info:-
Raspberry Pi 3
Running stretch (updated to latest version

Details of how far the installation progresses:-

Proceeding with installation
################################################################################
[ 35%] Built target AVSCommon
[ 38%] Built target SQLiteStorage
[ 38%] Linking CXX shared library libACL.so
[ 38%] Linking CXX shared library libADSL.so
CMakeFiles/ADSL.dir/DirectiveRouter.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
ADSL/src/CMakeFiles/ADSL.dir/build.make:174: recipe for target 'ADSL/src/libADSL.so' failed
make[3]: *** [ADSL/src/libADSL.so] Error 1
CMakeFiles/Makefile2:3462: recipe for target 'ADSL/src/CMakeFiles/ADSL.dir/all' failed
make[2]: *** [ADSL/src/CMakeFiles/ADSL.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/ACL.dir/Transport/MessageRequestHandler.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
ACL/src/CMakeFiles/ACL.dir/build.make:383: recipe for target 'ACL/src/libACL.so' failed
make[3]: *** [ACL/src/libACL.so] Error 1
CMakeFiles/Makefile2:3160: recipe for target 'ACL/src/CMakeFiles/ACL.dir/all' failed
make[2]: *** [ACL/src/CMakeFiles/ACL.dir/all] Error 2
CMakeFiles/Makefile2:10105: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:2526: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2
pi@raspberrypi:~ $

**Comment by scotthea-amazon** [comment]
Hello  [mwoodage](/mwoodage),

You might try deleting DirectiveRouter.cpp.o (or the whole build folder) and rebuilding.  Also, have you checked that you still plenty of space left on the device?

Best regards,
-SWH

**Comment by mwoodage** [comment]
> Hello [mwoodage](/mwoodage),
> 
> You might try deleting DirectiveRouter.cpp.o (or the whole build folder) and rebuilding. Also, have you checked that you still plenty of space left on the device?
> 
> Best regards,
> -SWH

Hi SWH, many thanks for your reply  - i've tried searching for the DirectiveRouter.capp.o folder but cannot find it - are you able to point me in the right direction?

Thanks
Martin

**Comment by mwoodage** [comment]
Managed to resolve this by deleting the folder **avs-device-sdk** and re-installing the whole thing again. My install also stopped again at 56% so deleted the folder again and started from scratch. Got there in the end as everything is now installed.

**Comment by kclchan** [comment]
Glad to hear you got it working now.  I'm going to close the issue.  Thanks!
