### ISSUE TITLE
Installation issue on Windows 10

### ISSUE THREAD

**Issue by MrParano1d** [alexa/avs-device-sdk#1235]
## Briefly summarize your issue:
I was following your Windows Setup Guide (https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script) and ran at this step into an issue `bash setup.sh config.json`
It's telling me
`The installation script doesn't support current system. (System: MSYS_NT-10.0 JP-PC 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys)`

When I executed this step in git bash I could agree the terms but pacman is missing in git bash.

## Provide the steps to reproduce the issue, if applicable:
All steps from your guide.

## Tell us about your environment:
Windows 10 Pro 64 Bit
CPU: i7-3770k

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:
- Windows 10

**Comment by scotthea-amazon** [comment]
Hello MrParano1d,

From the error message:

```
(System: MSYS_NT-10.0 JP-PC 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys)
```

It looks like you are running the MSYS2 shell and not the WinGW64 shell as specified in step 1 of the instructions: [Download and install MSYS2](https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script#download-and-install-msys2).

Best regards,
-SWH

**Comment by MrParano1d** [comment]
Well, that's embarrassing. Sorry, my bad!
