### ISSUE TITLE
How can we differentiate device’s microphone error from the semantics parsing failure ?

### ISSUE THREAD

**Issue by justy0714** [alexa/avs-device-sdk#124]
https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/alexa-voice-service-ux-design-guidelines

As the above amazon developer site indicates, " In the case of a low-confidence response, no sound should be played”.

When we test device SDK on raspberry pi, sometimes AVS client switches its state from Listening to Thinking and then to Speaking, but no sound be played.

These cases might be the so-called low-confidence responses.

But the low-confidence responses might be caused by bad sound quality or semantics parsing error of Alexa Cloud.

How can we differentiate the device’s microphone errors from Alex Cloud semantics parsing failure on AVS device SDK ?

Thansk!!

**Comment by kencecka** [comment]
Hi @justy0714,

You can really disregard the discussion about confidence levels int he UX guidelines.  There is no information about confidence levels exposed by the AVS API, and all handling of them is implemented in the cloud.  The only item in that section which applies to device implementers is: "Device error sounds should be used if there is an issue with connectivity."

Ken
