### ISSUE TITLE
Cross compiling SampleApp error.

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1242]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have compile SampleApp  for arm architecture with  arm-linux-gnueabi.

this is my build script:
TOOLCHAIN="/home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm"
TOOLCHAIN_HOST="arm-linux-gnueabi"
TOOLCHAIN_BUILD="x86_64-linux-gnu"
INSTALL_TARGET="/home/xxw/xuxuewen/work/alexa_for_idh/install"
THIRD_PARTY="${CDIR}/../third_party"

export AR="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-ar"
export CC="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-gcc"
export CPP="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-cpp"
export CROSS_SYSROOT="${TOOLCHAIN}/${TOOLCHAIN_HOST}/libc"
export CXX="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-g++"
export LD="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-ld"
#export LINK="${CXX}"
export PATH="${TOOLCHAIN}/bin:${PATH}"
export RANLIB="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-ranlib"
export READELF="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-readelf"
export STRIP="${TOOLCHAIN}/bin/${TOOLCHAIN_HOST}-strip"
export SYSROOT="${CROSS_SYSROOT}"
export CPPFLAGS="-I ${CROSS_SYSROOT}/include -I ${SYSROOT}/libc/usr/include -I /home/xxw/xuxuewen/work/alexa_for_idh/armv7/include -I ${INSTALL_TARGET}/include -I ${TOOLCHAIN}/${TOOLCHAIN_HOST}/include"
export CFLAGS="-I ${SYSROOT}/include -I ${SYSROOT}/libc/usr/include -I /home/xxw/xuxuewen/work/alexa_for_idh/armv7/include -I ${INSTALL_TARGET}/include -I ${TOOLCHAIN}/${TOOLCHAIN_HOST}/include"
export LDFLAGS="-L ${SYSROOT}/lib -L ${SYSROOT}/libc/usr/lib -L /home/xxw/xuxuewen/work/alexa_for_idh/armv7/lib -L ${INSTALL_TARGET}/lib"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/home/xxw/xuxuewen/work/alexa_for_idh/armv7/lib/pkgconfig:${INSTALL_TARGET}/lib/pkgconfig"

cmake ../avs-device-sdk \
    -DCMAKE_BUILD_TYPE="DEBUG" \
    -DCMAKE_CROSSCOMPILING="ON"\
    -DCMAKE_EXPORT_COMPILE_COMMANDS="ON" \
    -DCMAKE_INSTALL_PREFIX="${INSTALL_TARGET}" \
    -DCMAKE_PREFIX_PATH="${INSTALL_TARGET}" \
    -DCMAKE_TOOLCHAIN_FILE="/home/xxw/xuxuewen/work/alexa_for_idh/build/idh.toolchain.cmake" \
    -DSENSORY_KEY_WORD_DETECTOR="ON" \
    -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH="${THIRD_PARTY}/alexa-rpi/lib/libsnsr.a" \
    -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR="${THIRD_PARTY}/alexa-rpi/include" \
    -DGSTREAMER_MEDIA_PLAYER="ON" \

make SampleApp 2>&1|tee log

This is my  CMAKE_TOOLCHAIN_FILE:
cmake_minimum_required(VERSION 3.6.0)

set(CMAKE_SYSTEM_NAME Linux)

#idh path
set(IDH_TOOLCHAIN_PREFIX "arm-linux-gnueabi")
set(IDH_ARM_SYSROOT "/home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm/arm-linux-gnueabi/libc")
set(CMAKE_SYSROOT ${IDH_ARM_SYSROOT})
set(CMAKE_STAGING_PREFIX "/home/xxw/xuxuewen/work/alexa_for_idh/install")

set(CMAKE_C_COMPILER "${IDH_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${IDH_TOOLCHAIN_PREFIX}-g++")
set(CMAKE_AR "${IDH_TOOLCHAIN_PREFIX}-ar")
set(CMAKE_RANLIB "${IDH_TOOLCHAIN_PREFIX}-ranlib")
set(CMAKE_TOOLCHAIN_PREFIX "${IDH_TOOLCHAIN_PREFIX}")

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

## What is the expected behavior?

detail log:
xxw@kitty:~/xuxuewen/work/alexa_for_idh/build$ ./build.sh 
-- The CXX compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm/bin/arm-linux-gnueabi-g++
-- Check for working CXX compiler: /home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm/bin/arm-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Creating the build directory for the AlexaClientSDK with build type: DEBUG
Creating AlexaClientSDK with keyword detector type: Sensory
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Found gstreamer-1.0, version 1.10.1
--   Found gstreamer-app-1.0, version 1.10.1
Bluetooth implementation not supported
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 4.9.4
-- Check for working C compiler: /home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm/bin/arm-linux-gnueabi-gcc
-- Check for working C compiler: /home/xxw/xuxuewen/work/alexa_for_idh/toolchain/gcc-linaro-4.9.4-arm/bin/arm-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CURL: /home/xxw/xuxuewen/work/alexa_for_idh/install/lib/libcurl.so (found suitable version "7.61.0", minimum required is "7.43.0") 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ACL with build type: DEBUG
Creating ACL with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ADSL with build type: DEBUG
Creating ADSL with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the AFML with build type: DEBUG
Creating AFML with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the DeviceSettings with build type: DEBUG
Creating DeviceSettings with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the BluetoothImplementations with build type: DEBUG
Creating BluetoothImplementations with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the EqualizerImplementations with build type: DEBUG
Creating EqualizerImplementations with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CertifiedSender with build type: DEBUG
Creating CertifiedSender with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ContextManager with build type: DEBUG
Creating ContextManager with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CapabilitiesDelegate with build type: DEBUG
Creating CapabilitiesDelegate with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the PlaylistParser with build type: DEBUG
Creating PlaylistParser with keyword detector type: Sensory
Bluetooth implementation not supported
-- Checking for module 'libcrypto'
--   Found libcrypto, version 1.1.0h
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SENSORY with build type: DEBUG
Creating SENSORY with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the KeywordDetectorProvider with build type: DEBUG
Creating KeywordDetectorProvider with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the CapabilityAgents with build type: DEBUG
Creating CapabilityAgents with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the AIP with build type: DEBUG
Creating AIP with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Alerts with build type: DEBUG
Creating Alerts with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the AudioPlayer with build type: DEBUG
Creating AudioPlayer with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Bluetooth with build type: DEBUG
Creating Bluetooth with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the DoNotDisturbCA with build type: DEBUG
Creating DoNotDisturbCA with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Equalizer with build type: DEBUG
Creating Equalizer with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ExternalMediaPlayer with build type: DEBUG
Creating ExternalMediaPlayer with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the InteractionModel with build type: DEBUG
Creating InteractionModel with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the MRM with build type: DEBUG
Creating MRM with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the Notifications with build type: DEBUG
Creating Notifications with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeakerManager with build type: DEBUG
Creating SpeakerManager with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeechSynthesizer with build type: DEBUG
Creating SpeechSynthesizer with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Integration with build type: DEBUG
Creating Integration with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Please fill /home/xxw/xuxuewen/work/alexa_for_idh/build/Integration/AlexaClientSDKConfig.json before you execute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
Creating the build directory for the ApplicationUtilities with build type: DEBUG
Creating ApplicationUtilities with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the DefaultClient with build type: DEBUG
Creating DefaultClient with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the MediaPlayer with build type: DEBUG
Creating MediaPlayer with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ESP with build type: DEBUG
Creating ESP with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the RegistrationManager with build type: DEBUG
Creating RegistrationManager with keyword detector type: Sensory
Bluetooth implementation not supported
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Authorization with build type: DEBUG
Creating Authorization with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the CBLAuthDelegate with build type: DEBUG
Creating CBLAuthDelegate with keyword detector type: Sensory
Bluetooth implementation not supported
To build the sample app, please enable microphone and media player modules.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Storage with build type: DEBUG
Creating Storage with keyword detector type: Sensory
Bluetooth implementation not supported
Creating the build directory for the SQLiteStorage with build type: DEBUG
Creating SQLiteStorage with keyword detector type: Sensory
Bluetooth implementation not supported
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.24.0
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
FATALDoxygen is required to generate documentation.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxw/xuxuewen/work/alexa_for_idh/build
Scanning dependencies of target AVSCommon
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSDirective.cpp.o
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessage.cpp.o
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessageHeader.cpp.o
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AbstractAVSConnectionManager.cpp.o
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/BlockingPolicy.cpp.o
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/ExternalMediaPlayer/AdapterUtils.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/Attachment.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/AttachmentManager.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/AttachmentUtils.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachment.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachmentReader.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachmentWriter.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/CapabilityConfiguration.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/CapabilityAgent.cpp.o
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/DialogUXStateAggregator.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/EventBuilder.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/ExceptionEncounteredSender.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/HandlerAndPolicy.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/MessageRequest.cpp.o
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/NamespaceAndName.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Bluetooth/SDPRecords.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/BluetoothEventBus.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Configuration/ConfigurationNode.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/DeviceInfo.cpp.o
[  5%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Executor.cpp.o
[  6%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/FileUtils.cpp.o
[  6%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/FormattedAudioStreamAdapter.cpp.o
[  6%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/JSON/JSONGenerator.cpp.o
[  6%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/JSON/JSONUtils.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/HTTP2/HTTP2GetMimeHeadersResult.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/HTTP2/HTTP2MimeRequestEncoder.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/HTTP2/HTTP2MimeResponseDecoder.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/HTTP2/HTTP2SendDataResult.cpp.o
[  7%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CallbackData.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlEasyHandleWrapper.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlMultiHandleWrapper.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/HTTPContentFetcherFactory.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/HttpPost.cpp.o
[  8%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/HttpPut.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/HTTPResponse.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/LibCurlHttpContentFetcher.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/LibcurlHTTP2Connection.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/LibcurlHTTP2ConnectionFactory.cpp.o
[  9%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/LibcurlHTTP2Request.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/LibcurlUtils.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ConsoleLogger.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Level.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntry.cpp.o
[ 10%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntryBuffer.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogEntryStream.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Logger.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LoggerSinkManager.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LoggerUtils.cpp.o
[ 11%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/LogStringFormatter.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ModuleLogger.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ThreadMoniker.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/MacAddressString.cpp.o
[ 12%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Metrics.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Network/InternetConnectionMonitor.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/RequiresShutdown.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/RetryTimer.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/SafeCTimeAccess.cpp.o
[ 13%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Stopwatch.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Stream/StreamFunctions.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Stream/Streambuf.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/StringUtils.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskQueue.cpp.o
[ 14%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskThread.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimePoint.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimeUtils.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Timer.cpp.o
[ 15%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/UUIDGeneration.cpp.o
[ 15%] Linking CXX shared library libAVSCommon.so
[ 15%] Built target AVSCommon
Scanning dependencies of target gmock_main
[ 15%] Building CXX object ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o
[ 15%] Building CXX object ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
[ 15%] Building CXX object ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 16%] Linking CXX static library libgmock_main.a
Error running link command: No such file or directory
make[2]: *** [ThirdParty/googletest-release-1.8.0/googlemock/libgmock_main.a] Error 2
make[1]: *** [ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/all] Error 2
make: *** [all] Error 2

## What behavior are you observing?

The "ThirdParty/googletest-release-1.8.0/googlemock/CMakeFiles/gmock_main.dir/link.txt" file showed  "" qc libgmock_main.a  CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o CMakeFiles/gmock_main.dir/src/gmock-all.cc.o CMakeFiles/gmock_main.dir/src/gmock_main.cc.o

The link command is empty, but i don't know why.

### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:  arm

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @xuewenxu,

Looks like the error logs indicate that libgmock_main.a doesn't exist. Can you verify that the file doesn't exist by listing the following directory: <AVS_BUILD_DIR>/ThirdParty/googletest-release-1.8.0/googlemock/.

**Comment by xuewenxu** [comment]
Hi, @kjkh 
     Thanks for your reply, and i got it.
