### ISSUE TITLE
KITTAI_KEY_WORD_DETECTOR error

### ISSUE THREAD

**Issue by nunokid** [alexa/avs-device-sdk#125]
I want to run AVS on aarch64 linux board.
The sensory trigger is not working on my linux board, so I want to use KITT.

My cmake command is below.

cmake $SDK_SRC -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/sources/snowboy/lib/aarch64-ubuntu1604/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/sources/snowboy/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LOCAL_BUILD/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD

I met below error.

[ 68%] Linking CXX executable KittAiKeyWordDetectorTest
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:102: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1
CMakeFiles/Makefile2:4045: recipe for target 'KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all' failed
make[1]: *** [KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kencecka** [comment]
Hi @nunokid,

The KITT.AI snowboy library has a C++ binary interface.  That means you need to closely match your compiler vendor, version and configuration to those used by KITT.AI when they built the library they are distributing.  They note that their aarch64 library is specifically for Ubuntu 16.04.  That means you should either run Ubunutu 16.04, or research exactly what compiler it uses and use the same compiler when building the SDK.

Ken

**Comment by smititelu** [comment]
Try compilling with "CC=gcc-4.9 CXX=g++-4.9 cmake ..."

**Comment by nunokid** [comment]
Dear @smititelu @kencecka 

I try compilling with "CC=gcc-4.9 CXX=g++-4.9 cmake..."
But I met below error. Do you have the other solution?

ubuntu@localhost:~/BUILD$ CC=gcc-4.9 CXX=g++-4.9 cmake $SDK_SRC -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTA                                                                                                                 I_KEY_WORD_DETECTOR_LIB_PATH=/home/ubuntu/sources/snowboy/lib/aarch64-ubuntu1604/libsnowboy-detect.a                                                                                                                  -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ubuntu/sources/snowboy/include -DGSTREAMER_MEDIA_PLAYER=                                                                                                                 ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LOCAL_BUILD/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$LOCAL                                                                                                                 _BUILD/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD

ubuntu@localhost:~/BUILD$ sudo make

...
<<snip>>
...
[ 68%] Built target KITTAI
[ 68%] Building CXX object KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/KittAiKeyWordDetectorTest.cpp.o
In file included from /home/ubuntu/AVS_SDK/avs-device-sdk/KWD/KittAi/test/KittAiKeyWordDetectorTest.cpp:8:0:
/home/ubuntu/AVS_SDK/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/home/ubuntu/AVS_SDK/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/home/ubuntu/AVS_SDK/avs-device-sdk/KWD/KittAi/test/KittAiKeyWordDetectorTest.cpp:353:5:   required from here
/home/ubuntu/AVS_SDK/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lhs == rhs) {
           ^
[ 68%] Linking CXX executable KittAiKeyWordDetectorTest
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:102: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1
CMakeFiles/Makefile2:4045: recipe for target 'KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all' failed
make[1]: *** [KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by smititelu** [comment]
@nunokid I remember that happened to me also(CC/CXX didn't worked for me out-of-the-box also). But, after a fresh latest raspbian strech install, gcc/g++-4.9 compiled and SampleApp worked good.

**Comment by nunokid** [comment]
@smititelu
I did not use raspberry. I'll take another look at the other solutions.

**Comment by sangshengjie** [comment]
I tryed cross gcc/g++-5.4 to solved the problem.You can try.

**Comment by nunokid** [comment]
@sangshengjie 

I have already tried version 5.4, but still get an error.
My environments are as follows:

ubuntu@localhost:$ aarch64-linux-gnu-gcc -v
 Using built-in specs.
 COLLECT_GCC=aarch64-linux-gnu-gcc
 COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
 Target: aarch64-linux-gnu
 Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu116.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
 Thread model: posix
 gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4)

**Comment by nunokid** [comment]
I have resolved this issue by changing the default gcc version.

$ sudo apt-get install gcc-4.8

$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60
$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 60


Thanks All.
