### ISSUE TITLE
startsample.sh does't exit after I execute setup.sh

### ISSUE THREAD

**Issue by hotsauce1861** [alexa/avs-device-sdk#1252]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

after I execute script setup.sh，can't find startsample.sh

################################################################################

AVS Device SDK Android Script - Terms and Agreements

The AVS Device SDK is dependent on several third-party libraries, environments,
and/or other software packages that are installed using this script from
third-party sources ("External Dependencies"). These are terms and conditions
associated with the External Dependencies
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that
you need to agree to abide by if you choose to install the External Dependencies.

If you do not agree with every term and condition associated with the External
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".

################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
[ 32%] Built target AVSCommon
[ 32%] Built target SQLiteStorage
[ 34%] Built target ADSL
[ 39%] Built target ACL
[ 41%] Built target RegistrationManager
[ 41%] Built target AFML
[ 41%] Built target ContextManager
[ 44%] Built target EqualizerImplementations
[ 46%] Built target CapabilitiesDelegate
[ 46%] Built target SpeechEncoder
[ 48%] Built target PlaylistParser
[ 51%] Built target AudioResources
[ 51%] Built target AudioPlayer
[ 53%] Built target Bluetooth
[ 55%] Built target Equalizer
[ 58%] Built target ExternalMediaPlayer
[ 58%] Built target InteractionModel
[ 60%] Built target Notifications
[ 62%] Built target PlaybackController
[ 62%] Built target SpeakerManager
[ 65%] Built target SpeechSynthesizer
[ 67%] Built target TemplateRuntime
[ 72%] Built target AVSSystem
[ 74%] Built target AndroidUtilities
[ 74%] Built target CBLAuthDelegate
[ 76%] Built target CertifiedSender
[ 79%] Built target AIP
[ 79%] Built target DeviceSettings
[ 83%] Built target AndroidSLESMediaPlayer
[ 88%] Built target Alerts
[ 90%] Built target DoNotDisturbCA
[ 90%] Built target ESP
[ 93%] Built target Settings
[ 95%] Built target DefaultClient
[100%] Built target SampleApp

==============> SAVING CONFIGURATION FILE ==============

Usage: genConfig.sh <config.json file> <device_serial_number> <db path> <SDK Source Directory> <output AlexaClientSDKConfig.json file>
1) <config.json file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"
2) <device_serial_number> specifies the deviceInfo deviceSerialNumber in the output json file.
3) <db path> specifies the path to where the databases will be located.
4) <SDK Source Directory> specifies the root directory to where the avs-device-sdk source code is located.
5) <output AlexaClientSDKConfig.json file> output file

## Provide the steps to reproduce the issue, if applicable:

sudo bash setup.sh config.json -a androidConfig.txt -s 123456
## Tell us about your environment:

Linux server 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What version of the AVS Device SDK are you using?
      <1.12.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
Android

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by aeoloslee** [comment]
Have you solved this problem？
