### ISSUE TITLE
AlertObserverInterface is not notified when new ALERT/ALARM is set

### ISSUE THREAD

**Issue by julianorqti** [alexa/avs-device-sdk#1253]
<<Suggestion for new implementation >>

When a new alarm is set up AlertObserver objects inside AlertsCapabilityAgent class are not notified about that.
It is possible to enhance that interface to receive a notification every time a new ALARM is set, that way platform can take some action for that alert? For example, display alarm info on a screen.
New method for AlertObserverInterface should have Alarm type and time that it is scheduled to play.

Thank you,
Juliano RIbeiro

### What version of the AVS Device SDK are you using?
1.11

**Comment by kjkh** [comment]
Hi @julianorqti,

The `alertType` parameter has been added to the `AlertObserverInterface` in 1.12. The duration is not present, but I am curious what your use case for that is?

**Comment by julianorqti** [comment]
Hi Kjkh,

I want to know at what time alarm needs to be triggered to show case that in a display for instance.
I want to let user know that Alarms is set and it is configure to X:YY:ZZ

Thank you,
Juliano Ribeiro

**Comment by caleighatamazon** [comment]
Hi there, sorry for our late response on this. Are you still having issues?

**Comment by caleighatamazon** [comment]
No, not currently with AlertObserverInterface. I'll make an internal ticket for our team to consider this feature request for the alert observer. 

I'm also going to close this issue for now but definitely feel free to re-open if you have other questions or concerns regarding this.
