### ISSUE TITLE
ALEXA (avs sdk) response to "wake up word"

### ISSUE THREAD

**Issue by hinar24** [alexa/avs-device-sdk#1255]
Issue:
I had cross compiling AVS SDK for ARM platform.Everything is working fine.But sometimes it is responding to  wake up word and sometimes it is not responding to wake up word 'ALEXA' .In 10 cases it respond only for 1 or 2 time. Detect my voice sometimes but not responding to my friend's voice. After detecting wake up word every time its work properly for events.And also it is taking too much time for responding to event approx 1-2min.

## What is the expected behavior?
ALEXA AVS-SDK should response every time with wake up word 'ALEXA'.

## What behavior are you observing?
Irregular behavior with wake up word 'ALEXA'.

## Tell us about your environment:
AVS SDK - 1.12.0
aarch64-linux-gnu-gcc-5
snowboy 1.3.0

### Tell us what hardware you're using:
Laptop(Ubuntu16.04)

### Tell us about your OS (Type & version):
Linux 

I have attached debug9 log below.
[Debug9_log.txt](https://github.com/alexa/avs-device-sdk/files/2921871/Debug9_log.txt)

**Comment by kclchan** [comment]
Hi @hinar24,

Unfortunately the logs you attached didn't have enough information.  Did you try using 't' tap-to-talk in the SampleApp and see if Alexa is able to respond to you question every time?

Thanks,
Kenneth

**Comment by hinar24** [comment]
hi @kclchan,
I have try with 't' tap-to-talk.it's working fine every time.I have attached full debug9 log below for reference.
[SampleApp_log_debug9.txt](https://github.com/alexa/avs-device-sdk/files/2929422/SampleApp_log_debug9.txt)

**Comment by kclchan** [comment]
Hi @hinar24, from your log, I don't see anything suspicious.  The fact that tap-to-talk works every time indicates a problem with the wake word engine (WWE) not properly detecting your wakeword.  Maybe you could post a question in [snowboy](https://github.com/Kitt-AI/snowboy/issues) and see if they would be able to help you.  Thanks!

**Comment by hinar24** [comment]
Hi @kclchan,
Ok.Thank you for support.
