### ISSUE TITLE
SDK wont build

### ISSUE THREAD

**Issue by ikarimit** [alexa/avs-device-sdk#1257]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After using "cmake /{home}/{my_project}/source/avs-device-sdk \" and all the its options I try to "make" and I get an error.

## What is the expected behavior?

build SDK

## What behavior are you observing?

I get an error output:

$ make
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
make[2]: *** No rule to make target '/usr/local/opt/curl-openssl/lib/libcurl.dylib', needed by 'AVSCommon/libAVSCommon.so'.  Stop.
CMakeFiles/Makefile2:1383: recipe for target 'AVSCommon/CMakeFiles/AVSCommon.dir/all' failed
make[1]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

## Provide the steps to reproduce the issue, if applicable:

I fallowed the steps exactly as provided till this point

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Ubuntu 16.04 LTS

**Comment by kclchan** [comment]
Hi @ikarimit,

Did you follow the instruction [here](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide) for building the SDK?

Thanks,
Kenneth

**Comment by ikarimit** [comment]
Yes, to a T. I have tried rebuilding nghttp2 with SSL...I have uninstalled curl and reinstalled it also.

**Comment by kclchan** [comment]
Hi @ikarimit, 

Could you double check with guide did you follow?  For example:
`/usr/local/opt/curl-openssl/lib/libcurl.dylib` is a package installed with brew and is a CMAKE options for the macOS [guide](https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide).  But since your system is Ubuntu, I don't think you should use that cmake option.
And please delete your build directory and rerun the cmake command and try again.  Hope this helps!

Thanks,
Kenneth

**Comment by rash27** [comment]
I ran into exact same issue:

/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
make[3]: *** No rule to make target '/usr/local/opt/curl-openssl/lib/libcurl.dylib', needed by 'AVSCommon/libAVSCommon.so'.  Stop.
CMakeFiles/Makefile2:1383: recipe for target 'AVSCommon/CMakeFiles/AVSCommon.dir/all' failed
make[2]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
CMakeFiles/Makefile2:9833: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:2474: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

I am using v1.12 on Ubuntu ( 4.15.0-45-generic #48~16.04.1-Ubuntu)

Could you please let us know what's going on here?

**Comment by kclchan** [comment]
Hi @rash27 and @ikarimit, I believe there's a mistake in the Ubuntu documentation.  The cmake command should be this instead:
```
   cmake /{home}/sdk-folder/sdk-source/avs-device-sdk \
   -DSENSORY_KEY_WORD_DETECTOR=OFF \
   -DGSTREAMER_MEDIA_PLAYER=ON \
   -DPORTAUDIO=ON \
   -DPORTAUDIO_LIB_PATH=/{home}/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a \
   -DPORTAUDIO_INCLUDE_DIR=/{home}/sdk-folder/third-party/portaudio/include
```
Please delete the build directory and run cmake again.  Thanks!

**Comment by ikarimit** [comment]
ok, so, @kclchan,  I should change the avs-device-sdk folder from "/{home}/{my_project}/source/avs-device-sdk" to "/{home}/sdk-folder/source/avs-device-sdk"? and remove the curl library options correct?

**Comment by ikarimit** [comment]
I did not change the folder but now i get another error >:( 

<code>[ 97%] Linking CXX executable SampleApp
c++: error: ~/my_project/third-party/portaudio/lib/.libs/libportaudio.a: No such file or directory
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:415: recipe for target 'SampleApp/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:9821: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2</code>

I fixed the libcurl erro using this post <a href="https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ">here</a>

**Comment by kclchan** [comment]
Hi @ikarimit,

In the guide, there's a step `Install and configure PortAudio. Portaudio is required to stream microphone input/output data.`.  Could you check after doing that step, that you got a libportaudio.a in the {home}/my_project/third-party/portaudio/lib/.libs folder?

Also, for `-DPORTAUDIO_LIB_PATH` and `-DPORTAUDIO_INCLUDE_DIR`, could you specify the absolute path instead of the relative path?

Hope this helps.  Thanks!

**Comment by ikarimit** [comment]
@kclchan ,
I forgot to mention that I checked the portaudio directory and the file is in there. Also, I am using the full paths.

**Comment by kclchan** [comment]
Hi @ikarimit, thanks for the additional information.

Thanks for confirming that the below file exists:
```
/{home}/{my_project}/third-party/portaudio/lib/.libs/libportaudio.a
```

In your cmake option, Instead of specifying `PORTAUDIO_LIB_PATH` as 
```
-DPORTAUDIO_LIB_PATH=~/my_project/third-party/portaudio/lib/.libs/libportaudio.a
```

Could you try this:
```
-DPORTAUDIO_LIB_PATH=/{home}/{my_project}/third-party/portaudio/lib/.libs/libportaudio.a
```

I would also suggest first removing the build directory, run the cmake command, and then do make again.

Thanks!

**Comment by ikarimit** [comment]
@kclchan,
Alright! i'm in business. Adding the full path worked. Thank you all for your help.
