### ISSUE TITLE
Broken link to video tutorial in ReadME.md

### ISSUE THREAD

**Issue by sw-devendra** [alexa/avs-device-sdk#1258]
## Briefly summarize your issue:
There is a broken link to video tutorial under "Learn More About The AVS Device SDK" 
heading in ReadMe.md file: 
[Watch this tutorial](https://youtu.be/F5DixCPJYo8) to learn about the how this SDK works and the set up process.

## What is the expected behavior?
The link should be valid.

**Comment by kclchan** [comment]
Hi @sw-devendra.

Thanks for letting us know about this.  We've fixed the issue now, please try again.  Thanks!

Thanks,
Kenneth
