### ISSUE TITLE
How SDK knows, when it  deregistred from the alexa app.

### ISSUE THREAD

**Issue by vijay464** [alexa/avs-device-sdk#1259]
How the AVS DEVICE SDK knows it is de-registered from the alexa app.
As I have seen in Echo/Echo plus, After de-registration, If user interrupts the device Then it is going to setup mode.
How this kind of behavior can be handles in AVS DEVICE SDK.
If user de-register the SDK from alexa app, The sdk is not responding to user and giving authorization errors if user interrupts.
Can i get the de-registration status from this authorization errors.

## What is the expected behavior?
AVS DEVICE SDK should know the status of de-registration.

## What behavior are you observing?
Some messages are received by avs sdk when user press the de-register button from alexa app. But they are not clarifying that the user is de-registered from the alexa app. 

## Provide the steps to reproduce the issue, if applicable:
Register the SDK with amazon account.
Open alexa app and de-register the above device.

### What version of the AVS Device SDK are you using?
 AVS device sdk version 1.11

### Tell us what hardware you're using:
- [ ]  Laptop

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by kclchan** [comment]
Hi @vijay464,

I believe the information in #1179 will help you.  Thanks!

**Comment by vijay464** [comment]
Hi  kclchan,

Thank you for the information. I can follow that and implement. We can close this ticket. If I need any further info, I will try reopen the ticket.

Thanks
Vijay

**Comment by vijay464** [comment]
Hi  kclchan,

Thank you for the information. I can follow that and implement. We can close this ticket. If I need any further info, I will try reopen the ticket.

Thanks
Vijay
