### ISSUE TITLE
Run SampleApp  failed  on arm

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#1260]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I was cross compiled avs  for arm  devices, toolchain is arm-linux-guneabihf and the gcc version is 6.3.
The gstreamer and gstreamer-app  version  what i used is 1.10.1 (i just installed  the two packages gst-plugins-base-1.10.1 and gstreamer-1.10.1 ).
The glib version is glib-2.48.1 

## What is the expected behavior?

When i ran SampleApp, the error information as follow:
root@sl8521e_3h10:/data/alexa # export LD_LIBRARY_PATH=/data/alexa/lib         
root@sl8521e_3h10:/data/alexa #./bin/SampleApp AlexaClientSDKConfig.json DEBUG9                                                <
2015-01-01 00:05:19.472 [  1] I sdkVersion: 1.11.0
configFile AlexaClientSDKConfig.json

(SampleApp:544): GLib-GObject-CRITICAL **: g_param_spec_int64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:544): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:544): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:544): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2015-01-01 00:05:28.263 [  1] C SampleApplication:Failed to create media player for speech!
2015-01-01 00:05:28.520 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

It seems errors about the glib version，but i don't know which version of glib  needed by avs.

### What version of the AVS Device SDK are you using?
      <1.11.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:  arm devices

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @xuewenxu, could you try to install these packages, `gst-plugins-good gst-plugins-bad gst-libav` as well?  Thanks!

**Comment by xuewenxu** [comment]
Hi @kclchan, I  have installed these packages, gst-plugins-good gst-plugins-bad gst-libav, and the same errors as above.

**Comment by kclchan** [comment]
Hi @xuewenxu,

Maybe you can try turning on gstreamer logging (set the environment variable GST_DEBUG=4) to get additional detail on the errors.

e.g.
```
GST_DEBUG=4 ./bin/SampleApp AlexaClientSDKConfig.json DEBUG9
```

**Comment by xuewenxu** [comment]
Hi @kclchan ,
     There are logs  after run  GST_DEBUG=4 ./bin/SampleApp AlexaClientSDKConfig.json DEBUG9

root@sl8521e_3h10:/data/alexa # export LD_LIBRARY_PATH=/data/alexa/lib
bin/SampleApp AlexaClientSDKConfig.json DEBUG9                                <
2015-01-01 00:04:59.523 [  1] I sdkVersion: 1.11.0
configFile AlexaClientSDKConfig.json
0:00:00.168443539   542      0x1a7c600 INFO                GST_INIT gst.c:510:init_pre: Initializing GStreamer Core Library version 1.10.4
0:00:00.262189000   542      0x1a7c600 INFO                GST_INIT gst.c:511:init_pre: Using library installed in /home/xxw/xuxuewen/work/alexa_for_idh/install/lib
0:00:00.269601423   542      0x1a7c600 INFO                GST_INIT gst.c:522:init_pre: Linux localhost 4.4.83 #1 SMP PREEMPT Tue Feb 19 15:49:23 CST 2019 armv7l
0:00:00.695048269   542      0x1a7c600 INFO                GST_INIT gstmessage.c:126:_priv_gst_message_initialize: init messages

(SampleApp:542): GLib-GObject-CRITICAL **: g_param_spec_int64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed
1:00:01.023618999   542      0x1a7c600 INFO                GST_INIT gstcontext.c:83:_priv_gst_context_initialize: init contexts
1:00:01.076431538   542      0x1a7c600 INFO      GST_PLUGIN_LOADING gstplugin.c:316:_priv_gst_plugin_initialize: registering 0 static plugins

(SampleApp:542): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_param_spec_uint64: assertion 'default_value >= minimum && default_value <= maximum' failed

(SampleApp:542): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed
1:00:01.156811922   542      0x1a7c600 INFO      GST_PLUGIN_LOADING gstplugin.c:224:gst_plugin_register_static: registered static plugin "staticelements"
1:00:01.156931961   542      0x1a7c600 INFO      GST_PLUGIN_LOADING gstplugin.c:226:gst_plugin_register_static: added static plugin "staticelements", result: 1
1:00:01.176298769   542      0x1a7c600 INFO            GST_REGISTRY gstregistry.c:1738:ensure_current_registry: reading registry cache: /data/.cache/gstreamer-1.0/registry.arm.bin
1:00:01.280880076   542      0x1a7c600 INFO            GST_REGISTRY gstregistrybinary.c:537:priv_gst_registry_binary_read_cache: Unable to mmap file /data/.cache/gstreamer-1.0/registry.arm.bin : Failed to open file '/data/.cache/gstreamer-1.0/registry.arm.bin': open() failed: No such file or directory
1:00:01.290755922   542      0x1a7c600 INFO            GST_REGISTRY gstregistrybinary.c:547:priv_gst_registry_binary_read_cache: Unable to read file /data/.cache/gstreamer-1.0/registry.arm.bin : Failed to open file '/data/.cache/gstreamer-1.0/registry.arm.bin': No such file or directory
1:00:01.300635576   542      0x1a7c600 INFO            GST_REGISTRY gstregistry.c:1594:scan_and_update_registry: Validating plugins from registry cache: /data/.cache/gstreamer-1.0/registry.arm.bin
1:00:01.363762422   542      0x1a7c600 INFO            GST_REGISTRY gstregistry.c:1696:scan_and_update_registry: Registry cache has not changed
1:00:01.363900807   542      0x1a7c600 INFO            GST_REGISTRY gstregistry.c:1773:ensure_current_registry: registry reading and updating done, result = 1
1:00:01.364534307   542      0x1a7c600 INFO                GST_INIT gst.c:720:init_post: GLib runtime version: 2.48.1
1:00:01.364599961   542      0x1a7c600 INFO                GST_INIT gst.c:722:init_post: GLib headers version: 2.40.2
1:00:01.364635307   542      0x1a7c600 INFO                GST_INIT gst.c:723:init_post: initialized GStreamer successfully
1:00:01.383261730   542      0x1a7c600 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:460:gst_element_factory_make: no such element factory "queue2"!

(SampleApp:542): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:542): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2015-01-01 00:05:08.464 [  1] C SampleApplication:Failed to create media player for speech!
2015-01-01 00:05:08.704 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

The primary mistake seems to be  gstelementfactory.c:460:gst_element_factory_make: no such element factory "queue2"!，right？

**Comment by kclchan** [comment]
Hi @xuewenxu, I agree, the problem seems to be related to queue2 not found.  According to https://gstreamer.freedesktop.org/documentation/plugins.html, queue2 element should be part of coreelements.  Please double check on your installation of gstreamer.

**Comment by xuewenxu** [comment]
Hi @kclchan ,  I got it,  it's because not set environment variable GST_PLUGIN_PATH.  I have set it  and  it's ok.
BTW, what's the reason about  these errors  (SampleApp:542): GLib-GObject-CRITICAL **: g_param_spec_int64: assertion 'default_value >= minimum && default_value <= maximum' failed
(SampleApp:542): GLib-GObject-CRITICAL **: g_object_class_install_property: assertion 'G_IS_PARAM_SPEC (pspec)' failed

**Comment by kclchan** [comment]
@xuewenxu, nice to hear you got it working now.  I'm closing the issue now.
