### ISSUE TITLE
SampleApp multi turn interaction enter idle mode without waiting user response  

### ISSUE THREAD

**Issue by ada1013** [alexa/avs-device-sdk#1262]
## Briefly summarize your issue:
We are trying to use the AVS device SDK on our device, but multi turn interaction can't work by using SampleApp, Alexa just enters idle mode without waiting for our second sentence. The debug9 log is here: [1.log](https://github.com/alexa/avs-device-sdk/files/2934845/1.log), any suggestion would be appreciated. 

## What is the expected behavior?
me: Alexa, set a timer
Alexa: for how long?
-------------------------------->but in here, Alexa enters idle mode directly.
me: ten minutes
Alexa: ten minutes timer start now. 

## What behavior are you observing?
We have used SDK 1.11, and there is an error log : InProcessAttachmentReader:readFailed:reason=bytes requested smaller than SDS word size, so we doubted we met the same issue with #948 , so we upgrade to SDK 1.12, there is no "bytes requested smaller than SDS word size" message but the multi turn still fails.

## Provide the steps to reproduce the issue, if applicable:
using SampleApp to do the multi turn interaction. likes set a timer or alarm.

## Tell us about your environment:
ARM based embedded linux

### What version of the AVS Device SDK are you using?
      <1.12.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- Other - tell us more:

### Tell us about your OS (Type & version):
- Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @ada1013, thanks for providing the logs to the issue you are seeing, we are currently investigating why this is happening.  Does the issue happen all the time for you?

**Comment by kclchan** [comment]
And also, could you let us know the version of compiler you are using?  Thanks!

**Comment by ada1013** [comment]
Thanks for your response. I have tried the three different ways to try multi-turn interaction.
1. Wake word:  Simply say Alexa and begin your query.
     ->this one fails every time.
2. Tap to talk: Press 't' and Enter followed by your query (no need for the 'Alexa').
     ->this one fails every time.
3. Hold to talk: Press 'h' followed by Enter to simulate holding a button. Then say your query (no need for the 'Alexa').  Press 'h' followed by Enter to simulate releasing a button.
     ->this one works, I can send specific timer in the second sentence, and Alexa has right response to start the timer. Here is the log: [hold_to_talk.log](https://github.com/alexa/avs-device-sdk/files/2939310/hold_to_talk.log) 

The version of compiler I am using : gcc-5.2.0.

I am still trying to fix this issue, so please let me know if any suggestion, thanks again~

**Comment by kclchan** [comment]
Hi @ada1013, we are not able to reproduce the issue on our side.  But we have narrowed down the most likely culprit to be `DirectiveProcessor::getNextUnblockedDirectiveLocked()`

It would be great if you could add a log inside the for loop in `DirectiveProcessor::getNextUnblockedDirectiveLocked()`, like below:

```
for (auto it = m_handlingQueue.begin(); it != m_handlingQueue.end(); it++) {
        auto currentUsingAudio = it->second.getMediums()[BlockingPolicy::Medium::AUDIO];
        auto currentUsingVisual = it->second.getMediums()[BlockingPolicy::Medium::VISUAL];

        ACSDK_DEBUG9(LX(__func__)
                             .d("messageid", it->first->getMessageId())
                             .d("policy", it->second)
                             .d("currentAudio", currentUsingAudio)
                             .d("currentVisual", currentUsingVisual)
                             .d("audioBlocked", blockedMediums[BlockingPolicy::Medium::AUDIO])
                             .d("visualBlocked", blockedMediums[BlockingPolicy::Medium::VISUAL]));
```

Please build and test with the above change and provide us the DEBUG9 logs.

Also it would be interesting to see instead of doing this (in the same for loop):
```
        auto currentUsingAudio = it->second.getMediums()[BlockingPolicy::Medium::AUDIO];
        auto currentUsingVisual = it->second.getMediums()[BlockingPolicy::Medium::VISUAL];
```
Change it to this instead:
```
        bool currentUsingAudio = false;
        bool currentUsingVisual = false;

        if (it->second.getMediums()[BlockingPolicy::Medium::AUDIO]) {
            currentUsingAudio = true;
        }

        if (it->second.getMediums()[BlockingPolicy::Medium::VISUAL]) {
            currentUsingVisual = true;
        }
```

Please build and test again and see if there's any difference.  Please also provide us the DEBUG9 logs as well.

Finally, would you mind filling out this [Contact form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) so that we'll be able to reach out to you when we have more questions?  Thanks!

**Comment by ada1013** [comment]
Thanks @kclchan ,

multi-turn works after we followed your suggestion.

> Also it would be interesting to see instead of doing this (in the same for loop):

        auto currentUsingAudio = it->second.getMediums()[BlockingPolicy::Medium::AUDIO];
        auto currentUsingVisual = it->second.getMediums()[BlockingPolicy::Medium::VISUAL];

> Change  it to this instead:

        bool currentUsingAudio = false;
        bool currentUsingVisual = false;

        if (it->second.getMediums()[BlockingPolicy::Medium::AUDIO]) {
            currentUsingAudio = true;
        }

        if (it->second.getMediums()[BlockingPolicy::Medium::VISUAL]) {
            currentUsingVisual = true;
        }

Here are the logs: 
[multi-turn_fail.log](https://github.com/alexa/avs-device-sdk/files/2944339/multi-turn_fail.log) 
[multi-turn_work.log](https://github.com/alexa/avs-device-sdk/files/2944340/multi-turn_work.log)

Thanks for your help again. :+1:
