### ISSUE TITLE
Unable to run CMake; Package 'libffi' not found 

### ISSUE THREAD

**Issue by Eptin** [alexa/avs-device-sdk#1270]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
During installation, running the CMake command results in an error.

## What is the expected behavior?
CMake command during installation should succeed.

## What behavior are you observing?
Installation errors out with the following message:
```
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Package 'libffi', required by 'gobject-2.0', not found
--   Package 'libffi', required by 'gobject-2.0', not found
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:25 (include)
  CMakeLists.txt:10 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/[user]/my_project/build/CMakeFiles/CMakeOutput.log".
```
Here's [CMakeOutput.log](https://github.com/alexa/avs-device-sdk/files/2947874/CMakeOutput.log)

## Provide the steps to reproduce the issue, if applicable:
Follow the installation up through the `cd ~/my_project/build` step.
Run the following CMake command:
```
cmake ~/my_project/source/avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
-DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=~/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=~/my_project/third-party/portaudio/include \
-DCMAKE_BUILD_TYPE=DEBUG
```

Furthermore, `brew info libffi` shows that it's installed:
```
libffi: stable 3.2.1 (bottled), HEAD [keg-only]
Portable Foreign Function Interface library
https://sourceware.org/libffi/
/usr/local/Cellar/libffi/3.2.1 (16 files, 297.0KB)
  Poured from bottle on 2019-03-08 at 11:24:21
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libffi.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
libffi is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find libffi you may need to set:
  export LDFLAGS="-L/usr/local/opt/libffi/lib"

For pkg-config to find libffi you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

==> Analytics
install: 120,027 (30 days), 299,714 (90 days), 1,079,228 (365 days)
install_on_request: 3,001 (30 days), 8,679 (90 days), 37,393 (365 days)
build_error: 0 (30 days)
```

Additionally, I followed directions from this answer: https://apple.stackexchange.com/a/169605/22432
I attempted `locate libffi.pc` and it produced:
```
WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.
```
I then followed the directions and ran `sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist` to build the database. After relaunching Terminal, running `locate libffi.pc` now produces `/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/libffi.pc`. Nonetheless, the Device SDK installation still says
```
--   Package 'libffi', required by 'gobject-2.0', not found
--   Package 'libffi', required by 'gobject-2.0', not found
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
```
Help, I don't know what else to attempt at this point.

### What version of the AVS Device SDK are you using?
v1.12

### Tell us what hardware you're using:
MacBook Pro (13-inch, 2017)

### Tell us about your OS (Type & version):
High Sierra 10.13.6

**Comment by kclchan** [comment]
Hi @Eptin, could you try to check what's the value for the environment variable `PKG_CONFIG_PATH`
```
echo $PKG_CONFIG_PATH
```
If you haven't add `libffi` to it, maybe you can try to do this:
```
export PKG_CONFIG_PATH="usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
```
Hope this helps.  Thanks!

**Comment by Eptin** [comment]
Thanks for the advice; unfortunately, that didn't work. Here's the complete terminal history:

```
Last login: Fri Mar  8 20:35:06 on ttys001
f01898a40e96:~ micinnes$ export PKG_CONFIG_PATH="usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
f01898a40e96:~ micinnes$ echo $PKG_CONFIG_PATH
usr/local/opt/libffi/lib/pkgconfig:
f01898a40e96:~ micinnes$ cd ~/my_project/build
f01898a40e96:build micinnes$ cmake ~/my_project/source/avs-device-sdk \
> -DGSTREAMER_MEDIA_PLAYER=ON \
> -DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
> -DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \
> -DPORTAUDIO=ON \
> -DPORTAUDIO_LIB_PATH=~/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
> -DPORTAUDIO_INCLUDE_DIR=~/my_project/third-party/portaudio/include \
> -DCMAKE_BUILD_TYPE=DEBUG
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Package 'libffi', required by 'gobject-2.0', not found
--   Package 'libffi', required by 'gobject-2.0', not found
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:25 (include)
  CMakeLists.txt:10 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/micinnes/my_project/build/CMakeFiles/CMakeOutput.log".
f01898a40e96:build micinnes$ 
```

For completeness, I tried `export PKG_CONFIG_PATH="usr/local/opt/libffi/lib/pkgconfig"` in a new terminal session, but that didn't work either.

**Comment by aumatsui** [comment]
Hi @Eptin ,

Can you try the following?

```
cd ~/my_project/build
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```
and then running `cmake` as you did?

It looks like a leading slash character was missing on the config path. If this does not work, can you confirm that you can list the path? `ls -lah /usr/local/opt/libffi/lib/pkgconfig`

**Comment by Eptin** [comment]
That got things a little further. After exporting that new value and running CMake, now I get:

```
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Found gstreamer-1.0, version 1.14.4
--   Found gstreamer-app-1.0, version 1.14.4
Bluetooth implementation not supported
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found CURL: /usr/local/opt/curl-openssl/lib/libcurl.dylib (found suitable version "7.64.0", minimum required is "7.43.0") 
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ACL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ADSL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the AFML with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the DeviceSettings with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the BluetoothImplementations with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the EqualizerImplementations with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CertifiedSender with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ContextManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CapabilitiesDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the PlaylistParser with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Checking for module 'libcrypto'
--   No package 'libcrypto' found
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  PlaylistParser/src/CMakeLists.txt:2 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/Users/micinnes/my_project/build/CMakeFiles/CMakeOutput.log".
```

I don't have libcrypto installed, as `brew info libcrypto` produces:
```
Error: No available formula with the name "libcrypto" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
```

It doesn't appear to be available for installation through Homebrew either.
Also, `/usr/local/opt/libcrypto/` does not exist.

**Comment by aumatsui** [comment]
Hi, it seems that this back has been removed from brew. So you can try adding these arguments to the CMake command:

```
-DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib -DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include
```

**Comment by rwibawa** [comment]
I experienced the same thing since  I got a new macbook with Mojave last week. I think it has something to do with '**brew install curl-openssl**'. Some components are installed as keg-only (openssl, openldap, curl-openssl):

> ==> curl-openssl
curl-openssl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

> If you need to have curl-openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl-openssl/bin:$PATH"' >> ~/.bash_profile

> For compilers to find curl-openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/curl-openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/curl-openssl/include"

> For pkg-config to find curl-openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/curl-openssl/lib/pkgconfig"

I will try to update those environment variables and see if it's resolved.

**Comment by Eptin** [comment]
@aumatsui , unforunately, I've already tried that, as those two arguments were already in my original cmake command. (See https://github.com/alexa/avs-device-sdk/issues/1270#issue-419001891 )

**Comment by aumatsui** [comment]
I am sorry. I did not see that.
Can you try exporting this before cmake?

```
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:$PKG_CONFIG_PATH”
```
it may also be a good idea to use explicit paths instead of ones starting with tilde (`~`).

**Comment by Eptin** [comment]
That export, along with replacing all instances of `~/` with `/Users/username/`, worked. Don't know why it needed hardcoded paths, but it seems to have made a difference.
Now, CMake and `make SampleApp -j4` both work! Thank you!

**Comment by Vaishnavikumara** [comment]
I am still facing the error saying that "libcrypto"package cant be found.Please help!


vaishnavi@DESKTOP-HCUNIKM:~/my_project/build$ export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:$PKG_CONFIG_PATH"
vaishnavi@DESKTOP-HCUNIKM:~/my_project/build$ echo $PKG_CONFIG_PATH
/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:/usr/local/opt/libcrypto/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:” export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig:”
vaishnavi@DESKTOP-HCUNIKM:~/my_project/build$ cmake /home/vaishnavi/my_project/source/avs-device-sdk -Wno-dev -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/vaishnavi/my_project/third-party/portaudio/lib/.libs/libportaudio.a -DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib -DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include  -DPORTAUDIO_INCLUDE_DIR=/home/vaishnavi/my_project/third-party/portaudio/include && make
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the ACL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the ADSL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the AFML with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the DeviceSettings with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the BluetoothImplementations with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the EqualizerImplementations with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the CertifiedSender with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the ContextManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the CapabilitiesDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the PlaylistParser with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Checking for module 'libcrypto'
--   No package 'libcrypto' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  PlaylistParser/src/CMakeLists.txt:2 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/vaishnavi/my_project/build/CMakeFiles/CMakeOutput.log".
See also "/home/vaishnavi/my_project/build/CMakeFiles/CMakeError.log".
