### ISSUE TITLE
Readme file contains dead links for me

### ISSUE THREAD

**Issue by rekire** [alexa/avs-device-sdk#1274]
Sorry for ignoring your template, but this issue is very generic.

I see tons of 404 errors while searching resources related to Alexa. E.g. both links in the "Alexa Communications Library (ACL)" section of you readme file shows me a 404 error. I *guess* that is related to the routing of localized help pages. This is a generic hint to test your links in the documentation with a different browser language then English!

**Comment by aumatsui** [comment]
Hi rekire, 

Thank you for your message. Can you clarify which language you are using on your browser and in which URL you are receiving a 404? This will help us identifying and fixing the issue.

Regards,

**Comment by rekire** [comment]
I'm from Germany, so I'm using German.

I'll try to indentify some links timeboxed for 5 minutes:
https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection -> https://developer.amazon.com/de/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/avs-http2-requests -> https://developer.amazon.com/de/public/solutions/alexa/alexa-voice-service/docs/avs-http2-requests

https://developer.amazon.com/docs/alexa-voice-service/ -> https://developer.amazon.com/de/docs/alexa-voice-service/

https://developer.amazon.com/de/public/apis/engage/login-with-amazon/docs/cross_site_request_forgery.html

**Comment by aumatsui** [comment]
Hi rekire,

Thank you for your help. I will file an internal ticket to the team in charge of this documentation.

I am closing this issue, but feel free to reopen it if you have any additional data or concern.

Regards,

**Comment by rekire** [comment]
Could you leave a comment when this is fixed?
If so I could report more broken links when it should be fixed.
