### ISSUE TITLE
AVS device sdk authentication errors - The refresh request failed with the response code 400

### ISSUE THREAD

**Issue by satishc4u** [alexa/avs-device-sdk#128]
Hi,
I followed the https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide steps to setup avs device sdk in my raspberry pi.Getting the following error when my raspberry device is trying to access to authentication from amazon,
Help me to fix the issue.

**pi@raspberrypi:~/BUILD $ python AuthServer/AuthServer.py
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.**

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

Here is My **AlexaClientSDKConfig.json**

{
    "authDelegate":{
        "clientSecret":"1234",
        "deviceSerialNumber":"1234",
        "refreshToken":"",
        "clientId":"1234",
        "deviceTypeId":"234"
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"/home/pi/test/Database/",
     "alarmSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_01._TTH_.mp3",
     "alarmShortSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_01._TTH_.mp3",
     "timerSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_02._TTH_.mp3",
     "timerShortSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_02._TTH_.mp3"
   }
 }

**Comment by smititelu** [comment]
@satishc4u make sure you have the right authDelegate credentials in the AlexaClientSDKConfig.json, as found in your alexa developer account, after creating a new device. Also make sure to allow the redirect URL in the security tab, associated with your device. The redirect URL is the one found in AuthServer.py (grep for it).

Then delete the refeshToken line in the AlexaClientSDKConfig.json (it will be auto generated after the request), run the AuthServer.py and open that link in a browser and login.

Also, feel free to look in the AuthServer.py and change the listening and redirect address. :)

**Comment by kencecka** [comment]
Hi @satishc4u,

It looks like you have filled in random numbers for your clientSecret, clientId and deviceTypeId.  For AuthServer.py to work correctly, you need to put the real clientSecret, the real clientId, and the real deviceTypeID that you obtained when you created your device on developer.amazon.com.  You also need to provide a unique deviceSerialNumber, but you can make up any value you want for that (1234 should be fine).

Let us know if you are still having trouble after updating your AuthServer.py.

Ken

**Comment by kuodehai** [comment]
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

 {
    "authDelegate":{
        "clientSecret":"f3b48e88b92228324a40465329c4f365faf1ced97d128408b6d42669c57c7c4c",
        "deviceSerialNumber":"123456",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.37b63f01091146249651b5774523982b",
        "productId":"my_Device"
     },

   "alertsCapabilityAgent":{
        "databaseFilePath":"",
        "alarmSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01_short._TTH_.wav",
        "timerSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02_short._TTH_.wav"
   },

   "settings":{
        "databaseFilePath":"",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },

   "certifiedSender":{ 
        "databaseFilePath":"{SDK_CERTIFIED_SENDER_DATABASE_FILE_PATH}"
    }
 }

**Comment by kuodehai** [comment]
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

 {
    "authDelegate":{
        "clientSecret":"f3b48e88b92228324a40465329c4f365faf1ced97d128408b6d42669c57c7c4c",
        "deviceSerialNumber":"123456",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.37b63f01091146249651b5774523982b",
        "productId":"my_Device"
     },

   "alertsCapabilityAgent":{
        "databaseFilePath":"",
        "alarmSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01_short._TTH_.wav",
        "timerSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02_short._TTH_.wav"
   },

   "settings":{
        "databaseFilePath":"",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },

   "certifiedSender":{ 
        "databaseFilePath":"{SDK_CERTIFIED_SENDER_DATABASE_FILE_PATH}"
    }
 }

**Comment by baddemiya** [comment]
on browser open http://localhost:3000 and login with your amazon credentials
