### ISSUE TITLE
sampleApp can‘t connect server

### ISSUE THREAD

**Issue by ahducheng** [alexa/avs-device-sdk#1280]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?

Android4.4 does not support TLS1.2 agreement, I by modifying the libcore Nativecryto makes the SSL handshake with normal server, but when the SSL_write will now 
03-15 14:59:15.111 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err: javax.net.ssl.SSLException: Write error: ssl=0x7f74e408: I/O error during system call, Broken pipe
03-15 14:59:15.111 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)

I don't know what to do in android4.4 platform now can normal use the app，Server only supports two TLS1.2 version of encryption suite, does not support TLS and SSL3.0
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: andorid4.4 platform

### Tell us about your OS (Type & version):andorid4.4  platform
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by ahducheng** [comment]
[
[ThinkDrive.zip](https://github.com/alexa/avs-device-sdk/files/2969868/ThinkDrive.zip)
Is a network packet
](url)

**Comment by ahducheng** [comment]
System.err: javax.net.ssl.SSLException: Write error: ssl=0x7f74e408: I/O error during system call, Broken pipe
03-15 14:59:15.111 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
03-15 14:59:15.111 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:737)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.Okio$1.write(Okio.java:78)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSink.write(Http1Codec.java:325)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:85)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexavoicelibrary.actions.SendAudioActionFragment$2.writeTo(SendAudioActionFragment.java:145)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:59)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$AsyncEventHandler.success(AlexaManager.java:606)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$AsyncEventHandler.success(AlexaManager.java:586)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.interfaces.speechrecognizer.SpeechSendAudio.sendAudio(SpeechSendAudio.java:58)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$5$1$1.doInBackground(AlexaManager.java:351)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at com.willblaschko.android.alexa.AlexaManager$5$1$1.doInBackground(AlexaManager.java:346)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary W/System.err:     at java.lang.Thread.run(Thread.java:841)
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary I/BaseActivity: Event Error
03-15 14:59:15.121 7550-1242/com.willblaschko.android.alexavoicelibrary I/BaseActivity: Event Complete

**Comment by aumatsui** [comment]
Hi ahducheng,

Can you clarify which version of the SDK you are using? You can see on CHANGELOG.md, as the first version that appears on the document.

Thank you,

**Comment by aumatsui** [comment]
Based on your logs, it looks like you are using the Java client. Unfortunately this SDK was already deprecated and we no longer offer support for it.

Please let us know here if there is anything else we can help you with.

Regards,
