### ISSUE TITLE
alexa on raspberry pi does not play on bluetooth speaker

### ISSUE THREAD

**Issue by kiwisaurio** [alexa/avs-device-sdk#1283]
Hi guys, I've bought a new bluetooth speaker and paired it with my RPi. It works fine playing sounds from youtube and VLC, but when I start the Alexa script, it doesn't play on the bluetooth speaker. Does someone know something about this? I can share any info you guys need, just tell me about.

**Comment by kjkh** [comment]
Hi @kiwisaurio,

While the SDK supports sending audio to a connected Bluetooth speaker, customers must utilize another component to perform the actual audio routing. The SDK will send the audio data to whatever sink you are using in the gstreamer pipeline, but the audio data needs to be routed to the Bluetooth stack. One straight forward option is to use PulseAudio. Another option if you are using ALSA directly is to explore BlueALSA. However there will still be some additional work required if you go this route.
