### ISSUE TITLE
Dynamic KeywordDetectorProvider

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#1284]
Hello AVS-Team,

the [KeywordDetectorProvider.cpp](https://github.com/alexa/avs-device-sdk/blob/master/KWD/KWDProvider/src/KeywordDetectorProvider.cpp) is static in 2 ways

- the 3 KITT_AI_* params are static const (see #665)
- the result of KeywordDetectorProvider::create is set static with the build (see #684)

With a simple patch the KeywordDetectorProvider.cpp becomes dynamic so that

- the 3 KITT_AI_* params are expected as env-vars with the same names
- the result of KeywordDetectorProvider::create is evaluated at runtime depending on an env-var `WakeWordEngine`

You can find the patched version [here](https://gitlab.com/khassel/alexa_sdk_docker/blob/master/build/KeywordDetectorProvider.cpp) and I know that this is not the best solution (its my first C++ work ...) but this works in my environment (where the 3+1 env-vars are always set).

Purposes of the dynamic solution:
- no recompile necessary when changing the KITT_AI_* params
- for testing the SampleApp with different WakeWordEngines only one compile necessary
- simplifies providing the SampleApp as docker image (one compile, one image)

The issues #665 and #684 where closed with the comment "I have created a ticket for the SDK team.". May these tickets can be merged together and hopefully we can get a solution some day (should not cost much time ...).

Thanks,

Karsten.

### What version of the AVS Device SDK are you using?
v1.12

### Tell us what hardware you're using:
- [X] Raspberry Pi

### Tell us about your OS (Type & version):
- [X] Raspbian Stretch

**Comment by dhpp** [comment]
Thanks @khassel, we appreciate you taking the time to do this.  We will consider this when planning our future releases.
