### ISSUE TITLE
Multi-Room Music (MRM) setup issue

### ISSUE THREAD

**Issue by xurenjun** [alexa/avs-device-sdk#1287]
Hello AVS-Team,
1) When I used the MRM function based on AVS1.12, I found that SampleApp reported an error when 
    running:

    2019-03-21 01:26:29.773 [  1] E 
    CapabilitiesDelegate:capabilityMapIncorrectlyFormed:reason=interfaceTypeNotAvailable  
    2019-03-21 01:26:29.774 [  1] E 
    CapabilitiesDelegate:registerCapabilityFailed:reason=capabilityNotDefinedCorrectly
    2019-03-21 01:26:29.774 [  1] E 
    DefaultClient:initializeFailed:reason=unableToRegisterCapability,capabilitiesDelegate=MRM

2) AlexaClientSDKConfig.json add:
    "mrm": {
        "amazonId": "xxxxxx",
        "audioPlayerDeviceName": "hw:0,2",
        "audioPlayerSampleRate": 48000,
        "audioPlayerOffsetDurationNs": 0,
        "clockNominalDriftPpm": "0.0",
        "clockDriftTolerancePpm": "20.0",
        "audioClockSystemClockDriftPpm": "0.0"
    },

    "capabilitiesDelegate":{                 
        "endpoint": "https://api.amazonalexa.com",
        "overridenCapabilitiesPublishMessageBody": {                               
            "envelopeVersion":"20160207",       
            "capabilities":[
               {
                   "type":"AlexaInterface", 
                   "interface":"WholeHomeAudio",
                   "version":"1.1" 
                } 
            ]
        }
    },

3) Maybe there is something wrong with the configuration. Do you have the configuration instructions of 
    MRM? Or how to set up the MRM so that it works properly? Do you have a reference manual?

Thanks!

**Comment by xurenjun** [comment]
I have solved the above problem.  Need modify:

+/// Device Capability Framework - MRM interface type
+static const std::string MRM_CAPABILITY_INTERFACE_TYPE = "AlexaInterface";
+/// Device Capability Framework - MRM interface name
+static const std::string MRM_CAPABILITY_INTERFACE_NAME = "WholeHomeAudio";
+/// Device Capability Framework - MRM interface version
+static const std::string MRM_CAPABILITY_INTERFACE_VERSION = "1.1";

But how to set up a bedroom or living room ?

**Comment by dhpp** [comment]
Hi @xurenjun, if you have set this up correctly, then when running and connected to AVS your MRM-capable devices should be available to create groups in your Alexa companion app in the SmartHome->Groups->MRM Groups section.  Let us know if that does not seem to work.

**Comment by xurenjun** [comment]
![1](https://user-images.githubusercontent.com/19235590/54796684-22884880-4c8c-11e9-9133-4c8210bd08f0.jpg)
![2](https://user-images.githubusercontent.com/19235590/54796689-274cfc80-4c8c-11e9-9a66-603cdaae732d.jpg)
![QQ截图20190322101929](https://user-images.githubusercontent.com/19235590/54796697-2e740a80-4c8c-11e9-80a6-9ab5ca7e081c.png)

**Comment by xurenjun** [comment]
Thanks  @dhpp   I`m not found "SmartHome->Groups->MRM Groups section". But when I setup MRM groups via Alexa APP, I found some problems:
When the two platform devices are running, I can see the two online devices on the APP side:
![11](https://user-images.githubusercontent.com/19235590/54814515-e1635900-4cca-11e9-8096-c0827817fc87.png)

But when I choose renjun xu1, renjun, xu2 becomes Device Unreachable:
![22](https://user-images.githubusercontent.com/19235590/54814536-ede7b180-4cca-11e9-84e8-7988710a027b.png)

when I choose renjun xu2, renjun, xu1 becomes Device Unreachable:
![33](https://user-images.githubusercontent.com/19235590/54814552-f63fec80-4cca-11e9-96a4-7d049793a63d.png)

**Comment by xurenjun** [comment]
I see some errors in the log, but I'm not sure if this is the cause？

**Comment by xurenjun** [comment]
![000](https://user-images.githubusercontent.com/19235590/55047878-331c3280-5081-11e9-881c-94f98b7302ea.png)

I see some errors in the log, but I'm not sure if this is the cause？

**Comment by mvelegon-amzn** [comment]
Hi @xurenjun thank you for sending us the log. We are currently looking into it and will let you know once we have more information on this.

**Comment by celinval** [comment]
Hi @xurenjun,

Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.

Regards,
