### ISSUE TITLE
How to release and access to the microphone?

### ISSUE THREAD

**Issue by PattenKuo** [alexa/avs-device-sdk#1288]
## Briefly summarize your issue:
How to release and then access to the microphone? I'm running the Alexa on a AGL(Automotive Grade Linux) develop-board.
Other software may use microphone, however the Alexa always occupies the microphone and never realeases the microphone.
The question is:  Is there any function will let Alexa release the microphone? if yes, could you tell me where it is?if not, how can I  let Alexa release the microphone?
I'll appreciate it if you could help me.
Thanks.

## What is the expected behavior?
Release microphone --> access to microphone again.

### What version of the AVS Device SDK are you using?
    version: 1.9

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ✓ ] Other - tell us more: AGL board

### Tell us about your OS (Type & version):
- [ ✓ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @PattenKuo, we may provide this functionality already in the SampleApp per the mute functionality, which invokes the sampleApp::PortAudioMicrophoneWrapper::stopStreamingMicrophoneData method.  This invokes Pa_StopStream on PortAudio, which may be sufficient to release the microphone.  If that does not have the desired result, we would suggest digging deeper into the PortAudio interface to identify what further needs to be done.

Let us know if you need any further guidance on how to integrate that into the SampleApp.
