### ISSUE TITLE
Play falsh briefing failed.

### ISSUE THREAD

**Issue by ada1013** [alexa/avs-device-sdk#1290]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have problem to play flash briefing, the log is here: 
[1.log](https://github.com/alexa/avs-device-sdk/files/2994618/1.log)

I got an error message: 
UrlContentToAttachmentConverter:onPlaylistEntryParsed:status=ERROR.
Please let me know if any suggestion, thanks~

## What is the expected behavior?

play flash briefing as normal.
## What behavior are you observing?

No response.
## Provide the steps to reproduce the issue, if applicable:

me: Alexa, play my flash briefing.
Alexa: here is your flash briefing.
silence... 
### What version of the AVS Device SDK are you using?
      <1.12.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @ada1013, the logfile also shows trace such as:

PlaylistParser:doDepthFirstSearchFailed:reason=badHTTPContentReceived,statusCode=0

which suggests the flash briefing playlist was malformed when sent from the server.  The client was simply not able to parse it.  This may be addressed in a fix we are currently working on, so our suggestion would be to test this with the next release and let us know if the issue persists.

**Comment by ada1013** [comment]
Thanks @dhpp ,

May I know when will you release the next version?

**Comment by jpravs** [comment]
@dhpp to clarify, is this going to be a Cloud or SDK fix? Curious why only this device is running into this if it's a Cloud issue, I've tested other AVS devices and they don't exhibit this behavior

**Comment by ada1013** [comment]
Hi @dhpp , by upgrading to 1.12.1, the problem was solved. Thanks again for your help.
