### ISSUE TITLE
Italian not listed in Settings Interface documentation page

### ISSUE THREAD

**Issue by melvinwaller** [alexa/avs-device-sdk#1295]
## Briefly summarize your issue:
The SDK release notes and sample app refer to Italian, but the reference documentation for Settings does not list it-IT as a valid accepted value.

## What is the expected behavior?
I would expect to see it-IT under Accepted Key/Value Pairs at https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated-event

## What behavior are you observing?
As above

**Comment by mvelegon-amzn** [comment]
Hi @melvinwaller thank you for bringing this to our attention. We will get the documentation updated.
