### ISSUE TITLE
Unable to initialize Sample Application for Alexa AVS on Ubuntu 16.04

### ISSUE THREAD

**Issue by Mithun6193** [alexa/avs-device-sdk#1296]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
i am trying to create a Sample AVS application for ubuntu 16.04 (based on https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide) but i am facing some errors while initializing my Sample applciation ( from the authorisation part https://github.com/alexa/avs-device-sdk/wiki/Authorization#macOS,-Ubuntu-Linux-16.04-LTS,-and-Raspberry) on running this command /SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json

##################################
#       NOT YET AUTHORIZED       #
##################################
################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
################################################################################################

## What behavior are you observing?
2019-03-26 05:06:07.270 [  1] I sdkVersion: 1.12.0
configFile ./Integration/AlexaClientSDKConfig.json
2019-03-26 05:06:07.276 [  1] C SampleApplication:Failed to initialize SDK!
2019-03-26 05:06:07.278 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

## Provide the steps to reproduce the issue, if applicable:
following the steps given in the guide for ubuntu 16.04  https://github.com/alexa/avs-device-sdk/wiki/Authorization#macOS,-Ubuntu-Linux-16.04-LTS,-and-Raspberry

## Tell us about your environment:
ubuntu 16.04 LTS
### What version of the AVS Device SDK are you using?
    1.12.0

### Tell us what hardware you're using:
- [ yes] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [yes ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @Mithun6193 Thanks for reaching out. Looking at the output you sent, it seems like the AlexaClientSDKConfig.json file has not been configured correctly. Please follow the steps here to setup the AlexaClientSDKConfig.json file: https://github.com/alexa/avs-device-sdk/wiki/Authorization#Generic-Linux 

Additionally if you still face an issue please turn on debug logs by running the sample app as follows:
`SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9` and attach the log file to this issue.

**Comment by Mithun6193** [comment]
once i used the SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9 my error was the same as the one found on this link  https://github.com/alexa/avs-device-sdk/issues/681, thankyou so much for the insight.
