### ISSUE TITLE
unable to test curl after configuring with nghttp2 and openssl

### ISSUE THREAD

**Issue by Mithun6193** [alexa/avs-device-sdk#1297]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
i am following this guide https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide after "Download the latest version of curl and configure with support for nghttp2 and openssl:" i am supposed to test curl by  using this command 
curl -I https://nghttp2.org/ but when i execute that there is no response .

## What is the expected behavior?
HTTP/2 200
date: Fri, 15 Dec 2017 18:13:26 GMT
content-type: text/html
last-modified: Sat, 25 Nov 2017 14:02:51 GMT
etag: "5a19780b-19e1"
accept-ranges: bytes
content-length: 6625
x-backend-header-rtt: 0.001021
strict-transport-security: max-age=31536000
server: nghttpx
via: 2 nghttpx
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

## What behavior are you observing?
There is no response, i have to exit by pressing ctrl+c

## Provide the steps to reproduce the issue, if applicable:
follow the steps as in https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

## Tell us about your environment:
ubuntu 16.04 LTS
### What version of the AVS Device SDK are you using?
      1.12.0

### Tell us what hardware you're using:
- [yes ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ yes] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @Mithun6193 could you post the output of `curl --version` here?

**Comment by celinval** [comment]
Hi @Mithun6193, were you able to solve this problem? Can you reach the host:

`ping nghttp2.org`

**Comment by Mithun6193** [comment]
i am able to reach the host nghttp2.org but if i use https:// it does not work, it is taking too much time and is not working so i've decided to drop this project and try it with windows 64 bit version. Thank you for time.
