### ISSUE TITLE
Can't build Portaudio on Mojave MacOS.

### ISSUE THREAD

**Issue by tamarahills** [alexa/avs-device-sdk#1298]
## Briefly summarize your issue:
I'm unable to build portaudio on MacOS 10.14 (Mojave).

## What is the expected behavior?
Expected behavior is that the command `./configure --disable-mac-universal` should generate a makefile for me, but it does not.  

## What behavior are you observing?
I am successful at running all the prerequisites up to this point as per the MacOs quick start guide.  The help tells me to run `./configure --disable-mac-universal` if I get the error "error: cannot find 10.5 to 10.12 SDK".  so, after running `./configure --disable-mac-universal` I receive the following errors:

config.status: creating Makefile
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/gawk
  Reason: image not found
./config.status: line 1129:  9231 Done(141)               eval sed \"\$ac_sed_extra\" "$ac_file_inputs"
      9232 Abort trap: 6           | $AWK -f "$ac_tmp/subs.awk" > $ac_tmp/out
config.status: error: could not create Makefile

I also tried sudo, but receive the same result.

## Provide the steps to reproduce the issue, if applicable:
1.  Follow steps in MacOs quick start guide and then run `./configure --disable-mac-universal`

## Tell us about your environment:
MacOs 10.14 (Mojave)
Python 2.7.14
Xcode 10.1
Build version 10B61

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
Macbook pro 3.5 GHz Intel Core i7

### Tell us about your OS (Type & version):
- [ ] MacOS  10.14

**Comment by mvelegon-amzn** [comment]
Hi @tamarahills thanks for bringing this to our notice. From the error you posted, it seems like this is a dependency issue with gawk. Could you try running `brew upgrade gawk` and see if it fixes the issue?

**Comment by tamarahills** [comment]
@mvelegon-amzn That fixed it!  Thank you!
