### ISSUE TITLE
Volume goes up after the alarm is played

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1310]
Hello AVS Team,

I am using the api **void UIManager::onSpeakerSettingsChanged()**  for volume control from alexa into my system.

I observed the issue of volume increase after the alarm is played.

Steps:-
1. Currently the volume level of speaker is 6
2. Set an alarm by voice query.
3. The alarm will play with the same volume level 6.
4. Now Stop the alarm by saying "Alexa Stop the alarm".
5. Now again ask the query "Alexa What is the current volume level"
It will reply with 6 volume but the volume of speaker increased to high i.e 10.

As we have received the volume level high command from the server in  **void UIManager::onSpeakerSettingsChanged()** function.

This is happening only in the case when the alarm is played.

Can you please help me with the exact volume behavior of avs-device-sdk client  and AVS server in the case of playing alarm.

sdk version - 1.9
Platform - Ubuntu

**Comment by celinval** [comment]
Hi @sumit3817, I wasn't able to reproduce the issue. Can you please provide some logs? Thanks!

**Comment by sumit3817** [comment]
Hi,

This is fixed now. Sorry to trouble you.

This is the issue when after timer or alarm, server sends us the volume maximum notification.

It is handled now.

You can close this issue.

Thanks a lot for your support.

**Comment by celinval** [comment]
No worries. I'm glad to hear that the issue has been fixed already. Thanks for letting us know!
