### ISSUE TITLE
Alexa build sdk source: problem gstreamer-1.0

### ISSUE THREAD

**Issue by tjyuanxi** [alexa/avs-device-sdk#1311]
I complier alexa media player in ubuntu14.4 for arm .
Now I have had all gstreamer lib, but i do not know how join them to media player

My command:
source /opt/oecore-x86_64/environment-setup-cortexa7hf-neon-poky-linux-gnueabi
cmake ../MediaPlayer -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_BUILD_TYPE=Debug -DARCH=arm
Error:
CMake Error at /opt/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
A required package was not found
Call Stack (most recent call first):
/opt/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
/home/jiantang/blackwarrior/avs-device-sdk-master/build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
/home/jiantang/blackwarrior/avs-device-sdk-master/build/BuildDefaults.cmake:25 (include)
GStreamerMediaPlayer/CMakeLists.txt:4 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jiantang/blackwarrior/avs-device-sdk-master/MediaPlayer_build/CMakeFiles/CMakeOutput.log".

I set export PKG_CONFIG_PATH=/home/jiantang/blackwarrior/avs/gstplugin/lib/pkgconfig,but the issue is still occure.

Help me, thks

**Comment by celinval** [comment]
Hi @tjyuanxi ,

Can you export PKG_CONFIG_LIBDIR instead of PKG_CONFIG_PATH and see if it works?

Thanks,
Celina

**Comment by tjyuanxi** [comment]
@celinval  Thank you， i fixed by PKG_CONFIG_PATH
