### ISSUE TITLE
Question about AVS functional test case#107

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1312]
Hi AVS team,

I have a question about functional test case#107 in v2.0.7 document :

Verify that when the device is unable to connect to the AVS webservice, the device does not try to reconnect more than 50 times in 10 minutes, using an appropriate exponential backoff method.  See: https://docs.aws.amazon.com/general/latest/gr/api-retries.html for guidance.

Could you advise which part I can check in AVS SDK for this case? Is it registration interval ?

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang, you can find the reconnect backoff logic in this function:

https://github.com/alexa/avs-device-sdk/blob/c93a898b76b02c591daffee832f5f7cd64c46205/ACL/src/Transport/HTTP2Transport.cpp#L539

For CBL authorization, the logic is here:

https://github.com/alexa/avs-device-sdk/blob/c93a898b76b02c591daffee832f5f7cd64c46205/SampleApp/Authorization/CBLAuthDelegate/src/CBLAuthDelegate.cpp#L498

**Comment by zeusshuang** [comment]
thanks, just want to confirm the design.
