### ISSUE TITLE
Setup feezes on building InteractionManager.cpp.o

### ISSUE THREAD

**Issue by tarikaltuncu** [alexa/avs-device-sdk#1316]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
<Following the setup guide here: https://developer.amazon.com/docs/alexa-voice-service/build-the-avs-device-sdk.html
Tried a few times but each time the setup freezes the raspberry pi on building InteractionManager.cpp.o at 97%. 
Mouse cursor becomes extremely laggy.
Even system time does not update and no progress even after 1 hour.
Screen goes off after time out and comes back with a mouse move.>

## What is the expected behavior?
<To complete all>

## What behavior are you observing?
<Freezing before completion of setup>

## Provide the steps to reproduce the issue, if applicable:
<1. reboot 2.cd into github repo clone, run sudo bash setup.sh config.json [-s 1234]
>

### What version of the AVS Device SDK are you using?
      <1.12.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by tarikaltuncu** [comment]
I passed that point. Apparently, that point is where the setup requires the top amount of memory and it was because of low memory in the system.
If you set the graphic memory to 256 MB, you get 780 MB left and that step requires around 800 MB free memory.
Completed with success now.

**Comment by ujjwalk450** [comment]
@tarikaltuncu how much time does it usually take to complete that step ? my gpu memory is 32 mb and i still cannot complete it

**Comment by tarikaltuncu** [comment]
I don't remember, sorry.

**Comment by ujjwalk450** [comment]
i am stuck at the same issue and after a day of waiting, it closed the script automatically.

**Comment by Haddybaba123** [comment]
I also have the same problem first I was stucked at 93% then after writing various commands and decresing the graphics memory it started but then got stucked on 95% please help waiting from a month and I have also written the same thing on the stackoverflow but no response please please and please help me out

**Comment by Haddybaba123** [comment]
I think someone among you understands

**Comment by ujjwalk450** [comment]
@Haddybaba123 So here is how I resolved it
1. Switched to CLI mode instead of GUI for better RAM usage
2. Decrease your GPU memory as low as possible
3. Leave it overnight, it will fail/autoclose a minimum of 5-6 times before getting completed, everytime it fails, restart your Pi
