### ISSUE TITLE
Issue in Alexa pre-certification - WWE

### ISSUE THREAD

**Issue by irfankhanharman** [alexa/avs-device-sdk#1323]
We are working on one Alexa enabled device.  we are doing  pre-certification tests with one of the amazon authorized partners.  the product is for US and test files being used are US accent files. for most of US accents it works fine but for some accent files for Far field tests, the device is not waking up at all while other far field tests are working fine. we are using Amazon Alexa WWE.

Another interesting observation, it works fine with external music and device music but only for silence, this issue is coming.

## What is the expected behavior?
since it is Amazon WWE, it should wakeup for all the US accents from near and far filed.

## What behavior are you observing?
Device is not waking up for some US accents for far field test in silence.

## Tell us about your environment:
iAlexa 1.9 SDK.

### Tell us what hardware you're using:
3 mic array , Artik 530S, 512 MB RAM.

### Tell us about your OS (Type & version):
Ubuntu 16.04

Please suggest if we are missing any thing. initial feeling, it is some configuration?

appreciate your help.

**Comment by visayamv** [comment]
Hi @irfankhanharman , I would suggest to talk to your Amazon Business Development Representative (or your Amazon Authorized partner and talk to the Amazon Representative) regarding your case. They should be able to answer what voice models are supported.

**Comment by irfankhanharman** [comment]
thank you for quick reply. 
Though I have sent email to Amazon contact. but my concern is we are using Amazon WWE, so it should work like other devices. we are getting issue only during silence far field testing.

**Comment by visayamv** [comment]
Hi @irfankhanharman ,  Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.
