### ISSUE TITLE
[avs-device-sdk]1.9: How to stop the alarm by not giving command 'Alexa Stops'

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1324]
Hi AVS Team,

I need to know some information regarding timer and alarms alerts.

How to stop playing alarm by **not saying** 'Alexa Stop'. 

The scenario is when the user wants the alarm to be stopped by pressing the button on the device.
I need to stop this alarm by using some gpio control. Is there any API where I can stop the current playing alarm?

Platform - Ubuntu
avs-device-sdk version - 1.9

Thanks

**Comment by visayamv** [comment]
Hi @sumit3817 , when running SampleApp this is equivalent to the 's' command for stop foreground activity. You can try this out by setting up an alarm, and when the alarm fires, type 's' and press enter and it should stop the alarm.

Pressing 's' command calls the following function. You can do something similar to hook on your gpio handler.

https://github.com/alexa/avs-device-sdk/blob/451e6056aee3b92a01e9b58d79f1f30a11625beb/SampleApp/src/InteractionManager.cpp#L147-L149

**Comment by sumit3817** [comment]
Hi,

Thanks a lot for the information.
I have an another query. Is there any event callback given in SampleApp for the Alarm state:-
 1. Alarm played State
 2. Alarm snooze State
 3. Alarm Stopped State

I have a requirement to glow the LED on these states.

Thanks

**Comment by visayamv** [comment]
Hi @sumit3817 , yes, you can implement the AlertObserverInterface and register it to the AlertsCapabilityAgent::addObserver method.

**Comment by sumit3817** [comment]
Hi,

Thanks again for the information.

After implementing the function, I found an issue.

I am receiving AlertObserverInterface::State::STARTED immediately but there is a delay in AlertObserverInterface::State::STOPPED state.

When I say "Alexa Stop", the alarm gets stopped immediately but I receive this state on callback after 10 seconds.

Can you please tell why there is a delay of 10 seconds (in the case of AlertObserverInterface::State::STOPPED) on receiving this callback because I am glowing LED on the basis of this callback.

Thanks

**Comment by kclchan** [comment]
I believe this is related to ##1335, and since that issue is closed, I am closing this as well.  Thanks!
