### ISSUE TITLE
Missing-gst plugin when playing BBC news

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#133]
When I say ‘alexa，play bbc news ’，the sampleAPP will crash by the missing plugin err.But I have used gst-inspect-1.0 to check the plugin is installed.
```
2017-09-04 11:17:52.906 [  2] 9 MediaPlayer:handleBusMessage:message=GST_MESSAGE_BUFFERING,percent=100
2017-09-04 11:17:52.923 [ 10] I DirectiveRouter:preHandleDirective:messageId=e660643c-7bd5-4e14-9e54-c928bd24d9c9,action=calling
2017-09-04 11:17:52.932 [  2] E MediaPlayer:handleBusMessageError:source=decoder,error=Your GStreamer installation is missing a p
lug-in.,debug=gsturidecodebin.c(998)\: no_more_pads_full ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder\:
no suitable plugins found\:
gstdecodebin2.c(4600)\: gst_decode_bin_expose ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder/GstDecodeBin\:decodebin4
\:
no suitable plugins found\:
Missing decoder\: text/uri-list (text/uri-list)
```

**Comment by scotthea-amazon** [comment]
Hello NyxRockchip2017,

It looks like GStreamer is running in to a playlist that is not supported.  Unfortunately, the avs-device-sdk does not yet support playlists (just iHeartradio).  That will be coming in future releases.  Thank you for bringing this to our attention, it will make a good test case!

Thank you,
-SWH

**Comment by NyxRockchip2017** [comment]
ok，I hope you can solve it as soon as possible，thks.
