### ISSUE TITLE
Alerts: Callback is getting delayed for event capabilityAgents::alerts::AlertObserverInterface::State::STOPPED

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1335]
Hello AVS Team,

I have implemented the callback for Alerts in UIManager.cpp.
       **void UIManager::onAlertStateChange(const std::string& alertToken, capabilityAgents::alerts::AlertObserverInterface::State state, const std::string& reason);**

For the event **capabilityAgents::alerts::AlertObserverInterface::State::STOPPED**
When I say "Alexa Stop", the timer sound stops immediately **but I am getting this callback delayed for 8 to 10 seconds**

Can you please let me know the reason of getting this callback delayed ?
I have also debugged the avs-device-sdk code where it also delayed.

avs-device-sdk version - 1.9
Platform - Ubuntu

**Comment by kclchan** [comment]
@sumit3817, thanks for opening this issue.  Would you be able to attach the DEBUG9 logs for this issue so that we can investigate further the reasons for the delay.  Thanks!

**Comment by sumit3817** [comment]
Hi,

I have tested in 1.12.1 and found fixed.
You can close this issue.

Thanks for the support
