### ISSUE TITLE
Notifications: State OFF is not in sync with the server

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1337]
Hello AVS Team,

I am facing notification state sync issue with the server.

Scenario:-
I have two device (1 Amazon Echo Plus and another mine device on which avs-device-sdk 1.9 is running) configured with the same Amazon account. And both the devices are online
Skill Enabled on my account is : Notify Me
Steps:-
1. I send the notification and it is received on both the devices.
2. Now I power off my device
3. Ask "Alexa What are my notifications" to Echo device.
4. It replied well with the notifications and the notifications are cleared.
5. Now I power on my device, it comes up and connect to server, but the issue is the notification is not cleared from my device. I still gets NOTIFICATION_ON in the callback (already present in UIManager.cpp)
6. But when I ask "Alexa What are my notofications" to my device, it replied with no notification and I received NOTIFICATION_OFF now.

In the same opposite case, Amazon Echo is able to get the clear notification when it comes up.

**The issue is I am not able to get the NOTIFICATION_OFF state in the callback when the device comes up again**. It is not in sync with the server automatically.

Platform - Ubuntu
avs-device-sdk - 1.9

**Comment by kclchan** [comment]
Hi @sumit3817, would you be able to send us the DEBUG9 logs?

**Comment by elfdie00475** [comment]
Hi,

We have the same issue in #1248.
We take this issue to ask our AVS solutions architect. And this is his answer:
Looking at your log [(notification_log3.TXT)](https://github.com/alexa/avs-device-sdk/files/3210173/notification_log3.TXT), you are right. The cloud should send a clearIndicator directive at startup, but that doesn’t happen until line 997 . That is right in the midst of a SpeechRecognize event, so I am thinking you used a voice command to ask about notifications.

We think post result in here, it can be attention to SDK team. And hope this will help you.
Thanks~~
