### ISSUE TITLE
Deregister and republish Music Capabilities Agent

### ISSUE THREAD

**Issue by Agrahyah** [alexa/avs-device-sdk#1340]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue
For developing a Android companion app, want to temporarily disable Music player capabilities, when bluetooth is off or when correct bluetooth device is not connected to phone.

## What is the expected behavior?
No deregister function to disable and republis capabilities

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*] Other - tell us more: Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: Android

**Comment by Agrahyah** [comment]
For registration there is a method CapabilitiesDelegate.registerCapabilities but no such method to deregister them

**Comment by kjkh** [comment]
Hi @Agrahyah,

While possible, it is not recommended to dynamically de-registered capabilities based on state. This applies especially to AudioPlayer, which is a core Capability Agent upon which many cloud side components have complex (and legacy) interactions with. Doing so will likely have adverse side effects and not achieved the desired goal.

Can you elaborate further on the behavior you are trying to implement?

**Comment by Agrahyah** [comment]
I want to support Alexa Music only when a specific set of devices are connected to my mobile via Bluetooth, else I want to allow access to other Alexa functionalities but not the Music.

**Comment by dhpp** [comment]
@Agrahyah, per AVS and DCF documentation, the de-registration behavior your are seeking is not supported.  When a device connects to AVS, it must publish its supported capabilities so that AVS may correctly route and handle traffic for the device.  The closest you could get (which is supported by us) would be to exit the connection, and make a new connection to AVS publishing the different capability set.

**Comment by dhpp** [comment]
Closing for now - please re-open if you'd like further comment.
