### ISSUE TITLE
Timer：can not start

### ISSUE THREAD

**Issue by wjd19900102** [alexa/avs-device-sdk#1341]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

1.Modify the system time of the client
2.Set an timer for some time successfully
3.Modify the system time of the client
4.The timer can not start
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
HI @wjd19900102, could you elaborate on what is the client time you have before your timer test and the time you change to after?  And is there any particular reason why you would want to modify the system time of the client?

**Comment by dhpp** [comment]
Closing.  Please re-open or create a new ticket if you'd like to explore further.
