### ISSUE TITLE
respeaker core v2.0 error while get Authorization of AVS on Respeaker v 2.0

### ISSUE THREAD

**Issue by ParkChur** [alexa/avs-device-sdk#1344]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [V ] Other - tell us more: Respeaker v2.0

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ V] Other - tell us more: debian

I follow this site : http://wiki.seeedstudio.com/ReSpeaker_Core_v2.0/
and I faced a problem while doing 3.2 Get Authorization of AVS
Am I wrong client id, product id or clientsecret?
Help me plz!

The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

Serving Flask app "AuthServer" (lazy loading)
Environment: production
WARNING: Do not use the development server in a production environment.
Use a production WSGI server instead.
Debug mode: off
Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
and I saw this page when i open this link : http://127.0.0.1:3000/

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
scope=alexa%3Aall
redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthresponse
response_type=code
client_id=amzn1.application-oa2-client.48818436388a487f889497b6ada241e5
scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22AIspeaker%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22123456%22%7D%7D%7D

**Comment by ParkChur** [comment]
version is 1.6.0

**Comment by kjkh** [comment]
Hi @ParkChur,

The instructions that ReSpeakerCore wiki links for generating a security profile, https://github.com/alexa/avs-device-sdk/wiki/Create-Security-Profile, uses the newer CBL method of authentication. SDK v1.6 does not use it, and instead uses the old python server method. This implementation is deprecated and incompatible; using it is not advised.

If you wish to use the 1.6 version of authentication, please goto your Security Profile page and copy the Client Secret and Client ID under the **Web** (not Other devices and platforms as per the above link). These are what is compatible with the older mechanism. As well, please ensure that you enter the following URLs in the Web tab: 

"Allowed origins"

http://localhost:3000
https://localhost:3000

"Allowed return URLs":

https://localhost:3000/authresponse
http://localhost:3000/authresponse

I would advise reaching out to seeedstudio and seeing if they are interested in updating to a version of the SDK supporting CBL (v1.7+).

**Comment by ParkChur** [comment]
Could you tell me How to update sdk??

**Comment by kameshkancherla** [comment]
Have you added the below in product profile.
http://localhost:3000
https://localhost:3000

"Allowed return URLs":

https://localhost:3000/authresponse
http://localhost:3000/authresponse

Adjust the time zone on respeaker core and they try.

**Comment by ParkChur** [comment]
thank you kameshkancherla 
but I have already done them.

**Comment by ParkChur** [comment]
Thank you!! 
It works because of your advice.

But I faced new problems.
Run SampleApp and call Alexa
It does not react.
Do not talk to the speaker after thinking if you ask by pressing t.
(It worked well in the demo.)

**Comment by kameshkancherla** [comment]
Then kill this first and run.

Pulse audio  - - kill

Run sampleapp

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ParkChur** [comment]
Where should you do it?
I'm sorry to bother you with the details ...!

**Comment by kameshkancherla** [comment]
np.

I think you are running debian.

from debian cli - pulseaudio --kill, then start the sampleapp.

Regards
vithal

________________________________

**Comment by ParkChur** [comment]
Thanks a lot!

It works when t + enter is entered.
Alexa or Snowboy does not respond when you call.
And do you know where the source files are for the question I'm talking about?
Can you help me a little more?

**Comment by kameshkancherla** [comment]
Send the out put once

Regards
Vithal

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ParkChur** [comment]
Thank you always for your reply.

When I run SampleApp, I do not answer Alexa or Snowboy.
How should this be addressed?
Running it with the opensources solution is the same.

**Comment by kameshkancherla** [comment]
Send me the snip of ur screen or output

Regards
Vithal

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dhpp** [comment]
Hi @ParkChur - did you install the SDK via our setup script / steps as described [here](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script#setup)?  That allows you to install kitt.ai / snowboy.

**Comment by ParkChur** [comment]
to  kameshkancherla

Thank you all the time.

when i run SampleApp : 

respeaker@v2:~/respeaker_v2_eval$ ~/sdk-folder/sdk-build/SampleApp/src/SampleApp ~/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json
2019-05-26 04:31:23.805 [  1] I sdkVersion: 1.6.0
#############################
#       Connecting...       #
#############################

2019-05-26 04:31:25.601 [  2] I UIManager:DBusSignal:signalName=connecting
########################################
#       Alexa is currently idle!       #
########################################

2019-05-26 04:31:27.330 [  2] I UIManager:DBusSignal:signalName=ready
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.6.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.
|
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Echo Spatial Perception (ESP): This is for testing purpose only!           |
|       Press 'e' followed by Enter at any time to adjust ESP settings.      |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       register your device with another account.                           |
|       This will kill the application since we don't support login yet.     |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

t




-----------------------------

when i run open sourcesoulution

respeaker@v2:~/respeaker_v2_eval$ python ns_kws_alexa_with_light.py 
['arecord', '-t', 'raw', '-f', 'S16_LE', '-c', '1', '-r', '16000', '-D', 'default', '-q']
DEBUG:hyper.http20.connection:Selected NPN protocol: h2
DEBUG:hyper.http20.connection:recv for stream 0 with set([]) already present
INFO:hyper.http20.connection:Received unhandled event <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=2147483647), ChangedSetting(setting=SettingCodes._max_header_list_size, original_value=None, new_value=40960)}>
INFO:hyper.http20.connection:Received unhandled event <WindowUpdated stream_id:0, delta:2147418112>
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0xb1672cb0>
DEBUG:hpack.hpack:Adding (':method', 'GET') to the header table
DEBUG:hpack.hpack:Encoding 2 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'avs-alexa-na.amazon.com') to the header table
DEBUG:hpack.hpack:Encoding 1 with 6 bits
DEBUG:hpack.hpack:Encoding 17 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/v20160207/directives') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 15 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer Atza|IwEBIBy6D-Yep9uTkPxfBOBbpRwcsxgsHEacPpD4Z8_aJHwutqHFNRvt9KENgkouCR6Sp5cuSLMs4beuTxsN3WLFJ4_816Fhzru5U-OzyzAcpsP2upTk4LFOQutPVdjMqRr6jNg8aQcLBxCyQzOi2gF_3K3KGEuWvVin4aeq90Ym3yuHrUfGE3E32nO-qQ9TebXI1MYjj6J7dd32f77tYYoJhy14nc-PMULq678gMiT5LyAydNvDTxLEX7lI48ILaJOm_MLTEOE1KzHc4lY3ipctTjveN30gWQmQid1zXGxkvZLTszbVStLaXQ--CLq-K7iOI4SOaUkzKPR9RrdRt9ihedtfpto2O0b7excx7o26mkqQPATPkSrtYxTCTl6nCb8dG3d1I1j9bHgCluDYfnLiQkJ3qDHoeU8B26jvfZ-DBwgDRGxu2PFaPKn2nkF-Gon5X3dM6yz5eYS7N_2IjOMRMYtiZXmb-e4PvOf6O4NR8t6ixEHeAox42I-du4m-Gx146oifD3eCGb7-zRmqTopiZI0M') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 439 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ��A�t,:
                                                 �kT5�H����zD�c�� :Ć��I����Q�[�>��2x�w%�N_[�k~��u����dc�2k��_�D<��Z������/���n����7V�-ݟB▒�����,�χ+Q<0���[ද~��JѬV�Y���ju�ls����g������▒Sa����ł�]����^σ�,���%Ł�
                        ��Kv������:9���Wd��J�����g��"��p���^�A����>�����9�~;FF�ɜyuS���j�����9�jȝ�;�K ���v▒@���������>;���Z�~�ftڲ5�P�u��^���&Ծi�"e�'�F�|�˧����\;���by��{}Uz7����ǎk�[��g6ιY�����s�yV�w�����h����
��V�z��fMz��y�wLB��V��9��ƱZ��T�jkNג����XO��dZKZ�l^BӇ4��-�Q������z���▒?
DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}>
INFO:hyper.http20.connection:Received unhandled event <SettingsAcknowledged changed_settings:{}>
DEBUG:hyper.http20.connection:recv for stream 1 with set([]) already present
DEBUG:hpack.hpack:Decoding �T*@�����R���BM'�&Z�YJ!�6�X�Q,4(�z%��H�mR�P,��,��$��Q>�,��bX��
                        A�ǩ��=_
DEBUG:hpack.hpack:Decoded 8, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', '200'), consumed 1
DEBUG:hpack.hpack:Decoded 20, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 1, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('access-control-allow-origin', <memory at 0xb47c4490>), total consumed 3 bytes, indexed True
DEBUG:hpack.hpack:Decoded 12, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 44, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-amzn-requestid', '12a234fffe2ada48-00006ff2-0042b68b-9787bb1fc487eac3-37f269f1-1'), total consumed 59 bytes, indexed True
DEBUG:hpack.hpack:Decoded 31, consumed 1 bytes
DEBUG:hpack.hpack:Decoded 47, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('content-type', 'multipart/related; boundary=------abcde123; type=application/json'), total consumed 49 bytes, indexed True
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:1, weight:16, depe
nds_on:0, exclusive:False>
DEBUG:hpack.hpack:HPACK encoding <generator object inner at 0xb1694170>
DEBUG:hpack.hpack:Adding (':method', 'POST') to the header table
DEBUG:hpack.hpack:Encoding 3 with 7 bits
DEBUG:hpack.hpack:Adding (':scheme', 'https') to the header table
DEBUG:hpack.hpack:Encoding 7 with 7 bits
DEBUG:hpack.hpack:Adding (':authority', 'avs-alexa-na.amazon.com') to the header table
DEBUG:hpack.hpack:Encoding 63 with 7 bits
DEBUG:hpack.hpack:Adding (':path', '/v20160207/events') to the header table
DEBUG:hpack.hpack:Encoding 4 with 6 bits
DEBUG:hpack.hpack:Encoding 12 with 7 bits
DEBUG:hpack.hpack:Adding ('content-type', 'multipart/form-data; boundary=seeed-voice-engine') to the header table
DEBUG:hpack.hpack:Encoding 31 with 6 bits
DEBUG:hpack.hpack:Encoding 34 with 7 bits
DEBUG:hpack.hpack:Adding ('authorization', 'Bearer Atza|IwEBIBy6D-Yep9uTkPxfBOBbpRwcsxgsHEacPpD4Z8_aJHwutqHFNRvt9KENgkouCR6Sp5cuSLMs4beuTxsN3WLFJ4_816Fhzru5U-OzyzAcpsP2upTk4LFOQutPVdjMqRr6jNg8aQcLBxCyQzOi2gF_3K3KGEuWvVin4aeq90Ym3yuHrUfGE3E32nO-qQ9TebXI1MYjj6J7dd32f77tYYoJhy14nc-PMULq678gMiT5LyAydNvDTxLEX7lI48ILaJOm_MLTEOE1KzHc4lY3ipctTjveN30gWQmQid1zXGxkvZLTszbVStLaXQ--CLq-K7iOI4SOaUkzKPR9RrdRt9ihedtfpto2O0b7excx7o26mkqQPATPkSrtYxTCTl6nCb8dG3d1I1j9bHgCluDYfnLiQkJ3qDHoeU8B26jvfZ-DBwgDRGxu2PFaPKn2nkF-Gon5X3dM6yz5eYS7N_2IjOMRMYtiZXmb-e4PvOf6O4NR8t6ixEHeAox42I-du4m-Gx146oifD3eCGb7-zRmqTopiZI0M') to the header table
DEBUG:hpack.hpack:Encoding 23 with 4 bits
DEBUG:hpack.hpack:Encoding 439 with 7 bits
DEBUG:hpack.hpack:Encoded header block to ���D�c�� :�{���_���j�bX��R��H�Ԍ�� ��
Rȷs��X�Lj���Q�[�>��2x�w%�N_[�k~��u����dc�2k��_�D<��Z������/���n����7V�-ݟB▒�����,�χ+Q<0���[ද~��JѬV�Y���ju�ls����g������▒Sa����ł�]����^σ�,���%Ł�
                      ��Kv������:9���Wd��J�����g��"��p���^�A����>�����9�~;FF�ɜyuS���j�����9�jȝ�;�K ���v▒@���������>;���Z�~�ftڲ5�P�u��^���&Ծi�"e�'�F�|�˧����\;���by��{}Uz7����ǎk�[��g6ιY�����s�yV�w�����h����
��V�z��fMz��y�wLB��V��9��ƱZ��T�jkNג����XO��dZKZ�l^BӇ4��-�Q������z���▒?
INFO:avs.alexa:wait for response
DEBUG:hyper.http20.connection:recv for stream 3 with set([1]) already present
DEBUG:hpack.hpack:Decoding ���&Z�YJ!�6�X�Q,4(�z5�u�c�2���(��(�~P��
DEBUG:hpack.hpack:Decoded 9, consumed 1 bytes
DEBUG:hpack.hpack:Decoded (':status', '204'), consumed 1
DEBUG:hpack.hpack:Decoded 64, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('access-control-allow-origin', <memory at 0xb47c4490>), consumed 1
DEBUG:hpack.hpack:Decoded 63, consumed 2 bytes
DEBUG:hpack.hpack:Decoded 44, consumed 1 bytes
DEBUG:hpack.hpack:Decoded ('x-amzn-requestid', '12a234fffe2ada48-00006ff2-0042b68b-9787bb1fc487eac3-37f269f1-3'), total consumed 47 bytes, indexed True
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:3, weight:16, depends_on:0, exclusive:False>
INFO:avs.alexa:status code: 204
INFO:avs.alexa:on_ready

**Comment by ParkChur** [comment]
to dhpp

Thanks a lot but I think it didn't work on my OS

respeaker@v2:~$ sudo bash setup.sh config.json -s 998987
[sudo] password for respeaker: 
The installation script doesn't support current system. (System: Linux v2 4.4.138-respeaker-r0 #2 SMP Wed Jul 25 11:29:18 CST 2018 armv7l GNU/Linux)
respeaker@v2:~$ sudo bash setup.sh config.json -s 123456
The installation script doesn't support current system. (System: Linux v2 4.4.138-respeaker-r0 #2 SMP Wed Jul 25 11:29:18 CST 2018 armv7l GNU/Linux)

**Comment by ParkChur** [comment]
respeaker@v2:$ sudo bash setup.sh config.json -s 998987
[sudo] password for respeaker:
The installation script doesn't support current system. 

- [ ] 

- [ ] (System: Linux v2 4.4.138-respeaker-r0 #2 SMP Wed Jul 25 11:29:18 CST 2018 armv7l GNU/Linux)

respeaker@v2:$ sudo bash setup.sh config.json -s 123456
The installation script doesn't support current system. (System: Linux v2 4.4.138-respeaker-r0 #2 SMP Wed Jul 25 11:29:18 CST 2018 armv7l GNU/Linux)

**Comment by kameshkancherla** [comment]
What kind of hardware and os ur using.

Regards
Vithal

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ParkChur** [comment]
Too thankful to kameshkancherla

I solved the problems.
It seems that there was a conflict in the process of installing snowboy.
After reinstalling the OS, installing snowboy solved all the problems.
Thank you so much for your help so far!!
