### ISSUE TITLE
Tx-Rx speech abnormal 

### ISSUE THREAD

**Issue by kirankadam06** [alexa/avs-device-sdk#1345]
[Files.zip](https://github.com/alexa/avs-device-sdk/files/3150785/Files.zip)

(**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am using avs sdk for android platform.in real time everything works perfect like alexa responds to each query properly. our hardware consisting of  Qualcomm SDM450 chipset.
so basically we are fine tuning audio in our device. we came across speech speed abnormalities (query-response).from QXDM (qcom debug) tool we took isf file logs for audio and converted them to wav file using QCAT tool .when we play this wav we get speech rate abnormality what we ask to alexa and alexa response both. if tested without alexa ,with normal sound recorder app then logs are fine no issues .

## What is the expected behavior?
wav file must record normal speech rate as like real-time mode only.

## What behavior are you observing?
QXDM-QCAT wav file records Tx-Rx speech abnormal. attaching .wav file for same.

## Provide the steps to reproduce the issue, if applicable:
1.connect device to QXDM (check with QPST)
2.filter logs based on log packets for audio (select all).
3.ask alexa queries 3-4 of different kinds.
4.stop QXDM connection
5.save .isf file
6.import isf file to QCAT 
7.from view->vocoder playback ----convert to wav file (steps provided to qcat user guide )
8.listen to that wav file (check file ending with Tx)

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
custom hardware DVR8010 

### Tell us about your OS (Type & version):
android pie 9.0
)

**Comment by kjkh** [comment]
Hi @kirankadam06,

Unfortunately, this is beyond the scope of the SDK. You can attempt to dump the audio buffers going into and out of the SDK by modifying the code, and seeing if those wav files are replayed normally. Conversely, if there is business urgency to this matter, you can contact us directly by filling out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).

**Comment by aumatsui** [comment]
Hi @kirankadam06,

I am closing this issue now. Please feel free to reopen it if you need further assistance.

Thanks,
