### ISSUE TITLE
Bluetooth: Frequent BT Audio underrun every 60 seconds

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#1349]
Hello AVS Team,

When Alexa plays song using BT,  the audio underruns for 1 sec after every 60 seconds.
Can you please let me know What will be the root cause of this issue?

avs-device-sdk - 1.12.1
pulseaudio - 12.2
BlueZ - 5.42

**Comment by aumatsui** [comment]
Hi sumit3817,

Can you provide the DEBUG9 logs related to the issue so we can take a closer look at this problem?

Thank you,

**Comment by sumit3817** [comment]
[bt_underrun.log](https://github.com/alexa/avs-device-sdk/files/3177119/bt_underrun.log)

Hi,
PFA the DEBUG9 logs for bt underrun for 1 sec issue reproduced.

Thanks,
Sumit

**Comment by sumit3817** [comment]
Some of my observations from these logs, I am able to see these logs when there is a glitch:-

**2019-05-14 11:22:17.104 [ 18] 9 MediaPlayer:State Change:oldState=PLAYING,newState=PAUSED,pendingState=VOID_PENDING
2019-05-14 11:22:17.104 [ 18] 0 MediaPlayer:callingOnBufferUnderrun:currentId=1
2019-05-14 11:22:17.104 [ 18] 9 MediaPlayer:messageReceived:type=buffering,source=decodedQueue
2019-05-14 11:22:17.105 [ 18] 9 MediaPlayer:handleBusMessage:message=GST_MESSAGE_BUFFERING,percent=9**

**Comment by aumatsui** [comment]
Hi Sumit,

We are trying to reproduce the issue. Can you confirm that the perceived user experience is a pause of 1 second in the audio every 60 seconds?

Thank you

**Comment by aumatsui** [comment]
Your attached logs show an initial 1s delay, which is perhaps not related to the periodic 60 seconds underrun you experience. Can you provide more complete logs showing the periodic issue that you see?

We just tried to reproduce the issue and could not see it happening. What else can you share about your platform? What is your Linux distribution, for instance?

**Comment by sumit3817** [comment]
Hi,

Yes the perceived user experience is a pause of 1 second in the audio. But the period is not fixed.
Sometime it is 60 seconds and other time, it is 75 seconds. But this cycle is repeating in continous playback.

While debugging, I found, when the GST_MESSAGE_BUFFERING,percent=9, this issue comes.
I think the issue is with the buffer size. The buffer is being empty after 60-75 seconds everytime.

**Comment by sumit3817** [comment]
[bt_underrun_continous.log.tar.gz](https://github.com/alexa/avs-device-sdk/files/3190538/bt_underrun_continous.log.tar.gz)
Hi,
I have attached the complete continuous logs which have this issue 4 times in a row.
I have attached the tar file as the file size is greater than 10 MB.

**First time - 
2019-05-17 07:45:43.274 [ 17] 9 MediaPlayer:State Change:oldState=PAUSED,newState=PLAYING,pendingState=VOID_PENDING**

**Second Time -
2019-05-17 07:46:57.082 [ 17] 9 MediaPlayer:State Change:oldState=PAUSED,newState=PLAYING,pendingState=VOID_PENDING**

**Third Time -
2019-05-17 07:48:03.553 [ 17] 9 MediaPlayer:State Change:oldState=PAUSED,newState=PLAYING,pendingState=VOID_PENDING**

**Fourth Time -
2019-05-17 07:49:19.024 [ 17] 9 MediaPlayer:State Change:oldState=PAUSED,newState=PLAYING,pendingState=VOID_PENDING**

**Linux Machine Details:-
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial**

**uname -a
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Thu May 16 15:50:08 IST 2019 armv7l armv7l armv7l GNU/Linux**

PulseAudio - 12.2
BlueZ - 5.42

Please let me know if any more details needed.

**Comment by aumatsui** [comment]
Thank you for the additional information Sumit. We are investigating.

**Comment by sumit3817** [comment]
Hi,

Is there any update on this issue ?

**Comment by mvelegon-amzn** [comment]
Hi @sumit3817 Thanks for reaching out. We are still investigating this issue internally. Will update you once we have more information.

**Comment by kjkh** [comment]
Issue was resolved through another communication in another medium. Please re-open if there are any further questions.
