### ISSUE TITLE
Getting MEDIA_ERROR_INTERNAL_DEVICE_ERROR when playing songs from saavn.

### ISSUE THREAD

**Issue by sujisasken** [alexa/avs-device-sdk#1356]
Hi Amazon team,

preconditions:
we are using AVS SDK :1.12. with pause and resume behavior of Music (which is default sdk behavior).  

Steps to reproduce the issue.
1.Alexa+play songs from saavn.
2.when it is playing say Alexa+ play next song.
3.Now Alexa plays next song.
4.Now say Alexa+pause.
5.Now say Alexa+resume.

we will get this error "MEDIA_ERROR_INTERNAL_DEVICE_ERROR" and plays next song.

we kept GST_DEBUG=4
and collected logs

in that logs we found that snippet:

AudioPlayer:onPlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=GStreamer encountered a general stream error.,id=4
2019-05-17 05:30:15.911 [ 13] E AudioPlayer:executeOnPlaybackError:id=4,type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=GStreamer encountered a general stream error.

please find the attached logs with Gstreamer enabled .

Thanks
Sujith
[17.txt](https://github.com/alexa/avs-device-sdk/files/3190004/17.txt)

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sujisasken** [comment]
Attaching gstreamer logs.
[gstreamer_logs.txt](https://github.com/alexa/avs-device-sdk/files/3190072/gstreamer_logs.txt)

**Comment by sujisasken** [comment]
Hi Amazon Team,
Any update on this please.

Thanks
Sujith

**Comment by dhpp** [comment]
Hi @sujisasken, could you please provide DEBUG9 logs of the entire user interaction?  That will really help us get more context on the Directives received by the client, and how the SDK behaved.  Thanks.

**Comment by sujisasken** [comment]
Hi dhpp,

The above attached "17.txt" file is the debug9 logs.

After getting the error ,SDK played the next song .

Thanks
Sujith

**Comment by sujisasken** [comment]
Hi dhpp,

Please find the attached DEBUG9 logs.

[DEBUG9_logs.txt](https://github.com/alexa/avs-device-sdk/files/3221845/DEBUG9_logs.txt)

**Comment by kclchan** [comment]
Hi @sujisasken, sorry for getting back so late.  Could you try this again in v1.13 and see if it's still reproducible?  We have also added more logs and this will help with debugging the issue further.  Thanks!
