### ISSUE TITLE
AVS_functionnal_self_test_v2.1 Issues(#251) FR region

### ISSUE THREAD

**Issue by Baylibrejmonnet** [alexa/avs-device-sdk#1361]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The utterance **1. Quel est le volume?**
in test #251 don't work.
Alexa respond with the definition of VOLUME. 

## What is the expected behavior?
Alexa should give the volume level .

## What behavior are you observing?
Alexa respond with the definition of VOLUME. and not with the volume level 

## Provide the steps to reproduce the issue, if applicable:
SET the device with FR REGION and says:
Alexa, quel est le volume?

## Tell us about your environment:
I tried this issues with my prototype,aslo with ECHO DOT 3rd Gen and Harman Kardon Allure portable

and i have the same issues .

### What version of the AVS Device SDK are you using?
      last update on ECHOT DOT and HK allure

**Comment by dhpp** [comment]
Thanks @Baylibrejmonnet.  What you're describing is an issue on the cloud-side, so I've created a ticket internally for them to investigate.  Thank you for bringing this to our attention.  I'll close out this ticket in the meantime, since there is no SDK work for us to track here.
