### ISSUE TITLE
send voice physical Alexa Echo device via third party application 

### ISSUE THREAD

**Issue by mduzgun** [alexa/avs-device-sdk#1362]
How to send voice to my Alexa Echo device remotely ? For example, I want to record voice in office and send to Alexa Echo device in home. Is there any way?

**Comment by dhpp** [comment]
Hi @mduzgun, this is not something we officially support within the SDK, since our reference implementation requires the microphone to be on the device.  I would suggest you investigate streaming audio solutions to address your question.
