### ISSUE TITLE
 Is it possible to know the source and the variable where the user's statement is stored via avs?

### ISSUE THREAD

**Issue by ParkChur** [alexa/avs-device-sdk#1367]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [v ] Other - tell us more: respeaker core v2

### Tell us about your OS (Type & version):
- [v ] Linux debian
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

I searched avs source files speech_recognizer.py and speech_synthesizer.py, but I could not find a variable to store the user's statement.
Is it possible to know the source and the variable where the user's statement is stored via avs?
Can the variable or statement be printed on the terminal?

help me plz!

**Comment by mvelegon-amzn** [comment]
Hi @ParkChur could you give more information on what you mean by "user's statement"? Do you mean the audio input from the user's utterance? 

The user's utterance is streamed to the AVS cloud in the form of an event where it is interpreted and a directive is sent to the device to perform an action. More information of this can be found here: https://developer.amazon.com/docs/alexa-voice-service/interaction-model.html

For how audio is streamed from the mic to AVS please read the readme section here: https://github.com/alexa/avs-device-sdk 

Also, could you point me to the AVS source files (speech_recognizer.py and speech_synthesizer.py) you are referring to here?

**Comment by ParkChur** [comment]
Thank you for your attention.
Write down my final goal for seamless help.
My ultimate goal is to control ODROID-C2 (similar to RaspberryPi) with AVS (used as Respeaker).
For this I thought of two ways.
1.Respeaker sends user's command recognized through AVS to C2 via UART
2. How to control Respeaker and C2 through Amazon Web Service.
-----
The method we are looking for is one-way, looking for a variable to store the user's command data, but could not find it.
I zipped up the files you mentioned (speech_recognizer.py and speech_synthesizer.py).
[Desktop.zip](https://github.com/alexa/avs-device-sdk/files/3232377/Desktop.zip)

**Comment by mvelegon-amzn** [comment]
Hi @ParkChur Thanks for reaching out. 

I am not sure what you are asking for here. We own the AVS C++ SDK and we can help you with issues related to it. We do not own the speech_recognizer.py and speech_synthesizer.py files you mentioned and we would not be able to help you with those. Please let us know if you have any questions about the C++ SDK.
