### ISSUE TITLE
announcement feature

### ISSUE THREAD

**Issue by mduzgun** [alexa/avs-device-sdk#1369]
Hi, I don't use Announcement feature in AVS. I take response that "Sorry, You can't send announcements from this device yet. ". How to use Announcement feature?

**Comment by leino11121** [comment]
the same for my device.

**Comment by mvelegon-amzn** [comment]
Hi @mduzgun and @leino11121  Thanks for reaching out. The Announcement feature is not enabled out of the box while running the AVS C++ SDK. Currently, the feature is only supported on 1P devices and 3P devices which undergo a certification process.

Additionally, if you would like to get your AVS devices certified, please reach out to your Amazon Alexa solution partner to undergo the certification process.

Hope that helps!

Closing the issue, feel free to reopen if you have further questions.

**Comment by leino11121** [comment]
Hi @mvelegon-amzn ,

My device has pass the certification, but it still doesn't work. 

response like this: "Sorry, You can't send announcements from this device yet"

Thanks.
