### ISSUE TITLE
Can i use clion IDE run this avs-device-sdk?

### ISSUE THREAD

**Issue by RongjieChen** [alexa/avs-device-sdk#137]
i want to use clion IDE to run this avs-device-sdk，please tell me how can i do this?

**Comment by scotthea-amazon** [comment]
Hello RongjieChen,

Yes, you can use CLion to build the avs-device-sdk.  However, there are a few things you will need to do:

1.  Open CLion.  Select 'Import Project from Sources'.  Select the avs-device-sdk folder.  Make sure to NOT select "delete cmakelists.txt".  CLion will import and cmake will fail, that's ok.
2. avs-device-sdk protects itself from cmake's output being set to a directory within the source tree.  That is CLion's default behavior, so you need to specify a directory outside of the source tree.  You can do this by navigating CLion's menus: 'Preferences' | 'Build, Execution, Deployment' | 'CMake' | 'Generation Path', and specifying a path outside the avs-device-sdk source tree.
3. Again, under 'Preferences' | 'Build, Execution, Deployment' | 'CMake', add the cmake command line options you want to 'CMake options'.  These will typically include:
- -DGSTREAMER_MEDIA_PLAYER=ON
- -DCMAKE_BUILD_TYPE=DEBUG
If you want to include PortAudio, you will also want to specify:
- -DPORTAUDIO=ON
- -DPORTAUDIO_LIB_PATH=<path-to-portaudio-lib>
- -DPORTAUDIO_INCLUDE_DIR=<path-to-portaudio-include-dir>
4. If you want to run one of the executable projects (e.g. Sample App) from inside CLion, go to 'Edit Configurations' and select the project.  Then:
- Add TZ=UTC to 'Environment Variables'
- Add any required command line parameters to 'Program arguments'.  Typically this includes at least the path to your configuration file (i.e. AlexaClientSDKConfig.json).

I hope this helps,
-SWH

**Comment by RongjieChen** [comment]
@scotthea-amazon thx，this useful.
