### ISSUE TITLE
announcement feature doesn't work on 3rd Part devices.

### ISSUE THREAD

**Issue by leino11121** [alexa/avs-device-sdk#1370]
Dear,

As mentioned in #1369, announcement feature should work on 3p devices. 

But my device has pass the certification, but it still doesn't work.
response like this: "Sorry, You can't send announcements from this device yet"

Thanks.

**Comment by mvelegon-amzn** [comment]
Hi @leino11121 Thanks for reaching out. Since announcements was recently added to the certification process, it looks like you will have to resubmit for certification. Hope this helps.

**Comment by leino11121** [comment]
Thanks @mvelegon-amzn
