### ISSUE TITLE
ExternalMedia request token traffic flooding issue

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#1371]
Hi AVS team,

SDK 1.12 (or SDK1.11).  ARM based embedded linux.

Amazon team reported that there are ExternalMediaPlay.RequestToken events flooding from our devices worldwide. (all devices use same product id)
After check the log and source code, we believe it's from Spotify adapter in AVS SDK.

We tried to reproduce this case and found in this settings, we can see the event : 
- No Spotify account link in Amazon Alexa account. (or different spotify account from Spotify APP)
-  Plays spotify music from Spotify APP to AVS enabled speaker (i.e. our device) .

In this case, we can see the event will be sent 3 times in a minute.
We don't know if it's correct behavior, but thousands of our device (same product id) sent this event to Amazon server seems cause some troubles in server side.

Could you have some suggestion ?

attached is the DEBUG9 log. 

[teraterm5.log](https://github.com/alexa/avs-device-sdk/files/3241308/teraterm5.log)

**Comment by mvelegon-amzn** [comment]
Hi @zeusshuang thank you for reaching out. We have identified a fix for it and it was released in the latest spotify adapter release. Please work with your Alexa solution partner to get the latest version. Thanks.
