### ISSUE TITLE
Compile error using Amlogic Openlinux on A113X1 platform

### ISSUE THREAD

**Issue by joey1115** [alexa/avs-device-sdk#1376]
## Fail when building a package called "glib-networking":

I followed the instructions provided by Amlogic to build avs-sdk.
[http://openlinux2.amlogic.com/download/doc/A113X1_Usermanual.pdf](url)

To choose the compile configuration I used this command and slected "mesonaxg_s420_release"
`source ./buildroot/build/setenv.sh`

Then I used the following command to build the SDK
`make avs-sdk`

Then the program starts to download and build the prerequisite packages like "curl".
When it tries to build the package called "glib-networking", it failed and the command line outpus is attached below.

## What behavior are you observing?

umask 0022 && make -C /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/buildroot O=/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release glib-networking-rebuild
package/assistant-sdk/assistant-sdk.mk:18: " assistant_sdk file no exist"
rm -f /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_staging_installed
rm -f /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_target_installed
rm -f /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_images_installed
rm -f /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_host_installed
rm -f /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_built

glib-networking 2.50.0 Building
CC="/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/bin/aarch64-linux-gnu-gcc" CFLAGS="" PATH="/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/bin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/sbin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/bin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/sbin:/home/wang/bin:/home/wang/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" /usr/bin/make -j9 -C /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0
/usr/bin/make  all-recursive
Making all in po
make[4]: Nothing to be done for 'all'.
Making all in proxy/tests
/usr/bin/make  all-am
make[5]: Nothing to be done for 'all-am'.

glib-networking 2.50.0 Installing to staging directory

glib-networking 2.50.0 Fixing libtool files

glib-networking 2.50.0 Installing to target

#CC="/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/bin/aarch64-linux-gnu-gcc" CFLAGS="" PATH="/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/bin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/sbin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/bin:/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/host/usr/sbin:/home/wang/bin:/home/wang/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" /usr/bin/make -j9  install -C /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0
mkdir -p /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/target/usr/lib/gio/modules
cp /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/tls/gnutls/.libs/libgiognutls.so /home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/target/usr/lib/gio/modules
cp: cannot stat '/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/tls/gnutls/.libs/libgiognutls.so': No such file or directory
package/pkg-generic.mk:297: recipe for target '/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_target_installed' failed
make[1]: *** [/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/build/glib-networking-2.50.0/.stamp_target_installed] Error 1
/home/wang/Desktop/A113/openlinux/OpenLinux_20180907/output/mesonaxg_s420_release/Makefile:16: recipe for target '_all' failed
make: *** [_all] Error 2

## Provide the steps to reproduce the issue, if applicable:
Download and extract source code from 
[http://openlinux.amlogic.com:8000/download/ARM/filesystem/Linux_BSP/buildroot_openlinux_kernel_4.9_20180131.tar.gz](url)
or
[http://openlinux.amlogic.com:8000/download/ARM/filesystem/Linux_BSP/buildroot_openlinux_kernel_4.9_20180907.tar.gz](url)

Use the command:
`source ./buildroot/build/setenv.sh`
And select mesonaxg_s420_release

Build avs-sdk
`make avs-sdk`

Errors will show up when building the package called "glib-networking".

### What version of the AVS Device SDK are you using?
Souce code are compiled on Ubuntu 16.04

Target OS:
Amlogic Openlinux 20180131
Amlogic Openlinux 20180007
avs-sdk version: <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*] Other - tell us more:
A113X1 Dev Kit

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Souce code are compiled on Ubuntu 16.04

Target OS:
Amlogic Openlinux 20180131
Amlogic Openlinux 20180007

**Comment by womw** [comment]
@joey1115 Hey thanks for posting.

It appears that you are using out sdk on a hardware platform and OS that we do not support and a distribution of our sdk not from our github repo.

The dependency that is causing your error glib-networking is not one of the dependencies listed in our required dependencies page and as such we do not support its use with the sdk.

I advise that you bring this issue up with the board manufacturer you are using.
