### ISSUE TITLE
ADB mkdir permission denied

### ISSUE THREAD

**Issue by ajinkyaw** [alexa/avs-device-sdk#1377]
## Briefly summarize your issue:
I am trying to run AVS on an Android Device. Compiling and building it on UBUNTU Terminal while connecting the device using ADB.

## What behavior are you observing?
this is the snippet of last few lines i am sharing from terminal

+ printInfo 'Wait until device is online. Please make sure the device is ' connected.
+ echo ================================================================================
================================================================================
+ local ARGUMENT
+ for ARGUMENT in "$@"
+ echo '= Wait until device is online. Please make sure the device is '
= Wait until device is online. Please make sure the device is 
+ for ARGUMENT in "$@"
+ echo '= connected.'
= connected.
+ adb wait-for-device
+ printInfo 'Make sure device intall target exists and has write permission'
+ echo ================================================================================
================================================================================
+ local ARGUMENT
+ for ARGUMENT in "$@"
+ echo '= Make sure device intall target exists and has write permission'
= Make sure device intall target exists and has write permission
+ adb shell mkdir -p /system/repavs
+ adb shell mkdir -p /system/repavs/bin
mkdir: '/system/repavs/bin': Permission denied

## Provide the steps to reproduce the issue, if applicable:
while i am using command.
sudo bash -x setup.sh config.json -a androidConfig.txt -s 998987

and on another terminal, i am executing these commands before above command
adb connect <ip>
adb shell
xu 7411
mount -o remount,rw /system

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
@ajinkyaw Thanks for posting.

Did you run the command adb root before running adb connect? If so can you try doing that and see if you still have these permissions errors.

**Comment by ajinkyaw** [comment]
@womw  : Hi , i found the issue. its regarding the session of the terminal.
By opening a root access in a terminal will only allow to do root operations in same terminal session, another process or thread wont be able to get the root operation permission.
