### ISSUE TITLE
Build PortAudio to SampleApp error when linking

### ISSUE THREAD

**Issue by phyen808724** [alexa/avs-device-sdk#1380]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We want to build PortAudio to SampleApp but it will linking error.
We add below  in android.sh
-DPORTAUDIO="ON" \
-DPORTAUDIO_LIB_PATH="/home/phyen/work/avs_ori/Libraries/portaudio/lib/.libs/libportaudio.a" \
-DPORTAUDIO_INCLUDE_DIR="/home/phyen/work/avs_ori/Libraries/portaudio/include" \

And copy "libportaudio.a" to path "\Libraries\portaudio\lib\.libs" and "portaudio.h" to path "Libraries\portaudio\include"
==============================================
Build error as below :
[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/SampleEqualizerModeController.cpp.o
[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/main.cpp.o
[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o
[100%] Linking CXX executable SampleApp
/home/phyen/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/phyen/work/avs_ori/Libraries/portaudio/lib/.libs/libportaudio.a(pa_front.o): incompatible target
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:82: error: undefined reference to 'Pa_Initialize'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:92: error: undefined reference to 'Pa_OpenDefaultStream'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:107: error: undefined reference to 'Pa_GetDefaultInputDevice'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:113: error: undefined reference to 'Pa_OpenStream'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:70: error: undefined reference to 'Pa_StopStream'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:71: error: undefined reference to 'Pa_CloseStream'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:72: error: undefined reference to 'Pa_Terminate'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:133: error: undefined reference to 'Pa_StartStream'
/home/phyen/work/avs_ori/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:143: error: undefined reference to 'Pa_StopStream'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [SampleApp/src/SampleApp] Error 1
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [SampleApp] Error 2

### What version of the AVS Device SDK are you using?
      <x.y.z>
1.13
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Android

**Comment by womw** [comment]
Hey @phyen808724 thanks for the post.

Portaudio is currently not supported for the android build of our sdk.

**Comment by phyen808724** [comment]
Hi @womw ,

We want to record the raw stream to a file in avs sdk for debugging some audio issue. What we can do for this?
Thanks for your reply and help.

**Comment by womw** [comment]
Hi @phyen80872 ,

The android buffer uses the AndroidSLESMicrophone instead of portaudio. You can find the raw stream data inside of the AndroidSLESBufferQueue class the the microphone uses.

**Comment by phyen808724** [comment]
Hi @womw ,

Is it possible to store AndroidSLESBufferQueue to a audio file and pull this file from devices?
