### ISSUE TITLE
Indefinitely using the sensory truly hands free service installed in my raspberry pi

### ISSUE THREAD

**Issue by hemantvikram** [alexa/avs-device-sdk#1381]
Hi,
How can I continue using the sensory truly hands free service installed in my raspberry pi (avs-device-sdk) after its expiry?
I'm trying to build a product using raspberry pi with amazon voice service controlling the smart devices and responding to user utterances. I don't want to increase the price of my product by making my user to separately purchase Amazon Echo or other devices. Can you please let me know what are my options?

**Comment by womw** [comment]
Hie @hemantvikram , thanks for posting.

For continued use with sensory you should get in touch with their sales team to find a license that will work for your application.

You can contact their sales team at this [link](https://www.sensory.com/support/contact/us-sales/)
