### ISSUE TITLE
Alexa C++ Software Development IDE

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#139]
Which one IDE tools is suitable for Alxea software development?

**Comment by scotthea-amazon** [comment]
Hello aki29,

We do not have a recommended IDE for building avs-device-sdk.  The [Get Started](https://github.com/alexa/avs-device-sdk#get-started) section of our documentation includes links to quick start guides that explain how to build the SDK from the command line on different platforms.   That said, some developers have used CLion to build the SDK, and a [recent forum thread](https://github.com/alexa/avs-device-sdk/issues/137) includes some hints for making that work.

Thank you,
-SWH

**Comment by aki29** [comment]
thanks for your reply
