### ISSUE TITLE
AuthObserverInterface::State UNINITIALIZED is mis-spelled in operator<<

### ISSUE THREAD

**Issue by bastiansauert** [alexa/avs-device-sdk#1394]
## Briefly summarize your issue:
In file `AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/AuthObserverInterface.h` line `104`, there is a mis-spelling of the output for the AuthObserverInterface::State `UNINITIALIZED`.

## What is the expected behavior?
`return stream << "UNINITIALIZED";` (with `I` between `N` and `T`)

## What behavior are you observing?
`return stream << "UNINTIALIZED";` (without `I` between `N` and `T`)

### What version of the AVS Device SDK are you using?
Version 1.13 commit #9549185687fd963d0069a636807e0aee40023829

**Comment by kjkh** [comment]
Hi @bastiansauert,

Thanks for letting us know. We will fix this in a future release.

**Comment by bastiansauert** [comment]
Hi @kjkh,

thank you.

I just noticed that the same mis-spelling also occurs in file `AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/CapabilitiesObserverInterface.h` line `85`.

**Comment by kclchan** [comment]
Thanks.  We will fix this in a future release of the SDK also.

**Comment by kclchan** [comment]
This has been fixed in v1.14 of the SDK release.  Thanks!
