### ISSUE TITLE
Portaudio and KITT.ai build error

### ISSUE THREAD

**Issue by ShaatLa** [alexa/avs-device-sdk#1398]
## Briefly summarize your issue:
Can't make build with Portaudio integration. Also I have the same problem with KITT.ai.
Without these two addons I can make build without any problem.

## What is the expected behavior?
I would like to add portaudio and kitt.ai support for my build.

## What behavior are you observing?
This is my log during building with Portaudio:

################################################################################
Proceeding with installation
################################################################################
[ 31%] Built target AVSCommon
[ 34%] Built target SQLiteStorage
[ 38%] Built target ACL
[ 40%] Built target ADSL
[ 43%] Built target AFML
[ 45%] Built target RegistrationManager
[ 47%] Built target EqualizerImplementations
[ 47%] Built target ContextManager
[ 47%] Built target CapabilitiesDelegate
[ 50%] Built target PlaylistParser
[ 52%] Built target SpeechEncoder
[ 54%] Built target AudioResources
[ 56%] Built target AudioPlayer
[ 59%] Built target Bluetooth
[ 59%] Built target Equalizer
[ 59%] Built target ExternalMediaPlayer
[ 61%] Built target InteractionModel
[ 63%] Built target Notifications
[ 65%] Built target PlaybackController
[ 65%] Built target SpeakerManager
[ 68%] Built target SpeechSynthesizer
[ 70%] Built target TemplateRuntime
[ 72%] Built target AVSSystem
[ 77%] Built target AndroidUtilities
[ 77%] Built target CBLAuthDelegate
[ 79%] Built target AIP
[ 79%] Built target CertifiedSender
[ 79%] Built target ESP
[ 84%] Built target AndroidSLESMediaPlayer
[ 86%] Built target DeviceSettings
[ 88%] Built target Settings
[ 93%] Built target Alerts
[ 95%] Built target DoNotDisturbCA
[ 95%] Built target DefaultClient
[ 95%] Linking CXX executable SampleApp
/home/shaatla/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/shaatla/ThirdParty/portaudio/lib/.libs/libportaudio.a(pa_front.o): incompatible target
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:82: error: undefined reference to 'Pa_Initialize'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:92: error: undefined reference to 'Pa_OpenDefaultStream'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:107: error: undefined reference to 'Pa_GetDefaultInputDevice'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:113: error: undefined reference to 'Pa_OpenStream'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:70: error: undefined reference to 'Pa_StopStream'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:71: error: undefined reference to 'Pa_CloseStream'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:72: error: undefined reference to 'Pa_Terminate'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:133: error: undefined reference to 'Pa_StartStream'
/home/shaatla/AVS/avs-device-sdk/SampleApp/src/PortAudioMicrophoneWrapper.cpp:143: error: undefined reference to 'Pa_StopStream'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [SampleApp/src/SampleApp] Error 1
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [SampleApp] Error 2

## Provide the steps to reproduce the issue, if applicable:
To reproduce these errors I just can add
	-DPORTAUDIO=ON \
	-DPORTAUDIO_LIB_PATH=${HOME}/ThirdParty/portaudio/lib/.libs/libportaudio.a \
	-DPORTAUDIO_INCLUDE_DIR=${HOME}/ThirdParty/portaudio/include

or

      	-DKITTAI_KEY_WORD_DETECTOR=ON \
      	-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=${HOME}/ThirdParty/snowboy/lib/android/armv7a/libsnowboy-detect.a \
      	-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=${HOME}/ThirdParty/snowboy/include

to my Android.sh CMake parameters.
I also tried to change LIB_PATH for KITT.ai to android/arm8, ubuntu64, aarch64-ubuntu1604 but without success.

## Tell us about your environment:
I use Ubuntu 18.04.2 as build machine and start SampleApp on Device with Anrdoid 9 (ARMv8)
### What version of the AVS Device SDK are you using?
      <1.12.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android 9 on ARMv8

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Ubuntu 18.04.2

**Comment by ShaatLa** [comment]
This is my KITT.ai error:

Scanning dependencies of target KITTAI
[ 74%] Building CXX object KWD/KittAi/src/CMakeFiles/KITTAI.dir/SnowboyWrapper.cpp.o
[ 76%] Building CXX object KWD/KittAi/src/CMakeFiles/KITTAI.dir/KittAiKeyWordDetector.cpp.o
[ 76%] Linking CXX shared library libKITTAI.so
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(wave-audio.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(audio-lib.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(matrix-wrapper.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(vector-wrapper.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(snowboy-debug.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /root/forAVS/snowboy/lib/android/armv8-aarch64/libsnowboy-detect.a(snowboy-detect.o): incompatible target
/root/Android/ndk/ndk-bundle/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lblas
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:40: error: undefined reference to 'snowboy::SnowboyDetect::SnowboyDetect(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:44: error: undefined reference to 'snowboy::SnowboyDetect::RunDetection(short const*, int, bool)'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:48: error: undefined reference to 'snowboy::SnowboyDetect::SetSensitivity(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:52: error: undefined reference to 'snowboy::SnowboyDetect::SetAudioGain(float)'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:56: error: undefined reference to 'snowboy::SnowboyDetect::ApplyFrontend(bool)'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:60: error: undefined reference to 'snowboy::SnowboyDetect::SampleRate() const'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:64: error: undefined reference to 'snowboy::SnowboyDetect::NumChannels() const'
/root/AVS/avs-device-sdk/KWD/KittAi/src/SnowboyWrapper.cpp:68: error: undefined reference to 'snowboy::SnowboyDetect::BitsPerSample() const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [KWD/KittAi/src/libKITTAI.so] Error 1
make[2]: *** [KWD/KittAi/src/CMakeFiles/KITTAI.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object CertifiedSender/src/CMakeFiles/CertifiedSender.dir/SQLiteMessageStorage.cpp.o
[ 79%] Linking CXX shared library libCertifiedSender.so
[ 79%] Built target CertifiedSender
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [SampleApp] Error 2

**Comment by ShaatLa** [comment]
When I manualy change the ANDROID_ABI var in android.sh on "arm64-v8a" I catch these:

[ 32%] Linking CXX shared library libAVSCommon.so
/home/shaatla/AVS/debug/android-23/arm64-v8a/install/lib/libcurl.so: error adding symbols: File in wrong format
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [AVSCommon/libAVSCommon.so] Error 1
make[2]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [SampleApp] Error 2

**Comment by kjkh** [comment]
Hi @ShaatLa,

The SDK has microphone support for Android by utilizing the OpenSL ES APIs. Can I ask the reason behind wanting to integrate with PortAudio?

Regarding the Kitt.ai build failures, what are you setting as the TARGET_SYSTEM?

**Comment by ShaatLa** [comment]
Well, if there is no reason to use Portaudio, I can refuse it.

In Alexa's androidConfig.txt I set "arm".

**Comment by ShiBin1990** [comment]
hava you solve  this problem? i have the same issue, bin/ld: error: cannot find -lblas

**Comment by caleighatamazon** [comment]
Hi there, sorry for our late response on this. Are you still having problems?

**Comment by scotthea-amazon** [comment]
Hello @ShaatLa,

This issue has gone without a response for several weeks now.  I am closing it due to inactivity.  Please feel free to re-open it if I have closed it in error.

Best regards,
-SWH
