### ISSUE TITLE
How to save the response audio to a local file(.mp3) in v0.4 SDK

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#14]
I want to save the response audio to a local file, there is no problem to save before V0.4 alexa-client-sdk, **directive->getAttachmentReader(contentId);** returned a  **std::iostream** type, and we can save the audio using code below:

> `auto attachmentReader = directive->getAttachmentReader(contentId);
 auto status = attachmentReader.wait_for(WAIT_FOR_TIMEOUT_DURATION);
 std::ofstream out("result.mp3");  
 if (out.is_open())   
 {  
       out << attachmentReader.get()->rdbuf();
       out.close();  
} ` 

but in v0.4, the API changes to **directive->getAttachmentReader(contentId, AttachmentReader::Policy::BLOCKING);**, and returns a **AttachmentReader** type, how can I save the video with new APIs?

thanks.

**Comment by smitshilu** [comment]
How can I get mp3 or wav files in SDK 1.8?
