### ISSUE TITLE
AVS SDK Android Issue

### ISSUE THREAD

**Issue by ajinkyaw** [alexa/avs-device-sdk#1401]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am trying to run the AVS Sample app on android , i have compiled the avs sdk and trying to initiate and start the AVS through JNI layer.

## What is the expected behavior?
AVS should initialize.

## What behavior are you observing?
The only log i could manage to see in logcat was :
I/AVS1: config pat aj :/data/data/tv.cloudwalker.cwnxt.launcher/AlexaClientSDKConfig.json
? I/AVS1: at 353 RUnning ap with log level
? I/AVS1: at 360
? I/AVS1: at 371
? I/AVS1: config file loaded
? I/AVS1: at 389 config file loaded
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
? D/AudioTrack: Client defaulted notificationFrames to 1154 for frameCount 2308
? I/AVS1: Failed to create to SampleApplication!

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x ] Other - tell us more: x86 emualtor for android

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hi ajinkyaw,

It is not obvious to me what is going on here.  Can you provide your config file and DEBUG9 level log output in case it provides more info.

Thank you,
-SWH

**Comment by ajinkyaw** [comment]
Hi. @scotthea-amazon  thanks for reaching out.
Today itself i have solved the issue, by putting the logs and verifying.

Thanks.
