### ISSUE TITLE
openssl  

### ISSUE THREAD

**Issue by Lupopa** [alexa/avs-device-sdk#1402]
Hi

## Briefly summarize your issue:

Some packages could not be installed. That may mean that
You have requested an impossible situation if you have the
Unstable distribution still use some required packages
have not yet been created or have not yet left Incoming.
The following information may help you to resolve the situation:

The following packages have unmet dependencies:
libasound2-dev: Depends on: libasound2 (= 1.1.8-1)
libcurl4-openssl-dev: Collided with: libssl1.0-dev but 1.0.2q-2 should be installed
libgstreamer-plugins-bad1.0-dev: Depends on: libopencv-dev (> = 2.3.0) but should not be installed
E: Problems can not be solved, you have retained defective packages.

## What is the expected behavior?

can't install... after typing AGREE....

## What behavior are you observing?

libasound2-dev: Depends on: libasound2 (= 1.1.8-1)
libcurl4-openssl-dev: Collided with: libssl1.0-dev but 1.0.2q-2 should be installed
libgstreamer-plugins-bad1.0-dev: Depends on: libopencv-dev (> = 2.3.0) but should not be installed
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by Vaishnavikumara** [comment]
I am facing the same issue 


The following packages have unmet dependencies:
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed
E: Unable to correct problems, you have held broken packages

**Comment by Lupopa** [comment]
I think, the Problen are the Raspbian (Buster)
and the avs-device-sdk require Raspbian Stretch.
(Sorry for my english, i'm a German user ;-) )

**Comment by Lupopa** [comment]
I have download a Rasbian Stretch (over torrent "2018-06-27-raspbian-stretch.zip") and will test it.
I'll give feedback if it worked.

**Comment by Lupopa** [comment]
Okay, with "stretch" Alexa will run now...

**Comment by scotthea-amazon** [comment]
Hi Lupopa,

It looks like the problem has been resolved, so I am closing this issue.  Feel free to re-open it if it has been closed in error.

Thank you,
-SWH

**Comment by Vaishnavikumara** [comment]
But , as Raspbian is updated to buster now , I have to use buster . Also , stretch is not available on the offcial website of Raspberry Pi. I am almost done with the building , but I am getting an error "Failed to build the Sample Application" . Please do the needful

**Comment by Lupopa** [comment]
Yes great, you can download but about Torrent Raspbian Stretch. There you get the original version.

**Comment by Vaishnavikumara** [comment]
Yeah I did that. But is there no solution for the error faced while using the buster version?

**Comment by Lupopa** [comment]
Look there: https://github.com/alexa/avs-device-sdk#get-started 
"Raspberry Pi (Raspbian Stretch)"
