### ISSUE TITLE
How to store volume setting after device reboot?

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1403]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How to keep the volume adjust setting after device?
For example, the device startup will have speaker volume to 10
Once we say 'alexa, set volume to 5' and reboot device.
Next time when device startup. The speaker volume is still be 10 not 5

## What is the expected behavior?

Save volume adjust value

## What behavior are you observing?

The volume setting always be 10

## Provide the steps to reproduce the issue, if applicable:

1.Boot up
2.Set volume to 5
3.quit and re-run SampleApp

### What version of the AVS Device SDK are you using?
      <1.13.0>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello yuan0258,

Thank you for bringing this to our attention!  This appears to be a bug (functionality missing) in the SDK.  I will make sure we are tracking this so that it gets fixed.

Best regards,
-SWH

**Comment by yuan0258** [comment]
@scotthea-amazon 
Thank for your reply
Do you know which old version SDK is ok?

**Comment by scotthea-amazon** [comment]
Hello yuan0258,

The SDK has never had this functionality. so there is not an older version without this problem.

Thank you,
-SWH

**Comment by yuan0258** [comment]
Hi @scotthea-amazon ,
I try this feature at SDK v1.14.0. It still couldn't store volume.
Do I miss some something?
I also try to use menu to control speaker volume and quit.
It seems it couldn't load previous speaker volume setting.
Her is my steps
1.Run SampleApp
2.Use p + enter + 1 + 2 to decrease the volume
3.Quit SampleApp
4.Run SampleApp & use p + enter + 1 + 2 to decrease the volume. It seems volume still start with 10 not 9

**Comment by dhpp** [comment]
Hi @yuan0258, as SWH mentioned in his earlier post, the SDK does not support this at this time, however we do have a future work item to add at some point.  Thanks for raising the question, it is good feedback for us.  For now, I will close out this ticket.

**Comment by az2022** [comment]
Apart from the above request, a default volume setting to start with when alexa is starting for the very first time would be good. Perhaps something could be added to the AlexaClient json file for this?

**Comment by yuan0258** [comment]
@dhpp,
I use ubuntu 16.04 with 1.15 version.
It seems the behavior is same before.
I expect the user could set their volume and reboot device.
It should keep previous volume they set

**Comment by flos06** [comment]
Any progress on this?
