### ISSUE TITLE
Build faile due to  Unmet Dependencies

### ISSUE THREAD

**Issue by Vaishnavikumara** [alexa/avs-device-sdk#1405]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The configuration is not getting completed due to failure in installing certain packages .(Broken Images)

## What behavior are you observing?

==============> INSTALLING REQUIRED TOOLS AND PACKAGE ============

Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
cmake is already the newest version (3.13.4-1).
gcc is already the newest version (4:8.3.0-1+rpi2).
git is already the newest version (1:2.20.1-2).
gstreamer1.0-plugins-good is already the newest version (1.14.4-1).
libcurl4-openssl-dev is already the newest version (7.64.0-4).
libfaad-dev is already the newest version (2.8.8-3).
libgcrypt20-dev is already the newest version (1.8.4-5).
libgstreamer-plugins-bad1.0-dev is already the newest version (1.14.4-1+b1).
libsoup2.4-dev is already the newest version (2.64.2-2).
libsqlite3-dev is already the newest version (3.27.2-3).
libasound2-dev is already the newest version (1.1.8-1+rpt1).
python3-pip is already the newest version (18.1-5+rpt1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed
E: Unable to correct problems, you have held broken packages.

## Provide the steps to reproduce the issue, if applicable:

Followed  https://developer.amazon.com/docs/alexa-voice-service/build-the-avs-device-sdk.html

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:

- [ ] Raspberry Pi

### Tell us about your OS (Type & version):

- [ ] Raspbian Buster

**Comment by scotthea-amazon** [comment]
Hello Vaishnavikumara,

It sounds like you package database has some problems. As a starting point, you might try running sudo apt-get update and/or sudo apt-get autoremove and see if that resolves the issue or gives more useful error messages.

Googling further I see some promising hints for resolving held broken packages.  For example:  https://unix.stackexchange.com/questions/389156/how-to-fix-held-broken-packages

If you are still stuck, you might consider a fresh install of raspbian (erase your SD card and reimage it).

Best regards,
-SWH

**Comment by Vaishnavikumara** [comment]
I will try this and get back to you, thanks . But please dont close the issue prior to that

**Comment by Vaishnavikumara** [comment]
I am still facing the same error . But using Synaptic managerI observed one thing , the package "libcurl4-openssl-dev" has conflicts with libssl1.0-dev. How to overcome this and install these packages without conflict ? Kindly help

**Comment by kclchan** [comment]
Hi @Vaishnavikumara, could you try modify the pi.sh script in the tools/Install directory to instead installing the libssl1.0-dev package, change it to libssl-dev instead?

**Comment by Vaishnavikumara** [comment]
I will try that and get back to you. Thanks .

**Comment by Vaishnavikumara** [comment]
That worked and did not show the same error . But now a new error is popping up :
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/postgresql-11/libpq5_11.3-1_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


How to fix this ? Please Help.

**Comment by Vaishnavikumara** [comment]
Hi @kclchan , I solved the above error too , but now facing the following error saying "Sample Application failed to create PortAudioMicrophoneWrapper " . Please help .

The log is as follows :
[log.txt](https://github.com/alexa/avs-device-sdk/files/3358660/log.txt)

**Comment by kclchan** [comment]
Hi @Vaishnavikumara, please refer to my response in #1413.  Thanks!

**Comment by jolimk** [comment]
Hello, I see this issue was closed but im getting the same error on my Raspberry and have no idea how to fix this. Please help me. Thank you very very much.

**Comment by angus390** [comment]
> I will try that and get back to you. Thanks .

Hello, how do you modify the pi.sh scripts? thanks
