### ISSUE TITLE
Fail to build integration test on Window 10

### ISSUE THREAD

**Issue by nguyenhuy3588** [alexa/avs-device-sdk#1407]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
Unable to build integration test on Window 10

## Briefly summarize your issue:
I successfully built AVS and run sample app on my Window 10 environment with Mingw64, but when navigating to build folder and typing "make all integration" i can't finish the build due to "implicitly-declared" error like this:

![image](https://user-images.githubusercontent.com/16719961/60315582-4b0d9600-9991-11e9-8c40-bc38d5cf5619.png)

then it end the build:

![image](https://user-images.githubusercontent.com/16719961/60315606-6082c000-9991-11e9-95dd-d74894be4b5d.png)

## What is the expected behavior?
It should successfully build and run all the test

## What behavior are you observing?
It prompted error then stop building

## Provide the steps to reproduce the issue, if applicable:
1. Navigate to build folder
2. Type "make all integration"

### What version of the AVS Device SDK are you using?
      <1.13.0>

### Tell us what hardware you're using:
- Laptop

### Tell us about your OS (Type & version):
- Window 10 64 bit

**Comment by scotthea-amazon** [comment]
Hello nguyenhuy3588,

Of course we will go back and re-test , but we did not see this in our testing of 1.13 on Windows.  Is there anything special about your environment?

Also, can you tell is which version of the compiler you are using?

Thank you,
-SWH

**Comment by nguyenhuy3588** [comment]
Hi @scotthea-amazon, sorry for the late response, i faced this problem when cloning our source on Ubuntu and rebuilding it on Window( i successfully run on Ubuntu follow our guide). I think i failed because the linking process i use is not right, after that i tried on our setup script and successfully run on Window, so i think i will read more on the setup script and understand it, thanks for your help.
