### ISSUE TITLE
Alexa skill to control AVS device

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1408]
Hi, AVS team

We are studying Alexa skill and the target is that our AVS device can be done some custom intents.
Recently, we tried to control device by using the Alexa smart home skill. But, our device could not show up on Smart home device list, lead the skill could not control our device.

How does our device become a smart home device?

Thanks~~

**Comment by scotthea-amazon** [comment]
Hello elfdie00475,

Here is the documentation for adding smart-home skills to a device: https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html

Best regards,
-SWH

**Comment by elfdie00475** [comment]
Hi @scotthea-amazon ,

Thanks for your recommendations.
We are studying the documents of smart-home skills, we are also trying to create a skill by following the steps of [smart-home skill github ](https://github.com/alexa/skill-sample-python-smarthome-switch/blob/master/instructions/README.md).
Smart-home skill maybe can solve the part of our questions.

Thanks for your help.
