### ISSUE TITLE
can't find api like seekTo()  setVolume()/getVolume  mute()/unmute()

### ISSUE THREAD

**Issue by nongcunshaoye** [alexa/avs-device-sdk#141]
hi ! avs team! 
I can't find some api like seekTo()  setVolume()/getVolume  mute()/unmute() getDuration()  getCurrentPosition() in MediaPlayer module

**Comment by scotthea-amazon** [comment]
Hello nongcunshaoye,

Unfortunately, the [avs-device-sdk](https://github.com/alexa/avs-device-sdk) does not yet include [CapabilityAgents](https://github.com/alexa/avs-device-sdk/tree/master/CapabilityAgents) to handle directives for the [Speaker Interface](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speaker) or the [Playback Controller Interface](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/playbackcontroller).  Those feature will be added in an upcoming release, and when applicable the underlying functionality will be added to the [MediaPlayer](https://github.com/alexa/avs-device-sdk/tree/master/MediaPlayer) component.

Thanks,
-SWH

**Comment by nongcunshaoye** [comment]
@scotthea-amazon  Thanks very much!
