### ISSUE TITLE
Display wrong Serial number at https://alexa.amazon.com

### ISSUE THREAD

**Issue by phyen808724** [alexa/avs-device-sdk#1415]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Display wrong Serial number at https://alexa.amazon.com 

## What is the expected behavior?

Display correct Serial number at https://alexa.amazon.com like echo dot

## What behavior are you observing?

I want to build AVS sdk into android device and I follow https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide to build AVS sdk to android device.
I insert correct DSN into deviceSerialNumber of deviceInfo at config.jason file.
After CBL progress to register device to my Amazon account , I check DSN on website : https://alexa.amazon.com .
DSN is not correct on website.

### What version of the AVS Device SDK are you using?
      <x.y.z>
1.13.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
android devices

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
android devices

Log as below : 
07-04 09:11:11.608 E/CBLAuthDelegateConfiguration( 6394): getDeviceSerialNumber: 171845214D0743
07-04 09:11:11.609 E/CBLAuthDelegateConfiguration( 6394): sn: 171845214D0743
07-04 09:11:11.609 E/CBLAuthDelegateConfiguration( 6394): deviceSN: 171845214D0743
07-04 09:11:11.847 E/CapabilitiesDelegate( 6394): getPreviouslySentCapabilitiesPublishData
07-04 09:11:11.851 E/CapabilitiesDelegate( 6394): reset m_previousDeviceInfo
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): receiveCodePairResponse()
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): m_userCode = AEAHC6
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): m_deviceCode = d1252b64-3eb2-4424-a220-40295f5c34ed
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): verificationUri = https://amazon.com/us/code
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): expiresInSeconds = 600
07-04 09:11:13.339 E/CBLAuthDelegate( 6394): intervalSeconds = 30
07-04 09:11:13.340 E/CBLAuthDelegate( 6394): requestToken()
07-04 09:11:13.340 E/CBLAuthDelegate( 6394): m_deviceCode = d1252b64-3eb2-4424-a220-40295f5c34ed
07-04 09:11:13.340 E/CBLAuthDelegate( 6394): m_userCode = AEAHC6
07-04 09:11:13.602 E/CBLAuthDelegate( 6394): receiveTokenResponse()
07-04 09:11:18.603 E/CBLAuthDelegate( 6394): requestToken()
07-04 09:11:18.603 E/CBLAuthDelegate( 6394): m_deviceCode = d1252b64-3eb2-4424-a220-40295f5c34ed
07-04 09:11:18.603 E/CBLAuthDelegate( 6394): m_userCode = AEAHC6
07-04 09:11:18.883 E/CBLAuthDelegate( 6394): receiveTokenResponse()
07-04 09:11:28.179 E/CBLAuthDelegate( 6394): requestToken()
07-04 09:11:28.180 E/CBLAuthDelegate( 6394): m_deviceCode = d1252b64-3eb2-4424-a220-40295f5c34ed
07-04 09:11:28.180 E/CBLAuthDelegate( 6394): m_userCode = AEAHC6
07-04 09:11:28.443 E/CBLAuthDelegate( 6394): receiveTokenResponse()
07-04 09:11:33.444 E/CBLAuthDelegate( 6394): requestToken()
07-04 09:11:33.445 E/CBLAuthDelegate( 6394): m_deviceCode = d1252b64-3eb2-4424-a220-40295f5c34ed
07-04 09:11:33.445 E/CBLAuthDelegate( 6394): m_userCode = AEAHC6
07-04 09:11:33.996 E/CBLAuthDelegate( 6394): receiveTokenResponse()
07-04 09:11:33.997 E/CBLAuthDelegate( 6394): accessToken = Atza|IwEBIHigOsvG_ILu_GB4aZg6KcNu3dtFB0KDAFaGnInGti8baMlRhUadE2eBP1cphUukFWw-1qgELidEbiuXRSdNgOzF6-8SqSdasOxSiTWYUR3tIJWsd0AIiEivVUG_3tRWhlYNgACHHAsQewplLZ_KFsc7JVOgJVzb4d6UG2n-orKJD92y4LV6ZwOB1HzyKHdW6Yw3ktrYu3zyDmQq_Rf4eUXNqqzVQWYd4GBVRGCpmttCWF0ESvkZAeMdYJbgN2d605r3_t4EP04WTCytpYjJFLPuiUIOs8OD3vEANxn1BvOBHl4MjzAvyES2qnP3WaO1ETaykzi8lqQBscnnaYIM7mls7gEzcizLJPg11zZoghyjavcZ5Dz46952HHjwSGvN65J8WAg0QDlL5QP2sZlrb3cE-r2CkmQ-OHgTForzQYuopR6rzK6EHzRIgwRuPh2ywALpIp-K9b711ZDsuxs1W2fKBTCYG_daHeqJrlGOJZ6jlamfd1VMU44DAgE1sJBGsLA
07-04 09:11:33.997 E/CBLAuthDelegate( 6394): refreshToken = Atzr|IwEBIBHR5_fgAp3q6T_z6uAvZpcoACvQZyXQm4OgEg0iUKyKhhgCFYVYLtNV5QnDkJI5Y1ASi1CaAA618bRWUjRCHWRzBU_ucHDHs5Jq0glnvuA-bHX3iaqDge9zylFV09TzHShCfPc8Wg5tS3P8DvkD68mWm3NluIiqV13MoREcYS0_rrQagcp3UdkVScq9zfgWvElvnf6dh_kec85LDr9BhTMo0jHNi67HY_Go1fi4s_pR7QWjVtZUlAHv9FAIDj12swsCeeWDzlcjDAIwu_d5zFoR7PLKg8l3ww8lZPzFnnSqwPP8yFQy-hDR1tMmAlyp3N1lGro2zI1TYH8A6dAE0rRbVJvkfl0u1fP9NLaK9OWg9SUyn2EvOW9dnv3iyiPkR9b7O_0JrAkni9sM2S_QbJg-zwO5fYH5KHBbBKzSj1ee5q8FOMAdHM0kJ6ztgf7i81s9ZZEiUk9BRBiz2ocdT1ugywDh7UIktIYuuQSiU13tgZnMWZRqys6qe6FY4mgVbWyYKAStwpwnqD5tMDrIUVsB
07-04 09:11:33.997 E/CBLAuthDelegate( 6394): tokenType = bearer
07-04 09:11:33.997 E/CBLAuthDelegate( 6394): expiresInSeconds = 3600
07-04 09:11:34.069 E/CBLAuthDelegate( 6394): requestRefresh()
07-04 09:11:34.363 E/CBLAuthDelegate( 6394): receiveTokenResponse()
07-04 09:11:34.364 E/CBLAuthDelegate( 6394): accessToken = Atza|IwEBINP-39-IljG6bdGUywzNiddyknQ0YrHn2bVLnT2LrHdriNaQ84b_Wkam5rHH33DyfqE6a3zmSwYjfWV2VFWBqJe154vLQ3hEpaqcjcX6RHoV8kvRiEfNnaZBUz-PZA_bcFtLlTtr8q_GS2PMDxt_RxB5DwuKKxDatKfWbFZhl_Pt-aukjESEZAbnA1nJSFz8TPWHDFXCFY23Q0WDr6Y2DOzuy4y4ggyQAot7nnMZKIzHhGlRYA7P66lVNH-L9X_WqkK2V-eReT7cRw8wf82mre5gWIS3p6iUSb0AXAwTvTTB5Meq2SaztdN-OqJ0BUK5MZMq559ACZTVaNPpmiyjNGeKUtc4I1579QblK5Bj3kVjIzh3vUTVa2cuEAnggNEsIkbV8fE_Td18IRNAcwFrd54lfTKOMBNA5E_lP58F08b4TIYYCLKiWYDUKG6bcIjmRsVXrhF2fRjN9-4cpQMf5_UBwSiBQ9r6P6u8HiUnk77NXKsKVQ_aWeWazCsKpXrezh9NwX48KqPwBW_UWvStFYcPwiCL-ERTDgs3O7cXCy_tGQ
07-04 09:11:34.364 E/CBLAuthDelegate( 6394): refreshToken = Atzr|IwEBIBHR5_fgAp3q6T_z6uAvZpcoACvQZyXQm4OgEg0iUKyKhhgCFYVYLtNV5QnDkJI5Y1ASi1CaAA618bRWUjRCHWRzBU_ucHDHs5Jq0glnvuA-bHX3iaqDge9zylFV09TzHShCfPc8Wg5tS3P8DvkD68mWm3NluIiqV13MoREcYS0_rrQagcp3UdkVScq9zfgWvElvnf6dh_kec85LDr9BhTMo0jHNi67HY_Go1fi4s_pR7QWjVtZUlAHv9FAIDj12swsCeeWDzlcjDAIwu_d5zFoR7PLKg8l3ww8lZPzFnnSqwPP8yFQy-hDR1tMmAlyp3N1lGro2zI1TYH8A6dAE0rRbVJvkfl0u1fP9NLaK9OWg9SUyn2EvOW9dnv3iyiPkR9b7O_0JrAkni9sM2S_QbJg-zwO5fYH5KHBbBKzSj1ee5q8FOMAdHM0kJ6ztgf7i81s9ZZEiUk9BRBiz2ocdT1ugywDh7UIktIYuuQSiU13tgZnMWZRqys6qe6FY4mgVbWyYKAStwpwnqD5tMDrIUVsB
07-04 09:11:34.364 E/CBLAuthDelegate( 6394): tokenType = bearer
07-04 09:11:34.364 E/CBLAuthDelegate( 6394): expiresInSeconds = 3600
07-04 09:11:34.388 E/CBLAuthDelegate( 6394): setAuthState()
07-04 09:11:34.388 E/CBLAuthDelegate( 6394): m_authState = 0
07-04 09:11:34.388 E/CBLAuthDelegate( 6394): newAuthState = 1
07-04 09:11:35.285 E/CapabilitiesDelegate( 6394): HTTPResponseCode::SUCCESS_NO_CONTENT
07-04 09:11:35.285 E/CapabilitiesDelegate( 6394): saveCapabilitiesPublishData
07-04 09:11:35.285 E/CapabilitiesDelegate( 6394): put client ID
07-04 09:11:35.308 E/CapabilitiesDelegate( 6394): put product ID
07-04 09:11:35.325 E/CapabilitiesDelegate( 6394): put DeviceSerialNumber
07-04 09:11:35.369 E/CapabilitiesDelegate( 6394): getPreviouslySentCapabilitiesPublishData
07-04 09:11:35.372 E/CapabilitiesDelegate( 6394): previousClientId = amzn1.application-oa2-client.b4f68ba0f02842dd995017d611076d46
07-04 09:11:35.372 E/CapabilitiesDelegate( 6394): previousProductId = CDR8010
07-04 09:11:35.372 E/CapabilitiesDelegate( 6394): previousDeviceSerialNumber = 171845214D0743
07-04 09:11:35.374 E/CapabilitiesDelegate( 6394): previousCapabilitiesPublishMsgStr = {"envelopeVersion":"20160207","capabilities":[{"type":"AlexaInterface","interface":"EqualizerController","version":"1.0","configurations":{"bands":{"supported":[{"name":"BASS"},{"name":"MIDRANGE"},{"name":"TREBLE"}],"range":{"minimum":-6,"maximum":6}}}},{"type":"AlexaInterface","interface":"SpeechSynthesizer","version":"1.0"},{"type":"AlexaInterface","interface":"VisualActivityTracker","version":"1.0"},{"type":"AlexaInterface","interface":"Settings","version":"1.0"},{"type":"AlexaInterface","interface":"Alexa.DoNotDisturb","version":"1.0"},{"type":"AlexaInterface","interface":"Alexa.PlaybackStateReporter","version":"1.0"},{"type":"AlexaInterface","interface":"PlaybackController","version":"1.1"},{"type":"AlexaInterface","interface":"InteractionModel","version":"1.0"},{"type":"AlexaInterface","interface":"Alexa.FavoritesController","version":"1.0"},{"type":"AlexaInterface","interface":"TemplateRuntime","version":"1.1"},{"type":"AlexaInterface","interface":"Speaker","version
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityName = EqualizerController
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityConfigurations = {"bands":{"supported":[{"name":"BASS"},{"name":"MIDRANGE"},{"name":"TREBLE"}],"range":{"minimum":-6,"maximum":6}}}
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.EqualizerController
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityName = SpeechSynthesizer
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.SpeechSynthesizer
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityName = VisualActivityTracker
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.375 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.VisualActivityTracker
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityName = Settings
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Settings
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.DoNotDisturb
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.DoNotDisturb
07-04 09:11:35.376 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.PlaybackStateReporter
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.PlaybackStateReporter
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityName = PlaybackController
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.1
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.PlaybackController
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityName = InteractionModel
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.InteractionModel
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.FavoritesController
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.FavoritesController
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityName = TemplateRuntime
07-04 09:11:35.377 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.1
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.TemplateRuntime
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityName = Speaker
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Speaker
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.SeekController
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.SeekController
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityName = SpeechRecognizer
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityVersion = 2.1
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.SpeechRecognizer
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityName = Notifications
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Notifications
07-04 09:11:35.378 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.PlaylistController
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.PlaylistController
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityName = Alexa.PlaybackController
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alexa.PlaybackController
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityName = Alerts
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.3
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.Alerts
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityName = System
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.2
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.System
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityName = ExternalMediaPlayer
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityVersion = 1.0
07-04 09:11:35.379 E/CapabilitiesDelegate( 6394): capabilityKey = AlexaInterface.ExternalMediaPlayer
07-04 09:11:35.380 E/CapabilitiesDelegate( 6394): capabilityType = AlexaInterface

**Comment by Agrahyah** [comment]
Facing the same issue too

**Comment by kclchan** [comment]
Hi @Agrahyah and @phyen808724, please note that the serial number is an alphanumeric number of length 32 generated by AVS, and not the same as the deviceSerialNumber in the config.json file.

**Comment by phyen808724** [comment]
Hi @kclchan ,

Thanks for your help.

Thanks,
ph
