### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by Agrahyah** [alexa/avs-device-sdk#1416]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Android is soon going to support only ARM64v8 and deprecate usage of ARMv7a. For this purpose the current builds will fail and play store will soon not accept apks having ARMv7 .so libs. So when is the official support for ARM64 coming to AVS SDK.

## What is the expected behavior?
ARM8 build

## Tell us about your environment:
Android
### What version of the AVS Device SDK are you using?
      1.13.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android  ARM64 v8

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android ARM64 v8

**Comment by kclchan** [comment]
Hi @Agrahyah, thanks for getting in touch with us.  Adding support to Arm64v8 is on our backlog.

**Comment by Agrahyah** [comment]
Cant push 32bit versions of the apk including avs sdk any more on Google Playstore. Arm64 build needs to be on high priority. Awaiting quick update to the sdk.


![arm64](https://user-images.githubusercontent.com/25545904/63027243-39913680-beca-11e9-96b8-b0da796b33e1.PNG)
