### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by s235711** [alexa/avs-device-sdk#1418]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

can't compile the sdk
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Buster
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

ERROR
[ 95%] Linking CXX executable SampleApp
/usr/bin/ld: CMakeFiles/SampleApp.dir/SampleApplication.cpp.o: in function `std::__atomic_base<unsigned long long>::operator=(unsigned long long)':
/usr/include/c++/8/bits/atomic_base.h:374: undefined reference to `__atomic_store_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::write(void const*, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Writer::Writer(alexaClientSDK::avsCommon::utils::sds::WriterPolicy, std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::BufferLayout>)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o: in function `std::__atomic_base<unsigned long long>::operator unsigned long long() const':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../ACL/src/libACL.so: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/build.make:288: SampleApp/src/SampleApp] Error 1
make[2]: *** [CMakeFiles/Makefile2:10227: SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:10239: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:2580: SampleApp] Error 2

**Comment by kclchan** [comment]
HI @s235711, please note that Buster is not officially supported byt he avs-device-sdk.  But please refer to #1404 for a suggestion to fix this particular linking issue.  Thanks!

**Comment by Xxjojo** [comment]
I use the raspberry pi 4b and it doesn't work.
Can I maby install Debian on the Raspberry pi 4b?
