### ISSUE TITLE
How can I change wake up word from "Alexa" to "Hey dum dum"?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1419]
Hi,

I have just installed avs-device-sdk on raspberry pi 3 B by following this guide :
https://scribles.net/enabling-amazon-alexa-on-raspberry-pi/
&
https://developer.amazon.com/alexa-voice-service/learn/tutorials

I am thinking of making a  product which I think will be commercialized so I don't know I am on the right way or not. 

I want to change it's custom wake up word to something else. I didn't find any doc on this so asking here. And I also want to enable GPIO pin usage.

Thanks.

**Comment by kclchan** [comment]
Hi @rajdpandey, please note that the only accepted value for wakeword is "ALEXA".

Please refer to this for more information:
https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#speechrecognizer-context

**Comment by rajdpandey** [comment]
OK, so if I want to change it to the custom one how can I do it?

**Comment by khassel** [comment]
This project supports 2 WakeWordEngines

- Sensory: "Alexa" is the only WakeWord
- KittAi: Custom WakeWords are possible, see http://kitt.ai/

You can change the WakeWord for fun, but I think for productive solution thats not a good idea, e.g., if Alexa talks about herself, she will always say "Alexa" and never "Hey dum dum" ...

**Comment by dhpp** [comment]
This is not supported by AVS.  You may end up not getting any Alexa response from the server, since the cloud also verifies that the correct wakeword was spoken by the user.  I'll close this ticket out.
