### ISSUE TITLE
The following packages have unmet dependencies:  libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by jolimk** [alexa/avs-device-sdk#1421]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I try to `sudo bash setup.sh config.json -s 998987` I get the error `The following packages have unmet dependencies:
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed
E: Unable to correct problems, you have held broken packages.`

## What is the expected behavior?

Build should end successfully.

## What behavior are you observing?

The installing process stops.

## Provide the steps to reproduce the issue, if applicable:

Just running everything until sudo bash setup.sh config.json.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @jolimk 

Can you run the following commands and see if it fixes your issue:
`sudo apt-get build-dep libcurl4-openssl-dev
sudo apt-get install libcurl4-openssl-dev`

**Comment by ereich1217** [comment]
I am having the same issue.
I tried the two apt-get commands you listed, but it didn't change the error I am getting.

```
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
cmake is already the newest version (3.13.4-1).
gcc is already the newest version (4:8.3.0-1+rpi2).
gcc set to manually installed.
git is already the newest version (1:2.20.1-2).
gstreamer1.0-plugins-good is already the newest version (1.14.4-1).
libcurl4-openssl-dev is already the newest version (7.64.0-4).
python3-pip is already the newest version (18.1-5+rpt1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by ereich1217** [comment]
Update:
First, I was using Raspbian 10 (buster) not Raspbian 9 (stretch) as jolimk is using.
Second, I couldn't find Raspbian 9 available directly from raspberrypi.org.  I found multiple Raspbian 9 (stretch) images available from distrowatch.com
Lastly, I was able to to get the Raspbian 9 relase from 2018-11-13 to work with the setup.sh script.

https://distrowatch.com/?newsid=10376 

I wish I had a better solution that worked with the latest release, but this solved my problem.  I hope it helps you too.

**Comment by Yeremiy** [comment]
Hi. I have the same problem. 2 days I'm with that. probe that
sudo apt-get build-dep libcurl4-openssl-dev
sudo apt-get install libcurl4-openssl-dev
probe
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libssl1.0-dev
Nothing.
some more ideas? I see that many people have the same. search the internet nobody does not know

**Comment by dhpp** [comment]
Have you tried guidance as offered in discussions such as [here](https://askubuntu.com/questions/363200/e-unable-to-correct-problems-you-have-held-broken-packages) or [here](https://askubuntu.com/questions/705971/cannot-seem-to-install-libcurl4-openssl-dev-package)?

**Comment by Yeremiy** [comment]
hola. instalar me para con mismo error.
sudo apt-get build-dep libcurl4-openssl-dev // error : E: You must put some source URIs ("source") in your sources.list
sudo apt-get install libcurl4-openssl-dev // OK
sudo apt-get install libssl1.0-dev  // OK
sudo apt-cache policy libcurl4-openssl-dev libssl1.0-dev  // OK
sudo apt-get install libcurl4-openssl-dev  // OK
sudo apt-get install librtmp-dev  // OK
sudo apt-get clean  // OK
sudo apt-get autoclean    // OK
sudo apt-get -f install  // OK
and nothing. same mistake :
The following packages have unfulfilled dependencies:
  libcurl4-openssl-dev: Conflicts: libssl1.0-dev but 1.0.2q-2 is going to be installed
E: Problems could not be corrected, you have retained broken packages.
someone found how to fix this error?

**Comment by Yeremiy** [comment]
sudo nano /etc/apt/sources.list

uncomented url: deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free $
command: sudo apt-get build-dep libcurl4-openssl-dev / OK
Did not help.......

**Comment by Yeremiy** [comment]
helped me
sudo nano /home/pi/pi.sh
find libssl1.0-dev and change to libssl-dev

**Comment by womw** [comment]
Hi @jolimk are you still having trouble with this issue? has any of these comments helped resolve your issue?

@ereich1217 We are currently looking into how the sdk can support Raspbian Buster, until then we are currently only supporting Raspbian Stretch. It seems like you were able to successfully run the sdk.

**Comment by Yeremiy** [comment]
Hi. already fixed. I have no problem. Steps
no estoy seguro si nesecito todos pasos. perro yo echo:
1. sudo apt-get install libcurl4-openssl-dev // OK
    sudo apt-get install libssl1.0-dev // OK
    sudo apt-cache policy libcurl4-openssl-dev libssl1.0-dev // OK
    sudo apt-get install libcurl4-openssl-dev // OK
    sudo apt-get install librtmp-dev // OK
    sudo apt-get clean // OK
    sudo apt-get autoclean // OK
    sudo apt-get -f install // OK
   sudo apt-get build-dep libcurl4-openssl-dev // error : E: You must put some source URIs ("source") in 
   your sources.list     (solve with step 2)
2. Prblem build: sudo apt-get build-dep libcurl4-openssl-dev
    a) sudo nano /etc/apt/sources.list
         uncomented url: deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free $
   b) sudo apt-get build-dep libcurl4-openssl-dev //OK
3. solve with error: libcurl4-openssl-dev: Conflicts: libssl1.0-dev but 1.0.2q-2 is going to be installed:
           sudo nano /home/pi/pi.sh    
           find libssl1.0-dev and change to libssl-dev
4. GO :)
          sudo bash setup.sh config.json -s [1234]
5. Then it will be another mistake error :+1: 
collect2: error: ld returned 1 exit status
make [3]: *** [SampleApp / src / CMakeFiles / SampleApp.dir / build.make: 288: SampleApp / src / SampleApp] Error 1
make [2]: *** [CMakeFiles / Makefile2: 10227: SampleApp / src / CMakeFiles / SampleApp.dir / all] Error 2
make [1]: *** [CMakeFiles / Makefile2: 10239: SampleApp / src / CMakeFiles / SampleApp.dir / rule] Error 2
make: *** [Makefile: 2580: SampleApp] Error 2
FIXED:
sudo nano /home/pi/avs-device-sdk/SampleApp/CMakeLists.txt
put above everything:
set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")
6. GO :)
      sudo bash setup.sh config.json -s [1234]
FIN INSTALL :) OK

**Comment by womw** [comment]
OK, I will be closing this issue now then. If anyone still needs help feel free to reopen this issue or create a new one.

**Comment by samiron7567** [comment]
> helped me
> sudo nano /home/pi/pi.sh
> find libssl1.0-dev and change to libssl-dev
> a source : #1405

Thanks. This worked for me as well

**Comment by iguana03** [comment]
> sudo nano /home/pi/pi.sh
> find libssl1.0-dev and change to libssl-dev
> a source : #1405

Thanks @Yeremiy

**Comment by ravenslea** [comment]
> helped me
> sudo nano /home/pi/pi.sh
> find libssl1.0-dev and change to libssl-dev
> a source : #1405

Fixed it for me. Thanks @Yeremiy

**Comment by AndrewDrew100** [comment]
Openvas changed name to gvm
Solution: purge openvas and install gvm

so run #apt-get install gvm 
then   #gvm-setup 
and so on
