### ISSUE TITLE
Thumbs rating does not update by using voice

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1423]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi,

This issue only happen on Amazon music. Here is log: [thumb_up_by_voice.TXT](https://github.com/alexa/avs-device-sdk/files/3366841/thumb_up_by_voice.TXT).

When I played the music station on Amazon music (on line 1439), I used the voice command "Alexa, thumbs up" to control thumbs up state (on line 3668). In expect, SampleApp will receive the directive data to update thumbs up state after finishing response, but it doesn't.
I had been listened the response from AVS cloud (during line 4187 to line 4872) but thumbs up state still not change after resuming music. (on line 5035). Even I re-played the music, thumbs up state was also not updated. (during line 6445 to line 7388)

In Alexa App, thumbs up state was also not toggled to on.
Thanks~~
## What is the expected behavior?

The thumbs up state shall be updated immediately when I ask Alexa to toggle thumbs up state.

## What behavior are you observing?

SampleApp can get response by voice, but can not get directive data to update thumbs up state.
![Response from AVS cloud](https://user-images.githubusercontent.com/43197587/60787602-ec180000-a18c-11e9-9651-da405184e52e.png)

## Provide the steps to reproduce the issue, if applicable:

1. Play music station on Amazon Prime.
2. Setting thumbs up by using voice when music is playing.
3. Check thumbs up state on SampleApp and Alexa App.

### What version of the AVS Device SDK are you using?
      <1.13.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: arm-linux embedded system

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi, We are investigating the issue. Will update here when we have more information.

**Comment by ada1013** [comment]
Hi Team,

We also met the same issue, do you have any update for it? 
Thanks~

**Comment by caleighatamazon** [comment]
Hi there, sorry for our late response on this. Are you still having problems?

**Comment by ada1013** [comment]
Hi Team,

I have just tested it, thumbs down is good, but thumbs up doesn't work.

**Comment by caleighatamazon** [comment]
Have you tried this on our latest SDK release, too, and do you still see the problem? (1.16)

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please re-open if I've closed this in error.

**Comment by ashiksl** [comment]
Hi,

We also met the same issue with Alexa SDK 1.17.
Steps,
1. Play from amazon music
2. Setting "thumbs up" using voice utterance.
3. Check the THUMBS_UP value on renderplayerinfo card.
{**"selected":false**,"name":"**THUMBS_UP**","enabled":true,"type":"TOGGLE"
