### ISSUE TITLE
Alexa Device Serial Identification with Lambda Skill query from AVS server

### ISSUE THREAD

**Issue by iamartificialhuman** [alexa/avs-device-sdk#1424]
Hello AVS Team,

We have a project where in AVS is enabled on multiple devices having unique serial id. As per our business requirement, we have enabled custom alexa skill which can be used to get status and control certain features in these devices. 

Now as per our design of solution, we need to identify, a way as to which device was used by the user to invoke our custom skill. We looked into possible solutions but could not figure out a unique ID which the device can register itself to our cloud solution and then the same ID can be used in every intent invocation request received in our Lambda function , so that we can map which device was used for invocation of our skill. 

**Is there any way in avs-device-sdk client to send the device serial id to the AVS server?
If not then is there any way to get the device serial from lambda function?**

Thanks,
Arvind

**Comment by mvelegon-amzn** [comment]
Hi @iamartificialhuman thanks for reaching out. 

The avs-device-sdk does share the Device's serial number with the AVS server as part of authentication using the CBLAuthDelegate. However, I am not sure if it is exposed on the lambda.

Since this is a specific question regarding alexa-skills, could you please open an issue on the Alexa Skills Kit SDK github forum to understand if accessing the device serial number is possible?

**Comment by iamartificialhuman** [comment]
Hello Team,

I raised a request in "Alexa skill kit sdk git hub" and got the below response:

**Response from amazon team(Alexa skill kit sdk git hub):**

I want to make sure the sdk you are using is avs-device-sdk right? If so, it might be the wrong place to post this issue. Here is the github link for avs sdk (https://github.com/alexa/avs-device-sdk), it would be great if you can re-post this issue there. Let me know if you have any problems."

What should I do now?

**Comment by mvelegon-amzn** [comment]
Unfortunately, this is not the right forum to answer this question as from the avs-device-sdk perspective, the DSN is communicated with the cloud. If the lambda has access to it or not in the cloud is something the AVS or the skills folks can answer.

Could you please try posting your question here: https://forums.developer.amazon.com/spaces/38/index.html or
https://forums.developer.amazon.com/spaces/232/index.html
