### ISSUE TITLE
Broken link from main README

### ISSUE THREAD

**Issue by wincelet** [alexa/avs-device-sdk#1425]
## Briefly summarize your issue:
Links from the capability agents section of the main README mostly link to the general documentation page. 
DoNotDisturb link is a 404.
Some of the links appear correct: Bluetooth, EqualizerController and InteractionModel

## What is the expected behavior?
I would expect all links to go to their respective relevant API page. Not redirect to the general documentation home page. 

## Tell us about your environment:
Chrome browser

### Tell us about your OS (Type & version):
MacOS

**Comment by mvelegon-amzn** [comment]
@wincelet  Thank you for bringing this to our attention. We fixed this as part of the latest 1.14 release. Closing this ticket now.
