### ISSUE TITLE
Amazon Music - Alexa: I can not play Amazon music on this device.

### ISSUE THREAD

**Issue by Yeremiy** [alexa/avs-device-sdk#1427]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

does not play amazon music. he says i can't play amazon music on this device.
## What is the expected behavior?

play music by style or title.
## What behavior are you observing?

everything is working. except amazon music. the radio works.
## Tell us about your environment:

Windows 8.1, msys32
### What version of the AVS Device SDK are you using?
      <x.y.z>
not sure
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x ] Other - tell us more:
ESP32-Lerat v.4.3

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x ] Other - tell us more:
windows 8.1  msys32

**Comment by mvelegon-amzn** [comment]
Hi @Yeremiy thanks for reaching out. 

Amazon music is not enabled by default on AVS SDK devices. 

Access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

**Comment by Yeremiy** [comment]
Ok. Senks
