### ISSUE TITLE
Audio Volume Control

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#143]
Hi AVS Team,

How do we control device audio volume & media player audio volume?
We can't find any function call in avs-device-sdk source.

Many Thanks

**Comment by scotthea-amazon** [comment]
Hello aki29,

Unfortunately, the [avs-device-sdk](https://github.com/alexa/avs-device-sdk) does not yet include a [CapabilityAgent](https://github.com/alexa/avs-device-sdk/tree/master/CapabilityAgents) to handle directives for the [SpeakerInterface](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speaker).  That feature will be added in an upcoming release.

Thanks,
-SWH

**Comment by aki29** [comment]
thanks for your reply
