### ISSUE TITLE
libcrypto not found

### ISSUE THREAD

**Issue by AdityaGovardhan** [alexa/avs-device-sdk#1431]
While trying to build avs sdk on Ubuntu Linux, libcrypto couldn't be linked because openssl itself was not sufficient. I had to install libssl-dev for the same. I am not sure if this is an issue but wanted to bring it to notice. I used this for reference: https://stackoverflow.com/questions/13811889/cannot-find-libcrypto-in-ubuntu

**Comment by dhpp** [comment]
Thanks @AdityaGovardhan for bringing this to our attention.  We do list our dependencies [here](https://github.com/alexa/avs-device-sdk/wiki/Dependencies#libraries), just fyi, but appreciate setup on different platforms may vary.

**Comment by sniperman23** [comment]
Adding for people who have future problems with this. Having the depencies out of the box will not ensure the setup for AVS will work. I had the same issue while running "cmake".
Error:
--   No package 'libcrypto' found. 

I'm on Mac, and I have openssl which is their equivalent for libssl-dev. To fix this issue I had to use this: https://github.com/scipr-lab/libsnark/issues/99#issuecomment-367677834

**Comment by AdityaGovardhan** [comment]
> Adding for people who have future problems with this. Having the depencies out of the box will not ensure the setup for AVS will work. I had the same issue while running "cmake".
> Error:
> -- No package 'libcrypto' found.
> 
> I'm on Mac, and I have openssl which is their equivalent for libssl-dev. To fix this issue I had to use this: [scipr-lab/libsnark#99 (comment)](https://github.com/scipr-lab/libsnark/issues/99#issuecomment-367677834)

The cleaner solution I found after checking the dependency tree was installing libcurl3 and libssl-dev separately instead of libcurl4-openssl-dev

**Comment by AdityaGovardhan** [comment]
After checking debian packages [here](https://packages.debian.org/stretch/libcurl4-openssl-dev), you can see that libssl-dev is not required but suggested. So libcurl4-openssl-dev provides curl.h and libssl-dev provides libcrypto.h. Thus the appropriate command would be `sudo apt install libcurl4-openssl-dev libssl-dev`

**Comment by az2022** [comment]
@dhpp 
With later releases of AVS-SDK the libssl needs to be installed on Pi3 platforms and appears to be  missing from the dependency list.  Seems like I didn't have to do this with v1.7.1, but after upgrading to v1.13, it started throwing errors:

`Creating the build directory for the PlaylistParser with build type: RELEASE
Creating PlaylistParser with keyword detector type: Sensory
Bluetooth implementation not supported
-- Checking for module 'libcrypto'
--   No package 'libcrypto' found
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  PlaylistParser/src/CMakeLists.txt:2 (pkg_check_modules)`


Also, seems like after libssl-dev is installed you get a warning:

`[ 98%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/SampleEqualizerModeController.cpp.o
[ 98%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/main.cpp.o
[ 98%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o
[100%] Linking CXX executable SampleApp
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libcrypto.so.1.1
[100%] Built target SampleApp`

Installing 'libssl1.0-dev' makes the warning go away but I do not know if it's ok do this?
