### ISSUE TITLE
Audible  is playing from wrong time stamp

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1436]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:-->
When we are asking Alexa to play a book from audible,it starts streaming the recently read book and then after a while if we pause it and then resume, it will read from wrong time stamp i.e., it will go 15-20 secs behind and starts playing.

## What is the expected behavior?
Alexa should read the book from audible from  the timestamp that it is stopped.

## What behavior are you observing?
Alexa starts reading the book 15-20 secs behind

## Provide the steps to reproduce the issue, if applicable:

    Ask to play Audible ("Alexa, play Audible")
    Stop playing ("Alexa, stop")
    Resume playing ("Alexa, resume Audible")
    Check playing position

## Tell us about your environment:
AVS SDK version 1.12.0 

### Tell us what hardware you're using:
SDM450

### Tell us about your OS (Type & version):
Android P

**Comment by dipalisb** [comment]
Logcat_file
[audible_avs_play_resume.txt](https://github.com/alexa/avs-device-sdk/files/3411399/audible_avs_play_resume.txt)

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

I was able to reproduce your experience locally.  It appears that Alexa Service is sending an AudioPlayer.Play directive with an offset from well before the offset provided by the AudioPlayer PlaybackPaused and PlaybackStopped events sent to AVS when audible playback is paused.  We are investigating the source of this discrepancy.

That you for bringing this to our attention!
-SWH

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

I have heard back from the Audible service team, and they indicate that this 15 second rewind is intentional.

I am closing this issue as the behavior is as expected/designed.  Please feel free to re-open this issue if it has been closed in error.

Thank you again,
-SWH
