### ISSUE TITLE
Creating led indicators to go off when "Alexa" is triggered

### ISSUE THREAD

**Issue by Garretto123** [alexa/avs-device-sdk#1439]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 Its not as much an issue as just trying to figure out how to wire 2 led strips to light up when Alexa is triggered.

## What is the expected behavior?

When I say Alexa, the blue lights will light up
## What behavior are you observing?

I am not sure how to program the pins or whatever I have to do.
## Provide the steps to reproduce the issue, if applicable:

I am actually looking at the tutorials for AVS however, that applies to just 2 small leds where I want a whole strip to light up.
### What version of the AVS Device SDK are you using?
      <x.y.z>
Im not sure about my version of AVS but I downloaded it last week, so the latest.
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:
I am using a Raspberry Pi 3+B

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Raspbian Stretch

**Comment by womw** [comment]
Hello, thanks for posting.

Unfortunately we do not offer any support in regards to wiring leds or driving led strips using a Raspberry Pi.

**Comment by celinval** [comment]
Hi @Garretto123, I'm closing this issue since it seems to be out of the scope of the SDK. Please do not hesitate to contact us if you require more information regarding the usage of the SDK or any problems you might find in the future.

Thanks!
