### ISSUE TITLE
Failed to read config file On Android Device

### ISSUE THREAD

**Issue by ajinkyaw** [alexa/avs-device-sdk#1440]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am trying to run AVS on android mobile, but facing an error.
the error is :

>  type=1400 audit(0.0:38): avc: denied { search } for name="alexaSDK" dev="mmcblk0p7" ino=212032 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=dir permissive=0
> Failed to read config file /data/data/com.myapp.avs/alexaSDK/AlexaClientSDKConfig.json
> Failed to create to SampleApplication!

## What is the expected behavior?
Avs should run.

## What behavior are you observing?
1. The file AlexaClientSDKConfig exists on the path and its contents are also correct.
2. AlexaClientSDKConfig file and  /data/data/com.myapp.avs/alexaSDK folder has open access (permission to read and write), not restricted for any user.
3. I have tried running on emulator and its running smoothly. 

## Provide the steps to reproduce the issue, if applicable:
I am trying to run avs from android app using JNI. The location where i am installing the avs sdk is, **/data/data/com.myapp.avs** this is the folder of my android app. I have kept avs sdk files in 
**/data/data/com.myapp.avs/alexaSDK**.

## Tell us about your environment:
Android 24.
### What version of the AVS Device SDK are you using?
Latest One.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hello @ajinkyaw thanks for posting.

For android API Levels 23+ you need to require runtime permissions in addition to having read write access.

https://developer.android.com/training/permissions/requesting.html

**Comment by ajinkyaw** [comment]
@womw : i have given all the permissions on runtime , one more thing i wanted to report that this error was resolved by using **adb shell setenfoce 0** command.

**Comment by womw** [comment]
OK, if this has resolved your issue then I will be closing here, feel free to reopen or open a new issue if problems still occur.
