### ISSUE TITLE
How to play spotify on avs device

### ISSUE THREAD

**Issue by Vaishnavikumara** [alexa/avs-device-sdk#1444]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hi @Vaishnavikumara thanks for posting.

Access to Spotify is currently restricted to select devices. Please contact your Amazon Business Development Representative to get started on the approval for Spotify.

Closing this issue as resolved. Feel free to reopen or post a new issue.
