### ISSUE TITLE
How can I change the language of the Sample App?

### ISSUE THREAD

**Issue by jjanggoon** [alexa/avs-device-sdk#1446]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How can I change the language of the Sample App? I can't find the language option on the every where.
I looked it up in the following way, but there is no Language option.
- In the Alexa app on my phone navigate to Settings --> Device Settings --> My Sample Device
- In the alexa.amazon.com on browser navigate to Settings --> Devices --> My Sample Device

I know how to change the language via the 'c' command.
I want I can choose the language from the web page.

## What is the expected behavior?

alexa.amazon.com settings page should have a language option.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @jjanggoon,

The SDK currently does not support changing the Locale through the Companion App (Web or Mobile App).
