### ISSUE TITLE
Load language-model cpp  file during run time  (using KWD_AmazonLite as keyword detector)

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1449]
Hi all,
I have an issue regarding the loading of the particular model's cpp file based on the language selected. I'm using AmazonLite Keyword detector.
Issue Description:
Whenever we press 'c' in the terminal, settings option should be printed on the console (like the snippet attached   : lang_settings.png). This actually will set the locale but not the model. I have a task where I have to change the language by changing both the locale & model cpp file path.
i.e If my locale gets changed from english : en-Us to Japanese : ja-JP language, the locale will be changed by avs-sdk. Now I need to change the pathTo model file also, but it should be done dynamically.
 I've tried the following procedure:
Path:avs-device-sdk/SampleApp/src/UIManager.cpp
In UIManager::onSettingChanged, I have a set a flag value. whenever my language gets changed, the flag will also gets changes by 1& 0 for Japanese & English language respectively. I have attached the code snippet below:  
```
void UIManager::onSettingChanged(const std::string& key, const std::string& value) {
    m_executor.submit([key, value]() {
        std::string msg = key + " set to " + value;
        ConsolePrinter::prettyPrint(msg);
         if(value == "en-US")
                language_flag=0;
         else if(value == "ja-Jp")
                language_flag=1;
        ConsolePrinter::prettyPrint("Language flag changed");
    });
}

```
Later, whenever the flag gets changed, I tried changing the modelpath based on the selected flag in the file path: avs-device-sdk/KWD/KWDProvider/src/KeywordDetectorProvider.cpp. The code in the mentioned path is as follows:
```
#elif defined(KWD_AMAZONLITE)
    std::string modelPath;
    alexaClientSDK::avsCommon::utils::configuration::ConfigurationNode::getRoot()[std::string("sampleApp")].getString(
        "PryonLiteModelPath", &modelPath);
        if (language_flag == 0)
        modelPath="/product/avs/model/D.en-US.alexa.cpp";
        else if (language_flag == 1)
        modelPath="/product/avs/model/D.ja-JP.alexa.cpp";
I've printed the model path value after the return statement :
 return alexaClientSDK::kwd::PryonLiteKeywordDetector::create(
               stream, audioFormat, keyWordObservers, keyWordDetectorStateObservers, modelPath);
```
Modelpath is getting changed as per logs but the the cpp model file is not getting loaded & the app is not getting started  with this procedure. i.e after Authorized state , It's not going to Idle & Listening states.
Please let me know the path/ point of changing the model path and also how can I resolve this issue.
Thanks in advance.
![lang_settings](https://user-images.githubusercontent.com/52921278/62189885-c4801600-b38d-11e9-9ba8-6070acd3efbe.png)

**Comment by kjkh** [comment]
Hi @dipalisb,

Contact us privately [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) to have your issue further investigated.
