### ISSUE TITLE
Support of external DSP wakeWord detection

### ISSUE THREAD

**Issue by wchradiodev** [alexa/avs-device-sdk#145]
Where is the support of the external dsp wakeword detection via GPIO such as in the old sample app?

**Comment by sanjayrd** [comment]
Hi @wchradiodev,

Our SDK doesn't come with support for external wake word detection via GPIO directly; however, we do have hooks in place for any customer to hook up their own wake word engine by simply notifying the `KeywordObserverInterface` class. We will investigate adding support for this in the future.

Best,
Sanjay

**Comment by sanjayrd** [comment]
Also, if this is only for a push-to-talk style of Alexa interaction, i.e. pushing the pin to get the device to start listening, you can just see how the SampleApp does this as well. It's a matter of notifying the `AudioInputProcessor` anytime an interaction is begun. So, you could hook up the GPIO pins to make calls to this class.
