### ISSUE TITLE
Failed to create to SampleApplication!

### ISSUE THREAD

**Issue by TaoGegithub** [alexa/avs-device-sdk#1454]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
2019-08-05 06:54:03.187 [  1] I sdkVersion: 1.14.0
configFile ./Integration/AlexaClientSDKConfig.json
2019-08-05 06:54:03.236 [  1] C SampleApplication:Creation of AuthDelegate failed!
2019-08-05 06:54:03.237 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

## What is the expected behavior?
Wait for the sample app to display a message like this:
##################################
#       NOT YET AUTHORIZED       #
##################################
################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
################################################################################################

## What behavior are you observing?
Sample app can not start

## Provide the steps to reproduce the issue, if applicable:
I am operating according to this guidance document: [Ubuntu Linux Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide)

Every step I follow is in accordance with the guidance document.

I uploaded the logs to help you find out where the problem lies.
[CMakeError.log](https://github.com/alexa/avs-device-sdk/files/3466383/CMakeError.log)
[CMakeOutput.log](https://github.com/alexa/avs-device-sdk/files/3466384/CMakeOutput.log)
 

## Tell us about your environment:
Ubuntu 18.04 LTS
### What version of the AVS Device SDK are you using?
      <1.14.0>

### Tell us what hardware you're using:
- [ yes ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ yes ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @TaoGegithub,

From the error logs, it looks like CMake is unable to locate pthread. While it should be installed, can you double check and try `sudo apt-get install libpthread-stubs0-dev`?

**Comment by TaoGegithub** [comment]
> Hi @TaoGegithub,
> 
> From the error logs, it looks like CMake is unable to locate pthread. While it should be installed, can you double check and try `sudo apt-get install libpthread-stubs0-dev`?

**Comment by TaoGegithub** [comment]
Hello @kjkh ,

As you said, i confirmed it again. Run the bash command 'sudo apt-get install libpthread-stubs0-dev', it showed the following information: 

_Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpthread-stubs0-dev is already the newest version (0.3-4).
libpthread-stubs0-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded._
