### ISSUE TITLE
Problems creating cmake for Wake word detector for Ubuntu 18.04 

### ISSUE THREAD

**Issue by MaximusPrime123** [alexa/avs-device-sdk#1455]
Need help with the cmake command for the Wake word detector

I am trying to install the Alexa AVS-device-SDK on a NanoPC-T4 run FRIENDLYELEC's version of Ubuntu 18.04.  I can successfully install the software without a Wake word detector, but I can not get the cmake command to work if I try to build with WWD.  I am following the instructions from the following website for this build:

https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

## Briefly summarize your issue:
I will state my issue while keeping with file structure used in this guide, where the software was downloaded the $HOME/my_project/source.  Using this as my source directory my cmake command is as follows:

cmake $HOME/my_project/source/avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include \
-DCMAKE_BUILD_TYPE=DEBUG \
-DBLUETOOTH_BLUEZ=ON \
-DAMAZON_KEY_WORD_DETECTOR=ON \
-DAMAZON_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/my_project/source/avs-device-sdk/KWD/KWDProvider/include \
-DAMAZON_KEY_WORD_DETECTOR_LIB_PATH=$HOME/my_project/source/avs-device-sdk/KWD/KWDProvider/src/libKeywordDetectorProvider.so

Like I said above, the cmake command works just fine if I leave off the Key Word Detector.  Could you please tell me what is wrong with it?

I have also tried replacing it with the following one for SENSORY:
-DSENSORY_KEY_WORD_DETECTOR=ON \
-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/my_project/source/avs-device-sdk/KWD/Sensory/include \
-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=$HOME/my_project/source/avs-device-sdk/KWD/Sensory/lib/libthf.a

However, I could not get this to work either.  From the website that I was using I could build the Alexa AVS-device-SDK just by copying and pasting the commands, because it was so straight forward.  However, didn't include help for the wake word detector.  I really could find any good Linux (Ubuntu) help on the internet.  I couldn't find any help at all for the AMAZON Key Word Detector on the internet.  I found it looking through the Alexa code.

I would really like to use the Amazon Key Word Detector if possible instead of KattAI or SENSORY.  However, it would be really great if you could provide me with the cmake command for all of the available Key Word Detectors using the path format used in the Ubuntu Linux Quick Start Guide.  I really wish I know who to contact to get them to include that information at the end of their guide.  I am hoping that they will see this post and update their guide so others don't have the problems I have been struggling with.

## What is the expected behavior?
I would like to know what I am doing wrong with my cmake command so that my make will build successfully.

## What behavior are you observing?
When I run my cmake command, it ends with Configuring incomplete, errors occurred!  

## Provide the steps to reproduce the issue, if applicable:
On a Ubuntu or Linux system, follow the guide at this website:

https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

When you get to the part were you build the SDK, replace the guide's cmake command with my cmake command listed above.  As a test, you can follow this guide until you get to the cmake command and use my cmake command, but leave off the Wake Word Detector.  The cmake command should work like it should.  If you then run "make", you should not get any errors.  It only has problems with the Wake Word Detector lines.

## Tell us about your environment:
I using a NanoPC-T4 from FRIENDLYELEC.  I am running their version of Ubuntu 18.04.  I have updated all of the software and installed required third-party software.  Not just the third-party software listed in the guide from the website above, but from every other guide I could find for installing this software.  For the mic I am using a PS3 eye (camera), and for the speakers, I am using computer speakers plugged into the analog line out.  I have setup and configured the mic and speakers correctly, and verified that they work as expected.  

### What version of the AVS Device SDK are you using?
I am using the latest version from the following website:

https://github.com/alexa/avs-device-sdk.git

It looks like it is either Version 1.13 or 1.14.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X ] Other - tell us more:
NanoPC-T4
Here is a link to the website.  It has all the specs for the board.
 https://www.friendlyarm.com/index.php?route=product/product&product_id=225

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ X] Other - tell us more:
I am using the board manufacture's version of Ubuntu 18.04.  As far as I can tell, it is regular Ubuntu 18.04, but their Package Manager has different repositories.  I had to add repositories to be able to download some of the third-party software.

**Comment by kjkh** [comment]
Hi @MaximusPrime123,

You will want to use either `SENSORY_KEY_WORD_DETECTOR` or `KITTAI_KEY_WORD_DETECTOR` to enable that respective wakeword engine.

Please follow this link on how to enable them: https://github.com/alexa/avs-device-sdk/wiki/cmake-parameters#Wake-word-detector.

The library and directory paths that you need to include are not the ones in the source directory. They should be the respective third party (Kitt.AI or Sensory) headers and libraries. For example:

Kitt.AI
```
-DKITTAI_KEY_WORD_DETECTOR=ON \
-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=<KITT_AI_DIR>/snowboy/lib/ubuntu64/libsnowboy-detect.a \
-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=<KITT_AI_DIR>/snowboy/include
```

Sensory (Raspberry Pi example)
```
-DSENSORY_KEY_WORD_DETECTOR=ON \
-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=<SENSORY_DIR>/alexa-rpi/lib/libsnsr.a \
-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=<SENSORY_DIR>/alexa-rpi/include
```

**Comment by MaximusPrime123** [comment]
Thank you.  I was able to get it working with KITTAI.
