### ISSUE TITLE
Run Sample App on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by simocn77** [alexa/avs-device-sdk#1456]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have followed the "macOS Quick Start Guide"
cmake : ok
build : ok
jason cfg : ok
run sample app : ko

## What behavior are you observing?

dyld: Symbol not found: __ZTINSt3__112bad_weak_ptrE
  Referenced from: /Users/simocn/wip/sources/avs/avs_build/./SampleApp/src/SampleApp
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
 in /Users/simocn/wip/sources/avs/avs_build/./SampleApp/src/SampleApp
./build_mac.sh: line 58: 28493 Abort trap: 6           ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json## What is the expected behavior?
### What version of the AVS Device SDK are you using?
 
avs-device-sdk  <1.14>
macOS 10.14.6

### Tell us what hardware you're using:
- [ x ] Laptop

### Tell us about your OS (Type & version):
- [X] MacOS

**Comment by simocn77** [comment]
I find this solution.. is it ok ?

diff --git a/SampleApp/src/CMakeLists.txt b/SampleApp/src/CMakeLists.txt
index 61ab2f03e..2e3543473 100644
--- a/SampleApp/src/CMakeLists.txt
+++ b/SampleApp/src/CMakeLists.txt
@@ -73,7 +73,8 @@ endif()
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
     target_link_libraries(SampleApp
-        "-framework CoreAudio" 
+        "-framework CoreAudio"
+       "-lc++"
         "-framework AudioToolbox" 
         "-framework AudioUnit" 
         "-framework CoreServices"

**Comment by scotthea-amazon** [comment]
Hello @simocn77,

Thank you for providing your solution!

Since the problem appears to be resolved, I will close this issue.  If you think it has been closed in error, please feel free to re-open it.

Best regards
-SWH
