### ISSUE TITLE
Strange initializzation audio problem

### ISSUE THREAD

**Issue by misk0** [alexa/avs-device-sdk#1461]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Ok I'm trying to resolve this almost a week and I don't have any more ideas. 
So, I'm installing Alexa on Raspberry Pi 3B with SD card 16GB, usb microphone and HDMI monitor with speakers. 
I installed Raspbian scretch and I followed instruction from Amazon Developers site. Everything went well but I can not start it. 
Here you can see the log:  https://pastebin.com/fBGKUhLb

Obviouselly there is problem with PortAudio but I can't solve it. 

##I tried:
1. create .asoundrc and setup correctly speaker and microphone:
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
        rate 16000
    }
}

pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:0,1"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}

Commands like rec, aplay, arecord works correctly. I'm able to record sound and to play same wav to the speaker.  Still doesn't work

pi@aleksa:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

pi@aleksa:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

2. I changed another USB microphone, one is standard PnP another is AK171 or something. No luck

3. I changed RPi with same HW setup. No luck.

4. I connected headphones to 3.5mm jack and routed sound to them. No luck!

5. I used this command: env PA_ALSA_PLUGHW=2 sudo /home/pi/Assistants-Pi/Alexa/startsample.sh. Still no luck.

6. I tried to use Assistents-PI installation but result is the same. 

Something is wrong with PortAudio, even their examples have the same / similar error. 

I'm clueless and I don't have any more ideas what can I do. Feeling pretty desperate.. Please help

## What is the expected behavior?
SampleApp should start normally

## What behavior are you observing?
SampleApp won't start

## Provide the steps to reproduce the issue, if applicable:
sudo /home/pi/Assistants-Pi/Alexa/startsample.sh

### What version of the AVS Device SDK are you using?
I sdkVersion: 1.9.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**Comment by scotthea-amazon** [comment]
Hello @misk0,

This sounds very much like the problem reported here: https://github.com/alexa/avs-device-sdk/issues/1359.  Some people at the end of that thread are reporting success by installing an older version of Raspbian.

Best regards,
-SWH

**Comment by misk0** [comment]
Hi @scotthea-amazon 
thank you for your answer. I resolved my problem with THIRD microphone. I used old Logitech webcam with microphone integrated and it started to work without any problems.
Previous two microphones are: https://www.amazon.co.uk/Adafruit-Mini-USB-Microphone-ADA3367/dp/B071YMZQP1 from unknown producer 
This identifies itself as PnP Device

and
https://www.amazon.co.uk/dp/B076M4HXFH/ref=psdc_430594031_t3_B071YMZQP1 with same unkown producer.
This identifies as AK5731.

Problem is that both of them worked with RPi (arecord and aplay) and worked on Windows too.

I don't know at the end why they don't work with AVS but I solved my problem in this way.

**Comment by scotthea-amazon** [comment]
Hi @misk0,

I am very glad to hear you have found a way to make things work. Thank you for providing those details!

I am closing this issue since it appears to have bee resolved.  Please feel free to re-open it if you think it has been closed in error.

Thanks again!
-SWH
