### ISSUE TITLE
Alexa Build Error on Rapsberry pi 3 Buster

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1464]
I am trying to build Alexa on Raspberry pi using this Instructions: https://developer.amazon.com/docs/alexa-voice-service/build-the-avs-device-sdk.html

At start it was giving me this Error : Error : Installing Alexa : libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2q-2 is to be installed

For this I removed libssl1.0-dev from pi.sh and then run above setup. It is giving me this Error :
Before running I have installed libssl1.0-dev sparately.

```
[ 0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o

[ 0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlEasyHandleWrapper.cpp.o

/home/pi/avs-device-sdk/AVSCommon/AVS/src/AlexaClientSDKInit.cpp:16:10: fatal error: curl/curl.h: No such file or directory

#include <curl/curl.h>

^~~~~~~~~~~~~

compilation terminated.

make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:141: AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o] Error 1

make[3]: *** Waiting for unfinished jobs....

In file included from /home/pi/avs-device-sdk/AVSCommon/Utils/src/LibcurlUtils/CurlEasyHandleWrapper.cpp:20:

/home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/LibcurlUtils/CurlEasyHandleWrapper.h:20:10: fatal error: curl/curl.h: No such file or directory

#include <curl/curl.h>

^~~~~~~~~~~~~

compilation terminated.

make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:518: AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/LibcurlUtils/CurlEasyHandleWrapper.cpp.o] Error 1

make[2]: *** [CMakeFiles/Makefile2:1519: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2

make[1]: *** [CMakeFiles/Makefile2:10239: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2

make: *** [Makefile:2580: SampleApp] Error 2
```
Please Tell me how to solve this Error.

**Comment by scotthea-amazon** [comment]
Hello @rajdpandey,

Please note that we do not yet support the AVS Device SDK for Raspbian Buster (the latest supported version is Stretch).

From the error message you provided it sounds like the build can not find libcurl.

I would have expected that script to re-install libcurl if it was uninstalled.  Have you verified that libcurl4-openssl-dev was installed by setup.sh (e.g., by running:  apt list libcurl4-openssl-dev )?  You might try installing (or re-installing) libcurl4-openssl-dev directly with apt-get rather than via tsetup.sh.

It may also be that the changes to your environment have confused cmake.  You could try wiping out the build directory and re-running setup.sh.

Best regards,
-SWH

**Comment by rajdpandey** [comment]
Yeah, It ran when I installed it on Raspbian Stretch. So for running full Alexa on the raspberry pi is this: https://developer.amazon.com/docs/alexa-voice-service/build-the-avs-device-sdk.html guide is proper? I am thinking of making it a commercial product. I am having doubt because it says only sample app and when I tried step-by-step instructions the avs-device-SDK was of almost 3GB which wasn't in this instruction. Please Guide me.

**Comment by kclchan** [comment]
Hi @rajdpandey, please note that you will only need the executable and the associated shared libraries and dependencies on the commercial product to run the application.

As for your questions regarding a custom conversation, you may refer to #721 for more information.  Thanks!

**Comment by rajdpandey** [comment]
@kclchan Hi, I saw #721 but there also nobody answered how to control GPIO through custom skills and the owner of that issue has not provided solution also. There is another question Let's say I create a flask-ask server on raspberry pi (local server) and want to add it to HTTP (Endpoint in Alexa skill) will it work? 

I have created a sample but using flask, serveo.net, and Alexa skill. There are two major problems here.

1] Serveo.net changes public url every time on restart and stops after some time. There is no option for static URL.

2] I want to say simple "Alexa, turn on the red light" and make it work. but if I simply say that then it says no smart home device found etc.

I have set Invocation to turn so I thought if I say "Alexa, turn red light on" it will do but it has specified I have to say like "Alexa, ask or tell turn turn red light on" which is not good. So if you have any insight on this please help.

**Comment by kclchan** [comment]
Hi @rajdpandey, for questions related to skill, you will be able to get a better answer from the [skill forum](https://forums.developer.amazon.com/topics/alexa+skills+kit.html).

**Comment by rajdpandey** [comment]
@kclchan  I have already posted there.

**Comment by kclchan** [comment]
Closing this issue now since the question is posted on the forum.
