### ISSUE TITLE
Cross compiling SDK for raspberry pi using Visual studio 2015 or 2017

### ISSUE THREAD

**Issue by az2022** [alexa/avs-device-sdk#147]
I have a raspberry pi3 running raspbian stretch. I was able to compile the SDK right on the raspberry pi but  am having trouble using Visual studio to x-compile sdk from Windows environment. I would like to continue development from Windows environment if possible. Are there any steps I could try to get this working either in Visual studio 2015 or 2017?

**Comment by sanjayrd** [comment]
Hi @az2022,

Unfortunately, we've only tried cross-compiling on Linux for Raspberry Pi. We haven't tried cross compiling from a Windows environment. Is there any specific step that's giving you trouble?

Thanks,
Sanjay
