### ISSUE TITLE
Alexa does not catch (respond to) any queries

### ISSUE THREAD

**Issue by Tonny0125** [alexa/avs-device-sdk#1477]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After following the instruction of https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide
I executed “./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9”.
It started working, but Alexa never catch my queries such as “Alexa, what's the weather like?” or “Alexa, what time is it?”
even after “t+Enter” (followed by my query without saying "Alexa”).
I have confirmed that my microphone and speaker are working by “arecord -f cd -Dhw:1 | aplay -Dhw:1”.
I could hear my voice through earphone.

## What is the expected behavior?

Alexa catch my query, and shows on the screen
###########################
#       Speaking...       #
###########################
after
###########################
#       Thinking...       #
###########################

## What behavior are you observing?

“Speaking…” was never showed even after “t+Enter” communication.
The log showed as follows:

ubuntu@ubiquityrobot:~/my_project/build$ ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
2019-08-24 11:42:33.653 [  1] I sdkVersion: 1.14.0
configFile ./Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2019-08-24 11:42:33.658 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2019-08-24 11:42:33.658 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2019-08-24 11:42:34.072 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2019-08-24 11:42:34.072 [  1] I Setting:handleSetValue:value=false
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:968:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib pcm_dmix.c:968:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
###########################
#       Authorized!       #
###########################

ALSA lib pcm_dsnoop.c:545:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.14.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Reauthorize device:                                                        |
|       Press 'z' followed by Enter at any time to re-authorize your device. |
|       This will erase any data stored in the device and initiate           |
|       re-authorization.                                                    |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

t
############################
#       Listening...       #
############################

2019-08-24 11:42:41.932 [  9] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2019-08-24 11:42:41.934 [  9] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=ffb8d2a3-01a8-4d18-a1b8-943c1b041dc0
2019-08-24 11:42:47.502 [  5] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"eff1fba0-dc68-44c5-ac51-bf196cc19a66"\,dialogRequestId\:"ffb8d2a3-01a8-4d18-a1b8-943c1b041dc0"}
2019-08-24 11:42:47.502 [ 1b] I DirectiveRouter:preHandleDirective:messageId=eff1fba0-dc68-44c5-ac51-bf196cc19a66,action=calling
2019-08-24 11:42:47.503 [ 1c] I DirectiveRouter:handleDirective:messageId=eff1fba0-dc68-44c5-ac51-bf196cc19a66,action=calling
###########################
#       Thinking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

q
#####################################
#       Client not connected!       #
#####################################

2019-08-24 11:42:56.337 [ 1d] I LibcurlHTTP2Connection:cancelStream:streamId=AVSDownChannel-1
2019-08-24 11:42:56.406 [  1] E SettingManager:removeObserverFailed:reason=invalidSetting,settingIndex=0

## Provide the steps to reproduce the issue, if applicable:

I followed the instruction of https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide
except for the “Include Bluetooth (optional)” part.

### What version of the AVS Device SDK are you using?
HW : Raspberry Pi 3 Model B+ Rev1.3
Microphone : ReSpeaker 2-Mics Pi HAT
Speaker : Earphone connected the jack on ReSpeaker
OS : ubuntu 16.04.6 LTS

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Tonny0125** [comment]
I missed to write:
What version of the AVS Device SDK are you using?
-> SDK 1.14.0

**Comment by kjkh** [comment]
Hi @Tonny0125,

From the logs you have posted, the SDK is not connected to AVS. We will require further logging information to debug the issue.

In order to enable DEBUG9 logs, you must rebuild the SDK in DEBUG mode: https://github.com/alexa/avs-device-sdk/wiki/Build-Options#build-types

Can you do so and attach new logs?

**Comment by Tonny0125** [comment]
Hello @kjkh

Thank you for your reply.
I have reexecuted the process from the beginning with DEBUG mode and taken the log.
The log is uploaded at the below:
https://github.com/Tonny0125/AVS_SDK_Log

I did " t + Enter" once, still "speaking state" did not appear.

Thank you.

**Comment by celinval** [comment]
Hi @Tonny0125, are you able to record / play without using the `-Dhw:1` argument?

**Comment by Tonny0125** [comment]
Hello, @celinval , do you suggest me to try "record -f cd | aplay" without "-Dhw:1"?
Then, it does not work.

What does this result suggest?

**Comment by ereich1217** [comment]
This means your .asoundrc is missing or not configured correctly.  When you don't specify -Dhw:1 arecord/aplay use the default specified in .asoundrc.  AVS also uses the default devices specified in .asoundrc.

**Comment by Tonny0125** [comment]
Hello, @ereich1217 , @celinval 

Thank you for your advice.
I modify some files, still even aplay without "-Dhw:1" is not working.
It seems that only the default of pcm has not been superseded.
While it might be out of scope of this thread, it would be very helpful if you could give some more advice whether there is anything I am missing.

What I did and the issue are below:

[What I did]
I made .asoundrc and specified the following:
-----------
pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw           
        card 1
}
--------

Also, I modified /usr/share/alsa/alsa.conf to specify
-------
defaults.ctl.card 1
defaults.pcm.card 1
-------

[Issue]
Recording data could not be played with "aplay -D default (file name)."
I still need to add -Dhw:1 to play.

On the other hand, the default of alsamixer has been changed to card1 correctly.
Also, I could make an alias on .asoundrc properly.
-> These results indicate that .asoundrc is working.

So, it seems that only the default of pcm has not been superseded. <- This should be the problem.

Thank you in advance.

**Comment by Tonny0125** [comment]
Some sentences become unintentionally bold..

**Comment by Tonny0125** [comment]
Hello, @ereich1217 , @celinval , all

I could change the default setting by GUI, and now `arecord -f cd | aplay` is working without `-Dhw:1`.

Then, I tried `./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9` again.
But, I could not hear anything from Alexa.
The log file is [https://github.com/Tonny0125/AVS_SDK_Log/blob/master/log4.txt](url)

**[What I did]**

After entering t+Enter, I said "Alexa, what is the weather like?"

Alexa seems gathering information as to weather in my region.
And, alexa entered speaking state.

But, I could not hear anything.

What I could find in the log is a comment of "InProcessAttachmentReader:readFailed:reason=SDS is closed" at the end of the log.

**Comment by ereich1217** [comment]
I just re-read the instructions you said you followed.  The link you posted is for Ubuntu linux, not the raspberry pi.

Have you tried following the instructions for the raspberry pi:
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

It configures everything in the system for you including the .asoundrc files.
It also provides you with Sensory KWD.

The only catch is that you need to use stretch, not buster for your raspbian version.

**Comment by Tonny0125** [comment]
Hello, @ereich1217 , all

I re-installed raspbian stretch and build avs sdk according to [https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide](url).

Also, I modified MediaPlayer.cpp according to "no audio output from the SDK" of [https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide](url).

Finally, I can hear alexa's answer!!

Thank you very much for your kind support.

**Comment by scotthea-amazon** [comment]
Hello @Tonny0125 

I am closing this issue since it appears that the problem has been resolved.  Please feel free to re-open it if I have closed it in error.

Best regards,
-SWH
