### ISSUE TITLE
On being asked as "Who are you" ,Alexa is giving response like "Alexa is me" 

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1480]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
On being asked as "Who are you" ,Alexa is giving response like "Alexa is me" 
## Briefly summarize your issue:

In echo the answer is "I am Alexa..." where as in my case it is "Alexa is me ..."
## What is the expected behavior?

It should give response like "I am Alexa ..."
## What behavior are you observing?

It is giving response like "Alexa is me.."
## Provide the steps to reproduce the issue, if applicable:

Ask," Alexa, who are you?"

### What version of the AVS Device SDK are you using?
      AVS-1.12

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Android Pie 

### Tell us about your OS (Type & version):
- [ ~] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @dipalisb,

Thanks for bringing this to our attention. This is not an issue related to the SDK, as these responses are not generated here. If you have further questions, please reach out to the AVS teams via the forums: https://forums.developer.amazon.com/spaces/38/Alexa+Voice+Service.html.
