### ISSUE TITLE
TrulyHandsfree binaries license key has expired

### ISSUE THREAD

**Issue by saxonyfrank** [alexa/avs-device-sdk#1484]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When trying to execute "startsample.sh", it starts and gives the "Alexa is currently idle" message. Unfortunately there is noch reaction on the spoken keyword "Alexa".
But everything was fine for the last 8 days. I installed the AVS Device SDK on my Raspberry Pi 4 on 20 Aug 2019, removed "libssl1.0-dev" from "pi.sh" and added "set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")" in "/avs-device-sdk/SampleApp/CMakeLists.txt" to avoid undefined reference to `__atomic_store_8'. As recommended to get working the stuff on the Raspberry Pi 4 platform. And it worked perfectly.

For better understanding. Typing 't' instead of speaking "Alexa" during "Alexa is currently in idle state!", invokes "Listening...". After that the answer on my questions comes immediately.

## What is the expected behavior?
After starting "startsample.sh" the spoken keyword "Alexa" should be recognized during the "Alexa is currently idle!" state.

## What behavior are you observing?
And yes, everything worked without any problem until 27 Aug. Today I recognized the Sensory TrulyHandsfree binaries license key has expired. Executing "./third-party/alexa-rpi/bin/license.sh" ends in the "license expired on 28 Aug 2019 00:00:00 GMT" information.
When I quit "Pull from remote to update key? [yes or no]:" with "yes", "./third-party/alexa-pi/lib/libsnsr.a" is updated after reviewing the license agreement. Unfortunately it ends in "ERROR: license key has expired. Could not apply license key."

## Provide the steps to reproduce the issue, if applicable:
Start "startsample.sh" via "bash startsample.sh".

### What version of the AVS Device SDK are you using?
As I know version 1.14. But I am not sure.

### Tell us what hardware you're using:
Raspberry Pi 4

### Tell us about your OS (Type & version):
Raspbian Buster, based on Debian Buster

**Comment by timbeh** [comment]
The Sensory TrulyHandsfree binaries license key has expired. 
There is currently no solution to this.
#1483 and #1482 are the same issues.

**Comment by timbeh** [comment]
Good news! The issue has been resolved.
I contacted the developer and he has extended the license.
Everything should be working again, you can close this issue now. :)

**Comment by saxonyfrank** [comment]
Thanks a lot! I can confirm the issue is resolved. Applying the license key is no problem furthermore. Everything is working perfectly now.
