### ISSUE TITLE
How can we change WWE of alexa sample app?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1486]
I have built Alexa on raspberry pi by following this guide: https://developer.amazon.com/docs/alexa-voice-service/input-avs-credentials.html

The wake-up engine to detect "Alexa" is this:- Sensory TrulyHandsfree WakeWord Engine

This engine has a problem it provides license for 120 days and then after it expires due to which "Alexa" doesn't listen to "Alexa" wake up word. I want the wake-word engine to be permanent.

So is there a way to change this WWE to kitt-ai or pocketsphinx? or if not then is there any other way to build full Alexa on the raspberry pi in python language? Where I can change the WWE to any other and also if possible its voice to male.

I know I am asking too much but Please help.

**Comment by kjkh** [comment]
Hi @rajdpandey,

The SDK supports KittAi. Please refer to these instructions on enabling it: https://github.com/alexa/avs-device-sdk/wiki/Build-Options#wake-word-detector.

**Comment by rajdpandey** [comment]
@kjkh  Sorry for my stupidity, I am not able to understand the process written in the link you provided. I have never worked with C or C++ I am a Hardware guy. So please can you provide me a guide easier than above one.

This line doesn't say where should I change: Replace <wake-word-name> with SENSORY for Sensory, and KITTAI for KITT.ai.

What detector library or include the library and where can I get it:
_KEY_WORD_DETECTOR_LIB_PATH= The path to the wake word detector library.

_KEY_WORD_DETECTOR_INCLUDE_DIR= The path to the wake word detector include directory.

And where should I put above things? And how to turn on or off WWD?
And below that, there is something about Kitt.ai which I don't understand.

I am not a smart person or a very experienced guy. Can you help me, please?

**Comment by rajdpandey** [comment]
@kclchan Are you there?

**Comment by rajdpandey** [comment]
@samcoult @JamieMeyers @scotthea-amazon @kclchan @kjkh @mvelegon-amzn 

Can someone explain Please?

**Comment by mvelegon-amzn** [comment]
Hi @rajdpandey you will need to use this guide to setup the AVS SDK on pi.

https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#1-install-and-configure-dependencies-for-the-sdk

Before doing the "BUILD the SDK" step you will have to do the following.

1) Get KITT AI libraries and include files:

```
cd /home/pi/sdk-folder/third-party
git clone   https://github.com/Kitt-AI/snowboy
```

2) instead of using the cmake command mentioned which uses SENSORY WWD use this:

```
cd /home/pi/sdk-folder/sdk-build
cmake /home/pi/sdk-folder/sdk-source/avs-device-sdk \
-DKITTAI_KEY_WORD_DETECTOR=ON \
-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/sdk-folder/third-party/snowboy/lib/rpi/libsnowboy-detect.a \
-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/sdk-folder/third-party/snowboy/include \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=/home/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=/home/pi/sdk-folder/third-party/portaudio/include 
```

Hope this helps, let us know if you face further issues.

**Comment by rajdpandey** [comment]
Hi,
I have in /home/pi/avs-device-sdk which contains sample app
I have /home/pi/build which also contains sample app
& have /home/pi/third-party 

So what would be the sdk-folder, sdk-source in this?

**Comment by rajdpandey** [comment]
@mvelegon-amzn

**Comment by rajdpandey** [comment]
No is Answering so closing the Issue
