### ISSUE TITLE
Where and How can I create a function to run UART from C++ Sample App?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1491]
Hi,
@samcoult @JamieMeyers @scotthea-amazon @kclchan @kjkh 
I have built Alexa on raspberry pi by following its guide on developer.amaozon.com.

I have also created a custom skill which turns on and off the TV. Currently, I am running a Flask server to control GPIO so I can UART(RX, TX) between raspberry pi and Arduino UNO. I have port forwarded local flask server IP to serveo.net and using that URL serveo.net's in Endpoint. 
But serveo.net server down's after a couple of hours so I was thinking of another solution.
I have tried ngrok and everything but doesn't satisfy my need.

So I am thinking what if I can do this from Inside of Sample App. Like when I ask Alexa to turn on the TV. The response will be fetched from inside Sample App function which will validate if the response is "ON", "OFF" or "MUTE" then it will send this to Arduino using UART(RX, TX).
But I don't know how to fetch the response and where to create the function and what to use.
I am a Hardware developer and Know little python but C++ just bounces over my head and there is no proper documentation regarding the Functions and Files of Sample App from which I can help myself. 

So if anyone knows how to and where to write and do this in Sample App Please Let me know.
Thanks.

**Comment by mvelegon-amzn** [comment]
Hi @rajdpandey thanks for reaching out. Unfortunately for this specific issue there is no guide that we can provide. 

The SDK is meant to be a base that users build on top off to create applications that serve various use cases. For instance we provide various observer interfaces in the SDK that users can extend with their own implementations : https://alexa.github.io/avs-device-sdk/namespacealexa_client_s_d_k_1_1avs_common_1_1sdk_interfaces.html

You will have to see which of these are the most appropriate for your use case and write custom code to do what you are saying. To interact with a skill the TemplateRuntimeObserverInterface might be a good place to start.

Here is our code documentation: https://alexa.github.io/avs-device-sdk/

I am closing this issue now, please re-open if you have further questions.

**Comment by rajdpandey** [comment]
Hi @mvelegon-amzn ,

Is it permittable to change the codes in Sample Apps or do changes inside? And can you please help me with this issue also if possible: https://github.com/alexa/avs-device-sdk/issues/1486
