### ISSUE TITLE
Wake word engine is getting error with Unable to initialize Pryon detector

### ISSUE THREAD

**Issue by vaibhav2800** [alexa/avs-device-sdk#1492]
## Briefly summarize your issue:
I am using Alexa Auto SDK (since i am not able to find issue filling section of i had to report here),
i am using wake word engine (**AMAZONLITE**). I am compiling auto sdk with AMAZONLITE on ubuntu 16 and i am able to get wake word properly and working fine. But when i am creating **.aar** of **aace** and **maccandroid** from Android Studio and using it windows system i am getting following error.

> aace.amazonLite.AmazonLiteWakewordEngineAdapter:getModelPathFromLocale:pathToLocale=/data/user/0/com.abc/cache/appdata/models/D.en-US.alexa.bin
> 
> PryonLiteKeywordDetector:loadModelIntoMemoryFailed:reason=failedToCreateFileStreamWithGivenFilePath,filePath=/data/user/0/com.abc/cache/appdata/models/D.en-US.alexa.bin
> 
> PryonLiteKeywordDetector:initFailed:reason=failedToLoadModelIntoMemory
> 
> PryonLiteKeywordDetector:createFailed:reason=Unable to initialize Pryon detector

## What is the expected behavior?
It should work fine .

## What behavior are you observing?
I am getting the above error and screen hangs.

## Provide the steps to reproduce the issue, if applicable:
1- Build **Alexa Auto sdk** with **AMAZONLITE** for wake word.
2- Import sample in Android studio .
3- Create executable (.aar) in Android Studio for **aace** and **maccandroid** .
4- Create Android Project  and use the following executable in project.
5- Try to open project and it hangs with error.

## Tell us about your environment:
    Ubuntu 16.4 - For building Alexa AUTO SDK
    Android Studio

### What version of the AVS Device SDK are you using?
     Alexa Auto SDK 1.6

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by mvelegon-amzn** [comment]
Hi @vaibhav2800 could you please file a ticket with the Amazon solution partner who is working with you to get this investigated. I will be closing this ticket. Thanks.
