### ISSUE TITLE
What is AmazonLite?

### ISSUE THREAD

**Issue by v2nero** [alexa/avs-device-sdk#1493]
I've got some token about "AMAZONLITE" in the CMakeLists.txt. But i can't got much more information in the project and event searching on google.
Is it about reducing ROM requirement? or just an key word detector engine? Can i get some more information?
Pls help to cleary kindly. thx

@erikhopf-amzn @mvelegon-amzn

**Comment by mvelegon-amzn** [comment]
Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.
