### ISSUE TITLE
FFmpeg read audio frame occurrence leak memory?

### ISSUE THREAD

**Issue by sevencheng798** [alexa/avs-device-sdk#1496]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I found memory sustained  growth when our device are playing a url resource. And finally it was found that the leak was due to the failure to free the AVPacket. So I fixed the following code memory to become normal work.
```c
--- a/MediaPlayer/AndroidSLESMediaPlayer/src/FFmpegDeleter.cpp
+++ b/MediaPlayer/AndroidSLESMediaPlayer/src/FFmpegDeleter.cpp
@@ -55,7 +55,7 @@
 
 template <>
 void FFmpegDeleter<AVPacket>::operator()(AVPacket* packet) {
 - av_packet_unref(packet);
 + av_packet_free(&packet);
 }
 
 template <>
```
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Thanks @sevencheng798.  We've created an internal tracking ticket to fix this, we much appreciate your bringing this to our attention.  I'll close out this ticket in the meantime.
