### ISSUE TITLE
The RenderTemplateCard log does not show the word asked to spell

### ISSUE THREAD

**Issue by aginesh** [alexa/avs-device-sdk#1497]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The RenderTemplateCard log does not show the word being asked to spell

## What is the expected behavior?
The RenderTemplateCard log shows the word asked to spell

## What behavior are you observing?
The log just shows "..." instead of the actual word.

## Provide the steps to reproduce the issue, if applicable:
1. Start Alexa device SDK.
2. Issue commands such as "Alexa, how do you spell barn"
3. On the console following log can be seen
##############################################################################
#     RenderTemplateCard                                                      
#-----------------------------------------------------------------------------
# Focus State         : FOREGROUND
# Template Type       : BodyTemplate1
# Main Title          : How do you spell …?
##############################################################################

## Tell us about your environment:
Linux ubuntu 16.4
### What version of the AVS Device SDK are you using?
      1.13.0

### Tell us what hardware you're using:
Laptop

### Tell us about your OS (Type & version):
Linux

**Comment by dhpp** [comment]
Hi @aginesh, this appears to be Alexa's standard response to this query per TemplateRuntime, and we will not classify this as a bug.  However, if you wish to discuss further and suggest a different user experience, we would direct you to ask on the AVS Forums [here](https://forums.developer.amazon.com/spaces/38/index.html), as this is outside the scope of the device SDK.
