### ISSUE TITLE
Not a Issue- But a Question : How to turn off/on microphone from cmdline of Sample App(Alexa) in Raspberry pi?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1499]
Hi,

When we run Alexa (Sample App) in raspberry pi and then press m + Enter then it turns off the microphone, in short, doesn't listen from it and when we press same again it starts listening.

So How can I do it from the command line by passing an argument? 

For e.g python startsample.sh -m or --microphone disable something

**Comment by dhpp** [comment]
Hi @rajdpandey, sorry but our SampleApplication does not currently support this.  You may update the script and main.cpp however to do this as you wish, which should not be too complex.  Let us know if you need any further assistance with this.  I'll close out this ticket for now.

**Comment by rajdpandey** [comment]
@dhpp hey. I am a electronics student and just learnt python for raspberry and more and I am a beginner at that so C++ is just out of my league. If you can help me with code or something like I will appreciate it and it will be a lot of help to me  I have limited time and have to do more things so..
