### ISSUE TITLE
Question regarding process: From where and how does this Sample app takes and triggers the Wake up Word?

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1501]
Hi,

I am not familiar with C or C++ , but still I tried to go through all the codes of Alexa Sample app but didn't find the file or code from where it triggers the Alexa when I say "Alexa" and sends it to the cloud to verify and all. 

Please any one can guide me...

**Comment by womw** [comment]
Hi @rajdpandey 

You will find the code related to wake word detection in AudioInputProcessor. Note that the sdk does not come with a wake word engine and you must install and enable one separately. A WWE that you can use is [Kitt AI](https://github.com/Kitt-AI/snowboy) or [Sensory](https://github.com/Sensory/alexa-rpi)

**Comment by rajdpandey** [comment]
Hi @womw also the sending WWE data to Alexa Cloud happens in AudioInputProcessor? Thanks.

**Comment by womw** [comment]
Yes it also occurs in the AudioInputProcessor

**Comment by rajdpandey** [comment]
OK Thanks.
