### ISSUE TITLE
Not a Issue But a Question: Making it listen after executing a command for sometime

### ISSUE THREAD

**Issue by rajdpandey** [alexa/avs-device-sdk#1509]
Hi,

As I am creating a TV control skill when I tell Alexa: "Alexa, ask James to turn on the tv" it turns on the tv and again goes into an ideal state. I don't want that. When I ask Alexa to turn on tv it should turn on and then wait for some seconds for another command like user can say increase the volume or change channel etc. I don't want to say Alexa for each function or command. But I want it to listen for some seconds after the execution of commands not for just TV skill but for everything.

is it possible? How can I achieve it?

Thanks,
Raj Pandey

**Comment by womw** [comment]
Hey @rajdpandey thanks for posting.

It sounds like you have a question about how to develop a skill. This Github is dedicated to topics about the device sdk so this is outside of our scope.

You can try looking at some of the documentation we have available on skill development and getting in contact with the help team there.
https://developer.amazon.com/en-US/alexa/alexa-skills-kit/alexa-conversations
