### ISSUE TITLE
[Query]: AVS SDK Support for VoIP Based calling and Multi room music

### ISSUE THREAD

**Issue by indrachatterjee86** [alexa/avs-device-sdk#1511]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
This is not an issue but  a query. We wanted to understand, if current release i.e. 1.14.0 of AVS SDK supports VoIP Stack for calling and messaging. 

We also wanted to understand , if Multi Room Music Library can be integrated with AVS SDK.

## What is the expected behavior?
Alexa should try to dial a VoIP call to contact.

## What behavior are you observing?
When speech "Alexa Drop-in" is given, then response : "Alexa Calling is not supported in this device"

## Provide the steps to reproduce the issue, if applicable:
No Steps

### What version of the AVS Device SDK are you using?
1.14.0

### Tell us what hardware you're using:
Samsung Artik305

### Tell us about your OS (Type & version):
Ubuntu 16.0

**Comment by samcoult** [comment]
Hello @indrachatterjee86,

Please contact your Amazon Business Development Representative or use the [intake form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) to reach out directly regarding enabling the Multi Room Music and VoIP Communication features.
