### ISSUE TITLE
Missing Alexa.ApiGateway code in v1.15

### ISSUE THREAD

**Issue by jbfitb** [alexa/avs-device-sdk#1513]
## Briefly summarize your issue:
 - [Time Zones and Multi-language support were added in v1.15](https://github.com/alexa/avs-device-sdk/releases/tag/v1.15)
 - In order to use those features, [you have to upgrade to version 2.0 of the System interface](https://developer.amazon.com/docs/alexa-voice-service/system.html)
 - However, the `SetEndpoint` directive was removed from the 2.0 version of the System Interface.
 - [The replacement is to use the `Alexa.ApiGateway` interface instead](https://developer.amazon.com/docs/alexa-voice-service/alexa-apigateway.html)
 - However, there is no `ApiGateway`-related code in v1.15

## What is the expected behavior?
 - Hoping for code to handle the [new `SetGateway Directive`](https://developer.amazon.com/docs/alexa-voice-service/alexa-apigateway.html#setgateway). 
 - Without code to handle this, devices will not work outside of North America, or we are not able to upgrade to System Interface 2.0
 - Eager to use new System features like getting/setting Time Zone and Multi-language support

**Comment by celinval** [comment]
Hi @jbfitb,

That's a great question! The SDK v1.15 was released using a System Interface version that already supports the new get / set Time Zone and the Multi-language features. The only difference between the version that the SDK is using and System 2.0 is that we are still able to use SetEndpoint instead of the Alexa.ApiGateway.

Please let us know if you have any problem using the new features.

Best,
Celina
Celina

**Comment by jbfitb** [comment]
Thanks for the quick reply. Is there any documentation on this version of the System Interface? The official docs jump [from v1.2](https://developer.amazon.com/docs/alexa-voice-service/system.html?v=1_2) to [2.0](https://developer.amazon.com/docs/alexa-voice-service/system.html?v=2_0)

**Comment by celinval** [comment]
Hi @jbfitb, I'm sorry so for this confusion. We are working on this gap.

For now, you can use the 2.0 documentation as a reference. The main difference is that we removed the SetEndpoint directive on 2.0 in favor of a more complete Alexa.ApiGateway. For the SetEndpoint documentation, please refer to the 1.2.

**Comment by jbfitb** [comment]
Thanks again for the quick response! What version do I target for System in the Capabilities API? a new 1.3?

**Comment by kclchan** [comment]
Hi @jbfitb, you should target for System 1.4.  We have added a note in the document for System API (https://developer.amazon.com/docs/alexa-voice-service/system.html) to explain the differences between System v1.4 and System v2.0.  Thanks!

**Comment by jbfitb** [comment]
Thanks @kclchan!

**Comment by caleighatamazon** [comment]
Closing this issue :) Please feel free to re-open if you have more questions!
