### ISSUE TITLE
If BT is connected and streaming is Active, then another phone should not allowed to connect via BT.

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1514]
## Briefly summarize your issue:
When a phone is connected via Bluetooth, then another phone should not be connected to Bluetooth. This functionality gives bad experience to user if streaming is ACTIVE via first phone.  

## What is the expected behavior?
Another phone should not be connected when streaming is Active from first phone.

## What behavior are you observing?
Another phone connects while streaming is ACTIVE from first phone. 

## Provide the steps to reproduce the issue, if applicable:
1. Connect first phone via. BT
2. Play some music via BT.
3. Pair and connect another phone via BT. 
4. First phone disconnect silently and another phone connects via BT.

## Tell us about your environment:
AVS SDK Version 1.14.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### What version of the AVS Device SDK are you using?
1.14.0

### Tell us what hardware you're using:
Other: Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

### Tell us about your OS (Type & version):
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

Attaching the logs for this issue. 
[alexa_bt_overridden_issue.log](https://github.com/alexa/avs-device-sdk/files/3689286/alexa_bt_overridden_issue.log)

**Comment by scotthea-amazon** [comment]
Hello @mohitbansal19,

Thank you for bringing this to our attention.  We will look in to it.

Best regards,
-SWH

**Comment by caleighatamazon** [comment]
Hi there, sorry for our late response on this. Are you still having problems?

**Comment by mohitbansal19** [comment]
Yes, this issue exists in avs-sdk 1.14.0 version.

**Comment by caleighatamazon** [comment]
Have you also tried our latest release, 1.16? Does the problem also occur in that release?

**Comment by mohitbansal19** [comment]
We did not try this with latest release, 1.16 yet. Have you resolve this problem in 1.16 build?

**Comment by ajaythakur-dev** [comment]
Replying on behalf of @mohitbansal19: Tested same on 1.18 issue still persists.

**Comment by ajaythakur-dev** [comment]
As shared by Alexa Team: "This is working as designed, we do not block Bluetooth from connecting and being that only 1 device can be connected at a time the first one will get kicked off." So team can close this defect.
