### ISSUE TITLE
showing APL on device with display

### ISSUE THREAD

**Issue by k4Shinigami** [alexa/avs-device-sdk#1516]
## Briefly summarize your issue:
The requests from AVS doesn't have the necessary information to say that it supports a display to respond with APL. As per forum discussion, the request envelope should have `Alexa.Presentation.APL` in the supported interfaces. Responses that have display-cards do get passed in the response for Templateruntime to show the card in the log. But since the request doesn't have `Alexa.Presentation.APL` in the supported interfaces, the APL is not being returned to template renderer. Could I get the direction on what needs to be updated for this to work, or if the support is already there and I am missing something.

### What version of the AVS Device SDK are you using?
      v1.13

### Tell us what hardware you're using:
- [*] Other - tell us more: Android App

### Tell us about your OS (Type & version):
- [*] Other - tell us more: Android

**Comment by scotthea-amazon** [comment]
Hello @k4Shinigami 

The APL API’s are not public yet, and Alexa Device SDK doesn’t handle them.  Please use the [Request Access](https://developer.amazon.com/en-US/alexa/alexa-voice-service/alexa-smart-screen-sdk#request-access-to-the-sdk) form at the bottom of [Alexa Smart Screen and TV SDK](https://developer.amazon.com/en-US/alexa/alexa-voice-service/alexa-smart-screen-sdk) page to request access to SmartScreenSDK private beta.

Best regards,
-SWH

**Comment by k4Shinigami** [comment]
Thank you for the reply @scotthea-amazon . Just requested access to the sdk and hopefully I ll get it soon. 

One question is I am calling capabilities api to indicate the device has a display to get data for type listTemplate. I do get a success(204) from the capabilties endpoint after authentication. But the subsequent request from the avs-device doesn't have `display` in the supported interaces and only has `audioplayer`. Is this also a limitation on avs-device-sdk or am i missing something?

**Comment by caleighatamazon** [comment]
Hi @k4Shinigami, I'm not sure I understand the question. Could you give me a bit more detail about what you mean by "calling capabilities api to indicate the device has a display"?

**Comment by k4Shinigami** [comment]
Hello @caleighatamazon, for the background I am using a JNI wrapper around avs for Android - mostly from the [alexa-auto-sdk](https://github.com/alexa/alexa-auto-sdk) code. I am authorizing app using CBL. Once I get the auth token, I am sending a POST request to the [capabilities API](https://developer.amazon.com/docs/alexa-voice-service/capabilities-api.html) with  a body similar to the `Sample Request Body`. From what I understand from the documentation, I am only calling the capabilities once on AUTH and not for every request. I do get a success of 204 from the endpoint saying it registered the capabilities, but checking subsequent requests in developer console I dont see the capabilities/supportedInterfaces. It only has `audioplayer`.

Let me know if I said something confusing or did anything wrong in the flow. Cheers and Thanks!

**Comment by caleighatamazon** [comment]
Hi @k4Shinigami, thanks for your response. It does sound like your device is using the capabilities API at the appropriate time (that is, only when the device requires a new auth token). 

Could you provide the POST request body for the Capabilities API that you're sending (the capabilities list)? 

Also, in your original issue, you wrote "As per forum discussion" -- could you please send me the link to that forum discussion just to make sure I get the full context here?

Also, could you be more specific about how you "[check] subsequent requests in developer console"? Where are you looking for the product's capabilities in the dev console?

Thanks!

**Comment by k4Shinigami** [comment]
>Could you provide the POST request body for the Capabilities API that you're sending (the capabilities list)?

Alrighty =>
HEADERS:
```
("Content-Type", "application/json")
("x-amz-access-token", accessToken)
("Content-Length", String.valueOf(input.length))
```

BODY:
```
capabilitiesMap.put("TemplateRuntime", "1.0");
capabilitiesMap.put("AudioPlayer", "1.0");
capabilitiesMap.put("Notifications", "1.0");
capabilitiesMap.put("PlaybackController", "1.0");
capabilitiesMap.put("Speaker", "1.0");
capabilitiesMap.put("SpeechRecognizer", "1.0");
capabilitiesMap.put("SpeechSynthesizer", "1.0");
```

which translates to : 
```
{
    "envelopeVersion": "20160207",
    "capabilities": [
        {
            "type": "AlexaInterface",
            "interface": "TemplateRuntime",
            "version": "1.0"
        },
	{
            "type": "AlexaInterface",
            "interface": "AudioPlayer",
            "version": "1.0"
        },
        {
            "type": "AlexaInterface",
            "interface": "Notifications",
            "version": "1.0"
        },
        {
            "type": "AlexaInterface",
            "interface": "PlaybackController",
            "version": "1.1"
        },
        {
            "type": "AlexaInterface",
            "interface": "Speaker",
            "version": "1.0"
        },
        {
            "type": "AlexaInterface",
            "interface": "SpeechRecognizer",
            "version": "2.0"
        },
        {
            "type": "AlexaInterface",
            "interface": "SpeechSynthesizer",
            "version": "1.0"
        },
    ]
}
```
which is part of the sample request from capabilities API page. I was doing a `PUT` and NOT `POST` to the endpoint `https://api.amazonalexa.com/v1/devices/@self/capabilities`

> could you be more specific about how you "[check] subsequent requests in developer console"? Where are you looking for the product's capabilities in the dev console?

I was checking the cloudwatch logs of my skill lambda to determine the supportedInterfaces on the incoming request.

>Also, in your original issue, you wrote "As per forum discussion" -- could you please send me the link to that forum discussion just to make sure I get the full context here?

https://forums.developer.amazon.com/questions/196261/how-to-prevent-skill-with-apl-from-failing-on-devi.html?childToView=196262#answer-196262

In the answer there 
```   handlerInput.requestEnvelope.context.System.device.supportedInterfaces.Display) &&
    handlerInput.requestEnvelope.context.Viewport
}
```
Passing a response with bodyTemplate/weatherTemplate without the check works. But passing response with APL or a listtemplate without checking for display/viewport was just resulting in a `something went wrong with the skill`.

**Comment by ecruzado** [comment]
@k4Shinigami did you resolve the issue?

**Comment by chemudug-amzn** [comment]
Hi @k4Shinigami please take a look at https://github.com/alexa/alexa-smart-screen-sdk - our public smart screen sdk based on the voice sdk that supports APL.

https://developer.amazon.com/en-US/alexa/alexa-voice-service/alexa-smart-screen-sdk

You can read more about it here: https://developer.amazon.com/en-US/blogs/alexa/device-makers/2019/11/announcing-general-availability-of-alexa-smart-screen-sdk-for-tvs-smart-displays-and-more

**Comment by k4Shinigami** [comment]
@ecruzado Unfortunately no, I did not get time to go back to this but we were planning to use the smart screen sdk once it is out (which is out currently). Since we are passing the required params to the service, I dont imagine the problem is in the client. So instead of trying to hammer it down, we will explore the alternative.

Thank you @chemudug-amzn , we will start taking advantage of the smart screen sdk for the APL soon in our organization.
