### ISSUE TITLE
MediaPlayerTest failing

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#152]
Tag: v1.0.2

Building with -DGSTREAMER_MEDIA_PLAYER=ON, I get two test case errors.  Can I safely ignore these, and if so when will the test case issues be addressed?

    369/473 Testing: MediaPlayerTest.testStartPlayForUrl
    369/473 Test: MediaPlayerTest.testStartPlayForUrl
    Command: "/home/joel/git/build/avs-device-sdk-prefix/src/avs-device-sdk-build/MediaPlayer/test/MediaPlayerTest" "--gtest_filter=MediaPlayerTest.testStartPlayForUrl" "/home/joel/git/avs-device-sdk/MediaPlayer/inputs"
    Directory: /home/joel/git/build/avs-device-sdk-prefix/src/avs-device-sdk-build/MediaPlayer/test
    "MediaPlayerTest.testStartPlayForUrl" start time: Sep 12 17:42 UTC
    Output:
    ----------------------------------------------------------
    Note: Google Test filter = MediaPlayerTest.testStartPlayForUrl
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from MediaPlayerTest
    [ RUN      ] MediaPlayerTest.testStartPlayForUrl
    2017-09-12 17:42:13.265 [  1] 0 MediaPlayer:handleSetObserverCalled
    2017-09-12 17:42:13.265 [  2] 0 MediaPlayer:handleSetSourceForUrlCalled
    2017-09-12 17:42:13.267 [  2] 0 UrlSource:initCalledForUrlSource
    2017-09-12 17:42:13.267 [  2] 0     UrlSource:onPlaylistParsed:parseResult=PARSE_RESULT_UNHANDLED,numUrlsParsed=0
    2017-09-12 17:42:13.268 [  1] 0 MediaPlayer:handlePlayCalled
    2017-09-12 17:42:13.268 [  1] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
    2017-09-12 17:42:13.268 [  1] 0 MediaPlayer:handlePlay:supportsBuffering=1
    2017-09-12 17:42:13.273 [  1] I MediaPlayer:Starting Buffering
    /home/joel/git/avs-device-sdk/MediaPlayer/test/MediaPlayerTest.cpp:428: Failure
    Value of: m_playerObserver->waitForPlaybackStarted()
      Actual: false
    Expected: true
    2017-09-12 17:42:18.274 [  1] 0 MediaPlayer:handleStopCalled
    2017-09-12 17:42:18.276 [  1] 0 MediaPlayer:callingOnPlaybackFinished
    [  FAILED  ] MediaPlayerTest.testStartPlayForUrl (5033 ms)
    [----------] 1 test from MediaPlayerTest (5034 ms total)
    
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test case ran. (5035 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] MediaPlayerTest.testStartPlayForUrl
    
     1 FAILED TEST
    <end of output>
    Test time =   5.05 sec
    ----------------------------------------------------------
    Test Failed.
    "MediaPlayerTest.testStartPlayForUrl" end time: Sep 12 17:42 UTC
    "MediaPlayerTest.testStartPlayForUrl" time elapsed: 00:00:05
    ----------------------------------------------------------

    371/473 Testing: MediaPlayerTest.testConsecutiveSetSource
    371/473 Test: MediaPlayerTest.testConsecutiveSetSource
    Command: "/home/joel/git/build/avs-device-sdk-prefix/src/avs-device-sdk-build/MediaPlayer/test/MediaPlayerTest" "--gtest_filter=MediaPlayerTest.testConsecutiveSetSource"     "/home/joel/git/avs-device-sdk/MediaPlayer/inputs"
    Directory: /home/joel/git/build/avs-device-sdk-prefix/src/avs-device-sdk-build/MediaPlayer/test
    "MediaPlayerTest.testConsecutiveSetSource" start time: Sep 12 17:42 UTC
    Output:
    ----------------------------------------------------------
    Note: Google Test filter = MediaPlayerTest.testConsecutiveSetSource
    [==========] Running 1 test from 1 test case.
    [----------] Global test environment set-up.
    [----------] 1 test from MediaPlayerTest
    [ RUN      ] MediaPlayerTest.testConsecutiveSetSource
    2017-09-12 17:42:18.341 [  1] 0 MediaPlayer:handleSetObserverCalled
    2017-09-12 17:42:18.342 [  2] 0 MediaPlayer:handleSetSourceForUrlCalled
    2017-09-12 17:42:18.344 [  2] 0 UrlSource:initCalledForUrlSource
    2017-09-12 17:42:18.344 [  2] E DummyPlaylistParser:parsePlaylistFailed:reason=emptyUrl
    2017-09-12 17:42:18.344 [  2] E UrlSource:initFailed:reason=startingParsePlaylistFailed
    2017-09-12 17:42:18.344 [  2] E MediaPlayer:handleSetSourceForUrlFailed:reason=sourceIsNullptr
    2017-09-12 17:42:18.344 [  3] 0 MediaPlayer:handleSetSourceForUrlCalled
    2017-09-12 17:42:18.344 [  3] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
    2017-09-12 17:42:18.344 [  3] 0 UrlSource:initCalledForUrlSource
    2017-09-12 17:42:18.344 [  3] 0     UrlSource:onPlaylistParsed:parseResult=PARSE_RESULT_UNHANDLED,numUrlsParsed=0
    2017-09-12 17:42:18.345 [  1] 0 MediaPlayer:handlePlayCalled
    2017-09-12 17:42:18.345 [  1] 0 MediaPlayer:doStopSuccess:reason=alreadyStopped
    2017-09-12 17:42:18.345 [  1] 0 MediaPlayer:handlePlay:supportsBuffering=1
    2017-09-12 17:42:18.355 [  1] I MediaPlayer:Starting Buffering
    /home/joel/git/avs-device-sdk/MediaPlayer/test/MediaPlayerTest.cpp:451: Failure
    Value of: m_playerObserver->waitForPlaybackStarted()
      Actual: false
    Expected: true
    2017-09-12 17:42:23.356 [  1] 0 MediaPlayer:handleStopCalled
    2017-09-12 17:42:23.357 [  1] 0 MediaPlayer:callingOnPlaybackFinished
    [  FAILED  ] MediaPlayerTest.testConsecutiveSetSource (5031 ms)
    [----------] 1 test from MediaPlayerTest (5031 ms total)
    
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test case ran. (5031 ms total)
    [  PASSED  ] 0 tests.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] MediaPlayerTest.testConsecutiveSetSource
    
     1 FAILED TEST
    <end of output>
    Test time =   5.04 sec
    ----------------------------------------------------------
    Test Failed.
    "MediaPlayerTest.testConsecutiveSetSource" end time: Sep 12 17:42 UTC
    "MediaPlayerTest.testConsecutiveSetSource" time elapsed: 00:00:05
    ----------------------------------------------------------

**Comment by sanjayrd** [comment]
Hi @INRIX-joel-winarske,

I have not been able to reproduce the behavior you just described working on the 1.0.2 commit. A few questions:

- Is this happening for you consistently? 
- It's also possible that you don't have certain GStreamer plugins - can you verify? 
- What platform are you running on?

Thanks,
Sanjay

**Comment by INRIX-joel-winarske** [comment]
Hi @sanjayrd 

- It happens every test run
- Ubuntu 16.04 LTS

    gstreamer1.0-clutter-3.0 is already the newest version (3.0.18-1).
    gstreamer-tools is already the newest version (0.10.36-1.5ubuntu1).
    gstreamer0.10-doc is already the newest version (0.10.36-1.5ubuntu1).
    gstreamer0.10-nice is already the newest version (0.1.13-0ubuntu2).
    gstreamer0.10-tools is already the newest version (0.10.36-1.5ubuntu1).
    gstreamer1.0-clutter is already the newest version (2.0.18-1).
    gstreamer1.0-crystalhd is already the newest version (1:0.0~git20110715.fdd2f19-11build1).
    gstreamer1.0-dvswitch is already the newest version (0.1.1-1).
    gstreamer1.0-espeak is already the newest version (0.4.0-1).
    gstreamer1.0-fluendo-mp3 is already the newest version (0.10.32.debian-1).
    gstreamer1.0-nice is already the newest version (0.1.13-0ubuntu2).
    gstreamer1.0-pocketsphinx is already the newest version (0.8.0+real5prealpha-1ubuntu2).
    gstreamer1.0-alsa is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-doc is already the newest version (1.8.3-1~ubuntu0.1).
    gstreamer1.0-plugins-base is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-base-apps is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-base-dbg is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-base-doc is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-good is already the newest version (1.8.3-1ubuntu0.4).
    gstreamer1.0-plugins-good-dbg is already the newest version (1.8.3-1ubuntu0.4).
    gstreamer1.0-plugins-good-doc is already the newest version (1.8.3-1ubuntu0.4).
    gstreamer1.0-pulseaudio is already the newest version (1.8.3-1ubuntu0.4).
    gstreamer1.0-tools is already the newest version (1.8.3-1~ubuntu0.1).
    gstreamer1.0-x is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer-qapt is already the newest version (3.0.2-0ubuntu1.1).
    gstreamer0.10-alsa is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-gconf is already the newest version (0.10.31-3+nmu4ubuntu2.16.04.3).
    gstreamer0.10-gnomevfs is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-plugins-base is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-plugins-base-apps is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-plugins-base-dbg is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-plugins-base-doc is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer0.10-plugins-good is already the newest version (0.10.31-3+nmu4ubuntu2.16.04.3).
    gstreamer0.10-plugins-good-dbg is already the newest version (0.10.31-3+nmu4ubuntu2.16.04.3).
    gstreamer0.10-plugins-good-doc is already the newest version (0.10.31-3+nmu4ubuntu2.16.04.3).
    gstreamer0.10-pulseaudio is already the newest version (0.10.31-3+nmu4ubuntu2.16.04.3).
    gstreamer0.10-qapt is already the newest version (3.0.2-0ubuntu1.1).
    gstreamer0.10-x is already the newest version (0.10.36-2ubuntu0.1).
    gstreamer1.0-libav is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-libav-dbg is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-packagekit is already the newest version (0.8.17-4ubuntu6~gcc5.4ubuntu1.2).
    gstreamer1.0-plugins-bad is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-bad-dbg is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-bad-doc is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-bad-faad is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-bad-videoparsers is already the newest version (1.8.3-1ubuntu0.2).
    gstreamer1.0-plugins-ugly is already the newest version (1.8.3-1ubuntu0.1).
    gstreamer1.0-plugins-ugly-amr is already the newest version (1.8.3-1ubuntu0.1).
    gstreamer1.0-plugins-ugly-dbg is already the newest version (1.8.3-1ubuntu0.1).
    gstreamer1.0-plugins-ugly-doc is already the newest version (1.8.3-1ubuntu0.1).
    gstreamer1.0-vaapi is already the newest version (1.8.3-1~ubuntu0.1).
    gstreamer1.0-vaapi-doc is already the newest version (1.8.3-1~ubuntu0.1).
    gstreamer1.0-hybris:i386 is already the newest version (1.8.3-1ubuntu0.2).

**Comment by kjkh** [comment]
Hi,
The unit test failures is a known issue with gstreamer 1.8.3, and we are tracking this internally. If you do not wish to see the failures, upgrading to 1.10.4 is a possible solution.

**Comment by kclchan** [comment]
Closing this for now.  Please re-open if you are still seeing issues after upgrading gstreamer to 1.10.4.  Thanks.
