### ISSUE TITLE
CANNOT LINK EXECUTABLE cannot locate symbol " __aeabi_memcpy" referenced by "/data/Alexa/bin/SampleApp"... page record for 0xb6d5400c was not found (block_size=16)

### ISSUE THREAD

**Issue by jm47895** [alexa/avs-device-sdk#1520]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

So we are trying to run the SampleApp on Android. It built fine, tried to run and it seems like this file is missing: "__aeabi_memcpy" 

## What is the expected behavior?

Wait for the sample app to display a message like this:

##################################
#       NOT YET AUTHORIZED       #
##################################
################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
########################################################################################

## What behavior are you observing?

A file seems to be missing after building. 

## Provide the steps to reproduce the issue, if applicable:

Just make the Sample app and try and run. 

### What version of the AVS Device SDK are you using?
      <1.15.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [. ] Other - tell us more:
 
We are using a embedded device with an ARM Cortex-A9 

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [. ] Other - tell us more:

Android 24 and 25 (tried both on different embedded devices) on top of Linux

**Comment by scotthea-amazon** [comment]
Hello @jm47895 

It looks like you may be targeting a version of android that is newer than the device you are testing with.

Here is a link that may be helpful: https://github.com/android/ndk/issues/126

Best regards,
-SWH

**Comment by jm47895** [comment]
Yep that solved it! I thought we had a more updated version but we had Android platform-23 in the device. Thank you!

**Comment by bhagwandassony1** [comment]
![Screenshot_20200804-215851](https://user-images.githubusercontent.com/69147279/89323859-e33a7c00-d675-11ea-99d7-bef74ce24a08.png)
