### ISSUE TITLE
MimeResponseSink returning arbitrary enum value

### ISSUE THREAD

**Issue by jbfitb** [alexa/avs-device-sdk#1525]
## Briefly summarize your issue:
 - We keep getting [curl error 23 on receiving data](https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLEWRITEERROR):
```
HTTP2MimeResponseDecoder:onReceiveData:size=193
MimeResponseSink:onReceiveNonMimeData:size=193
HTTP2Transport:onActivity
CurlEasyHandleWrapper:libcurl:id=AVSEvent-553,text=Failed writing body (0 !\= 193)
LibcurlHTTP2Connection:streamFinished:streamId=AVSEvent-553,result=Error,CURLcode=23
```

 - [It looks like error 23 happens when](https://github.com/curl/curl/blob/0eec832603d3a4ba9ae69a16351cf29c37f7fb7c/lib/sendf.c#L614) the curl [write function callback](https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) fails
 - Walking down the code, [it seems that MimeResponseSink returns an arbitrary enum value for `HTTP2ReceiveDataStatus`](https://github.com/alexa/avs-device-sdk/blob/master/ACL/src/Transport/MimeResponseSink.cpp#L227)
 - It appears to accidentally invoke the constructor of the [`HTTP2ReceiveDataStatus` enum class](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/include/AVSCommon/Utils/HTTP2/HTTP2ReceiveDataStatus.h#L28) instead of returning `SUCCESS`, `ABORT`, or `PAUSE`.

## What is the expected behavior?
 - It's unclear what's expected here. On one hand, it seems that [the return value](https://github.com/alexa/avs-device-sdk/blob/master/ACL/src/Transport/MimeResponseSink.cpp#L227) should be `HTTP2ReceiveDataStatus::SUCCESS`
 - However, it also looks like the [write callback function of CURL expects `size_t` of the number of bytes written.](https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html)
 - And it looks like [`MimeRepsonseSink` can write fewer bytes than requested](https://github.com/alexa/avs-device-sdk/blob/master/ACL/src/Transport/MimeResponseSink.cpp#L222)
 - Ultimately, the number of bytes written should be bubbled up to [HTTP2MimeResponseDecoder](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/src/HTTP2/HTTP2MimeResponseDecoder.cpp#L173) which should then be bubbled up to become the return value for the curl write callback.

**Comment by scotthea-amazon** [comment]
Hello @jbfitb,

Thank you for bringing this to our attention!  The return of HTTP2ReceiveDataStatus(size) is certainly wrong.  The method should be returning HTTP2ReceiveDataStatus::SUCCESS - even if less than the full amount is appended to m_nonMimeBody.  The limit NON_MIME_BODY_MAX_SIZE applied in MimeResponseSink::onReceiveNonMimeData() is only there to prevent consuming an arbitrarily large amount of memory if an unexpectedly large body is returned for a non 200 reply .  Such reply bodies are usually just a message indicating why the request failed.

Best regards,
-SWH

**Comment by jbfitb** [comment]
Thanks @scotthea-amazon! I'm wondering if it meant to return [`HTTP2SendDataResult`](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/include/AVSCommon/Utils/HTTP2/HTTP2SendDataResult.h#L31) as it has both status and bytes read. 

Should bytes read be returned to curl?

**Comment by scotthea-amazon** [comment]
Hi @jbfitb,

Yes, the bytes read is returned to curl.  onReceiveNonMimeData() is returning the correct type as is the call to it in HTTP2MimeResponseDecoder::onReceiveData().  These return codes are  transformed in to the proper libcurl return value in LibcurlHTTP2Request::writeCallback().

Best regards,
-SWH

**Comment by jbfitb** [comment]
Hi @scotthea-amazon! [What about the case when `onReceiveNonMimeData` writes less than the requested amount of data?](https://github.com/alexa/avs-device-sdk/blob/master/ACL/src/Transport/MimeResponseSink.cpp#L223) The bytes read should be bubbled up to `HTTP2MimeResponseDecoder::onReceiveData()` and then to `LibcurlHTTP2Request::writeCallback()`, right?

Thanks!

**Comment by scotthea-amazon** [comment]
Hi @jbfitb,

No.  There is no need to bubble up the count of bytes copied.  onReceiveNonMimeData() is consuming the remaining bytes by dropping them.  It drops those bytes intentionally, so it does not need to buffer a potentially unbounded amount of data.

Best regards,
-SWH

**Comment by scotthea-amazon** [comment]
Hello @jbfitb,

I am closing this issue since it appears to have been resolved.  Please feel free to re-open it if I have closed it in error.

Best regards,
-SWH
