### ISSUE TITLE
Implement CURLOPT_SEEKFUNCTION

### ISSUE THREAD

**Issue by jbfitb** [alexa/avs-device-sdk#1526]
## What behavior are you observing?
- About 1 in 10 Alexa requests fail on mobile devices. 
- Requests generally fail with one of two errors: [curl error code 56](https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLERECVERROR) which is "receive error" or [curl error code 65](https://curl.haxx.se/libcurl/c/libcurl-errors.html#CURLESENDFAILREWIND) which is "rewind failed"
- I turned on `ACSDK_EMIT_SENSITIVE_LOGS` to output curl error messages and me help investigate what was going on
- It looks like the errors (both 56 and 65) are accompanied with this message `"necessary data rewind wasn't possible"`:

```
CurlEasyHandleWrapper:libcurl:id=AVSEvent-619,text=necessary data rewind wasn't possible
LibcurlHTTP2Request:getResponseCode:responseCode=0
LibcurlHTTP2Connection:streamFinished:streamId=AVSEvent-619,result=Error,CURLcode=56
```

 - It seems that implementing the [`CURLOPT_SEEKFUNCTION`](https://curl.haxx.se/libcurl/c/CURLOPT_SEEKFUNCTION.html) and setting [`CURLOPT_SEEKDATA`](https://curl.haxx.se/libcurl/c/CURLOPT_SEEKDATA.html) will solve this problem
 - This is a fairly simple change, as [`AttachmentReader` already has a seek function](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/AttachmentReader.h#L94) which mirrors the implementation of `CURLOPT_SEEKFUNCTION`: Both expect to be able to set the absolute index of the buffer instead of changing the cursor by some delta.

**Comment by kclchan** [comment]
Hi @jbfitb, thank you for reaching out to us and providing a solution in the pull request.  I have created an internal ticket to look into this.  Thanks!
