### ISSUE TITLE
Unexpected licensing error encountered. Exiting.

### ISSUE THREAD

**Issue by tunghustvn** [alexa/avs-device-sdk#1527]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I'm following the introduction from [Build the AVS Device](https://developer.amazon.com/docs/alexa-voice-service/build-the-avs-device-sdk.html) to install the sdk to my PC.
But when I ran the command on my terminal:
sudo bash setup.sh config.json [-s 1234]

## What behavior are you observing?

The terminal prompt that error:
`./alexa-rpi/bin/license.sh: line 49: /home/tungngo/third-party/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.`

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @tunghustvn, please note that the setup.sh script is not meant to be used on a Linux PC.  Please follow https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide instead.  Thanks!

**Comment by tunghustvn** [comment]
Thanks. I followed the tutorial and installed avs on raspberry pi 3B+ and it worked.
