### ISSUE TITLE
Pulseaudio Daemon Cannot Run at the Same Time

### ISSUE THREAD

**Issue by DMaiorino** [alexa/avs-device-sdk#1530]
## Briefly summarize your issue:
Since issue #1396 was closed out, opening this as a new issue. 
## What is the expected behavior?
SampleApp should run

## What behavior are you observing?
When starting SampleApp, the following error occurs:
```
PortAudioMicrophoneWrapper failing to initialize:

2019-10-19 01:19:11.100 [ 1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9997
```

## Provide the steps to reproduce the issue, if applicable:
Have portaudio running as a daemon, and attempt to start SampleApp.

### What version of the AVS Device SDK are you using?
Still an issue with the latest version 1.15.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ●] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ●] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ●] Other - tell us more: Tiny Core Linux

**Comment by khassel** [comment]
see https://github.com/alexa/avs-device-sdk/issues/1413#issuecomment-510233469 and the following comments

**Comment by khassel** [comment]
Hi Sam, I'm not the creator of this issue, so you may better ask @DMaiorino?

**Comment by samcoult** [comment]
@khassel , thanks for the clarification! Comment updated

**Comment by DMaiorino** [comment]
@khassel Thanks for the feedback, I tried this fix, and confirmed that the SampleApp successfully starts up. (No longer seeing the error reported in this issue) At the same time, it still looks like there is a problem with Pulseaudio running as a daemon as I am unable to speak to or hear from Alexa. If I shutdown the Pulseaudio daemon and retry, I am able to use Alexa without issue.

@samcoult Tested on hardware besides a Raspberry Pi with the same result, but for the testing on the Pi I used the Pi 2 model B.

**Comment by samcoult** [comment]
@DMaiorino ,

Thanks for reporting this issue, I have created an internal tracking issue to get this looked at.

**Comment by isdaves** [comment]
@samcoult Any updates on the internal issue? Can we have visibility over it?
Thanks!

**Comment by navehgrofi** [comment]
@samcoult 

are there any updated on this? we are also having issues with Pulse Audio server here

**Comment by navehgrofi** [comment]
@samcoult 

So what does it means? Is it resolved? Or will be resolved?

**Comment by samcoult** [comment]
Hi @navehgrofi , this ticket was closed in error.

The issue exists in our backlog and is under investigation/development for release in a future SDK release.

**Comment by kjkh** [comment]
After installing PulseAudio, please also install 

`sudo apt-get install gstreamer1.0-pulseaudio`

In your JSON configuration file, please add the following lines:
```
    "gstreamerMediaPlayer":{
        "audioSink":"pulsesink"
    },
```

Also, ensure that your .asoundrc is configured properly. Removing the local .asoundrc file (~/.asoundrc, or equivalent) worked in the past. Alternatively, you can manually configure it: (https://wiki.archlinux.org/index.php/PulseAudio/Examples#The_manual_sink_configuration_method)

You can also configure the output sink via pavucontrol `sudo apt-get install pavucontrol`.

Please try these steps and let us know if there are any further issues.

**Comment by navehgrofi** [comment]
@kjkh 

this does seem to make everything work!

thank you

**Comment by kclchan** [comment]
Closing this issue now as it's been resolved.
