### ISSUE TITLE
New Installation-No State of Speaking after Thinking

### ISSUE THREAD

**Issue by zeesh1979** [alexa/avs-device-sdk#1531]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
i dont know how to check but i used the same steps i followed earlier from amazon directly
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Below are logs that show some issue related to mediaplayer. i followed all similar opened issues but my problem is not fixed....

[log.txt](https://github.com/alexa/avs-device-sdk/files/3757608/log.txt)

**Comment by zeesh1979** [comment]
contents of my /etc/asound.conf:

pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:<card number>,<device number>"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:<card number>,<device number>"
  }
}

**Comment by zeesh1979** [comment]
i followed below steps:
1. sudo apt-get update
2. sudo apt-get upgrade
3. download below:
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/genConfig.sh
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh
4. Download your credentials (config.json) from AVS dashboard (Other devices and platforms) to /home/pi 
5. sudo bash setup.sh config.json [-s 1234]
6. sudo bash startsample.sh
7. goto https://amazon.com/us/code and input the auth code
8. sudo apt-get install pulseaudio
9. edit /etc/mpd.conf
audio_output {
  type   "pulse"
  name   "MPD PulseAudio Output"
}
10. edit /etc/pulse/default.pa
comment out  load-module module-suspend-on-idle
11. restart pi
12. setup .asoundrc with correct mic and speakers device ids

**Comment by samcoult** [comment]
Hi @zeesh1979 ,

Which version/model of raspberry pi are you using?

**Comment by zeesh1979** [comment]
Raspberry pi3 b+

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by samcoult** [comment]
HI @zeesh1979 , is the pulse audio input/output working for any other applications?

I recommend installing pavucontrol (sudo apt install pavucontrol) for a GUI frontend to the Pulse Audio Demon. There are also ncurses based terminal UI available which make debugging easier.

**Comment by zeesh1979** [comment]
i checked my audio devices using arecord and aplay and everything is fine. how i can check specifically pulseaudio?
one more thing: if i run alexa and say keyword then it goes into Thinking and if i presss Ctrl Z to terminate app then next time when i run it wont run until i change USB port of my mic....is that a bug?

________________________________

**Comment by zeesh1979** [comment]
I have installed this GUI app and attached are screenshots. i have also attached the alexa logs showing nothing after Thinking state.
________________________________

**Comment by zeesh1979** [comment]
problem resolved after fresh installation. i had jasper installed on same and may be that was conflicting...thanks for help
