### ISSUE TITLE
Locale-related changes made in AlexaClientSDKConfig.json not applied in CBLAuthDelegateConfiguration.cpp in version 1.15

### ISSUE THREAD

**Issue by Akshaykumar2002** [alexa/avs-device-sdk#1535]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
In AVS SDK version 1.15, AlexaClientSDKConfig.json has been modified such that the JSON object "settings" no longer exists and its functionality is included as part of "deviceSettings" JSON object. It was in "settings" that the locale of the Alexa was being set in the older versions. This has been moved to "deviceSettings" in 1.15. 

However, in CBLAuthDelegateConfiguration.cpp, the same has not been updated (i.e.) the CBLAuthDelegate instantiation still uses the older configuration setup (from "settings"). As a result, the code pair generated always seems to use the default value ("en-US") since the code searches for the "locale" field within the "settings" JSON object, which doesn't exist in 1.15. As a consequence, the code pair generated always seems to point to the US server.

## What is the expected behavior?
The code pair generated should point to the same locale as the value present in "defaultLocale" in AlexaClientSDKConfig.json during authentication (code-based linking). For example, if the locale is "en-US," then the code pair verification URL should be https://amazon.com/us/code, and if the locale is "de-DE," the code pair verification URL should be https://amazon.com/de/code.

## What behavior are you observing?
The code pair verification URL returned is always https://amazon.com/us/code.

## Provide the steps to reproduce the issue, if applicable:
Change the "defaultLocale" field in AlexaClientSDKConfig.json from "en-US" to "de-DE". Then, try to generate the code pair for authentication again. The observation is that it'll always generate the code pair for the US region. 

### What version of the AVS Device SDK are you using?
      <1.15.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @Akshaykumar2002 ,

Thank you for reporting this issue, I have created an internal issue to get this fixed.

**Comment by Yeremiy** [comment]
Hey. Is there any solution for changing the language ?. I also tried changing in AlexaClientSDKConfig.json to es -ES, I collect it again and it returns us-US

**Comment by scotthea-amazon** [comment]
Hello @Yeremiy,

I think you are asking to solve a different but similar sounding question question here that has been answered here: https://github.com/alexa/avs-device-sdk/issues/1577

@Akshaykumar2002,

Unfortunately, the problem you reported did not get fixed in the 1.17 release.

Thank you,
-SWH

**Comment by scotthea-amazon** [comment]
Hello @Yeremiy,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH

**Comment by xcraftster** [comment]
Same problem here with changing a locate from en-US to en-GB, it just doesn't change that

**Comment by zjn0505** [comment]
Is it fixed in [1.19](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html#version-1191)?

> Fixed issue that caused CBLAuthDelegateConfiguration.cpp file to read incorrect settings
