### ISSUE TITLE
Failed to create to SampleApplication!

### ISSUE THREAD

**Issue by kedarbhise** [alexa/avs-device-sdk#1536]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Sample App fails during execution with message:
Failed to create to SampleApplication!
This is after successful build of AVS Device SDK on Raspberry Pi 3 Model B.

Here is the final output on console:
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
startsample.sh: line 3:  3837 Segmentation fault      PA_ALSA_PLUGHW=1 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

Complete log is attached as startsamplefailure.txt
[startsamplefailure.txt](https://github.com/alexa/avs-device-sdk/files/3763740/startsamplefailure.txt)

## What is the expected behavior?

1. Sample App should execute correctly.
2. I should be able to obtain a Refresh Token from AVS to allow my device to maintain a connection to Alexa Voice Service in the cloud.
## What behavior are you observing?

1. startsample.h starts execution
2. After several pages of debug information, the startsample.sh exits with message:
Failed to create to SampleApplication!

## Provide the steps to reproduce the issue, if applicable:

1. Install and configure AVS Device SDK on Raspberry Pi using the steps in the guide at:
https://developer.amazon.com/docs/alexa-voice-service/register-a-product.html
2. In the step "Get a Refresh Token", attempt to launch sample app using the command:
cd /home/pi/
sudo bash startsample.sh

### What version of the AVS Device SDK are you using?
      1.10.0 
### What is the audio output?
    HDMI
### USB microphone connected?
    No
     
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ X] Other - tell us more: Raspbian Buster

**Comment by samcoult** [comment]
Hi @kedarbhise 
Have you tried running startsample.sh without sudo? 
Also, have you tried the latest version of the SDK 1.15?

**Comment by kedarbhise** [comment]
@samcoult 

Thank you for the suggestions. I tried both of them.
Unfortunately, neither of them helped.

I think there are a few unmet dependencies that the script is not able to resolve.
My next course is to reimage the SD card, and start from scratch, using the manual method of installing all dependencies first, and then installing the SDK.

**Comment by caleighatamazon** [comment]
Based on the logs and information you've provided, this does look like a problem with your audio set up:
```
2019-10-23 17:48:01.560 [  1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9985
2019-10-23 17:48:01.569 [  1] C PortAudioMicrophoneWrapper:Failed to initialize PortAudioMicrophoneWrapper
2019-10-23 17:48:01.570 [  1] C SampleApplication:Failed to create PortAudioMicrophoneWrapper!
```

There are [quite a few closed issues](https://github.com/alexa/avs-device-sdk/issues?utf8=%E2%9C%93&q=is%3Aissue+PortAudioMicrophoneWrapper%3AFailed+to+open+PortAudio+default+stream%3AerrorCode%3D-9985) that address this PortAudio -9985 error code. It often has to do with your device's audio configuration, which is hard for us to debug since there are so many different possible ways to set these things up! We will certainly try, but it is tricky.

It is odd that you were originally able to run the Sample App just fine, though, and now you are running into this problem. I'm not sure what to make of that, if nothing else changed on your device between the two attempts. Perhaps you can look at some of the earlier issues regarding this problem and see if any of their platforms or fixes will work for you.

Let me know if you try this and if you're still having trouble. It would also be helpful if you tell me whether any of those issues worked for you!

**Comment by kedarbhise** [comment]
@caleighatamazon : Thank you for the pointers to the previous issues. I will take a look at those and report if any worked for me.

My apologies for the unclear description in my original posting. The only thing that was successful was the build of the AVS SDK. I was never able to get the Sample App to run even once.

**Comment by kedarbhise** [comment]
Thanks for the suggestions.
I understand Buster is not officially supported as of now.
As a first step, I will try the fixes mentioned, and then try using Stretch as a second resort.

**Comment by caleighatamazon** [comment]
Sounds good. I'm going to close this issue for now since this is an issue with your audio set-up on the device and not with the SDK, but if, after trying the other existing solutions, you're still having problems, please do re-open this issue and let us know what you tried and we'll keep working on it.

**Comment by tcpipchip** [comment]
Hi
I am compiled the Amazon SDK to RASPBERRY PI ZERO and when i try to execute the
`sudo bash startsample.sh`
got
![image](https://user-images.githubusercontent.com/11488460/70340257-36320a00-182f-11ea-945e-b3a60d52fd0c.png)
Looks that is not creating code to raspberry pi zero archictecture
**ILLEGAL INSTRUCTION**
can you help me ?
BTW: usb sound board working good!

**Comment by ereich1217** [comment]
The exact error you are facing is that the Sensory KWD engine does not support the processor used on the Raspberry Pi Zero.  If you disable KWD support and re-build it will run.  I have done this in the past.

You can also use the Kitt.AI KWD engine which should work on the Zero, but I haven't tried this myself.

**Comment by tcpipchip** [comment]
Can you instruct me how to disable ?  Thank you

**Comment by tcpipchip** [comment]
https://github.com/alexa/avs-device-sdk/search?q=KITTAI_KEY_WORD_DETECTOR&unscoped_q=KITTAI_KEY_WORD_DETECTOR

I changed to ON

Testing if it will solve!

**Comment by tcpipchip** [comment]
not solved :(

**Comment by manazibmahmooth001** [comment]
2021-04-24 09:50:39.135 [  d] 9 TaskThread:startThread:moniker=  d,duration=6033
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

2021-04-24 09:50:39.137 [  1] 5 DefaultClient:addBluetoothDeviceObserver::Bluetooth disabled
2021-04-24 09:50:39.152 [  1] 5 TemplateRuntime:addObserver
2021-04-24 09:50:39.175 [ 11] 5 TemplateRuntime:addObserverInExecutor
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
startsample.sh: line 3:   824 Illegal instruction     PA_ALSA_PLUGHW=1 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

please fix this error 
rasbian stretch os 

microphone work perfectly
