### ISSUE TITLE
Amazon Music Stops when SampleApp reconnects to Amazon server

### ISSUE THREAD

**Issue by zoe0805** [alexa/avs-device-sdk#1537]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Amazon Music stop when SampleApp reconnects to Amazon server.
SampleApp reconnects to Amazon server approximately once an hour. 
At that time, If the audio state is FINISHED, next song will not be played.
I would like to to know how to fix this issue.

The debug5 log: [Raspi3.Debug5.log.txt](https://github.com/alexa/avs-device-sdk/files/3766007/Raspi3.Debug5.log.txt)
This issues: Line18445～

## What is the expected behavior?

・Amazon Music does not stop when SampleApp reconnects to Amazon server.
・Amazon Music is played continuously for more than 8 hours.

## What behavior are you observing?

When SampleApp reconnects to Amazon server and Audio State is FINISHED.

## Provide the steps to reproduce the issue, if applicable:

１．Launch SampleApp.
２．Play Amazon Music and leave it for an hour or more.

### What version of the AVS Device SDK are you using?
      <1.12.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @zoe0805 , are you seeing this issue with the latest version of the sdk (1.16)?

**Comment by zoe0805** [comment]
Hi @samcoult 
Thank you for your reply.
I will confirm SDK (1.16).

**Comment by zoe0805** [comment]
I've confirmed that It occurs in 1.16. But I could not get a debug log.

**Comment by scotthea-amazon** [comment]
@zoe0805,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
