### ISSUE TITLE
Long playback for pandora music - stops after 6 hours

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1538]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

This is log when I play pandora music from Taiwan site by US VPN
[sampleapp_20191024084751_pandora_longtest_fail.zip](https://github.com/alexa/avs-device-sdk/files/3766404/sampleapp_20191024084751_pandora_longtest_fail.zip)
It seems the music stop after line 603654.

## What is the expected behavior?

Alexa should play pandora music for more than 8+ hours.

## What behavior are you observing?

It stop at 6hr when it connecting server

## Provide the steps to reproduce the issue, if applicable:

alexa,play music from pandora

### What version of the AVS Device SDK are you using?
      <0.15.0>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux - Ubuntu 16.04
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Thanks for bringing this to our attention and providing the logs. We believe this is related to a bug we are currently tracking, and plan to fix in a later release. We'll provide an update when we have one. Thanks!

**Comment by yuan0258** [comment]
@caleighatamazon,
We found the avs log will reconnect to AVS server about 1hr during longtest with pandora
Event we use ethernet to replace wifi.
Does it’s normal behavior?
Log: https://github.com/alexa/avs-device-sdk/files/3766404/sampleapp_20191024084751_pandora_longtest_fail.zip
               Line 422: 2019-10-24 00:47:58.079 [  3] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 108161: 2019-10-24 01:45:25.834 [ 8a] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 202587: 2019-10-24 02:38:44.976 [ d3] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 301913: 2019-10-24 03:38:55.114 [123] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 402035: 2019-10-24 04:34:45.237 [178] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 503699: 2019-10-24 05:25:52.363 [1d5] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 603616: 2019-10-24 06:21:32.212 [22c] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS
               Line 604980: 2019-10-24 07:20:07.350 [23a] 5 HTTP2Transport:setStateLocked:newState=CONNECTING,changedReason=SUCCESS

**Comment by caleighatamazon** [comment]
Yes, it's expected that that the SDK Sample App to reconnects the AVS server about once per hour.

**Comment by yuan0258** [comment]
Why SDK Sample App need to reconnect the AVS server about once per hour?
What's the purpose?

**Comment by yuan0258** [comment]
https://developer.amazon.com/docs/alexa-voice-service/manage-http2-connection.html
Connection timeouts: If your HTTP2 client has connection pooling or marks connections as idle, adjust the timeout so the connection is not disrupted. If the connection is disrupted, make sure to complete the flow described for creating a connection, which includes re-establishing the downchannel stream and synchronizing state with AVS. Set the timeout to at least 60 minutes to ensure that your connection is not prematurely closed.
=======================================================
My question is when sampleapp play music from pandora. Why it will trigger 1hr timeout?
It seems the downchannel stream receive directives from MSP continuously

**Comment by yuan0258** [comment]
https://developer.amazon.com/docs/alexa-voice-service/manage-http2-connection.html
Connection timeouts: If your HTTP2 client has connection pooling or marks connections as idle, adjust the timeout so the connection is not disrupted. If the connection is disrupted, make sure to complete the flow described for creating a connection, which includes re-establishing the downchannel stream and synchronizing state with AVS. Set the timeout to at least 60 minutes to ensure that your connection is not prematurely closed.

My question is when sampleapp play music from pandora. Why it will trigger 1hr timeout?
It seems the downchannel stream receive directives from MSP continuously

**Comment by scotthea-amazon** [comment]
Hi @yuan0258,

Alexa voice service triggers reconnects about once an hour as part of maintaining the health of the service.

AudioPlayer music is generally delivered through a separate connection provided by a music service provider.

Best regards,
-SWH

**Comment by yuan0258** [comment]
Hi scotthea-amazon,

Is there another way to check overnight play stop problem?(network or MSP problem or SDK)
Does AVSSDK 1.15 or 1.16 pass play Pandora music over 8hr?

**Comment by samcoult** [comment]
Hi @yuan0258 

I am going to close this issue due to inactivity. Please open a new issue if necessary.
