### ISSUE TITLE
TuneIn Radio

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#154]
When I ask for a radio station such as "KEXP on TuneIn", it repeats error phrase twice "KEXP on TuneIn radio is not available right now".  Pretty sure it wants to re-direct based on the link returned from TuneIn.  Using VLC as a client doesn't have this problem, as it manages the re-direct.

    2017-09-12 22:54:29.060 [  2] E MediaPlayer:handleBusMessageError:source=decoder,error=Your GStreamer installation is missing a plug-in.,debug=gsturidecodebin.c(1006)\: no_more_pads_full ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder\:
    no suitable plugins found\:
    gstdecodebin2.c(4565)\: gst_decode_bin_expose ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder/GstDecodeBin\:decodebin10\:
    no suitable plugins found\:
    Missing decoder\: text/uri-list (text/uri-list)
    
    2017-09-12 22:54:29.060 [  2] 0 MediaPlayer:callingOnPlaybackError:error=Your GStreamer installation is missing a plug-in.
    2017-09-12 22:54:29.060 [  2] E MediaPlayer:handleBusMessageError:source=queue2-10,error=Internal data flow error.,debug=gstqueue2.c(3010)\: gst_queue2_loop ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder/GstQueue2\:queue2-10\:
    streaming task paused\, reason not-linked (-1)
    2017-09-12 22:54:29.060 [  2] 0 MediaPlayer:callingOnPlaybackError:error=Internal data flow error.

**Comment by sanjayrd** [comment]
Hi @INRIX-joel-winarske,

It seems to be an issue with parsing the URL (containing a playlist) returned from TuneIn. In the latest release (1.0.2), we don't support TuneIn yet, only iHeartRadio. The reason for this is that we integrated with a 3rd party library, Totem Playlist Parser, to extract URLs, and this library doesn't doesn't work on all platforms and has been a bit shaky for us. That being said, we do have support for using this library. See PlaylistParser/CMakeLists.txt for more info. You'll need to define the `TOTEM_PLPARSER` variable in your cmake command and link it in.

In our upcoming release, we plan on replacing this with our own PlaylistParser with capabilities of parsing remote URLs containing multiple URLs. I've testing the behavior you just described above and I've been able to play the station as expected. Hope that clarifies things.

Thanks,
Sanjay

**Comment by INRIX-joel-winarske** [comment]
Hi @sanjayrd 
Building with -DTOTEM_PLPARSER=ON addressed the problem.

What's the timeline for the updated PlaylistParser?  Also what are the other planned fixes/features?

Thanks,
Joel

**Comment by sanjayrd** [comment]
@INRIX-joel-winarske,

The timeline is approximately 4 weeks. The major feature will be the PlaylistParser, which should help out with a lot of the music provider issues we've been seeing. Other features will be bug fixes and minor improvements.

Thanks,
Sanjay
