### ISSUE TITLE
Multiple devices are not showing online in Alexa companion app

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1540]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

If there are two devices authorized with the same account,then only one account is being shown in Alexa companion app.

## What is the expected behavior?

If more than one device is authorized with the same account ,then all the devices must be shown online in Alexa companion app.

## What behavior are you observing?

If two devices are authorized with same amazon account, only one device is being shown as online in alexa companion app and the other device as offline..
## Provide the steps to reproduce the issue, if applicable:

Do CBL authorization of the both the devices with the same amazon account.
### What version of the AVS Device SDK are you using?
      <x.y.z>
sdk-version 1.12.0
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [. ] Other - tell us more:
android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ .] Other - tell us more:
Pie

**Comment by samcoult** [comment]
Hi @dipalisb ,
Are both devices registered with the same device ID?

**Comment by dipalisb** [comment]
Yes @samcoult ,
Both the devices are registered with same ID.

**Comment by caleighatamazon** [comment]
Hi @dipalisb, just to double-check: The devices have the same clientID, productID, and device serial number?

Devices require unique serial numbers but it's okay to have the same clientID and productID.

These values are set in alexaClientSDKConfig.json.

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
Yes all these values are same. We are using json for all our devices.

**Comment by caleighatamazon** [comment]
Hi @diaplisb, this might be your problem, then. All those values should *not* be the same; that is, the device serial numbers need to be different between the two devices. Can you try using two different serial numbers for each device and see if that solves your problem?
