### ISSUE TITLE
Error building AVS SDK with APL

### ISSUE THREAD

**Issue by ssalexa** [alexa/avs-device-sdk#1541]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When I build the library with the command I receive an error stating that something is wrong with a CMakeLists.txt file on line 19 at "asdk_install()". Same issue here but no solution posted: https://github.com/alexa/avs-device-sdk/issues/803

Would you please help? 

### What version of the AVS Device SDK are you using?
1.15

### Tell us what hardware you're using:
Mac

### Tell us about your OS (Type & version):
MacOS

**Comment by samcoult** [comment]
Hi @ssalexa , which version of MacOS are you using?

Have you executed all of the steps in this guide? https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

**Comment by ssalexa** [comment]
> Hi @ssalexa , which version of MacOS are you using?
> 
> Have you executed all of the steps in this guide? https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

I am using Mojave (10.14.6). I have followed instruction to set up AVS SDK.

**Comment by caleighatamazon** [comment]
Hi @ssalexa, may I ask where you accessed CapabilityAgents/AlexaPresentation/src/CMakeLists.txt? It's not part of our repo here on Github (see Capability Agents here: https://github.com/alexa/avs-device-sdk/tree/master/CapabilityAgents)

**Comment by ssalexa** [comment]
> Hi @ssalexa, may I ask where you accessed CapabilityAgents/AlexaPresentation/src/CMakeLists.txt? It's not part of our repo here on Github (see Capability Agents here: https://github.com/alexa/avs-device-sdk/tree/master/CapabilityAgents)
