### ISSUE TITLE
Missing quotation marks in macOS Setup command

### ISSUE THREAD

**Issue by ymarggraf** [alexa/avs-device-sdk#1543]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The closing quotation marks are probably missing in the documentation to setup the sampleApp for macOS. The command there is:
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/_path-to-openssl_/lib/pkgconfig:$PKG_CONFIG_PATH

## Provide the steps to reproduce the issue, if applicable:

The correct command could be (?):
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/_path-to-openssl_/lib/pkgconfig:$PKG_CONFIG_PATH"

### What version of the AVS Device SDK are you using?
      <not relevant>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Yes, you're right, this is definitely an error in our documentation! I'll file an internal ticket to get this fixed in the future. Thanks!

I'm going to close this issue for now, but feel free to re-open if you have more questions.

**Comment by caleighatamazon** [comment]
Fixed! :)
