### ISSUE TITLE
Can not change input and output on Raspberry pi

### ISSUE THREAD

**Issue by LynSolv** [alexa/avs-device-sdk#1544]
Hi all,

I have a quick issue and probably there is an easy solution that I'm not seeing but hopefully you can help me, 

I'm building a system using a Raspberry pi 3 B+ where I have a USB microphone for input , a miniDSP USBstreamer for output of the avs and other media using alsa dmix. To my understanding if I change the default pcm on the alsa configuration file ".asoundrc" the SampleApp should use that default device as input and output. 

But when I connect the USBStreamer and change the ALSA configuration file to use the usb microphone and the USB streamer output it uses the input of the USBStreamer and the onboard audio. if I use aplay and arecord its using the new alsa default device, so the configuration file is working outside the sample app.  

I build the raspberry pi Sample app using the  Raspberry Pi Quick starting guide using the bash script setup.sh. The sdkVersion is 1.16.0. As i mentioned I'm using a Raspberry pi with Raspbian version Buster headless.

Any help Is appreciated.

Best Regards

**Comment by ereich1217** [comment]
When you run SampleApp do you use sudo with it?  If so then the
/home/pi/.asoundrc isn't the file being used, but /root/.asoundrc . I
usually create a link from /root/.asoundrc to /home/pi/.asoundrc to solve
this problem.

**Comment by caleighatamazon** [comment]
Hi @LynSolv, @ereich1217 has a good idea. Let us know if trying that resolves the issue for you. Thanks!

**Comment by LynSolv** [comment]
@ereich1217  yeah that was the issue, Thanks a lot! =)

**Comment by caleighatamazon** [comment]
Great! Closing this issue.
