### ISSUE TITLE
Indication LEDs not working (GPIO not accessible from UIManager.cpp)

### ISSUE THREAD

**Issue by arjun312** [alexa/avs-device-sdk#1545]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I followed https://developer.amazon.com/docs/alexa-voice-service/indicate-device-state-with-leds.html .
Led connected for indicating alexa listening mode not working, I wrote a separate script to check the working of the circuit and it works. I guess it is problem in accessing GPIO using wiringpi with cpp or maybe it is because of Raspbian buster (I'm using RPi4 4gb variant). 

### What version of the AVS Device SDK are you using?
Version 1.16
firmware version:
(output from f command while running startsample)
      2019-10-30 12:19:16.505 [ 2c] 5 SoftwareInfoSender:setFirmwareVersion:firmwareVersion=21

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [*] Other - tell us more: Raspbian Buster

**Comment by caleighatamazon** [comment]
We don't officially support Raspbian Buster, so that could be the problem. Could you delete your build folder and re-build (re-run cmake and then make) for the Sample App, and share your logs here? I want to make sure that the WiringPi library is being added correctly.

**Comment by arjun312** [comment]
Thank you, I just made it work using python script run in cpp. so closing the issue.

**Comment by farhandsome** [comment]
Hey @arjun312,

Good work on getting this to run! Can you share more about how you integrated Python code into the CPP script? I'm wanting to do this, but with an addressable LED strip.

**Comment by arjun312** [comment]
I just coded in python for the led strip and made it run using system commands in cpp. Thats all
