### ISSUE TITLE
Volume change does not react immediately and sometime jump back to last volume level in Alexa app.

### ISSUE THREAD

**Issue by viru9289** [alexa/avs-device-sdk#1546]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When we are trying to change the volume using Alexa Companion App,then the volume is not being reflected immediately and some times it is jumping to last volume level.

## What is the expected behavior?

If we are changing the volume from Alexa companion App then that should be reflected in the device immediately.

## What behavior are you observing?

It is taking time to reflect in the device,(Less than a minute) but not immediately.

## Provide the steps to reproduce the issue, if applicable:

Ask "Alexa play songs from **** music.
Change volume from Alexa companion app.

### What version of the AVS Device SDK are you using?
      <x.y.z>
avs sdk 1.12.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [. ] Other - tell us more:
Pie 9.0

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
Please find the log attachment.
[volume_log_avs_14.txt](https://github.com/alexa/avs-device-sdk/files/3803420/volume_log_avs_14.txt)
