### ISSUE TITLE
Music long playback stops in 1 hour, BUFFER_UNDERRUN in AudioPlayer

### ISSUE THREAD

**Issue by pple6771** [alexa/avs-device-sdk#1547]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

MSP was iHeartRadio.
Music Playback stops in 1 hours. I checked the log file
and I found a lot of BUFFER_UNDERRUN errors in AudioPlayer.

## What is the expected behavior?

Music should play over 8+ hours

## What behavior are you observing?

Music playback stopped in 1 hour

## Provide the steps to reproduce the issue, if applicable:

Alexa, play katy perry on iHeartRadio

### What version of the AVS Device SDK are you using?
      <1.16>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
Android
and We are using AndroidSLESMediaPlayer

[log12_57.txt.zip](https://github.com/alexa/avs-device-sdk/files/3792993/log12_57.txt.zip)

**Comment by caleighatamazon** [comment]
Hi @pple6771, thanks for providing these logs. I've created a ticket for this to track internally and I'll let you know when we have any update.

**Comment by scotthea-amazon** [comment]
Hello @pple6771,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
