### ISSUE TITLE
When we tested MRM, we found the error HTTP error 502 Bad Gateway and the music can't play.

### ISSUE THREAD

**Issue by ada1013** [alexa/avs-device-sdk#1554]
## Briefly summarize your issue:
We have merged the MRM lib to our own devices, but when we tested the MRM function, seems there are some error so that our devices can't play music as our expectation. Please review the log and any suggestion would be appreciated. 
[avs.log](https://github.com/alexa/avs-device-sdk/files/3818921/avs.log)

## What is the expected behavior?
Play MRM music with others devices in the same group on our devices.

## What behavior are you observing?
After Alexa said right response, there was no music.

## Provide the steps to reproduce the issue, if applicable:
1. added my device and echo dot in the same group, and in the same local network.

### What version of the AVS Device SDK are you using?
      <1.14.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.
