### ISSUE TITLE
Problem with stop streaming microphone data

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1555]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, all:
We have implemented AVS on Android system recently. We get some problems, but they are not easily to be classified to SDK problems.

This is a problem we think more dependent on SDK.
When we stop the streaming microphone data, the mediaserver will crash. Although, we can start the streaming microphone data again cause the mediaserver will restart.

Can help us to confirm this situation?

Here is the log:
[microphone_off.TXT](https://github.com/alexa/avs-device-sdk/files/3822680/microphone_off.TXT)
Thanks~~
## What is the expected behavior?

The mediaserver should not crash.

## What behavior are you observing?

The mediaserver will crash.

## Provide the steps to reproduce the issue, if applicable:

Stop streaming microphone data from SampleApp.

### What version of the AVS Device SDK are you using?
      <1.14.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: embedded with wifi

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android P

**Comment by mvelegon-amzn** [comment]
Hi @elfdie00475 unfortunately we will not be able to assist you without fully understanding the changes you made to the SDK to support your use case. Could you give us more context on the changes that were made to V1.14 SDK ?

**Comment by elfdie00475** [comment]
Hi @mvelegon-amzn,
we only modify the SampleApp. The core is the same on V1.14.

And we confirm that the AndroidQueue will not update again when the issue happened.
Hope, it can be helpful.

Thanks~~
