### ISSUE TITLE
Read microphone stream data timeout on Android system

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#1556]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi all:

We get the problem at playing Amazon music.
We played Amazon music for a while and we tried to wake up AVS by using voice, but AVS didn't wake up. 
We checked the log and we found the keyword detector process always show the error message "readFromStreamFailed". We tried to restart SampleApp and do the same step, the same problem happened again.
Here is the log: 
[ReadMicrophoneStreamTimeout.TXT](https://github.com/alexa/avs-device-sdk/files/3823821/ReadMicrophoneStreamTimeout.TXT)

When we do this test, we use the USB ethernet port to connect the network. Does the USB ethernet port affect this problem happened? 

Can help us to fix it?
Thanks~~
## What is the expected behavior?

AVS can be waked up by voice when AVS is playing the music.

## What behavior are you observing?

AVS can't be waked up by voice.

## Provide the steps to reproduce the issue, if applicable:

1. Play the music for a while. (In the log, we play the music about 3 minutes)
2. Ask the weather by using voice to wake up AVS.
3. Check the log, does have the error message "readFromStreamFailed:reason=readerTimeOut". (In line 16883).
### What version of the AVS Device SDK are you using?
      <1.14.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: embedded with wifi

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android P

**Comment by mvelegon-amzn** [comment]
Hi @elfdie00475 Looking at the logs there is nothing obvious that stands out. We would need more information to debug this issue. Could you let us know if this is happening consistently? Are there several changes made to the version of the SDK you are running compared to V1.14?

**Comment by elfdie00475** [comment]
Hi @mvelegon-amzn,
1. yes, this is happening consistently
2. we only modify the SampleApp. The core is the same on V1.14.

And we confirm that the AndroidQueue will not update again when the issue happened.
Hope, it can be helpful.

Thanks~~
