### ISSUE TITLE
section 3.2 - raspberry pi quick start guide

### ISSUE THREAD

**Issue by pappy15** [alexa/avs-device-sdk#156]
Hi,

I'm trying to get the avs device sdk work on my raspberry pi 2 with raspbian jessie.
I followed the instructions from the quick start guide and now I'm stuck at section 3.2.
The cmake command shows the following issue:

cmake $SDK_SRC -DSENSORY_KEY_WORD_DETECTOR=ON-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=$LOCAL_BUILD/lib/libsnsr.a-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=$LOCAL_BUILD/include-DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON
cmake: /home/pi/local-builds/lib/libcurl.so.4: no version information available (required by cmake)
Creating the build directory for the AlexaClientSDK with build type: RELEASE
Creating AlexaClientSDK with keyword detector type: Sensory
CMake Error at build/cmake/PortAudio.cmake:15 (message):
  Must pass library path of PortAudio to enable it.
Call Stack (most recent call first):
  build/BuildDefaults.cmake:31 (include)
  CMakeLists.txt:7 (include)

-- Configuring incomplete, errors occurred!
See also "/home/pi/BUILD/CMakeFiles/CMakeOutput.log".

Hope someone can help me.
Thanks

**Comment by sanjayrd** [comment]
You'll also need to pass the path of the portaudio lib. See the following example:

`-DPORTAUDIO=ON
-DPORTAUDIO_LIB_PATH=$LOCAL_BUILD/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD/include`

Thanks,
Sanjay
