### ISSUE TITLE
Device 1 doesn't sync with another DUT2's status

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1560]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
This is a know bug in V1.12 but on V1.15 & 1.16, this issue is fixed. So, we need the patch of this implementation which can be applied on v1.12.

The exact scenario from AVS SDK which is fixed on v1.15.0 released 09/25/2019
**

> Fixed issue: notifications failed to sync upon device initialization. For example, let's say you had two devices - one turned on and the other turned off. After clearing the notification on the first device, it still showed up on the second device after turning it on.

**
Please do provide a patch which can be applied on avs-sdk v1.12.0

## What is the expected behavior?
 For Device 1, when it is powered back on, there is no audio or visual indicator for Notifications.

## What behavior are you observing?
Device 1 doesn't sync with another DUT2's status
still show Notifications LED

## Provide the steps to reproduce the issue, if applicable:
[Precondtion]:
1.You have the device under test (Device1) and an Amazon Alexa product (Device2). You have registered both with the same Amazon account.
2.You have just completed the prior test. Devices 1 and 2 are on, and both show the visual cue for Notifications.
1. Turn Device 1 off.
2. To Device 2, ask Alexa for your notifications. (What are my notifications?)
3. Turn Device 1 on.

### What version of the AVS Device SDK are you using?
V1.12

### Tell us what hardware you're using:
- [ ] Other CDR8010

### Tell us about your OS (Type & version):

- [ ] Other - Android Pi

**Comment by dhpp** [comment]
Hi @dipalisb.  I would suggest the following approach - take the 1.16 code from CapabilityAgents/Notifications, and simply replace the 1.12 version with that, and then let us know if there are further compile / interface problems that result (which cannot be trivially resolved).  The Notifications CA should be fairly decoupled from other SDK changes which will have been made.

I would add though that updating to the current version of the SDK is highly recommended to pick up other fixes and also new features.

Let us know if you need further assistance, thanks.

**Comment by dipalisb** [comment]
Hi @dhpp ,
I had tried replacing the CapabilityAgents > Notifications folder of the v1.16. 
As expected, there were some dependency errors. Please go through the screens attached for the errors, as a reference: (AvsSdkError_1 & 2):

> ![AvsSdkError_1](https://user-images.githubusercontent.com/52921278/68992592-77b84080-0893-11ea-8d41-e2db7b429916.png)
> ![avsSdkError_2](https://user-images.githubusercontent.com/52921278/68992593-7c7cf480-0893-11ea-940a-ccf6eac61041.png)

Can you please upload a patch for CapabilityAgents > Notifications of the latest version v1.16 or v1.15  which can be applied over v1.12.

Thanks.

**Comment by caleighatamazon** [comment]
Hi @dipalisb, we don't typically support patches in this way. Please reach out to your AVS Solutions Architect for the patch approval process if needed. I'm going to close this issue.
