### ISSUE TITLE
Work with a SIP device to support phone call

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#1561]
I know Echo connect can work with Echo compatible devices to provide phone call service.  The SDK also provide some UI interface for phone call, but it lack some component. We decide to make our Alexa device to work with another SIP device to provide phone call service. Can you share some guidance on how to implement that?

**Comment by dhpp** [comment]
Hi @subjectxbj.  This is a feature the SDK supports, but is not publicly available by default.

Please contact your Amazon Business Development Representative or use the [intake form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) to reach out directly regarding enabling the VoIP Communication features.
