### ISSUE TITLE
Unplugged device never goes offline

### ISSUE THREAD

**Issue by BrunoLaine** [alexa/avs-device-sdk#1562]
## Briefly summarize your issue:
If the device is unplugged while playing Amazon music, the application doesn't realize that the device has gone offline. 

## What is the expected behavior?
The device should be marked offline in the Amazon app and the progress bar should be stopped on the Amazon Music app.

## What behavior are you observing?
The progress bar is not stopped and the device is marked online in the Amazon application for at least 10 minutes.

## Provide the steps to reproduce the issue, if applicable:
Play music on the device on Amazon Music and unplug the device.

## Tell us about your environment:
This is a custom distribution based on linux but also reproduced on the echo dot 3. I couldn't reproduce on the SampleApp with a kill -9.

### What version of the AVS Device SDK are you using?
      v1.14

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @BrunoLaine.  Unfortunately, this is not really an SDK issue (which is strictly client side), but rather is cloud side, so we cannot directly address it.  I would suggest you bring the issue to the following forum:

[https://forums.developer.amazon.com/topics/feature+request.html](https://forums.developer.amazon.com/topics/feature+request.html)

and ask them there.  Thanks.

**Comment by BrunoLaine** [comment]
Thanks for you reply, I will open the issue there
