### ISSUE TITLE
When Timer,reminder and alert are ringing no clue from where the audio cue is coming from 

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1567]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When we set a timer to ring continuosly for one hour.The audio cue is ringing continuosly, however there is no clue or logcats from where the audio cue is coming from.
## What is the expected behavior?

In order to blink LED continuosly whenever the timer is set. One should know from where the audio cue is coming from 
## What behavior are you observing?

LED is blinking only once and then go off.
### What version of the AVS Device SDK are you using?
      <x.y.z>
avs sdk 1.12
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
android pie 9.0

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [. ] Other - tell us more:
pie 9.0

**Comment by dipalisb** [comment]
HI,
Is there any update on this issue.
Thanks,

**Comment by kjkh** [comment]
Hi @dipalisb,

If you wish to know when a Timer has stared or stopped, you can subscribe your application to be an observer to receive these callbacks. More specifically, you will receive callbacks when the state of the alert (including Timers and Reminders) changes. Please take a look at:

https://github.com/alexa/avs-device-sdk/blob/ea3ebdb6e75e04ad59d260607aea209c17423682/ApplicationUtilities/DefaultClient/src/DefaultClient.cpp#L1178

and

https://github.com/alexa/avs-device-sdk/blob/ea3ebdb6e75e04ad59d260607aea209c17423682/CapabilityAgents/Alerts/include/Alerts/AlertObserverInterface.h.

**Comment by dipalisb** [comment]
Hi @kjkh ,
We have tried keeping logs  in above mentioned 

avs-device-sdk/ApplicationUtilities/DefaultClient/src/DefaultClient.cpp
Line 1178 in ea3ebdb
file.
We are not getting any logs from this function when timer or reminder is set.
Thanks,

**Comment by dipalisb** [comment]
Hi @kjkh ,
We want to add LED implemetation for alerts,reminder and timer so that whenever alert is set LED should blink parallely with the audio cue.
In amazon forum, it is mentioned that alert has to ring continuosly for one hour though internet is disconnected. And there is some offline URL for ringing the audio cue.
Can you please confirm where can we implement our Led changes to make the Led and audio cue parallel.
Thanks,

**Comment by kjkh** [comment]
Hi @dipalisb,

`DefaultClient::addAlertsObserver` is a method to subscribe to `AlertObserverInterface::onAlertStateChange`, but the function itself does not get called when an alert renders. You will need to create a class which implements AlertObserverInterface, and add that class with `DefaultClient::addAlertsObserver`.

For an example of this pattern, please refer to our reference application implementation: https://github.com/alexa/avs-device-sdk/blob/ea3ebdb6e75e04ad59d260607aea209c17423682/SampleApp/src/SampleApplication.cpp#L721-L727.

**Comment by dipalisb** [comment]
Hi @kjkh ,

Thanks for the response.

We can create a class which implements AlertObserverInterface.
But,for blinking LED continuosly we need to know from where audio cue is coming.
If we create a class also we don't know from where audio cue is coming.
When Alert is started or stopped  we are getting trigger from 
https://github.com/alexa/avs-device-sdk/blob/ea3ebdb6e75e04ad59d260607aea209c17423682/CapabilityAgents/Alerts/src/Alert.cpp#L402
but,when alert is ringing continuosly we are not getting any trigger or from where the audio cue is coming.
Once,if we know that from paritcular function or class the triger is coming then,we can call the functionality required for Led implementation for Alerts.

Thanks,

**Comment by dipalisb** [comment]
Hi,
Is there any update on this issue.

**Comment by dipalisb** [comment]
Hi @kjkh ,
Could you please help us with this issue.

**Comment by celinval** [comment]
Hi @dipalisb, I'm not sure I understand the problem.

Have you tried to subcribe an AlertObserver which starts / stops the LED blinking according to the Alert state change?

For example, when your timer goes off, you should get a notification that one of your Alerts state has changed to. The SDK will call onAlertStateChange() method where the parameter `alertType` in this case will be "TIMER" and the state will be STARTED. Your observer implementation is now able to tell that a timer has gone off and it should start the LED blinking mode. Once the timer is cancelled / stopped, you should get another call to onAlertSateChange() telling the new state and you should be able to stop the LED from blinking.

**Comment by dipalisb** [comment]
Hi @celinval ,
Yes.  I am able to get logs when Alert starts and stops.
But,when Alert is set for example say ,timer then it will continuosly give audio cue for one hour and then stops.
I am able to get trigger only when Alert is started and  stopped but, Iam not able to get continuosly trigger when timer is ringing for one hour.
I would like to know from where the audio cue is coming.So that I can implement the Led changes in that function.
Thanks,

**Comment by dipalisb** [comment]
Hi @celinval ,
Is there any update on this issue.
Thanks,

**Comment by kclchan** [comment]
Hi @dipalisb, `alertType` has been added in `onAlertStateChange()` [callback](https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/Alerts/include/Alerts/AlertObserverInterface.h#L73).  Would this be sufficient for your use case?

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please feel free to comment on this issue or open a new one if you continue to have problems. Thanks!
