### ISSUE TITLE
linking skill session to specific device.

### ISSUE THREAD

**Issue by Genoil** [alexa/avs-device-sdk#1568]
We are building a Custom Skill that needs to be aware which specific device invocated it. As we are in development, all our Raspberry Pi clients running a modified version SampleApp are authorized under the same AVS account we are using to develop the skill.

We would expect that in the skill lambda backend, the Requestenvelope.context.system.device.deviceId would be unique per device, but it appears to be identical for different devices.

- we tried using different serial numbers (-s parameter) for each device build. no effect.
- we tried creating a different AVS product with unique config.json for each device. no effect.

It doesn't really matter for us which property in the Requestenvelope we use to uniquely identify a specific device, it could also be userId, apiAccessToken or anything else, as long as we can trace back a link to any of our devices. 

Is it at all possible to achieve this? Or do we have to duplicate our skill / duplicate our development account?

**Comment by kjkh** [comment]
Hi @Genoil ,

Unfortunately this is outside the scope of the SDK, as we do not control the identification scheme per device. You will receive better support by asking your question in the AVS Forums:

https://forums.developer.amazon.com/topics/alexa+skills+kit.html

If you have any further questions please feel free to reopen the ticket.
