### ISSUE TITLE
Integration Spotify with AVS

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1570]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We need to integrate spotify with our AVS enabled device.

## What is the expected behavior?
Need steps to integrate spotify. What would be the compilation steps or flags which would be use to compile alexa with spotify.

## What behavior are you observing?
After linking spotify premium account with our companion app, user can listen song via Spotify. 
For eg:- 
Alexa, play spotify 
Then if spotify is linked then music should streaming from spotify

## Tell us about your environment:
AVS SDK Version 1.14.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### What version of the AVS Device SDK are you using?
1.14.0

### Tell us what hardware you're using:
Other: Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

### Tell us about your OS (Type & version):
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by kjkh** [comment]
Hi @mohitbansal19,

This issue can be better resolved by contacting your Amazon Business Development Representative and working with us through the appropriate channels. Closing the ticket, but please feel free to reopen if you have further questions.
