### ISSUE TITLE
brightness level of light

### ISSUE THREAD

**Issue by mduzgun** [alexa/avs-device-sdk#1571]
I need brightness level of light.

 I take temperature value from AVS, but I can't obtain brightness level of light

Is there any command for it?

For example, what is brightness of light, etc

**Comment by kjkh** [comment]
Hi @mduzgun,

Can you provide further detail on your use case so we can better support you? How are you obtaining the temperature from AVS?

**Comment by mduzgun** [comment]
"what is the temperature in house" command obtains temperature from AVS. 
For example, I have a light connected Alexa. 
I want to know current on-off status and brightness of light. 
For Google home, I can use "what is brightness of light", then I can get to know brightness level of light.
Which command I can use for brightness of Alexa connected light?

**Comment by celinval** [comment]
Hi @mduzgun, please use [Amazon's Help and Customer Service](https://www.amazon.com/gp/help/customer/display.html?nodeId=508510&ref_=nav_em_T1_0_1_0_5_cs_help) for questions about Alexa utterances and behavior. This forum is dedicated for the AVS Device SDK.

Best,
Celina
