### ISSUE TITLE
long time to resume "play Joe Rogan Experience on TuneIn"

### ISSUE THREAD

**Issue by dpinarello** [alexa/avs-device-sdk#1573]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The SDK needs long time to play Joe Rogan Experience on TuneIn
same issue: https://github.com/alexa/avs-device-sdk/issues/1050

## What is the expected behavior?
Resume in short time

## What behavior are you observing?
The time to resume depend on offset to resume. If the offset is more than 10 minutes, it needs about 20/30 seconds or more (depend on net speed) to resume.

## Provide the steps to reproduce the issue, if applicable:

1. "Alexa play Joe Rogan Experience on TuneIn"
2. wait 6 minutes
3. "Alexa stop"
4. wait 2 minutes
5. "Alexa resume"
6. wait 16 minutes
7. "Alexa play <podcast_name> on TuneIn"
8. wait 16 minutes
9. "Alexa play Joe Rogan Experience on TuneIn"
10. "Alexa stop"

## Tell us about your environment:

      <1.14>
      <1.16>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: imx7

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: yocto thud with linux kernel

**Comment by scotthea-amazon** [comment]
Hello @dpinarello ,

Thank you for bringing this to our attention.  As you mentioned in your description, this is a known issue.  We still hope to address it in a future release.

Best regards,
-SWH

**Comment by dpinarello** [comment]
Hello @scotthea-amazon ,

thanks for your reply, the future release is 1.17 just released, or another future ones?
This mean that, at this moment, the behavior is this?

Best Regards,
Damiano

**Comment by caleighatamazon** [comment]
It was not fixed in 1.17 or 1.18, unfortunately.

**Comment by scotthea-amazon** [comment]
Hello @dpinarello,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
