### ISSUE TITLE
Alexa Calling feature help

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1574]
## Briefly summarize your issue:
We want to integrate Alexa calling feature into our device. Is this supported in present SDK as we are using avs-1.14.0?

## What is the expected behavior?
We want Alexa calling feature as it runs on Amazon Echo devices. 
But now when we ask Alexa to call then response is "Not supported at your device". 

## Tell us about your environment:
AVS SDK Version 1.14.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### What version of the AVS Device SDK are you using?
1.14.0

### Tell us what hardware you're using:
Other: Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

### Tell us about your OS (Type & version):
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by scotthea-amazon** [comment]
Hello @mohitbansal19,

Integration of Alexa Calling requires special permissions.  Please use the following form to request access to this feature: [Contact AVS Device SDK Team](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268)

Best regards,
-SWH

**Comment by mohitbansal19** [comment]
Thanks for help.

**Comment by syedfaisal5** [comment]
I have compiled Alexa SampleApp from Alexa AutoSDK version 2.1 . When i am saying  " Alexa, Call XYZ", the response i am getting is "calling with alexa is not supported on this device, u can use alexa app for calling ". How can i make SampleApp for calling. What special permission is required and how it will help for successfull integration Alexa Calling.
**GitHub Link for Log :** 
https://github.com/syedfaisal5/Programming/blob/master/DeviceDOesntSupportCalling.txt
