### ISSUE TITLE
When can you support 64bit cpu architecture on Android platform?

### ISSUE THREAD

**Issue by WksKing** [alexa/avs-device-sdk#1576]
Hi,

I know the current SDK version(v1.16) doesn't support 64bit CPU, I'd like to know when can you support 64bit? or Do you have a plan to support 64bit architecture in the future?

Regards!
King

**Comment by scotthea-amazon** [comment]
Hi @WksKing,

Our team is looking in to supporting this in a future release of the SDK, but we do not have a public release date for it at this time.

Best regards,
-SWH

**Comment by WksKing** [comment]
Hi @scotthea-amazon ,
Thanks for your reply. I will close the issue.

Thanks.
