### ISSUE TITLE
android 8.1        1、Alexa is currently idle!   2、ask"play music hero" 3、answer"not support this device"

### ISSUE THREAD

**Issue by storm8888** [alexa/avs-device-sdk#1580]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello @storm8888,

Access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

You can also try playing music with other music providers like iHeartRadio.

Best regards,
-SWH

**Comment by storm8888** [comment]
Thank you !
