### ISSUE TITLE
Hardware Button on Raspberry Pi

### ISSUE THREAD

**Issue by MEJD2004** [alexa/avs-device-sdk#1584]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Attempting to use the wiringpi.h library to read from a gpio input to trigger privacy mode. The outputs work for an rgb led for visual indicators however the input does not work
## What is the expected behavior?

The button when pressed should toggle privacy mode
## What behavior are you observing?

The pi does not respond
### What version of the AVS Device SDK are you using?
      latest

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
-  Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ereich1217** [comment]
wiringPi definitely works on the RPi with AVS.  I have used this read buttons from within AVS to control volume.

You should check your GPIO initialization to make sure that you set them to INPUT and that you set the correct pull up/down setting depending upon how you have it wired.

**Comment by MEJD2004** [comment]
where do you put it, i cant seem to get it to work, i initialise the pin etc. but it wont work unless i have done that wrong. does pull down need to be set or something and where in the code do you put button reads?

**Comment by samcoult** [comment]
Hi @MEJD2004 , I would suggest troubleshooting your GPIO issues in a small test program. Once you are sure the GPIO is working in your test program you can then use it with the SDK. Unfortunately GPIO issues are outside the scope of the AVS SDK.
