### ISSUE TITLE
Certification failed due to offset report not correct when playing music

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1587]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I am trying to play music and validate it using MVT tool(music validation tool) then the "ProgressReportDelayElapsed" has been failing.
It is showing that the expected is 1000 and the outcome is 5386

From the MVT tool the results are as follows:

1**2/17/2019 06:12:51 EVENT url ProgressReportDelayElapsed FAIL [INCORRECT_OFFSET_TOO_HIGH] 5386
(Expected:
1000)**

## What is the expected behavior?

https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/audioplayer.html#progressreportdelayelapsed

It is clearly mentioned in amazon forum.
## What behavior are you observing?

progressreportdelayelapsed is higher than expected.
### What version of the AVS Device SDK are you using?
avs sdl 1.12
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ .] Other - tell us more:
pie

**Comment by dipalisb** [comment]
[AMAZON_CLOUDFAILED1576563751125.pdf](https://github.com/alexa/avs-device-sdk/files/3982953/AMAZON_CLOUDFAILED1576563751125.pdf)
Please find the test results.

**Comment by kclchan** [comment]
Hi @dipalisb, could you try with a newer release of the SDK?  For example, looking at CHANGELOG.md, the below issue is fixed in v1.12.1.
```
Corrected pause/resume handling in ProgressTimer so that extra ProgressReportDelayElapsed events are not sent to AVS.
```

**Comment by dipalisb** [comment]
Hi @kclchan ,
Thanks for the response.
We have verified this issue on avs sdk 1.12.1 and it is working fine.
But, there are some other scenarios which are failing.
PlaybackStopped and PlaybackNearlyFinished are failing.
Please find the test results
[avs_1_17_testresults.pdf](https://github.com/alexa/avs-device-sdk/files/3987596/avs_1_17_testresults.pdf)

**Comment by kclchan** [comment]
Hi @dipalisb, just to confirm, are you testing with 1.12.1 or 1.17?  Also, could you try to rerun the tests and see if you get the same result?  And please attached the DEBUG9 log as well.  Thanks!

**Comment by dipalisb** [comment]
Hi @kclchan ,
As suggested we have tested with AVS SDK .12.1 and now we want to upgrade to SDK 1.17.0 so we  have tested with both the versions.
With both the versions we facing similar issues failing. 

1.) Extra ProgressReportDelayElapsed

2.) Incorrect PlaybackStopped offset when song is interrupted 

3.) Delayed PlaybackStarted

Please find the attachment for DEBUG9 logcats. It is tested on SDK1.12.0 and above mentioned three scenarios are  failing.
[avs_1_12_0_debug9_1.txt](https://github.com/alexa/avs-device-sdk/files/3994477/avs_1_12_0_debug9_1.txt)

Also, please find the attached test-results.
[avs_1_12_0.pdf](https://github.com/alexa/avs-device-sdk/files/3994484/avs_1_12_0.pdf)

The above three scenarios are failing from our end.

**Comment by dipalisb** [comment]
Hi @kclchan ,

We have tested this scenario on AVS SDK v1.17.0 and below mentioned scenarios are failing.
1. PlaybackStopped
2. PlaybackStarted
3. PlaybackNearlyFinished
4. PlaybackFinished
Could please let us know what was the actual cause for this failure.

Please find the debug9 logcats for avs sdk 1.17.0
[avs_1_17_0_debug9_1.txt](https://github.com/alexa/avs-device-sdk/files/3994881/avs_1_17_0_debug9_1.txt)

Also the test results 
[avs_1_17_debug9_1.pdf](https://github.com/alexa/avs-device-sdk/files/3994882/avs_1_17_debug9_1.pdf)

Thanks,

**Comment by dipalisb** [comment]
Hi @kclchan ,

May I know, is there any update on this issue.
Could you please respond as soon as possible.

Thanks,

**Comment by samcoult** [comment]
Hi @dipalisb ,

We have created an internal tracking issue to investigate this. Thank you for reporting this issue.

**Comment by dipalisb** [comment]
OK 
We will be waiting for your response
Thanks,

**Comment by dipalisb** [comment]
Hi @samcoult , @kclchan ,
May I know is there any progress on this issue.
And also, could please confirm that Is there anything that we can do to resolve this issue from device side. 
Thanks,

**Comment by dipalisb** [comment]
Hi,
Could you please tell us ,Is there any update on this issue.
This issue is blocking for amazon certification.
Thanks,

**Comment by dipalisb** [comment]
Hi,
Could you please tell us ,Is there any update on this issue.
Thanks,

**Comment by womw** [comment]
Hi @dipalisb we are still investigating this internally

**Comment by dipalisb** [comment]
Hi,
Could you please tell us ,Is there any update on this issue.
Thanks,

**Comment by kclchan** [comment]
Hi @dipalisb, sorry for the long delay.  Looking at the logs avs_1_17_0_debug9_1.txt where you tested with v1.17, it appears there were lots of stuttering happening during the audio playback, and that is causing the certification to fail.  Could you retry the test again with v1.17, preferably with a better internet connection, and see if the result is different?

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please open a new issue if you continue to have problems, or comment on this one again if it is not resolved.
