### ISSUE TITLE
'make SampleApp' unsuccessful; libMediaPlayer.so: undefined reference to 

### ISSUE THREAD

**Issue by AxelMKlein** [alexa/avs-device-sdk#1589]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When starting make SensorApp, the process ends with error messages.

## What is the expected behavior?

The process should run through without error messages.

## What behavior are you observing?

The process ends with these error messages:

`[ 95%] Linking CXX executable SampleApp
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libcrypto.so.1.1
../../MediaPlayer/GStreamerMediaPlayer/src/libMediaPlayer.so: undefined reference to 'gst_interpolation_control_source_new\'
../../MediaPlayer/GStreamerMediaPlayer/src/libMediaPlayer.so: undefined reference to ´ 'gst_direct_control_binding_new'
../../MediaPlayer/GStreamerMediaPlayer/src/libMediaPlayer.so: undefined reference to 'gst_timed_value_control_source_set'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:476: die Regel für Ziel „SampleApp/src/SampleApp“ scheiterte
make[3]: *** [SampleApp/src/SampleApp] Fehler 1
CMakeFiles/Makefile2:12595: die Regel für Ziel „SampleApp/src/CMakeFiles/SampleApp.dir/all“ scheiterte
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Fehler 2
CMakeFiles/Makefile2:12607: die Regel für Ziel „SampleApp/src/CMakeFiles/SampleApp.dir/rule“ scheiterte
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Fehler 2
Makefile:3150: die Regel für Ziel „SampleApp“ scheiterte
make: *** [SampleApp] Fehler 2`

## Provide the steps to reproduce the issue, if applicable:

Here is my cmake command:
`sudo cmake /home/pi/bin/alexa_sdk_download/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/bin/alexa_sdk_download/third-party/alexa-rpi/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/bin/alexa_sdk_download/third-party/alexa-rpi/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/pi/bin/alexa_sdk_download/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/pi/bin/alexa_sdk_download/third-party/portaudio/include`

Then I executed:
`sudo make SampleApp`

### What version of the AVS Device SDK are you using?
      <1.17.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @AxelMKlein ,

The error message you posted indicates that the linker cannot find a few gstreamer functions. Can you try running the following commands to double check gstreamer is installed, and then running make again?

```
sudo apt-get update

  sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev libssl-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good libasound2-dev sox
```

**Comment by AxelMKlein** [comment]
Hi @samcoult ,

Thank you for the quick reply.

Unfortunately running these commands reveal that everything is there and up to date:

`:~ $ sudo apt update && sudo apt upgrade
OK:1 http://archive.raspberrypi.org/debian stretch InRelease
Holen:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15,0 kB]
Es wurden 15,0 kB in 1 s geholt (11,7 kB/s).
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.        
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
pi@axelpi:~ $ sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev libssl-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good libasound2-dev sox
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.        
Statusinformationen werden eingelesen.... Fertig
build-essential ist schon die neueste Version (12.3).
cmake ist schon die neueste Version (3.7.2-1).
gcc ist schon die neueste Version (4:6.3.0-4).
git ist schon die neueste Version (1:2.11.0-3+deb9u5).
gstreamer1.0-plugins-good ist schon die neueste Version (1.10.4-1).
libcurl4-openssl-dev ist schon die neueste Version (7.52.1-5+deb9u9).
libfaad-dev ist schon die neueste Version (2.8.0~cvs20161113-1+deb9u2).
libgcrypt20-dev ist schon die neueste Version (1.7.6-2+deb9u3).
libgstreamer-plugins-bad1.0-dev ist schon die neueste Version (1.10.4-1).
libsoup2.4-dev ist schon die neueste Version (2.56.0-2+deb9u2).
libsqlite3-dev ist schon die neueste Version (3.16.2-5+deb9u1).
libssl-dev ist schon die neueste Version (1.1.0l-1~deb9u1).
sox ist schon die neueste Version (14.4.1-5+deb9u2).
libasound2-dev ist schon die neueste Version (1.1.3-5+rpt4).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.`

And hence the error messages remain the same as before :-( .

Any other thought?
Thanks in advance.

**Comment by ypwangnexus** [comment]
It seems that there is missing library dependency and the quick dirty-way to fix it as follow
 
`sdk-build$ vi CMakeCache.txt`
GST_LDFLAGS:INTERNAL=-lgstapp-1.0;-lgstbase-1.0;**-lgstcontroller-1.0;**-lgstreamer-1.0;-lgobject-2.0;-lglib-2.0

**Comment by suchidog** [comment]
Hi @ypwangnexus and @AxelMKlein I am having a similar issue I think:

[ 95%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o
[ 95%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/SampleApplication.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/build.make:128: SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:12601: SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:12613: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3152: SampleApp] Error 2

I tried the suggestion above:

sudo apt-get update
sudo apt-get -y install etc etc

and got the same result as @AxelMKlein - everything was up to date.

Are you able to explain your quick dirty fix in your last post in steps as I am a bit of a beginner. Thank-you!

**Comment by AxelMKlein** [comment]
@ypwangnexus : 

Thank you very much! The making of the SampleApp is successful with this workaround.

Now I'm stuck at generating 'AlexaClientSDKConfig.json'. It's always empty after running the command

```
sudo bash genConfig.sh config.json 12345  /home/pi/bin/alexa_sdk_download/db  /home/pi/bin/alexa_sdk_download/avs-device-sdk  /home/pi/bin/alexa_sdk_download/build/Integration/AlexaClientSDKConfig.json  -DSDK_CONFIG_MANUFACTURER_NAME="Manufacturer"  -DSDK_CONFIG_DEVICE_DESCRIPTION="Description"
```
It ends like that:
```Completed generation of config file: /home/pi/bin/alexa_sdk_download/build/Integration/AlexaClientSDKConfig.json```
But I guess this would be a new bug-report.

**Comment by ypwangnexus** [comment]
@suchidog If you follow the https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html I would assume that your current working directory is 
`cd $HOME/my_project/build`
then using any favour editor you like to edit a file named CMakeCache.txt under that directory
find the line
`GST_LDFLAGS:INTERNAL=-lgstapp-1.0;-lgstbase-1.0;-lgstreamer-1.0;-lgobject-2.0;-lglib-2.0`
and change it to
`GST_LDFLAGS:INTERNAL=-lgstapp-1.0;-lgstbase-1.0;-lgstcontroller-1.0;-lgstreamer-1.0;-lgobject-2.0;-lglib-2.0`

**Comment by ypwangnexus** [comment]
@AxelMKlein It works for me.  As you are using 'sudo ..' to generate the .json so it might be needed to use 'sudo vi ..' to see the file.  Just double check.

**Comment by suchidog** [comment]
@ypwangnexus thanks for the explanation. However it didn't work for me. I keep getting this this point before the Pi freezes:

################################################################################
################################################################################
agree
################################################################################
Proceeding with installation
################################################################################
[ 31%] Built target AVSCommon
[ 31%] Built target SynchronizeStateSender
[ 35%] Built target ACL
[ 37%] Built target ADSL
[ 40%] Built target AFML
[ 42%] Built target Captions
[ 44%] Built target RegistrationManager
[ 46%] Built target SQLiteStorage
[ 48%] Built target Alexa
[ 53%] Built target EqualizerImplementations
[ 53%] Built target ContextManager
[ 57%] Built target PlaylistParser
[ 60%] Built target KWD
[ 62%] Built target SystemSoundPlayer
[ 62%] Built target SpeechEncoder
[ 64%] Built target AudioResources
[ 64%] Built target ApiGateway
[ 66%] Built target AudioPlayer
[ 66%] Built target Bluetooth
[ 66%] Built target Equalizer
[ 66%] Built target ExternalMediaPlayer
[ 66%] Built target InteractionModel
[ 68%] Built target Notifications
[ 71%] Built target PlaybackController
[ 71%] Built target SpeakerManager
[ 73%] Built target SpeechSynthesizer
[ 73%] Built target TemplateRuntime
[ 73%] Built target CBLAuthDelegate
[ 75%] Built target MediaPlayer
[ 77%] Built target AVSGatewayManager
[ 77%] Built target CertifiedSender
[ 80%] Built target Endpoints
[ 80%] Built target SENSORY
[ 82%] Built target CapabilitiesDelegate
[ 86%] Built target DeviceSettings
[ 86%] Built target KeywordDetectorProvider
[ 86%] Built target AIP
[ 88%] Built target DoNotDisturbCA
[ 93%] Built target Alerts
[ 95%] Built target AVSSystem
[ 95%] Building CXX object ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DeviceSettingsManagerBuilder.cpp.o
[ 95%] Building CXX object ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClient.cpp.o

**Comment by AxelMKlein** [comment]
@ypwangnexus: Thanks for the recommendation. But the file is really empty, I checked several times. I opened a new issue.

> @AxelMKlein It works for me. As you are using 'sudo ..' to generate the .json so it might be needed to use 'sudo vi ..' to see the file. Just double check.

**Comment by AxelMKlein** [comment]
From my point of view the issue is solved. 
Now it depends on @ypwangnexus whether his issue is the same as this one.

**Comment by womw** [comment]
@AxelMKlein I'm glad your issue has been resolved and I'll close this here.

@suchidog can you open a new issue regarding your particular problems?
