### ISSUE TITLE
Alexa is going to Listening State by triggering "Alexa" wakeword from its own response.

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1590]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When we say "Alexa, what is your name?" then Alexa response is "Iam Alexa"
By taking the wake word from its own response it is going to Listening State,without user interaction with Alexa.

## What is the expected behavior?

Alexa should not go to listening state by taking its own response.

## What behavior are you observing?

Alexa is going to Listening state taking "Alexa" word from its own response.

## Provide the steps to reproduce the issue, if applicable:

Ask, Alexa what is your name?
Alexa will respond as "My name is **Alexa**"
The "Alexa" word from its response is taken as wake word and it is going to Listening state.

### What version of the AVS Device SDK are you using?
      <AVS SDK 1.12.0>
Amazon PryonLite Wakeword Engine version 1.13.4
For more details
https://forums.developer.amazon.com/questions/220169/alexa-is-going-to-listening-state-triggering-wake.html

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ .] Other - tell us more:
android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [. ] Other - tell us more:
pie

**Comment by caleighatamazon** [comment]
Hi @dipalisb, thanks for reporting this. Can you please try reproducing the problem with our latest release (1.17)? Also, can you reproduce the issue but turn on logging with DEBUG9 and attach logs to this? Thanks.

**Comment by caleighatamazon** [comment]
Actually, I gave it a try and I reproduce this on 1.17. This is definitely a bug! I will file an internal ticket to get this fixed. Thanks for reporting the issue.

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
Is there any update on this issue.
Thanks,

**Comment by womw** [comment]
Hi @dipalisb 
This is a known issue that we are still investigating internally. I believe the same behaviour should occur for both prime and non-prime accounts.

**Comment by dipalisb** [comment]
Hi @womw ,
Please find the logcats for AVS SDK 1.17.0 with DEBUG9

Can you please confirm the below scenario.
![alexa_states](https://user-images.githubusercontent.com/52921278/71957385-a1e30a80-3213-11ea-80bb-2cbfc7cc416e.png)

In the screenshot 
For the first time when we "Alexa who are you" then from Idle it is going to Listening state and then thinking and speaking .
After it is responding as "I'm Alexa" from speaking it is going to Idle state and then again going to Listening state.

For the second time, when it is going to Listening state by triggering the wake word from its own response at that time  If we ask Alexa anything then it is not giving any response.

From the logcats,
[DEBUG9_pupc_11887_charl.txt](https://github.com/alexa/avs-device-sdk/files/4034008/DEBUG9_pupc_11887_charl.txt)
can you please explain what does the value "confidence" refers to. Because the value is different for the first and second time Listening states.
First time when user gave wakeword Alexa :
**2020-01-07 08:56:41.032 [ 2b] I PryonLiteKeywordDetector:resultCallback:keyword=ALEXA,confidence=778
**
And the second time when Alexa is going to Listening state by triggering the wake-word from its own response.
**2020-01-07 08:56:46.650 [ 2b] I PryonLiteKeywordDetector:resultCallback:keyword=ALEXA,confidence=584
**
P.S : We are using the wakeword Engine pryonLitekeywordDetector 1.13.4

Thanks,

**Comment by womw** [comment]
Hi @dipalisb 

Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.
