### ISSUE TITLE
'AlexaClientSDKConfig.json' is empty after running genConfig.sh

### ISSUE THREAD

**Issue by AxelMKlein** [alexa/avs-device-sdk#1591]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I'm stuck at generating 'AlexaClientSDKConfig.json'. It's always empty after running the following command in the directory 'in the directory ~/bin/alexa_sdk_download/avs-device-sdk/tools/Install'

```
sudo bash genConfig.sh config.json 12345  /home/pi/bin/alexa_sdk_download/db  /home/pi/bin/alexa_sdk_download/avs-device-sdk  /home/pi/bin/alexa_sdk_download/build/Integration/AlexaClientSDKConfig.json  -DSDK_CONFIG_MANUFACTURER_NAME="Manufacturer"  -DSDK_CONFIG_DEVICE_DESCRIPTION="Description"
```
## What is the expected behavior?

It is expected that a valid file 'AlexaClientSDKConfig.json' is created in the directory: ':~/bin/alexa_sdk_download/build/Integration'.

## What behavior are you observing?

This is the message of running 'genConfig.sh':

```Completed generation of config file: /home/pi/bin/alexa_sdk_download/build/Integration/AlexaClientSDKConfig.json```

so, without any error-message. 
But the 'AlexaClientSDKConfig.json' is empty. 
:-(.

How can I get a valid  'AlexaClientSDKConfig.json'?

### What version of the AVS Device SDK are you using?
      <1.17.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by AxelMKlein** [comment]
Issue is solved.

The file 'AlexaClientSDKConfig.json' was empty already in the source-directory.

After I replaced it with the correct one, the file showed up correctly in the build-directory.

**Comment by aamir6629** [comment]
Facing same issue what should I do to resolve it
