### ISSUE TITLE
Raspberry pi zero w with bluetooth option

### ISSUE THREAD

**Issue by JyothishGeorge** [alexa/avs-device-sdk#1592]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Trying to build the sdk with Bluetooth option on a raspberry pi zero w . I get the following exception while trying to make the sample application. The error is as follows

[ 53%] Building CXX object BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/PulseAudioBluetoothInitializer.cpp.o
/home/pi/sdk-folder/sdk-source/avs-device-sdk/BluetoothImplementations/BlueZ/src/PulseAudioBluetoothInitializer.cpp: In member function ‘bool alexaClientSDK::bluetoothImplementations::blueZ::PulseAudioBluetoothInitializer::updateStateLocked(const alexaClientSDK::bluetoothImplementations::blueZ::PulseAudioBluetoothInitializer::ModuleState&, const string&)’:
/home/pi/sdk-folder/sdk-source/avs-device-sdk/BluetoothImplementations/BlueZ/src/PulseAudioBluetoothInitializer.cpp:252:17: error: variable ‘currentState’ set but not used [-Werror=unused-but-set-variable]
     ModuleState currentState = ModuleState::UNKNOWN;
                 ^~~~~~~~~~~~
/home/pi/sdk-folder/sdk-source/avs-device-sdk/BluetoothImplementations/BlueZ/src/PulseAudioBluetoothInitializer.cpp: At global scope:
/home/pi/sdk-folder/sdk-source/avs-device-sdk/BluetoothImplementations/BlueZ/src/PulseAudioBluetoothInitializer.cpp:60:20: error: ‘std::__cxx11::string alexaClientSDK::bluetoothImplementations::blueZ::stateToString(pa_context_state_t)’ defined but not used [-Werror=unused-function]
 static std::string stateToString(pa_context_state_t state) {
                    ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/build.make:297: BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/PulseAudioBluetoothInitializer.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:6546: BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:12875: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3217: SampleApp] Error 2

## What is the expected behavior?
The sample applications should be created successfully

## What behavior are you observing?
Exception while making the sample application

## Provide the steps to reproduce the issue, if applicable:
cmake /home/pi/sdk-folder/sdk-source/avs-device-sdk \
-DSENSORY_KEY_WORD_DETECTOR=ON \
-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/sdk-folder/third-party/alexa-rpi/lib/libsnsr.a \
-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/sdk-folder/third-party/alexa-rpi/include \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=/home/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=/home/pi/sdk-folder/third-party/portaudio/include \
-DBLUETOOTH_BLUEZ=ON \
-DBLUETOOTH_BLUEZ_PULSEAUDIO_OVERRIDE_ENDPOINTS=ON 

## Tell us about your environment:
Raspberry pi zero w with Raspbian NOOBS
### What version of the AVS Device SDK are you using?
     The latest version cloned

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [- ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Raspbian Jessy

**Comment by womw** [comment]
Hi @JyothishGeorge thanks for posting.

Do you mind sharing what compiler and version you are using? Also maybe try building with the flag -DCMAKE_BUILD_TYPE=DEBUG so that the unused variable and method are used.

**Comment by nickosouras** [comment]
how to change cmake variables to enable bluetooth? and what file do I need to modify? https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#bluetooth

**Comment by celinval** [comment]
Hi @nickosouras, you need to rerun cmake and pass the new values for the variables documented in the documentation link. See the example column how to use it.

You might need to remove your CMakeCache.txt file.

**Comment by caleighatamazon** [comment]
Hi, I'm going to close this issue due to inactivity, but please feel free to open a new one if you're still having problems.
