### ISSUE TITLE
Alexa on Raspberry Pi Using Bluetooth Speaker with Mic

### ISSUE THREAD

**Issue by raspberrypi9** [alexa/avs-device-sdk#1594]
Hi,

Please forgive me if this is not the appropriate forum for this question.  It appeared like it might be based on past issues that came up in my searching.

I am interested in implementing Alexa/AVS on a Raspberry Pi.  Instead of using a hardwired speaker and microphone, as in all the tutorials I have seen, I would like to use a bluetooth speaker that has a built in microphone.  I did some searching and it did not look like this was supported back in 2018, but I was wondering if newer releases of the SDK might support this.

If you would please let me know if this is currently possible, and share any tips on how to move forward, I would really appreciate it.

Thanks so much for your help.

**Comment by womw** [comment]
Hi @raspberrypi9 thanks for posting.

I believe that the Raspberry Pi with bluetooth speaker and microphone should be possible. The effort required to do such a setup goes beyond the scope of the SDK Issues board however and we will not be able to assist you with this setup.

Thanks
