### ISSUE TITLE
AVS crash on null pointer in log message (SpeechSynthesizer)

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1596]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
In SpeechSynthesizer::executeHandleAfterValidation(...) line 633 of SpeechSynthesizer.cpp in v1.17 the error message attempts to access "m_currentInfo" instead of "speakInfo" in the error message, this causes a dereference of a null pointer in some cases. 

## What is the expected behavior?
AVS should not crash

## What behavior are you observing?
AVS crashes on a null pointer(sometimes when playing Jeopardy, i.e.)

## Provide the steps to reproduce the issue, if applicable:
played Jeopardy while AVS was running in GDB a few times.

## Tell us about your environment:
Headless generic linux device. Partially modified SDK.

### What version of the AVS Device SDK are you using?
1.16, but but also exists in 1.17

### Tell us what hardware you're using:
- [ x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hey @brett-lynnes 

Thanks for posting this. I've noted this issue and we are investigating this internally.

**Comment by brett-lynnes** [comment]
thought i would throw a backtrace on this for shoots and giggles:

Thread 875 "SampleApp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff6d7fa700 (LWP 30258)]
0x00007ffff61a7512 in std::__shared_ptr<alexaClientSDK::avsCommon::avs::AVSDirective, (__gnu_cxx::_Lock_policy)2>::get (
    this=0x0) at /usr/include/c++/7/bits/shared_ptr_base.h:1258
1258	      { return _M_ptr; }
(gdb) bt
#0  0x00007ffff61a7512 in std::__shared_ptr<alexaClientSDK::avsCommon::avs::AVSDirective, (__gnu_cxx::_Lock_policy)2>::get() const (this=0x0) at /usr/include/c++/7/bits/shared_ptr_base.h:1258
#1  0x00007ffff61a4fcc in std::__shared_ptr_access<alexaClientSDK::avsCommon::avs::AVSDirective, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const (this=0x0) at /usr/include/c++/7/bits/shared_ptr_base.h:975
#2  0x00007ffff61a2a44 in std::__shared_ptr_access<alexaClientSDK::avsCommon::avs::AVSDirective, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const (this=0x0) at /usr/include/c++/7/bits/shared_ptr_base.h:969
#3  0x00007ffff0a49cc6 in alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::executeHandleAfterValidation(std::shared_ptr<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::SpeakDirectiveInfo>) (this=
    0x555555fc6590, speakInfo=std::shared_ptr<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::SpeakDirectiveInfo> (use count 2, weak count 0) = {...})
    at /home/lynnes/AVS/avs-device-sdk/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp:631
#4  0x00007ffff0a4aa2c in alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::executeHandle(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>) (this=0x555555fc6590, info=
    std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo> (use count 2, weak count 0) = {...})
    at /home/lynnes/AVS/avs-device-sdk/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp:677
#5  0x00007ffff0a44353 in alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::<lambda()>::operator()(void) const (__closure=0x7fff84001508)
    at /home/lynnes/AVS/avs-device-sdk/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp:229
#6  0x00007ffff0a81492 in std::__invoke_impl<void, alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>&>(std::__invoke_other, alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::<lambda()> &) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#7  0x00007ffff0a800a5 in std::__invoke<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>&>(alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::<lambda()> &) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#8  0x00007ffff0a7e812 in std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()>::__call<void>(std::tuple<> &&, std::_Index_tuple<>) (this=0x7fff84001508, __args=...) at /usr/include/c++/7/functional:467
#9  0x00007ffff0a7c46b in std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()>::operator()<>(void) (this=0x7fff84001508) at /usr/include/c++/7/functional:551
#10 0x00007ffff0a785da in std::__invoke_impl<void, std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()>&>(std::__invoke_other, std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()> &) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#11 0x00007ffff0a750d0 in std::__invoke<std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()>&>(std::_Bind<alexaClientSDK::capabilityAgents::speechSynthesizer::SpeechSynthesizer::handleDirective(std::shared_ptr<alexaClientSDK::avsCommon::avs::CapabilityAgent::DirectiveInfo>)::<lambda()>()> &) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95

**Comment by dhpp** [comment]
Thanks again @brett-lynnes - this will be addressed in the next SDK release.  We really appreciate you bringing this to our attention.
