### ISSUE TITLE
"Alexa, play Ted talks on tuneln", when enter the set url steps , we can't parse the needed information from the url sent by AVS cloud

### ISSUE THREAD

**Issue by tinypancake** [alexa/avs-device-sdk#1597]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Firstly, I create a new audiomediaplayer to take place of the AVS source code
Second, its playflow is by setSource ( getting the music source with url) not the handleBusmessage
Then, it works well when I play music on Pandora and IheartRadio, however, when I want to play on Tuneln , it has failed.

## What is the expected behavior?
It can work well no matter in Pandora or IheartRadio or Tuneln

## What behavior are you observing?
I have tried to access the url when I want to play something on Tuneln, here I can get a M3U file, but the content is only one line :  #STATUS: 400
Does it represent for there is nothing to get?

### What version of the AVS Device SDK are you using?
      AVS SDK V1.15

### Tell us what hardware you're using:
- [ ] Other - tell us more: Linux platform

### Tell us about your OS (Type & version):
- [ ] Linux

The following is my Logs:
(200102_15:27:01.087)2020-01-02 07:27:01.062 [ 1b] 1 AudioPlayer:executePrePlay:playBehavior=REPLACE_ALL,state=IDLE
(200102_15:27:01.087)2020-01-02 07:27:01.062 [ 1b] 1 AudioPlayer:setSource
(200102_15:27:01.087)[SmartAudioPlayerWrapper] [INFO] set url source
(200102_15:27:01.087)<SAPlayer-DRIVER> setDataSource(98) setDataSource(0x1c2478) url(http://opml.radiotime.com/Tune.ashx?id=e45085637&sid=s24948&formats=aac,mp3&partnerId=4JqugguZ&serial=AF42JPWG5KMI3IYG5WUSWMUGJ7VA) id(3)
(200102_15:27:01.087)<SAPlayer> PlayerMessageReceive(873) kWhatSetDataSource (0x1c26b0)
(200102_15:27:01.087)(0xaeb040e8)create messagequeue name mq-0xaeb040e8
(200102_15:27:01.087)<SAPlayer> <SAPlayer> setDataSource(144) GenericMessageReceive(603) setDataSource http://opml.radiotime.com/Tune.ashx?id=e45085637&sid=s24948&formats=aac,mp3&partnerId=4JqugguZ&serial=AF42JPWG5KMI3IYG5WUSWMUGJ7VA
(200102_15:27:01.087)GenericMessageReceive pid 596 tid 1278<SAPlayer-DEMUXER> 
(200102_15:27:01.087)FFDemuxer(90) After FFDemuxer mUrl is http://opml.radiotime.com/Tune.ashx?id=e45085637&sid=s24948&formats=aac,mp3&partnerId=4JqugguZ&serial=AF42JPWG5KMI3IYG5WUSWMUGJ7VA!
(200102_15:27:01.087)<SAPlayer-DEMUXER> OpenDemux(118) OpenDemux Start!
(200102_15:27:01.087)<SAPlayer-STREAMER> SetDataSource(85) After SetDataSource mUrl is http://opml.radiotime.com/Tune.ashx?id=e45085637&sid=s24948&formats=aac,mp3&partnerId=4JqugguZ&serial=AF42JPWG5KMI3IYG5WUSWMUGJ7VA!
(200102_15:27:01.087)<SAPlayer-STREAMER> OpenAvio(98) OpenAvio Start!
(200102_15:27:01.087)<SAPlayer-STREAMER> OpenAvio(148) http set timeout
(200102_15:27:06.667)<SAPlayer-DRIVER> start(228) start(0x1c2478), state is 2, eos is 0, mId(3)
(200102_15:27:06.667)<SAPlayer> PlayerMessageReceive(911) kWhatPrepare TIME 1577950026549078000!
(200102_15:27:06.667)<SAPlayer> <SAPlayer> LEAVING PlayerMessageReceive
(200102_15:27:06.667)GenericMessageReceive(616) kWhatPrepareAsync (0xaeb007a0)
(200102_15:27:06.667)<SAPlayer-DEMUXER> Start(269) FFDemuxer Start!
(200102_15:27:06.667)<SAPlayer-DEMUXER> Start(284) [XY] modify the detect length!
(200102_15:27:06.667)<SAPlayer-DEMUXER> Start(289) Couldn't Probe Format! -1094995529

**Comment by womw** [comment]
Hi @tinypancake  thanks for posting,

Is your Mediaplayer configured to handle playing and parsing .m3u files? The error message Couldn't Probe Format seems to suggest a format error that doesn't seem to happen with iHeartRadio.

**Comment by tinypancake** [comment]
Yes.
M3U file is a list of music resource urls, our player will use these urls to play music.
The issue is that the M3U file from the tuneln is just one line #STATUS=400




| |
邱香域
|
|
15827528242
邮箱：cxiaomaomiao@163.com
|

签名由 网易邮箱大师 定制

On 01/08/2020 08:56, womw wrote:

Hi @tinypancake thanks for posting,

Is your Mediaplayer configured to handle playing and parsing .m3u files? The error message Couldn't Probe Format seems to suggest a format error that doesn't seem to happen with iHeartRadio.

**Comment by womw** [comment]
@tinypancake I've followed the links that you've posted in your log and receive .m3u that I'm able to play. Perhaps this is an issue with receiving the correct files from tunein? Does this happen for all tunein stations/songs?

**Comment by tinypancake** [comment]
Yes, it happened for all tunein stations/songs, and can you tell me the way you use the url to play ? Did you use other players? 
Thanks very much.

**Comment by womw** [comment]
Hello,

I was able to download the m3u file following the links posted in your log. I was able to play these files successfully using the local media player on my laptop.

In terms of implementation of mediaplayer for our SDK we have 2, Gstreamer and FFmpeg. Both of these implementations are able to successfully play tunein.

**Comment by tinypancake** [comment]
Thanks very much . How can I use the ffmpeg mediaplayer in SDK ? Because I just see the Gstreamer mediaplayer，and I do not find the other one. It is so kind-hearted if you can tell me where to realize the another type of mediaplayer，I believe this will help me greatly in dealing with this issue! 
Best Regard

**Comment by tinypancake** [comment]
And Could you tell me the ffmpeg version you use with ?

**Comment by tinypancake** [comment]
BTW, is there some option parameters of ffmpeg need to be set to play the url from tunein , such as enable-parser , enable-demuxer and etc?
