### ISSUE TITLE
Alexa is not getting disconnected after removing ethernet cable from WIFI router 

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1599]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 With proper internet connection, I have asked the query to Alexa. After sometime ethernet cable is removed from wifi router, Alexa should show disconnected state but it is showing connected state and going to listening. After 2 min of waiting, Alexa is not going to listening and getting disonnected 

## What is the expected behavior?

-->Alexa should immediately get disconnect after removing Ethernet cable from WIFI router 
[Alexa_not_getting_disconnected_log.txt](https://github.com/alexa/avs-device-sdk/files/4045348/Alexa_not_getting_disconnected_log.txt)

## What behavior are you observing?

-->Alexa is not getting disconnected after removing ethernet cable from WIFI router 

## Provide the steps to reproduce the issue, if applicable:

1.Device is setup and connected to a Wi-Fi Router
2.Ask query to Alexa.
3. Remove ethernet from WIFI router.

### What version of the AVS Device SDK are you using?
AVS-SDK 1.17

### Tell us what hardware you're using:
- [ ] Desktop

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by womw** [comment]
Hey @dipalisb thanks for posting.

The SDK maintains a connection with AVS by sending a keep alive ping while idle every 5 minutes.

Is the issue that while disconnected from internet and attempting to enter listening state that the device does not enter a disconnected state?

**Comment by dipalisb** [comment]
Hi @womw ,

Yes, Device is going to listening state even if Ethernet cable is removed from router.

Is this a known bug?

Is it fine to change the 5 min time-out to 5 sec?

**Comment by mvelegon-amzn** [comment]
Hi @dipalisb it is not recommended to change the ping timer to a shorter interval. The 5 min is a specification from AVS: https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/manage-http2-connection.html#ping-timeout

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity, but please open a new issue if you continue to have problems.
