### ISSUE TITLE
Supports to add a customized signal processing algorithms?

### ISSUE THREAD

**Issue by liudqc1** [alexa/avs-device-sdk#160]
Hi, I have a question about Audio Signal Processor (ASP) . We have a our own audio signal processing algorithms(AEC/NR),  I'd like to know if alexa-device-sdk supports to add our own algorithms to ASP module? if so, what do we need to do?

please advise, thanks.

**Comment by sanjayrd** [comment]
Hi @liudqc1,

Yes, this is definitely possible. The SDK architecture as is stands right now reads user audio bytes from a SharedDataStream object, which your microphone (but not necessarily) will be writing to. At the moment, the SDK doesn't come with hooks to add in your own ASP, but you can certainly perform processing prior to writing these bytes into the SharedDataStream. By doing this, the SDK will only consume the audio bytes that have been processed. Hope that helps.

Thanks,
Sanjay

**Comment by pilakedh** [comment]
Where can i get buffer of the audio played out by AVS? I would like to use it for echo cancellation algorithm.

**Comment by retunestan** [comment]
How can I access audio output stream (raw audio samples) ? Cause I need the final output for AEC as refenrece signal.
