### ISSUE TITLE
catching smart alerts (broken glass, smoke etc.)

### ISSUE THREAD

**Issue by mduzgun** [alexa/avs-device-sdk#1602]
Hi, I want to get broken glass notificaiton from my Alexa device.
How to get/catch broken glass, smoke notification/alerts?

**Comment by maheshvele** [comment]
Hi @mduzgun thanks for reaching out. Does the Alexa device you are using use the SDK?

If it uses the SDK, the Alexa Guard features to detect broken glass/smoke alarms are not supported yet.

**Comment by mvelegon-amzn** [comment]
@mduzgun Thanks for reaching out. Does your Alexa device use the SDK? 

Currently the Alexa Guard feature to detect (broken glass, smoke alarms etc) are not supported on devices using the SDK.

**Comment by ilkan** [comment]
> @mduzgun Thanks for reaching out. Does your Alexa device use the SDK?
> 
> Currently the Alexa Guard feature to detect (broken glass, smoke alarms etc) are not supported on devices using the SDK.

We want to be a official partner. At this time is it possible?

**Comment by mvelegon-amzn** [comment]
@mduzgun @ilkan thank you for your interest. We will get back to you shortly on this.

**Comment by ilkan** [comment]
@mvelegon-amzn any update?

**Comment by dhpp** [comment]
Hi @ilkan, sorry that we can't comment on our internal roadmap for this feature, but we have captured your request for it and that is helpful for us.

To become an official partner, please reach out to our business unit per the contact page here:
https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268

I'll close this ticket out in the meantime, thanks.
