### ISSUE TITLE
Alexa is not responding to Wake up Word 

### ISSUE THREAD

**Issue by daler-rahimov** [alexa/avs-device-sdk#1603]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Alexa is not responding to Wake up Word but everything works fine when pressing 't'. There are couple of errors at the start of the Sample App but it does not stop it from working with with "Tab to talk". It's fresh install of Ubuntu Server 16.04 

[log.log](https://github.com/alexa/avs-device-sdk/files/4087734/log.log)
[log.log.debug9](https://github.com/alexa/avs-device-sdk/files/4087750/log.log)

## What is the expected behavior?

Alexa goes to listening mode 

## What behavior are you observing?

Alexa is in idle mode 

## Provide the steps to reproduce the issue, if applicable:

[Set up the AVS SDK on Ubuntu Linux](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html) 

### What version of the AVS Device SDK are you using?
      SDK Version 1.17.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: AAEON UP UP Squared Board

### Tell us about your OS (Type & version):
- [x] Linux. Ubuntu 16.04 
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Hardware Devices 
```
**** List of PLAYBACK Hardware Devices ****
card 1: Device [USB2.0 Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by ereich1217** [comment]
You didn't build it with wakeword support.

From the top of your log.log file:
2020-01-20 20:27:15.142 [  1] I LocaleAssetsManager:initialize:supportedWakeWords=NONE

Refer here for how to run cmake with the proper parameters:
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#wake-word

**Comment by maheshvele** [comment]
@daler-rahimov Thanks for reaching out. As @ereich1217 mentioned, please build with wakeword support. The document you linked builds the SDK without a wake word.

**Comment by mvelegon-amzn** [comment]
Hi @daler-rahimov thanks for reaching out. As @ereich1217 mentioned, please build the SDK using a wake word detector.

**Comment by daler-rahimov** [comment]
Thanks for a quick response. I thought this was for third-party engines and AVS had it's own internal one

**Comment by daler-rahimov** [comment]
In case anyone else has same issues here what was missing 

```bash

# Some lib/apps needed for Snowboy and AVS SDK on Ubuntu 16.04 
apt-get install alsa alsa-tools
sudo apt-get install libatlas-base-dev liblapack-dev libblas-dev   
sudo apt install gstreamer1.0-alsa
sudo apt-get install libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good

# Clone Snowboy
cd $HOME/my_project/third-party
git clone https://github.com/Kitt-AI/snowboy

# cp model to correct path 
cp $HOME/my_project/third-party/snowboy/resources/alexa/alexa_02092017.umdl $HOME/my_project/third-party/snowboy/resources/alexa.umdl

### Build with Snowboy 
cd $HOME/my_project/build
cmake $HOME/my_project/source/avs-device-sdk \
-DKITTAI_KEY_WORD_DETECTOR=ON \
-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$HOME/my_project/third-party/snowboy/lib/ubuntu64/libsnowboy-detect.a \
-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/my_project/third-party/snowboy/include \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include \
-DCMAKE_BUILD_TYPE=DEBUG

make SampleApp -j4

## run with Snowboy 
cd $HOME/my_project/build
./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json $HOME/my_project/third-party/snowboy/resources/ 

```
