### ISSUE TITLE
std::random_device always returns 0 entropy() on (some) Linux

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1605]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
according to: [http://www.cplusplus.com/reference/random/random_device/entropy/](http://www.cplusplus.com/reference/random/random_device/entropy/) because the Linux devices (Ubuntu and a Yocto build) we use have RN engines instead of generators the call to .entropy() is always going to result in 0.  the code in AVSCommon/Utils/src/UUIDGeneration.cpp around line 157 is expecting a result out of this and will always end up printing a warning about low entropy: 

> W UUIDGeneration:low entropy on call to generate UUID:current entropy=0 

the code still generates entropy and seed correctly for the ibe, but getting that warning spam in the logs is a bit annoying (also the ibe has to be reseeded every call to UUIDGen, so slightly inefficient too).

## What is the expected behavior?
no warning spam on devices with a random number engine instead of a generator

## What behavior are you observing?
warning spam

## Provide the steps to reproduce the issue, if applicable:
build on Ubuntu 18.04 (probably most Linux devices)

### What version of the AVS Device SDK are you using?
      <1.17.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @brett-lynnes thanks for bringing this to our attention. I logged an internal ticket to track this. We will get back to you once we have more information.

**Comment by simocn77** [comment]
Hi, I have similar issue using an yocto on an imx7d platform. 

 W UUIDGeneration:low entropy on call to generate UUID:current entropy=32

Im not expert , I would like to understand if I have a problem or no.

I'm using "rngd -r /dev/hwrng" to use hw random numbers generator , and this is the out of my "random device" : using c++ (std::random_device rd;) 

#### default random_device characteristics:
#### minimum: 0
#### maximum: 4294967295
#### entropy: 32
#### a random number: 4070332805

and  :  
cat /proc/sys/kernel/random/entropy_avail
3283

in the SDK the ENTROPY_THRESHOLD for the warning is 600. 

do you think my device is ok ?

**Comment by brett-lynnes** [comment]
> Hi, I have similar issue using an yocto on an imx7d platform.
> 
> W UUIDGeneration:low entropy on call to generate UUID:current entropy=32
> 
> Im not expert , I would like to understand if I have a problem or no.
> 
> I'm using "rngd -r /dev/hwrng" to use hw random numbers generator , and this is the out of my "random device" : using c++ (std::random_device rd;)
> 
> default random_device characteristics:
> minimum: 0
> maximum: 4294967295
> entropy: 32
> a random number: 4070332805
> 
> and :
> cat /proc/sys/kernel/random/entropy_avail
> 3283
> 
> in the SDK the ENTROPY_THRESHOLD for the warning is 600.
> 
> do you think my device is ok ?

I went over the code pretty carefully where the warning is being printed. The result from the independent_bits_engine ends up getting a good seed (from some clock-based salting) and is used correctly to start generating cryptographically secure random numbers (basically, a little overkill for UUID generation, imho). The only real issue on Yocto (we use an imx6) is that every time you need a UUID it has to re-seed the engine which is a tad slow on our processors... (also generates the warning in the logs).

**Comment by scotthea-amazon** [comment]
Hi @brett-lynnes,

We now have a task in our backlog to add this feature, so I am closing out the issue.  We will announce the enhancement in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when it is implemented.

Thank you for bringing this to our attention!

Best regards,
-SWH
