### ISSUE TITLE
Avs SDK 1.17: Sample Application Build.

### ISSUE THREAD

**Issue by sakthisg** [alexa/avs-device-sdk#1606]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have cross compiled the the 1.17 with portaudio.
After Authorised, i see the  Invalid Option print continously. Not able to provide any input to the sample application.

## What is the expected behavior?
it should wait for the options to enter..

## What behavior are you observing?
continous prints of Invalid Option

## Provide the steps to reproduce the issue, if applicable:
Run the sample app with json file.

### What version of the AVS Device SDK are you using?
1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Cross compiled for linux arm

### Tell us about your OS (Type & version):
- [ ] Linux

[TVLog 16 42 55 23 Jan 20.zip](https://github.com/alexa/avs-device-sdk/files/4102885/TVLog.16.42.55.23.Jan.20.zip)

**Comment by ereich1217** [comment]
It looks like you have forced SampleApp to start at boot up.  Do you have the same problem if you start it from the command line manually?

There are extra steps you must take to get SampleApp to function correctly from start up.

**Comment by sakthisg** [comment]
I have started the sampleApp in command line manually .

**Comment by mvelegon-amzn** [comment]
Hi @sakthisg it looks like you are running the SampleApp as a background process.
`
[2020-01-23 16:44:06.452] /media/sda1/NVT_Alexa/1_17/SampleApp /media/sda1/NVT_Ale
[2020-01-23 16:44:06.452] xa/1_17/AlexaClientSDKConfig.json DEBUG9 &
`
 Is there any reason for that? 

If incase you would have to run it as a background process, you will have to use something like this:

`mkfifo /tmp/input
tail -f /tmp/input | ./SampleApp/src/SampleApp Integration/AlexaClientSDKConfig.json DEBUG9 &`

then to pass STDIN to the backgrounded sample app , use this:
`echo "q" > /tmp/input`

**Comment by sakthisg** [comment]
By removing the background & , i could see the menu properly...
With 1.17, No Sound from Alexa ! I am not hearing the playback sound with ALSA. I have referred the https://github.com/alexa/avs-device-sdk/issues/500 
Changed as below:: MediaPlayer.cpp
Changing
m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");
to
m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");
Any clue?

**Comment by dhpp** [comment]
Hi @sakthisg, did you review the GStreamer plugin requirements, which will need to be available on your target platform?  Please see here:
[https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#core-music-provider](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#core-music-provider)
and
[https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#sample-app](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#sample-app), 
since your error trace mentions a missing such dependency.  Please let us know if this helps.

**Comment by sakthisg** [comment]
i will check this, Thanks..
With portAudio, 
[TVLog 10 39 13 27 Jan 20.zip](https://github.com/alexa/avs-device-sdk/files/4142056/TVLog.10.39.13.27.Jan.20.zip)
 Sample Application crashes...backtrace is as below...

2020-01-27 10:41:36.611] #0  0x00358e80 in Copy_16_To_16 ()
[2020-01-27 10:41:36.611] [Current thread is 1 (LWP 3695)]
[2020-01-27 10:41:36.627] #0  0x00358e80 in Copy_16_To_16 ()
[2020-01-27 10:41:36.627] #1  0x0035a5f0 in NonAdaptingProcess ()
[2020-01-27 10:41:36.642] #2  0x0035b548 in PaUtil_EndBufferProcessing ()
[2020-01-27 10:41:36.642] #3  0x003522d6 in CallbackThreadFunc ()
[2020-01-27 10:41:36.642] #4  0xb5d805a2 in ?? () from /lib/libpthread.so.0
[TVLog 10 39 13 27 Jan 20.zip](https://github.com/alexa/avs-device-sdk/files/4142055/TVLog.10.39.13.27.Jan.20.zip)

**Comment by caleighatamazon** [comment]
@sakthisg Were you able to verify that you installed all required GStreamer dependencies? I still notice some GStreamer plugin-related errors in the logs.

**Comment by sakthisg** [comment]
Yes. It is working now. Thanks for the inputs!
