### ISSUE TITLE
audioVolumeRamp can only be applied to all Alerts (not just Alarms)

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1607]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
if you turn on audioVolumeRamp (gstreamer.fade) it very nicely starts the media playing from an Alarm at a low volume up to the maximum set volume. however, it also does the same thing to Timers and Reminders. this can be a problem since you might not hear a 15 second timer going off until 20 seconds or so have passed. if your alert volume is set low enough, you may miss part of a Reminder altogether since the first part could be inaudible.

in order to pass through additional information (the Type of Alert that is Rendering) to the Renderer and have the Renderer check whether the Media should play fades it would need to send something over `MediaPlayerObserverInterface::start(...) ` (which is an SDK::common::utils interface so i dont have a good way of changing it). 

currently the Renderer only checks to see if the media ramp configuration is set:
`m_alarmVolumeRampEnabled = settings::types::isEnabled(alarmVolumeRampSetting);` and doesnt have access to any information on the source of what it is rendering (except if it is a url or localAsset).

## What is the expected behavior?
Amazon devices that have alarm fading enabled (tested on the new Alexa Show) have Timers start and play at the same volume from the exact time it triggers until it is stopped, while also having the ability for Alarms start low and gradually fade in turned on. Basically Alarm volume fading should only function on Alarms, not Timers.

## What behavior are you observing?
      Timers and Reminders are also fading in if Alarm fading is enabled.

## Provide the steps to reproduce the issue, if applicable:
build 1.17. toggle Alarm fade in. set an Alarm, verify it is fading in. set a 5 second Timer, verify it also fades in (so you probably wont hear it until 10 seconds).

## Tell us about your environment:
      Linux.

### What version of the AVS Device SDK are you using?
      <1.17.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @brett-lynnes Thanks for bringing this to our attention. I logged an internal ticket to get this addressed. We will update this ticket once we have more information.

**Comment by kclchan** [comment]
Hi @brett-lynnes, we have fixed this issue in v1.18.  Thanks!

**Comment by brett-lynnes** [comment]
Tested today. Looks good.
