### ISSUE TITLE
How to get text from AVS ?

### ISSUE THREAD

**Issue by kartikeya-rana** [alexa/avs-device-sdk#1609]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I query AVS with audio file, audio file (stream bytes) is returned in response. How can I get text response from AVS? Which API should I call to get text ?

## What is the expected behavior?

AVS request (input) -> text or audio
AVS response (output) -> text and audio

## Provide the steps to reproduce the issue, if applicable:

I'm using the following python library to query AVS. https://pypi.org/project/avs-client/

### Tell us what hardware you're using:
 Desktop / Laptop

### Tell us about your OS (Type & version):
Linux
MacOS

**Comment by dhpp** [comment]
Hi @kartikeya-rana.

Please see the caption element within many AVS Directives, such as [https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/speechsynthesizer.html#speak-directive](SpeechSynthesizer.Speak).  This is provided in the WebVTT format, and you may review our [https://github.com/alexa/avs-device-sdk/tree/master/Captions](Captions) library, and the usage notes for the Captions feature [https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/features.html#captions](here).

There is no other API or mechanism at this point provided by AVS to send text data for rendered speech.

Let us know if you need any further guidance.
