### ISSUE TITLE
how run all test in  Embedded Systems ?have a script ?

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexa/avs-device-sdk#161]
In avs-device-sdk , each module have many  XXTEST  file  to test source file function with gtest,  but  too many,  can run all test  in the project  with a cpmmad ?

**Comment by sanjayrd** [comment]
Hi @zuowanbushiwo,

Just running `make test` will run all unit tests and running `make integration` will run all integration tests. Hope that helps.

Thanks,
Sanjay

**Comment by zuowanbushiwo** [comment]
@sanjayrd 
thanks very much, Maybe my statement is unclear, I want run in my  Embedded Systems openwrt  OS ( my host is ubuntu)， that maybe no ctest command，  Do you konw how I can  run those test（make test，make integration）？ thanks

**Comment by kjkh** [comment]
Hi,

I am not aware of any scripts to run all tests without using the Makefile targets. The standard way in which we do so is what @sanjayrd mentioned, and that is using the `make test` and `make integration` targets (which use ctest). To unblock, the two alternatives seem to be:

1. Cross-compile CMake onto OpenWRT.
2. Manually write script to launch test binaries.

Some tips to help if you decide to go with option 2:

Unit Tests:
You can modify <src_dir>/Tools/Testing.cmake to print out the unit tests and arguments needed after you run cmake on your host:

 20         foreach (testsourcefile IN LISTS tests)
   21             get_filename_component(testname ${testsourcefile} NAME_WE)
   22             add_executable(${testname} ${testsourcefile})
   23             target_include_directories(${testname} PRIVATE ${includes})
   24             target_link_libraries(${testname} ${libraries} gtest_main gmock_main)
   25             add_test(NAME ${testname}_test COMMAND ${testname} "${inputs}")
                    #### Add this line below ####
   26             MESSAGE(${CMAKE_CURRENT_SOURCE_DIR}/${testname} " " ${inputs})
   27             GTEST_ADD_TESTS(${testname} "${inputs}" ${testsourcefile})
   28             add_dependencies(unit ${testname})

Integration Tests:
The needed commands are in <src_dir>Integration/tests/CMakeLists.txt
