### ISSUE TITLE
 Weather forecast doesn't restart when interrupted by volume changing command

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1613]
## What is the expected behavior?
 Alexa restart the weather forecast at the new volume level.

## What behavior are you observing?
 Alexa doesn't restart the weather forecast
Log is attached below:
[log_weatherForecast.txt](https://github.com/alexa/avs-device-sdk/files/4159957/log_weatherForecast.txt)

## Provide the steps to reproduce the issue, if applicable:
1) Ask "Alexa, what's the volume?" and note the volume level.
2) Ask "Alexa, what's the weather?"
3) While Alexa is answering the weather forecast, use the command "Alexa, raise/lower the volume" to interrupt Alexa.
[Precondition]
1) UUT is connected to the internet.
2) UUT has logged in an Alexa account.
## Tell us about your environment:
HW: DVR
### What version of the AVS Device SDK are you using?
Alexa SDK; 1.17

### Tell us what hardware you're using:
 Desktop 

### Tell us about your OS (Type & version):
- [ ] Linux 

@jpeddicord @caleighatamazon @amazon-auto @jjamazon  @mavamazon  @bandkenamazoncom

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
Could you please verify this issue and let me know from where the issue is - Whether it is from AVS-SDK side or from AWS cloud.
Thanks!

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
We have verified the same issue on PURE AVS-SDK v1.17 with-out any code changes, still the issue(Weather forecast doesn't restart when interrupted by volume changing command) is reproducible for 7/8 re-trails. Could you please help to verify the same.


PURE AVS-SDK v1.17 (through Shell):

Observations for issue is reproducible scenario ( 7/8 times)

    **Listening*    -*Alexa, what is the weather in Mumbai

    **Speaking  - RenderCard Template - Weather forecast details **

    **Listening**   - Alexa, decrease/increase the volume

    **Thinking* ,* followed by  - Source AVS_SPEAKER_VOLUME changes **

    **Idle**,  followed by - Rendercard template cleared

Observations for issue is not reproduced scenario (1/8 times), log analysis as follows:

    **Listening*    -*Alexa, what is the weather in Mumbai

    **Speaking  - RenderCard Template **

    **Listening**   - Alexa, decrease/increase the volume

    **Idle**,  followed by - Source AVS_SPEAKER_VOLUME changes

    **Speaking  - Restarting Weather forecast details **

    **Idle**,  followed by - Rendercard template cleared **


Also, for reference attached are the snippets of AVS-SDK logs- for reproduced & not reproduced cases.
Thanks!
![PUPC13187_NotReproduced](https://user-images.githubusercontent.com/52921278/74586622-50e2e500-500f-11ea-8b82-5e71ff0eca64.png)
![PUPC13187_Reproduced](https://user-images.githubusercontent.com/52921278/74586623-53453f00-500f-11ea-9248-931f59ffde80.png)

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

We have not been able to reproduce this with SampleApp locally.  If you can do so, please provide us with DEBUG9 level logs for a reproduction of this issue so we can investigate.

Best regards,
-SWH

**Comment by dipalisb** [comment]
Hi @scotthea-amazon ,
I have attached the logs to this comment, please do analyze.
Thanks!
[log_weatherForecast_Debug9.txt](https://github.com/alexa/avs-device-sdk/files/4217558/log_weatherForecast_Debug9.txt)

**Comment by kclchan** [comment]
Hi @dipalisb, I have looked at the logs and I couldn't find anything wrong on the device side.  It seems the issue is that AVS is not sending a new Speak directive with the weather forecast.

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity. Please comment on this issue with more details if you think I've closed this in error. Thanks!
