### ISSUE TITLE
Alexa answer wrong volume level of timer and alarm

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1614]
## What is the expected behavior?
2) Alexa answer "timer and alarm sounds are at volume 10"
4) Every time change the volume, UUT shows white LED. The string on the screen indicate the alert volume is set to 5 and the timer sound decrease.
5) Alexa answer "timer and alarm sounds are at volume 5"

## What behavior are you observing?
 5) Alexa answer "timer and alarm sounds are at volume 10"

## Provide the steps to reproduce the issue, if applicable:
[Precondition]
1) UUT is connected to the internet.
2) UUT has logged in an Alexa account.

**SCENARIO:1**
1) "Alexa, set a timer for 5 seconds."
2) While the timer is ringing, ask "Alexa, what's the volume?" and take note of the timer and alarm volume.
3) Menu > Settings > Amazon Alexa > Alexa volume > Alert volume
4) Press vol- button to lower the volume to 5.
5) Ask "Alexa, what's the volume?"

## Tell us about your environment:
HW: DVR
### What version of the AVS Device SDK are you using?
Alexa SDK: 1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Linux

**SCENARIO:2**
1) Check CDR8010's alert volume is at level 10 and set a timer.
2) While the timer is ringing, ask "Alexa, what's the volume?" and take note of the timer and alarm volume.
3) On CDR8010: Menu > Settings > Amazon Alexa > Alexa volume > Alert volume
4) Press vol- button to lower the volume to 5.
5) Ask "Alexa, what's the volume?"
6) On Alexa APP: Menu > Reminders & Alarms >Timers > Settings > Choose CDR8010
7) Drag the volume bar to volume 0
8) Ask  "Alexa, what's the volume?"
Observations:
2) Alexa answer "timer and alarm sounds are at volume 10"
4) Alert sounds lower and on CDR8010 it display the message"Alexa volume set to 5"
5) Alexa answer "timer and alarm sounds are at volume 10"
6) Alexa APP shows the alert volume is  at volume 10
7) The timer doesn't sound. Alexa APP and CDR8010 show the volume is at volume 0.
8) Alexa answer "timer and alarm sounds are at volume 0"

@amazon-auto @jjamazon  @bandkenamazoncom @mavamazon  @caleighatamazon

**Comment by dipalisb** [comment]
Hi @caleighatamazon ,
Could you please verify this issue and let me know from where the issue is - Whether it is from AVS-SDK side or from AWS cloud.
Thanks!

**Comment by dipalisb** [comment]
Hi @caleighatamazon 
We have verified this issue on AVS-SDK v1.17 without any code changes. Issue is reproducible over there also. Please help to verify & confirm the same.
**Below are  the steps for test procedure:**
1) Check CDR8010's alert volume is at level 10 and set a timer.
2) While the timer is ringing, ask "Alexa, what's the volume?" and take note of the timer and alarm volume.
3) On CDR8010: Menu > Settings > Amazon Alexa > Alexa volume > Alert volume
4) Press vol- button to lower the volume to 5.
5) Ask "Alexa, what's the volume?"
6) On Alexa APP: Menu > Reminders & Alarms >Timers > Settings > Choose CDR8010
7) Drag the volume bar to volume 0
8) Ask  "Alexa, what's the volume?"

**[ Acualobservation]**
2) Alexa answer "timer and alarm sounds are at volume 10"
4) Alert sounds lower and on CDR8010 it display the message"Alexa volume set to 5"
5) Alexa answer "timer and alarm sounds are at volume 10"
6) Alexa APP shows the alert volume is  at volume 10
7) The timer doesn't sound. Alexa APP and CDR8010 show the volume is at volume 0.
8) Alexa answer "timer and alarm sounds are at volume 0"

Analysis:
Changes at Amazon Alexa App side are getting reflected over the CDR device, but changes from CDR device are not getting reflected at Amazon Alexa App side.
Please help to verify & confirm the same. Thanks!

**Comment by kclchan** [comment]
Hi @dipalisb, could you tell us on what's being done in Step 3 `On CDR8010: Menu > Settings > Amazon Alexa > Alexa volume > Alert volume`?  Please note that there's currently no event for a device to report to AVS about changes to the alarm volume.

**Comment by dipalisb** [comment]
Hi @kclchan ,
For your below query:
**Please note that there's currently no event for a device to report to AVS about changes to the alarm volume.**
>> Does this mean that the changes (related to alerts) from device side won't reflect at AVS-SDK?
     Please do confirm. Thanks!

**Comment by kclchan** [comment]
Hi @dipalisb, yes, since there's no such event, alerts volume changes made on the device will not be reflected in AVS.

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
