### ISSUE TITLE
AVS Android SDK Setup

### ISSUE THREAD

**Issue by sai13ram** [alexa/avs-device-sdk#1615]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am following the steps in accordance with the site [(https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html#get-started )](url) and in the step 3 of Authorization, while running the command `sudo bash setup.sh config.json -a androidConfig.txt` i am not getting the Sample App getting installed. Instead, i am getting an error as below
```
================================================================================
= Wait until device is online. Please make sure the device is 
= connected.
================================================================================

= Make sure device intall target exists and has write permission
mkdir: '/home': Read-only file system
```

## What is the expected behavior?
It is expected to show the progress of installation of the App in the Android Device i think so

## What behavior are you observing?
```
================================================================================
= Wait until device is online. Please make sure the device is 
= connected.
================================================================================

= Make sure device intall target exists and has write permission
mkdir: '/home': Read-only file system
```
## Tell us about your environment:
Ubuntu 18.04LTS with ADB, AVS SDK on Android Set up
### What version of the AVS Device SDK are you using?
      <1.17.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
- [x] Linux

**Comment by FennyR** [comment]
Hi,
 I am also facing the same issue. I am trying to build the AVS SDK sample app on an android device. I am using Macbook with Catalina OS for development. Please find the logs below.

================================================================================
= Installing AVS Device SDK on the target device.
================================================================================
= Wait until device is online. Please make sure the device is 
= connected.
================================================================================
= Make sure device intall target exists and has write permission
mkdir: '/System': Read-only file system
