### ISSUE TITLE
Problem adding Raspi Alexa device to MRM group

### ISSUE THREAD

**Issue by leramleram** [alexa/avs-device-sdk#1616]
Hi there!

I have issues with my newly created Alexa device running on a Rasberry 3 B+ (Stretch)
After everything had been set up like described at https://developer.amazon.com, I tried to connect the new device to my MRM group via the IOS Alexa app.
Unfortunately it tells me that the Alexa device on the Raspi needs a firmware update.

## Briefly summarize your issue:
Cannot add Alexa on raspberry to Multiroom Music group due to "firmware update needed"

## What is the expected behavior?
Adding MRM should be possible

## What behavior are you observing?
If I want to add the Alexa device i just created on my raspberry via the IOS Alexa app to my MRM group, but if i try then the IOS app reports "firmware update needed".

## Provide the steps to reproduce the issue, if applicable:
-Installed and set up everything like described at https://developer.amazon.com/

## Tell us about your environment:
-Rasberry 3 B+
-Raspbian stretch with up to date packages

### What version of the AVS Device SDK are you using?
      not sure, did it with the actual available version

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello @leramleram,

MRM is an optional feature that requires additional software.  You will need to work through your Amazon business contact to get access to the additional software required.

Best regards,
-SWH
