### ISSUE TITLE
Alexa goes offline after some time

### ISSUE THREAD

**Issue by zeesh1979** [alexa/avs-device-sdk#1617]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am running alexa in background but after some time it goes offline and stops responding

## What is the expected behavior?
it should keep on running

## What behavior are you observing?
it goes offline after sometime

## Provide the steps to reproduce the issue, if applicable:
i am using crontab to run alexa at startup/after reboot using:
crontab -e
and put this line in there: @reboot sudo bash startsample.sh

alexa works fine and responds good...but after say 30min or sometimes more when i say the wake word nothing happens. as i am running in background so i dont know what is going on or how i see what happened, so when i check on my Amazon Alexa app installed on mobile, the status shown is offline

## Tell us about your environment:
I am using Stretch
### What version of the AVS Device SDK are you using?
how to check this? i am using the install instructions from same amazon developer link and assume it contains the latest version
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by zeesh1979** [comment]
today i removed it from running at boot and ran it in normal TTY for many hours and there was no issue. why its giving problem when we run at startup in any way (tried running as service as well as via crontab).....it works for some time and then stop responding. when checked in alexa app, it shows the status is offline

**Comment by zeesh1979** [comment]
today i modified my LXDE file to run alexa at boot
sudo nano /home/pi/.config/lxsession/LXDE-pi/autostart
and added below
@sudo bash /home/pi/startsample.sh

after boot, alexa was working fine but then again when i checked after around 30min, it wasnt running. i ran the command top to check running items, when alexa was responding then top showed me at the top but when it stopped the top wasnt showing sampleapp running...please help as i am banging my head for last many days :(

**Comment by zeesh1979** [comment]
one more thing, i have also changed my uimanager file to show me LED indications based on state. these LEDs work fine if u run sample app via terminal (alexa also works fine without interruption) but when i use any of the methods to run at boot my LEDs do not work in normal way even if alexa is working or no

**Comment by scotthea-amazon** [comment]
Hello @zeesh1979,

It is very hard to see what is going wrong without more data.

Can you provide a DEBUG9 level log (must be built as a DEBUG build, and SampleApp started with the DEBUG9 log level on the command line).

Best regards,
-SWH

**Comment by zeesh1979** [comment]
Thanks for the response. i finally resolved it yesterday. the problem was due to high cpu utilization of sample app when i run it headless. i spotted a similar issue of high cpu here and went through the steps and it resolved the issues....thanks again. keep up the good work. im going to close this issue now
