### ISSUE TITLE
AVS stop capture and AVS response takes more time

### ISSUE THREAD

**Issue by FinnyBaskar** [alexa/avs-device-sdk#1619]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Start simple query(what is the weather in london), AVS state changes to LISTENING, after query utterance, stop capture comes after ~1sec.  Stop capture to audio being played out takes ~ 3.5secs. 

## What is the expected behavior?

Expect the stop capture comes faster and the query response (from stop capture to speak direction) in less than 2 secs
## What behavior are you observing?

stop capture comes after ~1sec after utterance.  Stop capture to audio being played out takes ~ 3.5secs. 
## Provide the steps to reproduce the issue, if applicable:

logs are attached for reference
[AVS-Response-Delayed.log](https://github.com/alexa/avs-device-sdk/files/4185634/AVS-Response-Delayed.log)

## Tell us about your environment:

Following things are tried, but did not help
1) changed the endpoint to "endpoint": "https://alexa.eu.gateway.devices.a2z.com"
2)  "gstreamerMediaPlayer":{
         "outputConversion":{
             "rate":16000,
             "format":"S16LE",
             "channels":1
         },
        "audioSink":"alsasink"
     }
3) compile the SDK with RELEAE build
### What version of the AVS Device SDK are you using?
      <1.14.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:  Cortex-A9

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello @FinnyBaskar,

The timing of StopCapture is driven by AlexaService deciding that it has heard enough.  One second after the user stops speaking is not particularly unusual. .

Looking at the attached log I see the following:

The user speaks for at most 3.7 seconds, at which point a StopCapture directive arrives.
`
2020-02-11 11:32:13.708 [  c] 0 EventBuilder:buildJsonEventString:messageId=959d6b16-ded8-45ae-8e32-3d14afd64172,namespace=SpeechRecognizer,name=Recognize
2020-02-11 11:32:17.464 [  8] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"344e0cf4-903c-4a7b-8076-ccfe308ef5a5"\,dialogRequestId\:"f427222c-6815-4b8d-a865-30ce9669aee5"}
`

The Speak directive arrives in less than 600 milliseconds.
`
2020-02-11 11:32:18.022 [  8] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"bee1a4d3-6521-4719-9c07-ffd9e945b0b6"\,dialogRequestId\:"f427222c-6815-4b8d-a865-30ce9669aee5"}
`

Playback of the received Alexa Speech starts within another 600 milliseconds.
`
2020-02-11 11:32:18.606 [  e] 9 SpeechSynthesizer:onPlaybackStarted:callbackSourceId=3
2020-02-11 11:32:32.037 [  e] 9 SpeechSynthesizer:onPlaybackFinished:callbackSourceId=3`

Even including a 1 second pause between the end of user speech and the arrival of StopCapture, from these logs it looks like the delay is only 2.2 seconds (1 + 0.6 + 0.6) - not 3.5 seconds.

Are you experiencing a consistent 3.5 second delay?  Might another log show a more problematic example?

Best regards,
-SWH

**Comment by FinnyBaskar** [comment]
Hello @scotthea-amazon 
         Thanks.
we learned that end of query to the response played by alexa should be less than 2.1 sec. So trying to identify where delay is introduced . 

In the attached log the delay is ~ 2.7 sec.

attached the logs and also audio capture for reference
[logs.zip](https://github.com/alexa/avs-device-sdk/files/4204013/logs.zip)


Regards
Finny

**Comment by kclchan** [comment]
Hi @FinnyBaskar,

From the logs, again I am not seeing much delay.

After the user stops speaking and AVS determines that it's the end of the utterance (as @scotthea-amazon, this may take around one second), AVS sends a StopDirective at:

`2020-02-11 12:41:00.234 [  5] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"05d579f0-dc9f-4b6d-a440-2d2985ecf776"\,dialogRequestId\:"5aee8561-0721-49ea-851c-5497a3062a37"}`

And in ~600ms, AVS sends a Speak directive with the weather information:
`2020-02-11 12:41:00.800 [  5] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"106f5dec-a03f-46fc-852d-a0212f697981"\,dialogRequestId\:"5aee8561-0721-49ea-851c-5497a3062a37"}`

And in less than 100ms, the device starts speaking:
`2020-02-11 12:41:01.816 [  e] 0 MediaPlayer:callingOnPlaybackStarted:name=SpeakMediaPlayer,currentId=1`

Thanks.

**Comment by FinnyBaskar** [comment]
Hello @kclchan ,
                       thanks. 
The similar use case i tested on echo and found the overall response is much faster. Attached the captured wave file for reference.  in the  captured  audio, end of utterance to response is being played by Alexa is just ~1.6sec. 
I think the 1 sec stop capture delay makes the difference between these two. 

Is it any way related to the audio quality that is being sent from our platform ?. 
Are there anything can be done to reduce stop capture delay ?

[Response-echo.zip](https://github.com/alexa/avs-device-sdk/files/4225053/Response-echo.zip)

Regards
Finny

**Comment by FinnyBaskar** [comment]
Hello @scotthea-amazon  @kclchan ,
 
any update ??

Regards
Finny

**Comment by samcoult** [comment]
Hi @FinnyBaskar  , from the logs you provided the delays do not seem too unusual. It is possible the hardware from your platform is slower than the echo device.

**Comment by FinnyBaskar** [comment]
Thanks, Let me check
