### ISSUE TITLE
Run Authserver on device without display

### ISSUE THREAD

**Issue by nunokid** [alexa/avs-device-sdk#162]
I am going to integrate AVS SDK on fedora base.
However, there is no display on the device.
How do I go about completing the sdk build and running authserver?

Can I run the browser remotely after running AuthServer.py?

**Comment by sanjayrd** [comment]
Hi @nunokid,

There's no need to run the auth server specifically on your device without a display. You can always generate the refresh token and other credentials using the AuthServer on some local machine and then copy over the filled out JSON file with your credentials into your device.

Hope that helps,
Sanjay
