### ISSUE TITLE
Unable to test IHeart Radio Custom music validation testing for 1 hr / 24 hr

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1621]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 We need to generate ALL PASS report for IHeart Radio Custom music validation testing. We have used the check-list provided by Alexa Voice Service to test the scenarios. As we go with the check-list (contains the "next" utterance 8 times), at one time testing we can not skip the song more than 8 times. Once the limit exceeds, the response came on Tuesday as  "you can not skip the song anymore for 1 hour" and on Wednesday the response is as "you can not skip the song anymore for 24 hour".

## What is the expected behavior?

--> There should not be any conditions to test the music validation for IHeart Radio Custom.
 
## What behavior are you observing?

--> We have to hold our testing for 1 hr/24 hr which is not correct

## Provide the steps to reproduce the issue, if applicable:

1. Test the utterance in IHeart Radio Custom Skill check-list (Please find the attached 
[iHeartRadioCertificationChecklist_05_03_2019.xlsx](https://github.com/alexa/avs-device-sdk/files/4198566/iHeartRadioCertificationChecklist_05_03_2019.xlsx)
Check-list)

**Comment by scotthea-amazon** [comment]
Hello @dipalisb,

It sounds like you will need to upgrade the iHeart radio account you are using for testing such that it allows for unlimited skipping.  A quick search on this turned up the following link: [Skip limit on iHeartRadio](https://help.iheart.com/hc/en-us/articles/228919387-Skip-limit-on-iHeartRadio)

Best regards,
-SWH

**Comment by caleighatamazon** [comment]
I'm going to close this issue due to inactivity, but please open a new one if you're continuing to have problems with this. Thanks!
