### ISSUE TITLE
Raspberry PI with Alexa does not recognise custom skills

### ISSUE THREAD

**Issue by vjvicky007** [alexa/avs-device-sdk#1625]
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [x] Raspbian Buster
- [ ] Other - tell us more:

i cant able to call my customized skill using avs in alexa-raspberry.

**Comment by samcoult** [comment]
Hi @vjvicky007 

Are you able to call your customized skill using the Alexa app, or the SDK on a different platform?

**Comment by vjvicky007** [comment]
Hi @samcoult 
yes i can able to call my customized skill using alexa app. The problem in my project is , i run the avs-device-sdk in my raspberry pi 4 so that i can able to activate avs. Its showing response to my command.e.g) what is the time now? and i got a response its 11.56 AM. But i can't able to open or call any of my customized skill in same alexa account using raspberry. is there any chance to call my customized skill?????

**Comment by samcoult** [comment]
Hi @vjvicky007 

You should be able to call your custom skill from the SDK Sample App running on any platform. It's possible that your device is not authorized to use your custom skill. I suggest you consult the Alexa Developer Portal support knowledge-base and forum to help you get your device authorized to use your custom skill. https://forums.developer.amazon.com/index.html

**Comment by vjvicky007** [comment]
Hi @samcoult 
Thank you sam and i have submit my queries in alexa developer portal. But already some have asked same type of question but there is no solution for the probelm. They have replied "you can able to call your skill" thats it. No solution for the probelm. let wait for the response.

**Comment by vjvicky007** [comment]
Hi @sam,
I didn't get any response from amazon forum ,even i have raised same question in AVS dashboard. Is it compulsory for the device to get authorized for the devices.

**Comment by samcoult** [comment]
Hi @vjvicky007 ,

Unfortunately custom skill development and enabling is outside the scope of this support forum and we will not be able to assist you.

**Comment by vjvicky007** [comment]
HI @samcoult ,
Okay sam

**Comment by vjvicky007** [comment]
Hi @samcoult ,
Is there any other forum is available regarding same problem. can you suggest me?

**Comment by samcoult** [comment]
Hi @vjvicky007 , I believe the developer forum linked above is the best resource.

**Comment by vjvicky007** [comment]
Hi @samcoult ,
Thank you.
