### ISSUE TITLE
Bluetooth is not working with latest iOS 13.3.1

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1626]
BT is not connecting with IOS 13.3.1

## What is the expected behavior?
BT should connects with latest IOS 13.3.1

## What behavior are you observing?
BT is not connecting.

## Tell us about your environment:
Other: Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

AVS SDK Version 1.14.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### What version of the AVS Device SDK are you using?
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by samcoult** [comment]
Hi @mohitbansal19 

Are you able to connect over BlueTooth with the latest version of the SDK (1.18)?

**Comment by mohitbansal19** [comment]
Hi @samcoult 

   We did not try with latest v1.18 SDK as we are getting some linking issues in Alexa compilation.
Below is the reference for that issue that we raised for compilation issue:- 

https://github.com/alexa/avs-device-sdk/issues/1631

Thanks
Mohit Bansal

**Comment by caleighatamazon** [comment]
Okay, I see that issue. If you're still unable to compile 1.18, in the meantime, can you please provide us with full DEBUG9 logs for 1.14 so we can take a look at that? Thanks.

**Comment by mohitbansal19** [comment]
Hi,

    After updating BlueZ stack 5.5 this is working with us.

Thanks
Mohit Bansal

**Comment by caleighatamazon** [comment]
Great, thanks. I'm going to close this issue.
