### ISSUE TITLE
CBLAuthDelegate:receiveTokenResponseFailed:result=AUTHORIZATION_PENDING

### ISSUE THREAD

**Issue by gudipudiramanakumar** [alexa/avs-device-sdk#1630]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I'am not recieving the device code and link to get my device authorised.

##################################
#       NOT YET AUTHORIZED       #
##################################
################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
################################################################################################

###########################
#       Authorized!       #
###########################
########################################
#       Alexa is currently idle!       #
########################################

##################################################
#       Checking for authorization (18)...       #
##################################################

2020-02-27 03:16:18.737 [  3] 5 HttpPost:doPostSucceeded:code=400
2020-02-27 03:16:18.739 [  3] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2020-02-27 03:16:18.740 [  3] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2020-02-27 03:16:18.740 [  3] 5 CBLAuthDelegate:errorInLwaResponseBody:error=authorization_pending,errorCode=AUTHORIZATION_PENDING
2020-02-27 03:16:18.741 [  3] 5 CBLAuthDelegate:setAuthError:authError=AUTHORIZATION_PENDING
2020-02-27 03:16:18.742 [  3] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=AUTHORIZATION_PENDING
2020-02-27 03:16:23.746 [  3] 5 CBLAuthDelegate:requestToken

## Provide the steps to reproduce the issue, if applicable:
Double clicking startsample.bat.

### Tell us what hardware you're using:
- [* ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [* ] Other - Windows 10

**Comment by mikeluebke** [comment]
How did you fix this issue? I am having the same thing only on a raspberry pi

**Comment by javierbu** [comment]
I have the same problem. but he never authorizes me. I have tried deleting cblAuthDelegate.db and generating a new config.json. I understand that the config.json prevents the error of mistyping the clientID. I'm working on bullseye in raspberry.
can it compile without errors in bullseye?

**Comment by Pseudomizer** [comment]
Same here. It never authorizes and says Authorization pending. I redid the security profile, I activated it, checked the config and Alexa Integration files over and over again. I recompiled the SDK with and without DKCS11 as I saw somewhere that it is now required, but this changed nothing. 

It goes into this loop of Checking for Authorization... :-(
