### ISSUE TITLE
Alexa v1.18.0 compilation issue

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1631]
## Briefly summarize your issue:
We are getting compilation issue in Alexa while using v1.18.0, while v1.14 alexa is compiling successfully with same environment.  

## What is the expected behavior?
Alexa with v1.18.0 should compile successfully.

## What behavior are you observing?
We are compiling Alexa with DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON flags. We are getting linking issues from v1.18 onwards with portaudio. 

Below is the error we are getting:- 

[100%] Linking CXX shared library libLibSampleApp.so
/opt/toolchains/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: /home/mbansal/build/MagicBox_AlexaSrc/build/build_debug_18/lib/libportaudio.a(pa_front.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/mbansal/build/MagicBox_AlexaSrc/build/build_debug_18/lib/libportaudio.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/LibSampleApp.dir/build.make:478: recipe for target 'SampleApp/src/libLibSampleApp.so' failed
make[2]: *** [SampleApp/src/libLibSampleApp.so] Error 1
CMakeFiles/Makefile2:13254: recipe for target 'SampleApp/src/CMakeFiles/LibSampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/LibSampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2 

## Provide the steps to reproduce the issue, if applicable:
Below is the cmake command that we are using to compile Alexa:- 
cmake -DCMAKE_TOOLCHAIN_FILE=$BUILD_PATH/build/toolchain.cmake $SRC_PATH -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -DKWD=ON -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$LIB_PATH/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$INCLUDE_PATH -DAMAZONLITE_KEY_WORD_DETECTOR=ON -DAMAZONLITE_KEY_WORD_DETECTOR_LIB_PATH=$LIB_PATH/libpryon_lite.a -DAMAZONLITE_KEY_WORD_DETECTOR_INCLUDE_DIR=$INCLUDE_PATH -DAMAZONLITE_KEY_WORD_DETECTOR_DYNAMIC_MODEL_LOADING=ON -DBLUETOOTH_BLUEZ=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACSDK_EMIT_SENSITIVE_LOGS=OFF -DBLUETOOTH_BLUEZ_PULSEAUDIO_OVERRIDE_ENDPOINTS=ON

## Tell us about your environment:
Other: Hardware: Samsung Artik 305 Secure Board
ARH: ARMv7

AVS SDK Version 1.18.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### What version of the AVS Device SDK are you using?
1.18.0

### Tell us what hardware you're using:
ARMv7 with hard floating point

**Comment by mohitbansal19** [comment]
Hi AVS,
   Adding some more inputs:- 
We cross compiled portaudio with FPIC flag and that FPIC issue is resolved.
But now jack related errors are coming. Below are the errors which we are getting:- 

[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/main.cpp.o
[100%] Linking CXX executable SampleApp
/opt/toolchains/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libcrypto.so.1.1, needed by /usr/arm-linux-gnueabihf/lib/libcurl.so, may conflict with libcrypto.so.1.0.0
libLibSampleApp.so: undefined reference to `jack_activate'
libLibSampleApp.so: undefined reference to `jack_port_get_latency'
libLibSampleApp.so: undefined reference to `jack_frame_time'
libLibSampleApp.so: undefined reference to `jack_set_process_callback'
libLibSampleApp.so: undefined reference to `jack_client_close'
libLibSampleApp.so: undefined reference to `jack_get_sample_rate'
libLibSampleApp.so: undefined reference to `jack_get_ports'
libLibSampleApp.so: undefined reference to `jack_port_disconnect'
libLibSampleApp.so: undefined reference to `jack_port_name'
libLibSampleApp.so: undefined reference to `jack_connect'
libLibSampleApp.so: undefined reference to `jack_get_buffer_size'
libLibSampleApp.so: undefined reference to `jack_port_name_size'
libLibSampleApp.so: undefined reference to `jack_port_unregister'
libLibSampleApp.so: undefined reference to `jack_client_name_size'
libLibSampleApp.so: undefined reference to `jack_set_sample_rate_callback'
libLibSampleApp.so: undefined reference to `jack_deactivate'
libLibSampleApp.so: undefined reference to `jack_port_get_buffer'
libLibSampleApp.so: undefined reference to `jack_port_register'
libLibSampleApp.so: undefined reference to `jack_port_connected'
libLibSampleApp.so: undefined reference to `jack_set_error_function'
libLibSampleApp.so: undefined reference to `jack_on_shutdown'
libLibSampleApp.so: undefined reference to `jack_get_client_name'
libLibSampleApp.so: undefined reference to `jack_set_xrun_callback'
libLibSampleApp.so: undefined reference to `jack_client_open'
libLibSampleApp.so: undefined reference to `jack_port_by_name'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:141: recipe for target 'SampleApp/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:13334: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed

Thanks,
Mohit Bansal

**Comment by samcoult** [comment]
Hi @mohitbansal19 

In the 1.18 build we now require linking against the shared portaudio library, eg. the **libportaudio.so** file.

Try a clean build with `-DPORTAUDIO_LIB_PATH=$LIB_PATH/libportaudio.so`

Thanks

**Comment by mohitbansal19** [comment]
Hi @samcoult 
   We tried with .so also, but we are getting some jack related errors that I shared you in above chat. Below are the errors that we are getting:- 

[100%] Built target LibSampleApp
Scanning dependencies of target SampleApp
[100%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/main.cpp.o
[100%] Linking CXX executable SampleApp
/opt/toolchains/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libjack.so.0, needed by /home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so, not found (try using -rpath or -rpath-link)
/opt/toolchains/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libcrypto.so.1.1, needed by /usr/arm-linux-gnueabihf/lib/libcurl.so, may conflict with libcrypto.so.1.0.0
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_activate'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_get_latency'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_frame_time'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_set_process_callback'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_client_close'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_get_sample_rate'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_get_ports'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_disconnect'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_name'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_connect'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_get_buffer_size'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_name_size'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_unregister'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_client_name_size'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_set_sample_rate_callback'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_deactivate'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_get_buffer'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_register'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_connected'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_set_error_function'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_on_shutdown'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_get_client_name'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_set_xrun_callback'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_client_open'
/home/vaishali/build/MagicBox_Alexa/build/build_debug_18/lib/libportaudio.so: undefined reference to `jack_port_by_name'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:141: recipe for target 'SampleApp/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:13334: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

We got success in compilation when we compile portaudio with disable "jack" option. Please confirm is there any new dependency introduces regarding "jack" in new SDK-18.

Thanks
Mohit Bansal

**Comment by mvelegon-amzn** [comment]
@mohitbansal19 we do not have any new dependency that is introduced regarding the jack option in v 1.18. We do have a change where we started using a shared library for port audio instead of the static library as before.

**Comment by caleighatamazon** [comment]
@mohitbansal19 Have you been able to resolve this problem?

**Comment by mohitbansal19** [comment]
Hi @caleighatamazon 

   Yes, my problem has been resolved after using libportaudio.so file. 

For reference I am adding some points that we used to create libportaudio.so :- 
./configure CFLAGS=-fPIC –jack-disable

Note:- We don't have jack port in our hardware device.

Thanks,
Mohit Bansal

**Comment by IeiuniumLux** [comment]
Wow @mohitbansal19, thank you!  I just hit the same issue and `CFLAGS=-fPIC` fixed it.

```./configure CFLAGS=-fPIC --without-jack && make```

**Comment by caleighatamazon** [comment]
Nice! I'm going to close this issue.
