### ISSUE TITLE
AVS Device SDK v1.18 google test compile error for iOS AVS SDK

### ISSUE THREAD

**Issue by ssneeraj** [alexa/avs-device-sdk#1633]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
On the link https://developer.amazon.com/pt-BR/docs/alexa/avs-device-sdk/ios.html
Performing Step **4 Download and cross-compile Google Test.**

Running

**cmake ../googletest \
-DIOS_DEPLOYMENT_TARGET=10.0 \
-DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake \
-DIOS_PLATFORM=OS \**

## What is the expected behavior?

Should result in no compile errors

## What behavior are you observing?
HQsharmneMAC:cross-compile sharmne$ cd googletest_build
HQsharmneMAC:googletest_build sharmne$ cmake ../googletest \
> -DIOS_DEPLOYMENT_TARGET=10.0 \
> -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake \
> -DIOS_PLATFORM=OS \
> 
CMake Deprecation Warning at /Users/sharmne/cross-compile/ios-cmake/ios.toolchain.cmake:150 (message):
  IOS_PLATFORM argument is DEPRECATED.  Consider using the new PLATFORM
  argument instead.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)

CMake Deprecation Warning at /Users/sharmne/cross-compile/ios-cmake/ios.toolchain.cmake:155 (message):
  IOS_DEPLOYMENT_TARGET argument is DEPRECATED.  Consider using the new
  DEPLOYMENT_TARGET argument instead.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CMakeDetermineSystem.cmake:90 (include)
  CMakeLists.txt:10 (project)

-- Enabling bitcode support by default. ENABLE_BITCODE not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Configuring iphoneos build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
-- Using minimum deployment version: 10.0 (SDK version: 13.2)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- Using a data_ptr size of: 8
-- Using install_name_tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
CMake Deprecation Warning at /Users/sharmne/cross-compile/ios-cmake/ios.toolchain.cmake:150 (message):
  IOS_PLATFORM argument is DEPRECATED.  Consider using the new PLATFORM
  argument instead.
Call Stack (most recent call first):
  /Users/sharmne/cross-compile/googletest_build/CMakeFiles/3.16.4/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:10 (project)

CMake Deprecation Warning at /Users/sharmne/cross-compile/ios-cmake/ios.toolchain.cmake:155 (message):
  IOS_DEPLOYMENT_TARGET argument is DEPRECATED.  Consider using the new
  DEPLOYMENT_TARGET argument instead.
Call Stack (most recent call first):
  /Users/sharmne/cross-compile/googletest_build/CMakeFiles/3.16.4/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:10 (project)

-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/sharmne/cross-compile/googletest_build
HQsharmneMAC:googletest_build sharmne$ make
Scanning dependencies of target gtest
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /Users/sharmne/cross-compile/googletest/googletest/src/gtest-all.cc:38:
In file included from /Users/sharmne/cross-compile/googletest/googletest/include/gtest/gtest.h:62:
In file included from /Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-internal.h:40:
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:842:12: error: no member named 'make_tuple' in namespace 'std'
using std::make_tuple;
      ~~~~~^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:843:12: error: no member named 'tuple' in namespace 'std'
using std::tuple;
      ~~~~~^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:922:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_ASSIGN_(RE);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:965:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(GTestLog);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:965:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1209:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(Notification);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1209:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1319:22: error: 'override' keyword is a C++11 extension [-Werror,-Wc++11-extensions]
  ~ThreadWithParam() override { Join(); }
                     ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1328:14: error: 'override' keyword is a C++11 extension [-Werror,-Wc++11-extensions]
  void Run() override {
             ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1343:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(ThreadWithParam);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1343:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1701:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(Mutex);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1701:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1719:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(GTestMutexLock);
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1719:3: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1776:5: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
    GTEST_DISALLOW_COPY_AND_ASSIGN_(ValueHolder);
    ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1776:5: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1808:5: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
    GTEST_DISALLOW_COPY_AND_ASSIGN_(ValueHolderFactory);
    ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:682:24: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  type(type const &) = delete; \
                       ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:1808:5: error: deleted function definitions are a C++11 extension
      [-Werror,-Wc++11-extensions]
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:683:3: note: expanded from macro 'GTEST_DISALLOW_COPY_AND_ASSIGN_'
  GTEST_DISALLOW_ASSIGN_(type)
  ^
/Users/sharmne/cross-compile/googletest/googletest/include/gtest/internal/gtest-port.h:677:35: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  type& operator=(type const &) = delete
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
HQsharmneMAC:googletest_build sharmne$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

## Provide the steps to reproduce the issue, if applicable:

On the link https://developer.amazon.com/pt-BR/docs/alexa/avs-device-sdk/ios.html

After you have done steps 1 - 3
Performing Step **4 Download and cross-compile Google Test.**

Running

**cmake ../googletest \
-DIOS_DEPLOYMENT_TARGET=10.0 \
-DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake \
-DIOS_PLATFORM=OS \**

## Tell us about your environment:
<!--- Include as many relevant details about the environment you experienced the bug in -->
### What version of the AVS Device SDK are you using?
 AVS SDK v1.18

### Tell us what hardware you're using:
- [Y] Laptop

### Tell us about your OS (Type & version):
MacOS 
Mojave Version 10.14.6 

**gcc --version**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by mvelegon-amzn** [comment]
it seems like the compilation errors above are because of C++11 usage in googletest 

Can you add this cmake flag to check if it helps with the compilation?

`-DCMAKE_CXX_FLAGS:STRING=-std=c++11`

**Comment by ssneeraj** [comment]
Here's the command and googletest compiled without error adding -DCMAKE_CXX_FLAGS:STRING=-std=c++11

**cmake ../googletest -DEPLOYMENT_TARGET=10.0 -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake -DPLATFORM=OS -DCMAKE_CXX_FLAGS:STRING=-std=c++11**


HQsharmneMAC:googletest_build sharmne$ cmake ../googletest -DEPLOYMENT_TARGET=10.0 -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake -DPLATFORM=OS -DCMAKE_CXX_FLAGS:STRING=-std=c++11
-- Using the default min-version since DEPLOYMENT_TARGET not provided!
-- Enabling bitcode support by default. ENABLE_BITCODE not provided!
-- Enabling ARC support by default. ENABLE_ARC not provided!
-- Hiding symbols visibility by default. ENABLE_VISIBILITY not provided!
-- Using NON-strict compiler checks by default. ENABLE_STRICT_TRY_COMPILE not provided!
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Configuring iphoneos build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
-- Using minimum deployment version: 9.0 (SDK version: 13.2)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- Using a data_ptr size of: 8
-- Using install_name_tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Enabling bitcode support.
-- Enabling ARC support.
-- Hiding symbols (-fvisibility=hidden).
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    EPLOYMENT_TARGET


-- Build files have been written to: /Users/sharmne/cross-compile/googletest_build

**Comment by mvelegon-amzn** [comment]
Thanks, I am closing this issue for now and we will track it through our internal ticket to update documentation.

**Comment by 593980284** [comment]
I met the same problem, how to solve it？

**Comment by NISHIGANDHA123** [comment]
Hi, I am facing issue in building AVS SDK framework on iOS platform.
Below issue we are facing when I trigger build command.

CMake Error at /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL: Found unsuitable version "7.64.1", but required is at
  least "7.67.0" (found
  /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/lib/libcurl.tbd,
  )
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/FindCURL.cmake:181 (find_package_handle_standard_args)
  cmakeBuild/cmake/Curl.cmake:11 (find_package)
  cmakeBuild/BuildDefaults.cmake:21 (include)
  cmakeBuild/BuildDefaults.cmake:62 (include_once)
  CMakeLists.txt:14 (include)

I tried changing the curl default path by setting export PATH="/usr/local/Cellar/curl/7.82.0/bin:$PATH" 

And now when i run 
curl -V
It displays 
- curl -V
- curl 7.82.0 (x86_64-apple-darwin20.6.0) libcurl/7.82.0 (SecureTransport) OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libssh2/1.10.0 nghttp2/1.47.0 librtmp/2.3 OpenLDAP/2.6.1
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets zstd
 
Please help me.
Not able to proceed.
