### ISSUE TITLE
iPhone 11(ios:13.3.1) is not able to connect through alexa voice command

### ISSUE THREAD

**Issue by amitchauhan18may** [alexa/avs-device-sdk#1639]
[**IMPORTANT**:]([url]([url](url))) Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Alexa is not controlling Connect/Disconnect for iPhone11(ios:13.3.1)

## What is the expected behavior?

1. It should connect/Disconnect using Voice Assistant
## What behavior are you observing?

1. It is not controlling connect/disconnect

## Provide the steps to reproduce the issue, if applicable:

1. First we paired with the device manually
2. Ask multiple query for Connect/Disconnect my phone
3. It won't connect/disconnect
4. While ask for connecting: It says no device found to connect
5. While ask for disconnect: No device to disconnect

## Tell us about your environment:
- [Ubuntu-16.04 ] Linux: 4.4.71
PulseAudio: 12.2
BlueZ:5.50
iphone 11(ios:13.3.1)

### What version of the AVS Device SDK are you using?
      <1.18.0>

### Tell us what hardware you're using:
On artik-305

### Tell us about your OS (Type & version):
- [Ubuntu-16.04 ] Linux: 4.4.71
PulseAudio: 12.2
BlueZ:5.50

**Comment by mvelegon-amzn** [comment]
Hi, Thanks for reaching out. In order for us to help us debug further, could you please add the DEBUG9 logs collected during this scenario?

**Comment by amitchauhan18may** [comment]
[alexa.pdf](https://github.com/alexa/avs-device-sdk/files/4316973/alexa.pdf)

**Comment by caleighatamazon** [comment]
Hi @amitchauhan18may, thanks for the logs. Could you actually provide the full DEBUG9 logs, rather than grep-ing for Blue in particular?

**Comment by amitchauhan18may** [comment]
[alexa.pdf](https://github.com/alexa/avs-device-sdk/files/4323445/alexa.pdf)

Hi, Please find the logs.

1. I connected iphone11 manually.
Result: Connected(As expected)
2. I asked alexa to disconnect my phone:
Result: Disconnected(As expected)
3. Asked alexa to connect my phone
Result: Alexa replied searching, unable to find (Not Expected)

In expected result, it should connect to phone.

**Comment by caleighatamazon** [comment]
Thanks, we're taking a look.

**Comment by kjkh** [comment]
Hi @amitchauhan18may,

Are you still facing problems regarding iPhone connectivity?

**Comment by ajaythakur-dev** [comment]
Replying on behalf of @amitchauhan18may: Tested same on 1.18 issue still persists.
