### ISSUE TITLE
There are so much threads in sdk

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#164]
Hi @avs team

I see the  class `Excutor` in **Excutor.cpp**, it supply a **An internal executor that performs execution of callable objects passed to it sequentially but asynchronously.**， But everywhere use the `Excutor` by `Executor m_executor;` will create a thread, so it may be nothing in `x86` linxu system, but when in **embeded systen**， too much thread will cost too much memory. actually we just need only one thread to supply **sequentially but asynchronously call** function in **one process**.

so I suggest optimize this for **embeded systen**。

**Comment by kjkh** [comment]
Hi,
Thanks for your suggestion. We'll log the issue internally and explore ways that we can reduce the number of threads we're using.

Currently are you running into resource constraints while using our SDK?

**Comment by sundq** [comment]
No, But I think in embeded system,  The less SDK's memory requirements means low cost.

**Comment by kjkh** [comment]
Yes, definitely.
Closing the issue, please re-open if you have any further comments.
