### ISSUE TITLE
Header file "portaudio.h" missing

### ISSUE THREAD

**Issue by shashwatsinha28** [alexa/avs-device-sdk#1640]
## Briefly summarize your issue:
I am trying to build AVS device sdk on linux ubuntu 19.10. (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/linux.html). After going through all the steps, on running the make command, there is a missing header file error for the file "portaudio.h". I have also tried searching for the file on github for versions 1.17 and 1.18 but the file is not there on github too.

## What is the expected behavior?
The make command should build the AVS sdk on the Linux machine and the sample app should run.

## What behavior are you observing?
In the directory source/SampleApp/include/SampleApp, the file PortAudioMicrophoneWrapper.h has an include statement for the file portaudio.h. This header file is missing from the source code.

## Tell us about your environment:
I am buulding the AVS sdk version 1.17 on ubuntu 19.10.

### Tell us what hardware you're using:
The hardware being used is a laptop.
![Screenshot from 2020-03-04 16-38-37](https://user-images.githubusercontent.com/20424516/76139052-b8221100-6072-11ea-9aff-8c45999cb96f.png)

**Comment by mvelegon-amzn** [comment]
Hi @shashwatsinha28 in order to better assist you, could you please add here the cmake command you are using? 

Portaudio is a third party library and is a necessary dependency for the SDK. Please follow this guide https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html#set-up-your-ubuntu-environment to install it and specify the correct locations in the cmake configuration.

**Comment by shashwatsinha28** [comment]
Hi, I am using the following cmake commands to set up AVS on generic linux. cmake $HOME/my_project/source/avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include \
-DCMAKE_BUILD_TYPE=DEBUG

But the portaudio library is missing from the third party folder.

**Comment by caleighatamazon** [comment]
Hi @shashwatsinha28, if the portaudio library is missing from the third party folder, please make sure to download and install it, and then retry building the Sample App.

The instructions for downloading and installing Portaudio can be found in our quick start guide for Ubuntu. It's step 6 under https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html#set-up-your-ubuntu-environment.

Once you've followed all those steps, re-try building the SDK. Hope this helps.

**Comment by kjkh** [comment]
Hi @shashwatsinha28,

Did you get a chance to build PortAudio? Are you still facing issues?

**Comment by caleighatamazon** [comment]
I'm going to close this issue due to inactivity, but please feel free to re-open it if I've closed it in error.

**Comment by yaoyoyo** [comment]
i have the same problem on mac os.
after setting up portalAudio, build SampleApp successfully, but  "make SampleApp" got an error: 
----
avs-device-sdk/SampleApp/include/SampleApp/PortAudioMicrophoneWrapper.h:24:10: fatal error: 
      'portaudio.h' file not found

@caleighatamazon
