### ISSUE TITLE
how to identify the opus format of captured audio？(android)

### ISSUE THREAD

**Issue by a1990517123** [alexa/avs-device-sdk#1641]
can i upload the opus format of audio file to alexa for identify? (android)

**Comment by caleighatamazon** [comment]
Yes, SpeechRecognizer.Recognize event does support Opus encoding.

You can see all the specs here: https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/speechrecognizer.html#recognize

**Comment by a1990517123** [comment]
I'm structuring an HTTP/2 request for AVS.
Audio files in PCM format can be recognized already。
When I want to recognize audio files in opus format，I changed the value of the format parameter from AUDIO_L16_RATE_16000_CHANNELS_1 to OPUS.   The values of other parameters have not changed. But it doesn't work right now。Are there any other parameters that need to be modified？
