### ISSUE TITLE
A question about opus audio recognition

### ISSUE THREAD

**Issue by ChangJingPei** [alexa/avs-device-sdk#1642]
I'm structuring an HTTP/2 request for AVS.
Audio files in PCM format can be recognized already。
When I want to recognize audio files in opus format，I changed the value of the format parameter from AUDIO_L16_RATE_16000_CHANNELS_1 to OPUS.   The values of other parameters have not changed. But it doesn't work right now。Are there any other parameters that need to be modified？

_Originally posted by @a1990517123 in https://github.com/alexa/avs-device-sdk/issues/1641#issuecomment-597508820_

**Comment by caleighatamazon** [comment]
No, you shouldn't need to change any other parameters -- you're doing that correctly.

Can you confirm that the audio file you send in the Recognize event adhere to the specifications? (https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/speechrecognizer.html#recognize)

The SDK Sample App actually also has the option of supporting OPUS, if you'd like to examine how our sample app sends Recognize events. You can turn on that option at compilation: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#additional-options (see "Opus" in the table).

**Comment by a1990517123** [comment]
Thank you very much!    Audio stream in opus format on android can be recognized already。

**Comment by a1990517123** [comment]
Thank you very much!  Audio stream in opus format on android can be recognized already。

**Comment by caleighatamazon** [comment]
Great! Do you have more questions about OPUS encoding?

**Comment by ChangJingPei** [comment]
No，thank you。😊
