### ISSUE TITLE
Timers, alarms and reminders not sounding

### ISSUE THREAD

**Issue by xcraftster** [alexa/avs-device-sdk#1648]
## Briefly summarize your issue:

When I set and an alarm, a reminder or a timer on Pi with Alexa it does not sound on it.

## What is the expected behavior?

I am expecting a sound when an alarm, a reminder or a timer is triggered

## What behavior are you observing?

Alexa does not produce any announcements at all except for a glitch which I will describe below.

## Provide the steps to reproduce the issue, if applicable:

For example, I say, "Alexa, set an alarm at 2:05pm today" and it replies me back that an alarm has been successfully set. When time is up, nothing happens. Please note that Alexa is idle at this moment, it doesn't play music or anything like that.

Also, there is another glitch - when I set up a reminder in Alexa app on Android, the reminder did not work on Pi with Alexa also. I then rebooted Pi with Alexa and it announced this reminder right after booting (I set up SampleApp as a service). Then I deleted this reminder in Alexa app on Android and rebooted my Pi with Alexa again and it announced this reminder also! Then this thing disappeared after several reboots.

The date and timezone on Pi is ok. I checked it with date command. When you ask Alexa about the current time and date it also says that correctly.

### What version of the AVS Device SDK are you using?
      <1.18.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x ] Raspberry Pi 3b
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x ] Raspbian Buster Lite (Linux raspberrypi 4.19.108-v7+ #1298 SMP Fri Mar 6 18:04:35 GMT 2020 armv7l GNU/Linux)
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by xcraftster** [comment]
Ok guys, here is some addition to what I noticed today. I use Respeaker USB mic array (with 7PDM microphones) for this Alexa setup. My playback device was connected to the 3.5mm Jack outlet on the same mic array. When I run Alexa as a service I hear sound from my playback device connected to mic array. 

What I did today. I disabled Alexa as a service. Then I plugged my speaker inlet to 3.5mm Jack outlet on Pi itself, changed ,asoundrc file respectively, rebooted Pi and ran SampleApp again and set my next alarm. When time was up Alexa triggered this alarm and I heard the sound. When I ran SampleApp with 3.5mm Jack on mic array (changed .asoundrc respectively) I saw that Alexa was capturing sound but didn't play it that on my speaker for some reason.

**Comment by kjkh** [comment]
Hi @xcraftster,

Sorry for the delayed reply. Can you clarify what you mean when you say you are running Alexa as a service? It sounds like the issue here is with your hardware setup and not the SDK itself. Are you facing any other issues related to the Alerts logic in the SDK that you need help with?

**Comment by xcraftster** [comment]
No worries mate, it's ok. 

Here is the thing. I compile Alexa with: 
`sudo bash setup.sh config.json`
and then run:
`sudo bash startsample.sh`
and then ask Alexa to set an alarm, it responds to me that alarm was set and when the time is up, I can hear the alarm. It is working. Here is what I did next:
I then stop startsample.sh and set up to run Alexa as a service.
I created a file alexa.sh file:
`nano ~/alexa.sh`
and inserted the following in it:
'#!/bin/bash
  cd "/home/pi/build/SampleApp/src"
  PA_ALSA_PLUGHW=1 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" NONE
'
then I created alexa.service file: 
`sudo nano /lib/systemd/system/alexa.service`
and inserted the following in it:
`[Unit]
Description=Amazon Alexa
Wants=network-online.target
After=network-online.target
[Service]
Type=simple
ExecStart=/home/pi/alexa.sh
Restart=on-abort
User=pi
Group=pi
[Install]
WantedBy=multi-user.target`

Then I enabled alexa.service on boot:
`sudo systemctl enable alexa` and rebooted Raspberry Pi.

When my Raspberry reboots, Alexa starts working, I ask her the same thing, to set an alarm, it responds to me that alarm was set but when the time is up, I don't hear any sound of an alarm. Same for timers and reminders.
I am using Seeed's ReSpeaker 7PDM Mic Array for this set up, my Speaker is hooked up to 3.5mm Jack on Raspberry Pi itself. Also, my current /etc/asound.conf file is now the following:
`pcm.!default {
   type asym
   playback.pcm {
       type plug
       slave.pcm "hw:0,0"
   }
   capture.pcm {
       type dsnoop
       ipc_key 5432
       slave {
           pcm "hw:1,0"
           buffer_size 96000
           channels 1
           rate 16000
           format S16_LE
       }
   }
}
`
For the rest of the stuff, Alexa works just fine. I tuned it to work with IFTTT for home automation and it works flawless.

**Comment by atmatthewat** [comment]
You are running the sample app manually as `root` by prepending `sudo`.
Your service is configured with `User=pi ` and `Group=pi`

This is just a guess, but it may be that the database file configured in AlexaClientSDKConfig.json in the alertsCapabilityAgent:databaseFilePath is not writable by the `pi` user/group.

If debugging is enabled, you would see this error logged if that is the case:
`SQLiteStatement:SQLiteStatement::stepFailed::Executing the select did not generate a row or complete.:result=8
`

**Comment by xcraftster** [comment]
Thanks mate! Yes, changing User/Group to root in /lib/systemd/system/alexa.service fixed the issue but I wanned to run Alexa as User/Group 'pi', so I just changed ownership of all files in ~/db folder including folder itself:

'''
sudo chown -R pi:pi ~/db
'''
changed User/Group to 'pi' in /lib/systemd/system/alexa.service respectively and restarted Alexa service:

'''
sudo systemctl restart alexa.service
'''

and it worked also!

Thanks for your help bud!

> You are running the sample app manually as `root` by prepending `sudo`.
> Your service is configured with `User=pi ` and `Group=pi`
> 
> This is just a guess, but it may be that the database file configured in AlexaClientSDKConfig.json in the alertsCapabilityAgent:databaseFilePath is not writable by the `pi` user/group.
> 
> If debugging is enabled, you would see this error logged if that is the case:
> `SQLiteStatement:SQLiteStatement::stepFailed::Executing the select did not generate a row or complete.:result=8 `
