### ISSUE TITLE
Not all of the error types are supported for ErrorResponse for ModeController

### ISSUE THREAD

**Issue by laishiekai** [alexa/avs-device-sdk#1651]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am playing with the sample app and I found that ModeController only support a few error types, for example, VALUE_OUT_OF_RANGE, INTERNAL_ERROR and INVALID_VALUE. If I send back the ErrorResponse with other types like NOT_SUPPORTED_IN_CURRENT_MODE, Alexa will just response: "Sorry, discoball is not responding". It sounds like the ErrorResponse is not even been received. There is no way to tell if an error type is supported at the cloud side.

I have not tested the other controllers, currently only seeing the issue for ModeController.

## What is the expected behavior?

There should be documentation about which type of errors are supported for each controller.

## What behavior are you observing?

Currently devs can only try and error by themselves.

## Provide the steps to reproduce the issue, if applicable:

Replace the error type in 
std::pair<AlexaResponseType, std::string> ModeControllerHandler::setMode()
And force the code to always return with error.
Compile and run the sample app.

### What version of the AVS Device SDK are you using?
      <x.y.z>
I am using 1.17.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Windows 10 Laptop.

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Windows 10, version 1909.

**Comment by womw** [comment]
Hi @laishiekai thanks for posting,

Can you post DEBUG9 logs of this interaction?

**Comment by laishiekai** [comment]
DEBUG9 will be very verbose. But here is the json payload for the ErrorResponse (I removed correlationToken) :

2020-03-31 18:42:21.106 [ 33] 0 EventBuilder:buildJsonEventString:---------------- event={"event"\:{"endpoint"\:{"endpointId"\:"amzn1.application-oa2-client.e9d98ae6aaf3428da71637584b7101a1\:\:A4PC_POC\:\:123456\:\:Discoball"}\,"header"\:{"namespace"\:"Alexa"\,"name"\:"ErrorResponse"\,"messageId"\:"3addc361-2655-4e68-95e9-7c2b3cd406cb"\,"correlationToken"\:"..."\,"eventCorrelationToken"\:"3addc361-2655-4e68-95e9-7c2b3cd406cb"\,"payloadVersion"\:"3"\,"instance"\:"Discoball.Mode"}\,"payload"\:{"type"\:"NOT_SUPPORTED_IN_CURRENT_MODE"\,"message"\:"gg"}}}

And like I said, Alexa will reply: "Sorry, Discoball is not responding". 

To reproduce, go to 
`std::pair<AlexaResponseType, std::string> ModeControllerHandler::setMode()`
And change the returnign line to be:
`return std::make_pair(AlexaResponseType::NOT_SUPPORTED_IN_CURRENT_MODE, "gg");`
And ask Alexa to change Discoball to blue.

**Comment by mvelegon-amzn** [comment]
Hi @laishiekai thanks for sending the logs. This does not appear to be an issue with the SDK. Could you direct this question in the Alexa Voice Service forums?

Also, as per documentaiton here: https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-errorresponse.html#error-types It looks like the NOT_SUPPORTED_IN_CURRENT_MODE code needs additional information in payload, are you sending that?


NOT_SUPPORTED_IN_CURRENT_MODE | The endpoint can't be set to the specified value because of its current mode of operation. When you send this error response, include a field in the payload named currentDeviceMode that indicates why the device cannot be set to the new value. Valid values are COLOR, ASLEEP, NOT_PROVISIONED, OTHER.
-- | --

**Comment by laishiekai** [comment]
Thanks, I will try the payload!
