### ISSUE TITLE
Unable to find UIManager.cpp

### ISSUE THREAD

**Issue by aashwinGaur** [alexa/avs-device-sdk#1652]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am unable to find UIManager.cpp van you please tell me where it is located , i am using a raspberry pi and the folder structure  has changed , KIndly help me out (Can't find it in the **SampleApp** folder )
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ *] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ * ] Raspbian Duster
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hello, thanks for posting @aashwinGaur 

You can fine the UIManager.cpp file in the SampleApp folder.
https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/UIManager.cpp

If you still can not find the file consider recloning the repo.

**Comment by kjkh** [comment]
Hi @aashwinGaur,

Are you having any additional issues locating UIManager.cpp?

**Comment by aashwinGaur** [comment]
Found it ..Thanks
