### ISSUE TITLE
Longtime playback for IheartRadio failed after 5 hours

### ISSUE THREAD

**Issue by tinypancake** [alexa/avs-device-sdk#1654]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Long playback for iHeartRadio stops after 5 hours or less than 5 hours.

## What is the expected behavior?
Music is still playing after 8+ hours

## What behavior are you observing?
Music stops after about 5 hours (some cases less than 3 hours)

## Provide the steps to reproduce the issue, if applicable:
Start a  iHeartRadio live radio station and leave it playing

## Tell us about your environment:
We are using the SDK integrated with our Network and BT features.

### What version of the AVS Device SDK are you using?
      SDK 1.17.0

### Tell us what hardware you're using:
- [ ] Other - tell us more: 

### Tell us about your OS (Type & version):
- [ ] Linux

The problem seems to occur when some events of AudioPlayer need to be sent and the SDK is renewing the HTTP2 connection, around line 818874/819035. In that case the event StreamMetadataExtracted and PlaybackFinished are not sent and therefore response directive is not received. 
The error about libcurl are that: 
one is LibcurlHTTP2Connection:streamFinished:streamId=AVSEvent-4223,result=Stream error in the HTTP/2 framing layer,CURLcode=92, and the other is LibcurlHTTP2Connection:streamFinished:streamId=AVSDownChannel-3577,result=Failure when receiving data from the peer,CURLcode=56 

OSS version:  libcurl/7.53.1 OpenSSL/1.1.1a zlib/1.2.11 nghttp2/1.26.0

And I have tried the patch refered in #1595 , but it seems not work.

[IheartRadio longtime play issue.zip](https://github.com/alexa/avs-device-sdk/files/4378665/IheartRadio.longtime.play.issue.zip)

**Comment by tinypancake** [comment]
In addition , I have tried "Long playback for Amazon Music", I start a  Prime playlist which contains 278 songs lasting over 16 hours and leave it playing , and Music is still playing after 10+ hours.

**Comment by womw** [comment]
Hi thanks for posting @tinypancake, 

This is a known issue and we are looking into this. We'll update this ticket when this issue has been resolved.

**Comment by tinypancake** [comment]
Thank you to let me know this @womw , hope I can get the solution from your side and keep yourself healthy.

**Comment by scotthea-amazon** [comment]
Hello @tinypancake,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
