### ISSUE TITLE
SystemClockDelay.cpp error: no matching function for call to 'max'

### ISSUE THREAD

**Issue by jbfitb** [alexa/avs-device-sdk#1657]
###  Briefly summarize your issue:
 - Updated the SDK to v1.18.0
 - Tried to compile for Android

Got the following error:

```
/Users/user/dev/AVSDeviceSDK/Captions/Implementation/src/SystemClockDelay.cpp:26:47: error: no matching function for call to 'max'
    auto duration = std::chrono::milliseconds(std::max(zero, milliseconds.count()));
                                              ^~~~~~~~
/Users/user/Library/Android/ndk/ndk-bundle/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/algorithm:2529:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long' vs. 'long long')
max(const _Tp& __a, const _Tp& __b)
^
/Users/user/Library/Android/ndk/ndk-bundle/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/algorithm:2539:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Users/user/Library/Android/ndk/ndk-bundle/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/algorithm:2521:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Users/user/Library/Android/ndk/ndk-bundle/android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/algorithm:2547:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
1 error generated
```

### What is the expected behavior?

It appears that there needs a cast in order to get the template `max` function to see both arguments as the same type

#### Current Code

```
void SystemClockDelay::delay(std::chrono::milliseconds milliseconds) {
    int64_t zero = 0;
    auto duration = std::chrono::milliseconds(std::max(zero, milliseconds.count()));
    std::this_thread::sleep_for(duration);
}
```

#### Possible soluion

```
void SystemClockDelay::delay(std::chrono::milliseconds milliseconds) {
    int64_t zero = 0;
    auto duration = std::chrono::milliseconds(std::max(zero, static_cast<int64_t>(milliseconds.count())));
    std::this_thread::sleep_for(duration);
}
```

[According to the chrono docs, ](https://en.cppreference.com/w/cpp/chrono/duration) milliseconds should have 57 bits (or more), so `int64_t` should be an upcast.

### What version of the AVS Device SDK are you using?
      v1.18.0

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Cross-compiling for Android

**Comment by kjkh** [comment]
Hi @jbfitb,

Thanks for bringing this to light. Since this code is effectively doing a negative check, it would be preferable to explicitly do that check by comparing milliseconds.count() against zero, and assigning values as appropriate. Then, the cast can be avoided altogether.This will be tracked and fixed in an upcoming release.

**Comment by scotthea-amazon** [comment]
@jbfitb,

Hi @ghe0Rghe,

We have a task in our backlog to fix this, so I am closing out the issue.  We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Thank you again for bringing this to our attention!

Best regards,
-SWH
