### ISSUE TITLE
If Iphone or any media sync property enabled phone connected to device via. BT, volume is not controlling

### ISSUE THREAD

**Issue by mohitbansal19** [alexa/avs-device-sdk#1660]
## Briefly summarize your issue:
Volume is not controlling when Iphone or any volume sync enabled phone is connected via Bluetooth.

## What is the expected behavior?
Volume should control. We are raising this ticket because the old ticket has been closed. We are giving the reference for old ticket and it is as below:- 
https://github.com/alexa/avs-device-sdk/issues/1472

## What behavior are you observing?
Volume is not controlling via. phone

## Provide the steps to reproduce the issue, if applicable:
1. Connect phone via. bluetooth. 
2. Play some music.
3. Increase or decrease volume from phone.

## Tell us about your environment:
AVS SDK Version 1.18.0 Cross Compiled to run on below Hardware.
PulseAudio
Bluetooth

### Tell us what hardware you're using:
Other: Hardware: Samsung Artik 305 Secure Board
armv7hf

### Tell us about your OS (Type & version):
Linux, Ubuntu 16.04
Linux artik 4.4.71-UNRELEASED #1 SMP PREEMPT Tue Aug 20 18:39:35 IST 2019 armv7l armv7l armv7l GNU/Linux

**Comment by kjkh** [comment]
Hi @mohitbansal19,

Since there is context in the old ticket, I will be moving the conversation back to there and closing this ticket.
