### ISSUE TITLE
Bluetooth Connect/Disconnect sounds no longer play

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1661]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Previously when connecting to a Bluetooth A2DP device the AVS server would send back a message to play which would sound like "*bloop* Phoney has connected". Now the message only plays "Phoney has connected". Same for disconnect (except it played *blee-bloop*). This makes it so devices using the SDK no longer comply with the functional requirements [9.2](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/functional-requirements.html)

## What is the expected behavior?
Server should send down the *bleeps* and *bloops* to play again, or the SDK should build the noises into the systemSoundMediaPlayer and execute those noises in the UIManager (or somewhere else in the SampleApp or generic Bluetooth implementation in the SDK)

## What behavior are you observing?
previously *bleeps* and *bloops* played while connecting/disconnecting to a Bluetooth device. Now they do not. I do see a "ducking" message I do not remember seeing before in the logs.

## Provide the steps to reproduce the issue, if applicable:
Create the Sample App with Bluetooth enabled, connect a Bluetooth device. No *bleep* sounds happen (TTS saying the phone name is the only thing that plays). Previously (a few months ago) it did.

## Tell us about your environment:
I tested this bug on 18.0.0 and just to check I was not losing my mind i recompiled and tried it on 16.0 as well (the version I was using when the sounds were working). This bug also exists on 16.0 now.

### What version of the AVS Device SDK are you using?
      <18.0.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @brett-lynnes, thanks for letting us know about this issue.  We will open an internal ticket to investigate this further.  Thanks!

**Comment by scotthea-amazon** [comment]
Hi @brett-lynnes,

We have a task in our backlog to fix this, so I am closing out the issue. We will announce a fix in our [release notes](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/release-notes.html) when the fix is released.

Best regards,
-SWH
