### ISSUE TITLE
Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2335:5: error: delete called on non-final       'alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]     delete __ptr;

### ISSUE THREAD

**Issue by ssalexa** [alexa/avs-device-sdk#1663]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Following the mac installation instruction, but fail on make -j4 to build the SDK. I want to build 1.17 version

## What behavior are you observing?
Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2335:5: error: delete called on non-final
      'alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    delete __ptr;

## Provide the steps to reproduce the issue, if applicable:
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Network/InternetConnectionMonitor.cpp.o
In file included from /Users/Documents/GitHub/mysdk/source/avs-device-sdk/AVSCommon/Utils/src/Network/InternetConnectionMonitor.cpp:16:
In file included from /Users/Documents/GitHub/mysdk/source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Network/InternetConnectionMonitor.h:20:
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2335:5: error: delete called on non-final
      'alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    delete __ptr;
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2648:7: note: in instantiation of member function
      'std::__1::default_delete<alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor>::operator()' requested here
      __ptr_.second()(__tmp);
      ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/memory:2602:19: note: in instantiation of member function
      'std::__1::unique_ptr<alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor,
      std::__1::default_delete<alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor> >::reset' requested here
  ~unique_ptr() { reset(); }
                  ^
/Users/Documents/GitHub/mysdk/source/avs-device-sdk/AVSCommon/Utils/src/Network/InternetConnectionMonitor.cpp:52:16: note: in instantiation of member function
      'std::__1::unique_ptr<alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor,
      std::__1::default_delete<alexaClientSDK::avsCommon::utils::network::InternetConnectionMonitor> >::~unique_ptr' requested here
        return nullptr;
               ^
1 error generated.
make[2]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Network/InternetConnectionMonitor.cpp.o] Error 1
make[1]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2

### What version of the AVS Device SDK are you using?
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### Tell us what hardware you're using:
- [X ] Desktop / Laptop - Mac Mojave
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @ssalexa, I wasn't able to get the error you saw despite using the same clang version.  Could you double check, in your workspace, that if you have a virtual destructor for `InternetConnectionMonitorInterface` similar to [here](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/InternetConnectionMonitorInterface.h#L45).

**Comment by ssalexa** [comment]
I guess it's my environment issue. Let me close this ticket.
