### ISSUE TITLE
Gstreamer error when running simple app in device "Thinking" state

### ISSUE THREAD

**Issue by kcieniawski** [alexa/avs-device-sdk#1665]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Alexa Sample App is is able to get voice from microphone and received response from cloud however there is no output from microphone. Alexa is running with KITTAI key word detector. Word "Alexa" triggers "Listening" state. Then state "Thinking" is triggered. After that error from gstreamer is received and device switch to error state.

## What is the expected behavior?

Output from speaker should appear.

## What behavior are you observing?

I am starting sample application. Application starts correctly. I am asking Alexa simple question e.g. "What time is it?". Then application start thinking about question. After that application doesn't switch to "speking" state but instead it switch to "idle" state. Error added bellow happens.

**
(SampleApp:3954): GLib-GObject-WARNING **: 18:02:55.696: invalid (NULL) pointer instance

(SampleApp:3954): GLib-GObject-CRITICAL **: 18:02:55.696: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(SampleApp:3954): GLib-GObject-WARNING **: 18:02:55.697: invalid (NULL) pointer instance

(SampleApp:3954): GLib-GObject-CRITICAL **: 18:02:55.697: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(SampleApp:3954): GLib-GObject-WARNING **: 18:02:55.698: invalid (NULL) pointer instance

(SampleApp:3954): GLib-GObject-CRITICAL **: 18:02:55.698: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
**

I am attaching logs from sample application both for application and gstream. For application there were  'DEBUG9" log and for gstreamer there were GST_DEBUG=5
I have tested 'gst-launch-1.0 -m audiotestsrc ! autoaudiosink' command and it is working correctly. I also tested pulseaudio configuration by running 'arecord test.wav' and 'aplay test.wav'. 'arecord 'command managed to get sound and 'aplay' command play it correctly.

This issue seems to be similar to https://github.com/alexa/avs-device-sdk/issues/390 however there is no information how to fix it.

[gstream-log.txt](https://github.com/alexa/avs-device-sdk/files/4444762/gstream-log.txt)
[alexa_log.txt](https://github.com/alexa/avs-device-sdk/files/4444765/alexa_log.txt)

## Provide the steps to reproduce the issue, if applicable:

Use tutorial to setup Alexa machine: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/linux.html
Installing all requirements and building sample application.
Then on first application start issue appears.

### What version of the AVS Device SDK are you using?
      1.18.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
aarch64 base Linux device based on system on module Core3399J-JD4, Rockchip 3399 processor.

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
uname -a
Linux firefly 4.4.167-g17982fadb9b5-dirty #9 SMP Mon Mar 16 13:01:41 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by kclchan** [comment]
Hi @kcieniawski, from the logs attached, I see this error message:
```
2020-04-07 09:58:56.007 [ 1a] E BaseStreamSource:initFailed:reason=createDecoderElementFailed
```
This indicates that some Gstreamer plug-ins are not installed.  Could you check if have installed the dependencies as described in [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#mediaplayerinterface.)

Also, you may want to check if the environment variable GST_PLUGIN_PATH is set correctly.  You could refer to #1260 for more information.

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity. Please re-open if I've closed this in error.
