### ISSUE TITLE
Bluetooth not getting paired with another device when it is already connected with one.

### ISSUE THREAD

**Issue by prateek-web** [alexa/avs-device-sdk#1668]
## Briefly summarize your issue:
Bluetooth is not getting paired with another device when it is already connected with one. And another device, in multiple re-tries, gets paired but affects already connected device which it shouldn't.

## What is the expected behavior?
Without Alexa, with bt-agent (Bluez-tools binary) running, bluetooth on the device gets paired and connected (Calls only) with other devices meanwhile it is connected (Calls and Audio) with one device. And Other connected devices should not affect already connected device (Media playback not to be affected).

## What behavior are you observing?
With Alexa, with or without bt-agent (Bluez-tools binary) running, bluetooth on the device does not get paired with other devices meanwhile it is connected (Calls and Audio) with one device. And when playing audio with one device, in multiple re-tries, another device gets paired but does not connect, and it even affects the media playback on already connected device which it shouldn't.

## Provide the steps to reproduce the issue, if applicable:
1. Connect any phone (In our case was ->Iphone 7 having ios 13.3.1) with device running Alexa 1.14 and having bluez5. 
2. Put it on media playback. 
3. Try pairing any other device (In our case was -> Iphone 6s having ios 11.4 + Samsung J3 Pro android). I won't get paired.
4. Try multiple times. I may get paired, but then it will affect music playback on previously connected device.

## Tell us about your environment:
Ubuntu 16.4 (OS)
Alexa 1.14
PulseAudio: 12.2
Bluez-5.50 + Bluez-tools (Bluez-tools optional)

### Tell us what hardware you're using:
Samsung Artik-305

### Tell us about your OS (Type & version):
Ubuntu 16.4 (Linux)

**Comment by kclchan** [comment]
Hi @prateek-web, could you please attach the DEBUG9 log?  Thanks!

**Comment by kclchan** [comment]
Hi @prateek-web, upon further investigation, this is the expected behavior.  The SDK only support one active A2Dp device at a time.
