### ISSUE TITLE
AVS SDK 1.17 - Reminder not getting triggered in my setup  Help Needed

### ISSUE THREAD

**Issue by sakthisg** [alexa/avs-device-sdk#1671]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I had set a reminder using my amazon log in.
The device receives the reminder Set request. But the reminder never triggered off..
Am i missing any configuration in my Device?

## What is the expected behavior?
Reminder should be triggered.

## What behavior are you observing?
Reminder not triggered.

### What version of the AVS Device SDK are you using?
      1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Crosscompiled for arm platform

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

[Logs.txt](https://github.com/alexa/avs-device-sdk/files/4469732/Logs.txt)

**Comment by scotthea-amazon** [comment]
Hello @sakthisg,

Looking at the log you provided, the only evidence of a reminders is in a context that is being gathered to be sent with an event.  This includes the following scheduledTime values:
- 2020-04-14T00\:30\:09+0000
- 2020-04-14T00\:48\:00+0000
- 2020-04-14T00\:50\:00+0000

However, the last time stamp in the log is for 2020-04-13 18:47:21.416
So, it appears that the reminders were all set for the following day.

Was the log gathered before the test was complete?

If you send more logs, please use DEBUG9 level so that the logs include the maximum information.

Thank you,
-SWH

**Comment by sakthisg** [comment]
[TVLog 17 52 25 14 Apr 20.log](https://github.com/alexa/avs-device-sdk/files/4475215/TVLog.17.52.25.14.Apr.20.log)
Alert set at 05:52 PM IST to trigger a reminder at 5:58 PM IST ..Only set Alert Prints i see at 5:52: 
No reminder fired at 5:58 PM. Logs Captured till 06:00 PM. Do you see any issues?

**Comment by scotthea-amazon** [comment]
Ho @sakthisg,

Thank you for the updated and detailed logs.  Unfortunately, I see a very similar pattern.  The line that shows when the reminder was scheduled for:

`[2020-04-14 17:52:46.394] 2020-04-14 12:22:45.844 [ 22] 1 AlertsCapabilityAgent:executeNotifyObservers:alertToken=amzn1.as-ct.v1.Domain\:Application\:Reminders#DNID#8cd6e424-a0e8-4f44-9327-b231b0c5d312,alertType=REMINDER,state=SCHEDULED_FOR_LATER,reason=2020-04-15T00\:58\:00+0000`

...indicates that the reminder was scheduled for the next day (2020-04-15), while the test only runs through 2020-04-14 18:00.  Actually, looking again at that log line I included above, the time of the reminder is also way off - it appears to be for 00:58, not 17:58.  

It sounds like there is a problem somewhere that is causing your reminder to get scheduled for the next day.  That could be on the device or in the cloud.  I wonder, if right after you create your reminder you ask?:

    "Alexa, What are my reminders?"

Does Alexa report the expected date and time?  What time does she report when you ask?:

    "Alexa, What time is it?"

What does she report when you ask:

    "Alexa, What is my time zone?"

I am closing this issue pending your response. When you have more information for us to follow up with, please re-open this issue and post your new information and any relevant comments.

Best regards,
-SWH

**Comment by sakthisg** [comment]
Yes it is time zone problem.Thanks for the information!
