### ISSUE TITLE
Diagnostics cannot load custom Alert Capability in DefaultClient

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1675]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
on line 1283 of DefaultClient.cpp the DiagnosticsInterface is instantiated and adds the alert observer with addAlertObserver(...) ... however the interface it is observing is not part of the SDK and is located in a capability agent for Alerts. We (and probably many others) wrote our own capability agent for Alerts, which has a different interface.

The only way to continue loading Diagnostics this way would be to incorporate all of Diagnostics into the build and change the derived interface from AlertsObserverInterface to the one in our build.

## What is the expected behavior?
Diagnostics should not be dependent on interfaces internal to capability agents

## What behavior are you observing?
Build will not function on our system without me re-coding Diagnostics or removing line 1283 in DefaultClient.cpp

## Provide the steps to reproduce the issue, if applicable:

n/a

### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @brett-lynnes,

I think you are correct, the default client should depend on a separate AlertsInterface which your custom Alerts Capability Agent can implement.

I have created an internal ticket to track this feature/improvement request and get it scheduled for a future release.

Thank you for your contribution to the Alexa Device SDK!

Sam
