### ISSUE TITLE
Issue Running config script during set up on Rasberry Pi - Errno 2 - No such file or directory

### ISSUE THREAD

**Issue by gemma2301** [alexa/avs-device-sdk#1676]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I get as far through the guidance notes to running the configuration file installing on Raspberry pi and then hit an error - "Errno 2 - No such file or directory" the config file is most definitely there correctly. I am struggling to work out what is causing the issue. Here is the guidance notes I have been following.
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#run-the-configuration-script
Here is the whole message:
Traceback (most recent call last):
File "<stdin>", line 3, in <module>
IOError: [Errno 2] No such file or directory: '/home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json'

## What is the expected behavior?

I am assuming the config script should run without issue.

## What behavior are you observing?

Error message - no such file or directory see details above.

## Provide the steps to reproduce the issue, if applicable:

I follow the steps outlined in the documentation link above.

### What version of the AVS Device SDK are you using?
      current version

### Tell us what hardware you're using:

- [ 4 Model B] Raspberry Pi
-

### Tell us about your OS (Type & version):

- [v10 ] Raspbian Buster

**Comment by samcoult** [comment]
Hi @gemma2301 ,

Its possible the directory"/home/pi/sdk-folder/sdk-build/Integration/" does not exist, please create that directory and re-run the command. Also please provide the exact command you are using, as that will help us debug.

Thanks!

**Comment by gemma2301** [comment]
@samcoult thanks for your help. i checked the directory and indeed it was missing! now fixed :-)
