### ISSUE TITLE
Building MRM 

### ISSUE THREAD

**Issue by bimbim2401** [alexa/avs-device-sdk#1678]
## Briefly summarize your issue:

Hello

- I want to add the MRM capability to my raspberry project but i understand that i have to patch it. 
I try to contact an amazon business representative and fill out the the contact form but without success. Nobody try to contact me

- I want also to add the playing music features from Amazon music but it tell me that this functionnality doesn't work on this device. And i can't validate the music validation on developper website because the amazon music item is not present

I have a amazon prime account and and unlimited for amazon music

Can you please help me ?

### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [x ] Raspberry Pi

### Tell us about your OS (Type & version):
- [x] Raspbian buster

**Comment by samcoult** [comment]
Hi @bimbim2401 ,

We cannot help you acquire an SDK adapter on this support forum. I encourage you to reach out again and wait for a response from your Amazon Business Representative.

Thanks!
