### ISSUE TITLE
Alexa calling is not supported

### ISSUE THREAD

**Issue by syedfaisal5** [alexa/avs-device-sdk#1679]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When i say "Call Faisal", alexa is saying "calling with alexa is not supported on this device"

## What is the expected behavior?
Alexa  should make call if they found contact number or should say that contact number is not found

## What behavior are you observing?
When is say "Alexa, call faisal", the i receives an audio which says "calling with alexa is not supported on this device, u can use alexa app for calling"

## Provide the steps to reproduce the issue, if applicable:
On Linux: 
1. Compile the C++ SampleApp from Auto SDK 2.1
2. After successful authentication, pressed 'T' for Tap to talk.
3. Alexa, call faisal             ---> This to invoke call
On android:
1. after successful authentication, on saying " call faisal" , getting same response here also.

## Tell us about your environment:
Compiled and tested the code on Linux 16.04 and also tested on  Qualcomm Android board. Getting same response on both the platform.
### What version of the AVS Device SDK are you using?
      Alexa Auto SDK 2.1

### Tell us what hardware you're using:
- [ ] Laptop and Qualcomm android board.

### Tell us about your OS (Type & version):
- [ ] Linux and Android

https://github.com/syedfaisal5/Programming/blob/master/DeviceDOesntSupportCalling.txt

**Comment by syedfaisal5** [comment]
Please provide permission so that Alexa calling feature is getting enabled. So,that i can test the feature from SampleApp on Linux platform or android board.

**Comment by samcoult** [comment]
An SDK adapter is required to enable calling features in the SDK. Please reach out to your Amazon Business Contact to acquire the necessary components.
