### ISSUE TITLE
AmazonLite WWE not responding

### ISSUE THREAD

**Issue by Renegade85** [alexa/avs-device-sdk#1680]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Saying "Alexa" doesn't trigger the AmazonLite WWE integrated into AVS.

## What is the expected behavior?

AVS should trigger on "Alexa" and listen to query

## What behavior are you observing?

Keyword not detected

## Provide the steps to reproduce the issue, if applicable:

The AmazonLite is incorporated into AVS as described in the adapter README applying a patch through python script. Adapter used is vresion 2.1.0. cmake executed as instructed.
Only confusing part is, that library contains so & so.2.3 libraries. Tried building library with both, but still no response.

### What version of the AVS Device SDK are you using?
AVS 1.19.0
Adapter 2.1.0
WWE 2.3.2

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
i.MX8M

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:
Embedded linux from NXP for i.MX8M

Build log from Debug:
[avs.log](https://github.com/alexa/avs-device-sdk/files/4517037/avs.log)

**Comment by samcoult** [comment]
Instead of GitHub, a direct channel between your company and Amazon is more suitable for the contents of your question. I am closing this issue and we are looking forward to continue working with you when you reach us through the other channel.

**Comment by Renegade85** [comment]
Hi samcoult,

I've contacted Ram already. Looking forward his response. Thank you and have a nice day.
