### ISSUE TITLE
Calling feature test through C++ Alexa SampleApp

### ISSUE THREAD

**Issue by syedfaisal5** [alexa/avs-device-sdk#1681]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Using Alexa SampleApp i tried testing calling number. I received audio that "calling with alexa is not supported on this device". I am using Linux ubuntu 16.04 version to compile the code. Do i need to change something in my code. During compilation of alexa auto sdk, avs sdk is downloaded and compiled. Separately i checked in avs sdk, i found that in PCC.make, Phone call feature is OFF. Do i need to make some changes in auto sdk or in cmake file of auto sdk, enabling the PCC feature for AVS sdk ?

## What is the expected behavior?
 It should say if number is not found that " number is not found".This kind of reply i should receive.

## What behavior are you observing?
calling with alexa is not supported on this device.

## Provide the steps to reproduce the issue, if applicable:

1. run the c++ sampleapp.
2. press T, and say "Alexa call faisal"

### What version of the AVS Device SDK are you using?
      <x.y.z>1.17

### Tell us what hardware you're using:
- [ ] Desktop/Laptop Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux Ubuntu 16.04
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @syedfaisal5 
Calling support in the SDK requires an sdk adapter package. Please reach out to your Amazon business contact in order to get more information.
Thanks!

**Comment by syedfaisal5** [comment]
> Hi @syedfaisal5
> Calling support in the SDK requires an sdk adapter package. Please reach out to your Amazon business contact in order to get more information.
> Thanks!
Is this for SampleApp default phonecall feature testing also ? I am trying to check default phone call feature with given contact.json file, but still it is saying : " calling with alexa is not supported on this device". Does something need to enable or make changes in auto sdk.
