### ISSUE TITLE
Update the Ubuntu quick start for libportaudio.so

### ISSUE THREAD

**Issue by jonsmirl** [alexa/avs-device-sdk#1686]
Hi @mohitbansal19 

In the 1.18 build we now require linking against the shared portaudio library, eg. the **libportaudio.so** file.

Try a clean build with `-DPORTAUDIO_LIB_PATH=$LIB_PATH/libportaudio.so`

Thanks

_Originally posted by @samcoult in https://github.com/alexa/avs-device-sdk/issues/1631#issuecomment-592096831_

The Ubuntu quickstart needs to be updated for this.
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/ubuntu.html

**Comment by caleighatamazon** [comment]
Hi @jonsmirl, thanks for pointing this out. I'll create an internal ticket to fix this bug in the documentation and make sure it is resolved.

**Comment by caleighatamazon** [comment]
Hi @jonsmirl, I believe the issue is now resolved. Thanks for pointing it out!
