### ISSUE TITLE
Can't enable wake word with the sample app

### ISSUE THREAD

**Issue by Eddyah** [alexa/avs-device-sdk#1687]
## Briefly summarize your issue:
I've installed Alexa Sample on my laptop (Ubuntu Linux 16.04 LTS) following the instructions here: [https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html#run-and-authorize-the-sample-app](url) . The Sample App can be triggered when I press T+Enter but I would like to trigger it with the wake word "Alexa". 

So I ran the following command :

`cd $HOME/pi/sdk-folder/sdk-build
cmake $HOME/pi/sdk-folder/sdk-source/avs-device-sdk -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.so -DPORTAUDIO_INCLUDE_DIR=$HOME/pi/sdk-folder/third-party/portaudio/include -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$HOME/pi/third-party/snowboy/lib/ubuntu64/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/pi/third-party/snowboy/include -DCMAKE_BUILD_TYPE=DEBUG`

But I got some error messages you can see in the log file. 
[log_Wakeword.txt](https://github.com/alexa/avs-device-sdk/files/4549645/log_Wakeword.txt)

## What is the expected behavior?
The Sample App should be built with the wakeword enabled.

## What behavior are you observing?
The cmake command doesn't work

## Provide the steps to reproduce the issue, if applicable:
Since I already have the Sample App built without the wake word enabled, I did the following steps:

`cd $HOME/pi/sdk-folder/sdk-build
cmake $HOME/pi/sdk-folder/sdk-source/avs-device-sdk -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.so -DPORTAUDIO_INCLUDE_DIR=$HOME/pi/sdk-folder/third-party/portaudio/include -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$HOME/pi/third-party/snowboy/lib/ubuntu64/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/pi/third-party/snowboy/include -DCMAKE_BUILD_TYPE=DEBUG`

## Tell us about your environment:
Laptop Ubuntu Linux 16.04 LTS
### What version of the AVS Device SDK are you using?
      <1.18.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @Eddyah, according to your logs, this problem is unrelated to wakeword.

Instead, the problem is that your build directory is inside the source code directory. 

Please follow the instructions given in the logs here:

```
###############################################################################
#                                                                             #
# ERROR:                                                                      #
# AlexaClientSDK must not be built in the AlexaClientSDK source directory.    #
#                                                                             #
# You must run cmake in a separate build directory completely outside the     #
# the source directory.                                                       #
#                                                                             #
# Source Directory:                                                           #
#     $HOME/pi/sdk-folder/sdk-source/avs-device-sdk                    #
# Build Directory:                                                            #
#     $HOME/pi/sdk-folder/sdk-source/avs-device-sdk                    #
#                                                                             #
# NOTE:                                                                       #
# Since you have tried to create an in-source build already, CMake may have   #
# created some files and directories in the source tree. To find these files, #
# run:                                                                        #
#     $ git status                                                            #
#                                                                             #
# To remove these files, simply use 'rm' on the appropriate files and         #
# directories.                                                                #
#                                                                             #
###############################################################################
```
