### ISSUE TITLE
Can't build the sample app

### ISSUE THREAD

**Issue by Eddyah** [alexa/avs-device-sdk#1688]
## Briefly summarize your issue:
I'm trying to build the Sample App with the wake word enable with Kitt-AI but I got some issues. 
I could run the following instruction:
`cd $HOME/pi2/sdk-folder/sdk-build
cmake $HOME/pi2/sdk-folder/sdk-source/avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/pi2/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.so \
-DPORTAUDIO_INCLUDE_DIR=$HOME/pi2/sdk-folder/third-party/portaudio/include \
-DKITTAI_KEY_WORD_DETECTOR=ON \
-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$HOME/pi2/sdk-folder/third-party/snowboy/lib/ubuntu64/libsnowboy-detect.a \
-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/pi2/sdk-folder/third-party/snowboy/include \
-DCMAKE_BUILD_TYPE=DEBUG`

But when I run ` make SampleApp -j2` , I got some errors.

## What is the expected behavior?
The Sample App should be built

## What behavior are you observing?

When I run ` make SampleApp -j2`, I get this:

/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 31%] Built target AVSCommon
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 33%] Built target SQLiteStorage
[ 33%] Built target RegistrationManager
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 35%] Built target ADSL
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 37%] Built target InterruptModel
[ 42%] Built target ACL
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 42%] Built target Captions
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 42%] Built target AVSGatewayManager
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 42%] Built target Alexa
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 44%] Built target EqualizerImplementations
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 44%] Built target ContextManager
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 44%] Built target KWD
[ 46%] Built target PlaylistParser
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 48%] Built target SpeechEncoder
[ 48%] Built target SystemSoundPlayer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 51%] Built target AudioResources
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 51%] Built target SpeakerManager
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 51%] Built target ApiGateway
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 53%] Built target AudioPlayer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 55%] Built target Bluetooth
[ 57%] Built target Equalizer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 57%] Built target InteractionModel
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 60%] Built target Notifications
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 60%] Built target PlaybackController
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 60%] Built target SpeechSynthesizer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 60%] Built target TemplateRuntime
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 62%] Built target CBLAuthDelegate
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 64%] Built target SynchronizeStateSender
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 64%] Built target CertifiedSender
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 68%] Built target MediaPlayer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 71%] Built target AFML
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 73%] Built target Endpoints
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 75%] Linking CXX shared library libKITTAI.so
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 77%] Built target ExternalMediaPlayer
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 80%] Built target DeviceSettings
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 80%] Built target CapabilitiesDelegate
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
Scanning dependencies of target AIP
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
KWD/KittAi/src/CMakeFiles/KITTAI.dir/build.make:124: recipe for target 'KWD/KittAi/src/libKITTAI.so' failed
make[3]: *** [KWD/KittAi/src/libKITTAI.so] Error 1
CMakeFiles/Makefile2:8096: recipe for target 'KWD/KittAi/src/CMakeFiles/KITTAI.dir/all' failed
make[2]: *** [KWD/KittAi/src/CMakeFiles/KITTAI.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 80%] Building CXX object CapabilityAgents/AIP/src/CMakeFiles/AIP.dir/AudioInputProcessor.cpp.o
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 80%] Linking CXX shared library libAIP.so
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 80%] Built target AIP
CMakeFiles/Makefile2:12409: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:3111: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

## Provide the steps to reproduce the issue, if applicable:

`$HOME/pi2/sdk-folder/third-party
git clone https://github.com/kitt-ai/snowboy
cd $HOME/pi2/sdk-folder/sdk-build
cmake $HOME/pi2/sdk-folder/sdk-source/avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/pi2/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.so \
-DPORTAUDIO_INCLUDE_DIR=$HOME/pi2/sdk-folder/third-party/portaudio/include \
-DKITTAI_KEY_WORD_DETECTOR=ON \
-DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$HOME/pi2/sdk-folder/third-party/snowboy/lib/ubuntu64/libsnowboy-detect.a \
-DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/pi2/sdk-folder/third-party/snowboy/include \
-DCMAKE_BUILD_TYPE=DEBUG
`

## Tell us about your environment:
Laptop Ubuntu Linux 16.04 LTS
### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi, can you confirm that you have successfully installed all the required dependencies of the SDK? Did you see any error messages when installing those dependencies?

Instructions for Ubuntu here: https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

**Comment by drift21** [comment]
I reinstalled everything and now it seems to work, maybe my dependencies were not installed correctly. Thank you for your advice.
Regards.

**Comment by Eddyah** [comment]
Hi, yes because I've build an another Sample App without the wake word and it's working.

**Comment by caleighatamazon** [comment]
The cmake output looks okay. Can you try re-installing the dependencies, and please share the output from doing so:

```
 sudo apt-get install -y \
 git gcc cmake openssl clang-format libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev \
 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
 gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools \
 pulseaudio doxygen libsqlite3-dev repo libasound2-dev
```

In your logs, it looks like a missing dependency: `/usr/bin/ld: cannot find -lblas` So let's verify that it is installed. Can you also provide the output for the following?

```
ldconfig -p | grep blas
```

You can try installing it like so:

```
sudo apt-get install libblas-dev
```

**Comment by Eddyah** [comment]
Hey, 

The output from re-installing the dependencies is:

sudo apt-get install -y \

 git gcc cmake openssl clang-format libgstreamer1.0-0 libgstreamer-plugins-base1.0-dev \
  gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
  gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools \
  pulseaudio doxygen libsqlite3-dev repo libasound2-dev
[sudo] password for mollyl: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libasound2-dev is already the newest version (1.1.0-0ubuntu1).
repo is already the newest version (1.12.32-2).
cmake is already the newest version (3.5.1-1ubuntu3).
doxygen is already the newest version (1.8.11-1ubuntu0.1).
git is already the newest version (1:2.7.4-0ubuntu1.9).
gstreamer1.0-doc is already the newest version (1.8.3-1~ubuntu0.1).
gstreamer1.0-plugins-base is already the newest version (1.8.3-1ubuntu0.3).
gstreamer1.0-plugins-good is already the newest version (1.8.3-1ubuntu0.4).
gstreamer1.0-tools is already the newest version (1.8.3-1~ubuntu0.1).
libgstreamer-plugins-base1.0-dev is already the newest version (1.8.3-1ubuntu0.3).
libgstreamer-plugins-base1.0-dev set to manually installed.
libgstreamer1.0-0 is already the newest version (1.8.3-1~ubuntu0.1).
libsqlite3-dev is already the newest version (3.11.0-1ubuntu1.4).
openssl is already the newest version (1.0.2g-1ubuntu4.15).
pulseaudio is already the newest version (1:8.0-0ubuntu3.11).
clang-format is already the newest version (1:3.8-33ubuntu3.1).
gstreamer1.0-libav is already the newest version (1.8.3-1ubuntu0.2).
gstreamer1.0-plugins-bad is already the newest version (1.8.3-1ubuntu0.2).
gstreamer1.0-plugins-ugly is already the newest version (1.8.3-1ubuntu0.1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-91 linux-headers-4.15.0-91-generic
  linux-image-4.15.0-91-generic linux-modules-4.15.0-91-generic
  linux-modules-extra-4.15.0-91-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.



The output for `ldconfig -p | grep blas` is `libblas.so.3 (libc6,x86-64) => /usr/lib/libblas.so.3`
I've installed it with the command you gave me. 

I've run ` make SampleApp -j2` and I think it's working now. Thank you!!

**Comment by caleighatamazon** [comment]
Great! I'll close this issue as resolved, then.

**Comment by carlos211** [comment]
hello how could you help me with this problem that I am presenting when trying to install the main dependencies of the SDK.

sudo apt-get install -y \ gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools \
> pulseaudio doxygen libsqlite3-dev repo libasound2-dev
Reading package list ... Done
Creating dependency tree
Reading status information ... Done
E: The package could not be located
E: Failed to locate repo package.
