### ISSUE TITLE
Bluetooth connectivity of device, notified to SampleApp android version

### ISSUE THREAD

**Issue by syedfaisal5** [alexa/avs-device-sdk#1689]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 I have connected my phone with android board, on which SampleApp is installed. Phone connection is successfully. SampleApp is not aware of the phone connection with the bluetooth.

## What is the expected behavior?
 SampleApp should detect the phone connectivity through bluetooth.

## What behavior are you observing?
SampleApp is not aware of the phone connection with the bluetooth.

## Provide the steps to reproduce the issue, if applicable:
 1. Connect the phone with the android board through bluetooth , connection is successful.
2. try call scenario ( contact is uploaded successfully ).
3. It is saying " Please connect phone through bluetooth".

### What version of the AVS Device SDK are you using?
      <x.y.z>1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop yes
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: Qualcomm Android board

**Comment by caleighatamazon** [comment]
Hi there, can you please build the SDK with DEBUG9 turned on and provide us the full logs (from starting to quitting the app) where you reproduce the problem?

**Comment by syedfaisal5** [comment]
Hi Minshall,

Please guide to enable debug9 from alexa suto sdk?

Thanks

**Comment by caleighatamazon** [comment]
Hi @syedfaisal5, the Auto SDK is a separate project from this one. If you are using the Auto SDK, we request that you reach out to the PTM and/or SA assigned to you. You can get help with the Alexa Auto SDK by accessing https://developer.amazon.com/alexa-voice-service/alexa-auto-sdk. 

The current Auto SDK sample app does not support Bluetooth connection and that might be enhanced in future.

I'm going to close this issue.
