### ISSUE TITLE
How to make authorization request to https://www.amazon.com/ap/oa?

### ISSUE THREAD

**Issue by singaravelann** [alexa/avs-device-sdk#169]
Based on my understanding, it is required to make authorization request to  https://www.amazon.com/ap/oa with "Authorization code" to get access and refresh token for the first time. 
This requires sign-in to amazon.com
Can you help with the process of sign in with nghttp2 APIs?

Thanks in advance.

**Comment by kjkh** [comment]
Hi, 

The following files can be helpful as a guideline:

- <AVS_SDK_SRC>/tools/AuthServer/AuthServer.py
This file contains a Python implementation on retrieving the refresh token.
- <AVS_SDK_SRC>/AuthDelegate/src/AuthDelegate.cpp
- <AVS_SDK_SRC>/AuthDelegate/src/HttpPost.cpp
These files demonstrate how to use the curl APIs.

Additional resources can also be found here: http://login.amazon.com/. If you have any further questions, feel free to re-open.
