### ISSUE TITLE
Can't run and can't authorize sample App - Kitt-AI

### ISSUE THREAD

**Issue by Eddyah** [alexa/avs-device-sdk#1691]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I entered these commands to run the Sample App:

$cd $HOME/pi2/sdk-folder/sdk-build/
./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json $HOME/pi2/sdk-folder/third-party/snowboy/resources debug9

And the Sample App can't run and can't be authorized. 

## What is the expected behavior?
The Sample App should run

## What behavior are you observing?

[logKittAI.txt](https://github.com/alexa/avs-device-sdk/files/4561310/logKittAI.txt)

When I try to run the Sample App I got "Aborted(core dumped" as you can see in the log file. 
Also, even if I authorize the device at https:/amazon.com/us/code with the given code, it will ask me again when I try to re-run. 

## Provide the steps to reproduce the issue, if applicable:
`$cd $HOME/pi2/sdk-folder/sdk-build
./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json $HOME/pi2/sdk-folder/third-party/snowboy/resources debug9`

## Tell us about your environment:
Laptop Ubuntu Linux 16.04 LTS
### What version of the AVS Device SDK are you using?
      <1.19.1>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @Eddyah, the logs state the following:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (Input():snowboy-io.cc:315) Fail to open input file "/home/mollyl/pi2/sdk-folder/third-party/snowboy/resources/alexa.umdl"

[stack trace: ]
```

That file is required for running the Sample App with KittAI. Can you verify that the file exists at that location?

**Comment by Eddyah** [comment]
Hi @caleighatamazon , 

The `alexa.umdl` is at the location `/home/mollyl/pi2/sdk-folder/third-party/snowboy/resources/alexa/alexa-avs-sample-app/alexa.umdl`. I provided the path `/home/mollyl/pi2/sdk-folder/third-party/snowboy/resource` when I launched the Sample App because when I didn't, it said that it couldn't find the `common.res` file

**Comment by caleighatamazon** [comment]
@Eddyah, please place both files in the same directory. Then you can pass the filepath to that directory when you launch the app.

Something like this:

```
cp /home/mollyl/pi2/sdk-folder/third-party/snowboy/resources/alexa/alexa-avs-sample-app/alexa.umdl /home/mollyl/pi2/sdk-folder/third-party/snowboy/resources/alexa.umdl
cd $HOME/pi2/sdk-folder/sdk-build/
./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json $HOME/pi2/sdk-folder/third-party/snowboy/resources debug9
```

**Comment by Eddyah** [comment]
Hi @caleighatamazon , it worked. Thank you and sorry about that!

**Comment by caleighatamazon** [comment]
Great! Closing this issue.
