### ISSUE TITLE
Alexa cannot talk while other services use the soundcard audio output

### ISSUE THREAD

**Issue by minion190422** [alexa/avs-device-sdk#1693]
[aosundrc.txt](https://github.com/alexa/avs-device-sdk/files/4567746/aosundrc.txt)
[asound.txt](https://github.com/alexa/avs-device-sdk/files/4567747/asound.txt)

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I use a Raspberry Pi 3 model B+ and on top of it the Soundcard HiFiBerry DAC+ Pro.  Besides Alexa the RasPi also runs raspotify (https://dtcooper.github.io/raspotify/). The soundcard is connected to our old Bose loudspeaker. 
The sound works great. the Spotify client works, Alexa works too, but...

As soon as I play music through the Spotify client and then ask Alexa for something, the following happens:
Alexa can be awakened by means of Wake-Word and understands what is being said. In the terminal the messages "Listening" and "Thinking" come, but after that not "Speaking".

In DEBUG9 mode, after "Thinking" it says: "Default device is busy." So as soon as a service uses the soundcard, I can't use Alexa anymore. 
The soundcard is set as default device in ALSA and the audio output works as said. 

Latest Raspbian Buster and SDK 1.19.1 in use.

## What is the expected behavior?

I use a Raspberry Pi 4 (4GB RAM) on which I have also installed raspotify (https://dtcooper.github.io/raspotify/) and Alexa. But here I realize the audio output only via the 3.55mm audio output directly to the speaker. 
While the service of the Spotify client is active and plays music, I can ask Alexa something and she can answer over the music. 
I want to have the same over the other RasPi with the soundcard. I want to be able to stop the music playback by Alexa for example or ask her something and listen to her answer.

Same here: SDK=1.19.1 and latest Raspbian Buster

## What behavior are you observing?

As soon as I play music through the Spotify client and then ask Alexa for something, the following happens:
Alexa can be awakened by means of Wake-Word and understands what is being said. In the terminal, the messages "Listening" and "Thinking" come, but after that not "Speaking".

In DEBUG9 mode, after "Thinking" it says: "Default device is busy." So as soon as a service uses the soundcard, I can't use Alexa anymore. 
The soundcard is set as the default device in ALSA and the audio output works as said. 
## Provide the steps to reproduce the issue, if applicable:

1. Install Alexa and raspotify
2. Use the same Hardware and make Soundcard as default ALSA device
3. Start playback of Spotify music via Spotify client on the RasPi 
4. Try to ask Alexa something - there will be no answer although she understands everything
### What version of the AVS Device SDK are you using?
      <x.y.z>
Latest Raspian Buster and SDK=1.19.1
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Raspbian Buster

**Comment by mvelegon-amzn** [comment]
Hi @minion190422 Thanks for reaching out. Could you please send full debug9 logs for both scenarios - with Raspberry Pi 4 where its functioning as expected as well as the Raspberry Pi where you observe this issue?

We do not do anything platform specific as far as sound card is concerned so I am suspecting its an underlying issue outside the scope of the SDK. If you send us the logs we can take a look and provide possible next steps. 

Thanks

**Comment by minion190422** [comment]
[RasPi3B - not_working_Logs.txt](https://github.com/alexa/avs-device-sdk/files/4581938/RasPi3B.-.not_working_Logs.txt)
[RasPi4 - working_Logs.txt](https://github.com/alexa/avs-device-sdk/files/4581939/RasPi4.-.working_Logs.txt)

Hi, @mvelegon-amzn for looking at my issue.
I also think you're right and it's not a bug directly related to the SDK, but since I haven't found any documentation about this bug anywhere, I posted it here.
Attached are the logs for both Pi models. I started Alexa, using the Alexa skill "Connect Control" I asked for all Spotify Connect devices. Then (after "expecting") I selected a device for music playback and the music was played over the connected speaker. Then I asked Alexa about the weather - once it works and Alexa talks while the music is playing in the background (RasPi 4), once not (RasPi 3B+).

Addition to the soundcard: It is connected to the Raspberry Pi via all GPIO pins. For the setup, I used the following documentation from HiFiBerry: https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/ for my DAC+ Pro. 
I had Alexa on the RasPi 3 before, at that time without a soundcard and it worked via the audio jack, as it does now with the RasPi 4. So it's certainly up to the configuration of the hardware. 

I hope that you can help me. Thanks a lot.

**Comment by kclchan** [comment]
Hi @minion190422, this is outside the scope of the SDK.  But I could suggest adding a dmix plugin as suggested in the troubleshoot guide [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/troubleshooting.html#linux).  Search for "Can't play more than one sound simultaneously".
