### ISSUE TITLE
failure to build AVS SDK Sample App on Android 

### ISSUE THREAD

**Issue by FennyR** [alexa/avs-device-sdk#1694]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When I am trying to build AVS SDK project on android application, I am facing the below issue.

## What is the expected behavior?
The build scripts should run and download all project directories and folders along with StartSample.sh file

## What behavior are you observing?
Make sure device intall target exists and has write permission
mkdir: '/System': Read-only file system
## Provide the steps to reproduce the issue, if applicable:

run this command :
bash setup.sh config.json -a androidConfig.txt -s 998987

## Tell us about your environment:
Configuration: Macbook (Catalina OS)
Android Emulator (Rooted): API Level: 27
 System image: X64
Build path: /System/Volumes/Data/AVS-SDK-App (AVS-SDK-App is the folder name)
### What version of the AVS Device SDK are you using?
  27

### Tell us what hardware you're using:
- [ ] Desktop / Laptop : Macbook
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS : Catalina
[AVS SDK Issue.pdf](https://github.com/alexa/avs-device-sdk/files/4568701/AVS.SDK.Issue.pdf)

- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @FennyR , according to the information you've provided, it looks like the path you are providing to install the SDK is a read-only directory. If it's a read-only directory, you will not be permitted to write the SDK files to that location:

```
Make sure device install target exists and has write permission
mkdir: '/System': Read-only file system
```

Can you make sure that the path you provide for installing the SDK has write permissions?

**Comment by kjkh** [comment]
Closing ticket due to inactivity. If there are further questions, please create a new ticket and refer to this.
