### ISSUE TITLE
Alarm during Call is connected

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1696]
## Briefly summarize your issue:
I set Alarm for one min **ALERT_STATE: STARTED**  . Then I make  a call and my call state changes to **CallState::CALL_CONNECTED**
During this Call, Alarm played untill I cancel it by saying "Alexa, Turn off Alarm" or **ALERT_STATE: STOPPED**

Can you tell me the channel when we talk during call(Dialog, Alerts  or Content)?
[Alert_IncomingCall_Issue.txt](https://github.com/alexa/avs-device-sdk/files/4574508/Alert_IncomingCall_Issue.txt)

## What is the expected behavior?
alarm should be snoozed till my call disconnect or **CallState::DISCONNECTED**.

## What behavior are you observing?
Alarm played during call is connected.

## Provide the steps to reproduce the issue, if applicable:
1) set Alarm for one min
2) Make a call to device
3) Observe the tone of Alarm during call
4) After sometime, cancel/Turn off Alarm.
5) Disconnect Call.

## Tell us about your environment:
avs-device-sdk-1.18
avs_client_sdk_comms_adapter.1.6.tar.gz
AlexaCommsLib v3.1.118

### Tell us what hardware you're using:
On artik-305

### Tell us about your OS (Type & version):
[Ubuntu-16.04 ] Linux: 4.4.71

**Comment by caleighatamazon** [comment]
Hi @Alexa-AUH, can you please open an internal TT with our team or reach out to your SA? We do not support the comms adapter on our public Github forum. I'm going to close this issue.
