### ISSUE TITLE
ProgressReportDelayElapsed is failing with tag INCORRECT_OFFSET_TOO_HIGH and DELAYED

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1697]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When I am trying to play music and validate it using MVT tool(music validation tool) then the "**ProgressReportDelayElapsed**" has been failing with tags INCORRECT_OFFSET_TOO_HIGH and DELAYED for IHeart station and Amazon music.
**For Amazon Music:**
For Tag [DELAYED] - Expected offset is 6000 and outcome is 6665.
For Tag [INCORRECT_OFFSET_TOO_HIGH] - Expected offset is 2000 and outcome is 5386.
**For IHeart Music:**
For Tag [INCORRECT_OFFSET_TOO_HIGH] - Expected offset is 16500 and outcome is 18854.

Due to this certification is failing.
We have tested the scenario over Pure AVS-SDK V1.19 and we are able to generate ALL PASS report. Please check the Pass report 
[All_Pass_1.17.pdf](https://github.com/alexa/avs-device-sdk/files/4597854/All_Pass_1.17.pdf)

I have attached the DEBUG9 logs and MVT reports. Please do check and help us.
**DEBUG9 logs Amazon music -**
[20200430_Amazon_music_log_v2.txt](https://github.com/alexa/avs-device-sdk/files/4582222/20200430_Amazon_music_log_v2.txt)
**DEBUG9 logs IHeart Radio -**
[20200430_iHR_Log_v2.txt](https://github.com/alexa/avs-device-sdk/files/4582234/20200430_iHR_Log_v2.txt)
**Reports of IHeart Radio -**
[SN0391_SW0317_iHeartRadio_custom_log__2020-04-30-02-35-17_Event_Logs.pdf](https://github.com/alexa/avs-device-sdk/files/4582245/SN0391_SW0317_iHeartRadio_custom_log__2020-04-30-02-35-17_Event_Logs.pdf)
**Reports of Amazon music -**
[SN0391_SW0317_Amazon_music_log__2020-04-30-04-52-23_Event_Logs.pdf](https://github.com/alexa/avs-device-sdk/files/4582261/SN0391_SW0317_Amazon_music_log__2020-04-30-04-52-23_Event_Logs.pdf)

Amazon Cloud team has give some pointers for this failures like extra 2-3 second delay  is RF signal dropout, or some RF signal integrity issue or anything else.
Could you please help us for the terms RF signal dropout, or some RF signal integrity issue.

## What is the expected behavior?
Offset of progressreportdelayelapsed should be in acceptance range as mentioned in url https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/audioplayer.html#progressreportdelayelapsed

## What behavior are you observing?
Offset progressreportdelayelapsed is higher than expected.

## Provide the steps to reproduce the issue, if applicable:
Use the checklist provided by MVT to test
Generate report through MVT report generation tool

### What version of the AVS Device SDK are you using?
Used AVS-SDK V-1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @dipalisb Thanks for reaching out.

We are currently looking into this issue. I have a few questions for you:

1) Have there been any changes made to the 1.17 version of the SDK 
2) Are you able to upgrade and test on the 1.19 version of the SDK

**Comment by dipalisb** [comment]
Hi @mvelegon-amzn ,

Thanks for your response.

I have added our response to your query please check -

1.Have there been any changes made to the 1.17 version of the SDK
 --> We have tested with the pure AVS-SDK, without our changes and it is failing.
2.Are you able to upgrade and test on the 1.19 version of the SDK
-->Yes, we have tested with V1.19 without any change. Only one all PASS report has been generated and sometimes it is failing on V1.19 as well.

**Comment by dipalisb** [comment]
Hi @mvelegon-amzn ,

We have made the change in AVS-SDK code, to reduce the wait to send the ProgressReportDelayElapsed event to AVS.

There are two waits used for progress delay, one before the song starts i.e progress is zero and second is when the progress reaches the delay offset.

We tried to manipulate the timeout for second wait but it didn't help.

So when we disabled the second wait as shown in below snippet, not only the issue was fixed but significant improvement was observed in delay values i.e 1299 instead of 5200
File name -CapabilityAgents/AudioPlayer/src/ProgressTimer.cpp
![image](https://user-images.githubusercontent.com/52921278/82238425-e4042180-9954-11ea-8f30-bb87b7e3d6c3.png)

We are able to generate PASS report with the change shown in above image.

Please let us know your feedback on our change of SDK code.

Thanks.

**Comment by scotthea-amazon** [comment]
Hi @dipalisb,

Thank you for sharing your ideas!

We cannot recommend removing that wait altogether.  While looking at a log you provided for another issue we saw a flood of high frequency logs that result from removing this wait.  You probably do not want this thread running flat out just to check the progress of playback.

Instead, you might want to try something like cutting "timeout" in half and skipping the wait altogether when the result is below some threshold (e.g. 10 milliseconds).

I am going to close this issue.  If you are still experiencing problems, please open a new issue and refer to this one for context if appropriate.

Best Regards,
-SWH
