### ISSUE TITLE
How to make DBLUETOOTH_BLUEZ = ON in avs sdk when using Android sample app

### ISSUE THREAD

**Issue by syedfaisal5** [alexa/avs-device-sdk#1698]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 I am facing directive handler failure issue while pairing phone through bluetooth . i found that in the avs sdk bluetooth.cmake file, DBLUETOOTH_BLUEZ is OFF. PLease let me know how i can make change in this cmake file because i am just compiling android sampleapp code and using it. Do i need to contact amazon business partner, will they do ?

## What is the expected behavior?
 find and pair the phone

## What behavior are you observing?
 exception occured

## Provide the steps to reproduce the issue, if applicable:
 Enable bluetooth and say "Alexa pair my phone"

### What version of the AVS Device SDK are you using?
      <x.y.z>
1.17.0
### Tell us what hardware you're using:
- [ ] Desktop / Laptop Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: Android

**Comment by mvelegon-amzn** [comment]
Hi @syedfaisal5 we do not support blueZ on Android platform currently. We only support BlueZ for Ubuntu and Raspberry Pi. I will be closing this ticket, please let us know if you have any other questions.
