### ISSUE TITLE
Class diagram to understand the design

### ISSUE THREAD

**Issue by Jigar27** [alexa/avs-device-sdk#170]
Hello,
Can you share the class diagram or any alternate which can help to understand the flow and design??

**Comment by kjkh** [comment]
Hi,
You can generate documentation through running `make doc`. Amongst the available documentation is a class hierarchy diagram. Feel free to re-open if this does not suffice.

**Comment by kjkh** [comment]
Additionally, these can be accessed at: https://alexa.github.io/avs-device-sdk/
