### ISSUE TITLE
Library "libandroidicu.so" not found error when tried to run AVS-SDK SampleApp on Android 10 baseline

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1700]
**Detailed explanation of the documentation problem:**
>> When tried to run AVS-SDK SampleApp on Android Q build. There is an error:: library "libandroidicu.so" not found.
If I push the same SampleApp and run it on Android P baseline, this error is not there and working as expected.

**Steps to reproduce this issue/error::**
a. Download AVS SDK v1.19 using the URL - https://github.com/alexa/avs-device-sdk , build the sdk & push libraries to Android 10/ Android 9 device and run the SampleApp (for more steps to build & run android SDK is in the same sdk URL)
**Expected Result: ** SampleApp shoud run and able to interact with Alexa
**Current result::**
On Android 10:: Below is the exact error:  CANNOT LINK EXECUTABLE "/product/avs/bin/SampleApp": library "libandroidicu.so" not found
On Android 9 ::  Working as expected

**For reference, I have attached a screenshot for this error.** -
![AndroidQ_AVSError](https://user-images.githubusercontent.com/31942830/81193877-947b3880-8fd9-11ea-9859-620c8b14eb6f.png)

 Please check the below URL, to the relevant document on developer.android.com** 
(https://source.android.com/devices/architecture/modular-system/runtime

Also, I saw a similar library libandroidicu.so not found issue in the below URL::
https://stackoverflow.com/questions/59376458/androidruntime-java-lang-unsatisfiedlinkerror-dlopen-failed-library-libandro

Please take this issue on high priority and help to provide suggestion to fix this soon.

Thanks in advance!

**Comment by mvelegon-amzn** [comment]
Hi @DeepikaBalaga This issue does not appear to be an issue with the SDK but rather an issue with an Android dependency. I found this link which has a same issue and it also has a resolution. Please try if this works: https://github.com/google/oboe/issues/421.

I am closing this issue now, please feel free to reopen incase you have follow up questions.

**Comment by DeepikaBalaga** [comment]
Hi @mvelegon-amzn ,
The point here is with the same SampleApp & so files in the lib/ I'm able to run Alexa on Android 9 baseline, whereas with the Android 10 it's showing this error. Please help to run this at your end and let me know whether you are also facing or not.
Because I have tried multiple times with multiple versions of Android NDK and the issue is still reproducible.
Please try to understand the urgency and let me know the results by running SampleApp once on Android 10.
Thanks in advance.
