### ISSUE TITLE
How do I auto start Alexa on my pi

### ISSUE THREAD

**Issue by ansu1997** [alexa/avs-device-sdk#1704]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I don’t know how to auto start my Alexa on pi

## What is the expected behavior?
The code I run in terminal is “ cd /home/pi/sdk-folder/sdk-build && ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json ../third-party/alexa-rpi/models “
 And it works ... but how do I auto start Alexa sdk... im new to this so please help me ...

### What version of the AVS Device SDK are you using?
      1.18.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [. ] Raspberry Pi
- [ ] Other - tell us more: 

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: raspbian buster

**Comment by ereich1217** [comment]
This isn't really an Alexa issue, but a Linux issue.  There are multiple ways you can do this.

Here is a site that explains five ways to run programs at startup:
https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

**Comment by ansu1997** [comment]
> This isn't really an Alexa issue, but a Linux issue. There are multiple ways you can do this.
> 
> Here is a site that explains five ways to run programs at startup:
> https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

I did check the link you posted ... but all these suggests for python programs ... how do I do it for Alexa ..?

**Comment by ereich1217** [comment]
Here is a site that describes the issue specifically for Alexa:
https://pimylifeup.com/raspberry-pi-alexa/

**Comment by samcoult** [comment]
Hi @ansu1997 ,

As @ereich1217 suggested, this problem is outside the scope of SDK support. There are many ways to "auto start" or "start on boot" a program in linux or raspberry-pi environment, and I encourage you to look for platform specific resources (like those linked above) in order to answer your question.
