### ISSUE TITLE
Alexa is currently idle! raspberry PI4 B

### ISSUE THREAD

**Issue by dbartholomew1974** [alexa/avs-device-sdk#1706]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Alexa is currently idle! 
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by samcoult** [comment]
Hi @dbartholomew1974 

We are unable to assist you with your problem unless you fill out more information about the problem you are experiencing. Please fill a new issue with the template fields fully filled out.
