### ISSUE TITLE
Annoying reply from Alexa

### ISSUE THREAD

**Issue by xcraftster** [alexa/avs-device-sdk#1709]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ Raspbian Buster ] Other - tell us more:

Guys, I use Alexa on Raspberry Pi for home automation and I really love it, however, I think it is really annoying to hear "i don't see any smart home devices do you have a smart device that I should connect to?" every time Alexa does not recognize your command.

**Comment by samcoult** [comment]
Hi @xcraftster ,

We are happy to hear that you are enjoying using Alexa!

The content of your request is outside the scope of SDK Support. I encourage you to provide feedback to the Alexa Voice Service via there developer forum https://forums.developer.amazon.com/spaces/38/Alexa+Voice+Service.html

I will now close this issue, feel free to open a new issue if you require assistance with the AVS SDK.

**Comment by xcraftster** [comment]
Ok, got it! Thank you guys!
