### ISSUE TITLE
Pi quick start suggestions

### ISSUE THREAD

**Issue by BrennanGit** [alexa/avs-device-sdk#171]
In building the sample app on the pi, we found a few usability issues in authentication that could do with mentioning on the wiki.
- deviceTypeId is equivalent to productId from the Amazon Developer Website
- deviceSerialNumber cannot be left empty
A solution to this could be more informative error messages on authentication failure or maybe a sandbox mode for testing that doesn't require it.
- It would also be helpful to provide simple instructions on how to access the authentication link from a separate computer in the case that Raspbian lite is installed. 
- Finally, a slightly nicer download link for the sounds required would be helpful, these lines could be added to the wiki: 
`wget https://images-na.ssl-images-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-voice-service/docs/audio/states/med_system_alerts_melodic_02._TTH_.mp3 -O tmr.wav`
`wget https://images-na.ssl-images-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-voice-service/docs/audio/states/med_system_alerts_melodic_02_short._TTH_.wav -O tmr_sht.wav`
`wget https://images-na.ssl-images-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-voice-service/docs/audio/states/med_system_alerts_melodic_01._TTH_.mp3 -O alrm.wav`
`wget https://images-na.ssl-images-amazon.com/images/G/01/mobile-apps/dex/alexa/alexa-voice-service/docs/audio/states/med_system_alerts_melodic_01_short._TTH_.wav -O alrm_sht.wav
`

**Comment by kjkh** [comment]
Hi, thanks for the suggestions. We will review them and update the document as applicable.
