### ISSUE TITLE
How to build on buildroot

### ISSUE THREAD

**Issue by yangsongx** [alexa/avs-device-sdk#1711]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
By default, the build failed on buildroot

## What is the expected behavior?
It should pass the build

## What behavior are you observing?
I knew the reason why it failed, because by default, cmake behavior is like this:

```
$ cd avs-1.18.0/
$ mkdir build/ && cd build/
$ cmake ../
```

Unfortunately , AVS didn't follow above default behavior, it required below action instead:

```
Suppose avs-1.18.0 is in the same level as below build dir
$ mkdir build/ && cd build/
$ cmake ../avs-1.18.0
```

The problem is, HOW Can I put the build dir as the same level as the AVS code? I suffered this too much!!!

And I strongly suggest adding such instruction in the document, as buildroot is widely used for Linux, and of course it would be greate if we can get Yocto build instruction as well.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [X ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @yangsongx,

The SDK does not currently support in source builds. Looking through the Buildroot user manual (https://buildroot.org/downloads/manual/manual.pdf), there appears to be a variable, `SUPPORTS_IN_SOURCE_BUILD` , that can be defined for a package. Please set this to `NO` in your .mk file and let us know if this resolves the issue.

I will create a ticket for your request for Yocto and Buildroot support.

**Comment by yangsongx** [comment]
Thanks for your help.
