### ISSUE TITLE
Calling make fails after cross-compiling latest version for iOS

### ISSUE THREAD

**Issue by Mechan0** [alexa/avs-device-sdk#1714]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After following the [iOS cross compile guide](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ios.html) to a tee, compiling openSSL etc. and successfully calling CMake with the appropriate and correct library/includes directory, calling `make` results in fatal error where 'curl/curl.h' is not found.
`
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o
/Users/jameswilliamson/Documents/avs-device-sdk-build/avs-device-sdk/AVSCommon/AVS/src/AlexaClientSDKInit.cpp:16:10: fatal error: 'curl/curl.h' file not found`

## What is the expected behavior?

The includes should correctly locate the header files for curl specified by the -DCURL_INCLUDE_DIR argument, which is pointing to the correct archive includes folder as specified by the cross compile guide

## What behavior are you observing?

Calling `make` fails due to not being able to locate the `curl/curl.h` header

## Provide the steps to reproduce the issue, if applicable:

Follow the cross compile guide, call `make` in the directory that `cmake` was called in.

### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Compiling for iOS using 2019 Macbook Pro 

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hi, it appears that the installation directions for libcurl is out of date for that guide. Can you try downloading curl according to this dependencies page?
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/dependencies.html#required-dependencies

**Comment by Mechan0** [comment]
@womw Update on this. After doing some debugging using VERBOSE=1 when calling `make` and getting the full compile command for the file at issue, it seems like cmake is not expanding the relative filepath (../) and the compiler doesn't expand this either, even though this is done correctly for google test where the argument is expanded to the full path for the compiler. Fixed this by giving the path in full for both the curl library and include folder, only then was the c++ compiler able to locate the includes/library. I believe the guide should be updated to reflect this or the cmake changed to expand the relative path specified in the cross compile guide.

**Comment by chaserr** [comment]
like this: 
`-DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
-DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \`

replace the iOS platform's parameter of curl in cmake with the macOS configuration of curl 
it can compile through

The full cmake parameter：
`cmake $HOME/cross-compile/avs-device-sdk \
-DIOS_DEPLOYMENT_TARGET=10.0 -Wno-dev \
-DCMAKE_OSX_ARCHITECTURES=arm64 \
-DCMAKE_TOOLCHAIN_FILE=$HOME/cross-compile/ios-cmake/ios.toolchain.cmake \
-DCMAKE_BUILD_TYPE=DEBUG \
-DACSDK_EMIT_SENSITIVE_LOGS=ON \
-DIOS_PLATFORM=OS \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
-DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \
-DGTEST_LIBRARY=$HOME/cross-compile/googletest_build/lib/libgmock.a \
-DGTEST_MAIN_LIBRARY=$HOME/cross-compile/googletest_build/lib/libgmock_main.a \
-DGTEST_INCLUDE_DIR=$HOME/cross-compile/googletest/googletest/include/ \
-DPKG_CONFIG_EXECUTABLE=/usr/local/bin/pkg-config`

**Comment by iogbole** [comment]
I had a similar error, executing `sudo apt-get install libcurl4-openssl-dev` and restarting the installation resolved the issue.

**Comment by mvelegon-amzn** [comment]
@iogbole thanks for providing the step to resolve this.

@chaserr could you please try this and let us know if you are still seeing this issue?

**Comment by jorge-simon** [comment]
> sudo apt-get install libcurl4-openssl-dev

worked!
