### ISSUE TITLE
AVS SDK 1.17: Logout App crashes.

### ISSUE THREAD

**Issue by sakthisg** [alexa/avs-device-sdk#1715]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Create a Linux application with AVS SDK 1.17 When i call logout, I see the application crashes.

## What is the expected behavior?
Should not crash.

## What behavior are you observing?
Segmentation fault.

## Provide the steps to reproduce the issue, if applicable:
Call Logout API sequence as implemented in sampleApp

### What version of the AVS Device SDK are you using?
      1.17.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Linux Arm Cross compiled

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Linux
[LogOut_Crash.txt](https://github.com/alexa/avs-device-sdk/files/4671639/LogOut_Crash.txt)

**Comment by kjkh** [comment]
Hi @sakthisg,

From the logs, it is not evident what is causing the segfault. Is this consistently reproducible? Would you be able to attach the core dump as well?

Can you also try and see if this is reproducible in 1.19?

**Comment by sakthisg** [comment]
i have not tried in 1.19. core information for 1.17 also not complete.
