### ISSUE TITLE
Failed to initialize SDK! Failed to initialize SampleApplication! Failed to create SampleApplication!

### ISSUE THREAD

**Issue by 9s2j6** [alexa/avs-device-sdk#1716]
## Briefly summarize your issue:
I have followed [this](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html) tutorial, but when I go to [run](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#run-and-authorize-the-sample-app) the sample app, I get the following error message.

## What is the expected behavior?
The SampleApp runs and shows this:
```
##################################
 #       NOT YET AUTHORIZED       #
 ##################################
 ################################################################################################
 #       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
 ################################################################################################
```

## What behavior are you observing?
```
2020-05-24 01:03:17.312 [ 1] I sdk Version: 1.19.1
configFile ./Integration/AlexaClientSDKConfig.json 
2020-05-24 01:03:17.328 [ 1] C SampleApplication: Failed to initialize SDK!
2020-05-24 01:03:17.328 [ 1] C SampleApplication: Failed to initialize SampleApplication 
Failed to create Sample Application!
```

## Provide the steps to reproduce the issue, if applicable:
Followed this [tutorial](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html) exactly

### What version of the AVS Device SDK are you using?
      1.19.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Raspbian Buster
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @9s2j6,

In order for the SampleApp to be usable, you must first authenticate and register the SDK to an account. Please go to the link specified in the logs (https://amazon.com/us/code) and enter the given code. If you have further questions, please re-open the ticket and we can assist you further.

**Comment by 9s2j6** [comment]
Hi @kjkh,
The log where the authentication process is shown is an example of the expected behavior. Under that log are errors I am getting before I am even given the option to authenticate.

**Comment by mvelegon-amzn** [comment]
Hi @9s2j6 Can you run the SampleApp with DEBUG9 logs and post the logs here?

**Comment by 9s2j6** [comment]
Hi @mvelegon-amzn,
Here are the complete logs:
Running `PA_ALSA_PLUGHW=1./SampleApp/src/SampleApp./Integration/AlexaClientSDKConfig.json DEBUG9` in `~/sdk-folder/sdk-build` gives me this:

```
2020-06-04 17:39:55.458 [  1] I sdkVersion: 1.19.1
configFile ./Integration/AlexaClientSDKConfig.json
2020-06-04 17:39:55.718 [  1] C SampleApplication:Failed to initialize SDK!
2020-06-04 17:39:55.718 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create SampleApplication!
```

**Comment by kclchan** [comment]
Could you make sure you added '[-DCMAKE_BUILD_TYPE=DEBUG](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#build)' in your cmake command, do a make and rerun with SampleApp with DEBUG9?  This should give us more information on what might be happening.  Thanks!

**Comment by 9s2j6** [comment]
Hi @kclchan,
I have added '-DCMAKE_BUILD_TYPE=DEBUG' in my cmake command and done a make and rerun, but I have received the same error.

**Comment by kclchan** [comment]
Hi @9s2j6, the logs is still not showing anything useful.  Could you try this following the steps in [here](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html)?  This guide uses the setup.sh which should help with setup.  Thanks!

**Comment by 9s2j6** [comment]
Hi @kclchan,
The setup.sh script as shown in the steps above runs smoothly until it is 97% done with the build. At that point, my Pi freezes. I have attached the complete logs for the setup.sh script below.
[logs.txt](https://github.com/alexa/avs-device-sdk/files/4808202/logs.txt)

**Comment by ereich1217** [comment]
I have run into this exact problem many times and this has fixed it every time:

**If your device freezes - don't worry, restart it by unplugging your Pi's power cord. When you get back to your desktop, re-run the above setup.sh command to finish your install.**

https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html

**Comment by 9s2j6** [comment]
Hi @ereich1217,
Rebooting the Pi and re-running setup.sh does not solve my problem, the Pi freezes again when it reaches around 97%.

**Comment by alexandrekm-amzn** [comment]
Hi @9s2j6 
This issue has been inactive for 22 days. Another thing you can try: modify the setup.sh script to compile with a single thread (remove -j 2). If that doesn't work please open another ticket.
