### ISSUE TITLE
Audible can`t play issue

### ISSUE THREAD

**Issue by PerSpc** [alexa/avs-device-sdk#1721]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
1）AVS with Kindle/Music/IHeartradio is normal, but Audible is not.
2）My personal AVS account is a paid account, and I open audible skill.

## What is the expected behavior?
 Audible can be played normal.

## What behavior are you observing?
The following error occurs while playing Audible:
2020-06-05 03:10:05.200 [ 1b] E MediaPlayer:handleBusMessageError:name=AudioMediaPlayer,source=decoder,error=This appears to be a text file,debug=gstdecodebin2.c(2852)\: type_found ()\: /GstPipeline\:audio-pipeline/GstDecodeBin\:decoder\:
decodebin cannot decode plain text files
2020-06-05 03:10:05.202 [ 1b] E MediaPlayer:getCurrentStreamOffsetFailed:name=AudioMediaPlayer,reason=getElementGetStateFailure

## Provide the steps to reproduce the issue, if applicable:
“Alexa, play Life of Pi on audible”

## Tell us about your environment:
      AVS SDK 1.19
      gstreamer1-1.14.4

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more: aarch64 cortex A53 4core

### Tell us about your OS (Type & version):
- [ *] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by PerSpc** [comment]
But I can play audible's URL using gst-play-1.0：

# gst-play-1.0 "https://d1jobzhhm62zby.cloudfront.net/bk_adbl_031393/475522/sign
ed/g1/bk_adbl_031393_22,32_v4.m3u8?start_sec=1628&end_sec=2279&X-Amz-Algorithm=A
WS4-HMAC-SHA256&X-Amz-Credential=MD1BAJ27VEMQ8GGY7BZB/20200605/us-east-1/cloudfr
ont/aws4_request&X-Amz-Date=20200605T033845Z&X-Amz-Expires=60&X-Amz-SignedHeader
s=host&X-Amz-Signature=56ee66f6080cbada3adc776abd510baf4fb685ceee5aa1ebd97125001
d9e01b8"
Press 'k' to see a list of keyboard shortcuts.
Now playing https://d1jobzhhm62zby.cloudfront.net/bk_adbl_031393/475522/signed/g1/bk_adbl_031393_22,32_v4.m3u8?start_sec=1628&end_sec=2279&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=MD1BAJ27VEMQ8GGY7BZB/20200605/us-east-1/cloudfront/aws4_request&X-Amz-Date=20200605T033845Z&X-Amz-Expires=60&X-Amz-SignedHeaders=host&X-Amz-Signature=56ee66f6080cbada3adc776abd510baf4fb685ceee5aa1ebd97125001d9e01b8
Redistribute latency...
0:00:07.8 / 0:10:51.4

**Comment by kclchan** [comment]
Hi @PerSpc, thanks for contacting us about this.  This is a known bug in the PlaylistParser of the SDK and will be fixed in a future version of the SDK.  Thanks!
