### ISSUE TITLE
AVS Device on Raspberry Pi Authorization Code

### ISSUE THREAD

**Issue by hankp46** [alexa/avs-device-sdk#1724]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Every time I run the startsample.sh script it requires a new authorization code. Research shows the use of a refresh token and companion service, but it didn't seem to apply to the Raspberry Pi. Can you give me some advice on how to implement so don't have to enter a new code each time

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ereich1217** [comment]
By default it only requires authorization once.

Can you provide DEBUG9 log files?

**Comment by hankp46** [comment]
Here's the DEBUG9 Log File
[logxfil.txt](https://github.com/alexa/avs-device-sdk/files/4742563/logxfil.txt)

**Comment by kclchan** [comment]
Hi @hankp46,

According to the log:
```
SQLiteStatement:SQLiteStatement::finalizeFailed::Could release the prepared statement.:rcode=8
```
And the documentation from sqlite: https://www.sqlite.org/c3ref/c_abort.html

I seems that the database is readonly.  Could you check and enable write permission to the database files that are pointed to by the /home/pi/build/Integration/AlexaClientSDKConfig.json?

Or if you executed the `setup.sh` using `sudo`, you will need to run `startsample.sh` with `sudo` as well.  Hope this helps.  Thanks!

**Comment by hankp46** [comment]
Thanks. I resolved with another install.
