### ISSUE TITLE
SampleApplication:Failed to create keyword detector!

### ISSUE THREAD

**Issue by hankp46** [alexa/avs-device-sdk#1726]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
While running sample.sh
PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
Get following error;
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
2020-06-08 16:34:06.601 [  1] C SampleApplication:Failed to create keyword detector!

I did get this error during the make SampleApp
pi@raspberrypi:~/sdk-folder/sdk-build $ make SampleApp -- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
bash: syntax error near unexpected token `('

### What version of the AVS Device SDK are you using?
      1.19.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ x]  Raspian Buster

**Comment by ereich1217** [comment]
The problem you are describing isn't related to gtest.  gtest isn't necessary to build or run SampleApp.

This looks like either you have an installation error with ALSA, a configuration error with ALSA or you don't have a mic plugged into your raspberry pi.

**Comment by kclchan** [comment]
Hi @hankp46, please make sure your .aroundrc file is correctly configured: https://www.alsa-project.org/wiki/Asoundrc

**Comment by hankp46** [comment]
I did a new install an it is working fine.
Thanks
