### ISSUE TITLE
SpotifyESDKAdapter::handleLogin not being called

### ISSUE THREAD

**Issue by saurabh1234** [alexa/avs-device-sdk#1727]
## Briefly summarize your issue:
`void SpotifyESDKAdapter::handleLogin()` is not being called from the avs SDK. I suspect `ExternalMediaAdapterInterface` is not calling the handleLogin API. **playerId is empty**

## What is the expected behavior?
`handleLogin` should be called from my opinion / What can be the reasons that handle login is not being called ?

## What behavior are you observing?
`LOGS` - **`playerId`** is empty as you can see from logs
```
[ 15] 0 SpotifyESDKAdapter:Entered sessionManagementLoop.
[ 15] I SpotifyESDKAdapter:Sending RequestToken:reason=User not loggedIn.

...
[ 17] 0 SpotifyESDKAdapter:handleAuthorized:playerId=
```

## Provide the steps to reproduce the issue, if applicable:
Install the SDK's as metioned in the AVS doc.

### What version of the AVS Device SDK are you using?
   1. AVS SDK Version 1.19.1,  
   2. SpotifyESDKAdapter 1.19

### Tell us what hardware you're using:
- [ x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @saurabh1234, this issue can be better resolved by contacting your Amazon Business Development Representative and working with us through the appropriate channels. Closing the ticket, but please feel free to reopen if you have further questions.
