### ISSUE TITLE
ARM 64

### ISSUE THREAD

**Issue by jagould2012** [alexa/avs-device-sdk#1730]
I have my app working properly on Android using the build instructions. However, I only have armeabi-v7a libraries, and need arm64 to meet Googles requirements.

I see a lot of past closed bugs going back to 2019, 2018 stating that arm64 support is coming, but it doesnt look like instructions were ever posted. Can you confirm:

- arm64 support works
- what has to be done to build it for Android

**Comment by kclchan** [comment]
Hi @jagould2012, yes, arm64 support is in our backlog.  The changes will mostly be in android.sh to support the new platform so that the correct toolchains are used.

**Comment by jonathan-k4** [comment]
I see issues going back to 2018 about it being in the backlog. Google will no longer accept 32 bit apps. When is it expected?

Can you share any of the work on android.sh? I started changing it myself and got all the third-party stuff building for arm64, but then avs wouldn’t link against them. Any thoughts on what needs to change on avs other than the tool chain?
