### ISSUE TITLE
ProgressReportIntervalElapsed event is getting FAILED for TUNEIN podcast with tag as a DELAYED

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1733]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
ProgressReportIntervalElapsed event is failing in TuneIn music service.

We are getting offset value as 1800211 as target value is 1800000. This means there is no problem with offset value, the value is correct. Even though its getting failed.

We have tried to generate MVT report for TuneIn Podcast many times with Pure SDK v1.17 but always ProgressReportIntervalElapsed getting failed with tag as DELAYED.

As mentioned in below snippet that, event failure will get tagged as a DELAYED when the lenience is more than 3 seconds. But after comparing all the reports, the observation is as, even though the lenience is more than 3 seconds, we are getting event as pass

_Note (Reference- https://developer.amazon.com/en-US/docs/alexa/mvt/cert-requirements-mvt.html) :
Consider an utterance where the time between the play directive and the PlaybackStarted event was 8 seconds, which is above the maximum 3 seconds lenience for this event. This case would be tagged as a DELAYED failure by the MVT._

Please check the below snippet of ALL PASS report, timestamp of play directive is 11:11:58 and the timestamp of PlaybackStarted is 11:12:05. This difference is about 7 seconds which is greater than 3 seconds, even though we are not getting failure as mentioned in above note-
![image](https://user-images.githubusercontent.com/52921278/84497625-cb292a80-accc-11ea-81b1-355536ffdfbd.png)

Please check the below links for DEBUG9 logs and AQT reports-
DEBUG9 logs drivelink :: https://drive.google.com/file/d/1OZaoYzwkJ2VqevdHhdBaGiOXRbtmm58z/view?usp=sharing

AQT results for reference- zip file:: https://drive.google.com/open?id=1SXm7K1240_etxGTgCbC4FH20WOd6yku4

Always we are facing the failure as delayed. We need your help to in this issue.

Below is my observation that -
- Event is sent from AVS-SDK on time but its taking time to reach the server.
-  AVS-SDK is taking time send the event

Could you please let me know which can be the reason of failure from above observation.

Need your help to debug this issue.
 
## What is the expected behavior?
ProgressReportIntervalElapsed should get PASS

## What behavior are you observing?
ProgressReportIntervalElapsed is getting failed with tag DELAYED

## Provide the steps to reproduce the issue, if applicable:
Use the checklist provided by MVT to test
Generate report through MVT report generation tool

### What version of the AVS Device SDK are you using?
      AVS SDK 1.17

### Tell us what hardware you're using:
Android

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @dipalisb, I couldn't correlate the DEBUG9 log file with the AQT report as they seem to have executed at different time; the log file is on 2020-06-03, while the report is on 05/22/2020.

I would suggest you to contact your Amazon Business Development Representative and working with us through the appropriate channels. Closing the ticket, but please feel free to reopen if you have further questions.
