### ISSUE TITLE
Header file "portaudio.h" missing

### ISSUE THREAD

**Issue by chaserr** [alexa/avs-device-sdk#1735]
## Briefly summarize your issue:

I am trying to build AVS device sdk on MacOS 10.15.4. (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/mac-os.html). After going through all the steps, on running the make command, there is a missing header file error for the file "portaudio.h".
but it's on my computer: 
/Users/tongxing/my_project/third-part/portaudio/lib/.libs/libportaudio.a
/Users/tongxing/my_project/third-part/portaudio/include/portaudio.h

## What is the expected behavior?
The make command should build the AVS sdk on the Linux machine and the sample app should run.

## What behavior are you observing?
In the directory source/SampleApp/include/SampleApp, the file PortAudioMicrophoneWrapper.h has an #include <portaudio.h>. This header file is missing from the source code.

## Tell us about your environment:
I am buulding the AVS sdk version 1.19.0 on MacOS 10.15.4.

### Tell us what hardware you're using:
The hardware being used is a laptop.
![截屏2020-06-17 下午3 22 23](https://user-images.githubusercontent.com/10346215/84868019-9cd19380-b0ae-11ea-93df-4ba2335a21fa.png)

**Comment by ereich1217** [comment]
Step 6 of the Mac OS instructions explains how to install PortAudio https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/mac-os.html

After you follow this step you should see portaudio.h in the directory $HOME/third-party/portaudio/include

Verify the Port Audio was installed correctly.

**Comment by chaserr** [comment]
> Mac OS指令的第6步说明了如何安装PortAudio [https://developer.amazon.com/zh-CN/docs/alexa/avs-device-sdk/mac-os.html](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/mac-os.html)
> 
> 完成此步骤后，您应该在目录$ HOME / third-party / portaudio / include中看到portaudio.h
> 
> 验证端口音频是否正确安装。

**Comment by chaserr** [comment]
@ereich1217 
I was able to find the corresponding file, but still failed to compile。
![Uploading 截屏2020-06-18 上午10.09.56.png…]()
![截屏2020-06-18 上午10 09 30](https://user-images.githubusercontent.com/10346215/84969928-46b32d80-b14c-11ea-96db-2bf2ca2e6ed6.png)

**Comment by ereich1217** [comment]
Can you post the **cmake** command that you used when you created your build directory?

**Comment by chaserr** [comment]
> 您可以发布在创建构建目录时使用的**cmake**命令吗？

`cmake $HOME/my_project/source/avs-device-sdk \
 -DGSTREAMER_MEDIA_PLAYER=ON \
 -DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
 -DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \
 -DPORTAUDIO=ON \
 -DPORTAUDIO_LIB_PATH=$HOME/my_project/third-party/portaudio/lib/.libs/libportaudio.a \
 -DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include \
 -DCMAKE_BUILD_TYPE=DEBUG`

**Comment by scotthea-amazon** [comment]
Hi @chaserr ,

Looking at the path you showed in your summary:

    `/Users/tongxing/my_project/third-part/portaudio/include/portaudio.h`

I see that

   `/third-part/`

is missing a `y` that is included in your cmake command line:

    `-DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include`

Could that be the problem?

If that is not the problem, I suggest adding `VERBOSE=1` to your invocation of make.  That should show you the full command line passed to the compiler and from there we can see what include directories were actually provided.

Best regards,
-SWH

**Comment by chaserr** [comment]
My God, I made a stupid mistake.
Hi  @scotthea-amazon  
Thank you very much. After I changed the file path to third-party, I compiled it again and it passed smoothly.
