### ISSUE TITLE
What's the exactly logic of checking dependency libcurl package?

### ISSUE THREAD

**Issue by yangsongx** [alexa/avs-device-sdk#1738]
I am really feel frustrating for build AVS.

I made a rootfs with all dependencies listed on the AVS document.

After I all done, I'm sure all depencies are satisfied, and the libcurl is HTTP2 enabled. For example, suppose I used /alexa/ as the rootfs, then the libcurl is build out to /alexa/lib/libcurl.so,

And I also let the pkg-config be able to locate this libcurl correctly:

```
$ pkg-config --cflags libcurl
-I/alexa/include -L/alexa/lib -lcurl
```

But, when I trigger the cmake:

```
make ../avs-device-sdk-1.18.0/ -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/alexa/lib/libportaudio.so -DPORTAUDIO_INCLUDE_DIR=/alexa/include -DCMAKE_BUILD_TYPE=DEBUG
```

It reported libcurl is NOT FOUND!!!!

I am confused very much about this!!!!! Because libcurl already be able to detect as I showed!

What's the logic of dependency-checking for AVS? Could someone help me?

I am building this on Debian 10.4 Generic Linux.

**Comment by caleighatamazon** [comment]
Hi @yangsongx, you can specify the location of curl in the cmake flags `CURL_LIBRARY` and `CURL_INCLUDE_DIR`.
