### ISSUE TITLE
Failed to run on Android 

### ISSUE THREAD

**Issue by albanoandrea** [alexa/avs-device-sdk#1739]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Build avs device sdk for Android, following [this guide](https://developer.amazon.com/it-IT/docs/alexa/avs-device-sdk/android.html).
When trying to run the sample app got the following error:

> CANNOT LINK EXECUTABLE "/data/local/tmp/alexa_sdk/bin/SampleApp": library "libLibSampleApp.so" not found: needed by main executable

Same error replicated on AVD based on Pixel XL API 30, x86 and a physical ARM android device under development.

## What is the expected behavior?
Start avs console

## What behavior are you observing?
Generated library seems to miss some dependency. 
The library not found it's actually there, in the right place.

## Provide the steps to reproduce the issue, if applicable:
Follow this  [this guide](https://developer.amazon.com/it-IT/docs/alexa/avs-device-sdk/android.html) and then run the generated files on an AVD.

Here the androidConfig.txt used:
```
# Fill the lines below to configure android build.
PLATFORM="android"
API_LEVEL="26"
TARGET_SYSTEM="x86"
DEVICE_INSTALL_PATH="/data/local/tmp/alexa_sdk"
BUILD_TYPE="debug"
```

## Tell us about your environment:
Ubuntu 16.04

### What version of the AVS Device SDK are you using?
     Master: 1.19.1 currently

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
AVD Pixel XL API 30

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ x] Other - tell us more:
Android

**Comment by caleighatamazon** [comment]
Hello! Did you use the generated `startsample.sh` bash script to run the Sample App? If not, what command did you use to start the app?

**Comment by albanoandrea** [comment]
Yes,
I've tried both to run `startsample.sh` and to run the same line from adb shell.

**Comment by caleighatamazon** [comment]
Do you see any errors when you build the SDK for Android? Or is the error only when you actually run the app?

Is this error the full error log or is there anything else printed when you try to run the app? `CANNOT LINK EXECUTABLE "/data/local/tmp/alexa_sdk/bin/SampleApp": library "libLibSampleApp.so" not found: needed by main executable`

Have you made any modifications, or are you just running our setup and SDK exactly as we provide it?

**Comment by albanoandrea** [comment]
No modification at all and build seems totally successfull.
If no one else can replicate the issue I will try on a different system to check it it's my machine the cause.

**Comment by albanoandrea** [comment]
Hi,
just to infrom that on a brand new machine it works fine, so I suppose there is something wrong on my building machine.
Thanks for the support.

**Comment by caleighatamazon** [comment]
Awesome! Glad it's working.

**Comment by Andrea2202** [comment]
Hi All! I've the same problem in a real device 

`CANNOT LINK EXECUTABLE "./SampleApp": cannot locate symbol "EVP_MD_CTX_init" referenced by "/system/lib/libsqlite.so"...`

This i my configuration

`# Fill the lines below to configure android build.
PLATFORM="android"
API_LEVEL="26"
TARGET_SYSTEM="arm"
DEVICE_INSTALL_PATH="/data/local/tmp/alexa_sdk"
BUILD_TYPE="debug"`

I'm working on a Galaxy A10 with android 10

Thnaks in advance
