### ISSUE TITLE
Alexa is going to connecting state with new cacert.pem

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1740]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have build the AVS-SDK over server and able to generate the lib files, SampleApp and cacert.pem with CA certificates.
With above build we are trying to run the Alexa but it is going to **CONNECTING** state and getting below error in DEBUG9 logs -

> 2020-06-23 09:53:21.330 [  3] 5 CBLAuthDelegate:requestCodePair
> 2020-06-23 09:53:21.713 [  3] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=77,error=Error
> 2020-06-23 09:53:21.714 [  3] 5 CBLAuthDelegate:receiveCodePairResponse:code=0
> 2020-06-23 09:53:21.715 [  3] 5 CBLAuthDelegate:mapHTTPStatusToError:code=0,error=UNKNOWN_ERROR
> 2020-06-23 09:53:21.716 [  3] E CBLAuthDelegate:parseLWAResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
> 2020-06-23 09:53:21.716 [  3] 5 CBLAuthDelegate:setAuthError:authError=UNKNOWN_ERROR
> 2020-06-23 09:53:21.716 [  3] 0 CBLAuthDelegate:receiveCodePairResponseFailed:result=UNKNOWN_ERROR

Could you please let me know, is this error related to curl library or due to CA libraries?

Need help to resolve this issue.

Thank you in advance.

## What is the expected behavior?
Alexa should work as expected

## What behavior are you observing?
Alexa is going to connecting and not able to do CBL (Code Base Linking)

## Provide the steps to reproduce the issue, if applicable:
Used below command to run Alexa-

> adb shell LD_LIBRARY_PATH=/product/avs/lib       /product/avs/bin/SampleApp       /product/avs/AlexaClientSDKConfig.json DEBUG9

### What version of the AVS Device SDK are you using?
      AVS-SDK 1.17

### Tell us what hardware you're using:
Android

### Tell us about your OS (Type & version):
Linux

**Comment by caleighatamazon** [comment]
Hi @dipalisb, error 77 from curl would appear to indicate a problem with your SSL CA Cert, as described [here](https://stackoverflow.com/questions/17064601/curl-not-working-error-77-for-ssl-connections-on-centos-for-non-root-users). Maybe #900 , #990, or #1186 will also provide some guidance. Please let us know if you need further help.

**Comment by dipalisb** [comment]
Hi @caleighatamazon,

We took the reference of the issue id's provided by you but the issue us not resolved at our end. 

With all the change we are facing same error.

Could please let us know some other solution.

Thanks.

**Comment by caleighatamazon** [comment]
Hi @dipalisb , can you let me know what the output is when you run this:

```
adb shell ls -l  /product/avs
```

It might help to run the sample app with adb root access (run `adb root` before running the sample app).

Are you using our [quick start instructions for Android](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html)?

**Comment by dipalisb** [comment]
Hi @caleighatamazon,

Please find the below response -

> can you let me know what the output is when you run this:

Already running with root even though we are facing failure. Please check the below snippet-

![image](https://user-images.githubusercontent.com/52921278/85890792-b2139400-b80b-11ea-98e7-0cb001b97f69.png)

> Are you using our quick start instructions for Android?

Yes we had referred the suggested URL while building AVS-SDK. 

Thanks.

**Comment by caleighatamazon** [comment]
Can you verify that the curl library you are using with the SDK was configured with the correct path to `cacert.pem`?

You can do this by checking curl's `config.log`. Here's one way to check that log. You'll have to update the below variables with whatever you specified when running the set-up script.
```
cd ${PATH_TO_WHERE_YOU_RAN_SETUP}/debug/android-{$API_LEVEL}/{TARGET_SYSTEM}/curl
vim config.log
```

Near the top of that text file, you'll see the arguments used to build curl ("Invocation command line was" ...). The important one to pay attention to is `--with-ca-bundle`. That tells curl where to find that CA bundle.

Yours should look like this: `--with-ca-bundle=/product/avs/cacert.pem`. If it's not correct, you can re-run the setup script from scratch, making sure to clean up the build directory on the device as well.

If it is correct, though, then you will want to look into your Android device's CA certificates -- perhaps they are out-dated. The SDK simply uses those certificates, like so (from `android.sh`):

```
  printInfo "Generate CA bundle"
  ${ADB} shell "echo > ${CURL_CA_BUNDLE}"
  ${ADB} shell \
      "for f in \$(ls ${ANDROID_CA_PATH}); do \
          cat ${ANDROID_CA_PATH}\$f | grep 'END CERTIFICATE' -B 100 >> ${CURL_CA_BUNDLE}; \
      done;"
}
```

So if there's a problem with Android CA certificates, then there will be a problem with the SDK.

Hopefully this helps. Let me know if you have more questions.

**Comment by mvelegon-amzn** [comment]
Hi @dipalisb would you still need assistance with this issue?

**Comment by dipalisb** [comment]
Hi @caleighatamazon,

Thank you so much for response. Now the issue is resolved at our end.

Hi @mvelegon-amzn,
Issue is resolved at our end.

Thank you.
