### ISSUE TITLE
Linux Desktop and v1.20.0: No sound playing radio

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#1748]
## Briefly summarize your issue:
Running alexa-sdk v1.20.0 on Linux Desktop. I can talk to alexa and hear her answers. But when I say "Alexa, play hr3" or "Alexa, play hr3 from tunein", Alexa repeat "hr3 on ..." but then there is no sound, no radio playing.

## What is the expected behavior?
Radio playing.

## What behavior are you observing?
Silence.

## Provide the steps to reproduce the issue, if applicable:
see above.

## Tell us about your environment:
Running on ubuntu desktop.
### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

The problem is new with version 1.20.0, version 1.19.1 works.
There is no problem running on a raspberry pi, here both versions work.

This issue is hard to reproduce when DEBUG9 is enabled, so it is may time critical.
If the issue occurs and I repeat "Alexa, play hr3" with this second try it works.

The following logfile contains this scenario:

* "Alexa, play hr3"
* after SPEAKING 2 RenderPlayerInfoCard's (2xPLAYING), no radio playing
* again "Alexa, play hr3"
* after SPEAKING 3 RenderPlayerInfoCard's (1xSTOPPED, 2xPLAYING), radio playing

The only thing I observed while testing is, if this issue occurs, the value `Offset milliseconds` of the first PLAYING RenderPlayerInfoCard is very small, always < 10.

Logfile with debug9:
[alexa_v1.20.0.log](https://github.com/alexa/avs-device-sdk/files/4847342/alexa_v1.20.0.log)

**Comment by mvelegon-amzn** [comment]
Hi @khassel We are currently looking into this issue. We will update once we have more info. In the mean time if you figured out a way to reproduce this issue consistently please let us know as it will help us with debugging this issue further.

**Comment by khassel** [comment]
Thanks!

Using `-DCMAKE_BUILD_TYPE=MINSIZEREL` I can reproduce this with every run of the SampleApp, but that's may not so good for debugging ...

**Comment by kclchan** [comment]
Hi @khassel, sorry for the late reply.  I notice in the log that the fake-audio-sink is being used:

```
2020-06-29 17:40:44.813 [ 14] 9 MediaPlayer:messageReceived:name=AudioMediaPlayer,type=state-changed,source=fake-audio-sink
```

Just want to see if you have made any modification to MediaPlayer?  If not, could you try adding this configuration in AlexaClientSDKConfig.json to not use the default `autoaudiosink`, but use `alsasink` instead:

```
    "gstreamerMediaPlayer":{
         "audioSink":"alsasink"
     },
```

**Comment by khassel** [comment]
With the above gstreamer option, playing radio doesn't work:
````
2020-08-05 20:48:13.959 [ 24] E MediaPlayer:handlePlayFailed:name=AudioMediaPlayer:reason=gstElementSetStateFailure
2020-08-05 20:48:13.959 [ 24] E MediaPlayer:getCurrentStreamOffsetFailed:name=AudioMediaPlayer,reason=getElementGetStateFailure
2020-08-05 20:48:13.960 [ 24] E MediaPlayer:getCurrentStreamOffsetFailed:name=AudioMediaPlayer,reason=getElementGetStateFailure
2020-08-05 20:48:14.045 [ 24] E MediaPlayer:handleBusMessageError:name=AudioMediaPlayer,source=audio_sink,error=Could not open audio device for playback. Device is being used by another application.,debug=gstalsasink.c(860)\: gst_alsasink_open ()\: /GstPipeline\:audio-pipeline/GstAlsaSink\:audio_sink\:
Device 'default' is busy
````

As already described in the original post, playing radio works with the second try (without gstreamer option).

**Comment by kclchan** [comment]
Hi @khassel, thanks for getting back so quickly, according to the logs, it seems the problem was trying to play two items at the same time:

```
error=Could not open audio device for playback. Device is being used by another application.,debug=gstalsasink.c(860
```

I think you would need to add something like dmix in your alsa configuration.  Please find more details in [here](https://alsa.opensrc.org/Dmix).

**Comment by khassel** [comment]
I`m not convinced, that this is related to the original issue.

My setup worked with all sdk versions before, but not with v1.20.0. Same setup with v1.19.1 works. I spent much time to catch the logs und bringing this up, but at this point I will stop digging deaper (and playing around with alsa config).

Feel free to close this.

**Comment by kclchan** [comment]
Please feel to open a new issue if you have more questions.  Thanks.
