### ISSUE TITLE
Any state change notification sound ?

### ISSUE THREAD

**Issue by justy0714** [alexa/avs-device-sdk#175]
Does AVS device SDK provide state change notification sound like Echo has ?
For example: 1. When Echo is ready, it says 'Hello' to let user know that system initiation is done
                      2. When Echo is in setup mode, it says 'Now in setup mode...' to inform user using APP to 
                          configure Echo.

Thanks!!!

**Comment by kjkh** [comment]
Hi, 
The AVS SDK doesn't currently support sound notifications of state. In the Sample App, we do support printing of various states during a dialog. See the enum `DialogUXStateObserverInterface`. These mostly correspond to the ones provided in the UX Guidelines. We'll create a feature request internally for this. Thanks for the question! Closing the issue, but feel free to re-open if you have any further comments.
