### ISSUE TITLE
raspberry pi alexa

### ISSUE THREAD

**Issue by githhub1d** [alexa/avs-device-sdk#1753]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by alexandrekm-amzn** [comment]
This issue doesn't follow the Issue Reporting Guide and it looks like it was created by mistake, closing it.
