### ISSUE TITLE
alexa/alexa-auto-sdk : Unable to have A2A calling with ACM extension enabled.

### ISSUE THREAD

**Issue by Ruhi697** [alexa/avs-device-sdk#1756]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
**AUTO-SDK** : Unable to use ACM extension in auto-sdk for A2A calling. After the utterance "Alexa Call 'name', the response we get is : Calling with Alexa is not supported on this device, you can use the Alexa app instead.

Below logs shows successful integration of AlexaComms extension as well as initialization of the same -
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.331 INFO ++++++++++:**AlexaCommsService:init**
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.333 INFO :::##################################
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.335 INFO :::# AlexaCommsLib
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.336 INFO :::# Version: 3.1.118
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.338 INFO :::# Build Time: 01/17/2020 06:56
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.340 INFO :::# Git Base:
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.343 INFO ----------:AlexaCommsService:init
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.345 INFO ----------:AlexaCommsService:createSipUserAgent
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.347 INFO ----------:AlexaCommsService:createInstance
com.amazon.sampleapp: [AVS] I CallManager:commsMessage::2020-07-04 21:42:44.349 INFO ++++++++++**:AlexaCommsService:run::Running AlexaCommsService 3.1.118** 01/17/2020 06:56

In the ACM README.MD ,Starfield Services Root Certificate Authority - G2 is mentioned. How do we add this certificate to the device to ensure ACM working?

## What is the expected behavior?
It is expected that after extending the ACM module, an A2A call should happen over data.

## What behavior are you observing?
After the utterance "Alexa Call 'name', the response we get is : Calling with Alexa is not supported on this device, you can use the ALexa app instead.

## Provide the steps to reproduce the issue, if applicable:
1. Adding AlexaComms externsion into Auto SDK
2.  Extending AlexaComms class to get Alexa calling functionality
3.  Install the generated sample app apk to the target device
4. gave permissions to use device contacts.
5. .testing inbound & outbound calls with AlexaCommsHandler

### What version of the AVS Device SDK are you using?
      <alexa-auto-sdk 2.2.1>

### Tell us what hardware you're using:
- [ ] Other - Android 10, Qualcomm chipset : sdm660 and sdm450

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by kjkh** [comment]
Hi @Ruhi697,

Alexa Automotive SDK inquiries are not typically within the domain of this forum. A common cause of this issue is that the account is not provisioned correctly. Please reach out to your Amazon business representative to investigate further, as it requires providing sensitive information such as the Customer ID.

**Comment by Ruhi697** [comment]
Hi @kjkh ,
Thank you for your response.
We will certainly reach out to our Amazon representative regarding this issue. 
Meanwhile, if you could relay some pointers that we could try, please let me know.
Could you also suggest at which forum are the Auto-SDK inquiries explicitly addressed, if any ?

**Comment by madelynj** [comment]
@Ruhi697 Please direct Auto SDK inquiries to your automotive Solutions Architect or Partner Manager for the quickest resolution. Thanks!
