### ISSUE TITLE
Android example without root user

### ISSUE THREAD

**Issue by dewijones92** [alexa/avs-device-sdk#1758]
## Briefly summarize your issue:
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html
I am following this example here. But I can not run `bash startsample.sh` as I do not have root

## What is the expected behavior?
Successfully run the sample app using  `bash startsample.sh`

## What behavior are you observing?
I am unable to set executable permissions on anything in the /sdcard directory.  i.e. **chmod +x**
This is preventing me from running this app.
Also /sdcard is the only directory I can write to using the adb shell.  
When trying to connect adb as root I get the following error message:
`adbd cannot run as root in production builds`

## Tell us about your environment:
Android version 9

## Suggestion
Is there a way to make just a normal APK of the sample app? So I can easily run it? 
This won't require adb **root**

Please help
Many thanks :)

**Comment by dewijones92** [comment]
Please get back to me when you can.
My company are rolling out our smart devices to multiple care homes soon. We are deciding between: Alexa, Google and Mozilla's DeepSpeech.
Many thanks

**Comment by dewijones92** [comment]
Any update on this please?
Thanks

**Comment by kjkh** [comment]
Hi,

We would like to further continue this conversation on another channel. Do you currently have an Amazon business representative you can contact? If not, we will follow up with how you can best reach out to us.

**Comment by scotthea-amazon** [comment]
@dewijones92,

Have you been able to make contact through an Amazon business representative?

Best regards,
-SWH

**Comment by dewijones92** [comment]
@scotthea-amazon 
Hi can you please give me your email address?
I have a query about integrating with amazon custom skills.
Here is my email address
dewi@caredirect.tech
Thanks

**Comment by caleighatamazon** [comment]
Hi there, can you please email our team at avs-device-sdk@amazon.com ?

Thanks. I'll close this issue and we can continue the conversation over email.
