### ISSUE TITLE
ExternalMediaPlayer uses PlaybackController v1.0

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#1760]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
ExternalMediaPlayer capability uses interface "Alexa.PlaybackController" version 1.0 while the new capability agent PlaybackController uses interface "PlaybackController" version 1.1. This is causing my Capability Discovery to report this: 

{"type":"AlexaInterface","interface":"Alexa.PlaybackController","version":"1.0"},{"type":"AlexaInterface","interface":"PlaybackController","version":"1.1"}

## What is the expected behavior?
I don't believe I should have two different PlaybackController versions being supported simultaneously.

## What behavior are you observing?
i observe the capability discovery reporting two PlaybackController versions

## Provide the steps to reproduce the issue, if applicable:
read the discovery off the http2 line as it talks to the endpoint, or print the discovery packet inside the Capabilities/src/Utils

### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi Brett,

While having similar names, these are two separate interfaces, and are not equivalent to each other. Is this causing any functional problems?

**Comment by brett-lynnes** [comment]
As far as I can tell, the modules they are used in appear to be functioning as expected (although it is hard to see which directive is handled by which module even with DEBUG9 logs).

can you guys clean up the interface documentation (or provide links in these confusing ones) so it is possible to find both "Alexa.PlaybackController" and "PlaybackController" since they are apparently two separate things?
