### ISSUE TITLE
Alexa speaking slowly on Raspberry Pi 3B

### ISSUE THREAD

**Issue by lebkuecher** [alexa/avs-device-sdk#1763]
I have setup everything, and I've followed the steps other steps suggested here to try to fix, and nothing seems to be able to fix it.

**Comment by kjkh** [comment]
Hi,

Can you please provide more information on your setup? 

Which version of the SDK are you using?
How did you set up the PI?
Are you using ALSA directly or PulseAudio?

**Comment by lebkuecher** [comment]
> Hi,
> 
> Can you please provide more information on your setup? 
> 
> Which version of the SDK are you using?
> How did you set up the PI?
> Are you using ALSA directly or PulseAudio?

I am unsure how to find the version number.  I followed the directions in this page: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html

This is the second version actually, I tried a different one first and had the same problem.  On the page linked above, there is a part when you test your audio, and the playback was just fine, so it appears to just be an issue with the Alexa part.

The setup appears to use Alsa.  My mic is the PS Eye, which was highly recommended when I did research beforehand.  Actually works great and picks up my voice from other rooms when in trying to use one of the Dots.  On the Pi, I an also running the MagicMirror software.  And I have the 3B version of the Pi.

If you have any additional questions, please let me know.

**Comment by ereich1217** [comment]
When you start the SampleApp it will tell you the SDK version almost immediately.
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.18.0

**Comment by lebkuecher** [comment]
Thanks.  It is 1.20.0

**Comment by ereich1217** [comment]
You say that you are running the "MagicMirror" software.  Have you successfully run AVS on your Raspberry Pi as a clean setup as described in the quick start guide?  When using AVS with other software running on the system there can be interaction problems.  Try getting AVS running on a pristine Raspberry Pi first with your hardware and confirm everything is working that way.

It is possible that MagicMirror is changing an audio setting that is impacting the playback speed of your audio in AVS without AVS being aware.

**Comment by scotthea-amazon** [comment]
Hello @lebkuecher,

Just to make sure we understand the problem, when you say Alexa is speaking slowly - do you mean that the audio is distorted, or do you mean that there is an unusual delay between making a request, the playback of Alexa's reply?

Best regards,
-SWH

**Comment by lebkuecher** [comment]
Distorted, she almost sounds drunk.

**Comment by scotthea-amazon** [comment]
Hello @lebkuecher,

Thank you for the clarification!

Please let us know if running the AVS SDK in a pristine environment resolves the issue.

Best regards,
-SWH

**Comment by kclchan** [comment]
Closing this issue now.   Thanks.

**Comment by rajat8888** [comment]
Same issue tried everything
