### ISSUE TITLE
Regarding logging issue

### ISSUE THREAD

**Issue by umash99** [alexa/avs-device-sdk#1766]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
is there any option to capture all the alexa log in a file 

## What is the expected behavior?
log should be present in log folder 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello @umash99,

If you are using SampelApp "as is", you can redirect the console output to a file.

If you are willing to modify SampleApp, you can create your own implementation of the `Logger` class:

https://github.com/alexa/avs-device-sdk/blob/v1.20.0/AVSCommon/Utils/include/AVSCommon/Utils/Logger/Logger.h#L150

You will only need to override the emit() method, which you in your case would write to a file.

You will also need a static factory function for you Logger implementation that returns `std::shared_ptr<Logger>`.  For instance:

class MyLogger : public Logger {
public:
    static std::shared_ptr<Logger> createMyLogger() {
        return std::shared_ptr<Logger>(new MyLogger());
    }
    ...

Then, replace `getConsoleLogger` in the following line with `MyLogger::createMyLogger`.

https://github.com/alexa/avs-device-sdk/blob/v1.20.0/applications/acsdkDefaultSampleApplicationOptions/src/DefaultSampleApplicationOptionsComponent.cpp#L47

Best regards,
-SWH

**Comment by umash99** [comment]
Thank you,, can you please tell me modifying the sampleApp  mean , you are referring  avs-device-sdk  or something else and which one is good in terms of log size !!

**Comment by kclchan** [comment]
Hi @umash99, the SDK uses the ConsoleLogger to print logs to the console.  @scotthea-amazon is suggesting that you can write your own logger such that logs will be printed to a file instead, and has provided instruction on such.

Alternately, if you want to use SampleApp "as is", then you can redirect the console output to a file.  For example, one way to do this is to use `tee`:

 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9 | tee <name and location of your log file>

Hope this helps.

**Comment by umash99** [comment]
Hi ,
can you confirm , we are using v1.18 , is it required below line which i got in first reponse 
 replace getConsoleLogger in the following line with MyLogger::createMyLogger  this one is present application folder which is available in V1.20  not in 1.18  
in that case if we write the own logger class will it be useful !!

**Comment by umash99** [comment]
thank you ..can you please confirm  we are using  1.18 repo...and in that

**Comment by umash99** [comment]
Can it be possible to do without modifying the Sampleapp ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by umash99** [comment]
Can it be possible to do without modifying the Sampleapp
