### ISSUE TITLE
C++ internal compiler error for SampleApplication.cpp.o

### ISSUE THREAD

**Issue by ujjwalk450** [alexa/avs-device-sdk#1767]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
SDK build freezes at 97% while building cxx object SampleApplication.cpp.o

## What behavior are you observing?
Raspberry Pi hangs with full RAM usage for 2-3 hours and after that c++ reports internal complier error

## Provide the steps to reproduce the issue, if applicable:
Build the SDK on raspberry pi running the raspabian version in the guide.

## Tell us about your environment:
Raspberry Pi 3b overclocked to 1350Mhz processor freq and 588Mhz SDRAM freq running noobs v2.9.

### What version of the AVS Device SDK are you using?
 1.20.0

### Tell us what hardware you're using:

![IMG_20200731_101101](https://user-images.githubusercontent.com/20141784/89068375-b729ad00-d38e-11ea-878a-83f106e31b64.jpg)
Raspberry Pi

### Tell us about your OS (Type & version):

Raspbian Stretch

**Comment by kclchan** [comment]
Hi @ujjwalk450, could you try compiling with -j1 option?  We have found that the pi may overheat when run with too many parallel jobs.  Also, could you try not overclock your pi and see if it makes a difference?  Thanks.

**Comment by ujjwalk450** [comment]
@kclchan thanks for the suggestion, but it did not work. However I got it to work by selecting CLI as my boot option from raspi-config and I didn't use desktop which saved a bit of RAM for the process to get complete.
