### ISSUE TITLE
when downloading the SDK WWW.PortAudio.Com website is down it seems. just retrying. is there any workaround for this or just need to wait for the website to respond?

### ISSUE THREAD

**Issue by ashoksva** [alexa/avs-device-sdk#1768]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ujjwalk450** [comment]
Need to wait, it started working this morning

**Comment by ashoksva** [comment]
its working now...thank you

**Comment by ujjwalk450** [comment]
Please close the issue

**Comment by ashoksva** [comment]
worked after a day..
