### ISSUE TITLE
Script checking compatibility if my system meets your minimum requirement

### ISSUE THREAD

**Issue by ghost** [alexa/avs-device-sdk#177]
Hello , 

I am looking if you have a script which i can run on my system and check if my systems meets your minimum requirement like gstreamer or lib-curl ? 

Thanks
Paul

**Comment by kjkh** [comment]
Hi,
Unfortunately we do not currently have such a script that verifies all dependencies. You can see a list of the required dependencies here: https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#core-dependencies. In addition, we have instructions for [Linux, macOS](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide), and [Raspberry PI](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide) which will guide you in obtaining the necessary dependencies to run our SDK.

**Comment by mradulan** [comment]
Hi Paul, can you close the issue? Do you have more questions about dependencies?

**Comment by kclchan** [comment]
Closing the issue.  Please reopen if you have further questions.  Thanks!
