### ISSUE TITLE
Give "Resume" command after pause an Audible book, Alexa will resume Amazon music instead of Audible book

### ISSUE THREAD

**Issue by DeepikaBalaga** [alexa/avs-device-sdk#1770]
[Steps]
1) Ask Alexa to read Audible book. ("Alexa, read The Hobbit.")
2) "Alexa, stop."
3) "Alexa, play."
4) "Alexa, pause."
5) "Alexa, resume."

## Briefly summarize your issue:
Give "Resume" command after pause an Audible book, Alexa will resume Amazon music instead of Audible book

## What is the expected behavior?
2) Alexa stop reading Audible book.
3) Alexa resume to read Audible book.
4) Alexa stop reading Audible book.
5) Alexa resume to read Audible book.

## What behavior are you observing?
5) Alexa resume Amazon Music.
log: A10_audible_resume.txt attached below.

## Provide the steps to reproduce the issue, if applicable:
As mentioned above
### What version of the AVS Device SDK are you using?
      1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Linux

LOGS BELOW:
[A10_AudibleIssue_log.txt](https://github.com/alexa/avs-device-sdk/files/5013819/A10_AudibleIssue_log.txt)

**Comment by DeepikaBalaga** [comment]
In-addition to the above query, we have 2 more pointers:

1. **Account basis reproducibility**: Issue is reproduced only with one account for 10/10 re-trails  and with other accounts Audible is playing after resume also. **Account with the issue reproducibility -bdc7sit20@gmail.com**
2. **Log analysis: l**ease check below additional information from our end after analyzing the logs of issue reproducible and not reproducible cases.

For issue reproducible case, please check the below logs:
![image](https://user-images.githubusercontent.com/31942830/89342750-d98a3600-d6c0-11ea-8fcb-22987d938cba.png)
For issue not-reproducible case, please check the below logs:
![image](https://user-images.githubusercontent.com/31942830/89342806-f161ba00-d6c0-11ea-9536-b42829870e7c.png)

Let us know for any other information needed from our end and help to get back ASAP.

Thanks!

**Comment by kclchan** [comment]
Hi @DeepikaBalaga, sorry, the logs you provided does not contain enough information for further investigation.  Would it be possible to attach the full DEBUG9 log from the SDK?

**Comment by DeepikaBalaga** [comment]
> Hi @DeepikaBalaga, sorry, the logs you provided does not contain enough information for further investigation. Would it be possible to attach the full DEBUG9 log from the SDK?

Hi @kclchan Thanks for the response, we will reproduce this issue and send the DEBUG9 logs to you ASAP.

**Comment by DeepikaBalaga** [comment]
> Hi @DeepikaBalaga, sorry, the logs you provided does not contain enough information for further investigation. Would it be possible to attach the full DEBUG9 log from the SDK?

Thanks for the waiting @kclchan ,
Please check the below DEBUG9 logs for this issue. Also, we found one more issue when tried to capture DEBUG9 logs. That is Alexa got disconnected Automatically. 

Please help to check this main issue - Give "Resume" command after pause an Audible book, Alexa will resume Amazon music instead of Audible book #1770  and let us know for the updates.


DEBUG9 LOGS::: 
[A10_AudibleIssue_DEBUG9_log.txt](https://github.com/alexa/avs-device-sdk/files/5073617/A10_AudibleIssue_DEBUG9_log.txt)

Thanks!

**Comment by DeepikaBalaga** [comment]
Dear @kclchan , 

Thanks for waiting, please check the attached DEBUG9 logs captured.

Help us to either resolve this issue or support us to analyze the root cause from the DEBUG9 logs.

Let us know for any other information needed from our end.
[log_A10_AudibleResumeIssue_DEBUG9.txt](https://github.com/alexa/avs-device-sdk/files/5082170/log_A10_AudibleResumeIssue_DEBUG9.txt)

**Comment by mvelegon-amzn** [comment]
Hi @DeepikaBalaga The latest log you provided shows that the client is not connected to Alexa yet. It appears there is an issue with registration as well: 

`2020-08-14 06:19:43.416 [ 2c] E MessageRequest:onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"58cb66c9-6a06-4ecc-a5f1-95fc824cffc3"}\,"payload"\:{"code"\:"INVALID_REQUEST_EXCEPTION"\,"description"\:"Registration information does not match for the AVS endpoint\: Registered productId is <CDR8010>. Registered deviceSerialNumber is <61A4B000204>"}}`

Could you please share how you registered the device and how you generated the AlexaClientSDKConfg.json file?

**Comment by DeepikaBalaga** [comment]
Dear @mvelegon-amzn   @kclchan ,

Please check the below attached DEBUG9 logs for this issue. Let me know for any further information from our end.

As this is a long time issue, please help to check and help us fast.
Thanks!
[A10_audibleLogs.txt](https://github.com/alexa/avs-device-sdk/files/5121327/A10_audibleLogs.txt)

**Comment by womw** [comment]
Hi @DeepikaBalaga I see from the logs that following the resume utterance, that a Play Directive for Amazon Music. I'm going to raise this issue with the cloud team to see why this is being sent.

**Comment by DeepikaBalaga** [comment]
@womw , Thanks for the update.

**just for information, please note that this issue is getting reproduced only with one account -  bdc7sit20@gmail.com**

We have verified with other accounts and working as expected overthere.

Please help to check whether this cloud issue might be an account related issue!! We will be waiting for your response.

Thanks in advance!

**Comment by womw** [comment]
Hi @DeepikaBalaga can you provide a more recent log of this issue happening? It will help assist our Cloud team with their investigation.

**Comment by DeepikaBalaga** [comment]
Hi @womw ,
Please check the below logs attached below::
[A10_audibleLogs.txt](https://github.com/alexa/avs-device-sdk/files/5140088/A10_audibleLogs.txt)

We are observing this issue only on one account only  with username -bdc7sit20@gmail.com

Please help us to solve if this is an account related issue or any other cloud issue.

Thanks in advance!

**Comment by DeepikaBalaga** [comment]
Hi @womw ,  @kclchan ,  @mvelegon-amzn ,

Please let us know for any updates on this issue and confirm whether it's any account related issue or not.

Thanks!

**Comment by womw** [comment]
Hi @DeepikaBalaga  This issue is still under investigation

**Comment by DeepikaBalaga** [comment]
Hi team,

Thanks for the message.

I'm not sure about the issue as I left earlier organization. I'll surely
forward this email and let them know to reproduce the issue.

Best,
Deepika

**Comment by blazusiak-amazon** [comment]
Hello @DeepikaBalaga, 

Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
