### ISSUE TITLE
Give Resume command after pausing iheart radio artist station (e.g. Lady Gaga Station), song playback is restarted 

### ISSUE THREAD

**Issue by skd007** [alexa/avs-device-sdk#1771]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by skd007** [comment]
Expected behaviour. Song should be resumed.

**Comment by kclchan** [comment]
Hi @skd007, would you be able to try it on the latest version (v1.20) of the SDK?  If it's still reproducible, could you attach the DEBUG9 logs so we can further investigate the issue.  Thanks.

**Comment by skd007** [comment]
Hi , I won't be able to try on lastest SDK version. After using default SDK 1.14 code without any changes to 
bool MediaPlayer::queryIsSeekable(bool* isSeekable) in MediaPlayer.cpp file.
Seek() works fine for Heart radio and song is resumed. 
But seek for other CP's like Amazon Music and Audible fails with message getseekSimple failed.

**Comment by caleighatamazon** [comment]
Hi @skd007 , thanks for the information. Can you please attach the DEBUG9 logs where you reproduce this issue on 1.14?

**Comment by caleighatamazon** [comment]
I'm going to close this to inactivity, but please re-open a new issue with the DEBUG9  logs if this continues to be a problem.
