### ISSUE TITLE
Adding function to SDK issue

### ISSUE THREAD

**Issue by shao-estone** [alexa/avs-device-sdk#1772]
I'm trying to call a function under one of control handler.  in this case I added another class called test.cpp which print out a line on console when it's called.

I'm calling this method in PeripheralEndpointModeControllerHandler, under where it would do ConsolePrint::perttyPrint.

I have my cpp and header in the right path, have all the includes. modified the CMakeLists.txt
however it still seems like some linking issue.  Please let me know what I'm missing.

the following is the error:

[ 88%] Built target acsdkDefaultSampleApplicationOptions
[ 88%] Built target acsdkDoNotDisturb
[ 88%] Built target AIP
[ 90%] Built target acsdkAlerts
[ 93%] Built target AVSSystem
[ 93%] Built target DefaultClient
[100%] Built target LibSampleApp
[100%] Linking CXX executable SampleApp
libLibSampleApp.so: undefined reference to `alexaClientSDK::sampleApp::test::printingtest()'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:146: recipe for target 'SampleApp/src/SampleApp' failed
make[3]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:13670: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
CMakeFiles/Makefile2:13682: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:3319: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

**Comment by kclchan** [comment]
Hi @shao-estone, based on the error, it seems that you are not correctly modifying the CMakeLists.txt file to include your new test.cpp source file in a way that the libLibSampleApp.so is able to find the symbols.  Please note that this question is outside the scope of the SDK and I would recommend you to look into a [cmake tutorial](https://cmake.org/cmake/help/git-stage/guide/tutorial/index.html).  Thanks.
