### ISSUE TITLE
Alexa goes offline after a while  when device is at idle status

### ISSUE THREAD

**Issue by jiekesanguo** [alexa/avs-device-sdk#1773]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Alexa goes offline every other hour, it was always in idle state.

## What is the expected behavior?
Alexa should be online if the network was good

## What behavior are you observing?
this is the log fragment, the connection between the client and the server is broken, Please refer to the attachment for details
2020-08-04 16:50:08.842 [ 7c] 9 HTTP2MimeResponseDecoder:onResponseFinished:status=COMPLETE
2020-08-04 16:50:08.842 [ 7c] 9 MimeResponseSink:onResponseFinished:status=COMPLETE
2020-08-04 16:50:08.842 [ 7c] 5 DownchannelHandler:onResponseFinished:status=COMPLETE,nonMimeBody=
2020-08-04 16:50:08.842 [ 7c] 7 HTTP2Transport:onDownchannelFinished
2020-08-04 16:50:08.843 [ 7c] 5 HTTP2Transport:setStateLocked:newState=SERVER_SIDE_DISCONNECT,changedReason=SERVER_SIDE_DISCONNECT

### What version of the AVS Device SDK are you using?
      <1.19.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
openwrt  linux 4.4.25
[20200804-device-01.log](https://github.com/alexa/avs-device-sdk/files/5030440/20200804-device-01.log)

**Comment by scotthea-amazon** [comment]
Hello @jiekesanguo,

Periodic SERVER_SIDE_DISCONNECTs are expected, typically around every 50-55 minutes.  The client should automatically create a new connection.  Looking at your log that appear to be what is going on.

Best regards,
-SWH

**Comment by kclchan** [comment]
Hi @jiekesanguo, I am going to close this issue now.  Please feel free to create a new issues if you have new questions.  Thanks!

**Comment by tinypancake** [comment]
> Hello @jiekesanguo,
> 
> Periodic SERVER_SIDE_DISCONNECTs are expected, typically around every 50-55 minutes. The client should automatically create a new connection. Looking at your log that appear to be what is going on.
> 
> Best regards,
> -SWH

Hello @scotthea-amazon 

If the SERVER_SIDE_DISCONNECT appears in about 1min, and then it will reconnect to cloud, and the device always shows offline in the Alexa app. What will cause this issue?

**Comment by tinypancake** [comment]
Hello @ scotthea-amazon
If the SERVER_SIDE_DISCONNECT appears in about 1min, and then it will reconnect to cloud, and the device always shows offline in the Alexa app. What will cause this issue?
