### ISSUE TITLE
Alert volume functionality confirmation.

### ISSUE THREAD

**Issue by cameled** [alexa/avs-device-sdk#1775]
## Briefly summarize your issue:
I found after avs-device-sdk v1.18, if there is content playing, such as music, and the system volume is higher than the alert volume, the alert **will not** plays at the system volume level. Is that alert volume functionality adjustment?

Related document: https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/ux-design-attention.html#alarms-and-timers

## What behavior are you observing?
When music is playing, then timer/alarm starts actively. UIManager will receive an Alert volume changed notification, but there's no change for the alert volume.

## Provide the steps to reproduce the issue, if applicable:
1. Set speaker volume to 5
2. Set alert volume to 1.
3. Play music.
4. Set a timer for 5 seconds.
5. UIManager will receive alert volume changed event when timer active. (There's no change for alert volume)

### What version of the AVS Device SDK are you using?
      avs-device-sdk v1.20

### Tell us what hardware you're using:
- [ *] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @cameled , thanks for reporting this issue. I agree with you that this looks to be a bug. I'll create an internal ticket tracking this issue.
