### ISSUE TITLE
portaudio issue

### ISSUE THREAD

**Issue by bhandarisandeep** [alexa/avs-device-sdk#1776]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am getting the portaudio.h : no such file or directory error after running the "make -j4" command in the sdk-build directory

## What is the expected behavior?
the code should compile properly and the user should be able to run the "make install"

## What behavior are you observing?
i am getting these errors:

```
In file included from /home/b0x/sdk_folder/avs-device-sdk/SampleApp/src/SampleApplication.cpp:51:0:
/home/b0x/sdk_folder/avs-device-sdk/SampleApp/include/SampleApp/PortAudioMicrophoneWrapper.h:24:23: fatal error: portaudio.h: No such file or directory
compilation terminated.
SampleApp/src/CMakeFiles/LibSampleApp.dir/build.make:350: recipe for target 'SampleApp/src/CMakeFiles/LibSampleApp.dir/SampleApplication.cpp.o' failed
make[2]: *** [SampleApp/src/CMakeFiles/LibSampleApp.dir/SampleApplication.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:12992: recipe for target 'SampleApp/src/CMakeFiles/LibSampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/LibSampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

```

## Provide the steps to reproduce the issue, if applicable:
after installing the dependencies in the directory as mentioned in the Amazon alexa AVS docs, i tried to compile the project files
and i was getting these errors

## Tell us about your environment:
i am using an ubuntu flavored "back-box" environment. 
 
### What version of the AVS Device SDK are you using?
      v1.20.0

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @bhandarisandeep , thanks for posting. Can you please make sure you installed portaudio?

```
 cd ${PATH_TO_YOUR_THIRDPARTY_DEPENDENCIES}
 wget -c http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
 tar xf pa_stable_v190600_20161030.tgz

 cd portaudio
 ./configure --without-jack && make
```
You will also need to ensure when you build the SDK that you use the following cmake arguments (along with whatever other arguments you used):
```
...
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=${PATH_TO_PORTAUDIO}/portaudio/lib/.libs/libportaudio.so \
-DPORTAUDIO_INCLUDE_DIR=${PATH_TO_PORTAUDIO}/portaudio/include \
...
```

These instructions can be found under the "Ubuntu" tab in our Linux instructions (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/linux.html). There is a documentation bug in our "Generic Linux" tab where the Portaudio instructions are missing, which may lead to the error you see here where Portaudio is not found! We will fix that bug soon.
.

Please let me know if you have other questions or if my instructions aren't clear.

**Comment by mvelegon-amzn** [comment]
Hi @bhandarisandeep Closing this issue as we haven't heard back from you. The issue with portaudio.h file not being found can be fixed by building port audio and using the cmake commands mentioned by @caleighatamazon above. Please open a new issue if you have trouble compiling the SDK.
