### ISSUE TITLE
[es-US]Alexa server reply SUCCESS_NO_CONTENT but the audio is good

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1778]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

I use DIAGNOSTICS audio inject mode to test es-US. 
It seems the es-US "bucle" command couldn't recognize by alexa cloud server.

> 
2020-08-13 02:14:26.925 [ 21] 0 AudioInputProcessor:onSendCompleted:status=SUCCESS_NO_CONTENT
2020-08-13 02:14:26.925 [ 21] 0 AudioInputProcessor:resetState:dueToStatus=SUCCESS_NO_CONTENT

Test audio from our prep-process audio. 
[ufb_00_esUS.wav.tar.gz](https://github.com/alexa/avs-device-sdk/files/5072080/ufb_00_esUS.wav.tar.gz)

Log:
[avs_debug9_es_US.log](https://github.com/alexa/avs-device-sdk/files/5072064/avs_debug9_es_US.log)

Here is my device history
![image](https://user-images.githubusercontent.com/2118320/90199446-66429b80-de07-11ea-8f74-f62e82010a7d.png)

Here is one of audio file download from device history. It seems the audio is good and clear to hear "bucle"
[playOption.wav.tar.gz](https://github.com/alexa/avs-device-sdk/files/5072102/playOption.wav.tar.gz)

## Briefly summarize your issue:

Expect the alexa cloud could recognize the es-US command "loop" 

## What is the expected behavior?

When we do AQT es-US testing. The alexa server couldn't recognize "bucle" command.
It will cause test fail 

## What behavior are you observing?

The audio is already send to server successfully and the audio content is clear to hear "bucle"

## Provide the steps to reproduce the issue, if applicable:

1.Build AVS with DIAGNOSTICS audio inject mode
2.Change es-US locale by 'c' -> '1' -> '9'
3.Use ufb_00_esUS.wav.tar.gz audio to start test by 'o' -> 'a' -> '1' and type absolute path of the wav file

### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @yuan0258 , a few questions for you:
1. Does audio injection work for other audio files you've recorded? Is this the only one you have a problem with?
2. Can you try recording a different audio file of "bucle" to see if that works?
3. Did you build the SDK with wakeword enabled, or no?

**Comment by yuan0258** [comment]
Hi @caleighatamazon ,
1. Yes. It could work with other audio files. Yes. in other language such as en-US is ok to trigger alexa,loop mode

2. Here is another audio file it works. The first "alexa,bucle" is copy from previous one. The second "alexa,bucle" is used other text to speech method to produce. The third 
audio files
[ufb_mic33dB_mic_esUS.zip](https://github.com/alexa/avs-device-sdk/files/5081618/ufb_mic33dB_mic_esUS.zip)
![ufb_mic33dB_mic_esUS_audio](https://user-images.githubusercontent.com/2118320/90347631-33e1aa00-e064-11ea-8ff7-7134b8e260b7.png)
log:
[ufb_mic33dB_mic_esUS.log](https://github.com/alexa/avs-device-sdk/files/5081616/ufb_mic33dB_mic_esUS.log)
device history:
![ufb_mic33dB_mic_esUS_device_history](https://user-images.githubusercontent.com/2118320/90347648-422fc600-e064-11ea-9e19-6affcb27a23a.png)

3.Yes. I build the sdk with pryonlite wakeword(2.4.4)

**Comment by mvelegon-amzn** [comment]
Hi @yuan0258 I think this is a cloud issue and we will route it internally to the right team. Could you share the audio file where "bucle" was not being recognized so that we can reproduce it locally?

**Comment by yuan0258** [comment]
@mvelegon-amzn ,

You could use this audio file to reproduce it 
https://github.com/alexa/avs-device-sdk/files/5072102/playOption.wav.tar.gz

**Comment by womw** [comment]
Hello @yuan0258 
I tested on my SampleApp and was able to have bucle recognized by Alexa. Is it this specific audio file that you are having trouble getting recognized? Can you unblock by using a new recording of bucle or does all of your bucle recordings fail?

**Comment by yuan0258** [comment]
@womw 
Could you try the audio file ufb_00_esUS.wav.tar.gz which I attach in https://github.com/alexa/avs-device-sdk/issues/1778#issue-678818094?

The fail result show shown by device history

**Comment by yuan0258** [comment]
@womw,

Do you have any hint about this issue?

**Comment by caleighatamazon** [comment]
If other recordings of "bucle" work, then the issue is not with language recognition but likely with the quality of that one particular audio file. My recommendation is that you use one of the audio files you have of "bucle" that work for audio injection. Please let us know if that's not possible.

**Comment by yuan0258** [comment]
@caleighatamazon,

The orignal recordings of "bucle" is from AQT es-US testing. 
It couldn't not change the test audio file during AQT testing.
We observe those three language(es-US/es-MX/es-ES) using the same AQT test audio file to start playback testing.
The es-MX has same problem.
The es-ES could reginize correctly.
Maybe there some hint for you

**Comment by yuan0258** [comment]
Finally we report this issue to AQT team. They reproduce the new audio files to resolve this problem
The key problem is when keyword and command is speak by different people. I will cause cloud recognize command fail by keyword trigger case
If it use Push-to-talk to feed same data to cloud. The result is same
