### ISSUE TITLE
Illegal Instruction while running Alexa Sample App on raspberry pi zero W

### ISSUE THREAD

**Issue by oopyaephyo** [alexa/avs-device-sdk#1780]
i am getting an error when i try to run SampleApp.

pi@raspberrypi:~/sdk-folder/sdk-build $ PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
configFile ./Integration/AlexaClientSDKConfig.json
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: ETXBMF       #
################################################################################################

#################################################
#       Checking for authorization (1)...       #
#################################################

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
#################################################
#       Checking for authorization (2)...       #
#################################################

Illegal instruction

**Comment by mvelegon-amzn** [comment]
Hi @oopyaephyo Thanks for reaching out. The issue you are seeing does not appear to be an SDK related issue. It seems like an issue with microphone or audio on the Raspberry Pi you are using.

Please ensure you follow the instructions mentioned here:
- https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html
- https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/troubleshooting.html

Here are links to old SDK issues with the same problem:
- https://github.com/alexa/avs-device-sdk/issues/780
- https://github.com/alexa/avs-device-sdk/issues/1682

Hope this helps.
