### ISSUE TITLE
Alexa not Speaking in Sepeakers

### ISSUE THREAD

**Issue by Jodaci** [alexa/avs-device-sdk#1786]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Alexa, Listen, Think, and Sepak on comand line, but there is no sound in my sepakers

## What is the expected behavior?

Alexa should Speak

## What behavior are you observing?

no audio outut from Alexa. even though i can listen to songs from youtube.

### What version of the AVS Device SDK are you using?

       Version 1.20.1 alexa-client-sdk 

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Raspbian Buster

Very Thanks for Help

**Comment by womw** [comment]
Hi @Jodaci thanks for posting.
Have you setup your raspberry pi according to the quick start guide https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html

It is important to install all dependencies and to configure ~/.asoundrc file. Also make sure that you build with portaudio.

**Comment by Jodaci** [comment]
Problem Issued,

I had problems with the ~/.asoundrc File, at the end like this

pcm.!default {
   type asym
    playback.pcm {
      type plug
      slave.pcm "hw:2,0"
    }
    capture.pcm {
      type plug
      slave.pcm "hw:3,0"
    }
 }

Look for de "hw:#,#" with comands **aplay -l** and **arecord -l**

I had issues with the gstreamer1.0-alsa too but replacing the existing audio_sink values in the MediaPlayer.cpp 

m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");

With the following audio_sink values

m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");

Now all works fine

Thanks
