### ISSUE TITLE
Alexa suddenly stop reading kindle book

### ISSUE THREAD

**Issue by dipalisb** [alexa/avs-device-sdk#1788]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have used the Pure AVS-SDK 1.17 to run the kiddle book. I give a command as "Ask Alexa to read kindle book.", Alexa read the book for about 3 seconds but suddenly stop. Alexa is getting aborted as shown below -
```
2020-09-03 05:30:20.705 [  c] 5 TemplateRuntime:handleRenderPlayerInfoDirective
2020-09-03 05:30:20.706 [  c] 9 DirectiveProcessor:processCancelingQueueLocked:size=0
Aborted 
```
I have collected the DEBUG9 logs ([kindle_logs.txt](https://github.com/alexa/avs-device-sdk/files/5167871/kindle_logs.txt)) for the testing.
I am facing this issue with English and Japanese language both.

Could you please tell why the Alexa is getting aborted while executing the kindle book commands.

## What is the expected behavior?
1) Alexa start to read Kindle book.
2) Alexa continue to read Kindle book without error

## What behavior are you observing?
Alexa read the book for about 3 seconds but suddenly stop. Then Alexa shows no reaction to wake word or action button until restarting the Alexa.

## Provide the steps to reproduce the issue, if applicable:
1) On DUT, set Alexa language as Japanese/English
2) Ask Alexa to read kindle book. (アレクサ、キンドルの本を読んで)
3) Wait for at least 10 seconds.

### What version of the AVS Device SDK are you using?
AVS-SDK 1.17

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Other - Android P

**Comment by alexandrekm-amzn** [comment]
hello @dipalisb  thank you for reporting this issue. This is a known issue and we will have a fix in the next release (1.21).
I'm closing this issue if the problem still persists with 1.21 please open a new ticket.
