### ISSUE TITLE
Can't configure default input device

### ISSUE THREAD

**Issue by ejlim81** [alexa/avs-device-sdk#1789]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, I tried running SampleApp from our board in development (Ubuntu18.04).
When I look at the log, it seems that the voice capture fails.
It seems to be a problem with the ALSA device configuration, but I don't know how to fix it.

## What is the expected behavior?

I want to configure ALSA to capture the voice properly.

## What behavior are you observing?

The wrong device is recognized as the default device and voice capture is attempted.

## Tell us about your environment:

Our board has one sound card, and I want to configure it to capture and playback audio.
 - capture : hw:0,2 playback: hw:0,0

**arecord -l**
**** List of CAPTURE Hardware Devices ****
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 0: CPU BE I2S0 snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 1: DSP HOSTLESS snd-soc-dummy-dai-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 2: DSP PDMMIC snd-soc-dummy-dai-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

 **aplay -l**
ubuntu@DQ1:~/my_project/build$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 0: CPU BE I2S0 snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 1: DSP HOSTLESS snd-soc-dummy-dai-1 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: lgedqb0sndcard [lge,dq-b0-snd-card], device 2: DSP PDMMIC snd-soc-dummy-dai-2 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

 **I made an $HOME/.asoundrc like this:**
```
pcm.!default {
        type asym
        capture.pcm "mic"
        playback.pcm "speaker"
}
pcm.mic {
        type plug
        slave {
                pcm "hw:0,2"
        }
}
pcm.speaker {
        type plug
        slave {
                pcm "hw:0,0"
        }
}
```

I tried to capture and play my voice using aplay and arecord, which worked fine.
```
arecord -t raw -r 16000 -f S16_LE -c 1 -d 5 111.pcm
aplay -t raw -r 16000 -f S16_LE -c 1 -B 1 111.pcm
```

I start Samplee App after enabled Portaudio log and I saw [default] device set as default input/output.
I don't know the [default] device come from.
```
before paHostApiInitializers[0].
ALSA version (build): 1.1.3
ALSA version (runtime): 1.1.3
BuildDeviceList: Ignoring ALSA plugin device [cards] of type [unknown]
BuildDeviceList: Found plugin [sysdefault] of type [unknown]
....
........
BuildDeviceList: Found plugin [spdif] of type [unknown]
BuildDeviceList: Found plugin [hdmi] of type [unknown]
BuildDeviceList: Found plugin [dmix] of type [unknown]
BuildDeviceList: Ignoring ALSA plugin device [dsnoop] of type [unknown]
BuildDeviceList: Found plugin [modem] of type [unknown]
BuildDeviceList: Found plugin [phoneline] of type [unknown]
BuildDeviceList: Ignoring ALSA plugin device [hw] of type [hw]
BuildDeviceList: Ignoring ALSA plugin device [plughw] of type [plug]
BuildDeviceList: Ignoring ALSA plugin device [plug] of type [plug]
BuildDeviceList: Ignoring ALSA plugin device [shm] of type [shm]
......
.........
BuildDeviceList: Found plugin [default] of type [asym]
BuildDeviceList: Found plugin [mic] of type [plug]
BuildDeviceList: Found plugin [speaker] of type [plug]
BuildDeviceList: Filling device info for 23 devices
FillInDevInfo: Filling device info for: lge,dq-b0-snd-card: - (hw:0,0)
2020-09-08 07:59:03.379 [  5] 9 LibCurlHttpContentFetcher:transferThread::end
2020-09-08 07:59:03.379 [  5] 9 LibCurlHttpContentFetcher:stateTransition:oldState=FETCHING_BODY,newState=BODY_DONE:State transition
GropeDevice: collecting info ..
GropeDevice: collecting info ..
Default input device: lge,dq-b0-snd-card: - (hw:0,0) hw:0,0
Default output device: lge,dq-b0-snd-card: - (hw:0,0)             --> eunjung: default input & output device added here.
FillInDevInfo: Adding device lge,dq-b0-snd-card: - (hw:0,0): 0
FillInDevInfo: Filling device info for: lge,dq-b0-snd-card: - (hw:0,1)
GropeDevice: collecting info ..
GropeDevice: collecting info ..
FillInDevInfo: Adding device lge,dq-b0-snd-card: - (hw:0,1): 1
FillInDevInfo: Filling device info for: lge,dq-b0-snd-card: - (hw:0,2)
GropeDevice: collecting info ..
GropeDevice: collecting info ..
FillInDevInfo: Adding device lge,dq-b0-snd-card: - (hw:0,2): 2
FillInDevInfo: Filling device info for: sysdefault
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
FillInDevInfo: Adding device sysdefault: 3
...
......
FillInDevInfo: Filling device info for: mic
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
FillInDevInfo: Adding device mic: 4
FillInDevInfo: Filling device info for: speaker
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
FillInDevInfo: Adding device speaker: 5
FillInDevInfo: Filling device info for: dmix
GropeDevice: collecting info ..
FillInDevInfo: Adding device dmix: 6
FillInDevInfo: Filling device info for: default
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
GropeDevice: collecting info ..
GropeDevice: Limiting number of plugin channels to 128
Default input device: default default
Default output device: default           --> eunjung: default input & output device added again.
FillInDevInfo: Adding device default: 7
```
Listening is displayed in the Sample App, so even if you input a voice, it goes to idle without any data captured on the log.  All of bytesRead was 0.

After modifying the PortAudioMicrophoneWrapper.cpp code to use PaDeviceIndex 2 arbitrarily in initialize() function, the voice was captured normally and I was able to talk with Alexa. (PaDeviceIndex 2 means hw: 0,2 as shown in Portaudio log)

**I want to know how to configure ALSA to use hw:0,2 as default input device.**

### What version of the AVS Device SDK are you using?
      <1.20.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ O] Other - tell us more:

### Tell us about your OS (Type & version):
- [O ] Linux - Ubuntu18.04
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @ejlim81,

Can you take a read through some of these resources and see if they can help resolve your problem?

- https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture#An_example_of_setting_default_device_using_%22defaults%22_node
- https://www.alsa-project.org/wiki/Asoundrc

**Comment by caleighatamazon** [comment]
Closed due to inactivity. Please open a new issue if this continues to be a problem.
