### ISSUE TITLE
Alexa Smart Screen RaspberryPi4 quick start guide install issue

### ISSUE THREAD

**Issue by CAG5** [alexa/avs-device-sdk#1795]
As of the last time that I reinstalled raspbian and started from scratch, my OS is whatever the raspberry pi had for the noobs full download as of this morning.  I am trying to install the Alexa Smart Screen SDK on my Raspberry Pi 4.  I make it all the way without any issues to step 9.  The second part of step 9 is the make portion of the code, upon completion I get the following errors and logfile (Attached Doc)
[Errors and log file.docx](https://github.com/alexa/avs-device-sdk/files/5219583/Errors.and.log.file.docx)

At this point of have completely erased and started from scratch at least 10 times in the past week, not to mention the countless retrys and fixes in between, so any help would be greatly appreciated.

**Comment by scotthea-amazon** [comment]
Hello @CAG5,

This is the wrong forum for this question.  Please re-post it to the [alexa-smart-screen-sdk](https://github.com/alexa/alexa-smart-screen-sdk) forum.

Best regards,
-SWH

**Comment by CAG5** [comment]
> Hello @CAG5,
> 
> This is the wrong forum for this question. Please re-post it to the [alexa-smart-screen-sdk](https://github.com/alexa/alexa-smart-screen-sdk) forum.
> 
> Best regards,
> -SWH

Will do, thank you.
