### ISSUE TITLE
Volume change / repeats last response

### ISSUE THREAD

**Issue by ereich1217** [alexa/avs-device-sdk#1798]
## Briefly summarize your issue:
When asking what volume Alexa is set to it will report volume and then repeat previous response.

## What is the expected behavior?
Only report volume.

## What behavior are you observing?
The previous response can be repeated several time.  It appears that if I continue for up to a minute from the initial joke it will eventually stop repeating the joke.

## Provide the steps to reproduce the issue, if applicable:
* "Alexa set volume 3", _Silence as expected_
* "Alexa tell me a joke", _Alexa tells a joke_
* "Alexa what is your volume?"  _"This device is at volume 3" (as expected), repeats joke (not expected)_
* "Alexa increase volume?"  _repeats joke (not expected)_
* "Alexa what is your volume?"  _"This device is at volume 4" (as expected), repeats joke (not expected)_
* "Alexa decrease volume?"  _repeats joke (not expected)_
* "Alexa what is your volume?"  _"This device is at volume 3" (as expected), repeats joke (not expected)_
* "Alexa set volume 4",  _repeats joke (not expected)_

## Tell us about your environment:
I first discovered this issue on an embedded Linux device, but found that it also happens on the Amazon Echo dot or the Mac.

**Comment by caleighatamazon** [comment]
Hello @ereich1217 , I am able to reproduce this. I'll file an internal ticket to track this defect. Thanks for reporting it!

**Comment by caleighatamazon** [comment]
@ereich1217 , I have one more question for you. What version of the SDK did you reproduce this on?

**Comment by ereich1217** [comment]
I reproduced it on 1.18 and 1.20.
