### ISSUE TITLE
can't play kindle book

### ISSUE THREAD

**Issue by Guoina** [alexa/avs-device-sdk#1801]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
Can't play kindle book.

## Briefly summarize your issue:

when I say "alexa, play kindle book",the sampleApp responds book's name  then it  does not read any book but just replay " something went wrong". This account didn't play any kindle books before with SDK-1.17。 Now SDK-1.20 this problem happens.
And When change another account which can read kindle books normally with SDK-1.17, it can  normally read books on  SDK 1.20.

## What is the expected behavior?

it can play kindle books 
## What behavior are you observing?

can't not read kindle book. It syas "something went wrong"
## Provide the steps to reproduce the issue, if applicable:

just say "play kindle books"
### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
 Other - tell us more:
linux with crossed compile

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @Guoina, can you please reproduce the problem and capture DEBUG9 logs?  Thanks!

**Comment by Guoina** [comment]
[alexa.log](https://github.com/alexa/avs-device-sdk/files/5302630/alexa.log)
I capture DEBUG9 logs  of sdk_1.20  for this problem. please handle it .

**Comment by kclchan** [comment]
HI @Guoina, thanks for the log file.  In the log file, it seems there's no AudioPlayer.Play directive to play the book so it seems to be a cloud issue.  I have filed an internal ticket to investigate further.  Thanks!

**Comment by Guoina** [comment]
@kclchan Thanks for your reply and I really respect the resolution of this issue.

**Comment by kclchan** [comment]
Hi @Guoina, we just got a response that the issue is fixed already.  Could you try again and see if you can still reproduce this?  If it's still a problem, please attach the latest DEBUG9 log.  Thanks!

**Comment by Guoina** [comment]
Hi @kclchan,  the issue is solved perfectly and thanks for your response very much.
