### ISSUE TITLE
Spotify doesn't work with the AVS on a Raspberry Pi.

### ISSUE THREAD

**Issue by likithh** [alexa/avs-device-sdk#1809]
## Briefly summarize your issue:
I installed the AVS Service on my Raspberry Pi 2B with a USB Mic and a network adaptor, but when I try to play music through spotify it says, Spotify isn't available on this device. I've tweaked with all the settings in the Amazon Alexa App on my Android Device.

## What is the expected behavior?
It was supposed to play music through Spotify
## What behavior are you observing?
It says the device isn't supported for Spotify.

### What version of the AVS Device SDK are you using?
      <1.18.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- Raspberry Pi 
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
-  Raspberry Pi Desktop Environment
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by alexandrekm-amzn** [comment]
hi @likithh 
A Spotify adapter is required to support Spotify with the SDK. If you're ready to integrate Spotify into your product, reach out to your Amazon point of contact to get started.

if you do not yet have an Amazon point of contact, I recommend using the contact form on the Amazon Developer Portal: https://developer.amazon.com/support/contact-us
