### ISSUE TITLE
How can I get current notification state after reboot?

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#181]
Hi,
    I can receive SetIndicator Directive in my app to indicate that I get a notification message, then to play sound cue and light LED; but If I reboot my device, how can I get the last notification state? I want to show the user that there have some unread notifications when APP start running. 
 Thanks!

**Comment by kjkh** [comment]
Hi,
We will officially support Notifications in a future release.

For your custom implementation, you'll need some sort of storage mechanism to persist the notification state into and retrieve it upon restart. 

The Alerts Capability Agent follows a similar design pattern, and uses an SQL database for its storage. There are additional complexities with Alerts that aren't applicable to Notifications, but it can serve as a good reference.

**Comment by boyce-xx** [comment]
@kjkh ,
Got it.
Thanks for your reply.
