### ISSUE TITLE
Raspberry Pi 4 Sound issue. Headphone-Jack does not work

### ISSUE THREAD

**Issue by Sirpercal** [alexa/avs-device-sdk#1811]
I've try the get the sound output thru the 3.5mm analog jack using Raspberry PI Desktop interface as well as using sudo raspi-config but nothing worked. All the other apps played sound thru the analog jack except Alexa

## What is the expected behavior?
We should have the choice to select the sound output device from the desktop interface.

## What behavior are you observing?
The sound output always go thru the HDMI device.

## Provide the steps to reproduce the issue, if applicable:
Simply install the avs-device-sdk using the instructions provided by Amazon AVS web site.

### What version of the AVS Device SDK are you using?
      <1.20.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ X] Raspbian Buster
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by alexandrekm-amzn** [comment]
hello @Sirpercal 
Thanks for reaching out, to be able to help you I'm going to ask you to try a few things: 

1) make sure your asoundrc is configured like this: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#set-up-the-microphone
2) set the environment variable 'export PA_ALSA_PLUGHW=1'
3) Edit your AlexaClientSDKConfig.json to instruct gstreamer to use alsa sink https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html#set-up-your-configuration-file    (Add an audioSink to AlexaClientSDKConfig.json)

You can use this command 'gst-launch-1.0 audiotestsrc ! alsasink' to help you to debug the issue (it will play a tone through the speaker)


If that doesn't solve the issue please run the Sample app with DEBUG9 and attach the logs here.

**Comment by gelaw2** [comment]
This fixed my sound issue.  Thanks
