### ISSUE TITLE
V1.20.0 first time playing Spotify music from Spotify App does not play TTS "connect spotify"

### ISSUE THREAD

**Issue by keying-linkplay** [alexa/avs-device-sdk#1816]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When using the latest sdk v1.20.0 with enable Spotify Patch, playing music from Spotify App the device does not play the TTS "connect spotify", and this issue is not happened on avs device sdk v1.18.0. we find that the AVS Spotify Api changed. from the old api: The TTS will received from this API  **ExternalMediaPlayer.Login**

## What is the expected behavior?

when first time play Spotify music from Spotify App, it does not play "connect spotify" TTS

## What behavior are you observing?

when first time play Spotify music from Spotify App, it will play "connect spotify" TTS

## Provide the steps to reproduce the issue, if applicable:

1. after the device initialize, open Spotify app
2. find the device from Spotify App, then connect the device
3. play some music from Spotfy App

### What version of the AVS Device SDK are you using?
avs device sdk: v1.20.0
spotify patch: Spotify-1.20.tar.gz

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ * ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ * ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @keying-linkplay,

Due to the nature of the issue, can you please reach out through your Amazon Business Representative and we can debug this using a separate communication channel.

**Comment by keying-linkplay** [comment]
OK
