### ISSUE TITLE
Is there a plan to support bluez under android system, or there are other ways to support bluetooth capabilityAgent under andriod？

### ISSUE THREAD

**Issue by xlb767923274** [alexa/avs-device-sdk#1818]
Hi @syedfaisal5 we do not support blueZ on Android platform currently. We only support BlueZ for Ubuntu and Raspberry Pi. I will be closing this ticket, please let us know if you have any other questions.

_Originally posted by @mvelegon-amzn in https://github.com/alexa/avs-device-sdk/issues/1698#issuecomment-624940039_

**Comment by kjkh** [comment]
Hi @xlb767923274,

For feature requests, please submit an inquiry to avs-device-sdk@amazon.com.
