### ISSUE TITLE
Android SDK Build

### ISSUE THREAD

**Issue by Carmelo1966** [alexa/avs-device-sdk#1819]
Hello. I want to build the SDK for Android to use it from an Android App.
1) I registered a new product as Android App in the developer console, so I've got my Client ID, Client Secret, Security Profile ID and the API key. But I cannot find any config.json file to download.
2) I setted up a Linux machine to build the SDK following the guide "Set up the AVS Device SDK on Android". But how can I run the android.sh script without the config.json file? Maybe that the config.json is only needed for a device with Alexa built in but is not mandatory for an Android App?
3) Can I find somewhere the SDK already packaged as aar library?
4) I cannot find any example of an Android app. All the links in many post lead to a page not found error. So can you tell me where to find some additional documentation and examples  to use the SDK from Android Studio?
Thank you

**Comment by kjkh** [comment]
Hi @Carmelo1966,

1, 2: Please follow https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/register-a-product.html#set-up-your-avs-security-profile for instructions on generating the config file. The file is needed to run the AVS SDK.
3. We do not currently distribute any prebuilt binaries.
4. We do not currently support this feature. The extent of Android support can be found at this guide (https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html), which it appears you are currently following. If you are interested in having this feature, please submit a request to: avs-device-sdk@amazon.com.

**Comment by kclchan** [comment]
Closing this as all the questions have been answered.  Please feel free to open a new ticket if you have further questions.
