### ISSUE TITLE
SpeechRecognizer Interface Audio Format 

### ISSUE THREAD

**Issue by baytechlovr** [alexa/avs-device-sdk#182]
I see that you have hard coded the audio input interface - 
    16bit Linear PCM
    16kHz sample rate
    Single channel
    Little endian byte order
My audio microphone does not support it and I am connecting a microphone directly to the pi which gives me 32 bit 32KHz , do u have support for that or how i can do it ? 

Thanks in advance .

**Comment by mradulan** [comment]
AVS will be parsing the binary data as LPCM16. All captured audio sent to AVS should be encoded as:
16bit Linear PCM (LPCM16)
16kHz sample rate
Single channel
Little endian byte order

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/speechrecognizer

We do not have any support for other formats. You will have to externally convert it to LPCM16 before passing it to pi.

**Comment by kclchan** [comment]
Closing the issue now.  Please re-open if you need more information.  Thanks!
