### ISSUE TITLE
using the pointer after std::move

### ISSUE THREAD

**Issue by keying-linkplay** [alexa/avs-device-sdk#1821]
After std::move(); the mrmCapabilityAgent will become to nullptr, so the line 243 is a issue:

https://github.com/alexa/avs-device-sdk/blob/6840059a1023ff97a841c08c2f32b2f15036bd48/SampleApp/src/ExternalCapabilitiesBuilder.cpp#L237

https://github.com/alexa/avs-device-sdk/blob/6840059a1023ff97a841c08c2f32b2f15036bd48/SampleApp/src/ExternalCapabilitiesBuilder.cpp#L243

**Comment by kjkh** [comment]
Hi @keying-linkplay,

Thanks for pointing this out, this will be fixed.

**Comment by kjkh** [comment]
Are you seeing any segfaults related to this on shutdown?

**Comment by keying-linkplay** [comment]
sometimes will segfault, not always.

**Comment by kjkh** [comment]
Thanks for the information. This has been added to our backlog and will be resolved in an upcoming release.
