### ISSUE TITLE
Alexa-Spotify and BT music play issue

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1822]
## Briefly summarize your issue:
BT music does not stop when music plays from the Spotify app and Speaker(TREBL) plays BT music and after changing song Speaker(TREBL) continues with Spotify connect and disconnect BT.

 **Actual Result getting**
BT music does not stop when music plays from the Spotify app and TREBL plays BT music.

## What is the expected behavior?
BT music should stop when users play music from Spotify Connect.
PFA.

## What behavior are you observing?
BT music does not stop when music plays from the Spotify app and TREBL play BT music and after changing song TREBL continues with Spotify connect and disconnect BT.

## Provide the steps to reproduce the issue, if applicable:
1. Connect App with TREBL and configure Wi-Fi.
2. Configure Wi-Fi and BT.
3. Play music using Spotify connect.
4. Connect BT with TREBL and Play music.
5. Spotify still connected with TREBL but music paused on Spotify connect.
6. Now resume Spotify connect.
7. Music starts steaming on Spotify connect but TREBL still playing music from BT.
8. When a song change or the user interacts with Spotify then TREBL plays Spotify music.

## Tell us about your environment:
Linux
Alexa SDK: avs-device-sdk-1.18
Alexa adapter: Spotify-1.8.1.tar.gz
Spotify adapter: spotify_embedded-playapi-v3.20d-SPRINT_TREBL-linux_armv7hf-32bit-Release.tar.gz

### What version of the AVS Device SDK are you using?
      avs-device-sdk-1.18

### Tell us what hardware you're using:
Linux-Ubuntu 16.04

### Tell us about your OS (Type & version):
 Linux

**Comment by Alexa-AUH** [comment]
[alexa.txt](https://github.com/alexa/avs-device-sdk/files/5465383/alexa.txt)
[ExternalMediaPlayerAdapters_json.txt](https://github.com/alexa/avs-device-sdk/files/5465392/ExternalMediaPlayerAdapters_json.txt)
[AlexaClientSDKConfig_json.txt](https://github.com/alexa/avs-device-sdk/files/5465393/AlexaClientSDKConfig_json.txt)

**Comment by kjkh** [comment]
Hi @Alexa-AUH,

Due to the nature of the issue, please reach out through your Amazon Business Representative to further debug the problem. I will be closing this ticket.
