### ISSUE TITLE
Alexa-Spotify music is streaming automatically after connection established.

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1823]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Music is streaming automatically when the Spotify app having a paused track is connected to Sprint TREBL.

## What is the expected behavior?
Whenever Spotify connects with Alexa-Spotify integrated SDK, then Spotify should get connected and do not starts playing music on the connected device automatically.

## What behavior are you observing?
Whenever the Spotify app connects with Alexa-Spotify integrated SDK, then Spotify starts playing music on the connected device (Sprint TREBL).

## Provide the steps to reproduce the issue, if applicable:

   1. Link Spotify account with Alexa.
   2. Open Spotify app.
    3. Play music on Spotify app. (Output should be from phone)
    4. Now pause the track.
    5. Now connect with Sprint-TREBL.
    6. Observe that music is streaming automatically when Spotify app having paused track is connected to Sprint TREBL.

## Tell us about your environment:
Linux
Alexa SDK: avs-device-sdk-1.18
Alexa adapter: Spotify-1.8.1.tar.gz
Spotify adapter: spotify_embedded-playapi-v3.20d-SPRINT_TREBL-linux_armv7hf-32bit-Release.tar.gz

### What version of the AVS Device SDK are you using?
  avs-device-sdk-1.18

### Tell us what hardware you're using:
  Linux-Ubuntu 16.04

[alexa.txt](https://github.com/alexa/avs-device-sdk/files/5465377/alexa.txt)

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by kjkh** [comment]
Hi @Alexa-AUH,

Due to the nature of the issue, please reach out through your Amazon Business Representative to further debug the problem. I will be closing this ticket.
