### ISSUE TITLE
Sending location to AVS : alexa-auto-sdk

### ISSUE THREAD

**Issue by bijumens** [alexa/avs-device-sdk#1825]
I have a query related to sending location to AVS. Currently I'm working with integration of Alexa into a Head Unit. 

**Issue:** When device location is turned OFF, we are sending Location as null expecting that Alexa will pick up the user's location from his/her amazon account. But this doesn't seem the right way to do as aace is throwing an error :
_AACE_JNI: aace.jni.alexa.LocationProviderBinder:getLocation:invalidLocation_

**Question: What value should be passed to AVS if there is no location to be shared so that Alexa will pick up the user's location from their amazon account.**

Platform: Android API 27 (Android 8.1)
AlexaAutoSDK Version : 2.2.0

**Comment by scotthea-amazon** [comment]
Hello @bijumens,

This is a question for the Automotive SDK.  Please see their page for getting help: https://github.com/alexa/alexa-auto-sdk/blob/3.0/NEED_HELP.md

Best regards,
-SWH

**Comment by scotthea-amazon** [comment]
Closing this issue since it is not specific to avs-device-sdk.
