### ISSUE TITLE
Error Re-building Sample App

### ISSUE THREAD

**Issue by lilyt86** [alexa/avs-device-sdk#1826]
## Briefly summarize your issue:
**Hi**

I am trying to rebuild Alexa on "Raspberry pi 4" using this Instructions: https://developer.amazon.com/it-IT/docs/alexa/alexa-voice-service/indicate-device-state-with-leds.html

**as soon as I give the command** : sudo bash setup.sh config.json
**gives me this error** :

[ 88%] Built target acsdkDoNotDisturb

[ 88%] Built target acsdkCore

[ 90%] Built target acsdkAlerts

[ 90%] Built target acsdkDefaultSampleApplicationOptions

[ 90%] Built target acsdkLibcurlAlexaCommunications

[ 93%] Built target DefaultClient

[ 97%] Built target LibSampleApp

[100%] Built target LibPreviewAlexaClient

[100%] Linking CXX executable PreviewAlexaClient

/usr/bin/ld: ../../../SampleApp/src/libLibSampleApp.so: undefined reference to `digitalWrite'

collect2: error: ld returned 1 exit status

make[3]: *** [applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/build.make:149: applications/acsdkPreviewAlexaClient/src/PreviewAlexaClient] Error 1

make[2]: *** [CMakeFiles/Makefile2:4473: applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/all] Error 2

make[1]: *** [CMakeFiles/Makefile2:4485: applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/rule] Error 2

make: *** [Makefile:1163: PreviewAlexaClient] Error 2

**Can you help me please.**

## What is the expected behavior?

**at the end of programming I should talk to alexa and be able to observe the response and listening LEDs light up**

## What behavior are you observing?

**alexa does not finish programming and therefore goes into total lockdown**

## Provide the steps to reproduce the issue, if applicable:

**you need to follow the guide**
https://developer.amazon.com/it-IT/docs/alexa/alexa-voice-service/indicate-device-state-with-leds.html

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi 4 Model B
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [x] Raspbian buster
- [ ] Other - tell us more:

**Comment by ereich1217** [comment]
It looks like you skipped a step in changes to your cmake files.  The error you are getting is that the linker doesn't know where to find the library.

**Here is the part you seem to have missed:**
For the final step, you'll need to make a change to the CMake file in order for the project to use the WiringPi library when you rebuild the Sample App. Open the file “CMakeLists.txt” from the same home/pi/avs-device-sdk/SampleApp/src folder and add target_link_libraries(SampleApp "-lwiringPi") at the bottom of the file as shown.

**Comment by lilyt86** [comment]
the code: target_link_libraries(SampleApp "-lwiringPi")

has been correctly inserted as described in the guide.
I also tried to do it all over again, paying much more attention.
the result is the same

![Alexa Cmakelist](https://user-images.githubusercontent.com/57452133/98354827-8b6b3280-2021-11eb-9156-82a29ec5b6e4.jpg)

**Comment by scotthea-amazon** [comment]
@lilyt86,

Have you tried removing the "-l" from the line?  For example:

    target_link_libraries(SampleApp "wiringPi")

Do you know the path to wiringPi?  If so, you might also try specifying the path.  i.e.:

    target_link_libraries(SampleApp "<absolute_path>/wiringPi")

Best regards,
-SWH

**Comment by aamirasmal** [comment]
i have exactely the same problem i try to change target_link_libraries(SampleApp "wiringPi")  but he did'nt work 

Can you help please 

Thank you

**Comment by kclchan** [comment]
Hi @lilyt86 and @aamirasmal, could you try this instead:

```
target_link_libraries(LibSampleApp "-lwiringPi")
```

**Comment by aamirasmal** [comment]
@kclchan

 ​target_link_libraries(LibSampleApp "-lwiringPi")

I have try this code because this line is the official code so he didd'nt work

Thanks you

Have a nice day

**Comment by lilyt86** [comment]
@scotthea-amazon 
**with this line**: target_link_libraries(SampleApp "wiringPi")
**i have this response**:

[100%] Linking CXX executable PreviewAlexaClient
/usr/bin/ld: ../../../SampleApp/src/libLibSampleApp.so: undefined reference to `digitalWrite'
collect2: error: ld returned 1 exit status
make[3]: *** [applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/build.make:149: applications/acsdkPreviewAlexaClient/src/PreviewAlexaClient] Error 1
make[2]: *** [CMakeFiles/Makefile2:4473: applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4485: applications/acsdkPreviewAlexaClient/src/CMakeFiles/PreviewAlexaClient.dir/rule] Error 2
make: *** [Makefile:1163: PreviewAlexaClient] Error 2

**and I'm sorry but I don't know how to set this line**: target_link_libraries(SampleApp "<absolute_path>/wiringPi")
**I only know the GPIO from which the signal comes out but I don't know how to set it within the code**

**Comment by aamirasmal** [comment]
@lilyt86  il have thé samedi answer

**Comment by kclchan** [comment]
HI @aamirasmal and @lilyt86, please note that the suggestion I provided earlier is different from the guide.  In the guide, it's
```
target_link_libraries(SampleApp "-lwiringPi")
```

But I would like you to try the below instead:
```
​target_link_libraries(LibSampleApp "-lwiringPi")
```

Please note the difference between `SampleApp` and `LibSampleApp`.  Thanks!

**Comment by lilyt86** [comment]
**with this line**: ​target_link_libraries(LibSampleApp "-lwiringPi")

**the error is different**:

Adding CapabilityAgent AIP
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent Alexa
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent ApiGateway
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent InteractionModel
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent PlaybackController
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent SoftwareComponentReporter
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent SpeakerManager
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent SpeechSynthesizer
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent System
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Adding CapabilityAgent TemplateRuntime
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Please fill /home/pi/build/Integration/AlexaClientSDKConfig.json before you execute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
CMake Error at SampleApp/src/CMakeLists.txt:150:
  Parse error.  Expected a command name, got unquoted argument with text
  "​target_link_libraries".

-- Configuring incomplete, errors occurred!
See also "/home/pi/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:194: cmake_check_build_system] Error 1

pi@raspberrypi:~/build/SampleApp $

**Comment by aamirasmal** [comment]
@kclchan @scotthea-amazon @lilyt86 

i have the same error  

can i help you please

Thank you

Have a nice day

**Comment by kclchan** [comment]
Hi @lilyt86, I am surprised you are getting a Parse error with by adding target_link_libraries(LibSampleApp "-lwiringPi") to your CMake.  Please note that target_link_libraries is a cmake command (https://cmake.org/cmake/help/latest/command/target_link_libraries.html) that is trying add the wiringPi dependency to LibSampleApp.  Could you share in more details your modification in CmakeLists.txt?

For everyone else, could you try to add in [here](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/CMakeLists.txt#L139) 
```
 target_link_libraries(LibSampleApp "-lwiringPi")
```

**Comment by aamirasmal** [comment]
@kclchan   @lilyt86 

THANK YOU !!!!!!!!!!!!!!

you have reason my sdk was complete thank you very much

**Comment by lilyt86** [comment]
thank you so much @kclchan
I have now completed my SDK.
but I have other problems @aamirasmal can I contact you in pvt for a comparison of our SDKs?

**Comment by aamirasmal** [comment]
@lilyt86  

Yes

**Comment by aamirasmal** [comment]
@lilyt86  

I am new on GitHub you Can contact me on Instagram  

My account is

aamirasmal15

Because il didn't find the. Private communication
