### ISSUE TITLE
Spotify Alarm and normal alarm play at the same time

### ISSUE THREAD

**Issue by keying-linkplay** [alexa/avs-device-sdk#1827]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

when I set only one spotify alarm, when the time is arrived, at first the spotify start play. but after about 30 seconds
the normal alarm also start play. This issue also happened on device sdk v1.20.0.

## What is the expected behavior?

When set a Spotify Alarm, it need only play the spotify music, needn't play the normal alarm sound

## What behavior are you observing?

Spotify Alarm and normal alarm play at the same time

## Provide the steps to reproduce the issue, if applicable:

1. wake me up to songs from spotify at 4:51 am
2. when the alarm fired, it start play spotify music, but after 30 seconds a normal alarm sound start play.

### What version of the AVS Device SDK are you using?
 avs device sdk:     v1.18.0
 SpotifyAdapter:    1.18

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ * ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ * ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
@keying-linkplay,

Thank you for bringing this to our attention!

Would you please attach a full DEBUG9 level log to this issue, so that we can get a better idea of what is happening in your particular environment?

Best regards,
-SWH

**Comment by keying-linkplay** [comment]
[spotify-alarm-error.txt](https://github.com/alexa/avs-device-sdk/files/5507741/spotify-alarm-error.txt)

**Comment by keying-linkplay** [comment]
[Uploading spotify-alarm-issue.log…]()

**Comment by keying-linkplay** [comment]
[spotify-alarm-issue.txt](https://github.com/alexa/avs-device-sdk/files/5508048/spotify-alarm-issue.txt)

**Comment by keying-linkplay** [comment]
@scotthea-amazon  and this issue is easy to reproduce, 100% can reproduce by using v1.18.0 with Spotify patch 1.18.  by the way the esdk version is: v3.114.42

**Comment by keying-linkplay** [comment]
and if I set a prime music alarm, and it works well, analysis the the log: when the alarm arrived server will send the AudioPlay.Play directive to device, and when the device send the event AudioPlay.PlaybackStarted to server. server will
send a Alerts.DeleteAlert to device to delete the current alarm.

**Comment by keying-linkplay** [comment]
[amazon-music-alarm.txt](https://github.com/alexa/avs-device-sdk/files/5509264/amazon-music-alarm.txt)

**Comment by kclchan** [comment]
Hi @keying-linkplay, 

Please re-try with the latest version of the SDK.  And due to the nature of the issue, please reach out through your Amazon Business Representative to further debug the problem. I will be closing this ticket.
