### ISSUE TITLE
setup.sh> pi.sh: line 36: pip: command not found

### ISSUE THREAD

**Issue by mincequi** [alexa/avs-device-sdk#1828]
##  Briefly summarize your issue:
As of 2020/11//11 when i execute the setup.sh script, i got the issie pip: command not found.
Apparently, python-pip is not installed as dependency. 

## What is the expected behavior?
setup.sh runs without issues.

## What behavior are you observing?
setup.sh -> pi.sh prints error: line 36: pip: command not found

## Provide the steps to reproduce the issue, if applicable:
> sudo bash setup.sh config.json

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [X] Raspbian Buster
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @mincequi, thanks for reporting this.  Could you make a change on [line 36](https://github.com/alexa/avs-device-sdk/blob/master/tools/Install/pi.sh#L36) in pi.sh to use 'pip3' instead of 'pip' and see if this resolves the error?

**Comment by mincequi** [comment]
Yes, that solves this issue.

**Comment by kclchan** [comment]
Thanks for reporting this issue.  We will fix this in a future release.  Thanks!
