### ISSUE TITLE
Alexa wake word is not working

### ISSUE THREAD

**Issue by sumiitsaxena** [alexa/avs-device-sdk#1830]
## Briefly summarize your issue:
I installed Alexa SDK as described on amazon.com. Everything works well, just that "Alexa" wakeword is not detected.

## What is the expected behavior?
It should wake up with wake word "Alexa"

## What behavior are you observing?
It works when I enter "T"+Enter. But wake word is not working

## Tell us about your environment:
I installed SDk on raspberry Pi4 with latest raspbian buster OS.

### Tell us what hardware you're using:
- Raspberry Pi4

### Tell us about your OS (Type & version):
- Raspbian buster latest

**Comment by kclchan** [comment]
Hi @sumiitsaxena, did you follow this guide [here](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html) and use the setup.sh script to install Alexa SDK?  If so, please attach the DEBUG9 log.

**Comment by sumiitsaxena** [comment]
Hello @kclchan yes I did use this guide and used exactly same command "sudo bash setup.sh config.json [-s 1234]"
1 strange thing I noticed is that after entering "AGREE", for sensory wakeword this is stated - 
"At some point, the SDK installation pauses and asks you to accept Sensory Wake Word terms and conditions — you must type yes to accept."

But for me I did not had to type "yes" at all. It installed normally.

Also, please guide me how to get DEBUG9 logs. Sorry I am a newbie in this. Hope you understand.

Thanks & Regards
Sumit

**Comment by lilyt86** [comment]
if installing alexa from scratch, it will always ask you to accept the Sensory Wake Word terms and conditions.
if, on the other hand, you try the same step several times, it will no longer ask you to accept them since you have already done so before.

regarding alexa's response when called. I have no idea why it doesn't work with official channels but I solved it by installing "**PulseAudio**" and changing the parameters

**Comment by sumiitsaxena** [comment]
Hello @lilyt86 
How did you install "PulseAudio" and  what parameters did you change in it?

Thanks
Sumit

**Comment by lilyt86** [comment]
i got the codes from this link: https://www.raspberrypi.org/forums/viewtopic.php?t=62851

after installing it you will find PulseAUdio in the preferences bar.
the parameters to be changed appear on the main screen **_ONLY_** when you call Alexa

**Comment by kclchan** [comment]
Hi @sumiitsaxena, could you try to delete your workspace and run the script from scratch?

**Comment by sumiitsaxena** [comment]
> Hi @sumiitsaxena, could you try to delete your workspace and run the script from scratch?

Hi @kclchan I am trying to deregister and delete the existing project. Deregister is successful still project is not getting deleted. It says a product is alredy registered to this project. I_ am not able to do this as well. :(

**Comment by lilyt86** [comment]
the project therefore the config.json file that generates amazon developer cannot be deleted but can be used N times on different Raspberry.
so i advise you to format your Rpi memory and install all over again and using the same config.json you already got earlier

**Comment by sumiitsaxena** [comment]
@lilyt86 oh ok, I have tried this 3-4 times, but same results.

**Comment by sumiitsaxena** [comment]
Anyone please help, I am not able to fix this issue

**Comment by caleighatamazon** [comment]
Hi @sumiitsaxena, can you delete the workspace where you ran the script? That means that you should no longer have a build directory, source directory, or anything else. There is no need to actually deregister the product. Instead, it would be easiest for you to start from scratch.

Basically, we would like you to start over with the setup script, as if you were running it for the first time.

Please be careful not to delete anything important -- we are only asking you to delete everything from your previous attempts at running the script.

After doing the above, if you run into the same problem, please run the app with DEBUG9 logging enabled and attach the logs as a separate file to this ticket.

**Comment by sumiitsaxena** [comment]
Hi @caleighatamazon I tried deleting workspace and re-run the commands, these are the new errors I am getting now.

pi@raspberrypi:~ $ sudo bash setup.sh config.json [-s 1234]
################################################################################
################################################################################


AVS Device SDK Raspberry pi Script - Terms and Agreements


The AVS Device SDK is dependent on several third-party libraries, environments, 
and/or other software packages that are installed using this script from 
third-party sources ("External Dependencies"). These are terms and conditions 
associated with the External Dependencies 
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that 
you need to agree to abide by if you choose to install the External Dependencies.


If you do not agree with every term and condition associated with the External 
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".


################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
CMake Error: The source directory "/home/pi/avs-device-sdk" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [Makefile:4226: cmake_check_build_system] Error 1

**Comment by sumiitsaxena** [comment]
Hi @caleighatamazon also, please guide me how to enable DEBUG9 logs?

**Comment by ereich1217** [comment]
How much space is on your SD card?

Can you copy the output starting with the **wget** commands all the way through where you get the error?  If you didn't edit your previous response there is something wrong with the script you are running, the OS, or the SD card.

wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh \
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/genConfig.sh \
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh

**Comment by sumiitsaxena** [comment]
Hello @ereich1217 SD card memory is 64 GB.
These command run successfully. Below are the prints on console.

Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Nov 18 08:28:18 2020
pi@raspberrypi:~ $ wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh
--2020-11-18 15:43:22--  https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8791 (8.6K) [text/plain]
Saving to: ‘setup.sh.2’

setup.sh.2                                   100%[=============================================================================================>]   8.58K  10.2KB/s    in 0.8s    

2020-11-18 15:43:24 (10.2 KB/s) - ‘setup.sh.2’ saved [8791/8791]

pi@raspberrypi:~ $ wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/genConfig.sh
--2020-11-18 15:43:24--  https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/genConfig.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7002 (6.8K) [text/plain]
Saving to: ‘genConfig.sh.2’

genConfig.sh.2                               100%[=============================================================================================>]   6.84K  6.27KB/s    in 1.1s    

2020-11-18 15:43:27 (6.27 KB/s) - ‘genConfig.sh.2’ saved [7002/7002]

pi@raspberrypi:~ $ wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh
--2020-11-18 15:43:30--  https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.56.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2875 (2.8K) [text/plain]
Saving to: ‘pi.sh.2’

pi.sh.2                                      100%[=============================================================================================>]   2.81K  --.-KB/s    in 0.001s  

2020-11-18 15:43:31 (2.75 MB/s) - ‘pi.sh.2’ saved [2875/2875]

pi@raspberrypi:~ $

**Comment by ereich1217** [comment]
Also, run the command "sudo bash setup.sh config.json" and include all of the output from that command.

**Comment by sumiitsaxena** [comment]
Hello @ereich1217 Below is the command output
pi@raspberrypi:~ $ sudo bash setup.sh config.json
################################################################################
################################################################################


AVS Device SDK Raspberry pi Script - Terms and Agreements


The AVS Device SDK is dependent on several third-party libraries, environments, 
and/or other software packages that are installed using this script from 
third-party sources ("External Dependencies"). These are terms and conditions 
associated with the External Dependencies 
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that 
you need to agree to abide by if you choose to install the External Dependencies.


If you do not agree with every term and condition associated with the External 
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".


################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
[ 33%] Built target AVSCommon
[ 35%] Built target SQLiteStorage
[ 35%] Built target SynchronizeStateSender
[ 38%] Built target acsdkManufactory
[ 40%] Built target RegistrationManager
[ 42%] Built target AudioResources
[ 45%] Built target Captions
[ 50%] Built target acsdkBluetooth
[ 50%] Built target acsdkEqualizerImplementations
[ 52%] Built target acsdkExternalMediaPlayerInterfaces
[ 54%] Built target acsdkNotifications
[ 54%] Built target acsdkNullMetricRecorder
[ 54%] Built target CBLAuthDelegate
[ 54%] Built target InterruptModel
[ 54%] Built target acsdkStartupManager
[ 54%] Built target AVSGatewayManager
[ 54%] Built target ContextManager
[ 54%] Built target acsdkShutdownManager
[ 59%] Built target ACL
[ 61%] Built target ADSL
[ 61%] Built target CaptionsComponent
[ 64%] Built target PlaylistParser
[ 64%] Built target KWD
[ 64%] Built target SystemSoundPlayer
[ 64%] Built target SpeechEncoder
[ 64%] Built target ApiGateway
[ 64%] Built target InteractionModel
[ 66%] Built target PlaybackController
[ 66%] Built target SoftwareComponentReporter
[ 66%] Built target SpeechSynthesizer
[ 66%] Built target TemplateRuntime
[ 69%] Built target SDKComponent
[ 71%] Built target MediaPlayer
[ 71%] Built target CertifiedSender
[ 71%] Built target Alexa
[ 73%] Built target acsdkAudioPlayer
[ 76%] Built target acsdkEqualizer
[ 76%] Built target acsdkExternalMediaPlayer
[ 76%] Built target acsdkSampleApplicationCBLAuthRequester
[ 78%] Built target AFML
[ 78%] Built target acsdkPostConnectOperationProviderRegistrar
[ 80%] Built target acsdkShared
[ 80%] Built target SENSORY
[ 83%] Built target Endpoints
[ 85%] Built target DeviceSettings
[ 85%] Built target KeywordDetectorProvider
[ 85%] Built target SpeakerManager
[ 85%] Built target acsdkDoNotDisturb
[ 88%] Built target CapabilitiesDelegate
[ 88%] Built target AIP
[ 90%] Built target AVSSystem
[ 92%] Built target acsdkAlerts
[ 92%] Built target acsdkCore
[ 92%] Built target acsdkDefaultSampleApplicationOptions
[ 95%] Built target DefaultClient
[100%] Built target LibSampleApp
[100%] Built target SampleApp
[ 31%] Built target AVSCommon
[ 34%] Built target SQLiteStorage
[ 34%] Built target SynchronizeStateSender
[ 36%] Built target acsdkManufactory
[ 38%] Built target RegistrationManager
[ 40%] Built target AudioResources
[ 43%] Built target Captions
[ 45%] Built target acsdkBluetooth
[ 47%] Built target acsdkEqualizerImplementations
[ 50%] Built target acsdkExternalMediaPlayerInterfaces
[ 52%] Built target acsdkNotifications
[ 52%] Built target CBLAuthDelegate
[ 52%] Built target acsdkStartupManager
[ 52%] Built target acsdkShutdownManager
[ 52%] Built target acsdkNullMetricRecorder
[ 52%] Built target acsdkSampleApplicationCBLAuthRequester
[ 52%] Built target InterruptModel
[ 52%] Built target acsdkPostConnectOperationProviderRegistrar
[ 52%] Built target AVSGatewayManager
[ 52%] Built target ContextManager
[ 56%] Built target ACL
[ 56%] Built target acsdkLibcurlHTTPContentFetcher
[ 59%] Built target PlaylistParser
[ 61%] Built target ADSL
[ 61%] Built target CaptionsComponent
[ 61%] Built target KWD
[ 61%] Built target SystemSoundPlayer
[ 61%] Built target SpeechEncoder
[ 61%] Built target ApiGateway
[ 61%] Built target InteractionModel
[ 63%] Built target PlaybackController
[ 63%] Built target SoftwareComponentReporter
[ 63%] Built target TemplateRuntime
[ 63%] Built target SpeechSynthesizer
[ 65%] Built target SDKComponent
[ 65%] Built target CertifiedSender
[ 65%] Built target Alexa
[ 68%] Built target acsdkEqualizer
[ 70%] Built target acsdkAudioPlayer
[ 70%] Built target acsdkCBLAuthorizationDelegate
[ 70%] Built target acsdkExternalMediaPlayer
[ 72%] Built target acsdkShared
[ 75%] Built target AFML
[ 75%] Built target SENSORY
[ 77%] Built target MediaPlayer
[ 79%] Built target Endpoints
[ 81%] Built target DeviceSettings
[ 84%] Built target acsdkDefaultInternetConnectionMonitor
[ 86%] Built target CapabilitiesDelegate
[ 86%] Built target acsdkGstreamerApplicationAudioPipelineFactory
[ 86%] Built target KeywordDetectorProvider
[ 86%] Built target AIP
[ 88%] Built target AVSSystem
[ 88%] Built target SpeakerManager
[ 88%] Built target acsdkDoNotDisturb
[ 88%] Built target acsdkCore
[ 90%] Built target acsdkAlerts
[ 90%] Built target acsdkDefaultSampleApplicationOptions
[ 90%] Built target acsdkLibcurlAlexaCommunications
[ 93%] Built target DefaultClient
[ 97%] Built target LibSampleApp
[100%] Built target LibPreviewAlexaClient
[100%] Built target PreviewAlexaClient

==============> SAVING CONFIGURATION FILE ==============

Completed generation of config file: /home/pi/build/Integration/tmp_AlexaClientSDKConfig.json

==============> FINAL CONFIGURATION  ==============

 {
    "gstreamerMediaPlayer":{
        "audioSink":"alsasink"
    },
    "cblAuthDelegate":{
        // Path to CBLAuthDelegate's database file. e.g. /home/ubuntu/Build/cblAuthDelegate.db
        // Note: The directory specified must be valid.
        // The database file (cblAuthDelegate.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for CBLAuthDelegate (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/cblAuthDelegate.db"
    },
    "deviceInfo":{
        // Unique device serial number. e.g. 123456
        "deviceSerialNumber":"123456",
        // The Client ID of the Product from developer.amazon.com
        "clientId":"amzn1.application-oa2-client.111b56646614404792bc64cb7aa55712",
        // Product ID from developer.amazon.com
        "productId":"RaspberryPi4",
        // The name of the device manufacturer.
        "manufacturerName": "Test Manufacturer",
        // The description of the device which should contain the manufacturer name or how the device is connected.
        "description": "Test Device"
    },
    "avsGatewayManager": {
        // Allows configuring the AVS Gateway the device should connect to.
        // Important Note: The AVSGatewayManager stores a previously verified gateway in the MiscDB and uses it
        // to establish a connection with AVS. In order to override the gateway configured here, you may have to
        // delete the AVSGatewayManager table under the MiscDB.
        // "avsGateway":"https://alexa.na.gateway.devices.a2z.com"
    },
    "capabilitiesDelegate":{
        // Path to misc database file. e.g. /home/ubuntu/Build/capabilitiesDelegate.db
        // Note: The directory specified must be valid.
        // The database file (capabilitiesDelegate.db) will be created by SampleApp, do not create it yourself.
        "databaseFilePath":"/home/pi/db/capabilitiesDelegate.db"
    },
    "miscDatabase":{
        // Path to misc database file. e.g. /home/ubuntu/Build/miscDatabase.db
        // Note: The directory specified must be valid.
        // The database file (miscDatabase.db) will be created by SampleApp, do not create it yourself.
        "databaseFilePath":"/home/pi/db/miscDatabase.db"
    },
    "alertsCapabilityAgent":{
        // Path to Alerts database file. e.g. /home/ubuntu/Build/alerts.db
        // Note: The directory specified must be valid.
        // The database file (alerts.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for alerts (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/alerts.db"
    },
    "deviceSettings":{
        // Path to Device Settings database file. e.g. /home/ubuntu/Build/deviceSettings.db
        // Note: The directory specified must be valid.
        // The database file (deviceSettings.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for device settings (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/deviceSettings.db",
        // The list of supported locales on this device.
        "locales":["en-US","en-GB","de-DE","en-IN","en-CA","ja-JP","en-AU","fr-FR","it-IT","es-ES","es-MX","fr-CA",
            "es-US", "hi-IN", "pt-BR"],
        // The default locale of this device.
        "defaultLocale":"en-US",
        // The list of locale combinations supported on this device.
        "localeCombinations":[
            ["en-US", "es-US"],
            ["es-US", "en-US"],
            ["en-IN", "hi-IN"],
            ["hi-IN", "en-IN"],
            ["fr-CA", "en-CA"],
            ["en-CA", "fr-CA"]
        ],
        // The default timezone of this device.  This is an optional parameter; if it isn't specified, Etc/GMT is set as
        // the default timezone.
        "defaultTimezone":"America/Vancouver"
    },
    "bluetooth" : {
        // Path to Bluetooth database file. e.g. /home/ubuntu/Build/bluetooth.db
        // Note: The directory specified must be valid.
        // The database file (bluetooth.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for bluetooth (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/bluetooth.db"
    },
    "certifiedSender":{
        // Path to Certified Sender database file. e.g. /home/ubuntu/Build/certifiedsender.db
        // Note: The directory specified must be valid.
        // The database file (certifiedsender.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for certifiedSender (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/certifiedSender.db"
    },
    "notifications":{
        // Path to Notifications database file. e.g. /home/ubuntu/Build/notifications.db
        // Note: The directory specified must be valid.
        // The database file (notifications.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for notifications (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/db/notifications.db"
    },
    "diagnostics":{
        // Flag for allowing tracing from SDK start up (By default, it's false)
        "protocolTraceFromStartup": false,
        // The maximum number of directive/event messages to store. If exceeded, additional messages will not be stored.
        "maxTracedMessages":1
    },
    "externalMediaPlayer": {
        // Agent identifier provided by AlexaMusic.
        // Developers creating their own adaptors must use an Agent ID assigned to them by Alexa Music
        "agentString": "CQCAFYNYDC"
    },
    "audioPlayer": {
        // To specify the number of MediaPlayer instances for AudioPlayer to use,
        // a value of '1' will result in limited pre-buffering:  It will buffer during introductory TTS, but not
        // the next track.
        // A value of '2' will allow next track buffering as well.  If multiple Play directives are expected to be enqueued,
        // at the same time, and the memory is available, a value of 3 or more will allow additional buffering.
        // The default is '2'.
        // "audioMediaPlayerPoolSize": 1
    },
    "sampleApp": {
        // To specify if the SampleApp supports display cards.
        "displayCardsSupported":true
        // The firmware version of the device to send in SoftwareInfo event.
        // Note: The firmware version should be a positive 32-bit integer in the range [1-2147483647].
        // e.g. "firmwareVersion": 123
        // The default endpoint to connect to.
        // See https://developer.amazon.com/docs/alexa/alexa-voice-service/api-overview.html#endpoints for regions and values
        // e.g. "endpoint": "https://alexa.na.gateway.devices.a2z.com"

        // Example of specifying suggested latency in seconds when openning PortAudio stream. By default,
        // when this paramater isn't specified, SampleApp calls Pa_OpenDefaultStream to use the default value.
        // See http://portaudio.com/docs/v19-doxydocs/structPaStreamParameters.html for further explanation
        // on this parameter.
        //"portAudio":{
        //    "suggestedLatency": 0.150
        //}
    }

    // Example of specifying output format and the audioSink for the gstreamer-based MediaPlayer bundled with the SDK.
    // Many platforms will automatically set the output format correctly, but in some cases where the hardware requires
    // a specific format and the software stack is not automatically setting it correctly, these parameters can be used
    // to manually specify the output format.  Supported rate/format/channels values are documented in detail here:
    // https://gstreamer.freedesktop.org/documentation/design/mediatype-audio-raw.html
    //
    // By default the "autoaudiosink" element is used in the pipeline.  This element automatically selects the best sink
    // to use based on the configuration in the system.  But sometimes the wrong sink is selected and that prevented sound
    // from being played.  A new configuration is added where the audio sink can be specified for their system.
    // "gstreamerMediaPlayer":{
    //     "outputConversion":{
    //         "rate":16000,
    //         "format":"S16LE",
    //         "channels":1
    //     },
    //     "audioSink":"autoaudiosink"
    // },

    // Example of specifiying curl options that is different from the default values used by libcurl.
    // "libcurlUtils":{
    //
    //     By default libcurl is built with paths to a CA bundle and a directory containing CA certificates. You can
    //     direct the AVS Device SDK to configure libcurl to use an additional path to directories containing CA
    //     certificates via the CURLOPT_CAPATH setting.  Additional details of this curl option can be found in:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_CAPATH.html
    //     "CURLOPT_CAPATH":"INSERT_YOUR_CA_CERTIFICATE_PATH_HERE",
    //
    //     You can specify the AVS Device SDK to use a specific outgoing network interface.  More information of
    //     this curl option can be found here:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html
    //     "CURLOPT_INTERFACE":"INSERT_YOUR_INTERFACE_HERE"
    // },

    // Example of specifying a default log level for all ModuleLoggers.  If not specified, ModuleLoggers get
    // their log level from the sink logger.
    // "logging":{
    //     "logLevel":"INFO"
    // },

    // Example of overriding a specific ModuleLogger's log level whether it was specified by the default value
    // provided by the logging.logLevel value (as in the above example) or the log level of the sink logger.
    // "acl":{
    //     "logLevel":"DEBUG9"
    // },

    // // Example for specifiying the Template Runtime display card timeout values.
    // "templateRuntimeCapabilityAgent": {
    //     // If present, shall override the default timeout for clearing the RenderTemplate display card when SpeechSynthesizer is in FINISHED state.
    //     "displayCardTTSFinishedTimeout": 2000,
    //     // If present, shall override the default timeout in ms for clearing the RenderPlayerInfo display card when AudioPlayer is in FINISHED state.
    //     "displayCardAudioPlaybackFinishedTimeout": 2000,
    //     // If present, shall override the default timeout in ms for clearing the RenderPlayerInfo display card when AudioPlayer is in STOPPED or PAUSED state.
    //     "displayCardAudioPlaybackStoppedPausedTimeout": 60000
    // }

    // // The equalizer function allows you to adjust equalizer settings, such as decibel (dB) levels and modes.
    // // By default, the equalizer is enabled. The default settings are:
    // // * `"enabled":true`. By default, the equalizer is active.
    // // * All `"bands"` are active: `BASS`, `MIDRANGE`, `TREBLE`.
    // // * "modes" are disabled. See below for more information.
    // // * Minimum band level (`"minLevel"`): -6 dB
    // // * Maximum band level (`"maxLevel"`): +6 dB
    // // * Default state (defaultState): All "bands" are set to 0dB, and no "mode" is active.

    // "equalizer": {
    //     // Enables or disables the equalizer. Setting this value to `false` will disable the equalizer locally, and report to AVS that it is disabled.
    //     "enabled": true,
    //     // The equalizer bands supported by the device. Currently, there are only three available options: `BASS`, `MIDRANGE` and `TREBLE`.
    //     // By default, all bands are enabled. However, if you specify a band or bands, then only those will be supported.
    //     // bands will be supported.
    //     "bands": {
    //         "BASS": true,
    //         "MIDRANGE": true,
    //         "TREBLE": true
    //     },
    //     // The equalizer modes supported by the device. AVS doesn't define specific behavior for modes,
    //     // the `EqualizerModeControllerInterface` defines this behavior. AVS provides the following options for modes: "MOVIE", "MUSIC", "NIGHT",
    //     // "SPORT", "TV". By default, all modes are disabled (`false`), unless specifically marked as enabled (`true`).
    //     "modes": {
    //         "NIGHT": false,
    //         "MOVIE": false,
    //         "MUSIC": false,
    //         "SPORT": false,
    //         "TV": false
    //     },
    //     // The equalizer factory settings. These default values are used for a newly registered device, or when a user requests that Alexa reset a band.
    //     "defaultState": {
    //         // The default mode to be applied. When no default mode is desired, set the `"mode"` value to `"NONE"`, which is a custom value.
    //         "mode": "NONE",
    //         // Defines band level defaults (integer dB)
    //         "bands": {
    //             "BASS": 0,
    //             "MIDRANGE": 0,
    //             "TREBLE": 0
    //         }
    //     },
    //     // Minimum value an equalizer band could have (integer dB).
    //     "minLevel": -6,
    //     // Maximum value an equalizer band could have (integer dB).
    //     "maxLevel": 6,
    //     // Default delta value to adjust the equalizer band (integer dB).
    //     "defaultDelta": 1
    // }

    // Example of setting the minUnmuteVolume level in SpeakerManager
    // "speakerManagerCapabilityAgent": {
    //     // If present, shall override the default minUnmuteVolume value that the device restores to when unmuting
    //     // at volume level 0.
    //     // "minUnmuteVolume": 10
    // }

 }


// Notes for logging
// The log levels are supported to debug when SampleApp is not working as expected.
// There are 14 levels of logging with DEBUG9 providing the highest level of logging and CRITICAL providing
// the lowest level of logging i.e. if DEBUG9 is specified while running the SampleApp, all the logs at DEBUG9 and
// below are displayed, whereas if CRITICAL is specified, only logs of CRITICAL are displayed.
// The 14 levels are:
// DEBUG9, DEBUG8, DEBUG7, DEBUG6, DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, DEBUG0, INFO, WARN, ERROR, CRITICAL.

// To selectively see the logging for a particular module, you can specify logging level in this json file.
// Some examples are:
// To only see logs of level INFO and below for ACL and MediaPlayer modules,
// -  grep for ACSDK_LOG_MODULE in source folder. Find the log module for ACL and MediaPlayer.
// -  Put the following in json:

// "acl":{
//  "logLevel":"INFO"
// },
// "mediaPlayer":{
//  "logLevel":"INFO"
// }

// To enable DEBUG, build with cmake option -DCMAKE_BUILD_TYPE=DEBUG. By default it is built with RELEASE build.
// And run the SampleApp similar to the following command.
// e.g. ./SampleApp /home/ubuntu/.../AlexaClientSDKConfig.json /home/ubuntu/KittAiModels/ DEBUG9"
 **** Completed Configuration/Build ***
pi@raspberrypi:~ $

**Comment by mvelegon-amzn** [comment]
Can you post full DEBUG9 logs which shows that wake word is not detected?

**Comment by mvelegon-amzn** [comment]
Also, can you post the command you used to run the SampleApp?

**Comment by sumiitsaxena** [comment]
Hello @mvelegon
Command I used is - 
sudo bash startsample.sh

Can you please guide me on how to take Debug9 logs?

**Comment by mvelegon-amzn** [comment]
@sumiitsaxena When you run the above script, there should be logs printed on the console, can you capture the output in a file and attach it here?

**Comment by sumiitsaxena** [comment]
@mvelegon-amzn I have pasted out here itself in my above reply. Please check if you can check and resolve the issue. 
Thanks in advance.
Sumit Saxena

**Comment by sumiitsaxena** [comment]
Anyone please help with this issue!!!

**Comment by caleighatamazon** [comment]
Hi @sumiitsaxena , we need DEBUG9 logs to proceed further -- we can't tell what is going wrong with your app right now.

Please reproduce the problem (where wakeword isn't detected) by running the app:

`sudo bash startsample.sh`

When you run that command, logs should be printed to the console. Can you capture that output and attach it as a file to the issue?

**Comment by sumiitsaxena** [comment]
Hi @caleighatamazon 
I have attached the logs file.
Please check if you can analyze it for the issue.
[Uploading session.log…]()

**Comment by womw** [comment]
hi @sumiitsaxena looking through your logs I see that your SampleApplication does not connect to AVS.

```
2020-12-19 01:53:40.026 [  4] 9 InternetConnectionMonitor:testConnection::Finished reading
2020-12-19 01:53:40.026 [  4] 5 InternetConnectionMonitor:updateConnectionStatus:connected=false
2020-12-19 01:53:40.028 [  4] 9 LibCurlHttpContentFetcher:~LibCurlHttpContentFetcher
2020-12-19 01:53:40.077 [  2] E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=6,error=Couldn't resolve host name
```

Can you confirm that your raspberry pi is connected to the internet?

**Comment by sumiitsaxena** [comment]
Hi @womw 
Please check new attached logs
[session.log](https://github.com/alexa/avs-device-sdk/files/5747682/session.log)

**Comment by ereich1217** [comment]
Are you able to use aplay and arecord to play and record audio?

**Comment by sumiitsaxena** [comment]
@ereich1217 Yes I am able to use arecord and aplay

**Comment by kclchan** [comment]
Hi @sumiitsaxena, you mentioned that tap-to-talk is working for you (i.e press 't'), is that still the case?  If tap-to-talk is working for you, could you try to say Alexa more slowly (e.g. A-lex-xa) and see if it works?

**Comment by sumiitsaxena** [comment]
Hi @kclchan I tried speaking slowly, but it did not recognise it.
I think from logs I can see that it is not going in listening mode

**Comment by kclchan** [comment]
Hi @sumiitsaxena, does tap-to-talk (press 't' and say "What time is it") work for you?

**Comment by sumiitsaxena** [comment]
hello @kclchan yes as I already stated tap to talk works fine

**Comment by caleighatamazon** [comment]
Hi @sumiitsaxena , the logs you provided only cover about 4 seconds (from `2020-12-28 13:28:20.891` to `2020-12-28 13:28:24.221`). I can't tell exactly when you tried to wake up Alexa, especially since the session was only live for about two seconds after the app first became Authorized. 

Can you reproduce the problem and also demonstrate how tap-to-talk is working? If you could also give a timestamp of roughly when you tried to wake up Alexa, that would be helpful, too (then I could know where in the logs you tried to wake her up but no response).

Also, I see you're using SDK 1.21. Did earlier versions of the SDK work for you, or is this your first time using the SDK?

There is some troubleshooting advice given in the [Sensory wakeword Github repository](https://github.com/Sensory/alexa-rpi):
```
Verify that your audio configuration is suitable by running this command to make a ten second long audio recording:

arecord -d 10 -f S16_LE -r 16000 test.wav

Listen to the test recording and verify that it is clear: aplay test.wav
```

What happens when you try that and say "Alexa" on the recording? Is the test recording clear?

**Comment by djdocta** [comment]
All,
this has nothing to do with the installation steps. 
Amazon works with a third party for the wakeword recognition and its linked to a license. The license is valide up to 120 days and needs to get updated once this period is exceeded. In order to correct the issue, tap the following command in your home directory :

./third-party/alexa-rpi/bin/license.sh 

It will give you following result : 

ERROR: license expired on 10 Dec 2020 14:00:00 GMT
The Sensory TrulyHandsfree binaries license key has expired.
Pull from remote to update key? [yes or no]: yes

Once you see the above message, just answer with YES and you'll be good to go with Alexa :-)

**Comment by sumiitsaxena** [comment]
Hi @djdocta 
./third-party/alexa-rpi/bin/license.sh
Above command returned nothing. Please help. :-(

**Comment by djdocta** [comment]
Hi @sumiitsaxena  
If nothing is returned by the command, then it means that your license is still VALID (thats actually the normal behaviour).

**Comment by sumiitsaxena** [comment]
Hi @djdocta 
I can see from the logs when I run this sample app that Alexa is not going in "Listening..." mode.
What can be the issue? :(

**Comment by djdocta** [comment]
If its not even going on Listening mode, then your installation is wrong. 
Then it should not even work with the "T" + Enter.

**Comment by caleighatamazon** [comment]
I'm going to close this one due to inactivity. Please open a new issue with fresh logs and a description of the error if this is still a problem for you. Thanks!
