### ISSUE TITLE
Bluetooth Sink on Pi per default (or configurable)

### ISSUE THREAD

**Issue by mincequi** [alexa/avs-device-sdk#1831]
## Briefly summarize your issue:
Bluetooth sink disabled on Raspberry Pi per default.

To enable it, i installed libsbc-dev and edit pi.sh:30 and add the line
-DBLUETOOTH_BLUEZ=ON.

That'si t. Maybe we can enable this per default or add an option to pi.sh?
Maybe an official documentation would also help here.

## What is the expected behavior?
As a user of avs-device-sdk on raspberry pi, i want to have bluetooth sink capabilities enabled per default (or as an option to setup scripts).

### What version of the AVS Device SDK are you using?
      <1.21.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [X] Raspbian Buster
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @mincequi, thanks for your suggestion, I have created a ticket to our development backlog to have this looked into.  Please also note we have documentation on how to enable bluetooth here: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#bluetooth
