### ISSUE TITLE
Jack server is not running or cannot be started

### ISSUE THREAD

**Issue by shreyas-rc** [alexa/avs-device-sdk#1835]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @shreyas-rc , this issue does not contain any information. I am going to close it. Please open a new issue and fill out our  [Issue Reporting Guide](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/report-issue.html) if you want guidance.
