### ISSUE TITLE
v1.21.0 libDefaultClient.so and libADSL.so and libACL.so undefined references to alexaClientSDK

### ISSUE THREAD

**Issue by jcatumba** [alexa/avs-device-sdk#1836]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When I run make SampleApp -j2 the compilation goes well until almost 100% completed. After the [100%] Linking CXX executable SampleApp message, I got different messages of undefined references like:
* libDefaultClient.so undefined reference to alexaClientSDK::acl::AVSConnectionManager::createMessageSenderInterface
* libADSL.so undefined reference to alexaClientSDK::adsl::DirectiveProcessor::enable
* libACL.so undefined reference to alexaClientSDK::acl::DownchannelHandler::create

## What is the expected behavior?
Successful compilatio of SampleApp

## What behavior are you observing?
Undefined references on three libraries.

## Provide the steps to reproduce the issue, if applicable:
Execute make SampleApp -j2

### What version of the AVS Device SDK are you using?
      <1.21.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more: Ubuntu 20.10 for Raspberry Pi

**Comment by caleighatamazon** [comment]
Hi @jcatumba, can you build and run an earlier version of the SDK (say 1.20) on your platform, or is this specific to 1.21?

Are you using one of our setup scripts to build the SDK, or following one of our guides? If so, which one, and have you made any modifications?

**Comment by jcatumba** [comment]
Hi @caleighatamazon, I'm going to try to build the 1.20 version.

The guide I'm following is the one for [Ubuntu](https://developer.amazon.com/es-ES/docs/alexa/avs-device-sdk/ubuntu.html) since that the Raspberry Pi guide recomends Raspbian.

**Comment by jcatumba** [comment]
Hi @caleighatamazon, the build of v1.20.1 was successful. I managed to launch the SampleApp, and also see it on the Alexa App on my phone.

**Comment by mvelegon-amzn** [comment]
Hi @jcatumba can you post the cmake command you used with 1.21.0 version here so that I can try and reproduce this locally? Also, it would be helpful if you post the full build log along with all the commands you run. Thanks!

**Comment by jcatumba** [comment]
Hi @mvelegon-amzn. The cmake command was

    cmake $HOME/alexa/source/avs-device-sdk  -DGSTREAMER_MEDIA_PLAYER=ON  -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/alexa/third-party/portaudio/lib/.libs/libportaudio.so  -DPORTAUDIO_INCLUDE_DIR=$HOME/alexa/third-party/portaudio/include  -DCMAKE_BUILD_TYPE=DEBUG

I tried to clean up the build directory to get a clean log output for v1.21.0, but this time the built was successful.

**Comment by mvelegon-amzn** [comment]
@jcatumba Glad that worked. Will be closing this issue, please open a new issue if you need further assistance.
