### ISSUE TITLE
Raspberry OS 64-bit support

### ISSUE THREAD

**Issue by goldyfruit** [alexa/avs-device-sdk#1837]
Hi,

I'm trying to setup Alexa AI on my Raspberry Pi 4 using the Raspberry OS 64-bit but it failed during the installation because of Sensory which is not compiled to run on 64-bit OS.

Does Sensory is the only available option?
An issue has been opened on their repository for months now; https://github.com/Sensory/alexa-rpi/issues/10

Thanks :+1:

**Comment by caleighatamazon** [comment]
Hi @goldyfruit , at this time Sensory is our only supported open source wakeword engine. You can build the SDK and Sample App without wakeword, though. In that case you'd end up with a tap-to-talk Sample App.

To do so, you'll need to change the `pi.sh` script starting at line 24. Remove the existing `CMAKE_PLATFORM_SPECIFIC` definition and use this instead:
```
CMAKE_PLATFORM_SPECIFIC=(-DSENSORY_KEY_WORD_DETECTOR=OFF \
    -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON \
    -DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" \
    -DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include")
```

Then you'll need to delete your previous build directory and re-run the script.

**Comment by goldyfruit** [comment]
@caleighatamazon thanks for the alternative but not having a wake word is not a solution that I can use. :/
