### ISSUE TITLE
Raspberry-AVS

### ISSUE THREAD

**Issue by kccjazzman** [alexa/avs-device-sdk#1838]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Trying to install AVS on a raspberry pi  running Debian Buster     
 and getting the error when trying to run install script with following command:

sudo bash setup.sh config.json [-s 1234]
The installation script doesn't support current system. (System: Linux pi 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux)

I know others have run into the same problem but haven't seen a solution for Debian Buster.  Please advise.

Thanks

## What is the expected behavior?
Provided install script should install correctly

## What behavior are you observing?
Script giving above error.

## Tell us about your environment:
Running Linux Debian Buster VM on Window 10 Desktop Platform

### Tell us about your OS (Type & version):Static hostname: pi
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ee77245e33724dae94558e4e0c296588
           Boot ID: fe67fa98962648298fe630b1e7c3e2c4
    Virtualization: oracle
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-10-amd64
      Architecture: x86-64

**Comment by mvelegon-amzn** [comment]
Hi @kccjazzman We do not support this platform for pi. The setup.sh script is meant to be used on Raspbian OS.

Can you try using this Ubuntu wiki to setup the SDK: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html

**Comment by mvelegon-amzn** [comment]
Closing this issue as the pi running debian buster is not supported.
