### ISSUE TITLE
Sample Android application is not working.

### ISSUE THREAD

**Issue by akahay159** [alexa/avs-device-sdk#1840]
I have build Alexa auto sdk version 3 and when i was running android application to my phone, i was not getting any logs. It was a dunny application without any interaction. Can anyone help me what could be wrong in that?

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mvelegon-amzn** [comment]
Hi @akahay159 Thanks for reaching out. Regarding issues with Alexa Auto SDK, it would be better to get in touch with an Amazon Solution Architect to answer question. 

This forum is for issues regarding the AVS C++ SDK.
