### ISSUE TITLE
Failed to start sample application - Failed to open PortAudio - Raspberry Pi 

### ISSUE THREAD

**Issue by freemansoft** [alexa/avs-device-sdk#1845]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Built the sample using this guide https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html
Sample app fails to start on Raspberry Pi - messages imply microphone error
### Update after submission - 
* alexa-smart-screen works on the same Raspberry Pi built using https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html It clones this branch instead of using the scripts described on the page above ``` git clone --single-branch --branch v1.21.0 git://github.com/alexa/avs-device-sdk.git```

## What is the expected behavior?
Sample App should run

## What behavior are you observing?
Sample app fails to start
```
2020-12-06 16:00:30.744 [  1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9985
2020-12-06 16:00:30.744 [  1] C PortAudioMicrophoneWrapper:Failed to initialize PortAudioMicrophoneWrapper
```

Note that I did see the app run through the authorization block without pausing. That feels like a different issue
```
2020-12-06 16:10:58.600 [  3] 5 CBLAuthDelegate:setAuthError:authError=SUCCESS
##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: CV6JUE       #
################################################################################################

2020-12-06 16:10:58.601 [  3] 5 CBLAuthDelegate:handleRequestingToken
2020-12-06 16:10:58.602 [  3] 5 CBLAuthDelegate:requestToken
#################################################
#       Checking for authorization (1)...       #
#################################################

2020-12-06 16:10:58.603 [  1] 5 CaptionsComponent:createCaptionManagerInterface::captions disabled
```

## Provide the steps to reproduce the issue, if applicable:
1. Install sdk on Raspberry Pi
1. Build - USB microphone not plugged in during build
1. Verify microphone with `arecord -d 10 -f cd foo.wav` and `aplay foo.wav`
1. Run sample app

## Tell us about your environment:
1. Raspberry Pi 3 running without monitor or keyboard
1. AIY Voice Hat installed
1. Latest O/S installed - including Google voice
1. Logitech USB Rockband Microphone

`arecorde -l `
```
**** List of CAPTURE Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-codec-0 [Google voiceHAT SoundCard HiFi voicehat-codec-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: Microphone [Logitech USB Microphone], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

aplay -l
```
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-codec-0 [Google voiceHAT SoundCard HiFi voicehat-codec-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

`~/.asoundrc `
```
pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:0,0"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:1,0"
    }
}
``` 

### What version of the AVS Device SDK are you using?
*Master* as of 12/2020 - looks like 1.21

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Raspbian Buster
- [ ] Other - tell us more:

```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### Notes
Looked at AlexaClientSDKConfig.json and there was no `portAudio` section mentioned in https://github.com/alexa/avs-device-sdk/issues/842  .  Did not rebuild logging all portAudio devices as recommended in *842*

[SampleAppLog.txt](https://github.com/alexa/avs-device-sdk/files/5649093/SampleAppLog.txt)

**Comment by alexandrekm-amzn** [comment]
@freemansoft 
Thanks for reaching out, before I can help you further please try the instructions in this reply https://github.com/alexa/avs-device-sdk/issues/1811#issuecomment-716747992

If that doesn't solve your issue please run with DEBUG9 logs and attach them here.

Thanks!

**Comment by freemansoft** [comment]
Log files were attached to the original report.
Re-ran and attaching the log files here

Note that in the original report, I ran the SampleApp two different ways per the instructions on two different pages. It looks like both pages pull down the same avs-sdk repository but configure it subtly different.  One works and one doesn't. I wouldn't even care but the one that fails is the one that supports a wake word.

1. **Failed** Built and ran as in https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html - 
    1.  not this requires to run as sudo
    1.  Claims to work with wake words in logs
    1.  Created example with https://github.com/freemansoft/RaspberryPi/blob/master/alexa-voice-service-sdk-setup.sh
    1.  Ran example with https://github.com/freemansoft/RaspberryPi/blob/master/alexa-voice-service-sdk-run.sh
1. **Succeeded** Built and ran as  https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html  - 
    1.  does not run as sudo - 
    1.  must use buttons, wake word not enabled
    1.  Create example with https://github.com/freemansoft/RaspberryPi/blob/master/alexa-smart-screen-voice-sdk-setup.sh
    1.  Ran example https://github.com/freemansoft/RaspberryPi/blob/master/alexa-smart-screen-voice-sdk-run.sh

[SampleAppLog-2020-12-07.txt](https://github.com/alexa/avs-device-sdk/files/5656266/SampleAppLog-2020-12-07.txt)

**Comment by ereich1217** [comment]
For your Failed example I see you are running it with sudo.
I also see your post of ~/.asoundrc above which would only be used by the version that succeeded and isn't using sudo.
Did you confirm that your /root/.asoundrc is also correct?  This is the one that is used when you are running the app with sudo.

**Comment by freemansoft** [comment]
Good question.  
The configuration is in `/etc/asound.conf` and in `~/.asoundrc`. It didn't help.

As stated above, 
* The SDK set up as described in the smart screen guide _works_ for me.  
    *  Note: It pauses the program so I can authorize via https://www.amazon.com/a/code
* The SDK set up as described in the avs guide _does not work_ for me.  
    *  Note: It does not pause the SampleApp so I can authorize via https://www.amazon.com/a/code
    *  Not sure why the instructions say this has to run as sudo when the other version does not.

I was able to enable wake words by adding the sensory library to the smart screen example so I can continue my work.  
* Automated install scripts for both examples https://github.com/freemansoft/RaspberryPi
