### ISSUE TITLE
avs-device-sdk instructions and alexa -smart-screen-sdk instructions do not use the same folder

### ISSUE THREAD

**Issue by flashbif** [alexa/avs-device-sdk#1847]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
Are you aware that the avs device  sdk uses sdk-folder (dash), and the alexa smart screen sdk instructions use sdk_folder (underscore)?
Failed to create   SampleApplication! (#64)
Hi @flashbif,
Thanks a lot for reaching out to Alexa team. I am wondering if this is microphone issue:
2020-12-10 00:24:07.352 [ 1] C PortAudioMicrophoneWrapper:Failed to open PortAudio default stream:errorCode=-9985
2020-12-10 00:24:07.352 [ 1] C PortAudioMicrophoneWrapper:Failed to initialize PortAudioMicrophoneWrapper
2020-12-10 00:24:07.353 [ 1] C SampleApplication:Failed to create microphone wrapper!

From what you have mentioned, it looks like is a problem related to avs-device-sdk Sample App. Please file an issue with device sdk team: https://github.com/alexa/avs-device-sdk/issues
Thanks!

## Briefly summarize your issue:

Failed to create SampleApplication! #64 May be a microphone issue. I have tested the microphones and speakers.
-followed case 1841 and 1090. i don't know how to run patest1.
~/.asoundrc =
pcm.!default {
type asym
playback.pcm {
type plug
slave.pcm "hw:2,0"
}
capture.pcm {
type plug
slave.pcm "hw:2,0"
}
}
arecord and aplay work for both microphones
## What behavior are you observing?

Perhaps the card 2 device 0  not compatible with the instructions. The instruction show:
Will try to run patest1 as suggested by @visayamv in issue #1090 except use sdk_folder instead of sdk-folder.

pi@raspberrypi:~/sdk_folder/third-party/portaudio/bin $ ./patest1
patest1.c

## Provide the steps to reproduce the issue, if applicable:

Follow Alexa Smart Screen SDK through step 5. Step 6 https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html#step-6 failed. Reran after verifying arecord and aplay work

### What version of the AVS Device SDK are you using?
1.21.1

What version of the AVS Device SDK are you using?
1.21.0

Tell us what hardware you're using:
 Raspberry Pi 4 - version 10 (buster)
mini microphone on 3/0
webcam microphone on 2/0
analog speakers
Tell us about your OS (Type & version):
Raspian Buster

**Comment by alexandrekm-amzn** [comment]
Hi @flashbif 
Thanks for reaching out, before I can help you further please try the instructions in this reply https://github.com/alexa/avs-device-sdk/issues/1811#issuecomment-716747992

If that doesn't solve your issue please run with DEBUG9 logs and attach them here.

Thanks!

**Comment by flashbif** [comment]
1.pi@raspberrypi:/ $ nano ~/.asoundrc 
pcm.!default {
   type asym
   playback.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
   capture.pcm {
     type plug
      slave.pcm "hw:1,0"
   }
 }
2. pi@raspberrypi:/ $ sudo apt-get install sox -y && rec test.wav DEBUG9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sox is already the newest version (14.4.2+git20190427-1).
0 upgraded, 0 newly installed, 0 to remove and 190 not upgraded.
rec WARN alsa: can't encode 0-bit Unknown or not applicable
rec FAIL formats: can't open input file `test.wav': No such file or directory

**Comment by flashbif** [comment]
pi@raspberrypi:/ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 2: C920 [HD Pro Webcam C920], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:/ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3

**Comment by flashbif** [comment]
is the difference in folder locations (sdk-folder from this thread and sdk_folder from the smart-screen thread) messing me up?

**Comment by flashbif** [comment]
@caleighatamazon I have proceeded as far as I can without feedback. I followed #1811  as far as i can. Any suggestions?

**Comment by flashbif** [comment]
Ok, I reran the whole build process using the scripts. changed asoundrc to match my devices and was able to build sample app. there is debug response when using wake word and addition debug response when asking what time it is. I cannot hear Alexa's response. arecord and aplay work fine.

**Comment by flashbif** [comment]
@alexandrekm-amzn

**Comment by flashbif** [comment]
No help provided. Ap starts but no sound heard
