### ISSUE TITLE
fatal error: curl/curl.h: File or directory not found 

### ISSUE THREAD

**Issue by 0Wafflez0** [alexa/avs-device-sdk#1850]
## Briefly summarize your issue:
I wanted to make my own echo based on a Raspberry. So i used the instruction manual and got to work. I had to install a "Setup.sh" so i did but i got an error at the end.

## What behavior are you observing?
I got the error: https://pastebin.com/adH7CkUs

### Tell us what hardware you're using:
-  Desktop / Laptop (realVNC)
-  Raspberry Pi

### Tell us about your OS (Type & version):
- Raspbian Stretch

**Comment by womw** [comment]
Hi @0Wafflez0 thanks for posting,

Did you install the sdk using the install script? It should have installed curl
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html

You can also specify the location of curl with the following flags
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html

**Comment by phonnik** [comment]
I had the same issue. This solved it: `sudo apt-get install libcurl4-openssl-dev`

[https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory/11471743](url)

**Comment by 0Wafflez0** [comment]
> Hi @0Wafflez0 thanks for posting,
> 
> Did you install the sdk using the install script? It should have installed curl
> https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html
> 
> You can also specify the location of curl with the following flags
> https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/build-the-avs-device-sdk.html

ah yes i did it now with the install script. it works thx 👍 :D

**Comment by giorgosgs** [comment]
> 
> 
> I had the same issue. This solved it: `sudo apt-get install libcurl4-openssl-dev`
> 
> [https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory/11471743](url)

I had the same issue with the latest Buster and latest AVS SDK. I have run the install script but it didnt install curl.
This fixed it.

**Comment by tdididit** [comment]
sudo apt-get install libcurl4-gnutls-dev
