### ISSUE TITLE
Spotify-Alexa Resume song issue

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1852]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am using avs-device-sdk-1.18 Spotify ESDK Adapter-3.122.67 and Adapter v.1.8. Alexa. Spotify resumes from where it was left paused but Alexa says “What do you want me to Play?”.

## What is the expected behavior?
Spotify resumes the song from where it was left paused 8 hours ago.

## What behavior are you observing?
Instead of playing the paused song, Alexa says “What do you want me to Play?”

## Provide the steps to reproduce the issue, if applicable:
-	Alexa play Spotify
-	Alexa pause
-	After 8 to 10 hours Alexa resume

## Tell us about your environment:
avs-device-sdk-1.18
Spotify ESDK-3.122.67
Adapter v1.8

### What version of the AVS Device SDK are you using?
      avs-device-sdk-1.18

### Tell us what hardware you're using:
Linux-Ubuntu 16.04

### Tell us about your OS (Type & version):
- [x] Linux
[Resume_issue.zip](https://github.com/alexa/avs-device-sdk/files/5733667/Resume_issue.zip)

**Comment by kclchan** [comment]
Hi @Alexa-AUH, 

Due to the nature of the issue, can you please reach out through your Amazon Business Representative and we can debug this using a separate communication channel.  Thanks!
