### ISSUE TITLE
The specific TuneIn podcast playback is too slow to fail AQT Music performance

### ISSUE THREAD

**Issue by yuan0258** [alexa/avs-device-sdk#1853]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When playing or resume the program "Joe Rogan Experience" on TuneIn podcast, it needs the time to wait TuneIn to play in some time.
The time exceeds 13 seconds and above which not match AQT Music expected.
(Echo dot doesn't have this problem)

## What is the expected behavior?

TuneIn should be played less then 13 seconds.

## What behavior are you observing?

It needs to wait exceeds to 13 seconds to play some times.

## Provide the steps to reproduce the issue, if applicable:

1. Alexa, play the program Joe Rogan Experience on TuneIn.
2. (Alexa will response playing the program Joe Rogan Experience on Tune. Resuming....)
3. (wait TuneIn play)

Log:
[play_tunein_podcast_debug9.zip](https://github.com/alexa/avs-device-sdk/files/5734261/play_tunein_podcast_debug9.zip)

### What version of the AVS Device SDK are you using?
      <1.19.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hi @yuan0258 , this is an issue with TuneIn podcasts as they are downloaded from 0:00 and must buffer all the data up until the desired timestamp.

Some ways to ensure this test proceeds smoothly is to make sure you have a fast and stable internet connection to your device.

Another step to do is to make sure that AQT testing is done from the start of the podcast. You can do this by running the steps before proceeding with AQT testing

‘Alexa, play the Joe Rogan Experience’
(Alexa announces she is resuming the Joe Rogan experience, then the podcast starts.)
‘Alexa, restart’
(Alexa announces the start of the podcast, which starts)
‘Alexa, stop’

For more help please contact your amazon representative

**Comment by oscar1372** [comment]
Hi @womw , I follow your steps to setup the position of podcast before AQT TuneIn Podcast testing. There are two podcast "Joe Rogan Experience" and "Up First". It is improve for first time playing but still failed in the after.

I checked the report. It is failed for delayed when playing "Joe Rogan Experience" in the third time(No.27) due to timestamp. 
(RaspberryPi)
![image](https://user-images.githubusercontent.com/4708741/103075748-37370480-4607-11eb-8ec5-2f5230123b57.png)

I uses Echo dot to test same test case. it doesn't have the delayed problem. Does is it use difference way to download TuneIn podcast?
(Echo dot)
![image](https://user-images.githubusercontent.com/4708741/103076244-3d79b080-4608-11eb-9841-284b1ea0f967.png)

I will also provide this information to our amazon representative.

**Comment by oscar1372** [comment]
Hi @womw , Is it possible to use "Range" header to speed up the content downloading? 

I found gstreamer will return the offset bytes of seeking when resuming TuneIn podcast. (ex: AttachmentReaderSource:handleSeekData:offset=124415584)

And I check podcast response header, it is accept "Range" header. So, I think SDK should able to set "Range: bytes" header for content fetch to speed up when seeking. But UrlContentToAttachmentConverter can not update offset during content fetch.

If I want to use "Range" header in existing HTTP content fetch, I needs to modify flow of MediaPlayer and UrlContentToAttachmentConverter to support stop current and create new one with "Range" header.

Or maybe it has better way to implement.

**Comment by caleighatamazon** [comment]
Hi @oscar1372 , unfortunately what you propose isn't possible in the SDK right now. There's no directive to "resume", but rather the device would just get another PLAY directive with an offset, so we'd also need to put in some effort to see if it's even possible to use the last byte offset.

Implementing something like what you suggest constitutes a feature request, so I'll label this issue as such. I suggest you reach out to your Amazon business associate to continue the conversation if you'd like this feature request to be prioritized.

**Comment by caleighatamazon** [comment]
I'm going to close this due to inactivity. Please open a new issue or get in touch with your Amazon business contact if you want to ask for this feature to be prioritized.
