### ISSUE TITLE
./genConfig.sh syntax error

### ISSUE THREAD

**Issue by Sizuku2847** [alexa/avs-device-sdk#1858]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I get a Python configuration error

## What is the expected behavior?

Completed generation of config file:
Log appears

## What behavior are you observing?

./genConfig.sh: line 122: python: command not found

## Provide the steps to reproduce the issue, if applicable:

Occurs when you refer to the Startup Guide and perform step 4.5.b

## Tell us about your environment:

RaspberryPi 4 (Ubuntu 20.10)
PC(Ubuntu20.10)
See the URL below
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/ubuntu.html

### What version of the AVS Device SDK are you using?
      <1.21.0>

### Tell us what hardware you're using:
- [〇] Desktop / Laptop
- [〇] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [〇] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @Sizuku2847, based on the error, it seems Python is not installed in your system.  Please follow the instruction [here](https://docs.python-guide.org/starting/install3/linux/) to install.

**Comment by Sizuku2847** [comment]
Hi @kclchan ,I already have python on my system. But when I run the command, it doesn't work.

hiyori@hiyori-desktop:~$ python3 --version
Python 3.8.6

**Comment by kclchan** [comment]
Hi @Sizuku2847, the script uses `python` instead of `python3`.  Please follow the instruction [here](https://askubuntu.com/questions/1256996/i-cant-check-python-version-on-ubuntu-20-04) to use python3 as python.

**Comment by Sizuku2847** [comment]
Hi @kclchan , The program worked fine when I ran it exactly as you said. Thank you very much.
