### ISSUE TITLE
How to build the device sdk to auto sdk?

### ISSUE THREAD

**Issue by xiaocrazy** [alexa/avs-device-sdk#1859]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I want to change the code at "alexa-auto-sdk-2.3/builder/build/tmp-android-22/work/armv7a-neon-linux-androideabi/avs-device-sdk/1.19.1-r0/avs-device-sdk-1.19.1/KWD/AmazonLite/src" in auto sdk,but we just can build the so file,how to make build effictive in auto sdk when we run the sampleapp.apk
## What is the expected behavior?

When we change the code at "alexa-auto-sdk-2.3/builder/build/tmp-android-22/work/armv7a-neon-linux-androideabi/avs-device-sdk/1.19.1-r0/avs-device-sdk-1.19.1/KWD/AmazonLite/src" in auto sdk,it can not be effictive
## What behavior are you observing?

When we add the log to "alexa-auto-sdk-2.3/builder/build/tmp-android-22/work/armv7a-neon-linux-androideabi/avs-device-sdk/1.19.1-r0/avs-device-sdk-1.19.1/KWD/AmazonLite/src",it will be printed at least
## Provide the steps to reproduce the issue, if applicable:

Build commands:./build.sh android -t androidarm ../extensions/extras/amazonlite
## Tell us about your environment:

Ubuntu:16.04
### What version of the AVS Device SDK are you using?
      <x.y.z>
Auto SDK:2.3
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ V] Other - tell us more:
> Android

### Tell us about your OS (Type & version):
- [V ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi @xiaocrazy , this is a question for the Auto SDK. Please see their page for getting help: https://github.com/alexa/alexa-auto-sdk/blob/3.0/NEED_HELP.md

We don't support the Auto SDK in this forum, so I'll close this ticket.
