### ISSUE TITLE
how can gstreamer play the url for audible book?

### ISSUE THREAD

**Issue by xiaow6** [alexa/avs-device-sdk#186]
We have some troubles to play audible book, for the gstreamer we are using, it couldn't parse the url linked to the audible book.  And the m3u8 format is not supported by Gstreamer.

**Comment by xiaow6** [comment]
Even VLC can't play the url.

**Comment by sanjayrd** [comment]
Hi @xiaow6,

Are you parsing the playlist url manually and then giving the urls that actually point to the audio file to GStreamer? We've found that giving the raw M3U8 url to GStreamer appears to work, as GStreamer is able to parse M3U8 urls. The necessary plugin for this is `gst-plugins-bad`.

**Comment by xiaow6** [comment]
Hi Sanjay,

Do you know which option should I use? We have this plugin but it has so many options.

**Comment by sanjayrd** [comment]
Please see our `MediaPlayer.cpp` and `URLSource.cpp` files for reference on how to do this. `gst-plugins-bad` will also require `souphttpsrc` in order to play the audio.

**Comment by scotthea-amazon** [comment]
Hello xiaow6,

The last question was answered and there has been no further activity on this issue for a very long time.  So, I am closing this issue.  If I have closed in in error, please feel free to re-open it.

Thank you,
-SWH
