### ISSUE TITLE
Do not getting LED Notification

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1860]
## Briefly summarize your issue:
Alexa is not indicating about message received notification.

## What is the expected behavior?
Alexa should notify about the received message like this example below.
################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

## What behavior are you observing?
Alexa did not indicate about new message LED.

## Provide the steps to reproduce the issue, if applicable:
Send a message to Alexa using Alexa comms and observe the logs and LED.

## Tell us about your environment:
avs-device-sdk-1.18
Spotify ESDK-3.122.67
Adapter v1.8

### What version of the AVS Device SDK are you using?
 avs-device-sdk-1.18

### Tell us what hardware you're using:
Linux-Ubuntu 16.04

### Tell us about your OS (Type & version):
- [x] Linux
[Alexa_no_message_Led_issue.txt](https://github.com/alexa/avs-device-sdk/files/5770180/Alexa_no_message_Led_issue.txt)

**Comment by caleighatamazon** [comment]
Hi @Alexa-AUH, can you please copy this information to a ticket with your Amazon contact? There is some confidential logging in this issue so I'm going to remove it from the Github post, but please reach out to your Amazon contact and we can keep helping there.
