### ISSUE TITLE
How can Smart Home for AVS work with MQTT?

### ISSUE THREAD

**Issue by zzk135246** [alexa/avs-device-sdk#1862]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I've been trying to work on Smart Home for AVS to control connected devices in my home.
I want to use the peripheral endpoint controller instead of going through the smart home skill.
I've already set up mosquitto and configured the devices I want to control.
The last step I'm trying to do is have AVS able to publish / subscribe to my topics and control the connected devices.
I've done some research about this, most answers suggest me to use AWS IoT or the smart home skill, which defeats the purpose of me wanting to have everything running on the same linux device.
## What is the expected behavior?

AVS subscribes to a topic, when the topic for a light changes to "off", Alexa will sync and set the controller to "off"
AVS can publish to a topic, when the peripheral endpoint toggle controller triggers and set to "on", it will p publish message "on" to a topic.

## What behavior are you observing?

The publishing part I managed to achieve by running shell command when the controller is trigger.
I'm really stuck on the subscribing part.  Which when a topic changes, the controller on AVS side will also change.

Has anyone tried to do this? I know this is not necessary an Issue, but the AVS forum on amazon developer was depreciated. 
https://forums.developer.amazon.com/articles/233837/the-avs-forum-space-has-been-deprecated.html

**Comment by caleighatamazon** [comment]
Hi @zzk135246 , unfortunately your question is beyond the scope of our forum -- this Github forum is just for supporting issues and bugs related to the AVS Device SDK.

I recommend you use the contact form and explain your questions here: https://developer.amazon.com/alexa/console/contact-us
