### ISSUE TITLE
Repeat code

### ISSUE THREAD

**Issue by keying-linkplay** [alexa/avs-device-sdk#1865]
both line 80 and line 84 set the m_currentPowerState and copyOfObservers, i think it can remove one of them.
https://github.com/alexa/avs-device-sdk/blob/8e77a64c5be5a0b7b19c53549d91b0c45c37df3a/SampleApp/src/PeripheralEndpoint/PeripheralEndpointPowerControllerHandler.cpp#L80

https://github.com/alexa/avs-device-sdk/blob/8e77a64c5be5a0b7b19c53549d91b0c45c37df3a/SampleApp/src/PeripheralEndpoint/PeripheralEndpointPowerControllerHandler.cpp#L84

**Comment by mvelegon-amzn** [comment]
Hi @keying-linkplay thanks for letting us know. It does seem the redundant code in line 80 and 81 is not useful. I think the original intention was to notify the observers only if there is a change compared to the previous setting. I will open a ticket internally to get this addressed. Thanks!
