### ISSUE TITLE
alexa raspberry pi Espalexa.h And  fauxmo.h Librarie

### ISSUE THREAD

**Issue by Wasu-RPI** [alexa/avs-device-sdk#1868]
I Make Project Sonoff Smart Home projects, use Espalexa.h And  fauxmo.h Librarie Libraries With ESP8266 And Wemos D1 mini .It Complier Pass and Run devices to find and assign IP in the same wifi With Alexa, but Alexa can't find devices Ask for advice, fix

**Comment by womw** [comment]
Hi @Wasu-RPI thanks for posting

Can you please resubmit your issue according to the template? It's hard to understand what the problem is.

**Comment by alexandrekm-amzn** [comment]
hi @Wasu-RPI 

Can you open a new issue following the template? As soon as you click the ' New Issue' button the template will show up in the issue's body, please fill the fields shown there.
