### ISSUE TITLE
Question about AVS de-registration event

### ISSUE THREAD

**Issue by eytu0233** [alexa/avs-device-sdk#1869]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi AVS team,

We have a question about how to receive AVS de-registration event from APP.
While we de-register a device from APP, it may receive System:ResetUserInactivity and AudioPlayer:Stop directives.
Is ResetUserInactivity the directive which we can consider to be the de-registration event?
like 
DirectiveSequencer:onDirective:directive=namespace\:System\,name\:ResetUserInactivity\,messageId\:da1b85e0-d8e2-4388-873b-4993cec952e0\,dialogRequestId\:\,correlationToken\:\,eventCorrelationToken\:\,payloadVersion\:\,instance\:

If not, could you advice us to achieve a better way to get real-time deregistration notification ?

## What is the expected behavior?

Trigger a de-registration event and let device handle.

## What behavior are you observing?

No de-registration event.

## Provide the steps to reproduce the issue, if applicable:

De-register a device from APP.

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.21.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [* ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [* ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by yuan0258** [comment]
Using Metric recording it seems only get ResetUserInactivity after alexa app de-register
[{"directive":{"header":{"namespace":"System","name":"ResetUserInactivity","messageId":"f04bd389-6478-40f8-964a-3e9af1aa83fe"},"payload":{"cause":"GUI_ACTION"}}}]

**Comment by alexandrekm-amzn** [comment]
Hello @yuan0258 

The ResetUserInactivity is sent to reset the inactivity timer(https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/system.html#resetuserinactivity).

To detect a deregistration you can implement a RegistrationObserver and listen for the logout signal.

see: 
1) https://alexa.github.io/avs-device-sdk/classalexa_client_s_d_k_1_1registration_manager_1_1_registration_manager.html
2) https://alexa.github.io/avs-device-sdk/classalexa_client_s_d_k_1_1registration_manager_1_1_registration_observer_interface.html

**Comment by yuan0258** [comment]
@alexandrekm-amzn,
It seems RegistrationObserver need user trigger logout locally. If user use Alexa App to de-register device.
Could we get the logout directive from cloud?

**Comment by alexandrekm-amzn** [comment]
@yuan0258 
Unfortunately no such directive exists at the moment, we are working to improve the experience in those situations, please keep posted for updates.
