### ISSUE TITLE
Fatal Error: snsr.h file not found

### ISSUE THREAD

**Issue by Henry-Yi-2022** [alexa/avs-device-sdk#1871]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am trying to add the Snowboy wake word engine for my AVS device (I am currently running on MacOS), but when I run the command "make SampleApp" it produces the error message "Fatal Error: snsr.h file not found".  I found the snsr.h file online and downloaded it, but when I put it into the correct folder, it produced a linker error when I ran the make command again.  

## What is the expected behavior?

Build successfully

## What behavior are you observing?

"Fatal Error: snsr.h file not found"

## Provide the steps to reproduce the issue, if applicable:

1. Set up AVS according to: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/mac-os.html
2. Clone Snowboy code and place it into the third-party folder
3. Add the following to the cmake command :
  -DSENSORY_KEY_WORD_DETECTOR=ON \
 -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=../third-party/snowboy/lib/osx/libsnowboy-detect.a \
 -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=../third-party/snowboy/include
4. Rerun cmake and make commands

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [*] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @Henry-Yi-2022,

You seem to have confused Sensory with Kitt.AI (snowboy), which is wake word detector that is no longer supported.

**Comment by Henry-Yi-2022** [comment]
Thanks! What would be a good wake word engine for MacOS users then?

**Comment by kjkh** [comment]
Hi @Henry-Yi-2022,

Unfortunately, there is not currently replacement for wake word on macOS. If it's convenient, Sensory is supported on Raspberry Pi. Additionally, if you are working with an Amazon Business Representative, please reach out to them for possible alternatives.
