### ISSUE TITLE
AVS Device SDK build issues

### ISSUE THREAD

**Issue by kfisher-vizio** [alexa/avs-device-sdk#1873]
## Briefly summarize your issue:
While following this guide: [macOS Quick Start Guide](https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/mac-os.html) I am able to successfully complete all steps up until Step 4.

Running `make -j4` begins the build process, but aborts with the following error:

`[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WavUtils.cpp.o
make[2]: *** No rule to make target `/usr/local/opt/curl-openssl/lib/libcurl.dylib', needed by `AVSCommon/libAVSCommon.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WorkerThread.cpp.o
make[1]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make: *** [all] Error 2`

I have made numerous attempts to resolve this issue by resetting my environment, uninstalling dependencies, and starting from scratch. I've even had several other fellow developers attempt to follow this script on their machines and they end up with the same issue. Always aborts at 17%.

Updated the git repos given in the script to the latest versions (avs-device-sdk to 1.22.0 and apl-core-library to 1.5.1 respectively) and I get the same error, but this time it occurs at 16%:

`[ 16%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WavUtils.cpp.o
make[2]: *** No rule to make target `/usr/local/opt/curl-openssl/lib/libcurl.dylib', needed by `AVSCommon/libAVSCommon.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 16%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WorkerThread.cpp.o
make[1]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make: *** [all] Error 2`

## What is the expected behavior?
Components should compile successfully

## What behavior are you observing?
As outlined above, get a consistent and reproducible error across multiple machines

## Provide the steps to reproduce the issue, if applicable:
Follow the script detailed in the macOS Quick Start Guide

## Tell us about your environment:
MacOS, Catalina 10.15.7

`Homebrew 2.7.7
Homebrew/homebrew-core (git revision 0df95c; last commit 2021-02-01)
Homebrew/homebrew-cask (git revision 936b7; last commit 2021-02-01)`

`xcode-select version 2373`

### What version of the AVS Device SDK are you using?
      v1.21.0 (as detailed in Step 3 of the script)

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [X] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @kfisher-vizio,

Can you attach your cmake command as well as the full stack trace for the error?

**Comment by kfisher-vizio** [comment]
The cmake command is simply a copy and paste from the install guide that I linked to above:
`cmake ../avs-device-sdk \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DCURL_LIBRARY=/usr/local/opt/curl-openssl/lib/libcurl.dylib \
-DCURL_INCLUDE_DIR=/usr/local/opt/curl-openssl/include \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=$HOME/sdk_folder/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=$HOME/sdk_folder/third-party/portaudio/include \
-DCMAKE_BUILD_TYPE=DEBUG \
-DCMAKE_INSTALL_PREFIX=$HOME/sdk_folder/sdk-install \
-DRAPIDJSON_MEM_OPTIMIZATION=OFF`

I'm attaching the piped terminal output (with the --debug flag) of the "make -j4" for your viewing enjoyment. I'm assuming that's what you mean by stack trace on a command line build.
[outfile.log](https://github.com/alexa/avs-device-sdk/files/5912933/outfile.log)

**Comment by kfisher-vizio** [comment]
Determined what the root cause of my error was. The installed path of curl-openssl has evidently changed since this script was last written. Both instances of the `/usr/local/opt/curl-openssl/` path in the `cmake` command should instead be `/usr/local/opt/curl/`. Problem solved
