### ISSUE TITLE
[Question] Does the AVS device SDK support Alexa gadgets?

### ISSUE THREAD

**Issue by jimenaCabrejas** [alexa/avs-device-sdk#1874]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Hello, I was wondering if the AVS device SDK allows Alexa gadgets to connect to the built-in device. I haven't seen anything in the documentation about BLE support or connecting Alexa gadgets with this SDK but maybe I'm not looking in the right place. 

If this feature is not supported yet, are there any plans to implement this feature in the future?

Thanks and Regards!

**Comment by kjkh** [comment]
Hi @jimenaCabrejas,

The AVS SDK does not currently support Alexa gadgets. Unfortunately, we cannot comment on future release plans. If you have access to an Alexa Business Representative, you can try reaching out to them for any further details.
