### ISSUE TITLE
No audio playback - what specific gst plugins are required for the avs-sdk?

### ISSUE THREAD

**Issue by mattwood2000** [alexa/avs-device-sdk#1875]
## Briefly summarize your issue:
I get no audio playback via the SampleApp, but platform audio record/playback works correctly

## What is the expected behavior?
Audio playback as expected

## What behavior are you observing?
No audio

## Provide the steps to reproduce the issue, if applicable:
n/a

### What version of the AVS Device SDK are you using?
      v1.11.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ x] Other - tell us more:
Custom hardware based on armv7

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

On my platform, the audio record/playback works correctly (i.e aplay/arecord), and the Sensory KWD detection works to trigger Alexa, however I get no playback after a query (i.e what is the weather, etc.).

I suspect I'm missing some gst plugins either in the base, good, or bad packages.  They are not pre-compiled so I need to enable them and rebuild the target system.

Is there an list of plugins required to be enabled in the gst-base, gst-good, and gst-bad packages for the AVS SDK?

Running the SampleApp and asking a question results in the output below (trimmed for what I thought was relevant).

Any help would be appreciated!

GST_DEBUG=4 ./SampleApp AlexaClientSDKConfig.json Sensory_KWD/alexa-rpi/models DEBUG9
...
...
0:00:09.676418068   670   0x115200 WARN                    alsa pcm_dmix.c:1024:snd_pcm_dmix_open: alsalib error: The dmix plugin supports only playback stream
0:00:10.187781415   670   0x115200 WARN                    alsa pcm_dsnoop.c:577:snd_pcm_dsnoop_open: alsalib error: The dsnoop plugin supports only capture stream
...
...
###########################
#       Thinking...       #
###########################
...
...
2021-02-03 17:39:46.034 [  5] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
0:06:37.178805609   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<audio_sink> current NULL pending VOID_PENDING, desired next NULL
0:06:37.528551734   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<audio_sink> skipping transition from NULL to  NULL
0:06:37.528690333   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'audio_sink' changed state to 1(NULL) successfully
0:06:37.528854332   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<caps> current NULL pending VOID_PENDING, desired next NULL
0:06:37.528924331   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<caps> skipping transition from NULL to  NULL
0:06:37.529016330   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'caps' changed state to 1(NULL) successfully
0:06:37.529107730   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<resample> current NULL pending VOID_PENDING, desired next NULL
0:06:37.529169729   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<resample> skipping transition from NULL to  NULL
0:06:37.529258728   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'resample' changed state to 1(NULL) successfully
0:06:37.529343328   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<volume> current NULL pending VOID_PENDING, desired next NULL
0:06:37.529403527   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<volume> skipping transition from NULL to  NULL
0:06:37.529485127   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'volume' changed state to 1(NULL) successfully
0:06:37.529565926   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<converter> current NULL pending VOID_PENDING, desired next NULL
0:06:37.529625326   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<converter> skipping transition from NULL to  NULL
0:06:37.529689325   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'converter' changed state to 1(NULL) successfully
0:06:37.529781324   670   0x174520 INFO              GST_STATES gstbin.c:2507:gst_bin_element_set_state:<decodedQueue> current NULL pending VOID_PENDING, desired next NULL
0:06:37.529842124   670   0x174520 INFO              GST_STATES gstbin.c:2624:gst_bin_element_set_state:<decodedQueue> skipping transition from NULL to  NULL
0:06:37.529904124   670   0x174520 INFO              GST_STATES gstbin.c:2955:gst_bin_change_state_func:<audio-pipeline> child 'decodedQueue' changed state to 1(NULL) successfully
0:06:37.530002323   670   0x174520 INFO              GST_STATES gstelement.c:2676:gst_element_continue_state:<audio-pipeline> completed state change to NULL
0:06:37.530168521   670   0x174520 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:462:gst_element_factory_make: no such element factory "appsrc"!
...
...
########################################
#       Alexa is currently idle!       #
########################################

2021-02-03 17:39:46.386 [  5] E BaseStreamSource:initFailed:reason=createSourceElementFailed
2021-02-03 17:39:46.745 [  5] 9 BaseStreamSource:~BaseStreamSource

(<unknown>:670): GLib-GObject-WARNING **: 12:39:46.745: invalid (NULL) pointer instance

(<unknown>:670): GLib-GObject-CRITICAL **: 12:39:46.745: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(<unknown>:670): GLib-GObject-WARNING **: 12:39:46.745: invalid (NULL) pointer instance

(<unknown>:670): GLib-GObject-CRITICAL **: 12:39:46.745: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(<unknown>:670): GLib-GObject-WARNING **: 12:39:46.745: invalid (NULL) pointer instance

(<unknown>:670): GLib-GObject-CRITICAL **: 12:39:46.746: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
2021-02-03 17:39:46.746 [  5] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=AttachmentReaderSource
2021-02-03 17:39:46.746 [  5] E MediaPlayer:handleSetAttachmentReaderSourceFailed:reason=sourceIsNullptr
2021-02-03 17:39:46.746 [ 19] E SpeechSynthesizer:startPlayingFailed:reason=setSourceFailed
2021-02-03 17:39:46.746 [ 19] 0 SpeechSynthesizer:executePlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=playFailed
2021-02-03 17:39:46.746 [ 19] 9 SpeechSynthesizer:setCurrentStateLocked:state=FINISHED

**Comment by kjkh** [comment]
Hi @mattwood2000,

Your error logs indicate that `appsrc` is missing: 

`0:06:37.530168521 670 0x174520 WARN GST_ELEMENT_FACTORY gstelementfactory.c:462:gst_element_factory_make: no such element factory "appsrc"!`

Unfortunately we do not have a comprehensive list of plugins. These will vary depending on platform and dependencies. However, GStreamer will typically indicate missing elements in its error logging.

**Comment by mattwood2000** [comment]
Thanks @kjkh I went through and started enabling plugins and was able to get it working.  I'll need to figure out which ones were the required plugins.  It might be useful to have a specific list of the plugins as not all use cases for AVS will use a distro with package management (i.e embedded Linux).

Thanks!
