### ISSUE TITLE
Timeout function to quit SampleApp without user input

### ISSUE THREAD

**Issue by ejri** [alexa/avs-device-sdk#1876]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Running Alexa on raspberry pi, wanted to run Alexa within a timeout function (to save battery power).  

To quit the SampleApp, users would need to input (q + enter). 
- Is there a way to quit the app or create a timeout quit function without relying on the input, or threading. 

## What is the expected behavior?
works as expected. 

## What behavior are you observing?
as expected 

## Provide the steps to reproduce the issue, if applicable:

```
import concurrent.futures
# import keyboard
import subprocess
import threading
import time
from timeit import default_timer as timer
from pynput.keyboard import Key, Controller

keyboard = Controller()  # Create the controller

# function to input (q + enter)  while Alexa is running to quit application
# after 10 seconds  (time_to_stop) is specified in running thread function
def start_timing(time_to_stop):
    stay_connected = True
    start = timer()
    while stay_connected == True:
        end = timer()
        time_difference = end - start
        if time_difference > time_to_stop:
            # input('q')
            keyboard.press("q")
            keyboard.release("q")
            time.sleep(0.2)
            keyboard.press(Key.enter)
            keyboard.release(Key.enter)
            time.sleep(0.2)
            stay_connected = False
            break

    return "Alexa ran out of time."


def start_alexa():
    subprocess.call("bash /home/pi/startsample.sh", shell=True)


with concurrent.futures.ThreadPoolExecutor() as executer:
    f1 = executer.submit(start_alexa)
    # time_to_stop = 30 seconds
    f2 = executer.submit(start_timing, 30)
    print(f2.result())
```

## Tell us about your environment:
ssh @pi. VSCode 
Overall setup:
https://github.com/ejri/Wise_Tree_5G_at_UBC

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Raspbian buster

**Comment by kclchan** [comment]
Hi @ejri, this is an interesting idea.  Please note that the SampleApp is just an example application on how to use the AVS Device SDK.  If you want, you can create your own version of application and create this timer for your use case.  Thanks!
