### ISSUE TITLE
Unable to trace the Audio Input given to the system

### ISSUE THREAD

**Issue by Jigar27** [alexa/avs-device-sdk#188]
Hello,
I am trying to feed the audio files (saved files) to the system instead of microphone data. I came to know that notifyOfTapToTalk() function is responsible for getting the audio input stream from AudioProvider. But I am not able to understand the flow. Can you please explain a little that what happens when notifyOfTapToTalk is called and how the audio stream is stored in buffer ??

**Comment by mradulan** [comment]
notifyOfTapToTalk calls the Recognize function in AudioInputProcessor.cpp which sends a Recognize event to AVS. The AudioInputProcessorIntegrationTest.cpp feeds audio files from the system to test it.

**Comment by kclchan** [comment]
I think this is similar to #198, so I am going to close this ticket.  Thanks!
