### ISSUE TITLE
need  libAlexaCommsLib.so file compatible for 64bit

### ISSUE THREAD

**Issue by prachipsutane** [alexa/avs-device-sdk#1880]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have NXP iMX8MMini-EVK evaluation board. It is a 64bit processor.
 I am porting avs-device-sdk from 32 to 64 bit.
I have 32 bit compatible libAlexaCommsLib.so file. when i try to compile it on 64 bit machine i am getting error saying : "file in wrong format". (for obvious reason).

this is why i need  libAlexaCommsLib.so file compatible for 64bit.

## What is the expected behavior?

when I include the 64bit so file, my application should compile successfully 

## What behavior are you observing?

As I a compiling the code which includes a 32 bit so file, I am getting an error saying "file in the wrong format."

## Provide the steps to reproduce the issue, if applicable:

I run the sh file which internally invokes a cmake file. and eventually using a 'libAlexaCommsLib.so' 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [.] Other - tell us more:   
using NXP iMX8MMini-EVK evaluation board
Which has Yocto in it

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [.] Other - tell us more: 
-using NXP iMX8MMini-EVK evaluation board
Which has Yocto in it

**Comment by mvelegon-amzn** [comment]
Hi @prachipsutane for this Comms related question could you please fcontact your Amazon Solutions Architect. Since this library is not open source we do not provide support for it on github. Thanks!
