### ISSUE TITLE
Build avs-device-sdk with WakeWord engine on Raspberry Pi Desktop for PC

### ISSUE THREAD

**Issue by GitHubUser4234** [alexa/avs-device-sdk#1881]
Hi,

I'm trying to build the latest avs-device-sdk on Raspberry Pi Desktop for PC (x64). Following the RPI instruction didn't work because it is ARM based. But it **did work** when following the instruction for Ubuntu and Alexa could understand what was said through the microphone. Unfortunately, the instruction for Ubuntu doesn't contain the WakeWord engine, so I then tried to build the sdk by using porcupine which is currently said to be the best WakeWord engine out there. I cloned porcupine and ran:

`cd $HOME/my_project/build`

```
 cmake $HOME/my_project/source/avs-device-sdk \
 -DGSTREAMER_MEDIA_PLAYER=ON \
 -DPORTAUDIO=ON \
 -DPORTAUDIO_LIB_PATH=$HOME/my_project/third-party/portaudio/lib/.libs/libportaudio.so \
 -DPORTAUDIO_INCLUDE_DIR=$HOME/my_project/third-party/portaudio/include \
 -DSENSORY_KEY_WORD_DETECTOR=ON \
 -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=$HOME/my_project/third-party/porcupine/lib/linux/x86_64/libpv_porcupine.so \
 -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=$HOME/my_project/third-party/porcupine/include
```

` make SampleApp -j2 `

However it returned this error:

_[ 80%] Built target DeviceSettings
In file included from /home/pi/my_project/source/avs-device-sdk/KWD/Sensory/src/SensoryKeywordDetector.cpp:20:
/home/pi/my_project/source/avs-device-sdk/KWD/Sensory/include/Sensory/SensoryKeywordDetector.h:31:10: fatal error: snsr.h: No such file or directory
 #include "snsr.h"
          ^~~~~~~~
compilation terminated.
make[3]: *** [KWD/Sensory/src/CMakeFiles/SENSORY.dir/build.make:63: KWD/Sensory/src/CMakeFiles/SENSORY.dir/SensoryKeywordDetector.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:12253: KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 82%] Built target SpeakerManager
make[1]: *** [CMakeFiles/Makefile2:15235: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:3568: SampleApp] Error 2_

Why does it complain about snsr.h when it should use porcupine and not Sensory? How can the problem be solved?

Thank you.

### Tell us what hardware you're using:
- [ x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ x] Other - tell us more:
 Raspberry Pi Desktop for PC

**Comment by mvelegon-amzn** [comment]
Hi @GitHubUser4234 we do not currently support Procupine as a Keyword detector for AVS SDK. Note that in order to add support to a new keyword engine we will have to make some changes to the SDK. You can take a look at SensoryKeywordDetector.h and SensoryKeywordDetector.cpp files to get more information on how to do this.

**Comment by GitHubUser4234** [comment]
If effort is put into writing the procupine keyword detector for AVS SDK, will it be possible to merge it into the SDK by pull request or would there be licencing/policy issues preventing it?

**Comment by womw** [comment]
Hi, currently we're not accepting pull requests for our SDK.

You're more than welcome to write your own keyword detector for Porcupine but it's not one we're currently supporting.
