### ISSUE TITLE
Start of SampleApp fails with "Illegal Instruction"

### ISSUE THREAD

**Issue by pcnetzwerke** [alexa/avs-device-sdk#1882]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I think I compiled and configured the SDK SampleApp as described [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html).
When I start the SampleApp, it fails wirh "Illegal Instruction".

## What is the expected behavior?
Well, the SampleApp should start.

## What behavior are you observing?
```
pi@radio2 ~/downloads/avs-device-sdk/sdk-build $ PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
configFile ./Integration/AlexaClientSDKConfig.json
##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: [...xyz...]       #
################################################################################################

#################################################
#       Checking for authorization (1)...       #
#################################################

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 923
#################################################
#       Checking for authorization (2)...       #
#################################################

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 933
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 933
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 933
Illegal instruction
pi@radio2 ~/downloads/avs-device-sdk/sdk-build $
```
## Provide the steps to reproduce the issue, if applicable:
Well, I do not know, but maybe it is related to my sound config.
rec works, I can listen to the recorded wav-file.
hw-sink 1:0 is a usb card for output
hw-sink 2:0 is a usb card for micro

```
pi@radio2 ~ $ cat .asoundrc
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
}
pi@radio2 ~ $ rec test.wav
rec WARN alsa: can't encode 0-bit Unknown or not applicable

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:01.96 [00:00:00.00] Out:90.1k [      |      ]        Clip:0    ^C
Aborted.
pi@radio2 ~ $ play test.wav
play WARN alsa: can't encode 0-bit Unknown or not applicable

test.wav:

 File Size: 360k      Bit Rate: 1.54M
  Encoding: Signed PCM
  Channels: 2 @ 16-bit
Samplerate: 48000Hz
Replaygain: off
  Duration: 00:00:01.88

In:72.7% 00:00:01.37 [00:00:00.51] Out:65.5k [      |      ]        Clip:0
```

I configured sdk to use alsa as sink:

```
pi@radio2 ~/downloads/avs-device-sdk/sdk-build $ head -6 ./Integration/AlexaClientSDKConfig.json
{
    "gstreamerMediaPlayer":{
        "audioSink":"alsasink"
        //"audioSink":"pulsesink"
    },
    "cblAuthDelegate":{
```

### What version of the AVS Device SDK are you using?
Version 1.22.0 alexa-client-sdk

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

```
pi@radio2 ~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

I am definitely not familiar with linux sound, but I could imagine this issue has to do with it. But after searching in internet the whole morning I have no idea what to do next or where to start debugging.

Thanks for all Your work, I really appreciate your help a lot!

**Comment by mvelegon-amzn** [comment]
Hi @pcnetzwerke please make sure that you have a microphone installed when you run the SampleApp.

Also please take a look at the following issues which have some resolution steps:
https://github.com/alexa/avs-device-sdk/issues/1372
https://github.com/alexa/avs-device-sdk/issues/1366

**Comment by pcnetzwerke** [comment]
Hi @mvelegon-amzn

Thany You very much, that #1372 helped a lot.
Reason: I am using RASPi v1 too, although not suggested. I thought it was only a matter of performance, so please excuse my mistake.
In the meantime I got it running on a RASPI v3 following the guide with one exception: I needed to install the package gstreamer1.0-alsa in addition to them mentioned ones.

off topic: unfortunately my plan does not work: I wanted to upgrade my mp3 radios with amazon prime music, but that is not possible because alexa says "music & video is not supported on your device"..... :-(

Thank You very much for Your work & time!
