### ISSUE TITLE
Indicate Device States with LEDs doesn't activate LEDs 

### ISSUE THREAD

**Issue by erikthegamer1242** [alexa/avs-device-sdk#1883]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When setting up the LEDs with [this](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/indicate-device-state-with-leds.html) and recompiling the SampleApp none o the LEDs light up, but when I use a simple Python program to just flash them they work without a problem.
## What is the expected behavior?

LEDs should light
## What behavior are you observing?

LEDs don't light
## Provide the steps to reproduce the issue, if applicable:

use https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/indicate-device-state-with-leds.html to setup LEDs and start `sudo bash startsample.sh`
### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Rasbian Buster

**Comment by womw** [comment]
Hi @erikthegamer1242 thanks for posting.

Are you able to directly turn on the LED's in main.cpp of the SampleApp like you do in your simple Python program? This seems to be an issue not with the SDK but with using the PiWiring library which extends beyond the scope that I can support you with. Can you make sure the library is correct for the Pi model you are using?

**Comment by erikthegamer1242** [comment]
I will try the main.cpp, how can I check the library version which I need, I am running on pi 4

**Comment by erikthegamer1242** [comment]
> I will try the main.cpp

I tried and it didn'work where should I go to ask for support?

**Comment by erikthegamer1242** [comment]
SOLVED: Once you told me to check the library version I figured it out, for everyone else here is the solution:

### Steps to make LEDs work on AVS 1.22.0

1. Follow http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/
2. Then recompile and run the SampleApp
