### ISSUE TITLE
Play an audio file before the response from Alexa

### ISSUE THREAD

**Issue by lenhattu** [alexa/avs-device-sdk#1884]
## Briefly summarize your issue:

I tried to modify the startPlaying() function in SpeechSynthesizer.cpp to first play an audio file then the response from Alexa.
[https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078](https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078)
I tried creating a MediaPlayer's source id of the audio file then passing it to the play() function but it doesn't work. Please see the details of my modification below.

## What is the expected behavior?

When I tap 't' to ask "What is the weather?", it should first play my audio file then play the response to my question "What is the weather?"

## What behavior are you observing?

Audio file is not played although m_speechPlayer->play() returns true. Also, consecutive play() calls seem not possible.

## Provide the steps to reproduce the issue, if applicable:

I modify the startPlaying() function in [https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078](https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078)
to:

void SpeechSynthesizer::startPlaying() {
    ACSDK_DEBUG9(LX("startPlaying"));

    std::string file_audio_path("/home/ubuntu/my_project/myaudio.mp3");
    MediaPlayerInterface::SourceId mysourceid = m_speechPlayer->setSource(file_audio_path);
    if (!m_speechPlayer->play(mysourceid)) {
        executePlaybackError(ErrorType::MEDIA_ERROR_INTERNAL_DEVICE_ERROR, "playFailed");
    }
    
    std::shared_ptr<AttachmentReader> attachmentReader = std::move(m_currentInfo->attachmentReader);
    m_mediaSourceId = m_speechPlayer->setSource(std::move(attachmentReader));
    if (m_captionManager && m_captionManager->isEnabled() && m_currentInfo->captionData.isValid()) {
        m_captionManager->onCaption(m_mediaSourceId, m_currentInfo->captionData);
    }
    
    if (MediaPlayerInterface::ERROR == m_mediaSourceId) {
        ACSDK_ERROR(LX("startPlayingFailed").d("reason", "setSourceFailed"));
        executePlaybackError(ErrorType::MEDIA_ERROR_INTERNAL_DEVICE_ERROR, "playFailed");
    } else if (!m_speechPlayer->play(m_mediaSourceId)) {
        executePlaybackError(ErrorType::MEDIA_ERROR_INTERNAL_DEVICE_ERROR, "playFailed");
    }
}

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by womw** [comment]
Hey @lenhattu thanks for posting.

In order to play an audio file you need to first process the file as a istream. 

You can see an example of this in the SystemSoundAudioFactory and the SystemSoundPlayer

https://github.com/alexa/avs-device-sdk/blob/master/ApplicationUtilities/Resources/Audio/src/SystemSoundAudioFactory.cpp#L27

https://github.com/alexa/avs-device-sdk/blob/master/ApplicationUtilities/SystemSoundPlayer/src/SystemSoundPlayer.cpp#L75

**Comment by lenhattu** [comment]
> Hey @lenhattu thanks for posting.
> 
> In order to play an audio file you need to first process the file as a istream.
> 
> You can see an example of this in the SystemSoundAudioFactory and the SystemSoundPlayer
> 
> https://github.com/alexa/avs-device-sdk/blob/master/ApplicationUtilities/Resources/Audio/src/SystemSoundAudioFactory.cpp#L27
> 
> https://github.com/alexa/avs-device-sdk/blob/master/ApplicationUtilities/SystemSoundPlayer/src/SystemSoundPlayer.cpp#L75

Hi @womw, thank you so much for your help!

So based on your example, if I hexdump my audio file to a C header file: 
`xxd -i myaudio.mp3 myaudio.h`
I will be able to reuse the AudioFactory module in your example to process my file as a istream. Am I right?

I am still curious about why passing the url of the audio file to MediaPlayer->setSource() function (like what I did) does not work as I see some examples doing that in MediaPlayerTest here: [https://github.com/alexa/avs-device-sdk/blob/master/MediaPlayer/GStreamerMediaPlayer/test/MediaPlayerTest.cpp#L748](https://github.com/alexa/avs-device-sdk/blob/master/MediaPlayer/GStreamerMediaPlayer/test/MediaPlayerTest.cpp#L748)

**Comment by alexandrekm-amzn** [comment]
Hi @lenhattu 
The tests you linked are unit tests using Mocks to abstract some part of the code. Have you tried the instructions posted by @womw ?

**Comment by lenhattu** [comment]
> Hi @lenhattu
> The tests you linked are unit tests using Mocks to abstract some part of the code. Have you tried the instructions posted by @womw ?

I was able to play the audio file by following the instruction posted by @womw.

But the issue is that I can only play 1 sourceId in the startPlaying() function at [https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078](https://github.com/alexa/avs-device-sdk/blob/master/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L1078).

How can I play 2 sourceIds one after the other? Basically, I would like to first play my audio file then the response from Alexa.
