### ISSUE TITLE
Compiling AVS for ubuntu, problem with Sensory

### ISSUE THREAD

**Issue by erikthegamer1242** [alexa/avs-device-sdk#1885]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When getting to the part in the [guide](urhttps://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html#build-the-avs-device-sdk-sample-appl) i get to the part to download Sensory, i git clone it into third-party and wheni try to run it it gives me this error:
`license.sh: line 49: /home/ubuntu/Desktop/UbuntuAlexa/third-party/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.
`
## What is the expected behavior?

It should go through and accept the licence 
## What behavior are you observing?

it gives an error
## Provide the steps to reproduce the issue, if applicable:

This section of [this](https://github.com/alexa/avs-device-sdk/issues/611) GitHub issue
**for Sensory:
cd ~/sdk-folder/third-party
git clone --depth 1 https://github.com/Sensory/alexa-rpi.git
cd alexa-rpi
./bin/license.sh;**
### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Ubuntu 18.04

**Comment by alexandrekm-amzn** [comment]
Hi @erikthegamer1242 
Thanks for reaching out, the reason that you are facing this error is because the sensory binary you are checking out is for raspberry pi and you are running on x86 hence the binary incompatibility error.

Unfortunately, we do not have a wake word detector compatible with the x86 platform that we can recommend. 

Thanks
-Alex

**Comment by caleighatamazon** [comment]
Closing this issue.
