### ISSUE TITLE
Grammar errors on help pages.

### ISSUE THREAD

**Issue by mg94c18** [alexa/avs-device-sdk#1886]
## Briefly summarize your issue:
Grammar errors on help pages.

## What is the expected behavior?
Proper grammar.

## What behavior are you observing?
It says "you must you must have a microphone."

## Provide the steps to reproduce the issue, if applicable:
Go to https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html
Read the "Required hardware" section.
It says "you must you must have a microphone."

## Tell us about your environment:
N/A

### Tell us what hardware you're using:
N/A

### Tell us about your OS (Type & version):
N/A

**Comment by alexandrekm-amzn** [comment]
Hi @mg94c18 
Thanks for pointing out the error, I already submitted informed the team responsible for the public docs, and this will get fixed soon. Keep posted

Thanks,
-Alex

**Comment by kjkh** [comment]
This has been fixed, closing ticket.
