### ISSUE TITLE
Cloning git repo takes forever; should use "--depth 1"

### ISSUE THREAD

**Issue by mg94c18** [alexa/avs-device-sdk#1887]
## Briefly summarize your issue:
When I go through setup steps, git clone command takes a very long time.

## What is the expected behavior?
It should finish within 60 seconds.
I recommend that you add "--depth 1" to instructions because most people are not interested in git history.

## What behavior are you observing?
It takes more than five minutes.  I terminated it then.

## Provide the steps to reproduce the issue, if applicable:
git clone https://github.com/alexa/avs-device-sdk.git

### What version of the AVS Device SDK are you using?
1.18.0 and higher

### Tell us what hardware you're using:
- Desktop

### Tell us about your OS (Type & version):
- Linux

**Comment by alexandrekm-amzn** [comment]
hi @mg94c18 
Thanks for reaching out, and for your suggestion, it's a valid request. I forwarded the suggestion to the team that takes care of the documentation, keep posted for changes.


I'll be closing this ticket, in case you have more questions do not hesitate to ask.
