### ISSUE TITLE
Long time to register endpoint when not register alexa immediately

### ISSUE THREAD

**Issue by oscar1372** [alexa/avs-device-sdk#1888]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When not register alexa immediately and waiting about 7~8 minutes, alexa will not register endpoint immediately and can not trigger alexa after getting "authorized" status.

Here is device sdk 1.22.0's log
[register_1_22_0.log](https://github.com/alexa/avs-device-sdk/files/6109713/register_1_22_0.log)

According the log, it seem sdk needs to wait "PostConnectVerifyGatewaySender:sendVerifyGateway" to verify gateway sucessfully.
But it can not verify successfully when alexa is unauthorized status. I think it is expected behavior. However, PostConnectVerifyGatewaySender will keep to retry with the below duration. The max duration reach 256 seconds(about 4 minutes).
https://github.com/alexa/avs-device-sdk/blob/8e77a64c5be5a0b7b19c53549d91b0c45c37df3a/AVSGatewayManager/src/PostConnectVerifyGatewaySender.cpp#L47

So, alexa can not get verify gateway immediately after registering (Need retry timer to trigger).
User may think alexa has problem which can not trigger.
Is it possible to change flow so that PostConnectVerifyGatewaySender starts after registering?

## What is the expected behavior?

Getting "Successfully registered 1 endpoint(s)." immediately after getting "authorized" status.

## What behavior are you observing?

It needs to wait 2~4 minutes to getting "Successfully registered 1 endpoint(s)."

## Provide the steps to reproduce the issue, if applicable:

1. Clear database and restart SampleApp.
2. Wait 7~8 minutes
3. Register code

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by alexandrekm-amzn** [comment]
hi @oscar1372 

Thanks for letting us know about it. I created an internal ticket to get this addressed and we will fix this in one of our future releases.
