### ISSUE TITLE
SDK won't build

### ISSUE THREAD

**Issue by clinesmith-m** [alexa/avs-device-sdk#1891]
## Briefly summarize your issue:
I've been following [this](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html) guide to install the Alexa SDK on my laptop. I'm able to run the first cmake command found [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ubuntu.html#build-the-avs-device-sdk-sample-app) with no apparent issues, but compilation fails when I run `make SampleApp -j2`.

## What is the expected behavior?
The SDK should build.

## What behavior are you observing?
I get this error output:
`$ make SampleApp -j2`
...
`[ 95%] Building CXX object SampleApp/src/CMakeFiles/LibSampleApp.dir/SampleEqualizerModeController.cpp.o
make[3]: *** No rule to make target '/home/michael/my_project/third-party/portaudio/lib/.libs/libportaudio.so', needed by 'SampleApp/src/libLibSampleApp.so'.  Stop.
make[3]: *** Waiting for unfinished jobs....
[ 95%] Building CXX object SampleApp/src/CMakeFiles/LibSampleApp.dir/PortAudioMicrophoneWrapper.cpp.o
CMakeFiles/Makefile2:15072: recipe for target 'SampleApp/src/CMakeFiles/LibSampleApp.dir/all' failed
make[2]: *** [SampleApp/src/CMakeFiles/LibSampleApp.dir/all] Error 2
CMakeFiles/Makefile2:14995: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:3529: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2`

## Provide the steps to reproduce the issue, if applicable:
I followed the steps in the install guide exactly to this point. I noticed some similarities to [issue #1257](https://github.com/alexa/avs-device-sdk/issues/1257), so I tried to follow some of the recommendations made there, but it didn't seem to make much of a difference.

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux (Mint 19.1)
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by alexandrekm-amzn** [comment]
hi @clinesmith-m ,
Thanks for reaching out, the error you are facing is because the SDK build script cannot find the portaudio library.
Double check if this path is correct /home/michael/my_project/third-party/portaudio/lib/.libs/libportaudio.so and if this is the same you used in the cmake command. 

You can also paste the exact cmake command you used so we can double check that.

Thanks,
-Alex

**Comment by clinesmith-m** [comment]
Thanks for pointing that out! My path was off because I was trying to reuse the same script I made when I installed the SDK in another environment, but forgot that I had changed the name of the ~/my_project/ directory. It builds properly now. I'm closing the issue.
