### ISSUE TITLE
end of create calendar dialog fails with "I'm having trouble understanding"

### ISSUE THREAD

**Issue by sdetweil** [alexa/avs-device-sdk#1892]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have my own 'avs' sdk implementation. all used to work great (July 2020),  I have been sick, and now just back verifying before release...  but now creating a calendar entry fails.  (which works on a real echo device)

this is a multi-turn dialog

alexa, create a calendar entry
prompt, "what date and time"
response, "tuesday at 2 pm"
prompt, "what is the name of the event"
response, "just testing"
prompt, "thats 'Just Testing' on Tuesday (date) at 2pm, right"
response "yes"  (also tried, ok, correct, sure, all fail the same, real echo works fine)
final alexa reply, "I'm having trouble understand"
and the event does not get created

## What is the expected behavior?
the final reply from a real echo device is "Ok, I've added that"
and the event is created

## What behavior are you observing?
final alexa reply, "I'm having trouble understand"
and the event does not get created

## Provide the steps to reproduce the issue, if applicable:

this is a extension of a smart mirror environment. 
[files.zip](https://github.com/alexa/avs-device-sdk/files/6142250/files.zip)

### What version of the AVS Device SDK are you using?
      <x.y.z>
not using SDK, using own code following avs http/2 spec
I do my own voice reco and audio file capture. the response process is identical for each gathered prompt response

attached is a zip file of the confirmation response from my app, and the response from avs
awsin.wav is inbound to avs
response.mp3 is the avs reponse

I had created a case on the amazon developer support
RE:[CASE 8095156021] avs application add calendar event multi-step dialog fails on confirmation
and posted in the developer forum
https://forums.developer.amazon.com/questions/237793/avs-application-add-calendar-event-multi-step-dial.html

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
- [ ] Raspian Buster

**Comment by kjkh** [comment]
Hi @sdetweil,

Unfortunately your question is beyond the scope of this forum. The forum is meant for issues related to the AVS Device SDK. If you do not receive an answer to your forum question, you can try reaching out via the contact form here: https://developer.amazon.com/alexa/console/contact-us.

**Comment by sdetweil** [comment]
thanks.. I was directed here from there already
https://developer.amazon.com/alexa/console/contact-us/case?caseID=8095156021

**Comment by caleighatamazon** [comment]
I'm going to close this issue since unfortunately we cannot help issues unrelated to the Device SDK.

**Comment by sdetweil** [comment]
thanks. the resolution was that I wasn't sending the status events for speechStarted and speechFinished
