### ISSUE TITLE
WAKEWORD initiator is bad request and TAP initiator is OK

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#1897]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Get bad request when communicating with AVS server using WAKEWORD initiator, but used TAP initiator is success.
Log information: [avs.log](https://github.com/alexa/avs-device-sdk/files/6188087/avs.log)
Thanks!

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @BobXLiu, were there any changes made to the SDK or the wakeword adapter?  From the logs, I am seeing messages like this:
```
[Status]: RingBuffer rp wrapped(524160) count=336
```
I would like to suggest double checking if the data are being written to the AudioInputStream correctly.

**Comment by BobXLiu** [comment]
Hi @kclchan, This issue has been resolved and the root cause is incorrect context content
