### ISSUE TITLE
getting error while building alexa sdk : libpryon_lite.a: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by prachipsutane** [alexa/avs-device-sdk#1898]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

i have been trying to build alexa sdk, facing this error:

## What is the expected behavior?

build succesfull 
## What behavior are you observing?

getting error : libpryon_lite.a: error adding symbols: file in wrong format
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [=] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more: 

### Tell us about your OS (Type & version):
- [ =] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

This is what error looks like:

/home/admin2/avs-device-sdk-1.18/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapid                              json/document.h:540:7: note: 'class rapidjson::GenericValue<rapidjson::UTF8<> >' declared here
  540 | class GenericValue {
      |       ^~~~~~~~~~~~
[ 68%] Linking CXX executable ContextManagerTest
[ 68%] Built target ContextManagerTest
Scanning dependencies of target IterativePlaylistParserTest
[ 68%] Building CXX object PlaylistParser/test/CMakeFiles/IterativePlaylistParserTest.dir/IterativePlaylis                              tParserTest.cpp.o
[ 68%] Linking CXX executable PlaylistParserTest
[ 68%] Built target PlaylistParserTest
Scanning dependencies of target AbstractKeywordDetectorTest
[ 69%] Building CXX object KWD/test/CMakeFiles/AbstractKeywordDetectorTest.dir/AbstractKeywordDetectorTest                              .cpp.o
[ 69%] Linking CXX executable ContentDecrypterTest
[ 69%] Built target ContentDecrypterTest
Scanning dependencies of target AMAZONLITE
[ 69%] Building CXX object KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/PryonLiteKeywordDetector.cpp.o
[ 70%] Linking CXX shared library libCapabilitiesDelegate.so
[ 70%] Built target CapabilitiesDelegate
Scanning dependencies of target ApiGatewayCapabilityAgentTest
[ 70%] Building CXX object CapabilityAgents/ApiGateway/test/CMakeFiles/ApiGatewayCapabilityAgentTest.dir/A                              piGatewayCapabilityAgentTest.cpp.o
[ 70%] Linking CXX shared library libAMAZONLITE.so
/opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-po                              ky-linux/9.2.0/real-ld: /home/admin2/prachi/trebl-alexa_new/build/lib/libpryon_lite.a: error adding symbol                              s: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/build.make:87: KWD/AmazonLite/src/libAMAZONLITE                              .so] Error 1
make[1]: *** [CMakeFiles/Makefile2:6911: KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX executable IterativePlaylistParserTest
[ 70%] Built target IterativePlaylistParserTest
[ 70%] Linking CXX executable AbstractKeywordDetectorTest
[ 70%] Built target AbstractKeywordDetectorTest
[ 70%] Linking CXX executable ApiGatewayCapabilityAgentTest
[ 70%] Built target ApiGatewayCapabilityAgentTest
make: *** [Makefile:141: all] Error 2
make failed, please check logs

**Comment by kclchan** [comment]
Hi @prachipsutane, please could contact your Amazon Solutions Architect for support with question like these.  I am going to close this issue now.  Thanks!
