### ISSUE TITLE
Getting error : libpryon_lite.a: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by prachipsutane** [alexa/avs-device-sdk#1900]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have been trying to build alexa sdk on ubuntu machine. I am getting error saying : libpryon_lite.a: error adding symbols: file in wrong format
error: 
Scanning dependencies of target AbstractKeywordDetectorTest
[ 69%] Building CXX object KWD/test/CMakeFiles/AbstractKeywordDetectorTest.dir/AbstractKeywordDetectorTest.cpp.o
[ 70%] Linking CXX shared library libCapabilitiesDelegate.so
[ 70%] Linking CXX executable ContentDecrypterTest
[ 70%] Built target CapabilitiesDelegate
Scanning dependencies of target AMAZONLITE
[ 70%] Building CXX object KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/PryonLiteKeywordDetector.cpp.o
[ 70%] Built target ContentDecrypterTest
Scanning dependencies of target ApiGatewayCapabilityAgentTest
[ 70%] Building CXX object CapabilityAgents/ApiGateway/test/CMakeFiles/ApiGatewayCapabilityAgentTest.dir/ApiGatewayCapabilityAgentTest.cpp.o
[ 70%] Linking CXX shared library libAMAZONLITE.so
/opt/fsl-imx-xwayland/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/real-ld: /home/user/trebl-alexa_new/build/lib/libpryon_lite.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/build.make:87: KWD/AmazonLite/src/libAMAZONLITE.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:6911: KWD/AmazonLite/src/CMakeFiles/AMAZONLITE.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX executable IterativePlaylistParserTest
[ 70%] Built target IterativePlaylistParserTest
[ 70%] Linking CXX executable AbstractKeywordDetectorTest
[ 70%] Built target AbstractKeywordDetectorTest
[ 70%] Linking CXX executable ApiGatewayCapabilityAgentTest
[ 70%] Built target ApiGatewayCapabilityAgentTest
make: *** [Makefile:141: all] Error 2
make failed, please check logs

## What behavior are you observing?

when i see the file format of .a file i got this:
 objdump -f libpryon_lite.a
In archive libpryon_lite.a:

dnh2gi4wegoyz6oeuvsa7ur5opkrb3je.o:     file format elf32-little
architecture: UNKNOWN!, flags 0x00000010:
HAS_SYMS
start address 0x00000000

n6i52kx3axccjcjy5mmzvp7hfpei7eaz.o:     file format elf32-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x00000000

kzbmlgptuownevigg5e73lwwcs4ixby2.o:     file format elf32-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x00000000

6kjor4czrdmnjq7az7hdumwz7ba6opgv.o:     file format elf32-little
architecture: UNKNOWN!, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x00000000

here all these .o files are 32bit. and i want 64bit files.
where can i get those or how can i build those.?
please help.
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ -] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ -] Linux :  Ubuntu 20.04.2 LTS

- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @prachipsutane, please could contact your Amazon Solutions Architect for support with question like these. I am going to close this issue now. Thanks!
