### ISSUE TITLE
CANNOT LINK EXECUTABLE "/system/alexa/bin/SampleApp": library "libsqlite3.so" not found

### ISSUE THREAD

**Issue by AppropriateEagle** [alexa/avs-device-sdk#1902]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?
run avs

## What behavior are you observing?
error: dependency missing

## Provide the steps to reproduce the issue, if applicable:
bash startsample.sh 
WARNING: linker: Warning: "/system/alexa/bin/SampleApp" unused DT entry: DT_RPATH (type 0xf arg 0x5a18) (ignoring)
CANNOT LINK EXECUTABLE "/system/alexa/bin/SampleApp": library "libsqlite3.so" not found

## Tell us about your environment:
android 9 / ubuntu 20.04
### What version of the AVS Device SDK are you using?
      latest

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ X] Other - tell us more:adroid 9

### Tell us about your OS (Type & version):
- [ X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by caleighatamazon** [comment]
Hi there, can you confirm that you used our Android quick start guide to build the SDK Sample App for Android? https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/android.html
