### ISSUE TITLE
Alexa Comms is not working

### ISSUE THREAD

**Issue by Alexa-AUH** [alexa/avs-device-sdk#1904]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide)

## Briefly summarize your issue:
While running Alexa comms, failed to create SipUserAgentInterface_create which results in "Failed to create to SampleApplication!"

## What is the expected behavior?
Alexa should run with the Comms feature.

## What behavior are you observing?
Alexa is not working at all.

## Provide the steps to reproduce the issue, if applicable:
AVS SDK- 1.18
AlexaCommsLib_3.2.23
comms_adapter.1.6

[Alexa.txt](https://github.com/alexa/avs-device-sdk/files/6262983/Alexa.txt)

## Tell us about your environment:
Linux-Ubuntu 16.04

### What version of the AVS Device SDK are you using?
      1.18

### Tell us what hardware you're using:
Artik305

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by womw** [comment]
Hi @Alexa-AUH thanks for posting

Can you please reach out to your amazon representative to receive further support?
