### ISSUE TITLE
Should be used getScheduledTime_ISO_8601Locked instead. std::mutex - non recursive and current code lead to deadlock.

### ISSUE THREAD

**Issue by alexismailov2** [alexa/avs-device-sdk#1905]
https://github.com/alexa/avs-device-sdk/blob/f2dab7ee26e59caa41fa861e04df256fa8563ef1/capabilities/Alerts/acsdkAlerts/src/Alert.cpp#L823

**Comment by womw** [comment]
Hi @alexismailov2 thanks for posting.

Thanks for bringing this bug to our attention, we will be investigating this internally.

**Comment by kjkh** [comment]
This was fixed in 1.25. The printDiagnostic() function now calls non-locking versions of those methods.
