### ISSUE TITLE
Dead lock on non recursive mutex. may be can be used m_dynamicData.timePoint.getTime_Unix() directly.

### ISSUE THREAD

**Issue by alexismailov2** [alexa/avs-device-sdk#1906]
https://github.com/alexa/avs-device-sdk/blob/f2dab7ee26e59caa41fa861e04df256fa8563ef1/capabilities/Alerts/acsdkAlerts/src/Alert.cpp#L824

**Comment by womw** [comment]
Hello @alexismailov2 thanks for posting.

Thanks for bringing this bug to our attention, we will investigate this internally.

**Comment by kjkh** [comment]
This was fixed in 1.25. The printDiagnostic() function now calls non-locking versions of those methods.
