### ISSUE TITLE
AVS stops installing on Raspi

### ISSUE THREAD

**Issue by Pipopa** [alexa/avs-device-sdk#1908]
## Briefly summarize your issue:
I try to make my Raspberry Pi a Alexa. When I install the programm on my Pi it always stops at:
/home/pi/avs-device-sdk/thirdparty/rapidjson/rapidjson-1.1.0/include/rapidjson/document.h:578:7: note: class rapidjson ::GenericValue<rapidjson::UTF8<> declare class here class GemericValue {

## What is the expected behavior?
It should keep on installing. The tutorial said it will take 20 minutes but I waited over an hour each time

## What behavior are you observing?
Its just doing nothing

## Tell us about your environment:
Im working on a raspi 3a+ with the latest derbian console

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

**Comment by alexandrekm-amzn** [comment]
hi @Pipopa 
Thanks for reaching out. We will need extra info to be able to help you:
* which type of installation are you following? can you link the documentation?
* is this a raspberry pi 4? if so what operating system are you using? 
* please attach the complete build log in the ticket.

**Comment by Pipopa** [comment]
> hi @Pipopa
> Thanks for reaching out. We will need extra info to be able to help you:
> 
> * which type of installation are you following? can you link the documentation?
> * is this a raspberry pi 4? if so what operating system are you using?
> * please attach the complete build log in the ticket.


Hi @alexandrekm-amzn,
thanks for the quick response.

I'm following this installation: 
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html

I'm using a raspberry pi 3a+ with the Raspberry Pi OS Lite (2021-03-04)

The build log is:

pi@raspberrypi:~ $ sudo bash setup.sh config.json [-s 1234]
################################################################################
################################################################################


AVS Device SDK Raspberry pi Script - Terms and Agreements


The AVS Device SDK is dependent on several third-party libraries, environments,
and/or other software packages that are installed using this script from
third-party sources ("External Dependencies"). These are terms and conditions
associated with the External Dependencies
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that
you need to agree to abide by if you choose to install the External Dependencies                                                                                                                                                             .


If you do not agree with every term and condition associated with the External
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".


################################################################################
################################################################################
agree
################################################################################
Proceeding with installation
################################################################################
[ 29%] Built target AVSCommon
[ 31%] Built target SQLiteStorage
[ 31%] Built target SynchronizeStateSender
[ 34%] Built target RegistrationManager
[ 34%] Built target acsdkManufactory
[ 38%] Built target AudioResources
[ 38%] Built target Captions
[ 40%] Built target acsdkEqualizerImplementations
[ 43%] Built target acsdkBluetooth
[ 45%] Built target acsdkExternalMediaPlayerInterfaces
[ 47%] Built target acsdkNotifications
[ 52%] Built target ACL
[ 52%] Built target ADSL
[ 52%] Built target SystemSoundPlayer
[ 52%] Built target InterruptModel
[ 52%] Built target acsdkNullMetricRecorder
[ 52%] Built target SpeechEncoder
[ 54%] Built target acsdkStartupManager
[ 54%] Built target CBLAuthDelegate
[ 54%] Built target acsdkSystemClockMonitor
[ 56%] Built target AVSGatewayManager
[ 56%] Built target ContextManager
[ 56%] Built target acsdkShutdownManager
[ 56%] Built target CaptionsComponent
[ 59%] Built target PlaylistParser
[ 59%] Built target KWD
[ 59%] Built target ApiGateway
[ 59%] Built target InteractionModel
[ 59%] Built target PlaybackController
[ 59%] Built target SoftwareComponentReporter
[ 61%] Built target SpeechSynthesizer
[ 61%] Built target TemplateRuntime
[ 61%] Built target SDKComponent
[ 61%] Built target CertifiedSender
[ 63%] Built target MediaPlayer
Scanning dependencies of target DeviceSettings
[ 65%] Built target Alexa
[ 65%] Building CXX object EXTENSION/AudioPlayer/acsdkAudioPlayer/src/CMakeFiles                                                                                                                                                             /acsdkAudioPlayer.dir/AudioPlayer.cpp.o
[ 65%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/CloudContr                                                                                                                                                             olledSettingProtocol.cpp.o
[ 65%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/DeviceCont                                                                                                                                                             rolledSettingProtocol.cpp.o
[ 65%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/SettingEve                                                                                                                                                             ntSender.cpp.o
In file included from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Configuration/ConfigurationNode.h:28,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/Logger.h:25,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/LoggerUtils.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Optional.h:18,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityTag.h:22,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/NamespaceAndName.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityAgent.h:24,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/include/acsdkAudioPlayer/AudioPlayer.h:26,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/src/AudioPlayer.cpp:21:
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator                                                                                                                                                             >::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson                                                                                                                                                             ::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjso                                                                                                                                                             n::CrtAllocator; rapidjson::GenericValue<Encoding, Allocator>::Member = rapidjso                                                                                                                                                             n::GenericMember<rapidjson::UTF8<>, rapidjson::CrtAllocator>; rapidjson::SizeTyp                                                                                                                                                             e = unsigned int]’:
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2401:9:   required from ‘bool rapidjson::GenericDocument<Encoding, All                                                                                                                                                             ocator, StackAllocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjs                                                                                                                                                             on::UTF8<>; Allocator = rapidjson::CrtAllocator; StackAllocator = rapidjson::Crt                                                                                                                                                             Allocator; rapidjson::SizeType = unsigned int]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:1736:18:   required from ‘rapidjson::GenericReader<SourceEncoding, Targe                                                                                                                                                             tEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<Sourc                                                                                                                                                             eEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<Sou                                                                                                                                                             rceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::                                                                                                                                                             GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson:                                                                                                                                                             :GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsing                                                                                                                                                             State, InputStream&, Handler&) [with unsigned int parseFlags = 0; InputStream =                                                                                                                                                              rapidjson::GenericStringStream<rapidjson::UTF8<> >; Handler = rapidjson::Generic                                                                                                                                                             Document<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding                                                                                                                                                              = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReade                                                                                                                                                             r<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&,                                                                                                                                                              Handler&) [with unsigned int parseFlags = 0; InputStream = rapidjson::GenericStr                                                                                                                                                             ingStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::U                                                                                                                                                             TF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>;                                                                                                                                                              StackAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader                                                                                                                                                             <SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&)                                                                                                                                                              [with unsigned int parseFlags = 0; InputStream = rapidjson::GenericStringStream<                                                                                                                                                             rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; S                                                                                                                                                             ourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllo                                                                                                                                                             cator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2197:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::ParseStream(InputStream&) [with unsigned int parseFlags = 0; SourceEncodin                                                                                                                                                             g = rapidjson::UTF8<>; InputStream = rapidjson::GenericStringStream<rapidjson::U                                                                                                                                                             TF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAllocator; Stac                                                                                                                                                             kAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2262:55:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const typename SourceEncoding::Ch*) [with unsigned int parseFlags =                                                                                                                                                              0; SourceEncoding = rapidjson::UTF8<>; Encoding = rapidjson::UTF8<>; Allocator =                                                                                                                                                              rapidjson::CrtAllocator; StackAllocator = rapidjson::CrtAllocator; typename Sou                                                                                                                                                             rceEncoding::Ch = char]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2308:43:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const std::__cxx11::basic_string<typename ValueType::Ch>&) [with uns                                                                                                                                                             igned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::C                                                                                                                                                             rtAllocator; StackAllocator = rapidjson::CrtAllocator; typename ValueType::Ch =                                                                                                                                                              char]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2312:41:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const std::__cxx11::basic_string<typename ValueType::Ch>&) [with Enc                                                                                                                                                             oding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAllocator; StackAllocator =                                                                                                                                                              rapidjson::CrtAllocator; typename ValueType::Ch = char]’
/home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudioPlayer/src/AudioPlaye                                                                                                                                                             r.cpp:938:82:   required from here
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:1990:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing t                                                                                                                                                             o an object of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘                                                                                                                                                             struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::CrtAllocator>’} wi                                                                                                                                                             th no trivial copy-assignment; use copy-assignment instead [-Wclass-memaccess]
             std::memcpy(m, members, count * sizeof(Member));
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Configuration/ConfigurationNode.h:28,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/Logger.h:25,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/LoggerUtils.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Optional.h:18,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityTag.h:22,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/NamespaceAndName.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityAgent.h:24,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/include/acsdkAudioPlayer/AudioPlayer.h:26,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/src/AudioPlayer.cpp:21:
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:109:8: note: ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {ak                                                                                                                                                             a ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::CrtAllocator>’}                                                                                                                                                              declared here
 struct GenericMember {
        ^~~~~~~~~~~~~
In file included from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Configuration/ConfigurationNode.h:28,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/Logger.h:25,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Logger/LoggerUtils.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/                                                                                                                                                             Utils/Optional.h:18,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityTag.h:22,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/NamespaceAndName.h:21,
                 from /home/pi/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AV                                                                                                                                                             S/CapabilityAgent.h:24,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/include/acsdkAudioPlayer/AudioPlayer.h:26,
                 from /home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudi                                                                                                                                                             oPlayer/src/AudioPlayer.cpp:21:
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator                                                                                                                                                             >::SetArrayRaw(rapidjson::GenericValue<Encoding, Allocator>*, rapidjson::SizeTyp                                                                                                                                                             e, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAll                                                                                                                                                             ocator; rapidjson::SizeType = unsigned int]’:
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2409:9:   required from ‘bool rapidjson::GenericDocument<Encoding, All                                                                                                                                                             ocator, StackAllocator>::EndArray(rapidjson::SizeType) [with Encoding = rapidjso                                                                                                                                                             n::UTF8<>; Allocator = rapidjson::CrtAllocator; StackAllocator = rapidjson::CrtA                                                                                                                                                             llocator; rapidjson::SizeType = unsigned int]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:1766:18:   required from ‘rapidjson::GenericReader<SourceEncoding, Targe                                                                                                                                                             tEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<Sourc                                                                                                                                                             eEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<Sou                                                                                                                                                             rceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::                                                                                                                                                             GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson:                                                                                                                                                             :GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsing                                                                                                                                                             State, InputStream&, Handler&) [with unsigned int parseFlags = 0; InputStream =                                                                                                                                                              rapidjson::GenericStringStream<rapidjson::UTF8<> >; Handler = rapidjson::Generic                                                                                                                                                             Document<rapidjson::UTF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding                                                                                                                                                              = rapidjson::UTF8<>; StackAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReade                                                                                                                                                             r<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&,                                                                                                                                                              Handler&) [with unsigned int parseFlags = 0; InputStream = rapidjson::GenericStr                                                                                                                                                             ingStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::U                                                                                                                                                             TF8<> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>;                                                                                                                                                              StackAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/r                                                                                                                                                             eader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader                                                                                                                                                             <SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&)                                                                                                                                                              [with unsigned int parseFlags = 0; InputStream = rapidjson::GenericStringStream<                                                                                                                                                             rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<> >; S                                                                                                                                                             ourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllo                                                                                                                                                             cator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2197:22:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::ParseStream(InputStream&) [with unsigned int parseFlags = 0; SourceEncodin                                                                                                                                                             g = rapidjson::UTF8<>; InputStream = rapidjson::GenericStringStream<rapidjson::U                                                                                                                                                             TF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAllocator; Stac                                                                                                                                                             kAllocator = rapidjson::CrtAllocator]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2262:55:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const typename SourceEncoding::Ch*) [with unsigned int parseFlags =                                                                                                                                                              0; SourceEncoding = rapidjson::UTF8<>; Encoding = rapidjson::UTF8<>; Allocator =                                                                                                                                                              rapidjson::CrtAllocator; StackAllocator = rapidjson::CrtAllocator; typename Sou                                                                                                                                                             rceEncoding::Ch = char]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2308:43:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const std::__cxx11::basic_string<typename ValueType::Ch>&) [with uns                                                                                                                                                             igned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::C                                                                                                                                                             rtAllocator; StackAllocator = rapidjson::CrtAllocator; typename ValueType::Ch =                                                                                                                                                              char]’
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:2312:41:   required from ‘rapidjson::GenericDocument<Encoding, Allocat                                                                                                                                                             or, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAlloca                                                                                                                                                             tor>::Parse(const std::__cxx11::basic_string<typename ValueType::Ch>&) [with Enc                                                                                                                                                             oding = rapidjson::UTF8<>; Allocator = rapidjson::CrtAllocator; StackAllocator =                                                                                                                                                              rapidjson::CrtAllocator; typename ValueType::Ch = char]’
/home/pi/avs-device-sdk/capabilities/AudioPlayer/acsdkAudioPlayer/src/AudioPlaye                                                                                                                                                             r.cpp:938:82:   required from here
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:1977:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing t                                                                                                                                                             o an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no                                                                                                                                                              trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wc                                                                                                                                                             lass-memaccess]
             std::memcpy(e, values, count * sizeof(GenericValue));
             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson/d                                                                                                                                                             ocument.h:578:7: note: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ decla                                                                                                                                                             red here
 class GenericValue {
       ^~~~~~~~~~~~
[ 65%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/SettingEve                                                                                                                                                             ntRequestObserver.cpp.o
[ 65%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/SettingCon                                                                                                                                                             nectionObserver.cpp.o
[ 68%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/SharedAVSS                                                                                                                                                             ettingProtocol.cpp.o
[ 68%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/Storage/SQLiteDeviceSettingStorage.cpp.o
[ 68%] Building CXX object Settings/src/CMakeFiles/DeviceSettings.dir/Types/LocaleWakeWordsSetting.cpp.o
