### ISSUE TITLE
iOS AVS Not recognising Smart Home Devices in account

### ISSUE THREAD

**Issue by Ken-Howe** [alexa/avs-device-sdk#1914]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Not recognising Smart Home Devices in account, if I use the Alexa App or my Alexa device the smart home devices are recognised and the interaction works. I use LWA and the same account as my main Alexa account for my iOS App.. All the non smart home commands work as expected and I receive a response. But if I ask for a smart home comment linked to my account, then I always get a response saying there are no devices linked with Kens Account 

## What is the expected behavior?
Ask Alexa to interact with a Smart Home Device... eg "Alexa turn on Office Light"

## What behavior are you observing?
AVS returns there are no Smart Home Device on Kens Account

### What version of the AVS Device SDK are you using?
      3.0.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] iPhone

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other -iOS

**Comment by kjkh** [comment]
Hi @Ken-Howe,

Please attach DEBUG9 logs. Additionally, you clarify the version of the AVS SDK you're using? 3.0.0 is not an official release version, please see this list:

https://github.com/alexa/avs-device-sdk/releases

Also, to clarify, in what capacity are you using the AVS SDK? Have you created your own iOS app using the AVS SDK?

**Comment by Ken-Howe** [comment]
Apologies, posted in the wrong please... This is not an issue with the SDK as I'm getting responses. Its just that any request using Smart Home Devices does not work.
