### ISSUE TITLE
[Self test ID:267]Can not get current JP account information

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#1916]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

"AVS function self-check list [test case ID: 267]" requires the AVS APP to obtain account information. When I set the AVS APP language to JP and log in to my JP account, I cannot get the account information when i ask whose account is this, but when I use the same code to build the English version and log in to my English account, I can get the account information with the same question.

## Provide the steps to reproduce the issue, if applicable:

**Abnormal behavior:** 
1. Build JP version and login JP account
2. ask "alexa, これ は 誰 の アカウント です か" [means: alexa, Whose account is this?]
3. It will answer "わかりませんでした。すみません。"[means: i don't know, sorry] . 
      Or sometimes answer"すみません、その人はまだ知りませんが、これからもっとたくさんの人と知り合うのを楽しみにしています。" [means: I'm sorry, I don't know that person yet, but I'm looking forward to meeting more people in the future.]

=======================================================================================
**Normal behavior:**
1. Build English version and login my English account
2. ask "alexa, who's account is this"
3. It will answer"I'm not sure who's speaking, but you're in **Bob's account.** To teach me to recognize your voice, just say, Alexa, learn my voice."

Both the avsGateway and endpoint are "https://alexa.fe.gateway.devices.a2z.com"
My question: Why can not get account information in JP account?

### What version of the AVS Device SDK are you using?
      <1.22.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @BobXLiu, would you be able to attach the DEBUG9 log?  Thanks!

**Comment by BobXLiu** [comment]
Hi @kclchan,

The log information as below. Thanks!

JP log: 
[log_JP.txt](https://github.com/alexa/avs-device-sdk/files/6402324/log_JP.txt)

US log:
[log_US.txt](https://github.com/alexa/avs-device-sdk/files/6402328/log_US.txt)

**Comment by kclchan** [comment]
Hi @BobXLiu, I will file an ticket internally to investigate this.  Thanks.

**Comment by blazusiak-amazon** [comment]
Hello @BobXLiu,
Are you still experiencing this issue?

**Comment by blazusiak-amazon** [comment]
Hello @BobXLiu, 

Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
