### ISSUE TITLE
Keyword detection delay using wake word engine

### ISSUE THREAD

**Issue by alozach** [alexa/avs-device-sdk#1919]
When running the SampleApp, I have a delay of ~2sec between the end of the "Alexa" utterance and the actual detection of the keyword by the Sensory wake word engine.
The audio reading seems to be done correctly, ~8ms per call to `readFromStream`, and with the default value of `msToPushPerIteration` (10ms)

I have the exact same behavior after having integrated the Porcupine wake word engine.

The CPU usage is ~60% when Alexa is idle, but could it be a performance issue due to my environment?

### What version of the AVS Device SDK are you using?
      1.18.0

### Tell us what hardware you're using:
iMX6ULL arm Cortex-A7 (single 900MHz)

### Tell us about your OS (Type & version):
Custom Linux (kernel 4.9.11)

**Comment by kclchan** [comment]
Hi @alozach, 60% usage does seem very high when Alexa is idle.  Could you try disabling logging or use RELEASE build instead of DEBUG build to see if it makes a difference?

**Comment by alozach** [comment]
Hi @kclchan, thank you for your help
I was wrong about the CPU usage. I have done other tests, and I have 35-40% usage when idle (and 2-3% more with a debug build).

We currently have a custom version inspired by the SampleApp, but performing the keyword detection directly in a DSP, which notifies our integration when "Alexa" has been said. We wanted to evaluate the impact of using a third-party wakeword engine directly in our integration because of some problems related to our DSP.
The main difference in the Sensory version is the loop of `SensoryKeywordProvider` reading the audio stream and performing detection, whereas the DSP version does not use the stream for the detection.

Do you think it could be a portaudio/microphone issue, or that we should stick with our DSP integration?

**Comment by kclchan** [comment]
Unfortunately the Sensory wakeword engine is no longer supported by the SDK.  If you have an Alexa Business Representative, you can reach out to them for further questions.
