### ISSUE TITLE
Kindle book UI pause then verbal play results in "Sorry, music and radio playback are not supported on this device"

### ISSUE THREAD

**Issue by Mechan0** [alexa/avs-device-sdk#1924]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Doing the self tests for Kindle book playback, testing playback initiation via the official Amazon app on iOS to our device, then pausing on the official app UI correctly results in our device pausing playback. But a verbal "play" command results in Alexa responding "Sorry, music and radio playback are not supported on this device". This test is necessary for the device to pass testing, so although our device does not support music playback this should be a supported usecase.

The device should resume the audiobook correctly after receiving a "play" command, rather than giving an error as if we requested music playback.
## What behavior are you observing?
The device responds "Sorry, this device does not support music or radio playback" when requesting "play" or "resume" rather than continuing to play the audio book.

## Provide the steps to reproduce the issue, if applicable:

1. Setup our device with a logged in and authorized account
2. Open the official iOS Alexa app on another device 
3. Go to Play -> Select a Kindle book -> Select our device
4. Once audiobook playback begins, pause with the official Alexa iOS app UI, which pauses playback on our device
5. On our device, push to talk and say "Play" as specified in the test document
6. Alexa responds "Sorry, this device does not support music or radio playback"

### What version of the AVS Device SDK are you using?
      1.23

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
iPad Pro

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
iOS 13

**Comment by Mechan0** [comment]
[Kindle test error.txt](https://github.com/alexa/avs-device-sdk/files/6417103/Kindle.test.error.txt)
DEBUG9 logs

**Comment by blazusiak-amazon** [comment]
Hello @Mechan0,
Are you still experiencing this issue? Are you able to recreate this issue on the latest SDK Version?

**Comment by blazusiak-amazon** [comment]
Hello @Mechan0,
I will be closing this ticket due to inactivity. If this issue persists, please feel free to cut a new ticket.
