### ISSUE TITLE
Saving audio response from AVS to .mp3 files

### ISSUE THREAD

**Issue by mkb878** [alexa/avs-device-sdk#1926]
## Briefly summarize your issue:
I would like to be able to save audio responses from the AVS to .mp3 files (including both synthesised speech responses and other audio files that may contain speech). I am grateful for any advice on the best way to do this. I have looked at previous issues on this topic - such as https://github.com/alexa/avs-device-sdk/issues/14 , but have not been able to implement the solutions discussed previously, I am not sure where the code to save audio responses should be added. 

### What version of the AVS Device SDK are you using?
      1.23.0

### Tell us what hardware you're using:
 Ubuntu virtual machine on a desktop host.

### Tell us about your OS (Type & version):
 Ubuntu 18.04

**Comment by alexandrekm-amzn** [comment]
hi @mkb878 
The SDK uses curl to communicate with servers.
HTTP2Stream.cpp in ACL has code that can emit verbose libcurl diagnostics.  These diagnostics are in the form of three files output per stream
    * Hex dump of all transfers annotated with libcurl debug messages
    * Raw data sent
    * Raw data received  (this is what you are interested in)

To enable this feature, the SDK must be re-build from the cmake step with the options:

-DACSDK_EMIT_CURL_LOGS=ON -DACSDK_EMIT_SENSITIVE_LOGS=ON

An additional option is required in AlexaClientSDKConfig.json to specify where these files are to be written:

{  "libcurlUtils" : { "streamLogPrefix" : "<absolute path to put log files (including terminal forward slash)>" } }


After you run the sampleApp with those options go to the directory you specified in the config file and run this command

```
for f in $(ls stream-*in.bin)
do
  echo ---- $f
  hexdump $f | grep fffb
done
```
You will see an output like this:

```
---- stream-52263370623582-AVSEvent-7-in.bin
00028d0 1019 7a48 ea65 1162 fffb 64f3 29c4 e125
0005540 ab72 fcb9 cdb6 da99 fffb 64f3 1ec4 5b21
```
this means that this is a mp3 file (output from alexa), rename the file to mp3 and you can play it.

I hope this is detailed, easy and will help you. Please let me know if that works.

Regards,
-Alexandre
