### ISSUE TITLE
That feature is only available on certified alexa builtin devices

### ISSUE THREAD

**Issue by royka1** [alexa/avs-device-sdk#1927]
## Briefly summarize your issue:
I've followed the docs on Amazon to install Alexa on a Raspberry Pi, this worked good for about a year, since an hour ago it stopped working correctly. No matter what I say, it responds by saying with "feature is only available on certified alexa builtin devices"

## What is the expected behavior?
To answer the questions and execute the orders.

## What behavior are you observing?
The same answer for everything

## Provide the steps to reproduce the issue, if applicable:
Saying "Alexa ...."

### What version of the AVS Device SDK are you using?
      1.21

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Debian 10.4

**Comment by thardbarger** [comment]
I’ve experienced the same issue starting today.

**Comment by GitHubUser4234** [comment]
Yes, same here, the prototypes stopped working, even the simplest commands like "Can you hear me" or "Good morning" result in Alexa saying the feature was only available on certified Alexa builtin devices :fearful:

Please help, thanks!

**Comment by caleighatamazon** [comment]
We're taking a look. Thanks for reporting this!

**Comment by royka1** [comment]
@caleighatamazon It's working again. But are there plans to stop the service for non certified devices?

**Comment by thardbarger** [comment]
It's working again for me also. Many thanks!

**Comment by smirkhani** [comment]
@caleighatamazon - We are encountering this same issue from yesterday. I found this post by searching the error message. Can you please help us to resolve the issue?

**Comment by cherylatamazon** [comment]
@smirkhani Answered this question here: https://github.com/alexa/avs-device-sdk/issues/1993
