### ISSUE TITLE
AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2

### ISSUE THREAD

**Issue by SivaNallamalli** [alexa/avs-device-sdk#1931]
## Briefly summarize your issue:
< SampleApp throwing an error curlDoesNotSupportHTTP2 though  i enabled curl with http2 support

curl -I https://nghttp2.org/ 
HTTP/1.1 200 OK
Date: Mon, 24 May 2021 15:22:13 GMT
Content-Type: text/html
Last-Modified: Tue, 02 Feb 2021 11:41:51 GMT
Etag: "60193a7f-19d8"
Accept-Ranges: bytes
Content-Length: 6616
X-Backend-Header-Rtt: 0.001771
Strict-Transport-Security: max-age=31536000
Server: nghttpx
Via: 2 nghttpx
alt-svc: h3-29=":443"; ma=3600
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff

 curl -V
curl 7.69.1 (arm-poky-linux-gnueabi) libcurl/7.69.1 GnuTLS/3.6.8 (OpenSSL/1.1.1g) zlib/1.2.11 libidn2/2.0.5
Release-Date: 2020-03-11
Protocols: file ftp ftps http https pop3 pop3s smb smbs smtp smtps 
Features: AsynchDNS HTTPS-proxy IDN IPv6 Largefile libz MultiSSL NTLM SSL TLS-SRP UnixSockets >

## What is the expected behavior?
< SampleApp should run >

## What behavior are you observing?
< SampleApp fails with AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2 >

## Provide the steps to reproduce the issue, if applicable:
< i am using yocto recipe with modification to build image. https://github.com/cesarjhernandez/meta-avs-demos/tree/master/recipes-avs/avs-device-sdk>

### What version of the AVS Device SDK are you using?
      <i am using avs-devie-sdk 1.23.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more: beagleboard based custom board.

### Tell us about your OS (Type & version):
- [ ] Linux 
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
 Linux kernel  4.19.160-rt69-gb3a2247aae

**Comment by kjkh** [comment]
Hi @SivaNallamalli,

A possibility here is that while you have compiled curl correctly, this version of curl is not being used when compiling the AVS SDK.

You can change this by explicitly specifying the location of the curl library and headers with the following cmake flags: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#curl_library

**Comment by garmin-holder** [comment]
I wanted to check on what support the SDK currently has for Sidewalk network. I’ve been asked to verify that our 3rd party device will not get pulled into the Sidewalk. From what I can tell the SDK doesn’t add support for Sidewalk, but wanted to verify that.

________________________________

CONFIDENTIALITY NOTICE: This email and any attachments are for the sole use of the intended recipient(s) and contain information that may be Garmin confidential and/or Garmin legally privileged. If you have received this email in error, please notify the sender by reply email and delete the message. Any disclosure, copying, distribution or use of this communication (including attachments) by someone other than the intended recipient is prohibited. Thank you.

**Comment by kclchan** [comment]
Hi @garmin-holder, the SDK doesn't add support for Sidewalk.
