### ISSUE TITLE
Stuck on Build

### ISSUE THREAD

**Issue by TheBozzz34** [alexa/avs-device-sdk#1932]
Building the Amazon SDK from the Amazon Developer docs works up until
 `[ 90%] Building CXX object ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClientComponent.cpp.o`
Where it immediately gets stuck and the entire pi has to be rebooted. I am fairly certain its not a thermal issue since it has an ICE Cooler from GeeekPi

## What is the expected behaviour?
Build should continue to `[100%] Built Target SampleApp`

## What behavior are you observing?
Raspi completely freezes

## Provide the steps to reproduce the issue, if applicable:
get setup scripts, then run `sudo bash setup.sh config.json [-s 1234]`

### What version of the AVS Device SDK are you using?
      AVS Version 1.23.0
      

### Tell us what hardware you're using:
Raspberry Pi 4 Model B Rev 1.1

### Tell us about your OS (Type & version):
Raspbian GNU/Linux 10 (buster) armv7l

**Comment by TheBozzz34** [comment]
No there are not any errors, it just simply freezes, i'll modify the setup.sh as soon as i can and report the results

**Comment by kclchan** [comment]
Hi @TheBozzz34, can you try increasing the swap memory size.  You can refer to #1856

**Comment by TheBozzz34** [comment]
Hello, sorry for the lat response, i tried both solutions, but to no avail,
it still gets stuck at
`[ 90%] Building CXX object
ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClientComponent.cpp.o`
