### ISSUE TITLE
SampleApp don't start

### ISSUE THREAD

**Issue by Panp59** [alexa/avs-device-sdk#1938]
## Briefly summarize your issue:
All seems to be allright but sampleApp crashes after asking authorization

## What behavior are you observing?
command launched :

> PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
> configFile ./Integration/AlexaClientSDKConfig.json

result :
```
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: *****       #
################################################################################################

#################################################
#       Checking for authorization (1)...       #
#################################################

Illegal instruction

```

### Tell us what hardware you're using:
- [x] Raspberry Pi

Mic is ok, I can record and listen.
I can register the code on the url, but it changes at every time and the app don't start better...

**Comment by kclchan** [comment]
Hi @Panp59, which version of the Raspberry Pi are you using?  Please note that in [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html) the prerequisites is Raspberry Pi 3 or 4.

**Comment by Panp59** [comment]
Hi,

Yes indeed that s a pi2  😔
No way to run it ?

**Comment by ereich1217** [comment]
You can use other Raspberry Pis, but you can't use the Sensory Wake word engine.   You can use the Kitt.AI wake word engine without any issue.

**Comment by Panp59** [comment]
OK that's great. How could I register the app ? Or at least to have some logs to debug ?

**Comment by blazusiak-amazon** [comment]
Hello @Panp59,

**Comment by blazusiak-amazon** [comment]
Hello @Panp59,

**Comment by blazusiak-amazon** [comment]
Hello @Panp59,
Are you still experiencing issues setting up SampleApp on your Raspberry Pi?
