### ISSUE TITLE
what caused CLIENT_ERROR_BAD_REQUEST at sending audio?

### ISSUE THREAD

**Issue by xlb767923274** [alexa/avs-device-sdk#1945]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After wakeword, when sending audio, CLIENT_ERROR_BAD_REQUEST was returned, and then AIP switched from RECOGNIZING to IDLE directly, and stop capture audio, what caused CLIENT_ERROR_BAD_REQUEST?

## What is the expected behavior?

Normal recording, send audio and receive directives

## What behavior are you observing?

The recording was interrupted

## Provide the steps to reproduce the issue, if applicable:

Any interaction

### What version of the AVS Device SDK are you using?
      <x.y.z>
mmsdk 2.5.0 + avs sdk1.22.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:   RK3326/PX30

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ *] Other - tell us more:    android8.1

logfile(DEBUG9)
[speaker_20210629-020435.log](https://github.com/alexa/avs-device-sdk/files/6761195/speaker_20210629-020435.log)

**Comment by kjkh** [comment]
Hi,

Apologies for the delayed response. Can you comment on if this has always happened or if this is a sudden development? If this is still reproducible, can you please attach fresh DEBUG9 logs? I was unable to find cloud side logs for your request, which may be due to them expiring.

**Comment by xlb767923274** [comment]
thanks for replay， here is the newest DEBUG9 log  ：

 C:\Users\Administrator\Downloads\TTS无回复14：26分\speaker_20210719-102900.log (6 hits)
	Line 30479: 07-19 11:40:26.333 D/AlexaSampleApp( 3268): [ 3e] 0 AudioInputProcessor:onSendCompleted:status=CLIENT_ERROR_BAD_REQUEST
	Line 30480: 07-19 11:40:26.333 D/AlexaSampleApp( 3268): [ 3e] 0 AudioInputProcessor:resetState:dueToStatus=CLIENT_ERROR_BAD_REQUEST
	Line 31164: 07-19 11:40:50.789 D/AlexaSampleApp( 3268): [ 3e] 0 AudioInputProcessor:onSendCompleted:status=CLIENT_ERROR_BAD_REQUEST
	Line 31166: 07-19 11:40:50.789 D/AlexaSampleApp( 3268): [ 3e] 0 AudioInputProcessor:resetState:dueToStatus=CLIENT_ERROR_BAD_REQUEST
	Line 120498: 07-19 14:25:08.646 D/AlexaSampleApp( 3268): [ 8e] 0 AudioInputProcessor:onSendCompleted:status=CLIENT_ERROR_BAD_REQUEST
	Line 120499: 07-19 14:25:08.646 D/AlexaSampleApp( 3268): [ 8e] 0 AudioInputProcessor:resetState:dueToStatus=CLIENT_ERROR_BAD_REQUEST




[speaker_20210719-102900.log](https://github.com/alexa/avs-device-sdk/files/6844750/speaker_20210719-102900.log)

**Comment by kjkh** [comment]
Hi,

Are you still experiencing this problem?

**Comment by blazusiak-amazon** [comment]
Hello @xlb767923274, 

Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
