### ISSUE TITLE
AVS android app does not detect alexa custom skill. avs app commands not added in alexa history.

### ISSUE THREAD

**Issue by aneesu401** [alexa/avs-device-sdk#1946]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

AVS android app does not detect alexa custom skill. avs app commands not added in alexa history.

## What is the expected behavior?

AVS android app should detect alexa custom skills. avs app commands should also be visile in alexa history.

## What behavior are you observing?

AVS android app does not detect alexa custom skill. avs app commands not added in alexa history. 

## Provide the steps to reproduce the issue, if applicable:

I created a Custom Alexa skill(reference1) and AVS sdk integrated android app(reference2). Then I enabled skilled skill in Alexa app, Add beta test user. Alexa default skills are working with my android app. But the custom skill is not working with AVS sdk integrated android app.

With Alexa Test Simulator [Custom skill is working]
With Alexa App in Android Phone [Custom skill is working]
With MyApp(AVS SDK Integrated) in Android Phone [Custom skill is NOT working]

Some forum says after setting language to EN-US should work, in my case that also did not solve issue.

reference1: https://medium.com/crowdbotics/how-to-build-a-custom-amazon-alexa-skill-step-by-step-my-favorite-chess-player-dcc0edae53fb
reference2: https://github.com/evil0327/Alexa-On-Android/tree/master/AlexaDemo

Used same amazon account for avs login and alexa skill for which beta test is enabled.
"Development" option is already enabled in Alexa "Test" tab.
My skill is already enabled in alexa web "skill" section.

Working Voice Request through Alexa "Test" Tab:
alexa ask demo command to launch custom
reply: custom
history is recorded in Alexa website

Not-Working Voice Request through AVS app:
alexa ask demo command to launch custom
reply is: Did you mean jesus command
history is NOT recorded in Alexa website

My AVS voice call:

            String url = new StringBuilder()
                    .append(mContext.getString(R.string.alexa_api))
                    .append("/")
                    .append(mContext.getString(R.string.alexa_api_version))
                    .append("/")
                    .append("events")
                    .toString();

            Request.Builder requestBuilder = new Request.Builder();
            requestBuilder.url(url);
            requestBuilder.addHeader("Authorization", "Bearer " + LoginManager.getToken());

            String event = Event.getSpeechRecognizerEvent();
            MultipartBody.Builder bodyBuilder = new MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("metadata", "metadata", RequestBody.create(MediaType.parse("application/json; charset=UTF-8"), event));
            bodyBuilder.addFormDataPart("audio", "speech.wav", RequestBody.create(MediaType.parse("application/octet-stream"), fileBytes));
            requestBuilder.post(bodyBuilder.build());
            Request request = requestBuilder.build();

            Call currentCall = ClientUtil.getTLS12OkHttpClient().newCall(request);

            try {
                Response response = currentCall.execute(); 

### What version of the AVS Device SDK are you using?
      <v20160207>

### Tell us what hardware you're using:
- [ ] Samsung M21, Moto G3
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Android 11, Android 10, Android 6

**Comment by kjkh** [comment]
Hi,

This forum is only for issues related to the avs-device-sdk. It appears that you are using a reference implementation form another repository, which we do not have the knowledge to support.

Please take a look through this document for a list of commonly asked questions.
https://developer.amazon.com/en-US/docs/alexa/custom-skills/skills-beta-testing-for-alexa-skills.html

In particular, please ensure that the account you're using to test the skill has been allow listed for your customer skill, and that the region of your skill matches those of the device:

> What if my beta tester uses a device that has a different region and locale than my skill?
> If your skill is available for all regions, or available for the same region and locale as that of the beta tester's device, then they can use your skill. If your beta tester uses a device with a different region and locale than your skill, then they will not be able to use your skill.

If that FAQ does not help, another option is to reach out to the ASK forum: https://amazon.developer.forums.answerhub.com/spaces/23/index.html.
