### ISSUE TITLE
Failed to cancel Alarm -- certification case [Alarm-cancel]

### ISSUE THREAD

**Issue by xlb767923274** [alexa/avs-device-sdk#1947]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

can't cancel alarm

## What is the expected behavior?

alarm can be canceled

## What behavior are you observing?

alexa said that "Your alarm is not set."

## Provide the steps to reproduce the issue, if applicable:

1. set alarm for one minute  
   ->alexa said that, "1 minute, starting now"
2. cancel alarm (before alarm arrives)
   ->alexa said that, "Your alarm is not set."

### What version of the AVS Device SDK are you using?
      <x.y.z> = 1.24.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more: RK3326/PX30

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

screenshot from Review Voice History
![failedtocancel](https://user-images.githubusercontent.com/49935559/125770170-46bc729e-d4a7-4e32-9e08-3c3c177a8378.png)

**Comment by kjkh** [comment]
Hi @xlb767923274,

The problem here is due to the nuance between Alarms and Timers. When you said set an alarm for one minute, Alexa created a Timer for you (Timers are duration based, Alarms are timestamp based). 

I just tested this, and saying "Alexa, cancel the timer" successful stops it. If these are the exact wording on the certification test that is expected, please reach out to the certification team to further clarify this.

**Comment by xlb767923274** [comment]
> Hi @xlb767923274,
> 
> The problem here is due to the nuance between Alarms and Timers. When you said set an alarm for one minute, Alexa created a Timer for you (Timers are duration based, Alarms are timestamp based).
> 
> I just tested this, and saying "Alexa, cancel the timer" successful stops it. If these are the exact wording on the certification test that is expected, please reach out to the certification team to further clarify this.

thanks for reply， we will check the case with certification team.
