### ISSUE TITLE
yocto build support

### ISSUE THREAD

**Issue by moose-rivieh** [alexa/avs-device-sdk#1949]
There was no documentation on how to include this library in a yocto build? Is this not possible?

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: NXP using yocto generated Linux image.

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
@moose-rivieh, we currently do not have plans to support yocto.  Thanks for your interest in the project.
