### ISSUE TITLE
Could you supply a param switch to control compile sdk test or not

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#195]
Hi avs team

Could you supply a param switch to control compile sdk test or not

**Comment by mradulan** [comment]
Hi @sundq , do you mean you want to compile the test code separately?

**Comment by sundq** [comment]
@mradulan No, I mean compile the sdk without compile test code， you know the compile take long time.

**Comment by mradulan** [comment]
you can comment all lines which come in the output of 
grep -r "add_subdirectory(\"test\")" .
By that you will be only building the source code and not test code.

**Comment by sundq** [comment]
Yes, it works, But every time we upgrade the sdk, we should do comment test again, you can supply a param like cmake -DTEST.

**Comment by mradulan** [comment]
Hi @sundq , if you are trying to build only SampleApp, you can do 'make SampleApp' and it will only build files needed for SampleApp, not test files. If you want to build entire SDK without test files build it as 'make ACL ADSL AFML ....' with all the components but without the test files in them.

**Comment by kclchan** [comment]
Hi @sundq, we will add a way to disable building the tests in our future release.  In the meantime, please try the suggestions made by @mradulan.  Thanks!
