### ISSUE TITLE
AVS do not support multiple logout/login

### ISSUE THREAD

**Issue by rom-vdb** [alexa/avs-device-sdk#1950]
## Briefly summarize your issue:
AVS do not support well multiple logout/login, threads are leaking and oom crash occurs

## What is the expected behavior?
multiple logout/login support without leaks

## What behavior are you observing?
Some threads are leaking, RSS memory is increasing (more than 2Mbytes per logout/login)

## Provide the steps to reproduce the issue, if applicable:
using avs in smart screen patching the version to call resetDevice when pressing navigation button
or in our smart screen set top box integration

### What version of the AVS Device SDK are you using?
avs 1.24.0
smart screen 2.7.0

### Tell us what hardware you're using:
- linux ubuntu PC
or
- bcm7268 set top box

### Tell us about your OS (Type & version):
- [x ] Linux

I have seen a first fix in smart screen 2.7.0 solving the serverThread leak issue

But in avs code, I see at least that other threads leaking:
- mediaplayer workerloop threads: (8 threads added per logout/login)
- DirectiveSequencer::receivingLoop (3 threads added per logout/login)
- TimerDelegate::timerLoop (2 threads added per logout/login)
- CertifiedSender::mainloop() (1 thread added per logout/login)

**Comment by kjkh** [comment]
Hi,

Can you clarify if you are using the SampleApp from the AVS SDK, the SampleApp from the Smart Screen SDK or your own application?

Are you tearing down DefaultClient completely between restarts?

**Comment by rom-vdb** [comment]
Hello Keith,

In the steps to reproduce I wrote
_using avs in smart screen patching the version to call resetDevice when pressing navigation button
or in our smart screen set top box integration_

So to be more precise, I use **smartscreen vanilla ubuntu sample app** + a little patch to call the resetDevice function when pressing navigation button
(I have also the same leak issue using our smartscreen sample app integration in our STB device)
here is the patch:
```
void GUIManager::handleNavigationEvent(smartScreenSDKInterfaces::NavigationEvent event) {
-    m_executor.submit([this, event]() {
         ACSDK_DEBUG3(LX(__func__).d(
             "processNavigationEvent in executor", smartScreenSDKInterfaces::navigationEventToString(event)));
 
         // TODO : Implement more robust visual presentation and granular channel orchestration for local navigation
         switch (event) {
             case smartScreenSDKInterfaces::NavigationEvent::BACK:
-                executeBackNavigation();
+                // executeBackNavigation();
+                resetDevice();
                 break;
             case smartScreenSDKInterfaces::NavigationEvent::EXIT:
-                executeExitNavigation();
+                //executeExitNavigation();
+                ACSDK_DEBUG3(LX(__func__).d(
+                    "RVDB", smartScreenSDKInterfaces::navigationEventToString(event)));
+                resetDevice();
                 break;
             default:
                 // Not possible as returned above.
                 break;
         }
-    });
 }
```
So I am only calling resetDevice.
Can you tell me how to tear down DefaultClient properly using smartscreen sample app ?

**Comment by kjkh** [comment]
Unfortunately that is outside the scope this forum. I suggest posting this issue to https://github.com/alexa/alexa-smart-screen-sdk.

However, if you can determine that DefaultClient has been shutdown, yet there is still a memory leak, then please reach back to us.

Regarding the MediaPlayers, can you also ensure that those objects are not being kept alive even after they've been passed into DefaultClient.

**Comment by rom-vdb** [comment]
hello @kjkh 
I am a little bit lost, since @sngoc-amazon answered me to open an issue here in a comment of https://github.com/alexa/alexa-smart-screen-sdk/issues/97
Ok, I will try to understand how DefaultClient is initialized (and maybe not closed ?) in the vanilla smartscreen sampleapp context, but as far as I understand, it concerns a vanilla sample app, I was thinking you were interested

**Comment by blazusiak-amazon** [comment]
This issue is being tracked in the [Alexa Smart Screen SDK forum](https://github.com/alexa/alexa-smart-screen-sdk/issues/97)
