### ISSUE TITLE
Audio playback not supported on this device

### ISSUE THREAD

**Issue by MuQ-dev** [alexa/avs-device-sdk#1952]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I installed avs on my raspberry pi 4, and when I try to play music, I get this: "Audio playback not supported on this device"
I have looked at the Music Service Validation, but I am pretty lost here.
### What version of the AVS Device SDK are you using?
      <x.y.z> Latest Version, Sample App

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [x] Other - tell us more:
Raspberry Pi 4

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
Raspberry Pi OS

**Comment by kjkh** [comment]
Hi,

Unfortunately music playback is only supported on certified devices. If you have an Alexa Business Representative, you can reach out to them for further questions.
