### ISSUE TITLE
Audio feedback is not available for alexa actions/responses involving overlay display.  

### ISSUE THREAD

**Issue by sudharsantel** [alexa/avs-device-sdk#1953]
## Briefly summarize your issue:
When we invoke any action/command using alexa that involves overlay display, audio feedback is not available. For example, when we invoke alexa and say "what is the weather in newyork". It display's an overlay with climate information with out any audio feedback.

## What is the expected behavior?
Audio feedback should be available along with overlay display.

## What behavior are you observing?

Only overlay display is available. No audio feedback is observed

## Provide the steps to reproduce the issue, if applicable:
Invoke sample app client with wake word detection from smart screen sdk.

### What version of the AVS Device SDK are you using?
     avs device sdk version - 1.23.0
     avs smart screen sdk version - 2.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sudharsantel** [comment]
[alexa-weather-debug.txt](https://github.com/alexa/avs-device-sdk/files/6946236/alexa-weather-debug.txt)

**Comment by sudharsantel** [comment]
[alexa-weather-debug-log.txt](https://github.com/alexa/avs-device-sdk/files/6992371/alexa-weather-debug-log.txt)

Latest log file uploaded.

**Comment by kjkh** [comment]
Hi,

I do not see a Speak directive coming down from the cloud. Has this recently stopped working, or has this never worked? Do you receive audio from the cloud for other utterances such as "Alexa, Tell me a Joke?"

**Comment by blazusiak-amazon** [comment]
Due to over 2 months of inactivity from the original requester, this issue will be closed. If the requester feels that the issue has not been fully resolved and still requires support they may submit a new issue.
