### ISSUE TITLE
Illegal instruction error while intializing sample app

### ISSUE THREAD

**Issue by Anandkrizz** [alexa/avs-device-sdk#1956]
### What version of the AVS Device SDK are you using?
      <>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [o] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [o] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ereich1217** [comment]
What type of Raspberry Pi are you using?
Do you have the Sensory wake word enabled?

**Comment by Anandkrizz** [comment]
> What type of Raspberry Pi are you using?
> Do you have the Sensory wake word enabled?

Im using **Raspberry pi version B+ rev 1.2** and it shows alexa service active and running i tried recording audio with mic and played it back its working fine ( on a different method https://nematicslab.com/amazon-alexa-on-raspberry-pi/ shown in this website and it was fast and easy ,no errors ( after the reboot it says hello and its not responding tried many times calling alex, idont know whats the issue. Is it audio in or out or because of the older version of pi : (
**i dont know more about this sensory or kitt.ai some says sensory dosent work on older version .**
Now im using Rasbian Stretch , when i was using Rasbian buster it shows error creating sample app failed. it got fixed after installing older version stretch. the issue here is with different method of installation , thanks @ereich1217  for the reply, if u know any step by step process it would be helpful. coz im not an expert in these kind of things so..

**Comment by Anandkrizz** [comment]
@ereich1217  
● **AlexaPi.service** - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled; vendor preset: enabled)
   Active: **active (running)** since Wed 2021-08-11 16:44:23 IST; 12min ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
 Main PID: 367 (python3)
   CGroup: /system.slice/AlexaPi.service
           └─367 /usr/bin/python3 /opt/AlexaPi/src/main.py --daemon

Aug 11 16:46:21 raspberrypi python3[367]: ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM
Aug 11 16:46:21 raspberrypi python3[367]: Expression 'alsa_snd_pcm_hw_params_set_period_size_near
Aug 11 16:46:28 raspberrypi python3[367]: /opt/AlexaPi/src/main.py:71: YAMLLoadWarning: calling y
Aug 11 16:46:28 raspberrypi python3[367]:   config = yaml.load(stream)
Aug 11 16:46:28 raspberrypi python3[367]: INFO: Checking Internet Connection ...
Aug 11 16:46:30 raspberrypi python3[367]: INFO: Connection OK
Aug 11 16:46:30 raspberrypi python3[367]: INFO: AVS token: Requesting a new one
Aug 11 16:46:31 raspberrypi python3[367]: INFO: AVS token: Obtained successfully
Aug 11 16:46:59 raspberrypi python3[367]: INFO: Triggered: pocketsphinx
Aug 11 16:47:09 raspberrypi python3[367]: INFO: Triggered: pocketsphinx
~

**Comment by ereich1217** [comment]
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html

Required hardware
Raspberry Pi – Use a Raspberry Pi 3 or 4.

The easiest way to resolve this is to get a Pi 3 or 4.

**Comment by Anandkrizz** [comment]
> https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html
> 
> Required hardware
> Raspberry Pi – Use a Raspberry Pi 3 or 4.
> 
> The easiest way to resolve this is to get a Pi 3 or 4.

But some of the guys installed it on older pi's  , is there any way?
to fix?

**Comment by ereich1217** [comment]
You can as long as you don't use sensory.  If you use kitt.ai then it will
work.

Le mer. 11 août 2021 21 h 58, Anandkrizz ***@***.***> a
écrit :

**Comment by Anandkrizz** [comment]
> You can as long as you don't use sensory.  If you use kitt.ai then it will
> work.

How can I install it using kitt.ai ? Is there any tutorials or something?

**Comment by kjkh** [comment]
Hi,

It looks like you are using the AlexaPi project, which is not affiliated with the avs-device-sdk project. Unfortunately, we cannot provide further support on that.

If you wish to try setting up your Pi using the avs-device-sdk, please refer to these guides:

https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html

As noted in this thread, the official supported versions for Raspberry Pi are: **Raspberry Pi 3 or 4.** You may try with older versions, but we cannot guarantee their functionality.
