### ISSUE TITLE
Failed to create SampleApplication!

### ISSUE THREAD

**Issue by Renthner** [alexa/avs-device-sdk#1958]
## Briefly summarize your issue:
I followed this tutorial for my Alexa on my RasPi 4: https://developer.amazon.com/de-DE/docs/alexa/avs-device-sdk/raspberry-pi.html
I just don't have a mic to record. So I will just use it as a Music-Player.

## What is the expected behavior?
It should give me this lines:
```
 ##################################
 #       NOT YET AUTHORIZED       #
 ##################################
 ################################################################################################
 #       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: {XXXX}       #
 ################################################################################################
```

## What behavior are you observing?
When I input the command it gives back "Failed to create SampleApplication!"
```
root@raspberrypi:/home/pi/sdk-folder/sdk-build# PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
configFile ./Integration/AlexaClientSDKConfig.json
Failed to create SampleApplication!
```

## Provide the steps to reproduce the issue, if applicable:
As I said, I just follow the manual here: https://developer.amazon.com/de-DE/docs/alexa/avs-device-sdk/raspberry-pi.html

### What version of the AVS Device SDK are you using?
      <The newest right now? (10th August 2021)>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other: Raspberry Pi OS

**Comment by Renthner** [comment]
Sadly I still have the problem.
The Thread of @don-boucher didn't help me...
Has anyone an idea how to fix it?

**Comment by kjkh** [comment]
Hi,

Can you please ensure you have built in DEBUG mode and attach DEBUG9 logs?

**Comment by Renthner** [comment]
Hi @kjkh,

I don't know if I built in DEBUG mode... Where can I see if I was building in DEBUG mode?

Greetings

**Comment by naihchams1** [comment]
Hi @Renthner,
Did you find any solution? I am currently facing the same issue.
Regards,

**Comment by Renthner** [comment]
Hey, @naihchams1,

I gave up ... I meanwhile bought an Alexa when it was on sale. Maybe I'll try again soon, but I don't need it right now.

Regards
