### ISSUE TITLE
Failed to install avs-device-sdk make: *** [Makefile:3663: SampleApp] Error 2

### ISSUE THREAD

**Issue by SnEhERANDE** [alexa/avs-device-sdk#1960]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi I am following this tutorial - https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/windows-64.html
I am stuck at https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/windows-64.html#step-5-download-the-sdk-and-dependencies
I am getting errors while installing  it is throwing errors I tried running this more than one time but same errors are coming these are the errors - 
![tmp_error](https://user-images.githubusercontent.com/62797634/129676603-aa45eb1b-5d34-4180-982d-1871f65d0d0b.JPG)

## What is the expected behavior?

I want the SDK to run properly as shown in the tutorial
## What behavior are you observing?

But it is throwing errors and not creating the "startsample.bat"
## Provide the steps to reproduce the issue, if applicable:

Just do everything the tutorial said on windows 8.1 laptop
## Tell us about your environment:

I am using windows 8.1 and the ram is 16 GB and cpu is 3.1 GHZ.
### What version of the AVS Device SDK are you using?
      I don't know I am installing and I am new to AVS.

### Tell us what hardware you're using:
-  Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- Other - tell us more: I am using windows 8.1

**Comment by kjkh** [comment]
Hi,

What the error indicates is that the linker `lld` is not being found. Please ensure that you have followed the instructions in the previous steps, particularly Step 2.

You can try manually installing `lld`: `pacman -S mingw-w64-x86_64-lld`

Also note, the official supported version is Windows 10. If upgrading to that is possible, I suggest doing so as there may be other unexpected errors otherwise.

**Comment by PaintThis** [comment]
I have also encountered this linker error, I will try the work around.

**Comment by SnEhERANDE** [comment]
Hello @kjkh thanks for the answer. 
the build error got solved by the lld command. 
but new error is coming when running the startsample.bat and this new error is also coming to another device with windows 10.

![sample_app error](https://user-images.githubusercontent.com/62797634/132634293-a72dac30-b9f8-41f5-8bc2-39e3ddddf8a6.JPG)
 should I create a new issue for this and close this or should I keep it in this issue?

**Comment by PaintThis** [comment]
Hello @SnEhERANDE 
I also got this error and got an idea for a work around from this: 
https://github.com/alexa/avs-device-sdk/issues/1776

though I didn't follow the instructions exactly, I didn't do the wget and untarring, 
I just did this:

cd portaudio
 ./configure --without-jack
 
make install
after that I could run the sampleapp, hope this helps

**Comment by SnEhERANDE** [comment]
Hi @PaintThis  
Sorry but I am new to this can you explain little more how to do this command.

I am doing this - 
![tmp_img](https://user-images.githubusercontent.com/62797634/133030932-a522e4a5-f4b3-471c-ab9b-8db6f534bb01.JPG)

Can you please tell me what am I supposed to do?

**Comment by SnEhERANDE** [comment]
Thank you @PaintThis & @kjkh.
Closing this issue and creating a new issue for  ./configure --without-jack
