### ISSUE TITLE
Wake Word settings cannot be changed using CMake

### ISSUE THREAD

**Issue by hatosan0112** [alexa/avs-device-sdk#1966]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I want to start SampleApp by wake word.
But I don't know the path of the library and include

## What is the expected behavior?

By calling 「Alexa」, the Sample App works.

## What behavior are you observing?

Enter the following command in the terminal
　cmake /home/denki/my_project/source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/denki/my_project/source/avs-device-sdk/KWD/Sensory/include/KWD/AbstractKeyWordDetector.h -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/denki/my_project/source/avs-device-sdk/KWD/Sensory
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    //CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error: Could not open file for write in copy operation //CMakeFiles/3.10.2/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:145 (file):
  file problem creating directory: //CMakeFiles/3.10.2/CompilerIdCXX
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:706 (file):
  file failed to open for writing (No such file or directory):

    //CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:706 (file):
  file failed to open for writing (No such file or directory):

    //CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:4 (project)

-- The CXX compiler identification is unknown
CMake Error: Could not open file for write in copy operation //CMakeFiles/3.10.2/CMakeCXXCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/share/cmake-3.10/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error: Could not find cmake module file: //CMakeFiles/3.10.2/CMakeCXXCompiler.cmake
-- Check for working CXX compiler: /usr/bin/c++
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:25 (file):
  file failed to open for writing (No such file or directory):

    //CMakeFiles/CMakeTmp/testCXXCompiler.cxx
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:30 (try_compile):
  Unknown extension ".cxx" for file

    //CMakeFiles/CMakeTmp/testCXXCompiler.cxx

  try_compile() works only for enabled languages.  Currently these are:

    CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:41 (file):
  file failed to open for writing (No such file or directory):

    //CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: //CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. //CMakeCache.txt
CMake Error: : System Error: Permission denied

## Tell us about your environment:

OS:Ubuntu18.04

### What version of the AVS Device SDK are you using?
Ver : latest edition

### Tell us what hardware you're using:
- [ 〇] Other - tell us more: Jetson XAVIER NX

### Tell us about your OS (Type & version):
- [〇] Linux : Ubunut18.04

**Comment by kjkh** [comment]
Hi,

The explanation for the variables can be found here: 
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#wake-word.

Wakeword is only supported on Raspberry Pi at the moment due the availability of the wakeword binaries. Please follow this guide to set it up:
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html

**Comment by hatosan0112** [comment]
Thank you for your reply.

The inside of the avs-device-sdk/KWD folder has the following structure.
.
├── CMakeLists.txt
├── include
│   └── KWD
│       └── AbstractKeywordDetector.h
├── inputs
│   ├── alexa_joke.wav
│   ├── alexa_stop_alexa_joke.wav
│   ├── four_alexa.wav
│   └── stop_stop.wav
├── KittAi
│   ├── CMakeLists.txt
│   ├── include
│   │   └── KittAi
│   │       ├── KittAiKeyWordDetector.h
│   │       └── SnowboyWrapper.h
│   ├── src
│   │   ├── CMakeLists.txt
│   │   ├── KittAiKeyWordDetector.cpp
│   │   └── SnowboyWrapper.cpp
│   └── test
│       ├── CMakeLists.txt
│       └── KittAiKeyWordDetectorTest.cpp
├── KWDProvider
│   ├── CMakeLists.txt
│   ├── include
│   │   └── KWDProvider
│   │       └── KeywordDetectorProvider.h
│   └── src
│       ├── CMakeLists.txt
│       └── KeywordDetectorProvider.cpp
├── Sensory
│   ├── CMakeLists.txt
│   ├── include
│   │   └── Sensory
│   │       └── SensoryKeywordDetector.h
│   ├── src
│   │   ├── CMakeLists.txt
│   │   └── SensoryKeywordDetector.cpp
│   └── test
│       ├── CMakeLists.txt
│       └── SensoryKeywordDetectorTest.cpp
├── src
│   ├── AbstractKeywordDetector.cpp
│   └── CMakeLists.txt
└── test
    ├── AbstractKeywordDetectorTest.cpp
    └── CMakeLists.txt

In cmake, there is a place where library folder is specified. But my folder doesn't have a library folder.

What am I missing?

**Comment by kjkh** [comment]
The expected params are from the Sensory Github repositories, not from the AVS SDK:

From https://github.com/alexa/avs-device-sdk/blob/master/tools/Install/pi.sh:
```
-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=$THIRD_PARTY_PATH/alexa-rpi/lib/libsnsr.a \
-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=$THIRD_PARTY_PATH/alexa-rpi/include \
 ```

**Comment by hatosan0112** [comment]
Hi

I could do as written.

but I cannot be activated by wake word.
Is it affected that the OS is not Ubuntu?

**Comment by blazusiak-amazon** [comment]
Hello @hatosan0112,
Are you still experiencing issues with Wake Word engine?
