### ISSUE TITLE
Hot to use Alexa Cast

### ISSUE THREAD

**Issue by CyberSinh** [alexa/avs-device-sdk#1967]
I installed AVS on my Raspberry Pi 3 to cast audio from my Amazon Music app, but the Pi doesn't appear as available device for audio casting in the app.

What can I do ?

## What is the expected behavior?
The Pi should appear as available for audio casting in the Amazon Music app, like any other Alexa-enabled devices.

## What behavior are you observing?
The Alexa-enabled Pi doesn't appear ready to cast from the Amazon Music app.

### What version of the AVS Device SDK are you using?
- Latest

### Tell us what hardware you're using:
- Raspberry Pi 3B

### Tell us about your OS (Type & version):
- Latest Raspbian

**Comment by kjkh** [comment]
Hi,

Can you explain which version of the SDK you are using? Also, please provide any DEBUG9 logs so that we can better assist you.

**Comment by CyberSinh** [comment]
I follow the tutorial available here: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html
The SDK used by the script should be the latest.

The DEBUG9 log is attached:
[DEBUG9.txt](https://github.com/alexa/avs-device-sdk/files/7081590/DEBUG9.txt)

Thanks!

**Comment by CyberSinh** [comment]
Any idea?

**Comment by kjkh** [comment]
Hi @CyberSinh,

This feature should now be available. If you have an AVS SDK instance on the Raspberry Pi that can support music playback, registering it to the same account as your Amazon Music account will allow you to connect to the Raspberry Pi and play from that device. To do this, please enter the Amazon Music app and click the gear icon for settings, and click "Connect to a Device". 

However, note that your Raspberry Pi AVS SDK product must support music playback.

**Comment by CyberSinh** [comment]
Thanks @kjkh.
I did some more tests with the latest version of the SDK, but using the [official script](https://developer.amazon.com/fr-FR/docs/alexa/avs-device-sdk/raspberry-pi-script.html), the _SampleApplication_ compilation fails. It seems that the problem is related to the lack of audio capture device, which is desired because it is not necessary for the intended use (audio streaming from the Amazon Music app). The Alexa device has been configured as "mic-less" in capabilities. 
If my understanding of the [compilation logs](https://pastebin.com/Ji0tMkvh) is correct, how do I compile _SampleApplication_ on a device without a microphone?

**Comment by CyberSinh** [comment]
Compiling the Alexa SDK on a Raspberry is a real pain. Why not provide directly precompiled binary?

**Comment by kjkh** [comment]
It appears that compilation has not failed, but that instead this is a runtime failure.

SampleApplication specifically is intended to be used with a microphone implementation. If you do not wish to have one, and are familiar with C++, you can modify SampleApplication to bypass this behavior.

The quick and dirty way would be to no-op / return false in all of the methods in PortAudioMicrophoneWrapper.cpp: https://github.com/alexa/avs-device-sdk/blob/v1.26.0/SampleApp/src/PortAudioMicrophoneWrapper.cpp.

A more involved alternative would be to implement a NoOpMicrophoneWrapper implementation.

**Comment by blazusiak-amazon** [comment]
Hello @CyberSinh, 

Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.

**Comment by CyberSinh** [comment]
I finally gave up on the idea of using Alexa Cast to stream Amazon Music with a Raspberry Pi. 
It's a real hell: no pre-compiled binary, compilation that crashes the Pi (temperature too high, lack of memory to complete the compilation,...) and lasts for hours, no responsive technical support, no native mic-less support... 
I've wasted enough time for an obviously unsupported scenario.
