### ISSUE TITLE
Steep 13 of test the alexa smart screen device SDK sample app failing

### ISSUE THREAD

**Issue by kaygeeyem16** [alexa/avs-device-sdk#1970]
hi Team,

In Raspberry Pi 4, I am following the below link but stuck at step13, which is test the alexa smart screen device SDK sample.
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html

PA_ALSA_PLUGHW=1 ./modules/Alexa/SampleApp/src/SampleApp -C \
 $HOME/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json -C \
 $HOME/sdk_folder/alexa-smart-screen-sdk/modules/GUI/config/SmartScreenSDKConfig.json -L INFO

Below is what i see in the Raspberry Pi command line.
2021-09-08 07:44:48.314 [  3] I ContextManager:updateCapabilityState
2021-09-08 07:44:48.315 [  3] E ContextManager:getContextAvailableCallbackIfReadyLockedFailed:reason=nullRequester,token=18

Please help to have this resolved. Not sure where the error is.

Thanks and Best Regards,
Ganesh

**Comment by blazusiak-amazon** [comment]
Hello @kaygeeyem16 
Are you still struggling with this issue? Any updates or success since you last posted?

**Comment by kaygeeyem16** [comment]
THis is resolved. Thanks
