### ISSUE TITLE
Reminders beyond 24 hours are played as alarm clock.

### ISSUE THREAD

**Issue by Lmau3** [alexa/avs-device-sdk#1971]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi Teams, 
Reminder than 24 hours: the expiration runs a beep reminder and alarm clock sound sequence instead of the recorded reminder message.
Instead if I set up reminders within 24 hours it works regularly.
I did not find anything about information both in the sdk documentation and in the other issues, can you help me understand how to solve the problem.
Thanks and Best Regards,
Mauro.

## What is the expected behavior?

I expect the reminder to be reproduced correctly after 24 hours, as well as the one within 24 hours.

## What behavior are you observing?

Reminder than 24 hours: the expiration runs a beep reminder and alarm clock sound sequence instead of the recorded reminder message.
See attach log 
[log_reminder_08_set_21_after24hours.txt](https://github.com/alexa/avs-device-sdk/files/7136482/log_reminder_08_set_21_after24hours.txt)

## Provide the steps to reproduce the issue, if applicable:

With the voice command ALEXA add a reminder with a deadline of more than 24 hours, for example tomorrow plus one hour of the current one.

### What version of the AVS Device SDK are you using?
      <1.18.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x ] Other - tell us more: imx7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x ] Other - tell us more: yocto dunfell with linux kernel

**Comment by kjkh** [comment]
Hi @Lmau3,

Thank you for raising this. We are investigating the issue.

**Comment by azlsfrossard** [comment]
Hi @Lmau3,

From the logs I can observe that there was an error on the device while it tried to play the stream:

```
2021-09-08 10:50:03.120 [ 19] 1 Renderer:executeOnPlaybackError:sourceId=72,type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=streamingError
2021-09-08 10:50:03.120 [ 19] 5 Renderer:resetSourceId
2021-09-08 10:50:03.120 [ 19] 1 Alert:onRendererStateChange:state=ERROR,reason=streamingError,m_hasTimerExpired=false,m_dynamicData.state=ACTIVE
2021-09-08 10:50:03.120 [ 19] E Alert:onRendererStateChangeFailed:reason=streamingError:Renderer failed to handle a url. Retrying with local background audio
 sound.
```

This error is usually related to errors on the device which could related to specific device configuration. Were you able to overcome this issue?

If not, can you also try this on our latest version - 1.26 or higher?

Thanks

**Comment by azlffrossa** [comment]
Hi @Lmau3, 

Do you still have this issue?

I just tested with our latest version and it works as expected.

We get 3 rings for the reminder, and once I ask what is the reminder, Alexa proceeds to read the reminder. The behavior was the same for reminders within 24 hours and over 24 hours.

**Comment by Lmau3** [comment]
Hi @azlffrossa ,
Thanks for your comments and testing, but unfortunately for now we cannot use a SDK other than 1.18 on our device.

We cannot understand why the error is on our device, since we reproduce the reminder correctly if the deadline does not exceed 24 hours, while we have the problem if it exceeds 24 hours.

I believe that the audio streaming is sent from the cloud and not saved directly on the device, so I assume that the problem may be that the reminder is no longer found on the cloud because the url where it looks for it is no longer valid see the sdk message "**_Renderer failed to handle to url_** ".

I am waiting for your comment to understand if my suspicion is plausible and how I can find a solution about it.

Thanks.

**Comment by azlffrossa** [comment]
Do you get the reminder if you ask "Alexa, what's my reminder?"

**Comment by Lmau3** [comment]
Hi @azlffrossa ,

Sorry I closed the issues by mistake. Now I have reopened it.

**Comment by sharmajs-amzn** [comment]
Hello @Lmau3 
Are you still experiencing this issue ? if so can you please set another reminder > 24 hrs out and report the time here when the reminder starts ?

**Comment by Lmau3** [comment]
Hello @sharmajs-amzn ,
yes, I'm still having this problem. I have set a reminder> 24 hours for tomorrow 27 April at 9.30 ( 11.30 – Italy time: System :: timeZone ',' "" Europe / Rome "" ') set at 8.45 ( 10.45 italy time  ) 
I am attaching the database alerts.db log for clarity.
[alerts_database_reminder_more24hour.txt](https://github.com/alexa/avs-device-sdk/files/8561553/alerts_database_reminder_more24hour.txt)

Please note that I'm porting code from sdk 1.18 to sdk 1.25 and I'm experiencing the same problem.

**Comment by blazusiak-amazon** [comment]
Hello @Lmau3,
Any updates on the new reminders test on SDK Version 1.26?

**Comment by blazusiak-amazon** [comment]
Hello @Lmau3,
Will you be able to provide any updates on the new reminders test on SDK Version 1.26? Otherwise, I will proceed with closing the ticket.

**Comment by Lmau3** [comment]
Hello  @Jacob
no i'm still working on porting the code, in this period i'm doing my
summer vacation, i think i'll finish the job in september. I will keep you
updates as soon as I will do the first tests

regards,
Mauro

Il giorno lun 22 ago 2022 alle ore 02:32 Jacob Blazusiak <
***@***.***> ha scritto:

**Comment by blazusiak-amazon** [comment]
Hello @Lmau3,
I will be closing this ticket due to inactivity. If this issue appears again, please feel free to cut a new ticket.
