### ISSUE TITLE
SampleApp.exe not running libportaudio-2.dll is missing error

### ISSUE THREAD

**Issue by SnEhERANDE** [alexa/avs-device-sdk#1974]
## Briefly summarize your issue:
Hi I am new and I am following this tutorial - https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/windows-64.html
I am stuck at https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/windows-64.html#step-6-run-and-authorize-the-sample-app
When I open the app this happens

![](https://user-images.githubusercontent.com/62797634/132634293-a72dac30-b9f8-41f5-8bc2-39e3ddddf8a6.JPG)
 
So I installed it from this issue https://github.com/alexa/avs-device-sdk/issues/1776

Then this is happening while installing - 

![](https://user-images.githubusercontent.com/62797634/133037915-f440ce7b-bf53-41de-a4e1-93d56f480850.JPG)

 

## What is the expected behavior?
This llb audio file should install. Also the sample app should work.

## What behavior are you observing?
I am having error while installing the llb file and I think it is because of my operating system which is not unix based. 

## Provide the steps to reproduce the issue, if applicable:
Do the steps said in the tutorial and in this issue https://github.com/alexa/avs-device-sdk/issues/1776 on a windows 8.1/10 machine. 

## Tell us about your environment:
Using windows 8.1 but also facing the issue on a windows 10 machine.
### What version of the AVS Device SDK are you using?
      I don't know I am new but the latest one

### Tell us what hardware you're using:
- Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- Other - tell us more: Windows 8.1 & Windows 10

**Comment by PaintThis** [comment]
Hi @SnEhERANDE 

You missed the step to "cd portaudio"

cd portaudio
./configure --without-jack
make install

**Comment by SnEhERANDE** [comment]
Hi Thanks. Sorry but I don't know why I am getting so many errors but this is the error now I am facing I also ran "make install" also this "bash setup.sh config.json -s 998987" and this is the error.

![Capture](https://user-images.githubusercontent.com/62797634/133397536-88f4a938-4a48-4aa7-9ecb-b187ecac43a6.JPG)

How to solve this?

Thanks

**Comment by SnEhERANDE** [comment]
Hi, Thanks for the information. Everything is working.
