### ISSUE TITLE
Sensory repository down

### ISSUE THREAD

**Issue by flos06** [alexa/avs-device-sdk#1976]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am getting this error when trying to install the Alexa SDK on RPI 4.
fatal: remote error:
  Repository not found.

## What is the expected behavior?

I'd expect it to find the repository and install

## What behavior are you observing?

It is not finding the repository. Which is not surprising seeing as https://github.com/Sensory/alexa-rpi gives a 404 not found

## Provide the steps to reproduce the issue, if applicable:

Install sensory

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Ddvos** [comment]
I am having the same issue. Is there already any sollution?

**Comment by flos06** [comment]
Not that I know of unfortunately

**Comment by Ddvos** [comment]
Maybe it could help if there was another repo. We can update de link to https://github.com/Sensory/alexa-rpi  in the setup.sh file

**Comment by flos06** [comment]
I've tried to find one but all the forks all outdated.

**Comment by Ddvos** [comment]
I think we have to wait on an update from out Amazon....

**Comment by 0zuzu** [comment]
Fuck

**Comment by gauthiersornet** [comment]
What about this one githib link : https://github.com/jcakchen/alexa-rpi
Change the line :
TEST_MODEL_DOWNLOAD="https://github.com/Sensory/alexa-rpi/blob/master/models/spot-alexa-rpi-31000.snsr"
By this one : 
TEST_MODEL_DOWNLOAD="https://github.com/jcakchen/alexa-rpi/models/spot-alexa-rpi-31000.snsr"

**Comment by flos06** [comment]
Wouldn't you need the license in order for it to work though?

**Comment by gauthiersornet** [comment]
I'm testing... But the compilation seems to be stuck... I let it and i'll see...

**Comment by flos06** [comment]
I've tried. Spits out an error at the end that the library isn't licensed

**Comment by gauthiersornet** [comment]
It is still stuck :/

**Comment by flos06** [comment]
well unless someone shares their latest license-key.txt it wont matter anyways :(

**Comment by sammy4703** [comment]
I emailed Sensory about this - here's response:-
Hi xxx

Sensory has made a business decision to remove this project from GitHub. We apologize for any inconvenience. If you would like to explore a license of Sensory technology, contact sales@sensory.com.

**Comment by flos06** [comment]
Well that sucks.

**Comment by moskyow** [comment]
There is another way to have Alexa on Raspy ?

**Comment by flos06** [comment]
You can use KITTAI (snowboy) wakeword engine instead of sensory, however you would need the alexa sdk 1.24 as 1.25 removed support for it. Should still be doable though

**Comment by moskyow** [comment]
> You can use KITTAI (snowboy) wakeword engine instead of sensory, however you would need the alexa sdk 1.24 as 1.25 removed support for it. Should still be doable though

Project closed on Dec. 31st, 2020

**Comment by Ddvos** [comment]
Maybe this one?
https://github.com/alexa-pi/AlexaPi

I haven't tried because it looks outdated. 

I want to use Alexa for playing Spotify because as far as I know, that isn't possible with Google Assistant.
Maybe you guys can use Google Assistant?

**Comment by Ddvos** [comment]
Here is a temporary solution:

https://github.com/alexa/avs-device-sdk/issues/1980

But as far as I know, you can only use the tab to speak

**Comment by flos06** [comment]
I've build it using KITT ai and honestly its working fine. 
FYI Ddvos you can't use spotify on the alexa sdk either :( You have to be whitelisted and they don't seem to do that anymore unless you are a commercial user.

**Comment by GitHubUser4234** [comment]
I've built it with Kitt.AI as well, but it triggers way more often to false positives (listening although wake word hasn't been said). That totally sucks.

Amazon, what do you suggest, after all the steps in the [setup guide](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html)  became invalid too.

Wold be great if someone could make the necessary changes to support the superior and free Porcupine Wake Word Engine.

**Comment by shivasiddharth** [comment]
I have created a hack for triggering Alexa using Picovoice porcupine. If someone can come up with something more neat, it would be great. If we can have a socket server running along with the UI Manager, then the job is done.

**Comment by shivasiddharth** [comment]
Here is how it works https://www.youtube.com/watch?v=uYtlX260JOc&t=466s

**Comment by fivenote** [comment]
> I have created a hack for triggering Alexa using Picovoice porcupine: https://github.com/shivasiddharth/avs-device-sdk-pi If someone can come up with something more neat, it would be great. If we can have a socket server running along with the UI Manager, then the job is done.

Excellent workaround! Thanks @shivasiddharth!

I made a few tweaks for my setup. I wanted it to find the SampleApp's window id each time it starts, and keep it minimized when not detecting the watchword. So...

This bash script starts my alexa script (a modified version of the SampleApp start script). It saves the window id to /tmp, then minimizes it. It then starts my version of shivasiddharth's alexa_picovoice_trigger.py that I called wakeAlexa.py

```
#!/bin/bash

#start alexa and give unique pilexa name for window search
lxterminal -t pilexa -e alexa &

#save alexa window id and minimize
sleep 3
xdotool search --desktop 0 --onlyvisible --name pilexa > /tmp/pilexa
xdotool search --desktop 0 --onlyvisible --name pilexa windowminimize %@
xdotool search --desktop 0 --onlyvisible --name wakeAlexa windowminimize %@

#start porcupine wakeword listener
python3 $HOME/bin/wakeAlexa.py --access_key <my access key> --keywords alexa grapefruit

#cleanup
pkill SampleApp

exit 0
```

In the wakeAlexa.py script, I modified the command that takes action when the wake word is detected. It unminimizes the window, sends the 't' command, and re-minimizes.

```
subprocess.call("wmctrl -ia $(cat /tmp/pilexa) && xdotool search --desktop 0 --onlyvisible --name pilexa windowfocus %@ keydown --window %@ t keyup --window %@ t keydown --window %@ Return keyup --window %@ Return windowminimize %@",shell=True)
```

This is all definitely a workaround. I usually run the SampleApp as a service as I test my apps with it. This workaround puts it all out on the desktop. It would be great if Amazon integrated porcupine into the SampleApp.

Hope this helps us all for now. Thanks again @shivasiddharth!

**Comment by GitHubUser4234** [comment]
Hi shivasiddharth and fivenote,

Really great to see that there is a workaround for porcupine! But still there is this huge issue of #1993 which makes usage of Alexa very limited. Routines and skills don't work without certification anymore like they did before.

**Comment by j4ckp0t85** [comment]
hi guys. i have successfully tried the porcupine method. my problem is that i have a very basic hardware (an orange pi pc) and i mainly don't use windowed terminal.

i have enabled a vnc server to try it but it's laggy (the wake word detector is good but the tap to talk is not hitting.

no way without using real desktop terminals?

**Comment by kenarsa** [comment]
It is `possible` to use [Porcupine](https://github.com/Picovoice/porcupine) as a wake word engine. Picovoice has a free tier that allows using its SDK on up to 3 devices for anyone. That being said, someone (preferably someone on the AVS side) need to do the integration (wrapping Porcupine C class in C++ class that AVS accepts). `Disclaimer, I work for Picovoice.`
