### ISSUE TITLE
AVS SDK 1.24.0 stuck after Authorization process

### ISSUE THREAD

**Issue by yvonne-mendonsa** [alexa/avs-device-sdk#1978]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

SDK Version 1.24 that I am using on my linux system does not go to Idle state. It seems to be stuck just after the authorization process in HTTP2Transport

## What is the expected behavior?

After successful authorization , the state in HTTP2Transport should move from AUTHORIZING to CONNECTED as it does in SDK verison 1.19

## What behavior are you observing?

After successful authorization, the system gets stuck. The HTTP2Transport appears to be hung on trying to acquire mutex lock. Attached log with level DEBUG9 enabled and the source file with added logs in HTTP2Transport.cpp.

## Provide the steps to reproduce the issue, if applicable:

The problem is always reproducible in bringing up the version 1.24 SDK

### What version of the AVS Device SDK are you using?
Issue seen on SDK version 1.24

### Tell us what hardware you're using:
Set-top box

### Tell us about your OS (Type & version):
Linux OS version 4.19.113
[HTTP2Transport.zip](https://github.com/alexa/avs-device-sdk/files/7177801/HTTP2Transport.zip)

[SDK_1.24_DEBUG9_log.log](https://github.com/alexa/avs-device-sdk/files/7177529/SDK_1.24_DEBUG9_log.log)

**Comment by azlsfrossard** [comment]
I see you are using CBL Authorization. So this happens after you input the code at www.amazon.com/us/code ? Also, one thing that caught my eyes is that it seems the gateway was verified before authorization happened, can you confirm that?

**Comment by yvonne-mendonsa** [comment]
> 
> 
> I see you are using CBL Authorization. So this happens after you input the code at [www.amazon.com/us/code](http://www.amazon.com/us/code) ? Also, one thing that caught my eyes is that it seems the gateway was verified before authorization happened, can you confirm that?

Thanks for your response. Yes, I am using CBL authorization, but since it was already authorized in a previous run, I did not have to input any code.
I am attaching another log with a fresh run ( after clearing the DBs) and the problem seen right after entering the code.[](ur
[SDK_1.24_DEBUG9_Authorization_log.log](https://github.com/alexa/avs-device-sdk/files/7241174/SDK_1.24_DEBUG9_Authorization_log.log)
l)

**Comment by yvonne-mendonsa** [comment]
On further investigation, it looks to be stuck in HTTP2Transport::State HTTP2Transport::monitorSharedQueueWhileWaiting at the below point when m_state = whileState = AUTHORIZING:

`m_wakeEvent.waitUntil(lock, wakeTime, [this, whileState, messageRequestTime] {
        return m_state != whileState || m_sharedRequestQueue->peekRequestTime() != messageRequestTime;
    });
`

It appears that the thread is waking up spuriously and evaluating the predicate continuously (this was seen by adding a log in the predicate block). So the waitUntil does not go to wait state and release the mutex.
There is a change noticed in the later versions of the SDKs in the value of the wakeTime parameter initialized in HTTP2Transport::monitorSharedQueueWhileWaiting:

What was earlier:

`/**
     * Monitor the shared message queue while waiting for a state change.  If messages have been sitting in the
     * queue for too long (e.g. during prolonged internet connectivity outtage), complete them as TIMEDOUT.
     *
     * @param whileState The @c State to keep waiting in.
     * @param wakeTime The max time point to wait for.
     * @return The new state.
     */
    State monitorSharedQueueWhileWaiting(
        State whileState,
        std::chrono::time_point<std::chrono::steady_clock> maxWakeTime =
            std::chrono::time_point<std::chrono::steady_clock>::max());
`

has in later versions been changed to the below with added comment in the code:

`State monitorSharedQueueWhileWaiting(
        State whileState,
        std::chrono::time_point<std::chrono::steady_clock> maxWakeTime = avsCommon::utils::timing::getDistantFuture())
/**
 * Get a consistent future @c steady_clock::time_point that we deem unreachable (110+ years), avoiding
 * steady_clock::time_point::max() which results in an overflow due to a gcc bug.
 * @see
 * https://gcc-bugs.gcc.gnu.narkive.com/LBRgUQhD/bug-c-58931-new-condition-variable-wait-until-overflowed-by-large-time-point-steady-clock
 *
 * @return Get a consistent @c steady_clock::time_point that we deem unreachable.
 */

inline std::chrono::steady_clock::time_point getDistantFuture() {
    static const auto distantFuture =  std::chrono::steady_clock::now() + std::chrono::hours(1000000);
    return distantFuture;
}
`

The getDistantFuture value returned looks to be causing the problem behaviour.
We reduced the wakeTime value from :

`inline std::chrono::steady_clock::time_point getDistantFuture() {
    static const auto distantFuture =  std::chrono::steady_clock::now() + std::chrono::hours(1000000);
    return distantFuture;
`

to:

`inline std::chrono::steady_clock::time_point getDistantFuture() {
    static const auto distantFuture =  std::chrono::steady_clock::now() + std::chrono::hours(600000);
    return distantFuture;
`

With this change, the waitUntil condition goes to wait state, and the predicate is evaluated only when there is a notify-all on a change in m_state and the thread is not blocked on the mutex.

attaching logs for reference
[1.24_AVS_LogWithChange.log](https://github.com/alexa/avs-device-sdk/files/7241313/1.24_AVS_LogWithChange.log)
[1.24_AVS_LogWithoutChange.log](https://github.com/alexa/avs-device-sdk/files/7241314/1.24_AVS_LogWithoutChange.log)

[1.24_AVS_LogWithoutChange_PrintInPredicate.log](https://github.com/alexa/avs-device-sdk/files/7241316/1.24_AVS_LogWithoutChange_PrintInPredicate.log)

**Comment by kjkh** [comment]
Hi,

Thank you for raising this. It is interesting that changing the wait time of the underlying std::condition_variable is affecting spurious wake up behavior. Can you please also share the cmake flags you are using to compile the SDK, as well as the compiler version?

**Comment by blazusiak-amazon** [comment]
Helo @yvonne-mendonsa,
Are you still experiencing this issue?

**Comment by blazusiak-amazon** [comment]
Hello @yvonne-mendonsa,

Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
