### ISSUE TITLE
Changing Audio Output Device on Raspberry Pi 4

### ISSUE THREAD

**Issue by DallasPhoenix69** [alexa/avs-device-sdk#1979]
I was wondering if it was possible to change the output device for sound to my onboard soundcard (Raspiaudio Ultra+). The card has 2 built-in speakers and microphones. The microphones work but I cannot change the output, and can only use my built-in audio jack.

### What version of the AVS Device SDK are you using?
      1.23.0

### Tell us what hardware you're using:
 Raspberry Pi 4B

### Tell us about your OS (Type & version):
Raspberry Pi OS (32-bit) / 2021-05-07

**Comment by valeri-atamaniouk** [comment]
Hello @DallasPhoenix69 ,

By default, SDK uses GStreamer on Raspberry PI. You can check which audio sinks are present on your device:

```
gst-inspect-1.0 | grep -i audio | grep -i sink
```

Then, you can modify AlexaClientSDKConfig.json to use required sink. Add a "gstreamerMediaPlayer" section into configuration as follows:

```
"gstreamerMediaPlayer":{
  "audioSink": "my_preferred_sink_name"
},
```

**Comment by blazusiak-amazon** [comment]
Hello @DallasPhoenix69 
Did the instructions provided answer your question? Were you successful in changing the output?

**Comment by DallasPhoenix69** [comment]
Glad you checked in... Dealing with this issue today.

Thank you,

Robert Grover, PhD(c)
9424 Mustang Trail Drive
Reno, Nevada 89506
775-287-8101

**Comment by DallasPhoenix69** [comment]
I ran that command and got this: bash: gst-inspect-1.0: command not found

**Comment by blazusiak-amazon** [comment]
Hello @DallasPhoenix69,

Are you still experiencing this issue? If that is the case, could you please try disabling jack server?
