### ISSUE TITLE
'alexa-rpi' fatal remote error: Repository not found

### ISSUE THREAD

**Issue by 0zuzu** [alexa/avs-device-sdk#1980]
AVS script fails installation after trying to clone the sensory repo. Apparently, its Github has expired, so the installation cannot be completed.

Link to the repository: "https://github.com/Sensory/alexa-rpi.git".

Please fix this asap.

**Comment by t-ohno215** [comment]
I'm facing the same issue. 
It seems to have been closed once in the past, but I can't seem to access Github again.
"https://github.com/alexa/avs-device-sdk/issues/1379"

**Comment by moskyow** [comment]
Same problem here

**Comment by valeri-atamaniouk** [comment]
Hello,
We are aware of the issue and working on a solution.

As a temporary workaround you can disable Sensory download commands, and disable it for the build. AVS SDK features will still be available with tap to talk functionality.

Replace `-DSENSORY_KEY_WORD_DETECTOR=ON` with  `-DSENSORY_KEY_WORD_DETECTOR=OFF` and comment out `build_kwd_engine` command in `run_os_specifics` function.

**Comment by t-ohno215** [comment]
thank you for your reply.

Was the specific content of the workaround good as follows?
---------
1.pi.sh: L43
run_os_specifics() {
  build_port_audio
  build_curl
  build_kwd_engine <- Comment out
  configure_sound
}

---------
2.pi.sh: L24
CMAKE_PLATFORM_SPECIFIC = (-DSENSORY_KEY_WORD_DETECTOR = ON \
 ↓
CMAKE_PLATFORM_SPECIFIC = (-DSENSORY_KEY_WORD_DETECTOR = OFF \
change to

---------
As an additional question,
When responding with tap to talk,I want to respond by pressing 26pin of raspberryPi where should I change it?

**Comment by Ddvos** [comment]
> Hello,
> We are aware of the issue and working on a solution.
> 
> As a temporary workaround you can disable Sensory download commands, and disable it for the build. AVS SDK features will still be available with tap to talk functionality.
> 
> Replace `-DSENSORY_KEY_WORD_DETECTOR=ON` with `-DSENSORY_KEY_WORD_DETECTOR=OFF` and comment out `build_kwd_engine` command in `run_os_specifics` function.

Thanks this one is working for me, I hope you guys will fix the Sensory error because I want to use it stand alone without the need for a button/tap to talk. For now, it isn't possible for Alexa to listen continuously? Thanks for the help

**Comment by valeri-atamaniouk** [comment]
Hello @t-ohno215

Your change is appropriate.

If you want to wire a hardware button you can look into https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/UserInputManager.cpp class as it handles all input events for SampleApp.

**Comment by valeri-atamaniouk** [comment]
Hello @Ddvos 

You can patch sources https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/UserInputManager.cpp  to constantly enter the device into listening state. This might or might not do what you expect.

**Comment by t-ohno215** [comment]
@Ddvos
Thank you for answering.
alexa-rpi, Snowboy seems to have finished the project, so consider alternatives.
I'd like to consider Julius as an alternative, but is there any other good idea?

**Comment by t-ohno215** [comment]
@valeri-atamaniouk
Thanks. I will try the correspondence of the hardware button.

**Comment by GitHubUser4234** [comment]
Really hope this can fixed soon. Looks like there are no real alternatives to Sensory except KITT.AI (which is not maintained anymore)?

**Comment by GitHubUser4234** [comment]
Amazon has now removed the Sensory step from the [setup guide](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html) :disappointed_relieved:

**Comment by EricRafaelP** [comment]
I am waiting for an update to this problem too.

**Comment by j4ckp0t85** [comment]
so from 27th of this month we can basically say goodbye to voice detection (last license published), no other choices?

**Comment by valeri-atamaniouk** [comment]
Hello,

Sensory is no longer required by setup scripts starting from 1.26 release.

**Comment by lambrohan** [comment]
@valeri-atamaniouk But alexa-pi can be activated with voice right?

**Comment by EricRafaelP** [comment]
> @valeri-atamaniouk But alexa-pi can be activated with voice right?

I would like to know too.

**Comment by GitHubUser4234** [comment]
> Sensory is no longer required by setup scripts starting from 1.26 release.

What does it mean, "no longer required". It was not required before either, but now this option has been taken away from us.! Same goes for routine commands that dont work anymore either (see #1993). 

Looks like Amazon wants to kick out the nerds who are using AVS to build a custom home automation system as we don't generate profit ....
