### ISSUE TITLE
Play history is empty in Now Playing page

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#199]
After I used iHeartRadio account play some songs, login the [Amazon Alexa Setting](https://alexa.amazon.com/spa/index.html#player/history) and found the play history is empty in Now Playing page.
Have Any suggestion for it?

**Comment by mradulan** [comment]
The link you sent didn't open. Can you try [this](https://alexa.amazon.com/spa/index.html#player/history) link?

**Comment by BobXLiu** [comment]
Hi mradulan,
I can open the link you sent and found the play history still is empty.
Do you have any suggestion?

**Comment by mradulan** [comment]
Do you have more than one account for Alexa? Are you able to hear iHeartRadio play on your Alexa device? Can you send some log when you do hear it?

**Comment by BobXLiu** [comment]
I used more than two accounts for Alexa and can listen iHearRadio play on my Alexa device.
Please check the [log](https://gist.github.com/BobXLiu/b9ddcdcf7f064dc5d36bcf82a8909bee) information.
Thanks!

**Comment by dhpp** [comment]
Hi BobXLiu, this works for us.  How are you invoking the iHeartRadio?  Is it via the SampleApp, or a custom implementation?  Also, could you please double check which account you are logged into at alexa.amazon.com, and ensure it's the same account you are running your local application.  It is possible that you are looking at the play history for a different account than the one you are listening to music on.

**Comment by BobXLiu** [comment]
Custom implementation base on AudioPlayerIntegrationTest.cpp file and test step as below:
1. I used Bob account logged into [Amazon Alexa](https://alexa.amazon.com/spa/index.html#music/services) and link the iHeartRadio account, then switch Now Playing page. 
2. Used the Bob account logged into my alexa device and say " play lady gaga station from iHeartRadio", then can listen iHeartRadio play on my alexa device.
3. After some minutes and double check the Amazon Alexa Now Playing page, found the Queue tab has some music play finish and has one playing now , but the history tab is empty.
Thanks!

**Comment by BennyAvramson** [comment]
Hi @BobXLiu,

Can you try it by using the sample app?

Thanks,
Benny

**Comment by scotthea-amazon** [comment]
Hello BobXLiu,

Thee has been no reply to the latest question for several weeks now, so I am closing this issue.  If it has been closed in error, please feel free to re-open it.

Than you,
-SWH
