### ISSUE TITLE
Hi，The operating system of our MCU is RT_ Thread or FreeRTOS. I hope it can be integrated with AVS through SDK

### ISSUE THREAD

**Issue by Thomas-fang** [alexa/avs-device-sdk#1991]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by kjkh** [comment]
Hi @Thomas-fang,

While we have not tried this platform, the provided code is open source and hopefully can fit your needs. If you have any further questions or comments on compatibility, please create a new issue. Closing.
