### ISSUE TITLE
feature is only available on certified alexa builtin devices

### ISSUE THREAD

**Issue by smirkhani** [alexa/avs-device-sdk#1993]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We are building a web app that uses AVS. We registered an AVS device. And also wrote our own javascript connector to AVS endpoint (using http-2). Since two days ago, the endpoint is not working for us anymore and says "feature is only available on certified Alexa builtin devices"
## What is the expected behavior?

When we say for example "Alexa, ask lexie assistant order my favorite mushroom food", we expect Alexa to responds to us through AVS end point. Like I said this was happening before and I am pretty sure we did not change anything on our side.

## What behavior are you observing?

We get this message: "feature is only available on certified Alexa builtin devices"

## Provide the steps to reproduce the issue, if applicable:

Our Lexi skill is not public yet, but if we add you to our skill you can reproduce this by saying for example "Alexa, ask lexie assistant order my favorite mushroom food"

### What version of the AVS Device SDK are you using?
      <x.y.z>
We are not using the AVS Device SDK

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by cherylatamazon** [comment]
Hi, this behavior is due to the fact that your device is uncertified; only limited features are available for uncertified devices: https://github.com/alexa/avs-device-sdk/security/policy . Once you have certified your device, it should work correctly. You can find out more about device certification here: https://developer.amazon.com/en-US/alexa/devices/connected-devices/business-resources/works-with-alexa

**Comment by GitHubUser4234** [comment]
> Hi, this behavior is due to the fact that your device is uncertified; only limited features are available for uncertified devices: https://github.com/alexa/avs-device-sdk/security/policy . Once you have certified your device, it should work as expected. You can find out more about device certification here: https://developer.amazon.com/en-US/alexa/devices/connected-devices/business-resources/works-with-alexa

But certification is probably not for the nerds (like me)  that run their own AVS on RPI to build a private home automation system, right?
