### ISSUE TITLE
Preload Alexa into pi 4b

### ISSUE THREAD

**Issue by yulonglovecode** [alexa/avs-device-sdk#1998]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Currently i am helping my company to implment AVS into our IoT products. Is it possible to pre-load Alexa with our customised alexa skill into the pi ? From all the different forums i have tried to set up alexa but all packages still have to be configured one by one.

**Comment by kclchan** [comment]
Hi @yulonglovecode, could you elaborate on what you meant by pre-loading your customized skill into the pi?  How are you loading it in the pi currently?

**Comment by yulonglovecode** [comment]
Hey @kclchan, thanks for the reply.Currently i sm having some hard time to implement skills into my pi. All i can do is to connect the web server to skills endpoint and use alexa skills Test on my laptop to interact with pi as a receiver which is kind of pointless. Do you have any idea how to implement skills on raspberry pi ?

**Comment by valeri-atamaniouk** [comment]
Hello @yulonglovecode 

Skills can be developed using Alexa Skill Kit: https://developer.amazon.com/en-US/alexa/alexa-skills-kit

Alexa Device SDK can be used to provide new hardware interface to skills. For that you need to develop Capability Agent that will receive directives and send events as appropriate to hardware module. 
Examples of CAs:
https://alexa.github.io/avs-device-sdk/classalexa_client_s_d_k_1_1avs_common_1_1avs_1_1_capability_agent.html
