### ISSUE TITLE
device refuses to play Apple Music with response "Apple Music is not supported on this device"

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#2000]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Cannot get Apple Music to function

## What is the expected behavior?

After following the instructions to enable ffmpeg, Apple Music should play on our device

## What behavior are you observing?

AVS responds with "Apple Music is not supported on this device"

## Provide the steps to reproduce the issue, if applicable:

Install AVS on Ubuntu

install libavcodec-dev libavformat-dev libavutil-dev ffmpeg

build with  -DENABLE_SAMPLE_AES=ON
 -DFFMPEG_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/
 -DFFMPEG_LIB_PATH=/usr/lib/x86_64-linux-gnu

verify the build says "Including FFmpeg libraries"

install the SDK, build our app against it (basically just the sample app for the purposes of repro)

link amazon account to device

link Apple Music in skills to amazon account

say "Alexa play Apple Music"

expect music to start playing: actually get response of "Apple Music is not supported on this device"
[logs.txt](https://github.com/alexa/avs-device-sdk/files/7664198/logs.txt)

### What version of the AVS Device SDK are you using?
      <1.25.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @brett-lynnes, looking at the logs, it seems that there's only Speak directives from AVS when you ask it to play Apple Music:
```
[I](139891899881216) 22:47:53.8828 2021-12-06 22:47:53.882 [ 10] I DirectiveSequencer:onDirective:directive=namespace\:SpeechSynthesizer\,name\:Speak\,messageId\:a78152b3-8177-4c66-9255-d2682bb03db9\,dialogRequestId\:7adadbbd-ee8c-4986-b520-b05e543e30f6\,correlationToken\:\,eventCorrelationToken\:\,payloadVersion\:\,instance\:
```
So this could be an account linking issue.  Were you able to get this working with other versions of the SDK before?

**Comment by painnovation** [comment]
Hi @kclchan, I work with @brett-lynnes on this and we haven't tested this on any other SDK version.

**Comment by womw** [comment]
@painnovation @brett-lynnes Can you work with an Amazon Representative to enable Apple Music Support for your device?

**Comment by painnovation** [comment]
We got in contact after we filed this bug. The Docs don't say anything about this being a requirement so we thought we were doing something wrong.

**Comment by womw** [comment]
OK, we'll look to see if we can improve our public documentation. If there are no other issues then I'll be closing this one. Feel free to reopen or open a new issue.
