### ISSUE TITLE
Issue during Set Up the AVS Device SDK on Raspberry Pi with a Script

### ISSUE THREAD

**Issue by francesco7752** [alexa/avs-device-sdk#2003]
Hi

I'm trying to install AVS SDK on Raspberry PI 4  model B Rev. 1.4 with RASPBIAN GNU / Linux 11 Operating System (bullseye), I follow the instructions found on https://developer.amazon.com/it-IT/docs/alexa/avs-device-sdk /raspberry-pi-script.html but when I run the script
sudo bash setup.sh config.json [-s 1234]
 I get the following error:

  0%] Built target acsdkCryptoInterfaces
[ 12%] Built target AVSCommon
[ 13%] Built target acsdkCodecUtils
[ 14%] Built target gmock
[ 14%] Built target gtest
[ 14%] Linking CXX executable InMemoryCommunicationPropertiesHandlerTest
[ 14%] Linking CXX executable InMemoryCommunicationInvokeHandlerTest
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationInvokeHandlerTest.dir/build.make:106: shared/acsdkCommunication/test/InMemoryCommunicationInvokeHandlerTest] Errore 1
make[1]: *** [CMakeFiles/Makefile2:17016: shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationInvokeHandlerTest.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationPropertiesHandlerTest.dir/build.make:106: shared/acsdkCommunication/test/InMemoryCommunicationPropertiesHandlerTest] Errore 1
make[1]: *** [CMakeFiles/Makefile2:16988: shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationPropertiesHandlerTest.dir/all] Errore 2
make: *** [Makefile:160: all] Errore 2

Can you help me please.

**Comment by shivasiddharth** [comment]
Before starting, run:
`export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0`
Bullseye is not stable yet. I would suggest you to stick to Buster.

**Comment by francesco7752** [comment]
Thanks but I keep getting the error (see below).
Unfortunately I don't know how to download Buster, I use NOOBS and it doesn't allow me to choose another version.


[ 13%] Built target acsdkCodecUtils
[ 14%] Built target gtest
[ 14%] Built target gmock
[ 14%] Linking CXX executable InMemoryCommunicationPropertiesHandlerTest
[ 14%] Linking CXX executable InMemoryCommunicationInvokeHandlerTest
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationInvokeHandlerTest.dir/build.make:106: shared/acsdkCommunication/test/InMemoryCommunicationInvokeHandlerTest] Errore 1
make[1]: *** [CMakeFiles/Makefile2:17016: shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationInvokeHandlerTest.dir/all] Errore 2
make[1]: *** Attesa per i processi non terminati....
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../../AVSCommon/libAVSCommon.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationPropertiesHandlerTest.dir/build.make:106: shared/acsdkCommunication/test/InMemoryCommunicationPropertiesHandlerTest] Errore 1
make[1]: *** [CMakeFiles/Makefile2:16988: shared/acsdkCommunication/test/CMakeFiles/InMemoryCommunicationPropertiesHandlerTest.dir/all] Errore 2
make: *** [Makefile:160: all] Errore 2

**Comment by shivasiddharth** [comment]
Here is the link to the OS https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-05-28/2021-05-07-raspios-buster-armhf.zip

**Comment by francesco7752** [comment]
Thanks. I installed Buster and it worked
