### ISSUE TITLE
hands free version of AVS

### ISSUE THREAD

**Issue by SEgyl** [alexa/avs-device-sdk#2004]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Currently i have set up alexa on my pi, Is there anyway to achieve the hands free function? 

 
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ x] Other - tell us more:
- raspbian bustler

**Comment by blazusiak-amazon** [comment]
Hello @SEgyl,

Hands free functionality can be achieved on your Pi if you integrate your own or publicly sourced wake word engine. Previously, this was possible using Sensory, however, recently Sensory has made a business decision to remove its wake word engine project from GitHub. However, shivasiddharth has been able to successfully get another wake word engine working named Porcupine.

Here is the link to the thread: https://github.com/alexa/avs-device-sdk/issues/1976

**Comment by kenarsa** [comment]
It is `possible` to use [Porcupine](https://github.com/Picovoice/porcupine) as a wake word engine. Picovoice has a free tier that allows using its SDK on up to 3 devices for anyone. That being said, someone (preferably someone on the AVS side) need to do the integration (wrapping Porcupine C class in C++ class that AVS accepts). `Disclaimer, I work for Picovoice.`
