### ISSUE TITLE
SampleApp not pausing for Authorisation

### ISSUE THREAD

**Issue by davevdm1968** [alexa/avs-device-sdk#2005]
## Briefly summarize your issue:
SampleApp not pausing for Authorisation 

$ PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
configFile ./Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2022-01-01 11:50:42.696 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
To enable debug logs, rebuild in DEBUG mode by using the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG or (if you *really* want debug logs in a RELEASE build) use the cmake parameter -DACSDK_DEBUG_LOG=ON.

2022-01-01 11:50:42.696 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
To enable debug logs, rebuild in DEBUG mode by using the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG or (if you *really* want debug logs in a RELEASE build) use the cmake parameter -DACSDK_DEBUG_LOG=ON.

(SampleApp:30474): GStreamer-CRITICAL **: 13:50:42.751: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:30474): GLib-CRITICAL **: 13:50:42.751: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
##################################
#       NOT YET AUTHORIZED       #
##################################

################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: AWAB26       #
################################################################################################

Failed to create SampleApplication!

## What is the expected behaviour?
I thought it would pause until I have authorised it on the amazon website
I do successfully go authorise, run it again but it keeps coming back with different code

## Provide the steps to reproduce the issue, if applicable:
I followed this page to install
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi.html

everything went well until i got to Step 7: Run and authorize the sample app

### What version of the AVS Device SDK are you using?
      <x.y.z>
not sure, used this command 1 Jan 2022
git clone --single-branch git://github.com/alexa/avs-device-sdk.git

 Raspberry Pi

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by blazusiak-amazon** [comment]
Hello @davevdm1968,
I have a few questions that could help clarify the situation:

1. Are you making sure to keep the Sample Application running while you open a separate web browser or device to authorize the application with the code provided? I am asking because, I noticed that in your comments you wrote that you successfully authorize, and then proceed to run the Sample Application again. But when you do run it again, it runs with a different authorization code.
2. Is the message "Failed to create SampleApplication!" appearing after you input the code provided for the linking? It not, when does this message appear for you?

**Comment by davevdm1968** [comment]
I ssh into the pi then
I start the app using the following command 
PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
It ends immediately after the code comes up
I thought it needed to be authorised so I opened a separate browser and authorise the code
It comes back successful on the browser
then still in the ssh terminal i try the same command and it has the same result with a different code

terminal recording attached

https://user-images.githubusercontent.com/39761531/147967688-e0175e82-6897-4601-ba3d-a6ecd0f7a6d2.mov

**Comment by blazusiak-amazon** [comment]
Hello @davevdm1968 ,
It looks like you are experiencing a gstreamer related issue. Could you please try and verify installing gstreamer?
`sudo apt-get install gstreamer1.0-alsa`

**Comment by davevdm1968** [comment]
thank you, that worked instantly.
