### ISSUE TITLE
Support for android kitkat (4.4.4) devices

### ISSUE THREAD

**Issue by josefeliuf** [alexa/avs-device-sdk#2008]
## Briefly summarize your issue:
Hey guys! i know that the actual avs-device-sdk only has support for android 6.0+ devices, but i wanted to know if there is an old version that works on android 4.4.4 or maybe another viable option that works similar to alexa. Thanks :)

### Tell us what hardware you're using:
- SmartWatch

### Tell us about your OS (Type & version):
- Android 4.4.4

**Comment by valeri-atamaniouk** [comment]
Hello @josefeliuf 

Alexa Device SDK doesn't support Android releases before 6.0 (Marshmallow), and it has not been verified to build and work with KitKat.

**Comment by josefeliuf** [comment]
In that case, can i virtualize alexa and connect the kitkat device to the server to listen for alexa answers? 

My actual flow would be something like this:

1. Record audio file on the kitkat device
2. upload the file to S3
3. trigger lambda function when object created
4. use the audio file (or maybe speech to text) as input for this server running alexa
5. get the answer from alexa
6. send it back to the kitkat device

My problem is specifically with step 4 and 5, is that even possible? i've been looking for anwers but have not found any yet :(
