### ISSUE TITLE
Double negative

### ISSUE THREAD

**Issue by metalivedev** [alexa/avs-device-sdk#2010]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
There is a double negative in the Security.md

## What is the expected behavior?
Describe warning screen as happening when device is _not_ certified by Amazon.

## What behavior are you observing?
It says "not been not certified"

## Provide the steps to reproduce the issue, if applicable:
See https://github.com/alexa/avs-device-sdk/pull/2009

### Tell us what hardware you're using:
My eyes.

### Tell us about your OS (Type & version):
English (Natural Language, American)

**Comment by womw** [comment]
Hey @metalivedev thanks for bringing this to our attention. We'll take a look and investigate this internally.

**Comment by azlsfrossard** [comment]
Fix is done and should be available in the upcoming release.
