### ISSUE TITLE
My pi stops downloading at 95%

### ISSUE THREAD

**Issue by Sai9555** [alexa/avs-device-sdk#2011]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by Sai9555** [comment]
Hey guys my raspberry 3b+ was running everything perfectly until it reaches 95% on the sample app downloads and then the pi freezes and i cant do anything

**Comment by wryley-amzn** [comment]
Hi! Please check https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide, are there any additional logs you could provide us to help debug this issue, from the build or download stage if there are any?

**Comment by mariopaonessa** [comment]
Increasing the swap size helped me. kind regards M

**Comment by azlsfrossard** [comment]
Hi, can you try the suggestion provided by the user '@mariopaonessa' at [this issue](https://github.com/alexa/avs-device-sdk/issues/2012)?
