### ISSUE TITLE
call to https://api.amazon.com/auth/o2/token fails

### ISSUE THREAD

**Issue by zhaokai3000** [alexa/avs-device-sdk#2015]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We are try to authorize a device using an companion app referring to the following online document:
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/authorize-companion-app.html

I'm using c++ to write a program to call the rest api to get token with the information get from the companion app. The rest api is called with libcurl apis.
Sometimes I get the right result:
> POST /auth/o2/token HTTP/1.1
Host: api.amazon.com
Accept: application/x-www-form-urlencoded
Content-Type: application/x-www-form-urlencoded
Content-Length: 312

< HTTP/1.1 200 OK
< Server: Server
< Date: Wed, 16 Feb 2022 11:24:44 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 956
< Connection: keep-alive
< x-amz-rid: DJRRN7H5GY82W041YAAV
< x-amzn-RequestId: 996c44ab-a3e9-4835-a751-1386da259fd6
< X-Amz-Date: Wed, 16 Feb 2022 11:24:44 GMT
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Vary: Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent
< Permissions-Policy: interest-cohort=()

But **MOST** times I get the following error:
> POST /auth/o2/token HTTP/1.1
Host: api.amazon.com
Accept: application/x-www-form-urlencoded
Content-Type: application/x-www-form-urlencoded
Content-Length: 312

< HTTP/1.1 200 OK
< Server: Server
< Date: Wed, 16 Feb 2022 11:24:44 GMT
< Content-Type: application/json;charset=UTF-8
< Content-Length: 956
< Connection: keep-alive
< x-amz-rid: DJRRN7H5GY82W041YAAV
< x-amzn-RequestId: 996c44ab-a3e9-4835-a751-1386da259fd6
< X-Amz-Date: Wed, 16 Feb 2022 11:24:44 GMT
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Vary: Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent
< Permissions-Policy: interest-cohort=()

and the error information looks like the following one:
{"error_index":"cAyG4y4_QEa8p_ERZfPligAAAAAAAAABIHrAAp69So3164EjobkPXTkzEVzTmbfqoByPhyFiZFpcPjs0qvNs3OKgo7_PdtQNP1YIf_H3L3bnhdXwM-RqgGGWbR54gNUzsBHpy3qhTiTXRm83y-Okgrrk2ux1upU0wEm3zNPJE8g8DCi-5igpSFp3NA8qDI3T9f3Rwk7dZ5bbeysNm1fSneZ5A8o7EZkuG6O4TsZd5kNZaJst4xBa_A==","error_description":"Malformed request","error":"invalid_request"}

I wonder if I could get any more detailed information from this message?

## What is the expected behavior?
Allways the right result for the api.

## What behavior are you observing?
Most times the api fails.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
Embedded linux device.

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by blazusiak-amazon** [comment]
Hello @zhaokai3000,
I notice that in both scenarios you mention that the server responds with a 200 OK, whereas the error information below responds with an Invalid Request, which should be a 400. Can you confirm whether this is the behavior you are seeing? If it is not, can you post the client error you are receiving from the server?

**Comment by zhaokai3000** [comment]
Something wrong with my usage of libcurl, the call to curl_easy_setopt with command CURLOPT_POSTFIELDS doesn't make a copy of the post data while I'm using a temporary variable for the post data. So the post data is sometimes corrupted.
Closing this issue...

**Comment by Kiennguyen08** [comment]
Hi @zhaokai3000 can you tell me how you transmit information get from companion app to device?
