### ISSUE TITLE
Unable to download AVS config.json file (Download button missing ?)

### ISSUE THREAD

**Issue by rahuldas790** [alexa/avs-device-sdk#2016]
## Issue:
Unable to download config.json file

## What is the expected behavior?
According to the steps given in the developer console, after i register my device, i should get the config.json file downloaded
which is required in the below step
`bash setup.sh config.json -a androidConfig.txt -s 998987` 

## What behavior are you observing?
I cannot see any download button to get the config.json file anywhere, also it didn't download automatically after registering the device

## Provide the steps to reproduce the issue, if applicable:
I followed the steps given in this doc
[https://developer.amazon.com/en-GB/docs/alexa/avs-device-sdk/android.html](https://developer.amazon.com/en-GB/docs/alexa/avs-device-sdk/android.html)

## Tell us about your environment:
AVS Built-in device, Android

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - Android TV(ATV) Set top box

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - Android, version 10:

**Comment by azlffrossa** [comment]
Hi, here is where you can find it:

1. Go to this [page](https://developer.amazon.com/alexa/console/avs/products) and then select the product you have created.
2. Under product details select "Security Profile"
3. Select "Other devices and platforms" tab
4. Click the download button at the bottom of the page.

If that don't work, please reopen the ticket.

Thanks.
