### ISSUE TITLE
Typo in PreviewAlexaClient.cpp

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#2018]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Typo around line 200 of applications/acsdkPreviewAlexaClient/src/PreviewAlexaClient.cpp

the line: 
std::shared_ptr<avsCommon::sdkInterfaces::storage::MiscStorageInterface>,

is duplicated

## What is the expected behavior?

no typo

## What behavior are you observing?

typo

## Provide the steps to reproduce the issue, if applicable:

please look at the indicated spot in code

## Tell us about your environment:

this bug occurs on all platforms

### What version of the AVS Device SDK are you using?
      <1.26.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi,

Thanks for pointing this out. We will make the appropriate fixes. Closing out the ticket.
