### ISSUE TITLE
CLONING SDK- Issue

### ISSUE THREAD

**Issue by Karthikeyyan** [alexa/avs-device-sdk#2019]
Error Message  while using wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh \- 

Cloning into 'avs-device-sdk'..
fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information

Unable to Install Amazon AVS SDK on Raspberry Pi. Based on my understanding there was a recent Github security update which doesn't like the download url. I guess Install/setup.sh needs a change 
from
CLONE_URL=${CLONE_URL:- 'git://github.com/alexa/avs-device-sdk.git'}
to
CLONE_URL=${CLONE_URL:- 'git@github.com/alexa/avs-device-sdk.git'}

Solution from other forums-
git config --global url."git@github.com:".insteadOf git://github.com/

**Comment by womw** [comment]
Hi @Karthikeyyan thanks for bringing this to our attention, we'll take a look at this.

**Comment by kjkh** [comment]
Closing issue as this is resolved.
