### ISSUE TITLE
Feature request for CMake files - Enable PkgConfig detection

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#202]
In a case where I have a master CMakeLists.txt using External_Project_Add(), I like to use the following scheme:

    PKG_CONFIG_PATH=/home/joel/git/demo/build/out/lib/pkgconfig cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/joel/git/demo/build/out

Once the first "external" project is built, the install step will install everything with the pkgconfig.  This allows a paradigm where the next dependency can detect it's dependency via package config.  The package config detection gets implemented something like this:

    FIND_PACKAGE(PkgConfig)

    IF (PKG_CONFIG_FOUND)
    PKG_CHECK_MODULES(PORTAUDIO portaudio-2.0)
        IF (PORTAUDIO_FOUND)
            INCLUDE_DIRECTORIES(${PORTAUDIO_INCLUDE_DIRS})
            LINK_DIRECTORIES(${PORTAUDIO_LIBRARY_DIRS})
        ENDIF (PORTAUDIO_FOUND)
    ENDIF (PKG_CONFIG_FOUND)
    IF (NOT PORTAUDIO_FOUND)
        FIND_PACKAGE(portaudio-2.0)
        IF (PORTAUDIO_FOUND)
            INCLUDE_DIRECTORIES(${PORTAUDIO_INCLUDE_DIR})
            LINK_DIRECTORIES(${PORTAUDIO_LIBRARY_DIRS})
        ENDIF (PORTAUDIO_FOUND)
    ENDIF (NOT PORTAUDIO_FOUND)

This allows building/detecting sandbox packages, building/detecting system packages, and overriding via:

    -DPORTAUDIO_FOUND=ON
    -DPORTAUDIO_INCLUDE_DIR="${MY_PATH}/include"
    -DPORTAUDIO_LIBRARY="${MY_PATH}/lib/my_custom_pa_lib.a"

So if you don't set the PKG_CONFIG_PATH variable, it will default to your system.  If you pass in PORTAUDIO_FOUND, it won't actually detect it and the variables you pass in will stick (override case).

This works the same for Mac, Linux, Cygwin, and Android.  In the case of Native Windows it fails to find PkgConfig, so it would default to FIND_PACKAGE.  The same override logic works here too.

**Comment by kclchan** [comment]
Thanks for the suggestion.  We have created a task for the team to work on regarding this.  Thanks.
