### ISSUE TITLE
Wrong playback hardware device is used

### ISSUE THREAD

**Issue by Noahfreriksen** [alexa/avs-device-sdk#2022]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The SampleApp is using the wrong device for its playback when installing with the script

## What is the expected behavior?
That the SampleApp uses card 1 device 0 as a playback device

## What behavior are you observing?
The SampleApp is using card 0 device 0 as a playback device

## Provide the steps to reproduce the issue, if applicable:
Install the AVS SDK with the raspberry pi from script instructions

## Tell us about your environment:
This is the asound.conf file used in this setup:
~~~
 pcm.!default {
   type asym
    playback.pcm {
      type plug
      slave.pcm "hw:1,0"
    }
    capture.pcm {
      type plug
      slave.pcm "hw:1,0"
    }
 }
~~~
When following the instructions for installing AVS SDK from source, the right playback device is used. When using the script, the wrong playback device is used.
### What version of the AVS Device SDK are you using?
      <1.26.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:
Raspbian Buster

**Comment by Noahfreriksen** [comment]
Update,

I disabled the bcm card and now AVS returns the following error when trying to output audio:
~~~
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
~~~

Of course I set the default card in the alsa configs to the card that is still available.

**Comment by womw** [comment]
hello @Noahfreriksen we're currently investigating this issue, thanks for bringing this to our attention

**Comment by cherylatamazon** [comment]
@Noahfreriksen  what version of Buster are you using? Regular or lite?

**Comment by blazusiak-amazon** [comment]
Hello @Noahfreriksen,
Are you still experiencing this issue?

**Comment by blazusiak-amazon** [comment]
Hello @Noahfreriksen,
Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
