### ISSUE TITLE
How can AVS return text in the response?

### ISSUE THREAD

**Issue by ZhangyeAye** [alexa/avs-device-sdk#2025]
for example when I say "alexa,what‘s the weather in New York", avs response "New York would be cloudy at the time with the temperature from eighteen to twenty-eight."。both two is sound, how can i get text。
thanks

**Comment by wryley-amzn** [comment]
Hi @ZhangyeAye, to get the text of the speech response you can enable captions by following these instructions: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/features.html#captions. 

However, please keep in mind that captions should only be used for accessibility / UI purposes and not have business logic built on top of them.

**Comment by EastApex** [comment]
Hi @wryley-amzn Thank you for your reply, but this is not what I wanted.
What I want is to return text via Alexa Voice Service without using DeviceSDK.
Thank you very much!

**Comment by wryley-amzn** [comment]
Please see this page for what is returned from the cloud for speak directives - perhaps something you need is there. https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/speechsynthesizer.html

**Comment by blazusiak-amazon** [comment]
Hello @EastApex,
Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question was not been answered fully.
