### ISSUE TITLE
Loading Multiple WakeWord Models in to the pryonlitewakeword detector. 

### ISSUE THREAD

**Issue by sivakumarar** [alexa/avs-device-sdk#2027]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

This may not be a bug, but a query or clarification.
In the PryonLiteKeywordDetector adaptor used for AlexaVoiceService SDK version 1.26, it can load single WWE model file in to memory and pass in to PryonLite_Initialize for using for detection.
In case of two model files present, one for English and another for different language eg. French. 
How do we load both the models in to the PryonLiteKeywordDetector to detect both languages.

## What is the expected behavior?

Need to load both the models for English and French in to the PryonLiteKeywordDetector and detect both the languages from User.

## What behavior are you observing?

In the code could see only one model can be loaded in PryonLite_Initialize(), api.
Example loading model in to below structure,
const void* model;
size_t sizeofModel;

## Provide the steps to reproduce the issue, if applicable:

When using AVS SDK and pryonlitekeyword detector for detecting the Wakeword from user, want to use multiple models.

### What version of the AVS Device SDK are you using?
      <1.26.0>

### Tell us what hardware you're using:
Custom Hardware

### Tell us about your OS (Type & version):
Linux

**Comment by blazusiak-amazon** [comment]
Hello @sivakumarar, 
Could you please file a ticket with an Amazon Solutions Partner who is working with you to get this investigated? 
I will be closing this ticket. 
Best
