### ISSUE TITLE
Cannot update aace.geolocation.geolocationEnablement property

### ISSUE THREAD

**Issue by RaniVincent123** [alexa/avs-device-sdk#2028]
_This is an issue related to Alexa Auto SDK 4.0, posting the issue here since "Issues" section is unavailable in Auto SDK github page.
It would be great if a solution is suggested else please provide a way to communicate with the auto SDK team._

## Briefly summarize your issue:
We are facing an issue in updating aace.geolocation.geolocationEnablement SDK property. Update is getting failed.
We have a requirement to enable/disable user location sharing permission from a settings screen. We tried the same implementation as provided by the AACS Sample app:

`        mAlexaPropertyManager.updateAlexaProperty(AACSPropertyConstants.GEOLOCATION_ENABLED, value)
                .doOnSuccess((succeeded) -> {
                    if (succeeded) {
                        Log.d(TAG, "Successfully updated geolocation value to: " + value);
                        EventBus.getDefault().post(new WorkflowMessage(LOCATION_CONSENT_COMPLETED));
                    } else {
                        Log.e(TAG, "Failed to update geolocation value to: " + value);
                        EventBus.getDefault().post(new WorkflowMessage(SETUP_ERROR));
                    }
                })
                .subscribe(); `

## What is the expected behavior?
Geo location property must be updated to desired values.

## What behavior are you observing?

An error is thrown from SDK like below:
`AAC] E aace.propertyManager.PropertyManagerEngineService:setProperty:reason=propertyNotFound,name=aace.geolocation.geolocationEnablement`

**Comment by yyang160** [comment]
Hello,

Thanks for reaching out. Geolocation is an Alexa Auto SDK extension which you can obtain from our Solution Architects (please refer to this documentation in Alexa Auto SDK for this: https://github.com/alexa/alexa-auto-sdk/blob/9324a7776da8b2d2210b76a88330c3f695d9b9f6/NEED_HELP.md). Without the extension, the property is not available and geolocation consent would not be updated. 

Additionally, you can ask questions directly on Auto SDK Github repo by creating a pull request. Our on-call will constantly check and respond there for any issues.

Thanks.
