### ISSUE TITLE
Sorry music or radio playback is not supported on this device

### ISSUE THREAD

**Issue by vanelk** [alexa/avs-device-sdk#2036]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have successfully compiled and was able to run the Sample App from the avs-device-sdk on my raspberry pi. Still, when I ask Alexa to play some music I get the response "Sorry music or radio playback is not supported on this device".

## What is the expected behavior?
I expected the app to play a track from my Amazon prime music library or even Spotify account.

## What behavior are you observing?
Sorry music or radio playback is not supported on this device

## Provide the steps to reproduce the issue, if applicable:
Launch SampleApp
press t and enter for request 
Say: *Alexa, play some music*

## Tell us about your environment:
cd /opt/alexa/sdk-folder/sdk-build
 PA_ALSA_PLUGHW=1 ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json DEBUG9
configFile ./Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2022-05-29 23:05:36.539 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
To enable debug logs, rebuild in DEBUG mode by using the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG or (if you *really* want debug logs in a RELEASE build) use the cmake parameter -DACSDK_DEBUG_LOG=ON.

2022-05-29 23:05:36.539 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
To enable debug logs, rebuild in DEBUG mode by using the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG or (if you *really* want debug logs in a RELEASE build) use the cmake parameter -DACSDK_DEBUG_LOG=ON.

2022-05-29 23:05:36.675 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
To enable debug logs, rebuild in DEBUG mode by using the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG or (if you *really* want debug logs in a RELEASE build) use the cmake parameter -DACSDK_DEBUG_LOG=ON.

2022-05-29 23:05:36.675 [  1] I Setting:handleSetValue:value=false3990065800
2022-05-29 23:05:36.676 [  1] I Setting:handleSetValue:value="NONE"3990065800
2022-05-29 23:05:36.676 [  1] I Setting:handleSetValue:value="TONE"3990065800
2022-05-29 23:05:36.677 [  1] I Setting:handleSetValue:value="TONE"3990065800
2022-05-29 23:05:36.677 [  1] I Setting:handleSetValue:value="America/Vancouver"3990065800
2022-05-29 23:05:36.678 [  1] I Setting:handleSetValue:value={}3990065800
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
###########################
#       Authorized!       #
###########################

#############################
#       Connecting...       #
#############################

                  #    #     #  #####      #####  ######  #    #
                 # #   #     # #     #    #     # #     # #   #
                #   #  #     # #          #       #     # #  #
               #     # #     #  #####      #####  #     # ###
               #######  #   #        #          # #     # #  #
               #     #   # #   #     #    #     # #     # #   #
               #     #    #     #####      #####  ######  #    #

       #####                                           #
      #     #   ##   #    # #####  #      ######      # #   #####  #####
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #
       #####  #    # # ## # #    # #      #####     #     # #    # #    #
            # ###### #    # #####  #      #         ####### #####  #####
      #     # #    # #    # #      #      #         #     # #      #
       #####  #    # #    # #      ###### ######    #     # #      #

       SDK Version 1.26.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Reauthorize device:                                                        |
|       Press 'z' followed by Enter at any time to re-authorize your device. |
|       This will erase any data stored in the device and initiate           |
|       re-authorization.                                                    |
| Device Setup Complete:                                                     |
|       Press 'v' followed by Enter at any time to indicate that device      |
|       setup is complete.                                                   |
|                                                                            |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

#######################################################
#       Successfully registered 1 endpoint(s).        #
#######################################################

########################################
#       Alexa is currently idle!       #
########################################

t
############################
#       Listening...       #
############################

###########################
#       Thinking...       #
###########################

###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

### What version of the AVS Device SDK are you using?
      1.26.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more:
Raspberry pi OS

**Comment by blazusiak-amazon** [comment]
Hello @vanelk

Unfortunately music playback is only supported on certified devices. If you have an Alexa Business Representative, you can reach out to them for further questions.
