### ISSUE TITLE
Unable to install script on Raspberry Pi 4

### ISSUE THREAD

**Issue by Mystik01** [alexa/avs-device-sdk#2038]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Unable to install the script on my Raspberry Pi
When I run ` sudo bash setup.sh config.json [-s 1234]`

## What is the expected behavior?

From the docs "AVS Device SDK Raspberry Pi Script - Terms and Agreements appear" but I do not get that, it errors. 

## What behavior are you observing?
I receive an error:
```
pi@raspberrypi:~ $ sudo bash setup.sh config.json [-s 1234]
PKCS11 parameters are not specified. Hardware security module integration is disabled.
The installation script doesn't support current system. (System: Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux)
```

## Provide the steps to reproduce the issue, if applicable:
I Was following the docs [here](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/raspberry-pi-script.html)
When I run ` sudo bash setup.sh config.json [-s 1234]` it error
I did replace the git command git://github.com/alexa/avs-device-sdk.git with https://github.com/alexa/avs-device-sdk.git in the setup.sh script.

### Tell us what hardware you're using:
Raspberry Pi 4 - 4gb

### Tell us about your OS (Type & version):
Raspberry Pi OS
System: 64-bit
Debian version: 11 (bullseye)

I think possibly it may be because it is a new version of Debian?

**Comment by Zubair-Frotan** [comment]
Hello dear respected friends!
I faced a issue when installing "bash setup.sh config.json" on my raspberry pi 4 model B so i can not install it. error message is "PKCS11 parameters are not specified. Hardware security module integration is disabled.
The installation script doesn't support current system. (System: Linux pi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux) ". 
Help me please how to solve this problem.
