### ISSUE TITLE
AudioPlayer not paused while wake up on PlaybackStarted status

### ISSUE THREAD

**Issue by jacky-ge** [alexa/avs-device-sdk#204]
The problem is easy to come up with,  and it will result in multiple sounds.

Reproduction：
1、first play Music loop or play book.
2、wake up and talk with AudioPlayer playing.

**Comment by kclchan** [comment]
Could you clarify what you mean by "multiple sound"?  Does it mean that AudioPlayer will kept on playing in the background after a barge-in?  If that's the case, then we should have a fix for this issue in our next software release.

**Comment by scotthea-amazon** [comment]
Hello jacky-ge,

There has been no answer to the last posted question for a long time, so I am closing this issue.  If I have closed it in error, please feel free to re-open it.

Thank you,
-SWH
