### ISSUE TITLE
avs-alexa-na.amazon.com url ping failed

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#2040]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We need to check the internet connection locally, when I test internet connection today using avs-alexa-na.amazon.com url (do ping test: ping -c 2 avs-alexa-na.amazon.com), it always fails. why? if it is not allowed to ping test, can you provide another internet address to check the internet connection?
Thanks!

### What version of the AVS Device SDK are you using?
      <1.22>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @BobXLiu,

It's not advised to check internet connection by pinging that endpoint. If your device has already gone through discovery and is authorized, you can check AVS connection by pinging the assigned gateway (this is assigned by AVS on discovery): 
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/manage-http2-connection.html#ping-timeout

Discovery documentation:
https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/alexa-apigateway.html

However, note that this is different from internet connectivity of your device as a whole. If that is the goal, there is not an official URL that Alexa provides for that.

**Comment by blazusiak-amazon** [comment]
Hello @BobXLiu,
Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question was not been answered fully.
