### ISSUE TITLE
Which version of OPUS codec 

### ISSUE THREAD

**Issue by msabatin** [alexa/avs-device-sdk#2042]
Hello. I just have a general question about the version of OPUS required for AVS and AMA.

As I understand it from examining the specifications, the current minimum version of OPUS required by Amazon is 1.2.1. My question is if there are any plans to upgrade this minimum requirement in the foreseeable future to 1.3.1. 

Thanks

**Comment by wryley-amzn** [comment]
Is there a specific reason for the minimum upgrade inquiry? Is there something incompatible with upgrading the version?

**Comment by msabatin** [comment]
No, just looking for clarity if we need to start preparing for an upgrade of OPUS. Good that we can stick to 1.2.1 for now.
