### ISSUE TITLE
C++ condition_variable wait_for api cause CPU loading high

### ISSUE THREAD

**Issue by ape-ai** [alexa/avs-device-sdk#2049]
i found an issue about when using the C++ condition_variable api wait_for and the wait duration set to std::chrono::steady_clock::now() + std::chrono::hours(1000000) will cause the CPU loading higher than other wait duration (like 10 seconds). maybe the std::chrono::steady_clock::now() + std::chrono::hours(1000000) is overflow cause the CPU loading is higher.

https://github.com/alexa/avs-device-sdk/blob/7f9b5b7885640cf0df676ef3a777d456332d284b/AVSCommon/Utils/include/AVSCommon/Utils/Timing/DistantFuture.h#L35

**Comment by sharmajs-amzn** [comment]
Hello @ape-ai ,
Could you provide the information provided in the template so that we can better help you:

    Summary of the issue
    Expected Behavior
    Steps to Reproduce
    Version of the SDK being used
    Hardware and OS being used

**Comment by blazusiak-amazon** [comment]
Hello @ape-ai,
Due to the inactivity of this ticket, this ticket will be closed. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.
