### ISSUE TITLE
Alexa with WWE: current status

### ISSUE THREAD

**Issue by RafigRzayev** [alexa/avs-device-sdk#2050]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We want to add Alexa into our product. Our product requires hands-free operation of Alexa, so we have to use wake word engine. These two issues are relevant: https://github.com/alexa/avs-device-sdk/issues/1976 and https://github.com/alexa/avs-device-sdk/issues/2004.

We have tried the method provided by users in https://github.com/alexa/avs-device-sdk/issues/1976, it works with manual operation, and workaround to make it automatic with terminals is not working properly in our system. 

Please correct me if I am wrong, but it looks to me that today there is no official way to do this. The Sensory and Kitt-AI are closed projects. And there is no official example for Porcupine. 

Could you please tell then what is supported option? How do all these Alexa home devices operate if there is no supported WWE engine? 

As I have read through opened issues on this repository, I believe a lot of people need a common thing: an example which is hands-free, and works automatically after boot. 

Could you please make an example with an active WWE that end-users can use? If not, could you provide guidance about what to change in the SDK code in order to integrate WWE(e.g Porcupine)? 

I would appreciate any help.

### What version of the AVS Device SDK are you using? 
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Rock Pi 4B

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
@RafigRzayev, if not done already, please create a Amazon developer account (https://developer.amazon.com/en-US/docs/alexa/ask-overviews/create-developer-account.html).  After an account is created, you can contact our [AVS Support Center](https://developer.amazon.com/alexa/console/avs/support) for support regarding WWE.

**Comment by RafigRzayev** [comment]
@kclchan I responded to an email and my colleague also wrote through developer account. Through developer account we got following reply:  

> Due to the high volume of interest, we are not currently able to accommodate this request. Thank you for your understanding.

And I didn't get reply on the email (wrote 11 days ago).

**Comment by RafigRzayev** [comment]
Closing the issue. As I have understood, this topic is could be solved on corporate level, not through here.
