### ISSUE TITLE
Echo Show has songs come up as recently played that are not something we played? I have several devices in our home, but these explicit songs are not what we listen to.  I have 2 Echo Dots and one Show. Could these songs be from the neighbor's device?

### ISSUE THREAD

**Issue by BALDEAGLEVETERANs** [alexa/avs-device-sdk#2051]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by blazusiak-amazon** [comment]
Hello @BALDEAGLEVETERANs
