### ISSUE TITLE
Build Error - WorkerThread.cpp:59:20: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]

### ISSUE THREAD

**Issue by akhabali** [alexa/avs-device-sdk#2052]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Build failing on Windows 10 with (MINGW64_NT-10.0-19044) as follows

```
[ 25%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WorkerThread.cpp.obj
C:/msys64/home/me/projects/amazon-avs/avs-device-sdk/AVSCommon/Utils/src/WorkerThread.cpp:59:20: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
    m_workerFunc = move(workFunc);
                   ^
                   std::
1 error generated.
make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:1574: AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WorkerThread.cpp.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:8362: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:15426: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:4209: SampleApp] Error 2
```

## Provide the steps to reproduce the issue, if applicable:

Run build from master branch on windows 10 using the setup.sh script

### What version of the AVS Device SDK are you using?
      Master branch

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows 10 (MINGW64_NT-10.0-19044))

**Comment by blazusiak-amazon** [comment]
Hello @akhabali,

Thank you for bringing this issue to our attention. 
A formal fix for this issue is being investigated internally.
In the meantime, this issue can be resolved by including `std::` before the move function call in `avs-device-sdk/AVSCommon/Utils/src/WorkerThread.cpp:59:20`

```
m_workerFunc = std::move(workFunc);
```

**Comment by kclchan** [comment]
Closing the ticket since a solution has been provided.

**Comment by zrrbite** [comment]
I've also found this issue in the following files:

DavsRequest.cpp 
UrlRequest.cpp
VendableArtifact.cpp
