### ISSUE TITLE
clang++: error: invalid linker name in argument '-fuse-ld=lld'

### ISSUE THREAD

**Issue by akhabali** [alexa/avs-device-sdk#2054]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The setup.sh fails on Windows MINGW64 with the following error:

Is the `wingw.sh` script responsible of installing required dependencies missing a required component ?

```
...
################################################################################
Proceeding with installation
################################################################################
Consolidate compiler generated dependencies of target acsdkCryptoInterfaces
[  0%] Linking CXX shared library ../../../../bin/libacsdkCryptoInterfaces.dll
Consolidate compiler generated dependencies of target AVSCommon
clang++: error: invalid linker name in argument '-fuse-ld=lld'
make[3]: *** [core/Crypto/acsdkCryptoInterfaces/src/CMakeFiles/acsdkCryptoInterfaces.dir/build.make:114: bin/libacsdkCryptoInterfaces.dll] Error 1
make[2]: *** [CMakeFiles/Makefile2:11689: core/Crypto/acsdkCryptoInterfaces/src/CMakeFiles/acsdkCryptoInterfaces.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/WorkerThread.cpp.obj
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/FileSystem/FileSystemUtilsWindows.cpp.obj
[  2%] Linking CXX shared library ../bin/libAVSCommon.dll
clang++: error: invalid linker name in argument '-fuse-ld=lld'
make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:1828: bin/libAVSCommon.dll] Error 1
make[2]: *** [CMakeFiles/Makefile2:8360: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:15421: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:4209: SampleApp] Error 2
```

## What is the expected behavior?

setup.sh to work without errors

## Provide the steps to reproduce the issue, if applicable:

follow the steps here https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/windows-64.html

### What version of the AVS Device SDK are you using?
      master (1.26.0)

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows 10 (MINGW64_NT-10.0-19044)

**Comment by blazusiak-amazon** [comment]
Hello @akhabali, 
Thank you for bringing this issue to our attention.
A formal fix for this issue is being investigated internally. In the meantime you can try the following. 
Within the mingw.sh file on Line 37, could you update the code to the following:
```
pacman -S ${PACMAN_ARGS} git mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-lld mingw-w64-x86_64-cmake msys/tar msys/make
```

**Comment by kclchan** [comment]
Closing the ticket since a solution has been provided.
