### ISSUE TITLE
VERBOSE

### ISSUE THREAD

**Issue by sugie** [alexa/avs-device-sdk#2058]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by blazusiak-amazon** [comment]
Hello @sugie,
Due to the issue being empty, I will close it. Please feel free to open a new ticket with a complete explanation of the issue you are experiencing or the question that you have.
