### ISSUE TITLE
Adding support for porcupine

### ISSUE THREAD

**Issue by fmarotta** [alexa/avs-device-sdk#2060]
Hi there, this past weekend I decided to take up the challenge posed by @kenarsa in #2004 and #1976, and eventually implemented a wrapper class for Porcupine. The wake word detection works fine! It was quite a bit of work for me, and the process was not documented anywhere, so it might be interesting for somebody to have at least an example of how to add a custom WWE. The code is now in [my fork](https://github.com/fmarotta/avs-device-sdk): would a PR be welcome?

**Comment by rowisahub** [comment]
Man, thank you.
I've been trying to rap my head around trying to do the same thing for like a year now. This is going to help a lot.
I would honestly love to see this as a PR.

If i can figure it out, I'll add a PR for [Implement Wake Word Verification](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/avs-ww-overview.html).

But you've helped my a lot, thank you so much

**Comment by watsocao** [comment]
Hi @fmarotta ,
Thank you for your hard work to integrate a custom WWE, however, we could not take a PR due to licensing. I will close this ticket. Please feel free to re-open the ticket if you have more questions or feel that your question has not been answered fully.

**Comment by Ian-Zz** [comment]
> Hi there, this past weekend I decided to take up the challenge-- The code is now in [my fork](https://github.com/fmarotta/avs-device-sdk): would a PR be welcome?

This looks very cool and thanks for it.
But first. Could you be so kind to tell me what sort of porcupine install I would do on a pi3 running pi os bullseye. I tried it with the pip3 python install and setting paths. If python isn't the way to go please advise. I am not able to buld the app yet with your repository. Thanks again.

**Comment by BadGones0l** [comment]
Hello 

Hello 

I succeeded to configure porcupine, using the C++ repository
However, I have a problem with the environment variables

![image](https://user-images.githubusercontent.com/66170163/226688973-6cf5f4d7-5215-44c4-9abe-b6251fa60c9c.png)


![image](https://user-images.githubusercontent.com/66170163/226689561-2fe74808-047d-4841-bd9a-a942d9af4b4d.png)

Can you help me
