### ISSUE TITLE
Code typo in SDK V3.0 Quickstart Guide for Raspberry Pi

### ISSUE THREAD

**Issue by ulritter** [alexa/avs-device-sdk#2063]
There is a code typo in the SDK V3.0 Quickstart Guide for **Raspberry Pi** which causes cmake to terminate with a fatal error (websocketpp/server.hpp: file not found):

In "[https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/smart-screen-raspberry-pi.html](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/smart-screen-raspberry-pi.html)" 
at 
"Step 3: Download and build the AVS Device SDK and IPC Server Sample Application" 
in topic 
"3. The following CMake command builds the dependencies for IPC Server Sample Application":
the line 

 -DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk_folder/third-party/websocketpp-0.8.2 \
should be  
-DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk-folder/third-party/websocketpp-0.8.2 \
(underscore needs to be replaced with hyphen)

**Comment by powj** [comment]
Thank you for reporting this issue, we will ensure the documentation is updated.

**Comment by watsocao** [comment]
We have updated the document so close it.
