### ISSUE TITLE
Supporting Android in the 3.0.0 SDK

### ISSUE THREAD

**Issue by KushtrimPacaj** [alexa/avs-device-sdk#2067]
On the previous version of avs-device-sdk, there was the option to build for Android, but based on the readme in 3.0.0 it has been dropped as supported platform. ( It lists only Ubuntu Linux, Raspberry Pi, macOS ).

Why was Android dropped, and are there plans to officially support Android in 3+ SDKs?

**Comment by watsocao** [comment]
Hi @KushtrimPacaj ,
Thank you for your interest on integrating Alexa avs-device-sdk with Android application. You are right that 3.0.0 release does not support Android. We do not have plan to support Android atm.
