### ISSUE TITLE
How to set a Europe timezone for Sample Console App?

### ISSUE THREAD

**Issue by tcsabina** [alexa/avs-device-sdk#2076]
Currently my Sample Console App has wrong time. Looking at the settings of the console app I can only select timezones in the US.
Is it possible to set an EU timezone, UTC+1 for example?

**Comment by frolland04** [comment]
Hello,
as a workaround, I added these 2 lines in my build script, just after calling 'genConfig.sh' :

sed -i 's/"defaultLocale":"en-US",/"defaultLocale":"fr-FR",/g' $SDK_CONFIG_FILE
sed -i 's/"defaultTimezone":"America\/Vancouver"/"defaultTimezone":"Europe\/Paris"/g' $SDK_CONFIG_FILE

(where $SDK_CONFIG_FILE is the full path to AlexaClientSDKConfig.json)
Doing so, Alexa client is ready from the start, using my language and TZ.
F.

**Comment by tcsabina** [comment]
> Hello, as a workaround, I added these 2 lines in my build script, just after calling 'genConfig.sh' :
> 
> sed -i 's/"defaultLocale":"en-US",/"defaultLocale":"fr-FR",/g' $SDK_CONFIG_FILE sed -i 's/"defaultTimezone":"America/Vancouver"/"defaultTimezone":"Europe/Paris"/g' $SDK_CONFIG_FILE
> 
> (where $SDK_CONFIG_FILE is the full path to AlexaClientSDKConfig.json) Doing so, Alexa client is ready from the start, using my language and TZ. F.

Thanks, this probably would help some!

In the meanwhile I've managed to change it with the help of the mobile phone app. I've downloaded it, connected my sample app to it and in the setting I was able to change the timezone.
