### ISSUE TITLE
how to make avs device sdk without google test support ?

### ISSUE THREAD

**Issue by DiazSo** [alexa/avs-device-sdk#208]
Hi Sir,

Is it possible to make avs device sdk without google test support?
it seems google test is enabled in default. How to disable ?

Thanks!

**Comment by kclchan** [comment]
Hi @DiazSo, we will add a way to do this in our future release.  In the meantime, please try "make SampleApp".  This should only build the SDK without the tests.  Thanks!

**Comment by kclchan** [comment]
Hi @DiazSo, we have added in v1.2 of the SDK a new cmake option "-DACSDK_EXCLUDE_TEST_FROM_ALL=ON" so that tests will not be built with make all.   Thanks!
