### ISSUE TITLE
Issue with Installation - Stuck at Building DefaultClient and DefaultClientBuilder

### ISSUE THREAD

**Issue by Maldrik** [alexa/avs-device-sdk#2090]
Hello everyone,

I've been trying to install the Alexa AVS Device SDK on my Raspberry Pi but have encountered an issue. The installation gets stuck at the building stage of DefaultClient and DefaultClientBuilder, and I haven't been able to find a solution.

At time of stuck, the following text is on the display:

Building CXX object ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClientBuilder.cpp.o
Building CXX object ApplicationUtilities/DefaultClient/src/CMakeFiles/DefaultClient.dir/DefaultClient.cpp.o

Unfortunately, the progress stalls at 97%, and the installation terminates thereafter.

I've already attempted the installation multiple times, but the problem persists. Additionally, I tried manually compiling the "DefaultClientBuilder.cpp" and "DefaultClient.cpp" files using the g++ -c command to generate the object files. However, this resulted in another error:

arduino

DefaultClient.cpp:16:10: fatal error: acsdkExternalMediaPlayerInterfaces/ExternalMediaAdapterConstants.h: No such file or directory
   16 | #include <acsdkExternalMediaPlayerInterfaces/ExternalMediaAdapterConstants.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

It seems that during the compilation of "DefaultClient.cpp," a required header file named "ExternalMediaAdapterConstants.h" cannot be found.

I have already searched the documentation of the Alexa AVS Device SDK and developer community for solutions, but so far, I haven't had any success.

Has anyone else experienced a similar issue or found a solution? I would greatly appreciate any help or advice to successfully complete the installation.

Thank you in advance!

**Comment by Rohithprime** [comment]
Try this
From the command line, run the following commands to increase the virtual memory on your device.

Stop the operating system from using the current swap file.

sudo dphys-swapfile swapoff

Modify the swap file configuration file.

sudo nano /etc/dphys-swapfile

Find CONF_SWAPSIZE in the file, and then update it to 2048.
CONF_SWAPSIZE=2048

Reinitialize the swap file of your Raspberry Pi.

sudo dphys-swapfile setup

Turn the swap system back on.

sudo dphys-swapfile swapon

Restart your Raspberry Pi.

sudo reboot

Link for this code:
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/troubleshooting.html

**Comment by Maldrik** [comment]
Yes, it works. 
Thank you so much :)
