### ISSUE TITLE
Missing $ in Integration/AlexaClientSDKConfig.json ?

### ISSUE THREAD

**Issue by pthedinger** [alexa/avs-device-sdk#213]
In Integration/AlexaClientSDKConfig.json, should:

"certifiedSender":{ 
        "databaseFilePath":"{SDK_CERTIFIED_SENDER_DATABASE_FILE_PATH}"
    }

be

"certifiedSender":{ 
        "databaseFilePath":"${SDK_CERTIFIED_SENDER_DATABASE_FILE_PATH}"
    }

?

**Comment by kclchan** [comment]
Hi @pthedinger, 

{SDK_CERTIFIED_SENDER_DATABASE_FILE_PATH} is meant to be replaced with the file path to where the database file is located.  A database file will be created at that location if the database does not already exist.

For example:
"certifiedSender":{
"databaseFilePath":"/home/anExistingFolder/anotherExistingFolder/certifiedSender.db"
}

Thanks,
Kenneth

**Comment by pthedinger** [comment]
If the file contains variables (hence the request to add the missing $) then you can run a command like this:
`envsubst < $SOURCE/Integration/AlexaClientSDKConfig.json > $BUILD/Integration/AlexaClientSDKConfig.json`

to automatically replace all of these variables without having to manually edit the files.

**Comment by BennyAvramson** [comment]
Hi @pthedinger,

As @kclchan said it just meant to be a place holder. But you made a good point and we may consider it internally.

Thanks,
Benny
