### ISSUE TITLE
AVS 1.1.0 supprted featurs

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#222]
Please clarify what new features are supported for AVS 1.1.0. The Read me file and Changelog.md file does not match.
**From, Readme :** 
v1.1 released 10/02/2017:
Enhancements
•The SDK now supports TuneIn, Audible, Pandora, SiriusXM, Kindle Books, and Amazon Music.
•Added a capability agent for Settings, which allows a client to notify Alexa of locale changes.

From Changelog.md :

[1.1.0] - 2017-10-02
•Enhancements
◦Better GStreamer error reporting. MediaPlayer used to only report  MEDIA_ERROR_UNKNOWN , now reports more specific errors as defined in  ErrorType.h .
◦Codebase has been formatted for easier reading.

No mention of Amazon music , Audible etc.

**Comment by dhpp** [comment]
Hi shikha-bansal,

Thanks for bringing this to our attention.  Please go with the readme text.  We will correct this in our next release (and update our process to avoid this in future).

-David

**Comment by shikha-bansal** [comment]
If the README txt is correct , I tried playing music via amazon music , but it says 
"Amazon music is not supported on this device".

Nor am I able to use Audible and other services.

**Comment by shikha-bansal** [comment]
Sorry , I am able to use Audible  , Kindle books and TuneIn.
 
But the music apps Amazon music , Pandora, SiriusXM it says they are not supported,

**Comment by chenxiaoqun** [comment]
Same question, Amazon music/Pandora/Spotify have not supported for me also in AVS 1.1

Amazon music/Pandora/Spotify are not supported by voice commands, it replies "Amazon music(Spotify or Pandora) is not supported on this device"

But there is a little different when checking with Alexa App.

1Launch the Alexa app.
2Tap the Menu button in the top left corner > Music，Books & Books > Pandora.  it says "App Support Unavailable"
2Tap the Menu button in the top left corner > Music，Books & Books > Spotify.  it says "App Support Unavailable"
3 But 2Tap the Menu button in the top left corner > Music，Books & Books > Music.  everything seems fine and cast the music to the device works too.
