### ISSUE TITLE
gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#224]
when i install mediaplayer process,i face the issue and how to solve it?

**Comment by MikeYen** [comment]
what is the os version you use?

**Comment by captainpanther** [comment]
ubuntu 14.04

**Comment by dhpp** [comment]
Hi there, can you please provide more details about the issue you're facing?

**Comment by captainpanther** [comment]
i build the media player process , to use "cmake <path-to-source> -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=<path-to-GStreamer-build>"  ,and appear this issue 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'

**Comment by scotthea-amazon** [comment]
Hello captainpanther,

Sorry for the long delay in getting back to you.  That message indicates that you are attempting to build with a version of gstreamer that is less than the required minimum.  See: [MediaPlayer Reference Implementation Dependencies](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#mediaplayer-reference-implementation-dependencies).

Please let us know if this helps you or if you have already gotten past this problem.

Thank you,
-SWH

**Comment by sanjayrd** [comment]
I'm going to go ahead and close this issue @captainpanther, since based on your other issues, it looks like you got past this step. Please reopen if that isn't the case.

Thanks,
Sanjay
