### ISSUE TITLE
Could NOT find CURL: Found unsuitable version "7.35.0", but required is at   least "7.43.0"

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#225]
OS:ubuntu 14.04

which method to solve it!

**Comment by snailwft** [comment]
hi @captainpanther 
The libcurl version you should install >= 7.43.0, your current version is 7.35.0.

**Comment by dhpp** [comment]
Thanks snailwft for answering the question.  captainpanther, please re-open this ticket if that does not resolve your issue.
