### ISSUE TITLE
When I execution  TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json DEBUG9 generate the following error

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#228]
hi, 
I execution it without build with a Wake Word Detector,please help me.

# TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json DEBUG9 
Running app with log level: DEBUG9
2017-10-11 11:30:43.398 [  1] I ConfigurationNode:initializeSuccess

(SampleApp:16822): GStreamer-WARNING **: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
2017-10-11 11:30:43.772 [  1] E AlertsCapabilityAgent:initializeDefaultSoundsFailed::could not read alarm audio file path.
2017-10-11 11:30:43.772 [  1] E AlertsCapabilityAgent:initializeFailed::Could not initialize default sounds.
2017-10-11 11:30:43.772 [  1] E AlertsCapabilityAgent:createFailed:reason=Initializion error.
2017-10-11 11:30:43.774 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=AlertsCapabilityAgent
2017-10-11 11:30:43.774 [  1] E DefaultClient:initializeFailed:reason=unableToCreateAlertsCapabilityAgent
2017-10-11 11:30:43.774 [  1] I DirectiveSequencer:doShutdown
Failed to create default SDK client!

(SampleApp:16822): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-10-11 11:30:49.035 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:16822): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:16822): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed

(SampleApp:16822): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
2017-10-11 11:30:49.038 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed

(SampleApp:16822): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:16822): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed
Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by Longynus83** [comment]
Hi @snailwft ,
Based on the log you posted it seems like the client is unable to find the sounds path.

The client needs up to 4 files (2 mp3, one for alarm and one for timer, and 2 wav, one for alarm and one for timer) to be present, and their path must be provided by updating the AlexaSDKClient.json configuration file.

Audio files can be downloaded by having a look at the "Timers and Alarms" section at the following URL:

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/alexa-voice-service-ux-design-guidelines#attention

Additionally, do not forget to just put in the same configuration file the path for the alert database (e.g. /home/alert.db), as if it does not exist it will be automatically created.

Regards

**Comment by rustihammer** [comment]
I remembered I came across the same issue when I first tried to build this.  It wasn't expected the SampleApp wouldn't run without these files.  I would suggest to commit these sound files and database files even the db files are empty.  There are already too much setups before the SampleApp can run!

**Comment by snailwft** [comment]
hi @Longynus83 @rustihammer 
I downloaded the sound file. In your way, it's passed now. Thank you very much.

**Comment by dhpp** [comment]
Thanks all.  

Yes, the AlertsCapabilityAgent requires these things to be provided in the configuration, or it will fail its create() method.  Subsequently, the SampleApp cannot run.
