### ISSUE TITLE
Without -DGSTREAMER_MEDIA_PLAYER=ON make SampleApp don't work

### ISSUE THREAD

**Issue by lucastanure** [alexa/avs-device-sdk#229]
Configuration without -DGSTREAMER_MEDIA_PLAYER=ON doesn't build SampleApp

**Comment by Longynus83** [comment]
Hi @lucastanure ,
The behavior you reported is pretty normal, and cannot be considered an issue. 

As per available guidelines, to build the Alexa client both dependencies from PortAudio and GStreamer are mandatory, as the SampleApp Cmake file will check for both of these to be matched and, in case it is unable to find them, it will silently skip the SampleApp build process, as per following extract from the CMake file:

if(PORTAUDIO AND GSTREAMER_MEDIA_PLAYER) add_subdirectory("src") endif()

Additionally, GStreamer is used inside the Alexa client to get the audio stream and route it toward the default audio output (via an ad hoc GStreamer pipeline).

Regards

**Comment by Longynus83** [comment]
Hi @lucastanure  ,
The behavior you reported is pretty normal, and cannot be considered an issue.

As per available guidelines, to build the Alexa client both dependencies from PortAudio and GStreamer are mandatory, as the SampleApp Cmake file will check for both of these to be matched and, in case it is unable to find them, it will silently skip the SampleApp build process, as per following extract from the CMake file:

if(PORTAUDIO AND GSTREAMER_MEDIA_PLAYER) add_subdirectory("src") endif()

Additionally, GStreamer is used inside the Alexa client to get the audio stream and route it toward the default audio output (via an ad hoc GStreamer pipeline).

Regards

**Comment by dhpp** [comment]
Thanks Longynus83.
