### ISSUE TITLE
Getting stuck in "Listening" state - sdk v1.1.0

### ISSUE THREAD

**Issue by az2022** [alexa/avs-device-sdk#231]
Randomly the sample app gets stuck in the "Listening" state and doesn't recover until user intervenes, i.e. I need to press 'S' to stop the interaction and issue the command again to get it work. So far I have only seen this when the app first starts. (BTW, I have seen the same behavior in v1.0.3. but I am currently using v1.1.0 and the issue still shows). The issue doesn't happen all the time but seems like 1 in 4 times. Here's the log with debug9 enabled:

*******************************************************************************
Running app with log level: DEBUG9
2017-10-12 01:02:52.421 [  1] I ConfigurationNode:initializeSuccess
2017-10-12 01:02:52.704 [  1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1f22e08,policy=BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x1f23498,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x1f23498,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x1f23498,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x1f22388,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x1f22388,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x1f24108,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x1f24108,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x1f2d020,policy=NON_BLOCKING
2017-10-12 01:02:52.709 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x1f22144,policy=NON_BLOCKING
#############################
#       Connecting...       #
#############################
########################################
#       Alexa is currently idle!       #
########################################
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
2017-10-12 01:02:55.526 [  1] I SensoryKeywordDetector:License expires on 28 Jan 2018 00:00:00 GMT
2017-10-12 01:02:55.527 [  1] I SensoryKeywordDetector:Sensory library license does not expire for at least 60 more days.
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

############################
#       Listening...       #
############################
2017-10-12 01:02:59.729 [  2] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=0c30a3d5-1b46-4fc2-b2a5-cdaa94fdd6ea
2017-10-12 01:03:30.023 [  3] I HTTP2Transport:streamProgressTimedOut:streamId=5

*********************************
I don't see anything logged into the History log on alexa.amazon.com.

**Comment by dhpp** [comment]
Hi az2022,

The ALSA trace looks suspicious, so could you please take a look at the audio dependencies as specified [here](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies)?  Let us know if this addresses the issue for you, thanks.

**Comment by az2022** [comment]
I have installed the SDK on a fresh copy of Raspbian Stretch and followed the instructions as detailed on your website at: https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide. 

Here's what I have:

gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)

cmake version 3.7.2

curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

nghttp2 - shared library v1.18.1 installed 

OpenSSL 1.1.0f  25 May 2017

Don't have Doxygen

sqlite3 - shared library v3.16.2 installed (this is what can be downloaded with Stretch, vs 3.19.3 mentioned in your min requirements. Since I am testing Alerts, this shouldn't matter?)

gstreamer - 1.10.4 (Do have all the good, bad, ugly, av plugins as well).

As for the Alsa traces, I have tried sdks 1.0.2 (Jessie), 1.0.3(Jessie) and now 1.1.0(Stretch) but ALSA lib has never stopped complaining! Doesn't seem any different now.

The fact that when I press "s" it get's out of the stuck state and starts functioning normally (shown below log), I hope should point to something?

############################
#       Listening...       #
############################
2017-10-12 20:00:51.223 [  2] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=0c30a3d5-1b46-4fc2-b2a5-cdaa94fdd6ea
2017-10-12 20:01:21.554 [  3] I HTTP2Transport:streamProgressTimedOut:streamId=5

s  (<======================= PRESSING STOP HERE==================)

########################################
#       Alexa is currently idle!       #
########################################
############################
#       Listening...       #
############################
2017-10-12 20:01:53.070 [  2] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=0c30a3d5-1b46-4fc2-b2a5-cdaa94fdd6ea,newValue=49e271af-0ac0-4ee6-ab50-b74786199551
2017-10-12 20:01:55.133 [  4] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"1b36981d-c24f-4568-8462-2604a4132db4"\,dialogRequestId\:""}
2017-10-12 20:01:55.134 [  5] I DirectiveRouter:preHandleDirective:messageId=1b36981d-c24f-4568-8462-2604a4132db4,action=calling
2017-10-12 20:01:55.134 [  6] I DirectiveRouter:handleDirective:messageId=1b36981d-c24f-4568-8462-2604a4132db4,action=calling
###########################
#       Thinking...       #
###########################
2017-10-12 20:01:55.143 [  3] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2017-10-12 20:01:55.423 [  4] I DirectiveSequencer:onDirective:directive={"namespace\:"Speaker"\,name\:"SetMute"\,messageId\:"c525e0b3-7f4f-48e3-bf19-ab201180a45a"\,dialogRequestId\:"49e271af-0ac0-4ee6-ab50-b74786199551"}
2017-10-12 20:01:55.423 [  5] W DirectiveRouter:preHandleDirectiveFailed:messageId=c525e0b3-7f4f-48e3-bf19-ab201180a45a,reason=noHandlerRegistered
2017-10-12 20:01:55.423 [  5] I DirectiveSequencer:sendingExceptionEncountered:messageId=c525e0b3-7f4f-48e3-bf19-ab201180a45a
2017-10-12 20:01:55.423 [  4] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"4ff72a1a-e7e1-4f2f-9803-062800bc1caa"\,dialogRequestId\:"49e271af-0ac0-4ee6-ab50-b74786199551"}
2017-10-12 20:01:55.424 [  5] I DirectiveRouter:preHandleDirective:messageId=4ff72a1a-e7e1-4f2f-9803-062800bc1caa,action=calling
2017-10-12 20:01:55.425 [  6] I DirectiveRouter:handleDirective:messageId=4ff72a1a-e7e1-4f2f-9803-062800bc1caa,action=calling
2017-10-12 20:01:55.513 [  7] I InProcessAttachmentReader:readFailed:reason=SDS is closed
###########################
#       Speaking...       #
###########################
########################################
#       Alexa is currently idle!       #
########################################

**Comment by az2022** [comment]
So, after a bit of digging in, seems like whenever it doesn't work, I see the function "HTTP2Stream::writeCallback" called right after the wakeword is issued, i.e. right after I say "Alexa" and the curl_easy_getinfo responds with a code of 400. While in the case that does work, the "HTTP2Stream::writeCallback" function is NOT called till the entire question is complete, i.e. "Alexa, what time is it" and ofcourse the response code at this time is 200. I am not familiar with curl so not sure what prompts this behavior.

**Comment by az2022** [comment]
Issue appears to be fixed with sdk v1.2.0.
