### ISSUE TITLE
Alexa SampleApp v.1.1.0 - Unable to play any TuneIn station

### ISSUE THREAD

**Issue by Longynus83** [alexa/avs-device-sdk#236]
Good day everyone, 
I am testing the Alexa client aligned to v.1.1.0 release. During my test session I am able to successfully ask questions to Alexa, but when it comes to ask Alexa to play a station from TuneIn (tap to talk, and then ask "Play the station The Legend" e.g.) I hear "The legend from TuneIn" but then no sound comes out. I tested almost 30 radios, without getting the chance of being able to play any of them.

I attach to this ticket the log acquired from the SampleApp test session with DEBUG9 level.

Having a quick look, the only errors I noticed in the log when asking for a TuneIn station is about some missing fields in the JSon.

Thanks indeed for your support

[alexaClientLog_20171012_165453.log](https://github.com/alexa/avs-device-sdk/files/1379775/alexaClientLog_20171012_165453.log)

**Comment by dhpp** [comment]
Hi Longynus83,

Has this worked for you previously?  The logs look ok, and the missing JSON fields don't prevent the AudioPlayer from attempting to render the url.  TuneIn provides urls from within their own network, and I believe we have seen issues before where some of those urls were not accessible to some customers.

If this always breaks for you, then we can investigate further.

**Comment by Longynus83** [comment]
Hi @dhpp,
Thanks for your feedback. Yesterday, after posting the  issue I tried again several times (most likely 40-50 radios) and I succeeded only once with one of the radios that did not worked previuosly.

Additionally, using the same account and credential with the javaclient with one of the radios that was not working with C++ agent, It succeeded at first attempt.

The strange thing is that right after asking for the TuneIn radio, the agent react as if immediately after the radio audio would be played and, after this, nothing happens (that is different from other scenarios where the "...radio is currently unavailable" text is played).

**Comment by Longynus83** [comment]
Hi All,
any hint on this?

Thanks indeed

**Comment by Longynus83** [comment]
Good day everyone, 
is anybody having a look/investigating the issue that I reported?

Could you please provide an update on this?

Thanks indeed

**Comment by ryan-esty** [comment]
Have you tried doing the news flash briefing? I get the alexa words of what service I picked then when the actual content comes I get nothing.

**Comment by Longynus83** [comment]
@ryan-esty Same behavior on my side, I mean, for the flash news. At the time being I am unable to get TuneIn as well as flash news, and I tested flash news in the past without problems...this is why I opened this issue.

Regards

**Comment by ryan-esty** [comment]
@Longynus83 same as me this worked in the past and now is broken. I even had iheartradio working and now it doesn't. I had to make changes to get my stuff to work in my environment but if others are having issues I'm guessing it isn't those changes.

**Comment by Longynus83** [comment]
@dhpp Do you think it is possible to mark this issue for investigation on your side, as based on what @ryan-esty reported it seems like I am not the only one that is facing issued with C++ SDK features like this.

My apologize for the direct mention in this post, but I am really looking forward to the next SDK update to get this issue hopefully fixed.

Thanks and Regards

**Comment by ryan-esty** [comment]
@Longynus83 I was able to back down to 1.0.2 and one change that I put in that could of broke the later build is using alsasink. I'm trying to use pulsesink now and see if I can get it working. Not sure if you tried using alsasink in MediaPlayer or not.

**Comment by krishnaswamyna** [comment]
@Longynus83 Same behavior on myside for news as well.
@dhpp Is this being worked on or do you think if there is any setup issue on our side? Can you suggest any changes we can try?

**Comment by ryan-esty** [comment]
@krishnaswamyna  did it break when you went from 1.0.2 to 1.1.0 or did it never work? I'm still using 1.0.2 and this feature seems to work with only pulseaudio but I can't say for certain. I had to change the code for my project as autoaudiosink doesn't work for me. It seems others have 1.1.0 working with the news services and streaming so I don't think something broke.

**Comment by Longynus83** [comment]
I was using the TuneIn radio with acceptable success ratio of getting a radio played with previous versions of the SDK (the last I remember is v.1.0.3, but I cannot give it for 100% sure...much better to rely on v.1.0.2).

After upgrading to v.1.1.0 I get the 100% of failure ratio trying to play a TuneIn radio, so there must be something that resulted in this feature to be broken. Please, be aware that I am not saying that this is necessarily an issue in the Alexa SDK, as it can also be a compatibility issue with all the linked libraries for example.

At least I am not the only one facing such issue, so this should help in root-causing this issue.

Regards

**Comment by bandkenamazoncom** [comment]
Thanks for the details.  We are looking into it.   Are all TuneIn channels not working, or is it a few specific ones?

**Comment by ryan-esty** [comment]
@bandkenamazoncom when I upgraded to 1.1.0 even the news flash briefing didn't work and I think that is true for others in this thread.

**Comment by Longynus83** [comment]
Additionally, using same credential that I am currently using in Alexa C++ SDK in the javaclient is resulting in different behavior: the javaclient works like a charm with TuneIn radio using the same credentials for getting the refresh token, so most likely is not something related to the account itself.

@bandkenamazoncom In my case all TuneIn channels either return "XXX is currently unavailable" or in the strangest scenario right after asking for the TuneIn radio, the agent react as if immediately after the radio audio would be played (saying "here is XXX from TuneIn" or something like this) and, after this, nothing happens...

**Comment by bandkenamazoncom** [comment]
There are a number of deadlocks in MediaPlayer that we are fixing in the next release, and it looks like this is one of those.  Please stay tuned!

**Comment by krishnaswamyna** [comment]
@ryan-esty I tried directly on v1.1.0 and flash briefing did not work. It speaks out the source and after that there is no audio. I did not try on any previous release. But yes i could try on v1.0.3. 

I will also wait for next release as mentioned by @bandkenamazoncom

**Comment by ryan-esty** [comment]
All I upgraded to 1.2 and my streaming issues went away. Thanks avs-team.

**Comment by Longynus83** [comment]
@ryan-esty I still got no chance of trying the new release, but as per your feedback I am looking forward to this new drop...
