### ISSUE TITLE
Fatal error - Missing "snsr.h"

### ISSUE THREAD

**Issue by tkamaal** [alexa/avs-device-sdk#237]
I'm installing avs-device-sdk on to Raspberry Pi (OS - Stretch). During compilation I get an error stating snsr.h file is missing. I did look into the folders present in the avs-device-sdk project wasn't able to locate the header file. Kindly, help by providing some inputs.

**Comment by Sergogr** [comment]
This header file is from Sensory wake-word detector. You need to clone the following library: 
https://github.com/Sensory/alexa-rpi
Ans double check your make files that correct include path is configured.

Alternatively, you can build SDK without wake-word detection (only hold to speak and tap to speak features will work, thou).

**Comment by tkamaal** [comment]
Cloned the repo from https://github.com/Sensory/alexa-rpi and copied the "snsr.h" from Sensory to sdk-source/avs-device-sdk/KWD?Sensory/include/Sensory

After this, I don't see the "snsr.h" missing error but run into the following error 

make[2]: * No rule to make target '/home/pi/sdk-folder/third-party/alexa-rpi/lib/libsnsr.a', needed by 'KWD/Sensory/src/libSENSORY.so'.  Stop.
CMakeFiles/Makefile2:4233: recipe for target 'KWD/Sensory/src/CMakeFiles/SENSORY.dir/all' failed
make[1]: * [KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: * [all] Error 2

**Comment by tkamaal** [comment]
Cloned the latest repo again and followed the instructions to run SampleApp on Raspberry Pi 3 Model B. Things seem to be working. Closing this issue.

**Comment by safarcikm** [comment]
Hi, I came across the same issue, I did the same steps but I still can’t get over the resulting error. Could you clarify your steps after copying snsr.h?
