### ISSUE TITLE
cross compile issues

### ISSUE THREAD

**Issue by paragone** [alexa/avs-device-sdk#239]
hi guys,
           i cross compile the sdk with gcc of 4.8.3 and meet some problem.

[  0%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/ExceptionEncounteredSender.cpp.o
In file included from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskThread.h:25:0,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:24,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/include/AVSCommon/AVS/ExceptionEncounteredSender.h:26,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/src/ExceptionEncounteredSender.cpp:23:
/home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h: In function 'void alexaClientSDK::avsCommon::utils::threading::forwardPromise(std::shared_ptr<std::promise<T> >, std::future<T>*) [with T = void]':
/home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h:152:11: error: invalid use of incomplete type 'class std::future<void>'
     future->get();
           ^
In file included from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:21:0,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/include/AVSCommon/AVS/ExceptionEncounteredSender.h:26,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/src/ExceptionEncounteredSender.cpp:23:
/opt/toolchain/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:113:11: error: declaration of 'class std::future<void>'
     class future;
           ^
In file included from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskThread.h:25:0,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:24,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/include/AVSCommon/AVS/ExceptionEncounteredSender.h:26,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/src/ExceptionEncounteredSender.cpp:23:
/home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h:153:12: error: invalid use of incomplete type 'class std::promise<void>'
     promise->set_value();
            ^
In file included from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:21:0,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/include/AVSCommon/AVS/ExceptionEncounteredSender.h:26,
                 from /home/alexa/avs-device-sdk-1.1.0/AVSCommon/AVS/src/ExceptionEncounteredSender.cpp:23:
/opt/toolchain/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:122:11: error: declaration of 'class std::promise<void>'
     class promise;

can you guys give some advie,

**Comment by chenxiaoqun** [comment]
recommend to update the toolchain, the SDK source code uses lots of new C++ features

**Comment by JamieMeyers** [comment]
@paragone your compiler does not meet the minimum requirements per https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies. Please update to GCC 4.8.5 or later.

**Comment by octGitHub** [comment]
@JamieMeyers 

**I have quest about GCC version. ( Mine is 4.7.3 ...  what a pity )**

    Why you chosen  the GCC 4.8.5 to be the minus version when you started this SDK ?
    It's just because the dependent library needs or 
    most of the embedded  system has higher version  toolchain  than GCC 4.8.5 ?

**Comment by junlon2006** [comment]
**Mine gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)** 
 4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/CapabilityAgent.cpp.o
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  4%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/DialogUXStateAggregator.cpp.o
In file included from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskThread.h:23:0,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:22,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/DialogUXStateAggregator.h:28,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/DialogUXStateAggregator.cpp:16:
/home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h: In function ‘void alexaClientSDK::avsCommon::utils::threading::forwardPromise(std::shared_ptr<std::promise<T> >, std::future<T>*) [with T = void]’:
/home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h:150:11: error: invalid use of incomplete type ‘class std::future<void>’
     future->get();
           ^
In file included from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:19:0,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/DialogUXStateAggregator.h:28,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/DialogUXStateAggregator.cpp:16:
/usr/arm-linux-gnueabi/include/c++/5/future:115:11: note: declaration of ‘class std::future<void>’
     class future;
           ^
In file included from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskThread.h:23:0,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/Executor.h:22,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/DialogUXStateAggregator.h:28,
                 from /home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/DialogUXStateAggregator.cpp:16:
/home/junlon2006/workspace/amazon/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Threading/TaskQueue.h:151:12: error: invalid use of incomplete type ‘class std::promise<void>’
     promise->set_value();
            ^
In file included from /home/junlon2006/workspace/amazon/sdk-folder/sdk-s

**Comment by wojiaoxizhan** [comment]
@junlon2006 
When I cross-compile, I have the same error as you. How do you solve it?
My cross-compilation toolchain is csky-linux-gcc v6.3

**Comment by junlon2006** [comment]
> @junlon2006
> When I cross-compile, I have the same error as you. How do you solve it?
> My cross-compilation toolchain is csky-linux-gcc v6.3

hf works

**Comment by wojiaoxizhan** [comment]
@junlon2006 
What do you mean? Please say more clearly, thank you!
