### ISSUE TITLE
How to recover the Context when connection is disconnect?

### ISSUE THREAD

**Issue by howardguo** [alexa/avs-device-sdk#241]
Dear
As we know, the connection between my device and AVS server is disconnected every 60 minutes, and we have to reconnect it. But if so, the context is discard, the music can not displayed continuously as before. How to do with this issue? 
Btw, our device has already certificated by amazon, so could you disable the 60 minutes disconnect limit?

**Comment by dhpp** [comment]
Hi @howardguo,

The SynchronizeState Event should communicate to AVS the current state of the client, which in the case you describe would include the song that's playing.  AVS, on its new connection, would then continue to respond correctly to Events the client sends, such as PlaybackFinished, and then send the new song.

The server-side disconnect is a policy on the server, which we are not able to change, although this should be fine as the AVS protocol can work across such reconnections.

Could you please clarify your exact problem, and how you can reproduce it?  Thanks.
