### ISSUE TITLE
How/Will the SDK support obtain tokens Companion App and refresh Tokens 

### ISSUE THREAD

**Issue by chenxiaoqun** [alexa/avs-device-sdk#243]
I`m trying to obtain tokens from Companion App in replace of AuthServer.py, I modify the Companion App to request refresh tokens and create AlexaClientSDKConfig.json and send to device. it works.
But I don`t think this the right way, just hate change much to the SDK and when be covered   when you have update,

I wonder how/will you support this function in future.  Will be great if you share me some information. I have some questions：
1 Will you support services discover in the SDK to make Companion App to discover Alexa-Enabled device?
2 Will support request and refresh tokens in the SDK, I suppose it needs OAuth, which library will use support OAuth?

**Comment by dhpp** [comment]
Hi @chenxiaoqun,

Thanks for your questions.

1) I'm not sure what you mean exactly.  Could you please clarify?
2) Please take a look at our AuthDelegate component of the SDK, which takes care of refreshing the auth token periodically.  This component interacts with LWA (Amazon's OAuth2 server) on the user's behalf.  After your initial interaction with LWA (which AuthServer.py helps with), you should not need to do this again.  

-David

**Comment by satishc4u** [comment]
HI dhpp,

Please clarify me.
How long the refresh token will be valid ?
if it expires do we need to again execute the following or will AVS SDK automatically update the refresh token in AlexaClientSDKConfig.json.

**python AuthServer/AuthServer.py**

**Comment by mavamazon** [comment]
Hi Satish,

Refresh tokens are valid indefinitely, unless the user has removed the website or mobile app from the list of allowed apps for their account. You may find more details here:
https://developer.amazon.com/docs/login-with-amazon/refresh-token.html

Andrey.
