### ISSUE TITLE
AVS device sdk on Android

### ISSUE THREAD

**Issue by nunokid** [alexa/avs-device-sdk#246]
Hi.

Can AVS device SDK be integrated on Android device?

**Comment by jairajiv** [comment]
@nunokid, I will contact you offline to discuss the use case. Please fill out this [Contact Form](https://tinyurl.com/AVSContactForm) for me to contact you.

**Comment by boyce-xx** [comment]
Is it possible that you can share the info with me? how to use avs-device-sdk on Android？

**Comment by nunoki** [comment]
@jairajiv 

I have updated via the contact form you have guided.
Thanks a lot.

**Comment by jairajiv** [comment]
AVS provides code for companion apps for Android and iOS. The companion app is used for enrolling and managing an AVS device. Here are the links to companion apps.
 
Android - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/androidCompanionApp
iOS - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/iOSCompanionApp

**Comment by getAkashJain** [comment]
@jairajiv 

These two links are not working
Android - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/androidCompanionApp
iOS - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/iOSCompanionApp
