### ISSUE TITLE
run "python AuthServer/AuthServer.py" have problem

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#247]
**my json:**
 {
    "authDelegate":{
        "clientSecret":"1fa82761f6cbe75a3eb80d859b4552d9b7ac01e8d0feac91ae287596d9fbced4",
        "deviceSerialNumber":"a23456",
        "refreshToken":"xxxxx",
        "clientId":"amzn1.application-oa2-client.e257d6e87a7c472ab9173b0465467bc8",
        "deviceTypeId":"device_a"
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"/home/db/db1.db",
     "alarmSoundFilePath":"/home/sound/file_sound_1.mp3",
     "alarmShortSoundFilePath":"/home/sound/file_sound_2.mp3",
     "timerSoundFilePath":"/home/sound/file_time_sound_1.mp3",
     "timerShortSoundFilePath":"/home/sound/file_time_sound_2.mp3"
   },

   "settings":{
        "databaseFilePath":"/home/db/settings_db1.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },
   "certifiedSender":{ 
        "databaseFilePath":"/home/db/certified_db1.db"
    }
 }

enter  "http://localhost:3000"
**but grow below problem:**

Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
Request Details
scope=alexa%3Aall
redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthresponse
response_type=code
client_id=amzn1.application-oa2-client.e257d6e87a7c472ab9173b0465467b8c
scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22device_a%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22a23456%22%7D%7D%7D

how to solve it?

**Comment by Longynus83** [comment]
Hi @captainpanther,
Please visit the amazon developer portal and navigate to the Alexa tab, then click on Alexa Voice service. Click on "Manage" for the device/application you are using, then move to the Security profile section. At the bottom of this page you will find two textfields for "Allowed origins" and "Allowed return URLs", and there you should put the `http://localhost:3000` and `http://localhost:3000/authresponse`. 

At the time being the protocol I am using is HTTP as switching on HTTPS is returning an SSL related error, preventing the refresh token to be generated.

This should fix your error

**Comment by captainpanther** [comment]
Hi Longynus83:
i have been put http://localhost:3000 and http://localhost:3000/authresponse ,but it still have original problem!

**Comment by captainpanther** [comment]
ok , it is http://localhost:3000  ,not htt**p**://localhost:3000

**Comment by BennyAvramson** [comment]
Hi @captainpanther,

Did that solve the issue?

Thanks,
Benny

**Comment by captainpanther** [comment]
Ok , it solved

2017-10-18 8:45 GMT+08:00 Benny Avramson <notifications@github.com>:
