### ISSUE TITLE
Is "Display card" capability supported?

### ISSUE THREAD

**Issue by Longynus83** [alexa/avs-device-sdk#248]
Good morning,
From the amazon developer portal (`Alexa` tab, then -> `Alexa Voice service` -> `Manage` (for the device/application I am using) -> `Capabilities` section) I selected the Display card checkbox with the media option.

Having a look at the DEBU9 level log produced by the application running, I can't see any additional information about the media content returned when I ask for something. Typical scenario for example is the weather forecast: when I ask for "weather condition in Chicago for this week" I can hear the weather forecast, but no additional "data" to handle related media contents are provided in the log. If I check the Alexa page, I can see the snapshot with media content providing visual forecast in Chicago.

As for now, still 2 options are possible:

1. _Media content are handled by the SampleApp but no log output are produced_: if this is the case couuld you please guide me to the source code section such media content are handled?
2. _No matter the fact that I requested to display cards with media content, such data are not handled by the SampleApp_: in this case, could you please share if there is any plan to provide this feature, and which is the hypothetical timeline for having such content delivered in an upcoming release?

Thanks indeed

**Comment by BennyAvramson** [comment]
Hi @Longynus83,

Thanks for asking about this - this is on our feature roadmap, but we can't comment on schedule.

Thanks,
Benny
