### ISSUE TITLE
v1.1.0 build error

### ISSUE THREAD

**Issue by nunoki** [alexa/avs-device-sdk#249]
Hi, I tried to build version 1.1.0 sdk.
I met below error.  Please check it.

$ sudo make
sudo: unable to resolve host localhost.localdomain
[ 16%] Built target AVSCommon
[ 17%] Built target gmock_main
[ 18%] Built target gtest
[ 19%] Built target gtest_main
[ 20%] Built target AttachmentCommonTestLib
[ 21%] Built target AttachmentWriterTest
[ 22%] Built target AttachmentTest
[ 22%] Built target AttachmentReaderTest
[ 23%] Built target AttachmentManagerV2Test
[ 24%] Built target AlexaClientSDKInitTest
[ 25%] Built target NamespaceAndNameTest
[ 26%] Built target CapabilityAgentTest
[ 27%] Built target HandlerAndPolicyTest
[ 28%] Built target ExceptionEncounteredSenderTest
[ 29%] Built target DialogUXStateAggregatorTest
[ 29%] Built target LogEntryStreamTest
[ 30%] Built target RequiresShutdownTest
[ 31%] Built target ExecutorTest
[ 32%] Built target ConfigurationNodeTest
[ 33%] Built target LoggerTest
[ 34%] Built target JSONUtilTest
[ 35%] Built target SharedDataStreamTest
[ 36%] Built target TaskThreadTest
[ 37%] Built target UUIDGenerationTest
[ 37%] Built target TaskQueueTest
[ 38%] Built target TimerTest
[ 38%] Building CXX object ACL/src/CMakeFiles/ACL.dir/AVSConnectionManager.cpp.o
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In constructor ‘alexaClientSDK::acl::AVSConnectionManager::AVSConnectionManager(std::shared_ptr<alexaClientSDK::acl::MessageRouterInterface>, std::unordered_set<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::ConnectionStatusObserverInterface> >, std::unordered_set<std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::MessageObserverInterface> >)’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:85:9: error: class ‘alexaClientSDK::acl::AVSConnectionManager’ does not have any field named ‘AbstractConnection’
         AbstractConnection{connectionStatusObservers},
         ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In member function ‘virtual void alexaClientSDK::acl::AVSConnectionManager::doShutdown()’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:94:20: error: ‘clearObservers’ was not declared in this scope
     clearObservers();
                    ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:96:42: error: ‘m_messageObserverMutex’ was not declared in this scope
         std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                          ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:96:64: error: no matching function for call to ‘std::lock_guard<std::mutex>::lock_guard(<brace-enclosed initializer list>)’
         std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                                                ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:96:64: note: candidates are:
In file included from /home/ubuntu/local-builds/include/AVSCommon/Utils/Logger/Logger.h:23:0,
                 from /home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:18:
/usr/include/c++/4.8/mutex:416:7: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&, std::adopt_lock_t) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       lock_guard(mutex_type& __m, adopt_lock_t) : _M_device(__m)
       ^
/usr/include/c++/4.8/mutex:416:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:413:16: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       explicit lock_guard(mutex_type& __m) : _M_device(__m)
                ^
/usr/include/c++/4.8/mutex:413:16: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::lock_guard<std::mutex>::mutex_type& {aka std::mutex&}’
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In member function ‘void alexaClientSDK::acl::AVSConnectionManager::addMessageObserver(std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::MessageObserverInterface>)’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:142:38: error: ‘m_messageObserverMutex’ was not declared in this scope
     std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                      ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:142:60: error: no matching function for call to ‘std::lock_guard<std::mutex>::lock_guard(<brace-enclosed initializer list>)’
     std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                                            ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:142:60: note: candidates are:
In file included from /home/ubuntu/local-builds/include/AVSCommon/Utils/Logger/Logger.h:23:0,
                 from /home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:18:
/usr/include/c++/4.8/mutex:416:7: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&, std::adopt_lock_t) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       lock_guard(mutex_type& __m, adopt_lock_t) : _M_device(__m)
       ^
/usr/include/c++/4.8/mutex:416:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:413:16: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       explicit lock_guard(mutex_type& __m) : _M_device(__m)
                ^
/usr/include/c++/4.8/mutex:413:16: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::lock_guard<std::mutex>::mutex_type& {aka std::mutex&}’
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In member function ‘void alexaClientSDK::acl::AVSConnectionManager::removeMessageObserver(std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::MessageObserverInterface>)’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:153:38: error: ‘m_messageObserverMutex’ was not declared in this scope
     std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                      ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:153:60: error: no matching function for call to ‘std::lock_guard<std::mutex>::lock_guard(<brace-enclosed initializer list>)’
     std::lock_guard<std::mutex> lock{m_messageObserverMutex};
                                                            ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:153:60: note: candidates are:
In file included from /home/ubuntu/local-builds/include/AVSCommon/Utils/Logger/Logger.h:23:0,
                 from /home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:18:
/usr/include/c++/4.8/mutex:416:7: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&, std::adopt_lock_t) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       lock_guard(mutex_type& __m, adopt_lock_t) : _M_device(__m)
       ^
/usr/include/c++/4.8/mutex:416:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:413:16: note: std::lock_guard<_Mutex>::lock_guard(std::lock_guard<_Mutex>::mutex_type&) [with _Mutex = std::mutex; std::lock_guard<_Mutex>::mutex_type = std::mutex]
       explicit lock_guard(mutex_type& __m) : _M_device(__m)
                ^
/usr/include/c++/4.8/mutex:413:16: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::lock_guard<std::mutex>::mutex_type& {aka std::mutex&}’
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In member function ‘virtual void alexaClientSDK::acl::AVSConnectionManager::onConnectionStatusChanged(alexaClientSDK::avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::Status, alexaClientSDK::avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason)’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:160:42: error: ‘updateConnectionStatus’ was not declared in this scope
     updateConnectionStatus(status, reason);
                                          ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp: In member function ‘virtual void alexaClientSDK::acl::AVSConnectionManager::receive(const string&, const string&)’:
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:164:39: error: ‘m_messageObserverMutex’ was not declared in this scope
     std::unique_lock<std::mutex> lock{m_messageObserverMutex};
                                       ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:164:61: error: no matching function for call to ‘std::unique_lock<std::mutex>::unique_lock(<brace-enclosed initializer list>)’
     std::unique_lock<std::mutex> lock{m_messageObserverMutex};
                                                             ^
/home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:164:61: note: candidates are:
In file included from /home/ubuntu/local-builds/include/AVSCommon/Utils/Logger/Logger.h:23:0,
                 from /home/ubuntu/AVS_SDK/avs-device-sdk-1.1.0/ACL/src/AVSConnectionManager.cpp:18:
/usr/include/c++/4.8/mutex:482:7: note: std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>&&) [with _Mutex = std::mutex]
       unique_lock(unique_lock&& __u) noexcept
       ^
/usr/include/c++/4.8/mutex:482:7: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::unique_lock<std::mutex>&&’
/usr/include/c++/4.8/mutex:468:2: note: template<class _Rep, class _Period> std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&, const std::chrono::duration<_Rep, _Period>&)
  unique_lock(mutex_type& __m,
  ^
/usr/include/c++/4.8/mutex:468:2: note:   template argument deduction/substitution failed:
/usr/include/c++/4.8/mutex:462:2: note: template<class _Clock, class _Duration> std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&, const std::chrono::time_point<_Clock, _Duration>&)
  unique_lock(mutex_type& __m,
  ^
/usr/include/c++/4.8/mutex:462:2: note:   template argument deduction/substitution failed:
/usr/include/c++/4.8/mutex:455:7: note: std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&, std::adopt_lock_t) [with _Mutex = std::mutex; std::unique_lock<_Mutex>::mutex_type = std::mutex]
       unique_lock(mutex_type& __m, adopt_lock_t)
       ^
/usr/include/c++/4.8/mutex:455:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:451:7: note: std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&, std::try_to_lock_t) [with _Mutex = std::mutex; std::unique_lock<_Mutex>::mutex_type = std::mutex]
       unique_lock(mutex_type& __m, try_to_lock_t)
       ^
/usr/include/c++/4.8/mutex:451:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:447:7: note: std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&, std::defer_lock_t) [with _Mutex = std::mutex; std::unique_lock<_Mutex>::mutex_type = std::mutex]
       unique_lock(mutex_type& __m, defer_lock_t) noexcept
       ^
/usr/include/c++/4.8/mutex:447:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/4.8/mutex:440:16: note: std::unique_lock<_Mutex>::unique_lock(std::unique_lock<_Mutex>::mutex_type&) [with _Mutex = std::mutex; std::unique_lock<_Mutex>::mutex_type = std::mutex]
       explicit unique_lock(mutex_type& __m)
                ^
/usr/include/c++/4.8/mutex:440:16: note:   no known conversion for argument 1 from ‘<type error>’ to ‘std::unique_lock<std::mutex>::mutex_type& {aka std::mutex&}’
/usr/include/c++/4.8/mutex:436:7: note: std::unique_lock<_Mutex>::unique_lock() [with _Mutex = std::mutex]
       unique_lock() noexcept
       ^
/usr/include/c++/4.8/mutex:436:7: note:   candidate expects 0 arguments, 1 provided
ACL/src/CMakeFiles/ACL.dir/build.make:62: recipe for target 'ACL/src/CMakeFiles/ACL.dir/AVSConnectionManager.cpp.o' failed
make[2]: *** [ACL/src/CMakeFiles/ACL.dir/AVSConnectionManager.cpp.o] Error 1
CMakeFiles/Makefile2:2422: recipe for target 'ACL/src/CMakeFiles/ACL.dir/all' failed
make[1]: *** [ACL/src/CMakeFiles/ACL.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by BennyAvramson** [comment]
Hi @nunoki,

Could you update what platform and compiler you're using?

Thanks,
Benny

**Comment by nunoki** [comment]
Hi @BennyAvramson 
My dev environments are below:
 
OS: ubuntu 16.04 (arm64)
GCC version:  4.8.5

Thank.

**Comment by nunoki** [comment]
I solved this issue.
Deleted all existing build history and tried a new build.
Now, OK.

Thanks.
