### ISSUE TITLE
SDK working with KITT.AI wake word engine?

### ISSUE THREAD

**Issue by Zacki84** [alexa/avs-device-sdk#250]
Hi

Is the AVS-Device-SDK for Raspberry also working with the KITT.AI wake word engine or
is it only working with Sensory as in your description?
If it´s working, what do I have to do, to get it run?

Thanks

**Comment by BennyAvramson** [comment]
Hi @Zacki84,

The SDK can work with either of those.
Please follow the [Linux instructions](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide) or [Pi instructions](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide) to build with a wake detector.

Thanks,
Benny
