### ISSUE TITLE
how to install Googletest and use it in avs-device-sdk??

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#251]
i can't find any details that install googletest and running method,
please help ,thank.

**Comment by BennyAvramson** [comment]
Hi @captainpanther,

The gtest code is already included in the source tree [here](https://github.com/alexa/avs-device-sdk/tree/master/ThirdParty/googletest-release-1.8.0). 

Thanks,
Benny

**Comment by sanjayrd** [comment]
You shouldn't need to install it as we already included it in the source code of the SDK. Building the SDK should be all you need to do, since the Google Test code will get compiled along with the SDK.
