### ISSUE TITLE
AVS device sdk on Android device

### ISSUE THREAD

**Issue by ssadakk** [alexa/avs-device-sdk#252]
Hi, 
I'd like to integrate AVS device sdk on Android based device.
Is it could be possible?

Thanks a lot.

**Comment by jairajiv** [comment]
AVS provides code for companion apps for Android and iOS. The companion app is used for enrolling and managing an AVS device. Here are the links to companion apps.

Android - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/androidCompanionApp
iOS - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/iOSCompanionApp

If you want to discuss your use case further, Please fill out this [Contact Form](https://tinyurl.com/AVSContactForm).

**Comment by ssadakk** [comment]
Thanks, I've summit my info there.
Actually what I want to know is that are there any library or sdk for communicate with AVS (alexa).
