### ISSUE TITLE
Can we use Alexa app to configure wifi and certificate device with amazon account?

### ISSUE THREAD

**Issue by dreamforever** [alexa/avs-device-sdk#254]
Can we use Alexa app to configure wifi and certificate device with amazon account?
Thank you : )

**Comment by BennyAvramson** [comment]
Hi @dreamforever,

Could you elaborate more on the use case.

Thanks,
Benny

**Comment by dreamforever** [comment]
For example, I have a new device with avs, can I use Alexa app to configure wifi for this device? If device can not connect to wifi, this device can not connect to avs cloud.

Thanks

**Comment by BennyAvramson** [comment]
Hi @dreamforever,

Using the Alexa Speech to Text requires connectivity to AVS which you can't have without wifi.

Thanks,
Benny

**Comment by sanjayrd** [comment]
Hi @dreamforever,

This is not possible through the Alexa app. You will need some sort of custom companion app that can set up your device if your device does not come with any UI, or this can be implemented on the device itself if the device has some sort of UI that allows for setting up wifi. 

You might want to check out [Code-Based Linking](https://developer.amazon.com/docs/alexa-voice-service/code-based-linking-other-platforms.html), which might be helpful for the problem you're trying to solve here

I'm going to go ahead and close this issue for now, but please reopen if you have any further questions.

Thanks,
Sanjay
