### ISSUE TITLE
Google test fail message 

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#255]
hi all:
   error message is below-
The following tests FAILED:
	 12 - AlexaClientSDKInitTest_test (Failed)
	 13 - AlexaClientSDKInitTest.initializeNoJSONConfig (Failed)
	 15 - AlexaClientSDKInitTest.initializeValidJSONConfig (Failed)
	 17 - AlexaClientSDKInitTest.isInitialized (Failed)
	236 - HTTP2StreamTest_test (Failed)
	237 - HTTP2StreamTest.testExceptionReceivedSingleWrite (Failed)
	238 - HTTP2StreamTest.testExceptionReceivedMultiWrite (Failed)
	239 - HTTP2StreamTest.testHeaderCallback (Failed)
	240 - HTTP2StreamTest.testReadCallBack (Failed)
	248 - HTTP2StreamPoolTest_test (Failed)
	249 - HTTP2StreamPoolTest.GetStreamSendNullPtrForMoreThanMaxStreams (Failed)
	252 - HTTP2StreamPoolTest.PostStreamSendNullPtrForMoreThanMaxStreams (Failed)
	253 - HTTP2StreamPoolTest.ReleaseStreamTestSendMoreThanMaxStreams (Failed)
	254 - HTTP2StreamPoolTest.ReleaseStreamTestAfterNullTest (Failed)
	272 - AVSConnectionManagerTest_test (SEGFAULT)
	273 - AVSConnectionManagerTest.createTest (SEGFAULT)
	274 - AVSConnectionManagerTest.createWithNullMessageRouterAndObservers (SEGFAULT)
	275 - AVSConnectionManagerTest.addConnectionStatusObserverNull (SEGFAULT)
	276 - AVSConnectionManagerTest.addConnectionStatusObserverValid (SEGFAULT)
	277 - AVSConnectionManagerTest.removeConnectionStatusObserverNull (SEGFAULT)
	278 - AVSConnectionManagerTest.addMessageObserverNull (SEGFAULT)
	279 - AVSConnectionManagerTest.removeMessageObserverNull (SEGFAULT)
	280 - AVSConnectionManagerTest.enableAndDisableFunction (SEGFAULT)
	281 - AVSConnectionManagerTest.sendMessageRequestTest (SEGFAULT)
	282 - AVSConnectionManagerTest.setAVSEndpointTest (SEGFAULT)
	283 - AuthDelegateTest_test (Failed)
	284 - AuthDelegateTest.createNullConfig (Failed)
	285 - AuthDelegateTest.createMissingClientId (Failed)
	286 - AuthDelegateTest.createMissingClientSecret (Failed)
	287 - AuthDelegateTest.createMissingRefreshToken (Failed)
	288 - AuthDelegateTest.create (Failed)
	289 - AuthDelegateTest.addAuthObserverNull (Failed)
	290 - AuthDelegateTest.removeAuthObserverNull (Failed)
	291 - AuthDelegateTest.addMultipleAuthObserver (Failed)
	292 - AuthDelegateTest.retry (Failed)
	293 - AuthDelegateTest.expirationNotification (Failed)
	294 - AuthDelegateTest.recoverAfterExpiration (Failed)
	295 - AuthDelegateTest.unrecoverableErrorNotification (Failed)
	367 - MediaPlayerTest_test (Failed)
	368 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
	369 - MediaPlayerTest.testStartPlayForUrl (Failed)
	371 - MediaPlayerTest.testConsecutiveSetSource (Failed)
	372 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
	373 - MediaPlayerTest.testStopPlay (Failed)
	374 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)
	375 - MediaPlayerTest.testPauseDuringPlay (Failed)
	376 - MediaPlayerTest.testPlayAfterPause (Failed)
	377 - MediaPlayerTest.testStopAfterPause (Failed)
	378 - MediaPlayerTest.testPauseAfterPause (Failed)
	379 - MediaPlayerTest.testResumeAfterPause (Failed)
	380 - MediaPlayerTest.testResumeAfterPlay (Failed)
	381 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)
	383 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
	384 - MediaPlayerTest.testUnsteadyReads (Failed)
	387 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
	388 - MediaPlayerTest.testSetOffsetUnseekable (Failed)
	389 - MediaPlayerTest.testSetOffsetOutsideBounds (Failed)
	390 - MediaPlayerTest.testSetSourceResetsOffset (Failed)
Errors while running CTest
make: *** [test] Error 8

how to solved it ?

**Comment by BennyAvramson** [comment]
Hi @captainpanther,

In order to detailed log, please rerun a specific test case (e.g. `AlexaClientSDKInitTest`)
```bash
cd AVSCommon/AVS/test
./AlexaClientSDKInitTest
```

and paste the output here.

Thanks,
Benny

**Comment by captainpanther** [comment]
Running main() from gtest_main.cc
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from AlexaClientSDKInitTest
[ RUN      ] AlexaClientSDKInitTest.initializeNoJSONConfig
2017-10-19 17:46:24.305 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2
/home/whiteknight/NXP_test/mediaplayer/avs-device-sdk-master/AVSCommon/AVS/test/AlexaClientSDKInitTest.cpp:39: Failure
Value of: AlexaClientSDKInit::initialize({})
  Actual: false
Expected: true
[  FAILED  ] AlexaClientSDKInitTest.initializeNoJSONConfig (0 ms)
[ RUN      ] AlexaClientSDKInitTest.initializeInvalidJSONConfig
2017-10-19 17:46:24.305 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2
[       OK ] AlexaClientSDKInitTest.initializeInvalidJSONConfig (0 ms)
[ RUN      ] AlexaClientSDKInitTest.initializeValidJSONConfig
2017-10-19 17:46:24.305 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2
/home/whiteknight/NXP_test/mediaplayer/avs-device-sdk-master/AVSCommon/AVS/test/AlexaClientSDKInitTest.cpp:62: Failure
Value of: AlexaClientSDKInit::initialize({&validJSON})
  Actual: false
Expected: true
[  FAILED  ] AlexaClientSDKInitTest.initializeValidJSONConfig (0 ms)
[ RUN      ] AlexaClientSDKInitTest.uninitializedIsInitialized
[       OK ] AlexaClientSDKInitTest.uninitializedIsInitialized (0 ms)
[ RUN      ] AlexaClientSDKInitTest.isInitialized
2017-10-19 17:46:24.305 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2
/home/whiteknight/NXP_test/mediaplayer/avs-device-sdk-master/AVSCommon/AVS/test/AlexaClientSDKInitTest.cpp:77: Failure
Value of: AlexaClientSDKInit::initialize({})
  Actual: false
Expected: true
[  FAILED  ] AlexaClientSDKInitTest.isInitialized (0 ms)
[ RUN      ] AlexaClientSDKInitTest.uninitialize
2017-10-19 17:46:24.305 [  1] E AlexaClientSdkInit:initializeError:reason=notInitialized
[       OK ] AlexaClientSDKInitTest.uninitialize (0 ms)
[----------] 6 tests from AlexaClientSDKInitTest (0 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] AlexaClientSDKInitTest.initializeNoJSONConfig
[  FAILED  ] AlexaClientSDKInitTest.initializeValidJSONConfig
[  FAILED  ] AlexaClientSDKInitTest.isInitialized

 3 FAILED TESTS
whiteknight@whiteknight-HP-Z200-Workstation:~/NXP_test/mediaplayer_build/AVSCommon/AVS/test$ curl -v
curl: no URL spe

**Comment by BennyAvramson** [comment]
Hi @captainpanther,

By this line:
```bash
2017-10-19 17:46:24.305 [ 1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2
```
it seems your libcurl doesn't support HTTP2.

What is the platform in question?
Could you run `curl --version` and paste the output here

Thanks,
Benny

**Comment by captainpanther** [comment]
curl --version is below:

curl 7.50.2 (x86_64-pc-linux-gnu) libcurl/7.56.0 OpenSSL/1.0.1f zlib/1.2.8 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by captainpanther** [comment]
(a)
apt-get install make binutils autoconf automake autotools-dev libtool pkg-config zlib1g-dev libcunit1-dev libssl-dev libssh2-1-dev libxml2-dev libev-dev libevent-dev libjansson-dev libjemalloc-dev cython python3.4-dev python-setuptools

(b)spdylay
git clone https://github.com/tatsuhiro-t/spdylay.git
cd spdylay/
autoreconf -i
automake
autoconf
./configure
make
make install
cd ..

(3)nghttp2
git clone https://github.com/tatsuhiro-t/nghttp2.git
cd nghttp2
autoreconf -i
automake
autoconf
./configure
make
make install

(4)libcurl and curl
wget http://curl.haxx.se/download/curl-7.45.0.tar.gz
tar xvf curl-7.45.0.tar.gz
cd curl-7.45.0
./configure --with-nghtt2=/usr/local/nghttp2
make
make install

(5)setting:
 export PATH=$PATH:/usr/local/lib
 create  /etc/ld.so.conf.d/local.conf ， add content -> /usr/local/lib
 sudo ldconfig

(6)command:curl –version 
if contain 'nghttp2' it successed.

**Comment by sanjayrd** [comment]
Hi @captainpanther,

The version of libcurl which the SDK is being linked with does not have http2 support, which is a requirement of the SDK and AVS in general. For context, when I run `curl --version`, here is my output:
`
curl 7.52.1 (x86_64-apple-darwin15.6.0) libcurl/7.52.1 OpenSSL/1.0.2m zlib/1.2.5 nghttp2/1.13.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
` 

In your above steps, when installing curl, you install version **7.45.0**. Our SDK has a minimum requirement of **7.50.2**. Even though your curl --version output says 7.50.2, that curl version is not the one being linked to the SDK.

Thanks,
Sanjay

**Comment by guneykayim** [comment]
Hello,

I am having the same problem, `AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2`

However, I think my curl supports http2, this is what I get when I run `curl --version`: 
`curl 7.59.0 (x86_64-apple-darwin16.7.0) libcurl/7.59.0 OpenSSL/1.0.2o zlib/1.2.8 libidn2/2.0.4 nghttp2/1.31.1
Release-Date: 2018-03-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
`

AVS SDK version I am using is 1.7.0
I'm on a Mac, it is running Sierra (10.12.6)
I followed this [guide](https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide) to run.

What might be the reason for this?

**Comment by foggerwoody** [comment]
Hi guneykayim
I also have the same problem, have you revolved it ?

Thank you,
Di

**Comment by guneykayim** [comment]
Hi @foggerwoody 

I couldn't fix it, but as a workaround, I changed the source code, I removed the if check which controls if my curl supports http2 or not and built it that way. 

I simply modified _AlexaClientSDKInit.cpp_ file, `AlexaClientSDKInit::initialize` function, removed the first if check which controls the curl version.
