### ISSUE TITLE
If my product is to be commercialized?

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#259]
Hi,
Frist, wiki says Authserver can only be used for testing. If the product to be commercialized must be used other ways to obtain access token. If  use other methods, sample app code needs to be changed?What about the changes?
Second,If my product is to be commercialized, is the sample app available?

**Comment by BennyAvramson** [comment]
Hi @snailwft,

[License.txt](https://github.com/alexa/avs-device-sdk/blob/master/LICENSE.txt) governs the use of the Amazon Software provided in this repository.

Thanks,
Benny

**Comment by anu-mathur** [comment]
Hi @snailwft 
I am doing a user study on the AVS-device-SDK and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) and I will get in touch with you.
Thanks
