### ISSUE TITLE
Question about AuthServer.py and get refresh token process

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#263]
Hi AVS team,
 
I have a question about the process for getting first token.
 
In sample code, AuthServer.py, and the document, it needs to put "client secret", "client id", "product id", and a unique serial number to get a authentication token.
There is another must parameter is "redirect URI", and it's defined in development website. The default value is "localhost:3000".
 
I got a problem here. I am not running on a PC or Pi, so I will need to use a external PC connected to my AVS box and redirect to LWA. However, while it return the response code, it will try to move to "redirect URI", the "localhost:3000", but my external PC cannot know where is "localhost:3000", its because it's on AVS box.
If I tried to modify the python code and set my AVS box's IP (real IP address), it will say it's not in whitelist, I guess I need to set this IP to my development website for this product.
 
For development process, it's fine, but if I will try to make it as commercial product and deploy to tester's site, it will be a problem.
Is there any way to let "redirect URI" to be "ANY" and not be blocked by whitelist ?

Thanks,

**Comment by stevbenn** [comment]
@zeusshuang 
The whitelist is for security when using LWA.  You'll want to use a domain name (or cname) instead.  The process for setting redirect_uri is here:
https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html

You can make the change in the Security Profile after logging into your AVS developer portal account.
https://developer.amazon.com/avs/home.html#/avs/home
