### ISSUE TITLE
how to install Gstreamer ?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#264]
i have been used the command  "sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools" to install.

But run GoogleTest,and result is  : 
96% tests passed, 20 tests failed out of 478

Total Test time (real) =  36.39 sec

The following tests FAILED:
	367 - MediaPlayerTest_test (Failed)
	368 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
	369 - MediaPlayerTest.testStartPlayForUrl (Failed)
	371 - MediaPlayerTest.testConsecutiveSetSource (Failed)
	372 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
	373 - MediaPlayerTest.testStopPlay (Failed)
	374 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)
	375 - MediaPlayerTest.testPauseDuringPlay (Failed)
	376 - MediaPlayerTest.testPlayAfterPause (Failed)
	377 - MediaPlayerTest.testStopAfterPause (Failed)
	378 - MediaPlayerTest.testPauseAfterPause (Failed)
	379 - MediaPlayerTest.testResumeAfterPause (Failed)
	380 - MediaPlayerTest.testResumeAfterPlay (Failed)
	381 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)
	383 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
	384 - MediaPlayerTest.testUnsteadyReads (Failed)
	387 - MediaPlayerTest.testSetOffsetSeekableSource (Failed)
	388 - MediaPlayerTest.testSetOffsetUnseekable (Failed)
	389 - MediaPlayerTest.testSetOffsetOutsideBounds (Failed)
	390 - MediaPlayerTest.testSetSourceResetsOffset (Failed)
Errors while running CTest
make: *** [test] Error 8

how to install Gstreamer correctly?

**Comment by bandkenamazoncom** [comment]
Can you show me the cmake command you used to build this?

**Comment by captainpanther** [comment]
command:
cmake /home/username/NXP_test/mediaplayer/avs-device-sdk-master -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/home/username/NXP_test/gstreamer/1104/build

**Comment by bandkenamazoncom** [comment]
@captainpanther, I just checked the gstreamer version that is included with ubuntu and it is 1.8.  The SDK is currently only certified with 1.10.4 for Linux distros.

https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies

I have typically downloaded the source for gstreamer and compiled myself.

**Comment by captainpanther** [comment]
install /usr/local and install in order for  Gstreamer
