### ISSUE TITLE
SDK can not play music 

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#267]
hi @avs team

I run the SampleApp, then wake up alexa and say "play music", it not paly music ,the log is here

[https://app.box.com/file/240502106647](url)

**Comment by ryan-esty** [comment]
Are you having the same issue as #236? What version of the SDK are you using?

**Comment by sundq** [comment]
@ryan-esty The version is 1.0.2， I have no the issue #236

**Comment by ryan-esty** [comment]
@sundq 1.0.2 to my knowledge only works with iheartradio. You need to create an iheartradio account and link them before you can play music.

**Comment by bandkenamazoncom** [comment]
Thanks for the response.  Closing issue. Feel free to re-open if there are any additional questions.

**Comment by sundq** [comment]
Resovled, because my gstreamer don't support `https` and m3u8, need install glib-networking, gnutls, gst-libav
