### ISSUE TITLE
CURL_HTTP_VERSION_2_0 setting options at downchannel

### ISSUE THREAD

**Issue by wonderjason** [alexa/avs-device-sdk#268]
Dear @avsteam,

When SampleApp get access token, the curl option with CURL_HTTP_VERSION_2_0 is used.
Does downchannel establish connection set the curl option with CURL_HTTP_VERSION_2_0 ?

My Log is shown below:

* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=latinum.amazon.com
*  start date: Aug 23 00:00:00 2017 GMT
*  expire date: May 21 23:59:59 2018 GMT
*  subjectAltName: host "avs-alexa-na.amazon.com" matched cert's "avs-alexa-na.amazon.com"
*  issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
final nheader=0
* Using Stream ID: 1 (easy handle 0x796f88)
> GET /v20160207/directives **HTTP/1.1**
Host: avs-alexa-na.amazon.com
Accept: */*
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...

* Connection state changed (MAX_CONCURRENT_STREAMS updated)!

**Comment by bandkenamazoncom** [comment]
Yes, CURL_HTTP_VERSION_2_0 is set.
