### ISSUE TITLE
badHTTPContentReceived

### ISSUE THREAD

**Issue by louisjzl** [alexa/avs-device-sdk#271]
The PlaylistParser works very well when playing local music. But when I try to play music with an HTTP url, there is always an error with PlaylistParser, reporting  badHTTPContentReceived. At the meantime, I deliver  the HTTP url directly to the pipeline, and the music can be played. The network works very well. Is there any solution to this problem? Thanks a lot.

**Comment by bandkenamazoncom** [comment]
That error occurs when we don't receive a 200 from the request.  What is the URL that you are playing from?
