### ISSUE TITLE
How to progamatically tell when the SDK is using the speaker

### ISSUE THREAD

**Issue by ryan-esty** [alexa/avs-device-sdk#272]
We would like to know when the speaker is free. I see that when the UI state transitions from speaking to idle Alexa is done until the next state. This doesn't catch the case with the streaming things like news  and music. Is the only way to catch when the SDK is streaming is to set an observer on the audio player using setObserver()?

**Comment by bandkenamazoncom** [comment]
Your plan is the the easiest way to go about it for now.

An alternative is to create a new observer that can be injected into the media players.  This would have to be plumbed into the 3 media players that are currently instantiated.  That's the "correct" way to do it, but it's more complicated.

**Comment by ryan-esty** [comment]
Thanks for the info and suggestion. You can close this.

**Comment by bandkenamazoncom** [comment]
I think that you need to add a second observer

**Comment by ryan-esty** [comment]
@bandkenamazoncom unless I vectorize m_playerObserver, I don't see how the code below will allow another observer. DefaultClient is calling all the setObservers for the players, so when I do my observer I loose the observer that the DefaultClient set up, unless I vectorize, like I said.
void MediaPlayer::handleSetObserver(
        std::promise<void>* promise,
        std::shared_ptr<avsCommon::utils::mediaPlayer::MediaPlayerObserverInterface> observer) {
    ACSDK_DEBUG(LX("handleSetObserverCalled"));
    m_playerObserver = observer;
    promise->set_value();
}

**Comment by bandkenamazoncom** [comment]
That's one way to do it, the other is to have a second observer instance in MediaPlayer so the first one isn't written.

**Comment by ryan-esty** [comment]
@bandkenamazoncom I thought there was away around not changing the SDK code. It would be more general if we vectorize it then anyone could use it out side the SDK. Of course we would have to change the setObserver to addObserver and follow the model of the other interfaces that use addObserver. If it is useful and eventually does get into the mainline then I wouldn't have to keep on merging it in all the time. Thanks for the info and help.

**Comment by ryan-esty** [comment]
Just in case someone else needs this in version 1.2 I was able to add an observer to the default client using the m_audioPlayer.
