### ISSUE TITLE
Notifications support in SDK

### ISSUE THREAD

**Issue by lajeeraj** [alexa/avs-device-sdk#273]
As per AlexaClientSDK  1.1.0 documentation ( https://alexa.github.io/avs-device-sdk/ ), Notifications and few other components are not supported. When will this be available in SDK?

Thanks,
Laji.

**Comment by jairajiv** [comment]
@lajeeraj. We generally do not comment on the timing of new releases. Please fill out this [Contact Form](https://tinyurl.com/AVSContactForm) if you would like for us to contact you.

**Comment by bandkenamazoncom** [comment]
Thanks @jairajiv!
