### ISSUE TITLE
ALEXA SDK (1.0.2) - Audio Response not received sometimes

### ISSUE THREAD

**Issue by Jigar27** [alexa/avs-device-sdk#274]
Hello,
I am able to feed a raw data file to the Alexa SDK and was able to get the response from AVS. But I was experiencing a weird behavior as AVS sometimes responds and sometimes does not respond the same input raw file and now from yesterday, I haven't received any response. Is there anything I am missing out? 
>>> debug log:
> CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
> DialogUXStateAggregator:transitionFromThinkingTimedOut

This two debug lines are the difference between a successful run and an unsuccessful run.

**Comment by bandkenamazoncom** [comment]
Can you provide some more details?  What is the raw data file?  Is it an audio file?  Is the SDK in the correct state for transmitting the data to AVS?

**Comment by Jigar27** [comment]
Thanks for attending the bug. The issue was in populating the vector of char. Issue has been resolved.
