### ISSUE TITLE
Can not update Refresh Token.

### ISSUE THREAD

**Issue by cyh52701** [alexa/avs-device-sdk#275]
Hi, 

I setup the avs-device-sdk 1.1.0 on my Raspberry Pi 3.
But I can not update Refresh Token.

1. My /home/pi/sdk-folder/sdk-build/Integration//AlexaClientSDKConfig.json
    "authDelegate":{
        "clientSecret":"9f5d3e1e069429961eb88f3601b30c06deab3e8d750a711000be3030--------",
        "deviceSerialNumber":"12345678",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.aeaada4d89e043cfa445e2f7--------",
        "productId":"my_pi3"
     },
    => error message,
          The refresh request failed with the response code 400. This might be due to a bad refresh token or  bad client data. We will continue with getting a refresh token, discarding the one in the file.

         * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2.  My /home/pi/sdk-folder/sdk-build/Integration//AlexaClientSDKConfig.json
    "authDelegate":{
        "clientSecret":"9f5d3e1e069429961eb88f3601b30c06deab3e8d750a711000be3030--------",
        "deviceSerialNumber":"12345678",
        "clientId":"amzn1.application-oa2-client.aeaada4d89e043cfa445e2f7--------",
        "productId":"my_pi3"
     },
    => error message,
         * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
--------------------------------------------------------------------------------------------------------------
My AVS device information:
Product ID: my_pi3
Client ID: amzn1.application-oa2-client.aeaada4d89e043cfa445e2f7--------
Client secret: 9f5d3e1e069429961eb88f3601b30c06deab3e8d750a711000be3030--------
Amazon ID: A1G5MK7OLP7IOT
Allowed origins: http://localhost:3000
Allowed return URLs: http://localhost:3000/authresponse
--------------------------------------------------------------------------------------------------------------
How to fix the issue?
Thanks!

BR,
Wilson

**Comment by snailwft** [comment]
hi, @cyh52701 
This is not an error message, you have to use your browser to http://localhost:3000, then you will be redirected to the login interface of amazon, input your account and password, you will automatically return a refresh token to your json file.

**Comment by cyh52701** [comment]
Hi, 

I run the http://localhost:3000 on my browser.
I have fixed the Refresh Token issue.
THS!

**Comment by bandkenamazoncom** [comment]
Thanks @snailwft!

**Comment by bandkenamazoncom** [comment]
Closing as it appears to be resolved.  If you're still facing the same issue, please re-open!
