### ISSUE TITLE
Can SharedDataStream be used for IPC (shared memory)?

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexa/avs-device-sdk#276]
SharedDataStream is designed very well， Can I uesd for IPC ? How？   if can , it very usedfull 。 Thanks

**Comment by bandkenamazoncom** [comment]
SharedDataStream is designed to support IPC, but it hasn't been developed.  Generally, the SDK wasn't designed to run the components in different processes.  Some components require less work to support it than others.

Here's some info/examples that might help:
https://alexa.github.io/avs-device-sdk/classalexa_client_s_d_k_1_1avs_common_1_1utils_1_1sds_1_1_shared_data_stream.html

https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/include/AVSCommon/Utils/SDS/InProcessSDS.h#L35

https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/Utils/test/SharedDataStreamTest.cpp#L43

**Comment by bandkenamazoncom** [comment]
Closing as the question has been answered.  Please re-open if you need more information.
