### ISSUE TITLE
MediaPlayerTest  fail

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#277]
command : ./MediaPlayerTest something.mp3 or something.wav

message:
/avs-device-sdk-master/MediaPlayer/test/MediaPlayerTest.cpp:272: Failure
Value of: m_stream->good()
  Actual: false
Expected: true
/avs-device-sdk-master/MediaPlayer/test/MediaPlayerTest.cpp:504: Failure
Value of: m_playerObserver->waitForPlaybackStarted()
  Actual: false
Expected: true

how to fix it ?

**Comment by bandkenamazoncom** [comment]
It should be 

$ ./MediaPlayerTest /full/path/to/folder/containing_fox_dog.mp3/

**Comment by captainpanther** [comment]
i use it command : 
$ ./MediaPlayerTest /full/path/to/folder/containing_fox_dog.mp3/

but it still have problem

**Comment by bandkenamazoncom** [comment]
you need to replace "/full/path/to/folder/containing_fox_dog.mp3/" with your own path.  If you've downloaded the SDK it will be <full_path_to_folder_containing_sdk>/MediaPlayer/inputs/

**Comment by captainpanther** [comment]
install Gstreamer correctly and will solve it!
