### ISSUE TITLE
It take very long time to upgrade when SDK modify much code

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#279]
I have notice that the verion 1.1.0 released, and I want to upgrade my AVS SDK， but I found it very hard to upgrade because there are so much changed. 
I take the demo code in issue #121, and I impelement myself 
Client and AudioMediaPlayer by refer the `DefaultClient` and `AudioMediaPlayer` in SDK。
This make it take very long time to upgrage SDK when   `DefaultClient` and `AudioMediaPlayer` in SDK have  very much changed.

So could you supply a abstract `DefaultClient` and `AudioMediaPlayer`， The user of SDK  can inherit them, and implement themself Client and AudioMediaPlayer， so it will not affect user when SDK have any changed.

**Comment by bandkenamazoncom** [comment]
That's a reasonable idea. However, DefaultClient + MediaPlayer (as it's now called) are intended to be an example of what could be done and is not a requirement to use the SDK.  They make the Sample App full featured and show how the various components are connected together.

**Comment by sundq** [comment]
@bandkenamazoncom But I think there must be a way that implement the sdk which  have less effect it's user when upgrade the sdk. 
for example, I don't need modify my code when I upgrade python from 2.6.* to 2.7.*.
You know much code modified means much test, so I will not upgrade the sdk to v1.1.0  if I am product manager or project manager.

**Comment by sanjayrd** [comment]
Hi @sundq,

Thank you for the suggestion. We will investigate the problem you're seeing and see if it would be feasible to abstract out the DefaultClient. Basically as I understand it, you want a way to be able to provide specific Channel configurations to the DefaultClient, correct? Or is there something else as well?

Thanks,
Sanjay

**Comment by sundq** [comment]
Hi  @sanjayrd
 
The problem have metioned in issue #121: I just want to play local audio file, but the question is I can not play the auido file directely， I must acquire the `focuse` to play my audio file to make sure there are only one player  to play at the same time。so I must implement `avs client` and `audioPlayer` myself, but if the sdk have much changed on `DefaultClient` and `AudioPlayer`, I must take long time to upgrade my application.
