### ISSUE TITLE
Missing key: "amzn1.application-oa2-client.3963ee41f46ss79a84e62d25cc291a70".

### ISSUE THREAD

**Issue by kuodehai** [alexa/avs-device-sdk#282]
Missing key: "amzn1.application-oa2-client.3963ee41f46ss79a84e62d25cc291a70". The list of required keys are:
 * amzn1.application-oa2-client.3963ee41f46ss79a84e62d25cc291a70
 * d571bb9c065a5a9d9cdd58eaff5ca03f80rrr530b62f1b299f0142096aaee83e
 * my_Device
 * 171030001

**Comment by kuodehai** [comment]
{
    "authDelegate":{
        "clientSecret":"d571bb9c065a5a9d9cdd58eaff5ca03f80rrr530b62f1b299f0142096aaee83e",
        "deviceSerialNumber":"171030001",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.3963ee41f46ss79a84e62d25cc291a70",
        "productId":"my_Device"
   },
   "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/alerts.db",
        "alarmSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01_short._TTH_.wav",
        "timerSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02_short._TTH_.wav"
   },
   "settings":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
   },
   "certifiedSender":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/certifiedSender.db"
   }
}

**Comment by kuodehai** [comment]
{
    "authDelegate":{
        "clientSecret":"d571bb9c065a5a9d9cdd58eaff5ca03f80rrr530b62f1b299f0142096aaee83e",
        "deviceSerialNumber":"171030001",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.3963ee41f46ss79a84e62d25cc291a70",
        "productId":"my_Device"
   },
   "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/alerts.db",
        "alarmSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_01_short._TTH_.wav",
        "timerSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/pi/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02_short._TTH_.wav"
   },
   "settings":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
   },
   "certifiedSender":{
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/certifiedSender.db"
   }
}

**Comment by frozenberg** [comment]
Hi @kuodehai, are you getting this message when running AuthServer.py?

**Comment by kuodehai** [comment]
it has been  solved, thank  you.
