### ISSUE TITLE
how to launch SampleApp in embedded system?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#283]
In yocto project , how to implement it? Because  in "Install the AVS Device SDK" , use command:cmake <absolute-path-to-source>
-DCMAKE_INSTALL_PREFIX=<absolute-path-to-out-of-source-build>

it grow  lib and include folder , how to trigger SampleApp in embedded system?

**Comment by frozenberg** [comment]
Hi @captainpanther, I'm not entirely sure what you mean by "trigger SampleApp in embedded system". Are you looking to run the SampleApp on startup? What platform are you developing on?

**Comment by frozenberg** [comment]
Closing due to lack of response.
