### ISSUE TITLE
make integration AlexaCommunicationsLibraryTest.testConnectAndDisconnect ，testSendInvalidEvent

### ISSUE THREAD

**Issue by kuodehai** [alexa/avs-device-sdk#284]
TZ=UTC make all integration

Connecting timed out.

2017-10-30 15:33:03.762 [  1] 0 MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED

2017-10-30 15:33:03.762 [  1] 0 PostConnectSynchronize:PostConnectSynchronizer::doShutdown().

2017-10-30 15:33:03.809 [ 1f] 0 HTTP2StreamPool:releaseStream:streamId=97,numAcquiredStreams=0

2017-10-30 15:33:03.809 [ 1f] 0 HTTP2StreamPool:getStream:streamId=99,numAcquiredStreams=1

2017-10-30 15:33:03.809 [ 1f] 0 HTTP2StreamPool:releaseStream:streamId=99,numAcquiredStreams=0

2017-10-30 15:33:03.809 [ 1f] 0 PostConnectSynchronize:onSendCompleted:status=NOT_CONNECTED

2017-10-30 15:33:03.810 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=MessageRouter

[  FAILED  ] AlexaCommunicationsLibraryTest.testMultipleConnectionStatusObservers (17999 ms)

[----------] 10 tests from AlexaCommunicationsLibraryTest (186367 ms total)

[----------] Global test environment tear-down

[==========] 10 tests from 1 test case ran. (186369 ms total)
AlexaCommunicationsLibraryTest.testMultipleConnectionStatusObservers (17999 ms)

[----------] 10 tests from AlexaCommunicationsLibraryTest (186367 ms total)

[----------] Global test environment tear-down

[==========] 10 tests from 1 test case ran. (186369 ms total)

[  PASSED  ] 0 tests.

[  FAILED  ] 10 tests, listed below:

[  FAILED  ] AlexaCommunicationsLibraryTest.testConnectAndDisconnect

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendEvent

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendInvalidEvent

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendEventWithAttachment

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendEventAndReceiveDirective

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendEventsSerially

[  FAILED  ] AlexaCommunicationsLibraryTest.testSendEventsConcurrently

[  FAILED  ] AlexaCommunicationsLibraryTest.testReceiveDirectiveOnDownchannel

[  FAILED  ] AlexaCommunicationsLibraryTest.testPersistentConnection

[  FAILED  ] AlexaCommunicationsLibraryTest.testMultipleConnectionStatusObservers

10 FAILED TESTS

Integration/test/CMakeFiles/integration.dir/build.make:57: recipe for target 'Integration/test/CMakeFiles/integration' failed

make[3]: *** [Integration/test/CMakeFiles/integration

**Comment by frozenberg** [comment]
Hi @kuodehai, it's possible that your network is too slow for the default time out. As a quick fix, try increasing the timeout in `ConnectionStatusObserver.h`, specifically in 

`bool waitFor(... duration = std::chrono::seconds(15));`

Also, could you provide the logs from running this test directly copied and pasted from your terminal?

Thanks.

**Comment by kuodehai** [comment]
openssl version

**Comment by kuodehai** [comment]
openssl version
