### ISSUE TITLE
How to change language by set user account?

### ISSUE THREAD

**Issue by howardguo** [alexa/avs-device-sdk#288]
Dear all
As my understanding, SetEndpoint directive is for country setting, and SettingsUpdated eventis for changing language. 
Do I have to send SettingsUpdated event for changing language? Is it the only way to change language?
Attached file is my test case which come from amazon. I saw that it only need change the account country setting , that can send a SetEndpoint directive to my device. But no way let me know the language information, So I don't know how to send SettingsUpdated event based by SetEndpoint .
Something wrong with my understanding?

![testcase](https://user-images.githubusercontent.com/18320718/32273472-97ceaf0e-bf3d-11e7-97f1-4f9c8948b234.png)

**Comment by frozenberg** [comment]
Hi @howardguo, are you writing your own application using the SDK? You can refer to Settings.cpp to see how language may be changed.

**Comment by howardguo** [comment]
Hi, master
We don't use the SDK, :(. But I also read the Settings.cpp source code. I understand it is still need to send SettingsUpdated event actively to change the language. 
My question is that's the only way(send SettingsUpdated event) to change the language?:).
 If I don't send SettingsUpdated , have anther interface to change language(ex: modify account setting or others)?

**Comment by frozenberg** [comment]
The SettingsUpdated event is sent only after the language is changed. To change your language settings on your device you should be able to log into alexa.amazon.com, click settings on the left and find your device.

**Comment by mradulan** [comment]
Hi @howardguo , in 3P devies, you cannot change language from account setting. If you have a echo or echo dot, you can change the language from the account setting. In few months, we will have the directive to update settings, at that time, you can change the language from the account.

**Comment by howardguo** [comment]
OK，Thanks all! 👍
