### ISSUE TITLE
Can't receive more than 64K data using nghttp2 in c code

### ISSUE THREAD

**Issue by tejas-volansys** [alexa/avs-device-sdk#289]
Hi,

I have implemented c code using nghttp2 library and Application can't receive more than 64K audio response data. Is there any configuration or way to remove this limit? Help will be greatly appreciated.

**Comment by frozenberg** [comment]
Hi @tejas-volansys, it might be useful to get some code snippets of the application you are writing as well as some logs of the interactions that you are engaging in. 

Thanks in advance!

**Comment by frozenberg** [comment]
Closing due to lack of response.
