### ISSUE TITLE
How to obtain final speech text after SpeechRecognizer 

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#294]
Hi AVS team,

How to we obtain speech text after SpeechRecognizer, we hope to use it for other applications

Thanks

**Comment by frozenberg** [comment]
Hi @aki29, do you mean you want to capture the user speech audio for later use?

**Comment by aki29** [comment]
Hi frozenberg,
No,
We hope to get the text after AVS voice recognition.
Such as we say "Alexa, what time is it"
We would link to know how to get "what time is it"

THX

**Comment by scotthea-amazon** [comment]
Hi aki29,

Sorry for the delayed response to your question.  AVS currently does not return text to AVS clients.  However, you can capture the recognized text if it is targeting a skill.  Here is an [older forum post](https://forums.developer.amazon.com/questions/10996/can-alexa-voice-service-return-text-in-the-respons.html) discussing how this might be done.

Regards,
-SWH

**Comment by aki29** [comment]
Hi SWH,

Thanks for your update.

BRs
aki
