### ISSUE TITLE
SharedDataStream Index Can be define int32_t？

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexa/avs-device-sdk#296]
in our platform，rewrite a SDSTraits struct,   AtomicIndex  is a  int32_t  type， if we  using Index = uint64_t ，There will be type conversion errors in these places：
*m_readerCloseIndex = std::numeric_limits<Index>::max(); 
 Index absolute = std::numeric_limits<Index>::max();
will cause the program to run incorrectly。
so we  using Index = int32_t， the program  is  run  ok。
But I'm worried that this will not be a problem， if the program run a log time ，  writeStartCursor （int32） Will exceed the maximum  and maybe have a wrong,  Is that right？

thanks！

**Comment by frozenberg** [comment]
Hi @zuowanbushiwo, currently we have no logic in place to handle an overflow, so you will definitely run into some issues if you leave the application running for a long time. Why do you need int32? 

If you are running into conversion errors it may be safer to simply rework the downstream changes necessary from keeping the int64.

**Comment by zuowanbushiwo** [comment]
@frozenberg 
 thanks very much！
Our team is working on a project that avs SmartSpeaker plus MultiRoom 。 we have developed our  MultiRoom system。 we think that let  avs mediaplayer run on our MultiRoom process to Play simultaneously。 if your MediaPlayerObserverInterface only setsource(url)， We have already done it。but other dataStream source ，we nead a IPC  way to Exchange data。 we  used shardDataStrem with rewrite  a SDSTraits struct。 
we uesd  http://androidxref.com/7.1.1_r6/xref/system/core/include/cutils/atomic.h rewrite class AtomicIndex，this source file only supports int32_t， and we  have no idea about int64_ t and   uint64_ t  implementation。
