### ISSUE TITLE
Wake rate problem

### ISSUE THREAD

**Issue by cuizhenke** [alexa/avs-device-sdk#297]
Hi AVS team,
    We want to use this SDK1.2 to pass amazon quick test. During our self test,We found in some girls voice  tone is difficult to wake up, we can't pass the wake up test rate.We're using the Sensory's wake up solution.
    Does the Sensory's word model covers the quick test voice sample? Other peoples have used the Sensory's wake up module with SDK passed through the quick test?
thanks.

**Comment by jairajiv** [comment]
@cuizhenke - The Sensory Wake Word library referenced in the SDK repository is for integration purpose only. We recommend that you contact [Sensory](http://www.sensory.com/support/contact/us-sales/) to get a suitable Wake Word solution. Please feel free to contact Amazon's Business Development if you need any further assistance.
