### ISSUE TITLE
make test failed?

### ISSUE THREAD

**Issue by octGitHub** [alexa/avs-device-sdk#307]
After I make successfully.
I do the "make all test". And it shows

```

92% tests passed, 42 tests failed out of 512

Total Test time (real) = 22.91 sec

The following tests FAILED:
63 - AlexaClientSDKInitTest.initializeNoJSONConfig (Failed)
65 - AlexaClientSDKInitTest.initializeValidJSONConfig (Failed)
67 - AlexaClientSDKInitTest.isInitialized (Failed)
217 - AVSConnectionManagerTest.createTest (Failed)
218 - AVSConnectionManagerTest.createWithNullMessageRouterAndObservers (Failed)
220 - AVSConnectionManagerTest.addConnectionStatusObserverValid (SEGFAULT)
224 - AVSConnectionManagerTest.enableAndDisableFunction (SEGFAULT)
225 - AVSConnectionManagerTest.sendMessageRequestTest (SEGFAULT)
226 - AVSConnectionManagerTest.setAVSEndpointTest (SEGFAULT)
243 - HTTP2StreamPoolTest.GetStreamSendNullPtrForMoreThanMaxStreams (Failed)
246 - HTTP2StreamPoolTest.PostStreamSendNullPtrForMoreThanMaxStreams (Failed)
247 - HTTP2StreamPoolTest.ReleaseStreamTestSendMoreThanMaxStreams (Failed)
248 - HTTP2StreamPoolTest.ReleaseStreamTestAfterNullTest (Failed)
249 - HTTP2StreamTest.testExceptionReceivedSingleWrite (Failed)
250 - HTTP2StreamTest.testExceptionReceivedMultiWrite (Failed)
251 - HTTP2StreamTest.testHeaderCallback (Failed)
252 - HTTP2StreamTest.testReadCallBack (Failed)
260 - AuthDelegateTest.createNullConfig (Failed)
261 - AuthDelegateTest.createMissingClientId (Failed)
262 - AuthDelegateTest.createMissingClientSecret (Failed)
263 - AuthDelegateTest.createMissingRefreshToken (Failed)
264 - AuthDelegateTest.create (Failed)
265 - AuthDelegateTest.addAuthObserverNull (Failed)
266 - AuthDelegateTest.removeAuthObserverNull (Failed)
267 - AuthDelegateTest.addMultipleAuthObserver (Failed)
268 - AuthDelegateTest.retry (Failed)
269 - AuthDelegateTest.expirationNotification (Failed)
270 - AuthDelegateTest.recoverAfterExpiration (Failed)
271 - AuthDelegateTest.unrecoverableErrorNotification (Failed)
480 - SettingsTest.createTest (SEGFAULT)
481 - SettingsTest.addGlobalSettingsObserverTest (SEGFAULT)
482 - SettingsTest.removeGlobalSettingsObserverTest (SEGFAULT)
483 - SettingsTest.addSingleSettingObserverWithInvalidKeyTest (SEGFAULT)
484 - SettingsTest.removeSingleSettingObserverWithInvalidKeyTest (SEGFAULT)
485 - SettingsTest.removeSingleSettingObserverWithCorrectKeyTest (SEGFAULT)
486 - SettingsTest.defaultSettingsCorrect (SEGFAULT)
487 - SettingsTest.clearDatabaseTest (SEGFAULT)
488 - SettingsTest.storeDatabaseTest (SEGFAULT)
489 - SettingsTest.modifyDatabaseTest (SEGFAULT)
490 - SettingsTest.eraseTest (SEGFAULT)
491 - SettingsTest.createDatabaseTest (SEGFAULT)
492 - SettingsTest.openAndCloseDatabaseTest (SEGFAULT)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

```

What can I do to solve these error?
My cmake cmd is "cmake ../avs-device-sdk/  -DCMAKE_BUILD_TYPE=DEBUG"

**Comment by jjamazon** [comment]
Hi octGitHub,

Have you filled out your JSON config file AlexaClientSDKConfig.json? 
https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#build-for-generic-linux--macos

What platform are you running this on ? what version of the code are you using ?

**Comment by octGitHub** [comment]
Thx for reply!  

        I pulled the latest code from github at 20171106. 
        It was runed on linux for testing .
        My AlexaClientSDKConfig.json is out of source directory. I just filled authDelegate's fields of the JSON config file AlexaClientSDKConfig.json befroe I make test.  Should I fill all of the config fiels  if some function I never used?  
{
    "authDelegate":{
        "clientSecret":"---myclientSecret---",
        "deviceSerialNumber":"--mydeviceSerialNumber---",
        "refreshToken":"",
        "clientId":"---myclientId--",
        "productId":"--myproductId--"
     },

   "alertsCapabilityAgent":{
        "databaseFilePath":"",
        "alarmSoundFilePath":"",
        "alarmShortSoundFilePath":"",
        "timerSoundFilePath":"",
        "timerShortSoundFilePath":""
   },

   "settings":{
        "databaseFilePath":"",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },
   "certifiedSender":{ 
        "databaseFilePath":""
    }
 }

      BTW.
      If I use the lower version gcc 4.7.4 in arm linux ( qsdk ) , will it work?
      my linux compiler is gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5).

**Comment by jjamazon** [comment]
Yes would recommend filling in the rest of the fields in the json file.

**Comment by octGitHub** [comment]
OK. thx.  I  will try.

**Comment by octGitHub** [comment]
@jjamazon 
  
        I have tried filling  with JSON config file AlexaClientSDKConfig.json out of source.

        My json file is 

```

{
    "authDelegate":{
     "clientSecret":"---myclientSecret---",
     "deviceSerialNumber":"--mydeviceSerialNumber---",
     "refreshToken":"",
     "clientId":"---myclientId--",
     "productId":"--myproductId--"
},

   "alertsCapabilityAgent":{
        "databaseFilePath":"/home/yummy/Desktop/2Test/res/alexa/alertsCapabilityAgent.db",
        "alarmSoundFilePath":"/home/yummy/Desktop/2Test/res/alexa/med_system_alerts_melodic_01_short._TTH_.wav",
        "alarmShortSoundFilePath":"/home/yummy/Desktop/2Test/res/alexa/med_system_alerts_melodic_01._TTH_.mp3",
        "timerSoundFilePath":"/home/yummy/Desktop/2Test/res/alexa/med_system_alerts_melodic_02._TTH_.mp3",
        "timerShortSoundFilePath":"/home/yummy/Desktop/2Test/res/alexa/med_system_alerts_melodic_02_short._TTH_.wav"
   },

   "settings":{
        "databaseFilePath":"/home/yummy/Desktop/2Test/res/alexa/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },
   "certifiedSender":{
        "databaseFilePath":"/home/yummy/Desktop/2Test/res/alexa/certifiedSender.db"
    }
 }

```

but it was still failed at testing 

```

92% tests passed, 42 tests failed out of 512

Total Test time (real) =  21.80 sec

The following tests FAILED:
	 63 - AlexaClientSDKInitTest.initializeNoJSONConfig (Failed)
	 65 - AlexaClientSDKInitTest.initializeValidJSONConfig (Failed)
	 67 - AlexaClientSDKInitTest.isInitialized (Failed)
	217 - AVSConnectionManagerTest.createTest (Failed)
	218 - AVSConnectionManagerTest.createWithNullMessageRouterAndObservers (Failed)
	220 - AVSConnectionManagerTest.addConnectionStatusObserverValid (SEGFAULT)
	224 - AVSConnectionManagerTest.enableAndDisableFunction (SEGFAULT)
	225 - AVSConnectionManagerTest.sendMessageRequestTest (SEGFAULT)
	226 - AVSConnectionManagerTest.setAVSEndpointTest (SEGFAULT)
	243 - HTTP2StreamPoolTest.GetStreamSendNullPtrForMoreThanMaxStreams (Failed)
	246 - HTTP2StreamPoolTest.PostStreamSendNullPtrForMoreThanMaxStreams (Failed)
	247 - HTTP2StreamPoolTest.ReleaseStreamTestSendMoreThanMaxStreams (Failed)
	248 - HTTP2StreamPoolTest.ReleaseStreamTestAfterNullTest (Failed)
	249 - HTTP2StreamTest.testExceptionReceivedSingleWrite (Failed)
	250 - HTTP2StreamTest.testExceptionReceivedMultiWrite (Failed)
	251 - HTTP2StreamTest.testHeaderCallback (Failed)
	252 - HTTP2StreamTest.testReadCallBack (Failed)
	260 - AuthDelegateTest.createNullConfig (Failed)
	261 - AuthDelegateTest.createMissingClientId (Failed)
	262 - AuthDelegateTest.createMissingClientSecret (Failed)
	263 - AuthDelegateTest.createMissingRefreshToken (Failed)
	264 - AuthDelegateTest.create (Failed)
	265 - AuthDelegateTest.addAuthObserverNull (Failed)
	266 - AuthDelegateTest.removeAuthObserverNull (Failed)
	267 - AuthDelegateTest.addMultipleAuthObserver (Failed)
	268 - AuthDelegateTest.retry (Failed)
	269 - AuthDelegateTest.expirationNotification (Failed)
	270 - AuthDelegateTest.recoverAfterExpiration (Failed)
	271 - AuthDelegateTest.unrecoverableErrorNotification (Failed)
	480 - SettingsTest.createTest (SEGFAULT)
	481 - SettingsTest.addGlobalSettingsObserverTest (SEGFAULT)
	482 - SettingsTest.removeGlobalSettingsObserverTest (SEGFAULT)
	483 - SettingsTest.addSingleSettingObserverWithInvalidKeyTest (SEGFAULT)
	484 - SettingsTest.removeSingleSettingObserverWithInvalidKeyTest (SEGFAULT)
	485 - SettingsTest.removeSingleSettingObserverWithCorrectKeyTest (SEGFAULT)
	486 - SettingsTest.defaultSettingsCorrect (SEGFAULT)
	487 - SettingsTest.clearDatabaseTest (SEGFAULT)
	488 - SettingsTest.storeDatabaseTest (SEGFAULT)
	489 - SettingsTest.modifyDatabaseTest (SEGFAULT)
	490 - SettingsTest.eraseTest (SEGFAULT)
	491 - SettingsTest.createDatabaseTest (SEGFAULT)
	492 - SettingsTest.openAndCloseDatabaseTest (SEGFAULT)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

```

        My cmake command is
        cmake ../avs-device-sdk/  -DCMAKE_BUILD_TYPE=DEBUG 

        Is there any problem here?

**Comment by jjamazon** [comment]
The cmake command looks incomplete.

Take a look here for for Building SDK on Pi.
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#2-build-the-sdk

**Comment by octGitHub** [comment]
Thx for reply!
       OK. thx. I will try.

**Comment by octGitHub** [comment]
I solved this make test failed now. It took me several times to try.
The key point is : 
    you should analyse the error report one by one.
    2017-12-04 08:27:35.513 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2

I solved this by replace the curl  which not support  http2 . 

Just mark here.  Hope it will help.

**Comment by vsthirunavukkarasu** [comment]
Hi octGitHub,
I am also got the same below error,
**2017-12-04 08:27:35.513 [ 1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2**

How you replaced curl version and which version? 

Note: 
I'm using yocto image and there is no apt-get.

**Comment by octGitHub** [comment]
my replace curl version is  curl-7.57.0

    wget  https://curl.haxx.se/download/curl-7.57.0.tar.gz
    tar  -zvxf   curl-7.57.0.tar.gz   &&  cd  ./curl-7.57.0

    ./configure --with-nghttp2="path to your nghttp2 's library  or bin"   --with-ssl

FYI

**Comment by vsthirunavukkarasu** [comment]
Hi,
Thank you so much for the information.
I built the nghttp2 and called in curl configuration like below,
**./configure --host=x86_64 --target=arm-linux --with-nghttp2=/home/thiru/build-avs-device-sdk-Pico_Kit_cmake/Packages/nghttp2/buildNghttp2/lib**

But i' getting below error,
**error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file.**
Did you faced any issues like this?
if you have any idea kindly help me to solve this issue.

**Comment by octGitHub** [comment]
When you are building nghttp2 , try to use it's cmake

      cmake ../    -DCMAKE_INSTALL_PREFIX="path to install lib and bin "

After you make success, you may see its pkconfig file

        /pkgconfig/libnghttp2.pc

**Comment by vsthirunavukkarasu** [comment]
Hi octGitHub,
Thank you so much for the help.
Everything working fine.

**Comment by octGitHub** [comment]
with  pleasure
