### ISSUE TITLE
how to use toolchain with avs-device-sdk and run in embedded system?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#308]
above issue,Can i use Sample/src/./SampleApp in embedded system AND  SampleApp is runnable?
how to compile SampleApp and run it in embedded system(**not Raspberry Pi  system**)?

**Comment by jjamazon** [comment]
The C++ SDK can be used in an embedded system. Can you provide more information on the system you are targeting, OS, CPU, do you have a native toolchain, or are you planning to cross compile.

**Comment by captainpanther** [comment]
OS:NXP 's iMX7_Dual ,CPU:M4+A7 ,toolchain:i use yocto 's bitbake meta-toolchain

**Comment by jjamazon** [comment]
we do not have any documentation on how to build using specific toolchains. 

If you can build with all these dependencies, it should work.
https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies

**Comment by sanjayrd** [comment]
Closing for now due to inactivity. Please reopen if you have any further questions.

Thanks,
Sanjay
