### ISSUE TITLE
when we test avs sdk for long times, we encounter curl_multi_perform() crashes.

### ISSUE THREAD

**Issue by cxt32** [alexa/avs-device-sdk#309]
when we are testing avs sdk for long times ( >= 10 hours), we find there are crashes. here, we can provide two screen shots.

![curl_multi_perform1](https://user-images.githubusercontent.com/33440310/32474908-bdc1ca3e-c334-11e7-9bd5-96a4679b5a56.png)
![curl_multi_perform2](https://user-images.githubusercontent.com/33440310/32474909-be0336a4-c334-11e7-840c-8c3968326e8f.png)

**Comment by captainpanther** [comment]
u update cmake  to 3.10 or later.

**Comment by jjamazon** [comment]
Hi cxt32, can you provide us with some more information. Are you running the SampleApp.

What OS what version of the code ? What kind of testing is going on ? Playing music? , etc.

**Comment by cxt32** [comment]
Thanks a lot. finally, we find this was our own bug.
