### ISSUE TITLE
Question about AuthServer.py

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#311]
Hi AVS team,
 
I have a question from "AuthServer.py" against the document from https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-app.html 
 
In the document, it said it will have a "code_verifier" for client/server challenge, but in AuthServer.py, it seems no this data ?
And in AuthServer.py, it will use "client_secret", but in the document, it does not mention this part.
Will it be a different document for first installation process ?

Thanks,

**Comment by jjamazon** [comment]
Sorry is your question in relation to the C++ SDK ? If it is for the C++ SDK you can find some information here.

https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#run-authserver

**Comment by sanjayrd** [comment]
Hi @zeusshuang,

The documentation you linked is for authorizing a companion app, specifically for mobile (Android/iOS). AuthServer.py implements the other [protocol](https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html), which does not require a code_verifier.

Hope that clarifies things,
Sanjay

**Comment by zeusshuang** [comment]
@sanjayrd ,
sorry to reopen this ticket,
I have a question after reviewed AuthDelegate.cpp and AuthServer.py
In "AuthDelegate.cpp", it seems it only implemented [https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html](url) , 
if we have this way [https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-app.html](url)  , we need to modify the AuthDelegate.cpp by ourselves ?
