### ISSUE TITLE
Problems encountered in playing iheartradio

### ISSUE THREAD

**Issue by cuizhenke** [alexa/avs-device-sdk#312]
Hi AVS team,
We find "error Server does not support seeking" in playing iheartradio,please help me check it.For more log,please see log file.We are using SDK 1.2.
[Gst-error .txt](https://github.com/alexa/avs-device-sdk/files/1452518/Gst-error.txt)

thanks.

E MediaPlayer:handleBusMessageError:source=source,error=Server does not support seeking.,debug=gstsouphttpsrc.c(1484)\: gst_soup_http_src_do_request ()\: /GstPipeline\:audio-pipeline/GstURIDecodeBin\:decoder/GstSoupHTTPSrc\:source\:
Server does not accept Range HTTP header\, URL\: http\://c8icyelb.prod.playlists.ihrhls.com/2525_icy?at\=1&fb_broadcast\=false&deviceid\=amzn1.account.AEYUG43ZOTWXICM2Y2Y3FFODEZOQ&callLetters\=WWDC-FM&streamid\=2525&clienttype\=amazon&iheartradioversion\=1.0&osversion\=1.0&devicename\=Indigo&terminalid\=304&init_id\=8169&profileid\=400706100\, Redirect to\: (NULL)

**Comment by jjamazon** [comment]
Hi cuizhenke,

can you clarify what you mean by seeking? 

iHeartRadio is a radio station that does not support seeking (no skip, no forward, no next/previous). They also have custom stations that support next and previous songs, but not seeking within songs.

**Comment by cuizhenke** [comment]
Hi @jjamazon ,
I didn't do the seek operation.The problem appear when I play the iHeartRadio station normally.When it appears,the MediaPlayer doesn't work.Have you ever met with this problem?How to solve?
thanks.

**Comment by kencecka** [comment]
Hi @cuizhenke,

Is this issue reproducible for you, or was it an isolated/rare intermittent failure?  Looking at the logs, it appears that you had a stutter (buffer underrun), and this somehow resulted in a seek, but I can't see precisely why a seek would have been attempted (the SDK code doesn't appear to be doing it directly).

Ken

**Comment by sanjayrd** [comment]
Hi @cuizhenke,

Please try upgrading your SDK version and see if you're still having issues. I'm going to close this for now due to inactivity but please reopen if you're still seeing issues.

Thanks,
Sanjay
