### ISSUE TITLE
Required GStreamer plugins?

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#315]
What are the required GStreamer plugins?

One method is to enable GST logging and parse the output.  I'm hoping it's documented somewhere.

I'm building GStreamer with statically linked plugins, so I need to be specific.

Thanks

**Comment by jjamazon** [comment]
Hi INRIX-joel-winarske ,

https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#minimum-requirements-and-dependencies

**Comment by INRIX-joel-winarske** [comment]
That's pretty much the kitchen sink.  I'm wondering the minimum list of plugin libraries I need to link against, without concerns for any run time issues.

**Comment by kencecka** [comment]
Hi @INRIX-joel-winarske,

I don't think we have anything more refined at this time with respect to gstreamer plugins.  You can refer to this page for a full list of recommended media formats: https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html

From there, you can pick and choose the specific gstreamer plugins you want to use to support those formats.

Ken

**Comment by sanjayrd** [comment]
Hi @INRIX-joel-winarske,

Although we currently don't have a refined list of requirements, we will try and put together a better list of requirements soon.

In the meantime, the following links might be helpful to you:
[1](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html#getting-pipeline-graphs)
[2](https://developer.ridgerun.com/wiki/index.php/How_to_generate_a_Gstreamer_pipeline_diagram_(graph))

These links go through the steps of generating a GStreamer pipeline graph, so you should be able to see exactly which GStreamer elements are being pulled in and used.

Thanks,
Sanjay

**Comment by fv2018** [comment]
Hi @INRIX-joel-winarske @sanjayrd ,
 Did a min list of GStreamer lib's ever get created?  
Thanks.

**Comment by fv2018** [comment]
Hi @INRIX-joel-winarske @sanjayrd ,
 Did a min list of GStreamer lib's ever get created?  
Thanks.
