### ISSUE TITLE
Curl CAPATH value

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#316]
How do I override the CURLOPT_CAPATH, which appears to be hard coded to the host value.

In Changelog.md I see:

    Added the ability to specify a `CURLOPT_CAPATH` value to be used when libcurl is used by ACL and 
    AuthDelegate.  See See Appendix C in the README for details. 

However there is no reference to this in the README.

Thanks

**Comment by INRIX-joel-winarske** [comment]
Based on the source, it looks like you add something like this to AlexaClientSDKConfig.json.

    "libcurlUtils" {
        "CURLOPT_CAPATH":"/path/for/custom/certs"
    }

**Comment by scotthea-amazon** [comment]
Hello INRIX-joel-winarske,

Yes, that is correct.  Thank you!

BTW, if you encounter issues setting up your custom path you can get curl diagnostic information by building with -DCMAKE_BUILD_TYPE=DEBUG -DACSDK_EMIT_SENSITIVE_LOGS=ON on the cmake command line.

Regards,
-SWH
