### ISSUE TITLE
integration  test failed?

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexa/avs-device-sdk#317]
I use ubuntu 14.04 64-bit  on VMware， 
host pc： windows 10， Intel Core i7-6560U， 64-bit operating system x64-based processor 。
I used   Kitt-AI snowboy  resources：
https://github.com/Kitt-AI/snowboy/blob/master/lib/ubuntu64/libsnowboy-detect.a
https://github.com/Kitt-AI/snowboy/blob/master/resources/alexa.umdl
https://github.com/Kitt-AI/snowboy/blob/master/resources/common.res

The following error is my choice of resources wrong?
[----------] 18 tests from AudioInputProcessorTest (370870 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 1 test case ran. (370870 ms total)
[  PASSED  ] 13 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] AudioInputProcessorTest.wakeWordMultiturn
[  FAILED  ] AudioInputProcessorTest.wakeWordMultiturnWithoutUserResponse
[  FAILED  ] AudioInputProcessorTest.tapToTalkMultiturn
[  FAILED  ] AudioInputProcessorTest.tapToTalkMultiturnWithoutUserResponse
[  FAILED  ] AudioInputProcessorTest.holdToTalkMultiTurnWithSilence
	
	
99% tests passed, 8 tests failed out of 579

Total Test time (real) = 151.54 sec

The following tests FAILED:
	417 - KittAiKeyWordTest.invalidStream (Failed)
	418 - KittAiKeyWordTest.incompatibleEndianness (Failed)
	419 - KittAiKeyWordTest.getExpectedNumberOfDetectionsInFourAlexasAudioFileForOneObserver (Failed)
	420 - KittAiKeyWordTest.getExpectedNumberOfDetectionsInFourAlexasAudioFileForTwoObservers (Failed)
	421 - KittAiKeyWordTest.getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileForOneObserver (Failed)
	422 - KittAiKeyWordTest.getExpectedNumberOfDetectionsInAlexaStopAlexaJokeAudioFileForTwoObservers (Failed)
	423 - KittAiKeyWordTest.getActiveState (Failed)
	424 - KittAiKeyWordTest.getStreamClosedState (Failed)

thanks！

**Comment by jjamazon** [comment]
Hi zuowanbushiwo ,

Take a look here, it tells you where to download the files from for integration test.

https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#run-integration-tests

**Comment by zuowanbushiwo** [comment]
@jjamazon  
thanks！
