### ISSUE TITLE
While playing specific music station from iHR, going to next track is actually going to next 2 track.

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#319]
1. While the lady gaga station is playing, say "alexa , next"
2. Go to the [Amazon Alexa](https://pitangui.amazon.com/spa/index.html#player) Now playing screen.
3. I can see that two songs are skipped

Another issue:
1. While the lady gaga station is playing, say "alexa, previous"
2. Go to the [Amazon Alexa](https://pitangui.amazon.com/spa/index.html#player) Now playing screen.
3. I can see that a new song start playing, can not back to the previous song
Have any suggestions?

**Comment by jjamazon** [comment]
Hi BobXLiu,
Thanks for bringing this up.  

This is a known issue, and we are actively working on a fix.

**Comment by jjamazon** [comment]
Hi BobXLiu,

We can reproduce the "Alexa next" issue, 
but were unable to reproduce the "Alexa previous" issue.

Can you provide us with some logs, so we can diagnose it further.

Is this with the SampleApp? If so can you enable DEBUG9 by running cmake with -DCMAKE_BUILD_TYPE=DEBUG and enabling DEBUG9 mode with

TZ=UTC ./SampleApp /root/BUILD/Integration/AlexaClientSDKConfig.json DEBUG9

Please attach the entire log.

Also what version of the code are you using and which platform.

**Comment by BobXLiu** [comment]
Hi @jjamazon ,
Thanks for you reply!
I will re-create about Amazon music "previous" issue  and close this one.
