### ISSUE TITLE
Is there a Device SDK for Android based Device?

### ISSUE THREAD

**Issue by yangtu222** [alexa/avs-device-sdk#321]
I am working on a device based Android platform and want to use AVS. Is there an Android version of Device SDK? I found out that in issue list many developers working on android and asked many questions about android Device porting problems, so I think it is a general problem that many developers like me are sucked in porting C++ SDK to Android SDK. It will be very nice to extend AVS products if there has an offical Android Device SDK. So, is there a Device SDK for Android based Device? or future?

**Comment by jjamazon** [comment]
Hi yangtu222,

We do not have an Android based SDK, however the C++ SDK has been successfully used in Android environments. The C++ SDK has been written with the goal to be generic and portable.

**Comment by wantitmore** [comment]
@jjamazon hi,I am not family with C++,would you please tell me the detail of how to use C++ SDK in Android environment.use NDK? how to use? thanks a lot !~

**Comment by kencecka** [comment]
Hi @wantitmore,

We don't have a guide on integrating the C++ SDK with Android available at this time.  In general, you would compile and link it using the Android NDK, and then connect it to a java app through JNI.

Ken

**Comment by sanjayrd** [comment]
Hi @yangtu222 and @wantitmore,

We are working on developing a getting started guide for developing on an Android environment. Please contact us using the following [link](https://www.amazon.com/forms/099adfa2-e94a-4c6d-9bd2-cffbf2d34676) if you'd like a beta preview or version!

Thanks,
Sanjay

**Comment by jackho1977** [comment]
Hi sanjaryd,
I try following link you mentioned above to request a beta version started guide for Android
But I didn't get any response, could you help me about this request?

Thank you.
Jack Ho

**Comment by swy0710** [comment]
Hello, @sanjayrd 
I would like to get the guide for android as well.
That link doesn't work for me.
Please share the guide.

Thank you.

**Comment by sanjayrd** [comment]
Hi all,

Please fill out the following [form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and we will reach out to you with information on an Android guide.

Thanks,
Sanjay

**Comment by econno11ee** [comment]
Same here erin@mistyrobotics.com

**Comment by wtohgf** [comment]
Same here hegf@neusoft.com

Thanks alot!

**Comment by CodingDog** [comment]
Hi， I had filled out the form~
Please send me the guide, thanks
liuyulin1987@gmail.com

**Comment by jie714** [comment]
Hi @sanjayrd,
I already fill out the form 2 months ago,
but still not get any guide form your side.
Could you please share the guide to me?
jack.ho@askey.com
Thank you.

**Comment by Ehsanta83** [comment]
Hi @sanjayrd,
I filled out the form too. Could you please send me the guide as well?
esntat@gmail.com
Thanks.

**Comment by mmabluesky** [comment]
Hi @sanjayrd,

I filled out the form too. Could you please send me the guide as well ?

yuanxuya@outlook.com
Thanks !

**Comment by rony-temi** [comment]
Hi @sanjayrd !
I filled the form as well and I would like to get the android guide.
Rony@robotemi.com

Thanks,
Ron.

**Comment by EddyHong** [comment]
Hi @sanjayrd,
I filled out the form too. Could you please send me the guide as well?
eddy@iriver.com
Thanks.

**Comment by xiezhengfeng** [comment]
Will this help? https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide
