### ISSUE TITLE
Modifying avs-device-sdk SampleApp response to custom questions. 

### ISSUE THREAD

**Issue by tkamaal** [alexa/avs-device-sdk#323]
Hello,

**Background**:
I've installed avs-device-sdk [v1.2] on Raspberry Pi 3 Model B. I'm running SampleApp and using voice trigger to wake Alexa. 

**Aim**: 
User asks few questions **specifically** related to our project. As an example: "_Change temperature_" or "_Change brightness_" etc. I want Alexa to **NOT** respond back with **speech output** but instead print a message on the console whenever these custom questions have been asked. 

**Question**:
As of now, by going through the documentation provided for [speech recognizer](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html) and [speech synthesizer](https://developer.amazon.com/docs/alexa-voice-service/speechsynthesizer.html) audio information is converted to binary code. Is there a way to capture user's question? If so, can we stop streaming if it's a custom question to cloud and just print a reply on console? Please do provide a direction to modify the code.

**Comment by jjamazon** [comment]
Hi tkamaal,
Maybe you need to write an Alexa skill to handle these custom requests. The SDK forwards all requests to the Alexa AVS.

**Comment by tkamaal** [comment]
@jjamazon Thank you.

**Comment by jayEmbedded** [comment]
@jjamazon : We want to be able to control the GPIO of the RPi 3 board using AVS C/C++ SDK.
As an example:
"Alexa, turn on the fan."
And we want to be able to see one of the GPIO to be set High.
In order to do so, do we need to write an Alexa skill for that?

**Comment by kencecka** [comment]
Hi @jayEmbedded,

That's correct.  The AVS client code is only concerned with basic voice interaction with the cloud service.  The interpretation of user speech and decision of how to respond to that speech is handled entirely in the cloud.  For your example, you would need to create a skill in the cloud which knows how to interpret your specific commands ("Alexa, tell MySkill to turn on the fan"), and then your skill would communicate with your hardware through a separate channel (direct connection, AWS IoT, etc) to send a command that turns the fan on.

Ken

**Comment by kencecka** [comment]
@jayEmbedded - I'm going to close this issue as the original question has been answered.  Feel free to open a new issue if you have further questions.
