### ISSUE TITLE
compile SampleApp for arm embedded system process

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#325]
First command: cmake /home/~/avs-device-sdk-master  -DGSTREAMER_MEDIA_PLAYER=ON - ~~~~

Do i need to add option in cmake command ?? or how to use cmake to make SampleApp for arm embedded device ??
and comiple SampleApp to be arm executable file.

**Comment by jjamazon** [comment]
Hi captainpanther,

We do not have specific docs on how to run c++ SDK on arm embedded device.

Your best bet would be to follow the Linux Quick Start guide and tailor it for your specific environment.

https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#sample-app-dependencies

**Comment by anu-mathur** [comment]
@captainpanther 

I am doing a user study on the AVS-device-SDK and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) and I will get in touch with you.
Thanks

**Comment by sanjayrd** [comment]
Closing for now due to inactivity. Please reopen if you still have questions.

Thanks,
Sanjay
