### ISSUE TITLE
Amazon music "previous" issue

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#326]
Giving the "previous" command during Amazon music playback skips to the next song instead of going back to the previous one, please check my log information on [this](https://gist.github.com/BobXLiu/426f455a29c028aa3d8cee5b79027618).
duplicate procedure:
1. Say "alexa, Echo favorites playlist from prime music", then the device will play Amazon music.
2. After play some songs then press one of the song before on web UI.
3. Say "alexa, previous", device will play next song instead of going to back previous one.

So i updated [AudioPlayerIntegrationTest](https://gist.github.com/BobXLiu/484a3f1f1807edf01c4517a230c7bf77) file and test Amazon music found that it will jump to first song when send "previous" WAV file.
Duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music A.
2. After minutes, the device will play Amazon music D(playlist: A,B,C,D).
2. Go to the [Amazon Alexa](https://pitangui.amazon.com/spa/index.html#player) Now playing screen.
3. Click Music C , device will play Amazon music C.
3. The device will play first song A after AudioPlayerIntegrationTest send "previous" WAV file.

I put my log information to [this](https://gist.github.com/BobXLiu/4112f63132de7f0816219b442b80b06b)

Code version: SDK 1.1 and 1.2
Platform: 
/ # uname -a
Linux apq8009 3.18.44 #1 SMP PREEMPT Mon Nov 6 20:00:30 CST 2017 armv7l GNU/Linux

**Comment by jjamazon** [comment]
Thank you BobXLiu, will let you know what we find.

**Comment by sanjayrd** [comment]
Hi @BobXLiu,

We believe this had to do with the way we were reporting offsets in previous versions of the SDK. Could you try upgrading to our latest v1.3 and see if you're still having the issue?

Thanks,
Sanjay
