### ISSUE TITLE
How to play local audio file

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#327]
In the version 1.2.0, add struct `AudioItem`, how I constructor a `AudioItem` when I want to play local audio file.

**Comment by jjamazon** [comment]
Hi sundq,

AudioItem is structure representation of AVS directive and is part of AudioPlayer. AudioPlayer is not designed to play local files.

You need to look into MediaPlayer to play local files.

Take a look at the MediaPlayer unit test that plays a local file.

MediaPlayer/test/MediaPlayerTest /Users/jnjshn/src/test-1/avs-cpp-sdk/MediaPlayer/inputs/ --gtest_filter=*testStartPlayForUrl
