### ISSUE TITLE
I can't stop iHR in V1.2.0, it's OK in V1.1.0 SDK

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#328]
Hi ,
I got an issue that I can't stop iHR play in V1.2.0 SDK using my custom APP, but I can stop it in V1.1.0 SDK, [this](https://gist.github.com/boyce-xx/91be3635c0d581794e78a195ae828c48) is error log link, please help to check if it's an error of SDK.

I say "Alexa, stop" during iHR playing, I will get a stop directive.

> 2017-11-06 10:52:18.403 [ 11] I DirectiveSequencer:onDirective:UnparsedDirective={"directive"\:{"header"\:{"namespace"\:"AudioPlayer"\,"name"\:"Stop"\,"messageId"\:"b8941afb-980a-4856-86c6-025ea27ad981"\,"dialogRequestId"\:"e187c3e3-6f32-4bb8-be88-fcfc7a171e44"}\,"payload"\:{}}}

but wait for a seconds, I will get another directive which is Play, and the directive doesn't contains dialogRequestId in data:

> 2017-11-06 10:52:19.525 [ 11] I DirectiveSequencer:onDirective:UnparsedDirective={"directive"\:{"header"\:{"namespace"\:"AudioPlayer"\,"name"\:"Play"\,"messageId"\:"5e895ae6-cbee-4c14-a3e1-0281fdaefad4"}\,"payload"\:{"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#7201fe87-3772-4961-b4ea-cc8425ea2c0e\:1"\,"stream"\:{"offsetInMilliseconds"\:0\,"expiryTime"\:"2017-11-06T10\:53\:19+0000"\,"progressReport"\:{"progressReportIntervalInMilliseconds"\:60000}\,"url"\:"http\://c1icyelb.prod.playlists.ihrhls.com/4257_icy?at\=1&fb_broadcast\=false&deviceid\=amzn1.account.AHGEBUDLL7TRMRM3QUUWDV5VECTA&callLetters\=KBKS-FM&streamid\=4257&clienttype\=amazon&iheartradioversion\=1.0&osversion\=1.0&devicename\=Indigo&terminalid\=304&init_id\=8169&profileid\=404738524"\,"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#7201fe87-3772-4961-b4ea-cc8425ea2c0e\:1"}}\,"playBehavior"\:"REPLACE_ALL"}}}

refer to [AudioPlayer interface](https://developer.amazon.com/docs/alexa-voice-service/audioplayer.html#play), the directive should contain dialogRequestId, right?

thank you!

**Comment by jjamazon** [comment]
Hi boyce-xx,

We are looking into this issue and will keep you posted.

**Comment by kjkh** [comment]
Hi @boyce-xx,

Are you still seeing this issue in V1.3.0?

**Comment by boyce-xx** [comment]
Hi @kjkh , @jjamazon ,
    Upgrade to the SDK 1.3.0, didn't see the issue.
    Thank you.
