### ISSUE TITLE
How to do build SampleAPP without TemplateRuntime due to on GUI soupport?

### ISSUE THREAD

**Issue by wonderjason** [alexa/avs-device-sdk#331]
Hello amazon team,
How to do build SampleAPP without TemplateRuntime due to on GUI soupport?

**Comment by priyagsenthil** [comment]
Hi wonderjason,

In the CMakeLists.txt under /Users/psendil/SDK_latest_11032017/AlexaClientSDK/CapabilityAgents
 remove TemplateRuntime from the set of libraries to be compiled. Additionally some changes will be required to the SampleApp to stop instantiating/using this component.

Thanks for brining this to our notice. We will try to make our build system more flexible to pick and choose components.

Thanks
Prita
