### ISSUE TITLE
MediaPlayer worked well but some tests failed

### ISSUE THREAD

**Issue by louisjzl** [alexa/avs-device-sdk#333]
I have run Alexa 1.2.0 to play music successfully. But when I run the tests, some of the MediaPlayerTest and AudioPlayerIntegrationTest failed. I am a little confused about the tests.
The test FlashBriefing of AudioPlayerIntegrationTest failed. I noticed that the audio from the url given by Alexa lasted about 350 seconds, and in the test SONG_TIMEOUT_DURATION=120s, which would lead to the test failure. Maybe it is more reasonable to make SONG_TIMEOUT_DURATION larger, for example 500s, to ensure that the test can pass.
For  MediaPlayerTest, I have got 5 failed tests:
The tests testUnsteadyReads and testRecoveryFromPauseReads failed to start. With my device, it is a little slow to start playing the music. It takes about 10 seconds. And I set the time waiting for start larger to pass these two tests with the codes: ASSERT_TRUE(m_playerObserver->waitForPlaybackStarted(source, std::chrono::milliseconds(15000))).
The tests testSetOffsetUnseekable and testSetSourceResetsOffset failed because the time recorded by the system timeElapsed is 150ms smaller that MP3_FILE_LENGTH. I am sure that the playback of  fox_dog.mp3 is complete. Maybe the code ASSERT_TRUE(timeElapsed >= MP3_FILE_LENGTH) should be replaced by ASSERT_TRUE(timeElapsed+TOLERANCE >= MP3_FILE_LENGTH)?
For the new test testReadTags, I am wondering whether fox_dog.mp3 can return 3 tags. I have played it with gst-launch-1.0 many times, and always got 2 GST_MESSAGE_TAG.
Is there any idea about theses tests? And is my modification reasonable? Thank you very much if there are some reponse.

**Comment by priyagsenthil** [comment]
Hi louisjzl,

The integration tests have been a little rigid and we are working on making them more robust.
We will investigate the offset management tests testSetOffsetUnseekable and testSetOffsetUnseekable in the MediaPlayer test suite.

Thanks
Priya

**Comment by louisjzl** [comment]
Hi Priya,
Thank you very much for your response. But I am still concerned about the tests  testUnsteadyReads and testRecoveryFromPauseReads. Is it normal for my device to spend about 10 seconds to start the playback?
And also, I am wondering whether there is something wrong with my GStreamer plugins, because I can get only two sets of tags from fox_dog.mp3, while the test itself claims that the mp3 should return 3 sets.  Is there any way to confirm the real number of tags.

**Comment by priyagsenthil** [comment]
Hi louisjzl

Which version of gstreamer are you using. The recommended version is 1.10.4. Also which platform are you running the SampleApp on. 

Thanks
Priya

**Comment by louisjzl** [comment]
Yes. I am using GStreamer 1.10.4, and I run the tests on Linux.
