### ISSUE TITLE
disabling alarms and timers

### ISSUE THREAD

**Issue by ryan-esty** [alexa/avs-device-sdk#334]
The product we are trying to design doesn't lend itself to supporting alarms and timer easily. In our developer portal where we defined our product we don't have named alarms and timers as a supported capability. The SDK will still set a timer and/or alarm. Do we need to change the default client to rip out the alerts capabilities? I was hoping that just not checking the Named timers and alarms on the devices profile would be enough in the developer portal. We would like Alexa just to say alarms and timers aren't supported on this device. I know she does this with some devices but that could be an API versioning issue.

Ryan

**Comment by priyagsenthil** [comment]
Hi Ryan,

That is the intent. If you disable alerts you shouldn't be needing to do anything more with the SDK. The SDK will have the capability to do this if enabled. But as long as the feature is disabled AVS should be rejecting all alert related queries. If this is not happening please let us know with which versions of SDK you are seeing this issue and associated log.

Thanks
Priya

**Comment by ryan-esty** [comment]
Hi @priyagsenthil ,

Thanks for the response. I told my device profile that it doesn't support timers/alarms as described in this image. 
![alarm_setting](https://user-images.githubusercontent.com/27737781/32782439-68279332-c916-11e7-9029-700d8910251c.png) Not sure if there is another place I have to do this. Following is the log using the 1.2 SDK in our project:
[alarm_log.txt](https://github.com/alexa/avs-device-sdk/files/1471010/alarm_log.txt)

**Comment by priyagsenthil** [comment]
Hi Ryan,

The option on the capabilities page that you are showing is only for the ‘named timers and reminders’ options, which currently means alerts which contain custom URLs for rendering, as opposed to the regular ‘beep’ audio file.  Regular alerts will still be sent to the device. We are checking to see if there is a way to turn off alerts completely on a device and will get back to you as we find more info.

Thanks
Priya

**Comment by ryan-esty** [comment]
@priyagsenthil ,

Thanks for the reply and looking into this. I did try to take out the alert capability from the cmake files but then the test code wouldn't compile. That's when I decided to ask the question and hopefully it is something simple.

Ryan

**Comment by priyagsenthil** [comment]
Hi Ryan,

Could you try removing instantiation/usage of the alerts capability agent from the DefaultClient.cpp in addition to removing Alerts from the CapabiltyAgents CMakeLists.txt? This will not prevent alert related directives from being sent. It will only prevent them from being serviced as there are registered handlers. We will continue to investigate what is needed to make sure alert related queries are ignored if alerts capability is not chosen.

Thanks
Priya

**Comment by ryan-esty** [comment]
Priya,

I'll give it a try. I know I had issues before in the compilation of the test code when I tried to remove that. I'll see if I can get around it.

Ryan

**Comment by priyagsenthil** [comment]
Hi Ryan,

We discussed internally and unfortunately there is no way to disable alerts and alerts is a base Alexa requirement?

Thanks
Pria

**Comment by ryan-esty** [comment]
Pria,

Thanks for looking into this. That is unfortunate but I guess we don't have a choice.

Ryan

**Comment by anu-mathur** [comment]
Hi @ryan-esty 
I am doing a user study on the AVS-device-SDK and would love to talk to you about your experiences as a developer. To participate, please fill out this [Contact Form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) and I will get in touch with you.
Thanks!

**Comment by ryan-esty** [comment]
@anu-mathur,

That link doesn't work.

Ryan

**Comment by anu-mathur** [comment]
@ryan-esty : Can you try again? It seems to be working here. [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268)
