### ISSUE TITLE
Question - check point to measure AVS delay

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#335]
Hi AVS team,
 
We would like to measure AVS delay under different network condition, is there any check points from the debug message or functions, so that we can measure the impact under different network condition ?

Thanks,

**Comment by priyagsenthil** [comment]
Hi,

Is this for JAVA SampleApp or with C++ SDK? We already have this in JAVA SampleApp for specific directives/events. If you are looking for C++ SDK if the SampleApp is run with DEBUG9 level you would  need to match up the request with the expected onDirective() call to find the duration. Please provide more details on what you are looking for.

Thanks
Priya

**Comment by priyagsenthil** [comment]
Hi zeusshuang,

Its actually the reverse. We have some metric reporting in the C++ SDK and not in JAVA SampleApp. Let us know what you are looking for.

Thanks

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,
I am working on C++ SDK.
I would like to check the delay during the system is busy (busy on other non-AVS tasks, or networking bandwidth is full).
So, for system busy case, I think it may impact the wake word detection and events ? due to AVS is user mode process, and it maybe swap out by other high priority task or kernel mode driver ?
And for networking is full case, I think it may impact the on-line streaming or Q&A process ?
It's because I have no full picture about the impact in AVS under sysytem busy or bandwidth cases, so I would like to know the major check points so that I can design test cases to make sure the user experiences is good.

**Comment by kencecka** [comment]
Hi @zeusshuang,

The SDK currently has a fairly simple mechanism for capturing metrics.  There is an [AVSCommon/Utils/Metrics.h](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/AVSCommon/Utils/include/AVSCommon/Utils/Metrics.h) header you need to include, and then you can call [ACSDK_METRIC_MSG()](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/AVSCommon/Utils/include/AVSCommon/Utils/Metrics.h#L157) to log timestamped metrics.  These will appear at the critical logging level, so you can build in release mode and run with CRITICAL logging enabled to see them.  This gives the minimum amount of overhead, while still logging the metrics.  You can search the codebase to find existing calls - we've already sprinkled [metrics](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/ADSL/src/DirectiveSequencer.cpp#L134) [calls](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/ADSL/src/MessageInterpreter.cpp#L156) [in](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/AVSCommon/AVS/src/EventBuilder.cpp#L162) a [number](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/CapabilityAgents/AIP/src/AudioInputProcessor.cpp#L195) of [places](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/CapabilityAgents/SpeechSynthesizer/src/SpeechSynthesizer.cpp#L172) that you may find useful.

Ken

**Comment by scotthea-amazon** [comment]
Hello @zeusshuang,

I am closing this issue because it appears to be resolved.  Please feel free to re-open it if I have closed it in error.

Thank you,
-SWH
