### ISSUE TITLE
I can't hear the audio response when I ask a question after playing sports update.

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#337]
Hi,
I got an issue after playing my sports update: **I can't hear the response when I ask a question after playing sports update.**
the re-creation procedure as below:
1. say "Alexa, what's my sports update"
2. Alexa will start to read the sports update; when the reading is finished, say "Alexa, what time is it"
3. I can see the request audio and response text on web UI settings, but I can't hear the audio response.

[here](https://gist.github.com/boyce-xx/3cfe898ab8c8f8644cd9aa54964e8a38) is the test log,  from that, you can see I got a directive from AVS:

> 2017-11-14 10:17:12.922 [  e] I DirectiveSequencer:onDirective:UnparsedDirective={"directive"\:{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"Speak"\,"messageId"\:"132a266f-1490-429c-b181-a9198507d955"\,"dialogRequestId"\:"eb03050e-cfaa-41ad-b6ad-4f568e1ead27"}\,"payload"\:{"url"\:"cid\:DeviceTTSRendererV4_2c1ba85d-0da8-4ad9-9c4b-e5f2686d5f29_19202016"\,"format"\:"AUDIO_MPEG"\,"token"\:"amzn1.as-ct.v1.Domain\:Application\:NotificationsV4#ACRI#DeviceTTSRendererV4_2c1ba85d-0da8-4ad9-9c4b-e5f2686d5f29"}}}

but I don't see the "SpeechStarted" event is sent out.
Please clarify if it is a SDK issue?

PS: I'm using V1.1.0 SDK.

**Comment by priyagsenthil** [comment]
hi boyce-xx,

We tried the sequence in SDK1.2.0 on SampleApp in MAC and don't see the issue. Are you seeing this issue on any specific platform. Could yo try with 1.2.0 and provide details of the platform on which you are seeing this.

Thanks
Priya

**Comment by boyce-xx** [comment]
Hi @priyagsenthil ,

I have tried it with V1.2.0 SDK, the issue still exist.
I'm testing it on my own product, the details of my platform is:

> / # uname -a
Linux apq8009 3.18.44 #1 SMP PREEMPT Mon Nov 13 10:37:58 CST 2017 armv7l GNU/Linux



I put the whole test log to [here](https://gist.github.com/boyce-xx/2e89d94f5ea1ca9b6db80179dc45205c).
maybe you can duplicate it easily by the following procedure:
1. say "Alexa, what's my sports update",  Alexa will start to read the sports update.
2. during playing, to say "Alexa, what time is it" to barge-in
3. at this moment, "Sports update" will be paused, but you can't hear the response about you question "What time is it"; then "Sports update" will continue to play.
4. Waiting for the playing to finish.
5. then you can ask Alexa a question, something like that: "Alexa, Nice to meet you"; recording is OK, web UI is OK(I can see the request question and feedback), but I don't hear the response audio **anymore**; continue to ask, still no response audio playing. 


from the whole test log, here are some time points:
**<1>. I asked "Alexa, play my sports update"**

> 2017-11-15 10:59:22.875 [  9] 0 AudioInputProcessor:executeOnFocusChanged:newFocus=FOREGROUND
AVSConnectionManager::sendMessage {"context":[{"header":{"namespace":"AudioPlayer","name":"PlaybackState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"IDLE"}},{"header":{"namespace":"SpeechSynthesizer","name":"SpeechState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"FINISHED"}},{"header":{"namespace":"Alerts","name":"AlertsState"},"payload":{"allAlerts":[],"activeAlerts":[]}},{"header":{"namespace":"SpeechRecognizer","name":"RecognizerState"},"payload":{"wakeword":"alexa"}},{"header":{"namespace":"Speaker","name":"VolumeState"},"payload":{"volume":80,"muted":0}}],"event":{"header":{"namespace":"SpeechRecognizer","name":"Recognize","messageId":"e27a5c85-6ea2-4565-a9e1-3444ce13c4b0","dialogRequestId":"4d26da04-abac-4195-b6e5-d30481f30981"},"payload":{"profile":"NEAR_FIELD","format":"AUDIO_L16_RATE_16000_CHANNELS_1","initiator":{"type":"WAKEWORD","payload":{"wakeWordIndices":{"startIndexInSamples":8000,"endIndexInSamples":17360}}}}}}

**<2>. Start play sports update**

> 2017-11-15 10:59:27.797 [  8] 0 ContextManager:updateStateLocked:action=updatedState,state={"token"\:"amzn1.as-ct.v1.Domain\:Application\:Sports#ACRI#PlatformTTSRenderer_1d0f9c94-17ce-4aef-938f-c0f32b4872c0"\,"offsetInMilliseconds"\:9\,"playerActivity"\:"PLAYING"},namespace=SpeechSynthesizer,name=SpeechState
2017-11-15 10:59:27.798 [  8] 0 EventBuilder:buildJsonEventString:messageId=c053ac23-4685-4e6b-87e8-4fb42e9e83ee,namespace=SpeechSynthesizer,name=SpeechStarted
AVSConnectionManager::sendMessage {"event":{"header":{"namespace":"SpeechSynthesizer","name":"SpeechStarted","messageId":"c053ac23-4685-4e6b-87e8-4fb42e9e83ee"},"payload":{"token":"amzn1.as-ct.v1.Domain:Application:Sports#ACRI#PlatformTTSRenderer_1d0f9c94-17ce-4aef-938f-c0f32b4872c0"}}}
TestSpeechSynthesizerObserver::onStateChanged  currentSpeechSynthesizerState: 1, newState = 0
*** onSpeechSynthesizerObserverStateChanged:: Start to open < Speaking > LED

**<3>. start barge-in**

> 2017-11-15 10:59:43.745 [  a] 0 HTTP2StreamPool:releaseStream:streamId=29,numAcquiredStreams=1
 *** testKeyWordObserverDebug:: onKeyWordDetected

**<3.1>.  I got a Speak directive, but not see SpeechStarted event**
> 2017-11-15 10:59:47.827 [  f] I DirectiveRouter:preHandleDirective:UnparsedDirective={"directive"\:{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"Speak"\,"messageId"\:"fcd8da98-558e-4040-9789-aee9ab846061"\,"dialogRequestId"\:"38f71918-6dcd-47a7-acc5-2d815561b9f8"}\,"payload"\:{"url"\:"cid\:DeviceTTSRendererV4_a10b7f1b-4693-478d-9c73-663b1f8263fa_1658447908"\,"format"\:"AUDIO_MPEG"\,"token"\:"amzn1.as-ct.v1.Domain\:Application\:NotificationsV4#ACRI#DeviceTTSRendererV4_a10b7f1b-4693-478d-9c73-663b1f8263fa"}}}

**<3.2>. but I can see an error here**

> 2017-11-15 10:59:47.914 [  2] E MediaPlayer:handleBusMessageError:source=audio_sink,error=Could not get/set settings from/on resource.,debug=/home/peter/workspace/src/db2.1-le/apss/poky/build/tmp-glibc/work/armv7a-vfp-neon-oe-linux-gnueabi/gst-plugins/git-r0/vendor/qcom/proprietary/gst-plugins/sys/qahw/gstqahwsink.c(1585)\: gst_qahw_ring_buffer_acquire ()\: /GstPipeline\:audio-pipeline/GstQahwSink\:audio_sink\:
Failed to open output stream\: -17
2017-11-15 10:59:47.915 [  2] 0 MediaPlayer:callingOnPlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=Could not get/set settings from/on resource.,currentId=5
2017-11-15 10:59:47.916 [  8] 0 SpeechSynthesizer:executePlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=Could not get/set settings from/on resource.

**<4>. sports update resumed**

> 2017-11-15 10:59:50.401 [  7] E AudioPlayer:executeOnPlaybackStarted:id=6
--> King:: AudioPlayer changeActivity  from  FINISHED to PLAYING...
2017-11-15 10:59:50.402 [  7] E AudioPlayer:changeActivity:from=FINISHED,to=PLAYING

**<5>. Sport update Finished**

> 2017-11-15 11:00:18.845 [  7] E AudioPlayer:executeProvideState:sendToken=false,stateRequestToken=0
--> King:: AudioPlayer executeProvideState update payload to: {"token":"amzn1.as-ct.v1.Domain:Application:Sports#ACRI#ssml#ACRI#b0305ab0-90c4-4f91-8d7c-f3b6ef73c279.26a9f630-e32e-4a12-abe2-d6ebecfc1427.4-0","offsetInMilliseconds":24,"playerActivity":"FINISHED"}

**<6>. ask Alexa a question**

> 2017-11-15 11:00:23.286 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut
 *** testKeyWordObserverDebug:: onKeyWordDetected

**<7>. get Speak directive, but no speechStart event**

> 2017-11-15 11:01:07.597 [  f] I DirectiveRouter:preHandleDirective:UnparsedDirective={"directive"\:{"header"\:{"namespace"\:"SpeechSynthesizer"\,"name"\:"Speak"\,"messageId"\:"fb44bfc4-0514-4561-83e9-d596e118b036"\,"dialogRequestId"\:"a2c3edd1-117c-4eea-96f4-4b8b01053c40"}\,"payload"\:{"url"\:"cid\:DeviceTTSRendererV4_864d922d-c15b-4425-a3cd-3925e3b6b9af_1681441564"\,"format"\:"AUDIO_MPEG"\,"token"\:"amzn1.as-ct.v1.HouseholdSpeechlet#ACRI#DeviceTTSRendererV4_864d922d-c15b-4425-a3cd-3925e3b6b9af"}}}

**Comment by kclchan** [comment]
According to the logs, the problems seems to be related to the gstreamer audio_sink:

MediaPlayer:handleBusMessageError:source=audio_sink,error=Could not get/set settings from/on resource.,debug=/home/peter/workspace/src/db2.1-le/apss/poky/build/tmp-glibc/work/armv7a-vfp-neon-oe-linux-gnueabi/gst-plugins/git-r0/vendor/qcom/proprietary/gst-plugins/sys/qahw/gstqahwsink.c(1585): gst_qahw_ring_buffer_acquire (): /GstPipeline:audio-pipeline/GstQahwSink:audio_sink:

Were you able to look into this and see what might be happening?

**Comment by frozenberg** [comment]
Hi @boyce-xx,

We haven't received a response in a while so I'm going to close this. Feel free to reply and reopen this issue if you have any more information that you would like us to look into.

Fede
