### ISSUE TITLE
Amazon music issue

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#338]
I updated AudioPlayerIntegrationTest file and found some problems as below while test amazon music.

**Question 1:**
It will stop amazon music while send "loop on" WAV file(But I also found "loop off", "shuffle on" or "shuffle off" had the same issue).
[Here](https://gist.github.com/BobXLiu/c90e4714660321c2e0d278469ae49939) is AudioPlayerIntegrationTest file source code and i attached the [loop on log](https://gist.github.com/BobXLiu/a2228aa0869b08b9aeb157f0331de5e9) , [loop off log](https://gist.github.com/BobXLiu/c5dbdc37e7181a7a09dcbde75865d724), [shuffle on log](https://gist.github.com/BobXLiu/da34edd23bd1f3bf0b58e89d2973b1dd) and [shuffle off log](https://gist.github.com/BobXLiu/3deea6b53b39aa4a5ecd99fea03c5f5f)

duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music
2. After 60 seconds, the AudioPlayerIntegrationTest will send "loop on" WAV file, it will stop play amazon music.

--------
**Question 2:**
It will play a new song while send "next" WAV file.
[Here](https://gist.github.com/BobXLiu/a984491778e766cffbb6c76c2569d95c) is AudioPlayerIntegrationTest file and i put log information to [this](https://gist.github.com/BobXLiu/70a17618056c450f1cdccd475eb7fd46).

duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music A.
2. After minutes, the device will play Amazon music D(playlist: A,B,C,D).
3. Go to the [Amazon Alexa](https://pitangui.amazon.com/spa/index.html#player) Now playing screen.
4. Click Music B , device will play Amazon music B.
5. After seconds, the AudioPlayerIntegrationTest will send "next" WAV file, it will play a new song.

--------

**Question 3:**
It will start playing from the beginning after pause then play on amazon music.
[Here](https://gist.github.com/BobXLiu/966b2e01bdaffa0b2ae1296697d966cb) is AudioPlayerIntegrationTest file source code and i put the log information to [this](https://gist.github.com/BobXLiu/db2688202c94c0bde1f47eaf18c83cc2).

duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music
2. After 60 seconds, the AudioPlayerIntegrationTest will send "pause" WAV file, it will stop play amazon music.
3.  After 20 seconds, the AudioPlayerIntegrationTest will send "play" WAV file, it will start play amazon music, but it will start playing from beginning.
-----

**Question 4:**
It will start playing from the beginning after stop then resume on amazon music.
[Here](https://gist.github.com/BobXLiu/dfaae8041f662cb67a0163b7044aaf33) is AudioPlayerIntegrationTest file source code and i put the log information to [this](https://gist.github.com/BobXLiu/28cd1daafa6927852818db81a0b068ef).

duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music
2. After 60 seconds, the AudioPlayerIntegrationTest will send "stop" WAV file, it will stop play amazon music.
3.  After 20 seconds, the AudioPlayerIntegrationTest will send "resume" WAV file, it will start play amazon music, but it will start playing from beginning.
------

**Question 5:**
Amazon music "previous" issue #326

**Comment by priyagsenthil** [comment]
Hi BobXLiu,

We will try the case 1 that you pointed out.

Regarding 2: It sounds like the right behavior. When next is pressed shouldn't play a new song. If shuffle was enabled it was probably not the next song in the queue. Please advise what am missing here.

Regarding 3 and 4: This is a known issue in the SDK and we are working on fixing this in our future release.

What MediaPlayer are you using for your testing? I see a lot of ACDB -> in the logs which we havent seen before. 

Thanks
Priya

**Comment by BobXLiu** [comment]
Hi @priyagsenthil ,

The shuffle was disabled while test amazon music about question 2.
Sorry for update question 2 duplicate procedure:
1. Run AudioPlayerIntegrationTest tool, the device will play Amazon music A.
2. After minutes, the device will play Amazon music D(playlist: A,B,C,D).
3. Go to the Amazon Alexa Now playing screen.
4. Click Music B , device will play Amazon music B.
5. After seconds, the AudioPlayerIntegrationTest will send "next" WAV file, **_it will play a new song E_**.

**Comment by kclchan** [comment]
Hi @BobXLiu, in the v1.3 release there is a fix to an issue "Fixed a bug which was causing problems with pause/resume and next/previous with Amazon Music.".  Would you able to test v1.3 fixes the issues you were seeing?  Thanks!

**Comment by BobXLiu** [comment]
Hi @kclchan ,
Thanks, this issue has been fixed in the v1.3.
