### ISSUE TITLE
Question about AVS registration status

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#339]
Hi AVS team,
 
I have a question about the AVS registration status.
Q1 - while I de-register a device from APP, I may receive a disconnect or deregister message. While I received a disconnect message, how can I know if it's deregister case or other exception ?

Q2 - If I can just check the "refresh token" status for "register" or "deregister" state ? If the refresh token is invalid, will it only be deregister case ? (or un-register case ?)

Q3 - While a AVS is registered, is there any case that it will become "unregister" state ? (i.e. not from user  kick off the device case)

**Comment by priyagsenthil** [comment]
Hi Zuesshuang,

We tried the registration/deregistration scenarios and here are the findings

For Q1 there could be 2 possibilities
 1. If the device is started after the device has been registered in the logs you should be able to see the error AuthDelegate:handleLwaResponseFailed:error=invalid_grant,isUnrecoverable=true
2017-11-15 21:45:07.241 [  4] E AuthDelegate:threadStopping:reason=encounteredUnrecoverableError
2017-11-15 21:45:07.241 [  4] 0 AuthDelegate:onAuthStateChangeCalled:state=3,error=6 and the device fails to connect to AVS.

2. If the device was registered while it was online the device would receive a SERVER_SIDE_DISCONNECT.  There should be an exception message "onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"843d41bd-0ae9-42db-bce2-5616fd6044d0"}\,"payload"\:{"code"\:"UNAUTHORIZED_REQUEST_EXCEPTION"\,"description"\:"Unable to authenticate the request. Please provide a valid authorization token."}}"
Ideally this should be flagged as an unrecoverable error and system should bail out but this is not the case now and we are looking to fix this.

Q2 - Am not sure I understand your question completely. Are you asking if the refresh token can be invalid only in the deregister case. If so, the answer is no. The refresh token can be invalid even when its expired but the error code will not mark it as unrecoverable error.

Q3 - There has some interaction to deregister a device. It could be the user triggering the deregister or it could be amazon or the device manufacturer who sees issues with the account or device who could deregister the device.

Hope this clarifies.

Thanks
Priya

**Comment by zeusshuang** [comment]
Hi @priyagsenthil  ,
 
Thanks for the comments.
For the answer from Q2, if it's a typo for "access token", not a "refresh token"?
Will the "refresh token" expire ? By my tests, if I hard coded the "refresh token" in AlexaClientSDKConfig.json, after days and system boot up, it will still work to get access token correctly in SampleApp.

And for Q1, will "SERVER_SIDE_DISCONNECT" message only happen in deregister case ? Or I still need to check the reason in exception message ?

Thanks,

**Comment by priyagsenthil** [comment]
Hi zeusshuang,

SERVER_SIDE_DISCONNECT can happen under multiple scenarios including the deregister case. So you still check for the exception message.

refresh_token is fixed over the lifetime of a clientID. A valid refresh_token is required to fetch an access token. So when the refresh_token is invalidated on deregister a user cannot  generate valid access tokens to authenticate. Hope this clarifies.

Thanks
Priya

**Comment by zeusshuang** [comment]
@priyagsenthil  thanks for the comments, it's helpful!
