### ISSUE TITLE
Issue with playlist playback from Amzon Prime

### ISSUE THREAD

**Issue by abiswa** [alexa/avs-device-sdk#341]
Hi AVS Team,

I am using AVS SDK 1.2 and having issue with playing playlist from Amazon Prime. Please find below details of my use-case.

I created a playlist in Amazon Prime with 5 songs.
If I say "Alexa play song from playlist Myplaylist"
It plays First song in the list.
Then "Alexa Next"
It plays second song in the list.
[Alexa.log](https://github.com/alexa/avs-device-sdk/files/1474920/Alexa.log)

Then "Alexa Next"
It plays second song in the list again.

For all subsequent next command it is playing the 2nd song only from the list. Suffle is off in this use case.

In the console log I found that for the first MediaPlayer::setSource call I am getting url of first song

url=>https://dawax2ualjfe6.cloudfront.net/OMC7DA3WBY281A%2Fa04f63a8-7ace-4f48-a373-583498957a6c?response-content-disposition=filename%3D%22Happiness_ID3.mp3%22&Expires=1510754400&Signature=SugVN~695v9K9QglETdlLE7oZtm~~SihJuBjSojiKz7EBi24LE6NbQCInMtNixLcHcKi6SMsn~2TA2C9Ho90PRG8d3LMI2D4wdxPqael5PXrTrHJR1dqRBLSIeF6z~e0qf7gm67NiJcOKsaAagBk11RXRfp0RZKtpmhcODfC1oE_&Key-Pair-Id=APKAJVZTZLZ7I5XDXGUQ

For the 2nd MediaPlayer::setSource call url of 2nd song

url=>https://dawax2ualjfe6.cloudfront.net/OMC7DA3WBY281A%2F045fe282-b89b-4ee9-b57e-b521d1b574bf?response-content-disposition=filename%3D%22v1_CBR_44_1kHz_dualChannel_128kbps_CR71542.mp3%22&Expires=1510754400&Signature=eLbN~mWEz2157bF1pZuZilJTUQi-DH10J~rruvJSl2xD6vz3BBVSMSNON3E61HGpWEmM48pB5ZW6VH5B44gW4YEZocX07t7X7vBnOggknqbWsEHv2R91~nKpimt-HaJeJzEH34-QeVDb5EhS0uoOeavqwR~94ZKekpFdbtfXZvM_&Key-Pair-Id=APKAJVZTZLZ7I5XDXGUQ

For the 3rd MediaPlayer::setSource call url of 2nd song again

url=>https://dawax2ualjfe6.cloudfront.net/OMC7DA3WBY281A%2F045fe282-b89b-4ee9-b57e-b521d1b574bf?response-content-disposition=filename%3D%22v1_CBR_44_1kHz_dualChannel_128kbps_CR71542.mp3%22&Expires=1510754400&Signature=eLbN~mWEz2157bF1pZuZilJTUQi-DH10J~rruvJSl2xD6vz3BBVSMSNON3E61HGpWEmM48pB5ZW6VH5B44gW4YEZocX07t7X7vBnOggknqbWsEHv2R91~nKpimt-HaJeJzEH34-QeVDb5EhS0uoOeavqwR~94ZKekpFdbtfXZvM_&Key-Pair-Id=APKAJVZTZLZ7I5XDXGUQ

For the second playback I did not observe any error from MediaPlayer and plabackStopped is also sent.

MediaPlayer:callingOnPlaybackStopped:currentId=3
2017-11-15 13:07:36.253 [  2] 0 AudioPlayer:onPlaybackStopped:id=3
2017-11-15 13:07:36.253 [  8] 1 AudioPlayer:executeOnPlaybackStopped:id=3
2017-11-15 13:07:36.253 [  8] 0 AudioPlayer:changeActivity:from=PAUSED,to=STOPPED
2017-11-15 13:07:36.253 [  8] 0 AudioPlayer:executeProvideState:sendToken=false,stateRequestToken=0
2017-11-15 13:07:36.253 [  8] 0 ContextManager:updateStateLocked:action=updatedState,state={"token"\:"amzn1.as-ct.v1.Dee-Domain-Music#ACRI#url#ACRI#e348af61-2e23-4b69-b708-7ce494713c52\:2"\,"offsetInMilliseconds"\:3795\,"playerActivity"\:"STOPPED"},namespace=AudioPlayer,name=PlaybackState

I have attached console log for your reference.

Is it a known issue with sdk? Please let me know if you need any further information.

Thanks
Arindam Biswas

**Comment by priyagsenthil** [comment]
Hi abiswa,

We haven't been able to reproduce the issue. Getting the same URL maybe ok as long as the offset is different. Unfortunately the offset set in the PLAY directive is not logged. So its unclear what went wrong. Will continue to see if we are able to reproduce the issue or if you could reproduce the issue printing the full payload of the AudioPlayer directives it will help investigate further.

Thanks
Priya

**Comment by kencecka** [comment]
Hi @abiswa,

We have confirmed this issue and will be fixing it in the next release of the SDK.

Ken

**Comment by sanjayrd** [comment]
Hi @abiswa,

We believe this had been addressed in our v1.3 release. Please try upgrading and seeing if your issue still persists.

Thanks,
Sanjay
