### ISSUE TITLE
Audio Codecs Support - opus

### ISSUE THREAD

**Issue by wonderjason** [alexa/avs-device-sdk#344]
Dear Alexa team,
as URL: https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html#audio-codecs

There is opus of audio codec at avs compatibility support list.
What condition is need to use it? How to trigger it?

Thanks

**Comment by priyagsenthil** [comment]
Hi wonderjason,

At present there is no usecase which triggers the need for Opus codec but it has been added to the list as we plan to have usecases which use this codec sometime in the near future.

Thanks
Priya
