### ISSUE TITLE
Error:  what():  Resource temporarily unavailable

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#345]
Hi,

I encountered a fatal error during my longrun test(happened about running 2 hours),  error message like below:

> terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted

The re-creation procedure as below:
1. ask "Alexa, what time is it"
2. after 1 minute, ask "Alexa, what's the weather like today"
3. after 1 minute, ask "Alexa, where is Shanghai"
4. after 1 minute, go to step 1 and start cycle test.

I'm running on SDK V1.1.0
---
I can see the same issue in the bottom of [this](https://github.com/alexa/avs-device-sdk/issues/127), but have no answer about it

**Comment by ryan-esty** [comment]
@boyce-xx ,

There is a new build that fixes some memory issues. I haven't tried it but if you can upgrade I think they are on 1.2.1 now. Also a few had issues streaming with 1.1.

Ryan

**Comment by priyagsenthil** [comment]
Hi boyce-xx,

We addressed a bunch of stability issues encountered in the earlier SDK release with SDK 1.2.1 release. Please try with the latest version released yesterday. If you still see the issue do let us know.

Thanks
Priya

**Comment by kencecka** [comment]
Hi @boyce-xx,

I'm going to go ahead and close this issue.  Please re-open if you are still encountering aborts after updating to the latest release.

Ken
