### ISSUE TITLE
TLS certificate failed when say what's news

### ISSUE THREAD

**Issue by Ryan-fu-yang** [alexa/avs-device-sdk#350]
[caputure.zip](https://github.com/alexa/avs-device-sdk/files/1495429/caputure.zip)

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      <1.2.1>
      
## Briefly summarize your issue:
say "what's news", gstreamer can't play media file. when I use gst-launch-1.0 to play the URL https://play.podtrac.com/npr-500005/npr.mc.tritondigital.com/NP
R_500005/media/anon.npr-mp3/npr/newscasts/2017/11/22/newscast010621.mp3?agent-de
vice=amazon-echo&orgId=1&d=300&p=500005&story=565869788&t=podcast&e=565869788&sc
=alexa&utm_campaign=nprnewsnow
the output like following:
Setting pipeline to PAUSED ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0: Secure connection setup failed.
Additional debug info:
gstsouphttpsrc.c(1299): gst_soup_http_src_parse_status (): /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0:
Unacceptable TLS certificate (6), URL: https://play.podtrac.com/npr-500005/npr.mc.tritondigital.com/NPR_500005/media/anon.npr-mp3/npr/newscasts/2017/11/22/newscast010621.mp3?agent-device=amazon-echo, Redirect to: (NULL)
Execution ended after 0:00:01.793232663
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

please check the attachment file I uploaded, which include the tls packet captured. thanks!

## Tell us about your environment:
openssl 1.0.2
gnutls 3.5.13
gstreamer 1.10.4
glib-networking 2.50.0
### Tell us what hardware you're using:
MIPS 32

### Tell us about your OS (Type & version):
Linux

**Comment by mavamazon** [comment]
Hi!

Could you please answer several questions:
- Does it happen all the time you are trying to play news?
- Can you open this URL with your browser?

Also, can you please check your date and time as well.

**Comment by Ryan-fu-yang** [comment]
Hi mavamazon,
Thank your reply. I've found the root. The certification file I used seems not full, it work again after I change another ca certification file.
