### ISSUE TITLE
Bluetooth capability agent added later?

### ISSUE THREAD

**Issue by cuizhenke** [alexa/avs-device-sdk#361]
Hi AVS team,
    Do you have the plan to add Bluetooth Capability Agents?

**Comment by kencecka** [comment]
Hi @cuizhenke,

Yes - we are working on bluetooth support, and will be including it in a future release.

Ken

**Comment by scotthea-amazon** [comment]
The question appears to have been answered. Please re-open this issue if it has been closed in error.

**Comment by mikejrh** [comment]
Any ETA for bluetooth support ?  Thanks,
