### ISSUE TITLE
Cannot play music through my registered device with SampleApp on macOS

### ISSUE THREAD

**Issue by scurdy** [alexa/avs-device-sdk#362]
What version of the AVS Device SDK are you using?
master v1.2.1

Briefly summarize your issue:
Running SampleApp on macOS, when invoking "Alexa, play Jazz music" or any request to play something, her response is always " Amazon Music is not supported on this device"

What behavior are you observing?
It seems that my device is not listed in the "Your Amazon Music Settings" page "Manage your Device" is an empty list, whereas in alexa.amazon.com, I can clearly see that in "Settings"->"Device" my device is "Online" and properly registered.

Tell us about your environment:
I build SampleApp for macOS and run it smoothly whenever I need to ask any question to the ASV service. However playing music seems to be not supported according to Alexa answer.
One more thing that can be relevant:
I am registered in Denmark. So far Amazon Music is not available in Denmark yet. I intended to overcome the problem by asking a US colleague to share his credentials so I could add him as a user in my developer console profile. He set up a Amazon Music unlimited account from US.
I refresh the token by login in with his account. I asked Alexa "which account is this?", she answered properly but I still cannot play music.

Tell us what hardware you're using:
MacBook Pro (Retina, 15-inch, Mid 2015)
v10.13.1

**Comment by kencecka** [comment]
Hi @scurdy,

Access to Amazon Music is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

Ken

**Comment by scurdy** [comment]
Dear Ken,
Once again thank you for your fast answer. The device in question is a prototype that will be demoed in CES 2018, so it is crucial it can play Music on command.
I have been spending almost 1 hour trying to find how to contact the business development representative without success, would you please be kind and guide me in that matter. 
thanks.

**Comment by anu-mathur** [comment]
Hi @scurdy 
Can we have a quick call to discuss your issue further? Please fill out this [Contact Form](https://tiny.amazon.com/m48sz8fg/AVS-ContactForm) and I will get in touch with you.
Thanks

**Comment by scurdy** [comment]
Hi Ken,
sorry but "tiny.amazon.com" does not work. it is the link in Contact form. I am very up for a quick call. by the way in I am in Europe GTM+1 so we can align with our working hours.

**Comment by anu-mathur** [comment]
@scurdy 

Can you try this link: https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268


Thanks

**Comment by scotthea-amazon** [comment]
The question appears to have been answered. Please re-open this issue if it has been closed in error.
