### ISSUE TITLE
v1.2.1 build errors / Android NDK 16 - Clang

### ISSUE THREAD

**Issue by INRIX-joel-winarske** [alexa/avs-device-sdk#363]
## What version of the AVS Device SDK are you using?
1.2.1
      
## Briefly summarize your issue:
Build errors

## What is the expected behavior?
Similar experience to v1.2.0 build...

## What behavior are you observing?
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/MessageRouter.cpp:115:21: error: out-of-line definition of 'onConnected'
      does not match any declaration in 'alexaClientSDK::acl::MessageRouter'
void MessageRouter::onConnected(std::shared_ptr<TransportInterface> transport) {
                    ^~~~~~~~~~~
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/MessageRouter.cpp:124:21: error: out-of-line definition of 'onDisconnected'
      does not match any declaration in 'alexaClientSDK::acl::MessageRouter'
void MessageRouter::onDisconnected(
                    ^~~~~~~~~~~~~~
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/MessageRouter.cpp:151:21: error: out-of-line definition of
      'onServerSideDisconnect' does not match any declaration in 'alexaClientSDK::acl::MessageRouter'
void MessageRouter::onServerSideDisconnect(std::shared_ptr<TransportInterface> transport) {
                    ^~~~~~~~~~~~~~~~~~~~~~
make[2]: Leaving directory `/home/joel/git/AVSD/build'
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:172:9: error: initializer 'm_disconnectedSent' does not
      name a non-static data member or base class; did you mean the member 'm_disconnectReason'?
        m_disconnectedSent{false},
        ^~~~~~~~~~~~~~~~~~
        m_disconnectReason
/home/joel/git/AVSD/out/x86_64/include/ACL/Transport/HTTP2Transport.h:355:80: note: 'm_disconnectReason' declared here
    avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason m_disconnectReason;
                                                                               ^
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:172:28: error: cannot initialize a member subobject of
      type 'avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason' with an rvalue of type 'bool'
        m_disconnectedSent{false},
                           ^~~~~
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:704:13: error: use of undeclared identifier
      'm_disconnectedSent'
        if (m_disconnectedSent) {
            ^
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:707:9: error: use of undeclared identifier
      'm_disconnectedSent'; did you mean 'm_disconnectReason'?
        m_disconnectedSent = true;
        ^~~~~~~~~~~~~~~~~~
        m_disconnectReason
/home/joel/git/AVSD/out/x86_64/include/ACL/Transport/HTTP2Transport.h:355:80: note: 'm_disconnectReason' declared here
    avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason m_disconnectReason;
                                                                               ^
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:707:30: error: assigning to
      'avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason' from incompatible type 'bool'
        m_disconnectedSent = true;
                             ^~~~
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:780:42: error: too many arguments to function call,
      expected 0, have 1
        observer->onServerSideDisconnect(shared_from_this());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
/home/joel/git/AVSD/out/x86_64/include/ACL/Transport/TransportObserverInterface.h:51:5: note: 'onServerSideDisconnect' declared here
    virtual void onServerSideDisconnect() = 0;
    ^
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:790:54: error: too many arguments to function call,
      expected single argument 'reason', have 2 arguments
        observer->onDisconnected(shared_from_this(), reason);
        ~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~~~
/home/joel/git/AVSD/out/x86_64/include/ACL/Transport/TransportObserverInterface.h:46:5: note: 'onDisconnected' declared here
    virtual void onDisconnected(avsCommon::sdkInterfaces::ConnectionStatusObserverInterface::ChangedReason reason) = 0;
    ^
make[2]: Leaving directory `/home/joel/git/AVSD/build'
make -f AVSCommon/Utils/test/Common/CMakeFiles/UtilsCommonTestLib.dir/build.make AVSCommon/Utils/test/Common/CMakeFiles/UtilsCommonTestLib.dir/build
make[2]: Entering directory `/home/joel/git/AVSD/build'
/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp:800:31: error: too many arguments to function call,
      expected 0, have 1
        observer->onConnected(shared_from_this());
        ~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
/home/joel/git/AVSD/out/x86_64/include/ACL/Transport/TransportObserverInterface.h:40:5: note: 'onConnected' declared here
    virtual void onConnected() = 0;
    ^

## Provide the steps to reproduce the issue, if applicable:

[ 33%] Building CXX object ACL/src/CMakeFiles/ACL.dir/Transport/HTTP2Transport.cpp.o
cd /home/joel/git/AVSD/build/ACL/src && /opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android --gcc-toolchain=/opt/android-ndk-r16/toolchains/x86_64-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r16/sysroot  -DACL_EXPORTS -DACSDK_LOG_MODULE=acl -DACSDK_OPENSSL_MIN_VER_REQUIRED=2.6.0 -DGSTREAMER_MEDIA_PLAYER -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/MultipartParser -I/home/joel/git/AVSD/out/x86_64/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/AVS/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/Utils/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include -isystem /opt/android-ndk-r16/sources/cxx-stl/llvm-libc++/include -isystem /opt/android-ndk-r16/sources/android/support/include -isystem /opt/android-ndk-r16/sources/cxx-stl/llvm-libc++abi/include  -isystem /opt/android-ndk-r16/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -DDEBUG -DACSDK_DEBUG_LOG_ENABLED -Wall -Wsign-compare -g -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/ACL.dir/Transport/HTTP2Transport.cpp.o -c /home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/HTTP2Transport.cpp

[ 34%] Building CXX object ACL/src/CMakeFiles/ACL.dir/Transport/MessageRouter.cpp.o
cd /home/joel/git/AVSD/build/ACL/src && /opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=x86_64-none-linux-android --gcc-toolchain=/opt/android-ndk-r16/toolchains/x86_64-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r16/sysroot  -DACL_EXPORTS -DACSDK_LOG_MODULE=acl -DACSDK_OPENSSL_MIN_VER_REQUIRED=2.6.0 -DGSTREAMER_MEDIA_PLAYER -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/MultipartParser -I/home/joel/git/AVSD/out/x86_64/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/AVS/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/AVSCommon/Utils/include -I/home/joel/git/AVSD/ThirdParty/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include -isystem /opt/android-ndk-r16/sources/cxx-stl/llvm-libc++/include -isystem /opt/android-ndk-r16/sources/android/support/include -isystem /opt/android-ndk-r16/sources/cxx-stl/llvm-libc++abi/include  -isystem /opt/android-ndk-r16/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -DDEBUG -DACSDK_DEBUG_LOG_ENABLED -Wall -Wsign-compare -g -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/ACL.dir/Transport/MessageRouter.cpp.o -c /home/joel/git/AVSD/ThirdParty/avs-device-sdk/ACL/src/Transport/MessageRouter.cpp

## Tell us about your environment:
Android NDK 16

**/opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --version**
    Android clang version 5.0.300080  (based on LLVM 5.0.300080)
    Target: x86_64-unknown-linux
    Thread model: posix
    InstalledDir: /opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin

### Tell us what hardware you're using:
Android 5+

### Tell us about your OS (Type & version):
Host = Linux - Ubuntu 16.04 LTS
Target = Android 5+

**Comment by INRIX-joel-winarske** [comment]
**/opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --version**
    Android clang version 5.0.300080  (based on LLVM 5.0.300080)
    Target: x86_64-unknown-linux
    Thread model: posix
    InstalledDir: /opt/android-ndk-r16/toolchains/llvm/prebuilt/linux-x86_64/bin

**Comment by kencecka** [comment]
Hi @INRIX-joel-winarske,

It looks like you might have a mixed set of sources from different releases.  Can you do a clean checkout from github and try again?  For example, the first error above is reporting that MessageRouter::onConnected() has not been declared, but you can see it [here](https://github.com/alexa/avs-device-sdk/blob/v1.2.1/ACL/include/ACL/Transport/MessageRouter.h#L77) in the header.

Ken

**Comment by INRIX-joel-winarske** [comment]
Indeed it was a stale code issue :)  Builds great.

Thanks
