### ISSUE TITLE
How to Enable Sound Effects On wakeword Detection

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#364]
Hi Experts,

SDK Version:- 1.2.1
OS:- Linux
HW:- Armv7

I have integrated Alexa to our device and it's working fine. I have Tested it with a USB speaker. 
Going forward, now I  have to enable sound effects after wakeupword is detected i.e. Before Start and after Stop Listening. I am referring to below guide:- 
https://developer.amazon.com/docs/alexa-voice-service/ux-design-overview.html#start-and-stop-listening

But ,I am not sure how I can do it in SDK which API I should call and from where, as I am very new to C++. Can someone please help.

Thanks in Advance.

Regards
Sandy

**Comment by kencecka** [comment]
Hi @sandeepajesh,

Good question.  The SampleApp doesn't currently implement attention sounds, but it does have the hooks necessary to do so.  I would start by looking at UIManager::printState().  This function displays the state transitions in the console, and those are the same transitions you want to detect to play attention sounds.  Whenever printState() gets called, you can examine m_dialogState to determine which sound to play.  As for actually playing the sound, you will probably want to instantiate a new MediaPlayer instance which is used for these sounds.

Ken

**Comment by sandeepajesh** [comment]
Thanks for the information Ken. I will check this.
