### ISSUE TITLE
How to alert to user if there is no internet access

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#366]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      1.2.0
      
## Briefly summarize your issue:
Amazon Echo will tell the user via voice if echo has no internet access like "Your echo lost internet connection". So there must be a built-in audio on the device. So where can we get such audio, so that I can play it out when my device detect the internet disconnection? 

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Raspbian Stretch

**Comment by kencecka** [comment]
Hi @subjectxbj,

AVS does not provide error sounds; you'll need to create your own device sounds for connection issues.

K3n

**Comment by priyagsenthil** [comment]
Test message.

**Comment by subjectxbj** [comment]
@kencecka ,
Thanks.
