### ISSUE TITLE
Can Not Play Music. Geeting Message Amazon Music Not Supported on This Device

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#367]
Hi Team,

I have a query related to Playing Amazon Music on our Prototype device.
When invoking "Alexa, play music", Response is always " Amazon Music is not supported on this device"

Do we have support for Amazon Music on Test devices in India ? 
If No, How we can have support for this on our Prototype device. It's the major requirement for our device. Please help.

Regards
Sandeep S

**Comment by kencecka** [comment]
Hi @sandeepajesh,

There is no restriction for Amazon Music in India, but access to Amazon Music in general is currently restricted to Alexa-enabled devices that are approved for commercial distribution and use. Please contact your Amazon Business Development Representative to get started on the approval for Amazon Music.

Ken
