### ISSUE TITLE
Build SampleApp with DCMAKE_PREFIX_PATH geting failed

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#368]
Hi Team,

I am able to build avs-device-sdk and have tested it with SampleApp.
Now ,I want to build SampleApp available with SDK ,path specified using DCMAKE_PREFIX_PATH

CMake command that I am using:-

cmake ../avs-device-sdk/ -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/usr/local/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/root/portaudio/portaudio/include -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/root/alexa/extra/alexa-rpi/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/root/alexa/extra/alexa-rpi/include -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/usr/local/lib/ -DACSDK_EMIT_SENSITIVE_LOGS=ON -DCURL_LIBRARY=/usr/local/alexa_libs/lib/libcurl.so -DCURL_INCLUDE_DIR=/usr/local/alexa_libs/include -DCMAKE_BUILD_TYPE=DEBUG **-DCMAKE_INSTALL_PREFIX=/root/libs_alexa**

Then, make install

Then Alexa SDK libs are available in /root/libs_alexa .

Now I want to compile Sample Application using DCMAKE_PREFIX_PATH=/root/libs_alexa .

I made some changes to cmake and tried to build it:-

cmake --DCMAKE_PREFIX_PATH=/root/libs_alexa -DPORTAUDIO_LIB_PATH=/usr/local/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/root/portaudio/portaudio/include  -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/root/alexa/extra/alexa-rpi/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/root/alexa/extra/alexa-rpi/include  -DCMAKE_BUILD_TYPE=DEBUG

But it's getting failed , error below:-

[100%] Linking CXX executable SampleApp
/usr/bin/ld: CMakeFiles/SampleApp.dir/SampleApplication.cpp.o: undefined reference to symbol '_ZN14alexaClientSDK16capabilityAgents6alerts7storage18SQLiteAlertStorageC1Ev'
**//usr/local/lib/libAlerts.so**: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/Sample.dir/build.make:330: recipe for target 'SampleApp' failed
make[2]: *** [SampleApp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [CMakeFiles/SampleApp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
[root@artik src]#

Can someone please guide how can build it with -DCMAKE_PREFIX_PATH.

Thx-
Sandeep S

**Comment by kencecka** [comment]
Hi @sandeepajesh,

The SampleApp bundled with the SDK is set up to build as part of the SDK.  you can't build it from outside without making modifications to the CMakeLists.txt files.  Here's a quick example:

1.  cmake, make, make install the SDK (to /root/libs_alexa).
2.  The SDK currently does not install the rapidjson headers, but they are needed for external builds.  Copy avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include/rapidjson to the include dir of your installed SDK files (/root/libs_alexa/include/rapidjson).
3.  Copy avs-device-sdk/SampleApp to ExternalSampleApp (somewhere outside of the SDK).
4.  Change ExternalSampleApp/CMakeLists.txt to the following:
```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(ExternalSampleApp LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DRAPIDJSON_HAS_STDSTRING")
add_subdirectory("src")
```
5.  Change ExternalSampleApp/src/CmakeLists.txt to the following:
```
find_package(PkgConfig)
pkg_check_modules(SDK REQUIRED AlexaClientSDK)
pkg_check_modules(PortAudio REQUIRED portaudio-2.0)
link_directories(${SDK_LIBRARY_DIRS})
add_executable(ExternalSampleApp 
    main.cpp 
    PortAudioMicrophoneWrapper.cpp 
    InteractionManager.cpp 
    UserInputManager.cpp
    ConsolePrinter.cpp
    GuiRenderer.cpp
    UIManager.cpp
    KeywordObserver.cpp
    ConnectionObserver.cpp
    SampleApplication.cpp)
target_link_libraries(ExternalSampleApp 
    ${SDK_LIBRARIES}
    ${PortAudio_LIBRARIES}
    rt
    m
    pthread
    asound)
target_include_directories(ExternalSampleApp
    PUBLIC "${ExternalSampleApp_SOURCE_DIR}/include"
    PUBLIC ${SDK_INCLUDE_DIRS}
    PUBLIC ${PortAudio_INCLUDE_DIRS})
```
6.  Create an ExternalSampleApp-build directory to build your external application in
7.  Run CMake in ExternalSampleApp-build, pointing at your ExternalSampleApp source directory with modified CMakeList.txt files, with CMAKE_PREFIX_PATH pointing at your installed SDK files (/root/libs_alexa).

Ken

**Comment by sandeepajesh** [comment]
Many Thanks Ken. It worked.

**Comment by onny** [comment]
Okay I was able to fix this, here is it: ``ExternalExampleApp/CMakeLists.txt``
```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(SampleApp LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DRAPIDJSON_HAS_STDSTRING")
if (GSTREAMER_MEDIA_PLAYER)
    add_definitions("-DGSTREAMER_MEDIA_PLAYER")
endif()
add_subdirectory("src")
```
Best regards,
Jonas
