### ISSUE TITLE
Setting GPIO High/Low with simple commands like "Alexa, turn on the fan".

### ISSUE THREAD

**Issue by jayEmbedded** [alexa/avs-device-sdk#369]
With Reference to **_Modifying avs-device-sdk SampleApp response to custom questions_** (https://github.com/alexa/avs-device-sdk/issues/323#issuecomment-348615410),

Thank you @kencecka for clarifying.
In the example you used (_"Alexa, tell MySkill to turn on the fan"_), I can understand, that it will require a **_custom skill_**.
But for the example like ("Alexa, turn on the fan."), there isn't like "tell MySkill" or "ask MySkill". I am not sure if the custom skill can help in this example?
How can I achieve like "Alexa, turn on the fan" phrase to see one of the GPIO to be set High.

**Comment by scotthea-amazon** [comment]
Hello jayEmbedded,

A simpler interaction like you describe can be created using [Alexa Smart Home](https://developer.amazon.com/alexa/smart-home/learn).

Alexa Smart Home devices reply upon an Alexa enabled device to provide the Alexa voice user interface.  The Alexa enabled device sends voice requests to the cloud, where they are interpreted.  One potential outcome of the interpretation is to send commands to Alexa Smart Home devices.

If you want your device to both act upon interactions like you describe above, and provide the Alexa voice user interface (i.e. listening for Alexa commands and playing Alexa responses), you could combine both an Alexa client built with the [AVS Device SDK](https://developer.amazon.com/alexa-voice-service/sdk)  and Alexa Smart Home functionality into the same device.

I hope that help clarify things,
-SWH

**Comment by jayEmbedded** [comment]
Thank you so much for the response, @scotthea-amazon. 
That's exactly I wanted to know, it makes the picture clear now.
Now, I'll look for how to combine AVS Device SDK and Alexa Smart Home functionality.
If you know, whether AWS provides any reference design or document about combining, can you please share? That will be really helpful to minimize the time realize the functionality and prototyping.

**Comment by scotthea-amazon** [comment]
Hi jayEmbedded,

Unfortunately, we do not have any ready examples or documents on this to point you at.  The implementation of those two parts are completely separate at the moment.

Regards,
-SWH

**Comment by jayEmbedded** [comment]
Okay, thanks for checking and confirming @scotthea-amazon .
