### ISSUE TITLE
ConnectByDeviceIdSucceeded Event  cause INTERNAL_SERVICE_EXCEPTION

### ISSUE THREAD

**Issue by axdc11239** [alexa/avs-device-sdk#370]
Hello, AVS Team:

I'm still working on implement Bluetooth interface.

It's work fine with `EnterDiscoverMode` , `ScanDevice`, `PairDevice` ...etc

until `ConnectByDeviceId`

when this directive come , i response this 

```
{
	"context":[
		{
			"header":{
				"namespace":"Speaker",
				"name":"VolumeState"
			},
			"payload":{
				"volume":100,
				"muted":false
			}
		},
		{
			"header":{
				"namespace":"SpeechSynthesizer",
				"name":"SpeechState"
			},
			"payload":{
				"token":"amzn1.as-ct.v1.Bluetooth#ACRI#PlatformTTSRenderer_32366c69-3f33-440a-82c5-9192f81c3046",
				"offsetInMilliseconds":0,
				"playerActivity":"FINISHED"
			}
		},
		{
			"header":{
				"namespace":"AudioPlayer",
				"name":"PlaybackState"
			},
			"payload":{
				"token":"",
				"offsetInMilliseconds":0,
				"playerActivity":"IDLE"
			}
		},
		{
			"header":{
				"namespace":"Bluetooth",
				"name":"BluetoothState"
			},
			"payload":{
				"alexaDevice":{
					"friendlyName":"my_alexa_device"
				},
				"pairedDevices":[
				],
				"activeDevice":{
					"uniqueDeviceId":"4d2a9f3a-d8ce-11e7-b997-b827ebb5c166",
					"friendlyName":"Lai MacBook Pro",
					"supportedProfile":[
						{
							"name":"A2DP-SOURCE",
							"version":"1.3"
						},
						{
							"name":"A2DP-SINK",
							"version":"1.3"
						}
					],
					"streaming":"INACTIVE"
				}
			}
		},
		{
			"header":{
				"namespace":"SpeechRecognizer",
				"name":"RecognizerState"
			},
			"payload":{
				"wakeword":""
			}
		},
		{
			"header":{
				"namespace":"Alerts",
				"name":"AlertsState"
			},
			"payload":{
				"allAlerts":[
				],
				"activeAlerts":[
				]
			}
		}
	],
	"event":{
		"header":{
		"namespace":"Bluetooth",
		"name":"ConnectByDeviceIdSucceeded",
		"messageId":"8ad29dff-49b8-4e6b-9f02-815c045e39f1"
	},
	"payload":{
		"device":{
			"uniqueDeviceId":"4d2a9f3a-d8ce-11e7-b997-b827ebb5c166",
			"friendlyName":"Lai MacBook Pro"
		},
			"requester":"CLOUD"
		}
	}
}
```

but i get this error msg 

```
2017-12-04 08:37:18.695 [  9] E MessageRequest:onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"0d5e5649-8641-4e52-8458-298a2ec2de46"}\,"payload"\:{"code"\:"INTERNAL_SERVICE_EXCEPTION"\,"description"\:"Request could not be executed due to an internal service error."}}
```
## Test Flow

1. In Amazon Alexa Bluetooth Console click `Pair A New Device`
2. Wait avs-client reply `Scan Device List`
3. Click the device which i want to pair
4. I can see that device in the paird device page
5. And i Click that device again, trying to connect
6. Connect failed due to `INTERNAL_SERVICE_EXCEPTION`

## Question :
- Is there something I missed in my context or my event payload?
- When a `Paired Device` is `ConnectByDeviceId` success, i need to put them from `"pairedDevices"` to  `"activeDevice"` , is that right?

**Comment by scotthea-amazon** [comment]
Hi axdc11239,

Can you provide the x-amzn-requestid value from the log for one of these failed requests?  That may allow us to see what the server did not like about your event.

Thank you,
-SWH

**Comment by axdc11239** [comment]
Hi, Thanks for your reply.

This is my log

```
2017-12-05 01:57:32.707 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"Bluetooth"\,name\:"ConnectByDeviceId"\,messageId\:"be25b878-0321-477e-b381-961bc2ed8b46"\,dialogRequestId\:""}
2017-12-05 01:57:32.707 [  4] I DirectiveRouter:preHandleDirective:messageId=be25b878-0321-477e-b381-961bc2ed8b46,action=calling
2017-12-05 01:57:32.707 [  5] I DirectiveRouter:handleDirective:messageId=be25b878-0321-477e-b381-961bc2ed8b46,action=calling
2017-12-05 01:57:32.709 [  6] I Bluetooth:onContextAvailable:event=ConnectByDeviceIdSucceeded
2017-12-05 01:57:33.182 [  9] E MessageRequest:onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"66ead6ce-6e16-4704-96d8-db0d9eb1c9a4"}\,"payload"\:{"code"\:"INTERNAL_SERVICE_EXCEPTION"\,"description"\:"Request could not be executed due to an internal service error."}}
```

-Edmund

**Comment by scotthea-amazon** [comment]
Hi Edmund,

Sorry, but that log does not include an **x-amzn-requestId** value.  Lines with those values will include the string **x-amzn-requestId** before the value we need to look at the server logs.

If you are not seeing lines like those in your logs, are you testing with a DEBUG build?  You can create a debug build by passing -DCMAKE_BUILD_TYPE=DEBUG on the cmake command line.  That is required, otherwise DEBUG level logging is compiled out.  You will also need to specify DEBUG9 on the SampleApp command line to enable DEBUG logging.

Also, it is often most helpful to just attach the whole log output (as a file, if possible, please) in case it contains other clues to the root of the problem.

Regards,
-SWH

**Comment by axdc11239** [comment]
Thanks for reminding!

the attachment file is the whole log output.

[2017_12_05_13_13_avs_log.txt](https://github.com/alexa/avs-device-sdk/files/1529779/2017_12_05_13_13_avs_log.txt)

**Comment by scotthea-amazon** [comment]
Hello axdc11239,

When  connecting a paired device succeeds, the device should be under both **activeDevice** and **pairedDevices**.  If a new device is paired with Alexa device, it should be added to the **pairedDevice** list and when a bluetooth device is connected, it should appear in **activeDevice**.

Please let us know if this helps you,
-SWH

**Comment by axdc11239** [comment]
Hi, Thanks for your help.

It seems works.

but i have 2 another question

1.
when i followed your instruction to let a `activeDevice` added to the `pairedDevice` 

avs bluetooth console showing a `blue bluetooth icon` which means we connected.

but my device still showing the same error.

```
2017-12-06 01:53:38.708 [  9] 0 EventBuilder:buildJsonEventString:messageId=82c5aeaf-e127-414a-aaff-29e5f6ab44fc,namespace=Bluetooth,name=ScanDevicesUpdated
2017-12-06 01:53:38.713 [  9] I Bluetooth:onContextAvailable:event=ConnectByDeviceIdSucceeded
2017-12-06 01:53:38.715 [  9] 0 EventBuilder:buildJsonEventString:messageId=f339ed13-ea73-4f39-a360-b5d7c3832427,namespace=Bluetooth,name=ConnectByDeviceIdSucceeded
2017-12-06 01:53:38.766 [  b] 0 HTTP2Transport:processNextOutgoingMessage
2017-12-06 01:53:38.766 [  b] 0 HTTP2StreamPool:getStream:streamId=23,numAcquiredStreams=2
2017-12-06 01:53:39.109 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0e9c6ffffee94c42-00004067-000029fe-7d01bcf734d7ae5b-523490b6-23
2017-12-06 01:53:39.109 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=23,result=204
2017-12-06 01:53:39.110 [  b] 0 HTTP2StreamPool:releaseStream:streamId=23,numAcquiredStreams=1
2017-12-06 01:53:39.110 [  b] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-12-06 01:53:39.110 [  b] 0 HTTP2Transport:processNextOutgoingMessage
2017-12-06 01:53:39.110 [  b] 0 HTTP2StreamPool:getStream:streamId=25,numAcquiredStreams=2
2017-12-06 01:53:39.471 [  b] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0e9c6ffffee94c42-00004067-000029fe-7d01bcf734d7ae5b-523490b6-25
2017-12-06 01:53:39.472 [  b] E MessageRequest:onExceptionReceived:exception={"header"\:{"namespace"\:"System"\,"name"\:"Exception"\,"messageId"\:"8249fafd-ac4b-4ce0-b8ed-b10fb962609a"}\,"payload"\:{"code"\:"INTERNAL_SERVICE_EXCEPTION"\,"description"\:"Request could not be executed due to an internal service error."}}
2017-12-06 01:53:39.473 [  b] 0 HTTP2Transport:cleanupFinishedStream:streamId=25,result=500
2017-12-06 01:53:39.474 [  b] 0 HTTP2StreamPool:releaseStream:streamId=25,numAcquiredStreams=1
```

what is this exception means? 

2. Is there any case that a device showing on `activeDevice` but not in `pariedDevice` ?

Because , I saw the `Bluetooth Interface Document` has a `Context Sample`

the `activeDevice`  "AVS Device 1" is not added in `pairedDevices` 

Is this sample need to be modified or that is a special case?

**Comment by scotthea-amazon** [comment]
Hello Edmund,

Regarding 1:
 
Looking up the service logs for the latest exception you included, I see the same error being reported.  Looking again at your request, I see that you have used the name **"supportedProfile"** and not **"supportedProfiles"** as specified [here](https://developer.amazon.com/docs/alexa-voice-service/bluetooth.html#context) (Note the 's' at the end).  Please let us know whether or not changing this helps.

Regarding 2:

As far as I know, there is not case for a **"activeDevice"** to not also be in the list of **"pairedDevices"**.

Also, would you please provide a link to the misleading example in our documentation, I have not found the case that you are referring to.

Thank you,
-SWH

**Comment by axdc11239** [comment]
Dear scotthea:

Thanks for your reply.

Tomorrow, I will try the first problem.

and 

The second one, I found this example at [Bluetooth Document](https://developer.amazon.com/docs/alexa-voice-service/bluetooth.html)

in the `Context` chapter

![image](https://user-images.githubusercontent.com/14975154/33663785-4ba43612-dacc-11e7-8521-d27362f16440.png)

There is a ` > Show Sample ` button there

![image](https://user-images.githubusercontent.com/14975154/33663822-6b43a426-dacc-11e7-84e2-1c200899a4f5.png)

And click it , that is what i talking to.

I copied this example to here.

And I found this example is also using `supportedProfile` but not `supportedProfiles`  , that maybe not correct too, right?

```
{
    "header": {
        "namespace": "Bluetooth",
        "name": "BluetoothState",
    },
    "payload": {
        "alexaDevice": {
            "friendlyName": "Echo-0ST",
        },
        "pairedDevices": [
            {
                // This identifies Kelly's Phone as a paired device
                // that supports two profiles.
                "uniqueDeviceID": "353088131600891",
                "friendlyName": "Kelly's Phone",
                "supportedProfile":[
                    {
                        "name" : "A2DP-SOURCE",
                        "version" : "1.3"
                    },
                    {
                        "name" : "AVRCP",
                        "version" : "1.0"
                    }
                ],
            },
        ],
        // This identifies the connected device and its supported
        // profiles.
        "activeDevice": {
           "uniqueDeviceID": "367388087352897",
           "friendlyName": "AVS Device 1",
           "supportedProfile":[
                {
                    "name" : "A2DP-SOURCE",
                    "version" : "1.3"
                },
                {
                    "name" : "AVRCP",
                    "version" : "1.0"
                },
                {
                    "name" : "A2DP-SINK",
                    "version" : "1.3"
                }
           ],
           // This is the streaming state at the time an event is sent.
           // This will determine what playback directives are sent to your
           // product.
           streaming: "ACTIVE"
        },
    }
}
```

Thanks for your help.

Edmund

**Comment by scotthea-amazon** [comment]
Hello Edmund,

Thank you so much for pointing this out so clearly!  We will work on getting the documentation corrected.

Regards,
-SWH

**Comment by scotthea-amazon** [comment]
Hello Edmund,

Taking a further look at the services log, it seems that the request sent triggering your latest exception is also badly malformed.  The message that was received was:

> {"context":[{"header":{"namespace":"Speaker","name":"VolumeState"},"payload":{"volume":100,"muted":false}},{"header":{"namespace":"SpeechSynthesizer","name":"SpeechState"},"payload":{"token":"amzn1.as-ct.v1.Bluetooth#ACRI#PlatformTTSRenderer_b6ab3247-83f8-4142-a4f0-87c1ec2b111c","offsetInMilliseconds":0,"playerActivity":"FINISHED"}},{"header":{"namespace":"AudioPlayer","name":"PlaybackState"},"payload":{"token":"","offsetInMilliseconds":0,"playerActivity":"IDLE"}},{"header":{"namespace":"Bluetooth","name":"BluetoothState"},"payload":{"alexaDevice":{"friendlyName":"[[SCRUBBED]]","friendlyName":"[[SCRUBBED]]","supportedProfile":[{"name":"A2DP-SOURCE","version":"1.3"},{"name":"A2DP-SINK","version":"1.3"}]}],"activeDevice":{"uniqueDeviceId":"4140abd2-da28-11e7-acd7-b827ebb5c166","friendlyName":"[[SCRUBBED]]","supportedProfile":[{"name":"A2DP-SOURCE","version":"1.3"},{"name":"A2DP-SINK","version":"1.3"}],"streaming":"INACTIVE"}}},{"header":{"namespace":"SpeechRecognizer","name":"RecognizerState"},"payload":{"wakeword":""}},{"header":{"namespace":"Alerts","name":"AlertsState"},"payload":{"allAlerts":[],"activeAlerts":[]}}],"event":{"header":{"namespace":"Bluetooth","name":"ConnectByDeviceIdSucceeded","messageId":"f339ed13-ea73-4f39-a360-b5d7c3832427"},"payload":{"device":{"uniqueDeviceId":"4140abd2-da28-11e7-acd7-b827ebb5c166","friendlyName":"[[SCRUBBED]]"},"requester":"DEVICE"}}}

If you run that through a JSON validator you will find that there is an unexpected ']' right before "activeDevice".  There are also two "friendlyName" values under "alexaDevice", as well as a "supportedProfile" value under "alexaDevice". 

It looks to me as if the start of the "pairedDevices" section has gone missing from the message that was sent.

Regards,
-SWH

**Comment by axdc11239** [comment]
Since I modify the JSON key from `supportedProfile` to `supportedProfiles` , there is no more exceptions.

At the same time , I checked the JSON format before I sent , everything seems works fine. It is weird. I will keep observing this JSON format problem.

At the end, thanks for your helps, again.

## I summarized my problems and the solutions.

When you paired a device , you need to update your context `Bluetooth.BluetoothState`.

This paired device should add to `pairedDevice` list but not in `activeDevice`

and the most important thing is, if there is no `activeDevice` you **CAN NOT** have this JSON key with an empty JSON object like below example

```
{ 
  ...
  ...
  "activeDevice":{}
}
```

this will cause an internal exceptions too.

If you connected a device and you need to update your context before you send back 

`ConnectByDeviceIdSucceeded` event

and the connected device should add to  **BOTH** `activeDevice` and `pairedDevice`

-----------------------------------

Edmund

**Comment by scotthea-amazon** [comment]
Hello Edmund,

Thank you for the summary and also for reporting the restriction on an empty "activeDevice" object.

The issue appears to have been addressed, so I will close it.  Please re-open it if I have closed it in error.

Thank you for your help!
-SWH
