### ISSUE TITLE
can't play spotify music on AVS sdk device

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#371]
Hi AVS team,
We have a spotify account and play spotify music on Echo dot.
(https://user-images.githubusercontent.com/511139/33593605-1b96a11e-d9cb-11e7-9e42-d2ac0f32e1f4.png
![image](https://user-images.githubusercontent.com/511139/33593720-9632137c-d9cb-11e7-822f-7e4e410b203d.png)

But we can't play spotify music on AVS sdk device
![image](https://user-images.githubusercontent.com/511139/33593706-85402324-d9cb-11e7-9f64-fdb4c1b60af6.png)

Thanks

**Comment by scotthea-amazon** [comment]
Hello Aki29,

Spotify music playback is not yet supported in the AVS SDK. Please work with your business team to contact AVS Business Development for more details.

Thank you,
-SWH

**Comment by aki29** [comment]
Hi 
Got it
Many Thanks
