### ISSUE TITLE
Alexa, getting into Loop for Command "Alexa ! Who are you"

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#372]
Hi Experts,

I have integrated Alexa into our Armv7 based Prototype device and It was working fine. Today I am having a very strange issue as described below:-
      
## Briefly summarize your issue:
Command: Alexa, Whats the Time
Response:- Time is 3:20 PM

Command: Alexa, What's the Weather forecast for Today.
Response :- Correct weather report

Alexa, Who are you?
Response :- I am Alexa And I <after this it again start with I am Alexa and I ... I am Alexa and I ....I am Alexa and I......I am Alexa and I......> In between Some time response is, Calling with Alexa is not supported
[log_file.txt](https://github.com/alexa/avs-device-sdk/files/1530663/log_file.txt)

My Observation:-
If we have Alexa keyword into a command response , then sensory lib detects it as an wake word and state got changed from Speaking to Listening. So now it's waiting for User Input, if there is no audio detected , its changing state from Listening->Thinking->Speaking. Again it tries to play earlier command response (Command: who are you) and again wakeword is detected and it goes on and on.  

I am also attaching DEBUG9 logs.

## What version of the AVS Device SDK are you using?
     1.2.1

### Tell us about your OS (Type & version):
[ ] Linux

Thx-
Sandy

**Comment by scotthea-amazon** [comment]
Hi Sandy,

As you noted above, the problem is that the reply in this case includes the word "Alexa", which triggers wake word detection, interrupting the playback and then repeating when the recognize terminates.  You can use headphones or tap-talk as a work-around, but what you really need is an Acoustic Echo Cancellation (AEC) component to filter the speaker output from the microphone input.  Currently, we do not provide an audio front end component with the SDK to perform this operation.

Regards,
-SWH

**Comment by sanjayrd** [comment]
As Scott mentioned, you'll need to add in some sort of Audio Front End component that can subtract the output noise from the input audio. This is not provided by default in the SDK since it is hardware specific.

Thanks,
Sanjay

**Comment by subjectxbj** [comment]
Hi @scotthea-amazon ,

I met the same problem on our unit with SDK 1.6 and 1.7.1. I have reported this issue to our audio front end chip vendor. But they said that even the unit is wakeup by the response, the Cloud Based WW Verification should be able to detect this false wakeup, so the unit should not enter the loop. Is that true?
