### ISSUE TITLE
Turn on LED when wake word detected

### ISSUE THREAD

**Issue by Jeins98** [alexa/avs-device-sdk#373]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      newest
      
## Briefly summarize your issue:
Hello is it possible to update the code so, that raspberry pi can turn on a led when the wake word is detected

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessie
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello Jeins98,

Is this a feature request?  If so, you should create a request for it in our [Feature Request space](https://forums.developer.amazon.com/spaces/185/index.html) within the forums.

Thank you,
-SWH

**Comment by sanjayrd** [comment]
Hi @Jeins98,

Even though we don't currently do this in the SampleApp or SDK currently, you can do this glue code that you will need to write. In the following [code](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/KeywordObserver.cpp), you can put in the glue code to turn on an LED in the `KeywordObserver::onKeyWordDetected()` function, which gets called whenever a wake word is detected. Note however that this suggestion is only valid if you want to modify our SampleApp. A custom app will require similar changes elsewhere. 

Thanks,
Sanjay

**Comment by Jeins98** [comment]
Many Thanks it works!!

**Comment by sharkwheels** [comment]
I'm also trying to do this, does anyone have an example of what they did?

**Comment by Jeins98** [comment]
I did this like the comment before. I worked for me.

Nadine <notifications@github.com> schrieb am Fr., 7. Sep. 2018, 19:39:

**Comment by shivasiddharth** [comment]
@sharkwheels  I was kind looking for something similar and was not sure as to where the changes had to be made, so i came up with my own script.  Just run the startsample through this. https://github.com/shivasiddharth/Assistants-Pi/blob/master/Alexa/alexa.py

**Comment by Aryanaut** [comment]
I'm still not able to get it working even after going into Keyword Observer code. Alexa works but the LED's don't turn on. I have checked all the connections to be secure. What could be the reason for it to not work?
