### ISSUE TITLE
MediaPlayer Failed to Create Audio Sink

### ISSUE THREAD

**Issue by changyp6** [alexa/avs-device-sdk#375]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      <1.2.1>
      
## Briefly summarize your issue:
Cross compile AVS SDK to AARCH64 Linux, and run SampleApp,
SampleApp always reports the following logs:

Running app with log level: DEBUG9
2017-12-04 09:39:40.262 [  1] I ConfigurationNode:initializeSuccess
2017-12-04 09:39:40.272 [  1] 9 MediaPlayer:createCalled
2017-12-04 09:39:40.319 [  1] E MediaPlayer:setupPipelineFailed:reason=createAudioSinkElementFailed
2017-12-04 09:39:40.319 [  1] E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed
2017-12-04 09:39:40.319 [  1] 9 MediaPlayer:~MediaPlayerCalled

(SampleApp:533): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(SampleApp:533): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
2017-12-04 09:39:40.320 [  1] 9 MediaPlayer:resetPipeline

(SampleApp:533): GLib-CRITICAL **: Source ID 2036430700 was not found when attempting to remove it
Failed to create media player for speech!
Failed to initialize SampleApplication
Failed to create to SampleApplication!

gst_element_factory_make("autoaudiosink", "audio_sink") always fail.
After changing "autoaudiosink" to "alsasink", everything works OK

## What is the expected behavior?
gst_element_factory_make("autoaudiosink", "audio_sink"), should work normally

## What behavior are you observing?
gst_element_factory_make("autoaudiosink", "audio_sink"), failed to create audio_sink

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
AARCH64 Cortex-a53 ARM CPU

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessie
- [x] Other - tell us more:
AARCH64 Linux, with alsa-1.1.4.1, pulseaudio-11.1, gstreamer 1.12.3
All these libraries are cross-compiled

**Comment by scotthea-amazon** [comment]
Hello changyp6,

When the creation of autoaudiosink fails it is often due to a failure to load a gstreamer library.

Have you included all of the gstreamer dependencies listed in the [MediaPlayer Reference Implementation Dependencies](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#mediaplayer-reference-implementation-dependencies) in your configuration?

If you have, you can also enable gstreamer logging using the [GST_DEBUG environment variable](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html).  That may help you pinpoint the source of the problem.

Please let us know if this helps,
-SWH

**Comment by avp24** [comment]
Hi @changyp6 , I am also trying to cross compile AVS SDK for Cortex-a53 ARM CPU. I have also cross compiled all the required libraries prior to cross compile AVS SDK and facing error in executing SampleApp. I am getting similar error like you.
 **E MediaPlayer:setupPipelineFailed:reason=createQueueElementFailed**
Can you tell me why I am getting this error? Also which files do I need to copy on board after cross compilation of AVS SDK & Gstreamer?
Thanks!

**Comment by avp24** [comment]
Hi @changyp6 , On executing SampleApp I observe these logs everytime. Do you have any idea for this?
**E MediaPlayer:setupPipelineFailed:reason=createQueueElementFailed**
**E MediaPlayer:initPlayerFailed:reason=setupPipelineFailed**
