### ISSUE TITLE
build settings for regular make file needed

### ISSUE THREAD

**Issue by kennykc** [alexa/avs-device-sdk#376]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What version of the AVS Device SDK are you using?
      <1.2.1>
      
## Briefly summarize your issue:

need build configuration to compile the SDK code under Eclipse or using regular make file, eg. the pre-processors, compiler options, link libraries...etc.
 
## Tell us about your environment:
ubuntu

### Tell us what hardware you're using:
- [ x] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ x] Raspbian Stretch
- [ ] Raspbian Jessie
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello kennykc,

The avs-device-sdk build is defined in CMake's syntax.  On Linux systems the default output of CMake is a set of directories and Makefiles such that you use make to compile and link the source.

We do not currently have any notes on using the avs-device-sdk with Eclipse.  With a little googling, I found what appears to be a promising link about [Using CMake and Eclipse for CMake enabled projects](https://cmake.org/Wiki/CMake:Eclipse_UNIX_Tutorial).

regards,
-SWH
