### ISSUE TITLE
Some Integration Test FAILED

### ISSUE THREAD

**Issue by sam-wen** [alexa/avs-device-sdk#377]
## What version of the AVS Device SDK are you using?
      <1.2.1>
      
## Briefly summarize your issue:
Hi AVS team,

I got some FAIL while running Integration Test.

2 in AlertIntegrationTest,
[  FAILED  ] AlertsTest.UserLongUnrelatedBargeInOnActiveTimer
[  FAILED  ] AlertsTest.UserSpeakingWhenAlertShouldBeActive
Failed Log as follows,
[AlertIntegrationTest-FAILED.log](https://github.com/alexa/avs-device-sdk/files/1538204/AlertIntegrationTest-FAILED.log)

1 in AlexaDirectiveSequencerLibraryTest
[  FAILED  ]AlexaDirectiveSequencerLibraryTest.oneBlockingDirectiveInTheMiddle
Failed Log as follows,
[AlertIntegrationTest-FAILED.log](https://github.com/alexa/avs-device-sdk/files/1538255/AlertIntegrationTest-FAILED.log)

1 in SpeechSynthesizerIntegrationTest
[  FAILED  ] SpeechSynthesizerTest.handleMultipleConsecutiveSpeaks
Failed Log as follows,
[SpeechSynthesizerTest-FAILED.log](https://github.com/alexa/avs-device-sdk/files/1538206/SpeechSynthesizerTest-FAILED.log)

Could you provide some suggestion ?
Thanks

**Comment by scotthea-amazon** [comment]
Hello sam-wen,

Unfortunately, the integration tests are not 100% reliable.  These tests interact with live services over unknown networking conditions, and some also interact with user specific settings.  Beyond that, some of our tests have been built such that they do not tolerate perfectly acceptable variations in the content and timing of replies from AVS.  All that said, we are actively working to make these test more reliable.

Thank you,
-SWH

**Comment by sam-wen** [comment]
Hi SWH
Thank you
I also take AudioPlayerIngetrationTest, playbackFinishedFound failed.
[AudioPlayerIntegrationTest-FAILED.log](https://github.com/alexa/avs-device-sdk/files/1541278/AudioPlayerIntegrationTest-FAILED.log)
Is it also not reliable result ?

**Comment by scotthea-amazon** [comment]
Hello sam-wen,

Yes, that test is also fragile.  Beyond the live service / unknown networking conditions / variation in content and timing, it invokes flash briefing whose content may be customized on a per user basis.

Best regards,
-SWH

**Comment by sam-wen** [comment]
Hi SWH,

Okay, thank you.
