### ISSUE TITLE
Invalid Configuration Causing SampleApp SegmentFault

### ISSUE THREAD

**Issue by changyp6** [alexa/avs-device-sdk#382]
SDK 1.3.0
    "alertsCapabilityAgent":{
         **"databaseFilePath":"/usr/share/avs/alexa.db",**
    }, 
If this single line json is ended with comma ',', SampleApp just crashes after reporting "Failed to parse configuration".

SampleApp should just report "Failed to parse configuration" without segment fault.

**Comment by scotthea-amazon** [comment]
Hello changyp6,

Thank you for bringing this to our attention!  We will look in to it.

-SWH

**Comment by kclchan** [comment]
We have found the root cause and will include a fix for this in our next software release.  Thanks for reporting it!
