### ISSUE TITLE
gstreamer plugin issue with the SampleApp

### ISSUE THREAD

**Issue by kennykc** [alexa/avs-device-sdk#390]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

can anyone point out the cause of the following issues. It looks gstreamer plugin related.

############################
#       Listening...       #
############################

###########################
#       Thinking...       #
###########################

(SampleApp:17110): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(SampleApp:17110): GLib-GObject-CRITICAL **: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(SampleApp:17110): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(SampleApp:17110): GLib-GObject-CRITICAL **: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
########################################
#       Alexa is currently idle!       #
########################################

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Hi @kennykc,

It's a bit hard to debug without additional information or logs. What version of the SDK are you using and can you give us some steps to reproduce what you've encountered? Is this leading to any sort of crash/undefined behavior or just some nasty log messages? Do you have all the GStreamer plugins that are required as listed [here](https://github.com/alexa/avs-device-sdk/wiki/Minimum-Requirements-and-Dependencies) installed? 

If possible, could you post additional logs in here leading up to those messages? One thing that might also help you see what may be happening is setting the environment variable `GST_DEBUG=[1,2,3,4, or 5]` to see GStreamer log messages.

Thanks,
Sanjay

**Comment by anu-mathur** [comment]
Hi @kennykc 
Can we talk more about your use case with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you.
Thanks

**Comment by mradulan** [comment]
@kennykc , does the issue still exist?
