### ISSUE TITLE
build SDK issue

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#393]
hi,
    I'am build the SDK using ubuntu 16.04 and I want to get the  executable file of SampleApp. When I excuted cmake command: cmake ../avs-device-sdk -DCMAKE_BUILD_TYPE=DEBUG -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH="/usr/local" -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=../PortAudio/portaudio/lib/.libs -DPORTAU    DIO_INCLUDE_DIR=../PortAudio/portaudio/include 

error information:  
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:28 (include)
  CMakeLists.txt:7 (include)

-- Configuring incomplete, errors occurred!

Note: GStreamer was installed from source and it's version is 1.10.4 . The installed path is /usr/local.

Please help me, thanks!

**Comment by sanjayrd** [comment]
Hi @xuewenxu,

Do you have another version of GStreamer also located in "/usr/local"? It's possible that the SDK CMake command is picking up a different version of GStreamer located there that doesn't meet the minimum version requirements.

Thanks,
Sanjay

**Comment by anu-mathur** [comment]
Hi @xuewenxu 

Can we talk more about your use case with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you.
Thanks

**Comment by mradulan** [comment]
@xuewenxu , if the issue is resolved, can you close the ticket?

**Comment by xuewenxu** [comment]
The issue is resolved,Thanks!   Sorry, I'm forget to close.

**Comment by kylecombes** [comment]
What was the solution to this problem?

**Comment by yoelrc88** [comment]
@xuewenxu Can you help here? I am having the same output as you did.

**Comment by yoelrc88** [comment]
Hey @kylecombes , making sure I installed gtreamer again solved my issue.
`sudo apt-get -y install  libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good`

**Comment by celinval** [comment]
Hi @kylecombes,

Can you double check if your gstreamer installation is ok? If you are still having problems, please create a new issue.

**Comment by kylecombes** [comment]
Hi @celinval and @yoelrc88,

Thanks for responding to my message. I'll pass this info along to the other person I was working with on this, but I'm not sure if he's still trying to fix it. I'll create another issue if we're still having problems.
