### ISSUE TITLE
Compilation error with GCC7

### ISSUE THREAD

**Issue by AlexVangelov** [alexa/avs-device-sdk#396]
Compilation failed with gcc7
> ...avs-device-sdk/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/Audio/AlertsAudioFactoryInterface.h:36:18: error: ‘function’ in namespace ‘std’ does not name a template type
     virtual std::function<std::unique_ptr<std::istream>()> alarmDefault() const = 0;

Please add `#include <functional>` in the .h file if pull request is not acceptable.
https://github.com/alexa/avs-device-sdk/pull/395

Thank you.

**Comment by sanjayrd** [comment]
Hi @AlexVangelov,

Thanks for pointing this out. We will include the fix in the next release.

Best,
Sanjay

**Comment by kclchan** [comment]
This is fixed in v1.4.0.  Thanks!

**Comment by sposelenov** [comment]
The same compilation error observed for NotificationsAudioFactoryInterface.h located in the same directory. Adding "#include <functional>" helps. Please fix.

Thanks!

Regards,
Sergei
