### ISSUE TITLE
where is  sound file that alexa responsed ?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#398]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

how coud i find the responsing soud file location?
## What is the expected behavior?

use other player to play sound file.
### What version of the AVS Device SDK are you using?
      <x.y.z>
AVS SDK 1.2.0
ubuntu 14.04 64bit
### Tell us what hardware you're using:
- [V ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [V ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ryan-esty** [comment]
@captainpanther the MediaPlayer in the SDK is using gstreamer to stream the file there is no actual file that is saved temporarily or anything of that nature.

**Comment by kjkh** [comment]
Hi @captainpanther,

As @ryan-esty mentioned, there are no saved files. Audio responses that come from AVS come as binary attachments. If you wish to use a separate player, you would need to create your own MediaPlayer implementation, although this is not a trivial task.

**Comment by kjkh** [comment]
Closing issue. If there are further questions please feel free to re-open.
