### ISSUE TITLE
why do the message 'connecting' in SampleApp ?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#405]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When i run ./SampleApp ../../Integration/AlexaClient.json
it enter the  keyword console ,after meet "press t "... "press h" .
Then it show message 'connecting'  ,'connecting' 

## What is the expected behavior?

It should not be show  'connecting'
## What behavior are you observing?

connecting message is always
## Provide the steps to reproduce the issue, if applicable:

./SampleApp ../../Integration/AlexaClient.json
## Tell us about your environment:
ubuntu 14.04 bit 

### What version of the AVS Device SDK are you using?
      AVS <1.2.0>

### Tell us what hardware you're using:
- [V ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ V] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @captainpanther,

Can you collect debug logs by building the SampleApp in DEBUG mode and running it with DEBUG9?

**Comment by frozenberg** [comment]
Hi @captainpanther,

It's been a while since you last responded. If you want to respond with some debug logs feel free to reopen this issue.

Fede
