### ISSUE TITLE
Play Amazon Music has gstreamers error when resume after stop

### ISSUE THREAD

**Issue by xiaow6** [alexa/avs-device-sdk#407]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
For some songs, if I stop it and resume it, it will pop up this error, also if I pause then play it. Not happens for every song, just some songs so you might not see it

## What is the expected behavior?
Alexa play, Alexa stop, Alexa resume, should reume 

## What behavior are you observing?
 sometimes it can't resume, sometimes it jump to next song 

## Provide the steps to reproduce the issue, if applicable:
 Alexa play music, Alexa stop, Alexa resume. You have to try to find a song has this issue

## Tell us about your environment:
 Include as many relevant details about the environment you experienced the bug in 
### What version of the AVS Device SDK are you using?
Latest version SDK
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ x] Other - tell us more: Openwrt based Linux. ARM A53.

Repeating logs:
(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed
2017-12-21 19:59:21.916 [  a] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 0ab540fffed3ec6a-00001019-00063a58-ebb805168588731d-303e250d-105
2017-12-21 19:59:21.916 [  a] 0 HTTP2Transport:cleanupFinishedStream:streamId=105,result=204
2017-12-21 19:59:21.916 [  a] 0 HTTP2StreamPool:releaseStream:streamId=105,numAcquiredStreams=1
2017-12-21 19:59:21.916 [  a] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2017-12-21 19:59:21.916 [  a] 0 HTTP2Transport:processNextOutgoingMessage
2017-12-21 19:59:21.916 [  a] 0 HTTP2StreamPool:getStream:streamId=107,numAcquiredStreams=2
2017-12-21 19:59:21.917 [  a] 9 HTTP2Transport:insertActiveStream:handle=0x3423d8a8

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

(SampleApp:1668): GStreamer-CRITICAL **: gst_segment_to_stream_time: assertion 'segment->format == format' failed

**Comment by xiaow6** [comment]
Based on my test, even the same song, once you say stop then resume, it has this log sometimes and then stop and resume again, there is no error log.  So I think this is a bug. 
I put all log here. 
[Gstreamer.txt](https://github.com/alexa/avs-device-sdk/files/1580478/Gstreamer.txt)

**Comment by kjkh** [comment]
Hi @xiaow6,

Which version of GStreamer are you using?

**Comment by xiaow6** [comment]
@kjkh 1.10.4

**Comment by mradulan** [comment]
The logs do show that the databaseFilePath for settings and certifiedSender have not been written in the AlexaClientSDKConfig.json

**Comment by frozenberg** [comment]
Hi @xiaow6,

What version of the SDK are you running? 

Fede

**Comment by sanjayrd** [comment]
Hi @xiaow6,

This was an issue with a previous version of our SDK that has been resolved in newer versions. Closing this issue to to inactivity, but please reopen if you're still seeing issues.

Thanks,
Sanjay
