### ISSUE TITLE
Which file to decide that  use  the BaseStreamSource.cpp  or  UrlSource.cpp???

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#408]
in AVS Device SDK,

in source code, i just see the MediaPlayerInterface  own BaseStreamSource.cpp  and UrlSource.cpp two types source.

But  Can i know that which source code to decide that use BaseStreamSource.cpp  or UrlSource.cpp??

**Comment by kjkh** [comment]
Hi @captainpanther,

There are actually three different source classes:

- AttachmentReaderSource : BaseStreamSource
- IStreamSource : BaseStreamSource
- UrlSource

UrlSource is deprecated and will mostly likely be removed in a future release. It's not currently used anywhere. Its purpose has been replaced by a combination of the AttachmentReaderSource and HTTP content retrieval classes.

However, those should not be confused with the sources that MediaPlayer supports. The MediaPlayerInterface (and our implementation) currently support three different sources:

- SourceId setSource(std::shared_ptr<avsCommon::avs::attachment::AttachmentReader> attachmentReader);
- SourceId setSource(std::shared_ptr<std::istream> stream, bool repeat);
- SourceId setSource(const std::string& url, std::chrono::milliseconds offset = std::chrono::milliseconds::zero());

Hope this helps.

**Comment by captainpanther** [comment]
Thank ur reply, but i want to know which file  decide to use  BaseStreamSource.cpp or UrlSource.cpp in source code project. 
is MediaPlayerInterface ?

**Comment by mradulan** [comment]
BaseStreamSource.cpp
