### ISSUE TITLE
how to force all response sounds that use  Uridecodebin in UrlSource?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#409]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

detain issu in https://github.com/alexa/avs-device-sdk/issues/406
when response sound use decodebin  by BaseStreamSource , my arm embedd system can't play it sound but the player's progress seem has been running
## What is the expected behavior?

the response sound of BaseStreamSource that should be played
## What behavior are you observing?

the response sound of BaseStreamSource can't play sound 
## Provide the steps to reproduce the issue, if applicable:

TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json 
## Tell us about your environment:
NXP in yocto

### What version of the AVS Device SDK are you using?
   AVS  Device SDK <1.2.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [V ] Other - NXP in yocto
### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ V] Other - NXP in yocto

**Comment by mradulan** [comment]
can you try SDK 1.3 if it works for you?

**Comment by captainpanther** [comment]
Ok, the issue is not my now issue.Thank

**Comment by mradulan** [comment]
if it is resolved, please close the ticket.

**Comment by kclchan** [comment]
Closing issue as it doesn't seem to be an issue anymore.  Please re-open if it's not the case.  Thanks!
