### ISSUE TITLE
Can't to found "Active Listening" status in SDKv1.3

### ISSUE THREAD

**Issue by CarlosHua** [alexa/avs-device-sdk#411]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We in order to implement [UX Attention System](https://developer.amazon.com/docs/alexa-voice-service/ux-design-attention.html), but  didn't to found "Active Listening" status in SDK. Please refer the [DialogUXStateObserverInterface.h](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/DialogUXStateObserverInterface.h). 
Please advise how to identify this status ? Thanks.
### What version of the AVS Device SDK are you using?
      <1.3.0>

### Tell us about your OS (Type & version):
- [x] Linux - embedded

**Comment by mradulan** [comment]
Hi @CarlosHua , thank you for bringing this to our attention. We will check if we need to add it for the Attention System.

**Comment by sanjayrd** [comment]
Hi @CarlosHua,

This is something you will need to implement on your end if you have an Audio Front End system that is capable of `Voice Activity Detection`. Essentially, if your hardware can pick up on whether a customer is currently making an utterance (as opposed to silence), then you can display some sort of Active Listening message or voice chrome.

Thanks,
Sanjay

**Comment by CarlosHua** [comment]
Hi @sanjayrd,
Thanks for your reply. 
So "Active Listening" and "Stop Listening" status should be decided by hardware.

**Comment by sanjayrd** [comment]
Hi @CarlosHua,

Yes, that's correct.

Thanks,
Sanjay

**Comment by sanjayrd** [comment]
Hi @CarlosHua,

I just wanted to also add that this can also be done by the wake word engine and not necessarily the hardware if you are working with a wake word engine that supports voice activity detection.

Thanks,
Sanjay
