### ISSUE TITLE
.db file doesn't create in the build directory??

### ISSUE THREAD

**Issue by kiruthi95** [alexa/avs-device-sdk#412]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

After cmake no .db file has been created?? .. then how to give path for .json file

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kiruthi95** [comment]
After cmake no .db file has been created?? .. then how to give path for .json file

**Comment by kiruthi95** [comment]
kiruthika@kiruthika-VirtualBox:~/avs_sdk/build1/SampleApp/src$ TZ=UTC ./SampleApp ./AlexaClientSDKConfig.json   DEBUG9
Failed to initialize SDK!
Failed to initialize SampleApplication
Failed to create to SampleApplication!
Anyone please help me to resolve this issue??

**Comment by skyfall1970** [comment]
it should grow .db  after run ./SampleApp.
in AlexaClientSDKConfig.json setting, u should be sure  that all folders  are existing.
