### ISSUE TITLE
In SpeechSynthesizer , how to make  AttachmentReader be a mp3/wave  local file?

### ISSUE THREAD

**Issue by captainpanther** [alexa/avs-device-sdk#414]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

make speech AttachmentReader be a local sound file
## What is the expected behavior?

save a local file and can be played
## Tell us about your environment:

ubuntu 14.04 64bit
### What version of the AVS Device SDK are you using?
    AVS  <1.2.0>

### Tell us what hardware you're using:
- [V ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [V ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mradulan** [comment]
You want to play a local file instead of a voice command to Alexa right? SpeechSynthesizerIntegrationTest.cpp does that by sending "recognize_whats_up_test.wav". Check the  function setupMessageWithAttachmentAndSend at line 414 to see how local file is used to send to AVS.

**Comment by anu-mathur** [comment]
Hi @captainpanther 
Can we talk more about your use case with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you.
Thanks

**Comment by mradulan** [comment]
@captainpanther , check if the solution worked.

**Comment by captainpanther** [comment]
i have been fillouted the contact form

2017-12-28 6:05 GMT+08:00 Mradula Nayak <notifications@github.com>:

**Comment by mradulan** [comment]
@captainpanther , if the issue is resolved, please close the ticket. Thanks!
