### ISSUE TITLE
How to play attention system of sounds when AVS in streaming status ?

### ISSUE THREAD

**Issue by CarlosHua** [alexa/avs-device-sdk#415]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How to play [attention system of sounds](https://developer.amazon.com/docs/alexa-voice-service/ux-design-attention.html) when AVS in streaming status ? 

## What behavior are you observing?

In order to play the notify voice at "Stop Listening", If I using aplay by system call, I will got the "audio open error: Device or resource busy" error msg when AVS in streaming on iHR. I think it caused by AVS AudioPlay in using now, so have any recommend on it ?  or have any better way to integrate these notify voice with AVS AudioPlay. Please help to advise. Thanks.

### What version of the AVS Device SDK are you using?
      <1.3.0>

### Tell us what hardware you're using:
- [X] Other - tell us more:
Cross compile on embedded

### Tell us about your OS (Type & version):
- [x] Linux

In addition, regarding Active Listening/Stop Listening definition on UX Attention System document, the [DialogUXStateObserverInterface.h](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/DialogUXStateObserverInterface.h) not define in the head file, how do I identify these specify status ? Thanks.

**Comment by mradulan** [comment]
Hi @CarlosHua , we can understand the issue better if you can paste debug logs by running SampleApp with DEBUG9 option. Play iHR in the SampleApp and play notify voice at "Stop Listening".

**Comment by CarlosHua** [comment]
Hi @mradulan,
Provide log with DEBUG9 option,
[aplay_error.log](https://github.com/alexa/avs-device-sdk/files/1590884/aplay_error.log)

You can see that at line 195, 
It's first "Listening" states, so aplay tool can play the /jffs/ful_ui_wakesound.wav attention sound successfully, because AVS no streaming any source for now.

After I said "Alexa, play some music" requisition, so AVS play the music now.
You can see line 798,1162 when I trigger Alexa, then AVS would change to "Listening" status, at this time, aplay can not play the /jffs/ful_ui_wakesound.wav now since got error msg "aplay: main:722: audio open error: Device or resource busy" which is AVS AudioPlayer at following stats,
    
   ##### 2017-12-28 08:22:34.685 [  9] 0 DirectiveProcessor:scrubDialogRequestIdLocked:dialogRequestId=d853e690-b360-4e75-af2d-5cc4a7990576
   ##### 2017-12-28 08:22:34.682 [  8] 1 AudioPlayer:executeOnFocusChanged:from=FOREGROUND,to=BACKGROUND,m_currentActivity=PLAYING
   ##### 2017-12-28 08:22:34.687 [  8] 1 AudioPlayer:executeOnFocusChanged:action=pauseMediaPlayer

If I say "Alexa, stop the music". then say Alexa again, the attention sound can be play very well.
Thanks.

**Comment by kclchan** [comment]
Closing issue.
