### ISSUE TITLE
Sample App Failed to create default SDK Client

### ISSUE THREAD

**Issue by vsthirunavukkarasu** [alexa/avs-device-sdk#416]
## Brief of my issue:
I success fully builded avs-device-sdk in my Target Board,
But i'm getting below errors while running the Sampleapp Executable
I'm using below command to run SampleApp
**TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json ../../Integration/inputs/SensoryModels/ DEBUG9**

and I'm Getting below errors,

**Running app with log level: DEBUG9
2017-12-26 09:51:59.868 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuld with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2017-12-26 09:51:59.870 [  1] I ConfigurationNode:initializeSuccess
2017-12-26 09:52:00.004 [  1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
2017-12-26 09:52:00.005 [  1] E Settings:initializeFailed:reason=SqliteFilePathNotFound
2017-12-26 09:52:00.005 [  1] E Settings:createFailed:reason=Initialization error.
2017-12-26 09:52:00.006 [  1] E DefaultClient:initializeFailed:reason=unableToCreateSettingsObject
2017-12-26 09:52:00.006 [  1] I DirectiveSequencer:doShutdown
2017-12-26 09:52:00.008 [  2] I CertifiedSender:CertifiedSender worker thread done.  exiting mainloop.
Failed to create default SDK client!
Failed to initialize SampleApplication
Failed to create to SampleApplication!**

### Tell us what hardware you're using:
**--PICO-PI-IMX7d**

### Tell us about your OS (Type & version):
**- -Yocto Based Linux**

Anyone please help me to solve this issue.

**Comment by vsthirunavukkarasu** [comment]
And my AlexaClientSDKConfig.json file is looking like below,

{
    "authDelegate":{
        "clientSecret":"my_secret_id",
        "deviceSerialNumber":"123456",

"refreshToken":"Atzr|IwEBIOq8KuoikJyEscxrvQlW2ELvwW2coV9yIXlub-54Fw6szXBVJmMB-X5-U589hP0eZ9e8HtLNWpQOPkNKNKHHdtwnKoxA5mjbbQIo7GoSzcdXihh81RpZ1X0ycczvE_tr50bbwC1BmtUQy0R9Od6STQVnZFt4PJW$
        "clientId":"my_Client_Id",
        "productId":"rpiEcho"
     },

   "alertsCapabilityAgent":{
        "databaseFilePath":"/home/root/build_db/alerts.db",
        "alarmSoundFilePath":"/home/root/alexa_sound/med_system_alerts_alarming_03.mp3",
        "alarmShortSoundFilePath":"/home/root/alexa_sound/med_system_alerts_alarming_03_short.wav",
        "timerSoundFilePath":"/home/root/alexa_sound/med_system_alerts_melodic_03.mp3",
        "timerShortSoundFilePath":"/home/root/alexa_sound/med_system_alerts_melodic_03_short.wav"
   },

   "settings":{
        "databaseFilePath":"",
        "defaultAVSClientSettings":{
            "locale":"en-US"
          }
    },

   "certifiedSender":{
        "databaseFilePath":"/home/root/build_db/alerts.db"
    }
 }

**Comment by mradulan** [comment]
The databaseFilePath for settings is empty. It should be different than alerts db file. Something like "/home/root/build_db/settings.db". Also the databaseFilePath for certifiedSender should be different, which is like "/home/root/build_db/certifiedSender.db" .

**Comment by vsthirunavukkarasu** [comment]
Hi,
Thank you. I got cleared that issues with your help.
And now i'm getting below error.

2017-12-27 06:06:54.589 [  1] I ConfigurationNode:initializeSuccess
2017-12-27 06:06:54.803 [  1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
2017-12-27 06:06:54.807 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x71a748,policy=BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x71b010,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x71b010,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x71b010,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x719fc8,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x719fc8,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x71bca0,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x71bca0,policy=NON_BLOCKING
2017-12-27 06:06:54.808 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x743768,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x719da4,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x742c90,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x742c90,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetVolume,handler=0x742c90,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderPlayerInfo,handler=0x742fc8,policy=NON_BLOCKING
2017-12-27 06:06:54.809 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderTemplate,handler=0x742fc8,policy=NON_BLOCKING
#############################
#       Connecting...       #
#############################

2017-12-27 06:07:01.819 [  2] I DirectiveSequencer:onDirective:directive={"namespace\:"System"\,name\:"SetEndpoint"\,messageId\:"f130fda3-9e2e-43b7-a900-8812edeadf62"\,dialogRequestId\:""}
2017-12-27 06:07:01.820 [  3] I DirectiveRouter:preHandleDirective:messageId=f130fda3-9e2e-43b7-a900-8812edeadf62,action=calling
2017-12-27 06:07:01.820 [  4] I DirectiveRouter:handleDirective:messageId=f130fda3-9e2e-43b7-a900-8812edeadf62,action=calling
########################################
#       Alexa is currently idle!       #
########################################

**#####################################
#       Client not connected!       #
#####################################**

########################################
#       Alexa is currently idle!       #
########################################

ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline**#####################################
#       Client not connected!       #
#####################################**
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-poky-linux-gnueabi/alsa-plugins/1.0.29-r0/alsa-plugins-1.0.29/pulse/pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-poky-linux-gnueabi/alsa-plugins/1.0.29-r0/alsa-plugins-1.0.29/pulse/pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream**#####################################
#       Client not connected!       #
#####################################**
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dmix.c:977:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
ALSA lib /home/jiserver/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-vfp-neon-mx7d-poky-linux-gnueabi/alsa-lib/1.0.29-r0/alsa-lib-1.0.29/src/pcm/pcm_dsnoop.c:553:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
2017-12-27 06:07:07.566 [  1] I SensoryKeywordDetector:License expires on 28 Mar 2018 00:00:00 GMT
2017-12-27 06:07:07.566 [  1] I SensoryKeywordDetector:Sensory library license does not expire for at least 60 more days.
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+


So The issue is ,
**#####################################
#       Client not connected!       #
#####################################**

**Comment by mradulan** [comment]
do you have gstreamer1.0-alsa installed on your system? can you try
`sudo apt install gstreamer1.0-alsa`

Also verify you have basic functionality (you should hear a constant tone):
`$ gst-launch-0.10 audiotestsrc ! autoaudiosink`

verify you can play mp3 (using mad decoder from gstreamer1.0-plugins-ugly):
`$ gst-launch-1.0 filesrc location=${HOME}/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02.TTH.mp3 ! mpegaudioparse ! mad! autoaudiosink`

**Comment by vsthirunavukkarasu** [comment]
Hi,
I am using yocto image, and i dont have **apt** to install the packages.
But i have native compiler with image and i tried compiling sources but getting lot of dependency issues.
Is there any way to upgrade the gstreamer-1.0 - 1.10.4 version in yocto sources?

Thanks & regards,
Thiru.

**Comment by mradulan** [comment]
@vsthirunavukkarasu , have you tried the smart project management system of yocto? https://community.nxp.com/docs/DOC-328199

Also what about the basic functionality testing? 
`$ gst-launch-0.10 audiotestsrc ! autoaudiosink`

And playing of mp3
`$ gst-launch-1.0 filesrc location=${HOME}/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02.TTH.mp3 ! mpegaudioparse ! mad! autoaudiosink`

**Comment by vsthirunavukkarasu** [comment]
@mradulan,
Thank you so much for your valuable answer,
i run  **gst-launch-1.0** command and i got below msg.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...

====== BEEP: 4.0.9 build on Dec 27 2017 15:29:51. ======
	Core: MP3 decoder Wrapper  build on Mar 21 2014 15:04:50
 file: /usr/lib/imx-mm/audio-codec/wrap/lib_mp3d_wrap_arm12_elinux.so.3
CODEC: BLN_MAD-MMCODECS_MP3D_ARM_02.13.00_CORTEX-A8  build on Apr 10 2014 15:26:15.
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstAudioSinkClock
Got EOS from element "pipeline0".
Execution ended after 0:00:06.848453419
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**And the mp3 file is playing perfectly.**,

But i'm getting below response from AVS,
After listening mode it is **going to idle,** 
**Speaking mode is not working** 

###########################
#       Thinking...       #
###########################

2017-12-29 09:02:28.967 [  6] I InProcessAttachmentReader:readFailed:reason=SDS is closed
########################################
#       Alexa is currently idle!       #
########################################

If you have any solution kindly share to me.

Thanks & Regards,
Thiru.

**Comment by mradulan** [comment]
if the playing of mp3 is working perfectly, there are no gstreamer issues. What questions are you trying for it to go to IDLE mode from THINKING mode. Can you try some questions like:
1. What's the weather outside?
2. Tell me a joke.
3. Wikipedia. Lions.

**Comment by vsthirunavukkarasu** [comment]
@mradulan,
I Tried all questions, But there is no response, it not even entered into SPEAKING mode.
After THINKING it's went to **Alexa is currently idle!**.
any solutions?

**Comment by kclchan** [comment]
Hi @vsthirunavukkarasu, in order to investigate further, would you be able to attach the DEBUG9 logs.

You can enable DEBUG9 by running cmake with -DCMAKE_BUILD_TYPE=DEBUG and enabling DEBUG9 mode with $TZ=UTC ./SampleApp DEBUG9
Please capture the entire log and attach the file.

**Comment by vsthirunavukkarasu** [comment]
Hi,
Please find the logfile in attachment.
i tried all below questions,
 1.   What's the weather outside?
 2.  Tell me a joke.
 3.  Wikipedia. Lions.

[logFile.txt](https://github.com/alexa/avs-device-sdk/files/1605606/logFile.txt)

**Comment by vsthirunavukkarasu** [comment]
Hi @mradulan,
Actually i'm using gstreamer version 1.6 not yet upgraded.
i think bcoz of that only issue.
Is there any way to upgarde gstreamer in yocto based system.
my yocto version is **Jethro 4.1.15** which is Gstreamer 1.6 is max version.
Do you have any way to upgrade gstreamer version ?

**Comment by vsthirunavukkarasu** [comment]
Hi @mradulan ,
I upgraded to gstreamer 1.10.4 and all its plugins
Now i builded AVS and I got the same issue.

**gst-launch-1.0 filesrc location=${HOME}/sdk-folder/application-necessities/sound-files/med_system_alerts_melodic_02.TTH.mp3 ! mpegaudioparse ! mad! autoaudiosink**

while running above command, I'm Getting below log.

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPipeline:pipeline0/GstMpegAudioParse:mpegaudioparse0: Internal data stream error.
Additional debug info:
gstbaseparse.c(3608): gst_base_parse_loop (): /GstPipeline:pipeline0/GstMpegAudioParse:mpegaudioparse0:
streaming stopped, reason not-negotiated (-4)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

Any Solutions?

**Comment by kclchan** [comment]
Hi @vsthirunavukkarasu, maybe try with something more simple and see if you can hear a constant tone:
gst-launch-1.0 audiotestsrc ! autoaudiosink

Can you try running your cmake again with -DCMAKE_BUILD_TYPE=DEBUG option and rebuild the SampleApp again and running it with DEBUG9? This would enable more information in the log.

From the log you attach, it seems that AVS doesn't understand your intent.  Could you look into your dialog history:
https://alexa.amazon.com/spa/index.html#settings/dialogs

and see if it's understanding what you are saying?

**Comment by vsthirunavukkarasu** [comment]
HI @kclchan ,
Enabled Detailed log. Please find the log file in attachment.
And in Dialog History containing all asked questions, its updating as well.
When i try to play some Tunein Radio station, i'm getting below msg,
**your alexa device is currently offline, Please plug in your Alexa device And ensure it is properly connected to WiFi** 
But AVS Code is running it is in connected state. All Histories are coming.

[detailedLogAVS.txt](https://github.com/alexa/avs-device-sdk/files/1608543/detailedLogAVS.txt)

Kindly help me to solve the issue.

**Comment by vsthirunavukkarasu** [comment]
Hi @kclchan ,
Still it is not entering into Speaking mode from Thinking mode.

**Comment by BennyAvramson** [comment]
Hi @vsthirunavukkarasu, 

1. Have you tried running `gst-launch-1.0 audiotestsrc ! autoaudiosink`? If so, what were the results?

2. For the offline message you mentioned, I'm assuming the message was presented on the Alexa website. In that case, make sure you're logged in to the website with the same account you have authenticated the SampleApp

**Comment by frozenberg** [comment]
Hi @vsthirunavukkarasu,

Let us know if you have any more information or if you were able to use the above guidance towards any success.

Fede
