### ISSUE TITLE
Compile with buildroot

### ISSUE THREAD

**Issue by rueichang** [alexa/avs-device-sdk#417]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I want to put avs sdk in buildroot and compile it. But everything not smooth.

## What is the expected behavior?

Compile a SampleApp that we could said Alexa to it and get properly response from AVS.

## What behavior are you observing?

Compile error....

=========compile error message======
S=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON  -DLIBRARY_OUTPUT_PATH=/home/ruei/tmpgit/RK3229BSP/buildroot/board/rockchip/rk322x/fs-overlay/usr/lib -DEXECUTABLE_OUTPUT_PATH=/home/ruei/tmpgit/RK3229BSP/buildroot/board/rockchip/rk322x/fs-overlay/usr/bin )
-- The CXX compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /home/ruei/tmpgit/RK3229BSP/buildroot/output/host/usr/bin/arm-rockchip-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/ruei/tmpgit/RK3229BSP/buildroot/output/host/usr/bin/arm-rockchip-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

=========================================================
 ERROR:                                                                      
AlexaClientSDK must not be built in the AlexaClientSDK source directory.    
                                                                             
 You must run cmake in a separate build directory completely outside the     
 the source directory.                                                       
                                                                             
 Source Directory:                                                           
     /home/ruei/tmpgit/RK3229BSP/buildroot/output/build/avsdevicesdk         
 Build Directory:                                                            
     /home/ruei/tmpgit/RK3229BSP/buildroot/output/build/avsdevicesdk         
                                                                             
 NOTE:                                                                       
 Since you have tried to create an in-source build already, CMake may have   
 created some files and directories in the source tree. To find these files, 
 run:                                                                        
     $ git status                                                            
                                                                             
 To remove these files, simply use 'rm' on the appropriate files and         
 directories.                                                                
                                                                             
=================================================================
Make Error at build/cmake/DisallowOutOfSourceBuilds.cmake:59 (message):
  In-source-build detected, quitting!
Call Stack (most recent call first):
  build/cmake/DisallowOutOfSourceBuilds.cmake:63 (DisallowOutOfSourceBuilds)
  build/BuildDefaults.cmake:7 (include)
  CMakeLists.txt:7 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ruei/tmpgit/RK3229BSP/buildroot/output/build/avsdevicesdk/CMakeFiles/CMakeOutput.log".
package/pkg-generic.mk:191: recipe for target '/home/ruei/tmpgit/RK3229BSP/buildroot/output/build/avsdevicesdk/.stamp_configured' failed
make[2]: *** [/home/ruei/tmpgit/RK3229BSP/buildroot/output/build/avsdevicesdk/.stamp_configured] Error 1
Makefile:41: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/ruei/tmpgit/RK3229BSP/buildroot'
/home/ruei/tmpgit/RK3229BSP/device/rockchip/rk322x//make.mk:18: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

=======================

## Tell us about your environment:

GCC version 4.9.x
GStreamer 1.12.2

### What version of the AVS Device SDK are you using?
      <x.y.z> v1.3.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more: rockchip rk3229

### Tell us about your OS (Type & version):
- [ * ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

close

**Comment by mradulan** [comment]
any reason why you are compiling in the same directory as source? The SDK compilation needs to be in a separate build directory.

**Comment by rueichang** [comment]
@mradulan  Thank you for your reply. I'm sorry, it's my first to compile the SDK.  Did you mean there is a SDK folder in avs-device-sdk?  So, I need to separate and build it, right? 

And I just start learning cmake. I thought I could compile it cuz  there is a CMakeLists.txt under avs-device-sdk.

**Comment by mradulan** [comment]
if avs-cpp-sdk is the source folder, create a separate 'Build' folder outside of it and run the Cmake command from build folder.
[This](https://github.com/alexa/avs-device-sdk/wiki/Linux-Quick-Start-Guide#create-an-out-of-source-build) step specifically tells to create a out of source build.

**Comment by rueichang** [comment]
@mradulan  OK, thank you so much.I hope I could understand about how buildroot works. Otherwise, I will meet more issue at this.

**Comment by mradulan** [comment]
@rueichang , let me know if you are able to compile it. If so, please close the ticket. Thanks!

**Comment by rueichang** [comment]
close

**Comment by xuewenxu** [comment]
@rueichang , I have the same problem as you,  have you soved it ?  Please tell me how to do!  Thanks

**Comment by rueichang** [comment]
@xuewenxu Hello there, we had installed all the libraries that SampleAPP needs to solve our problem.

Maybe you could refer the following link: https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide#setup

Please ensure all instructions of Setup are completed. Hope your problem can be fixed soon.

**Comment by xuewenxu** [comment]
@rueichang  Thanks your reply!
