### ISSUE TITLE
Question about the device serial number displayed on APP

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#425]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
On Alexa APP or Settings Web site, there is a tag named : Serial number
It seems its a random number (or hashed string ?) by device.
I would like to know how this serial number will be generated ? 

## What is the expected behavior?
I would like to know the format of the serial number and would like to control the data for our products.

## Provide the steps to reproduce the issue, if applicable:
Installed a Alexa and check the serial number on APP.

### What version of the AVS Device SDK are you using?
      1.3.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ X] Other - tell us more: ARM based embedded system

### Tell us about your OS (Type & version):
- [X ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mradulan** [comment]
the serial number is an alphanumeric number of length 32 generated by AVS.

**Comment by zeusshuang** [comment]
Hi @mradulan ,
 
thanks for the comment, so it's generated from AVS SDK, and I could find it in the source code ?

**Comment by mradulan** [comment]
no its is generated by Alexa Voice Service i.e. cloud. SDK does not generate the serial number.

**Comment by zeusshuang** [comment]
Hi @mradulan ,
 
is there any way I can get this serial number from the cloud, so that we could save it in local device for further trouble shooting or identification purpose ?

**Comment by mradulan** [comment]
there are no events or directive using which you can this number

**Comment by zeusshuang** [comment]
Hi Mradula,

Thanks for the confirmation. We can close this case.

2017-12-30 7:05 GMT+08:00 Mradula Nayak <notifications@github.com>:
