### ISSUE TITLE
APP display "Your Alexa device is not connected" but it's actually running locally

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#428]
## Briefly summarize your issue:
APP display "Your Alexa device is not connected" but it's actually running locally.

From Alexa APP or website : https://pitangui.amazon.com/spa/index.html
It can display the current Alexa status, from my test, it's running Amazon Prime Music or iHeartRadio
However, somehow it become "Your Alexa device is not connected" with a WiFi disconnect icon,
but it's actually playing and can play next song if it's playing Prime Music.
From the log, it ever dump the "setupDownchannelStream ..." and into "Connecting..." state.
During the period, I could make sure the WiFi is working due to we monitor the ping status.

I have two questions here ,
(1) which situation that the Downchannel will try to reconnect ?  
(2) why APP show incorrect information while the Alexa device is actually running.
For (2), during our evaluation these weeks, we never see such behavior with Amazon Echo(v1) on same test. (we often run it overnight or over weekend for long term Music test)

## What is the expected behavior?
It should respond correct Alexa device status if the connecting reset.

## What behavior are you observing?
Please see my description in issue summery.

## Provide the steps to reproduce the issue, if applicable:
Please see my description in issue summery.

### What version of the AVS Device SDK are you using?
      1.3.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X ] Other - tell us more: ARM based embedded Linux system

### Tell us about your OS (Type & version):
- [X ] Linux
- [ ] MacOS
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @zeusshuang, the device would try to reconnect the down-channel whenever it is closed.  And thanks for bringing this issue to our attention, we will look into it and get back to you asap.  One more question, if you press "refresh" on your browser, does it show the correct status again?

**Comment by zeusshuang** [comment]
Hi @kclchan ,

Thanks for the feedback, and yes, it will show the correct "now playing" list again after press "refresh" key.
While it display "Your Alexa device is not connected" on APP or website page, the music is still playing, and it will play the next song correctly.

**Comment by kclchan** [comment]
Hi @zeusshuang, thanks for confirming the behavior.  We will look into it and update you asap.  Thanks!

**Comment by scotthea-amazon** [comment]
Hi @zeusshuang,

It is possible for the SDK to be trying to reconnect to AVS while music is playing - because they rely on different endpoints.  If the SDK is not connect to AVS (in which case it will be trying to reconnect AVS) the device is expected to show up as offline.

I just tried this recently with SDK 1.10 and with alexa.amazon.com, and it looks like the page is refreshing the offline/online state fairly quickly and without a manual refresh.

Are you still observing a problem in this area?

Thank you,
-SWH

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

I will try it with SDK 1.10 and feedback asap.

**Comment by kjkh** [comment]
Hi @zeusshuang,

Are you still experiencing this issue with the latest version of the SDK?

**Comment by zeusshuang** [comment]
We can close this case.
