### ISSUE TITLE
issues while performing cmake

### ISSUE THREAD

**Issue by surajhes** [alexa/avs-device-sdk#43]
HI i was trying to perform cmake in the new build directory and following the steps to make a generic Linux Build and i am trying with KItt.ai model. While performing the cmake i am getting following error inspite of providing correct parameters for Kitt.ai Following is the error i am getting

Creating the build directory for the AlexaClientSDK with build type: DEBUG
Creating AlexaClientSDK with keyword detector type: KittAi
CMake Error at /usr/local/share/cmake-3.9/Modules/GoogleTest.cmake:127 (if):
  if given arguments:

    "AlexaClientSDKInitTest" "IN_LIST" "allKeywords"

  Unknown arguments specified
Call Stack (most recent call first):
  tools/Testing.cmake:22 (GTEST_ADD_TESTS)
  AVSCommon/AVS/test/CMakeLists.txt:2 (discover_unit_tests)

-- Configuring incomplete, errors occurred!

**Comment by DEW916** [comment]
Hi @sanjayrd , 
While performing Build the SDK task and after entering below mentioned command I am getting errors.Please help me regarding this,
**cd /home/pi/sdk-folder/sdk-build
cmake /home/pi/sdk-folder/sdk-source/avs-device-sdk \
-DSENSORY_KEY_WORD_DETECTOR=ON \
-DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/sdk-folder/third-party/alexa-rpi/lib/libsnsr.a \
-DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/sdk-folder/third-party/alexa-rpi/include \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DPORTAUDIO=ON \
-DPORTAUDIO_LIB_PATH=/home/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=/home/pi/sdk-folder/third-party/portaudio/include**
 
**ERROR:**

Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.52.1") 
CMake Error at AVSCommon/AVS/test/CMakeLists.txt:6 (discover_unit_tests):
  Unknown CMake command "discover_unit_tests".

-- Configuring incomplete, errors occurred!
See also "/home/pi/sdk-folder/sdk-build/CMakeFiles/CMakeOutput.log".
