### ISSUE TITLE
Capture & Playback at 48 kHz stereo

### ISSUE THREAD

**Issue by az2022** [alexa/avs-device-sdk#434]
Hi,
I am using a modified version of Raspbian and am trying to source audio from MIC & playback audio at 48 kHz in stereo mode. Am using SDK version 1.3.0. Everything works fine with the default AVS SDK 1.3.0. SDK seems to be setting MIC sampling at 16 kHz mono (my understanding based on macros in SampleApplication.cpp & PortAudioWrapper.cpp), everything works at this default setting but when I change either number of channels from 1 to 2 and/or sampling from 16 kHz to 48 kHz, nothing works. I do not Sensory and use "TAP" option to send query commands to AVS. 

- Do I need to do anything more to bump up the rate & receive stereo instead of mono from MIC (or ALSA I guess)?
- What rate does AVS playback speech and audio? Can this be changed to always receive 48 kHz from the cloud? If not, what options do I have to playback at 48 kHz?
- Why are there multiple macros for Number-of-channels and Sampling rate (SampleApplication.cpp & PortAudioWrapper.cpp)

PS: Although using image based on Raspbian I have a slightly different hw architecture (uses Xilinx Zynq which uses ARM Cortex A9).

**Comment by sanjayrd** [comment]
Hi @az2022,

1. For the microphone input, the audio is required to be in the following format:
All captured audio sent to AVS should be encoded as:
 - 16bit Linear PCM
 - 16kHz sample rate
 - Single channel
 - Little endian byte order
This is something that AVS documents [here](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize).

2. The only information supplied by AVS is that audio sent down to SpeechSynthesizer is AUDIO_MPEG. You can always re-sample or re-format the binary audio stream that is sent down to fit your needs. If you are using our GStreamer based MediaPlayer, we will have this as a configuration option in our 1.4 release.

3. No reason. One set is used to configure PortAudio and one set is used to supply the metadata of the AudioFormat object of the microphone stream to the SDK. These could be combined.

Thanks,
Sanjay

**Comment by BennyAvramson** [comment]
hi @az2022,

- For the Mic, as you can see on the [AVS doc](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize), all the captured audio sent to AVS should be 16 kHz and single channel.

- For audio received from AVS
  - For audio originated by an Alexa Skill or Music provider, the sample rate depends on the provider.
  - For audio originated by AVS [SpeechSynthsizer](https://developer.amazon.com/docs/alexa-voice-service/speechsynthesizer.html): `SpeechSynthesizer` is MP3, so MP3 dictates all that data within the stream itself.
- The constants on `PortAudioMicrophoneWrapper.cpp` are used to initialize portAudio. The constants on `SampleApplication.cpp` are used to initialize the AIP Capability Agent

**Comment by BennyAvramson** [comment]
Hi @az2022,

Is there any reason to resample it before playing? Anyway, The `MediaPlayer` class will be a good place to start with

**Comment by az2022** [comment]
Also, are there any block/sequence diagrams that details how SDK interacts with other s/w packages like PortAudio, GStreamer, ALSA etc, perhaps detailing the control and data path and what changes can be affected from within the SDK. So far it seems like a black box.

**Comment by az2022** [comment]
@BennyAvramson - I don't really need to resample it. The particular issue I am facing is, with music playing back from AVS cloud (Amazon Music library) I hear some popping sounds. Just based on listening, it seems like some higher frequency sounds are being clipped off. If I play the same music using "asound" app (basically downloading the same song on my device and using "asound" to play it) there's no problem. Almost seems like there's some default setting somewhere which needs to be tweaked? Perhaps from GStreamer? BTW, I don't have modifications in the MediaPlayer class and it still uses the GStreamer libraries. Let me know your thoughts. Thanks.

**Comment by az2022** [comment]
**Update**: Popping is there when playing radio songs as well but I don't hear the popping sounds when playing news, unless it's very subtle! Also I might be incorrect that popping occurs at higher frequencies, I did hear it randomly (perhaps at some notes but I am not sure) but so far only when there's some music/lyrics being played, i.e. not when there's slight silence in between the lyrics/music, meaning when there's no music or lyrics being played within a song there's no popping.

**Comment by az2022** [comment]
Seems like removing Pulse Audio library (pulseaudio) and related ALSA plugin (libasound2-plugins), cleared the distortions. Theoretically GStreamer->PulseAudio->Alsa route should have worked for playback, right? Previously when I used "aplay" it did use PulseAudio and audio was clear but not when using in combination with GStreamer (using AVS SDK), perhaps something is not being set correctly by GStreamer/AVS-SDK when using PulseAudio.

**Comment by bandkenamazoncom** [comment]
Thanks for the updates!

Do you have an example of the audio that causes the problems in the SDK?

**Comment by az2022** [comment]
I was able to reproduce with an iHeart radio station music as well, i.e. almost any cloud music should do to reproduce this.

**Comment by bandkenamazoncom** [comment]
Do you have this problem for all cloud based streams?  It's not common, most will play fine.  What version of gstreamer are you using?

**Comment by frozenberg** [comment]
Hi @az2022,

This might be an annoying fix but potentially worth a try: upgrading gstreamer to 1.12. If it's an issue with gstreamer then maybe it was patched.

I've not been able to reproduce this issue.

Fede
