### ISSUE TITLE
Regarding android App Development with avs-device-sdk

### ISSUE THREAD

**Issue by vsthirunavukkarasu** [alexa/avs-device-sdk#441]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We need to know the how the meta data information is transferring from product to App. at the time of fresh configuration of Echo Dot Device.

We need to do the same kind of activity. So any one having the content kindly share me.
Thanks in Advance.

### Tell us what hardware you're using:
PICO-PI-IMX7d

### Tell us about your OS (Type & version):
Yocto Based Linux

**Comment by BennyAvramson** [comment]
Hi @vsthirunavukkarasu,

Could you elaborate and provide more background on your question?
What are you trying to build? Is it an SDK based solution? What exactly are you referring to with "fresh configuration of Echo Dot"?

Thanks

**Comment by frozenberg** [comment]
Hi @vsthirunavukkarasu,

Haven't heard from you in a little while so I'm going to close this issue. If you want to respond to @BennyAvramson's questions feel free to reopen this issue.
