### ISSUE TITLE
Raspberry Setup Scripts URL wrong

### ISSUE THREAD

**Issue by comdata** [alexa/avs-device-sdk#444]
## Briefly summarize your issue:

URL: https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

Step 1 in "Setup and Run" points not to RAW files but to the HTML representations.

Need to be changed to:

https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/RaspberryPi/setup.sh

and:

https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/RaspberryPi/config.txt

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi comdata,

Thanks for bringing this to our attention - we expect to update our documentation shortly to reflect this correction.
