### ISSUE TITLE
GLib-GObject-WARNING **: value "0.000000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#445]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We are porting alexa on our current product. The toolchain on our current product is a little old, which does not meet the requirement of building AVS. But it is not possible to upgrade the toolchain because it is provided by the SoC vendor.  So we are building alexa SDK and relative depency libs on a seperate system which has the latest toolchains. After that, we move all the generated library files and “SampleApp” to the product.  

But the problem is it seems has some problem during running:
[XXXX12345678] /tmp/avs # ./SampleApp alexa/AlexaClientSDKConfig.json Debug9
Running app with log level: DEBUG9
2018-01-15 02:19:02.710 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-01-15 02:19:02.713 [  1] I ConfigurationNode:initializeSuccess

(gst-plugin-scanner:4331): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstpng.so': Error relocating /usr/lib/libpng16.so.16: inflateValidate: symbol not found

(SampleApp:4330): GLib-GObject-WARNING **: value "0.000000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'

(SampleApp:4330): GLib-GObject-WARNING **: value "0.000000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'

(SampleApp:4330): GLib-GObject-WARNING **: value "0.000000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'
2018-01-15 02:19:03.000 [  1] I AlertScheduler:executeScheduleNextAlertForRendering::no work to do.

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x10d7410,policy=BLOCKING
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0x10d3250,policy=NON_BLOCKING
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0x10d3250,policy=NON_BLOCKING
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0x10d3250,policy=NON_BLOCKING
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x10e2600,policy=NON_BLOCKING
2018-01-15 02:19:03.001 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0x10e2600,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0x10c6430,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0x10c6430,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0x1069130,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0x1076314,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x10a26c0,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x10a26c0,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetVolume,handler=0x10a26c0,policy=NON_BLOCKING
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderPlayerInfo,handler=0x1010100,policy=HANDLE_IMMEDIATELY
2018-01-15 02:19:03.002 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderTemplate,handler=0x1010100,policy=HANDLE_IMMEDIATELY
2018-01-15 02:19:05.640 [  1] I HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-na.amazon.com/v20160207/directives
#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_gcs_io.so
ALSA lib dlmisc.c:252:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_gcs_io.so
ALSA lib pcm_direct.c:1137:(snd1_pcm_direct_initialize_poll_fd) unable to open timer 'hw:CLASS=3,SCLASS=0,CARD=0,DEV=0,SUBDEV=0'
ALSA lib pcm_dmix.c:1099:(snd_pcm_dmix_open) unable to initialize poll_fd
                  #    #     #  #####      #####  ######  #    #
                 # #   #     # #     #    #     # #     # #   #
                #   #  #     # #          #       #     # #  #
               #     # #     #  #####      #####  #     # ###
               #######  #   #        #          # #     # #  #
               #     #   # #   #     #    #     # #     # #   #
               #     #    #     #####      #####  ######  #    #

       #####                                           #
      #     #   ##   #    # #####  #      ######      # #   #####  #####
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #
       #####  #    # # ## # #    # #      #####     #     # #    # #    #
            # ###### #    # #####  #      #         ####### #####  #####
      #     # #    # #    # #      #      #         #     # #      #
       #####  #    # #    # #      ###### ######    #     # #      #

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

p
+----------------------------------------------------------------------------+
|                          Speaker Options:                                  |
|                                                                            |
| Press '1' followed by Enter to modify AVS_SYNCED typed speakers.           |
|       AVS_SYNCED Speakers Control Volume For: Speech, Content.             |
| Press '2' followed by Enter to modify LOCAL typed speakers.                |
|       LOCAL Speakers Control Volume For: Alerts.                           |
+----------------------------------------------------------------------------+

1
+----------------------------------------------------------------------------+
|                          Volume Options:                                   |
|                                                                            |
| Press '1' followed by Enter to increase the volume.                        |
| Press '2' followed by Enter to decrease the volume.                        |
| Press '3' followed by Enter to mute the volume.                            |
| Press '4' followed by Enter to unmute the volume.                          |
| Press 'i' to display this help screen.                                     |
| Press 'q' to exit Volume Control Mode.                                     |
+----------------------------------------------------------------------------+

1

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable
2018-01-15 02:23:22.167 [  2] I SpeakerManager:executeSetMute::Skipping sending notifications:reason=forceNoNotifications

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_set_valist: property 'volume' of object class 'GstVolume' is not writable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_set_valist: property 'volume' of object class 'GstVolume' is not writable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable

(SampleApp:4330): GLib-GObject-WARNING **: g_object_get_valist: property 'volume' of object class 'GstVolume' is not readable
##################################################################
#       SOURCE:LOCAL_API TYPE:AVS_SYNCED VOLUME:100 MUTE:1       #
##################################################################

When I speak to the device, it can send message to avs server, and I can see this in the history on the alexa app. But it seems AVS can not recognize the voice, and when I replay the record on the alexa app, I hear nothing.

Also it seems it report error when I adjust the volume with the UI interface. 

Can you point anything wrong here?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [Y ] Other - tell us more: Qualcom 8074

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [Y ] Other - tell us more: Openwrt

**Comment by dhpp** [comment]
Hi @subjectxbj ,

Could you please read my response to #449, and let's continue the discussion there?  I will close this ticket, as both seem to be related to GStreamer on your target platform.
