### ISSUE TITLE
About Music playback doesn't immediately stop when a user barges-in on iHeartRadio.

### ISSUE THREAD

**Issue by zhm-nico-nico-ni** [alexa/avs-device-sdk#447]
`auto size = m_reader->read(info.data, info.size, &status);  // This make thread blocking `

I quite sure this code inside  AttachmentReaderSource.cpp blocking the sequence thread then cause the problem.

So I change like this:
`auto size = m_reader->read(info.data, info.size, &status, std::chrono::milliseconds(200));`

May help you

**Comment by zhm-nico-nico-ni** [comment]
Under this situation, getOffSet() inside AudioPlayer will also cause lag

**Comment by dhpp** [comment]
Thanks for the suggestion.

We are aware of the issue, and have prioritized a fix for future releases of the SDK.
