### ISSUE TITLE
mic input data format

### ISSUE THREAD

**Issue by yangk** [alexa/avs-device-sdk#448]
Hi,

I have integrated Alexa V1.3.0 into my Armv7 based Prototype device and it can work properly. But I found it bad to pick up the sound. You see in the code that audioport only opens one input channel,
so I'd like to know that SDK can only accept a single channel of data? Are we able to change the sampling rate? Where can I find the concrete data format of the recording, I need to do how to deal with the input data to get better results.

my environment:
Linux rockchip 3.10.104 armv7l GNU/Linux

We look forward to your reply.

**Comment by dhpp** [comment]
Hi @yangk,

Thanks for your question.  The requirements on audio format is not defined by the SDK, but by the AVS service itself.  In particular, please see the documentation [here](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize).

In particular:
"
All captured audio sent to AVS should be encoded as:
16bit Linear PCM
16kHz sample rate
Single channel
Little endian byte order
"

Please check that your audio format is following these requirements.  If you need further help, can you advise if you are successful in making connections to AVS, and you are receiving responses to the Recognize requests?

Thanks.

**Comment by yangk** [comment]
@dhpp I can use it correctly to connection to avs. Because I have six mic, I see only one channel is used in the code. Whether we need to integrate the processing algorithm of MIC itself and then send the processed single channel data to AVS? Otherwise, we did only use one mic.

**Comment by yangk** [comment]
Hi expert,

Do you have any comments?

**Comment by bandkenamazoncom** [comment]
The six mics will have to be collected to a single channel to send to AVS.

**Comment by yangk** [comment]
thanks
