### ISSUE TITLE
External DSP wakeWord detection Support

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#453]
Hello Team,

We are working on Alexa enabled prototype device and we have on board audio DSP. Earlier Java based Alexa SDK used to have that support . 
Does C++ SDK has support for external wake word detection via GPIO. ? or How we can hook up our own wake word engine?

Regards
Sandy

**Comment by dhpp** [comment]
Hi @sandeepajesh,

Please look at our KeywordDetector code, which is designed to be specialized by partners in this way.  For example, our KittAi implementation is here:

KWD/KittAi/include/KittAi/KittAiKeywordDetector.h

This class inherits from the base class:

KWD/include/KWD/AbstractKeywordDetector.h

You will then see in:

SampleApp/src/SampleApplication.cpp

where we instantiate the given detector for a build.  If you create a different specialization, then this is where you would change the code to have it take effect in the SampleApp.

Hope this helps, let us know if you have any further questions.

**Comment by sandeepajesh** [comment]
Thanks for the info. Very helpful.
