### ISSUE TITLE
Build with a Wake Word Detector

### ISSUE THREAD

**Issue by chraghunadh** [alexa/avs-device-sdk#457]
Hi
I am using ubuntu16.04.without KWD sensory working.
how to run with KWD.

I flowed this links
https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide
https://github.com/alexa/avs-device-sdk/wiki/Build-Options

/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 65%] Linking CXX shared library libSENSORY.so
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/ld: /home/raghu/Desktop/alexa-rpi/lib/libsnsr.a(libsnsr11003.o): Relocations in generic ELF (EM: 40)
/home/raghu/Desktop/alexa-rpi/lib/libsnsr.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
KWD/Sensory/src/CMakeFiles/SENSORY.dir/build.make:98: recipe for target 'KWD/Sensory/src/libSENSORY.so' failed
make[2]: *** [KWD/Sensory/src/libSENSORY.so] Error 1
CMakeFiles/Makefile2:4482: recipe for target 'KWD/Sensory/src/CMakeFiles/SENSORY.dir/all' failed
make[1]: *** [KWD/Sensory/src/CMakeFiles/SENSORY.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Thanks,
Raghu.

**Comment by dhpp** [comment]
Hi Raghu,

It looks like you've got a build issue with the Sensory library.  The error trace shows that library is in the wrong format for your build environment.  Did you follow our setup guidance [here](https://github.com/alexa/avs-device-sdk/wiki/Build-Options)?  How did you set up the libsnsr library?

**Comment by chraghunadh** [comment]
hi@dhpp,
Thank you for reply
I already  used this command  setting the path
cmake <absolute-path-to-source> -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=<absolute-path>/alexa-rpi/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=<absolute-path>/alexa-rpi/include

Thanks,
Raghu.

**Comment by chraghunadh** [comment]
i am try to run

raghu@raghu:alexa-rpi$ ./bin/license.sh 

./bin/license.sh: line 49: /home/raghu/Desktop/alexa-rpi/bin/sdk-license: cannot execute binary file: Exec format error
Unexpected licensing error encountered. Exiting.

**Comment by dhpp** [comment]
Hi Raghu,

Looking at the license.sh file [here](https://github.com/Sensory/alexa-rpi/blob/master/bin/license.sh), line 49, it appears that a file cannot be found.  

I would start by verifying that the variables on lines 21-24 of that script are correctly configured.  I would also carefully go through their README, particularly the [FAQ](https://github.com/Sensory/alexa-rpi#frequently-asked-questions).

Let us know if this helps solve your issue, thanks.

**Comment by sanjayrd** [comment]
Closing for now - please reopen if you're still having issues.

Thanks,
Sanjay
