### ISSUE TITLE
 build with KITT.ai error

### ISSUE THREAD

**Issue by chraghunadh** [alexa/avs-device-sdk#458]
Hi,

I am using ubuntu16.04.without KWD KITT.ai working.
how to run with KWD KITT.ai.

I flowed this links
https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide
https://github.com/alexa/avs-device-sdk/wiki/Build-Options

raghu@raghu:sdk-build$ cmake ../sdk-source/avs-device-sdk/ -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/raghu/Desktop/snowboy/lib/ubuntu64/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/raghu/Desktop/snowboy/include
(command)
I am using gcc version is
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ 62%] Linking CXX executable KittAiKeyWordDetectorTest
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/build.make:102: recipe for target 'KWD/KittAi/test/KittAiKeyWordDetectorTest' failed
make[2]: *** [KWD/KittAi/test/KittAiKeyWordDetectorTest] Error 1
CMakeFiles/Makefile2:4546: recipe for target 'KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all' failed
make[1]: *** [KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Thanks,
Raghu

**Comment by dhpp** [comment]
Hi Raghu,

This type of issue has been seen a few times by our users, for example [here](https://github.com/Kitt-AI/snowboy/issues/269), [here](https://github.com/alexa/avs-device-sdk/issues/300) and [here](https://github.com/Kitt-AI/snowboy/issues/305).

Please let us know if the guidance on those links help resolve this issue for you.  Thanks.

**Comment by chraghunadh** [comment]
Hi @dhpp,
KITT.ai or  Sensory support's ubuntu16.04 laptop.

Thanks,
Raghu

**Comment by bandkenamazoncom** [comment]
@chraghunadh, were you able to get the SDK to compile?

**Comment by chraghunadh** [comment]
Hi @bandkenamazoncom 
Yeah, I am able to compiled and run without keyword(sensory or kitt).It's working fine.
problem is keyword sensory not support on a ubuntu16.04 laptop so I am trying kitt.ai.
Thanks,
Raghu

**Comment by bandkenamazoncom** [comment]
I don't understand what your question is, can you please restate it?

**Comment by chraghunadh** [comment]
Hi @bandkenamazoncom 

cmake error. please see above first one.

Thanks,
Raghu.

**Comment by bandkenamazoncom** [comment]
Did you try with an older compiler?

This link looks like it might help.  There's a few things that you can try:  https://github.com/Kitt-AI/snowboy/issues/99.

**Comment by Yuhanlolo** [comment]
I'm using Mac and got the exact error. Did you solve it?

**Comment by mradulan** [comment]
gcc compiler 5.4 doesn't work with KittAi, although it works with gcc 4.8.5. Can you try with compiler 4.8.5?
