### ISSUE TITLE
The timer ring, off and on, during KissFM(iHR) playing in SDK V1.4.0

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#459]
Hi ,
I have a test case below to verify the timer function:

> (1) say "Alexa, set a timer for 1 minute", then you will hear "1 minute, starting now".
> (2) say "Alexa, play KissFM from iHeartRadio", then it start to play KissFM.
> (3) When the timer goes off, the timer start ring, but it's intermittent in first 30 seconds. [This](https://gist.github.com/boyce-xx/c12151dd342516af8bec80882c4ee413) is the test log.

In the test log, you will see the intermittent log from the time-point **2018-01-18 06:21:33.873** to **2018-01-18 06:22:06.273**, after that, the alarm ring will be normal.

It is worth mentioning that the issue will not happens if I ask the question "Alexa, play Lady gaga station from iHeartRadio" in the step 2 above.

Please have a try and clarify if it's a known issue. 
Thank you.

**Comment by dhpp** [comment]
Hi @boyce-xx,

I've looked at the log you provided, and the server logs, and I'd like to ask a few questions.  First of all, does this happen consistently?  Secondly, I noticed that the Alert.AlertStarted is the final Event sent on that AVS connection session, suggesting network issues were involved (unless you manually restarted the application or reset the AVS connection within the running process).

Also, could you please give a little more detail on exactly the problem you were hearing?  It's not entirely clear.  Thanks.

**Comment by boyce-xx** [comment]
Hi @dhpp ,
1. First of all, does this happen consistently?

> Yes, I can duplicate the issue one hundred percent follows the steps above on my device, my platform is: **Linux apq8009 3.18.44 #1 SMP PREEMPT Fri Dec 15 20:34:20 CST 2017 armv7l GNU/Linux**

2. Secondly, I noticed that the Alert.AlertStarted is the final Event sent on that AVS connection session, suggesting network issues were involved (unless you manually restarted the application or reset the AVS connection within the running process).

> I don't think it is a network issue, because the issue does not appear if I ask the question "play **Lady gaga station** from iHeartRadio" in the same network, the only difference is my question.

3. Also, could you please give a little more detail on exactly the problem you were hearing? It's not entirely clear.

> I set a timer in one minute before playing KissFM on iHeartRadio, during iHR playing, when the timer goes off, iHR will be switched to PAUSED state, the timer starts(local audio sound) ring, but the sound is abnormal in first about 30 seconds:  The ring is discontinuous(or disjointed), it can't speak fluently.

Thanks!

**Comment by bandkenamazoncom** [comment]
Hi @boyce-xx 

Can you tell me the version of the SDK that you are using?

**Comment by bandkenamazoncom** [comment]
I have been able to reproduce this locally.  I have filed a bug report in-house and we will look at it.

**Comment by boyce-xx** [comment]
Hi @bandkenamazoncom ,
   SDK version is 1.4.0, and thank you for clarifying.

**Comment by bandkenamazoncom** [comment]
Thanks for finding this!
