### ISSUE TITLE
Two questions with Kindle book and Amazon Music

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#460]
## Briefly summarize your issue:
Questions for incorrect behavior with Kindle book and Amazon Music with Amazon APP
Q1: I tried the Kindle book, while I said :  Alexa, next chapter.   It will jump to next chapter.  With Echo, it will not go to next chapter.  And from Amazon function checklist, it should not jump to next chapter and should ask user to do it from APP.

Q2: Amazon Prime Music with my playlists, while I said : Alexa, pause.  Alexa, resume,  the music playing behavior is correct (it will resume from last stop position), but the time bar on Amazon APP will go to beginning potion.   With Echo, the time bar is correct with the same test.

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X] Other - tell us more:  ARM based embedded system

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @zeusshuang,

Thanks for mentioning these issues.  Both are known, and are being worked on.

**Comment by bandkenamazoncom** [comment]
We are tracking this internally.
