### ISSUE TITLE
Query related to Amazon Wake word Engine (WWE) 

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/avs-device-sdk#464]
Hi Team,

Do we have  Amazon Wake word Engine (WWE) available?. If Yes, please let me know How we can integrate it to our prototype device.

We have integrated avs-device-SDK 1.4 on our device and currently we are using sensory as WWE and we want to use it with Amazon WWE.

Please help.

Regards
Sandeep S

**Comment by anu-mathur** [comment]
Hi @sandeepajesh 

Can we discuss your use case for more details? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will reach out to you.
Thanks

**Comment by bandkenamazoncom** [comment]
Thanks @anu-mathur!

**Comment by bandkenamazoncom** [comment]
I'm closing this, please re-open if our answer isn't sufficient.
