### ISSUE TITLE
required version is not available for gstreamer lib

### ISSUE THREAD

**Issue by imrajeshpal** [alexa/avs-device-sdk#465]
## Briefly summarize your issue:

sudo apt-get install libgstreamer-plugins-bad1.0-dev
I am trying to install above library...
but not able to install it because of following dependencies..
a. libgstreamer-plugins-bad1.0-dev : Depends: libgstreamer-plugins-bad1.0-0 (= 1.8.3-1ubuntu0.2) but it is not going to be installed
b. Depends: gir1.2-gst-plugins-bad-1.0 (= 1.8.3-1ubuntu0.2) but it is not going to be installed.

When tried to remove above dependencies it results in to some other dependencies.

### Tell us about your OS (Type & version):
- [ ] Linux, I am using ARTIK 530 development board
Below is the output of lscpu command
lscpu 
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 0 (v7l)
CPU max MHz:           1200.0000
CPU min MHz:           400.0000
Hypervisor vendor:     (nul

cat /proc/version 
Linux version 4.4.71-0530GC0F-44U-01Q1 (jenkins@iotadmin-PowerEdge-T630) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) ) #1 SMP PREEMPT Fri Aug 25 16:14:23 KST 2017

Any help would be appreciable.

**Comment by bandkenamazoncom** [comment]
Can you post the command and output?

**Comment by imrajeshpal** [comment]
By exporting the PKG_CONFIG_PATH, I resolved this issue.
:)
