### ISSUE TITLE
iHR can't be longrun playing sometimes.

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#467]
Hi,
    I'm using SDK version 1.4.0 to develop.
    I want to play iHR longrun more than 10 hours, but the playing will be stopped automatically sometimes, I have put the partial log to [HERE](https://gist.github.com/boyce-xx/030b7fb2bd9af5e68e5c293fd271f650). 
    From the log, you can see below that AudioPlayer will be switched the state to FINISHED from PLAYING.

> 2018-01-19 11:06:56.173 [  a] 0 AudioPlayer:changeActivity:from=PLAYING,to=FINISHED

It's not a correct behavior, because I was played KissFM on iHR, it's should be a endless playing.

Can you tell me which condition will cause this behavior? when I will get the FINISHED state even I don't ask Alexa to stop the playing?

Another question: I will get a lot of the log below during playing, is it normal? or is it any effect for the playing progress?

> InProcessAttachmentWriter:AttachmentWriter has timed out while attempting a write.

Thanks.

**Comment by bandkenamazoncom** [comment]
Looking at the logs, it appears that the stream sent an EOS:
`
018-01-19 11:06:55.871 [  2] 9 MediaPlayer:messageReceived:type=eos,source=playbin0
`
That's not something that is controlled by the SDK.

The log message:
`
InProcessAttachmentWriter:AttachmentWriter has timed out while attempting a write.
`
is fine.  It indicates that the local buffer is full and it is waiting to be drained by playing.

**Comment by boyce-xx** [comment]
Hi @bandkenamazoncom ,

> 2018-01-19 11:06:55.871 [ 2] 9 MediaPlayer:messageReceived:type=eos,source=playbin0

We can still see the issue during playing music now, could you explain who will control the message of EOS in details? I see the log in Mediaplayer.cpp

> gboolean MediaPlayer::handleBusMessage(GstMessage* message)

How can I avoid it?
Thanks.

**Comment by mradulan** [comment]
@boyce-xx , how many hours does the iHR run?

**Comment by boyce-xx** [comment]
Hi @mradulan ,
The time is not unstable, one hour, four hour or 12 hour and so on, but those are have the same log, and music has stopped, you can still have a  interaction with AVS.

**Comment by kencecka** [comment]
Hi @boyce-xx,

I've set up a test run and will try to reproduce the issue this week.  I'll keep you posted with any findings.

Ken

**Comment by boyce-xx** [comment]
@kencecka ,
Thanks for your update.
I can still see the issue in SDK V1.5.0.

**Comment by kencecka** [comment]
Hi @boyce-xx,

It took all week, but I finally have an update for you.  I started streaming KissFM on iHR at 2018-02-27 22:12:00.157 did not receive an EOS until 2018-03-02 13:15:07.002, so a total of 63 hours of continuous streaming.

I'll continue digging into it (and may need to hand it off to another engineer next week), but wanted to give you an update that we're able to reproduce.

Ken

**Comment by kencecka** [comment]
Hi @boyce-xx,

I've reviewed this a little further and verified that iHR sends its content directly as an AAC stream (not wrapped in a playlist), which means it's entirely in their control if/when/where to end the stream.  I have yet to find any documentation stating how long it is valid to stream from iHR for, but many services put a cap on this, so it's possible that we're just extending beyond their intended continuous streaming time.  If you happen to catch a log of it terminating after an hour, that would be interesting to look at in comparison to the end-of-stream I'm seeing after many hours.  We may have to get in contact with iHR for an explanation of why the stream is ending.

Ken

**Comment by boyce-xx** [comment]
Hi Ken,

Thanks for your response.
I was also trying to play Amazon music longrun test, but it's failed again.
I asked the Alexa a question: **Alexa, play michael jackson on Prime music.**
It was stopped after playing 5 songs. I have put the [whole log](https://gist.github.com/boyce-xx/7fb6488230a141ea1a6955a74c24ad4d). Please help to analyse.

Thanks a lot.

**Comment by sanjayrd** [comment]
Hi @boyce-xx,

I used the exact same utterance as you and was unable to reproduce the issue you just described above (Michael Jackson played on Prime Music for an hour continuously before I cut it off). Is this a special behavior you're seeing with your custom environment or is this happening on all your environments (i.e. Pi)?

Thanks,
Sanjay

**Comment by boyce-xx** [comment]
Hi @sanjayrd ,
So strange!
I can still see the issue no matter what I played iHR or Amazon music in SDK V1.6.0, and It has no fixed stop time. After it stopped, I could still ask a new question and got the response.

**Comment by scotthea-amazon** [comment]
Hi @boyce-xx,

Looking at the 'whole log' you provided it appears that the attachments for subsequent songs are arriving but that MediaPlayer/gstreamer is not consuming them.  I do not see any logs indicating calls in to MediaPlayer to trigger this.  If you can still reproduce this problem with prime music, could you enable gstreamer logging (see [gstreamer debugging](https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html), capture the combined console output and attach it here?  Such logs might help us understand why gstreamer is not calling the back for more data.

Thank you,
-SWH

**Comment by visayamv** [comment]
Hi @boyce-xx , I will be closing this thread due to inactivity. Please reopen it if you are still experiencing issues. Thanks.
