### ISSUE TITLE
directive when "Deregister" UI_ACTION is triggered.

### ISSUE THREAD

**Issue by howardguo** [alexa/avs-device-sdk#468]
Dear all
which directive when "Deregister" UI_ACTION(by alexa app or website settings) is triggered.
I saw ResetUserInactivity directive is sent to client when deregister. But still have some other active(like pause button by web) also can trigger this ResetUserInactivity directive. 
So I don't know how to distinguish this two scenario.

**Comment by bandkenamazoncom** [comment]
The directive is used to indicate that the device should restart the timer used to monitor the last time something happened.  There doesn't need to be any more action besides that.

**Comment by howardguo** [comment]
OK.Thanks
