### ISSUE TITLE
Question for Cloud-based wake word verification

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#471]
Hi Amazon team,
 
I am wondering if AVS C++ SDK include cloud-based wake word verification [(Streaming Requirements for Cloud-Based Wake Word Verification)](https://developer.amazon.com/docs/alexa-voice-service/streaming-requirements-for-cloud-based-wake-word-verification.html) ?

If it dose supported, how to enable this feature ?

Thanks,

**Comment by bandkenamazoncom** [comment]
The AVS SDK does include the WW verification in the cloud.  It is already enabled by default.  It's dependent on the wakeword engine to provide the start and end indices of the wakeword within the stream.

https://developer.amazon.com/docs/alexa-voice-service/enable-cloud-based-wake-word-verification.html
