### ISSUE TITLE
Pandora music cannot be resumed after pausing more than one hour

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#476]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I updated the [AudioPlayerIntegrationTest](https://gist.github.com/BobXLiu/154f664b98a49ea5a5f720ceb065e9c1) file test the Pandora music and found the Pandora music cannot be resumed after pausing more than one hour.

## What behavior are you observing?

When i checked the [log](https://gist.github.com/BobXLiu/1f080bc3780e48723adaa57f862d28ab) information and found the below error information:

> 2018-01-26 06:13:05.837 [ 12] E PlaylistParser:getHTTPContent:reason=badHTTPContentReceived
2018-01-26 06:13:05.841 [  2] 0 MediaPlayer:callingOnPlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=streamingError,currentId=3
2018-01-26 06:13:05.841 [  2] 0 AudioPlayer:onPlaybackError:type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=streamingError,id=3
2018-01-26 06:13:05.842 [  5] E AudioPlayer:executeOnPlaybackError:id=3,type=MEDIA_ERROR_INTERNAL_DEVICE_ERROR,error=streamingError

## Provide the steps to reproduce the issue, if applicable:

duplicate procedure:
1. Run AudioPlayerIntegrationTest test tool, the device will play Pandora music.
2. After 60 seconds,the AudioPlayerIntegrationTest will send "pause" WAV file, it will stop play music.
3. Leave the client idle for more than one hour.
4. After one hour, the AudioPlayerIntegrationTest will send "resume" WAV file, the device cannot play music.

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bandkenamazoncom** [comment]
Sorry, to hear about this.  I'm consulting with the rest of the team and will report back.

**Comment by frozenberg** [comment]
Hi @BobXLiu, 

This issue will be fixed in an upcoming release. Thanks for your patience.

Fede
