### ISSUE TITLE
problem of Speaker sample rate

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#480]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We are porting AVS client on our product. I know AVS requires that the sample rate of the mic-phone capture should always be 16000Hz/S16LE. But the response from AVS server varies depends on the source of the audio. The audio sample rate of the response may be 16kHz, 32kHz,48kHz...

So that means the speaker should support audio with different sample rate, and at the same time, audio capture should work at 16000/S16LE. Right?

But the problem is our hardware can only support audio output and input work at the same sample rate. That means, if the audio capture works at 16000/S16LE, the speaker should also work at this sample rate. So we need to force to resample all the response audio to 16000/S16LE before play it.

I'm not sure if this is allowed, and is this operation acceptable for product certification by Amazon?

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by frozenberg** [comment]
Hi @subjectxbj,

As far as I know, there aren't any restrictions on speaker sample rate. If I learn anything different I'll be sure to let you know!

Fede

**Comment by subjectxbj** [comment]
Thanks @frozenberg ,

That means we will need to resample all the response audio to 16000Hz. If user use it to play music with high sample rate like 48000Hz, the resample will lose some sound quality. Is this also acceptable? Can you confirm this? This is very urgent. Very appreciate.

Thanks,
Arthman

**Comment by frozenberg** [comment]
As long as the output isn't stuttering and can be reasonably listened to you should be fine.

Fede

**Comment by subjectxbj** [comment]
Just updated to SDK 1.4 and found Amazon has added the support of resample on playback. I can configure the resample in the configuration file instead of changing the code to add the audioresample plugin by myself.

Good job Amazon.

**Comment by ullasbharadwaj** [comment]
> 
> 
> Just updated to SDK 1.4 and found Amazon has added the support of resample on playback. I can configure the resample in the configuration file instead of changing the code to add the audioresample plugin by myself.
> 
> Good job Amazon.

May I know how you got on with resampling by changing config file?
