### ISSUE TITLE
Can avs-device-sdk integrated to Android Things system?

### ISSUE THREAD

**Issue by harman-sunnysun** [alexa/avs-device-sdk#482]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have a speaker which running Android Things system, I want to integrate avs-device-sdk to this system, can we discuss the feasibility?
Here are my imagination steps:
1.  Use Android ndk to build avs-deice-sdk + PortAudio to a library( suppose this library should running on /system/lib with root permission);
2. Develop a Android Service to communicate with AVS sdk as a daemon.
3. Develop a Android APP to call that Android Service to start or stop AVS.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:  Broadcom chipset.

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:  Android Things System

**Comment by frozenberg** [comment]
Hi @harman-sunnysun,

Building the SDK with android-ndk is certainly doable. Building Portaudio I've never personally done but I also believe is possible.

With respect to the next two items, I don't have much expertise in the Android development world but it definitely sounds feasible.

Fede

**Comment by anu-mathur** [comment]
Hi @harman-sunnysun 
Can we please talk more about your use case and experience with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you!
Thanks

**Comment by harman-sunnysun** [comment]
@frozenberg  thanks for you reply.

@anu-mathur sure, already fill out that Contact Form, please check it.

**Comment by mradulan** [comment]
closing the issue as it has been answered.
