### ISSUE TITLE
Can we setup avs-device-sdk for QNX?

### ISSUE THREAD

**Issue by kishordesai** [alexa/avs-device-sdk#483]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by kishordesai** [comment]
We want to setup avs on QNX OS. Can we do it?

**Comment by frozenberg** [comment]
Hi @kishordesai,

Setting up the SDK on QNX is possible, though at this time we do not provide guides on how to do it.

Fede

**Comment by anu-mathur** [comment]
Hi @kishordesai 
Can we please talk more about your use case and experience with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you!
Thanks

**Comment by kishordesai** [comment]
Hi @anu-mathur ,

**Comment by mradulan** [comment]
closing issue as solution is not present currently.
