### ISSUE TITLE
How to enable AVS SDK on Android

### ISSUE THREAD

**Issue by willnien10005914** [alexa/avs-device-sdk#485]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We are designing a speaker running Android system, is there any porting guide for AVS SDK since Android using TinyAlsa instead of Alsa.

Besides, we would like to support Alexa calling with or without video on this product, where we can get that supported AVS SDK?

Thanks.

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: ARM Cortex-A53

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android 7.0

**Comment by frozenberg** [comment]
Hi @willnien10005914,

One of our product managers will be in touch with you with regards to android support.

Fede

**Comment by anu-mathur** [comment]
Hi @willnien10005914 

Can we please talk more about your use case with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you!

Thanks

**Comment by mradulan** [comment]
closing as it will be solved offline

**Comment by anoop4real** [comment]
I am also interested to know....is this a confidential topic...how are apps like reverb working?

**Comment by anu-mathur** [comment]
@anoop4real 

Can we please talk more about your use case with the AVS Device SDK? Please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you!

This is not a confidential topic, but we are not yet ready for a public release, and thus releasing the Android guide in private.

Thanks

**Comment by anoop4real** [comment]
@anu-mathur 
I have filled up the contact form, please get back to me at the earliest.

**Comment by anoop4real** [comment]
@anu-mathur 
I am waiting for your input

**Comment by mmabluesky** [comment]
Hi @anu-mathur,
I filled out the form too. Could you please send me the guide as well?
yuanxuya@outlook.com
Thanks.

**Comment by anoop4real** [comment]
@mmabluesky
Dont expect anything from them.... Nobody contacted me. They have enabled Mobile App support in AVS and all, but no guide on how to properly integrate a client

**Comment by mmabluesky** [comment]
@anoop4real  hi , I saw on Amazon Developer Forums that you have successfully applied avs on Android. At the moment I am also engaged in this research, but there is no official guide. Can you give me some advice? Thanks

**Comment by anoop4real** [comment]
@mmabluesky 
I havent achieved everything but atleast speech/ listening back open custom skills etc works. I havent implemented the downchannel and data sync, I wasnt sure how. 
My starting point was https://github.com/willblaschko/AlexaAndroid , I went through the code and built a new project with some condensed logic, I am using Kotlin and its a shame that these guys are not responding to queries....

**Comment by anoop4real** [comment]
@mmabluesky
I actually didn't even try to combine with NDK, I am not that good with NDK, so I went exploring multiple samples and reached this state, I still need to handle many directives and true without official guidance its challenging (may be we need to show some money :) ).  Did you try asking the question in the forum? If you are ok to share the code, I can try debugging
I am planning to do a cross compile for iOS with AVS SDK and see if it works.

**Comment by WksKing** [comment]
Hi @anu-mathur ,

I have also filled up the contact form last week, but nobody contact me.
would you please send some information about the AVS Device SDK for Android platform?
My e-mail address is king_d_liu@wistron.com

Appreciate it.

**Comment by anoop4real** [comment]
@mmabluesky 
Can you check this thread? Might be helpful  https://github.com/alexa/avs-device-sdk/issues/305

**Comment by anu-mathur** [comment]
I re-shared the Android guide with all on this thread a couple of days back, and got confirmations! Please let us know if you face any access issues.

**Comment by mmabluesky** [comment]
@anoop4real  
Sorry, I only saw this message now.
I have successfully run avs device sdk on Android, everything works fine. ！

**Comment by anoop4real** [comment]
@mmabluesky 
I was able to build the sdk with the instruction provided by Amazon guys, I now have the JNI libs and created a new project and added the libs there as sourceSets....now I dont know the next steps he he....can you help me out?

**Comment by mmabluesky** [comment]
@anoop4real 
Ok, I can help you. I think email communication is too cumbersome. Due to the existence of China Great Wall Firewall, I am not convenient to use social software such as facebook. I don’t know if you use qq or WeChat. If you can, we can add friends.

**Comment by JLu76** [comment]
Hello @mmabluesky , do you think you could help me too? I can make a WeChat account.

**Comment by pkalebu** [comment]
@anu-mathur Could you share the guide with me as well, please. I filled out the form but haven't heard back.

**Comment by pkalebu** [comment]
@anoop4real could you please sent me your guide? I haven't heard back from Amazon yet.

**Comment by avp24** [comment]
@anoop4real Hi. Can you please share me the Android guide?

**Comment by pkalebu** [comment]
[Reference Guide to build Device SDK on Android.pdf](https://github.com/alexa/avs-device-sdk/files/2338191/Reference.Guide.to.build.Device.SDK.on.Android.pdf)

**Comment by rjajra** [comment]
@pkalebu Is SampleApp running after following reference guide?

**Comment by pkalebu** [comment]
Try [this](https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide) if it's not working

**Comment by rjajra** [comment]
@pkalebu Thanks I'll try this.
