### ISSUE TITLE
Device isn't added to alexa.amazon.tld?

### ISSUE THREAD

**Issue by Doxylamin** [alexa/avs-device-sdk#486]
## Briefly summarize your issue:
After I authorized the application and alexa is up and running, the webinterface on "alexa.amazon.de" still says I need to setup a device and redirects me to new-oobe. I've tried using "alexa.amazon.com" but it redirects me.

## What is the expected behavior?
Device is added to alexa.amazon.tld, like observed with the old sample app.

## What behavior are you observing?
Device isn't added to alexa.amazon.tld

### What version of the AVS Device SDK are you using?
      <1.4>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessie
- [ ] Other - tell us more:

**Comment by frozenberg** [comment]
Hi @Doxylamin,

Is your developer account a .de account? And have you tried accessing the site through incognito mode?

Fede

**Comment by Doxylamin** [comment]
Hey @frozenberg 
my company profile is set to Germany, still developers.amazon.com/de/ is redirecting me to amazon.com for signing in, which wasn't a ever problem.
It worked with the old [alexa-avs-sample-app](https://github.com/alexa/alexa/alexa-avs-sample-app) and it was added to my account just fine.

Yes, I've tried accessing the site through incognito mode.
> localhost:3000 redirects to amazon.com for sign in.
> alexa.amazon.com is redirecting me several times. I can't really explain it, so here's a recording of what happens: [streamable.com](https://streamable.com/9ddnx)

Thanks in advance,
Doxy

**Comment by frozenberg** [comment]
Hi @Doxylamin,

I am trying to contact the team in charge of the companion app website. Your patience is appreciated!

Fede

**Comment by frozenberg** [comment]
Hi @Doxylamin,

Sorry for the long wait. You may have to register your device with the correct endpoint, namely `https://avs-alexa-eu.amazon.com`. To do this, you can try editing `HTTP2Transport.cpp` line 53.

Change `https://avs-alexa-na.amazon.com` to `https://avs-alexa-eu.amazon.com` and let me know if you can see your device after the edit.

The option to change this in the config file will be made explicit in the next release.

**Comment by frozenberg** [comment]
Please see my edited comment above if you haven't

**Comment by Doxylamin** [comment]
Hey, thanks for the answer, really appreciate it.
Do I need to rebuild/remake afterwards?

**Comment by frozenberg** [comment]
Yes. When you run the app you should be able to see a line like this: `HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-eu.amazon.com/v20160207/directives` in the logs (provided you have logs enabled). 

If this doesn't work I will continue to research on our end.

**Comment by Doxylamin** [comment]
Hey Fede,
sorry for the late reply. I'll try it out on monday and give you feedback. :)

**Comment by celinval** [comment]
Hi @Doxylamin, Have you tried @frozenberg's suggestion yet? Thanks

**Comment by Doxylamin** [comment]
Yes, just tested it.
`2018-02-26 11:27:36.690 [  1] 9 HTTP2Transport:setupDownchannelStream:url=https\://avs-alexa-eu.amazon.com/v20160207/directives`

The authorization page was in german this time and th endpoint is also set correctly - as seen above. But the page `https://alexa.amazon.de/` still asks me to setup an Alexa device and if I skip this (by opening a direct link to the settings page) I see this: https://i.imgur.com/agTWjjY.png

**Comment by sanjayrd** [comment]
Hi @Doxylamin,

Are you logging into the Alexa Amazon page using your developer account or your user account? You'll need to log in via the user account that you provided to the Login With Amazon interface initially presented to you when you were authorizing the application (i.e. logging in with your Amazon account, not your Amazon developer account).

Thanks,
Sanjay

**Comment by Doxylamin** [comment]
I know. But the developer account is also my user account, i think. I used the Amazon SSO when registering. But that certainly wasn't an issue with the old sample app.

**Comment by celinval** [comment]
Hi @Doxylamin, are you able to run the SampleApp and interact with it? Can you please run the SampleApp with DEBUG9.

Thanks

**Comment by dhpp** [comment]
Closing for now.  Please re-open if the above answers didn't solve your issue.
