### ISSUE TITLE
I got curlDoesNotSupportHTTP2 error on Mac even though installed curl with nghttp2

### ISSUE THREAD

**Issue by harman-sunnysun** [alexa/avs-device-sdk#487]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Here is my curl version information:
 curl --version
curl 7.58.0 (x86_64-apple-darwin16.7.0) libcurl/7.58.0 zlib/1.2.8 nghttp2/1.29.0
Release-Date: 2018-01-24
Protocols: dict file ftp gopher http imap ldap ldaps pop3 rtsp smtp telnet tftp 
Features: AsynchDNS IPv6 Largefile libz HTTP2 UnixSockets 

Here is error message while running SampleApp on Mac:
2018-01-31 09:31:38.130 [  1] I sdkVersion: 1.4.0
Running app with log level: DEBUG9
2018-01-31 09:31:38.132 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-01-31 09:31:38.132 [  1] E AlexaClientSdkInit:initializeFailed:reason=curlDoesNotSupportHTTP2

Any idea about this issue? thanks.

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by frozenberg** [comment]
Hi @harman-sunnysun,

Some troubleshooting steps:

1. Can I see your cmake command?
2. Have you already tried uninstalling and reinstalling curl?

Fede

**Comment by frozenberg** [comment]
Oh and 

3. Can I see the output of running `brew info curl`?

**Comment by harman-sunnysun** [comment]
Have you already tried uninstalling and reinstalling curl?
--> Yes, I do.
Can I see the output of running brew info curl?
--> sure, here it is:
brew info curl
curl: stable 7.58.0 (bottled), HEAD [keg-only]
Get a file from an HTTP, HTTPS or FTP server
https://curl.haxx.se/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb
==> Dependencies
Build: pkg-config ✔
Optional: openssl ✔, rtmpdump ✘, libssh2 ✘, c-ares ✔, libmetalink ✘, nghttp2 ✔
==> Options
--with-c-ares
	Build with C-Ares async DNS support
--with-gssapi
	Build with GSSAPI/Kerberos authentication support.
--with-libmetalink
	Build with libmetalink support.
--with-libssh2
	Build with scp and sftp support
--with-nghttp2
	Build with HTTP/2 support (requires OpenSSL)
--with-openssl
	Build with OpenSSL instead of Secure Transport
--with-rtmpdump
	Build with RTMP support
--HEAD
	Install HEAD version
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

**Comment by harman-sunnysun** [comment]
After rebuild curl & avs, it works, thanks.
