### ISSUE TITLE
Question about the DeRegister function

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#488]
Hi AVS team,
 
It can deregister a device from APP, and this behavior something like remove this device, is my understanding correct ?  
And, if there is any way that it can deregister itself from AVS client directly ?
I think the deregister is not the same as "register fail".

Thanks,

**Comment by frozenberg** [comment]
Hi @zeusshuang,

There is currently no way for a device to deregister itself.

Fede

**Comment by zeusshuang** [comment]
Hi @frozenberg ,
Thanks for the comment.
