### ISSUE TITLE
Question about the Locale function and AVS running under different area.

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#489]
Hi AVS team,
 
I have questions about the "locale" defined in AlexaClientSDKConfig.json and related definition in AVS/Echo behaviors.

Q1 - The locale defined in AVS SDK, it seems only for change the "en-US",  "en-GB", "de-DE" value, but it seems do nothing with this "locale" value.  Will it do anything different while the "locale" value is different in configuration (eg. AlexaClientSDKConfig.json) ?

Q2 - Should I change different endpoint by different locale settings before SampleAPP start up, or Alexa server will change it by Event from LWA ?

Q3 - I need to contact with Sensory or KittAi to get different Alexa data model for different locale ? But I think the AVS SDK now does not change different KWD data model while local changed ?

Q4 - The Alexa services are bundled by use's account (user's address or country setting), not SampleAPP settings.  So while user changed their settings, SampleAPP will receive event from LWA to change locale automatically ?

Q5 - Should I need to change time zone (eg. the SampleAPP launch command: TZ=UTC) while the locale is not in States? or TZ=UTC is a fixed data, LWA will adjust it in cloud automatically ?

Sorry to raise so many questions here, please kindly help to have comments.

**Comment by frozenberg** [comment]
Hi @zeusshuang,

Q1: The value of locale in the AlexaClientSDKConfig.json is used if there isn't already a Settings database file available for the SDK to grab a setting from. When you change your locale, you are updating that database.

Q2: You can change the default endpoint to connect to through the json config file. If the service detects that another endpoint would better serve your device, a SetEndpoint directive will instruct your device to switch. See https://developer.amazon.com/docs/alexa-voice-service/system.html#setendpoint

Q3: If you are interested in different model files you should definitely consider contacting Sensory or KittAi.

Q4: Yes that seems to be correct. Again, see https://developer.amazon.com/docs/alexa-voice-service/system.html#setendpoint

Q5: TZ=UTC was being used for SDK-specific calculations. In a future release, we will be removing the dependency on that flag.

Hope that helps,
Fede

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

Thanks for the comments!!
For Q1 and Q4, I have some tests with SDK1.4.  
I tried to change my account's address to different country, and while I question the "time", it's actually respond the local time according to my address.
However, I did not receive any settings change event (SetEndpoint ) from LWA by AVS log.
Should I enable any compile option for such events ?
  
And for Q2, to change a better endpoint, I think it will also detect by server site and SampleAPP will receive "SetEndpoint" by endpoint handler ? 

Thanks,

**Comment by frozenberg** [comment]
Did you change your address through alexa.amazon.com?

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

Yes, I changed it from this site.
And I also check it by question "what time is it", it's actually changed to local time by different country and address.
But from AVS log, I did not receive any message from the log.

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

I have another question and would like to clarify.
How Amazon server respond to different language ? If device listen DE language, will it respond if the account is registered in Amazon UK ?  From my test, it will not respond if I play DE language to my US account but address is set to Germany.

**Comment by frozenberg** [comment]
Ok I have asked around and gotten some clarifications on certain things:

1. The locale setting determines what language/accent Alexa should speak with and what language/accent Alexa expects you to speak. All locales are available in all endpoints.

2. The endpoint you hit is determined by your account country settings.

3. The time that Alexa will report is based on your Timezone setting in your alexa.amazon.com portal. Have you checked that setting? (Not country/address)

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

Thanks for the comments, it's clear now.
We can close this ticket.
