### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by ela34** [alexa/avs-device-sdk#49]
Hi,

I'm getting started with this SDK. I followed the Quick Start Guide to build the SDK for Linux.
When I try to run AuthServer, I have this message in the console:

> The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.
> 
>  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

When I open the link http://127.0.0.1:3000/ in my browser, I have this message:

> We're sorry!
> An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
> 
> Error Summary
> 400 Bad Request
> The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
> Request Details
> scope=alexa%3Aall
> redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthresponse
> response_type=code
> client_id=_client_id_
> scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22 _deviceTypeId_ %22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%22123456%22%7D%7D%7D 

In my developer portal,  Allowed Origins is https://localhost:3000,  Allowed Return URLs is https://localhost:3000/authresponse

And the file Integration/AlexaClientSDKConfig.json is filled like this:

>  {
>     "authDelegate":{
>         "clientSecret":_clientSecret_,
>         "deviceSerialNumber":"123456",
>         "refreshToken":"",
>         "clientId":,_clientId_
>         "deviceTypeId":_deviceTypeId_
>      }
>  }

I got the _clientSecret_, _clientId_ and _deviceTypeId_ from my developer portal.

Any idea of what I am doing wrong? Thanks.

**Comment by nishmeht7** [comment]
@ela34 You can't use https in allowed return URLS?

**Comment by Eptin** [comment]
@nishmeht7 You can, but the`Allowed Return URLs` must match what you have for the `redirect_uri` (same with Origin; it too must match the originating URL).
Often times, I will add both `http` and `https` variations to cover all bases.
