### ISSUE TITLE
Unable to cross compile Googletest for iOS

### ISSUE THREAD

**Issue by charmainkho** [alexa/avs-device-sdk#492]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I tried to run this command on terminal : 
cmake ../googletest -DIOS_DEPLOYMENT_TARGET=10.0 -DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS

## What behavior are you observing?
It returns me this error:
-- Building with Xcode version: 
-- Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK:  for platform: OS
CMake Error at /Users/khokhaien/cross-compile/ios-cmake/ios.toolchain.cmake:145 (message):
  Invalid CMAKE_OSX_SYSROOT: does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/CMakeDetermineSystem.cmake:91 (include)
  CMakeLists.txt:7 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

### Tell us what hardware you're using:
- Macbook Pro 15"

### Tell us about your OS (Type & version):
- [ ] MacOS High Sierra Version 10.13.3

**Comment by 593980284** [comment]
I met the same problem, how to solve it

**Comment by 593980284** [comment]
curl --version
   curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
brew --version
   Homebrew 3.0.5
xcode-select --version
    xcode-select version 2373.

1. brew install cmake pkg-config
2. cd ~
3.  mkdir cross-compile
4.  cd cross-compile
5.  cd ~/cross-compile
6.  git clone https://github.com/leetal/ios-cmake.git
7.  git clone https://github.com/google/googletest.git
8.  mkdir googletest_build
9.  cd googletest_build
//All successful

10. cmake ../googletest \
-DIOS_DEPLOYMENT_TARGET=10.0 \
-DCMAKE_TOOLCHAIN_FILE=../ios-cmake/ios.toolchain.cmake \
-DIOS_PLATFORM=OS \

make

//Running this will report the above error
