### ISSUE TITLE
refresh request failed with the response code 400

### ISSUE THREAD

**Issue by tgraf2** [alexa/avs-device-sdk#493]
Hi,

I ran the 'Raspberry Pi Quick Start Guide with Script' on a newly setup PI3 with Raspbian Stretch with Desktop.  Everything ran without error until I ran 'sudo bash startauth.sh'.  The script failed with "The refresh request failed with the response code 400."

I have registered the product and filled in the product ID, Client ID, and Client secret in config.txt, which looks like this:

CLIENT_SECRET="<redacted>"
#NOTE: The Device Serial Number can be any unique number
DEVICE_SERIAL_NUMBER="012345"
CLIENT_ID="<redacted>"
PRODUCT_ID="alexa_pi"

I actually have several registered products.  I have tried the client info for each of them with the same result.  Not sure what else could be the problem.

**Comment by tgraf2** [comment]
Additional comment:  I tried to access http://127.0.0.1:3000 from the pi Chromium browser and it failed with "ERR_CONNECTION_REFUSED".  Is there another setting that I should be aware of?

**Comment by tgraf2** [comment]
Additional comment.  wget and curl get the same connection refused error: 

pi@raspberrypi:~ $ wget http://127.0.0.1:3000
--2018-02-02 11:32:57--  http://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... failed: Connection refused.
pi@raspberrypi:~ $ curl http://127.0.0.1:3000
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused

**Comment by frozenberg** [comment]
Hi @tgraf2,

When the script shows you that error message, do you also see the message . "Running on http://127.0.0..1:3000/" or does it simply exit to your terminal?

Fede

**Comment by tgraf2** [comment]
Hi Fede, 

When I run 'sudo bash startauth.sh' I get the following:

pi@raspberrypi:~ $ sudo bash startauth.sh
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

**Comment by frozenberg** [comment]
The ERR_CONNECTION_REFUSED message you are seeing usually happens when you try to access that url while not running the script.

Have you tried accessing the url while leaving the script running (and by running I mean in the state where you get the `The refresh request failed with the response code 400...` message you mentioned)

**Comment by tgraf2** [comment]
Hi,

Thanks for the advice.  I was able to authenticate when I left the script running, but startsample.sh fails with "AuthDelegate:initFailed:reason=missingConfigurationValue,key=refreshToken".  See the transcript below:

2018-02-02 19:17:23.158 [  1] I sdkVersion: 1.4.0
Running app with log level: DEBUG9
2018-02-02 19:17:23.580 [  1] I ConfigurationNode:initializeSuccess:configuration={"authDelegate"\:{"clientSecret"\:"2356bf1c47418fe20aaa389ce32f77a3461995527438f478a05ba4e770ac590a"\,"deviceSerialNumber"\:"012345"\,"refreshToken"\:""\,"clientId"\:"amzn1.application-oa2-client.9a5f4068421b4ba5a999f9db07c80023"\,"productId"\:"alexa_pi"}\,"alertsCapabilityAgent"\:{"databaseFilePath"\:"/home/pi/db/alerts.db"}\,"settings"\:{"databaseFilePath"\:"/home/pi/db/settings.db"\,"defaultAVSClientSettings"\:{"locale"\:"en-US"}}\,"certifiedSender"\:{"databaseFilePath"\:"/home/pi/db/certifiedSender.db"}\,"notifications"\:{"databaseFilePath"\:"/home/pi/db/notifications.db"}\,"sampleApp"\:{"displayCardsSupported"\:true}}
2018-02-02 19:17:23.627 [  1] 9 MediaPlayer:createCalled
2018-02-02 19:17:23.932 [  1] I MediaPlayer:noOutputConversion
2018-02-02 19:17:23.935 [  1] 9 MediaPlayer:createCalled
2018-02-02 19:17:23.938 [  1] I MediaPlayer:noOutputConversion
2018-02-02 19:17:23.942 [  1] 9 MediaPlayer:createCalled
2018-02-02 19:17:23.943 [  1] I MediaPlayer:noOutputConversion
2018-02-02 19:17:23.946 [  1] 9 MediaPlayer:createCalled
2018-02-02 19:17:23.947 [  1] I MediaPlayer:noOutputConversion
2018-02-02 19:17:23.954 [  1] E AuthDelegate:initFailed:reason=missingConfigurationValue,key=refreshToken
startsample.sh: line 3: 22120 Segmentation fault      TZ=UTC ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

**Comment by frozenberg** [comment]
Once you access http://127.0.0.1:3000/ and log in, your AlexaClientSDKConfig.json should be populated with a refresh token.

Were you presented with the opportunity to log in after running startauth.sh?

**Comment by tgraf2** [comment]
Yes.  I was able to login to Amazon successfully, but AlexaClientSDKConfig.json does not contain a refresh token.  Here is the "authDelegate" section of that file:

{
    "authDelegate":{
        // The Client Secret of the Product from developer.amazon.com
        "clientSecret":"${SDK_CONFIG_CLIENT_SECRET}",
        // Unique device serial number. e.g. 123456
        "deviceSerialNumber":"${SDK_CONFIG_DEVICE_SERIAL_NUMBER}",
        // Refresh Token populated by running AuthServer.py
        "refreshToken":"${SDK_CONFIG_REFRESH_TOKEN}",
        // The Client ID of the Product from developer.amazon.com
        "clientId":"${SDK_CONFIG_CLIENT_ID}",
        // Product ID from developer.amazon.com
        "productId":"${SDK_CONFIG_PRODUCT_ID}"
     },

**Comment by frozenberg** [comment]
Is that AlexaClientSDKConfig.json inside `avs-device-sdk/Integration` or in `build/Integration`? The AlexaClientSDKConfig.json that should be edited will be in your build directory.

**Comment by tgraf2** [comment]
AlexaClientSDKConfig.json is in /home/pi/avs-device-sdk/Integration.  
There is no folder called Integration in /home/pi/avs-device-sdk/build:

pi@raspberrypi:~ $ ls /home/pi/avs-device-sdk/build
BuildDefaults.cmake  cmake

**Comment by frozenberg** [comment]
Ok it looks like the build directory hasn't been set up.

Run `sudo bash setup.sh` and once that is done run the auth script again (`startauth.sh`).

Let me know how that works out.

**Comment by tgraf2** [comment]
**No luck yet.  I ran setup.sh again.  The final configuration is shown below:**

pi@raspberrypi:~ $ sudo bash setup.sh config.txt
...
==============> FINAL CONFIGURATION  ==============

{
    "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/db/alerts.db"
    },
    "certifiedSender":{
        "databaseFilePath":"/home/pi/db/certifiedSender.db"
    },
    "settings":{
        "databaseFilePath":"/home/pi/db/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
    },
    "notifications":{
        "databaseFilePath":"/home/pi/db/notifications.db"
    },
    "authDelegate":{
      "clientId":"amzn1.application-oa2-client.9a5f4068....",
        "clientSecret":"2356bf1c47418fe20aaa389ce32f77a3461995......",
        "deviceSerialNumber":"012345",
        "refreshToken":"",
        "productId":"alexa_pi"
    }
}

==============> SAVING AUDIO CONFIGURATION FILE ==============

**Then I ran sudo bash startauth.sh, which crashed:**

pi@raspberrypi:~ $ sudo bash startauth.sh
Traceback (most recent call last):
  File "AuthServer/AuthServer.py", line 82, in <module>
    configData = commentjson.load(configFile)
  File "/usr/local/lib/python2.7/dist-packages/commentjson/commentjson.py", line 94, in load
    raise JSONLibraryException(e.message)
commentjson.commentjson.JSONLibraryException: JSON Library Exception

Exception thrown by JSON library (json): JSON Library Exception

Exception thrown by JSON library (json): No JSON object could be decoded

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/commentjson/commentjson.py", line 57, in loads
        return json.loads('\n'.join(lines), **kwargs)
      File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
    

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/commentjson/commentjson.py", line 92, in load
        return loads(fp.read(), **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/commentjson/commentjson.py", line 59, in loads
        raise JSONLibraryException(e.message)
    JSONLibraryException: JSON Library Exception
    
    Exception thrown by JSON library (json): No JSON object could be decoded
    
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/commentjson/commentjson.py", line 57, in loads
            return json.loads('\n'.join(lines), **kwargs)
          File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
            return _default_decoder.decode(s)
          File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
            raise ValueError("No JSON object could be decoded")
        ValueError: No JSON object could be decoded

**Comment by frozenberg** [comment]
That is a strange error and suggests something strange about the directory you are working within. Can you try starting in a fresh directory? The script should not have crashed if the config file was in the right location.

Thanks

**Comment by tgraf2** [comment]
I reinstalled the sample app and it is now operating.  Thanks for your help.

**Comment by frozenberg** [comment]
No worries! Glad it's working.

**Comment by srinivasankh** [comment]
I got the exact same issue yesterday (_AuthDelegate:initFailed:reason=missingConfigurationValue,key=refreshToken_), now as per the suggestion from @frozenberg I will try to re-install in a fresh directory soon and check. But @tgraf2 is this what you have done to resolve the issue? 

Thanks,
Srini

**Comment by tgraf2** [comment]
Yes.  My mistake was I assumed "The refresh request failed with the response code 400." was an error!  You should ignore that message and continue with the install.  That worked for me, the second time around.

**Comment by srinivasankh** [comment]
I tried new install in fresh directory, now I am getting Internal Server error in the web browser after I enter http://127.0.0.1:3000 and then entering my Amazon credentials. Simultaneously when I checked , there is a syntax error: 
AttributeError: 'dict' object has no attribute 'has_key' - 
for the line 'if not tokenRequest.json().has_key('refresh_token'):'
I am using Python 3.5.3 and I know .has_key is removed form Python 3.5*
can you please let me know how this can be changed to:
if refresh_token not in tokenRequest.jason()
will this work? @tgraf2  @frozenberg 

Thanks in advance,
Srini

**Comment by srinivasankh** [comment]
@tgraf2 @frozenberg  I just commented that 'if' statement in that Python source code and now I am able to authenticate the request. Next I tried to run 'sudo bash startsample.sh' but it currently saying 'Alexa is currently idle!' --- should I try anything else?

**Comment by celinval** [comment]
Hi @srinivasankh,

Do you see any error while running the startsample.sh? Can you interact with the SampleApp?

**Comment by anubhavaich** [comment]
I had a similar problem, I realized there was a conflict between https and http. I added samle links with http in Allowed origin and Allowed return and it worked for me.
