### ISSUE TITLE
cmake fails on AudioResources

### ISSUE THREAD

**Issue by Killuaa27** [alexa/avs-device-sdk#494]
When I try to build the project using: 
`cmake /home/luigi/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/luigi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/luigi/sdk-folder/third-party/portaudio/include && make`
it fails.

My {HOME} is /home/luigi/

I've already read [that looks similar](https://github.com/alexa/avs-device-sdk/issues/249), tried `rm -r sdk-build` but the problem persists.

I am usign
- Laptop with Ubuntu 17.10
- gcc version 7.2.0

The error: 

Scanning dependencies of target AudioResources
[ 64%] Building CXX object ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/AlertsAudioFactory.cpp.o
[ 64%] Building CXX object ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/AudioFactory.cpp.o
[ 64%] Building CXX object ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/NotificationsAudioFactory.cpp.o
In file included from /home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/include/Audio/NotificationsAudioFactory.h:21:0,
                 from /home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/src/NotificationsAudioFactory.cpp:18:
/home/luigi/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/Audio/NotificationsAudioFactoryInterface.h:36:18: error: ‘function’ in namespace ‘std’ does not name a template type
     virtual std::function<std::unique_ptr<std::istream>()> notificationDefault() const = 0;
                  ^~~~~~~~
In file included from /home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/src/NotificationsAudioFactory.cpp:18:0:
/home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/include/Audio/NotificationsAudioFactory.h:33:10: error: ‘function’ in namespace ‘std’ does not name a template type
     std::function<std::unique_ptr<std::istream>()> notificationDefault() const override;
          ^~~~~~~~
/home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/src/NotificationsAudioFactory.cpp:34:6: error: ‘function’ in namespace ‘std’ does not name a template type
 std::function<std::unique_ptr<std::istream>()> NotificationsAudioFactory::notificationDefault() const {
      ^~~~~~~~
/home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/src/NotificationsAudioFactory.cpp:29:38: error: ‘std::unique_ptr<std::basic_istream<char> > alexaClientSDK::applicationUtilities::resources::audio::notificationDefaultFactory()’ defined but not used [-Werror=unused-function]
 static std::unique_ptr<std::istream> notificationDefaultFactory() {
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/build.make:110: recipe for target 'ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/NotificationsAudioFactory.cpp.o' failed
make[2]: *** [ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/NotificationsAudioFactory.cpp.o] Error 1
CMakeFiles/Makefile2:7090: recipe for target 'ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/all' failed
make[1]: *** [ApplicationUtilities/Resources/Audio/src/CMakeFiles/AudioResources.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mradulan** [comment]
are you using version 1.4? can you try putting #include <functional> in home/luigi/sdk-folder/sdk-source/avs-device-sdk/ApplicationUtilities/Resources/Audio/src/NotificationsAudioFactory.cpp?

**Comment by mcchots** [comment]
I had to add `#include <functional>` to 
 ```   
~/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/Audio/NotificationsAudioFactoryInterface.h
```    
as well to get it to compile successfully.

**Comment by mradulan** [comment]
If the issue is resolved, can you close it.

**Comment by Killuaa27** [comment]
Solved, thank you all
