### ISSUE TITLE
Unable to set alarm tone or volume

### ISSUE THREAD

**Issue by SpecificOcean** [alexa/avs-device-sdk#496]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am unable to control the alarm sound or volume for set alarms, with alexa or through the web app.

## What is the expected behavior?
Volume and tone should be able to be set in the alarms setting page on the alexa web app.

## What behavior are you observing?
No volume controls

### What version of the AVS Device SDK are you using?
      v1.4

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mradulan** [comment]
unfortunately for 3P devices, the volume controls are not there on the companion app. We will check this and update you.

**Comment by mradulan** [comment]
You can set the volume of alerts through the sample app options. In the menu, select 'p' and then '2' to  change the volume of alerts.

<img width="631" alt="screen shot 2018-02-06 at 12 51 56 pm" src="https://user-images.githubusercontent.com/28738524/35883667-de855ef2-0b3c-11e8-81d7-09bd1b360656.png">

The volume controls on the companion app will be added in the coming months.

**Comment by SpecificOcean** [comment]
@mradulan I know you can change the volume in the app, but i would also like to be able to configure the alarm tone, because I find the default one to be a tad too gentle.

**Comment by mradulan** [comment]
In the SDK we are not supposed to change the alarm tone. However, if you want to change it, you can run the script download the sound files from: https://developer.amazon.com/avs/home.html#/avs/previews/details/Alexa%20sound%20library%20for%20AVS
 and use the create_header.bash in "ApplicationUtilities/Resources/Audio/include/Audio/Data/" to create a header and then xxd.

**Comment by GYJohn** [comment]
Other volume question.
Normaly it should be posible to volume up a radio channel viva voice, isn't it?

**Comment by celinval** [comment]
Hi @GYJohn,

The SampleApp allow you to set volume for two different groups: 

1. Speech and content channels
2. Alert channels

You can adjust group 1's volume using the sample app menu as well as voice command. The second group you can configure using the sample app menu.
