### ISSUE TITLE
No start/stop listening sound

### ISSUE THREAD

**Issue by FL550** [alexa/avs-device-sdk#498]
## Briefly summarize your issue:
When running the sampleApp everything works fine, except the start and stop listening sounds are not there.  I can talk to Alexa and she answers me, but not with start/stop sound. 
I've run the test and a few of them failed in the first run, but after re-running the specific tests all went through. But the problem still exists.

## Provide the steps to reproduce the issue, if applicable:
Run only `sudo bash startsample.sh`

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- Raspberry Pi
### Tell us about your OS (Type & version):
-  Raspbian Stretch

I am using the 3,5mm jack of the pi for audio output and an usb mic for audio input.

Thanks in advance!

**Comment by mradulan** [comment]
I think you are talking about Attention sounds.  The SampleApp doesn't currently implement attention sounds. There is a solution in #364 on modifying the SDK for attention sounds.

**Comment by FL550** [comment]
Oh, I was unaware of this. Thanks, I will implement it then on my own. 
A hint on the project page about is might be usefull for others who run into this.
