### ISSUE TITLE
Does amazon plan to provide a C/C++ based AuthServer?

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#501]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Python is a little heavy on an embedded device which has limited flash . Does Amazon have a plan to develop a C/C++ based AuthServer to replace the current Python based AuthServer?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hi [Subjectxbj](https://github.com/subjectxbj),

No, there are no plans to create a C/C++ version of AuthServer.py.  AuthServer.py does not model any of the **device** side behaviors of the various methods for authorizing your device or application to access AVS (see [Authorization](https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#authorization for details on those methods)).  We are considering adding code to the SDK for the device side of those behaviors as time allows and as it becomes clear which ones would provide the most benefit to developers.

Thank you,
-SWH

**Comment by sanjayrd** [comment]
Closing for now, but please re-open if you have any further questions.

Thanks,
Sanjay
