### ISSUE TITLE
Alexa is currently idle! 

### ISSUE THREAD

**Issue by demayod684** [alexa/avs-device-sdk#503]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When attempting to run the sample app, I'm given this error below.

## What behavior are you observing?
I can't pinpoint what is causing the problem.

### What version of the AVS Device SDK are you using?
  Seems to be 1.4.0
  

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi 2 B
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

After running:

 cd /home/pi/sdk-folder/sdk-build/SampleApp/src && TZ=UTC ./SampleApp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/alexa-rpi/models

Im greeted with:

2018-02-10 00:56:18.583 [  1] I sdkVersion: 1.4.0
#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Illegal instruction

Any input would be greatly appreciated!

Thanks so much.

**Comment by demayod684** [comment]
Haven't figured it out yet, but hopefully someone can chime in. I feel like I've followed the steps, but I must be missing something

**Comment by celinval** [comment]
Hi @demayod684,

Is the sample-app working despite the warnings? Can you please run SampleApp with DEBUG9, execute the steps bellow and attach your log to this issue?

- Say something like "Alexa what's the weather?".
- Press "t" followed by Enter key. Then say "what's the weather?"

Thanks,

**Comment by scotthea-amazon** [comment]
Hi demayod684,

You need to build -DCMAKE_BUILD_TYPE=DEBUG if you want to get DEBUG (0-9) level logs (otherwise they are compiled out).

Cheers,
-SWH

**Comment by demayod684** [comment]
@celinval @scotthea-amazon 
So I think I've rebuilt with DEBUG9 enabled now. I've added -DCMAKE_BUILD_TYPE=DEBUG to the CMAKE step. But looks like the same info is spit out.
./SampleApp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/alexa-rpi/models debug9
2018-02-17 13:02:23.336 [  1] I sdkVersion: 1.5.0
Running app with log level: DEBUG9
2018-02-17 13:02:23.385 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-17 13:02:23.386 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

#############################
#       Connecting...       #
#############################

########################################
#       Alexa is currently idle!       #
########################################

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Illegal instruction

**Comment by demayod684** [comment]
@celinval @scotthea-amazon
I also never see “listening” or anything beyond what I’ve pasted above. I can verify that the mic is functioning during the test wav step.

**Comment by mavamazon** [comment]
@demayod684 
Do you have bluetooth speakers or similar bluetooth device configured in your system?

**Comment by demayod684** [comment]
@mavamazon no BT devices setup / configured. I do have a hifiberry dac attached to the Pi. Wondering if this could be an issue, but I don't think the AVS shares and common pins with the dac. I've also been going straight out to the 3.5mm jack instead of setting up the dac.

**Comment by demayod684** [comment]
@mavamazon @celinval @scotthea-amazon 
Fresh install. Now removed HifiBerry DAC. Same issues as above. No change.

**Comment by idcrook** [comment]
I'm getting the same error running SampleApp on a Raspberry Pi Zero W

```
file ./SampleApp
./SampleApp: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=21cda0bc3a5ad8955bc2adac900b8eb84281612d, not stripped
```

**Comment by kencecka** [comment]
Hi @demayod684,

To make progress here, we really need to get your debug logs working.  Reviewing the comments above, it looks like you've taken all the correct steps to enable them, but perhaps did not get a clean rebuild.  Can you try the following:

1. Delete your build directory
2. Create a new build directory
3. Run your `cmake` command with `-DCMAKE_BUILD_TYPE=DEBUG`
4. Run `make`
5. Run `SampleApp` with the `DEBUG9` command-line option

This should give you a lot of additional logging which you can post here for review.

@idcrook: Can you post your questions as a separate github issue?  It's going to be hard to respond to you without confusing the thread with @demayod684.  To answer your question about the Pi Zero, we're not actively testing on Pi Zero, and there may have been some specific problems that cropped up, but I would not expect an Illegal instruction error on Pi Zero (unless - maybe - you were using a binary component such as Kitt.AI or Sensory wakeword).

Ken

**Comment by idcrook** [comment]
I didn't mean to steal the thread. I had posted my response after I noticed @McRacoon also had gotten the same error on a Pi Zero. The strace output snippet I thought my be useful to localize where 'Illegal Operation' was getting generated, as I am getting basically identical output (as was how I found this issue via google).  I was planning next to go through the same steps on a Pi 3 instead, rather than trying to figure out if it was Pi Zero specific. 

FYI,  I built the avs demo app using the `setup.sh` included in the repo. And I had a Kitt.AI built from source on the Pi Zero-- but I am not all sure if if the AVS sample setup.sh pulls in the local python library?

anyway, thanks for your response, and I won't muddle up this issue further.

**Comment by jabulonboaz** [comment]
@idcrook can you provide information on how u build on a Pi zero pls? 
Did u just follow the process described in that url u quoted and nothing else? 
I have build with that url in pi3 and moved the sd card on pi zero w but it won't start up Alexa.

**Comment by celinval** [comment]
Hi @demayod684, are you still having the same problem? Can you please follow @kencecka advice on how to compile the sample app on debug mode? Also, can you please run the sample app using gdb?

Thanks

**Comment by crashflow** [comment]
DEBUG is already enabled in the setup.sh for the SDK, does that cover the SampleApp as well? 

I have the same problem as above had built using the setup.sh, but got the same output, nothing more descriptive. Also Raspi Zero W. I'm not experienced at compiling, so if you can give me instructions with that in mind, I can re-compile and give everyone the info they need.

    cd $BUILD_PATH
    cmake "$SOURCE_PATH/avs-device-sdk" \
    "${CMAKE_PLATFORM_SPECIFIC[@]}" \
    -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON \
    -DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" \
    -DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include" \
    -DCMAKE_BUILD_TYPE=DEBUG

    cd $BUILD_PATH
    make SampleApp -j2

else
    cd $BUILD_PATH
    make SampleApp -j2

**Comment by priyagsenthil** [comment]
First 

1. rm -rf $BUILD_PATH
2. cd $BUILD_PATH
3.  cmake "$SOURCE_PATH/avs-device-sdk" 
"${CMAKE_PLATFORM_SPECIFIC[@]}" 
-DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON 
-DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" 
-DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include" 
-DCMAKE_BUILD_TYPE=DEBUG -> assuming u don't want WW enabled
4. make SampleApp -j 2
5. cd $BUILD_PATH/SampleApp/src
6. Lauch SampleApp ./SampleApp <configfile> DEBUG9

**Comment by dhpp** [comment]
Closing.  Please re-open if you require further input from us.

**Comment by rsanjeev525** [comment]
#######################################
#       Alexa is currently idle!       #
########################################

2019-01-24 04:47:28.283 [ 1f] 5 ExchangeHandler:ExchangeHandler:context=0x72202624
2019-01-24 04:47:28.283 [ 1f] 5 MessageRequestHandler:MessageRequestHandler:context=0x72202624,messageRequest=0x72112504
2019-01-24 04:47:28.283 [ 1f] 5 HTTP2MimeRequestEncoder:HTTP2MimeRequestEncoder:boundary=WhooHooZeerOoonie!,source=0x2139764
2019-01-24 04:47:28.283 [ 1f] 5 MimeResponseSink:MimeResponseSink:handler=0x2139768
2019-01-24 04:47:28.283 [ 1f] 5 HTTP2MimeResponseDecoder:HTTP2MimeResponseDecoder
2019-01-24 04:47:28.283 [ 1f] 5 HTTP2Transport:onMessageRequestSent:countOfUnfinishedMessageHandlers=1
2019-01-24 04:47:28.283 [ 1f] 5 HTTP2Transport:createAndSendRequest:type=POST,url=https\://avs-alexa-eu.amazon.com/v20160207/events
2019-01-24 04:47:28.284 [ 1f] 5 HTTP2MimeRequestEncoder:getRequestHeaderLines
2019-01-24 04:47:28.284 [ 1f] 5 MessageRequestHandler:getRequestHeaderLines
2019-01-24 04:47:28.284 [ 1f] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.382 [ 1e] 9 LibcurlHTTP2Connection:insertActiveStream:handle=0x2142180,streamId=AVSEvent-9
2019-01-24 04:47:28.383 [ 1e] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-9,size=1,nmemb=16384,userData=0x1f27798
2019-01-24 04:47:28.383 [ 1e] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=NEW
2019-01-24 04:47:28.383 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=NEW,newState=GETTING_1ST_PART_HEADERS
2019-01-24 04:47:28.383 [ 1e] 5 MessageRequestHandler:getMimePartHeaderLines
2019-01-24 04:47:28.383 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.383 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=GETTING_1ST_PART_HEADERS,newState=SENDING_1ST_BOUNDARY
2019-01-24 04:47:28.383 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_1ST_BOUNDARY,newState=SENDING_PART_HEADERS
2019-01-24 04:47:28.384 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_PART_HEADERS,newState=SENDING_PART_DATA
2019-01-24 04:47:28.384 [ 1e] 5 MessageRequestHandler:onSendMimePartData:size=16277
2019-01-24 04:47:28.384 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.384 [ 1e] 5 MessageRequestHandler:onSendMimePartData:size=16115
2019-01-24 04:47:28.384 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.384 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_PART_DATA,newState=SENDING_END_BOUNDARY
2019-01-24 04:47:28.384 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_END_BOUNDARY,newState=GETTING_NTH_PART_HEADERS
2019-01-24 04:47:28.384 [ 1e] 5 MessageRequestHandler:getMimePartHeaderLines
2019-01-24 04:47:28.385 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.385 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=GETTING_NTH_PART_HEADERS,newState=SENDING_TERMINATING_DASHES
2019-01-24 04:47:28.385 [ 1e] 9 HTTP2MimeRequestEncoder:setState:state=SENDING_TERMINATING_DASHES,newState=DONE
2019-01-24 04:47:28.385 [ 1e] 9 LibcurlHTTP2Request:readCallback:id=AVSEvent-9,size=1,nmemb=16384,userData=0x1f27798
2019-01-24 04:47:28.385 [ 1e] 5 HTTP2MimeRequestEncoder:onSendData:size=16384,state=DONE
2019-01-24 04:47:28.891 [ 1e] 9 LibcurlHTTP2Request:headerCallback:id=AVSEvent-9,size=1,nmemb=13,userData=0x1f27798
2019-01-24 04:47:28.891 [ 1e] 5 HTTP2MimeResponseDecoder:onReceiveResponseCode:responseCode=204
2019-01-24 04:47:28.891 [ 1e] 5 MimeResponseSink:onReceiveResponseCode:responseCode=204
2019-01-24 04:47:28.891 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.891 [ 1e] 5 MessageRequestHandler:onReceiveResponseCode:responseCode=204
2019-01-24 04:47:28.891 [ 1e] 5 MessageRequestHandler:reportMessageRequestAcknowledged
2019-01-24 04:47:28.892 [ 1e] 5 HTTP2Transport:onMessageRequestAcknowledged
2019-01-24 04:47:28.892 [ 1e] 5 HTTP2MimeResponseDecoder:onReceiveHeaderLine:line=HTTP/2 204 

2019-01-24 04:47:28.892 [ 1e] 5 MimeResponseSink:onReceiveHeaderLine:line=HTTP/2 204 

2019-01-24 04:47:28.892 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.892 [ 1e] 9 LibcurlHTTP2Request:headerCallback:id=AVSEvent-9,size=1,nmemb=32,userData=0x1f27798
2019-01-24 04:47:28.892 [ 1e] 5 HTTP2MimeResponseDecoder:onReceiveHeaderLine:line=access-control-allow-origin\: *

2019-01-24 04:47:28.892 [ 1e] 5 MimeResponseSink:onReceiveHeaderLine:line=access-control-allow-origin\: *

2019-01-24 04:47:28.893 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.893 [ 1e] 9 LibcurlHTTP2Request:headerCallback:id=AVSEvent-9,size=1,nmemb=82,userData=0x1f27798
2019-01-24 04:47:28.893 [ 1e] 5 HTTP2MimeResponseDecoder:onReceiveHeaderLine:line=x-amzn-requestid\: 06bf7bfffe055ed6-00003407-0000ac21-b6d7c8f072d7baa6-fb525abd-5

2019-01-24 04:47:28.893 [ 1e] 5 MimeResponseSink:onReceiveHeaderLine:line=x-amzn-requestid\: 06bf7bfffe055ed6-00003407-0000ac21-b6d7c8f072d7baa6-fb525abd-5

2019-01-24 04:47:28.893 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.893 [ 1e] 0 MimeResponseSink:receivedRequestId:value=x-amzn-requestid\: 06bf7bfffe055ed6-00003407-0000ac21-b6d7c8f072d7baa6-fb525abd-5
2019-01-24 04:47:28.893 [ 1e] 9 LibcurlHTTP2Request:headerCallback:id=AVSEvent-9,size=1,nmemb=2,userData=0x1f27798
2019-01-24 04:47:28.893 [ 1e] 5 HTTP2MimeResponseDecoder:onReceiveHeaderLine:line=

2019-01-24 04:47:28.894 [ 1e] 5 MimeResponseSink:onReceiveHeaderLine:line=

2019-01-24 04:47:28.894 [ 1e] 5 HTTP2Transport:onActivity
2019-01-24 04:47:28.894 [ 1e] 5 HTTP2MimeResponseDecoder:onResponseFinished:status=COMPLETE
2019-01-24 04:47:28.894 [ 1e] 5 MimeResponseSink:onResponseFinished:status=COMPLETE
2019-01-24 04:47:28.894 [ 1e] 5 MessageRequestHandler:onResponseFinished:status=COMPLETE,responseCode=204
2019-01-24 04:47:28.894 [ 1e] 5 MessageRequestHandler:reportMessageRequestAcknowledged
2019-01-24 04:47:28.894 [ 1e] 5 MessageRequestHandler:reportMessageRequestFinished
2019-01-24 04:47:28.895 [ 1e] 5 HTTP2Transport:onMessageRequestFinished:countOfUnfinishedMessageHandlers=0
2019-01-24 04:47:28.895 [ 1e] 0 LibcurlHTTP2Connection:streamFinished:streamId=AVSEvent-9,result=No error,CURLcode=0
2019-01-24 04:47:28.895 [ 1e] 9 LibcurlHTTP2Connection:releaseStream:streamId=AVSEvent-9
2019-01-24 04:47:28.895 [ 1e] 5 MessageRequestHandler:reportMessageRequestAcknowledged
2019-01-24 04:47:28.895 [ 1e] 5 MessageRequestHandler:reportMessageRequestFinished


I am getting this message not able to hear anything from Alexa

KIndly help
