### ISSUE TITLE
Alexa stops working after a period of time

### ISSUE THREAD

**Issue by SpecificOcean** [alexa/avs-device-sdk#504]
## Briefly summarize your issue:
I have a script that starts the sample app on boot, and alexa works, for a few hours. The time period seems to be fairly random, sometimes it will work all day after a reboot, other times it will only work for an hour or so. When alexa stops working, some commands such as "sudo service --status-all" will make alexa work again, but only with that command running.

## What is the expected behavior?
Alexa should not stop working after a short period of time

## What behavior are you observing?
Alexa stops working over the course of a few hours

## Provide the steps to reproduce the issue, if applicable:
Use a script to start alexa, and alexa will stop working at least once before 12 hours.

## Tell us about your environment:
Running headless using script to start alexa. 
### What version of the AVS Device SDK are you using?
      v1.4

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by celinval** [comment]
Hi @SpecificOcean,

Which command are you using to start the sample-app and which mechanism are you using to start it on boot? Can you please run the sample app with DEBUG9 and output to a log file and see if you get any specific error?

Thanks

Thanks

**Comment by a2ron** [comment]
could you share you script to launch the sample app on boot?

**Comment by kencecka** [comment]
Hi @SpecificOcean,

I'll second @celinval's request for a DEBUG9 log showing the activity leading up to SampleApp terminating.

In addition, you might want to try upgrading to SDK 1.5.  It has a fix for an issue where SIGPIPE could causes the process to exit prematurely.

Ken

**Comment by SpecificOcean** [comment]
Sorry for the delay, the script I am using to start alexa is just a fairly simple bash script in /etc/init.d. Clock.py is an unrelated script that also needs ran on boot

`#!/bin/bash
cd /home/pi/work/clock/LED && sudo python clock.py
cd /home/pi/work/ && sudo bash startsample.sh` 

This script worked fine for a good amount of time, however now when I reboot my device alexa starts, but stops functioning after ~5 minutes. The other script that is launched by my startup script continues to run for as long as i need it to, however alexa does not.

**Comment by celinval** [comment]
Hi @SpecificOcean, do you have any update?

**Comment by SpecificOcean** [comment]
How would I set up my startup script to run alexa with DEBUG9, and then after running how would i retrieve the log?

**Comment by celinval** [comment]
I would suggest you to modify the startsample.sh script to redirect the output to a file. In the line that starts with `./SampleApp` add a file redirection after DEBUG9. For example:

```
./SampleApp "/home/pi/workplace/build/Integration/AlexaClientSDKConfig.json" "/home/pi/workplace/third-party/alexa-rpi/models" DEBUG9 >& /tmp/sample-app.log
```

**Note:** Just do this temporarily because the log file will grow constantly, unless if you rotate the logs.

**Comment by dhpp** [comment]
Our 1.7 release is now available - please update as mentioned above.  I'll close this ticket for now - please re-open if that does not address your issue.  Thanks.
