### ISSUE TITLE
How to customize Alexa reminders?

### ISSUE THREAD

**Issue by Yuhanlolo** [alexa/avs-device-sdk#506]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi, I was able to put AVS on my mac and I'm thinking of getting a raspberry pi for the next step. But before I move forward, I want to customize the current reminder settings in terms of the wording, duration, and frequency. I found the documentation on recurring reminders [here](https://developer.amazon.com/docs/alexa-voice-service/alerts-overview.html#scenario3). However, I'm not sure where to start with the example code provided. Is this "directive" already in the AVS SDK where I can edit its variables? .

## What is the expected behavior?
Alexa can send reminders in a more flexible way with customized duration (e.g., other than 2 times ), and wording (can be different every time), etc.

## What behavior are you observing?
Currently, I can use the Amazon Alex app to set reminders, or just talk to Alexa. However, it only starts with "here's your reminder" every time, and always repeat twice.

### What version of the AVS Device SDK are you using?
AVS SDK 1.4

### Tell us what hardware you're using:
I'm using my mac now, but will be using raspberry pi later.

**Comment by celinval** [comment]
Hi @Yuhanlolo,

You can configure reminders either via voice command or the alexa app. The SDK supports recurrent reminders as well as one time only. The SDK will receive a SetAlarm directive from AVS with the reminder properties and execute them accordingly.

**Comment by Yuhanlolo** [comment]
@celinval Thanks for the response! But can I change the sounds and duration of the reminders? 

Also, this might be a new question, Alexa doesn't seem to hear or record my response to the reminder. When I check out the interaction history, it only records the conversation of me setting the reminder, but not how I response to the reminder when I receive it. Is there a way for me to have Alexa record my responses to reminders?

**Comment by celinval** [comment]
Hi @Yuhanlolo,

You can find instructions on how to change the sounds of the reminders on issue #496.

Are you talking about the recording available on the alexa app? If that's the case, the SDK cannot control what is recorded.

**Comment by sanjayrd** [comment]
Hi @Yuhanlolo,

The SDK only records when an interaction is begun (i.e. what you say after tap a button, or say "Alexa"). If you want to see your response to the reminder on the app, just say "Alexa" followed by your response. 

Hope that helps,
Sanjay
