### ISSUE TITLE
How to identify the device(AVS SDK) is currently in DND mode?

### ISSUE THREAD

**Issue by melancholyhua** [alexa/avs-device-sdk#508]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How to identify the device(AVS SDK) is currently in DND(Do Not Disturb) mode ?

## What behavior are you observing?

I can using voice command "Alexa, do not disturb" or Amazon Alexa App to configure DND mode as on and off.  However I would like to know have any flag to record this status in SDKv1.4. Please advise, thanks.

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- [X] Other - tell us more:
Cross compile on embedded

### Tell us about your OS (Type & version):
- [x] Linux

**Comment by celinval** [comment]
Hi @melancholyhua, the SDK is currently not aware of the DND mode.

**Comment by melancholyhua** [comment]
Hi @celinval ,

Thanks for your reply,  when does the SDK can support it? Have any possible include it in next release?

**Comment by celinval** [comment]
Hi @melancholyhua, thanks for your interest. We are considering adding code to the SDK to support DND mode as time allows and as it becomes clear which features would provide the most benefit to developers.
