### ISSUE TITLE
Sensory readFromStreamFailed

### ISSUE THREAD

**Issue by m2sillanpaa** [alexa/avs-device-sdk#51]
Hi.

I'm trying to use the SensoryKeywordDetector with my app. However I get constant errors regarding readFromStream:

> 2017-07-10 12:11:54.203 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut

I've verified that recording works (arecord -d 10 -f S16_LE -r 16000 test.wav) like sensory recommends. Playback also OK. What could I check next?

Logs from situation:
>  2017-07-10 12:11:48.627 [  1] I ConfigurationNode:initializeSuccess
> 2017-07-10 12:11:49.422 [  2] 0 HttpPost:doPostSucceeded:code=200
> 2017-07-10 12:11:49.423 [  2] 0 AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
> 2017-07-10 12:11:49.423 [  2] 0 AuthDelegate:onAuthStateChangeCalled:state=1,error=0
> 2017-07-10 12:11:49.423 [  1] 0 MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
> 2017-07-10 12:11:50.189 [  3] I ?:?::x-amzn-requestid: 124bb5fffebb33ac-0000025b-00021465-fd3c45bf74cc3e5f-4bd04311-1
> 2017-07-10 12:11:50.189 [  3] 0 MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=CONNECTED
> 2017-07-10 12:11:50.192 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0xf8f838,policy=NON_BLOCKING
> 2017-07-10 12:11:50.192 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0xf8f838,policy=NON_BLOCKING
> 2017-07-10 12:11:50.194 [  1] I SensoryKeywordDetector:License expires on 28 Oct 2017 00:00:00 GMT
> 2017-07-10 12:11:50.194 [  1] I SensoryKeywordDetector:Sensory library license does not expire for at least 60 more days.
> 2017-07-10 12:11:50.203 [  1] I DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0xfa1260,policy=BLOCKING
> init done
> 2017-07-10 12:11:51.203 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut
> 2017-07-10 12:11:52.203 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut
> 2017-07-10 12:11:53.203 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut
> 2017-07-10 12:11:54.203 [  4] I AbstractKeywordDetector:readFromStreamFailed:reason=readerTimeOut
> ...

**Comment by a2ron** [comment]
+1

**Comment by desenvolvr** [comment]
+2
