### ISSUE TITLE
Compile error on MacOS  error: invalid use of non-static data member 'wordSize'

### ISSUE THREAD

**Issue by anuj123** [alexa/avs-device-sdk#511]
I am running into issue building SampleApp on Mac, seems like I am running into issue similar to
https://github.com/alexa/avs-device-sdk/issues/201 but on MAC, probably compiler issue

➜  sdk-build make clean
➜  sdk-build make VERBOSE=1
/usr/local/Cellar/cmake/3.10.2/bin/cmake -H/Users/anujt/sdk-folder/sdk-source/avs-device-sdk -B/Users/anujt/sdk-folder/sdk-build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_progress_start /Users/anujt/sdk-folder/sdk-build/CMakeFiles /Users/anujt/sdk-folder/sdk-build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f AVSCommon/CMakeFiles/AVSCommon.dir/build.make AVSCommon/CMakeFiles/AVSCommon.dir/depend
cd /Users/anujt/sdk-folder/sdk-build && /usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/anujt/sdk-folder/sdk-source/avs-device-sdk /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon /Users/anujt/sdk-folder/sdk-build /Users/anujt/sdk-folder/sdk-build/AVSCommon /Users/anujt/sdk-folder/sdk-build/AVSCommon/CMakeFiles/AVSCommon.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f AVSCommon/CMakeFiles/AVSCommon.dir/build.make AVSCommon/CMakeFiles/AVSCommon.dir/build
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSDirective.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/AVSDirective.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/AVSDirective.cpp
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessage.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/AVSMessage.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/AVSMessage.cpp
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AVSMessageHeader.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/AVSMessageHeader.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/AVSMessageHeader.cpp
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AbstractConnection.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/AbstractConnection.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/AbstractConnection.cpp
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/AlexaClientSDKInit.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/AlexaClientSDKInit.cpp
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/Attachment.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/Attachment/Attachment.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/Attachment.cpp
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/AttachmentManager.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/Attachment/AttachmentManager.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/AttachmentManager.cpp
[  3%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachment.cpp.o
cd /Users/anujt/sdk-folder/sdk-build/AVSCommon && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DACSDK_LOG_MODULE=avsCommon -DAVSCommon_EXPORTS -DGSTREAMER_MEDIA_PLAYER -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/googletest-release-1.8.0/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/SDKInterfaces/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include -I/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/ThirdParty/rapidjson/rapidjson-1.1.0/include  -DNDEBUG -Wall -Werror -O2 -DRAPIDJSON_HAS_STDSTRING -fPIC   -std=c++11 -o CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachment.cpp.o -c /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/InProcessAttachment.cpp
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/InProcessAttachment.cpp:16:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/InProcessAttachment.h:19:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/Attachment.h:25:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/InProcessSDS.h:25:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/SharedDataStream.h:465:
/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/BufferLayout.h:467:57: error:
      invalid use of non-static data member 'wordSize'
    if (wordSize > std::numeric_limits<decltype(Header::wordSize)>::max()) {
                                                ~~~~~~~~^~~~~~~~
/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/SharedDataStream.h:344:31: note:
      in instantiation of member function
      'alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::BufferLayout::init'
      requested here
    if (!sds->m_bufferLayout->init(wordSize, maxReaders)) {
                              ^
/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/InProcessAttachment.cpp:32:26: note: in
      instantiation of member function
      'alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::create'
      requested here
        m_sds = SDSType::create(buff);
                         ^
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/src/Attachment/InProcessAttachment.cpp:16:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/InProcessAttachment.h:19:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/AVS/include/AVSCommon/AVS/Attachment/Attachment.h:25:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/InProcessSDS.h:25:
In file included from /Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/SharedDataStream.h:465:
/Users/anujt/sdk-folder/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/SDS/BufferLayout.h:474:59: error:
      invalid use of non-static data member 'maxReaders'
    if (maxReaders > std::numeric_limits<decltype(Header::maxReaders)>::max()) {
                                                  ~~~~~~~~^~~~~~~~~~
2 errors generated.
make[2]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/Attachment/InProcessAttachment.cpp.o] Error 1
make[1]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make: *** [all] Error 2
➜  sdk-build g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
➜  sdk-build /usr/bin/c++ --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
➜  sdk-build

## What is the expected behavior?
No compile errors should appear

Unable to build sample app due to compilation issue

## What behavior are you observing?
Compile errors while trying to build SampleApp

## Provide the steps to reproduce the issue, if applicable:
Follow https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

## Tell us about your environment:
<!--- Include as many relevant details about the environment you experienced the bug in -->
### What version of the AVS Device SDK are you using?
     I cloned the latest sdk from repository, I am following this guide

     https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

### Tell us what hardware you're using:
- [ ]  Laptop



### Tell us about your OS (Type & version):

- [10.11.6 ] MacOS

**Comment by celinval** [comment]
Hi @anuj123,

Can you please try to install a newer version of Clang? This issue is related to older versions of Clang.

Thanks,

**Comment by anuj123** [comment]
Thanks I figured that out , was able to fix it by installing newer version of Xcode and cli tools

**Comment by celinval** [comment]
Awesome! Thanks for getting back to us.
