### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by stanklord** [alexa/avs-device-sdk#512]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I noticed that the sdk has been updated, what is the proper way to go about updating the app?

### What version of the AVS Device SDK are you using?
      v1.4

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by celinval** [comment]
Great question @stanklord. I would follow these steps:

1. Create a backup of your AlexaClientSDKConfig.json
2. Go to the source code directory and run:
`git pull`
3. Go to your build directory and run:
`make SampleApp`
4. Copy your original AlexaClientSDKConfig.json to the Integration/ folder inside your build directory.
5. Run the sample app.

Please let me know how it goes.

**Comment by zeusshuang** [comment]
Hi Amazon team,
 
Not sure if I missed anything while upgrade to SDK 1.5.
After built it and I found it still print SDK Version 1.4.0
And I found a header file : SDKVersion.h.in , but I could not find the definition for the project version.
Could you have hint for it ?

**Comment by SpecificOcean** [comment]
After following the steps above I am having issues getting alexa to work again, its giving me errors regarding client ID, stating that it is invalid. However when I check the config.txt that is in the same directory as sampleapp.sh my client ID is still there, and appears to be correct. Has there been a change in how client id/secret are saved?

**Comment by kencecka** [comment]
Glad to hear you got it working.  I'll close this issue, but please reopen if you have further questions.

Ken
