### ISSUE TITLE
Unable to run the Sample App in Raspberry pi

### ISSUE THREAD

**Issue by srinivasankh** [alexa/avs-device-sdk#513]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have followed all the instructions mentioned in getting this sample app running in Raspberry Pi, but when I run the last command specified at Step 4, which is:

`cd /home/pi/sdk-folder/sdk-build/SampleApp/src && TZ=UTC ./SampleApp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/alexa-rpi/models`

I am getting the below error message:
**-bash: ./SampleApp: No such file or directory**
Is this command rightly mentioned in the Quick Start guide for Raspberry pi? I am not sure why time-zone is being set followed by ./SampleApp/

I think I might have not used this command rightly, also I am not able to run the SampleApp in debug mode as well.

Am I missing anything here? Do I need to build first to run the app? sorry for my limited knowledge here.

Apologies if this issue is raised before.

## What is the expected behavior?

SampleApp should be up and running

## What behavior are you observing?

Sample App not getting executed.

## Provide the steps to reproduce the issue, if applicable:

Same steps as in the Quick Guide for Raspberry pi.

### What version of the AVS Device SDK are you using?
      1.5.0 release Feb 02, 2018

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by celinval** [comment]
Hi @srinivasankh,

Can you please do the following and paste the output of steps 2 and 4:

1. Make a backup of AlexaClientSDKConfig.json. Let's say, copy it to your home folder: 
`cp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json ~/`
2. Rerun step 2 (Build the SDK)
3. Copy your backup json file back:
`cp ~/AlexaClientSDKConfig.json /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json `
4. Run:
`cd /home/pi/sdk-folder/sdk-build/SampleApp/src && ./SampleApp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/alexa-rpi/models`

Another thing you can try is to follow the simplified [Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script).

**Comment by srinivasankh** [comment]
Hi @celinval thanks for your reply, much appreciated. I realised my build was not right I already did re-run step 2 as you mentioned here and I was able to run the app but now I am facing some other issue 'Client not connected' :-(

**Comment by mavamazon** [comment]
@srinivasankh 
Could you please elaborate on the issue? Could you also provide the log output of the Sample App?
