### ISSUE TITLE
Activation sound?

### ISSUE THREAD

**Issue by SteveW94** [alexa/avs-device-sdk#514]
As I want to run the sample-app headless on my Pi3:

Is it possible somehow to enable the same "I am listening now"-Ping sound here, as in the Java-Sample app, as I wanna now when Alexa is triggered and listening (unintentionally^^) and it seems there is no sound-indicator enabled by default here.

Thanks

**Comment by FL550** [comment]
Hi Steve,

See issue #498. 
I've added a simple system call to the sound-files. The files can be downloaded here: [Click](https://developer.amazon.com/de/docs/alexa-voice-service/ux-design-attention.html)
The file i've modified is the **UIManager.cpp** in the folder **avs-device-sdk/SampleApp/src**.
The line added is this: 
`system("play /home/pi/alexa/sounds/med_ui_wakesound._TTH_.wav");`

after the `case DialogUXState::LISTENING:` call. 

Then go to the folder `build` and run `make SampleApp && TZ=UTC ./SampleApp "/home/pi/alexa/build/Integration/AlexaClientSDKConfig.json" "/home/pi/alexa/third-party/alexa-rpi/models" DEBUG9` as proposed here: https://github.com/alexa/avs-device-sdk/issues/479#issuecomment-362906877

Of course you have to change your paths according to your system.

**Comment by celinval** [comment]
Great question, @SteveW94. As @FL550 mentioned, the SampleApp does not support attention sounds yet. You can find some tips on how to implement them in #364.

Thanks

**Comment by SteveW94** [comment]
@FL550 Thanks for help! Worked perfectly! :)

**Comment by gerardwr** [comment]
@FL550 
I tried your suggestion to ad a play command after
```
case DialogUXState::LISTENING:
```

When "listening" I get the ping-sound, but after that AVS chages to "thinking", then to "idle", then the "ping", then to "listening", etc. So it "loops.

I tried:
- removing the play command, and it working fine again (no ping ofcourse)
- mute the sound to make sure that the ping-sound is not interpreted by AVS as a command

Any idea how come?

**Comment by gerardwr** [comment]
@FL550 
When I added the play command in UserInputManager like below it works fine, no "looping".
```
        } else if (x == TAP) {
            system("play /Users/gerard/sdk-folder/application-necessities/sound-files/med_ui_wakesound.wav");
            m_interactionManager->tap();
```

Any ideas?

**Comment by FL550** [comment]
@gerardwr 
That is weird, because on my system it works flawlessly. Maybe there is a problem with the audio output being blocked.

**Comment by gerardwr** [comment]
@FL550 
It IS weird. Especially since @SteveW94 reported your way working too!?

I just use the standard SampleApp, I assume you did too.

Hmmmmmmmmm.......
