### ISSUE TITLE
Alexa not Speaking

### ISSUE THREAD

**Issue by baddemiya** [alexa/avs-device-sdk#515]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Alexa is performing following functions - listening and thinking. logs have been attached herewith. however it not speaking.

## What is the expected behavior?
    Alexa should respond

## What behavior are you observing?
    no aoudio outut from Alexa. even though i can listen to songs from youtube.

## Provide the steps to reproduce the issue, if applicable:
     Provide the steps for reproduce

### What version of the AVS Device SDK are you using?
      <1.5.0>

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Raspbian Stretch

please help find a solution

**Comment by baddemiya** [comment]
logs after debug:

ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
2018-02-16 22:12:16.343 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-16 22:12:16.343 [  1] I SensoryKeywordDetector:License expires on 28 May 2018 00:00:00 GMT
2018-02-16 22:12:16.343 [  1] I SensoryKeywordDetector:Sensory library license does not expire for at least 60 more days.
                  #    #     #  #####      #####  ######  #    #              
                 # #   #     # #     #    #     # #     # #   #               
                #   #  #     # #          #       #     # #  #                
               #     # #     #  #####      #####  #     # ###                 
               #######  #   #        #          # #     # #  #                
               #     #   # #   #     #    #     # #     # #   #               
               #     #    #     #####      #####  ######  #    #              
                                                                              
       #####                                           #                      
      #     #   ##   #    # #####  #      ######      # #   #####  #####      
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
       #####  #    # # ## # #    # #      #####     #     # #    # #    #     
            # ###### #    # #####  #      #         ####### #####  #####      
      #     # #    # #    # #      #      #         #     # #      #          
       #####  #    # #    # #      ###### ######    #     # #      #          

       SDK Version 1.5.0

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Wake word:                                                                 |
|       Simply say Alexa and begin your query.                               |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Privacy mode (microphone off):                                             |
|       Press 'm' and Enter to turn on and off the microphone.               |
| Echo Spatial Perception (ESP): This is only for testing purpose only!      |
|       Press 'e' followed by Enter at any time to adjust ESP settings.      |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

############################
#       Listening...       #
############################

2018-02-16 22:12:19.365 [  2] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-16 22:12:19.366 [  2] I DirectiveProcessor:setDialogRequestIdLocked:oldValue=,newValue=d1ac797e-b54d-4576-a657-b8e1c118e14a
2018-02-16 22:12:29.930 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"8ad5538d-43dc-449b-91c5-d3da7d05cfa9"\,dialogRequestId\:""}
2018-02-16 22:12:29.931 [  4] I DirectiveRouter:preHandleDirective:messageId=8ad5538d-43dc-449b-91c5-d3da7d05cfa9,action=calling
2018-02-16 22:12:29.931 [  5] I DirectiveRouter:handleDirective:messageId=8ad5538d-43dc-449b-91c5-d3da7d05cfa9,action=calling
###########################
#       Thinking...       #
###########################

2018-02-16 22:12:30.030 [  6] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-16 22:12:30.031 [  6] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-02-16 22:12:31.611 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechSynthesizer"\,name\:"Speak"\,messageId\:"ae1ae658-1c41-4173-8efe-a443e2d46fc2"\,dialogRequestId\:"d1ac797e-b54d-4576-a657-b8e1c118e14a"}
2018-02-16 22:12:31.611 [  3] I DirectiveSequencer:onDirective:directive={"namespace\:"TemplateRuntime"\,name\:"RenderTemplate"\,messageId\:"5e8a74a3-892e-4660-a528-a1ed29973415"\,dialogRequestId\:"d1ac797e-b54d-4576-a657-b8e1c118e14a"}
2018-02-16 22:12:31.612 [  4] I DirectiveRouter:preHandleDirective:messageId=ae1ae658-1c41-4173-8efe-a443e2d46fc2,action=calling
2018-02-16 22:12:31.612 [  4] I DirectiveRouter:handleDirectiveWithPolicyHandleImmediately:messageId=5e8a74a3-892e-4660-a528-a1ed29973415,action=calling
2018-02-16 22:12:31.612 [  5] I DirectiveRouter:handleDirective:messageId=ae1ae658-1c41-4173-8efe-a443e2d46fc2,action=calling
##############################################################################
#     RenderTemplateCard                                                      
#-----------------------------------------------------------------------------
# Template Type       : BodyTemplate2
# Main Title          : Who was India's first president?
##############################################################################

2018-02-16 22:12:31.616 [  7] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-02-16 22:12:31.616 [  7] E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed
2018-02-16 22:12:31.788 [  7] I InProcessAttachmentReader:readFailed:reason=SDS is closed
###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

**Comment by celinval** [comment]
Hi @baddemiya ,

Can you please provide the following information:

1. Which audio output are you using? USB, Audio Jack, HDMI?

2. Can you please execute the following commands and add their output here:

    cat ~/.asoundrc
    aplay -l -L
    arecord -l -L
    arecord /tmp/test.wav
    aplay /tmp/test.wav

3. Can you please run the two commands below and see if you hear a beep?

    gst-launch-1.0 -m audiotestsrc ! autoaudiosink
    gst-launch-1.0 -m audiotestsrc ! alsasink

Thanks

**Comment by baddemiya** [comment]
1. audio forced through 3.5mm jack.

2.**pi@blueberry:~ $ cat ~/.asoundrc**
pcm.!default {
 type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
}

**pi@blueberry:~ $ aplay -l -L**
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
sysdefault:CARD=vc4hdmi
    vc4-hdmi, 
    Default Audio Device
front:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    Front speakers
iec958:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    Direct sample mixing device
dsnoop:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    Direct sample snooping device
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, 
    Hardware device with all software conversions
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi [vc4-hdmi], device 0: MAI PCM vc4-hdmi-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**pi@blueberry:~ $ arecord -l -L**
null
    Discard all samples (playback) or generate zero samples (capture)
default
sysdefault:CARD=C170
    Webcam C170, USB Audio
    Default Audio Device
front:CARD=C170,DEV=0
    Webcam C170, USB Audio
    Front speakers
surround21:CARD=C170,DEV=0
    Webcam C170, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=C170,DEV=0
    Webcam C170, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=C170,DEV=0
    Webcam C170, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=C170,DEV=0
    Webcam C170, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=C170,DEV=0
    Webcam C170, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=C170,DEV=0
    Webcam C170, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=C170,DEV=0
    Webcam C170, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=C170,DEV=0
    Webcam C170, USB Audio
    Direct sample mixing device
dsnoop:CARD=C170,DEV=0
    Webcam C170, USB Audio
    Direct sample snooping device
hw:CARD=C170,DEV=0
    Webcam C170, USB Audio
    Direct hardware device without any conversions
plughw:CARD=C170,DEV=0
    Webcam C170, USB Audio
    Hardware device with all software conversions
**** List of CAPTURE Hardware Devices ****
card 2: C170 [Webcam C170], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**pi@blueberry:~ $ arecord /tmp/test.wav**
Recording WAVE '/tmp/test.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono
^CAborted by signal Interrupt...
**pi@blueberry:~ $ aplay /tmp/test.wav**
Playing WAVE '/tmp/test.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono

3.
pi@blueberry:~ $ gst-launch-1.0 -m audiotestsrc ! autoaudiosink
bash: gst-launch-1.0: command not found
pi@blueberry:~ $ gst-launch-1.0 -m audiotestsrc ! alsasink
bash: gst-launch-1.0: command not found

please find details as requested.

thanks.

**Comment by baddemiya** [comment]
Hi @celinval,

After installing gst tools, i am hearing beep after - 
pi@blueberry:~ $ gst-launch-1.0 -m audiotestsrc ! alsasink.

But no sound after pi@blueberry:~ $ gst-launch-1.0 -m audiotestsrc ! autoaudiosink.

I also tried to change autoaudiosink to alsasink in Mediaplayer.cpp line 599.

Still facing the same issue.

Edit -couple of errors i am getting is Sds in closed and sdsreader:seek failed

**Comment by baddemiya** [comment]
Update - When audio is recorded at 16 bit 48000hz output is clear and crisp.

When it is recorded at 8 bit 8000hz output is hardly recongnizable. Just some noice in between another noice.

**Comment by a2ron** [comment]
I solved it! My response on [Issue 500](https://github.com/alexa/avs-device-sdk/issues/500#issuecomment-366829573).

**Comment by baddemiya** [comment]
@a2ron What you have mentioned i have already done. If i am missing anything pl mention. Thanks

**Comment by kencecka** [comment]
Hi @baddemiya,

Since you are able to get audio output with alsasink from gst-launch-1.0, and you are not getting audio from SampleApp after modifying MediaPlayer.cpp, I think we need to see additional logging for further clues.

Can you re-run cmake with `-DCMAKE_BUILD_TYPE=DEBUG`, and then run SampleApp with the `DEBUG9` command-line parameter, and then post the logs here?

Thanks,
Ken

**Comment by scotthea-amazon** [comment]
Hi @baddemiya,

There has been no further traffic since Ken's last request for more info over two weeks ago, so I am closing this issue.  Please feel free to re-open it if you have more information or this issue has been closed in error.

Thank you,
-SWH
