### ISSUE TITLE
pa_jack.c undefined reference, rpi3 Jessie a5646fc build

### ISSUE THREAD

**Issue by L4v3nd3r** [alexa/avs-device-sdk#518]
Hi there, serious newbie here, having some trouble compiling on Rpi3 jessie, following instructions from [a5646fc](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide/a5646fc9e6dde8128c940b86a9bbece7f65c1ace) but to no avail. Attempted to compile and install jackd, libjack-dev, jack2 e.t.c and even to the point of copying jack.h and types.h into jack folder in hostapi which was in pa_jack.c #include ,also recompiled portaudio and reconfigured the build and sudo make clean but still have not managed to solve the issue of undefined reference during build. Understand that it might have something to do with the libraries but don't know where or how to fix it. Thanks in advance!

 `[100%] Linking CXX executable SampleApp
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `GetStreamTime'                                          :
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference                                           to `jack_frame_time'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1738: undefined reference                                           to `jack_get_sample_rate'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `UpdateQueue':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1427: undefined reference                                           to `jack_get_sample_rate'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `JackCallback':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1562: undefined reference                                           to `jack_port_get_buffer'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `RealProcess':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1349: undefined reference                                           to `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1365: undefined reference                                           to `jack_frame_time'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1367: undefined reference                                           to `jack_port_get_latency'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1370: undefined reference                                           to `jack_port_get_latency'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1391: undefined reference                                           to `jack_port_get_buffer'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1402: undefined reference                                           to `jack_port_get_buffer'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `RealStop':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1688: undefined reference                                           to `jack_port_connected'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1690: undefined reference                                           to `jack_port_disconnect'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1696: undefined reference                                           to `jack_port_connected'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1698: undefined reference                                           to `jack_port_disconnect'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `StartStream':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference                                           to `jack_port_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference                                           to `jack_port_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1609: undefined reference                                           to `jack_connect'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference                                           to `jack_port_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference                                           to `jack_port_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1619: undefined reference                                           to `jack_connect'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `CleanUpStream'                                          :
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:983: undefined reference t                                          o `jack_port_unregister'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:988: undefined reference t                                          o `jack_port_unregister'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `OpenStream':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1080: undefined reference                                           to `jack_port_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1081: undefined reference                                           to `jack_client_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1087: undefined reference                                           to `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1181: undefined reference                                           to `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1214: undefined reference                                           to `jack_port_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1215: undefined reference                                           to `jack_port_register'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1224: undefined reference                                           to `jack_port_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1225: undefined reference                                           to `jack_port_register'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1241: undefined reference                                           to `jack_get_ports'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1245: undefined reference                                           to `jack_port_by_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1265: undefined reference                                           to `jack_get_ports'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1269: undefined reference                                           to `jack_port_by_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1301: undefined reference                                           to `jack_port_get_latency'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1302: undefined reference                                           to `jack_get_buffer_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1305: undefined reference                                           to `jack_port_get_latency'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1306: undefined reference                                           to `jack_get_buffer_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1310: undefined reference                                           to `jack_frame_time'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `Terminate':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:820: undefined reference t                                          o `jack_deactivate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:825: undefined reference t                                          o `jack_client_close'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `IsFormatSuppor                                          ted':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference t                                          o `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference t                                          o `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:918: undefined reference t                                          o `jack_get_sample_rate'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `PaJack_Initial                                          ize':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:733: undefined reference t                                          o `jack_client_open'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `BuildDeviceLis                                          t':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:491: undefined reference t                                          o `jack_client_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:492: undefined reference t                                          o `jack_client_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:499: undefined reference t                                          o `jack_get_ports'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:517: undefined reference t                                          o `jack_client_name_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:558: undefined reference t                                          o `jack_get_sample_rate'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:589: undefined reference t                                          o `jack_get_ports'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:596: undefined reference t                                          o `jack_port_by_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:598: undefined reference t                                          o `jack_port_get_latency'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:610: undefined reference t                                          o `jack_get_ports'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:617: undefined reference t                                          o `jack_port_by_name'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:619: undefined reference t                                          o `jack_port_get_latency'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `PaJack_Initial                                          ize':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:781: undefined reference t                                          o `jack_on_shutdown'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:782: undefined reference t                                          o `jack_set_error_function'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:783: undefined reference t                                          o `jack_get_buffer_size'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:785: undefined reference t                                          o `jack_set_sample_rate_callback'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:786: undefined reference t                                          o `jack_set_xrun_callback'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:800: undefined reference t                                          o `jack_client_close'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:787: undefined reference t                                          o `jack_set_process_callback'
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:788: undefined reference t                                          o `jack_activate'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `PaJack_SetClie                                          ntName':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1750: undefined reference                                           to `jack_client_name_size'
/home/pi/local-builds/lib/libportaudio.a(pa_jack.o): In function `PaJack_GetClie                                          ntName':
/home/pi/sources/portaudio/src/hostapi/jack/pa_jack.c:1765: undefined reference                                           to `jack_get_client_name'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:356: recipe for target 'Sample                                          App/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:7590: recipe for target 'SampleApp/src/CMakeFiles/SampleApp                                          .dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by mavamazon** [comment]
Hi Lavender!

If you use the latest version of the SDK, please use the latest version of the [Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide). 

Please make sure that you built PortAudio without Jack dependency:
./configure --without-jack
This line is missing in the guide you used.

**Comment by L4v3nd3r** [comment]
Hi mavamazon, thanks for the tip, however i have another app running on my rpi which require jessie dependencies and hence i cannot port over to stretch. so Stretch is out of the question.

**Comment by L4v3nd3r** [comment]
and will try --without-jack again, i did try that once but it didn't work.

**Comment by mavamazon** [comment]
You can also try to link against jack libraries in SampleApp/src/CmakeLists.txt.

**Comment by L4v3nd3r** [comment]
i don't remember seeing any of them there, will check again thanks... right now i'm having a loosing battle against compiling an openssl 1.0.2 with a curl 7.50.2 that will work with a jessie cmake... the libraries are all over the place haha...

**Comment by mavamazon** [comment]
Please don't give up! AVS SDK team is counting on you!
Meanwhile please let me know if any of the above helps.

**Comment by L4v3nd3r** [comment]
I managed to solve that issue by compiling cmake 3.6.3 from source. cmake 3.6.2 does not agree with curl 7.50.2 libraries. On to the next step of compiling.

**Comment by L4v3nd3r** [comment]
You advice --without-jack worked like a charm! thank you! after much hiccups i managed to compile sample app with success , few notes, the jessie build tutorial leaves cmake libraries broken because 3.6.2 is not compatible with 7.50.2, cmake must be recompiled to version 3.6.3 from source.

**Comment by mavamazon** [comment]
Thank you for your response and suggestion! I will close the ticket. Feel free to reopen it if you have more questions regarding this issue.
