### ISSUE TITLE
Setup Error on Raspberry PI3: CMake: A required package was not found

### ISSUE THREAD

**Issue by jianwu** [alexa/avs-device-sdk#520]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Setup Error on Raspberry PI3, with error: CMake: A required package was not found

## What is the expected behavior?
Should install succefully

## What behavior are you observing?
The error message on the console is: 

==============> BUILDING SDK ==============

-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Creating the build directory for the AlexaClientSDK with build type: DEBUG
WARNING: Logging of sensitive information enabled!
Creating AlexaClientSDK with keyword detector type: Sensory
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--
--
CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:28 (include)
  CMakeLists.txt:7 (include)

-- Configuring incomplete, errors occurred!
See also "/home/pi/Downloads/build/CMakeFiles/CMakeOutput.log".

## Provide the steps to reproduce the issue, if applicable:
I follow the Raspberry PI instruction. I got above error after following step: 
sudo bash setup.sh config.txt
I also tried run 
sudo apt-get upgrade
sudo apt-get update

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [x] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Sorry, but this script is intended for Raspbian Stretch only - the parent document for this guide explicitly says that the script installation is for Stretch. We have also updated the guide to state that explicitly as well.

Please be advised to upgrade to Stretch.

If you still want to install on Jessie, please review [this guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide).

**Comment by jianwu** [comment]
Thanks for the information. I didn't notice it.  I'll try to upgrade my raspberry pi.
