### ISSUE TITLE
When Set Timer ends : WARNING:  GetCurrentIOBufferFrameSize...not implemented"

### ISSUE THREAD

**Issue by gerardwr** [alexa/avs-device-sdk#521]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I can set a timer OK. When the Timer edns it "beeps" but also results in  a WARNING. 

## What is the expected behavior?
no warning

## What behavior are you observing?
When Timers ends, Alexa repeats forever:
- double "beep"
- displays a WARNING
Pressing "s" stops this, and functions normally again.

## Provide the steps to reproduce the issue, if applicable:
- say "set timer for 15 seconds"
- Alexa speaks "15 seconds, starting now"
- after 15 seconds, beeps and warning
- press "s" to stop

See log below:

```
############################
#       Listening...       #
############################

###########################
#       Thinking...       #
###########################

###########################
#       Speaking...       #
###########################

########################################
#       Alexa is currently idle!       #
########################################

2018-02-18 23:49:42.254 SampleApp[73930:4009527] 23:49:42.254 WARNING:  38: virtual int AQMEIO_AU::GetCurrentIOBufferFrameSize(): called but not implemented
2018-02-18 23:49:48.326 SampleApp[73930:4009527] 23:49:48.326 WARNING:  38: virtual int AQMEIO_AU::GetCurrentIOBufferFrameSize(): called but not implemented
s
```

### What version of the AVS Device SDK are you using?
1.5.0

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!

You mentioned that you have to press "s" to stop this behavior, does it mean that application stops functioning normally after the warning messages? Do you hear only two "beeps" and then nothing or it continuously beeps until you ask it to stop?

**Comment by mavamazon** [comment]
I think you may safely ignore this. This seems to be a GStreamer warning that does not affect the actual user experience.

Anyway, please let me know if it was always reproducible right from the start or there was some action that caused GStreamer to behave like that?

**Comment by gerardwr** [comment]
@mavamazon 

One interesting addition to my previous post.

When I end SampleApp with ctr+c (while beeping away) the program is interupted, and stop naturally stops beeing.

But, when I restart the SampleApp anew it immediately resumes the "beeping"warning" even before the "menu" appears.

The SampleApp has an excellent memory ;-)

**Comment by gerardwr** [comment]
@mavamazon 

I'm afraid that ingnoring is impossbly. A alarm going off every second "forever" DOES affect the actual user experience in a horrible way. It literally makes "timers" impossible to use.

Yes, it's reproducible right from the start. After a restart, my command "set timer to 5 seconds", and the respons "5 seconds starting now" its starts "beeping away" after the 5 seconds.

Tell me if need some further testing for you.

**Comment by mavamazon** [comment]
@gerardwr 
I am afraid that this IS the expected behavior. Alarm will sound for a pretty long time unless you stop or snooze it. Also, in order to handle power outage any unstopped alarm will sound again if scheduled to the last 30 minutes before the application start.

**Comment by gerardwr** [comment]
@mavamazon 

Aaaaahhh, I get it now, that IS a sensible behaviour. Thanks for clearing that up.

Could you give an indication what the warning is about, is it GStreamer?

**Comment by mavamazon** [comment]
The only thing I found is probably the same as you did while googling:
https://forum.openframeworks.cc/t/gstreamer-getcurrentiobufferframesize-not-implemented-warning/15568

So it seems to be related to either GStreamer or its plugins. This is definitely not an SDK warning.

**Comment by gerardwr** [comment]
Thanks for the link, missed that one.

As you suggested, I 'have to live with it" for now.

I will close this issue now.

Thanks for your kind support, is appreciated.

Closing this issue now.
