### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by syl22-00** [alexa/avs-device-sdk#522]
There is an annoying typo in one of the github's wiki page:

In https://github.com/alexa/avs-device-sdk/wiki/Unit-and-Integration-Tests, in line:
```
cmake <absolute-path-to-source> -DNETWORK_INTEGRATION_TESTS=ON –DNETWORK_INTERFACE=eth0
```
There is a `–` instead of `-` in the second option which makes cmake interpret it as a path rather than an option.

**Comment by mavamazon** [comment]
Hi!

Thank you very much for letting us know! I've made the changes to the wiki.

I am closing the ticket. Feel free to reopen it in case you have more questions.
