### ISSUE TITLE
Failing Integration Tests

### ISSUE THREAD

**Issue by syl22-00** [alexa/avs-device-sdk#526]
On my environment, some Integration Tests always fail. Unit tests all pass.

Failing Integration Tests are:

* AlexaDirectiveSequencerLibraryTest.sendDirectiveWithoutADialogRequestID
* AlexaDirectiveSequencerLibraryTest.oneBlockingDirectiveInTheMiddle
* AlexaCommunicationsLibraryTest.testSendEvent
* AlexaCommunicationsLibraryTest.testSendEventsConcurrently
* AlexaCommunicationsLibraryTest.testReceiveDirectiveOnDownchannel
* AlexaCommunicationsLibraryTest.testPersistentConnection
* AudioPlayerTest.FlashBriefing
* SpeechSynthesizerTest.handleMultipleConsecutiveSpeaks

From the logs output in the console, here are some of the errors:

```
Value of: messageRequest->waitFor(expectedStatus, timeout)
  Actual: false
Expected: true
```
```
Value of: playbackNearlyFinishedFound
  Actual: false
Expected: true
```
```
Expected: status
      Which is: 4-byte object <01-00 00-00>
To be equal to: std::future_status::ready
      Which is: 4-byte object <00-00 00-00>
```
```
Failure
Expected: (params.type) != (TestDirectiveHandler::DirectiveParams::Type::TIMEOUT), actual: 4-byte object <05-00 00-00> vs 4-byte object <05-00 00-00>
```

Environment is Linux 16.04, 64 bits. Latest available SDK was built against `libcurl` compiled with `mbedtls` and `nghttp2`, [as described in your wiki](https://github.com/alexa/avs-device-sdk/wiki/Build-libcurl-with-mbed-TLS-and-nghttp2). `GSTREAMER_MEDIA_PLAYER`, `KITTAI_KEY_WORD_DETECTOR` and `PORTAUDIO` are all `ON`.

**Comment by mavamazon** [comment]
Thank you for reported issues! We are going to look deeper into it.

**Comment by sanjayrd** [comment]
Hi @syl22-00,

Based on your response, it sounds like these are only integration test failures. In general, some of our integration tests are flaky. This is especially true with the issues that you posted here as they seem mostly related to timeouts. We are working on fixing these to make them more rigid. If the Sample App is generally working for you well, and the unit tests consistently pass, then I wouldn't worry too much about it.

Thanks,
Sanjay

**Comment by syl22-00** [comment]
There is also the Network integration test, which does not build. Please see https://github.com/alexa/avs-device-sdk/issues/523 (issue was closed not because it was resolved but should be addressed as part of this issue).

**Comment by celinval** [comment]
Hi @syl22-00,

Which Linux are you using? is it Ubuntu? I'm using Ubuntu 16.04, and all the integration tests are passing for me.

Regarding AudioPlayerTest.FlashBriefing, have you enabled any flash briefing skill in your Alexa account? If you run the SampleApp and ask alexa for your flash briefing, does it work?

**Comment by dhpp** [comment]
Closing.  Please re-open if you would like further assistance from us, thanks.
