### ISSUE TITLE
Incorrect Alexa responses

### ISSUE THREAD

**Issue by az2022** [alexa/avs-device-sdk#527]
I see that on some occasions the responses coming back from Alexa is incorrect, i.e. in the history log I see the question gets interpreted correctly but the response is something weird. I have attached couple screenshots for this. 

This may not matter but am using Raspbian on a dual core ARM-Cortex A9.

![alexa_query_error1](https://user-images.githubusercontent.com/31804178/36475748-94b738dc-16f3-11e8-8bf3-0d1390080562.PNG)
![alexa_query_error2](https://user-images.githubusercontent.com/31804178/36475752-9953fccc-16f3-11e8-9c59-02b7bfc93919.PNG)

**Comment by mavamazon** [comment]
Hi @az2022!

Does it happen with all of your requests?

Could you please listen to your questions as they were heard by the Alexa (a triangle play button under the "Voice feedback") and see if the sound is clear enough. If it is too noisy you should probably make sure that you are using the fully functioning mic. You could also try to record some audio and play it back locally to see if the sound is ok:
arecord /tmp/test.wav
aplay /tmp/test.wav

Please let me know what was your experience with the sound.

**Comment by az2022** [comment]
No, not with all the requests. The confusion is, AVS's voice feedback as shown in attached pics, is converting to text correctly, for e.g. the comment next to "Alexa heard" is correct, i.e. 'spell hyderabad', 'who is working with you' but when it comes to responding it gets converted to 'spell butt' and 'who was the you' respectively.

**Comment by mavamazon** [comment]
@az2022,

After some investigation all I can suggest is just post a question to the [AVS Forum](https://forums.developer.amazon.com/spaces/38/index.html). SDK team is unable to help you with this matter, sorry.

**Comment by az2022** [comment]
Is it because it may not be related to SDK and probably to AVS cloud?

**Comment by mavamazon** [comment]
Yes, it is not related to the SDK, since SDK just delivers your voice to AVS and all the recognition and interpretation is done there.
