### ISSUE TITLE
Cloning Error in Raspberry Pi Guide with Script

### ISSUE THREAD

**Issue by niccolospa** [alexa/avs-device-sdk#529]
I'm getting this after launching `sudo bash setup.sh config.txt`
 ==============> CLONING SDK ==============

Cloning into 'avs-device-sdk'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection expired
github.com[1: 192.30.253.113]: errno=Connection expired

I'm using a Raspberry Pi 3 with Stretch, can someone help to sort this out?

**Comment by mavamazon** [comment]
Hi @niccolospa,

It seems like a connectivity problem on your environment. Setup script uses the default internet connection your OS configured to. Please check if the following command works:
git clone https://github.com/alexa/avs-device-sdk
Please let me know if command works while setup.sh fails.

**Comment by niccolospa** [comment]
Hi @mavamazon, if I launch `git clone https://github.com/alexa/avs-device-sdk` I get:
git-remote-https: symbol lookup error: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4: undefined symbol: nghttp2_session_callbacks_set_error_callback
Whereas if I add sudo it works...

**Comment by mavamazon** [comment]
@niccolospa,

Could you please also try this version of the command:
git clone git://github.com/alexa/avs-device-sdk

Beside that could you check the versions of the following libraries:
libcurl
nghttp2

**Comment by niccolospa** [comment]
I have libcurl at 7.52.1, how can I check for nghttp2? Using git clone git://github.com/alexa/avs-device-sdk generates the same "callback" error, if I add sudo before I get:
Cloning into 'avs-device-sdk'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection expired
github.com[1: 192.30.253.113]: errno=Connection expired

**Comment by mavamazon** [comment]
It appears that you may have a corporate network filter setup not to allow git:// protocol. Could you please try the following command and run the script again:

git config --global url."https://".insteadOf git://

Please let me know if it helps.
