### ISSUE TITLE
SpeechSynthesizerIntegrationTest Failed

### ISSUE THREAD

**Issue by jikaihu** [alexa/avs-device-sdk#53]
Hi.
   I will use alexa-client-sdk. Now I'm trying to run the SpeechSynthesizerIntegrationTest. But all of the tests  are failed.
    Could you help me to fix this error?

    Thanks

Logs from SpeechSynthesizerIntegrationTest:

[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from SpeechSynthesizerTest
[ RUN      ] SpeechSynthesizerTest.handleOneSpeech
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1272f50,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x1255c90,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x1255c90,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x1255c90,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.handleOneSpeech (11461 ms)
[ RUN      ] SpeechSynthesizerTest.handleMultipleConsecutiveSpeaks
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1271600,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x1261520,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x1261520,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x1261520,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.handleMultipleConsecutiveSpeaks (11187 ms)
[ RUN      ] SpeechSynthesizerTest.bargeInOnOneSpeech
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x138e930,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x126dc90,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x126dc90,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x126dc90,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.bargeInOnOneSpeech (11221 ms)
[ RUN      ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksAtTheBeginning
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x13b46b0,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x127fcd0,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x127fcd0,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x127fcd0,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksAtTheBeginning (11193 ms)
[ RUN      ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksInTheMiddle
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x13b2f20,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x13a2e30,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x13a2e30,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x13a2e30,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksInTheMiddle (11230 ms)
[ RUN      ] SpeechSynthesizerTest.multiturnScenario
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x13cff20,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x13bf510,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x13bf510,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x13bf510,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.multiturnScenario (11275 ms)
[ RUN      ] SpeechSynthesizerTest.handleNoSpeakDirectives
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x14f9c10,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x1380e80,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x1380e80,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x1380e80,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.handleNoSpeakDirectives (11170 ms)
[ RUN      ] SpeechSynthesizerTest.handleNoDirectives
ConfigurationNode:initializeSuccess
HttpPost:doPostSucceeded:code=200
AuthDelegate:handleLwaResponseSucceeded:expiresInSeconds=3600
AuthDelegate:onAuthStateChangeCalled:state=1,error=0
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=PENDING
Could not setup downchannel, retry count: 1
Could not setup downchannel, retry count: 2
Could not setup downchannel, retry count: 3
/home/jkh/amazon/alexa-client-sdk-master/Integration/test/SpeechSynthesizerIntegrationTest.cpp:466: Failure
Value of: m_connectionStatusObserver->waitFor(ConnectionStatusObserverInterface::Status::CONNECTED)
  Actual: false
Expected: true
Connecting timed out.
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0x1496a20,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0x141ab40,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0x141ab40,policy=BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0x141ab40,policy=BLOCKING
MessageRouter:connectionStatusChanged:reason=ACL_CLIENT_REQUEST,newStatus=DISCONNECTED
DirectiveSequencer:shutdown
[  FAILED  ] SpeechSynthesizerTest.handleNoDirectives (11191 ms)
[----------] 8 tests from SpeechSynthesizerTest (89930 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test case ran. (89930 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 8 tests, listed below:
[  FAILED  ] SpeechSynthesizerTest.handleOneSpeech
[  FAILED  ] SpeechSynthesizerTest.handleMultipleConsecutiveSpeaks
[  FAILED  ] SpeechSynthesizerTest.bargeInOnOneSpeech
[  FAILED  ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksAtTheBeginning
[  FAILED  ] SpeechSynthesizerTest.bargeInOnMultipleSpeaksInTheMiddle
[  FAILED  ] SpeechSynthesizerTest.multiturnScenario
[  FAILED  ] SpeechSynthesizerTest.handleNoSpeakDirectives
[  FAILED  ] SpeechSynthesizerTest.handleNoDirectives

 8 FAILED TESTS

**Comment by scotthea-amazon** [comment]
No updates on this for weeks.  If there are still questions, please update the ticket with more details and re-open.
