### ISSUE TITLE
Beep sound when Alexa is listening.

### ISSUE THREAD

**Issue by a2ron** [alexa/avs-device-sdk#533]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
I would be nice to listen a beep when Alexa starts listening.

## Briefly summarize your issue:

It wouldn't be a bug but a improvement.

## What is the expected behavior?

To heard a sound when Alexa wakes up.

## What behavior are you observing?

I hear Alexa voice responses, but no sound when Alexa start listening.

## Provide the steps to reproduce the issue, if applicable:

You wake Alexa with wake word agent, you listen a sound to know Alexa is listening.

### What version of the AVS Device SDK are you using?
      <1.5.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by vishnudevk** [comment]
without a screen its hard to know when alexa is listening, sometimes i have to repeat the full question after because wake word is not detected.

**Comment by FL550** [comment]
See #514 for an example

**Comment by kencecka** [comment]
I'll go ahead and close this for now - please reopen if you have further questions.

Ken
