### ISSUE TITLE
Alexa SDK Sample App audio issue

### ISSUE THREAD

**Issue by mdhussein** [alexa/avs-device-sdk#534]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Last year, I was able to run the sample app on my Raspberry pi 3.
This year, on a new raspberry pi, I am trying the Alexa SDK sample app.
Everything went fine and I was able to launch the sample app.
However, whenever I say something, I receive the HTTP_RESPONSE_NO_CONTENT.

## What is the expected behavior?
Alexa Sample App responds to queries.

## What behavior are you observing?
No response from Alexa Sample App

This is what I noticed:
###########################
#       Thinking...       #
###########################

2018-02-24 18:09:55.848 [  c] I InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-02-24 18:09:56.118 [  c] 0 HTTP2Stream:receivedRequestId:value=x-amzn-requestid\: 12470efffe37a252-000078a2-000a7327-7cd6ffdd8f21faf9-6afba8fa-5
2018-02-24 18:09:56.119 [  c] 0 HTTP2Stream:libcurl:streamId=5,text=Curl_http_done\: called premature \=\= 0
2018-02-24 18:09:56.119 [  c] 0 AudioInputProcessor:onSendCompleted:status=SUCCESS_NO_CONTENT
2018-02-24 18:09:56.119 [  c] 0 HTTP2Transport:cleanupFinishedStream:streamId=5,result=204
2018-02-24 18:09:56.119 [  c] 0 HTTP2StreamPool:releaseStream:streamId=5,numAcquiredStreams=1
2018-02-24 18:09:56.120 [  c] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
2018-02-24 18:10:00.848 [  e] 0 DialogUXStateAggregator:transitionFromThinkingTimedOut
2018-02-24 18:10:00.848 [  e] 0 DialogUXStateAggregator:setState:from=THINKING,to=IDLE
2018-02-24 18:10:00.849 [  b] 1 FocusManager:releaseChannel:channelName=Dialog

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:
I have set the usb microphone to be the default.
Speaker is connected to the raspberry.
I used arecord and aplay to record my voice and I was able to hear it clearly.

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi @mdhussein!

It seems that your mic records either silence or a distorted sound. Please run these commands to see if your mic is able to record:

arecord /tmp/test.wav
aplay /tmp/test.wav

**Comment by erickemde** [comment]
I'm having the same problem. I ran arecord and aplay and was able to record and play back audio.

**Comment by erickemde** [comment]
I said, "Alexa, what is 2 + 2". The application responded and looks like it is returning speech (there is a 'speaking ..' section in the response. My speakers are working (analog, not HDMI), but it seems like the audio isn't getting through.
[alexa-error.txt](https://github.com/alexa/avs-device-sdk/files/1773622/alexa-error.txt)

**Comment by mavamazon** [comment]
Hi @erickemde!

It seems that you have an issue with playback, not recording.
Could you please install gstreamer tools:
```
sudo apt install gstreamer1.0-tools gstreamer1.0-alsa
```
Then see if both of the commands produce the sound through the expected output:
```
gst-launch-1.0 -m audiotestsrc ! alsasink
gst-launch-1.0 -m audiotestsrc ! autoaudiosink
```

**Comment by pjaM1** [comment]
Hi @mavamazon ,

I get the same issue, using usb speaker and mic. - Jabra speak. 

gst-launch-1.0 -m audiotestsrc ! alsasink - Getting sound
gst-launch-1.0 -m audiotestsrc ! autoaudiosink - Not getting sound

Thanks,

Regards
Payam

**Comment by mavamazon** [comment]
Hey @pjaM1!

You can change the line in MediaPlayer.cpp (https://github.com/alexa/avs-device-sdk/blob/0be45093215d3e9594cb38228f2743a7b461c795/MediaPlayer/src/MediaPlayer.cpp#L599), so that instead of:

m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");

you have:

m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");

**Comment by pjaM1** [comment]
Hi @mavamazon 

After the change and then run:
make SampleApp && TZ=UTC ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

It works
Thanks, 
Regards
Payam

**Comment by kencecka** [comment]
Great - glad to hear it's working for you.  Let us know if you have any further questions.

Ken
