### ISSUE TITLE
why Alexa slow down my second question in my embed device? 

### ISSUE THREAD

**Issue by octGitHub** [alexa/avs-device-sdk#537]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After cross complie SDK successfully.  
I ran the SampleApp on the device.  
Firstly I ask a question , Alexa response normally.
Secondly  I ask a question again. Alexa response nothing. 

Note: I found the question I ask Secondly in the URL 
 ( https://pitangui.amazon.com/spa/index.html#settings/dialogs )
, and it showed the record has been slow down. 

## What is the expected behavior?

Record of the sencod round commnuication in the   ( https://pitangui.amazon.com/spa/index.html#settings/dialogs ) should be normal.

## What behavior are you observing?

After fist record , the second record seems not correct!

### What version of the AVS Device SDK are you using?
Alexa <1.5.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ 1 ] Other - tell us more:  arm device 

### Tell us about your OS (Type & version):
- [  1 ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Target system's gstreamer plugins:
[gst-plugin-list_v1.log](https://github.com/alexa/avs-device-sdk/files/1758465/gst-plugin-list_v1.log)

Please do tell me, is my plugin list fit all the Alexa need?  Is there miss some plugin?

###  This is my device log and dialog shortcut  : 
[COM-12_2018-02-26_19-35-33.log](https://github.com/alexa/avs-device-sdk/files/1758426/COM-12_2018-02-26_19-35-33.log)

![001](https://user-images.githubusercontent.com/14867254/36669116-b9024f62-1b2e-11e8-9aa8-fd3b49893664.png)

Line 219 is the first ask, and alexa sdk response correct.
Line 419 is the second ask.  and alexa sdk  has nothing response.

And we can see the second ask has been cut into four piece, and if you can check with the audio, you will found it was slow down very much.

Can any one help with this?

**Comment by kencecka** [comment]
Hi @octGitHub,

I've reviewed your logs and I don't see any obvious explanation there for the slowed audio and lack of response to your second recognize event.  I would suggest you try to narrow down where the audio is getting slowed/corrupted.  One simple way to do this to write the audio out to a file, and then play back the file to see if it is correct:

```
int PortAudioMicrophoneWrapper::PortAudioCallback(
    const void* inputBuffer,
    void* outputBuffer,
    unsigned long numSamples,
    const PaStreamCallbackTimeInfo* timeInfo,
    PaStreamCallbackFlags statusFlags,
    void* userData) {
```
```
    // ADD THIS
    static std::ofstream audioFile("capturedAudio.pcm", std::ios::binary);
```
```
    PortAudioMicrophoneWrapper* wrapper = static_cast<PortAudioMicrophoneWrapper*>(userData);
    ssize_t returnCode = wrapper->m_writer->write(inputBuffer, numSamples);
    if (returnCode <= 0) {
        ConsolePrinter::simplePrint("Failed to write to stream.");
        return paAbort;
    }
```
```
    // ADD THIS
    audioFile.write(reinterpret_cast<char*>(inputBuffer), numSamples * m_writer->getWordSize());
    audioFile.flush();
```
```
    return paContinue;
}
```

Now run through your test case of two Recognize events; the code changes above should write the captured voice audio from both events to the capturedAudio.pcm file.  You should be able to play it back using the SoX command `play -t raw -r 16k -b 16 -c 1 capturedAudio.pcm`.

If the speech from the second recognize event is slowed/corrupted in the captured file, then we need to look at PortAudio and your microphone audio path.  If the speech recorded in the file is correct, then we need to look at your SDS buffer configuration and other possible sources of corruption as the audio data passes through the SDK.

Ken

**Comment by octGitHub** [comment]
@kencecka 

  Thx for reply!


  I have added the code you pasted  above into SampleApp
  And I ran it on the deivce. I found the captured voice audio has been slow down after the firs speech. 


[capturedAudio.zip](https://github.com/alexa/avs-device-sdk/files/1761042/capturedAudio.zip)
    
   The portaudio in the device should be the version of v190600_20161030 according to the makefile.
   
![1](https://user-images.githubusercontent.com/14867254/36707950-9b6a6372-1bab-11e8-946a-49e47594185b.png)

   And where can  I find the  "microphone audio path" ?  My device is a arm linux

**Comment by octGitHub** [comment]
@kencecka 

  Hi, kencecka.  I have a idea of this problem.   
  After Alexa-Device-SDK  recorded the speech ( recorder initial the device mic to first audio paramerter, 16bit 16k, 1channel )  and sent to AVS, device get a response with a mp3 stream. then Alexa-Device-SDK  play it ( the  player initial  the device to second  audio paramerter, like 24k  )

   I doubt the device's audio paramerter ( bit rate and channel ) has been set to the player's .  So after the first speech, the second speech seems to be slowed down.

   So, Is it right ? And is there any way I can resample the input or output audio stream to just one audio paramerter, because I think my device only support one set of audio paramerter.

**Comment by kencecka** [comment]
Hi @octGitHub,

I played around with the sample rate and found that the first recording plays correctly at 16KHz, while the response and second recording play correctly at 48KHz:
`play -t raw -r 16k -b 16 -c 1 -e signed capturedAudio.pcm`
`play -t raw -r 48k -b 16 -c 1 -e signed capturedAudio.pcm`

Note however that there is a lot of static in the 48KHz segment, so the problem may be more than just an incorrect frequency.

Your idea about the MP3 playback changing frequencies is an interesting one.  Normally, the hardware and drivers for the microphone would be separate from the hardware and drivers for the speaker, so changing the frequency for one would not change the frequency for the other.  But some devices may have shared hardware or drivers that aren't able to keep the configuration separated.

If this is the case for your platform, one option is to change the output frequency to match the input frequency.  It doesn't appear that we've documented this in the sample AlexaClientSDKConfig.json yet, but there are some parameters you can set to change the output format for the gstreamer MediaPlayer provided with the SDK.  Try adding this to your config file and see if it helps:

```
     "gstreamerMediaPlayer":{
	 "outputConversion":{
	     "rate":16000,
	     "format":"S16LE",
	     "channels":1
	 }
    }
```

Ken

**Comment by octGitHub** [comment]
@kencecka 
  Hi, ken
  After added this configure , it seems not help, after first speech still output  48k. 
  
[device_resample_capturedAudio.zip](https://github.com/alexa/avs-device-sdk/files/1765834/device_resample_capturedAudio.zip)

**Comment by kencecka** [comment]
Hi @octGitHub,

Can you run with debug logging and post the results here?  We're looking for a line in your logs with the string "outputConversion" or "noOutputConversion".  You should see one or the other, with the former indicating that you have successfully enabled conversion in your config file.

Ken

**Comment by octGitHub** [comment]
@kencecka
 yes.  It's in the attachment  https://github.com/alexa/avs-device-sdk/files/1765834/device_resample_capturedAudio.zip
with  the  audio  and  runninglog

**Comment by kencecka** [comment]
Hi @octGitHub,

Thanks for posting the log.  I've reviewed it and confirmed that SampleApp is correctly interpreting the outputConversion you specified.  As that did not resolve the issue for you, I think you are going to have to work with your device vendor and/or their forums to learn more about how the audio system works and get advice on what might be changing the recording speeds.  You might also try asking on the [PortAudio mailing list](http://portaudio.com/contacts.html).

Ken

**Comment by octGitHub** [comment]
@kencecka   

  Thx for reply!

  I tried to initial mic to 48k and use codec ( maybe the ffmepg's ) to resample it to 16k, and it works fine.
  I doubt the gstreamers' resample seems not work correctly, but still no evidence...
  I think Alexa-Device-SDK working with no more third part libraries would be  better.  How can I check with it?  Any suggestion?

**Comment by kencecka** [comment]
Hi @octGitHub,

I expect actual Alexa speech (SpeechSynthesizer.Speak directives) will always use the same MP3 encoding, but content which comes in through AudioPlayer.Play directives can be in [a variety of formats and frequencies](https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html).  Changing your microphone sampling rate isn't going to be sufficient because the output from gstreamer is not consistent.

The outputConversion configuration options I described above address this by forcing gstreamer to always output a specific/fixed format.  However, it sounds like this change alone did not work for your system.  You might want to experiment with different outputConversion parameters to see if the ones I gave are not an exact match for your microphone input (for example, you might try U16LE rather than S16LE).

You can also try turning on gstreamer logging (set the environment variable GST_DEBUG=4) to get additional detail about the conversions and resampling gstreamer is doing.

Ken

**Comment by octGitHub** [comment]
@kencecka 

  Ok, Thx for your help all the time !  
   I will try to fix this.

**Comment by sanjayrd** [comment]
Hi @octGitHub. 

You probably could do this with GStreamer's APIs, but you would need to modify the SDK source code (`MediaPlayer/src/MediaPlayer/cpp`). You would need to probably insert new GStreamer elements after the decoder but before the audioSink. See `MediaPlayer/include/MediaPlayer/MediaPlayer.h` for documentation on this (specifically the documentation for `struct AudioPipeline`).

As Ken mentioned above, the experimenting with the config options is the easiest way to go forward.

Thanks,
Sanjay
