### ISSUE TITLE
Running SampleApp automatically on system boot

### ISSUE THREAD

**Issue by davorf** [alexa/avs-device-sdk#539]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Trying to run SampleApp automatically on boot. I've tried using rc.local, crontab and systemd.service, but wasn't able to make it work with any of them. 

## What is the expected behavior?

Is there a way to run SampleApp automatically on system boot - considering I'm using headless CLI only environment?

## What behavior are you observing?

- When using rc.local to run SampleApp (tried to run it as `/bin/bash /home/pi/startsample.sh`, and also tried making executable .sh script which contains `sudo /bin/bash /home/pi/startsample.sh`) after boot Raspberry pi freezes for couple of minutes, and SampleApp does not work. SampleApp also doesn't work when Raspberry becomes responsive.
- When using crontab, SampleApp works for a minute or so, then stops responding
- I've tried using different systemd.service Type (simple, idle), tried starting SampleApp directly (ExecStart populated with code that's inside startsample.sh script), using `/bin/bash /home/pi/startsample.sh`, using executable .sh script that runs `sudo /bin/bash /home/pi/startsample.sh`, tried different WorkingDirectory and User, but after starting it, service status gets flooded by "Invalid option" messages (the one framed with asterisks, that shows when you enter an option that does not exist via keyboard)

### What version of the AVS Device SDK are you using?
      <1.5.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

I'm running Alexa Sample App on Raspbian Stretch (build 2017-09-08) headless, CLI only.

**Comment by kencecka** [comment]
Hi @davorf,

Have you checked your process listings to see if SampleApp is running with 100% CPU usage?  I'm guessing you're having trouble running  SampleApp when it is not attached to a terminal.  SampleApp has a _very_ simple input model that reads characters from stdin in a loop.  If you try to run it as a daemon without stdin, it generally goes into a tight loop with the character reads failing.

Try modifying [UserInputManager.cpp here](https://github.com/alexa/avs-device-sdk/blob/v1.5/SampleApp/src/UserInputManager.cpp#L74) to look like this:

```
void UserInputManager::run() {
    if (!m_interactionManager) {
        return;
    }
    m_interactionManager->begin();
    while (true) {
```
```
        // ADD THIS
        std::this_thread::sleep_for(std::chrono::hours(1));
        continue;
```
```
        char x;
        std::cin >> x;
```

This will skip the keyboard input section and cause the process to run forever (until you kill it).

Ken

**Comment by khassel** [comment]
Hi Ken,

can we get a solution e.g. with a start parameter "HEADLESS" in a future release? 
Running this app as docker container is another case running in this issue.

Thanks,

Karsten.

**Comment by davorf** [comment]
Hello @kencecka

I've tried solution you've suggested and now systemd.service works - it doesn't flood status with "Invalid option" messages. Thank you a lot for your help. 

Best regards,
Davor 

P.S. Since there are other messages after the solution, I will leave issue open, but the original issue is definitely solved.

**Comment by mikejrh** [comment]
Could you share  the code you used to get SampleApp to run automatically on system boot using systemd.service ?   Also, does this include running wake word engine on system boot ?  Thanks.

**Comment by davorf** [comment]
Hello!

First I've created `alexa.sh` script with a following content:

```
#!bin/bash

sudo /bin/bash /home/pi/startsample.sh
```
Next, you need to make a script executable:

`sudo chmod +x /home/pi/alexa.sh`
 
Then, you need to create a systemd.service file:

`sudo nano /lib/systemd/system/alexa.service`

Enter the following inside alexa.service file:

```
[Unit] 
Description=Amazon Alexa
After=network.target network-online.target

[Service] 
Type=idle
ExecStart=/home/pi/alexa.sh
WorkingDirectory=/home/pi/build/SampleApp/src
User=pi

[Install]
WantedBy=multi-user.target
```
Change permissions of the service file using:

`sudo chmod 644 /lib/systemd/system/alexa.service`

Reload daemon, enable and start service:

```
sudo systemctl daemon-reload
sudo systemctl enable /lib/systemd/system/alexa.service
sudo systemctl start /lib/systemd/system/alexa.service
```
You can check status of the service using:

`sudo systemctl status /lib/systemd/system/alexa.service`

Regarding the question about wakeword engine, I'm using alexa-device-sdk (new C++ engine, not an old java) and wakeword engine is part of the SampleApp not a separate application. 

Best regards,
Davor

**Comment by undee123** [comment]
Hi Davor,

when I'm about to execute
`sudo systemctl start /lib/systemd/system/alexa.service`

I get
`Failed to start lib-systemd-system-alexa.service.mount: Unit lib-systemd-system-alexa.service.mount not found.
`

What can be the problem here?

Thank you very much!

Andy

**Comment by davorf** [comment]
Hello!

When I was creating/enabling/starting service, I was in /lib/systemd/system directory, so, I wasn't using full path to alexa.service. It looks like you don't need full path to a service when you enable/start/status a service, so, you should use

```
sudo systemctl daemon-reload
sudo systemctl enable alexa.service
sudo systemctl start alexa.service
sudo systemctl status alexa.service
```

Sorry for the confusion I've made. 

Best regards,
Davor

**Comment by mikejrh** [comment]
I am getting the following using the systemctl commands.  Please advise.  Thanks,

![image](https://user-images.githubusercontent.com/18380977/36947691-78c44d1a-1f9d-11e8-9e76-dddf53ea6e0a.png)

**Comment by davorf** [comment]
Hello!

Have you tried starting Alexa with a script you've made (alexa.sh)? While you are in /home/pi try running script with ./alexa.sh or from any other directory with /home/pi/alexa.sh

Best regards,
Davor

**Comment by mikejrh** [comment]
Alexa works using command  sudo bash alexa.sh (it doesn't work without the bash command).
However, when I reboot the system SampleApp no longer loads.  What am I missing ?  thanks

**Comment by davorf** [comment]
Hello!

To make it work as a service, alexa.sh should work without sudo and without explicit bash call. Have you made script executable with sudo chmod +x /home/pi/alexa.sh ?

Best regards,
Davor

**Comment by mikejrh** [comment]
![image](https://user-images.githubusercontent.com/18380977/36951802-b5ed227e-1fd5-11e8-8184-c7aa913d7547.png)

**Comment by davorf** [comment]
Hello!

It looks like the change in UserInputManager.cpp isn't applied. Have you recompiled source (just run sudo bash setup.sh config.txt again)? Then you should do authorization (run sudo bash startauth.sh). After that, service should work, and log should not get flooded with "Invalid option" error message. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

In addition, do you have `#!bin/bash` in the first line of your alexa.sh script? And what operating system your RPi runs on? 

Best regards,
Davor

**Comment by mikejrh** [comment]
Works great now after recompiling source.  I have #!bin/bash in the first line of the alexa.sh script and I am using Raspbian Stretch.  Thank you for sharing code and your help.

**Comment by davorf** [comment]
Hello!

Glad to hear you made it work. I'm just not sure why `alexa.sh` doesn't run without bash. Have you tried running it with an absolute path (/home/pi/alexa.sh)? I'm using Raspbian Stretch (build 2017-09-08), and it works, both, calling script manually and as service's ExecStart. 

Best regards,
Davor

**Comment by a2ron** [comment]
Hi! I cooked next script to launch `startsample.sh`attached to a terminal using `screen`. You can launch it periodically using `crontab`, it checks the app is running and launch if needed. It also checks  several error cases due to connectivity and so on.
Adapt `LOG_FOLDER` and `ALEXA_FOLDER` properly.

```bash
#!/bin/bash

LOG_FOLDER="/var/log/startsample"
ALEXA_FOLDER="/var/log/startsample"

_psName2Ids(){
    ps -aux | grep -i "$1" | awk '{print $2}'
}

psKill(){
     _psName2Ids $1 | xargs sudo kill -9 > /dev/null 2>&1;
}

findError(){
    cat ${LOG_FOLDER}/$(ls ${LOG_FOLDER} | tail -1)  | grep "$1" | wc | awk '{print $1}'
}

# check errors
error1=$(findError "AbstractKeywordDetector")
error2=$(findError "RequiresShutdown")
error3=$(findError "Alexa is currently idle!")

processes=($(_psName2Ids "startsample.sh"))
if [ ${#processes[@]} -le 1 ] || [ $error1 -gt 10 ] || [ $error2 -gt 0 ] || [ $error3 -lt 2 ] ; then

    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    sudo touch "$LOG_FOLDER/$now.log"
    sudo chmod go+rwx "$LOG_FOLDER/$now.log"
    cd "$ALEXA_FOLDER"
    psKill "startsample.sh"

    screen -L "$LOG_FOLDER/$now.log" -dm sudo bash startsample.sh
fi;
```
Hope you enjoy it.

**Comment by dhpp** [comment]
It appears all aspects of the question have been addressed here.  I will close this thread.  Please re-open if needed.

**Comment by NicoSoftware** [comment]
@davorf  
I did exactly what you've descriped, recompiled everthing and did the 
```
sudo bash startauth.sh
``` 
got the key but 
```
sudo bash startsample.sh
```
does absolutely nothing now

**Comment by iGodPhil** [comment]
Hey,

I'm using the AVS Version 1.6.0 and get the following error message:

`alexa.service - Amazon Alexa
   Loaded: loaded (/lib/systemd/system/alexa.service; enabled; vendor preset: enab
   Active: failed (Result: exit-code) since Mon 2018-07-30 19:27:49 CEST; 1h 16min
  Process: 2393 ExecStart=/home/pi/Programme/Alexa-Autostart/alexa.sh (code=exited
 Main PID: 2393 (code=exited, status=203/EXEC)

Jul 30 19:27:49 raspi systemd[1]: Started Amazon Alexa.
Jul 30 19:27:49 raspi systemd[1]: alexa.service: Main process exited, code=exited,
Jul 30 19:27:49 raspi systemd[1]: alexa.service: Unit entered failed state.
Jul 30 19:27:49 raspi systemd[1]: alexa.service: Failed with result 'exit-code'.`

I have modified the UserInputManager.cpp and recompiled.
This is my alexa.sh:
`#!bin/bash

sudo /bin/bash /home/pi/Programme/Alexa/startsample.sh
`
`sudo bash alexa.sh` works.
And this is my alexa.service:
`
[Unit]
Description=Amazon Alexa
After=network.target network-online.target

[Service]
Type=idle
ExecStart=/home/pi/Programme/Alexa-Autostart/alexa.sh
WorkingDirectory=/home/pi/Programme/Alexa/build/SampleApp/src
User=pi

[Install]
WantedBy=multi-user.target
`

So what can I do?

**Comment by Vino-git** [comment]
Used this https://github.com/alexa/avs-device-sdk/issues/539#issuecomment-369906721 method for this https://github.com/alexa/avs-device-sdk/issues/539#issuecomment-370881036. Works perfectly.

**Comment by iGodPhil** [comment]
Hi @a2ron. 
I've followed your instruction but get the following error but all log files are empty:

> pi@raspi:~ $ sudo systemctl status alexa.service
> ● alexa.service - Amazon Alexa
>    Loaded: loaded (/lib/systemd/system/alexa.service; enabled; vendor preset: enabled)
>    Active: inactive (dead) since Sun 2018-10-14 20:52:20 CEST; 14s ago
>   Process: 4141 ExecStart=/home/pi/alexa.sh (code=exited, status=0/SUCCESS)
>  Main PID: 4141 (code=exited, status=0/SUCCESS)
> 
> Okt 14 20:52:19 raspi systemd[1]: Started Amazon Alexa.
> Okt 14 20:52:20 raspi sudo[4174]:     **root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/touch /var/log/startsample/2018-10-14T18:52:20Z.log** 
> Okt 14 20:52:20 raspi sudo[4174]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Okt 14 20:52:20 raspi sudo[4174]: pam_unix(sudo:session): session closed for user root
> Okt 14 20:52:20 raspi sudo[4182]:     **root : TTY=unknown ; PWD=/ ; USER=root ;COMMAND=/bin/chmod go+rwx /var/log/startsample/2018-10-14T18:52:20Z.log** 
> Okt 14 20:52:20 raspi sudo[4182]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Okt 14 20:52:20 raspi sudo[4182]: pam_unix(sudo:session): session closed for user root
> Okt 14 20:52:20 raspi sudo[4195]:     **root : TTY=unknown ; PWD=/home/pi ; USER=root ;COMMAND=/bin/kill -9 4193** 
> Okt 14 20:52:20 raspi sudo[4195]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Okt 14 20:52:20 raspi sudo[4195]: pam_unix(sudo:session): session closed for user root

**Comment by iGodPhil** [comment]
I have solved my problem. The Problem was my systemd service file. 
You have to change to:


```
[Unit]
Description=Amazon Alexa
After=network.target network-online.target

[Service]
Type=forking
ExecStart=/home/pi/alexa.sh


[Install]
WantedBy=multi-user.target
```

And i added my alexa.sh from @a2ron but there are some differences:

```
#!/bin/bash

LOG_FOLDER="/home/pi/startsample"
ALEXA_FOLDER="/home/pi/"

_psName2Ids(){
    ps -aux | grep -i "$1" | awk '{print $2}'
}

psKill(){
     _psName2Ids $1 | xargs sudo kill -9 > /dev/null 2>&1;
}

findError(){
    cat ${LOG_FOLDER}/$(ls ${LOG_FOLDER} | tail -1)  | grep "$1" | wc | awk '{print $1}'
}

# check errors
error1=$(findError "AbstractKeywordDetector")
error2=$(findError "RequiresShutdown")
error3=$(findError "Alexa is currently idle!")

processes=($(_psName2Ids "startsample.sh"))
if [ ${#processes[@]} -le 1 ] || [ $error1 -gt 10 ] || [ $error2 -gt 0 ] || [ $error3 -lt 2 ] ; then

    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    sudo touch "$LOG_FOLDER/$now.log"
    sudo chmod go+rwx "$LOG_FOLDER/$now.log"
    cd "$ALEXA_FOLDER"
    psKill "startsample.sh"

    screen -L "$LOG_FOLDER/$now.log" -dm sudo bash startsample.sh
fi;

```

Now everything is fine with SDK Version 1.9.0.

**Comment by Tommy22er** [comment]
Ist es möglich dass sich das Terminal Fenster beim start in Desktop öffnet. Ich würde gerne Aleka configurieren oder beenden.

**Comment by chrishrb** [comment]
@kominoshja Just add these two lines

```
std::this_thread::sleep_for(std::chrono::hours(1));
continue;
```
in the UserInputManager.cpp here:

```
SampleAppReturnCode UserInputManager::run() {
    bool userTriggeredLogout = false;
    m_interactionManager->begin();
    while (true) {
	std::this_thread::sleep_for(std::chrono::hours(1));
	continue;
        char x;
        if (!readConsoleInput(&x)) {
            break;
```

**Comment by Andergraw** [comment]
Hi everyone,
thank you all for your inputs. Just in case this is useful for anyone else, I had the same problem @mikejrh did and the only problem was the shebang:
`#!bin/bash`
didn't work but 
`#!/bin/bash`
did
Cheers!

**Comment by pablinho1023** [comment]
Hello! I also did this:

````
SampleAppReturnCode` UserInputManager::run() {
    bool userTriggeredLogout = false;
    m_interactionManager->begin();
    while (true) {
	std::this_thread::sleep_for(std::chrono::hours(1));
	continue;
        char x;
        if (!readConsoleInput(&x)) {
            break;
```

But Alexa stops responding after a while. Is there something else that needs to be added?
