### ISSUE TITLE
Speech Recognizer - initiator + profile configuration

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#54]
Hi,

We are implementing Speech Recognizer using profile as FAR_FIELD and initiator ad WAKEWORD.
According to AVS API if WAKEWORD is used for initiator then KEYWORD Indices are required to be sent by device to the cloud for 2nd stage of Wake Word verification.
I have a couple of questions as to that:

1) Is it mandatory to send KEYWORD to cloud together with command buffer when WAKEWORD engine is in use?

2) **If not mandatory.** How can I configure my AudioInputprocessor to use WAKEWORD and DO NOT provide keyword indices to could? I have tried to send AudioInputProcessor::INVALID_INDEX as indices BEGIN and END values but cloud is considering voice buffer as false detection almost all the time. As soon as I send the recognize event  I am receiving a STOP directive almost immediately.
`m_aip->recognize(audioProvider, Initiator::WAKEWORD, aipBegin, aipEnd, keyword);`

3) **If Mandatory.** Can we switch and use TAP profile even if we have a WAKEWORD engine running? Looks like that only difference from TAP and WAKEWORD is the Wake Word 2nd stage Verification.

Thank you
Juliano Ribeiro

**Comment by dhpp** [comment]
Closing for now.  Please re-open if you wish to continue discussion.
