### ISSUE TITLE
make: *** No rule to make target 'SampleApp'.  Stop.

### ISSUE THREAD

**Issue by Krato5** [alexa/avs-device-sdk#542]
## Briefly summarize your issue:
the installation was stoped bcuz of permission of tgz file extraction of portaudio , but when i fix it manually ... after that wanted reinstall the auto installation it says like this : ( : make: *** No rule to make target 'SampleApp'.  Stop). 

## What is the expected behavior?
 its expected to continue the installation from where it stops or even repeat from first..

## What behavior are you observing?
it says : make: *** No rule to make target 'SampleApp'.  Stop.

## Provide the steps to reproduce the issue, if applicable:
install normally

### What version of the AVS Device SDK are you using?
      <1.5.0> mast avs device sdk 

### Tell us what hardware you're using:

- [x] Raspberry Pi

### Tell us about your OS (Type & version):

- [x] Raspbian Stretch

i install in media/usb directory

**Comment by mavamazon** [comment]
Hi @Krato5!

SampleApp target is disabled unless both Portaudio and GStreamer are enabled. It seems that in your case Portaudio has failed to install. Could you please retry the SDK installation from scratch?

As an option you can take a look at Portaudio installation section of our [step-by-step guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#12-install-dependencies). Also make sure that you run the cmake command with proper portaudio settings:
```
cmake /home/pi/sdk-folder/sdk-source/avs-device-sdk -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/pi/sdk-folder/third-party/portaudio/include
```
Please note that you should adjust paths accordingly.
