### ISSUE TITLE
Response waiting time is high for the silence queries 

### ISSUE THREAD

**Issue by NathanMani** [alexa/avs-device-sdk#543]
We are testing False Rejection Ratio(FRR) using AlexaSDKv1.5 on RPI. During this test case, ‘alexa’ will be played without query and the detected ‘alexa’ will be countered in the Alexa app web site. 
We have notice that the number of Alexa’s are missed in the cloud even though the local detection is proper (verified by console prints). Below is our analysis observation
1.	Alexa with query - Audio response received quickly. The subsequent Alexa is detected properly in both local and cloud even the subsequent Alexa played during Speaking/Thinking stage of current query (i.e it is treating as separate query).
2.	Alexa without query - No audio response expected for this query. The subsequent Alexa is detected properly in local and but not shown in cloud when the subsequent Alexa played during Speaking/Thinking stage of current query (i.e it is treating as same query/ not starting to cloud?)
Looks like the response waiting time is high for the query which doesn’t have audio attachment and also next Alexa is dropped if Alexa detected locally during Speaking/Thinking stage of current query.
We would like to know the how to test FRR with Alexa SDK. Please suggest us.

**Comment by sanjayrd** [comment]
Hi @NathanMani,

Can you contact us privately via this [form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268)? We might be able to give you better guidance for FRR testing.

Thanks,
Sanjay

**Comment by NathanMani** [comment]
Thank you i have submitted the form :)

**Comment by scotthea-amazon** [comment]
Hi @NathanMani,

I am closing out this issue as it appears you have been contacted.  Please feel free to re-open this issue if it has been closed in error.

Thank you,
-SWH
