### ISSUE TITLE
Spotify Question

### ISSUE THREAD

**Issue by adpandit** [alexa/avs-device-sdk#546]
AVS v1.5 has an external MediaPlayer interface. 

For Spotify, does the cloud handle the Spotify integration i.e. AVS sends a Spotify URL to play once the account for Spotify account credentials are added through the Alexa App. So it becomes like a regular TuneIn or another URL to stream? Or do we need to write an external Spotify adaptor derived from ExternalMediaAdapterInterface?

**Comment by sanjayrd** [comment]
Hi @adpandit,

The cloud does not handle Spotify integration. Spotify is a whole other beast that requires on device integration with the Spotify SDK. So yes, you would need to write an external Spotify adapter derived from the interface. Please contact us privately [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and we may be able to provide more information.

Thanks,
Sanjay

**Comment by adpandit** [comment]
Thanks @sanjayrd. I will have our folks reach out to your team.
