### ISSUE TITLE
How to get the audio data that send to the avs server?

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#547]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
How to get the audio data that send to the avs server?

## What is the expected behavior?
dump audio data,no include wakeword.

## What behavior are you observing?
dump audio data,no include wakeword.

## Provide the steps to reproduce the issue, if applicable:
No

## Tell us about your environment:
Buildroot 
### What version of the AVS Device SDK are you using?
      <1.5.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi 
- [ ] Other - tell us more: 

Raspberry Pi 

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
Buildroot

**Comment by sanjayrd** [comment]
Hi @NyxRockchip2017,

We don't provide functionality to  get the audio data back from the server. However, it's certainly possible for you to add code to dump the audio to a local file before sending it to the AVS servers. You would likely want to create another `SDSReader` just before making the `AudioInputProcessor::recognize()`, read the audio data, and then write it to a local file.

Thanks,
Sanjay
