### ISSUE TITLE
Setup failed on Raspberry Pi using script

### ISSUE THREAD

**Issue by devdream02** [alexa/avs-device-sdk#548]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Hi, was trying to setup AVS on raspberry Pi using script as mentioned in the help guide:-
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

Was on step no. 3 i.e. "sudo bash setup.sh config.txt"

In which the setup process hung up at "cloning of  AVS SDK" part due to some proxy issue and exixted abruptly.
 
Was able to fix the proxy issue and then again when i tried to run the command "sudo bash setup.sh config.txt" to rerun the installation, it gave me the below error:-

**"no rule to make target 'SampleApp'. Stop."**

Can anyone tell me how to proceed with the setup part or revert the partial installation.

## What is the expected behavior?
The installation should resume from the point it halted or from start

## What behavior are you observing?
Couldn't proceed with the setup part

## Tell us about your environment:
Rasbian Strech
### What version of the AVS Device SDK are you using?
      1.5.0

### Tell us what hardware you're using:
-  Raspberry Pi

### Tell us about your OS (Type & version):
- [x] Raspbian Stretch

**Comment by sanjayrd** [comment]
Hi @devdream02,

To revert the partial install process, you can remove the following directories:
`third-party`
`build`
`sounds`
`db`
`avs-device-sdk`

Running an `rm -rf` command from within each of those directories will reset the process and you can try running the scripts again.

Thanks,
Sanjay

**Comment by devdream02** [comment]
Thanks @sanjayrd, was able to solve the issue using the above  suggestions.

Regards,
Devyansh
