### ISSUE TITLE
How could I get the AmazonLite key-word lib?

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#549]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
How could I get the AmazonLite key-word lib?

## Briefly summarize your issue:

We want to get amazon lite key-word lib instead of sensory.
## What is the expected behavior?

We want to get amazon lite key-word lib instead of sensory.

## What behavior are you observing?

We want to get amazon lite key-word lib instead of sensory.

## Provide the steps to reproduce the issue, if applicable:

We want to get amazon lite key-word lib instead of sensory.

## Tell us about your environment:
linux-buildroot
### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Contact us privately [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).

Thanks,
Sanjay
