### ISSUE TITLE
std::future_error    Promise already satisfied

### ISSUE THREAD

**Issue by sangshengjie** [alexa/avs-device-sdk#55]
I rewrited the AudioInputProcessorIntegrationTest with SpeechSynthesizer, and feeding audio data which recorded by alsa. When I run it, sometimes the error appeared :

[log.txt](https://github.com/alexa/alexa-client-sdk/files/1141736/log.txt)

I found that the error is from the code : "promise->set_value(MediaPlayerStatus::PENDING);" by adding log
It seemed that the same promise in the handlePlay of MediaPlayer.cpp was set twice.

When I used the arm-linux-gnueabihf-g++ (crosstool-NG linaro-1.13.1-4.9-2014.05 - Linaro GCC 2014.05, 4.9.1 20140505 prerelease) to compile sdk, the error appeared. But the error disappeared when I used arm-linux-gnueabihf-g++ (Ubuntu/Linaro 4.8.4-2ubuntu1~14.04.1) 4.8.4. 
Did the compiler cause the error?

Thanks,
sangshengjie

**Comment by scotthea-amazon** [comment]
No update here for weeks.  If help is still needed, please update with further questions or details and re-open.
