### ISSUE TITLE
intermittent cutout of sound.

### ISSUE THREAD

**Issue by maccy99** [alexa/avs-device-sdk#551]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi guys, strange one this, whenever i use the wakeword the audio cuts out after 2 seconds comes back in 2 seconds later goes out again for 2 seconds then comes back and stays on, so the initial response after you ask question a you only get to hear half the conversation but it will play music or radio after the cut outs constantly with no problems,,,, now please bear in mind i have only started to learn about the Raspberry pi the last 2 days so i have little to knowledge about how to look for problems and what to look for, i have tried to search the forum for advice on how to repair lost, damaged or conflicting files where audio may be the issue but i have not come across this....lol

## What is the expected behavior?
normal response after asking a question

## What behavior are you observing?
intermittent audio cut out 2 seconds audio on 2 seconds audio off 2 on again 2 off and the normal!!!-->

### What version of the AVS Device SDK are you using?
      [1.6.0] - 2018-03-08

### Tell us what hardware you're using:

- [ ] Raspberry Pi

### Tell us about your OS (Type & version):

- [ ] Raspbian Stretch

**Comment by scotthea-amazon** [comment]
Hi maccy99,

From your description it sounds like some audio is already playing when you speak the wakeword.  Can you please provide detailed steps for how you are reproducing the problem, including things like how you start audio before invoking the wake-word, and what you actually say to trigger the problematic behavior?

If you can provide debug logs (build with -DCMAKE_BUILD_TYPE=DEBUG, and pass DEBUG9 on the command line to SampleApp), we may be have a little more to go on to find the root cause of this problem.

Finally, would it be possible to provide an audio recording of this interaction?

Thank you,
-SWH

**Comment by maccy99** [comment]
Hi SWH found the root of the problem turns out that if it is connected to monitor with speakers via hdmi it switches from hdmi to pcm back and forth until it registers default pcm 3.5mm audio output, if you control via vnc it works a treat but as soon as it connects to hdmi problem occurs,  i presume as hdmi is default on rp3 to set 3.5mm audio out as default is not complying with the settings, found this out by slightly pulling out 3,5 audio to find out when the break occurs sound on monitor/tv would come on then cut out back to 3.5 audio and so on, ther wouldn't be an issue if monitor had no speakers but as mine do that is why the problem occurred on my setup. By the way this with C++ not java, java sdk works a treat no problems but the reason i went for C++ as it covers a basic headless auto start function where as the sdk version trying several different methods not really worked for me must have installed alexa sample app 40 plus times now lol eventually i will find one where it will start and have no audio issues that works with MagicMirror by MichMich, currently on AlexaPi now does not register input or output at all after doing auto start, eventually will get there and lets face it i am learning the hard way!!!  Can only assume when users upload various ways of auto start function they don't take it into consideration that everyones layout has a slight different code to it, just a note as well there are a lot believe me after several plus attempts of installing alexa sdk , when it comes to following instructions and learning the basics that a lot of them are out dated where following instructions is not up to date. Thanks for response will keep you informed if and where i get somewhere... still learning to fail though

**Comment by maccy99** [comment]
Hi guys, Ok decided to return to this one and not give up, right got it all perfect by disconnecting monitor and using vnc then after a while sound stopped coming out of speakers, tried different ones even tried Bluetooth no sound coming out of any at all but mic is now picking up what i am saying. which is a good thing. can't seem to understand why as i never changed any settings at all it just stopped. don't know how to do a error report e.t.c. Any advice or pointing me in the right direction would be very much appreciated. Thanks

**Comment by maccy99** [comment]
Solved thank you so much @mavamazon  for your suggestion : - 

You can try to modify boot/config.txt: comment out the following line: hdmi_force_hotplug=1 and then reboot and try if SDK plays audio to correct output. Also you can change the line in MediaPlayer.cpp﻿, so that instead of:
m_pipeline.audioSink = gst_element_factory_make("autoaudiosink", "audio_sink");
you have:
m_pipeline.audioSink = gst_element_factory_make("alsasink", "audio_sink");

just goes to show if you look hard enogh you will find what your looking for. again Thank You
