### ISSUE TITLE
How can I enable full detail debuging log for SampleApp?

### ISSUE THREAD

**Issue by jasonvfang** [alexa/avs-device-sdk#552]
I intergrated avs device sdk on my ubuntu linux pc and the communication were good when I use SampleApp testing it.

I need to know what events received by the client during communication.
There were many debug levels here:
DEBUG9
DEBUG8
DEBUG7
DEBUG6
DEBUG5
DEBUG4
DEBUG3
DEBUG2
DEBUG1
DEBUG0
INFO
WARN
ERROR
CRITICAL
NONE

I opened the debug log level of DEBUG0 for sample app , eg:
 ./SampleApp ~/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json DEBUG0 

but still no events log appeared, there were only directive logs.

How can I enable full detail debuging log for SampleApp ? Should I recompile the whole project or just make SampleApp building with Debug option to enable detail debuging?
 
Thanks in advance!

**Comment by scotthea-amazon** [comment]
Hello jasonvfang,

The DEBUG0-DEBUG9 level logs are compiled out of RELEASE builds.  You can enable them by re-running cmake with -DCMAKE_BUILD_TYPE=DEBUG and re-running make SampleApp.

Also, passing DEBUG0 on the command line only enables CRITICAL-DEBUG0 logs.  You need to pass DEBUG9 on the command line to enable all log levels.

Thank you,
-SWH

**Comment by jasonvfang** [comment]
Thanks, It works now
