### ISSUE TITLE
How I can  get started on the approval for Amazon Music

### ISSUE THREAD

**Issue by FengXMGeek** [alexa/avs-device-sdk#556]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I can`t play any music! my company is a product alexa-enable of screen! Wo need to test some music !

## What is the expected behavior?
I say: play bye bye bye !

## What behavior are you observing?
Amazon Music is not supported on this device
I have send a email to avscert@amazon.com! but haven't got any responses!
I  follow the website :https://forums.developer.amazon.com/articles/59778/launch-with-avs.html

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
a device like echo show 

### Tell us about your OS (Type & version):
android

**Comment by scotthea-amazon** [comment]
Hi FengXMGeek,

I am very sorry to hear that your request has not been responded to.  I will see if I can find out why that occurred, and get that corrected.  In the mean time, please contact us privately [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).

Thank you,
-SWH

**Comment by FengXMGeek** [comment]
@scotthea-amazon  Hi I`m used android. and don`t use avs sdk. can  sdk play Amzon music?

**Comment by FengXMGeek** [comment]
@scotthea-amazon  please tell me how can I used some music to test! I`m developer a devices like echo show! It`s system is android! pelase help me!!! and I want to play music just like echo show! I say "play nobody"!  It returns "Amazon Music is not supported on this device". I must use sdk to play amzon music?

**Comment by scotthea-amazon** [comment]
Hi FengXMGeek,

Yes, the SDK can play amazon music, for commercial devices.  You will need to contact us about enabling it.  If you are interested in using the SDK on android please contact privately.  You can use [this link](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) for both requests.

Thank you,
-SWH

**Comment by cucubits** [comment]
May I ask why was it decided to no allow music playing with the SDK on personal projects? With the low price of the echo dot, I'm sure this wouldn't undermine sales. Was there any other reason? I'm already paying for amazon prime, it would have been nice to be able to use this feature here.

**Comment by anu-mathur** [comment]
@cucubits Amazon Music is not allowed on AVS personal projects due to licensing restrictions. We’re sorry for the inconvenience.
