### ISSUE TITLE
sudo bash startauth.sh does not work for me

### ISSUE THREAD

**Issue by sm8224** [alexa/avs-device-sdk#557]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
when i run the command:

sudo bash startauth.sh

from /home/pi  I get an error of sudo bash startauth.sh: no such file or directory

## What is the expected behavior?
I expect it to allow me to generate an authorization token 

## What behavior are you observing?
 I get an error of sudo bash startauth.sh: no such file or directory

## Provide the steps to reproduce the issue, if applicable:
simply run the following command:

 sudo bash startauth.sh

### What version of the AVS Device SDK are you using?
   Not sure.   Just following the guide for this project.    

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ENT8R** [comment]
Did you used the [Quick Start Guide with Script](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script)?
Maybe you can try it without `sudo`: e.g. just simply `bash startauth.sh`... But I think there will be no difference...
And as your error says: `no such file or directory`: Are you sure that the file `startauth.sh` exists in the directory `/home/pi`?

**Comment by sm8224** [comment]
I did use the script, and modified my config.text file.  followed the steps precisely.  

There is no startauth.sh in the directory, no.    It seems it was never created.    so not sure whats up with that.

**Comment by ENT8R** [comment]
But there is a `setup.sh` file?
Even if it exists, I would recommend to follow the steps of the [quick start guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script) again.

**Comment by Linux00** [comment]
I have the same error

**Comment by sm8224** [comment]
I bailed out of it and started a different process to do this project.
Which still has its own problems.    But it's working better that this one
did.

**Comment by ENT8R** [comment]
How did you do that? Following the detailed guide about how to install the SDK?
And if your issue is now fixed, this issue can be closed, can not it?

**Comment by sm8224** [comment]
Yes.  Close it.     I followed different instructions from Lifehacker.com
for this project.     Thank you

**Comment by ENT8R** [comment]
I don't have the ability to close this issue, but you can do this by simply clicking on the button "Close issue" below the comment input box...

**Comment by celinval** [comment]
I'm closing this issue based on the comments above. Thank you!

**Comment by apollo13yuma** [comment]
I have also same issue. How can get startauth.sh file?
