### ISSUE TITLE
RaspberryPi setup script fails if hostname is changed

### ISSUE THREAD

**Issue by suzukieng** [alexa/avs-device-sdk#558]
## Briefly summarize your issue:

The setup.sh invocation shown in the RaspberryPi guide (https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script) leads to an error if the hostname of the RaspberryPi was changed to something other than 'raspberrypi'.

## What is the expected behavior?

Platform 'pi' should be detected even if hostname is not raspberrypi, e.g. via `lsb_release -a` or `cat /etc/os-release`

## What behavior are you observing?

setup.sh fails to determine platform.

```pi@raspi3-alexa:~ $ sudo bash setup.sh config.txt 
The installation script doesn't support current system. (System: Linux raspi3-alexa 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Linux)
```

## Provide the steps to reproduce the issue, if applicable:

- Change RasperryPi hostname, e.g. using the raspi-config configuration tool
- Launch setup.sh script

## Tell us about your environment:

- RaspberryPi 3, using Raspbian Strech

### What version of the AVS Device SDK are you using?

I'm using the installation script from the guide:
```
wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/setup.sh && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/config.txt && wget https://raw.githubusercontent.com/alexa/avs-device-sdk/master/tools/Install/pi.sh
```

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hi suzukieng,

Thank you for bringing this to our attention.  It looks like we will need to look in to rework the platform detection logic.  In the mean time, you could edit tools/Install/setup.h locally to always set PLATFORM="pi".

I hope this helps,
-SWH

**Comment by bxnyintuc** [comment]
Same issue here.

**Comment by kclchan** [comment]
We have updated the setup.sh to better detect if the platform is "pi".  Thanks for bringing this to our attention.
