### ISSUE TITLE
How to use ExternalMediaPlayer CA

### ISSUE THREAD

**Issue by sundq** [alexa/avs-device-sdk#559]
How to use the ExternalMediaPlayer CA，I do not get the demo code in the sample application， can I use this CA to play local alert audio

**Comment by scotthea-amazon** [comment]
Hi sundq,

The new ExternalMediaPlayer CA is not for playing alert audio.  It is a new framework to allow AVS to interact with music providers that manage their own play queue.

Thank you,
-SWH
