### ISSUE TITLE
Linking error while linking libAVSCommon.so on OpenWRT platform

### ISSUE THREAD

**Issue by barrel35618** [alexa/avs-device-sdk#56]
Hi, I tried to port this SDK on OpenWRT platform, and got the linking error when it's linking libAVSCommon.so, it shows below message:
../../libAVSCommon.so: undefined reference to `_ZTHN14alexaClientSDK9avsCommon5utils6logger13ThreadMoniker15m_threadMonikerE'

And I found that this method should be provided by "ThreadMoniker.cpp.o" which comes from "ThreadMoniker.cpp". After using objdump and nm tools to verify this object file, it didn't contain required information in its symbol table. I also built this SDK on local side(x86 platform), it works fine without meet this issue.

I've compared these two object files which built by "x86 g++" and "arm-g++".
There is something missing in arm version.
![ss1](https://user-images.githubusercontent.com/29232958/28157841-5ec7f24c-67ea-11e7-9bc1-37d06fde8084.png)
.

Have you met this issue before? Or do you have any idea about how to deal with that?
Thanks.

My x86 g++ version is 4.8.4, the OpenWRT arm is 4.8.3.
I also check CFLAGS and related argument, it's all the same.

**Comment by jimmy2yang** [comment]
Thanks scotthea, we can pass this error and build the ibAVSCommon.so.

**Comment by thevamad** [comment]
@jimmy2yang : Can you please share the makefile recipe for building AVS on OpenWRT?

**Comment by jimmy2yang** [comment]
@thevamad : attachment is the Makefile for OpenWrt feed. I also add cmake file in the alexa sdk to setup some environment variables (It is dirty and should move to openwrt makefile)
[Makefile.txt](https://github.com/alexa/avs-device-sdk/files/1508265/Makefile.txt)

[openwrt.cmake.txt](https://github.com/alexa/avs-device-sdk/files/1508266/openwrt.cmake.txt)

**Comment by thevamad** [comment]
@jimmy2yang : thanks a ton for sharing.

**Comment by thevamad** [comment]
@jimmy2yang : Did you run the sample app on Openwrt? If so, how did you build gstreamer and the plugins (base, good, ugly)

**Comment by jimmy2yang** [comment]
Yes, I ran SampleApp on Openwrt. You can port the related packages from Openwrt packages repo.

**Comment by thevamad** [comment]
@jimmy2yang : thanks for the response. I have the packages from github. Which of the gstreamer good / base / ugly modules did you select ? Did you have to select some or all out of the submenus ?
Thanks again for your help!

**Comment by jimmy2yang** [comment]
I just enable all of good/base/ugly gstreamer modules. You can try to turn off somethings.

**Comment by yyccz123** [comment]
@jimmy2yang Can you please share the nghttp2 makefile recipe for building AVS on OpenWRT?

**Comment by thevamad** [comment]
@jimmy2yang : Can you please attach the version of threadmoniker.c and h that you used to pass the error ?

**Comment by lapchow** [comment]
Hi Developer, 
My company is looking for a developer for helping us porting AVS on OpenWRT as a project-based job.

Please contact me if you are interested. 
lap.chow@tinklabs.com
