### ISSUE TITLE
How can I let AVS know that my device is with screen?

### ISSUE THREAD

**Issue by FengXMGeek** [alexa/avs-device-sdk#560]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I try to use "the tonight show" skill to play video In avs-device-sdk project !
 I can reach a url :" https://s3.amazonaws.com/content-prod-tsjf-alexa-audio-us-east-1/Monologue.mp3" .
It`s not a video! But I can show a video in echo show with the some voice comand ！
Is these some parameters to tell cloud :"I`m a device with screen "?
## What is the expected behavior?

I want to get a mp4 url from the directive
## What behavior are you observing?

I can a mp3 url from the directive! but It run a video on  echo show !
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
android
### Tell us about your OS (Type & version):
android

**Comment by scotthea-amazon** [comment]
Hi FengXMGeek,

I am sorry to report that the AVS interfaces and avs-device-sdk project do not yet support the display of video.

Thank you,
-SWH

**Comment by FengXMGeek** [comment]
@scotthea-amazon  Hi,
I see a Scenario 5: "Alexa, what movies are playing by me?"
It show that my product can play a video !
https://developer.amazon.com/docs/alexa-voice-service/audioplayer-overview.html
and : Recommended Media Support , It show we must support for mp4!
https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html

**Comment by FengXMGeek** [comment]
@scotthea-amazon It`s impossible to play a video im my device?

**Comment by ENT8R** [comment]
The example scenario (number 5) you linked is not for playing a video on your device but rather for asking Alexa what movies are shown in **cinemas**  near your current location (nearby)

**Comment by ENT8R** [comment]
> @scotthea-amazon It`s impossible to play a video im my device?

He said that already: it is currently not possible at all...

**Comment by FengXMGeek** [comment]
@ENT8R so sadness to hear this message!!!!

**Comment by ENT8R** [comment]
So can this issue be closed now?

**Comment by FengXMGeek** [comment]
@ENT8R @scotthea-amazon  can you tell me the roadmap of api to display of video?

**Comment by FengXMGeek** [comment]
@ENT8R  wait please! I want to confirm it that we can make a right choose!

**Comment by anu-mathur** [comment]
@FengXMGeek We plan to add the video support in future, but do not have a date on it yet. Closing this thread for now.  Will post an update when we have a timeline.
