### ISSUE TITLE
How to update the SDK

### ISSUE THREAD

**Issue by GYJohn** [alexa/avs-device-sdk#561]
Hello,

to get the newest version of the sdk just use wget or is there any other option to not download everything?

Thank you.

**Comment by ENT8R** [comment]
The simplest way would be indeed to rerun the [simple install script](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script).
If you search for the ability to only update a single package or library, the best way would be to follow the [step-by-step guide](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide) which has detailed instructions on every single library/repository which is needed...

**Comment by GYJohn** [comment]
Okey, thank you.
Then i will rerun the install script.
