### ISSUE TITLE
Sound get slow and broken when Alexa speaks

### ISSUE THREAD

**Issue by a2ron** [alexa/avs-device-sdk#563]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Sound get slow and broken when Alexa speaks. When starting, I can reproduce a mp3 with no problems, but after Alexa speaks its first words, sound quality (pitch, speed...) get bad.

## What is the expected behavior?
Alexa speaks OK instead of like the devil.

## What behavior are you observing?
Alexa modify the sound output in Raspberry PI.

## Provide the steps to reproduce the issue, if applicable:
Just ask something to alexa and wait for response, sound will get broken.

### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Logs I think are related:
```
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
```

**Comment by Linux00** [comment]
I have the same question

**Comment by ENT8R** [comment]
Could you maybe run `arecord -l` and `aplay- l` and list the results here? And could you also paste the content of the `.asoundrc` file here?

**Comment by cucubits** [comment]
I had this happen to me as well. I could record/play sound just fine, .asoundrc was configured properly but Alexa would speak in slow motion. This was after experimenting and installing the SDK multiple times, I think I even tried google assistant on the same rpi. Most likely some driver or dependency got messed up. Once I installed everything again on a clean raspbian, following the provided guide, it worked fine, no more slow motion speaking.

**Comment by celinval** [comment]
Hi @a2ron,

This may be a side effect of our current workaround to get Audible working. Can you please turn on audioSink on [MediaPlayer.cpp line 667](https://github.com/alexa/avs-device-sdk/blob/v1.6/MediaPlayer/src/MediaPlayer.cpp#L667) and see if it fixes your problem? Please replace the following line:

`g_object_set(m_pipeline.audioSink, "sync", FALSE, NULL);`

by:

`g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);`

Let me know if it works,
Thanks

**Comment by Linux00** [comment]
it doent works(replace g_object_set(m_pipeline.audioSink, "sync", FALSE, NULL);

by:

g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);

**Comment by ENT8R** [comment]
Did you run `make SampleApp` after changing the file?

**Comment by a2ron** [comment]
@celinval Unfortunately, I can't check it because I solved the issue. Just installing it in a previous Raspbian Stretch release.
latest [2018-03-13](https://www.raspberrypi.org/downloads/raspbian/) DOESN'T WORK
previous [2017-11-16](https://www.raspberrypi.org/downloads/raspberry-pi-desktop/) WORKS FINE

**Comment by Marlor** [comment]
The latest Raspbian uses a new audio driver:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=195178
Until it is fixed in Alexa you can use the old one:
Add "audio_pwm_mode=1" in "/boot/config.txt"

**Comment by celinval** [comment]
Hi @a2ron, I'm happy you managed to solve your problem. Thank you and @Marlor for bringing our attention to a possible issue with the latest Raspbian Stretch release. We'll look into it.

**Comment by a2ron** [comment]
@Marlor I got the issue again and I solved doing you told us. Thanks!

**Comment by L1ghtning01** [comment]
I also have the same problem and adding "audio_pwm_mode=1" to "/boot/config.txt" did not change anything. Any suggestions?

**Comment by atresnjo** [comment]
I have the same issue running Raspbian Buster 4.19. Audio works fine playing youtube videos, spotify etc, but Alexa is the only issue.

> 
> 
> Hi @a2ron,
> 
> This may be a side effect of our current workaround to get Audible working. Can you please turn on audioSink on [MediaPlayer.cpp line 667](https://github.com/alexa/avs-device-sdk/blob/v1.6/MediaPlayer/src/MediaPlayer.cpp#L667) and see if it fixes your problem? Please replace the following line:
> 
> `g_object_set(m_pipeline.audioSink, "sync", FALSE, NULL);`
> 
> by:
> 
> `g_object_set(m_pipeline.audioSink, "sync", TRUE, NULL);`
> 
> Let me know if it works,
> Thanks

Tried this, ran the make file, it rebuilt the SampleApp and then I started it again but didn't help sadly.

> 
> 
> The latest Raspbian uses a new audio driver:
> https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=195178
> Until it is fixed in Alexa you can use the old one:
> Add "audio_pwm_mode=1" in "/boot/config.txt"

Tried this also, didn't help.

> 
> 
> Thanks @celinval!
> 
> Unfortunately, I can't check it because I solved the issue. Just installing it in a previous Raspbian Stretch release.
> 
> latest [2018-03-13](https://www.raspberrypi.org/downloads/raspbian/) DOESN'T WORK
> previous [2017-11-16](https://www.raspberrypi.org/downloads/raspberry-pi-desktop/) WORKS FINE

I guess I'll try this then.

**Comment by yanjunding** [comment]
@atresnjo Found solution?
same issue

**Comment by atresnjo** [comment]
> 
> 
> @atresnjo Found solution?
> same issue

I installed an older raspbian version from 2017 and that fixed it.

**Comment by sidchigo** [comment]
One solution that worked for me is to remove pulseaudio as that causes the broken voice issue.

**Comment by rajat8888** [comment]
I am still facing the same issue after trying even everything mentioned here. Alexa is sound slow and drunk
