### ISSUE TITLE
Connection refused Localhost:3000 - Refresh Token

### ISSUE THREAD

**Issue by Artka06** [alexa/avs-device-sdk#566]
Hello,

I am trying to Install Alexa on my Raspberry PI 2 following the step by step guide on github.

When I arrive to the moment where I should open localhost:3000 in my browser, I get under chrome and firefox, an error message: You can't reach this website - Localhost doesn't allow the connection.

Therefore, I can't get my refresh token to update the json file on my raspberry Pi.

When I launched the command: cd /home/pi/sdk-folder/sdk-build && python AuthServer/AuthServer.py

I get a message on my console saying:
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

I verified that my secret ID, amazon ID as well as product ID are correct to put this aside.

Do you have any idea on why I can't access my localhost via Chrome?

### Tell us what hardware you're using:
- [ X] Desktop / Laptop (Windows 10)
- [X ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Thank you so much for your help!!

**Comment by celinval** [comment]
Hi @Artka06, 

The error 400 is expected if you haven't acquired a valid token yet. When you run the AuthServer script, is this the exact output you are seeing?

> The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.
>
> \* Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)

Can you please click on the link and paste the exact error you are seeing in your browser? After you try to open it in your browser, can you also see if there is any new message in the AuthServer logs after you click the link?

Thanks,

**Comment by ZhichengG** [comment]
I see this "127.0.0.1 - - [23/Mar/2018 11:11:30] "GET / HTTP/1.1" 302 -"

**Comment by celinval** [comment]
How are you opening the link? Can you paste the address http://127.0.0.1:3000/ in your browser?

The 302 response is normal, since the link should redirect you to the amazon login page.

**Comment by dhpp** [comment]
Closing for now.  Please re-open if you need further assistance with this.

**Comment by xuqifu** [comment]
@ZhichengG I have same problem I am try to paste the address http://127.0.0.1:3000/ in a private window in  browser, but The connection always timed out, have you slove this problem? can you give a hand 
thanks !

**Comment by xuqifu** [comment]
@celinval    I have same problem I am try to paste the address http://127.0.0.1:3000/ in a private window in browser, but The connection always timed out, have you slove this problem? can you give a hand
thanks !

**Comment by xuqifu** [comment]
@celinval 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.
 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
redirect.
127.0.0.1 - - [02/May/2018 05:44:06] "GET / HTTP/1.1" 302 -
redirect.
127.0.0.1 - - [02/May/2018 05:46:17] "GET / HTTP/1.1" 302 -
redirect.
127.0.0.1 - - [02/May/2018 06:32:29] "GET / HTTP/1.1" 302 -
