### ISSUE TITLE
APP SDK for iOS and Android

### ISSUE THREAD

**Issue by rellfan** [alexa/avs-device-sdk#57]
Hi, I am APP developer. Are there SDK or Library for Android and iOS platform? We want to enable Alexa service on our own APP. Thanks.

**Comment by vkreal** [comment]
@jairajiv We have the same use case for Android and iOS platform. Can you please discuss it with us?

**Comment by jairajiv** [comment]
@vkreal - AVS provides code for companion apps for Android and iOS. The companion app is used for enrolling and managing an AVS device. Here are the links to companion apps.

Android - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/androidCompanionApp
iOS - https://github.com/alexa/alexa-avs-sample-app/tree/master/samples/iOSCompanionApp

If you want to discuss your use case further, Please fill out this [Contact Form.](https://tinyurl.com/AVSContactForm).

**Comment by youfu88** [comment]
@jairajiv 
  I have the same use case for Android and iOS platform. And I have already asked the same question on  the https://github.com/alexa/alexa-avs-sample-app/issues/1036#issuecomment-348216027,
  " The actual java AVS application is not supported on Android. It has only been tested on the platforms you listed above. There is an AVS C++ SDK, which does not formally support android yet, but has been successfully deployed on Android by other users."
Is it possible to provide libs for android or ios platform?
Thanks!

**Comment by scotthea-amazon** [comment]
Hi @jairajiv,

Sorry, but we do not have support for Android or iOS at this time.

Regards,
-SWH

**Comment by vkreal** [comment]
@scotthea-amazon do you guys expect to support Android in the near future?

**Comment by madhuravulapalli** [comment]
@scotthea-amazon 

do you mean can't build AVS sdk with android platform.?Some folks are saying  we can build the AVS SDK  with Android NDK.

**Comment by prihtiv** [comment]
I'm also struggle with the Alexa to connect with my custom skill. Its working fine on the test emulator which provided in the Alexa voice service, but i try to connect with my android application I'm not able to gettting the response as like as the emulator. I dont know what was the exact problem which i did.so please anyone help me out from this problem.Thanks in advance...
contact me as private aslo : kprithiv.003@gmail.com

**Comment by testCovai** [comment]
@prihtiv kindly help me i'm also struggling while integrating app to app linking using alexa skill kit
