### ISSUE TITLE
How to know device has been deregister ?

### ISSUE THREAD

**Issue by melancholyhua** [alexa/avs-device-sdk#574]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How to know device has been deregister ?

## What behavior are you observing?

Case 1: 
If do deregister when device is online, I only receive some debug msg(see attachment), is there have any function or flags can be identify ? So that I could let device go to setup mode immediately.
[deregister.log](https://github.com/alexa/avs-device-sdk/files/1836540/deregister.log)

Case 2:
If do deregister when device in offline, once device goes to online, I can check AuthObserverInterface::State::UNRECOVERABLE_ERROR via onAuthStateChange function. Hence I can handle this case.

Thanks.

### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [X] Other - tell us more:
Cross compile on embedded

### Tell us about your OS (Type & version):
- [x] Linux

**Comment by celinval** [comment]
Hi @melancholyhua, 

That's a great question! We are still improving the device deregistration experience. For now, please check the answer provided in #339.

Thanks
