### ISSUE TITLE
17 TaskThread 

### ISSUE THREAD

**Issue by sunjunlishi** [alexa/avs-device-sdk#576]
void TaskThread::start() {
	printf("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ TaskThread::start() %x\n",this);
    m_thread = std::thread{std::bind(&TaskThread::processTasksLoop, this)};
}
The program structure can consider the single pattern, considering the interaction between the 3 main classes; the sound playing, the Sound in, and the Amazon server interaction of three classes .
Too many threads, I don't think it's a good idea ,Although the structure of the program is perfect .

**Comment by celinval** [comment]
Hi @sunjunlishi, thank you for your feedback. I'll raise your suggestion in our team.
