### ISSUE TITLE
No playback sound... Still

### ISSUE THREAD

**Issue by sergeyDoroshenko** [alexa/avs-device-sdk#577]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
No audio played over USP speaker on raspberry pi 3

## What is the expected behavior?
audio should be played over USP speaker on raspberry pi 3 if .asoundrc specifies so.

## What behavior are you observing?
No sound when Alexa responds. 

## Provide the steps to reproduce the issue, if applicable:
say Alexa, then ask a question, then listen for the response.

### What version of the AVS Device SDK are you using?
[1.6.0] - 2018-03-08

### Tell us what hardware you're using:
Raspberry Pi 3

### Tell us about your OS (Type & version):
Raspbian Stretch

**Comment by celinval** [comment]
Hi @sergeyDoroshenko,

Do you mean USB speakers?  Can you please provide the following:

- Complete DEBUG9 logs of the sample app.
- Current content of ~/.asoundrc
- Output of the following command: `aplay -L -l`

Can you also please run the following commands and report if you are able to listen to any sound:
```
aplay <some_wav_file>
gst-launch-1.0 -m audiotestsrc ! autoaudiosink
gst-launch-1.0 -m audiotestsrc ! alsasink
```

Thanks

**Comment by sergeyDoroshenko** [comment]
@celinval:

this is the content of `~/.asoundrc` that works for standard tools like `aplay`:
`
pcm.dmixer {

    type dmix

    ipc_key 1024

    slave {

        pcm "hw:1,0"

        period_time 0

        period_size 1024

        buffer_size 8192

        rate 44100

    }



}

pcm.!default {
	type asym

        playback.pcm {

                type plug

		slave.pcm "dmixer"
        }

        capture.pcm {

                type plug

		slave {
	    		pcm "hw:1,0"
		}
        }
}
`

`aplay <wav file>` works correct

`aplay -L -l` output:
`null
    Discard all samples (playback) or generate zero samples (capture)
dmixer
default
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
sysdefault:CARD=CX100
    Polycom CX100, USB Audio
    Default Audio Device
front:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    Front speakers
surround21:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    Direct sample mixing device
dsnoop:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    Direct sample snooping device
hw:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    Direct hardware device without any conversions
plughw:CARD=CX100,DEV=0
    Polycom CX100, USB Audio
    Hardware device with all software conversions
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: CX100 [Polycom CX100], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

How to create complete logs with DEBUG9?

will send gst-launch-1.0 output later.

**Comment by sergeyDoroshenko** [comment]
@celinval:
`gst-launch-1.0` is not installed. should it be installed?

**Comment by sergeyDoroshenko** [comment]
@celinval:
Here is a closed issue that seems equal to the current one:
https://github.com/alexa/avs-device-sdk/issues/500

The wasn't fixed there.

**Comment by sergeyDoroshenko** [comment]
@celinval:
found this comment: https://github.com/alexa/avs-device-sdk/issues/500#issuecomment-368462509
That makes my USB speaker working for me.

**Comment by celinval** [comment]
Awesome! I'm happy to hear that you fixed your problem. :)
