### ISSUE TITLE
I want to know the wakeword whether wake up in the local?

### ISSUE THREAD

**Issue by snailwft** [alexa/avs-device-sdk#578]
hi,
I want to know whether the awakening is to wake up in the local or send the recording to the cloud, to wake up in the cloud?

**Comment by sanjayrd** [comment]
HI @snailwft,

All wake word detection happens locally. No audio is sent to the cloud until a wake word is detected locally.

Hope that helps,
Sanjay

**Comment by kclchan** [comment]
Hi @snailwft, I'm closing this issue now, but please reopen if you're still having further questions.
