### ISSUE TITLE
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by AkdM** [alexa/avs-device-sdk#579]
Following the Ubuntu Linux Quick Start Guide, I have a CMake error while building the Alexa SDK (with and without wakeword activated)

## What is the expected behavior?
Correctly build the SDK

## What behavior are you observing?
CMake error whild building the Alexa SDK:

```
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) (Required is
  at least version "7.43.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.7/Modules/FindCURL.cmake:50 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  AVSCommon/CMakeLists.txt:3 (find_package)
```

## Provide the steps to reproduce the issue, if applicable:
Follow the Wiki page, I did not do anything else really

## Tell us about your environment:
Debian 9.4.0 - amd64, freshly installed OS

### What version of the AVS Device SDK are you using?
      1.6

### Tell us what hardware you're using:
[FitPC-3](http://www.fit-pc.com/web/products/specifications/fit-pc3-models/?model%5B%5D=fit-PC3i-T56N-FM0)

### Tell us about your OS (Type & version):
Debian 9.4.0 - amd64

**Comment by priyagsenthil** [comment]
Hi,

Have you followed the instructions listed under 

https://github.com/alexa/avs-device-sdk/wiki/Build-libcurl-with-mbed-TLS-and-nghttp2

to build the CURL libraries. Please confirm.

Thanks

**Comment by priyagsenthil** [comment]
Hi,

A correction - the above link is only to build CURL with mbedTLS.

Download the latest version of curl and configure with support for nghttp2 and openssl:

Use the Ubuntu reference guide 
https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide 

for instructions to build curl with-ssl.

Am pasting the relevant segments below 
cd ~/sdk-folder/third-party
wget http://curl.haxx.se/download/curl-7.54.0.tar.bz2
tar -xvjf curl-7.54.0.tar.bz2
cd curl-7.54.0
./configure --with-nghttp2=/usr/local --with-ssl
make
sudo make install
sudo ldconfig

**Comment by AkdM** [comment]
That worked.
In fact, I was using curl v7.59, which is the actual latest version. It seems it won't work with that version.

**Comment by kclchan** [comment]
Hi @AkdM, I am closing this issue now, but please reopen if you're still having issues.
