### ISSUE TITLE
failed to build avs-device-sdk 1.6

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#583]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have no problem build avs-device-sdk 1.4, and recently I'm trying to update to 1.6. But in the same build environment, build avs-device-sdk 1.6 failed due to following error:

[ 16%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/SafeCTimeAccess.cpp.o
[ 16%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Stream/StreamFunctions.cpp.o
[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Stream/Streambuf.cpp.o
[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/StringUtils.cpp.o
[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskQueue.cpp.o
[ 17%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TaskThread.cpp.o
[ 18%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimePoint.cpp.o
[ 18%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimeUtils.cpp.o
[ 18%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Timer.cpp.o
[ 19%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/UUIDGeneration.cpp.o
/home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/src/TimeUtils.cpp: In member function 'bool alexaClientSDK::avsCommon::utils::timing::TimeUtils::convertTimeToUtcIso8601Rfc3339(const alexaClientSDK::avsCommon::utils::timing::timeval&, std::__cxx11::string*)':
/home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/src/TimeUtils.cpp:231:36: error: invalid use of incomplete type 'const struct alexaClientSDK::avsCommon::utils::timing::timeval'
     const time_t timeSecs = timeVal.tv_sec;
                                    ^
In file included from /home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/src/TimeUtils.cpp:23:0:
/home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Timing/TimeUtils.h:98:54: note: forward declaration of 'struct alexaClientSDK::avsCommon::utils::timing::timeval'
     bool convertTimeToUtcIso8601Rfc3339(const struct timeval& t, std::string* iso8601TimeString);
                                                      ^~~~~~~
/home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/src/TimeUtils.cpp:248:86: error: invalid use of incomplete type 'const struct alexaClientSDK::avsCommon::utils::timing::timeval'
     millisecondTrailer << buf << "." << std::setfill('0') << std::setw(3) << (timeVal.tv_usec / 1000) << "Z";
                                                                                      ^
In file included from /home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/src/TimeUtils.cpp:23:0:
/home/theuser/avs/src/sdk-source/avs-device-sdk/AVSCommon/Utils/include/AVSCommon/Utils/Timing/TimeUtils.h:98:54: note: forward declaration of 'struct alexaClientSDK::avsCommon::utils::timing::timeval'
     bool convertTimeToUtcIso8601Rfc3339(const struct timeval& t, std::string* iso8601TimeString);
                                                      ^~~~~~~
make[2]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:1239: AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/TimeUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1337: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by subjectxbj** [comment]
Looks like the compiler automatically add the namespace "alexaClientSDK.avsCommon.utils.timing" to the struct "struct timeval". I think you need to specify the name space to avoid this problem.

**Comment by priyagsenthil** [comment]
Which platform are you using to build the C++ SDK. struct timeval probably requires <sys/time.h> to be included.  Could you try adding this and checking if it builds.

**Comment by subjectxbj** [comment]
I'm building in the alpine-linux on a ARMv7 device. I will try add <sys/time.h>

**Comment by subjectxbj** [comment]
Hi priyagsenthil,
The compile pass after include <sys/time.h>. Do you have plan to fix this problem in the next release?

**Comment by priyagsenthil** [comment]
Yes we will.

**Comment by dhpp** [comment]
Closing.  This fix has been committed to the next release of the SDK.  Thanks again for bringing this to our attention.
