### ISSUE TITLE
About the avs SDK for display support.

### ISSUE THREAD

**Issue by lukunnr** [alexa/avs-device-sdk#584]
Hi 
Where can I find the SDK support for display? Currently, many of the code I see is about voice, but there is no part of the display, just as echo show can support display on the LCD.

**Comment by priyagsenthil** [comment]
The only support related to display available in the C++ SDK is the TemplateRunTime capabilityAgent which sends URL of images and the renderer is left to the integrator. There is no full fledged display support as in Echo Show in the SDK yet.

**Comment by lukunnr** [comment]
thank you，So what you're saying is that echo show is simply rendering the content of the url that's returned, without doing too much other intervention? So should I be able to do the same with the echo show if I implemented a browser?

**Comment by priyagsenthil** [comment]
No Alexa Show is doing more but the C++ SDK does not support all of the display features available in Echo Show. It only supports TemplateRunTime for display support the interface of which can be found in https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html.

**Comment by dhpp** [comment]
The C++ Client SDK is a reference implementation of the [AVS Interface](https://developer.amazon.com/docs/alexa-voice-service/api-overview.html), and as such we can only implement features which that service provides.  I would suggest you make visual feature suggestions for AVS at our forum [here](https://forums.developer.amazon.com/spaces/185/index.html).  In the meantime, I will close this ticket for now, as the question is outside the scope of the Client SDK.
