### ISSUE TITLE
How to activate Alexa when audio is played locally or via blutooth

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#589]
Hi,

Just like in Amazon Echo device, when some song or audio is played via bluetooth and if it is queried by saying Alexa, then Amazon Echo paused the audio and response to the query. And then again resume the song.

So how this behaviour can be possible in avs-device-sdk?

I have to play the audio file or song locally and want avs-device-sdk to pause the song when it enters in LISTENING mode by saying Alexa Wakeword and then again resume back the song when it goes to IDLE mode.

avs-device-sdk version  - 1.6
OS - Ubuntu

Thanks,
Sumit

**Comment by priyagsenthil** [comment]
Hi sumit,

Bluetooth is not currently supported in C++ SDK.

Thanks
Priya

**Comment by sumit3817** [comment]
Hi Priya,

Just want to know whether avs-device-sdk can pause the music or audio which is played locally or via blutooth when it enters in Listening mode.
Currently, Amazon Echo device is supporting this functionality.
It doesn't matters whether the music is played via bluetooth or played locally.

Thanks,
Sumit

**Comment by priyagsenthil** [comment]
Hi Sumit,

avs-device-sdk supports pause of music played locally either through voice-control (Alexa, Pause), Alexa companion app or during barge-in.

Thanks
Priya

**Comment by sumit3817** [comment]
Hi Priya,

Here is the scenario:-
The device is supporting bluetooth. And then using my phone I connect to that device using bluetooth and then play a song. 
Alexa application (avs-device-sdk)  is also running as an independent process on the same device. Now when I queried by saying Alexa, it comes in Listening mode and responds to my query but didn't pause the current music which is played locally via bluetooth.

The same scenario is supported by Amazon Echo device. 

How this can be achieved in Alexa application (avs-device-sdk)?

Thanks,
Sumit

**Comment by kclchan** [comment]
Hi @sumit3817, thanks for clearly describing the scenario.  This is not currently possible because the bluetooth audio is managed by the device's OS.  In the future when avs-device-sdk supports the Bluetooth interface (https://developer.amazon.com/docs/alexa-voice-service/bluetooth.html), then this support is possible.

**Comment by sumit3817** [comment]
Hi @kclchan 
Thanks for the information. 
 Can you please let me know when this bluetooth interface support will be available in avs-device-sdk?

Thanks,
Sumit

**Comment by kclchan** [comment]
The Bluetooth interface is on our feature roadmap, but we can't comment on schedule here.  Thanks for asking about this.

**Comment by kjkh** [comment]
Hi @sumit3817,

We have released the Bluetooth interface supporting the SINK use-case. This means that it will support a device (such as a phone) streaming to the AVS enabled device. Instructions on enabling it for Ubuntu can be found [here](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide#bluetooth). It can be compiled with the cmake option: -DBLUETOOTH_BLUEZ=ON.

I believe this answers your original question, so I will be closing the issue. However, please feel free to re-open if there are further questions.
