### ISSUE TITLE
Can't get display cards

### ISSUE THREAD

**Issue by syl22-00** [alexa/avs-device-sdk#590]
My client has `displayCardsSupported` set to true, but lambda functions associated to skills I make see 
`event.context.System.device.supportedInterfaces.Display` as false. If I call `renderTemplate` anyways, the returned audio says there is an error.

If this is a known issue, can you advise on how to send data back to the device? I tried to set session attributes in the lambda function but can't find how to see those attributes in the client.

I am using the latest available code of the SDK.

**Comment by priyagsenthil** [comment]
Its probably an issue with the SKILLs. We will check internally and get back to you.

**Comment by kclchan** [comment]
Hi @syl22-00, could you make sure if display cards is enabled by following this instruction?
https://developer.amazon.com/docs/alexa-voice-service/display-cards-overview.html#enable-display-cards

**Comment by syl22-00** [comment]
Thanks @kclchan , I indeed did not have this setting right, but after setting it, I still do not get the cards. As a summary, I have:

* "displayCardsSupported": true in the config file
* A skill with DisplayInterface On
* A device with Display Cards enabled

But in the lambda function, event.context.System.device.supportedInterfaces.Display is still false, and If I ignore it and still send a card, I get one with those error messages:
```
"title":{"subTitle":"my-skill-name","mainTitle":"Invalid Directive"},"textField":"Request Identifier: ...\n\nThe target device does not support directives for the Display interface"}
```

**Comment by kclchan** [comment]
Hi @syl22-00, could you check if you are getting a display card in the SampleApp if you ask for the weather?  Thanks!

**Comment by kclchan** [comment]
Hi @syl22-00, I am going to close this issue now.  You may try to post your questions in this forum to get more help related to your skill:
https://forums.developer.amazon.com/spaces/23/index.html
