### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by crashflow** [alexa/avs-device-sdk#593]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

On a Raspberry Pi Zero W the sample app crashes on start up.
## What is the expected behavior?

The app should run and not crash
## What behavior are you observing?

When I start the app, it fails after the notification phase and gives an error Illegal Instruction.
## Provide the steps to reproduce the issue, if applicable:

Make sure audio works (it does). Compile from source using instructions. Authorize. Run sample app.
### What version of the AVS Device SDK are you using?
      1.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi Zero W
- [x ] Other - tell us more: Seeed Voicecard 2 Mic Hat

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

The audio works well. And works well on Pi3 with Alexa working properly. I am trying to configure the unit and integration tests, but I'm having trouble with them because I'm not experienced.

Bash output:

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

2018-03-30 19:23:25.957 [  1] 5 TemplateRuntime:addObserver
2018-03-30 19:23:25.959 [ 10] 5 TemplateRuntime:addObserverInExecutor
2018-03-30 19:23:25.953 [  f] 0 HTTP2Transport:cleanupFinishedStream:streamId=3,result=204
2018-03-30 19:23:25.966 [  f] 0 HTTP2StreamPool:releaseStream:streamId=3,numAcquiredStreams=1
2018-03-30 19:23:25.969 [  f] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
./startsample.sh: line 3:  1896 Illegal instruction     ./SampleApp "/home/pi/Documents/alexa/build/Integration/AlexaClientSDKConfig.json" "/home/pi/Documents/alexa/third-party/alexa-rpi/models" DEBUG9

____________________

Strace: 

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

2018-03-30 19:29:29.833 [  1] 5 TemplateRuntime:addObserver
2018-03-30 19:29:29.835 [ 10] 5 TemplateRuntime:addObserverInExecutor
2018-03-30 19:29:29.829 [  f] 0 HTTP2Transport:cleanupFinishedStream:streamId=3,result=204
2018-03-30 19:29:29.847 [  f] 0 HTTP2StreamPool:releaseStream:streamId=3,numAcquiredStreams=1
2018-03-30 19:29:29.848 [  f] 0 CurlEasyHandleWrapper:reset:responseCode=HTTP_RESPONSE_SUCCESS_NO_CONTENT
[{WIFSIGNALED(s) && WTERMSIG(s) == SIGILL}], 0, NULL) = 2000
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6e036b0}, {sa_handler=0x53014, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb6e036b0}, 8) = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
brk(0xfb0000)                           = 0xfb0000
read(3, "# Locale name alias data base.\n#"..., 4096) = 2995
brk(0xfb1000)                           = 0xfb1000
brk(0xfb2000)                           = 0xfb2000
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "./startsample.sh: line 3:  2000 "..., 202./startsample.sh: line 3:  2000 Illegal instruction     ./SampleApp "/home/pi/Documents/alexa/build/Integration/AlexaClientSDKConfig.json" "/home/pi/Documents/alexa/third-party/alexa-rpi/models" DEBUG9
) = 202
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=2000, si_uid=0, si_status=SIGILL, si_utime=148, si_stime=33} ---
wait4(-1, 0xbee4bf9c, WNOHANG, NULL)    = -1 ECHILD (No child processes)
sigreturn({mask=[]})                    = 0
read(255, "", 201)                      = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
exit_group(132)                         = ?
+++ exited with 132 +++

**Comment by priyagsenthil** [comment]
Your issue seems related to https://github.com/alexa/avs-device-sdk/issues/503.

As noted in the thread we do not actively test the SDK on Pi Zero.
Can you try some of the suggestions from there?

1. Remove third party libraries like WW.
2. Start a fresh install or verify the versions of required third party libraries - curl, nghttp2 as the path of the illegal instruction seems to lead to CURL.
3. Compile the SDK with the -DCMAKE_BUILD_TYPE=Debug option to get a debug build.
4. Provide logs and trace of the crash.

**Comment by crashflow** [comment]
Thanks for the advice. I'll try. I would urge you to try and make the Zero work - the small form factor is irresistible and just begs to be put everywhere.

I have a noob question - I am pretty sure that the raspbi build specifies debug option for build. Are the logs that I copied not debug logs?

Again I know this isn't really on topic with the Zero W, so thanks for replying.

**Comment by kclchan** [comment]
Hi @crashflow, thanks, we are seeing the debug logs.

Could you try modifying the pi.sh and disable the wakeword detection to OFF (i.e. -DSENSORY_KEY_WORD_DETECTOR=OFF) and run the script again.  I think we are getting the illegal instruction error due to the library file from git://github.com/Sensory/alexa-rpi.git is not compatible with pi Zero.

**Comment by dhpp** [comment]
Closing for now.  Please re-open if you'd like further guidance from us.

**Comment by sriranjanr** [comment]
I am getting the exact same problem and I am using raspberry pi zero w.
