### ISSUE TITLE
Amazon Music is not supported on this device

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#596]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi Amazon,

I'm trying to do Music Self-Test. I have defined the product as a commercial product by marking "Yes" at item "Do you intend to distribute this product commercially?"

Then I tried to ask alexa to play music on the device, but it reponses "Amazon music is not supported on this device".

How can I do music self-test now in this case? 

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by anu-mathur** [comment]
Hi @subjectxbj 
Amazon Music is available only to whitelisted partners for commercial devices. Can we talk more about your use case, for next steps? Please fill out this contact form [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I'll reach out to you.

**Comment by subjectxbj** [comment]
Hi @anu-mathur ,
I have fill out the contact. Looking forward to get contact with you.

Thanks

**Comment by kclchan** [comment]
Hi @subjectxbj, thanks for getting in touch with us.  I am closing this issue now.  Thanks!
