### ISSUE TITLE
The sample app does not respond to locale change settings

### ISSUE THREAD

**Issue by aashwinGaur** [alexa/avs-device-sdk#597]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue
I want the sample app to start with "en-US" locale . I changed the value to "en-US" in  AlexaClientSDKConfig.json file also confirmed that the settings.db file has the value en-US. I re-compiled after changing the settings. But the app always starts with en-IN . I can change the locale by typing in the settings options in the terminal . But i have disabled the input as i wanted alexa to start on boot . 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ --->] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ --->] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @aashwinGaur, by changing the "locale" in terminal, does the setting persist after quitting and starting the SampleApp (without recompiling)?  If that's possible, are you using the same json file with the same database file after disabling input?

**Comment by kclchan** [comment]
Hi @aashwinGaur, thanks for the feedback.  We are looking into this issue and will let you know of any findings ASAP.  Thanks!

**Comment by dhpp** [comment]
@aashwinGaur, we have identified the root issue, and this will be fixed in an upcoming release of the SDK.  Thanks for bringing this to our attention.

**Comment by aashwinGaur** [comment]
Thank you
