### ISSUE TITLE
How to deregister a device not using hand-control on Alexa app?

### ISSUE THREAD

**Issue by actions-semi4378** [alexa/avs-device-sdk#598]
Hi,
We got a question and need your support. In normal way, when Echo is removed from my Amazon account and registered under my college's account, Echo is disappeared on my Alexa app and shown on Alexa app of my college's.

The problem we faced is device A (serial no. 12345678 for example) changed to be registered under my college's account. The device will still shown on my Alexa app but offline, meanwhile, on my college Alexa app. This makes isuses happen, sometimes device is on-line then off-line, on-line then off-line. And what we can do is only press deregister the device on Alexa app.
Is there any other way or API that can offer us to solve this problem? 

Thank you in advance!

**Comment by celinval** [comment]
Hi @actions-semi4378,

That's a great question. The SDK currently support factory reset which will wipe all the data saved on the device. Unfortunately, it still includes a manual step after the reset is performed.

You will need to deregister the device either using the Alexa App or Amazon website. See [this](https://www.amazon.com/gp/help/customer/display.html?nodeId=201357520) link for more details.

Best

**Comment by BennyAvramson** [comment]
Hi @actions-semi4378,

Regarding the issue you've raised on your first comment, as long as only a single account is online it should be fine.

Regarding request for the future, If you're interested in this feature, you should create a request for it in our Feature Request space within the forums: https://forums.developer.amazon.com/spaces/185/index.html. 

Thanks!

**Comment by dhpp** [comment]
I believe Celina and Benny have answered the key points here.  I will close for now.  Thanks.
