### ISSUE TITLE
Alexa volume level range

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#599]
Hi Amazon team,
 
I have a question about Alexa volume range.
By Echo user guide, the volume level is 1-10, so that I can ask : Alexa, volume 5
and from SDK it will receive 50 

Two questions here ,
(1) could it be re-ranged ? Eg, change to 1-11 , or 1-15 by product defined ?
(2) how to asked Alexa to adjust volume to 63 by voice command ?

Thanks,

**Comment by kclchan** [comment]
Hi @zeusshuang,
(1) The range cannot be product defined.  But please take a look at the Normalizer.cpp as a reference on how to normalize the volume range (0-100) from AVS to your product.
(2) No, this cannot be done with voice.  But you can do this in the companion app.

Thanks,
Kenneth

**Comment by zeusshuang** [comment]
Hi @kclchan ,

thanks for the comment.
Double confirm here ,
(1) From Echo for voice command, the level is 1-10 , it cannot be changed. 
(2) In AVS SDK, the range is 0-100 , and it can be set to 63 from APP (if APP send 63 to AVS).

**Comment by kclchan** [comment]
@zeusshuang, yes for both (1) and (2).  I am closing this issue now, please re-open it if you have more questions.  Thank!
