### ISSUE TITLE
errors while building avs device sdk

### ISSUE THREAD

**Issue by bharath4e9** [alexa/avs-device-sdk#601]
## Briefly summarize your issue:

->I have downloaded the avs device sdk into the source directory and run the cmake command from the build directory(as  shown in the https://github.com/alexa/avs-device-sdk/wiki/Linux-Reference-Guide)
->But iam getting errors related to ssl and nghttp2 library linking.

## What is the expected behavior?
->avs device sdk should be built and run
## What behavior are you observing?
errors while building the as device sdk.

### What version of the AVS Device SDK are you using?
      <x.y.z>
->Iam using avs device sdk 1.6 version.
### Tell us what hardware you're using:
- [ ] Desktop 

### Tell us about your OS (Type & version):
- [ ] Linux

here iam attaching the screeen shot of the errors that i got.
->can  anyone please help me out in solving the errors.

![screenshot from 2018-04-04 03-26-19 5](https://user-images.githubusercontent.com/38070199/38303181-e84fa04c-3822-11e8-9fea-5cf610b20642.png)
![screenshot from 2018-04-04 03-28-43 1](https://user-images.githubusercontent.com/38070199/38303182-e87b4198-3822-11e8-87d5-458cdb205a9b.png)
![screenshot from 2018-04-04 03-28-54 7](https://user-images.githubusercontent.com/38070199/38303183-e8a65e0a-3822-11e8-95a9-4197426151b4.png)
![screenshot from 2018-04-04 03-29-07 2](https://user-images.githubusercontent.com/38070199/38303184-e8d0c302-3822-11e8-9668-d4e1be842d9a.png)
![screenshot from 2018-04-04 03-29-15 1](https://user-images.githubusercontent.com/38070199/38303185-e8fd723a-3822-11e8-9679-6db69597c533.png)
![screenshot from 2018-04-04 03-29-23](https://user-images.githubusercontent.com/38070199/38303186-e92995cc-3822-11e8-82e6-26c41a658ab8.png)
![screenshot from 2018-04-04 03-29-30](https://user-images.githubusercontent.com/38070199/38303187-e95b9982-3822-11e8-90f9-d923d6d3669c.png)
![screenshot from 2018-04-04 03-29-38](https://user-images.githubusercontent.com/38070199/38303189-e98abece-3822-11e8-97c4-bc93aafc94dd.png)
![screenshot from 2018-04-04 03-29-46](https://user-images.githubusercontent.com/38070199/38303190-e9b37b52-3822-11e8-8338-42290a3f129b.png)
![screenshot from 2018-04-04 03-29-51](https://user-images.githubusercontent.com/38070199/38303191-e9e13d1c-3822-11e8-9a3b-d6ce024292aa.png)
![screenshot from 2018-04-04 03-30-01](https://user-images.githubusercontent.com/38070199/38303192-ea268688-3822-11e8-9994-40be374ce286.png)

**Comment by kclchan** [comment]
Hi @bharath4e9, from the error, it seems like the curl is not built with nghttp2 and openssl.  Could you try again by following this guide instead?
https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

**Comment by bharath4e9** [comment]
hi @kclchan  I have  built curl already with nghttp2 and openssl. and got the  http success message as shown in the above link.(https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide).But,
->whenever i tried to built the avs device sdk, it has shown errors as above (screen shots that i have attached).

**Comment by bharath4e9** [comment]
hi again  @kclchan,  i have built curl with version 7.54  but libcurl is still 7.47.
so, can you please say how to upgrade libcurl to  7.54 version.
->As you said,this might be the problem.
->so, can you please say how to upgrade libcurl to  7.54 version. and help me to solve the problem.

**Comment by kclchan** [comment]
Hi @bharath4e9, looks like there are two versions of libcurl in your system and the linker is picking the older version of the libcurl instead of v7.54.  I would like to confirm with you to see if you have done all these steps for curl as described in https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide:

cd ~/sdk-folder/third-party
wget http://curl.haxx.se/download/curl-7.54.0.tar.bz2
tar -xvjf curl-7.54.0.tar.bz2
cd curl-7.54.0
./configure --with-nghttp2=/usr/local --with-ssl
make
sudo make install
sudo ldconfig     

Especially the last step with "sudo ldconfig"?

Also can you do the command below to help us find out which libcurl and the order in which they are used:

ldconfig -v -N | grep 'libcurl\|:'

Once that's known, you can modify /etc/ld.so.conf.d and run "ldconfig" to change the order of the library path so that the new libcurl library will be used first.

**Comment by bharath4e9** [comment]
hi @kclchan, thanks for your reply, i will try to modify the /etc/ld.so.conf.d  file and will update you...thanks

**Comment by bharath4e9** [comment]
sdk has been successfully built now,  but when i run the make all integration test,i got the errors as shown in the screenshots
![integration_test_error1](https://user-images.githubusercontent.com/38070199/38553557-831ff98c-3c74-11e8-9eea-d5ae46fdd514.png)
![integration_test_error2](https://user-images.githubusercontent.com/38070199/38553561-836bc006-3c74-11e8-9b5e-490a2de25fe7.png)

**Comment by bharath4e9** [comment]
can you please help to fix those issues in step 5 and step 6

**Comment by BennyAvramson** [comment]
Hi @bharath4e9,

Could you take a look at https://github.com/alexa/avs-device-sdk/issues/196 and see if that solves your issue.

Thanks,
Benny

**Comment by dhpp** [comment]
Closing for now.  Please re-open if you need further assistance.
