### ISSUE TITLE
How to use Cloud-Based Wake Word Verification with avs-device-sdk?

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#603]
How to use Cloud-Based Wake Word Verification  with avs-device-sdk?
Is this already available in version 1.6? If not then what are the changes required to enable Cloud-Based Wake Word Verification?

OS - Linux Ubuntu
avs-device-sdk version - 1.6

Thanks,
Sumit

**Comment by kclchan** [comment]
Hi @sumit3817, the Cloud-Based Wake Word Verification is supported in the avs-device-sdk already.  Thanks!

**Comment by sumit3817** [comment]
Thanks for the information.
You can close the issue.

Thanks,
Sumit
