### ISSUE TITLE
Problem importing Flask

### ISSUE THREAD

**Issue by raibtoffoletto** [alexa/avs-device-sdk#606]
Hey Guys,

I'm trying to install the SDK in a Raspberry Pi 3+ following the instructions here.

However, I'm getting this message:
`Traceback (most recent call last):
  File "AuthServer/AuthServer.py", line 16, in <module>
    from flask import Flask, redirect, request
ImportError: No module named flask
`
I tried to create a virtualenv flask manually in the folder, in build and in the AuthServer folder,
however, the problem persists. Although I'm a hobbyist programmer, I'm unfamiliar with python 
so I can't quit track why this issue is happening trying to import the module.

Thanks

**Comment by khassel** [comment]
Hi,
looks like the flask installation failed. Had similar problems using the install-script.
Solved it running 
```
sudo apt-get -y install python-pip python
sudo pip install --upgrade setuptools
sudo pip install flask commentjson requests
```

**Comment by raibtoffoletto** [comment]
Thanks @khassel 

That worked, I could finish the compile!
Apparently what I was missing was just the setuptools
(although it should be present in a normal Raspbian install).
