### ISSUE TITLE
Alarm audio does not stop when speaking weather report

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#607]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
There are 2 test cases (4.6 and 4.7) in the AVS_functional_self-test_checklist_v1_7.xlsx. It requires when device is playing audio of timer or alarm, if user ask for weather, the device should stop playing audio of timer or alarm and turn to report the weather. But during my test, I found the timer audio is not stopped when playing weather report. That means the two audio are playing at the same time. Which make these 2 test cases fail.

I'm using "dmix plugin" as the audio playback.

## What is the expected behavior?
Timer audio should stop.

## What behavior are you observing?
Timer audio is not stopped when playing the weather report.

## Provide the steps to reproduce the issue, if applicable:
1. Ask alexa to setup  a timer for 5 seconds
2. After 5 seconds, the device start to play the timer audio
3. User speak "alexa, what is the weather".

### What version of the AVS Device SDK are you using?
      1.6

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [Y ] Other - tell us more: ARM7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [Y ] Other - tell us more: Alpine

**Comment by BennyAvramson** [comment]
Hi @subjectxbj,

Could you take a look at https://github.com/alexa/avs-device-sdk/issues/586 and see if that's solve this issue?

Thanks,
Benny

**Comment by subjectxbj** [comment]
OK, so looks like the alert sound and the alert short sound does not have too much volume difference. So I can't sense the volume down.
