### ISSUE TITLE
AVS SDK does not the state of Notifications Queued

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#612]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi, 

The AVS UX guidence require the device to support both "Notification Arrived" and "Notification Queued". But currently the SDK only support the Notification ON/OFF. How to map the state in the SDK to the states that are required by the UX requirement?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by BennyAvramson** [comment]
Hi @subjectxbj,

Currently in the SampleApp there's a visual indicator for having notifications in the queue.
We're looking into adding in the future a visual indicator for notification arrived.

Thanks,
Benny

**Comment by subjectxbj** [comment]
Ok, thanks. Looking forward to the new visual indicator.

**Comment by subjectxbj** [comment]
Reopen this issue since this indicator is still not implemented

**Comment by dhpp** [comment]
Hi @subjectxbj.  Sorry this ticket has not been updated in a while.  

To your question, can you please advise where you see this documented, especially with respect to certification?  My take on the AVS guidance is that showing a visual indicator is sufficient if a Notification has arrived for a user, since this is the API which AVS provides.

**Comment by kjkh** [comment]
Hi @subjectxbj,

This issue looks related to another one you have opened, https://github.com/alexa/avs-device-sdk/issues/897. That issue was resolved, so I will be closing this one. If you have any further questions, please feel free to re-open.
