### ISSUE TITLE
Code-Based Linking (CBL) for Other Devices and Platforms -Device Authorization Request fail!!!!

### ISSUE THREAD

**Issue by kuodehai** [alexa/avs-device-sdk#613]
curl -k -d 'response_type=device_code&client_id={{amzn1.application-oa2-client.37b63f01091146249651b5774523982b}}&scope=alexa%3Aall&scope_data=%7b%0d%0a++%22alexa%3aall%22%3a+%7b%0d%0a++++%22productID%22%3a+%22%7b%7bmy_Device%7d%7d%22%2c%0d%0a++++%22productInstanceAttributes%22%3a+%7b%0d%0a++++++++%22deviceSerialNumber%22%3a+%22%7b%7b%7d%7d%22%0d%0a++++%7d%0d%0a++%7d%0d%0a%7d' -H "Content-Type: application/x-www-form-urlencoded" -X POST https://api.amazon.com/auth/O2/create/codepair

{"error_description":"The request has an invalid parameter : client_id","error":"InvalidValue"}

**Comment by swapanj162** [comment]
Hi,
How did you remove this error?
