### ISSUE TITLE
Alexa APP will not change to offline after AVS device power off over 1 minute

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#616]
## Briefly summarize your issue:

AVS registered and connect with AWS correctly.
Then, power off the device directly, after 1 minute, the Alexa APP or Website still see it as online.
I wait over 5 minutes, but it still set online in APP. 

By Echo, it will become offline in 1 minute.

### What version of the AVS Device SDK are you using?
      1.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X ] Other - tell us more:  embedded Linux

### Tell us about your OS (Type & version):
- [X ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by BennyAvramson** [comment]
Hi @zeusshuang,

Does this only happens when you turn off the device or also when exiting the sampleApp?
Also, how much time it actually takes for the device to be offline on the Alexa app?

Thanks,
Benny

**Comment by zeusshuang** [comment]
Hi @BennyAvramson ,

Yes, it only happens while I turn off the device. From my test yesterday, it seems it did not become offline over 10 minutes, so I cannot know the  actually time that it will become offline automatically.

Thanks,

**Comment by zeusshuang** [comment]
Hi @BennyAvramson ,

thanks that and I will try it and check if I got the same result. So 10 minute
