### ISSUE TITLE
The Raspberry pi installation guide is confusing

### ISSUE THREAD

**Issue by sriranjanr** [alexa/avs-device-sdk#621]
In the raspberry pi installation guide it is mentioned to modify config.txt to add  Client ID, Client Secret, and Product ID. But the actual config.txt file has different entries which are device_serial_number, client_id and product_id. Now I know what the client_id is which I got when registering the device and its security but what are device_serial_number and product_id? When registering the device on amazon developer page we were hinted to save secuity_profile_id, client_id and client_secret. So what actually corresponds to the entried in config.txt. The naming of entries in the raspberry pi quick start page and the config.txt are not coherent/consistent and thus the confusion. Could someone tell me what shall I do here..?

**Comment by dhpp** [comment]
Hi @sriranjanr.  Thanks for asking about this.  

product_id is the second field under 'Product Information' if you click 'Manage' your device from the developer console.  It is a string you entered when you created the product.  

'device_serial_number' may be any string you wish, for example in the SDK sample .config file we suggest '123456'.

Let us know if you need any further assistance with this.

**Comment by dhpp** [comment]
I believe this issue is resolved.  Closing.  Please re-open if you'd like further input on this.
