### ISSUE TITLE
Raspberry Pi device installation with script fails at 95% mark

### ISSUE THREAD

**Issue by sriranjanr** [alexa/avs-device-sdk#622]
I am working with a raspberry pi zero w. I have followed the instructions given in raspberry pi avs sdk quick start guide. I tried compilation with the script sudo bash setup.sh config.txt . My compilation fails when it reaches 95% at sampleapplication.cpp.o

**Comment by dhpp** [comment]
Hi @sriranjanr, could you please post the compiler error output?  This will allow us to better understand the issue you're encountering.

**Comment by sriranjanr** [comment]
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:134: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o' failed
make[3]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o] Error 4
make[3]: *** Waiting for unfinished jobs....

**Comment by sriranjanr** [comment]
Is this a swap memory issue? Should I and how can I increase swap memory on raspberry pi zero?

**Comment by sriranjanr** [comment]
I increased the swap size to 1024 and it compiled fine. But now I am stuck at the next step. I am running raspberrypi zero w in headless mode through putty. In the quick start guide it is written to open the link http://localhost:3000/ in the browser.And I am guessing the browser in raspberrypi. Now in headless mode since there is no gui, how shall I execute this step?

**Comment by marath007** [comment]
v1.7 behave differently

**Comment by sriranjanr** [comment]
Ok I installed VNC to go to the amazon AVS login. But I am getting amazon 400 bad request. It says the redirect URLs are not whitelisted.
![allowed url](https://user-images.githubusercontent.com/8640547/38967570-3d7a05d4-43a5-11e8-83fe-5f508aa21f62.png)
But I have already mentioned the URLs in my web settings in the AVS portal.

**Comment by dhpp** [comment]
I believe this main question of this post is solved (install), and let's continue the runtime issue in the other post you opened, #625.  I'll close this thread out.  Thanks.

**Comment by DP0077bruh** [comment]
help me
same the alexa setup stops at 95%
im using raspberry pi 3

greetings from USA
