### ISSUE TITLE
No audio playback on Windows SDK

### ISSUE THREAD

**Issue by firoz91** [alexa/avs-device-sdk#624]
## Briefly summarize your issue:

I am setting up Windows SDK for the first time and I can not hear any audio coming out from the AVS SDK Sample App. I ran this command - **gst-launch-1.0 -m audiotestsrc ! autoaudiosink**  - to test if there is any beep coming out and it did. Please find the attached log. Thanks in advance for the help.

### What version of the AVS Device SDK are you using?
     1.6.0

### Tell us what hardware you're using:
Laptop

### Tell us about your OS (Type & version):
Windows

[Log.txt](https://github.com/alexa/avs-device-sdk/files/1926373/Log.txt)

**Comment by dhpp** [comment]
Hi @firoz91, 

thanks for providing the log, that helps us a lot.  We would advise you to update the SDK to the just released 1.7 version.  We addressed an issue with respect to the default audio sink initialization.  Your logs confirm this is the issue you are experiencing.

I'll close this ticket - please re-open if updating to 1.7 does not fix the issue, thanks.
