### ISSUE TITLE
Is it mandatory to enter the code for authorizing in SDK V1.7.0? it's very inconvenient for the first time to login.

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#631]
Hi,
I upgraded to SDK V1.7.0, and saw that the format of AlexaClientSDKConfig.json has been changed, so I followed the [guide](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide) to authorize, In my first time to initialize my AVS test flow, does I need to navigate a URL to enter a code? there have no display panel on my product, it's a smart speaker, so my question is:
 Is it mandatory to enter the code for authorize in SDK V1.7.0?
Can I skip the step? it's very inconvenient.

Please advise.

**Comment by dhpp** [comment]
Hi @boyce-xx,

Authorizing via CBL will only be required once, and then the auth token is persisted in the newly added database.  We have found that the previous method for auth provisioning was quite error prone for users, and that CBL is generally a lot simpler.

Yes, you will need to enter the code on a device with a screen.  When considering the use case of developing a smart speaker for a customer, then we would expect the CBL auth provisioning to occur on a companion app on their cellphone, for example.  The auth token could then be communicated to the speaker.

We are always open to feedback, so please do let us know if CBL presents persistent issues for you which we may not have considered.  Thanks.

**Comment by scotthea-amazon** [comment]
Hi Boyce-xx,
Just to be a little clearer, there are several ways to authorize a client to communicate with AVS (see [The API Overview Authorization section](https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#authorization).  CBLAuthDelegate is a concrete implementation of the [AuthDelegateInterface](https://github.com/alexa/avs-device-sdk/blob/master/AVSCommon/SDKInterfaces/include/AVSCommon/SDKInterfaces/AuthDelegateInterface.h).  The SDK is designed to allow you to implement the other authorization methods with your own implementation.

**Comment by boyce-xx** [comment]
Hi @dhpp , @scotthea-amazon:
Thank you.
If it's necessary to do, I can accept it.
I encountered a problem by using this new authorization: I want to know the current user's user profile likes userEmail and userName on my device, but I can't find a way to get it.
I was trying to get from the access token, searched in the SDK, I found this segmentation code in CBLAuthDelegate.cpp, the grant type is device_code:
```
avsCommon::utils::libcurlUtils::HTTPResponse CBLAuthDelegate::requestToken() {
    ACSDK_DEBUG5(LX("requestToken"));

    const std::vector<std::pair<std::string, std::string>> postData = {{POST_KEY_GRANT_TYPE, POST_VALUE_DEVICE_CODE},
                                                                       {POST_KEY_DEVICE_CODE, m_deviceCode},
                                                                       {POST_KEY_USER_CODE, m_userCode}};
    const std::vector<std::string> headerLines = {HEADER_LINE_URLENCODED};

    m_requestTime = std::chrono::steady_clock::now();

    return m_httpPost->doPost(
        m_configuration->getRequestTokenUrl(), headerLines, postData, m_configuration->getRequestTimeout());
}
```
 The response result will contains a access_token value, then I using the API:
`https://api.amazon.com/user/profile?access_token=<my_access_token>`
to get the user profile, but got the following error message:
`{"error_description":"The access token provided does not have required scope","error":"insufficient_scope"}`
I really need the user profile on my AVS device, do you have any good suggestion?
Thanks very much.

**Comment by boyce-xx** [comment]
Hi,
I have tried to add the code below in postData:
`{POST_KEY_SCOPE, "profile"},`
But got the same error:
`{"error_description":"The access token provided does not have required scope","error":"insufficient_scope"}`

**Comment by boyce-xx** [comment]
Hi,

Do you have any update for the question above?
Appreciate it!

**Comment by boyce-xx** [comment]
Hello, anybody here? 
Please help me!

**Comment by bandkenamazoncom** [comment]
Sorry that this has been delay.  It's a very specialized question.  I'm attempting to reproduce it to see is I can find out any information.

**Comment by boyce-xx** [comment]
Hi @bandkenamazoncom ,
Got it.
Thanks for your explanation.
