### ISSUE TITLE
Instructions not working!

### ISSUE THREAD

**Issue by marath007** [alexa/avs-device-sdk#633]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I installed a fresh install of raspberry stretch, fresh setup following the instruction.

And it does error 400... 

## What is the expected behavior?

it should work.. It used to work with the V1.0

## What behavior are you observing?

2018-04-20 00:02:31.111 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-04-20 00:02:31.111 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-04-20 00:02:31.111 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-04-20 00:02:31.112 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
2018-04-20 00:02:31.112 [  2] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
2018-04-20 00:02:31.112 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
2018-04-20 00:02:31.112 [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
2018-04-20 00:02:31.112 [  2] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST

### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### alexaclientsdkconfig.json

{
    "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/avs/db/alerts.db"
    },
    "certifiedSender":{
        "databaseFilePath":"/home/pi/avs/db/certifiedSender.db"
    },
    "settings":{
        "databaseFilePath":"/home/pi/avs/db/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
    },
    "notifications":{
        "databaseFilePath":"/home/pi/avs/db/notifications.db"
    },
    "cblAuthDelegate":{
        "databaseFilePath":"/home/pi/avs/db/cblAuthDelegate.db"
    },
    "deviceInfo":{
        "clientId":"the right text",
        "deviceSerialNumber":"456123",
        "productId":"the right thing"
    },
    "dcfDelegate":{
    },
    "miscDatabase":{
        "databaseFilePath":"/home/pi/avs/db/miscDatabase.db"
    },
    "gstreamerMediaPlayer":{
        "audioSink":"alsasink"
    }
}

### new install error message
2018-04-20 02:12:38.113 [  2] 5 HttpPost:doPostSucceeded:code=200
2018-04-20 02:12:38.116 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=200
2018-04-20 02:12:38.117 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=200,error=SUCCESS
2018-04-20 02:12:38.118 [  2] 5 CBLAuthDelegate:setAuthError:authError=SUCCESS
2018-04-20 02:12:38.118 [  2] 5 CBLAuthDelegate:setRefreshToken
2018-04-20 02:12:38.118 [  2] 5 SQLiteCBLAuthDelegateStorage:setRefreshToken
2018-04-20 02:12:38.324 [  2] 5 CBLAuthDelegate:handleRefreshingToken
2018-04-20 02:12:38.324 [  2] 5 CBLAuthDelegate:requestRefresh
2018-04-20 02:12:38.515 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-04-20 02:12:38.515 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-04-20 02:12:38.515 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-04-20 02:12:38.516 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
2018-04-20 02:12:38.516 [  2] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
2018-04-20 02:12:38.516 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
2018-04-20 02:12:38.516 [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
2018-04-20 02:12:38.516 [  2] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST
2018-04-20 02:12:38.516 [  2] 5 CBLAuthDelegate:handleStopping
2018-04-20 02:12:38.516 [  9] E DCFDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
2018-04-20 02:12:38.517 [  9] E DCFDelegate:publishCapabilitiesFailed:reason=getAuthTokenFailed
2018-04-20 02:12:38.517 [  9] 5 DCFDelegate:setDCFState:newDCFState=FATAL_ERROR
2018-04-20 02:12:38.517 [  9] 9 DCFDelegate:callingOnDCFStateChange:state=FATAL_ERROR,error=FORBIDDEN
2018-04-20 02:12:38.517 [  9] E DCFDelegate:dcfPublishFailed:reason=unableToPublishCapabilities

**Comment by dhpp** [comment]
Hi @marath007.  CBL requires that you send the ClientID generated by the CBL page, per the guide [here](https://developer.amazon.com/docs/alexa-voice-service/code-based-linking-other-platforms.html#step1).  Could you please double check this?

**Comment by marath007** [comment]
We're sorry!An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
--

**Comment by supermecho** [comment]
Hello @marath007 I had the same error message. I think I found my mistake : as described in the  the guide you should enter the Client ID generated by the Security Profile - Other Devices and Platforms dialog form. I used to input the ClientID from Dashboard - My products. I'll update you on the result asap. 
Not this from here : 
![image](https://user-images.githubusercontent.com/38582468/39082980-ca8fea9a-4564-11e8-885e-eda4b48bfc6c.png)
but from here 
![image](https://user-images.githubusercontent.com/38582468/39082994-1c026146-4565-11e8-82d9-83669d68704f.png)

**Comment by supermecho** [comment]
Yep, I confirm. After starting from 0 again, in phase Setup you have to edit the config.txt with the Client ID from here ( see pic below ) . Not it works fine !
@dhpp Thank you for your help ! This solved my issue ! gg 
![image](https://user-images.githubusercontent.com/38582468/39083240-60dda73a-456a-11e8-8856-269b4f7d1a44.png)

**Comment by marath007** [comment]
Trying at the moment... The instruction are fine 😀 !

**Comment by marath007** [comment]
So I am now at using kittai.
I did the custom CMAKE procedure used GCC4.9 and fixed an error in kitta.cpp 

I did make.. but how do i run the app now?



sudo cmake /home/pi/avs/avs-device-sdk -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/kittai/snowboy/lib/rpi/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/kittai/snowboy/include

**Comment by bandkenamazoncom** [comment]
$ SampleApp/src/SampleApplication <AlexaConfigFile.json>

**Comment by crashflow** [comment]
I had the wrong clientID. I fixed it (created one under "Other") as above. I deleted the auth db referenced in the json - cblAuthDelegate.db. I updated config.txt with correct clientID. I re-ran setup. I looked under "content and devices" after authorization on /us/code - but for some reason I still get 

2018-05-30 02:09:22.952 [  2] 5 CBLAuthDelegate:requestToken
2018-05-30 02:09:23.001 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-05-30 02:09:23.001 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-05-30 02:09:23.002 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-05-30 02:09:23.003 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=authorization_pending,errorCode=AUTHORIZATION_PENDING

Do I have to re-compile? I'm on a raspberry zero w and that will take a bunch of hours.

**Comment by crashflow** [comment]
I have the right version of libcurl. Correct version of ssl. Not sure what to check here. Still getting pending auth. Any clues I can give or things to check.

**Comment by marath007** [comment]
-when did you originally install it?
-what guide did you use?
seems like a config.json error
can you paste the config.json?

**Comment by crashflow** [comment]
config.txt

#NOTE: The Device Serial Number can be any unique number
DEVICE_SERIAL_NUMBER="11111"
CLIENT_ID="amzn1.application-oa2-client.bunchofnumbersandletters"
PRODUCT_ID="raspberrypilocal"


_______________

cat AlexaClientSDKConfig.json 
{
    "alertsCapabilityAgent":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/alerts.db"
    },
    "certifiedSender":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/certifiedSender.db"
    },
    "settings":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/settings.db",
        "defaultAVSClientSettings":{
            "locale":"en-US"
        }
    },
    "notifications":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/notifications.db"
    },
    "bluetooth" : {
        "databaseFilePath":"/home/pi/Documents/alexa/db/bluetooth.db"
    },
    "cblAuthDelegate":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/cblAuthDelegate.db"
    },
    "deviceInfo":{
        "clientId":"amzn1.application-oa2-client.bunchoflettersandnumbers",
        "deviceSerialNumber":"11111",
        "productId":"raspberrypilocal"
    },
    "capabilitiesDelegate":{
    },
    "miscDatabase":{
        "databaseFilePath":"/home/pi/Documents/alexa/db/miscDatabase.db"
    },
    "gstreamerMediaPlayer":{
        "audioSink":"alsasink"
    }
}

**Comment by crashflow** [comment]
Used this guide:

https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

**Comment by marath007** [comment]
I solved my issue of your kind by creating a new security profile.

**Comment by supermecho** [comment]
@ crashflow I made similar mistake but in my case I didn't manage to fix just by reconfiguring and restarting the setup. I had to recompile but on raspberrypi3 it's not an issue. On the zero I would first generate new security profile and double check everything before running the setup and authorization phase. Good luck!

**Comment by crashflow** [comment]
The weird thing is that the device gets created and associated with my Amazon account under "Manage Your Content and Devices". 

Does anyone know the syntax of authorization POST? Maybe I could make it with curl to see if it is failing.

By the way, I created a new product and a new security, deleted contents of DB directory, updated config.txtt, re-ran setup, checked the json (it was correct), authorized using /us/code, device was created as I noted above. And still can't get auth. 

I can't imagine that I would need to re-compile.

**Comment by marath007** [comment]
I never deleted .DB filesSent from my Huawei Mobile-------- Original Message --------Subject: Re: [alexa/avs-device-sdk] Instructions not working! (#633)From: crashflow To: alexa/avs-device-sdk CC: marath007 ,State change The weird thing is that the device gets created and associated with my Amazon account under "Manage Your Content and Devices".
Does anyone know the syntax of authorization POST? Maybe I could make it with curl to see if it is failing.
By the way, I created a new product and a new security, deleted contents of DB directory, updated config.txtt, re-ran setup, checked the json (it was correct), authorized using /us/code, device was created as I noted above. And still can't get auth.
I can't imagine that I would need to re-compile.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/alexa/avs-device-sdk/issues/633#issuecomment-393204739","url":"https://github.com/alexa/avs-device-sdk/issues/633#issuecomment-393204739","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexa/avs-device-sdk","title":"alexa/avs-device-sdk","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alexa/avs-device-sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@crashflow in #633: The weird thing is that the device gets created and associated with my Amazon account under \"Manage Your Content and Devices\". \r\n\r\nDoes anyone know the syntax of authorization POST? Maybe I could make it with curl to see if it is failing.\r\n\r\nBy the way, I created a new product and a new security, deleted contents of DB directory, updated config.txtt, re-ran setup, checked the json (it was correct), authorized using /us/code, device was created as I noted above. And still can't get auth. \r\n\r\nI can't imagine that I would need to re-compile.\r\n\r\n\r\n\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/alexa/avs-device-sdk/issues/633#issuecomment-393204739"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [alexa/avs-device-sdk] Instructions not working! (#633)",
"sections": [
{
"text": "",
"activityTitle": "**crashflow**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@crashflow",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"alexa/avs-device-sdk\",\n\"issueId\": 633,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"alexa/avs-device-sdk\",\n\"issueId\": 633\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/alexa/avs-device-sdk/issues/633#issuecomment-393204739"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 326289094\n}"
}
],
"themeColor": "26292E"
}
