### ISSUE TITLE
sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a: No such file or directory

### ISSUE THREAD

**Issue by cr1108x** [alexa/avs-device-sdk#635]
Hi!,please help me!!
I run this commond to build the SDK："cd /{HOME}/sdk-folder/sdk-build && cmake /{HOME}/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/{HOME}/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/{HOME}/sdk-folder/third-party/portaudio/include && make"

But is a error  has occurred, it said:"libportaudio.a:No such file or directory", but my libportaudio.a is exists!
the log as follow:
//================
[ 96%] Linking CXX executable SampleApp
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
c++: error: ~/alexa/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a: No such file or directory
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:359: recipe for target 'SampleApp/src/SampleApp' failed
make[2]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:8010: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
foryou@foryou-virtual-machine:~/alexa/sdk-folder/sdk-build$ 

//=================

### What version of the AVS Device SDK are you using?
      newest SDK

### Tell us what hardware you're using:
- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Linux-Ubuntu

**Comment by cr1108x** [comment]
Hi every please help me!

think you!!!

**Comment by ryan-esty** [comment]
@cr1108x,

you forgot a $. {HOME} should be ${HOME} that is why there is no home directory on your portaudio directory lines.

Ryan

**Comment by dhpp** [comment]
Thanks @ryan-esty.  @cr1108x - I'll close this for now - please re-open if you have further issues running those commands.

**Comment by cr1108x** [comment]
Thank you very much!!!
