### ISSUE TITLE
Issue of Audible playback behavior

### ISSUE THREAD

**Issue by fallouter007** [alexa/avs-device-sdk#636]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When playing Audible, ask to stop and then resume. It doesn't play from last finished position.

From log, it seems that the offset of resume command is rewind to 15 seconds before last finished position.
Is this an expected behavior of  AVS server (Audible service)? Or is there anything wrong?

2018-04-17 03:38:31.773 -> When starting to play Audible, the offset is 1562000.
2018-04-17 03:38:43.719 -> Seven seconds later, I stop Audible and offset updated to server is 1569000. And this value should be synced with server.
2018-04-17 03:38:47.848 -> After doing resume, the offset from server is 1554000.
Part of log is listed below.
```
2018-04-17 03:38:31.773 [  f] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.AudibleClientId#
ACRI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,73fd42df-cb7b-4033-a45a-36c86d87bcff#11"\,"stream"\:{"offsetInMilli
seconds"\:1562000\,"expiryTime"\:"2018-04-17T03\:38\:27+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:
30000\,"progressReportIntervalInMilliseconds"\:30000}\,"url"\:"https\://audiblecdn-vh.akamaihd.net/i/295892/audibleword
s/content/bk/reco/004772/V$000002$V/aax/bk_reco_004772_22_32.mp4/master.m3u8?start\=13202&end\=14944&hdnea\=st\=1523936
307~exp\=1523936367~acl\=/i/295892/audiblewords/content/bk/reco/004772/V$000002$V/aax/bk_reco_004772_22_32.mp4/*~data\=
13202\,14944~hmac\=db3fe728c866a5aa39d31b00b4b299860f282742bb5d7dcd7f097d35d9c130ca"\,"token"\:"amzn1.as-ct.v1.AudibleC
lientId#ACRI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,73fd42df-cb7b-4033-a45a-36c86d87bcff#11"}}\,"playBehavior"\
:"REPLACE_ALL"}
...
...
2018-04-17 03:38:45.509 [  9] 0 AudioInputProcessor:executeOnContextAvailable:jsonContext={"context"\:[{"header"\:{"nam
espace"\:"Speaker"\,"name"\:"VolumeState"}\,"payload"\:{"volume"\:33\,"muted"\:false}}\,{"header"\:{"namespace"\:"Notif
ications"\,"name"\:"IndicatorState"}\,"payload"\:{"isEnabled"\:false\,"isVisualIndicatorPersisted"\:false}}\,{"header"\
:{"namespace"\:"SpeechSynthesizer"\,"name"\:"SpeechState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.AudibleClientId#ACRI#D
eviceTTSRendererV4_c4fb406c-3fe9-43ac-8863-61df10bdbb20"\,"offsetInMilliseconds"\:0\,"playerActivity"\:"FINISHED"}}\,{"
header"\:{"namespace"\:"AudioPlayer"\,"name"\:"PlaybackState"}\,"payload"\:{"token"\:"amzn1.as-ct.v1.AudibleClientId#AC
RI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,73fd42df-cb7b-4033-a45a-36c86d87bcff#11"\,"offsetInMilliseconds"\:156
9000\,"playerActivity"\:"STOPPED"}}\,{"header"\:{"namespace"\:"SpeechRecognizer"\,"name"\:"RecognizerState"}\,"payload"
\:{"wakeword"\:"alexa"}}\,{"header"\:{"namespace"\:"Alerts"\,"name"\:"AlertsState"}\,"payload"\:{"allAlerts"\:[]\,"acti
veAlerts"\:[]}}]}
...
...
2018-04-17 03:38:47.848 [  f] 9 AudioPlayer:PLAY:payload={"audioItem"\:{"audioItemId"\:"amzn1.as-ct.v1.AudibleClientId#
ACRI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,95d72df6-8eff-4be2-8469-14ae5ebda102#11"\,"stream"\:{"offsetInMilli
seconds"\:1554000\,"expiryTime"\:"2018-04-17T03\:38\:47+0000"\,"progressReport"\:{"progressReportDelayInMilliseconds"\:
30000\,"progressReportIntervalInMilliseconds"\:30000}\,"url"\:"https\://audiblecdn-vh.akamaihd.net/i/295892/audibleword
s/content/bk/reco/004772/V$000002$V/aax/bk_reco_004772_22_32.mp4/master.m3u8?start\=13202&end\=14944&hdnea\=st\=1523936
327~exp\=1523936387~acl\=/i/295892/audiblewords/content/bk/reco/004772/V$000002$V/aax/bk_reco_004772_22_32.mp4/*~data\=
13202\,14944~hmac\=d0f3704bdc68c9d9ee45268ad170d579c9fe2ba9f9b32811ae47e525b47dfd66"\,"token"\:"amzn1.as-ct.v1.AudibleC
lientId#ACRI#url#ACRI#playq\:audiobook/audible;mv\=Audible\,95d72df6-8eff-4be2-8469-14ae5ebda102#11"}}\,"playBehavior"\
:"REPLACE_ALL"}
```

Full log can be found here. 
[audible_pause_resume_offset.txt](https://github.com/alexa/avs-device-sdk/files/1931584/audible_pause_resume_offset.txt)

## What is the expected behavior?

Audible starts playing from last finished position.

## What behavior are you observing?

Audible starts playing from 15 seconds before last finished position.

## Provide the steps to reproduce the issue, if applicable:

1. Ask to play Audible ("Alexa, play Audible")
2. Stop playing ("Alexa, stop")
3. Resume playing ("Alexa, resume Audible")
4. Check playing position

### What version of the AVS Device SDK are you using?
      <1.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
       ARM A7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
       Linux OpenWRT

**Comment by dhpp** [comment]
Hi @fallouter007.  This is a known issue, and has to do with interaction between AVS and Audible in the cloud.  Essentially, the offsets we receive and send are correctly handled by the Client SDK, but as you have found, they are not entirely correct.  I would presume that this is not a problem for the general user (in terms of client behavior of Audible content), which is why it is not more accurate.

If you think it's important, then I would suggest raising the issue with our [feature request forum](https://forums.developer.amazon.com/spaces/185/alexa-feature-requests.html), which is the general AVS intake forum, as opposed to this one which is focused on the Client SDK.

Thanks.  Will close this ticket out.

**Comment by fallouter007** [comment]
Hi @dhpp, thank you for the detailed explanation. Since it's a cloud-side issue, we'll leave it and see if there's any improvement in the future.
