### ISSUE TITLE
feature request for documentation on the sdk

### ISSUE THREAD

**Issue by ryan-esty** [alexa/avs-device-sdk#639]
list,

Can we get a list of things that the echo can do out of the box and the sdk can't. For example I know in the past your device needs to be white listed with Amazon to be able to do prime music, I think this is still true. What about Alexa for business? I know some of the older echo hardware can't even do Alexa for business. Are there other services that the echo can do that the sdk might not be able to do? Maybe this list is only a couple of items long but I'd still like to know.

Ryan

**Comment by bandkenamazoncom** [comment]
Thanks Ryan,

Is there a specific feature you have a question about?  This list is not publicly available at this time.  

@anu-mather - do we have any information about Alexa for Business?

**Comment by ryan-esty** [comment]
@bandkenamazoncom ,

Thanks for getting back to me. Our business model is only businesses not consumer markets. We watched the Alexa for business stuff and saw with some polycoms you could start a meeting for example. Things where you can enable voice activated work flows would be useful in our market. We are brute forcing some of this with Lex but it isn't ideal.

Ryan

**Comment by kencecka** [comment]
Hi @ryan-esty,

Sorry for the slow response.  If you still have questions about this, could you fill out this [contact form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) so we can discuss this further with you directly?

Thanks,
Ken

**Comment by ryan-esty** [comment]
Hi @kencecka ,

I believe you have my details on file.

Ryan
