### ISSUE TITLE
Display Cards on Raspberry Pi

### ISSUE THREAD

**Issue by Piflyer** [alexa/avs-device-sdk#642]
Hi,
I got a response from @dhpp from my earlier issue on display cards for my Raspberry Pi. How am I suppose to create the display cards? Is it in JSON or C++? Where am I suppose to put it? They told me to explore avs-device-sdk/CapabilityAgents/TemplateRuntime/ folder. What am I suppose to do?

**Comment by bandkenamazoncom** [comment]
Are you trying to render a display card or create one?  

The display cards are created as part of the AVS API and if you were creating one, it would be on an Alexa skill, not in the device.  That would be where the JSON creation occurs.

The SDK can render the Display cards, and that is C++ code in the TemplateRuntime area.  This code is used to render a text-based display.

**Comment by bandkenamazoncom** [comment]
I'm not quite sure of the question.  Can you provide a more concrete example? 

The display cards are created as part of a skill, and are sent to the client (as JSON) through a TempluateRuntime directive.  The client can choose what to do with the JSON data.

**Comment by Piflyer** [comment]
I mean where do you create the skill? And do I have to create a card for all responses?

**Comment by bandkenamazoncom** [comment]
That's part of the Skills SDK, which is different from the Client SDK.  It runs in the AVS cloud:

https://developer.amazon.com/alexa-skills-kit

**Comment by Piflyer** [comment]
Do I have to create one for all response that Alexa can say?

**Comment by bandkenamazoncom** [comment]
I'm not very familiar with Alexa Skills development.   You should look for information on their forums: https://forums.developer.amazon.com/spaces/23/index.html

**Comment by Piflyer** [comment]
After searching quite sometime, is there just a shortcut to just add Alexa's response to a JSON file? I know that after each request, there is a url for an image. Can we add the sample app output or not? Or can we just make an app that reads and creates a card? The alexa/avs-sample-app has an output of the card, and does this one have that? Thanks.

**Comment by bandkenamazoncom** [comment]
I still don't understand.  Can you provide a concrete example?

**Comment by bandkenamazoncom** [comment]
You need to go to the Skills forums (https://forums.developer.amazon.com/spaces/23/index.html).  The functionality you want is done in the Skill.  You will get better answers there!

Thanks!

**Comment by Piflyer** [comment]
How do I render a display then? Is the code similar to the one shown [here]?(https://developer.amazon.com/docs/alexa-voice-service/display-cards-overview.html)

**Comment by kencecka** [comment]
Hi @Piflyer,

Sorry for the slow response on this.  I see that there has been some confusion about how display cards work, so I will try to clarify.

When a user asks Alexa to do something, this gets interpreted as an intent (what did the user intend), which gets routed to an appropriate handler in the service.  This might be a handler for some core piece of Alexa functionality ("tell me a joke", "what's the weather", etc), or it might be a custom skill that someone wrote ("ask starbucks to order me some coffee").

In either case, the handler can respond in two ways: it can produce some text for Alexa to speak back to the user, and it can produce some visual content to display on the device's screen.  The text Alexa speaks is sent to the device in the form of a [SpeechSynthesizer.Speak](https://developer.amazon.com/docs/alexa-voice-service/speechsynthesizer.html#speak) directive, and the visual content is sent in the form of a [TemplateRuntime.RenderTemplate](https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html#rendertemplate) directive.

In the SDK, directives are received and routed to Capability Agents.  The SDK includes a SpeechSynthesizer capability agent which handles the speech, and a TemplateRuntime capability agent which handles the visual content.

The TemplateRuntime capability agent in the SDK is very minimal.  It provides the basic interface needed to receive the directive and extracts the JSON description of the visual content, and then simply passes that on to a user-provided handler which is responsible for actually interpreting the description and rendering it to the screen.  In SampleApp, the handler does not attempt to do any graphics rendering, but instead prints some text to the console.

If you are interested in rendering an image to a screen on your device, you would register a new handler to receive the JSON description, and then use your own code to interpret that JSON and render it.  The page you linked above gives guidelines on what the rendered images should look like.

Hopefully that helps clear things up.  Let us know if you have further questions.

Ken

**Comment by Piflyer** [comment]
How do I create the JSON render card, and execute it so it can be an Echo Show. Also how do I make it so it can copy the template id and execute it? Thanks.

**Comment by scotthea-amazon** [comment]
Hi @Piflyer,

It sounds like you are asking how you can send a card to an Echo Show - as opposed to how to render a card on a Raspberry Pi.  As @kencecka mentioned above, the creation of cards is handed by an **intent** that is either handled by directly by Amazon's Alexa functionality, or by a custom skill.  If you want to create your own card, you will need to do so by creating a custom skill with the [alexa-skills-kit](https://developer.amazon.com/alexa-skills-kit), as @bendkenamazon mentioned above.

If I have misinterpreted you, and you are trying to implement behavior on your on device,  you might find the following links helpful:
* [Display Cards Overview](https://developer.amazon.com/docs/alexa-voice-service/display-cards-overview.html)
* [TemplateRuntime Interface](https://developer.amazon.com/docs/alexa-voice-service/templateruntime.html)

I hope this helps,
-SWH

**Comment by Piflyer** [comment]
I meant that I want it run on a Raspberry Pi, but act like an echo show

**Comment by Piflyer** [comment]
Where is the capabilities API in the alexa-avs-sdk so I can follow the program?

**Comment by Piflyer** [comment]
I changed and added more to the file, so should it run after launching the app again, or does it need a specific command?

**Comment by dhpp** [comment]
Hi @Piflyer, sorry this ticket has not been updated in a while.  Do you still require assistance?

**Comment by dhpp** [comment]
Thanks @Piflyer - could you please elaborate further where you see the error, and post that error output in this thread?  That will give us better information about the exact problem you are having, and we can then help with next steps.

**Comment by dhpp** [comment]
Closing for now.  Please re-open or create a new ticket if we can help further.
