### ISSUE TITLE
SDK 1.7.0/Ubuntu/Kitt-AI: SampleApp crashes while starting

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#644]
## Briefly summarize your issue:
With SDK 1.6.0 the setup described below is working. Now with SDK 1.7.0 the same setup is crashing while starting. I have attached 2 files created with DEBUG9-Option with the working 1.6.0 and the crashing 1.7.0.
Another Setup with SDK 1.7.0/Raspberry Pi/Kitt-AI is working.

## What is the expected behavior?
SampleApp should start

## What behavior are you observing?
SampleApp crashes with *** Error in `./SampleApp': munmap_chunk(): invalid pointer: 0x00007ffdca7dc030 ***

## Provide the steps to reproduce the issue, if applicable:
```
cd ./SampleApp/src \
  && ./SampleApp \
  /srv/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json \
  /srv/sdk-folder/third-party/snowboy/resources/
```

## Tell us about your environment:
The build-script (Dockerfile) of the used environment: https://github.com/khassel/alexa_sdk_docker/blob/ubuntu64/build/Dockerfile
### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [X] Desktop / Laptop

### Tell us about your OS (Type & version):
- [X] Ubuntu Linux 16.04 LTS

### Attachments:
[avs_ubuntu_160.log](https://github.com/alexa/avs-device-sdk/files/1936130/avs_ubuntu_160.log)
[avs_ubuntu_170.log](https://github.com/alexa/avs-device-sdk/files/1936132/avs_ubuntu_170.log)

**Comment by bandkenamazoncom** [comment]
Thanks @khassel 

We're looking at it internally.  I don't see anything obvious from the logs.  Does it work OK without the wakeword engine?

**Comment by zeusshuang** [comment]
Hi , @bandkenamazoncom 

is it a known issue on SDK 1.7?  We got the same case with Sensory.  It will crassh at "onKeyWordDetected" without any output log. The AVS is working if I triggered by command directly.

**Comment by bandkenamazoncom** [comment]
We will figure that out shortly.  

@zeusshuang Can you post your stack trace or crash dump when it crashes?

**Comment by bandkenamazoncom** [comment]
There is a known issue with KITT.ai.  I'm interested to see if it is also in the Sensory build.

**Comment by khassel** [comment]
Only for clarifying: It is not a general problem with KITT.ai because the setup SDK 1.7.0/Raspberry Pi/Kitt-AI is working. Same setup on ubuntu crashes. Afaik Sensory is only running on raspberry, not on ubuntu.
May @zeusshuang can answer your Sensory question, I have no Sensory setup at the moment.

**Comment by zeusshuang** [comment]
Hi @bandkenamazoncom @khassel  ,

The SampleAPP crash silently while it enter "onKeyWordDetected" (so the Sensory can detect the keyword). I will check if I can provide more information for this case.

**Comment by khassel** [comment]
I now testet the setup SDK 1.7.0/Raspberry Pi/Sensory and it works.

So 
- SDK 1.7.0/Raspberry Pi/Sensory: O.K.
- SDK 1.7.0/Raspberry Pi/Kitt-AI: O.K.
- SDK 1.7.0/Ubuntu/Kitt-AI: crashing while starting

@bandkenamazoncom: Will there be a fix for the Ubuntu/Kitt-AI problem?

**Comment by khassel** [comment]
Testet with new SDK 1.7.1, no changes:

-  SDK 1.7.1/Raspberry Pi/Sensory: O.K.
-  SDK 1.7.1/Raspberry Pi/Kitt-AI: O.K.
-  SDK 1.7.1/Ubuntu/Kitt-AI: crashing while starting

**Comment by kencecka** [comment]
Thanks for the update and continued testing @khassel.  We have this in our backlog of issues to work on.

Ken

**Comment by jundeshen** [comment]
./SampleApp ~/AVS/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json ~/AVS/sdk-folder/third-party/snowboy/resources/  --> crash

cp third-party/snowboy/resources/alexa/alexa-avs-sample-app/alexa.umdl  third-party/snowboy/resources/
./SampleApp ~/AVS/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json ~/AVS/sdk-folder/third-party/snowboy/resources/  -->  OK

**Comment by khassel** [comment]
Thanks for contributing @jundeshen. May you can tell us which SDK-Version and hardware/os (pi or ubuntu) you are using?

 [My setup](https://github.com/khassel/alexa_sdk_docker/blob/a1add96ff3561be7cd944b434bb71fc13967226f/build/Dockerfile#L19)  with SDK 1.7.1/Ubuntu/Kitt-AI is still crashing although it contains the cp command.

**Comment by jundeshen** [comment]
SDK Version 1.7.1
notebook ubuntu META 18.04

**Comment by jundeshen** [comment]
I git clone https://github.com/Kitt-AI/snowboy  and checkout to tag v1.3.0

**Comment by khassel** [comment]
Thanks @jundeshen. 
Upgraded my docker image from ubuntu:16.04 to ubuntu:18.04, Application still crashes while starting.
I'm using Kitt-AI master branch, but testet now also with v1.3.0, no difference.

No idea at the moment ...

**Comment by khassel** [comment]
Testet with new SDK 1.8.0, no changes:

    SDK 1.8.0/Raspberry Pi/Sensory: O.K.
    SDK 1.8.0/Raspberry Pi/Kitt-AI: O.K.
    SDK 1.8.0/Ubuntu/Kitt-AI: crashing while starting

**Comment by khassel** [comment]
The problem on ubuntu (16.04 or 18.04) is Kitt-AI: 
Version 1.2.0 (which is mentioned in the setup) is working, all versions above are not.

On rasperry pi all versions are working.

Final question at the amazon stuff: Is this a problem on your or on the Kitt-AI side?

**Comment by LoganArnett** [comment]
Have there been any updates on this? I am currently getting the invalid pointer error as well

**Comment by LoganArnett** [comment]
I am getting this:
```
2018-10-10 19:45:31.620 [  1] I sdkVersion: 1.9.0
configFile Integration/AlexaClientSDKConfig.json
#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
*** Error in `./SampleApp/src/SampleApp': munmap_chunk(): invalid pointer: 0x00007fffe172f6e0 ***
```

**Comment by visayamv** [comment]
Hi @LoganArnett , there is a known issue with gcc 4.8.5 and Kitt.AI which we have raised to Kitt.AI here:

https://github.com/Kitt-AI/snowboy/issues/459

As a workaround, you can upgrade your GCC to 5.4.0 and edit build/cmake/BuildOptions.cmake file.

Add a CFLAG option "D_GLIBCXX_USE_CXX11_ABI=0 -pg" to the CMAKE variables:
CXX_PLATFORM_DEPENDENT_FLAGS_DEBUG, CXX_PLATFORM_DEPENDENT_FLAGS_RELEASE and CXX_PLATFORM_DEPENDENT_FLAGS_MINSIZEREL

**Comment by scotthea-amazon** [comment]
Hello khassel,

From the correspondence it sounds like this issue is resolved, so I am closing it.  If it is closed in error, feel free to re-open it and please indicate what is not working.

Thank you,
-SWH
