### ISSUE TITLE
Facing issues in AIP while building avs-device-sdk v1.7 

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#650]
Hi,
I am facing issues while building avs-device-sdk version 1.7.

Here are the console logs:-

Scanning dependencies of target KeywordDetectorProvider
[ 72%] Building CXX object KWD/KWDProvider/src/CMakeFiles/KeywordDetectorProvider.dir/KeywordDetectorProvider.cpp.o
Linking CXX shared library libKeywordDetectorProvider.so
[ 72%] Built target KeywordDetectorProvider
Scanning dependencies of target AIP
[ 73%] Building CXX object CapabilityAgents/AIP/src/CMakeFiles/AIP.dir/AudioInputProcessor.cpp.o
/home/harman/1.7_Alexa/sdk-source/avs-device-sdk/CapabilityAgents/AIP/src/AudioInputProcessor.cpp: In member function ‘void alexaClientSDK::capabilityAgents::aip::AudioInputProcessor::executeOnContextAvailable(std::string)’:
/home/harman/1.7_Alexa/sdk-source/avs-device-sdk/CapabilityAgents/AIP/src/AudioInputProcessor.cpp:637:29: error: ‘class alexaClientSDK::avsCommon::avs::MessageRequest’ has no member named ‘addAttachmentReader’
         m_recognizeRequest->addAttachmentReader(KWD_METADATA_FIELD_NAME, m_KWDMetadataReader);
                             ^
/home/harman/1.7_Alexa/sdk-source/avs-device-sdk/CapabilityAgents/AIP/src/AudioInputProcessor.cpp:639:25: error: ‘class alexaClientSDK::avsCommon::avs::MessageRequest’ has no member named ‘addAttachmentReader’
     m_recognizeRequest->addAttachmentReader(AUDIO_ATTACHMENT_FIELD_NAME, m_reader);
                         ^
make[2]: *** [CapabilityAgents/AIP/src/CMakeFiles/AIP.dir/AudioInputProcessor.cpp.o] Error 1
make[1]: *** [CapabilityAgents/AIP/src/CMakeFiles/AIP.dir/all] Error 2
make: *** [all] Error 2

Platform - ubuntu 32 bit
Version - 1.7

AIP is not able to compile. It tells alexaClientSDK::avsCommon::avs::MessageRequest’ has no member named ‘addAttachmentReader’.

Thanks, 
Sumit

**Comment by bandkenamazoncom** [comment]
What version of gcc are you using?  We only support 4.8.5 and above: https://github.com/alexa/avs-device-sdk/wiki/Dependencies

**Comment by sumit3817** [comment]
I am cross compiling it for artik.  
C Compiler - arm-linux-gnueabihf-gcc
C++ Compiler -  arm-linux-gnueabihf-g++

**Comment by sumit3817** [comment]
When I compile without Wake Word, again the build fails with similiar type of issue.
The logs are:-

Linking CXX executable CustomerDataManagerTest
[ 95%] Built target CustomerDataManagerTest
Scanning dependencies of target RegistrationManagerTest
[ 96%] Building CXX object RegistrationManager/test/CMakeFiles/RegistrationManagerTest.dir/RegistrationManagerTest.cpp.o
Linking CXX executable RegistrationManagerTest
[ 96%] Built target RegistrationManagerTest
Scanning dependencies of target SampleApp
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/ConnectionObserver.cpp.o
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/ConsolePrinter.cpp.o
[ 97%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/GuiRenderer.cpp.o
[ 98%] Building CXX object SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o
In file included from /home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:28:0,
                 from /home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:17:
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/KeywordObserver.h:49:10: error: ‘void alexaClientSDK::sampleApp::KeywordObserver::onKeyWordDetected(std::shared_ptr<alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits> >, std::__cxx11::string, alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Index, alexaClientSDK::avsCommon::utils::sds::SharedDataStream<alexaClientSDK::avsCommon::utils::sds::InProcessSDSTraits>::Index, std::shared_ptr<const std::vector<char> >)’ marked ‘override’, but does not override
     void onKeyWordDetected(
          ^
In file included from /home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:17:0:
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:55:25: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
         std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> callManager = nullptr);
                         ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:55:25: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:55:71: error: template argument 1 is invalid
         std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> callManager = nullptr);
                                                                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:236:21: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
     std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> m_callManager;
                     ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:236:21: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:236:67: error: template argument 1 is invalid
     std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> m_callManager;
                                                                   ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/include/SampleApp/InteractionManager.h:55:87: error: could not convert ‘nullptr’ from ‘std::nullptr_t’ to ‘int’
         std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> callManager = nullptr);
                                                                                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:32:21: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
     std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> callManager) :
                     ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:32:21: error: ‘CallManagerInterface’ is not a member of ‘alexaClientSDK::avsCommon::sdkInterfaces’
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:32:67: error: template argument 1 is invalid
     std::shared_ptr<avsCommon::sdkInterfaces::CallManagerInterface> callManager) :
                                                                   ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp: In lambda function:
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:253:23: error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘isCommsEnabled’
         if (m_client->isCommsEnabled()) {
                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp: In lambda function:
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:263:23: error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘isCommsEnabled’
         if (m_client->isCommsEnabled()) {
                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:264:23: error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘acceptCommsCall’
             m_client->acceptCommsCall();
                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp: In lambda function:
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:273:23: error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘isCommsEnabled’
         if (m_client->isCommsEnabled()) {
                       ^
/home/harman/WithoutWWE/sdk-source/avs-device-sdk/SampleApp/src/InteractionManager.cpp:274:23: error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘stopCommsCall’
             m_client->stopCommsCall();
                       ^
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/InteractionManager.cpp.o] Error 1
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
make: *** [all] Error 2

**Comment by bandkenamazoncom** [comment]
Can you provide the commands used to do the cmake and the build?

Thanks!

**Comment by sumit3817** [comment]
Hi,

Before cmake, export pkg config path where all .pc are present.
export PKG_CONFIG_PATH=/usr/arm-linux-gnueabihf/lib/pkgconfig:$PKG_CONFIG_PATH

The cmake command used while cross compiling:- 

cmake -DCMAKE_TOOLCHAIN_FILE=/home/harman/toolchain.cmake /home/harman/1.7_Alexa/sdk-source/avs-device-sdk  -DCMAKE_INSTALL_PREFIX=/home/harman/build_alexa -DCMAKE_PREFIX_PATH=/home/harman/build_alexa -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/harman/build_alexa/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/harman/build_alexa/include


toolchain.cmake file contents:-

INCLUDE(CMakeForceCompiler)
# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)
# specify the cross compiler
SET(CMAKE_C_COMPILER   arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
# where is the target environment
SET(CMAKE_FIND_ROOT_PATH  /usr/arm-linux-gnueabihf/)
# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

This is working till avs-device-sdk v1.6. 

Thanks,
Sumit

**Comment by sumit3817** [comment]
Hi,

The code base is latest as per 1.7 release and DefaultClient.h and .cpp files are latest as per 1.7 release.
All api's are present in DefaultClient but it is showing the following error:-
    error: ‘class alexaClientSDK::defaultClient::DefaultClient’ has no member named ‘isCommsEnabled’

If I am compiling with Sensory Mode = ON, then the same issue is with AIP:-
    error: ‘class alexaClientSDK::avsCommon::avs::MessageRequest’ has no member named ‘addAttachmentReader’

When I look into the code, the API 'addAttachmentReader' is already present in the file.

I have already attached the logs for both of the issues.

Is there other issue with namespace in 1.7 release?

Thanks,
Sumit

**Comment by sumit3817** [comment]
Hi,

This issue is fixed. There is a problem with include paths.
You can close this issue.

Thanks,
Sumit
