### ISSUE TITLE
How do I apply avs device sdk to android platform ?

### ISSUE THREAD

**Issue by mmabluesky** [alexa/avs-device-sdk#653]
Such as ，Who can give me some advice ？ Thanks ！

**Comment by bandkenamazoncom** [comment]
This is the right place to ask questions.  That answered your question, can I close this :)?

Do you have a specific question?

**Comment by mmabluesky** [comment]
Through a script, I compiled a dynamic library that can be used on android, but I do not have a reference example to call those APIs.

**Comment by bandkenamazoncom** [comment]
Can you give us some more information on what you did?
