### ISSUE TITLE
How to build&run avs-device-sdk Sample app on ARM32 platform

### ISSUE THREAD

**Issue by cr1108x** [alexa/avs-device-sdk#655]
Hi all:

I follow the "Ubuntu Linux Quick Start Guide"(https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide),  build and run the sample app successfully, 
but my purpose is to build and run the sample app on the ARM32(armv71) platform，who could teach me how to build and run on the ARM32(armv71) platform?

PS:My GNU/Linux platform is armv71

Thanks!!!

## Briefly summarize your issue:
   I want to run the sample on the arm32 platform 

## What is the expected behavior?
   I want to run the sample on the arm32 platform

### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [x] Other 
 - tell us more: ARM32 platform

### Tell us about your OS (Type & version):
- [x] Linux

**Comment by bandkenamazoncom** [comment]
We can help with specific questions that you have here!

**Comment by cr1108x** [comment]
Hi sir:
I builded the sample app successfully, but when i run the sample app on the ARM32(armv71) platform,an error has occurred: 
"-sh: ./SampleApp: cannot execute binary file"

please help me!
thanks

**Comment by cr1108x** [comment]
Hi sir:
I also want to konw how to cross complie Sample app for ARM32？

thanks

**Comment by cr1108x** [comment]
Hi all:
Would you give me some suggest about how to cross compile on the embedded system(ARM32)?

thanks

**Comment by bandkenamazoncom** [comment]
You can't build an executable for one architecture and expect it to work on a different platform.  That is likely the error that you have hit.  How did you build the SampleApp.

I suggest reading the documentation for the compiler that you wish to use to cross compile.  Is there a specific problem that you have (i.e. what have you tried)?

**Comment by cr1108x** [comment]
HI @bandkenamazoncom :

Do you have some documentation for cross compile Sample app？

thanks

**Comment by xuqifu** [comment]
hi @cr1108x 
    i have install cross compiler about arm-linux-gcc , but don't know how to replace of gcc . so build code error . can you share same experience for me.
thanks!

**Comment by kencecka** [comment]
Hi @cr1108x, @xuqifu,

We don' have any general guidelines for cross-compiling, as this is generally complex to set up correctly, and the exact details tend to vary widely.  You might want to start by reading some guides on cross-compiling with cmake.  Here's one that discusses it at length: https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling

Ken

**Comment by scotthea-amazon** [comment]
Hi @cr1108x, @xuqifu,

It appears that @kencecka has answered your question, so I am closing this issue. If you have other questions, please open a new issue. If you think that this issue should not have been closed, please feel free to re-open it and clarify what need to be addressed.

Thank you,
-SWH
