### ISSUE TITLE
AVS-SDK not running in bootup

### ISSUE THREAD

**Issue by jay7583** [alexa/avs-device-sdk#656]
Hi,
 I have installed AVS device SDK v1.7 in Raspbian strech desktop.It's running properly.I put in bootup sequence by using crontab.This is the command i have used in crontab.
   @reboot sudo bash /home/pi/echo/startsample.sh &
It's starting in bootup but not working,when i have checked process it was there.After five minutes RAM was shooting to maximum and pi was stucking for two minutes,after that Sample app process is stopping.
I don't understand why it's happening .I have  checked with putting some delay and starting up,still same result i am getting.
Any suggestions?

**Comment by bandkenamazoncom** [comment]
Does it have the same problem when starting it outside of cron?

**Comment by bandkenamazoncom** [comment]
Is it due to in running in the background?  What about instead of running at reboot, schedule it to run at a certain time?

I'm guessing, as it's really not clear what could be happening.

Can you try to start the SampleApp directly rather than using the startsample.sh script?

**Comment by khassel** [comment]
maybe https://github.com/alexa/avs-device-sdk/issues/539 helps

**Comment by jay7583** [comment]
Thanks @khassel @bandkenamazoncom 
i have followed #539 and it's working now.
