### ISSUE TITLE
E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed

### ISSUE THREAD

**Issue by aoGFX** [alexa/avs-device-sdk#659]
im on raspberry pi 3 model b with  Raspbian Stretch latest version
i was on sdk ver 1.6 an it was good but when i upgraded i have error
E MediaPlayer:saveOffsetBeforeTeardown - gst_element_query_position failed

**Comment by aoGFX** [comment]
i solved it by #565 and reboot then all thing fine now 💃

**Comment by bandkenamazoncom** [comment]
Thanks for updating!
