### ISSUE TITLE
Question about ESP

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#661]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi,
Amazon Echo already support ESP. And I also notice Amazon added the ESP code in SDK 1.6. But it requires the ESP library for DESP_LIB_PATH.

How can I get this library? Is it ready to be used in 3rd party device?

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by anu-mathur** [comment]
Hi @subjectxbj 
ESP libraries need a specific whitelisting process to be enabled for commercial devices. Please fill out this  [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I will get in touch with you for next steps.
Closing this issue for now.

**Comment by adcurtin** [comment]
How about non-commercial devices? I would like to make my own alexa device with ESP capabilities for my own personal use.
