### ISSUE TITLE
Problem upgrade to 1.7

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#663]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Hi,
I find the authentication method is changed in 1.7. This introduces a lot of trouble to integrate the upgraded SDK on our device. Originally, our device use the Companion site method to authenticate the device. But now the SDK changed to CBL. This will require us to do a lot of code change if we want to upgrade the SDK. Why not make this as a option, so that different devices can use different method?

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by frozenberg** [comment]
Hi @subjectxbj,

We switched to CBL for internal reasons, but you are free to implement authentication in the companion site method by implementing `AuthDelegateInterface`.

Fede
