### ISSUE TITLE
The behavior different while Barge-in during play music 

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#664]
Hi AVS team,
 
It's in SDK1.7.

There is a behavior different between SDK and commercial Echo product.
While barge-in command during the music is playing, it will lower the music volume and set to background in commercial Echo product; while in SDK, it will just pause the music and play the Q&A voice commands.

Will it a limitation in SDK, or it will plan to do it in further enhancement ?

Thanks,

**Comment by frozenberg** [comment]
Hi @zeusshuang,

No, this is not a limitation in the SDK. Either pausing or volume-attenuation are suitable as per https://developer.amazon.com/docs/alexa-voice-service/functional-requirements.html#media under **Media Services**

Fede

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

thanks for the comment.
if it plans to do the way like Echo in further SDK release ?

**Comment by frozenberg** [comment]
No, there aren't currently any plans to switch to volume-attenuation.

**Comment by zeusshuang** [comment]
thanks for the comments.
