### ISSUE TITLE
Enhancement: KITT_AI-Params as runtime-params

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#665]
## Briefly summarize your issue:
The following Kitt-Ai-Params are set as const in KeywordDetectorProvider.cpp
```
/// The sensitivity of the Kitt.ai engine.
static const double KITT_AI_SENSITIVITY = 0.6;

/// The audio amplifier level of the Kitt.ai engine.
static const float KITT_AI_AUDIO_GAIN = 2.0;

/// Whether Kitt.ai should apply front end audio processing.
static const bool KITT_AI_APPLY_FRONT_END_PROCESSING = true;
```
So afaik changing these params requires a recompile.
Can we get these params as runtime-params, set e.g. in AlexaClientSDKConfig.json?

For other Wakewords you have to play with these params and it is ugly to be forced to recompile everytime.

Thanks,

Karsten.

**Comment by frozenberg** [comment]
Hi @khassel,

Thanks for the suggestion. I have created a ticket for the SDK team.

Fede

**Comment by khassel** [comment]
@frozenberg : Any idea when this is coming?

Meanwhile I did a dirty `sed`-solution for the 2 params I need:
````
sed -i "s:KITT_AI_SENSITIVITY}},:atof(getenv(\"KITT_AI_SENSITIVITY\"))}},:" /srv/sdk-folder/sdk-source/avs-device-sdk/KWD/KWDProvider/src/KeywordDetectorProvider.cpp
sed -i "s:KITT_AI_APPLY_FRONT_END_PROCESSING);:(strcmp(getenv(\"KITT_AI_APPLY_FRONT_END_PROCESSING\"), \"true\") == 0));:" /srv/sdk-folder/sdk-source/avs-device-sdk/KWD/KWDProvider/src/KeywordDetectorProvider.cpp
````
Now after setting the 2 params as env-vars with the needed values this works without recompile.
