### ISSUE TITLE
Unable to run SampleApp for the first time during set up

### ISSUE THREAD

**Issue by NotGoodAtUsernames** [alexa/avs-device-sdk#667]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I'm following Raspberry Pi quick start guide. When I try to start the SampleApp using ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json in the sdk-build folder, I get the response 2018-04-29 11:48:27.578 [  1] I sdkVersion: 1.7.0
USAGE: ./SampleApp/src/SampleApp <path_to_AlexaClientSDKConfig.json> <path_to_inputs_folder> [log_level]

## What is the expected behavior?
The SampleApp should start.
## What behavior are you observing?
2018-04-29 11:48:27.578 [  1] I sdkVersion: 1.7.0
USAGE: ./SampleApp/src/SampleApp <path_to_AlexaClientSDKConfig.json> <path_to_inputs_folder> [log_level]

### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hi @NotGoodAtUsernames,

It appears that @frozenberg has answered your question, so I am closing this issue. If you have other questions, please open a new issue. If you think that this issue should not have been closed, please feel free to re-open it and clarify what need to be addressed.

Thank you,
-SWH

**Comment by mwfarooqi** [comment]
hi
I am new to all of this and having a similar issue. Following the steps provided by @frozenberg, I have put the correct path sources but keep getting the error as below. See attached config file. Also whilst the steps to create the sample app have been written very detailed for a novice to understand, I am unsure of how to setup the wakework engine. I would prefer using Sensory but I do not know how to do this. can you help please?

pi@raspberrypi:~/sdk-folder/sdk-build $ ./SampleApp/src/SampleApp "/home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKconfig.json" "/home/pi/sdk-folder/third-party/alexa-rpi/models"
2018-10-11 06:59:11.623 [  1] I sdkVersion: 1.9.0
configFile /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKconfig.json
2018-10-11 06:59:11.629 [  1] C SampleApplication:Failed to read config file:filename=/home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKconfig.json
Failed to read config file /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKconfig.json
2018-10-11 06:59:11.629 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!



 {
    "cblAuthDelegate":{
        // Path to CBLAuthDelegate's database file. e.g. /home/ubuntu/Build/cblAuthDelegate.db
        // Note: The directory specified must be valid.
        // The database file (cblAuthDelegate.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for CBLAuthDelegate (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/cblAuthDelegate.db"
    },
    "deviceInfo":{
        // Unique device serial number. e.g. 123456
        "deviceSerialNumber":"110700"
        // The Client ID of the Product developer.amazon.com
        "clientId":"amzn1.application-oa2-client.af92c85f89c0465bb8cf047a7f3f4881",
        // Product ID from developer.amazon.com
        "productId":"mo_mirror"
    },
    "capabilitiesDelegate":{
        // The endpoint to connect in order to send device capabilities.
        // This will only be used in DEBUG builds.
        // e.g. "endpoint": "https://api.amazonalexa.com"
        // Override the message to be sent out to the Capabilities API.
        // This will only be used in DEBUG builds.
        // e.g. "overridenCapabilitiesPublishMessageBody": {
        //          "envelopeVersion":"20160207",
        //          "capabilities":[
        //              {
        //                "type":"AlexaInterface",
        //                "interface":"Alerts",
        //                "version":"1.1"
        //              }
        //          ]
        //      }
    },
    "miscDatabase":{
        // Path to misc database file. e.g. /home/ubuntu/Build/miscDatabase.db
        // Note: The directory specified must be valid.
        // The database file (miscDatabase.db) will be created by SampleApp, do not create it yourself.
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/miscDatabase.db"
    },
    "alertsCapabilityAgent":{
        // Path to Alerts database file. e.g. /home/ubuntu/Build/alerts.db
        // Note: The directory specified must be valid.
        // The database file (alerts.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for alerts (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/alerts.db"
    },
    "settings":{
        // Path to Settings database file. e.g. /home/ubuntu/Build/settings.db
        // Note: The directory specified must be valid.
        // The database file (settings.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for settings (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/settings.db",
        "defaultAVSClientSettings":{
            // Default language for Alexa.
            // See https://developer.amazon.com/docs/alexa-voice-service/settings.html#settingsupdated for valid values.
            "locale":"en-US"
        }
    },
    "bluetooth" : {
        // Path to Bluetooth database file. e.g. /home/ubuntu/Build/bluetooth.db
        // Note: The directory specified must be valid.
        // The database file (bluetooth.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for bluetooth (don't use it for other components of SDK)
        //"databaseFilePath":""
    },
    "certifiedSender":{
        // Path to Certified Sender database file. e.g. /home/ubuntu/Build/certifiedsender.db
        // Note: The directory specified must be valid.
        // The database file (certifiedsender.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for certifiedSender (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/certifiedSender.db"
    },
    "notifications":{ 
        // Path to Notifications database file. e.g. /home/ubuntu/Build/notifications.db
        // Note: The directory specified must be valid.
        // The database file (notifications.db) will be created by SampleApp, do not create it yourself.
        // The database file should only be used for notifications (don't use it for other components of SDK)
        "databaseFilePath":"/home/pi/sdk-folder/application-necessities/notifications.db"
    },
    "sampleApp":{
        // To specify if the SampleApp supports display cards.
        "displayCardsSupported":true
        // The firmware version of the device to send in SoftwareInfo event.
        // Note: The firmware version should be a positive 32-bit integer in the range [1-2147483647].
        // e.g. "firmwareVersion": 123
        // The default endpoint to connect to.
        // See https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#endpoints for regions and values
        // e.g. "endpoint": "https://avs-alexa-na.amazon.com"

        // Example of specifying suggested latency in seconds when openning PortAudio stream. By default,
        // when this paramater isn't specified, SampleApp calls Pa_OpenDefaultStream to use the default value.
        // See http://portaudio.com/docs/v19-doxydocs/structPaStreamParameters.html for further explanation
        // on this parameter.
        //"portAudio":{
        //    "suggestedLatency": 0.150
        //}
    }

    // Example of specifying output format and the audioSink for the gstreamer-based MediaPlayer bundled with the SDK.
    // Many platforms will automatically set the output format correctly, but in some cases where the hardware requires
    // a specific format and the software stack is not automatically setting it correctly, these parameters can be used
    // to manually specify the output format.  Supported rate/format/channels values are documented in detail here:
    // https://gstreamer.freedesktop.org/documentation/design/mediatype-audio-raw.html
    //
    // By default the "autoaudiosink" element is used in the pipeline.  This element automatically selects the best sink
    // to use based on the configuration in the system.  But sometimes the wrong sink is selected and that prevented sound
    // from being played.  A new configuration is added where the audio sink can be specified for their system.
    // "gstreamerMediaPlayer":{
    //     "outputConversion":{
    //         "rate":16000,
    //         "format":"S16LE",
    //         "channels":1
    //     },
    //     "audioSink":"autoaudiosink"
    // },

    // Example of specifiying curl options that is different from the default values used by libcurl.
    // "libcurlUtils":{
    //
    //     By default libcurl is built with paths to a CA bundle and a directory containing CA certificates. You can
    //     direct the AVS Device SDK to configure libcurl to use an additional path to directories containing CA
    //     certificates via the CURLOPT_CAPATH setting.  Additional details of this curl option can be found in:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_CAPATH.html
    //     "CURLOPT_CAPATH":"INSERT_YOUR_CA_CERTIFICATE_PATH_HERE",
    //
    //     You can specify the AVS Device SDK to use a specific outgoing network interface.  More information of
    //     this curl option can be found here:
    //     https://curl.haxx.se/libcurl/c/CURLOPT_INTERFACE.html
    //     "CURLOPT_INTERFACE":"INSERT_YOUR_INTERFACE_HERE"
    // },

    // Example of specifying a default log level for all ModuleLoggers.  If not specified, ModuleLoggers get
    // their log level from the sink logger.
    // "logging":{
    //     "logLevel":"INFO"
    // },

    // Example of overriding a specific ModuleLogger's log level whether it was specified by the default value
    // provided by the logging.logLevel value (as in the above example) or the log level of the sink logger.
    // "acl":{
    //     "logLevel":"DEBUG9"
    // }
 }


// Notes for logging
// The log levels are supported to debug when SampleApp is not working as expected.
// There are 14 levels of logging with DEBUG9 providing the highest level of logging and CRITICAL providing
// the lowest level of logging i.e. if DEBUG9 is specified while running the SampleApp, all the logs at DEBUG9 and
// below are displayed, whereas if CRITICAL is specified, only logs of CRITICAL are displayed.
// The 14 levels are:
// DEBUG9, DEBUG8, DEBUG7, DEBUG6, DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, DEBUG0, INFO, WARN, ERROR, CRITICAL.

// To selectively see the logging for a particular module, you can specify logging level in this json file.
// Some examples are:
// To only see logs of level INFO and below for ACL and MediaPlayer modules,
// -  grep for ACSDK_LOG_MODULE in source folder. Find the log module for ACL and MediaPlayer.
// -  Put the following in json:

// "acl":{
//  "logLevel":"INFO"
// },
// "mediaPlayer":{
//  "logLevel":"INFO"
// }

// To enable DEBUG, build with cmake option -DCMAKE_BUILD_TYPE=DEBUG. By default it is built with RELEASE build.
// And run the SampleApp similar to the following command.
// e.g. ./SampleApp /home/ubuntu/.../AlexaClientSDKConfig.json /home/ubuntu/KittAiModels/ DEBUG9"
