### ISSUE TITLE
Can`t Find Smart Devices 

### ISSUE THREAD

**Issue by aoGFX** [alexa/avs-device-sdk#668]
I made a smart device with node mcu using this tutorial : http://www.instructables.com/id/Alexa-NodeMCU-WeMo-Emulation-Made-Simple/

I made it successfully and device connected to same wifi but when i say to alexa : "Search devices"
she replay with "can`t find any smart home devices connected"
i tried alexa app on my phone but i cant find devices too .

My Alexa Sdk on raspberryPI 3 Model B with Latest raspbian stretch
plz help :(

**Comment by aoGFX** [comment]
no help ?

**Comment by frozenberg** [comment]
Hi @aoGFX 

Unfortunately, AVS does not currently support device discovery.

Fede
