### ISSUE TITLE
microphone test failed

### ISSUE THREAD

**Issue by bill-lzb** [alexa/avs-device-sdk#669]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Microphone test failed.
## What is the expected behavior?

rec test.wav should work, and arecord -l should output the record devices.
## What behavior are you observing?

When I run rec test.wav, the following errors were output:
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
 rec FAIL formats: can't open input `default': snd_pcm_open error: No such file or directory

And arecord -l output nothing.
## Provide the steps to reproduce the issue, if applicable:

I just followed https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide.
### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by priyagsenthil** [comment]
Hi @bill-lzb,

Am closing this issue as we haven't heard back from you. If you still see the issue feel free to open another issue.

Thanks
Priya

**Comment by bill-lzb** [comment]
Hi Priya

After connecting a USB microphone, it became OK.

Thanks
Bill
