### ISSUE TITLE
Unable to build Sample app from outside in avs-device-sdk v1.7

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#671]
Hi,
I have followed #368 (https://github.com/alexa/avs-device-sdk/issues/368) for building SampleApp from outside.
It was working fine till avs-device-sdk v1.6
For v1.7, It is failed 
The logs are:-
        Scanning dependencies of target Simplifi_Alexa
[ 10%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/ConnectionObserver.cpp.o
[ 20%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/ConsolePrinter.cpp.o
[ 30%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/GuiRenderer.cpp.o
[ 40%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/InteractionManager.cpp.o
[ 50%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/KeywordObserver.cpp.o
[ 60%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/PortAudioMicrophoneWrapper.cpp.o
[ 70%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/UIManager.cpp.o
[ 80%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/UserInputManager.cpp.o
[ 90%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/SampleApplication.cpp.o
In file included from /home/harman/1.7_Alexa/sdk-source/Simplifi_Alexa/include/SampleApp/SampleApplication.h:31:0,
                 from /home/harman/1.7_Alexa/sdk-source/Simplifi_Alexa/src/SampleApplication.cpp:19:
/home/harman/build_alexa/include/MediaPlayer/MediaPlayer.h:29:21: fatal error: gst/gst.h: No such file or directory
 #include <gst/gst.h>

My src/CMakeLists.txt is:

find_package(PkgConfig)
pkg_check_modules(SDK REQUIRED AlexaClientSDK)
pkg_check_modules(PortAudio REQUIRED portaudio-2.0)
link_directories(${SDK_LIBRARY_DIRS})

set(Simplifi_Alexa_SOURCES)
list(APPEND Simplifi_Alexa_SOURCES 
    ConnectionObserver.cpp
    ConsolePrinter.cpp
    GuiRenderer.cpp
    InteractionManager.cpp
    KeywordObserver.cpp
    PortAudioMicrophoneWrapper.cpp
    UIManager.cpp
    UserInputManager.cpp
    SampleApplication.cpp
    main.cpp)

IF (HAS_EXTERNAL_MEDIA_PLAYER_ADAPTERS)
    file(GLOB_RECURSE SRC_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ExternalMediaAdapterRegistration/*.cpp)
    foreach(myfile ${SRC_FILE})
       list(APPEND Simplifi_Alexa_SOURCES ${myfile})
    endforeach(myfile)
ENDIF()

add_executable(Simplifi_Alexa ${Simplifi_Alexa_SOURCES})

target_include_directories(Simplifi_Alexa PUBLIC 
    "${Simplifi_Alexa_SOURCE_DIR}/include"
    "${MediaPlayer_SOURCE_DIR}/include"
    "${AudioResources_SOURCE_DIR}/include"
    "${RegistrationManager_SOURCE_DIR}/include"
    "${ESP_SOURCE_DIR}/include"
    "${PORTAUDIO_INCLUDE_DIR}")

target_link_libraries(Simplifi_Alexa 
    DefaultClient
    DCFDelegate
    CBLAuthDelegate
    MediaPlayer
    SQLiteStorage
    ESP
    "${PORTAUDIO_LIB_PATH}")
if(KWD)
    target_link_libraries(Simplifi_Alexa KeywordDetectorProvider)
endif()

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    target_link_libraries(Simplifi_Alexa
        "-framework CoreAudio" 
        "-framework AudioToolbox" 
        "-framework AudioUnit" 
        "-framework CoreServices" 
        "-framework Carbon")
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    target_link_libraries(Simplifi_Alexa
      rt m pthread asound)
endif()

My Simplifi_Alexa/CMakeLists.txt is: 

cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(Simplifi_Alexa LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DRAPIDJSON_HAS_STDSTRING")
add_subdirectory("src")

Thanks,
Sumit

**Comment by frozenberg** [comment]
Hi @sumit3817,

Can I see what your cmake command looks like? Also (just to make sure), have you installed gstreamer?

Fede

**Comment by sumit3817** [comment]
Hi,
Yes, gstreamer is already installed as I am able to compile avs-device-sdk.

To compile avs-device-sdk, cmake command:-

1) export PKG_CONFIG_PATH=/usr/arm-linux-gnueabihf/lib/pkgconfig:$PKG_CONFIG_PATH

2) cmake -DCMAKE_TOOLCHAIN_FILE=/home/harman/toolchain.cmake /home/harman/1.7_Alexa/sdk-source/avs-device-sdk -DCMAKE_INSTALL_PREFIX=/home/harman/build_alexa  -DSENSORY_KEY_WORD_DETECTOR=OFF  -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/harman/build_alexa/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/harman/build_alexa/include -DCMAKE_BUILD_TYPE=DEBUG

3) make
4) sudo make install

My all libraries get installed at path /home/harman/build_alexa 
Now the cmake command for building SampleApp application from outside

I have renamed SampleApp to Simplifi_Alexa

5) cmake -DCMAKE_TOOLCHAIN_FILE=/home/harman/toolchain.cmake /home/harman/1.7_Alexa/sdk-source/Simplifi_Alexa  -DCMAKE_PREFIX_PATH=/home/harman/build_alexa -DCMAKE_INSTALL_PREFIX=/home/harman/build_alexa  -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/harman/build_alexa/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/harman/build_alexa/include  -DCMAKE_BUILD_TYPE=DEBUG

6) make ------> Build error 

This was working till avs-device-sdk v1.6,
In 1.7, it get failed. 
Is there any more changes needed in src/CMakeLists.txt  for 1.7 to build the application from outside?

Thanks,
Sumit

**Comment by frozenberg** [comment]
You might need to change "DCFDelegate" to "CapabilitiesDelegate"

**Comment by sumit3817** [comment]
Hi,

This is done; It needs some more changes in src/CMakeLists.txt.
Thanks for your support.
You can close this issue.

Thanks,
Sumit
