### ISSUE TITLE
Does the authorization in SDK V1.6 still available in SDKV1.7?

### ISSUE THREAD

**Issue by boyce-xx** [alexa/avs-device-sdk#672]
Hi,
I noticed that below from the released notes for SDK V1.7.0:
`AuthDelegate and AuthServer.py have been replaced by CBLAUthDelegate, which uses Code Based Linking for authorization. `
I also noticed that there have three ways to authorize product from [here](https://developer.amazon.com/docs/alexa-voice-service/api-overview.html#authorization)

Because the AuthDelegate API has been removed from V1.7.0 SDK, so I want to know if the authorization prior to SDK V1.7.0 is available in SDK V1.7.0, if yes, how can I implement it?

Which authorization type is your suggested  in SDK V1.7.0 and Why? 

Thanks.

**Comment by frozenberg** [comment]
Hi @boyce-xx,

You can still use the old AuthDelegate interface by implementing `AuthDelegateInterface`. 

I don't have any recommendations for authorization type, though I find CBL a bit more convenient/user-friendly.

Fede

**Comment by boyce-xx** [comment]
Hi @frozenberg ,
Copy that.
Thanks for your clarification.
