### ISSUE TITLE
How to check DND mode ?

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#675]
Hi AVS team,

It's under SDK1.7.
I checked the gitHub#508, it said the DND mode flag is currently not supported ?

By Echo design, while it's in DND mode and a new notification arrived, it will show purple LED once.
So far in SDK1.7. if I enabled the DND, it will not receive the notification message (should be correct), but I even did not receive any directive to mentioned it's in DND mode and a new message arrived. (so I have no chance to indicate LED to the user)

Is this behavior correct by current SDK 1.7 design ?

**Comment by frozenberg** [comment]
Hi @zeusshuang ,

That's correct. DND is not supported in AVS as of today. Once DND is supported by AVS the SDK will implement an observer interface that you can use.

Fede

**Comment by zeusshuang** [comment]
Thanks for the comment.
