### ISSUE TITLE
Build Error AVS_SDK

### ISSUE THREAD

**Issue by dipankjain** [alexa/avs-device-sdk#676]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am trying to build AVS-SDK in my machine.

## What is the expected behavior?

While doing the build, i am getting error. Expected is to get the build successfully.

## What behavior are you observing?

Observing error while building.

With the error log:
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
Creating the build directory for the AlexaClientSDK with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ACL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Authorization with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CBLAuthDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ADSL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the AFML with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CertifiedSender with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ContextManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the DCFDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the MediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the PlaylistParser with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the CapabilityAgents with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AIP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Alerts with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the AudioPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ExternalMediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Notifications with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeakerManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeechSynthesizer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Integration with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Please fill //local/mnt/workspace/avs-sdk/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json before you execute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
Creating the build directory for the ApplicationUtilities with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DefaultClient with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ESP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the RegistrationManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SampleApp with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Storage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SQLiteStorage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: //local/mnt/workspace/avs-sdk/sdk-folder/sdk-build
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
make[1]: *** No rule to make target '//local/mnt/workspace/avs-sdk/sdk-folder/sdk-build/all'.  Stop.
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

## Provide the steps to reproduce the issue, if applicable:

followed the link:https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

### What version of the AVS Device SDK are you using?
      <x.y.z>
Enviroment: Ubuntu 16.04.
AVS-Latest

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
Desktop

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
LINUX-16.04

**Comment by frozenberg** [comment]
Hi @dipankjain,

Could you show me the exact `cmake` command you used? Could you also try running `cmake` and then `make` as separate commands and posting the output?

Fede

**Comment by dipankjain** [comment]
CMAKE COMMAND USED: cmake /$HOME/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/$HOME/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/$HOME/sdk-folder/third-party/portaudio/include && makecmake /$HOME/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/$HOME/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a


Output:
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
Creating the build directory for the AlexaClientSDK with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the ACL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the Authorization with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CBLAuthDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ADSL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the AFML with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the CertifiedSender with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the ContextManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the DCFDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the MediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the PlaylistParser with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the CapabilityAgents with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AIP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the Alerts with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the AudioPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the ExternalMediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Notifications with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeakerManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the SpeechSynthesizer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the Integration with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Please fill //local/mnt/workspace/avs-sdk/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json before you execute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
Creating the build directory for the ApplicationUtilities with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DefaultClient with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ESP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the RegistrationManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Creating the build directory for the SampleApp with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Storage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SQLiteStorage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: //local/mnt/workspace/avs-sdk/sdk-folder/sdk-build
bash: makecmake: command not found

When Runnig MAKE COMMAND output is :
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
make[1]: *** No rule to make target '//local/mnt/workspace/avs-sdk/sdk-folder/sdk-build/all'.  Stop.
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dipankjain** [comment]
gstreamer error has gone post doing:
sudo apt-get install cmake libgtest-dev
cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
 
# copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
sudo cp *.a /usr/lib


**Command:**
cmake /{HOME}/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/{HOME}/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/{HOME}/sdk-folder/third-party/portaudio/include && make

**But still getting error:**
 CMake Error: The source directory "/{HOME}/sdk-folder/sdk-source/avs-device-sdk" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
dipankj@dipankj-linux://local/mnt/workspace/avs-sdk$ cmake /$HOME/sdk-folder/sdk-source/avs-device-sdk -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/$HOME/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/$HOME/sdk-folder/third-party/portaudio/include && make
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
No build type specified, defaulting to Release.
Creating the build directory for the AlexaClientSDK with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   Found gstreamer-1.0, version 1.12.4
--   Found gstreamer-app-1.0, version 1.12.4
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CURL: /usr/local/lib/libcurl.so (found suitable version "7.54.0", minimum required is "7.43.0") 
-- Found GTest: /usr/lib/libgtest.a  
Creating the build directory for the ACL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Authorization with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CBLAuthDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ADSL with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AFML with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CertifiedSender with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ContextManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DCFDelegate with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the MediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the PlaylistParser with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CapabilityAgents with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AIP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Alerts with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AudioPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ExternalMediaPlayer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Notifications with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SpeakerManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SpeechSynthesizer with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ApplicationUtilities with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DefaultClient with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ESP with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the RegistrationManager with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SampleApp with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Storage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SQLiteStorage with build type: RELEASE
No keyword detector type specified, skipping build of keyword detector.
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.11.0
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: //local/mnt/workspace/avs-sdk
make[1]: *** No rule to make target '//local/mnt/workspace/avs-sdk/all'.  Stop.
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dipankjain** [comment]
**With Command**
cmake /$HOME/sdk-folder/sdk-source/avs-device-sdk -Wno-dev  -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/$HOME/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/$HOME/sdk-folder/third-party/portaudio/include && make

**Result**
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ACL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Authorization with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CBLAuthDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ADSL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AFML with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CertifiedSender with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ContextManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DCFDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the MediaPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the PlaylistParser with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the CapabilityAgents with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AIP with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Alerts with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the AudioPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ExternalMediaPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Notifications with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SpeakerManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SpeechSynthesizer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ApplicationUtilities with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the DefaultClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ESP with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the RegistrationManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SampleApp with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Storage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SQLiteStorage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Configuring done
-- Generating done
-- Build files have been written to: //local/mnt/workspace/avs-sdk/sdk-folder/sdk-build
make[1]: *** No rule to make target '//local/mnt/workspace/avs-sdk/sdk-folder/sdk-build/all'.  Stop.
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dipankjain** [comment]
IT statered to build, but got stuck at 
ir/SQLiteMessageStorage.cpp.o
[ 58%] Linking CXX shared library libCertifiedSender.so
[ 58%] Built target CertifiedSender
Scanning dependencies of target MessageStorageTest
[ 58%] Building CXX object CertifiedSender/test/CMakeFiles/MessageStorageTe                                                                                  st.dir/MessageStorageTest.cpp.o
[ 58%] Linking CXX executable MessageStorageTest
[ 58%] Built target MessageStorageTest
Scanning dependencies of target CertifiedSenderTest
[ 58%] Building CXX object CertifiedSender/test/CMakeFiles/CertifiedSenderT                                                                                  est.dir/CertifiedSenderTest.cpp.o
[ 58%] Linking CXX executable CertifiedSenderTest
[ 58%] Built target CertifiedSenderTest
Scanning dependencies of target ContextManager
[ 58%] Building CXX object ContextManager/src/CMakeFiles/ContextManager.dir                                                                                  /ContextManager.cpp.o
[ 59%] Linking CXX shared library libContextManager.so
[ 59%] Built target ContextManager
Scanning dependencies of target ContextManagerTest
[ 59%] Building CXX object ContextManager/test/CMakeFiles/ContextManagerTes                                                                                  t.dir/ContextManagerTest.cpp.o
[ 59%] Linking CXX executable ContextManagerTest
[ 59%] Built target ContextManagerTest
Scanning dependencies of target DCFDelegate
[ 59%] Building CXX object DCFDelegate/src/CMakeFiles/DCFDelegate.dir/DCFDe                                                                                  legate.cpp.o
//local/mnt/workspace/avs-sdk/sdk-folder/sdk-source/avs-device-sdk/DCFDeleg                                                                                  ate/src/DCFDelegate.cpp:28:44: fatal error: ACL/Transport/TransportDefines.                                                                                  h: No such file or directory
compilation terminated.
DCFDelegate/src/CMakeFiles/DCFDelegate.dir/build.make:62: recipe for target                                                                                   'DCFDelegate/src/CMakeFiles/DCFDelegate.dir/DCFDelegate.cpp.o' failed
make[2]: *** [DCFDelegate/src/CMakeFiles/DCFDelegate.dir/DCFDelegate.cpp.o]                                                                                   Error 1
CMakeFiles/Makefile2:4204: recipe for target 'DCFDelegate/src/CMakeFiles/DC                                                                                  FDelegate.dir/all' failed
make[1]: *** [DCFDelegate/src/CMakeFiles/DCFDelegate.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by frozenberg** [comment]
@dipankjain 

Great!
