### ISSUE TITLE
How to know it's Deregister from APP 

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#677]
Hi AVS team,

Its AVS SDK1.7.

I referenced the #339 and #574 , which I ever question dereigster message before.
It seems the message is different since SDK 1.7 ?
While I deregistered from APP, I will only receive "ResetUserInactivity" directive message.
May I say, while I receive this message, it's a deregister case ?

**Comment by zeusshuang** [comment]
Hi @frozenberg ,

Thanks for the information.
If it's not for the deregister case, is there any way in AVS client that I can know user click deregister from APP ?

**Comment by frozenberg** [comment]
You can implement a `RegistrationObserver`, look for the file `RegistrationObserver.h`.

RegistrationManager will notify any of those observers when logout() happens,.

**Comment by zeusshuang** [comment]
Thanks for the information! Will follow this way.
