### ISSUE TITLE
Make SampleApp(SDK 1.7.0) error  when  linking libKITTAI.so

### ISSUE THREAD

**Issue by xuewenxu** [alexa/avs-device-sdk#678]
When I build SampleApp on Raspberry Pi  and use KITT_AI  as KWD, it appears a error:

-- Build files have been written to: /home/pi/alexa_setup/build
[  0%] Built target gmock
[  1%] Built target gtest
[ 30%] Built target AVSCommon
[ 34%] Built target SQLiteStorage
[ 38%] Built target ACL
[ 40%] Built target RegistrationManager
[ 42%] Built target ADSL
[ 44%] Built target AFML
[ 44%] Built target CertifiedSender
[ 46%] Built target ContextManager
[ 48%] Built target PlaylistParser
[ 50%] Built target KWD
[ 51%] Built target AIP
[ 55%] Built target AudioResources
[ 57%] Built target AudioPlayer
[ 57%] Built target ExternalMediaPlayer
[ 59%] Built target Notifications
[ 61%] Built target PlaybackController
[ 63%] Built target SpeakerManager
[ 65%] Built target SpeechSynthesizer
[ 67%] Built target Settings
[ 71%] Built target AVSSystem
[ 73%] Built target TemplateRuntime
[ 75%] Built target ESP
[ 76%] Built target CBLAuthDelegate
[ 76%] Built target KITTAI
[ 80%] Built target MediaPlayer
[ 84%] Built target Alerts
[ 94%] Built target Integration
[ 94%] Built target KeywordDetectorProvider
[ 94%] Built target DefaultClient
[ 94%] Built target DCFDelegate
[ 94%] Linking CXX executable SampleApp
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../KWD/KittAi/src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
SampleApp/src/CMakeFiles/SampleApp.dir/build.make:363: recipe for target 'SampleApp/src/SampleApp' failed
make[3]: *** [SampleApp/src/SampleApp] Error 1
CMakeFiles/Makefile2:8240: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/all' failed
make[2]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/all] Error 2
CMakeFiles/Makefile2:8252: recipe for target 'SampleApp/src/CMakeFiles/SampleApp.dir/rule' failed
make[1]: *** [SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
Makefile:2123: recipe for target 'SampleApp' failed
make: *** [SampleApp] Error 2

Some information about build the SDK:
Get KITT_AI  from:   https://github.com/Kitt-AI/snowboy.git

cmake build option is set:  
CMAKE_PLATFORM_SPECIFIC=(-DKITTAI_KEY_WORD_DETECTOR=ON \
  -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=$THIRD_PARTY_PATH/snowboy/lib/rpi/libsnowboy-detect.a \
        -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=$THIRD_PARTY_PATH/snowboy/include)

gcc version:  gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)

**Comment by frozenberg** [comment]
Hi @xuewenxu,

We have some suggestions in the [https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide](Troubleshooting Guide) under **Trouble building with / linking against Kitt.ai**

Let me know if that helps,
Fede

**Comment by marath007** [comment]
I got a success and I can devise a custom bash file.
I'm new to github but I want to post my successful path, where do I do this?

**Comment by frozenberg** [comment]
You mean you want to post the steps you took that got everything working? Feel free to post it here -- if another user runs into this issue we can reference this post!

Fede

**Comment by marath007** [comment]
## PROCEDURE FOR WITH KITTAI
 <SPACE>

## Prerequisite
 <SPACE>

As of the available software on this date may 3, 2018 and  raspberry pie stretch with desktop, USB mic, sound out of the AUX.

**Comment by frozenberg** [comment]
Thanks @marath007 !

**Comment by marath007** [comment]
Super condensed install

``
bash this
`cd /home/pi/ && mkdir sdk-folder && cd sdk-folder && mkdir sdk-build sdk-source third-party application-necessities && cd application-necessities && mkdir sound-files && sudo apt-get update && sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good libasound2-dev doxygen && cd /home/pi/sdk-folder/third-party && wget -c http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz && tar zxf pa_stable_v190600_20161030.tgz && cd portaudio && ./configure --without-jack && make && pip install commentjson && cd /home/pi/sdk-folder/sdk-source && git clone git://github.com/alexa/avs-device-sdk.git && cd /home/pi/Desktop && sudo wget https://raw.githubusercontent.com/marath007/AnimatedProject/master/AlexaClientSDKConfig.json https://raw.githubusercontent.com/marath007/AnimatedProject/master/KittAiKeyWordDetector.cpp https://github.com/marath007/AnimatedProject/blob/master/MediaPlayer.cpp &&  nano ~/.asoundrc
`

paste 
`pcm.!default { type asym playback.pcm { type plug slave.pcm "hw:0,0" } capture.pcm { type plug slave.pcm "hw:1,0" } }`

bash that 
`sudo apt-get install swig3.0 python-pyaudio python3-pyaudio sox libatlas-base-dev -y && cd /home/pi/sdk-folder/third-party && git clone git://github.com/kitt-ai/snowboy.git && sudo apt-get install gstreamer1.0-tools && cd /home/pi/Desktop && sudo cp KittAiKeyWordDetector.cpp /home/pi/sdk-folder/sdk-source/avs-device-sdk/KWD/KittAi/src/KittAiKeyWordDetector.cpp && cd /home/pi/sdk-folder/third-party/snowboy/resources/alexa && cp alexa_02092017.umdl alexa.umdl && cd /home/pi/sdk-folder/third-party/snowboy/resources && cp common.res alexa/common.res && cd /home/pi/Desktop && sudo cp MediaPlayer.cpp /home/pi/sdk-folder/sdk-source/avs-device-sdk/MediaPlayer/src/MediaPlayer.cpp && cd /home/pi/sdk-folder/sdk-build && cmake /home/pi/sdk-folder/sdk-source/avs-device-sdk -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/sdk-folder/third-party/snowboy/lib/rpi/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/sdk-folder/third-party/snowboy/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/pi/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/pi/sdk-folder/third-party/portaudio/include -DCMAKE_CXX_FLAGS:STRING="-D_GLIBCXX_USE_CXX11_ABI=0 -pg" -DCMAKE_BUILD_TYPE=DEBUG && make SampleApp -j2 && cd /home/pi/Desktop cp AlexaClientSDKConfig.json /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json && sudo nano /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json
`
edit config then bash this
`cd /home/pi/sdk-folder/sdk-build/Integration && sudo cp AlexaClientSDKConfig.json AlexaClientSDKConfig2.json && cd /home/pi/sdk-folder/sdk-build/SampleApp/src && ./SampleApp /home/pi/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json /home/pi/sdk-folder/third-party/snowboy/resources/alexa DEBUG9`
