### ISSUE TITLE
Sensory AND KittAi together in one SampleApp

### ISSUE THREAD

**Issue by khassel** [alexa/avs-device-sdk#684]
The compile of the SampleApp is very time consuming so I testet compiling the SampleApp with Sensory and KittAi. This is possible giving cmake Sensory- and KittAi-Params.
But for starting the SampleApp with a specific WakeWordEngine a StartParam "WakeWordEngine" is missing.

Purposes:
- for testing the SampleApp with different WakeWordEngines only one compile necessary
- simplifies providing the SampleApp as docker image (one compile, one image)

Any chance to get such a setup with an additional StartParam? Or did I miss something and it is already possible?

Thanks,
Karsten.

**Comment by frozenberg** [comment]
Hi @khassel,

I've filed a feature request with the SDK team. Thanks for the suggestion.

Fede
