### ISSUE TITLE
UNRECOVERABLE AUTHORIZATION ERROR: UNAUTHORIZED_CLIENT

### ISSUE THREAD

**Issue by wong218** [alexa/avs-device-sdk#687]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
when i'm Initialize the sample app:
sudo bash startsample.sh
it is show
#       UNRECOVERABLE AUTHORIZATION ERROR: UNAUTHORIZED_CLIENT       #
######################################################################

2018-05-03 03:18:38.999 [  2] 5 CBLAuthDelegate:handleStopping
2018-05-03 03:18:38.999 [  9] E DCFDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
pure virtual method called
terminate called without an active exception
startsample.sh: line 3:   934 Aborted                 ./SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9

### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
 Raspberry Pi

### Tell us about your OS (Type & version):

- [ ]  Raspbian Stretch

**Comment by frozenberg** [comment]
Hi @wong218 

To fix this problem, you should take two steps:

1. Remove the CBL database file you are using. This will let the SDK prepare a fresh, uncorrupted database file.
2. Make sure the value of `clientId` in your `AlexaClientSDKConfig.json` file is the clientId found under the **Other devices and platforms tab** on www.developer.amazon.com, not the one found under the **Web** tab

As for the "virtual method" error, I am going to continue looking into it.

Fede

**Comment by guneykayim** [comment]
I was having the same problem, your answer solved it, thanks @frozenberg

**Comment by kjkh** [comment]
Closing issue. Please re-open if you continue to experience authentication errors after following @frozenberg's instructions.
