### ISSUE TITLE
Raspberry PI SampleApp is not starting

### ISSUE THREAD

**Issue by PavelYarysh** [alexa/avs-device-sdk#690]
I followed all the instructions provided here https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#12-install-dependencies and when it came to start an SampleApp I wrote the following code from the link provided: ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json 
And I get the response: USAGE: ./SampleApp/src/SampleApp <path_to_AlexaClientSDKConfig.json> <path_to_inputs_folder> [log_level]
I also tried to start it like this: ./SampleApp/src/SampleApp "/home/pi/build/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9
And received the message: Failed to create a SampleApp.
Can anyone provide any instructions on what to do?

**Comment by frozenberg** [comment]
Hi @PavelYarysh,

Could you post the actual log output from when you ran your second command?

Thanks,
Fede

**Comment by PavelYarysh** [comment]
d/Integration/AlexaClientSDKConfig.json" "/home/pi/third-party/alexa-rpi/models" DEBUG9
2018-05-04 17:43:00.750 [  1] I sdkVersion: 1.7.0
configFile /home/pi/build/Integration/AlexaClientSDKConfig.json
Running app with log level: DEBUG9
2018-05-04 17:43:00.755 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-05-04 17:43:00.755 [  1] W Logger:debugLogLevelSpecifiedWhenDebugLogsCompiledOut:level=DEBUG9:

WARNING: By default DEBUG logs are compiled out of RELEASE builds.
Rebuild with the cmake parameter -DCMAKE_BUILD_TYPE=DEBUG to enable debug logs.

2018-05-04 17:43:00.755 [  1] C SampleApplication:Failed to read config file:filename=/home/pi/build/Integration/AlexaClientSDKConfig.json
Failed to read config file /home/pi/build/Integration/AlexaClientSDKConfig.json
2018-05-04 17:43:00.755 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

**Comment by frozenberg** [comment]
Can you look at your AlexaClientSDKConfig.json file and make sure it is correctly configured? It looks like there was an issue when reading from it.

Also, let's rebuild with a DEBUG build by running

`cmake ../avs-device-sdk -DCMAKE_BUILD_TYPE=DEBUG`

Note that the first argument should be the path to your source directory.

**Comment by PavelYarysh** [comment]
here is what I got from the cmake command:
CMake Error at /usr/share/cmake-3.7/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "/usr/bin/c++" is not able to compile a simple test
  program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: //CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. //CMakeCache.txt
CMake Error: : System Error: Permission denied

here is my json file, I just copied it from the link and changed the product ID and client ID 
{
  "deviceInfo":{
    "deviceSerialNumber":"123456",
    "clientId":"amzn1.application-oa2-client.3daef90ebc764bfbd220734144a3bd1",
    "productId":"rasp"
  },
  "cblAuthDelegate":{
      "databaseFilePath":"/home/pi/sdk-folder/application-necessities/cblAuthDelegate.db"
  },
  "miscDatabase":{
      "databaseFilePath":"/home/pi/sdk-folder/application-necessities/miscDatabase.db"
  },
  "alertsCapabilityAgent":{
      "databaseFilePath":"/home/pi/sdk-folder/application-necessities/alerts.db"
  },
  "settings":{
      "databaseFilePath":"/home/pi/sdk-folder/application-necessities/settings.db",
      "defaultAVSClientSettings":{
          "locale":"en-US"
      }
  },
  "certifiedSender":{
     "databaseFilePath":"/home/pi/sdk-folder/application-necessities/certifiedSender.db"
  },
  "notifications":{
      "databaseFilePath":"/home/pi/sdk-folder/application-necessities/notifications.db"
  }
}

**Comment by PavelYarysh** [comment]
now I rebuilt again:
Creating the build directory for the DefaultClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the ESP with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the RegistrationManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the SampleApp with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the Storage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Creating the build directory for the SQLiteStorage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.16.2
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi

**Comment by PavelYarysh** [comment]
Also I found out, that I have two folders: build and source and each of them have similar folders and files, from which folder should I start SampleApp?

**Comment by PavelYarysh** [comment]
Finally it helped, thank you very much, I very appreciate your help!! And last question: if I want to make changes to source code for personal use, how would I rebuild the app?

**Comment by frozenberg** [comment]
You can

1. Edit whatever source code you want in your source directory.
2. In your build directory, run `make` (or, to speed things up, `make -j 2`).
3. Run SampleApp.

What I usually do is combine the last two steps into something like
`make -j 2 && ./SampleApp/src/SampleApp /path/to/AlexaClientSDKConfig.json /home/pi/third-party/alexa-rpi/models DEBUG9`

**Comment by PavelYarysh** [comment]
Thank you very much again, have a great day, my day just became great because of you:)

**Comment by PavelYarysh** [comment]
One last question, as I tried to rebuild files it looks like the make function just creates another app, instead of updating and Im running out of memory, does it suppose to go like that?

**Comment by frozenberg** [comment]
What do you mean by "creates another app"?

**Comment by PavelYarysh** [comment]
So the process is going really slow, like the first time I used make command, and for some reason I started running out of memory, although before the app worked and there were some memory space. I added only two lines of code without any additional libraries

**Comment by PavelYarysh** [comment]
Oh, I think I figured it out, I forgot to write SampleApp in make command
