### ISSUE TITLE
Sound cannot be output from headphone jack

### ISSUE THREAD

**Issue by bill-lzb** [alexa/avs-device-sdk#691]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I run sudo amixer cset numid=3 1 to set the sound to come from headphone jack, and then run the SampleApp, but the sound was output from HDMI
## What is the expected behavior?

After sudo amixer cset numid=3 1, the sound should be output from headphone jack.
## What behavior are you observing?

The sound was always output from HDMI.
## Provide the steps to reproduce the issue, if applicable:

First run sudo amixer cset numid=3 1.
Second run the SampleApp.
### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by priyagsenthil** [comment]
Please use the troubleshooting guide https://github.com/alexa/avs-device-sdk/wiki/Troubleshooting-Guide. There are some guides specifically to getting audio in USB vs headphone jack.

**Comment by Black-Behemoth** [comment]
The Troubleshooting guide in the post above is outdated since line 599 in MediaPlayer.cpp has been changed to 
      ACSDK_ERROR(LX("setupPipelineFailed").d("reason", "createCapabilityStructFailed"));

**Comment by kencecka** [comment]
@Black-Behemoth, thanks for pointing out the docs issue.  We'll update the guide to refer to the correct line numbers.

@bill-lzb, I'm going to go ahead and close this issue.  Please reopen if you are still having trouble.

Ken
