### ISSUE TITLE
I want to build an app which uses amazon Alexa using AVS SDK.

### ISSUE THREAD

**Issue by shriram10** [alexa/avs-device-sdk#702]
I want to build an app which uses amazon Alexa using AVS SDK. How do i integrate the sdk with my android framework. Can any one give a clear picture of how this works. 
Basically I want to build an app which takes audio input and send it to Alexa and want to get the response back.

**Comment by priyagsenthil** [comment]
Hi Shriram,

Currently C++ SDK provides instruction to build the component libraries for Android. You can reach out to anuma@amazon.com for access to the Andriod guide. Currently we do no support a full fledged SampleApp with audio path in Android. We only provider libraries of the core SDK components that a developer can hook up with Android audio path.

Thanks
Priya

**Comment by shriram10** [comment]
Thanks Priya, can you just tell me on how do I start building this. How do I make use of this AVS Device
 SDK in my android studio.

**Comment by priyagsenthil** [comment]
Hi Shriram10,

Reach out to anuma@amazon.com for access to the Android build guide.

Thanks
Priya

**Comment by mmabluesky** [comment]
@shriram10 
Hi Shriram,  Has  avs sdk  been successfully ported to Android  ?  How is your progress?

**Comment by shriram10** [comment]
Since i am a beginner in this, I have not done anything. Can you please tell me the steps to do this. I have just installed AVS SDk that's it.

**Comment by shriram10** [comment]
Can you please respond as soon as possible.

**Comment by kencecka** [comment]
Hi @shriram10,

To get additional help with Android, please fill out the contact form:
https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268

Ken
