### ISSUE TITLE
Code modification for custom application

### ISSUE THREAD

**Issue by sriranjanr** [alexa/avs-device-sdk#703]
Hello,

I am trying to add my custom hardware /software application to the alexa sample app. I want to make alexa listen when I press a button on the raspberry pi (I might want to use the wake work initially after button press but in the later version I will not include key word wake up, but I just need alexa to work with hardware button press). So where shall I modify the code to initiate alexa to listen. In the sample app in the output when I say alexa I get listening printed on the screen so where is the code where listening is actually being printed out? I am using SKD 1.6. Please let me know.

**Comment by priyagsenthil** [comment]
Hi sriranjanr,

SampleApp already takes an input 't' to simulate a button press. Take a look at UserInputManager.cpp  to see the controls and interaction with SampleApp.

THanks
Priya

**Comment by sriranjanr** [comment]
I have looked at UserInputManager.cpp and it comes to this 

else if (x == TAP) {
m_interactionManager->tap();

So should I add my button press code here?

**Comment by priyagsenthil** [comment]
Hi sriranjanr,

Yes that is correct.

**Comment by sriranjanr** [comment]
Is it possible to enable and disable wake word detection from the code in SampleApp? If yes how shall I do that. This is important for me to do so in my sample applications.

**Comment by priyagsenthil** [comment]
Hi sriranjanr,

Under build options
https://github.com/alexa/avs-device-sdk/wiki/Build-Options please go over the session about building with and without wakeword.

Look into the code in PortAudioWrapper to fetch the input audio bytes.

Thanks
Priya

**Comment by priyagsenthil** [comment]
The PortAudioCallback should be called continuously to read audio bytes as long as there input audio. Seeing the number of samples for one callback may not give the correct sample size. 

Thanks
Priya

**Comment by sriranjanr** [comment]
Whenever Alexa is listening the callback function is being called multiple times but the numSamples variable is always 139. I am unable to understand why this is happening. Could you provide me an alternate Portaudiomicrophonewrapper.cpp with few lines of code where I can access the input data bytes and numSamples. Could you once check it at your end...?

**Comment by sriranjanr** [comment]
I created float data pointers and when I read the values I am getting them to be very large float values or zero where as the port audio data values are supposed to be between -1.00 and 1.00 . Could you please provide a sample portaudiomicrophonewrapper.cpp file with code which would give me the right values...Please let me know.

**Comment by mavamazon** [comment]
Please try using int16_t instead of float. Each sample will contain values from -32767 to +32767, then you can scale them to [-1;+1] range. Sorry we could not provide you with the code other than presented in this repository.
