### ISSUE TITLE
Authorization /Registration failed.

### ISSUE THREAD

**Issue by KevSo1993** [alexa/avs-device-sdk#705]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I try to run the SampleApp on a RaspberryPi3. I did every step descriped in the guide for Raspberry. Also create a Security Profile and all the other things. If I start the SampleApp I have to register the device for the first time. Following message occured: 

2018-05-08 19:40:18.928 [  2] 5 CBLAuthDelegate:requestToken
################################################################################################
#       To authorize, browse to: 'https://amazon.com/us/code' and enter the code: DQZDMH       #
################################################################################################

#################################################
#       Checking for authorization (1)...       #
#################################################

2018-05-08 19:40:19.070 [  2] 5 HttpPost:doPostSucceeded:code=400
2018-05-08 19:40:19.070 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-05-08 19:40:19.070 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-05-08 19:40:19.071 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=authorization_pending,errorCode=AUTHORIZATION_PENDING
2018-05-08 19:40:19.071 [  2] 5 CBLAuthDelegate:setAuthError:authError=AUTHORIZATION_PENDING
2018-05-08 19:40:19.071 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=AUTHORIZATION_PENDING
2018-05-08 19:40:24.071 [  2] 5 CBLAuthDelegate:requestToken

So I open the Webexplorer and navigate to "https://amazon.com/us/code". There i have to sign in in my amazon account. After this step i have to enter the given code. With a click on "Continue" i will navigate to the next site were i can press "Allow". After that an Amazon-Error-Website occurs with the following message: 
"We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly. "

All help is welcome! 

PS: i checked the clientId 1millionen times, i cant detect any failure in my configuration.. 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [x ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello KevSo1993,

This error usually indicates that the **productId** value under the **deviceInfo** object in your _AlexaClientSDKConfig.json_ is incorrect.  Please double check that it matches the value titled "_Product ID_" on the "_Product information_" tab of the page for your device.  You can reach this page from the [developer console](https://developer.amazon.com/avs/home.html#/avs/home) by selecting "Manage" on the row for the device you are trying to authorize.

Please let us know if this fixes things for you,

-SWH

**Comment by KevSo1993** [comment]
A lot of thanks, that solved the problem!.

**Comment by kclchan** [comment]
Since the original issue reported by @KevSo1993 has been resolved, I'm closing this issue.  Thanks!
