### ISSUE TITLE
Alexa output keeps running in loops

### ISSUE THREAD

**Issue by sriranjanr** [alexa/avs-device-sdk#706]
I am working with SDK 1.6 and put alexa on raspberry pi. When I ask alexa a questions the output from the speaker keeps looping continuously. What shall I do to prevent this from happening.

**Comment by sriranjanr** [comment]
This does happen when the output speaker is placed close to the microphone.

**Comment by dhpp** [comment]
Since this ticket has not been updated in a while, I will close this out.  If you'd like to continue the discussion, could you please confirm the issue still persists with the current SDK release (1.10), and open a new ticket for us to track, thanks.
