### ISSUE TITLE
How to know the status of intenet connection in avs-device-sdk?

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#707]
Hi,

Is there any mechanism in avs-device-sdk to know the internet connectivity?
Suppose avs-device-sdk is running on machine, and the internet connection is lost on that machine, in this case is there any callback interface mechanism in avs-device-sdk?

Version - 1.7
OS - Ubuntu

Thanks,
Sumit

**Comment by sumit3817** [comment]
Hi Priya,

This network monitoring works only at the first time when application comes up.
But what when the application is already running and internet connection is lost?
Is there any mechanism that application will came to know that internet connection is lost?

Because I tested by disconnecting the network on Ubuntu machine, there are no logs and there is no action performed when the network is lost.

Thanks,
Sumit

**Comment by priyagsenthil** [comment]
Hi sumit3817,

The network monitoring timer kicks off every 5 minutes. Am suspecting you did not wait that long before checking the logs.

When I tried this out locally this is what I see.

2018-05-10 19:37:08.524 [  3] 5 InternetConnectionMonitor:updateConnectionSt    atus:connected=true
263 2018-05-10 19:42:08.546 [  3] 5 InternetConnectionMonitor:updateConnectionSt    atus:connected=false

If you would like the monitoring to kick-in faster adjust the periodicity of the timer which checks the internet connection.

Thanks
Priya
