### ISSUE TITLE
Incorrect playback behavior (stop/resume) from Amazon Music

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#708]
Hi AVS team,
 
We found after SDK1.7, the playback behavior is changed. (compared with previous version and Echo Dot2)

For example, while I say :  play Michael Jackson , it will list the playlist in APP, and play from song 1.
Then, I asked to "stop", then "resume my music", it will play the same song for seconds then switch to next song.
In previous version, although sometimes the progress will be incorrect, but the behavior is fine.(compared with Echo, or Alexa self checklist documents)

Is it a known issue in SDK1.7 ?

Thanks,

**Comment by priyagsenthil** [comment]
Hi zeusshuang,

We tested this on 1.7 and it works as expected on Mac and Ubuntu. Is there a particular platform where you are observing this behavior. Please advise.

Thanks
Priya

**Comment by priyagsenthil** [comment]
Hi zeusshuang,

We tried on raspberry pi as well and don't see this issue. Could you try it again and provide details of your device id and timestamp of the utterance for us to be able to understand this issue better.

Thanks
Priya

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,

Strange, it's really working fine this moment ... but we got same issue in past two days by different site and Amazon account.

is the device id the "serial number" in APP (a long sting in settings page).

**Comment by priyagsenthil** [comment]
Hi zeusshuang,

Yes thats the device-id. If you encounter the issue again please provide the timestamp and utterance with the device-id and we can take a look.

Thanks
Priya

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,

thanks, I will provide the details once I got this case again.

**Comment by zeusshuang** [comment]
Hi @priyagsenthil ,

We did a test today -

On APP, click Music, Video, and Books > Prime Music > 80s R&B Station , play
Listen a song for seconds and click next or thumb down button to play next song.

Let's Groove --> ok
Smooth Operator --> ok
Rhythm Nation ----> fail to start and jump to next song, Hello
Hello --> play okay.

The device SN is :  fbb746635d7f42818a37da024b143c46
Test date UTC :  2018-05-24  08:10 - 8:15:40

I know this test is not the same as previous voice command, but this symptom is the same as voice command to control playback.

**Comment by zeusshuang** [comment]
Hi AVS team.

I update logs and mp4 for the symptom.

Davice SN: 0c3ee1016b4c4acebb1efdc5e4183f44

[case708.zip](https://github.com/alexa/avs-device-sdk/files/2086836/case708.zip)

**Comment by zeusshuang** [comment]
Hi AVS team,

We still got such issues while we run AVS self test cases.
For this case, sometimes, we got another different response while action "pause" and "play".

Alexa, play top pop station from prime.
Alexa, pause.
Alexa, play.
--> sometimes, it say TTS again "Here is a station your might like: XXXXX, from amazon music ".

seems something wrong from the AVS server.
I wonder that while we got such case, will it impact the certification in Amazon Lab? due to it should be not DUT's issue.

**Comment by priyagsenthil** [comment]
Hi zeusshang,

Can you provide the DSN on which you tested and saw this behavior with the timestamp of the utterance. Its's possible Alexa heard differently. Can you look at the utterance history and verify that Alexa infact heard it as pause and play.

Thanks
