### ISSUE TITLE
Cant Install Alexa 

### ISSUE THREAD

**Issue by PavelYarysh** [alexa/avs-device-sdk#717]
After running the following command:
sudo apt-get -y install git gcc cmake build-essential libsqlite3-dev libcurl4-openssl-dev libfaad-dev libsoup2.4-dev libgcrypt20-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-good libasound2-dev doxygen

I received this:

sudo: unable to resolve host mcc
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
gcc is already the newest version.
gcc set to manually installed.
cmake is already the newest version.
The following package was automatically installed and is no longer required:
  libllvm3.7
Use 'apt-get autoremove' to remove it.
The following extra packages will be installed:
  cpp-4.9 curl g++-4.9 gcc-4.9 gcc-4.9-base gir1.2-glib-2.0 gir1.2-soup-2.4 libasan1 libasound2 libasound2-data libatomic1 libclang1-3.5 libcurl3 libelfg0
  libfaad2 libgcc-4.9-dev libgcc1 libgcrypt20 libgirepository-1.0-1 libglib2.0-bin libglib2.0-dev libgomp1 libgpg-error-dev libgstreamer-plugins-bad1.0-0
  libllvm3.5 libobjc-4.9-dev libobjc4 libpcre3-dev libpcrecpp0 libsoup-gnome2.4-1 libsoup2.4-1 libstdc++-4.9-dev libstdc++6 libubsan0 libwayland-cursor0
  libwayland-egl1-mesa libxml2 libxml2-dev
Suggested packages:
  gcc-4.9-locales doxygen-latex doxygen-doc doxygen-gui graphviz gcc-4.9-doc libstdc++6-4.9-dbg libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg
  libasan1-dbg liblsan0-dbg libtsan0-dbg libubsan0-dbg libcilkrts5-dbg libquadmath-dbg gettext-base git-daemon-run git-daemon-sysvinit git-doc git-el
  git-email git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn libasound2-plugins libasound2-doc libcurl4-doc libcurl3-dbg libidn11-dev libkrb5-dev
  libldap2-dev librtmp-dev libssh2-1-dev libssl-dev rng-tools libgcrypt20-doc libglib2.0-doc libsoup2.4-doc sqlite3-doc libstdc++-4.9-doc
The following NEW packages will be installed:
  doxygen gir1.2-glib-2.0 gir1.2-soup-2.4 libasound2-dev libclang1-3.5 libcurl4-openssl-dev libelfg0 libfaad-dev libfaad2 libgcrypt20-dev
  libgirepository-1.0-1 libglib2.0-bin libglib2.0-dev libgpg-error-dev libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-bad1.0-dev libllvm3.5
  libobjc-4.9-dev libobjc4 libpcre3-dev libpcrecpp0 libsoup-gnome2.4-1 libsoup2.4-dev libsqlite3-dev libwayland-cursor0 libwayland-egl1-mesa libxml2-dev
The following packages will be upgraded:
  cpp-4.9 curl g++-4.9 gcc-4.9 gcc-4.9-base git gstreamer1.0-plugins-good libasan1 libasound2 libasound2-data libatomic1 libcurl3 libgcc-4.9-dev libgcc1
  libgcrypt20 libgomp1 libsoup2.4-1 libstdc++-4.9-dev libstdc++6 libubsan0 libxml2
21 upgraded, 27 newly installed, 0 to remove and 319 not upgraded.
Need to get 52.2 MB of archives.
After this operation, 73.9 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libglib2.0-bin libglib2.0-dev
E: There are problems and -y was used without --force-yes

**Comment by priyagsenthil** [comment]
Hi PavelYarysh,

On which platform are you trying to install SDK and which version of the SDK.

WARNING: The following packages cannot be authenticated!
libglib2.0-bin libglib2.0-dev

Except for the above WARNING do not see an error messages. Please advise whats the error.

Thanks
Priya
