### ISSUE TITLE
How to get user profile in SDK 1.7.0

### ISSUE THREAD

**Issue by sugrsugr** [alexa/avs-device-sdk#718]
Hi,
    I want to use Alexa Skill in my device app, but i don't know how to get the user profile.

**Comment by mavamazon** [comment]
Hi!
In order to use skills you have to implement your own server side code and connect to that code from your app. I encourage you to take a look at [Alexa Skill Kit forums](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html).

**Comment by kjkh** [comment]
Closing issue. Feel free to re-open if there are any further questions.
