### ISSUE TITLE
Do you use OPUS CODEC for Echo Dot 2nd?

### ISSUE THREAD

**Issue by tifler** [alexa/avs-device-sdk#720]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

It's not an issue, but a question.

## What is the expected behavior?

I want to know whether you are using the OPUS codec or not.

## What behavior are you observing?

I captured TCP packets from both my device which is based on AVS Device SDK v1.6 and Echo Dot 2nd on the same network environment.
And I analyzed those packets using the Wireshark.

It says that Echo Dot's uploading data size is 3 or 4 times bigger than mine.
Through above, I guess that the Echo Dot 2nd is using OPUS CODEC. (In AIP's source code, you support both LPCM and OPUS.)
Can you confirm it ?

If not, can you explain why this phenomenon occurs.

## Provide the steps to reproduce the issue, if applicable:

1. Start tcpdump on a AP where EchoDot is connected to.
2. Play simple dialog like "Alexa, Good morning"
3. After answering, stop tcpdump and analyze its dump.

### What version of the AVS Device SDK are you using?
      <x.y.z>
1.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [O] Other - tell us more: Generic Linux based, ARMv7 Custom SoC

### Tell us about your OS (Type & version):
- [O] Linux. Build rootfs using Buildroot. Kernel's version is 3.10.x.
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by anu-mathur** [comment]
@tifler The current supported audio codecs and containers are listed here: https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html

Echo Dot does support OPUS, but not sure if that is what is leading to the difference here.

**Comment by tifler** [comment]
@anu-mathur Thanks for your reply.

I think the link you attached might be audio requirements for playback not capture maybe.
You may refer to the site below for capture audio format.
https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#recognize.

In order to show the actual situation, I brought some pics here.

Here are two captured image from the Wireshark. First one is for Echo Dot 2nd, and last one is for mine.
(They were captured by saying "Alexa, Good morning" once at the same time.)

![1-seq-dot-tx](https://user-images.githubusercontent.com/11977012/40151798-f29b975c-59bc-11e8-9903-6916fbb727cb.png)
**[Echo Dot's uploading sequence number pattern]**

In the case of Echo Dot, it sends a few 1360 bytes packets in the beginning of the session, and then sends 437 bytes packets interactively. Total uploaded size is about 48000 bytes.

![1-seq-axela-tx](https://user-images.githubusercontent.com/11977012/40151846-25463036-59bd-11e8-8ee7-e19a49cdd120.png)
**[My device's uploading sequence number pattern]**

I the case of mine, it sends mostly 1360 bytes packets in the whole session, and the sending style is a kind of burst transmission(not interactive). Total uploaded size is about 210000 bytes.

**Is there anyone who can explain the reason why ?**

Thanks for your time.

**Comment by anu-mathur** [comment]
@tifler I see what you are saying. The SDK does not support capture / upload in OPUS yet. And that is why you are seeing the difference. We do have it on our roadmap, and will update on GitHub when we start supporting it.

**Comment by tifler** [comment]
@anu-mathur Thanks for your reply and clarifications. I hope to see your release note for it soon. Have nice day.
