### ISSUE TITLE
SensoryKeywordDetector License expired

### ISSUE THREAD

**Issue by gigawatts** [alexa/avs-device-sdk#724]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When trying to execute the "startsample.sh" script, it starts, gives the "Alexa is idle" message, then shuts down with a "Client not connected" message. Error about SensoryKeyword license expired. How do we update this license?

## What is the expected behavior?
Sample app starts up and starts listening. It previously worked fine the last time I ran it (several months ago)

## What behavior are you observing?
Found this error in the log:

2018-05-16 03:12:28.770 [  1] E SensoryKeywordDetector:initFailed:reason=allocatingNewSessionFailed,error=snsrNew()\: License expired on 28 Feb 2018 00\:00\:00 GMT.
2018-05-16 03:12:28.770 [  1] E SensoryKeywordDetector:createFailed:reason=initDetectorFailed
Failed to create SensoryKeywWordDetector!

## Provide the steps to reproduce the issue, if applicable:
cd to /home/pi/avs-sdk
bash startsample.sh

### What version of the AVS Device SDK are you using?
Raspberry Pi 3, Not sure what SDK version, came from AVS re:invent workshop

### Tell us what hardware you're using:
- [X] Raspberry Pi

### Tell us about your OS (Type & version):
Description:    Raspbian GNU/Linux 9.4 (stretch)

**Comment by mavamazon** [comment]
Hi!
I think you should contact Sensory support regarding the license. Also you may consider Kitt.AI as an alternative. And you may integrate your own wake word engine as well.

**Comment by gigawatts** [comment]
Do you have a link to the Sensory folks git repo? I thought that was the default KWD engine included with this repo.

Do you have an example / tutorial for switching to the KITT.AI engine with this repo's sample project?

**Comment by mavamazon** [comment]
https://github.com/Sensory/alexa-rpi#license
There is also instructions on how to extend your non-commercial license.

To install Kitt.AI please follow the instructions there: https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai

**Comment by gigawatts** [comment]
Thanks! I'll give these a shot tonight.

**Comment by kjkh** [comment]
Hi @gigawatts,

Any progress with this?

**Comment by gigawatts** [comment]
I haven't gotten another chance to play with it. I'm sure its just the old code (from November) not playing nice with updates.

**Comment by kencecka** [comment]
I'm going to go ahead and close this for now.  Please reopen if you are still having problems.

Ken
