### ISSUE TITLE
sqlite undefined reference to `sqlite3_finalize

### ISSUE THREAD

**Issue by xuqifu** [alexa/avs-device-sdk#726]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

dear all:
i install sqlite {path :/home/software/sqlite} aleady
run command in  sdk-build
#cmake  ../sdk-source/avs-device-sdk-master -DSENSORY_KEY_WORD_DETECTOR=OFF -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/sdk-folder/third-party/portaudio/lib/.libs/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/sdk-folder/third-party/portaudio/include -DCMAKE_BUILD_TYPE=DEBUG
#sudo make
print error following:
[ 53%] Linking CXX executable MessageStorageTest
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_bind_int'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_column_int'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_column_int64'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_reset'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_close'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_column_name'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_column_text'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_bind_text'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_prepare_v2'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_errmsg'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_bind_int64'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_open_v2'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_exec'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_step'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_finalize'
../../Storage/SQLiteStorage/src/libSQLiteStorage.so: undefined reference to `sqlite3_column_count'
collect2: error: ld returned 1 exit status
CertifiedSender/test/CMakeFiles/MessageStorageTest.dir/build.make:102: recipe for target 'CertifiedSender/test/MessageStorageTest' failed
make[2]: *** [CertifiedSender/test/MessageStorageTest] Error 1
CMakeFiles/Makefile2:3950: recipe for target 'CertifiedSender/test/CMakeFiles/MessageStorageTest.dir/all' failed
make[1]: *** [CertifiedSender/test/CMakeFiles/MessageStorageTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

i have been modity a part of CMakeCache.txt as follow:
SQLITE_CFLAGS:INTERNAL=/home/software/sqlite/include
SQLITE_CFLAGS_I:INTERNAL=
SQLITE_CFLAGS_OTHER:INTERNAL=
SQLITE_FOUND:INTERNAL=1
SQLITE_INCLUDEDIR:INTERNAL=/home/software/sqlite/include
SQLITE_INCLUDE_DIRS:INTERNAL=
SQLITE_LDFLAGS:INTERNAL=-lsqlite3
SQLITE_LDFLAGS_OTHER:INTERNAL=
SQLITE_LIBDIR:INTERNAL=/home/software/sqlite/lib
SQLITE_LIBRARIES:INTERNAL=sqlite3
SQLITE_LIBRARY_DIRS:INTERNAL=
SQLITE_LIBS:INTERNAL=
SQLITE_LIBS_L:INTERNAL=
SQLITE_LIBS_OTHER:INTERNAL=
SQLITE_LIBS_PATHS:INTERNAL=
SQLITE_PREFIX:INTERNAL=/home/software/sqlite
SQLITE_STATIC_CFLAGS:INTERNAL=/home/software/sqlite/include  //sqlite 的安装路径
SQLITE_STATIC_CFLAGS_I:INTERNAL=
SQLITE_STATIC_CFLAGS_OTHER:INTERNAL=
SQLITE_STATIC_INCLUDE_DIRS:INTERNAL=
SQLITE_STATIC_LDFLAGS:INTERNAL=-lsqlite3;-ldl;-lpthread
SQLITE_STATIC_LDFLAGS_OTHER:INTERNAL=
SQLITE_STATIC_LIBDIR:INTERNAL=
SQLITE_STATIC_LIBRARIES:INTERNAL=sqlite3;dl;pthread
SQLITE_STATIC_LIBRARY_DIRS:INTERNAL=
SQLITE_STATIC_LIBS:INTERNAL=
SQLITE_STATIC_LIBS_L:INTERNAL=
SQLITE_STATIC_LIBS_OTHER:INTERNAL=
SQLITE_STATIC_LIBS_PATHS:INTERNAL=
SQLITE_VERSION:INTERNAL=3.11.0
SQLITE_sqlite3_INCLUDEDIR:INTERNAL=/home/software/sqlite/include
SQLITE_sqlite3_LIBDIR:INTERNAL=
SQLITE_sqlite3_PREFIX:INTERNAL=
SQLITE_sqlite3_VERSION:INTERNAL=
//ADVANCED property for variable: SVNCOMMAND
SVNCOMMAND-ADVANCED:INTERNAL=1
__pkg_config_checked_GST:INTERNAL=1
__pkg_config_checked_SQLITE:INTERNAL=1
prefix_result:INTERNAL=/usr/lib/x86_64-linux-gnu

i don't know how to change the CMakeFile.txt about appoint  the header file and the library file path so system default the sqlite in usr/local , but i install the sqlite in /home/software/sqlite. so i modify the CMakeCache.txt . how to modidy CMakeCache.txt or how to set CMakeFile.txt . hope give me help
thanks
### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ y] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [y ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by xuqifu** [comment]
hi mavamazon 
 Already installed libsqlite3-dev is still not work

**Comment by xuqifu** [comment]
hi @mavamazon 
Already installed libsqlite3-dev is still not work

**Comment by mavamazon** [comment]
Can you confirm that you installed libsqlite3-dev before changing the paths in a generated CMakeCache.txt and it didn't work? It seems that by overriding these you are setting the include/lib paths to the actual software rather then the libsqlite3-dev files.

**Comment by kjkh** [comment]
Hi, 

Is there an update on this?

**Comment by kencecka** [comment]
Hi @xuqifu,

I'm going to go ahead and close this for now.  Please reopen if you are still having trouble.

Ken
