### ISSUE TITLE
CMake error after checking the 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8' package

### ISSUE THREAD

**Issue by mhtahir** [alexa/avs-device-sdk#730]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am trying to make the SampleApp on RPi3 and getting missing pkg error. Here is console output:

## What behavior are you observing?

-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Creating the build directory for the AlexaClientSDK with build type: DEBUG
Creating AlexaClientSDK with keyword detector type: KittAi
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
--   
--   
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  build/cmake/MediaPlayer.cmake:14 (pkg_check_modules)
  build/BuildDefaults.cmake:25 (include)
  CMakeLists.txt:10 (include)

## Provide the steps to reproduce the issue, if applicable:

- Make with Keyword detection engine (Kitt.ai) on. I followed the steps from:
https://github.com/alexa/avs-device-sdk/issues/678

### What version of the AVS Device SDK are you using?
      v1.7.1

The OS version is:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mhtahir** [comment]
Issue resolved, package dependency was missing.

**Comment by seahorseing-around** [comment]
Hi,

I have the same issue, whar dependency was missing?

Thanks!
