### ISSUE TITLE
Windows 10 & Mingw issues

### ISSUE THREAD

**Issue by billskeen68** [alexa/avs-device-sdk#732]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Getting the following error when running bash setup.sh config.txt:

src/hostapi/oss/pa_unix_oss.c:54:10: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:227: src/hostapi/oss/pa_unix_oss.lo] Error 1

## What is the expected behavior?
Compiles without errors

## What behavior are you observing?
The error above

## Provide the steps to reproduce the issue, if applicable:
Windows 10 Pro
Install MSYS2 per instructions ( had to add c:/msys64/mingw64/bin to system path) http://www.msys2.org/

following instruction on this page:
https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script

### What version of the AVS Device SDK are you using?
1.7.x

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
Windows 10 Pro

**Comment by kjkh** [comment]
Hi @billskeen68,

Thanks for reaching out. Can you provide the full logs?

**Comment by billskeen68** [comment]
No idea what I did different this time. I deleted everything and started over again. Worked this time. This "user error" issue can be closed. Thanks

**Comment by kjkh** [comment]
Glad everything is working now! If you run into further issues feel free to re-open.

**Comment by joysl** [comment]
Hi,

**Comment by joysl** [comment]
Please reopen this ticket
I'm facing he same error on a Windows 10 machine
