### ISSUE TITLE
sample app not working due to libcurl-4.dll error

### ISSUE THREAD

**Issue by briyan06** [alexa/avs-device-sdk#733]
When i try to run the sample app an error comes. It says that the libcurl-4.dll is missing from my device.
I'm using a windows 7 pro pc

this is the screenshot of the error.

![capture](https://user-images.githubusercontent.com/39543891/40401536-7e8d84fe-5e64-11e8-9589-8cb33697b2e5.JPG)

**Comment by kjkh** [comment]
Hi @briyan06,

Libcurl is one of the SDK's dependencies. Did you run the installation script following the [Windows Quick Start Guide](https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script)?

Can you also check if libcurl is installed by running `pacman -Ss curl`?

**Comment by briyan06** [comment]
@kjkh Yes kjkh. I ran the installation script following the windows quick start guide. Yup I'll check running
pacman -Ss curl
