### ISSUE TITLE
Recommendation/Request: Port to JavaScript (not TypeScript)

### ISSUE THREAD

**Issue by MasterJames** [alexa/avs-device-sdk#736]
Recommendation/Request: Port to JavaScript (not TypeScript)

**Comment by kjkh** [comment]
Hi @MasterJames,

Thanks for the recommendation. We will create a ticket and track this internally. If there is a strong business need you can also contact us through this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).
