### ISSUE TITLE
How to use AMAZON KEY WORD DETECTOR on avs sdk?

### ISSUE THREAD

**Issue by jie714** [alexa/avs-device-sdk#738]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We saw the WAKE WORD ENGINE has macro define AMAZON_KEY_WORD_DETECTOR,
How to use it, is the key word detect on local device(just like KItt and Sensory)?

### What version of the AVS Device SDK are you using?
<1.7.1>
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:

**Comment by visayamv** [comment]
Hi @jie714 , please fill the [Contact form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and we'll reach out to you to discuss your inquiry

**Comment by jie714** [comment]
Hi @visayamv,

Already fill the Contact form.

Thanks.

Jack

**Comment by htfapps** [comment]
Hello, I'm updating a personal project, and I can't get information about AMAZONLITE_KEY_WORD_DETECTOR or AMAZON_KEY_WORD_DETECTOR.
The link to the form is no longer available.
Can you help me?
Thanks.
