### ISSUE TITLE
CBLAuthDelegate Error

### ISSUE THREAD

**Issue by bill-lzb** [alexa/avs-device-sdk#741]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After running ./SampleApp/src/SampleApp Integration/AlexaClientSDKConfig.json debug9, I got the following errors:
E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Peer certificate cannot be authenticated with given CA certificates
2018-05-28 08:33:43.596 [  2] E CBLAuthDelegate:parseLWAResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.

And the same issue is found at https://github.com/alexa/avs-device-sdk/issues/113, but nobody offers answer.
## What is the expected behavior?

It should show me the url and code to authorize.
## What behavior are you observing?

It output error(above)
## Provide the steps to reproduce the issue, if applicable:

run  ./SampleApp/src/SampleApp Integration/AlexaClientSDKConfig.json debug9
### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @bill-lzb , it seems your issue is the same as this: [SampleApp execute failed for error "Peer certificate cannot be authenticated with given CA certificates](https://github.com/alexa/avs-device-sdk/issues/166). 

Reconfigure and rebuild your curl with the '--with-ca-path=/etc/ssl/certs' option.

example:
./configure --with-ssl=$LOCAL_BUILD --with-nghttp2=$LOCAL_BUILD --prefix=$LOCAL_BUILD --with-ca-path=/etc/ssl/certs

do make , and make install afterwards.

**Comment by bill-lzb** [comment]
Hi @visayamv 

Thank you for you reply.
I tried it, but it did not work.
And I found my root error is:
DeviceInfo:createFailed:reason=missingClientId,key=clientId

My AlexaClientSDKConfig.json is like this:
{
  "deviceInfo":{
    "deviceSerialNumber":"2234567",
    "clientId":"amzn1.application-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "productId":"xxxxxxxxxxxxxx"
  },
  "cblAuthDelegate":{
      "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/cblAuthDelegate.db"
  },
  "miscDatabase":{
      "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/miscDatabase.db"
  },
  "alertsCapabilityAgent":{
      "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/alerts.db"
  },
  "settings":{
      "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/settings.db",
      "defaultAVSClientSettings":{
          "locale":"en-US"
      }
  },
  "certifiedSender":{
     "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/certifiedSender.db"
  },
  "notifications":{
      "databaseFilePath":"/home/root/avs-device-sdk/application-necessities/notifications.db"
  }
}

**Comment by bill-lzb** [comment]
Hi @visayamv 

after building curl with --with-ca-path=/etc/ssl/certs and rebuild avs-device-sdk, it works now.
Thank you!
