### ISSUE TITLE
 UNRECOVERABLE CAPABILITIES API ERROR: FORBIDDEN   

### ISSUE THREAD

**Issue by fedeblock** [alexa/avs-device-sdk#743]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
#       Entering limited interaction mode.                       #
##################################################################
There is some difficult to understand procedure in the RPI instructions, since many people is reporting the same problem and, after following instructions in other threads we keep stucked in the same error.
It seems Client ID, Amazon ID, ProductID, and all other IDs in AVS Products and Security profiles are confusing us all. 

We understood the fields in config.txt are 

DEVICE_SERIAL_NUMBER="whatever # you like while it´s unique for the device"
CLIENT_ID= Apps & Services ->Security Profile Management ->General->Client ID
PRODUCT_ID= Alexa Voice Service ->My Products->ProductID

But...  those values are not working.
We deleted ~/db/cblAuthDelegate.db and reauthorized the device a couple of times and it´s not working.

## What is the expected behavior?
A proper install of AVS-Device-SDK in a clean installed raspberry pi

## What behavior are you observing?

> 2018-05-28 16:17:36.940 [  2] 5 HttpPost:doPostSucceeded:code=400
> 2018-05-28 16:17:36.940 [  2] 5 CBLAuthDelegate:receiveTokenResponse:code=400
> 2018-05-28 16:17:36.940 [  2] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
> 2018-05-28 16:17:36.941 [  2] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
> 2018-05-28 16:17:36.941 [  2] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
> 2018-05-28 16:17:36.941 [  2] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
> 2018-05-28 16:17:36.941 [  2] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
> 2018-05-28 16:17:36.941 [  2] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST
> ##################################################################
> #       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
> #       Entering limited interaction mode.                       #
> ##################################################################
> 
> 2018-05-28 16:17:36.942 [  9] E CapabilitiesDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
> 2018-05-28 16:17:36.942 [  9] E CapabilitiesDelegate:publishCapabilitiesFailed:reason=getAuthTokenFailed
> 
> ....

> 2018-05-28 16:17:36.942 [  9] 5 CapabilitiesDelegate:setCapabilitiesState:newCapabilitiesState=FATAL_ERROR
> 2018-05-28 16:17:36.943 [  9] 9 CapabilitiesDelegate:callingOnCapabilitiesStateChange:state=FATAL_ERROR,error=FORBIDDEN
> 2018-05-28 16:17:36.944 [  9] E 

> CapabilitiesDelegate:capabilitiesPublishFailed:reason=unableToPublishCapabilities
> ###############################################################
> #       UNRECOVERABLE CAPABILITIES API ERROR: FORBIDDEN       #
> #       Entering limited interaction mode.                    #
> ###############################################################
> 
> 2018-05-28 16:17:36.942 [  2] 5 CBLAuthDelegate:handleStopping

## Tell us about your environment:

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
Linux version 4.14.34-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1110 SMP Mon Apr 16 15:18:51 BST 2018

### What version of the AVS Device SDK are you using?
 SDK Version 1.7.1

### Tell us what hardware you're using:

Raspberry Pi

### Tell us about your OS (Type & version):

 Raspbian Stretch

**Comment by visayamv** [comment]
Hi @fedeblock , to properly authorize your device using CBL, for the CLIENT_ID, you have to use the client ID found in  "Alexa Dashboard" > "My products" > "manage" > "Security Profiles" > "Other devices and platforms".

Please refer to this document for more information: https://github.com/alexa/avs-device-sdk/wiki/Code-Based-Linking----Configuration-Update-Guide

**Comment by fedeblock** [comment]
Found it!
It´s not actually from Alexa Dashboard but from Developer Console -> Alexa Voice Service -> My Products -> Manage ->Details and Management / Security Profile -> Other Devices and Platforms

or

[https://developer.amazon.com/avs/home.html#/avs/products/edit/RPIMindgeist/securityProfile/](https://developer.amazon.com/avs/home.html#/avs/products/edit/RPIMindgeist/securityProfile/
)

![image](https://user-images.githubusercontent.com/2471090/40653903-e38e34e8-633c-11e8-97b9-81e0b1590af4.png)

Must test before closing the thread, but i'm pretty sure it must work.

**Comment by visayamv** [comment]
Thanks @fedeblock , let me know if it worked

**Comment by fedeblock** [comment]
Solved!
