### ISSUE TITLE
Cross compiling using Visual Studio 2017 missing curl error

### ISSUE THREAD

**Issue by billskeen68** [alexa/avs-device-sdk#749]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I know that Visual Studio is not currently supported and in issue #147 this was asked and answered. This is not a bug but a request.

## What is the expected behavior?
Compile using Visual Studio 2017. I am able to build and run sample app on Windows 10 using Windows Quick Start Guide, which uses MinGW64. It would be nice to use all the features of VS2017.

## What behavior are you observing?
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY) (found suitable version
  "7.59.0", minimum required is "7.43.0")
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindCURL.cmake:48 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  AVSCommon/CMakeLists.txt:3 (find_package)

## Provide the steps to reproduce the issue, if applicable:
Open Visual Studio
Click File/Open/CMAKE and select CMakeLists.txt in avs-sdk root folder.

## Tell us about your environment:
Windows 10 Pro
Visual Studio Community Edition
Tried several flavors of curl including 7.54.0, 7.59.0 and a few other custom windows versions.

### What version of the AVS Device SDK are you using?
      1.7.1

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [X] Other - tell us more: Windows 10 Pro

**Comment by visayamv** [comment]
Hi @billskeen68 , I submitted your request for internal review.

**Comment by billskeen68** [comment]
Thank you.

**Comment by kencecka** [comment]
Hi @billskeen68,

We've added this issue to our backlog.  I'm going to go ahead and close the github issue.  Please reopen if you have further suggestions.

Ken
