### ISSUE TITLE
Limited Mode

### ISSUE THREAD

**Issue by judy0501** [alexa/avs-device-sdk#751]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I run the sample app, it keeps going into limited mode.
I already registered the device with the given code from previous run.

#################################################
#       NOTIFICATION INDICATOR STATE: OFF       #
#################################################

2018-06-01 07:53:11.056 [ 26] 5 TemplateRuntime:addObserverInExecutor
2018-06-01 07:53:11.528 [  1] 5 CBLAuthDelegate:addAuthObserver:observer=0xd5101f0
2018-06-01 07:53:11.529 [  1] 5 CapabilitiesDelegate:addCapabilitiesObserver:observer=0xd5101f8
2018-06-01 07:53:11.529 [  1] 5 CapabilitiesDelegate:addCapabilitiesObserver:observer=0x9b38c40
                  #    #     #  #####      #####  ######  #    #
                 # #   #     # #     #    #     # #     # #   #
                #   #  #     # #          #       #     # #  #
               #     # #     #  #####      #####  #     # ###
               #######  #   #        #          # #     # #  #
               #     #   # #   #     #    #     # #     # #   #
               #     #    #     #####      #####  ######  #    #

       #####                                           #
      #     #   ##   #    # #####  #      ######      # #   #####  #####
      #        #  #  ##  ## #    # #      #          #   #  #    # #    #
       #####  #    # # ## # #    # #      #####     #     # #    # #    #
            # ###### #    # #####  #      #         ####### #####  #####
      #     # #    # #    # #      #      #         #     # #      #
       #####  #    # #    # #      ###### ######    #     # #      #

       SDK Version 1.7.1

+----------------------------------------------------------------------------+
|                                  Options:                                  |
| Tap to talk:                                                               |
|       Press 't' and Enter followed by your query (no need for the 'Alexa').|
| Hold to talk:                                                              |
|       Press 'h' followed by Enter to simulate holding a button.            |
|       Then say your query (no need for the 'Alexa').                       |
|       Press 'h' followed by Enter to simulate releasing a button.          |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Playback Controls:                                                         |
|       Press '1' for a 'PLAY' button press.                                 |
|       Press '2' for a 'PAUSE' button press.                                |
|       Press '3' for a 'NEXT' button press.                                 |
|       Press '4' for a 'PREVIOUS' button press.                             |
| Settings:                                                                  |
|       Press 'c' followed by Enter at any time to see the settings screen.  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Firmware Version:                                                          |
|       Press 'f' followed by Enter at any time to report a different        |
|       firmware version.                                                    |
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

2018-06-01 07:53:11.552 [  c] 0 InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-06-01 07:53:11.553 [  c] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true
2018-06-01 07:53:11.553 [  c] 5 InternetConnectionMonitor:notifyObserversLocked
2018-06-01 07:53:12.746 [  9] 5 HttpPost:doPostSucceeded:code=400
2018-06-01 07:53:12.747 [  9] 5 CBLAuthDelegate:receiveTokenResponse:code=400
2018-06-01 07:53:12.750 [  9] 5 CBLAuthDelegate:mapHTTPStatusToError:code=400,error=INVALID_REQUEST
2018-06-01 07:53:12.752 [  9] 5 CBLAuthDelegate:errorInLwaResponseBody:error=invalid_request,errorCode=INVALID_REQUEST
2018-06-01 07:53:12.754 [  9] 5 CBLAuthDelegate:setAuthError:authError=INVALID_REQUEST
2018-06-01 07:53:12.758 [  9] 0 CBLAuthDelegate:receiveTokenResponseFailed:result=INVALID_REQUEST
2018-06-01 07:53:12.760 [  9] 5 CBLAuthDelegate:setAuthState:newAuthState=UNRECOVERABLE_ERROR
2018-06-01 07:53:12.763 [  9] 9 CBLAuthDelegate:callingOnAuthStateChange:state=UNRECOVERABLE_ERROR,error=INVALID_REQUEST
2018-06-01 07:53:12.767 [  9] 5 CBLAuthDelegate:handleStopping
2018-06-01 07:53:12.767 [  a] E CapabilitiesDelegate:getAuthTokenFailed:reason=Unrecoverable error by auth delegate
##################################################################
#       UNRECOVERABLE AUTHORIZATION ERROR: INVALID_REQUEST       #
#       Entering limited interaction mode.                       #
##################################################################

2018-06-01 07:53:12.772 [  a] E CapabilitiesDelegate:publishCapabilitiesFailed:reason=getAuthTokenFailed
+----------------------------------------------------------------------------+
|                          In Limited Mode:                                  |
+----------------------------------------------------------------------------+
| Status : Unrecoverable authorization failure.                              |
+----------------------------------------------------------------------------+
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

2018-06-01 07:53:12.781 [  a] 5 CapabilitiesDelegate:setCapabilitiesState:newCapabilitiesState=FATAL_ERROR
2018-06-01 07:53:12.791 [  a] 9 CapabilitiesDelegate:callingOnCapabilitiesStateChange:state=FATAL_ERROR,error=FORBIDDEN
2018-06-01 07:53:12.793 [  a] E CapabilitiesDelegate:capabilitiesPublishFailed:reason=unableToPublishCapabilities
###############################################################
#       UNRECOVERABLE CAPABILITIES API ERROR: FORBIDDEN       #
#       Entering limited interaction mode.                    #
###############################################################

+----------------------------------------------------------------------------+
|                          In Limited Mode:                                  |
+----------------------------------------------------------------------------+
| Status : Unrecoverable Capabilities API call failure.                      |
+----------------------------------------------------------------------------+
| Info:                                                                      |
|       Press 'i' followed by Enter at any time to see the help screen.      |
| Stop an interaction:                                                       |
|       Press 's' and Enter to stop an ongoing interaction.                  |
| Speaker Control:                                                           |
|       Press 'p' followed by Enter at any time to adjust speaker settings.  |
| Reset device:                                                              |
|       Press 'k' followed by Enter at any time to reset your device. This   |
|       will erase any data stored in the device and you will have to        |
|       re-register your device.                                             |
|       This option will also exit the application.                          |
| Quit:                                                                      |
|       Press 'q' followed by Enter at any time to quit the application.     |
+----------------------------------------------------------------------------+

2018-06-01 07:58:11.557 [  c] 5 InternetConnectionMonitor:testConnection
2018-06-01 07:58:12.142 [  c] 0 InProcessAttachmentReader:readFailed:reason=SDS is closed
2018-06-01 07:58:12.153 [  c] 5 InternetConnectionMonitor:updateConnectionStatus:connected=true

###########################
#       Authorized!       #
###########################
########################################
#       Alexa is currently idle!       #
########################################

### What version of the AVS Device SDK are you using?
      <x.y.z>
AlexaClientSDK  1.7.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Other - tell us more: Windows

**Comment by visayamv** [comment]
Hi @judy0501 , can you make sure that the CLIENT ID in your config json is taken from  Developer Console -> Alexa Voice Service -> My Products -> Manage ->Details and Management / Security Profile -> Other Devices and Platforms?

Please refer to this document for more information: https://github.com/alexa/avs-device-sdk/wiki/Code-Based-Linking----Configuration-Update-Guide

**Comment by judy0501** [comment]
Hi @visayamv, it works! Thank you.

**Comment by Maradox-D-Krypt** [comment]
@visayamv and where would i find this config json  file?
