### ISSUE TITLE
Alexa does not start on boot

### ISSUE THREAD

**Issue by NicoSoftware** [alexa/avs-device-sdk#753]
So the AVS-Device-SDK is running on my pi for about 2 months now.
I've modified the UserInputManager.cpp with this command:
```
    std::this_thread::sleep_for(std::chrono::hours(1));
```
Because the AVS stopped after about 1 hour.
The only thing that bothers me still, ist that it doesn't start on boot.
Is there away to make it executable on system startup? (Raspbian stretch)

**Comment by visayamv** [comment]
@NicoSoftware , the link @khassel gave can help you make it boot at startup.

**Comment by NicoSoftware** [comment]
Yeah I did every step and recompiled with:
´´´
sudo bash setup.sh config.txt
´´´
Now nothing works anymore.

**Comment by visayamv** [comment]
@NicoSoftware , paste the output of:
sudo bash -x startsample.sh

**Comment by NicoSoftware** [comment]
pi@raspberrypi:~ $ cd Desktop
pi@raspberrypi:~/Desktop $ sudo bash -x startsample.sh
+ cd /home/pi/Desktop/build/SampleApp/src
+ ./SampleApp /home/pi/Desktop/build/Integration/AlexaClientSDKConfig.json /home              /pi/Desktop/third-party/alexa-rpi/models DEBUG9
pi@raspberrypi:~/Desktop $

**Comment by visayamv** [comment]
@NicoSoftware , is your modification only adding the sleep on the UserInputManager.cpp? after yourrecompile and run the startsample.sh, the app does not show any logs and it just exits? is that correct?

**Comment by NicoSoftware** [comment]
Yes!
And of course alexa.sh but only to make it runnable with the autostart, but that doesnt have anything to do with the SampleApp

**Comment by visayamv** [comment]
Things to try:
1. Make sure that no other SampleApp is running. 
ps -ef | grep SampleApp
2. Revert back your change on UserInputManager.cpp, compile (and get the logs during compliation) and then check if the SampleApp will run again successfully.

**Comment by visayamv** [comment]
With the original code and SampleApp running, post the output of sudo bash -x alexa.sh

**Comment by NicoSoftware** [comment]
I have to say my SampleApp was about 3 months old, some parts of the repo changed, maybe thats the problem.
Yeah I'll try :)

**Comment by NicoSoftware** [comment]
I've reinstalled raspbian and installed it all over again but I get other Errors now:
https://github.com/alexa/avs-device-sdk/issues/759
