### ISSUE TITLE
Install script is saying system is not supported

### ISSUE THREAD

**Issue by sharkwheels** [alexa/avs-device-sdk#755]
Hello. I'm trying to install AVS on a raspberry pi 3 with Stretch installed (desktop version), and the install script is giving me this error: 

`The installation script doesn't support current system. (System: Linux sliceofpi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux)`

Not sure where to go from here, wanted to see if others have run into the same issue. 

Thanks.

**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Provided install script will not install claiming that stretch isn't suppored

## What is the expected behavior?
that the install script will install

## Provide the steps to reproduce the issue, if applicable:
ran sudo bash setup.sh config.txt

## Tell us about your environment:
Using an up to date install of raspian stretch. Using latest version of AVS as provided in Quick Start for Raspberry Pi on this github

### Tell us what hardware you're using:
- [x ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ x] Raspbian Stretch

**Comment by kencecka** [comment]
Hi @sharkwheels,

It looks like you have changed the name of your device from "pi" to "sliceofpi".  There is a known issue (see #558) with the script failing to recognize devices which have nonstandard names.  As a workaround, you could edit tools/Install/setup.h locally to always set PLATFORM="pi".

Ken

**Comment by sharkwheels** [comment]
Yup that worked. Thank you!

**Comment by scotthea-amazon** [comment]
Hello sharkwheels,

It appears that this issue has been resolved, so I am closing it.  If it has been closed in error, feel free to re-open it.

Best regards,
-SWH

**Comment by Virgil10** [comment]
I guess I’m a newb, how do you edit tools/Install/setup.h locally to always set PLATFORM="pi".?

Where is setup.h at? I can’t find it on my pi.

**Comment by noamalffasy** [comment]
@Virgil10 In case you haven't solved it or if anyone finds this issue and needs help:
He had a typo, he meant editing tools/Install/setup.sh.
If you downloaded only the setup.sh then edit it directly.

You need to go to the function `get_platform()` and change `if [[ "$uname_str" == "Linux raspberrypi"* ]]` to `if [[ "$uname_str" == "Linux <your device name>"* ]]`.

Hope it helped!

**Comment by zexeny** [comment]
> 
> 
> @Virgil10 In case you haven't solved it or if anyone finds this issue and needs help:
> He had a typo, he meant editing tools/Install/setup.sh.
> If you downloaded only the setup.sh then edit it directly.
> 
> You need to go to the function `get_platform()` and change
> 
> ```shell
> if [[ "$uname_str" == "Linux raspberrypi"* ]]
> ```
> 
> to
> 
> ```shell
> if [[ "$uname_str" == "Linux <your device name>"* ]]
> ```
> 
> Hope it helped!

that doesn't work for me but i found another way which was what @kencecka was talking about.
so open your setup.sh file and look for `PLATFORM=${PLATFORM:-$(get_platform)}`. 
I didn't want to modify the file directly so under `PLATFORM=${PLATFORM:-$(get_platform)}` I wrote `PLATFORM=Raspberry pi`. 

Like this when the script goes to:
`if [ "$PLATFORM" == "Raspberry pi" ]
then
  source pi.sh`
this condition will always be true. 

Might sound stupid but some people aren't that good at programming or never learned to code. 

ps: i'm a bit of a newb myself so I can't garantee it will work.
