### ISSUE TITLE
converting to ‘const std::unordered_set<std::basic_string<char> >’from initializer

### ISSUE THREAD

**Issue by SEUNGWOOWOO** [alexa/avs-device-sdk#758]
Hi,

IS same issue #697  and #698 

My development environment is like this.
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Linux tako2-si 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Is it difficult to fix the problem in my environment?

I have upgraded my app to SDK V1.7.1, but got an error below when building the SDK:

[ 46%] Building CXX object BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/BlueZAVRCPTarget.cpp.o
[ 46%] Building CXX object BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/BlueZBluetoothDevice.cpp.o
/home/king/Project/DB20_Linux/AVS/alexa-client-sdk_v1.7.1_Temp/avs-device-sdk-master/BluetoothImplementations/BlueZ/src/BlueZBluetoothDevice.cpp: In member function 'std::unordered_set<std::basic_string<char> > alexaClientSDK::bluetoothImplementations::blueZ::BlueZBluetoothDevice::getServiceUuids()':
/home/king/Project/DB20_Linux/AVS/alexa-client-sdk_v1.7.1_Temp/avs-device-sdk-master/BluetoothImplementations/BlueZ/src/BlueZBluetoothDevice.cpp:305:17: error: converting to 'std::unordered_set<std::basic_string<char> >' from initializer list would use explicit constructor 'std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]'
         return {};
                 ^
/home/king/Project/DB20_Linux/AVS/alexa-client-sdk_v1.7.1_Temp/avs-device-sdk-master/BluetoothImplementations/BlueZ/src/BlueZBluetoothDevice.cpp:314:17: error: converting to 'std::unordered_set<std::basic_string<char> >' from initializer list would use explicit constructor 'std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = std::basic_string<char>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]'
         return {};
                 ^
make[2]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/BlueZBluetoothDevice.cpp.o] Error 1
make[1]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/all] Error 2
make: *** [all] Error 2

I modified the “return {};” to "return uuids;" in BlueZBluetoothDevice.cpp, but don't know if it is right, please advise.

**Comment by SEUNGWOOWOO** [comment]
IS same ISSUE #1033

My development environment is like this.
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Linux tako2-si 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Is it difficult to fix the problem in my environment?

**Comment by kencecka** [comment]
Hi @SEUNGWOOWOO,

This looks like a compiler compatibility issue.  The minimum required gcc version for the SDK is 4.8.5, but it looks like you are trying to build with 4.8.4.  This specific compile error can be fixed by changing `return {};` to `return std::unordered_set<std::string>();`.

Ken

**Comment by SEUNGWOOWOO** [comment]
Hi @kencecka 

I did not tell you well

My sdk build is

axela-builder/uroad/output/build/avsbuild/BluetoothImplementations/BlueZ/src && /home/du5102/Alexa_source/axela-builder/uroad/output/host/bin/arm-buildroot-linux-gnueabihf-g++

arm-buildroot-linux-gnueabihf-g++.br_real (Buildroot 2017.11.2-00001-g818eddd) 4.9.4

It is not an ubuntu base, but an arm base.
Can I ask for confirmation again?
Do you have a compiler recommended by arm base?

Thanks you

**Comment by kencecka** [comment]
Hi @SEUNGWOOWOO,

Irrespective of platform, the minimum gcc release we are targeting is 4.8.5.  It sounds like you are still seeing this error with your 4.9.4 compiler, so I will file a ticket internally to adjust the code as I have described above.  In the mean time, if you make the change I suggested above, you should be able to compile.

Ken

**Comment by SEUNGWOOWOO** [comment]
Thanks you @kencecka 

Thank you very much for your help.

I still seeing this error with your 4.9.4 compiler(not change source)


I change " return {}; to return std::unordered_set<std::string>();." it should be able to complile

It is ok

However, I am wondering about the version of gcc that is normally build without modifications in arm-base

If there is a version that has been tested, can it be shared?

**Comment by kencecka** [comment]
Hi @SEUNGWOOWOO,

We regularly test builds against the  gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf toolchain for raspberry pi.

Ken

**Comment by kjkh** [comment]
This has been fixed in 1.9. Closing ticket, please re-open if there are further questions.
