### ISSUE TITLE
Question about timer/alarm setup

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#762]
Hi AVS team,

SDK 1.7.1

Not sure if I can raise a question here, this issue is the same on SDK and Echo Dot.
I tried to setup a timer by ,  Alexa, set a sleep timer for 2 minutes.
It will respond :  sleep timer for 2 minutes, starting now.  
From the response, it seems the setup is okay and started.
But on APP, there is no timer show up, also no response while time is up.

I check the use case, it should be correct to give a name for a timer, did I issue wrong command ?

**Comment by kencecka** [comment]
Hi @zeusshuang,

I have reproduced this issue as well, and am investigating.  I'll post an update here when I have more information.

Ken

**Comment by kencecka** [comment]
Hi @zeusshuang,

I followed up with the timers and alarms team and learned that a "sleep" timer is a special type of timer which turns off your music.  You will not receive a response when it expires; the intention is for it to quietly turn off music after the specified amount of time.

Ken
