### ISSUE TITLE
Broken packages during installation

### ISSUE THREAD

**Issue by tiancaipipi110** [alexa/avs-device-sdk#763]
During set up through Raspi console, after I typed 
`sudo bash setup.sh config.txt`
and 'AGREE',
It then showed up an error of 'unmet dependencies....libpeas-1.0-0...python3-gi-cairo...girl.2-peas-1.0.........etc........E: Unable to correct problems, you have held broken packages'

Can anyone provide some insight on this please?

Hardware: laptop+Raspberry Pi
OS: Noobs Raspbian

**Comment by kencecka** [comment]
Hi @tiancaipipi110,

It sounds like you package database has some problems.  As a starting point, you might try running `sudo apt-get update` and/or `sudo apt-get autoremove` and see if that resolves the issue or gives more useful error messages.  If you are still stuck, you might consider a fresh install of raspbian (erase your SD card and reimage it).

Ken

**Comment by tiancaipipi110** [comment]
@kencecka 
I tried with  `sudo apt-get autoremove` , then `sudo bash setup.sh config.txt`, still get the same error. 
Then I erased the SD card reimaged it with Raspbian(Noobs), still get the same error.
