### ISSUE TITLE
avs sdk error on Android platform

### ISSUE THREAD

**Issue by mmabluesky** [alexa/avs-device-sdk#766]
I have compiled the avs library for the Android platform ，but without an official guide, I walk hard every step .  
Through my efforts,   sampleAPP can successfully compile and run on Android studio, but each log shows "CBLAuthDelegate:getRefreshTokenFailed",  I'll attach a complete log, I need any help from you, Thanks.  
By the way, a month ago I had filled out a form, but the official never contacted me and helped me solve avs  on Android. I was very very disappointed.

### What version of the AVS Device SDK are you using?
      <1.7.1>

### Tell us what hardware you're using:
- [ ] Other - android phone:

### Tell us about your OS (Type & version):
-Android 7.1

----------------------------------------------------------------------------
appendix：
（Log）
CBLAuthDelegate:handleStarting
SQLiteCBLAuthDelegateStorage:getRefreshToken
SQLiteCBLAuthDelegateStorage:getRefreshTokenFailed:reason=stepResultWasNotRow
    CBLAuthDelegate:getRefreshTokenFailed
    CBLAuthDelegate:handleRequestingCodePair
    CBLAuthDelegate:requestCodePair
CapabilitiesDelegate:CapabilitiesDelegateInit:reason=missingCapabilitiesDelegateConfigurationValue,key=capabilitiesDelegate
CBLAuthDelegate:addAuthObserver:observer=0xeb46ac84
CBLAuthDelegate:addAuthObserver:observer=0xeb47b250
    CapabilitiesDelegate:addCapabilitiesObserver:observer=0xeb47b254
 InternetConnectionMonitor:startMonitoring
InternetConnectionMonitor:testConnection
    LibCurlHttpContentFetcher:getContentFailed:reason=enableLibCurlCookieEngineFailed
    InternetConnectionMonitor:testConnectionFailed:reason=nullHTTPContentReceived
    InternetConnectionMonitor:updateConnectionStatus:connected=false
SpeechSynthesizer:addObserver:observer=0xcfd11e14
PlaybackRouter:create::called
AlertScheduler:setTimerForNextAlertLocked
    AlertScheduler:executeScheduleNextAlertForRendering::no work to do.
AlertsCapabilityAgent:executeOnConnectionStatusChanged:status=DISCONNECTED,reason=ACL_CLIENT_REQUEST
NotificationsRenderer:create
NotificationsCapabilityAgent:init
    NotificationsRenderer:addObserver
NotificationsCapabilityAgent:executeInit
    NotificationsCapabilityAgent:notifyObservers:indicatorState=0
    NotificationsCapabilityAgent:executeProvideState:sendToken=false,stateRequestToken=0
ContextManager:updateStateLocked:action=updatedState,namespace=Notifications,name=IndicatorState
SpeakerManager:mapCreated:numAvsSynced=5,numLocal=1
SpeakerManager:validateSpeakerSettingsConsistencyResult:consistent=true
    SpeakerManager:validateSpeakerSettings:volume=100,mute=false
    SpeakerManager:updateContextManagerCalled:speakerType=AVS_SYNCED
 ExternalMediaPlayer:createAdapters
AudioPlayer:addObserver
TemplateRuntime:onDialogUXStateChanged:state=IDLE
DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechSynthesizer,name=Speak,handler=0xeb46adc0,policy=BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=ClearQueue,handler=0xeb44e600,policy=NON_BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Stop,handler=0xeb44e600,policy=NON_BLOCKING
 DirectiveRouter:addDirectiveHandlers:action=added,namespace=AudioPlayer,name=Play,handler=0xeb44e600,policy=NON_BLOCKING
  DirectiveRouter:addDirectiveHandlers:action=added,namespace=ExternalMediaPlayer,name=Login,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=ExternalMediaPlayer,name=Logout,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=ExternalMediaPlayer,name=Play,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaylistController,name=DisableRepeat,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=Play,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=StartOver,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=Previous,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=Pause,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.SeekController,name=AdjustSeekPosition,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=Rewind,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=Next,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaylistController,name=DisableShuffle,handler=0xeb423cc0,policy=NON_BLOCKING
DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaybackController,name=FastForward,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaylistController,name=EnableRepeatOne,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaylistController,name=EnableRepeat,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.PlaylistController,name=EnableShuffle,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.SeekController,name=SetSeekPosition,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.FavoritesController,name=Favorite,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alexa.FavoritesController,name=Unfavorite,handler=0xeb423cc0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=ExpectSpeech,handler=0xcfaba1c0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=SpeechRecognizer,name=StopCapture,handler=0xcfaba1c0,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=DeleteAlert,handler=0xeb46af00,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Alerts,name=SetAlert,handler=0xeb46af00,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=SetEndpoint,handler=0xeb426d20,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=System,name=ResetUserInactivity,handler=0xeb43f964,policy=NON_BLOCKING
 DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetMute,handler=0xeb423c00,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=AdjustVolume,handler=0xeb423c00,policy=NON_BLOCKING
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Speaker,name=SetVolume,handler=0xeb423c00,policy=NON_BLOCKING
    TemplateRuntime:getConfiguration
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderPlayerInfo,handler=0xeb46b180,policy=HANDLE_IMMEDIATELY
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=TemplateRuntime,name=RenderTemplate,handler=0xeb46b180,policy=HANDLE_IMMEDIATELY
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Notifications,name=ClearIndicator,handler=0xcfa83384,policy=HANDLE_IMMEDIATELY
    DirectiveRouter:addDirectiveHandlers:action=added,namespace=Notifications,name=SetIndicator,handler=0xcfa83384,policy=HANDLE_IMMEDIATELY
SpeakerManager:addSpeakerManagerObserverCalled
    SpeakerManager:addSpeakerManagerObserver:observer=0xeb47b260
    NotificationsCapabilityAgent:addObserver
TemplateRuntime:addObserver
TemplateRuntime:addObserverInExecutor
#################################################
    #       NOTIFICATION INDICATOR STATE: OFF       #
    #################################################
CBLAuthDelegate:addAuthObserver:observer=0xeb41d490
    CapabilitiesDelegate:addCapabilitiesObserver:observer=0xeb41d494
    CapabilitiesDelegate:addCapabilitiesObserver:observer=0xcfafc900
   #    #     #  #####      #####  ######  #    #              
                     # #   #     # #     #    #     # #     # #   #               
                    #   #  #     # #          #       #     # #  #                
                   #     # #     #  #####      #####  #     # ###                 
                   #######  #   #        #          # #     # #  #                
                   #     #   # #   #     #    #     # #     # #   #               
                   #     #    #     #####      #####  ######  #    #              
                                                                                  
           #####                                           #                      
          #     #   ##   #    # #####  #      ######      # #   #####  #####      
          #        #  #  ##  ## #    # #      #          #   #  #    # #    #     
           #####  #    # # ## # #    # #      #####     #     # #    # #    #     
                # ###### #    # #####  #      #         ####### #####  #####   
    +----------------------------------------------------------------------------+
    |                                  Options:                                  |
    | Tap to talk:                                                               |
    |       Press 't' and Enter followed by your query (no need for the 'Alexa').|
    | Hold to talk:                                                              |
    |       Press 'h' followed by Enter to simulate holding a button.            |
    |       Then say your query (no need for the 'Alexa').                       |
    |       Press 'h' followed by Enter to simulate releasing a button.          |
    | Stop an interaction:                                                       |
    |       Press 's' and Enter to stop an ongoing interaction.                  |
    | Playback Controls:                                                         |
    |       Press '1' for a 'PLAY' button press.                                 |
    |       Press '2' for a 'PAUSE' button press.                              
HttpPost:doPostFailed:reason=curl_easy_performFailed,result=28,error=Error
    CBLAuthDelegate:receiveCodePairResponse:code=0
    CBLAuthDelegate:mapHTTPStatusToError:code=0,error=UNKNOWN_ERROR
    CBLAuthDelegate:parseLWAResponseFailed:reason=parseJsonFailed,position=0,error=The document is empty.
    CBLAuthDelegate:setAuthError:authError=UNKNOWN_ERROR
    CBLAuthDelegate:receiveCodePairResponseFailed:result=UNKNOWN_ERROR
CBLAuthDelegate:requestCodePair
...

**Comment by kencecka** [comment]
Hi @mmabluesky,

I'm sorry to hear that you were not contacted.  I am checking into it and will get back to you.  Android support is still preliminary, and we have not released a guide for it yet on github.

Regarding your refresh token failures, could you repost your full log with the header information included (timestamps, thread IDs and error levels)?  Sometimes there is an error earlier in the log which explains the subsequent failures, but it's difficult to spot when the error levels are not included.

Ken

**Comment by mmabluesky** [comment]
hi,  @kencecka 

I am very happy to receive your reply. I hope you can contact me and give me some suggestions on the Android platform. The appendix is all prints that I can see. The log print of the Android platform is not the same as other platforms. I have no way to do the rating display, but I set DEBUG9 on the parameters. In theory, we can see all the information. of.

Looking forward to your reply, I hope you can contact me this time. My email address is yuanxuya@Outlook.com. Thank you.

Xuya

**Comment by mmabluesky** [comment]
hi, @kencecka

I am very glad to receive your reply. I hope you can contact me and give me some suggestions on the Android platform. The appendix is all prints that I can see. The log print of the Android platform is not the same as other platforms. I have no way to do the rating display, but I set DEBUG9 on the parameters. In theory, we can see all the information. of.

Looking forward to your reply, I hope you can contact me this time. My email address is yuanxuya@Outlook.com. Thank you.

Xuya

**Comment by kencecka** [comment]
Thanks - we'll be in touch with you directly.

**Comment by mmabluesky** [comment]
@kencecka 
Sorry, I haven't received your contact so far. 
Can you tell me when you will give me some advice on Android?

**Comment by scotthea-amazon** [comment]
Hello mmabluesky,

I see in the log you provided the message:
```
HttpPost:doPostFailed:reason=curl_easy_performFailed,result=28,error=Error
```
Per [libcurl-errors doc](https://curl.haxx.se/libcurl/c/libcurl-errors.html), a result of 28 indicates that a timeout has occurred.  Have you verified that your device or emulator has a viable internet connection?

Thanks,
-SWH

**Comment by mmabluesky** [comment]
@celinval     Thank you , I will try

**Comment by mmabluesky** [comment]
hi, @celinval 
Now always reported such an error  "HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Error" ，

**Comment by mmabluesky** [comment]
@scotthea-amazon  ，
now ，error code is 60  ,    what should I do

**Comment by mmabluesky** [comment]
[图片]

**Comment by mmabluesky** [comment]
![2lab s769_ft 9f6lq0d](https://user-images.githubusercontent.com/17948377/41332515-c370c024-6f10-11e8-958f-1636b9516c87.png)

**Comment by mmabluesky** [comment]
![xrw q uzj7qg4 84f lcdy](https://user-images.githubusercontent.com/17948377/41332575-f965771a-6f10-11e8-92cb-7c38af600515.png)

**Comment by mmabluesky** [comment]
@celinval 
hi, now  ,errorCode is 60 ,  what should I do ?

**Comment by mmabluesky** [comment]
![tim 20180613175236](https://user-images.githubusercontent.com/17948377/41344224-280b47ee-6f33-11e8-8232-cd47eab510f0.png)

**Comment by mmabluesky** [comment]
@scotthea-amazon 
now ,errorCode is 60 , what should I do ?  
Here is my option to compile libcurl for Android ,
![tim 20180613175900](https://user-images.githubusercontent.com/17948377/41344424-aa5925ea-6f33-11e8-8518-d8991b6d334b.png)

**Comment by celinval** [comment]
Now you need to configure the CA certificates. Because you are building --without-ca-path and --without-ca-bundle, curl doesn't know how to find the certificates.

Can you try following [this wiki](https://github.com/alexa/avs-device-sdk/wiki/Runtime-Configuration-for-CA-Certificates)? BTW, you might need to generate the certificates or convert the android certificates to [PEM format](http://how2ssl.com/articles/working_with_pem_files/).

**Comment by mmabluesky** [comment]
@celinval 
Hi, thanks for your help, I have successfully run AVS on Android, but when I integrate the snowboy wakeup word, the compilation has not passed. The following is the print log. Can you give me some advice? 
Looking forward to your reply ！



Log：
E:/Android/emdoorWork/avs-sdk-android/AVS_Demo/src/main/jni/thirdlib/alexa/include\AVSCommon/Utils/Memory/Memory.h:35: error: undefined reference to 'snowboy::SnowboyDetect::SnowboyDetect(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
E:/Android/emdoorWork/avs-sdk-android/AVS_Demo/src/main/jni/kwd/KittAiKeyWordDetector.cpp:135: error: undefined reference to 'snowboy::SnowboyDetect::SetSensitivity(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [E:/Android/emdoorWork/avs-sdk-android/AVS_Demo/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libemdoorSDK.so] Error 1

-

**Comment by sanjayrd** [comment]
Hi @mmabluesky,

Looks like the Snowboy team is making a fix for this same issue: https://github.com/Kitt-AI/snowboy/issues/389. They'll probably be much more helpful than we can with regards to Snowboy compilation on your platform!

Thanks,
Sanjay

**Comment by JLu76** [comment]
Hello @mmabluesky,

I've followed the the Amazon devs' guide on building the SDK for Android and I've built it successfully, so now I'm trying to get the Sample app running on Android.

Were you able to install GStreamer and run the sample app on Android properly? My main problem right now is getting CMake to find GStreamer. I've downloaded the [Android Universal Package](https://gstreamer.freedesktop.org/data/pkg/android/1.14.1/) bins and have tried setting -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_TARGET}:/path/to/gst_armv7 and -DCMAKE_PREFIX_PATH:PATH=${INSTALL_TARGET}:/path/to/gst_armv7. How do I get CMake to find the gstreamer files?

How did you get GStreamer working for the sample app? Thanks.

**Comment by pkalebu** [comment]
@JLu76 could you please send me the guide? I haven't received it from Amazon yet and it's been a while since I filled out the form

**Comment by sevencheng798** [comment]
Hi @JLu76 @pkalebu  Can you share the Guide for Android? thank your!
E-mail: 494918720@qq.com
