### ISSUE TITLE
Please add version information to all *.so files produces by the SDK. 

### ISSUE THREAD

**Issue by ghe0Rghe** [alexa/avs-device-sdk#767]
Please add version to all *.so files produces by the SDK. 
To do that we just need to add this CMake code to root CMakeLists.txt:
`set_target_properties(
ACL Notifications ADSL CapabilitiesDelegate PlaybackController AFML CBLAuthDelegate PlaylistParser AIP CertifiedSender RegistrationManager Alerts ContextManager Settings AudioPlayer DefaultClient SpeakerManager AudioResources  ESP SpeechSynthesizer AVSCommon ExternalMediaPlayer SQLiteStorage AVSSystem KWD TemplateRuntime
PROPERTIES VERSION 1.0 )
`
See the CMake docs: https://cmake.org/cmake/help/v3.0/command/set_target_properties.html
This is necessary when building for Linux (for ex: inside Yocto I had to patch the SDK (added versioning) to let it work correctly ) and IMHO it is a good practice anyway. Of course the version it self can be taken from `git describe` or any version that makes sense.

## What is the expected behavior?
This change let CMAKE to produce *.so files and sym-links accordingly:
`libACL.so -> libACL.so.1.0 and libACL.so.1.0` 

## What behavior are you observing?
As of now CMake produces only libACL.so

## Provide the steps to reproduce the issue, if applicable:
Simply compile the SDK with CMake

## Tell us about your environment:
IMHO the environment is not important. 

### Tell us what hardware you're using:
- [x ] Desktop / Laptop
- [x ] Other - tell us more: I'm cross-compiling with Yocto for our HW platform.

### Tell us about your OS (Type & version):
- [ x] Linux

**Comment by kencecka** [comment]
Hi @ghe0Rghe,

Thanks for the suggestion.  This has come up previously in #81, and we have it in our backlog of tasks for a future release.  I'll update our internal ticket with your notes as well.

Closing this for now as we're tracking it internally, but please reopen if you have further suggestions around library versioning.

Ken
