### ISSUE TITLE
make[2]: *** No rule to make target libcurl_iOS.a', needed by `AVSCommon/AVS/test/NamespaceAndNameTest'.  Stop. avs build error (Cross-compile for iOS)

### ISSUE THREAD

**Issue by wanJunGe** [alexa/avs-device-sdk#768]
os:mac os
hardware：mac pro
sdk :https://github.com/alexa/avs-device-sdk
version:1.7.1
Reference documents：https://github.com/alexa/avs-device-sdk/wiki/How-to-cross-compile-the-AVS-Device-SDK-for-iOS

i build the sdk step-by-step  with the help of the Reference documents up.
when i reached step 9:
Now we'll build the AVS Device SDK
there is a error occured:
[ 21%] Built target gtest_main
[ 22%] Built target AttachmentCommonTestLib
make[2]: *** No rule to make target `/XX/XX/cross-compile/Build-OpenSSL-cURL/archive/libcurl-7.54.1-openssl-1.0.2l-nghttp2-1.24.0/libcurl_iOS.a', needed by `AVSCommon/AVS/test/NamespaceAndNameTest'.  Stop.
make[1]: *** [AVSCommon/AVS/test/CMakeFiles/NamespaceAndNameTest.dir/all] Error 2
make: *** [all] Error 2

how can i build it succesfully?

**Comment by kencecka** [comment]
hi @wanJunGe,

I'm setting up an IOS build environment to verify the scripts.  Will get back to you with some suggestions soon.

Ken

**Comment by kencecka** [comment]
Hi @wanJunGe,

It appears that the IOS guide is out of date with the current release of the SDK.  I am opening up a ticket internally to update the guide with correct instructions.  This may take some time; we will get back to you when we have updated instructions.

Ken

**Comment by wanJunGe** [comment]
Thank you for your quick reply.

before the instructions updated,do I have other ways to get  the  output of compiling?
can you give me a demo of  compiled code?i need to stuty AVS as soon as possible。
I do apologise for troubling you。

**Comment by scotthea-amazon** [comment]
Hi @wanJunGe,

It is probably not a very appetizing answer, but if you need to study ASAP, you could build for another platform.  There are links for building on various platforms in the [Get Started](https://github.com/alexa/avs-device-sdk#get-started) section of the SDK documentation.

I hope that helps,
-SWH

**Comment by dhpp** [comment]
Hi @yuyubaba - this ticket has been open for a while without update - do you still require our assistance?

**Comment by celinval** [comment]
Hi @yuyubaba, I'm going to close this issue since it has been inactive for a couple months. Feel free to re-open this issue if still require our help.

Best!
