### ISSUE TITLE
sudo bash startauth.sh does not work

### ISSUE THREAD

**Issue by apollo13yuma** [alexa/avs-device-sdk#775]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
## Briefly summarize your issue:
I can not find file "startauth.sh" in my "/home/pi" directory.
Where can I get this file?

I execute the command as below.

sudo bash startauth.sh

 the following issue is similar.
https://github.com/alexa/avs-device-sdk/issues/557

## What behavior are you observing?
no such file or directory

### What version of the AVS Device SDK are you using?
 AVS Device SDK
1.6.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello apollo13yuma,

We have deprecated the authorization tools and examples in 1.6 because they did not implement any of the supported authorization methods ( [Companion App](https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-app.html), [Companion Site](https://developer.amazon.com/docs/alexa-voice-service/authorize-companion-site.html), [Code Based Linking](https://developer.amazon.com/docs/alexa-voice-service/code-based-linking-other-platforms.html), or [On Product](https://developer.amazon.com/docs/alexa-voice-service/authorize-on-product.html) ).  We strongly encourage you to update to a later version.

Regards,
-SWH

**Comment by apollo13yuma** [comment]
Hi Scotthea,

Thank you very much for your reply. I will try to update to AVS SDK 1.7.
If possible, would you please suggest how to upgrade 1.6 to 1.7 on Raspberry Pi?

Can I follow this setup?
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

Regards
Yuma

**Comment by scotthea-amazon** [comment]
Hello Yuma,

Those steps are intended to be used for building 1.7.1 from scratch.   If you do not have any work that depends upon 1.6 it would be simplest to just delete the folders created during your build of 1.6 and use the instructions you linked to.

If you really need to upgrade (e.g. you have changes to avs-device-sdk that you want to merge with 1.7.1) and already have 1.6 building, you can probably do a pull from within the avs-device-sdk folder to get the 1.7.1 source.  Of course, if you have made changes to the 1.6 avs-device-sdk, you will need to merge them.  Then use 'make SampleApp' in the build folder to build the 1.7.1 version of the SampeApp.  Then, you can start from the [Setup Your Configuration](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide#setup-your-configuration) step of the Quick Start Guide to configure and authorize SampleApp.  Note that where those configuration instructions refer to a **sdk-build**, your previous build of 1.6 probably named the folder **build**.

I hope that helps,
-SWH

**Comment by apollo13yuma** [comment]
hi SWH,
Thanks for your help. It was reslolved, when I use SDK 1.7.1.
However, I can not authorrize my cilent in Amazon web site.

https://github.com/alexa/avs-device-sdk/issues/790
