### ISSUE TITLE
Memory leak during long duration test

### ISSUE THREAD

**Issue by vaddep** [alexa/avs-device-sdk#776]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
- Create a playlist xyz with around 50 songs
- Ask Alexa, play the playlist xyz
- Ask Alexa, loop on
- Run this usecase for almost 2Hrs

## What is the expected behavior?
There should not be any memory leaks

## What behavior are you observing?
We see a memory leak around 9MB

## Provide the steps to reproduce the issue, if applicable:
- Create a playlist xyz with around 50 songs
- Ask Alexa, play the playlist xyz
- Ask Alexa, loop on
- Run this usecase for almost 2Hrs

## Tell us about your environment:
ARCH: ARM
OS: Linux

### What version of the AVS Device SDK are you using?
SDK 1.6

### Tell us what hardware you're using:
ARM 

### Tell us about your OS (Type & version):
- [ ] Linux

**Comment by scotthea-amazon** [comment]
Hello vaddep,

Thank you for bringing this to our attention!  Can you provide us with a little more information?:

- Logs for the session
- Tell us about how you are measuring memory use.  If possible, provide console output or a screen grab of your measurements.

Best regards,
-SWH
