### ISSUE TITLE
Add device to smarthome group

### ISSUE THREAD

**Issue by marcelveldt** [alexa/avs-device-sdk#782]
## Briefly summarize your issue:
A smart speaker built around the AVS SDK can't be added to any smart home groups in the Alexa app.

## What is the expected behavior?
Be able to add a Alexa enabled device (whether it's a real Echo or created with the SDK) to a smart home device group in the Alexa app.

## What behavior are you observing?
The Alexa app supports creating smart home groups in which you can add an Alexa enabled device if the Alexa device is positioned in that group/room. In my situation I have one real Echo device in the same network and 2 self-built devices running the sample app but I can't add any (not the real Echo nor the sample-app devices) to a smart home group. Tried both the iOS app and the webversion.

## Provide the steps to reproduce the issue, if applicable:
Open the Alexa app, navigate to Smart home.
Create a new group (smart devices) and try to add the Alexa enabled device there.

## Tell us about your environment:
I'm trying to create audiophile smart speakers/endpoints for multi room audio playback (Roon) and equip them with Alexa voice control. These endpoints run a pi3 as SBC with audiophile soundcard connected to it and a Mic Array. Before integrating my custom code I've started with a simple approach by just compiling and running the Sample App from the SDK. I also have an original Echo Dot connected to the same amazon account. Strange thing is that I the Echo dot also can't be connected to any smarthome group but maybe you just need more of them before this option is available ? Anyways, it would be great if you can use SDK-created Alexa devices within these smarthome groups too.

### What version of the AVS Device SDK are you using?
The latest, compiled a few days ago, freshly pulled from Github. Version 1.7.x 

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello marcelveldt,

Nice suggestion!  I have forwarded you idea to the team.

Thank you,
-SWH

**Comment by marcelveldt** [comment]
OK, great! Is my assumption true that this feature currently only is available if you have multiple real Echo devices ?

**Comment by scotthea-amazon** [comment]
Hello marcelveldt,

The feature is only enabled for a subset of device types.  I am not 100% sure if you have to have multiple devices.  However, when I try it with an account that only has one device, I don't seem to have the option - so you are probably right.

I hope that helps,
-SWH

**Comment by marcelveldt** [comment]
OK, thanks for the answer. Let's hope it's possible that devices built around the SDK can be added to those smart home groups too.

**Comment by snicker** [comment]
Is this possible yet?
