### ISSUE TITLE
Timer plays with music!

### ISSUE THREAD

**Issue by ANDROIDTODO** [alexa/avs-device-sdk#784]
Hi AVS team,

I encountered a problem , and it can be 100% reproduced.
SDK version is 1.7.1. 

The blewer is step:
1.play music(the music is playing)
2.set timer for 1 second.(wait 1 second,timer is playing , music paused)
3.play music(timer plays with music)

**Comment by scotthea-amazon** [comment]
Hello ANDROIDTODO,

That sounds very interesting.  Would you please attach complete (i.e. from the start of the session, through the misbehavior) DEBUG9 level logs for a reproduction of this?

Thank you,
-SWH

**Comment by leino11121** [comment]
Hi Scotthea

the same issue on 1.7.0, and it can be 100% reproduced.

The DEBUG9 log is in attachment.

[issue.log](https://github.com/alexa/avs-device-sdk/files/2110995/issue.log)

Thanks.

**Comment by sanjayrd** [comment]
Hi @ANDROIDTODO,

This appears to be an issue with our AudioPlayer capability agent and its management of focus. We will investigate further and get back to you.

Thanks for pointing this out,
Sanjay

**Comment by dhpp** [comment]
We believe this is now addressed in our 1.10 SDK release.  I'll close this out - can you please create a new tracking ticket if the issue still persists, thanks.
