### ISSUE TITLE
OOBE: The default language used

### ISSUE THREAD

**Issue by leino11121** [alexa/avs-device-sdk#789]
## Briefly summarize your issue:

My device uses the SDK(v1.7.0), I have almost finished all the develop. So we are testing it for certification. 

As mentioned in Functional_self-test_checklist,  if I change the country setting to Germany in https://www.amazon.com/mn/dcw/myx.html/ref=myk#/home/settings/payment, then register the device, When I say "what's the weather", the Alexa should response in German. but the response from Alexa is still in English. 
My account is US.
I have test it in PI, the same issue. 

I have closed the code client->sendDefaultSettings() in SampleApplication.cpp.

```
diff --git a/SampleApp/src/SampleApplication.cpp b/SampleApp/src/SampleApplication.cpp
index bf605199..74f0aa29 100644
--- a/SampleApp/src/SampleApplication.cpp
+++ b/SampleApp/src/SampleApplication.cpp
@@ -681,7 +681,7 @@ bool SampleApplication::initialize(
     client->connect(m_capabilitiesDelegate, endpoint);
 
     // Send default settings set by the user to AVS.
-    client->sendDefaultSettings();
+    //client->sendDefaultSettings();
 
     return true;
 }
```

I have check the log in PI, before I change the code, the SettingsUpdated event was sent to Alexa. after changed the code, the SettingsUpdated event wasn't sent. But still has the issue. 

#### My Country Setting.
![My Country Setting.](https://user-images.githubusercontent.com/8294714/41498702-cd3579e0-71a6-11e8-9c09-fae54b55679e.png)

#### Function-CheckList-OOBE2.1
![Function-CheckList-OOBE2.1](https://user-images.githubusercontent.com/8294714/41498710-dd114128-71a6-11e8-8d93-14f5c2289b2f.png)

## What is the expected behavior?
Response from Alexa is given in language of Country setting

## What behavior are you observing?
Response from Alexa is given in English

### What version of the AVS Device SDK are you using?
      <1.7.0>

### Tell us what hardware you're using:
- [x] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [x] Raspbian Stretch

**Comment by scotthea-amazon** [comment]
Hello leino11121,

Thank you for reporting this!

Would you please provide a full (from the start to end of session) DEBUG9 log from a DEBUG build - with the database file for the settings (the one pointed to by AlexaClientSDKConfig.json's settings::databaseFIlePath value) deleted before you start the sessio?  Would you also provide us a copy of your AlexaClientSDKConfig.json file.  That should help us track down both the service and client behavior.

Best regards,
-SWH

**Comment by leino11121** [comment]
Hi Scotthea,

Here is the log and AlexaClientSDKConfig.json. Before testing, I have clear the db files.

## Log on PI (SDK: v1.7.1)
[issue2.log](https://github.com/alexa/avs-device-sdk/files/2113346/issue2.log)

## AlexaClientSDKConfig.json

[AlexaClientSDKConfig.json.txt](https://github.com/alexa/avs-device-sdk/files/2113354/AlexaClientSDKConfig.json.txt)


Thanks. 
Leon

**Comment by sanjayrd** [comment]
Hi @leino11121,

Thank you for reporting the issue. I've reproduced it locally. We will get back to you upon further investigation.

- Sanjay

**Comment by leino11121** [comment]
Thanks Sanjay,

Look forward to your reply.

Br.
Leon

**Comment by sanjayrd** [comment]
Hi @leino11121,

Just to confirm, did you ask "What's the time" in German or English? The steps mention that you should be asking in "Country 1 Language" (German).

Thanks,
Sanjay

**Comment by leino11121** [comment]
HI @sanjayrd ,

I ask it in German.

Thanks.
Leon

**Comment by leino11121** [comment]
Hi @sanjayrd ,

Another test I have done:

**Comment by sanjayrd** [comment]
Hi @leino1112,

Thanks for letting us know. I'm still trying to dig into this internally, but will update this thread once we understand what might be going on.

Thanks,
Sanjay

**Comment by leino11121** [comment]
HI @sanjayrd 

Is there any update?

Thanks,
Leon

**Comment by kjkh** [comment]
Hi @leino11121,

Are you still experiencing this issue? If so, would it be possible to update to the latest version of the SDK and retry?
