### ISSUE TITLE
Duck volume during Barge in case (Audio Player + Speech Recognizer)

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#79]
Hi, 
I noticed that SDK 1.0 behavior for Audio player streaming I heart radio + speech recognizer event different form Amazon EHCO device.

Amazon ECHO: duck stream volume while processing voice and playing back response. After new use case is done, streaming volume form Audio Player is restored.
AVS SDK 1.0: pause Audio player while processing voice and playing back response. After new use case is done, Audio Player resumes streaming radio station.

Based on that, what is the desired behavior from AMAZON? Is SDK behavior going to change to mach Amazon ECHO device ?

Regards,
Juliano Ribeiro

**Comment by dhpp** [comment]
Thanks Juliano for asking this question.  We are looking into this and will update this ticket, and other things accordingly, shortly.

**Comment by dhpp** [comment]
Hi Juliano, to clarify, all sample applications of an AVS client which we provide implements the pausing behavior as you describe.

Our guidance here:

[https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/alexa-voice-service-functional-design-guide#media](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/alexa-voice-service-functional-design-guide#media)

expresses that an implementation may pause or attenuate, and that both are acceptable (with the exception of Audible per 4.1.1).
