### ISSUE TITLE
set loop/shuffle using sdk

### ISSUE THREAD

**Issue by leino11121** [alexa/avs-device-sdk#793]
Hi Alexa Team,

## Briefly summarize your issue:
In the music checklist (Section 18: DUT companion app), item 12 and 13, Click the loop/shuffle button on the DUT app to change the play mode. But I didn't find the API to achieve this function. 

![5](https://user-images.githubusercontent.com/8294714/41600367-58434d06-7408-11e8-9bab-92e444d0f500.jpg)

### What version of the AVS Device SDK are you using?
      <1.7.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Hi @leino11121,

This is handled through voice interaction (our cloud NLU will take care of it) and through button presses on the Alexa app. There is no need for your device to access this API.

Thanks,
Sanjay

**Comment by leino11121** [comment]
Hi @sanjayrd ,

I understand.

But how to understand the test case in the music checklist. I'm afraid it will be judged as failure if the companion app doesn't achieve loop/shuffle function.

Thanks,
Leon

**Comment by sanjayrd** [comment]
Hi @leino11121,

The companion app will talk to our cloud backend, which will in turn send directives to your device instructing the device what to do (for example, what songs to play and when to stop/resume). As long as your device responds correctly to these directives, you should be good.

You can verify on alexa.amazon.com and logging in with your user account (even better would be using the companion app). Clicking the "Now Playing" option should show you button options for shuffle and loop. You can test the behavior locally using a small playlist and seeing that the buttons both work as they should when playing this playlist.

Thanks,
Sanjay

**Comment by WksKing** [comment]
Hi @sanjayrd ,
I'm also interest in this question.
What is the meaning of your "The companion app", it means the **Amazon Alexa app** or our **custom companion app**?
If it means our custom companion app, then I want to know how to talk AVS cloud from our app to do loop/shuffle operation? do you have an interface to implement the requirement?

we have a test companion app and have a idea to add the function, below is the steps, would you help me check if it's right?
1. Connect the device(DUT) with the companion app(installed in an Android device) in the same network.
2.  Press the loop/shuffle button in companion app, then send the operation command to DUT.
3. DUT receives the command, then send loop/shuffle event to AVS cloud.
4. AVS cloud will in turn send directives to DUT.
Maybe, it's too tedious，but I don't have any other ideas. 
I'm using SDK V1.7.1.

Looking forawrd to your reply, thanks very much.

**Comment by sanjayrd** [comment]
Sorry for the confusion! By companion app, I meant the Amazon Alexa app.

Your device doesn't have to send any loop/shuffle event to the AVS cloud - this is handled only through voice and the Amazon Alexa app.

**Comment by WksKing** [comment]
Hi @sanjayrd ,
Is it possible to control(play/pause, previous, next, loop, shuffle) music play in my custom companion app(Android platform)?  If yes, how can I do it? I would like to add a "Now playing" page looks like in Amazon alexa app, does it have any interface to support?

Thanks a lot.

**Comment by sanjayrd** [comment]
It's certainly possible, but will require some work your part :)

Essentially, the device is the component making the API calls to AVS for pause, previous, etc, as well as the component receiving "display cards"/visuals from AVS. You could add buttons on your companion app, and forward these button presses to your device. Likewise, you could forward the TemplateRuntime display cards info coming from AVS to your device to your app.

Thanks,
Sanjay

**Comment by leino11121** [comment]
Thanks @sanjayrd , I close this issue.
