### ISSUE TITLE
How do I initialize a specific module if I change the network? Instead of restarting the entire program?

### ISSUE THREAD

**Issue by zuowanbushiwo** [alexa/avs-device-sdk#794]
We have some network-changing scenarios. At present, it is to restart the entire process. Is there any other way?
 
thanks！

**Comment by sanjayrd** [comment]
Hi @zuowanbushiwo,

Which module are you referring to? For some components it may be possible to simply destruct and construct a new class, but without knowing which module you're talking about, it's impossible to know for sure.

Thanks,
Sanjay
