### ISSUE TITLE
Deezer is not supported on this device

### ISSUE THREAD

**Issue by leino11121** [alexa/avs-device-sdk#796]
Dear Alexa Team:

## Briefly summarize your issue:
Deezer/SiriusXM is not supported on this device. 

In the Music checklist, there is case to use deezer/SiriusXM to play album/stations. But when I say "Play music from Deezer", Alexa responses "The Deezer is not supported on this device". 

My account is US, and before the test,  I have change the region/country to United States and enabled the skill on alexa app and linked to my Deezer/SiriusXM. 

The echo using the same account can playback correctly.

Here is the play siriusXM  on Pi.
[siriusxm.txt](https://github.com/alexa/avs-device-sdk/files/2122240/siriusxm.txt)

## What is the expected behavior?
Deezer/SiriusXM can be play on my device.

## What behavior are you observing?
Deezer/SiriusXM is not supported on this device. 

### What version of the AVS Device SDK are you using?
      <1.7.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [x] Other - tell us more: arm-linux

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Hi @leino11121,

You may need to be whitelisted for SiriusXM and certain other MSPs to work properly.

Thanks,
Sanjay

**Comment by leino11121** [comment]
Hi @sanjayrd ,

We had asked this question to our company's Amazon contact, but the answer is "just Spotify and Pandora need to be in whitelist". 

Can you please help to confirm it?

Thanks.
Leon

**Comment by leino11121** [comment]
Sorry, I have a mistake.
I has no question about this issue.

**Comment by mtosic** [comment]
I also get "Deezer is not supported on this device". I'm just having fun with SDK on raspberry pi and trying to set up Deezer.

It would be great if anyone has managed to set it up on RPi.
