### ISSUE TITLE
Can't get the "RenderPlayerInfo" when play audible(always) and kindleBook(click in alexa.amazon.com)

### ISSUE THREAD

**Issue by leino11121** [alexa/avs-device-sdk#797]
## Briefly summarize your issue:
Can't get the "RenderPlayerInfo" when play audible(always) and kindleBook(click in alexa.amazon.com).

But always ok when play Amazon Music. 

[click-on-alexa.amazon.com-kindlebook.log](https://github.com/alexa/avs-device-sdk/files/2123853/click-on-alexa.amazon.com-kindlebook.log)

[wakeup-audible.log](https://github.com/alexa/avs-device-sdk/files/2123854/wakeup-audible.log)

## What is the expected behavior?
Can't get the "RenderPlayerInfo"

### What version of the AVS Device SDK are you using?
      <1.7.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Hi @leino11121,

Display cards are only supported for music currently. They aren't supported for Audible and KindleBooks.

Thanks,
Sanjay

**Comment by sanjayrd** [comment]
Hi @leino11121,

Display cards are only supported for music currently. Audible and KindleBooks don't have this feature.

Thanks,
Sanjay

**Comment by leino11121** [comment]
Thanks @sanjayrd .

I will close this issue.

Leon
