### ISSUE TITLE
How to update lamda function (Nodejs ) timeout via ask

### ISSUE THREAD

**Issue by svarkey** [alexa/avs-device-sdk#798]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by sanjayrd** [comment]
Hi @svarkey,

Your question doesn't appear to be related to the C++ SDK, but rather the Alexa Skills Kit. You'll probably get a better answer if you post your question on their [forums](https://forums.developer.amazon.com/spaces/24/Alexa+Skills+Kit+Knowledge+Base.html).

Thanks,
Sanjay

**Comment by kjkh** [comment]
Issue has been resolved, and requester has not responded with additional comments. Please feel free to re-open if you have further questions.
