### ISSUE TITLE
Multiple devices using same AVS acocunt (Refresh Token)

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#80]
HI,

Is it possible to have multiple devices using same Amazon account on C++ AVS SDK? 
If so, what are the changes that we need on device to allow that?

So far, the behavior that we have observed is when second device tries to connect to AVS it is not able to establish connection. Only when first device disconnects we can connect second one to AVS.

Regards,
Juliano Ribeiro

**Comment by satishc4u** [comment]
Hi ,
I have one doubt, what is "deviceSerialNumber" in  AlexaClientSDKConfig.json file and where to get it ?
