### ISSUE TITLE
The CapabilitiesDelegate library does not compile if BUILD_TESTING is not enabled. 

### ISSUE THREAD

**Issue by ghe0Rghe** [alexa/avs-device-sdk#804]
## Briefly summarize your issue:
For production environments I would like to skip BUILD_TESTING and it is nice that there is a `cmake` flag for that. but if I disable it the CapabilitiesDelegate does not compile / link. This is because CapabilitiesDelegate links unconditionally to Integrate library but is should only link if BUILD_TESTING=On (when BUILD_TESTING=Off the Integrate library is not built at all). 

## What is the expected behavior?
if I set BUILD_TESTING=Off then the CapabilitiesDelegate still links corectly. 

## What behavior are you observing?
There is a linker error saying Integration library was not found. 

## Provide the steps to reproduce the issue, if applicable:
BUILD_TESTING=Off try to compile 

## Tell us about your environment:
Im using yocto for cross compile for ARM. 

### What version of the AVS Device SDK are you using?
      <1.7.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: our hardware based on IMX7

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by priyagsenthil** [comment]
Hi ghe0Rghe,

Thanks for bringing this to our attention. We will get it fixed for the next release of the SDK.

Thanks
Priya

**Comment by kclchan** [comment]
This is fixed in the latest release of the SDK.  Thanks for brining this to our attention.
