### ISSUE TITLE
Shared Library Does NOT have Version

### ISSUE THREAD

**Issue by changyp6** [alexa/avs-device-sdk#81]
All the shared library generated doesn't have version.
A standard shared library should have the following file name:
libNAME.so.major.minor.patch, and the soname of this library should be
libNAME.so.major

**Comment by dhpp** [comment]
Thanks changyp6, this is a great suggestion, and we've taken a note of this to prioritize against future work.  I'll leave this ticket open while we continue to explore.

**Comment by sanjayrd** [comment]
Closing for now, as we've added this to our backlog of things to do. Thanks for pointing this out @changyp6.
