### ISSUE TITLE
Failed to initialize SampleApplication

### ISSUE THREAD

**Issue by phamvinhtoan** [alexa/avs-device-sdk#813]
I follow this tutorial: 
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide/a5646fc9e6dde8128c940b86a9bbece7f65c1ace
 and stuck when i run SampleApp.

my result:
root@raspberrypi:/home/pi/BUILD# TZ=UTC ./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json $LOCAL_BUILD/models
2018-06-28 09:44:51.436 [  1] I sdkVersion: 1.8.0
configFile ./Integration/AlexaClientSDKConfig.json

(SampleApp:3017): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:3017): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
2018-06-28 09:44:51.517 [  1] C SampleApplication:Failed to create media player for speech!
2018-06-28 09:44:51.518 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!
any one can't help me ~~!

**Comment by priyagsenthil** [comment]
Hi phamvinhtoan,

Do you have the right version of gstreamer installed. If yes, whats the version you are using. Do yiou have all the required plugins : base, good, bad.

Can you rerun with GST_DEBUG set to 4 and send across the logs. 

Thanks
Priya

**Comment by avp24** [comment]
@phamvinhtoan what other ways did you try? Can you please elaborate? I am facing the same error on ARM platform.
Thanks!

**Comment by vaites** [comment]
I solved it installing `gstreamer1.0-alsa`. After installing it `gst-launch-1.0 audiotestsrc ! alsasink` must work and Alexa sample app too.
