### ISSUE TITLE
Unexpected no sound in tunein radio 8+ hours test

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#818]
Hi AVA team,

It's SDK 1.8.

Attached log is a unexpected no sound play under long term media test, it's play TuneIn radio for "BBC Radio 2".
From the log, I started play "BBC Radio 2" from TuneIn at UTC 6/29 11:50, it's our night here.
After I return to my Lab, no sound is playing but the console seems continue to dump media log, and from Amazon APP, it display it's playing.
Then, I ask "Alexa" and say Hi, it responded, and then the TuneIn radio back and continue to play "BBC Radio 2" (see about line#522959, or search keyword for "onKeyWordDetected" in the log).

Actually, we have experienced such issue for months while we started to test long term music test for iHeartRadio, Pandora, TuneIn and Amazon Music.
For Amazon Music, there is a case #750 said it's due to the account is not unlimited, but actually, we still can see such issue.
For other three Radio tests, we never experience it can play over 8 hours. Normally, it stops at 6-8 hours randomly. The Pandora even short, sometimes it may stop in a hour. (case #747).

Could you help to check my log, I would like to know how to identify the root cause for this long term music test case.

[tunein_overnight_fail.zip](https://github.com/alexa/avs-device-sdk/files/2151195/tunein_overnight_fail.zip)

**Comment by zeusshuang** [comment]
Hi AVS team,

I attached a new log based on SDK 1.8.

The log is a little huge ,
You can check "uptime" keyword which it indicate my start and end test date.
From UTC 2018-07-05 12:02 to 2018-07-05 22:53. 
I don't know when the TuneIn stopped playing, but from the log, I guess it may stop at line#513806
the timestamp "2018-07-05 21:56:19:201" , the symptom is a little same as case #727, but the different is that DUT is still alive and Q&A working, I even can ask to play music again.

While tunein stopped playing, the APP display it's still playing, and I can click stop from APP and it will stop (I can see it will not dump AttachmentReaderSource:read:size .... )


[TuneIn_8hours-0705-2018.zip](https://github.com/alexa/avs-device-sdk/files/2168695/TuneIn_8hours-0705-2018.zip)

**Comment by kjkh** [comment]
Hi @zeusshuang,

I don't see anything in the logs that would indicate that playback stopped, either within AudioPlayer or the MediaPlayer. I'll try running TuneIn overnight to see if I can reproduce. Do you also have any other information on reproduction steps? Does this only happen once it's elapsed the 6-8 hours, or can this be reproduced in some other way?

**Comment by kjkh** [comment]
Hi @zeusshuang,

Thanks for posting new logs. The original logs did not indicate anything in particular which showed AudioPlayer or MediaPlayer stopping. We'll take a look at the new ones, as well as attempt to reproduce the issue. Has this been seen in any other situations, or can this only be reproduced after the elapsed 6-8 hours?

**Comment by zeusshuang** [comment]
Hi @kjkh ,

Yes, so far from my tests, it can only reproduce after 6-8 hours. I ever doubted it's disconnected by radio station side but the APP still show its under playing state.

And it's very strange, it always failed after 6-8 hours in TuneIn test.  Another information is that if we setup a auto-test audio script and let it changes different station every hour, it will be fine.

I am not sure if it's related to the station due to I always test "BBC radio 2", I will try to test another stable station today.

**Comment by kclchan** [comment]
Hi @zeusshuang, do you still see this failure in the later version of the SDK?  If not, would you mind if we close the issue?
