### ISSUE TITLE
SDK build

### ISSUE THREAD

**Issue by yakov2006** [alexa/avs-device-sdk#82]
I was in trouble to build the C++ sdk(avs-device-sdk-master,v1.0.0 released 8/7/2017), the minimum requirements for compiler's tool chain is 
[GNU Compiler Collection (GCC) 4.8.5]or later,however,our TV platform's tool chain is gnu-toolchain_4.8.2. So, it's failed to build the C++ SDK.

Could you change the C++ SDK source to let the tool chain's requirement to be GNU Compiler Collection (GCC) 4.8.3 or earlier?
or could you give me some other suggestions ?

Maybe other people will have the same problem when to port the C++ SDK .

**Comment by dhpp** [comment]
Thanks yakov2006.  This is a nice suggestion, and we will certainly consider it for future work.  At the current time, GCC 4.8.5 is the minimum version which we support for building the SDK.

**Comment by yakov2006** [comment]
I am building  the v1.0.1 of the C++ SDK, Encountered such a compiler error：

Scanning dependencies of target AVSCommon
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Logger.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ThreadMoniker.cpp.o
Linking CXX shared library libAVSCommon.so
[ 26%] Built target AVSCommon
[ 27%] Built target gtest
[ 29%] Built target gmock_main
[ 30%] Built target gtest_main
[ 30%] Built target AttachmentCommonTestLib
Linking CXX executable AlexaClientSDKInitTest
[ 30%] Built target AlexaClientSDKInitTest
Scanning dependencies of target AttachmentManagerV2Test
[ 31%] Building CXX object AVSCommon/AVS/test/CMakeFiles/AttachmentManagerV2Test.dir/Attachment/AttachmentManagerV2Test.cpp.o
Linking CXX executable AttachmentManagerV2Test
[ 31%] Built target AttachmentManagerV2Test
Scanning dependencies of target AttachmentReaderTest
[ 32%] Building CXX object AVSCommon/AVS/test/CMakeFiles/AttachmentReaderTest.dir/Attachment/AttachmentReaderTest.cpp.o
^Cmake[2]: *** [AVSCommon/AVS/test/CMakeFiles/AttachmentReaderTest.dir/Attachment/AttachmentReaderTest.cpp.o] Interrupt
make[1]: *** [AVSCommon/AVS/test/CMakeFiles/AttachmentReaderTest.dir/all] Interrupt
make: *** [all] Interrupt

yangzq@sita1:~/samba/sita/trunk/tplayer/core/alexa/out_mt5658m$ 
yangzq@sita1:~/samba/sita/trunk/tplayer/core/alexa/out_mt5658m$ 
yangzq@sita1:~/samba/sita/trunk/tplayer/core/alexa/out_mt5658m$ make
Scanning dependencies of target AVSCommon
[  1%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/Logger.cpp.o
[  2%] Building CXX object AVSCommon/CMakeFiles/AVSCommon.dir/Utils/src/Logger/ThreadMoniker.cpp.o
Linking CXX shared library libAVSCommon.so
[ 26%] Built target AVSCommon
[ 27%] Built target gtest
[ 29%] Built target gmock_main
[ 30%] Built target gtest_main
[ 30%] Built target AttachmentCommonTestLib
Linking CXX executable AlexaClientSDKInitTest
../../libAVSCommon.so: undefined reference to `_ZTHN14alexaClientSDK9avsCommon5utils6logger13ThreadMoniker15m_threadMonikerE'
collect2: error: ld returned 1 exit status
make[2]: *** [AVSCommon/AVS/test/AlexaClientSDKInitTest] Error 1
make[1]: *** [AVSCommon/AVS/test/CMakeFiles/AlexaClientSDKInitTest.dir/all] Error 2
make: *** [all] Error 2
