### ISSUE TITLE
Tap to talk issue

### ISSUE THREAD

**Issue by ANDROIDTODO** [alexa/avs-device-sdk#820]
Hi AVS team,

I have encountered a problem about TAP-TO-TALK.
When i press 't' to talk, and then press 't' after i finished my words. The TTS has not been consumed.

Here is log.
[tap-to-talk.log](https://github.com/alexa/avs-device-sdk/files/2153695/tap-to-talk.log)

SDK version: 1.8.0
platform: ubuntu 16.04 LTS

**Comment by kjkh** [comment]
Hi @ANDROIDTODO,

With Tap to Talk, you do not need to press 't' again after you have finished your speech. AVS and the SDK will automatically handle stopping the stream once your voice request has been processed.

**Comment by kjkh** [comment]
This appears to be working as expected. Closing ticket, but please re-open if you have further questions.
