### ISSUE TITLE
InternetConnectionMonitor thread disappeared

### ISSUE THREAD

**Issue by justy0714** [alexa/avs-device-sdk#824]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Hi AVS team,

SDK 1.8

As following messages show that InternetConnectionMonitor thread disappeared after it got testConnectionFailed in 3 consecutive internet connection tests. And it never performed internet connection test again. 
Full log messages is in the attached file.

2018-07-02 23:56:03.064 [6ee] E LibCurlHttpContentFetcher:curlEasyPerformFailed:error=Couldn't resolve host name
2018-07-02 23:56:03.064 [  c] E InternetConnectionMonitor:testConnectionFailed:reason=badHTTPContentReceived
2018-07-02 23:56:03.065 [  c] 5 InternetConnectionMonitor:updateConnectionStatus:connected=false
2018-07-02 23:56:03.065 [  c] 5 InternetConnectionMonitor:notifyObserversLocked
2018-07-02 23:56:48.101 [6ef] E LibCurlHttpContentFetcher:curlEasyPerformFailed:error=Couldn't resolve host name
2018-07-02 23:56:48.102 [  c] E InternetConnectionMonitor:testConnectionFailed:reason=badHTTPContentReceived
2018-07-02 23:57:33.138 [6f0] E LibCurlHttpContentFetcher:curlEasyPerformFailed:error=Couldn't resolve host name
2018-07-02 23:57:33.139 [  c] E InternetConnectionMonitor:testConnectionFailed:reason=badHTTPContentReceived

[InternetConnectionMonitor_Disappear.log](https://github.com/alexa/avs-device-sdk/files/2158052/InternetConnectionMonitor_Disappear.log)

**Comment by kjkh** [comment]
Hi @justy0714,

I noticed the InternetConnectionMonitor is polling every minute, but the default is five. Did you make any modifications to the InternetConnectionMonitor?

The logs didn't reveal anything interesting in particular. I started the SDK and disabled internet connectivity, and did not see the InternetConnectionMonitor thread die after multiple failed attempts. Do you have steps to reproduce the issue?

**Comment by justy0714** [comment]
Hi, kjkh

We have shortened the internet connection test interval to 1 minute. This modification can help our device to detect internet connection status quickly and play the correct TTS while receiving push-to-talk request or wake-up word in internet connection lost status.

Therefore, the disappeared InternetConnectionMonitor thread can't provide correct internet connection status to our device and  device will play the wrong TTS to users and make users confused about the internet connection status.

Just as what you saw in the log, we didn't do any specific test on InternetConnectionMonitor. That log was retrieved from a device that had been playing Amazon music overnight. 

So you can try to reproduce this bug by shortening internet connection test interval and playing music overnight.

**Comment by kclchan** [comment]
Hi @justy0714,

Instead of the thread disappearing, I think it's possible that the thread is blocked by reading from the S3_TEST_URL.

To verify if this is indeed the case, would you be able to add more logs in InternetConnectionMonitor, such as this:

void InternetConnectionMonitor::testConnection() {
...
ACSDK_ERROR(LX("before getContent"));
auto httpContent = contentFetcher->getContent(HTTPContentFetcherInterface::FetchOptions::ENTIRE_BODY);
ACSDK_ERROR(LX("after getContent"));
...
ACSDK_ERROR(LX("before read"));
auto bytesRead = reader->read(buffer.data(), buffer.size(), &readStatus);
ACSDK_ERROR(LX("after read").d("bytesRead", bytesRead));
...
}

Thanks,
Kenneth

**Comment by zeusshuang** [comment]
Hi @kclchan ,

I have another log and may have same problem, the case is Internet is actually working, but InternetMonitor failed.
This user is in Germany and actually change to de-DE by AVS command.

[avs_dbg_log.txt](https://github.com/alexa/avs-device-sdk/files/2188620/avs_dbg_log.txt)

**Comment by kclchan** [comment]
Hi @zeusshuang,

We have fixed an issue with the InternetConnectionMonitor not timing out correctly.  Please try this again in v1.9.  Thanks!
