### ISSUE TITLE
Utilizing the captured speech from Mics for other processing before sending out to cloud

### ISSUE THREAD

**Issue by ullasbharadwaj** [alexa/avs-device-sdk#826]
Hi AVS team,
How do we obtain speech text after SpeechRecognizer, we hope to use it for other applications - posssibly also do some processing and then send the processed speech to Amazon server ?
If there is a method, can you pls shed some light into it?

I am using Alexa SDK with Raspbian stretch on RPi 3.

**Comment by kjkh** [comment]
Hi @ullasbharadwaj,

A general overview of the architecture:
A SharedDataStream is written to by the microphone class (in this case the PortAudioMicrophoneWrapper). The SharedDataStream is then read by the various AudioProvider objects (Tap To Talk, Wakeword, Hold to Talk, etc), and streamed to AVS when a Recognize is initiated via the AudioInputProcess capability agent.

The initialization of these objects can be seen [here](https://github.com/alexa/avs-device-sdk/blob/v1.8/SampleApp/src/SampleApplication.cpp#L551-L659) and the recognize workflow documentation is [here](https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html). Code snippets of interest in AudioInputProcessor can be found by following the _m_reader_ variable.

Here are a few possible routes you can explore depending on your needs and application:

1. Create your own MicrophoneWrapper object and pre-process before sending the data to the SharedDataStream.
1. Modify the AudioInputProcessor Capability Agent to perform additional processing before streaming to AVS.

**Comment by ullasbharadwaj** [comment]
Hello Keith Huang,
Thank you so much for a detailed explanation. Will follow the mentioned guideline and get back if some support is needed.

**Comment by kjkh** [comment]
No problem. I'm going to close this ticket, but feel free to re-open if you have any further questions.

**Comment by retunestan** [comment]
How can I access audio output stream (raw audio samples) ? Cause I need the final output for AEC as refenrece signal.
