### ISSUE TITLE
It's failed to run "AuthServer" to retrieve a valid refresh token from LWA

### ISSUE THREAD

**Issue by yakov2006** [alexa/avs-device-sdk#83]
I was in trouble to run "AuthServer" to retrieve a valid refresh token from LWA in my mac, details as following:

yakov-MacBook-Pro:Desktop yakov$ 
yakov-MacBook-Pro:Desktop yakov$ cd build_alexa/
yakov-MacBook-Pro:build_alexa yakov$ ls
ACL			CMakeFiles		MediaPlayer
ADSL			CTestTestfile.cmake	SampleApp
AFML			CapabilityAgents	Testing
AVSCommon		ContextManager		ThirdParty
ApplicationUtilities	DartConfiguration.tcl	cmake_install.cmake
AuthDelegate		Integration		doc
AuthServer		KWD
CMakeCache.txt		Makefile
yakov-MacBook-Pro:build_alexa yakov$ 
yakov-MacBook-Pro:build_alexa yakov$ 
yakov-MacBook-Pro:build_alexa yakov$ cat Integration/
.DS_Store                  Makefile
AlexaClientSDKConfig.json  cmake_install.cmake
CMakeFiles/                src/
CTestTestfile.cmake        test/
yakov-MacBook-Pro:build_alexa yakov$ cat Integration/AlexaClientSDKConfig.json 
 {
    "authDelegate":{
        "clientSecret":"**REDACTED**",
        "deviceSerialNumber":"**REDACTED**",
        "refreshToken":"**REDACTED**",
        "clientId":"**REDACTED**",
        "deviceTypeId":"**REDACTED**"
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"./",
     "alarmSoundFilePath":"./",
     "alarmShortSoundFilePath":"./",
     "timerSoundFilePath":"./",
     "timerShortSoundFilePath":"./"
   }
 }
yakov-MacBook-Pro:build_alexa yakov$ 
yakov-MacBook-Pro:build_alexa yakov$ 
yakov-MacBook-Pro:build_alexa yakov$ python
python             python2.6          python2.7          python3            python3-config     python3.6-32       python3.6m         pythonw            pythonw2.7
python-config      python2.6-config   python2.7-config   python3-32         python3.6          python3.6-config   python3.6m-config  pythonw2.6         
yakov-MacBook-Pro:build_alexa yakov$ python A
ACL/                  ADSL/                 AFML/                 AVSCommon/            ApplicationUtilities/ AuthDelegate/         AuthServer/           
yakov-MacBook-Pro:build_alexa yakov$ python AuthServer/AuthServer.py 
The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.

 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Aug/2017 11:24:44] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Aug/2017 11:24:46] "GET /authresponse?error_description=An+unknown+scope+was+requested&error=invalid_scope HTTP/1.1" 200 -
yakov-MacBook-Pro:build_alexa yakov$ 

In the browser,the log as following:
LWA did not return a refresh token, with the response code 400. This is most likely due to an error. Check the following JSON response:
{"error_description":"The request is missing a required parameter : code","error":"invalid_request"}
Server is shutting down, so you can close this window.

**Comment by dhpp** [comment]
Hi yakov2006, this tends to happen because a credential (from the AlexaClientSDKConfig.json file) is invalid, either due to being incorrectly copied & pasted, or if some " marks were missing.

The 400 response simply means that the LWA step (generating an OAuth2 credential with which to interact with AVS) failed due to the data you sent them.

My suggestion would be to carefully enter your credentials again into the file, and try again.  If there are still issues, then also double check you're entering the correct data (from the developer portal), as there is still scope to copy & paste the wrong thing.

**Comment by dylono96** [comment]
my raspberry runs the authentication tool on http://127.0.0.1:3000 instead of https://127.0.0.1:3000, does this matter?
Cause I have error code 400 as well, and im sure I have my creds correctly filled in.

**Comment by satishc4u** [comment]
Hi dylono96,
I am also getting the same issue.Did you find any solution ?

Thanks in advance

**Comment by dylono96** [comment]
Sadly not yet.
Im thinking I didnt enter the correct paths in the options that automatically generate , how did you fill in the config? Can you post a screenshot(without your credentials ofcourse)?

**Comment by satishc4u** [comment]
Here is my AlexaClientSDKConfig.json, 
{
    "authDelegate":{
        "clientSecret":"1234",
        "deviceSerialNumber":"1234",
        "refreshToken":"",
        "clientId":"1234",
        "deviceTypeId":"1234"
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"/home/pi/test/Database/",
     "alarmSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_01._TTH_.mp3",
     "alarmShortSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_01._TTH_.mp3",
     "timerSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_02._TTH_.mp3",
     "timerShortSoundFilePath":"/home/pi/test/res/med_system_alerts_melodic_02._TTH_.mp3"
   }
 }

**Comment by chesterkuo** [comment]
I got similar as in beginning, but I figure out this. Here is my case. (i'm using a EC2 instance and my local PC which is connect to intel directly without proxy and any router).

With AuthServer.py file default setting , it set as "app.run(host='127.0.0.1',port='3000')", which is mean it bind to ip=127.0.0.1 (local host) , but with some Linux platform security, this is mean port 3000 bind to localhost only. But you can change it to "0.0.0.0" , which is mean it will port and accept any connection to your AuthServer (py) with port 3000 (ex: http://public.ip:3000) and can be connected.

Second , with Authserver.py file , it have auth response set as "http://localhost:3000/authresponse" , I replace the "localhost" to my EC2 instance public ipv4 address.

The Allowed origin & Allowed return URL as show in (https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile) of security profile,   I add into following info:

"http://ec2-54-249-49-40.ap-northeast-1.compute.amazonaws.com:3000/" &
"http://ec2-54-249-49-40.ap-northeast-1.compute.amazonaws.com:3000/authresponse"

After then start Authserver.py file ,make sure it binding to port 3000 , then connect to "http://ec2-54-249-49-40.ap-northeast-1.compute.amazonaws.com:3000/"

You should see a browser message show this is success and can be closed.

**Comment by dylono96** [comment]
Thats how i filled it in as well, so I think it should be good satishc4u.
I will try your solution tomorrow and I will post my response here.

**Comment by dylono96** [comment]
![config](https://user-images.githubusercontent.com/20132281/29977302-3ee7b208-8f3d-11e7-9137-6c982a149840.PNG)
I changed my IP adress to 0.0.0.0:3000 and re added the adres in my security profile, but it still wont work.  
This is my config file.

**Comment by veeruice** [comment]
I am also facing similar problem. I m not getting pass the authorization. Do we just need the client Secret / client Id and deviceType ID alone and nothing else ? The deviceSerialNumber can be left empty or we have to fill in some default values ? (I tried both ways but didnt work). 

{
    "authDelegate":{
        "clientSecret":"684e****************************************************21b37",
        "deviceSerialNumber":"123456",
        "refreshToken":"",
        "clientId":"amzn1.application-oa2-client.****************************cf25ac66ed1",
        "deviceTypeId":"rasp***"
     },

   "alertsCapabilityAgent":{
     "databaseFilePath":"/home/pi/AVS_SDK/database/alerts.db",
     "alarmSoundFilePath":"/home/pi/Downloads/",
     "alarmShortSoundFilePath":"/home/pi/Downloads/",
     "timerSoundFilePath":"/home/pi/Downloads/",
     "timerShortSoundFilePath":"/home/pi/Downloads/"
   }
 }

Any help would be greatly appreciated.

Thanks

**Comment by chesterkuo** [comment]
I had all info inside authDelegate section , except "refreshToken".
There are two portion need to update (with my case) in AuthServer.py, 
For example:
1) app.run(host='0.0.0.0',port='3000')

2) redirectUri = 'http://xxxxx.xxx.xxx.xxx:3000/authresponse'

using ipv4 address instead of DNS hostname if you have NS resolved issue , both value need to have same info as AWS security profile defined.

Good lucks here.

**Comment by BennyAvramson** [comment]
Hi @yakov2006,

Did any of the above answers work for you?

Thanks,
Benny

**Comment by scotthea-amazon** [comment]
Hello yakov2006,

There has been no reply to this issue for several weeks, so I am closing the issue.  Please feel free to re-open it if It has been closed in error.

Thank you,
-SWH
