### ISSUE TITLE
macOS - how to enable wake word?

### ISSUE THREAD

**Issue by fedeblock** [alexa/avs-device-sdk#830]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Built the AVS-SDK, working properly.
## What is the expected behavior?

There is no wake word enabled
## What behavior are you observing?

per instructions, there are no guide for wake word setup.
## Provide the steps to reproduce the issue, if applicable:

Plain macOS avs-device-sdk install
### What version of the AVS Device SDK are you using?
      <x.y.z>
sdkVersion: 1.7.1

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [*] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @fedeblock,

Wake Word support for macOS can be enabled via Kitt.AI. The build options required for the SDK are [here](https://github.com/alexa/avs-device-sdk/wiki/Build-Options#kittai). The Kitt.AI libraries can be found [here](https://github.com/Kitt-AI/snowboy).

**Comment by fedeblock** [comment]
Thanks!
