### ISSUE TITLE
CapabilitiesDelegate should not link to Integration

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#832]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I notice the new component "CapabilitiesDelegate" is link to "Integration" in the file "Capabilitiesdelegation/src/CMakeList.txt":
```
target_link_libraries(CapabilitiesDelegate AVSCommon Integration ${CURL_LIBRARIES}) 
```
It should not link to Integration because "Integration" is not a core component in the AVS SDK. 

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @subjectxbj,

Thanks for pointing this out. We will fix this for a future release.

**Comment by kclchan** [comment]
This is fixed in the latest release of the SDK.  Thanks!
