### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by xuqifu** [alexa/avs-device-sdk#834]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @xuqifu,

This seems to have been accidentally opened incompleted. Can you provide a detailed description of the issue you are facing as well as which hardware/SDK version/OS you are using?

**Comment by xuqifu** [comment]
sdk version 1.7.0
i had installed curl-4.75 through arm-linux-gcc compiler. now check it.
#curl -I https://nghttp2.org/
  print error no  "ssl certificate " but l have certificate in /etc/ssl/certs

#curl -I https://nghttp2.org/ -k
print ok

**Comment by xuqifu** [comment]
hi @kjkh
sdk version 1.7.0
i had installed curl-4.75 through arm-linux-gcc compiler. now check it.
#curl -I https://nghttp2.org/
  print error no  "ssl certificate " but l have certificate in /etc/ssl/certs

#curl -I https://nghttp2.org/ -k
print ok

**Comment by kclchan** [comment]
Hi @xuqifu, your question is related to libcurl.  Did you try using the "--capath" to specify the path to the certs and see if it makes any difference.
If you have additional questions related to curl, I think this faq is a good resource:
https://curl.haxx.se/docs/faq.html
