### ISSUE TITLE
AVS : bash: startsample.sh: No such file or directory on raspberryPI W Zero

### ISSUE THREAD

**Issue by Raulpb49** [alexa/avs-device-sdk#835]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?
AVS should get install and startsample.sh should be able to run

## What behavior are you observing?

sudo bash startsample.sh
bash: startsample.sh: No such file or directory

## Provide the steps to reproduce the issue, if applicable:

I have followed the instruction from this [page](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script) 

I have lready created the device from the AVS console and have obtained the Client ID,Product Id and modified the config.txt

below is the content of config.txt 

DEVICE_SERIAL_NUMBER="123456"
CLIENT_ID="amzn1.application-oa2-client.620f892231a14c7ba14121dd27335d24" ( i have changed some digits here for the sake of posting it , to keep the anonymity )
PRODUCT_ID="my product id"

I ran this command : **### sudo bash setup.sh config.txt**
and get the below logs : 

After that when I ran : **### sudo bash startsample.sh**
I get : 
bash: startsample.sh: No such file or directory

<logs for the first command=>sudo bash setup.sh config.txt>
sudo bash setup.sh config.txt
################################################################################
################################################################################

AVS Device SDK Raspberry Pi Script - Terms and Agreements

The AVS Device SDK is dependent on several third-party libraries, environments, 
and/or other software packages that are installed using this script from 
third-party sources ("External Dependencies"). These are terms and conditions 
associated with the External Dependencies 
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that 
you need to agree to abide by if you choose to install the External Dependencies.

If you do not agree with every term and condition associated with the External 
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".

################################################################################
################################################################################
AGREE
################################################################################
Proceeding with installation
################################################################################
==============> INSTALLING REQUIRED TOOLS AND PACKAGE ============

Hit:1 http://archive.raspberrypi.org/debian stretch InRelease                                                        
Hit:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease                                                                     
Ign:3 http://ftp.de.debian.org/debian jessie InRelease                                                                               
Get:4 http://ftp.de.debian.org/debian jessie Release [148 kB]
Get:5 http://ftp.de.debian.org/debian jessie Release.gpg [2420 B]                                                                                                                                          
Ign:5 http://ftp.de.debian.org/debian jessie Release.gpg                                                                                                                                                   
Hit:6 http://ftp.de.debian.org/debian jessie/main armhf Packages                                                                                                                                           
Ign:6 http://ftp.de.debian.org/debian jessie/main armhf Packages                                                                                                                                           
Hit:7 http://ftp.de.debian.org/debian jessie/main Translation-en                                                                                                                                           
Ign:7 http://ftp.de.debian.org/debian jessie/main Translation-en                                                                                                                                           
Ign:6 http://ftp.de.debian.org/debian jessie/main armhf Packages                                                                                                                                           
Err:7 http://ftp.de.debian.org/debian jessie/main Translation-en                                                                                                                                           
  BZ2_bzread: /var/lib/apt/lists/partial/ftp.de.debian.org_debian_dists_jessie_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
Ign:6 http://ftp.de.debian.org/debian jessie/main armhf Packages                                                                                                                                           
Fetched 151 kB in 23s (6432 B/s)                                                                                                                                                                           
Reading package lists... Done
W: GPG error: http://ftp.de.debian.org/debian jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY CBF8D6FD518E17E1
W: The repository 'http://ftp.de.debian.org/debian jessie Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ftp.de.debian.org/debian/dists/jessie/main/i18n/Translation-en  BZ2_bzread: /var/lib/apt/lists/partial/ftp.de.debian.org_debian_dists_jessie_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_MAGIC)
E: Some index files failed to download. They have been ignored, or old ones used instead.
pi@raspberrypi:~ $ sudo bash startsample.sh
bash: startsample.sh: No such file or directory

### What version of the AVS Device SDK are you using?
      <x.y.z>
=> I followed the instructions. I think its not installed yet due to error above so cant tell the version.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
     RaspberryPI W Zero

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [X ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Raulpb49** [comment]
uname -a gives : Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l GNU/Linux

**Comment by kclchan** [comment]
Please note that as described in the setup guide, the guide is designed for Raspbian Stretch with Desktop.  But based on your logs, its seems you are running Raspbian Jessie instead.  Please try to upgrade to Stretch and try again.  Thanks.

**Comment by Raulpb49** [comment]
@kclchan thanks it worked ! 
I want to modify the scripts in a way so that my query can do the local jobs on the raspberry PI. 
e.g . Alexa set the GPIO XX High
Alexa send one to ten numbers on UART
Alexa open the camera
Kindly point me to the link where I can do so.
This is required for my home automation building project at college.
Many thanks in advance !
Rgds,
Rp

**Comment by Smanar** [comment]
I m on it ATM, and it's more complicated than you are thinking, Alaxe can't work localy, it's all cloudbased.
So for the classic way, you need to make your own skill, and make them to send request to a webserver on your raspberry.

**Comment by BennyAvramson** [comment]
Hi @Raulpb49,

As @Smanar mentioned, the way to do it is with [Alexa Skill](https://developer.amazon.com/alexa-skills-kit).

Thanks,
Benny

**Comment by Raulpb49** [comment]
Hello @BennyAvramson and @Smanar , thanks for the info. i was thinking to change that part where the audio is being played on the speakers.Just like that rpi will instead of (task1)playing the audio on the hw(hw1) do some task2 on hw2(hardware 2) since audio playing is done locally based on the commands given via speech. 
Also dont we have to rely on amazon echo or alexa devices to send command to rpi if we are using alexa skill?
Thnx
Rp

**Comment by Smanar** [comment]
I m not sure to understand. I suppose you have AVS on a raspberry like me.
The raspberry listen you and send audio file to Alexa server, the server process the audio and if you have custom skill, use them in the processing. From that it result an audio file that is send to raspberry to be played.
You only need 1 device (amazon echo or raspberry) and the alexa server.

IDK how you wana distinguish 1 command with another one with 2 audio file ?

The magic part is in the processing, it's the only part where you can do anything you want to do. Like send command to a webservice on your raspberry.

The return after the processing is almost useless for that you want to do.

**Comment by corincorvus** [comment]
Hi,
i tried to install all, but i have the same Problem. No "sampleapp.sh" in /home/pi/
i have raspbian buster, because i didnt find wheezy in the link or on raspberrypi.org.

may you have a solution?
