### ISSUE TITLE
Any real-time deregistration notification to AVS client ?

### ISSUE THREAD

**Issue by justy0714** [alexa/avs-device-sdk#836]
Hi, AVS team

AVS SDK Version: 1.8

We have developed an independent companion APP for users to interact with our Alexa enabled devices.
Users have also been instructed to register/deregister our Alexa enabled products with dedicated APP rather than Amazon Alexa APP.

However, users still can deregister an Alexa device via Amazon Alexa APP. While triggering a deregistration on Amazon Alexa APP, is there any deregistered notification sent to AVS client immediately to let AVS client inform companion APP  ?

In addition, as following link indicates "a user interaction on the Amazon Alexa app would trigger  ResetUserInactivity  directive", is it a good way to detect deregistration from Alexa APP by observing ResetUserInactivity  directive ? If not, could you advice us to achieve a better way to get real-time deregistration notification ? 

https://developer.amazon.com/docs/alexa-voice-service/system.html#resetuserinactivity

Best Regards,
Justy Huang

**Comment by kclchan** [comment]
Hi @justy0714,

ResetUserInactivity is not tied to deregistration. It is used to reset the timer that would signal a user being inactive (see https://developer.amazon.com/docs/alexa-voice-service/system.html#resetuserinactivity)

We are still improving the device deregistration experience. For now, please check the answer provided in #339. 

Thanks,
Kenneth
