### ISSUE TITLE
Cross compile the AVS Device SDK for iOS

### ISSUE THREAD

**Issue by 179992096** [alexa/avs-device-sdk#837]
## Briefly summarize your issue:
Cross compile the AVS Device SDK for iOS，I've compiled it，But I don't know how to use it，Because it doesn't have some .h files.

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ √] Other - tell us more:

**Comment by 179992096** [comment]
this is my cross compiled files:

https://pan.baidu.com/s/1f7DxR2MzL3mwZGnHNDXAVg

**Comment by 179992096** [comment]
Hi @kclchan  I don't how to use this Lib file, because add that file to Xcode project ，I can't find lib head file.

**Comment by kclchan** [comment]
Hi @179992096, sorry for not replying sooner.  The header files are in the folder where you put the SDK source code.  I think the first header file you should look at is:

`ApplicationUtilities/DefaultClient/include/DefaultClient/DefaultClient.h`

Also, you can use "make install" to install the headers and libraries files to your specified location.  Please rerun CMAKE with this option to specify your location:

`-DCMAKE_INSTALL_PREFIX=<location to where you want to install the files>`

Hope this helps!

Thanks,
Kenneth
