### ISSUE TITLE
AlexaCommsLib

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#841]
Hi AVS team,

We would like to enable AVS Comms function. (via -DCOMMS=ON -DCOMMS_LIB_PATH=<path-to-comms-lib> -DCOMMS_INCLUDE_DIR=<path-to-comms-include-dir>) 
Where to obtain AlexaCommsLib & CallManager related.

Many Thanks

**Comment by anu-mathur** [comment]
@aki29 Can you please fill out this [Contact Form](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268) and I'll get in touch with you?

**Comment by aki29** [comment]
OK Thanks
