### ISSUE TITLE
Talk to Alexa during TuneIn Playback

### ISSUE THREAD

**Issue by jimediaplayer** [alexa/avs-device-sdk#843]
We have ported AVS SDK Ver1.7 to our custom platform based on imx7D. We have built successfully and we could run Alexa also.

We asked Alexa to play from TuneIn. It said, getting the last tuneIn Station and started playing that station. We interrupted by asking a question. It went  to different states like Listening, Thinking and Speaking but the response was not heard. It was like muted.

After this, it resumed TuneIn playback.

We like to know though it got response for our question but it not speak out when we interrupted during TuneIn playback. Please check and advice.

**Comment by kclchan** [comment]
Hi @jimediaplayer, in order to investigate further, would you be able to attach the DEBUG9 logs.

You can enable DEBUG9 by running cmake with -DCMAKE_BUILD_TYPE=DEBUG and enabling DEBUG9 mode with $TZ=UTC ./SampleApp xxx/AlexaClientSDKConfig.json DEBUG9
Please capture the entire log and attach the file.

**Comment by jimediaplayer** [comment]
Hi,
Kindly find the attached log regarding issue mentioned above.
[TuneIn-AVS.txt](https://github.com/alexa/avs-device-sdk/files/2227565/TuneIn-AVS.txt)

**Comment by kclchan** [comment]
Hi @jimediaplayer, sorry for not getting back to you sooner, are you still seeing this issue.  The logs you provided doesn't contain the DEBUG9 logs.  But I remember some platforms are not able to play more than one sound simultaneously. Could you try adding a dmix plugin to your alsa: https://alsa.opensrc.org/Dmix
