### ISSUE TITLE
Streaming get stutter while playing iHeart Redio

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#846]
Hi AVS team,
 
SDK 1.8.1 on ARM based OpenWRT embedded linux.

We got several reports from users that streaming is stutter while playing radio, especially in the beginning streaming state.
It's reproducible in different area in states or other countries.

Here is a log for a this case :  Alexa, play W.B.Z from iHeart Radio
The media playback has short dropout for 5-10 seconds in beginning, then become stable and clear. 

My DSN is :  bb3651396a13455aaa600cd70b48cd89
You can see the UTC time stamp from the log.  Not sure if it's server's issue ?

And I found something different from other case, it seems the log for iHeart Radio is different from other, I can see may stopped / playing, maybe it's the root cause, but I have no idea of it.
Please help to check this case.

[WBZ_IHR.log](https://github.com/alexa/avs-device-sdk/files/2188354/WBZ_IHR.log)

**Comment by kclchan** [comment]
Hi @zeusshuang.

The shuttering depends on the radio station and the internet connection.  That being said, I've create an internal ticket to investigate if we can add additional buffering somewhere in the audio pipeline to alleviate the problem.

Thanks again for bringing this issue to our attention!

Thanks,
Kenneth

**Comment by kclchan** [comment]
This is fixed in v1.9.  Thanks for bringing this to our attention.
