### ISSUE TITLE
AVS SDK 1.6::Music streaming Barge-in use-case

### ISSUE THREAD

**Issue by adpandit** [alexa/avs-device-sdk#849]
We are seeing a considerable delay in receiving a STOP_CAPTURE when a user barges in with "Hey Alexa" but does not speak any phrase . 

Here is the use-case
1. Prime music is going on and User barges in by speaking "Hey Alexa". Alexa enters LISTENING state. 

Jul 13 06:16:57 apq8009 AlexaClientApp[1587]: ############################
Jul 13 06:16:57 apq8009 AlexaClientApp[1587]: #       Listening...       #
**Jul 13 06:16:57** apq8009 AlexaClientApp[1587]: ############################

2. Now user does not speak anything in the microphone. There is only silence. STOP_CAPTURE comes after considerable time

**Jul 13 06:17:03** apq8009 AlexaClientApp[1587]: 2018-07-13 06:17:03.117 [ 10] I DirectiveSequencer:onDirective:directive={"namespace\:"SpeechRecognizer"\,name\:"StopCapture"\,messageId\:"c2412e51-c1ac-4a77-9a66-2ece868ce81c"\,dialogRequestId\:"cc59eb6e-2600-4cad-b23d-d3aa0a4d6380"}

3. Now SDK goes into THINKING state but since there is no SPEAK directive the transitionFromThinkingTimedOut in DialogUXStateAggregator gets kicked in. This value is set to 5 seconds. 

**Jul 13 06:17:08** apq8009 AlexaClientApp[1587]: ########################################
Jul 13 06:17:08 apq8009 AlexaClientApp[1587]: #       Alexa is currently idle!       #
Jul 13 06:17:08 apq8009 AlexaClientApp[1587]: ########################################

Total time is 11 seconds (SDK delay time) before music has a chance to resume. Add a couple of seconds to restart the stream. Sometimes we have seen the STOP CAPTURE can take a considerable time to be received from the cloud. This is only when User barges in but does not SPEAK. 

Can we optimize the SDK further to match echo dot ~ roughly 6-7 seconds? It seems to me that SDK should not be going to THINKING considering that cloud would know nothing has been SPOKEN by the user, as there is no SPEAK. It should simply move to IDLE state.

**Comment by kclchan** [comment]
Hi @adpandit,

Thanks for bringing this issue into our attention.  Even though the cloud knows nothing is spoken, the device has no such knowledge and does not know if the last utterance would result in a SPEAK directive or not.  That is why the SDK has this transitionFromThinkingTimedOut timer so that it would transition back to idle state when no directives are received from AVS.

Hope this answers your question.

Thanks,
Kenneth

**Comment by adpandit** [comment]
Yes. Thank you for getting back to me. Looks like there is no way for us to reduce this timeout. 

Perhaps, in the later versions of the SDK, you can consider adding the enhancement for the device going back to IDLE state. Cloud can signal such a scenario.

Regards.

**Comment by BennyAvramson** [comment]
Hi @adpandit,

Thanks for your suggestion. We'll investigate it internally.

Thanks,
Benny
