### ISSUE TITLE
How can I config the asound.conf is well?

### ISSUE THREAD

**Issue by NyxRockchip2017** [alexa/avs-device-sdk#85]
It seems that playing book has some noise,How can I config the asound.conf is well?

**Comment by dhpp** [comment]
Hi there,

Could you give further details about your OS and runtime environment?  Here's a link to a resource I found online with respect to configuring ALSA via asound.conf, which will probably answer your question:

http://www.alsa-project.org/main/index.php/Asoundrc

Please let us know if it does not.

**Comment by NyxRockchip2017** [comment]
Thank you for your answer.My OS is linux based on kernel 3.10.
Does the sdk support bluetooth and speeches play at the same time.

**Comment by scotthea-amazon** [comment]
Hi NyxRockchip2017,
Bluetooth support has not yet been implemented for the avs-device-sdk.
Thanks,
-SWH
