### ISSUE TITLE
AVS abnormal after long-term iHeartRadio playing

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#855]
Hi AVS team,

SDK 1.8.0 .  ARM based OpenWRT embedded linux.

Attached a log from an overnight iHeartRadio station playing.
Finally the AVS cannot be waked up, and from the log, it seems the status is strange.
The streaming stopped playing and AVS cannot be waked up.

You can search keyword "onKeyWordDetected" in the log, it indicated user tried to wake AVS up (user said no response). I saw an error said "New audio provider can not override"

And you can search keyword like "Incoming new media item" , it's from display card and we dump it as a log to show a new station / song changed.
I can see the station is continue to stop / play / finish so quick (from display card).

Not sure if this issue is related to #727 or #747 .

[avs_dbg_log.zip](https://github.com/alexa/avs-device-sdk/files/2201757/avs_dbg_log.zip)

**Comment by BennyAvramson** [comment]
Hi @zeusshuang,

Looking on the error I mentioned above 
```
2018-07-16 22:07:43.613 [ 1e] E AudioInputProcessor:executeRecognizeFailed:reason=New audio provider can not override
```

It seems valid, as the SDK was in a listening mode and indeed I can see later the Speak directive resulted from the first user utterance
```
2018-07-16 22:07:53.048 [ 16] 0 EventBuilder:buildJsonEventString:messageId=91eff65f-63b8-47fa-bfc3-95e4ab886c2d,namespace=SpeechSynthesizer,name=SpeechStarted
```

Could you point at a timestamp in the logs where the error is occurring? 
Also, looking at your logs, I don't see any errors similar to #727. 

Thank,
benny

**Comment by zeusshuang** [comment]
Hi @BennyAvramson ,

If you search the keyword "Incoming new media item" (it's the log from display card while receive new music incoming), you can see the incoming music (station changes from iHeartRadio) is too quickly, but user said he just let it playing overnight, and finally the AVS is no response anymore.
We also see such behavior in our own test before and finally is also AVS stuck.
We are searching a quick reproduce way for this case, but it seems it's server site issue but let AVS goes into unknown blocking state ?

Regards,

**Comment by celinval** [comment]
Hi @zeusshuang,

Can you please clarify where in the code you have added the "Incoming new media item" log? I noticed that it is almost always followed by a "Media item ID" log. Are they related?

I'm asking because the ID is repeating multiple times.

Thanks

**Comment by zeusshuang** [comment]
Hi @celinval ,

We print the Media Item in function 'renderPlayerInfoCard' of  "SampleApp\src\GuiRenderer.cpp"
The "Media Item ID" in iHeartRadio case will be the same, but there is a number which will be increased while it plays next song or station.

Thanks,

**Comment by celinval** [comment]
Sorry @zeusshuang, 

I don't understand what's the problem with the "Incoming new media item". Is it the frequency that it gets called? The renderPlayerInfoCard is triggered to update the playing position as well as to update the music that's playing. I.e.: The renderPlayerInfoCard can be called while one song is playing and it does not indicate a song transition.

Can you please pinpoint what's the abnormal behavior and when (time in the logs) that the issue happened?

Thanks

**Comment by kclchan** [comment]
Hi @zeusshuang, do you still see this issue in the latest version of the SDK?  If not, would you mind if we close this issue?
