### ISSUE TITLE
SDK build error

### ISSUE THREAD

**Issue by bill-lzb** [alexa/avs-device-sdk#862]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I used the same steps as sdk v1.7.0 to build sdk 1.8.1, but error occurred.
## What is the expected behavior?

The build should be successful.
## What behavior are you observing?

The following error occurred:
AVS-Device-SDK-1.8.1/sdk-source/avs-device-sdk/SampleApp/src/KeywordObserver.cpp:44:24: error: ‘getEmptyESPData’ is not a member of ‘alexaClientSDK::capabilityAgents::aip::ESPData’
         auto espData = capabilityAgents::aip::ESPData::getEmptyESPData();
## Provide the steps to reproduce the issue, if applicable:

Just according to https://github.com/alexa/avs-device-sdk/wiki/Linux-Reference-Guide.
And I can build sdk v1.7.0.
### What version of the AVS Device SDK are you using?
      <1.8.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by BennyAvramson** [comment]
Hi @bill-lzb,

[ESPData.cpp](https://github.com/alexa/avs-device-sdk/blame/master/CapabilityAgents/AIP/src/ESPData.cpp#L27) does have `getEmptyESPData()` since v1.8.

Could you check if your **local copy** of the file has updated with this?

Thanks,
Benny

**Comment by bill-lzb** [comment]
Hi Benny

 

I run git clone git://github.com/alexa/avs-device-sdk.git, and downloaded the latest(1.8.1) AVS SDK.

And I checked ESPData.cpp, it has the following code:

const ESPData ESPData::getEmptyESPData() {

    static const ESPData emptyESPData{};

    return emptyESPData;

}

 

ZongbiaoLiao
