### ISSUE TITLE
No beep on start of request 

### ISSUE THREAD

**Issue by Dimmerworld** [alexa/avs-device-sdk#866]
## Briefly summarize your issue:

Recently installed this on my raspberry PI, everything else works fine besides the activation beep which is non-existent. When I try and turn it on in the app, it just switches off.
## What is the expected behavior?

I say Alexa and it should have a beep
## What behavior are you observing?

I say Alexa, no response but still completes request
## Provide the steps to reproduce the issue, if applicable:

1. install
2. Say Alexa andddd no beep sound 
### What version of the AVS Device SDK are you using?
      The latest at the time of this issue

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ * ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ * ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by Smanar** [comment]
I don't thnik there is sound by defaut, I haven't them too.
But take a look here https://developer.amazon.com/fr/docs/alexa-voice-service/indicate-device-state-with-sounds.html
