### ISSUE TITLE
Two issues while running Spotify

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#867]
Hi AVS team,
 
AVS SDK 1.8.1 ,  ARM based OpenWRT embedded Linux.

There are two issues while running Spotify.
1. While it set to DEBUG9, the streaming will get stutter, it seems the dump log issue. DEBUG5 is fine so far.
2. There is no display card supported while running spotify.

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang,

1- It is possible that the logs are affecting the audio quality. Usually, log statements are synchronized, so this could add an overhead to the media player thread. Do you see the same issue playing from a different source?
2- Do you mean in general or display cards related to spotify events?

Thanks,
Celina

**Comment by zeusshuang** [comment]
Hi @celinval ,

1. so far I only see this case on Spotify, other Music playing, Prime and other radio streaming looks fine.
2. the display cards like playing Prime Music, it will indicate the current song name and playing information. From the Amazon APP, it will display Spotify current playing information, so I think it should be put on display card event ?

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang, 

Thanks for the clarifications.

1. Please let us know if the same audio issue happens without logs and release build. As I mentioned, logs can cause performance degradation.
2. You are correct! Thanks for bringing this issue into our attention. I added your suggestion to our backlog.

Best,
Celina
