### ISSUE TITLE
How to  cross-compile and build the AVS Device SDK for ARM Devices

### ISSUE THREAD

**Issue by swathionchip** [alexa/avs-device-sdk#869]
Hi All,

How to  cross-compile and build the AVS Device SDK for ARM Devices in Linux system.
Thanks in Advance

Regards,
Swathi

**Comment by celinval** [comment]
Hi @swathionchip,

Try to include the following flags to your cmake configuration:

    -DCMAKE_CROSSCOMPILING=ON 
    -DCMAKE_TOOLCHAIN_FILE=<path to your toolchain file>

Please reopen the ticket if this doesn't work.

**Comment by avp24** [comment]
Hi All,

I am trying to cross compile and build AVS SDK for ARM Device using toolchain aarch64-linux-gnu-gcc-5. Using Ubuntu Reference guide I installed nghttp2 & libcurl oon my Host machine (Ubuntu 16.04) 
Toolchain file, Cmake command and its output is mentioned in the file attached herewith.
Now when I do make I get error like:
/home/ap/Desktop/VVDN_AVS/alexa/third-party/curl-7.54.0/lib/.libs/libcurl.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

[avs_sdk_arm_error.txt](https://github.com/alexa/avs-device-sdk/files/2392084/avs_sdk_arm_error.txt)
 

@swathionchip : Are you able to cross compile and AVS SDK for ARM Devices? Could you share your procedure.

Thanks.

**Comment by avp24** [comment]
@celinval I have compiled SampleApp for ARM. On executing SampleApp from the board I get below error:
(SampleApp:25804): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:25804): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-02 02:24:53.847 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

Am I missing any libraries?
Thanks!
