### ISSUE TITLE
Spotify command issue

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#877]
Hi AVS team,

SDK 1.8.1 , ARM based OpenWRT embeded linux.

I try the Spotify Music self-test. I found a strange issue while issue these commands:

Alexa, play amazon music.
Alexa, play spotify.
Alexa, stop music
Alexa, resume music.    ---> it will resume amazon music.
But, if I say: "Alexa, resume." it will resume the previous spotify music.
could you help to check your team if this behavior is expected ?

[Update 8/10]
By Spotify self-test. We found the section 1 case 7 and 9 are not working.
Alexa, play (or Alexa, play music)
Alexa, resume (or Alexa, resume music)
It will not play / resume Spotify but play iHeartRadio or Pandora automatically. (even I already set Spotify as preference music)

And section 1 case 14,  the "repeat all on" command is not working. ("repeat on" is okay)

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang,

Can you please double check on the alexa portal / alexa app that she understood "resume music"?

Thanks,
Celina

**Comment by zeusshuang** [comment]
Hi @celinval ,

This command is defined in AVS_SpotifyCertificationChecklist_4_03_2018 , item 9.
I checked Echo dot2, it's working as expected result. (i.e., it will resume Spotify correctly)

Regards,

**Comment by zeusshuang** [comment]
Hi @celinval ,

I would like to add another issue for this same verification test.
In section 3, item 1, My playlist.
Is there any limitation for the "play list" naming ?
We found a strange result.
If I named it's "my_playlist", and ask, Alexa, play my myplaylist from Spotify, it's working and play the list.
But if I named "script verification", it will say cannot fine the song "script verification" from Spotify. (I could make sure the wordings are recognized in history log).
Could you help to check your team and see if there is any naming limitation ?

Thanks,

**Comment by celinval** [comment]
Hi @zeusshuang, 

We were able to reproduce the spotify issue. I'll add to our backlog to fix the issue.

Regarding the name limitation, will it work if you say "Alexa, play script verification playlist from Spotify"?

Thanks

**Comment by zeusshuang** [comment]
Hi @celinval ,

Thanks for the feedback.
And yes, it's working for "Alexa, play script verification playlist from Spotify".
If it's the case, will it need to review the AVS test plan for Spotify ?

Thanks,

**Comment by zeusshuang** [comment]
Hi @celinval ,

I updated  the original issues report, please help to check it.

**Comment by kclchan** [comment]
Hi @zeusshuang, is this issue still valid?  If not, could we close this?

**Comment by zeusshuang** [comment]
I verified it on SDK 1.10 and it's working without problem.
We can close it now.
