### ISSUE TITLE
segmentation fault on step 'BUILDING SDK'

### ISSUE THREAD

**Issue by corentoulf** [alexa/avs-device-sdk#878]
Hi,

I'm trying to build AVS SDK on a Raspberry Pi and I get a segmentation fault at BUILDING SDK step.
I'm following the current Raspberry [tutorial](https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script) 

## What is the expected behavior?
The SDK should be building itself

## What behavior are you observing?
I get the following error, right after the setp.sh script starts step 'BUILDING SDK'

```
==============> BUILDING SDK ==============

setup.sh : ligne 215 : 12521 Erreur de segmentation  cmake "$SOURCE_PATH/avs-device-sdk" "${CMAKE_PLATFORM_SPECIFIC[@]}" -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH="$THIRD_PARTY_PATH/portaudio/lib/.libs/libportaudio.$LIB_SUFFIX" -DPORTAUDIO_INCLUDE_DIR="$THIRD_PARTY_PATH/portaudio/include" -DCMAKE_BUILD_TYPE=DEBUG

```

## Provide the steps to reproduce the issue, if applicable:
I followed the instructions detailed in the tutorial. I'm at the step : 

> Run the setup script with your configuration as an argument:
> sudo bash setup.sh config.txt

## Tell us about your environment:
Raspberry Pi 2 model B
running Raspbian GNU/Linux 9 (stretch)
audio soundcard : cirrus logic (wolfson)
I'm driving my Raspberry through ssh connection (the raspberry is in headless mode)

Thank you for your help.

**Comment by celinval** [comment]
Hi @corentoulf,

Thanks for moving your issue to this forum. Can you please provide the full output for the `setup.sh` execution? Can you also execute the commands below starting from the folder where you downloaded the `setup.sh` script and provide the output?

```
ls
cd build/
ls
cmake ../avs-device-sdk --debug-output \
    -DSENSORY_KEY_WORD_DETECTOR=ON \
    -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=../third-party/alexa-rpi/lib/libsnsr.a \
    -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=../third-party/alexa-rpi/include \
    -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON \
    -DPORTAUDIO_LIB_PATH="../third-party/portaudio/lib/.libs/libportaudio.a" \
    -DPORTAUDIO_INCLUDE_DIR="../third-party/portaudio/include" \
    -DCMAKE_BUILD_TYPE=DEBUG
```

Thanks

**Comment by corentoulf** [comment]
Hi @celinval ,

Here is the complete output of `setup.sh` followed by the commands you asked me to execute.
I precise that I commented the cloning part in `setup.sh` cause I already cloned it before.

[avs-sdk-build.txt](https://github.com/alexa/avs-device-sdk/files/2234747/avs-sdk-build.txt)

Thank your for your help

**Comment by celinval** [comment]
That's interesting. May I ask you which cmake version are you using?

Can you please rerun cmake using the command below to see if we can get a bit more information?

```
cmake ../avs-device-sdk --trace \
    -DSENSORY_KEY_WORD_DETECTOR=ON \
    -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=../third-party/alexa-rpi/lib/libsnsr.a \
    -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=../third-party/alexa-rpi/include \
    -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON \
    -DPORTAUDIO_LIB_PATH="../third-party/portaudio/lib/.libs/libportaudio.a" \
    -DPORTAUDIO_INCLUDE_DIR="../third-party/portaudio/include" \
    -DCMAKE_BUILD_TYPE=DEBUG
```

Thanks!

**Comment by corentoulf** [comment]
@celinval,

I decided to start on a fresh install of Raspbian Stretch as I was not able to obtain better results today.
It solved the issue.

The upgrade process from Jessie to Stretch may have break things somewhere...

Anyway, thank your for your quick support.
