### ISSUE TITLE
Snowboy build error

### ISSUE THREAD

**Issue by sajmplus** [alexa/avs-device-sdk#88]
Hi, 

i have problem with build sdk build. My cmake config:

`cmake ../avs-device-sdk -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/mkowalik/QtProjects/alexa/snowboy/lib/ubuntu64/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/mkowalik/QtProjects/alexa/snowboy/include -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/usr/local/lib/libportaudio.so -DPORTAUDIO_INCLUDE_DIR=/usr/local/include`

I'm getting following error:

> 
> Scanning dependencies of target KittAiKeyWordDetectorTest
> [ 70%] Building CXX object KWD/KittAi/test/CMakeFiles/KittAiKeyWordDetectorTest.dir/KittAiKeyWordDetectorTest.cpp.o
> In file included from /home/mkowalik/QtProjects/alexa/avs-device-sdk/KWD/KittAi/test/KittAiKeyWordDetectorTest.cpp:8:0:
> /home/mkowalik/QtProjects/alexa/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
> /home/mkowalik/QtProjects/alexa/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h:1421:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
> /home/mkowalik/QtProjects/alexa/avs-device-sdk/KWD/KittAi/test/KittAiKeyWordDetectorTest.cpp:353:5:   required from here
> /home/mkowalik/QtProjects/alexa/avs-device-sdk/ThirdParty/googletest-release-1.8.0/googletest/include/gtest/gtest.h:1392:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    if (lhs == rhs) {
>            ^
> [ 71%] Linking CXX executable KittAiKeyWordDetectorTest
> ../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ../src/libKITTAI.so: undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> collect2: error: ld returned 1 exit status

**Comment by sanjayrd** [comment]
Hi @sajmplus,

What compiler version are you using? Kitt.ai only releases certain versions of their binaries **publicly**, and we've found that only certain versions of GCC are compatible with building/linking Kitt.ai. If I recall correctly, certain higher versions of GCC couldn't link Kitt.ai properly. GCC 4.8.5 worked for me. If you need Kitt.ai for your specific compiler/toolchain, you can contact them to see what they can do.

Others were also having the same issue as you: https://github.com/Kitt-AI/snowboy/issues/99. There is a temporary fix in that issue that you can use as well if you are hesitant to change GCC versions.

Thanks,
Sanjay

**Comment by krisnaw** [comment]
Hi, I've got problem as well when running the cmake
`cmake $SDK_SRC -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=$LOCAL_BUILD/lib/libsnsr.a -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=$LOCAL_BUILD/include -DGSTREAMER_MEDIA_PLAYER=ON -DPORTAUDIO=ON
-DPORTAUDIO_LIB_PATH=$LOCAL_BUILD/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=$LOCAL_BUILD/include -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD`

**Comment by sajmplus** [comment]
I have installed gcc 5.4.0 and it is used as default.

Use of gcc-4.8 resolves problem. 

`CC=gcc-4.8 CXX=g++-4.8 cmake ../avs-device-sdk ...`
