### ISSUE TITLE
No automatically start on system boot in v1.6.0

### ISSUE THREAD

**Issue by iGodPhil** [alexa/avs-device-sdk#889]
## Briefly summarize your issue:
Hey,

I'm using the AVS Version 1.6.0 and get the following error message:

> alexa.service - Amazon Alexa
>    Loaded: loaded (/etc/systemd/system/alexa.service; enabled; vendor preset: enab
>    Active: failed (Result: exit-code) since Mon 2018-08-08 19:27:49 CEST; 1h 16min
>   Process: 2393 ExecStart=/home/pi/Programme/AlexaAutostart/alexa.sh (code=exited
>  Main PID: 2393 (code=exited, status=203/EXEC)
> 
> Jul 30 19:27:49 raspi systemd[1]: Started Amazon Alexa.
> Jul 30 19:27:49 raspi systemd[1]: alexa.service: Main process exited, code=exited,
> Jul 30 19:27:49 raspi systemd[1]: alexa.service: Unit entered failed state.
> Jul 30 19:27:49 raspi systemd[1]: alexa.service: Failed with result 'exit-code'.

I have modified the UserInputManager.cpp and recompiled.
This is my alexa.sh:

> #!bin/bash
> 
> sudo /bin/bash /home/pi/Programme/Alexa/startsample.sh

`sudo bash alexa.sh` works.
And this is my alexa.service:

> [Unit]
> Description=Amazon Alexa
> After=network.target network-online.target
> 
> [Service]
> Type=idle
> ExecStart=/home/pi/Programme/AlexaAutostart/alexa.sh
> WorkingDirectory=/home/pi/Programme/Alexa/build/SampleApp/src
> User=pi
> 
> [Install]
> WantedBy=multi-user.target

So what can I do?

## What is the expected behavior?
Is there a way to run SampleApp automatically on system boot?

## What behavior are you observing?
I've followed the step by step guid in #539 

### What version of the AVS Device SDK are you using?
      <1.6.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [X] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [X] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by mavamazon** [comment]
Hi!
Are you able to run the SampleApp as a standalone application using the same configuration?

**Comment by iGodPhil** [comment]
What do you mean with standalone Application?

‚sudo bash startsample.sh‘ or ‚sudo bash alexa.sh‘ works fine.

**Comment by iGodPhil** [comment]
Does anyone have an idea?

**Comment by mavamazon** [comment]
Hi!
In general SampleApp is not supposed to be run as a service and is provided for the reference on how to use SDK. If you still want to try to run it this way, @Arkadije, you may try to follow the steps from [this thread](https://github.com/alexa/avs-device-sdk/issues/539).
