### ISSUE TITLE
Stream sent to AVS cloud

### ISSUE THREAD

**Issue by shikha-bansal** [alexa/avs-device-sdk#89]
Is there a way I can playback the stream which is sent to the cloud when I ask a question to my device.
Is this stream available somewhere on the developer account ?

Thanks
Shikha

**Comment by dhpp** [comment]
Hi shikha-bansal,

Yes, we do provide this to end users.  Please go to https://alexa.amazon.com, then browse to Settings -> History (at the bottom of the screen) in the 'General' section.  From there you will see both the text that Alexa understood from the audio, and a link to the audio data that AVS received.  

Let us know if you have any further questions, thanks.
