### ISSUE TITLE
Wrong offset for playbackFinished when song ends

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#891]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Login with JP account and play music from my music library. play music is fine, but check the log information and found the offset is incorrect when the song play finished. May i know if this is a know issue?

## What is the expected behavior?

The offset should be correct when the song play finished.

## What behavior are you observing?

Checked the below log information:
line#927 start play music. 
line#1897: stop play music. 
line#2388: resume play music. 
line#3490 and line#3847: stop and play next music.
line#4747 and line#5124: stop and play previous music.
**line#14054: the music play finished, the offset is incorrect**
[offset_failed_log.txt](https://github.com/alexa/avs-device-sdk/files/2273450/offset_failed_log.txt)

## Provide the steps to reproduce the issue, if applicable:

1. play music from my music library.
2. after 15 seconds, stop play music.
3. after 15 seconds, resume play music.
4. after 15 seconds, next
5. after 15 seconds, previous. wait till the song ends, you can see the wrong offset .

### What version of the AVS Device SDK are you using?
      <1.8.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:  **OpenWrt**

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @BobXLiu , we have confirmed this issue and we are now working on a fix.
