### ISSUE TITLE
Alert / Alarm cannot stop correctly

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#893]
Hi AVS team,
 
AVS SDK 1.8.1.  ARM based OpenWRT embedded Linux.

There is a fail case while running Music and Alert / Alarm. Here are the steps and symptoms 

Alexa, play music   
Alexa, set timer for 1 minute.
(after timer is running)
Alexa, what time is it.
Alexa, what's the weather.
(some barge-in and Q&A,  it will stop alert tone and play TTS from server side)
Alexa, stop.  (stopped alert)
case 1: Music will resume.
case 2: Music will resume, but did not receive alert delete message.
case 3: Music and alert both stopped. and did not receive event to delete alert.

for case2 / case3, after DUT reboot and SDK is up, it will play alert tone again.

From the log, it seems it only stop audio player from the directive message, and never receive the message to delete / stop alert (but alert sound is actually stopped)

[avs_dbg_log2_timer_failed.log](https://github.com/alexa/avs-device-sdk/files/2277399/avs_dbg_log2_timer_failed.log)

**Comment by mavamazon** [comment]
HI!
Thank you for details! Can you please clarify what was actually playing when you say "Alexa, stop"? Was it music and alarm, Alexa speech and alarm or something else? In non-extended default SDK implementation music cannot play along with alerts, unless this music comes from Alexa's speech channel.

**Comment by zeusshuang** [comment]
Hi @mavamazon ,

mm .. from SDK 1.8.1, the alert
From my tests, after I asked "Alexa, stop", both Music and Alert tone stopped.

**Comment by zeusshuang** [comment]
Hi @mavamazon ,

You are correct. Sorry to make it confused. I revise my original report to make it clearly.
Normally, while alert is coming, the Music will stop and play alert tone.
And while asked Alexa, stop, it will stop alert and resume the music.
It's the working case.

But while I continue to barge-in during the alert tone playing, somehow SDK will not receive the alert delete message after finally "Alexa, stop" command. ( I expected it will stop alert first, and after reboot, it will continue to play alert tone)
It's not 100% reproducible, I got report from user to mention this case, so I tried to do these steps several times and got the fail log.

**Comment by mavamazon** [comment]
Not deleting an active alert after stopping it seems to be known behavior. Let me check if it was an intended behavior.

**Comment by visayamv** [comment]
Hi @zeusshuang , I am trying to figure the current state of your device when you said 'Alexa stop' and the AVS responded with a stop Audio player, but unfortunately, I'm missing the context states in the logs.

can you add DACSDK_EMIT_SENSITIVE_LOGS=ON to your cmake command line and reproduce the issue again?

Note that if you do enable sensitive logs, your logs may include information that you would not want to post publicly (e.g. configuration information used to authorize you client). So, you should be sure to scrub that kind of information before posting any such logs to this forum.
