### ISSUE TITLE
deviceId

### ISSUE THREAD

**Issue by aki29** [alexa/avs-device-sdk#895]
Hi AVS team,

How to get deviceId (such as amzn1.ask.device.AFZxxxxxx) in device sdk.

Our ASK would like to Identify which one device is using ASK service and send response message from our cloud server to this one

Many Thanks

**Comment by aki29** [comment]
Hi kjkh,

Yes, the deviceId on System Context object which was acquired from ASK Response is my require. Can I get the same deviceId with AVS C++ SDK ?

Thanks

**Comment by kjkh** [comment]
Closing ticket. If you have any further questions, please feel free to re-open.

**Comment by aginesh** [comment]
Hi @aki29,
    How did you finally manage with your requirement of getting the deviceId? I am also having a similar requirement as yours. Any details you could provide would be very helpful.

Thanks.
