### ISSUE TITLE
Audible book does not play, voice response saying "i am having trouble to play the book"

### ISSUE THREAD

**Issue by georgeyao310012** [alexa/avs-device-sdk#899]
My app is based on SDK v1.7.1, with media player ported to gstreamer v1.10.
The SampleApp works well with functions of authentication, playing music and displaying display cards.
But it encounters trouble playing audible book, there's voice directive telling "i am having trouble to play the book". 

I got console output as attached, can't explain why, 

1. the status changing from  IDLE -> LISTENING -> THINKING -> SPEAKING -> IDLE -> SPEAKING -> IDLE -> SPEAKING -> IDLE ..
2. when would alexa response " having trouble to play the book " ? any media format handling capability missed ? (MP4)

I'm using device with Linux 4.4, gstreamer 1.10, plugins installed.
The device is ARM based, with audio output via HDMI connecting to TV.

[audible book.txt](https://github.com/alexa/avs-device-sdk/files/2286234/audible.book.txt)

**Comment by kjkh** [comment]
Hi @georgeyao310012,

When attempting to access the Audible content, there was an error related to SSL certificates:

_2018-08-14 08:29:24.288 [ 1a] E LibCurlHttpContentFetcher:curlEasyPerformFailed:error=Peer certificate cannot be authenticated with given CA certificates_

It is interesting that there was no authentication failure. Do you see this with other music providers? Can you check your SSL certificates, and perhaps try using a different one?

**Comment by georgeyao310012** [comment]
Thank you for the reply,

Yes, it's strange that no failure with authentication or any other things. Tried other audio services, like music and radio works well, but failed with Audible book.

We tried different certificates, as described in tickets of: 
https://github.com/alexa/avs-device-sdk/issues/452, 
with ticket downloaded from url of https://curl.haxx.se/docs/caextract.html.

Things does not change.
Any other possible suspects, or test I can do to further investigate on the issue ?

**Comment by georgeyao310012** [comment]
Thanks for the help.

It's because we use the right CA for authorization, but that CA is not correctly used while setting up HTTPS connection while trying to access audible services.

It works now. 

So this ticket could be closed.
