### ISSUE TITLE
AuthServer errors on initial auth

### ISSUE THREAD

**Issue by ytn3rd** [alexa/avs-device-sdk#90]
I've gone through the instructions for setting this up on my RPi3 up until I run the AuthServer. (EDIT: I am using a fresh install of the latest version of Raspbian Jessie, 2017-07-05-raspbian-jessie, not latest version of Raspbian from their site (Stretch) which I had seen others have issues with)

> pi@fishpi:~/BUILD $ python AuthServer/AuthServer.py 
> The refresh request failed with the response code 400. This might be due to a bad refresh token or bad client data. We will continue with getting a refresh token, discarding the one in the file.
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
>     msg = self.format(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
>     return fmt.format(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
>     msg = msg % self.args
> TypeError: %d format: a number is required, not str
> Logged from file _internal.py, line 87

I get this error and now browser automatically opens. I assume the error is more of a warning because refreshToken was not set in the AlexaClientSDKConfig.json?

I manually navigated to http://localhost:3000, get redirected to Amazon and login, click Okay on the next accepting of security profile window, but then I get

> We're sorry!
> An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Something I found odd with this is that the [instructions](https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile) say to setup https:// for the allowed origins and callback, however if I try to use https I get an ERR_SSL_PROTOCOL_ERROR error. I did also update my security profile is to include both http and https versions  for callback and allowed origins.

Within AlexaClientSDKConfig.json clientSecret and clientId are correct copied from the site with no additional spaces in them. deviceTypeId is my value which amazon lists as Product ID which I believe to be correct. deviceSerialNumber and refreshToken are both empty strings. All of the values in alertsCapabilityAgent are still empty strings.

Going to http://localhost:3000 outputs 
> 127.0.0.1 - - [20/Aug/2017 12:56:23] "GET / HTTP/1.1" 302 -
In my console which I believe to be correct as its doing a redirect.

Going to https://localhost:3000 outputs 
> 127.0.0.1 - - [20/Aug/2017 12:56:50] code 400, message Bad request syntax ('\x16\x03\{other things like this I removed as I am unsure if its private or not')

One other thing that I found interesting was when I changed my deviceTypeId to what the web dashboard says is my Amazon ID I got the exact same error, so almost as though my original credentials are wrong but I am unsure how they can be.

**Comment by kaitco** [comment]
Check if your time/date and timezone is correct. I had the same problem.

**Comment by ytn3rd** [comment]
Installed ntpdate and forced it to a manual sync (via [this](https://raspberrypi.stackexchange.com/questions/8231/how-to-force-ntpd-to-update-date-time-after-boot) SO post)
Updated timezone to be Melbourne Australia and re-synced time to be sure.

Still the same error.

**Comment by DrJukka** [comment]
I'm now stuck at the exactly same place. I did though use the same product successfully with Ubuntu machine earlier, but with Raspberry I do get stuck. So incase you did find solution, please update it here as well

**Comment by mradulan** [comment]
please check if allowed origin and allowed return URL is http://localhost:3000 and http://localhost:3000/authresponse respectively.

**Comment by scotthea-amazon** [comment]
Hello ytn3rd and DrJukka,

It looks like this issue has probably been resolved (answered and not further activity for a long time).  I am closing this issue.  If I have closed this in error, please feel free to re-open it.

Best regards,
-SWH
