### ISSUE TITLE
Gnu C++ 7.x fails building with missing #include <functional>

### ISSUE THREAD

**Issue by brett-lynnes** [alexa/avs-device-sdk#908]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
see: #396 , same problem with the newly added bluetooth code in BlueZ/GVariantMapReader.h and BlueZ/GVariantTupleReader.h

## What is the expected behavior?
AVS should compile with -BLUETOOTH_BLUEZ on my system

## What behavior are you observing?
failure to build with:

`
In file included from /home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/BlueZUtils.h:21:0,
                 from /home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/src/DBusConnection.cpp:18:
/home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/GVariantTupleReader.h:115:23: error: ‘std::function’ has not been declared
     bool forEach(std::function<bool(GVariant* value)> iteratorFunction) const;
                       ^~~~~~~~
/home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/GVariantTupleReader.h:115:31: error: expected ‘,’ or ‘...’ before ‘<’ token
     bool forEach(std::function<bool(GVariant* value)> iteratorFunction) const;
                               ^
In file included from /home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/BlueZUtils.h:22:0,
                 from /home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/src/DBusConnection.cpp:18:
/home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/GVariantMapReader.h:112:23: error: ‘std::function’ has not been declared
     bool forEach(std::function<bool(char* key, GVariant* value)> iteratorFunction) const;
                       ^~~~~~~~
/home/lynnes/AVS/avs-device-sdk/BluetoothImplementations/BlueZ/include/BlueZ/GVariantMapReader.h:112:31: error: expected ‘,’ or ‘...’ before ‘<’ token
     bool forEach(std::function<bool(char* key, GVariant* value)> iteratorFunction) const;
                               ^
BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/build.make:206: recipe for target 'BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/DBusConnection.cpp.o' failed
make[2]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/DBusConnection.cpp.o] Error 1
CMakeFiles/Makefile2:3890: recipe for target 'BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/all' failed
make[1]: *** [BluetoothImplementations/BlueZ/src/CMakeFiles/BluetoothImplementationsBlueZ.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`
## Provide the steps to reproduce the issue, if applicable:
Ubuntu 18.x with Gnu C++ 7.3 and attempt to compile with -BLUETOOTH_BLUEZ (and some other included header hasn't already `#include <functional>`, possibly my installation of bluez-5.29 differs)

if you add `#include <functional>` to these files, the build succeeds:
BluetoothImplementations/BlueZ/include/BlueZ/GVariantMapReader.h
BluetoothImplementations/BlueZ/include/BlueZ/GVariantTupleReader.h

### What version of the AVS Device SDK are you using?
1.8.1

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kjkh** [comment]
Hi @brett-lynnes,

Thanks for bringing this to our attention. It will be fixed in a future release.

**Comment by scotthea-amazon** [comment]
Hello brett-lynnes,

Release 1.10 includes a change to fix this problem.  If you can, please let us know if it is fixed for you.

Thank you,
-SWH

**Comment by EpicIntegratedSystems** [comment]
Found a fix for me

`sudo apt-get install libsbc-dev`

Worked for ubuntu 16.04
