### ISSUE TITLE
Getting current clock/time through SDK

### ISSUE THREAD

**Issue by ankurawl** [alexa/avs-device-sdk#91]
Does the AVS SDK enable getting the precise Alexa Clock/Time? We want to display the current time on the device. We also want to use this time to manage local countdown of Alexa reminders/timers.

**Comment by JamieMeyers** [comment]
No, the AVS API does not help you with time synchronization. Please use NTP (Network Time Protocol) or some other time protocol to help ensure your device clock is correct.

The alerts time comes in using the ISO-8601 format, specifically RFC 3339 (and in UTC), so you can use this and your clock time to manage a local countdown.
