### ISSUE TITLE
"Alexa... how do you make chocolate chip cookies?" make alexa enter into loop 

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#915]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
1. I ask question: "Alexa... how do you make chocolate chip cookies?"
2. The unit answer: "OK, for chocolate chip cookies,I recommend J chocolate chip cookies, you can ask for more information or more recipe, see you next.". 
3. Then the unit is wakeup by the answer again, and replay  "OK, for chocolate chip cookies,I recommend J chocolate chip cookies, you can ask for more information or more recipe, see you next." again.
4. Loop to 3 again.

When I ask "alexa, what is your name", it also enter into similar loop. 

This issue can be reproduced on both 1.6 and 1.7.1. Does that mean "Cloud based WW Verification" is not working?

## What is the expected behavior?
The unit should change to idle after response.

### What version of the AVS Device SDK are you using?
      1.6 and 1.7.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more: Arm7

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more: AlpineLinux

**Comment by zeusshuang** [comment]
Hi @subjectxbj ,

I try your case and it seems your example is an interaction case ? The final answer the Alexa ask you to say "Next", if you say Next, it will say another recipe .. and if you say No, it will stop ..

**Comment by subjectxbj** [comment]
Hi @zeusshuang,
Thanks for your clarification. Yeah. That is the case.

**Comment by zeusshuang** [comment]
Hi @subjectxbj ,

No, you case seems AEC issue. your MIC should filter out self audio output.

**Comment by subjectxbj** [comment]
Thanks @zeusshuang . Yes that is my understanding as well.
