### ISSUE TITLE
Does offline alarm stop require a new Sensory Model?

### ISSUE THREAD

**Issue by subjectxbj** [alexa/avs-device-sdk#916]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I noticed the SDK 1.8 has introduced the offline alarm stop, but it requires that sensory need to recognize the new command. Does that mean we need a new sensory model file which can recognize this command? 

Thanks

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @subjectxbj , unfortunately Sensory does not support offline local stop. There is no Sensory model for "Alexa stop". There is no plan on supporting this at this stage

**Comment by subjectxbj** [comment]
Thanks
