### ISSUE TITLE
About Alexa certification

### ISSUE THREAD

**Issue by willnien** [alexa/avs-device-sdk#917]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

We would like to know whether it will block Alexa certification. If our product have third party local voice command with different trigger word, is it ok to apply to ALlexa certification?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: MT8516

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @willnien , only "Alexa" wake word is accepted.

https://developer.amazon.com/docs/alexa-voice-service/speechrecognizer.html#speechrecognizer-context

**Comment by willnien** [comment]
Hi @visayamv , thanks.

**Comment by visayamv** [comment]
Hi @willnien , I'm closing this issue. Please reopen if you have any more questions regarding this
