### ISSUE TITLE
[Window10] bash setup.sh config.txt Error

### ISSUE THREAD

**Issue by jessonwtp** [alexa/avs-device-sdk#918]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Step by step in https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script
But Error occurs when execute : bash setup.sh config.txt
-------------------------------------------------------------------------
cc1plus.exe: all warnings being treated as errors
make[3]: *** [AVSCommon/CMakeFiles/AVSCommon.dir/build.make:258: AVSCommon/CMakeFiles/AVSCommon.dir/AVS/src/EventBuilder.cpp.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:1367: AVSCommon/CMakeFiles/AVSCommon.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:8294: SampleApp/src/CMakeFiles/SampleApp.dir/rule] Error 2
make: *** [Makefile:2138: SampleApp] Error 2
-------------------------------------------------------------------------

## What is the expected behavior?

Should be no Error

## What behavior are you observing?

Shows Make Error

## Provide the steps to reproduce the issue, if applicable:

Step by step in https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script

### What version of the AVS Device SDK are you using?
      <x.y.z> v1.8.1 released 07/09/2018

### Tell us what hardware you're using:
- [*] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [*] Other - tell us more:Win10 64bit

**Comment by guruprasad363** [comment]
I am also facing the same problem. But I am using Windows 8.1.

**Comment by visayamv** [comment]
Hi @jessonwtp , can you try one of the following:

1. Disable the specific warning by appending -Wno-class-memaccess after -Werror (or equivalent for other compilers).
The build options file is located at <AVS_SDK_SOURCE_DIR>/build/cmake/BuildOptions.cmake.

2. Upgrade to the newest version of RapidJSON.
This can be done by navigating into <AVS_SDK_SOURCE_DIR>/ThirdParty/rapidjson, and cloning the new version of the RapidJSON source directory there. Then you need to modify <AVS_SDK_SOURCE_DIR>/ThirdParty/rapidjson/CMakeLists.txt and replace rapidjson-1.1.0 with the name of the new RapidJSON source directory.

**Comment by jessonwtp** [comment]
Hi @visayamv,
Many thanks for your comments, Now I can pass the setup and run alexa.
=================================================
1.Upgrade to the newest version of RapidJSON. 
   Get new version in : https://github.com/Tencent/rapidjson
   And replace the older version in /ThirdParty/rapidjson as you mentioned.
2.Then I Update Pacman again.
