### ISSUE TITLE
Need suggestion

### ISSUE THREAD

**Issue by itsani4u** [alexa/avs-device-sdk#919]
I am getting following error in Android Studio while trying to build the app:

Error:A problem occurred configuring project ':aace'.
> executing external native build for cmake /home/user/Documents/aac-sdk-1.0/platforms/android/aace/CMakeLists.txt

I am have followed guldelines from below links:

https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide

https://github.com/alexa/aac-sdk/blob/1.0/builder/BuildWithCMake.md

https://github.com/alexa/aac-sdk/tree/1.0/samples/android

Ubuntu 16.04 Android Studio 3.0.1, NDK 17.1 ,Android SDK Platform 26

Any help will be appreciated.

**Comment by visayamv** [comment]
Hi @itsani4u , the error seems to be related to Alexa Auto SDK, please request assistance from their team: https://github.com/alexa/aac-sdk

**Comment by itsani4u** [comment]
Hi @visayamv  My goal is to build Alexa Auto Sample app.
But while do so, CMakelist.txt of Android Platform code throwing error.

Could you please help me with the steps for build Android Sample app with NDK.

**Comment by visayamv** [comment]
Hi @itsani4u , the particular error  you mentioned:

Error:A problem occurred configuring project ':aace'.

is Alexa Auto SDK related which we don't maintain.
