### ISSUE TITLE
Spotify - the 'next' command fail

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#921]
Hi AVS team,

SDK 1.8.1 , ARM based embedded linux.

A fail case found while running spotify self test.

Steps and Symptom -
1. To editor a play list, input at least 2 songs in the list. (or play a exist playlist station is okay)
2. Play the a playlist from Spotify APP and cast to AVS SDK direclty. (or voice command to play song)
3. It will play the songs from the 1st item in the playlist
4. Issue voice command "Alexa, next", it will play next song.
5. while it's at the last song, while I asked the "next", it will play the last song again.  Compared with Echo, it will play from the beginning from the playlist.

from the log, it seems log "noNextTrackFound" , not sure if it's the cause.

[spotify_next_failed.log](https://github.com/alexa/avs-device-sdk/files/2316954/spotify_next_failed.log)

**Comment by visayamv** [comment]
Hi @zeusshuang , in my test, on step #5, it just continues to play the last song (i.e. it didn't start from the beginning). 

SDK issues 'next' to Spotify and it receives noNextTrack so SDK did not play anything.

If you want to loop it from the beginning, you have to enable "Repeat" in spotify (the button with 2 circular arrows).

After enabling this, when you say next on the last 'song' it will go to the first one.

**Comment by visayamv** [comment]
@zeusshuang , is this test part of the certification? can you give me the specific test item for this one with the expected results?

**Comment by zeusshuang** [comment]
Hi @visayamv ,

No, I think it's not part of the certification case for this steps. (AVS Spotify Certification Check list 4_03_2018)

The case only include the "Next" command -
Alexa, Next
Alexa, Next Song
Alexa, Next track
Alexa, skip

But I guess this issue was just found by the tester and issued a bug @@

**Comment by visayamv** [comment]
Thanks @zeusshuang. I'll investigate further on this, but from the looks of it, there maybe issue on the cloud side

**Comment by zeusshuang** [comment]
Hi @visayamv ,

maybe SDK issue , you will see the symptom is that if its in the final song, if it's still in the middle of the song, the "next" will only continue the current long.

**Comment by priyagsenthil** [comment]
Hi zeusshaung,

So the behavior seen from the device looks per AVS spec which suggests checking metadata of next track before calling next into the eSDK.

For echo and 1P devices when the Next directive is received they do not check for the metaData of the next track. They always call the eSDK to play the next track  which probably plays the first track resulting in the asymmetric behavior.

We will check with AVS team what is the expected behavior for this use case and get back to you on our findings.

Thanks
Priya

**Comment by kclchan** [comment]
Hi @zeusshuang, I am closing this issue now as I believe it has been resolved.  Please reopen it if it's closed in error.  Thanks!
