### ISSUE TITLE
directiveBeingPreHandled=(nullptr),description=stateChangeTimeout

### ISSUE THREAD

**Issue by xuqifu** [alexa/avs-device-sdk#922]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <1.8.1>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:
arm cortexA9

### Tell us about your OS (Type & version):
- [ y] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by visayamv** [comment]
Hi @xuqifu , can you provide the debug9 logs? It might be related to the last issue you submitted [Issue 911](https://github.com/alexa/avs-device-sdk/issues/911) as it contains the same error message

**Comment by dhpp** [comment]
Hi @xuqifu - could you please provide a description of the exact issue you are looking for assistance with in this ticket?  Just to make sure we are focusing on the right thing.  Thanks.
