### ISSUE TITLE
 E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by wangxiaohu2016** [alexa/avs-device-sdk#923]
I tried to porting AVS 1.7.0 to my ARM(the libc version is 2.19, GCC/G++ version is 4.9.x) Linux board.
I got the  error:
 E HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Peer certificate cannot be authenticated with given CA certificates
the CA file I used in libcurl is from Raspberry Pi (/etc/ssl/certs/ca-certificates.crt), it was OK on Raspberry Pi.
What is the expected behavior?
it should start SampleApp successfully.

What behavior are you observing?
Failed to connect to AVS!

### What version of the AVS Device SDK are you using?
1.7.0

### Tell us what hardware you're using:
ARMV7

### Tell us about your OS (Type & version):
- [ ] Linux
Could please help me? Thanks a lot.

**Comment by dhpp** [comment]
Hi @wangxiaohu2016, thanks for reporting this.  I believe this was seen earlier in #166 - could you take a look there and let us know if it resolves your issue?  Thanks.

**Comment by wangxiaohu2016** [comment]
Hi @dhpp :
     Yes, I tried it, but it still can't work. I used  --with-ca-path=/etc/ssl/certs in curl's confingure, the /etc/ssl/certs was from Raspberry Pi, and also I used sf-class2-root.crt from https://aws.amazon.com/cn/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/ (*Note :.....The certificate can be downloaded from here), but still can't work.
      Becasue it is the new hardware board, does it need to do the Amazon CTS test.

**Comment by wangxiaohu2016** [comment]
Hi Amazon engineer:
       Any feadback?

**Comment by wangxiaohu2016** [comment]
Here is my error log for 'HttpPost:doPostFailed:reason=curl_easy_performFailed,result=60,error=Peer certificate cannot be authenticated with given CA certificates'
[caErrorLog.txt](https://github.com/alexa/avs-device-sdk/files/2334763/caErrorLog.txt)

**Comment by kclchan** [comment]
Hi @wangxiaohu2016, it seems like your Linux board does not contain the correct ATS CAs.  Please take a look at this forum post:
https://forums.developer.amazon.com/articles/130944/update-certificate-authorities-for-your-avs-client.html, you may use https://avs-ats-cert-test.amazon.com to verify if your device's trust store has the correct ATS CAs.

For example, If you are using libcurl in the SampleApp, you can try to run "curl -v https://avs-ats-cert-test.amazon.com" on your device and see if you are able to establish the connection.

If not, please follow the directions under section "What to do if the Amazon Trust Services CAs are not in your trust store" in https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority

**Comment by visayamv** [comment]
Hi @wangxiaohu2016 , I'm closing this issue, but feel free to reopen if you're still having problems. Thanks
