### ISSUE TITLE
iHeartRadio is not currently available in your region

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#924]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When I tell alexa to play iHeartRadio, I get the reponse like iHeartRadio is not currently available in your region, but alexa can play iHeartRadio if I use another account in the same device and network.

## What is the expected behavior?

alexa play iHeartRadio as told 

## What behavior are you observing?

get reponse like iHeartRadio is not currently available in your region

### What version of the AVS Device SDK are you using?
      1.8.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more:  Embedded Systems

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ *] Other - tell us more: Linux kernel 4.4.35

**Comment by bennyAv10** [comment]
Hi @DonghuaZheng,

According to [iHeartRadio](https://help.iheart.com/hc/en-us/articles/228919427-Is-iHeartRadio-available-in-my-country-) only some regions are supported.

The region is determined by the setting of the Amazon account. The previous account you used was probably configured to one of the enabled iHeartRadio regions.

Thanks,
Benny

**Comment by DonghuaZheng** [comment]
I got it,  Thanks!
