### ISSUE TITLE
SampleApp failed to start

### ISSUE THREAD

**Issue by sajmplus** [alexa/avs-device-sdk#93]
Hi,

I followed readme instructions. I'm building like that:
`CC=gcc-4.8 CXX=g++-4.8 cmake ../avs-device-sdk -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/usr/local/lib/libportaudio.so -DPORTAUDIO_INCLUDE_DIR=/usr/local/include -DGSTREAMER_MEDIA_PLAYER=ON`

Make ends without errors, next i'm trying to run SampleApp:
`TZ=UTC ./SampleApp ../../Integration/AlexaClientSDKConfig.json DEBUG9`

And get following error:

> Running app with log level: DEBUG9
> 2017-08-21 10:17:37.422 [  1] I ConfigurationNode:initializeSuccess
> 2017-08-21 10:17:37.433 [  1] E AlertsCapabilityAgent:initializeAlertsFailed::could not load sqlite file path.
> 2017-08-21 10:17:37.433 [  1] E AlertsCapabilityAgent:initializeFailed::Could not initialize alerts.
> 2017-08-21 10:17:37.433 [  1] E AlertsCapabilityAgent:createFailed:reason=Initializion error.
> 2017-08-21 10:17:37.433 [  1] E RequiresShutdown:~RequiresShutdownFailed:reason=notShutdown,name=AlertsCapabilityAgent
> 2017-08-21 10:17:37.433 [  1] E DefaultClient:initializeFailed:reason=unableToCreateAlertsCapabilityAgent
> 2017-08-21 10:17:37.433 [  1] I DirectiveSequencer:doShutdown
> Failed to create default SDK client!
> 
> (SampleApp:29946): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
> 2017-08-21 10:17:38.405 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed
> 
> (SampleApp:29946): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
> 
> (SampleApp:29946): GLib-CRITICAL **: Source ID 14 was not found when attempting to remove it
> 
> (SampleApp:29946): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
> 2017-08-21 10:17:38.405 [  2] E MediaPlayer:doStopFailed:reason=gstElementGetStateFailed
> 
> (SampleApp:29946): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed
> 
> (SampleApp:29946): GLib-CRITICAL **: Source ID 18675600 was not found when attempting to remove it
> Failed to initialize SampleApplication
> Failed to create to SampleApplication!

Some tests also fails:

> 97% tests passed, 16 tests failed out of 473
> 
> Total Test time (real) = 184.11 sec
> 
> The following tests FAILED:
> 	367 - MediaPlayerTest_test (Failed)
> 	368 - MediaPlayerTest.testStartPlayWaitForEnd (Failed)
> 	369 - MediaPlayerTest.testStartPlayForUrl (Failed)
> 	371 - MediaPlayerTest.testConsecutiveSetSource (Failed)
> 	372 - MediaPlayerTest.testStartPlayWaitForEndStartPlayAgain (Failed)
> 	373 - MediaPlayerTest.testStopPlay (Failed)
> 	374 - MediaPlayerTest.testStartPlayCallAfterStopPlay (Failed)
> 	375 - MediaPlayerTest.testPauseDuringPlay (Failed)
> 	376 - MediaPlayerTest.testPlayAfterPause (Failed)
> 	377 - MediaPlayerTest.testStopAfterPause (Failed)
> 	378 - MediaPlayerTest.testPauseAfterPause (Failed)
> 	379 - MediaPlayerTest.testResumeAfterPause (Failed)
> 	380 - MediaPlayerTest.testResumeAfterPlay (Failed)
> 	381 - MediaPlayerTest.testGetOffsetInMilliseconds (Failed)
> 	382 - MediaPlayerTest.testPlayingTwoAttachments (Failed)
> 	383 - MediaPlayerTest.testUnsteadyReads (Failed)
> Errors while running CTest

**Comment by sajmplus** [comment]
Resolved.

I have to insert paths to sounds and database in AlexaClientSDKConfig.json:

```
"alertsCapabilityAgent":{
        "timerShortSoundFilePath":"/home/med_system_alerts_melodic_02_short._TTH_.wav",
        "alarmSoundFilePath":"/home/med_system_alerts_melodic_01._TTH_.mp3",
        "databaseFilePath":"/home/alerts.db",
        "timerSoundFilePath":"/home/med_system_alerts_melodic_02._TTH_.mp3",
        "alarmShortSoundFilePath":"/home/med_system_alerts_melodic_01_short._TTH_.wav"
}
```

You can download sounds here: https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/alexa-voice-service-ux-design-guidelines#attention

Database file will be created automatically if not exist.

**Comment by baddemiya** [comment]
how to enable debug9??
