### ISSUE TITLE
1.9 avs-device-sdk: Error in building SampleApp alone 

### ISSUE THREAD

**Issue by sumit3817** [alexa/avs-device-sdk#931]
Hello AVS Team,

I need to build my SampleApp alone. Can you please share the cmake file changes for the for the new release 1.9. 

I am able to build SampleApp seperately in version 1.8.

There is Authorization folder added in the new release 1.9. Can you please share the CMake file changes for the Authorization folder so that SampleApp can be build seperately.

Version - 1.9
OS - Ubuntu Linux

Thanks and Regards,
Sumit

**Comment by bennyAv10** [comment]
Hi @sumit3817,

Please post here the `cmake` and `make` commands you're running alongside the output from those commands.

Also, are you following the [Ubuntu-Linux-Quick-Start-Guide](https://github.com/alexa/avs-device-sdk/wiki/Ubuntu-Linux-Quick-Start-Guide)?

Thanks,
Benny

**Comment by kclchan** [comment]
Hi @sumit3817, Could you check in SampleApp/src/CMakeLists.txt if you have add CBLAuthDelegate in target_link_libraries?

e.g.
`
target_link_libraries(SampleApp 
...
    CBLAuthDelegate
...
)
`

**Comment by sumit3817** [comment]
Yes, it was added.

**Comment by sumit3817** [comment]
Now, I am facing the issue with portaudio.
The logs of cmake are:-

-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'AlexaClientSDK'
--   found AlexaClientSDK, version 1.9.0
-- checking for module 'portaudio-2.0'
--   package 'portaudio-2.0' not found
CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  src/CMakeLists.txt:3 (pkg_check_modules)


-- Configuring incomplete, errors occurred!

**Comment by kclchan** [comment]
Hi @sumit3817, for the portaudio error, is this something made yourself in cmake?  By default, the SDK uses some CMAKE options to set the libraries and include path for portaudio:

i.e. PORTAUDIO_LIB_PATH and PORTAUDIO_INCLUDE_DIR

**Comment by sumit3817** [comment]
Hi,
I have move forward and now facing the issue with Application Media Player:-
Here are the logs:-

[ 92%] Building CXX object src/CMakeFiles/Simplifi_Alexa.dir/SampleApplication.cpp.o
In file included from /home/harman/1.9_Alexa/sdk-source/Simplifi_Alexa/src/SampleApplication.cpp:18:0:
/home/harman/1.9_Alexa/sdk-source/Simplifi_Alexa/include/SampleApp/SampleApplication.h:117:55: error: ‘ApplicationMediaPlayer’ was not declared in this scope
     using MediaPlayerCreateFunction = std::shared_ptr<ApplicationMediaPlayer> (*)(
                                                       ^
/home/harman/1.9_Alexa/sdk-source/Simplifi_Alexa/include/SampleApp/SampleApplication.h:117:77: error: template argument 1 is invalid
     using MediaPlayerCreateFunction = std::shared_ptr<ApplicationMediaPlayer> (*)(

**Comment by sumit3817** [comment]
Hello AVS Team,

Thanks for your support. 
Now I am able to build Sample app alone. 
You can close this issue.

**Comment by onny** [comment]
@sumit3817 can you please share your build files? I'm facing the same issue.

**Comment by onny** [comment]
Okay I was able to fix this, see https://github.com/alexa/avs-device-sdk/issues/368
