### ISSUE TITLE
How to test LPCM and opus audio format with my own mediaplayer

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#937]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I implement MediaPlayer with my own mediaplayer instead of GStremer, but I don't how to confirm whether my own mediaplayer can play LPCM  and opus audio or not. I want know which situation that AVS can give the directive with payload which has LPCM and opus audio source.
## What is the expected behavior?

I want  whether my own mediaplayer can play LPCM and opus audio format or not
## What behavior are you observing?

I don't know how test my own mediaplayer with LPCM and opus audio format
### What version of the AVS Device SDK are you using?
      1.8.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more: Embeded system

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bennyAv10** [comment]
Hi @DonghuaZheng,

You can check supported music formats by music provider [here](https://developer.amazon.com/docs/alexa-voice-service/recommended-media-support.html#music-service-provider-msp-audio-formats).

Why not testing the required formats locally with unit\integration stesting?

Thanks,
Benny

**Comment by DonghuaZheng** [comment]
Hi @bennyAv10 
    Is the unit\integration stesting which you said in MediaPlayer/test directory? But the test code in that directory  is based on GStreamer, can I replace the GStreamer interface with my own mediaplayer interface? If I do that , the test result is valid or not?

 Thanks,
DonghuaZheng

**Comment by bennyAv10** [comment]
Hi @DonghuaZheng,

My intention was you'll implement your own testing before trying different music providers for this. You can take a look on [MediaplayerTest.cpp](https://github.com/alexa/avs-device-sdk/blob/master/MediaPlayer/GStreamerMediaPlayer/test/MediaPlayerTest.cpp) as a reference.

Thanks,
Benny

**Comment by DonghuaZheng** [comment]
@bennyAv10 I see, Thanks
