### ISSUE TITLE
Log is getting big

### ISSUE THREAD

**Issue by theskyliner** [alexa/avs-device-sdk#938]
## Briefly summarize your issue:
Via the following command I'm starting alexa in the background on my raspberry 3.
The result is an `alexa.log` file which size is increasing by 1MB every second.
```
sudo nohup bash startsample.sh &>/home/pi/alexa.log &
```

Sooner or later it's so big, that the 8GB SD Card is full.
Actually I wanted to have a log file, so I can check another problem.
Alexa works like a charm on start, but she stops working after some hours. Maybe it's the same problem, because there is no size left on the SD Card.

I guess even a bigger SD Card will not solve the problem, because the log is bigger and bigger.

How do you guys handle this?
I tried to empty the file via cronjob every 15 minutes, but because the script is reading and writing the file, I guess the cronjob cannot erase its data. When I remove it via cronjob and create it afterwards, the alexa scrip in the background crashes.

Guess the `startsample.sh` uses DEBUG logging, so maybe there is a type of logging with fewer content?

Would love to get some help, because I really enjoy this project!

### What version of the AVS Device SDK are you using?
      v1.9

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bennyAv10** [comment]
Hi @theskyliner,

The start script starts the sampleApp with Debug9 enabled. You can minimize the debug level by removing this argument from the script (`startsample.sh`).

Please let me know if that solves the issue.

Thanks,
Benny

**Comment by kclchan** [comment]
Hi @theskyliner, I think you can take a look at #539, the discussion in that issue should help you with starting the script in the background.

**Comment by visayamv** [comment]
Hi @theskyliner , I'm closing this issue, but feel free to reopen if you're still having problems. Thanks
