### ISSUE TITLE
Failed to create to SampleApplication!

### ISSUE THREAD

**Issue by ignaciosalia** [alexa/avs-device-sdk#944]
Hi, At trying to create SampleApplication I get this:

2018-09-05 18:34:10.114 [  1] I sdkVersion: 1.9.0
configFile Integration/AlexaClientSDKConfig.json
2018-09-05 18:34:10.155 [  1] C SampleApplication:Creation of AuthDelegate failed!
2018-09-05 18:34:10.155 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

What can be causing this issue?

**Comment by bennyAv10** [comment]
Hi @ignaciosalia,

Usually it means something is wrong in AlexaClientSDKConfig.json file.
What platform are you running? What guide did you follow for the installation? Please make sure all details are correct.

If the issue persist, please rerun the SampleApp with `debug9` enabled (Add `debug9` to the end of the command), and post the log messages here.

Thanks,
Benny

**Comment by ignaciosalia** [comment]
Hi, 
I'm running ubuntu 18.04.1 LTS, and follow the Ubuntu installation guide

I check the AlexaClientSDKConfig.json, and every look ok; I attched the log message it says is an error with
 "2018-09-06 00:02:44.296 [  1] E SQLiteUtils:openSQLiteDatabaseHelperFailed::Could not open database.:rcode=14,file path=/home/ignacio/sdk-folder/application-necesiies/cblAuthDelegate.db,error message=unable to open database file
2018-09-06 00:02:44.296 [  1] E SQLiteUtils:createSQLiteDatabaseFailed::Could not create database.
2018-09-06 00:02:44.296 [  1] E SQLiteDatabase:initialize::Database could not be created.:file path=/home/ignacio/sdk-folder/application-necesiies/cblAuthDelegate.db"
[SampleAppFailMessage.txt](https://github.com/alexa/avs-device-sdk/files/2354994/SampleAppFailMessage.txt)


Thank Ignacio

**Comment by ignaciosalia** [comment]
Hi @bennyAv10 

I can run the SampleApp now I only have an unrecoverable capabilities API error, and go direct to Limited Mode

 
Thanks, 
Ignacio

**Comment by bennyAv10** [comment]
Hi @ignaciosalia,

Please attach the log messages related to the new issue.

Thanks,
Benny
