### ISSUE TITLE
Android Quick Start Guide Supported version

### ISSUE THREAD

**Issue by yeolrim** [alexa/avs-device-sdk#946]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I found that the Android Quick Start Guide is available for API 23+.

 Why isn't it available for API22 (lollipop). Alexa auto can use the API22.
(https://github.com/alexa/aac-sdk/blob/1.1/samples/android/README.md)

As I know alexa auto uses avs, and I think you have to provide the same api.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop 
- [ ] Raspberry Pi
- [v ] Other - tell us more: android device

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [v ] Other - tell us more: android 5.1

**Comment by yeolrim** [comment]
Thank you for your answer.

**Comment by rjajra** [comment]
@bennyAv10 I've tried to setup in android 5.1.1 armv7-a with ndk16b and API_LEVEL=23, but sample app failing to load..

#bash startsample.sh 
WARNING: linker: /data/SampleApp: unused DT entry: type 0x6ffffffe arg 0x1db64
WARNING: linker: /data/SampleApp: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libDefaultClient.so: unused DT entry: type 0x6ffffffe arg 0x1f1cc
WARNING: linker: libDefaultClient.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libCapabilitiesDelegate.so: unused DT entry: type 0x6ffffffe arg 0x1cdd0
WARNING: linker: libCapabilitiesDelegate.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libCBLAuthDelegate.so: unused DT entry: type 0x6ffffffe arg 0x185f8
WARNING: linker: libCBLAuthDelegate.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libESP.so: unused DT entry: type 0x6ffffffe arg 0x1850
WARNING: linker: libESP.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libAndroidSLESMediaPlayer.so: unused DT entry: type 0x6ffffffe arg 0x1adc8
WARNING: linker: libAndroidSLESMediaPlayer.so: unused DT entry: type 0x6fffffff arg 0x7
WARNING: linker: libAlerts.so: unused DT entry: type 0x6ffffffe arg 0x47480
WARNING: linker: libAlerts.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libBluetooth.so: unused DT entry: type 0x6ffffffe arg 0x2d270
WARNING: linker: libBluetooth.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libInteractionModel.so: unused DT entry: type 0x6ffffffe arg 0x12a78
WARNING: linker: libInteractionModel.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libNotifications.so: unused DT entry: type 0x6ffffffe arg 0x26dac
WARNING: linker: libNotifications.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libAudioResources.so: unused DT entry: type 0x6ffffffe arg 0x6d58
WARNING: linker: libAudioResources.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libPlaybackController.so: unused DT entry: type 0x6ffffffe arg 0x13a88
WARNING: linker: libPlaybackController.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libSpeakerManager.so: unused DT entry: type 0x6ffffffe arg 0x2102c
WARNING: linker: libSpeakerManager.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libSpeechSynthesizer.so: unused DT entry: type 0x6ffffffe arg 0x265b4
WARNING: linker: libSpeechSynthesizer.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libSettings.so: unused DT entry: type 0x6ffffffe arg 0x1ce84
WARNING: linker: libSettings.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libCertifiedSender.so: unused DT entry: type 0x6ffffffe arg 0x10a84
WARNING: linker: libCertifiedSender.so: unused DT entry: type 0x6fffffff arg 0x1
WARNING: linker: libTemplateRuntime.so: unused DT entry: type 0x6ffffffe arg 0x1c1f8
WARNING: linker: libTemplateRuntime.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libAudioPlayer.so: unused DT entry: type 0x6ffffffe arg 0x28710
WARNING: linker: libAudioPlayer.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libExternalMediaPlayer.so: unused DT entry: type 0x6ffffffe arg 0x22d80
WARNING: linker: libExternalMediaPlayer.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libAVSSystem.so: unused DT entry: type 0x6ffffffe arg 0x277cc
WARNING: linker: libAVSSystem.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libContextManager.so: unused DT entry: type 0x6ffffffe arg 0x137c8
WARNING: linker: libContextManager.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libACL.so: unused DT entry: type 0x6ffffffe arg 0x28428
WARNING: linker: libACL.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libSQLiteStorage.so: unused DT entry: type 0x6ffffffe arg 0x85a8
WARNING: linker: libSQLiteStorage.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libsqlite3.so: unused DT entry: type 0x6ffffffe arg 0x4904
WARNING: linker: libsqlite3.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libRegistrationManager.so: unused DT entry: type 0x6ffffffe arg 0x670c
WARNING: linker: libRegistrationManager.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libAIP.so: unused DT entry: type 0x6ffffffe arg 0x277a8
WARNING: linker: libAIP.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libADSL.so: unused DT entry: type 0x6ffffffe arg 0x13d24
WARNING: linker: libADSL.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libAFML.so: unused DT entry: type 0x6ffffffe arg 0x1ead0
WARNING: linker: libAFML.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libAndroidUtilities.so: unused DT entry: type 0x6ffffffe arg 0x9174
WARNING: linker: libAndroidUtilities.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libPlaylistParser.so: unused DT entry: type 0x6ffffffe arg 0x132e0
WARNING: linker: libPlaylistParser.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libAVSCommon.so: unused DT entry: type 0x6ffffffe arg 0x66ca8
WARNING: linker: libAVSCommon.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libcurl.so: unused DT entry: type 0x6ffffffe arg 0x3658
WARNING: linker: libcurl.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libavcodec.so: unused DT entry: type 0x6ffffffe arg 0x5ea4
WARNING: linker: libavcodec.so: unused DT entry: type 0x6fffffff arg 0x4
WARNING: linker: libavutil.so: unused DT entry: type 0x6ffffffe arg 0x6b84
WARNING: linker: libavutil.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: libavformat.so: unused DT entry: type 0x6ffffffe arg 0x67b4
WARNING: linker: libavformat.so: unused DT entry: type 0x6fffffff arg 0x5
WARNING: linker: libswresample.so: unused DT entry: type 0x6ffffffe arg 0xe0c
WARNING: linker: libswresample.so: unused DT entry: type 0x6fffffff arg 0x3
WARNING: linker: libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2c06c
WARNING: linker: libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: libssl.so.1.1: unused DT entry: type 0x6ffffffe arg 0x8b7c
WARNING: linker: libssl.so.1.1: unused DT entry: type 0x6fffffff arg 0x2
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: libcrypto.so.1.1: unused DT entry: type 0x6ffffffe arg 0x2aadc
WARNING: linker: libcrypto.so.1.1: unused DT entry: type 0x6fffffff arg 0x1
CANNOT LINK EXECUTABLE DEPENDENCIES: cannot locate symbol "__poll_chk" referenced by "libcrypto.so.1.1"...
