### ISSUE TITLE
CAN NOT hear response while playing a song

### ISSUE THREAD

**Issue by DiazSo** [alexa/avs-device-sdk#947]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

There is no response output while playing a song.
## What is the expected behavior?

I expect : when my device is playing a song, then keyin "t" to start new query, then my device should play the response from AVS, and then continue playing the song
## What behavior are you observing?

1. send the command "sing a song"
2. my device will start to play a song
3. send the command "what day is today"
4. then there is no response output and there maybe no song output, too.
## Provide the steps to reproduce the issue, if applicable:

1. send the command "sing a song"
2. my device will start to play a song
3. send the command "what day is today"
4. then there is no response output and there maybe no song output, too.
### What version of the AVS Device SDK are you using?
      <x.y.z>
<1.9.0>
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [X ] Other - tell us more:
my MIPS embedded platform 

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bennyAv10** [comment]
Hi @DiazSo,

For looking further into the issue you're experiencing, please run the sampleApp with debug9 enabled (Add `debug9` to the end of the command) and post the log messages here.

Thanks,
Benny

**Comment by DiazSo** [comment]
Hi Benny,
the attached is the log data. In advance, I add a message output in gst-plugins-base-1.10.5/ext/alsa/gstalsasink.c, function gst_alsasink_write() to check how many bytes will be wrote into sound card.
the test steps:
1. 't' the line 293, then the 1st command is "sing a song"
2.  the gst pipeline will start to play the song
3.  the message "** Message: GST R 3840" is print out
3. the 2nd 't' is in line 1319, the 2nd command is "what day is today"
4. then the message "** Message: GST R xxxx" does NOT print out after the buffering percent is 100
5. after the message "Alexa is currently idle" is printed out, then you could see the message "** Message: GST R 3840" is print out again. it is playing the song

The issue is : CAN NOT hear response while playing a song
[alexa_sampleapp.txt](https://github.com/alexa/avs-device-sdk/files/2360387/alexa_sampleapp.txt)


it seems there is no audio data be wrote into sound card when my device receive the  response of 2nd command.

Thanks!
Diaz

**Comment by bennyAv10** [comment]
HI @DiazSo,

Looking on the log messages it seems AVS speech did played and then music has been resumed:

```
2018-09-07 08:51:43.185[  4]9 SpeechSynthesizer:onPlaybackStarted:callbackSourceId=2
.
.
.
###########################
#       Speaking...       #
###########################
2018-09-07 08:51:45.009[ 13]0 EventBuilder:buildJsonEventString:messageId=72b7723f-44c4-4ea6-a7dc-f9c965367378,namespace=SpeechSynthesizer,name=SpeechFinished
.
.
.
2018-09-07 08:51:45.219[ 12]1 AudioPlayer:executeOnFocusChanged:action=resumeMediaPlayer
```
Haven't you heard this particular Alexa response?

Thanks,
Benny

**Comment by DiazSo** [comment]
Hi Benny,

Yes, I do NOT hear the response from AVS. Since the message " Message: GST R xxxx" does not print out. I know that you mentioned above.  I have added the message in gst-plugins-base-1.10.5/ext/alsa/gstalsasink.c, function gst_alsasink_write(), but when "AudioPlayer:executeOnFocusChanged:action=resumeMediaPlayer", the message does not print out. Do you have any idea?

Best Regards,
Diaz

**Comment by DiazSo** [comment]
Hi Benny,

the new log is sampleapp log disabled and I enable GST log. You could check the line 269 that is the 2nd query while my device is playing the song. In line 306, the APPSrc is sending EOS. Then it will enter EOS state, there is no audio wrote into sound card. The information of CAP between the song and the response from AVS is different, one is 2 channel and another is 1 channel. But the GST pipe does not re-init, is it possible workable? 
[alexa_sampleapp_1.txt](https://github.com/alexa/avs-device-sdk/files/2366419/alexa_sampleapp_1.txt)

**Comment by kclchan** [comment]
Hi @DiazSo, I remember seeing a similar issue before and it was due to the platform not being able to play more than one sound simultaneously.  Could you try adding a dmix plugin to your alsa: https://alsa.opensrc.org/Dmix

**Comment by DiazSo** [comment]
Hi @kclchan ,
Yes, I try to use dmix plugin, then it can work.
Thanks!

**Comment by kclchan** [comment]
Hi @DiazSo, glad that it's working for you now.  Please feel free to re-open it if it has been closed in error.
