### ISSUE TITLE
Support GnuTLS

### ISSUE THREAD

**Issue by the-nic** [alexa/avs-device-sdk#95]
Currently, the device SDK compares the OpenSSL version from curl in `HTTP2Transport.cpp` with a hardcoded OpenSSL version. This however, is incompatible if curl is compiled with another ssl library, e.g. GnuTLS, which returns a version string like "GnuTLS/3.5.14".

Would it be possible to support other ssl libraries, too? Curl currently supports quite a few ssl libs: https://curl.haxx.se/docs/ssl-compared.html

**Comment by dhpp** [comment]
Hi there, thanks for bringing this to our attention.  We agree, this should at least be optional, and we will investigate making an appropriate change for our next release.

In the meantime, if you remove the line:

add_definitions("-DACSDK_OPENSSL_MIN_VER_REQUIRED=${OPENSSL_MIN_VERSION}")

from ACL/src/CMakeLists.txt

then this will no longer affect you.
