### ISSUE TITLE
Question Regarding Internet Disconnect

### ISSUE THREAD

**Issue by jpatu001** [alexa/avs-device-sdk#951]
Hi AVS team,

I have a question regarding how the sdk should handle internet disconnects. I'm using SDK 1.8.1 in embedded linux and raspberry pi 3(for testing comparison). How can I use the sdk to handle commands when internet is disconnected? Here's a log of the device's behavior when disconnected, line 242 is when it's disconnected and asked "Alexa what's the weather" [log.txt](https://github.com/alexa/avs-device-sdk/files/2362061/log.txt)

In the echo dot, if I say "Alexa what's the weather?" while the internet is disconnected(wifi router disconnected), it listens for a while then says something like "I can't connect to the wifi". However on the embedded unit(and even in rpi3 running same sdk 1.8.1) the command triggers a listening state and just stays there for a couple of minutes then goes straight to idle. It takes 5 minutes before it checks for connection. So in those 5 minutes, calling Alexa will result in multiple listening->idle state. After 5 minutes the connection gets checked then we get to the connecting state.

I've tried decreasing DEFAULT_TEST_PERIOD from InternetConnectionMonitor from 5 minutes to 1 minute to run the testConnection() more frequently, this helps us in putting visual cues(red LEDs) to notify of no connection but that is still not fast enough. I've tried putting less than a minute and I think it still took a minute to get something in onConnectionStatusChanged(). I've also tried changing the timeout time in HTTP2Transport, and this sure did made it much faster in detecting internet disconnection. Meaning I can get from idle state to connecting state as fast as a few seconds(depending on timeout time I set) and elminating the listening->idle state. However I'm wondering if there's a better way of checking disconnects and changing the states accordingly. 

I guess my question here is: Is there a way for us to determine(or run a ping/ or check connection) when in Listening state so that disconnects can be detected without the need of frequent polling/ pinging(and without that case where it stays in listening state for a few minutes)? What I'm trying to do here is implement the same reaction that the echo dot does(which I think is: go to listening state, realize that there's no connection to the server, then play a clip saying there's no internet connection). 

Thanks, 
jpatu001

**Comment by bennyAv10** [comment]
Hi @jpatu001,

The best way to improve the dis-connectivity awareness of the device is by integrating it with the OS/HW. So, whenever a disconnection occurs, the SDK will get notified and update the state to disconnected.

Decreasing  DEFAULT_TEST_PERIOD to 1 minutes is still not fast enough and also consumes resources from the device.

Please let me know if that answers your questions.

Thanks,
Benny

**Comment by jpatu001** [comment]
@bennyAv10  yes that answers my question. By implementing a OS/HW specific program to detect disconnection from the internet, how will I be able to relay that info to the sdk? Relay in a sense that how can I inform the SDK so that it will perform the appropriate steps of such disconnection such as changing state to connecting, and notifying observers of connection status changed.

Thanks

**Comment by jpatu001** [comment]
Follow up question, I was looking at the ACL HTTP2Transport.cpp and I saw one of the default timeout define in that file is only 30 seconds(STREAM_PROGRESS_TIMEOUT which is used for streamProgressTimedout). Is this function responsible for timing out of listening state when there's no connection to the avs server? I just saw that in the logs that I attached above, it took more than 30 seconds before I got the streamProgressTimedout.

**Comment by kclchan** [comment]
Hi @jpatu001, the STREAM_PROGRESS_TIMEOUT is used to set the time allowed for a particular message request to not see network activity before the message is considered to have timed out.

You may implement the InternetConnectionMonitorInterface interface using a OS/HW internet monitor to more quickly detect disconnection from the internet.  And with this, since your application knows that it's not connected to the internet, inside KeywordObserver::onKeyWordDetected(), you can put in the necessary visual/audio cues indicating device is no longer connected to the internet.

Hope this helps!
