### ISSUE TITLE
what is difference between  audio codec AAC-LC and LC-AAC？

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#955]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When read Recommended Media Support in Alexa Voice Services Docs， I found AAC-LC and LC-AAC audio codec in Music Service Provider (MSP) Audio Formats，like picture blow：
![image](https://user-images.githubusercontent.com/23712268/45397826-54cd4380-b674-11e8-8192-d72a4c7db062.png) 
I don't know what the difference between AAC-LC and LC-AAC.
I want to know the difference between AAC-LC and LC-AAC becasue I implemented MediaPlayer with my own mediaplayer, so I want to fix out whether my own mediaplayer support AAC-LC and LC-AAC or not？
In my opinion， AAC-LC and LC-AAC are same audio codec， mean Low Complexity ACC, am I right?

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @DonghuaZheng, I believe AAC-LC and LC-AAC  are the same. I am double checking with the team and will correct them.  Thanks for bringing this to our attention.

**Comment by DonghuaZheng** [comment]
@kclchan thanks
