### ISSUE TITLE
what is audio codec ACC？

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#957]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

When read Recommended Media Support in Alexa Voice Services Docs， I found ACC audio codec in Audio Containers，like picture blow：
![image](https://user-images.githubusercontent.com/23712268/45398854-69133f80-b678-11e8-8a9c-bf390ca4d3a3.png)
I don't know what ACC is and can't find information about it.
I want to know what ACC is becasue I implemented MediaPlayer with my own mediaplayer, so I want to fix out whether my own mediaplayer support ACC or not？
Thanks!
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @DonghuaZheng, I believe this is a typo and should be AAC.  I am double checking with the team and will correct it ASAP.  Thanks for bringing this to our attention!

**Comment by DonghuaZheng** [comment]
Hi, @kclchan Thanks!
