### ISSUE TITLE
The alarm does not ring at scheduled time when the network is disconnected

### ISSUE THREAD

**Issue by BobXLiu** [alexa/avs-device-sdk#959]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After set an alarm success, disconnect from the network, the alarm does not ring at scheduled time
## What is the expected behavior?

Disconnect from the network, the alarm should sound
## What behavior are you observing?

please check the log information:
[alarm_not_sound_after_disconnect.txt](https://github.com/alexa/avs-device-sdk/files/2374281/alarm_not_sound_after_disconnect.txt)

## Provide the steps to reproduce the issue, if applicable:

1. Login AVS and set an alarm(not timer).
2. disconnect from the network.
3. the alarm does not ring at scheduled time.

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: **OpenWrt**

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @BobXLiu, It's one of the known issues in v1.9 and will be fixed in our next software release.  Thanks!

**Comment by subjectxbj** [comment]
@kclchan Is this a new bug introduced in 1.9? I remember there is not such issue in 1.6.

**Comment by kclchan** [comment]
Hi @subjectxbj, yes, it's a new issue introduced in v1.9.

**Comment by dhpp** [comment]
We have addressed this now in in our recent 1.10 release.  Thanks again for bringing this to our attention.
