### ISSUE TITLE
Running avs always ties up the mic, stopping other apps from access the mic (especially on Android)...

### ISSUE THREAD

**Issue by wjennings** [alexa/avs-device-sdk#963]
## Briefly summarize your issue:
We run this on our Android device (among others), and we are only using push-to-talk.  However, the mic was always capturing via AVS, and no-one else was able to use the mic (no android apps, etc.).  This is not acceptable to us, and it would be great if there was an option to only enable the mic when required.

## What is the expected behavior?
If there was an option to only create and enable the mic when required, it would alleviate this issue.
We had to make changes such that the microphone was only created and used when "listening" (in this case by passing the openSlEngine to UIManager and calling createMicrophoneRecorder() and startStreamingMicrophoneData() since the create function opens the mic). And close the mic when thinking (mic_wrapper.reset()).

## What behavior are you observing?
No other apps can use the mic if the avs program is running.

## Provide the steps to reproduce the issue, if applicable:
run avs on android.  Try to use the mic on another Android application, it fails to open.

### What version of the AVS Device SDK are you using?
      1.9 running on Android 

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x ] Other - tell us more: 

### Tell us about your OS (Type & version):
- [x ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by kclchan** [comment]
Hi @wjennings, thank you for this suggestion. We will look into adding it for a future release of the SDK.  Thanks!

**Comment by PattenKuo** [comment]
@kclchan Hi,  Have you added this feature for a future release of the SDK? if added, could you please tell me the version of the SDK?
Thx.

**Comment by PattenKuo** [comment]
Could anyone else help me?
thanks.

**Comment by wjennings** [comment]
@PattenKuo I mentioned how I resolved the issue.  You can do the same.  Just work with it a bit, you'll get it.  I don't have time to offer more details.  To recount:

> We had to make changes such that the microphone was only created and used when "listening" (in this case by passing the openSlEngine to UIManager and calling createMicrophoneRecorder() and startStreamingMicrophoneData() since the create function opens the mic). And close the mic when thinking (mic_wrapper.reset()).

**Comment by PattenKuo** [comment]
@wjennings Oh, I missed the detailed you had mentioned above. 
I'll have a try, Thanks a lot.

**Comment by PattenKuo** [comment]
@wjennings Hi, I have tried the method you mentioned! But ItAlexa crashed.
I'll appreciate it if you could help me.
Tnanks.


`Mar 19 22:07:18 salvator-x SampleApp[4969]: ###########################
Mar 19 22:07:18 salvator-x SampleApp[4969]: #       Thinking...       #
Mar 19 22:07:18 salvator-x SampleApp[4969]: ###########################
Mar 19 22:07:18 salvator-x SampleApp[4969]: [2019-03-19 22:07:18] [frame_header] Dispatching write containing 1 message(s) containing 2 header bytes and 46 payload bytes
Mar 19 22:07:18 salvator-x SampleApp[4969]: [2019-03-19 22:07:18] [frame_header] Header Bytes:
Mar 19 22:07:18 salvator-x SampleApp[4969]: [0] (2) 81 2E
Mar 19 22:07:18 salvator-x SampleApp[4969]: [2019-03-19 22:07:18] [frame_payload] Payload Bytes:
Mar 19 22:07:18 salvator-x SampleApp[4969]: [0] (46) [1] {"type":"dialogState","content":"Thinking..."}
Mar 19 22:07:18 salvator-x audit[4969]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=System pid=4969 comm="pcm-io" exe="/usr/bin/avs-device-sdk/SampleApp" sig=11 res=1
Mar 19 22:07:18 salvator-x kernel: audit: type=1701 audit(1553033238.944:32): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=System pid=4969 comm="pcm-io" exe="/usr/bin/avs-device-sdk/SampleApp" sig=11 res=1
Mar 19 22:07:18 salvator-x kernel[3164]: [ 6271.473162] audit: type=1701 audit(1553033238.944:32): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=System pid=4969 comm="pcm-io" exe="/usr/bin/avs-device-sdk/SampleApp" sig=11 res=1
`

**Comment by caleighatamazon** [comment]
This issue was fixed in 1.16. Toggling the microphone off will unblock the mic for other Android apps.

Closing this issue -- please feel free to re-open if you have further questions!
