### ISSUE TITLE
Is there any C++ Smart Home Skill sample？

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#965]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Is there any C++ Smart Home Skill sample， I don't kown how to start, what I have to do ?
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bennyAv10** [comment]
Hi @DonghuaZheng,

Your skill back-end can be written in any language. When creating a skill you can specify the URL your back-end listens.

Let me know it this answers your question.

Thanks,
Benny

**Comment by DonghuaZheng** [comment]
@bennyAv10 Thanks
