### ISSUE TITLE
Question about MSP

### ISSUE THREAD

**Issue by elfdie00475** [alexa/avs-device-sdk#969]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I see the issue [#796](https://github.com/alexa/avs-device-sdk/issues/796) and I just ask some questions about MSP:
1. We let our device into the white list of Amazon Music, and we also can play Amazon Music. We also want to play Spotify music in our device. What we need to do?
2. In music self-test file, these are two sections about Amazon Music, one is "Amazon Music Library" and the other is "Prime Music". What is the different between two sections?

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [*****] Other - tell us more:

### Tell us about your OS (Type & version):
- [*****] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
Hello elfdie00475,

1) Yes.
2) Still looking in to this.

Best regards,
-SWH

**Comment by elfdie00475** [comment]
Hi @scotthea-amazon ,

We will discuss about Spotify music with AVS Business Development, thanks for your help.
And, I already know the difference between "Amazon music library" and "Amazon prime music".
So, I will close this issue.

Thanks for you help again.
