### ISSUE TITLE
Memory Consumption information

### ISSUE THREAD

**Issue by julianobRibeiro** [alexa/avs-device-sdk#97]
Hi,

Has Amazon or any of developer partners reported/noticed any memory leak while running AVS SDK for  long hours?
Is there any validation process from Amazon related to that for current AVS solution 1.0.1?

Thank you,
Juliano Ribeiro

**Comment by teresakang** [comment]
Hi,

We are doing 1.0.2 still noticed memory leak during long hours (48 hours), is there any feedback from Amazon? 

Thank you.

**Comment by kencecka** [comment]
Hi @julianobRibeiro,

We are not aware of any memory leaks, but have not done extensive testing for them yet.  I have filed an internal ticket to test for memory leaks, and we will address any findings in a future release.  We are also in the process of profiling typical resource usage/requirements for the SDK, and will update the SDK documentation with this data as soon as it is available.

Ken

**Comment by kclchan** [comment]
Hi @julianobRibeiro,

We have perform memory analysis and have not detected a memory leak in v1.1.

Thanks,
Kenneth
