### ISSUE TITLE
Pandora service is not working

### ISSUE THREAD

**Issue by zeusshuang** [alexa/avs-device-sdk#970]
Hi AVS team,

AVS SDK 1.8.1 / 1.9 , ARM based embedded linux system.

Since this week, the Pandora service seems be blocked while playing Pandora from AVS SDK.
Alexa, play Pandora.
It will respond try try to play last station but finally it will said , sorry something went wrong.

We tried Pandora last week and it's working well. And we also tried it with Amazon development kit and the result is the same, so it may be server site issue ? 

[pandora.log](https://github.com/alexa/avs-device-sdk/files/2395400/pandora.log)

**Comment by scotthea-amazon** [comment]
Hi zeusshuang,

Thank you for bringing this to our attention!   There is nothing obvious in the logs you posted, so we are looking in to the corresponding service logs.

Best regards,
-SWH

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

It is working now since 3 hours ago.  So it seems stop service for couple days.
Is it server site issue ?
May I say AVS and Echo is on different cloud server ?

**Comment by scotthea-amazon** [comment]
Hi zeusshuang,

Yes, this does appear to have been a service issue.  Just what went wrong is not yet clear.

AVS and Echo use different endpoints, but they are backed by the same services running across many servers.

Thank you,
-SWH

**Comment by scotthea-amazon** [comment]
Hi zeusshuang,

This was tracked down in Alexa service logs to a transient unexpected failure reported by the Pandora service.  That error appears to have been limited to a single user and to have cleared itself.

Best regards,
-SWH

**Comment by zeusshuang** [comment]
Hi @scotthea-amazon ,

thanks for the update, and the Pandora service was working after couple days.

**Comment by celinval** [comment]
Thanks @zeusshuang for reporting this issue. I'm going to close this for now. Please feel free to reopen it if  the same problem occurs again.
