### ISSUE TITLE
Can't change locale to another language via voice

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#971]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

My Alexa device's default locale is en-US, I want change language to japanese via voice , so made voice request "Alexa, change the language to japanese in this device", Alexa reponsed, "device doesn'st support that". So I want to kown how to change locale to another language via voice.
## What is the expected behavior?

Alexa should change language to Japanse so I can talk to alexa via Japanese.
## What behavior are you observing?

Alexa told me that my device does't support that while I can change locale through console.
### What version of the AVS Device SDK are you using?
      <x.y.z>
1.9.0
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more: Embedded system

### Tell us about your OS (Type & version):
- [* ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by scotthea-amazon** [comment]
@DonghuaZheng,

Sorry, but there is no option to set the language via voice.  You need to set it via the 'locale' value in the configuration (AlexaClientSDKConfig.json).  You *can* set the language for Amazon devices in the Alexa app, but that has not yet been wired up for SDK devices.

Best regards,
-SWH

**Comment by DonghuaZheng** [comment]
@scotthea-amazon thanks
