### ISSUE TITLE
startsample.bat error when executing

### ISSUE THREAD

**Issue by j0k3r87** [alexa/avs-device-sdk#975]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I installed the AVS device SDK for Windows according to your instructions. Everything went fine until I tried to execute the sampleapp.bat. Then I get the error:
SampleApp.exe D:/Profiles/Default/Desktop/msys64/home/myname/build/Integration/AlexaClientSDKConfig.json DEBUG9
The command "SampleApp.exe" is either written wrong or could not been found (translated from German)

## Tell us about your environment:
Windows 10 64bit

### What version of the AVS Device SDK are you using?
newest AVS device SDK from github

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Win 10

**Comment by scotthea-amazon** [comment]
Hello j0k3r87,

Can you look in your folder <msys64_installed_path>/alexa_sdk/build/bin and see if SampleApp.exe exists?

If it does not exist, could you capture the output of a re-run of make and post it to this thread (as an attachment would be preferred) ?

Thank you,
-SWH
