### ISSUE TITLE
Failed To create Sample Application on ARM Platform

### ISSUE THREAD

**Issue by avp24** [alexa/avs-device-sdk#978]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I have cross compiled avs sdk with wake word detector & portaudio enabled option, gstreamer & gstreamer-plugins for ARM platform using aarch64-linux-gnu- toolchain. After successful build procedure of above mentioned modules corresponding libraries were generated. (Verified that all binaries & libraries are ARM supported)
I copied SampleApp, AlexaClientSDKConfig.json & all the libraries on my board. Configured the json file and execute below command :
./SampleApp ../Integration/AlexaClientSDKConfig.json DEBUG=9

Below error is observed:
1970-01-02 04:49:09.737 [  1] I sdkVersion: 1.9.0
configFile ../Integration/AlexaClientSDKConfig.json

(SampleApp:9668): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(SampleApp:9668): GLib-CRITICAL **: g_main_context_find_source_by_id: assertion 'source_id > 0' failed
1970-01-02 04:49:09.746 [  1] C SampleApplication:Failed to create media player for speech!
1970-01-02 04:49:09.746 [  1] C SampleApplication:Failed to initialize SampleApplication
Failed to create to SampleApplication!

## What behavior are you observing?

Sample application is not executing.
### What version of the AVS Device SDK are you using?
      <x.y.z>
sdkVersion: 1.9.0 gstreamer & its plugins were cross-compiled manually using toolchain.
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ * ] Other - tell us more:
Qualcomm APQ8053

### Tell us about your OS (Type & version):
- [ * ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

Please guide me to solve this issue. My initial target is to communicate with Amazon Cloud using Sample App & final target is to run alexa voice service. If anybody has already performed the above tasks for ARM platform, kindly share your knowledge.
Thanks!

**Comment by dhpp** [comment]
Hi @avp24, I believe this has been done by others on this forum.  Could you please take a look at #432, #356, #379, for example.

The error trace you have indicates that the glib / gstreamer libraries may not be correctly installed.  Please see [here](https://github.com/alexa/avs-device-sdk/wiki/Dependencies) under the GStreamer details.

Let us know if the above is helpful, thanks.

**Comment by avp24** [comment]
Hi @dhpp, I have gone through #432, #356, #379 but it was not helpful to me.
I have build the avs sdk using the list of dependencies mentioned.
Can you please share me the initial steps which you followed after avs sdk is cross compiled for ARM. Maybe this can give some idea.
Thanks for reply!

**Comment by avp24** [comment]
Hi,
I am using glib 2.58.0 & gstreamer 1.14.2.
To build gstreamer for ARM below options are used:
./configure --prefix=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer-1.14.2 --host=aarch64-linux-gnu --build=x86_64-pc-linux-gnu --disable-gtk-doc PKG_CONFIG_PATH="$HOME/Desktop/VVDN_AVS/alexa/local_build_arm/glib/lib/pkgconfig" && make && make install
To build gst-plugins-base for ARM:
./configure --prefix=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gst-plugins-base CXX=aarch64-linux-gnu-g++-5 --host=aarch64-linux-gnu --build=x86_64-pc-linux-gnu --disable-x --disable-xvideo --disable-x11 --disable-gl --disable-libvisual --disable-opus --disable-xshm --disable-gnome_vfs --disable-ogg --disable-pango --disable-theora --disable-vorbis --disable-audiotestsrc -disable-gtk-doc --disable-examples PKG_CONFIG_PATH="$HOME/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer/lib/pkgconfig" && make && make install
To build gst-plugins-good :
./configure --prefix=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gst-plugins-good --host=aarch64-linux-gnu --build=x86_64-pc-linux-gnu -disable-gtk-doc --disable-examples --disable-videobox --disable-videocrop --disable-videofilter --disable-videomixer --disable-x --disable-cairo --disable-aalib --disable-aalibtest --disable-flac --disable-jack --disable-libcaca --disable-libpng --disable-libdv --disable-pulse --disable-dv1394 --disable-gdk_pixbuf --disable-qt --disable-shout2 --disable-soup --disable-speex --disable-vpx --disable-wavpack PKG_CONFIG_PATH="$HOME/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer/lib/pkgconfig"  && make && make install
To build gst-plugins-bad:
./configure --prefix=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gst-plugins-bad --host=aarch64-linux-gnu --build=x86_64-pc-linux-gnu --disable-audiovisualizers --disable-bayer --disable-dvbsuboverlay --disable-dvdspu --disable-faceoverlay --disable-festival --disable-fieldanalysis --disable-freeverb --disable-frei0r --disable-gaudieffects --disable-geometrictransform --disable-hls --disable-inter --disable-ivfparse --disable-mxf --disable-pcapparse --disable-pnm --disable-segmentclip --disable-siren --disable-smooth --disable-speed --disable-subenc --disable-vmnc --disable-y4m --disable-directsound --disable-wasapi --disable-direct3d --disable-android_media --disable-apple_media --disable-shm --disable-vcd --disable-opensles --disable-assrender --disable-voamrwbenc --disable-voaacenc --disable-chromaprint --disable-dc1394 --disable-decklink --disable-wayland --disable-dts --disable-resindvd --disable-faac --disable-faad --disable-flite --disable-gsm --disable-ladspa --disable-lv2 --disable-libmms --disable-modplug --disable-mplex --disable-musepack --disable-neon --disable-ofa --disable-openal --disable-opencv --disable-opus --disable-rsvg --disable-teletextdec --disable-wildmidi --disable-sndfile --disable-soundtouch --disable-spc --disable-gme --disable-dvb --disable-acm --disable-vdpau --disable-zbar --disable-spandsp --disable-jp2kdecimator --disable-mpegdemux --disable-mpegpsmux --disable-mpegtsdemux --disable-mpegtsmux --disable-netsim --disable-jpegformat --disable-proxy --disable-rawparse --disable-videofilters --disable-videoparsers --disable-videosignal --disable-direct3d --disable-winscreencap --disable-midi --disable-videoframe_audiolevel --disable-sdp --disable-timecode --disable-yadif --disable-stereo --disable-librfb --disable-kms --disable-ttml --disable-examples --disable-gl --disable-gtk-doc --with-pkg-config-path="$HOME/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer/lib/pkgconfig" && make && make install

After this I building AVS SDK using below options:
cmake /home/ap/Desktop/VVDN_AVS/alexa/avs-device-sdk -DCURL_LIBRARY=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/curl/lib/libcurl.so -DCURL_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/curl/include -DCMAKE_TOOLCHAIN_FILE=/home/ap/Desktop/VVDN_AVS/alexa/toolchain_generic.cmake -DSENSORY_KEY_WORD_DETECTOR=OFF -DKITTAI_KEY_WORD_DETECTOR=ON -DKITTAI_KEY_WORD_DETECTOR_LIB_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/wake_word_kitty/snowboy/lib/aarch64-ubuntu1604/libsnowboy-detect.a -DKITTAI_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/wake_word_kitty/snowboy/include -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_PREFIX_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/gstreamer -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/portaudio/lib/libportaudio.a -DPORTAUDIO_INCLUDE_DIR=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/portaudio/include -DCMAKE_PREFIX_PATH=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/alexa_build -DCMAKE_INSTALL_PREFIX=/home/ap/Desktop/VVDN_AVS/alexa/local_build_arm/alexa_build -DCMAKE_BUILD_TYPE=DEBUG -Wno-dev && make & make install

It shows: [100%] Built target SampleApp.
Then I copy SampleApp & all the static & shared libraries on my board.

Still I get the above mentioned error when SampleApp is executed on board. Am I missing here something? Please guide.
Thanks!

**Comment by avp24** [comment]
Error posted here is solved.

**Comment by cwyse** [comment]
What was the solution?  We have the exact same issue on OSX.

**Comment by avp24** [comment]
After loading all the gstreamer plugins in non-standard directory path for gstreamer plugins was passed. This solved the error.
