### ISSUE TITLE
Encountered such a compiler error when building  the v1.0.1 of the C++ SDK

### ISSUE THREAD

**Issue by yakov2006** [alexa/avs-device-sdk#98]
I am building the 1.0.1 the c++ SDK, Encountered such a compiler error:
yangzq@sita1:~/samba/sita/trunk/tplayer/core/alexa/out_mt5658m$ make
[ 26%] Built target AVSCommon
[ 27%] Built target gtest
[ 29%] Built target gmock_main
[ 30%] Built target gtest_main
[ 30%] Built target AttachmentCommonTestLib
Linking CXX executable AlexaClientSDKInitTest
../../libAVSCommon.so: undefined reference to `_ZTHN14alexaClientSDK9avsCommon5utils6logger13ThreadMoniker15m_threadMonikerE'
collect2: error: ld returned 1 exit status
make[2]: *** [AVSCommon/AVS/test/AlexaClientSDKInitTest] Error 1
make[1]: *** [AVSCommon/AVS/test/CMakeFiles/AlexaClientSDKInitTest.dir/all] Error 2
make: *** [all] Error 2

**Comment by kencecka** [comment]
Hi @yakov2006,

What compiler version are you using?  This sounds like a known issue we've seen before with older versions of GCC.  See this issue for a more detailed discussion of the issue and a possible workaround:
https://github.com/alexa/avs-device-sdk/issues/56

Please re-open this issue if you have further questions.

Ken
