### ISSUE TITLE
ALexa on Respeaker Core V2.0 Runs with Android 

### ISSUE THREAD

**Issue by kameshkancherla** [alexa/avs-device-sdk#986]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am not able to configure Alexa SDK on Android

## What is the expected behavior?
Alexa on android

## What behavior are you observing?
not able to install. I am new to this complete platform
## Provide the steps to reproduce the issue, if applicable:
I install android on Respeaker core v2.0
I am trying to install AVS SDK on android using ADB, but I am not able to.

### What version of the AVS Device SDK are you using?
      I am trying to install AVS Device SDK latest from https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ *] Other - tell us more:
Respeaker core v2.0

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [* ] Other - tell us more: Android 8.1

**Comment by kameshkancherla** [comment]
If possible provide me the correct procedure to setup AVS on respeaker core v2.0 which is running with Android.

**Comment by kameshkancherla** [comment]
Hi,
Yes I have root access, using ADB I am not able to install AVS SDK.
https://github.com/alexa/avs-device-sdk/wiki/Android-Quick-Start-Guide
As per this article, I installed all packages on my windows10 laptop. When I am trying execute using ADB 
shell bash setup.sh config.txt , it saying bash not exist.

Regards
Vithal

**Comment by kameshkancherla** [comment]
Friends, I installed Linux and followed the same procedure but I am still not able to install AVS SDK on android.

vithal@ubuntu:~$ adb connect 192.168.xxx.xxx
connected to 192.168.xxx.xxx:5555
vithal@ubuntu:~$ adb devices
List of devices attached
F5B1Exxxx	device
192.168.xxx.xxx:5555	device

After I ran shell bash setup.sh config.txt as per procedure, I am getting this error
vithal@ubuntu:~$ shell install setup.sh config.txt 
No command 'shell' found, did you mean:
 Command 'bshell' from package 'avahi-ui-utils' (universe)
 Command 'lshell' from package 'lshell' (universe)
 Command 'pshell' from package 'python-pyramid' (universe)
 Command 'jshell' from package 'openjdk-9-jdk-headless' (universe)
 Command 'spell' from package 'spell' (universe)
 Command 'shelr' from package 'shelr' (universe)
shell: command not found

vithal@ubuntu:~$ adb shell install setup.sh config.txt 
error: more than one device/emulator
vithal@ubuntu:~$ adb disconnect 192.168.178.213

vithal@ubuntu:~$ adb shell install setup.sh config.txt 
/system/bin/sh: install: not found
vithal@ubuntu:~$

**Comment by kameshkancherla** [comment]
vithal@ubuntu: adb shell install setup.sh config.txt
error: more than one device/emulator
vithal@ubuntu: adb disconnect 192.168.xxx.xx.

vithal@ubuntu: adb shell install setup.sh config.txt
/system/bin/sh: install: not found

**Comment by kameshkancherla** [comment]
I tried the procedure, finally I conclude this article will not help to install AVS SDK on android.

If any one tested this procedure and successful kindly let me know
Regards
Vithal

**Comment by kameshkancherla** [comment]
Friends, 

Do I need to install all these packages before I install AVS SDK on android.

libcurl 7.50.2 or later
nghttp2 1.0 or later
OpenSSL 1.0.2 or later
Doxygen 1.8.13 or later (required to build API documentation)
SQLite 3.19.3 or later (required for Alerts)

**Comment by visayamv** [comment]
@kameshkancherla , as discussed here https://github.com/alexa/avs-device-sdk/issues/901, you need to execute the commands on your Linux terminal which will cross-compile the SDK code and automatically copy the compiled libraries and executable to your android device.

All the dependencies will be installed by the script automatically so you don't have to worry about it.

I'll be closing this issue. Please reopen if you still can't figure out how to run the script to build the Android SampleApp.

**Comment by kameshkancherla** [comment]
Hi,

Thank you for information. I tried as advised below but I got this error.

make[1]: *** [crypto/aes/aes_cbc.o] Error 127
make[1]: Leaving directory '/home/vithal/release/android-27/armeabi-v7a/openssl'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

________________________________
