### ISSUE TITLE
Can I add self-defined directive in Alexa Skill Kits and add new capability agent in CapabilityAgents folder to handle selfdefined directive?

### ISSUE THREAD

**Issue by DonghuaZheng** [alexa/avs-device-sdk#987]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I want to add a new capability to control the device which intergrated with Alexa Voice Service SDK, so I want add new capability agent in CapabilityAgents to do it.
Howerver, I can not find any documents about how to add capability agent in AVS SDK and add selfdefined directive in Alexa Skill Kits. I want Can I do that and how to do that.
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @DonghuaZheng, this is not currently supported - the AVS Interfaces are quite carefully managed, and we don't have a process at this time for third parties to define a new Event or Directive.

I would suggest you post your suggestion on the more general Alexa Developer Forum for feedback [here](https://forums.developer.amazon.com/spaces/165/index.html).  Thanks.
