### ISSUE TITLE
Which ONE play the response from AVS if there are multiple AVS Client devices in the same room?

### ISSUE THREAD

**Issue by DiazSo** [alexa/avs-device-sdk#989]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

if there are multiple AVS Client devices in the same room, the user he/she use voice command to trigger interaction, then which one AVS client will play the response from AVS server?
## What is the expected behavior?

There is only one device play the response from AVS server.
## What behavior are you observing?

It seems all of the AVS client device play the response from AVS server if it receive the answer.
## Provide the steps to reproduce the issue, if applicable:

Setup multiple AVS client devices in one room, Start "SampleApp" on all devices then using voice command like "alexa, what time is it?", then all of AVS client will be wake-up and play response
### What version of the AVS Device SDK are you using?
      <x.y.z>
<1.9.0>
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: my embedded platform

### Tell us about your OS (Type & version):
- [X] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by dhpp** [comment]
Hi @DiazSo, I believe this is already something AVS takes care of.  It does require all devices to be under the same user account.  Is that the case here?  If the users are running registered to different users, yes they will all try to reply to the "Alexa" query, at least as things stand today.  Please let us know, thanks.

**Comment by zeusshuang** [comment]
Hi @dhpp ,

Followed by this question. To compared with Echo, it seems under AVS, it will need to wait until timeout in thinking state, but Echo, it will stop immediately (I checked with the LED status).
Is it a expected behavior ?  Is there any mechanism and received "cancel" from server side under this ESP state ?

**Comment by DiazSo** [comment]
> Hi @DiazSo, I believe this is already something AVS takes care of. It does require all devices to be under the same user account. Is that the case here? If the users are running registered to different users, yes they will all try to reply to the "Alexa" query, at least as things stand today. Please let us know, thanks.

Hi @dhpp . I have tested this condition. You are right. If all devices are under the same user account, then AVS takes care this condition. Only one device will play the response from AVS. If the devices are under different account then  all devices will play the response from AVS. In advance, could you provide the information about: 
when all device are under the same account, then how AVS know which device should play the response from AVS? I see the behavior :
all devices will enter the state  Listening...-->Thinking...--> then there is only one device will enter Speaking..., and finally, all device will enter "Alexa is currently idle!".

Thanks!

**Comment by visayamv** [comment]
Hi @DiazSo , according to this: https://www.amazon.com/gp/help/customer/display.html?nodeId=202013740 , the one you're closest to will respond. It's determined by the voice energy (ESP) determined from the audio.

I'll be closing this issue. But feel free to reopen if you have more questions regarding this
