### ISSUE TITLE
Feature Request: Support static libs

### ISSUE THREAD

**Issue by the-nic** [alexa/avs-device-sdk#99]
For my project I am integrating the source as a subdirectory in my project and simply add it via `add_subdirectory()` in my top `CMakeLists.txt`.
Therefore, I really dont need to ship the dynamic libraries but would prefer to link them statically and just have to ship a single binary.
Therefore my question: Would it be possible to remove the `SHARED` flag in the `add_library()` calls and make it globally configurable, whether one wants to build shared or static libraries? Whether shared or static libs are built could be configured then via the CMake variable `BUILD_SHARED_LIBS`.

**Comment by kencecka** [comment]
Hi Nicolas,

Thank you for this suggestion.  We will look into adding it for a future release of the SDK.  As it currently stands, there shouldn't be any problem with making the changes you suggest in your local copy of the SDK.  We have not been actively testing with static libraries, but I do not anticipate any problems using them.

Ken
