### ISSUE TITLE
How to build using visual studio?

### ISSUE THREAD

**Issue by gunnicus** [alexa/avs-device-sdk#991]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

How can I build using visual studio on Windows? I'm trying to open the CMakeLists.txt using visual studio but I got an error 

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY) (found suitable version
  "7.61.1", minimum required is "7.43.0")		C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake	137	

I do have curl curl-7.61.1-win64-mingw, I added curl-7.61.1-win64-mingw\bin folder to environment path variable but still have same error.
## What is the expected behavior?

Build using visual studio
## What behavior are you observing?

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY) (found suitable version
  "7.61.1", minimum required is "7.43.0")		C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake	137	
## Provide the steps to reproduce the issue, if applicable:

Open visual studio, open cmake, select CMakeLists.txt under root
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows10

**Comment by mavamazon** [comment]
Hi!
The project is originally intended to be built using the instructions provided here:
https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script
Can you confirm that you can build and run SDK following that instructions?
I am afraid that we cannot guarantee full support for windows IDEs including Visual Studio.

**Comment by gunnicus** [comment]
Thanks for your reply, please see #992, I'm following the guide, in Optional configurations, To build the SDK after making custom changes: Open the MinGW64 shell, and run make inside of the the alexa_sdk/build folder. This doesn't work. After I type make command inside alexa_sdk/build  folder, it shows me **make: *** No targets specified and no makefile found. Stop.** and nothing got built.

**Comment by celinval** [comment]
Hi @gunnicus, I posted a comment on #992. Let's try to fix that first, since that is the only build we support. 

Thanks
