### ISSUE TITLE
can't build on windows

### ISSUE THREAD

**Issue by gunnicus** [alexa/avs-device-sdk#992]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I'm trying to follow "Windows Quick Start Guide with Script" to build, in the guide it says: 
To build the SDK after making custom changes: Open the MinGW64 shell, and run make inside of the the alexa_sdk/build folder.

So I cd to the build folder, and typed make, here it shows me an error "No targets specified and no makefile found.  Stop"
water@DESKTOP-2BQ44E3 MINGW64 /C/msys64/home/water/avs-device-sdk/build
# make
make: *** No targets specified and no makefile found.  Stop.

## What is the expected behavior?

Project can be built

## What behavior are you observing?

water@DESKTOP-2BQ44E3 MINGW64 /C/msys64/home/water/avs-device-sdk/build
# make
make: *** No targets specified and no makefile found.  Stop.

## Provide the steps to reproduce the issue, if applicable:

open MinGW64 shell, cd to avs-device-sdk/build folder, type make and press enter

### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [x ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows 10

**Comment by mavamazon** [comment]
Hi! Were you able to build the application before you made the changes? In general this message may mean that CMake has not done its job in the folder.
I am going to perform some research on my side.

**Comment by celinval** [comment]
Hi @gunnicus,

Can you please run the setup script and post the logs here? Before you post the full logs, please make sure to remove the clientId and productId from your logs.

Thanks,

**Comment by gunnicus** [comment]
Thanks for your reply, the setup script is working. What I mean is in Windows-Quick-Start-Guide-with-Script wiki, "To build the SDK after making custom changes: Open the MinGW64 shell, and run make inside of the the alexa_sdk/build folder." This doesn't seems working. What I'm doing now is every time after I made a change, I just run "bash setup.sh config.txt" inside "C:/msys64/home/<user_name>" folder and it works. Not too sure how can I run make inside build folder.

**Comment by celinval** [comment]
Interesting, so doing the following doesn't work? What error are you getting?

```
cd <sdk-folder>/build
make SampleApp
```

**Comment by gunnicus** [comment]
Thanks, "make SampleApp" worked, I did type "SampleApp" previously, only "make" didn't work. Sorry I'm new to all these make commands. 
I think in the Windows-Quick-Start-Guide-with-Script wiki, maybe change this paragraph to  "To build the SDK after making custom changes: Open the MinGW64 shell, and run "make SampleApp" inside of the the alexa_sdk/build folder." may help a newbie like me.
Thanks again.

**Comment by celinval** [comment]
That's a great suggestion! I'm sorry if it wasn't very clear before.

Thanks
