### ISSUE TITLE
how to save response audio to a file?

### ISSUE THREAD

**Issue by gunnicus** [alexa/avs-device-sdk#993]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I'm trying to save response audio to a file, I added these code to SpeechSynthesizer, inside executePreHandleAfterValidation funtion. The file is saved no problem, However, when I open the result.mp3 file in a player, the voice is shattered, as twice as fast compare to normal speak. Can't really hear it properly, it only last 4 seconds, it is very different to what Alexa spoke, I wonder if this is a format/decode issue? If I want to save exactly what Alexa said audio to a file, where is the best place to do that?

I shared result.mp3 on google drive [https://drive.google.com/file/d/1wsnOl8ChO1RZJahscPrWnzJCK5cWAg0l/view?usp=sharing](url)

This is the code I add at SpeechSynthesizer after line 456 
std::ofstream out("result.mp3");
		if (out.is_open()) {
		char buf[1024];
		avsCommon::avs::attachment::AttachmentReader::ReadStatus status;
		while (true) {
        auto len = speakInfo->attachmentReader->read(buf, sizeof(buf), &status);
				if (status == avsCommon::avs::attachment::AttachmentReader::ReadStatus::OK) {
					out.write(buf, len);
					 ACSDK_DEBUG9(LX("executePreHandleAfterValidation")
                           .d("ReadStatus", "OK"));
				} else if (status == avsCommon::avs::attachment::AttachmentReader::ReadStatus::CLOSED) {
					 ACSDK_DEBUG9(LX("executePreHandleAfterValidation")
                           .d("ReadStatus", "CLOSED"));
					break;
				}
			}
			speakInfo->attachmentReader->close();
			 ACSDK_DEBUG9(LX("executePreHandleAfterValidation")
                           .d("output .mp3 file", "finished"));
		}
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows 10

**Comment by mavamazon** [comment]
Hi!
I would suggest you to play around GStreamer's plugin "filesink" that can be used in MediaPlayer. 
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-plugins/html/gstreamer-plugins-filesink.html
MediaPlayer code:
MediaPlayer/GStreamerMediaPlayer/src/MediaPlayer.cpp

If you want to save speech only you can make sure that your modified MediaPlayer is used there:
https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/SampleApplication.cpp#L366

**Comment by gunnicus** [comment]
thanks for your reply, I found something here https://github.com/alexa/avs-device-sdk/issues/14 , but I tried the code it doesn't seems working, is there anything similar I can do instead of use filesink?

**Comment by gunnicus** [comment]
@mavamazon thanks for your reply, a quick question is there a way to clone a AttachmentReader?

**Comment by celinval** [comment]
Hi @gunnicus,

There is no way to clone the AttachmentReader. You can have multiple readers, which should be enough for you to read the stream and redirect it to a file.

**Comment by gunnicus** [comment]
Hi, thanks for your reply. Can you please give me a hint or a sample how can I add another reader, which class should I look at. Great thanks.
