### ISSUE TITLE
sample.app not working

### ISSUE THREAD

**Issue by elledgeg** [alexa/avs-device-sdk#994]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have just run the Raspberry Pi Quick Start Guide with Script. 

The installation went well until I reached the point where I was ready to run sample.app (sudo bash startsample.sh). 

I received the message telling me to authorise and  I entered the code into the web site and received the message  "Success! Your registration is now complete." 

The system then reported " UNRECOVERABLE AUTHORIZATION ERROR: INVALID_CBL_CLIENT_ID Entering limited interaction mode" and hung waiting for further instructions.

I also decided to do another installation into another directory using the "step-by-step" instructions.
Again the installation went well until I got to sample.app.

I ran "./SampleApp/src/SampleApp ./Integration/AlexaClientSDKConfig.json" which responded with the message:
"SDKConfig.json
2018-09-30 12:38:56.867 [  1] I sdkVersion: 1.9.0
USAGE: ./SampleApp/src/SampleApp <path_to_AlexaClientSDKConfig.json> <path_to_inputs_folder> [log_level]"

## What is the expected behavior?
The app should run to completion
## What behavior are you observing?
The app failed. Please see details in the issue summary above.
## Provide the steps to reproduce the issue, if applicable:
n/a
### What version of the AVS Device SDK are you using?
   1.9

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by gunnicus** [comment]
Are you using the client id generated from "Other devices and platforms tab" at Security Profile?

**Comment by elledgeg** [comment]
Sorry, I wasn’t. I will go ahead and generate the id and get back to you if the problem persists.
Thanks for your help.
George.

**Comment by mavamazon** [comment]
Hi! Please let us know if it worked!

**Comment by elledgeg** [comment]
Success. Thank you for your help.
Regards,George

**Comment by mavamazon** [comment]
I am closing the issue then. Feel free to reopen it if required.
Kudos to @gunnicus for helping with this issue!

**Comment by suhail-jr** [comment]
Hello, Iam using the latest AVS-Device-SDK I followed the official documentation and everything went successfully. But once i start the sample application the device got authorized but the client is not connected. I double check everything, i used the exact Client.config file . But i still facing the issue. Please if somebody knows how to fix it, please help me
