### ISSUE TITLE
Stuck on Authorizing

### ISSUE THREAD

**Issue by WINGNUTDBQ** [alexa/avs-device-sdk#995]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## What is the expected behavior?
Trying to run Alexa on my Win 10 PC.

## What behavior are you observing?
The BAT file runs with ONE error....
****(SampleApp.exe:13808): GStreamer-WARNING **: 18:31:33.985: Failed to load plugin 'C:\msys64\mingw64\lib\gstreamer-1.0\libgstshout2.dll': 'C:\msys64\mingw64\lib\gstreamer-1.0\libgstshout2.dll': %1 is not a valid Win32 application.****

It then provides an authorization code, I go to https:/amazon.com/us/code, apply the code, and amazon tells me it is verified.  When I go back to the startsamle.bat, it just sits waiting for a return verification.

## Provide the steps to reproduce the issue, if applicable:
I followed all of the steps at this url  https://github.com/alexa/avs-device-sdk/wiki/Windows-Quick-Start-Guide-with-Script
And started from scratch twice with the same results

## Tell us about your environment:
Windows 10, 16GB of RAM, nVidia, SSD, nothing particularly unusual as far as software.
I used the 64-bit version of msys64 and followed the guide to the letter.  It appears from he error message that sampleapp.exe is expecting a 32-bit version of libgstshout2.dll.  The file is in the specified location.

### Tell us what hardware you're using:
- [X] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by gunnicus** [comment]
Is that your client id correct? It needs to be generated from  "Other devices and platforms tab", also if you change client id, you need to run the startsample.bat and press 'k' to reset.

**Comment by WINGNUTDBQ** [comment]
It was not correct originally, but is now.  I did not know about the 'k' key reset, I will try that.

>           Is that your client id correct? It needs to be generated from  "Other devices and platforms tab", also if you change client id, you need to run the startsample.bat and press 'k' to reset.

**Comment by celinval** [comment]
Hi @WINGNUTDBQ, did you manage to try @gunnicus suggestion?

Thanks
