### ISSUE TITLE
How to increase the volume of med_ui_wakesound.wav?

### ISSUE THREAD

**Issue by bogartescobar** [alexa/avs-device-sdk#997]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
med_ui_wakesound.wav volume too low for me.

## What behavior are you observing?
med_ui_wakesound.wav volume too low for me but Alexa responses are very audible.

### What version of the AVS Device SDK are you using?
    latest

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ **X**] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [**X** ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by wjennings** [comment]
You could simply use an audio editing program to modify the file's volume there.  For example, Audacity would work:
https://www.audacityteam.org/

**Comment by mavamazon** [comment]
In addition to @wjennings comment - could you please make sure that you are playing this file with a proper volume as well?

**Comment by bogartescobar** [comment]
@wjennings my Raspberry pi is on full volume

**Comment by wjennings** [comment]
@bogartescobar no I mean, you actually modify the med_ui_wakesound.wav file to increase it's amplitude, so it will be louder when it plays.  That means using a program to open that file and adjusting the amplitude so it's louder.  It has nothing to do with the volume level of the machine or speakers playing the sound.
