### ISSUE TITLE
How to build with a wake word detector on Windows?

### ISSUE THREAD

**Issue by gunnicus** [alexa/avs-device-sdk#998]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I followed the "Windows Quick Start Guide with Script", the SampleApp is running successfully, but when I say the word "Alexa" I got no response, I have to enter 't' every time I say a command. 

In KeywordDetector.cmake file I changed 
option(AMAZON_KEY_WORD_DETECTOR "Enable Amazon keyword detector." OFF) 
to
option(AMAZON_KEY_WORD_DETECTOR "Enable Amazon keyword detector." ON) 

but doesn't look like it made any difference, still no response to "Alexa".

I also tried modifiy setup.sh line 220, I downloaded sensory, I added -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH="$SOURCE_PATH/avs-device-sdk/ThirdParty/alexa-rpi-master/lib/libsnsr.a" -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR="$SOURCE_PATH/avs-device-sdk/ThirdParty/alexa-rpi-master/include"\ after -DCMAKE_BUILD_TYPE=DEBUG but when I build it still shows me  No keyword detector type specified, skipping build of keyword detector.

  mkdir -p $BUILD_PATH
  cd $BUILD_PATH
  cmake "$SOURCE_PATH/avs-device-sdk" \
      -DCMAKE_BUILD_TYPE=DEBUG -DSENSORY_KEY_WORD_DETECTOR=ON -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH="$SOURCE_PATH/avs-device-sdk/ThirdParty/alexa-rpi-master/lib/libsnsr.a" -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR="$SOURCE_PATH/avs-device-sdk/ThirdParty/alexa-rpi-master/include"\
      "${CMAKE_PLATFORM_SPECIFIC[@]}"
	  
		
  cd $BUILD_PATH
  make SampleApp -j2

Log file:
water@DESKTOP-2BQ44E3 MINGW64 /C/msys64/home/water
$ bash setup.sh config.txt
################################################################################
################################################################################

AVS Device SDK Windows mingw64 Script - Terms and Agreements

The AVS Device SDK is dependent on several third-party libraries, environments,
and/or other software packages that are installed using this script from
third-party sources ("External Dependencies"). These are terms and conditions
associated with the External Dependencies
(available at https://github.com/alexa/avs-device-sdk/wiki/Dependencies) that
you need to agree to abide by if you choose to install the External Dependencies.

If you do not agree with every term and condition associated with the External
Dependencies, enter "QUIT" in the command line when prompted by the installer.
Else enter "AGREE".

################################################################################
################################################################################
agree
################################################################################
Proceeding with installation
################################################################################
Creating the build directory for the AlexaClientSDK with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googlemock/CMakeLists.txt:40 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at ThirdParty/googletest-release-1.8.0/googletest/CMakeLists.txt:47 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ACL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ADSL with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the AFML with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the BluetoothImplementations with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the CertifiedSender with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ContextManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the CapabilitiesDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the PlaylistParser with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the CapabilityAgents with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the AIP with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Alerts with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the AudioPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Bluetooth with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ExternalMediaPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the InteractionModel with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the MRM with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the Notifications with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the SpeakerManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the SpeechSynthesizer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Integration with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Please fill C:/msys64/home/water/build/Integration/AlexaClientSDKConfig.json before you execute integration tests.
Skipping build of NetworkIntegrationTests.cpp.
Creating the build directory for the ApplicationUtilities with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the DefaultClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the MediaPlayer with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ESP with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the RegistrationManager with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the Authorization with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the CBLAuthDelegate with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SampleApp with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the Storage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SQLiteStorage with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
FATALDoxygen is required to generate documentation.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys64/home/water/build
[ 36%] Built target AVSCommon
[ 38%] Built target SQLiteStorage
[ 43%] Built target ACL
[ 45%] Built target ADSL
[ 50%] Built target AFML
[ 52%] Built target RegistrationManager
[ 54%] Built target ContextManager
[ 56%] Built target PlaylistParser
[ 56%] Built target AIP
[ 59%] Built target AudioResources
[ 61%] Built target AudioPlayer
[ 63%] Built target Bluetooth
[ 63%] Built target InteractionModel
[ 65%] Built target Notifications
[ 68%] Built target ExternalMediaPlayer
[ 70%] Built target PlaybackController
[ 70%] Built target SpeakerManager
[ 70%] Built target SpeechSynthesizer
[ 72%] Built target TemplateRuntime
[ 77%] Built target AVSSystem
[ 81%] Built target MediaPlayer
[ 84%] Built target ESP
[ 84%] Built target CBLAuthDelegate
[ 84%] Built target CertifiedSender
[ 86%] Built target CapabilitiesDelegate
[ 90%] Built target Alerts
[ 93%] Built target Settings
[ 93%] Built target DefaultClient
[100%] Built target SampleApp

==============> SAVING CONFIGURATION FILE ==============

==============> FINAL CONFIGURATION  ==============

## What is the expected behavior?

SampleApp respond to word "Alexa"
## What behavior are you observing?

SampleApp has no response to word "Alexa"
### What version of the AVS Device SDK are you using?
      <1.9.0>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Windows 10

**Comment by mavamazon** [comment]
Hi!
Sorry, we do not provide reference wakeword configuration for Windows, but you may use instructions for other platforms and adapt them for your needs using the wakeword engine of your choice.

**Comment by gunnicus** [comment]
Thanks for your reply, neither Sensory nor KITT.ai supports windows, what is the AMAZON_KEY_WORD_DETECTOR and AMAZONLITE_KEY_WORD_DETECTOR? Can I use one of those on Windows?

**Comment by LoganArnett** [comment]
@gunnicus have you made any progress on this? I am trying to accomplish the same result on Windows

**Comment by celinval** [comment]
Hi @gunnicus,
To know more about the Amazon Keyword, please contact us privately [here](https://www.amazon.com/forms/231ff404-261e-454c-917d-97208d9ea268).
