### ISSUE TITLE
How to identify DND event in AVS SDK v1.7?

### ISSUE THREAD

**Issue by jackeyu** [alexa/avs-device-sdk#999]
We test DND event in echo dot, we can see purple when enable Don't disturb me.
Then we test it in our device, and use sdk v1.7.  From log message, it is not easy to identify which message can point out "Don't disturb me' or not.

I saw close tickets #675 , #508 , all point out SDK does not support it.
But why echo do can recognize it?  
Could you help to provide some idea?

**Comment by mavamazon** [comment]
Hi! Echo Dot has a proprietary software inside and but are working hard to provide the same capabilities to SDK users as well. DND functionality is not available in our SDK, though.

**Comment by jackeyu** [comment]
Hi @mavamazon 
Why list DND item in certification if AVS SDK cannot identify DND?
Have I misunderstand about test item 247.

From functional self-test , it has certification about DND function.
![Uploading dnd-avscert.png…]()

**Comment by jackeyu** [comment]
I already get response from Amazon FAE , so I close it, thanks

**Comment by ajinkyaw** [comment]
@jackeyu  : hey hi . 
Why list DND item in certification if AVS SDK cannot identify DND?
Have I misunderstand about test item 247.  <<<---- what is the solution for this.
